### ISSUE TITLE
能不能封装到React里？

### ISSUE THREAD

**Issue by ZheFeng** [antvis/g2#1]
这个render的方式是基于DOM的。有没有计划做一个React的封装？

当然没有封装这样也可以在React里用，但总是麻烦一点。并且你们ant.design也是有完整React组建的，不知道是不是考虑呢？

**Comment by jaredleechn** [comment]
@ZheFeng 对应的 rc-g2 很快也会开源

**Comment by ZheFeng** [comment]
太好了。非常感谢
