### ISSUE TITLE
支持js object实例化chart

### ISSUE THREAD

**Issue by leo1024x** [antvis/g2#100]
用json比语法编程会不会更简洁、更友好？每一项都要调api配置太累了，也不易复用

var echarts = require('echarts');

var myChart = echarts.init(document.getElementById('main'));
// 绘制图表
myChart.setOption({
    title: { text: 'ECharts 入门示例' },
    tooltip: {},
    xAxis: {
        data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
    },
    yAxis: {},
    series: [{
        name: '销量',
        type: 'bar',
        data: [5, 20, 36, 10, 10, 20]
    }]
});

**Comment by simaQ** [comment]
这个我们目前正在整，四月中旬发布 2.3.0 会支持

**Comment by leo1024x** [comment]
跳票了 不开心

**Comment by simaQ** [comment]
啥？ 乖宝宝，偶们支持了呢~~~~ https://antv.alipay.com/g2/api/chart-options.html
