### ISSUE TITLE
建议把legend.items.checked的这个属性加入文档

### ISSUE THREAD

**Issue by redclown** [antvis/G2#1000]
通过点击事件实现legend默认选中取消的效果

1. 试了chart.filter,单一的geom是没问题的，但是多geom的时候（比如一个图中有两条现状图，两个柱状图），filter的时候会把带某一个字段的一整列全部删掉，会影响别的geom的展示

2.默认的legend多个geom也会有问题，柱状图线状图在一起的时候只会展示其中一种

3.hide和show，这两个效果差了点，（建议把官网里hide和show换成带动画的），其实legend自带的那种效果比较帅气

最后试了下legend.items.checked这个属性，居然真的能用，文档没有需要找很长时间，需要掉很多头发~~~

**Comment by dxq613** [comment]
应该要开放个 checkable 选项吧

**Comment by AwesomeDevin** [comment]
> 通过点击事件实现legend默认选中取消的效果
> 
> 1. 试了chart.filter,单一的geom是没问题的，但是多geom的时候（比如一个图中有两条现状图，两个柱状图），filter的时候会把带某一个字段的一整列全部删掉，会影响别的geom的展示
> 
> 2.默认的legend多个geom也会有问题，柱状图线状图在一起的时候只会展示其中一种
> 
> 3.hide和show，这两个效果差了点，（建议把官网里hide和show换成带动画的），其实legend自带的那种效果比较帅气
> 
> 最后试了下legend.items.checked这个属性，居然真的能用，文档没有需要找很长时间，需要掉很多头发~~~

你好，想问一下legend.items.checked如何使用，文档没看到相关说明

**Comment by simaQ** [comment]
checked 属性是一个标识位，用来标识该 item 是选中还是为选中。
