### ISSUE TITLE
 Will the G2 heatmap not work after setting opacity, urgent~

### ISSUE THREAD

**Issue by zhuyan0302** [antvis/g2#1005]
chart.heatmap().position('x*y').color('热力值', '#6E32C2-#1890FF-#12CCCC-#80FF73-#FAFFA8-#FFC838-#FF8C12-#FA541C-#F51D27').opacity(0.1);

页面上没有任何变化

**Comment by leungwensen** [comment]
热力图的原理粗浅地理解就是通过变化的 opacity 来绘制的（每个点从中心到边缘由浓转淡，多个点相互叠加）。所以在这个 geom 里我们没有处理 opacity 这个通道。事实上开源的所有 heatmap 都没有开放透明度配置。你可以设置 container 本身 css 的透明度来调整，或者重新指定颜色。
