### ISSUE TITLE
设置 geom 渐变色，tooltip 中marker 消失

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#1006]
如题。
demo：
https://codepen.io/hstealth/pen/NEPgxx

如果 tooltip 不能支持渐变色，是不是可以搞个普通色的 marker 上去。

**Comment by leungwensen** [comment]
是 bug，老版本是没问题的

**Comment by 1053061407** [comment]
> 是 bug，老版本是没问题的

那该怎么办呢？现在tooltip不显示marker了

**Comment by dxq613** [comment]
3.5.8 中修复了，不过渐变中不支持 rgba，可以用:

```js
chart.interval().position('genre*sold').color('l(90) 0:#ffff00 1:#ff00ff');
```
取渐变的第一个颜色：
![image](https://user-images.githubusercontent.com/1264678/65740941-05da3b00-e11d-11e9-930c-b77ac09da630.png)
