### ISSUE TITLE
使用geojson绘制地图区域. 多区域时会出现直线

### ISSUE THREAD

**Issue by skjun** [antvis/G2#1008]
使用南京市的geojson数据绘制时候,绘制错误
相同的数据,其它图表插件(echart)绘制没有问题
![default](https://user-images.githubusercontent.com/5182975/47989034-d0042080-e11e-11e8-97c1-e574df32939e.png)

地图数据:
[3201.json.zip](https://github.com/antvis/g2/files/2547636/3201.json.zip)

**Comment by leungwensen** [comment]
G2 版本？

**Comment by skjun** [comment]
> G2 版本？

G2:3.3.3
DataSet: 0.10.0

**Comment by forbreak** [comment]
好像有飞地就会有这种情况。 
G2: 3.4.5
DataSet： 0.10.1
这个要如何解决？

**Comment by simaQ** [comment]
使用 3.5.12 版本试试
