### ISSUE TITLE
关于热力图的点颜色始终不变，即使重新设置颜色值、甚至清除整个container 都无法生效

### ISSUE THREAD

**Issue by zhuyan0302** [antvis/g2#1009]
通过 chart.heatmap() .color('z', 'xxx-xxx-xxx')  这种方式设置

![image](https://user-images.githubusercontent.com/22267227/48038476-c1177f80-e1ab-11e8-9085-2a37f920cfe8.png)

颜色值通过外部传入的透明度会更换不同的一组色值，为什么始终是第一个颜色？

**Comment by zhuyan0302** [comment]
不管我如何的更改都不起作用

**Comment by zhuyan0302** [comment]
@huacnlee

**Comment by zhuyan0302** [comment]
@leungwensen @simaQ @dxq613 @elaine1234 @guisturdy 请帮忙看一下，谢谢

**Comment by zhuyan0302** [comment]
> 请发codepen链接

https://codepen.io/anon/pen/dQoVVR

**Comment by zhuyan0302** [comment]
> 请发codepen链接

大概情况类似，我每次都重新渲染了整个，可是热点的颜色值改变不了

**Comment by zhuyan0302** [comment]
> 请发codepen链接

![image](https://user-images.githubusercontent.com/22267227/48040056-633a6600-e1b2-11e8-9edf-4a4ac6fe1fff.png)

如图，图例颜色变化了，热点颜色依旧

**Comment by zhuyan0302** [comment]
> 你调试一下，看看传进去的是什么渐进色吧。我改动是可以的

可以发一下你的demo吗？

**Comment by leungwensen** [comment]
就是你发的 codepen 链接啊。。。你能不能认真写个能复现问题的 codepen，你这样问我帮不了你的

**Comment by zhuyan0302** [comment]
> 就是你发的codepen链接啊...你能不能认真写个能复现问题的codepen，你这样问我帮不了你的

我发的哪个 codepen 链接上左上角有个按钮，点击之后会删掉之前的热力图，然后重新创建一个，并设置新的颜色值，你可以试着点击一下，基本上我现在项目中碰到的问题就跟这个codepen 的问题一样，都是重新设置颜色后图例颜色变了，热点的颜色没变~麻烦你了~谢谢

**Comment by leungwensen** [comment]
确实是热力图缓存的一个 bug，没有考虑这个场景，抱歉。3.4 会发布
