### ISSUE TITLE
堆叠柱状图按照数值进行渐变时，只使用了渐变颜色中的第一个颜色问题

### ISSUE THREAD

**Issue by zhensherlock** [antvis/G2#1010]
* **G2 Version 3.3.2:
* **Platform mac:
* **CodePen Link https://codepen.io/sunzhenxuan/pen/QJbJdb
请问我按照'月均降雨量'进行渐变为什么没有生效，好像堆叠柱状图没法用数值进行渐变，都只使用了渐变颜色中的第一个颜色

**Comment by zhensherlock** [comment]
@huacnlee @leungwensen @simaQ @dxq613 @elaine1234 @guisturdy 帮忙看一下，谢谢

**Comment by simaQ** [comment]
不支持
