### ISSUE TITLE
 htmlTemplate resolve error in Axis

### ISSUE THREAD

**Issue by lanyulin** [antvis/g2#1013]
https://antv.alipay.com/zh-cn/g2/3.x/tutorial/axes.html
官网上就解析错了
![image](https://user-images.githubusercontent.com/13092461/48108793-9d256e00-e27f-11e8-8f99-304d2d495644.png)

@antv/data-set 版本号：0.8.9

**Comment by leungwensen** [comment]
需要加 useHtml: true 配置项。暂时无法更新官网，望见谅
