### ISSUE TITLE
在多种图例情况下，大小图例在指定某个字段时，设置不生效问题

### ISSUE THREAD

**Issue by zhensherlock** [antvis/g2#1016]
* **G2 Version 3.3.2:
* **Platform mac:
* **CodePen Link https://codepen.io/sunzhenxuan/pen/wQKRKM:

指定了size字段进行配置，但是没有生效
chart.legend('size', {
  sizeType: 'circle'
});
如果添加了position: 'right'  就直接报错了
![image](https://user-images.githubusercontent.com/3541162/48119939-a0365380-e2ab-11e8-9f6b-c47416ba1071.png)
帮忙看一下是什么问题

**Comment by paleface001** [comment]
升级一下版本？ 3.5.0及以上版本已经没有这个问题了
