### ISSUE TITLE
堆叠柱形图，图形的最小高度是否可以设置

### ISSUE THREAD

**Issue by wangdedi1990** [antvis/g2#1020]
![image](https://user-images.githubusercontent.com/28214000/48175490-44b9a380-e347-11e8-8552-e0e9ad2a9f53.png)

如图所示，如果图形高度过低导致图形文本放不下，是否有方法可以设置最小高度？

**Comment by leungwensen** [comment]
不可以，这样会破坏整个度量计算，而且会带来误解。请通过字体颜色或者 offset 之类的来规避这个问题
