### ISSUE TITLE
//关于热力图的颜色值跟图例选中的范围不一致，求解~谢谢

### ISSUE THREAD

**Issue by zhuyan0302** [antvis/g2#1022]
![image](https://user-images.githubusercontent.com/22267227/48238035-688eef00-e404-11e8-8139-1ff12f095297.png)

**Comment by zhuyan0302** [comment]
@leungwensen 这个在项目中正在使用，出现了如上图所示的情况，我所选中的图例范围并没有红色，为什么会出现红色的热点，希望能看一下这个问题，麻烦了~

**Comment by zhuyan0302** [comment]
![image](https://user-images.githubusercontent.com/22267227/48238204-0f738b00-e405-11e8-8456-aee516bb570e.png)
![image](https://user-images.githubusercontent.com/22267227/48238216-20240100-e405-11e8-86f5-ce025496985c.png)
都是还没到最红就出现了红颜色的热点

**Comment by leungwensen** [comment]
热力图和普通的图形不一样，这个渐变色其实只是所谓一个色板，在最后才根据每一个像素点的权重去色板里取色的。

而每个像素点的权重和原始数据点的权重不能一一对应，因为每个像素点是原始像素点权重值辐射、叠加后的结果。如果映射半径（size，也就是辐射的范围）设置过大，那会出现比较多高权重的区域。

连续图例上的颜色只反映单一值的映射结果，和热力图的实现逻辑不一样的

**Comment by zhuyan0302** [comment]
> 能，就是 size 和 blur 如果设置过大或过小，图例交互的结果可能会不太一样。图例筛选的点是稳定的，正确的，就是最终渲染出来的结果会有不同

刚才我没说清楚，我重新描述下
这样的话，是不是我无法设置热点的大小？（因为配置太大的话，会出现上述图例跟热点颜色没对应上的显示效果，是这样吗？）

**Comment by leungwensen** [comment]
能，只是热点大小会影响视觉效果。实际图例过滤的结果是正确的

**Comment by leungwensen** [comment]
还有一点，热力图映射颜色的字段，必须设置 nice： false

**Comment by zhuyan0302** [comment]
> 能，只是热点大小会影响视觉效果。实际图例过滤的结果是正确的

可以指点一下配置的方法吗？我现在配置出来的效果不是很理想
![image](https://user-images.githubusercontent.com/22267227/48241744-215c2a80-e413-11e8-8b58-65213aacd050.png)

这是我的配置方法，效果是这样的
![image](https://user-images.githubusercontent.com/22267227/48241767-33d66400-e413-11e8-89be-39a6a87d6ae5.png)
![image](https://user-images.githubusercontent.com/22267227/48241773-3a64db80-e413-11e8-8db6-be35baabd897.png)

**Comment by leungwensen** [comment]
我知道问题了。。。你 映射 color 的字段没有设置 nice: false ，自动计算 scale 的时候上下限变了。图形里的最大值是数据里的最大值，而 legend 里的最大值是 scale 的最大值，最小值也类似。所以看起来有偏差。不过现在设置 nice: false 的时候数据映射有点问题，你稍等我修复一下，今天就发布新版。到时候你映射颜色的字段加上 nice: false 就可以了。

**Comment by zhuyan0302** [comment]
> 我知道问题了。。。你 映射 color 的字段没有设置 nice: false ，自动计算 scale 的时候上下限变了。图形里的最大值是数据里的最大值，而 legend 里的最大值是 scale 的最大值，最小值也类似。所以看起来有偏差。不过现在设置 nice: false 的时候数据映射有点问题，你稍等我修复一下，今天就发布新版。到时候你映射颜色的字段加上 nice: false 就可以了。

非常感谢，希望今天下午能尽快解决，很急，项目过两天上线~，今天已经是最终测试时间了

**Comment by zhuyan0302** [comment]
> 我知道问题了。。。你 映射 color 的字段没有设置 nice: false ，自动计算 scale 的时候上下限变了。图形里的最大值是数据里的最大值，而 legend 里的最大值是 scale 的最大值，最小值也类似。所以看起来有偏差。不过现在设置 nice: false 的时候数据映射有点问题，你稍等我修复一下，今天就发布新版。到时候你映射颜色的字段加上 nice: false 就可以了。

请问下，新版今天几点发布？
