### ISSUE TITLE
关于热力图的配置了 scale.tickCount 属性后，图例选中范围的颜色跟热点的颜色对应不上

### ISSUE THREAD

**Issue by zhuyan0302** [antvis/g2#1023]
![image](https://user-images.githubusercontent.com/22267227/48239703-e524cc00-e40a-11e8-8137-9973a4cb11d4.png)

如上图所示，我在热力图中配置了这个属性

未调整图例的筛选范围时：
![image](https://user-images.githubusercontent.com/22267227/48239755-1ac9b500-e40b-11e8-990d-b8f5f674bef1.png)

调整图例的筛选范围后：
![image](https://user-images.githubusercontent.com/22267227/48239802-477dcc80-e40b-11e8-8f17-3df362ab0edb.png)

图例选中的范围并没有红色，可是热点红色还在，当我去除掉 scale.tickCount 的属性后：
![image](https://user-images.githubusercontent.com/22267227/48239836-69774f00-e40b-11e8-9a46-9320db2da70b.png)

图例的颜色跟热点的颜色则对应上了，但是这个时候热点就显得很怪了~

@leungwensen 请看一下，谢谢~

**Comment by dxq613** [comment]
@zhuyan0302 你加个 nice: false 试试。

**Comment by zhuyan0302** [comment]
> @zhuyan0302 你加个 nice: false 试试。

加上后：
![image](https://user-images.githubusercontent.com/22267227/48240593-51ed9580-e40e-11e8-9c59-a496217ca361.png)

![image](https://user-images.githubusercontent.com/22267227/48240608-6336a200-e40e-11e8-84e4-195cf6bc901a.png)

目前的配置是：
![image](https://user-images.githubusercontent.com/22267227/48240621-6c277380-e40e-11e8-955d-2fd93d0bbfe4.png)

**Comment by leungwensen** [comment]
https://github.com/antvis/g2/issues/1022#issuecomment-437233961

**Comment by zhuyan0302** [comment]
@leungwensen 我在这里@ 你把~

**Comment by leungwensen** [comment]
3.4.0-beta.1

**Comment by zhuyan0302** [comment]
@leungwensen

**Comment by leungwensen** [comment]
热力图画图的原理是这样的，每一个数据点准确的像素点有一个和数值等值的权重，然后它周围的像素点（没有数据的点）会按照你设置的 blur 和 size 扩散赋值权重。在半径为 size 的区域内，每一个点的权重都和数据点的权重一致，然后向外扩散 blur 距离的点的权重逐次递减到0。不同数据点对应的 size 和 blur 区域如果有重叠，那相应的点权重会叠加。你给的截图中心点的颜色没有错，只是你的 size 设置太大，所以那一片颜色看起来很显眼而已。如果你想效果明显一点，可以设置 size 小一点，blur 大一点：

```js
.size(10)
.style({
  blur: 30
});
```
