### ISSUE TITLE
无法查看2.X文档

### ISSUE THREAD

**Issue by yuhonyon** [antvis/g2#1024]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by leungwensen** [comment]
https://antvis.github.io/

**Comment by zpz1982** [comment]
我现在也遇到这个问题，老项目还是要维护的:(。新版网站已经无法找到2.x的网页，请给一下2.x API文档的链接。

**Comment by simaQ** [comment]
不好意思，为大家带来困扰。

2.x 的文档链接：https://antv.vision/old-site/g2/doc/index.html
