### ISSUE TITLE
多 view 下, tooltip 的辅助线不鼠标移动

### ISSUE THREAD

**Issue by liximomo** [antvis/g2#1029]
多 view 图表, 鼠标在底部 view 区域内, tooltip 辅助线不跟随鼠标移动.

* **G2 Version**: v3.3.4
* **Platform**: macos chrome
* **Mini Showcase(like screenshots)**:
鼠标在上面 view 内移动, 一切正常:
![image](https://user-images.githubusercontent.com/9816225/48654275-723cd600-ea46-11e8-8456-6ba381cc93ef.png)

鼠标**移至**下面 view 内移动, 辅助线不再随鼠标移动了:
![image](https://user-images.githubusercontent.com/9816225/48654255-3f92dd80-ea46-11e8-82bf-8f87751780bb.png)

 [codepen](https://codepen.io/liximomo/pen/MzbRmM?editors=1010) 复现.

**Comment by liximomo** [comment]
这个问题有进展吗?

**Comment by liximomo** [comment]
v3.4.1下依然存在此问题.

**Comment by leungwensen** [comment]
稍等我们定位一下问题
