### ISSUE TITLE
分类图例,如何默认只选择一个？

### ISSUE THREAD

**Issue by petitspois** [antvis/g2#103]
分类图例,如何默认只选择一个（multiple 多选）模式下。
![image](https://cloud.githubusercontent.com/assets/9461149/24737299/2cc9ee5c-1ac0-11e7-81a3-e7b2abb82387.png)

**Comment by collinsyu** [comment]
为啥关闭，咋配置啊

**Comment by leungwensen** [comment]
调用 chart.filter

**Comment by collinsyu** [comment]
会了，谢谢，数据没搞清楚
