### ISSUE TITLE
Tooltip 隐藏时不应占用空间

### ISSUE THREAD

**Issue by ascoders** [antvis/g2#1034]
Tooltip 被隐藏时，配置如图所示：

![image](https://user-images.githubusercontent.com/7970947/48456194-192c3280-e7f9-11e8-926c-b7a29e0d2c45.png)

建议改成 display: none; 或者把 dom 干掉，我们有个这样的场景：

外部容器和图表高度一样，但 tooltip 不显示时默认放在左下角，导致父容器出现滚动条。正常的理解，Tooltip 在不显示时，不应该对 Dom 结构产生任何副作用。

**Comment by leungwensen** [comment]
![image](https://user-images.githubusercontent.com/1655789/48535241-887f5080-e8e5-11e8-89e6-f6554cdf16cf.png)
