### ISSUE TITLE
Point with stack doesn't render properly in polar coord.

### ISSUE THREAD

**Issue by Frezc** [antvis/G2#1037]
* **G2 Version**: latest
* **Platform**: chrome 70
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/Frezc/pen/xQqReY

**Comment by simaQ** [comment]
设置因为限定了 score 数值范围，而发生层叠后，数值范围比你设置的大。

```js
chart.source(dv, {
  score: {
    min: 0,
    max: 80
  }
});
```
