### ISSUE TITLE
支持 Label 不溢出画布

### ISSUE THREAD

**Issue by ascoders** [antvis/G2#1045]
由于我们有邮件截图的场景，所以需要将 Label 显示在画布内。

现在 Y 轴最大值会将 Label 顶出画布外，希望给 Label 加一个参数，同时检测 Label 与 Label 间、Label 与画布间的碰撞，确保 Label 显示在画布内。

问题截图：

![image](https://user-images.githubusercontent.com/7970947/48656113-8f2fd400-ea5b-11e8-8e51-e914eff2515c.png)

**Comment by aa1011372655** [comment]
可以通过设置padding参数将label展示完全
https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_padding

**Comment by ascoders** [comment]
目前可以暂时这么解决，但这样会在 label 不溢出时，不要增加多余的 padding。还是希望 g2 可以考虑 label 与画布的碰撞。
