### ISSUE TITLE
Scale tick 采样优化

### ISSUE THREAD

**Issue by ascoders** [antvis/G2#1046]
希望 Scale tick 采样时（维度轴为连续类型时）可以优先显示左边第一项与右边第一项。或者可以给一个配置：

- 保证首部 tick 显示。
- 保证尾部 tick 显示。
- 保证首位 tick 同时显示。

DEMO：

![image](https://user-images.githubusercontent.com/7970947/48684713-e5cd1780-ebed-11e8-8313-61ad92eba092.png)

**Comment by aa1011372655** [comment]
不是很理解你的需求，如果是想完美展示你期望的x轴坐标的话，可以设置scale中的ticks自己计算想要计算的，https://www.yuque.com/antv/g2-docs/api-chart#eh2hbw

**Comment by Frezc** [comment]
@aa1011372655 我觉得tick确实需要优化一下，比如下面这个图表的最左侧15:15的点就应该显示出来
![image](https://user-images.githubusercontent.com/6942296/49274470-7e4b7d80-f4b3-11e8-8b2a-33a5d32d04e9.png)

我提个建议，如果最小点和最大点离最近的一个tick相差太远（> 0.6 * tickInterval）那就可以把那个点对应字段加入ticks，希望g2能默认支持类似特性。

**Comment by leungwensen** [comment]
time 和 timeCat 的 scale 优化会放到 4.0，稍等

**Comment by simaQ** [comment]
4.0 已经发布，欢迎使用/升级。
