### ISSUE TITLE
antv g2 目前是不支持IE9的版本吗？

### ISSUE THREAD

**Issue by happylzb** [antvis/g2#1047]
g2版本：g2-3.3.2/dist/g2.min.js 
问题：在使用ie9的浏览器时，浏览器报 SCRIPT5009: “Float32Array”未定义

**Comment by happylzb** [comment]
在使用ie9的浏览器时，浏览器报 script1002: 语法错误 Float32Array

**Comment by aa1011372655** [comment]
可以支持的，你需要引入shim来拓展ie9的方法，如"es5-shim","es6-shim","babel-polyfill"

**Comment by leungwensen** [comment]
定位到是一个上层依赖库 gl-matrix 的问题，我们会尽量在 fork 的版本里修复，多谢反馈。

**Comment by dixdiydiz** [comment]
2019年5月份了，这个BUG修复了吗？？
