### ISSUE TITLE
能否对地图GeoJSON transform使其只包含边界数据？

### ISSUE THREAD

**Issue by zenxds** [antvis/g2#1048]
* **G2 Version**: latest
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

比如一个中国地图，目前G2的style是对所有geometry都生效的，如果设置了stroke之后所有省份都会有边框，能否通过data-set的transform，或者对原始GeoJSON处理得到一份只含最外层边界的GeoJSON，类似[http://echarts.baidu.com/examples/editor.html?c=map-polygon](http://echarts.baidu.com/examples/editor.html?c=map-polygon)，可以只设置中国边界部分的storke，内部省份的stroke可以不设置

**Comment by leungwensen** [comment]
这个是百度地图底图提供的功能，是 GIS 引擎提供的能力。对于 G2 而言，内置太重了。后续可能会对接高德地图，你对这个层面的底图定制只能基于高德地图来做，没法在上层的可视化库里做的。
