### ISSUE TITLE
浮点数精度计算问题

### ISSUE THREAD

**Issue by zuimeiaj** [antvis/g2#105]
const G2LineChart = createG2((chart) => {
    chart.col("trade_amount",{
        alias:"交易金额"
    }).col("trade_date",{
        alias:"交易日期"
    })
    chart.line().position('trade_date*trade_amount').size(2);
    chart.render();
});
如果trade_amount 有小数点，左边金额区间有浮点数精度问题
![image](https://cloud.githubusercontent.com/assets/11345054/24938686/4eec70b8-1f6b-11e7-98c6-e7a1b2aab6a8.png)

**Comment by simaQ** [comment]
额，这个是 js 本身浮点数导致的问题。

**Comment by dxq613** [comment]
在列定义里面加个 formatter处理一下
