### ISSUE TITLE
antV基础折线图，两端的折线点，当鼠标mouseover时，tooltip并不会出现！ 

### ISSUE THREAD

**Issue by minsion** [antvis/g2#1050]
1.基础折线两端点的折线点，当鼠标mouseover时，tooltip有时并不会出现！
2.antV基础折线地址https://antv.alipay.com/zh-cn/g2/3.x/demo/line/basic.html
3.如果折线图数据就一个点的话，这个bug出现概率很大！

**Comment by aa1011372655** [comment]
这个设计就是如此的，由于plotRange层设计，当鼠标移出展示图形区域后会隐藏tooltip，@leungwensen，这个体验问题我之前提过，是否有优化必要，不过也不好判断，增加多少像素让tooltip仍然展示

**Comment by xile611** [comment]
G2新版本可以考虑一下这个问题
