### ISSUE TITLE
Legend-item click is not friendly

### ISSUE THREAD

**Issue by JackieLs** [antvis/g2#1051]
* **3.2.8**:
* **Mac Chrome**:
*![image](https://user-images.githubusercontent.com/14228179/48813472-11790a80-ed72-11e8-9f7d-05c052bfc79f.png)

If I clicked the legend, the special point would disappeared.
And if I defined the customer `handleClick` function, the default behavior would be disabled.
I hope both would be enabled, my own `clickHandler` and the `defaultClickHandler`.
I can commit a pr.

https://github.com/antvis/g2/blob/1c0810e34a9701606182dee51a25938d1aa37d18/src/chart/controller/legend.js#L104

**Comment by leungwensen** [comment]
Sure, we can have better conversation in a PR, through code
