### ISSUE TITLE
如何实现分类legend翻页显示

### ISSUE THREAD

**Issue by 15531400827** [antvis/g2#1052]
- bizcharts Version: 3.3.0
- CodePen Link:  https://codepen.io/15531400827/pen/pQWVyy
- 如演示中第一个图，实际使用中 不想让legend换行， 支持legend翻页显示吗？

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/demo/component/legend-pagenation.html
