### ISSUE TITLE
语雀上的文档不完善

### ISSUE THREAD

**Issue by yimingjfe** [antvis/g2#1056]
以前官网上的文档都已下线，链接都指向了语雀，但是语雀上的文档不完善，且体验差，g2这种产品需要查api的频率还是蛮高的，建议暂时不要将文档都迁移到语雀。

具体问题表现在以下两点：

- 目前语雀上文档内的链接都返回404，完全不可用。
- 语雀的搜索功能不是每个页面都有，且没有搜索提示。

这两点目前对效率影响很大，期望g2团队能够考虑此建议。

**Comment by leungwensen** [comment]
多谢建议！链接 404 的问题确实是我们文档走查还没做到位。

搜索可以到文档首页里去搜： https://www.yuque.com/antv/g2-docs 

语雀的搜索是基于商业级搜索引擎的，官网之前只是一个最最原始的分词、词典来做的，而且语雀最大的一个优点是大家可以很方便地一起来优化这份文档，而不是以往改代码、提 PR、合并、发布这么长的文档维护流程。从长远来看，语雀托管文档的优势是很大的，也会是以后我们维护文档的主力方向。

**Comment by leungwensen** [comment]
遇到问题欢迎直接在语雀文档评论区或者语雀群组的讨论区给我们提，团队所有的小伙伴都可以第一时间收到你的需求。如果有意愿一起完善整个文档，也可以考虑成为 AntV 语雀团队的 member，非常感谢

**Comment by leungwensen** [comment]
近期语雀会在文档页面加入搜索功能 @yimingjfe

**Comment by rephor** [comment]
求教一下： g2最新版本，圆形的径向树结构，根节点的名称怎么可以显示呢，虽然antv比较好用，目前文档比较少
