### ISSUE TITLE
3.4.1 版本词云图颜色挂了。

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#1060]
如题。
https://antv.alipay.com/zh-cn/g2/3.x/demo/other/word-cloud-mask.html#
![image](https://user-images.githubusercontent.com/3838676/48894642-3195f000-ee7e-11e8-87f1-99148a7538ec.png)

**Comment by LinFeng1997** [comment]
问题仍然存在

**Comment by PerseveranceZ** [comment]
3.4.1 - 3.4.5 词云的颜色都是默认值，设置无效。
@leungwensen

**Comment by leungwensen** [comment]
请参照这个 commit 改一下你们的词云代码： 

https://github.com/antvis/g2/commit/273d1ab8d8a0b2ef46949e1834099f56c3c75f14

它不是在 G2 代码层面改的，是 词云 自定义 shape 的代码变更，是 demo 实现的问题。
