### ISSUE TITLE
图例长时间挂着，会引起页面崩溃

### ISSUE THREAD

**Issue by gouyuheng** [antvis/g2#1063]
* **G2 Version**:3.2.2
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:this.myChart.line().position('time*value').color('kind', this.colors).size(2).animate({
        update: {
          duration: 0
        }
      }).tooltip('time*kind*value', (time, kind, value) => {
        return {
          title: getDate(time),
          name: kind,
          value: value
        }
      })
this.myChart.point().position('time*value').color('kind', this.colors).size(4).shape('kind', this.types).style({
        stroke: '#fff',
        lineWidth: 1
      }).animate({
        update: {
          duration: 0
        }
      })
      this.myChart.render()

**Comment by aa1011372655** [comment]
如果不想要animate，可以直接关闭，https://www.yuque.com/antv/g2-docs/api-chart#olu9bn
