### ISSUE TITLE
正常雷达图，如何为area添加tooltip，显示所有数据

### ISSUE THREAD

**Issue by SmileLxy** [antvis/g2#1064]
![image](https://user-images.githubusercontent.com/10398990/48926899-d101c400-ef0c-11e8-95ba-34f19dee968a.png)
，鼠标在a'rarea中时，显示一圈的所有数据，有这个配置吗

**Comment by aa1011372655** [comment]
配置没有，推荐使用tootip:change事件绑定来实现，https://www.yuque.com/antv/g2-docs/tutorial-tooltip#su3awb
