### ISSUE TITLE
3.4.2 版本，tooltip style 配置失效。

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#1068]
3.4.2 版本，
1、tooltip style 配置失效。
demo：
https://antv.alipay.com/zh-cn/g2/3.x/demo/line/basic.html
加入如下代码：
```
chart.tooltip({
  crosshairs: {
    type: 'line',
    style: {
      lineWidth:2,
      stroke:"#green"
    }
  }
});
```

2、 配置主题为 dark，tooltip 背景色 文本色 都有问题。
![image](https://user-images.githubusercontent.com/3838676/48991566-589a3d80-f16e-11e8-99a2-9dfdb4add75c.png)

**Comment by leungwensen** [comment]
@paleface001 确认下  crosshairs 的样式定义接口，现在貌似 lineStyle 能生效，但 style 不生效，和接口文档不符

**Comment by leungwensen** [comment]
3.4.5

**Comment by MwumLi** [comment]
lineStyle 确实生效，但是这个 issue 就这么关掉了, 文档依旧没更新
