### ISSUE TITLE
[Feature Request] 直方图支持自定义bar宽度

### ISSUE THREAD

**Issue by newraina** [antvis/g2#1072]
对带范围刻度的直方图设置 `size(<number>)` 并不生效，这种直方图的bar宽度目前只能和组距关联，但有时候，业务需要用到的是非标准的直方图，组距并不固定，甚至相差非常大，这时候使用默认的size规则会让图表非常奇怪，更希望能**通过 `size` 方法直接设置bar宽度**。

对带范围刻度的直方图设置 `size(<number>)` 并不生效的代码示例：
[[CodePen]](https://codepen.io/newraina/pen/RqJEmp)

**Comment by dxq613** [comment]
x轴你都限定范围了，size 不可能生效的，你这种场景需要使用一般的柱状图。
