### ISSUE TITLE
饼图的间距设置太大的时候   就会出现饼块不在同一个圆心的情况

### ISSUE THREAD

**Issue by lx70770** [antvis/g2#1073]
以下是官网的一个例子  将lineWidth属性设置到15的时候  就会出现
![image](https://user-images.githubusercontent.com/24996868/49056052-e6406080-f234-11e8-860c-10a01732a8c0.png)

**Comment by paleface001** [comment]
lineWidth是图形边框，所以设的值大了就回出现这种情况。饼图切片间隔比较大的时候，推荐使用自定义shape的方式解决，参见：https://antv.alipay.com/zh-cn/g2/3.x/demo/pie/pie-slice.html
