### ISSUE TITLE
G2 关于柱状图/条形图 interval radius 的问题

### ISSUE THREAD

**Issue by PerseveranceZ** [antvis/g2#1074]
目前 G2 GEOM 中 interval 设置 style radius 无效，而F2是可以的。

**Comment by aa1011372655** [comment]
可以使用自定义实现https://www.yuque.com/antv/g2-docs/tutorial-customize-shape

**Comment by PerseveranceZ** [comment]
感谢回答，现在就是这样实现的，不过类似柱状图转化条形图，为了要一个圆角，就需要写两个shape的，私以为 radius 后续还是场景比较多。

**Comment by leungwensen** [comment]
F2 出于性能的考虑，直角坐标系下 interval 是直接用 rect shape 来画的，G2 的实现方式不太一样，是通用 path 的，没有做圆角处理。自定义 shape 实现的圆角矩形方案已经有 demo 了（ https://antv.alipay.com/zh-cn/g2/3.x/demo/column/column-rounded.html ），并且自定义 shape 是可以复用的，就不变更现在 interval 的实现方式了。集成的话会放到下个大版本。

**Comment by PerseveranceZ** [comment]
感谢反馈




| |
杨明哲
邮箱：a2192466@163.com
|

签名由 网易邮箱大师 定制

在2018年11月30日 14:31，绝云 写道：

Closed #1074.
