### ISSUE TITLE
官网上的「堆叠柱状图」的示例坏了

### ISSUE THREAD

**Issue by hh54188** [antvis/g2#1076]
https://antv.alipay.com/zh-cn/g2/3.x/demo/column/stacked-column.html

**Comment by overkazaf** [comment]
![image](https://user-images.githubusercontent.com/4262574/52757247-02d38400-303f-11e9-886e-e96490209172.png)
还是没修复

**Comment by leungwensen** [comment]
需要等待发布，官网项目 site 已修复，但目前因为封网在等待发布排期
