### ISSUE TITLE
[Feature request] Option minHeight for geom interval.

### ISSUE THREAD

**Issue by aixfox** [antvis/g2#1077]
* **G2 Version**: 3.4.5
* **Platform**: chrome latest
* **Mini Showcase(like screenshots)**: see codepen
* **CodePen Link**: https://codepen.io/anon/pen/aQRbWB (js line 15)(echarts demo)

While max value of data is much larger than min value, likes [0.01, 0.001, 10000], geom interval renders 0px for min value. Adding minHeight to these bars would be a better render result.
Would you please taking some consideration? (It seems that having scale problems?)

**Comment by xile611** [comment]
The new feature will be considered in the next version of G2.
