### ISSUE TITLE
标题超长时，图表高度被压缩

### ISSUE THREAD

**Issue by ascoders** [antvis/g2#1079]
见下图：

![image](https://user-images.githubusercontent.com/7970947/49203255-82f43100-f3e2-11e8-83db-a8bedd397b14.png)

经过测试，与 `padding: auto` 的配置有关，请问是用法问题还是一个 BUG？

**Comment by dxq613** [comment]
把下面的 'auto' 改成固定值试试，应该是计算边距的时候，对左右和上下的文本同等对待了，没有考虑左边右边的文本不应该影响上下边距，上下的文本不应该影响左右的边距。

**Comment by ascoders** [comment]
@dxq613 是的，但是下面改成固定值可能导致 x 轴标题展示不出来，看能不能修复一下？

**Comment by dxq613** [comment]
图例也同样存在这个问题，得想一个通用的方案。
