### ISSUE TITLE
3.4.0版本之后的两个bug

### ISSUE THREAD

**Issue by zenxds** [antvis/g2#1081]
* **G2 Version**: latest
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

一个是某些图表会多出默认的fill，比如官网示例的[水波图](https://antv.alipay.com/zh-cn/g2/3.x/demo/other/liquid-fill-gauge.html)，设置一个空的fill之后就可以了

二是某些情况下color无法支持rgba，比如[这个例子](https://codepen.io/zenxds/pen/BGvorr)

**Comment by leungwensen** [comment]
第二个问题，正确的 color 映射的语法是这样的：

`chart.polygon().position('year*value').color('year', ['rgba(0, 0, 0, 0.1)'])`

第一个问题我们跟一下
