### ISSUE TITLE
漏斗图建议增加转化率方式

### ISSUE THREAD

**Issue by excxapp** [antvis/g2#1083]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
漏斗图建议增加：下图所示的，转化虚线，这样有利于数据分析
![image](https://user-images.githubusercontent.com/4355581/49334902-08aef100-f61c-11e8-923d-e9cf65d54633.png)

**Comment by xile611** [comment]
新特性，G2新版本统一考虑

**Comment by xiao15934831580** [comment]
这个新需求在4.0版本中添加了吗，怎么实现的呢
