### ISSUE TITLE
词云图绘制问题

### ISSUE THREAD

**Issue by Me-Momo** [antvis/g2#1084]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/15646325/49335460-ca6bfe80-f628-11e8-816a-742ae2a737bb.png)

修改画布大小后
![image](https://user-images.githubusercontent.com/15646325/49335469-db1c7480-f628-11e8-9065-f63ef4633cff.png)

可能原因
![image](https://user-images.githubusercontent.com/15646325/49335520-b70d6300-f629-11e8-8db6-9ae047b5e513.png)

* **CodePen Link**:
https://antv.alipay.com/zh-cn/g2/3.x/demo/other/word-cloud.html

**Comment by DonChengCheng** [comment]
@Me-Momo 词云图绘制的问题解决没有，如果解决了，是怎么解决的

**Comment by leungwensen** [comment]
词云布局的 size 必须和画布一致。

**Comment by Me-Momo** [comment]
![image](https://user-images.githubusercontent.com/15646325/49476736-c07b1300-f855-11e8-99bd-083f202196ab.png)

![image](https://user-images.githubusercontent.com/15646325/49476694-a3dedb00-f855-11e8-9a9f-254bc8a7629a.png)

**Comment by DonChengCheng** [comment]
词云布局的 size 是和画布一致的，但是问题还是存在

**Comment by yutao331763646** [comment]
同样的问题  有些词会消失
