### ISSUE TITLE
MiniArea组件鼠标离开后浮层无法消失

### ISSUE THREAD

**Issue by whwJason** [antvis/g2#1085]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by whwJason** [comment]
这个 图表详情 的浮层 如果 把整个  图表部分全部覆盖的 话 当鼠标离开的时候是消失不了的  这个 能改进下么？https://preview.pro.ant.design/dashboard/analysis
![image](https://github.com/whwJason/image/blob/master/image1.png)
![image](https://github.com/whwJason/image/blob/master/image2.png)

**Comment by aa1011372655** [comment]
建议canvas的高度与实际高度一致，先规避掉这种问题，无法干涉外部的图层关系，或者把覆盖上部的图层下沉，还是推荐高度一致
