### ISSUE TITLE
瀑布图，想要精确在柱子上才出现 tooltip，目前是在刻度范围内就出，不太合理。

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#1088]
如题：
![image](https://user-images.githubusercontent.com/3838676/49372088-7e0de500-f734-11e8-91f6-394e792f1ab2.png)

**Comment by weepy3641** [comment]
没有修复，想要的是在柱子上才出 tooltip，而目前是移动到刻度范围内，即使不在柱子上，tooltip 也会出来。

**Comment by jany3534** [comment]
tooltip 问题不少

**Comment by fikyair** [comment]
我觉的在范围内，出现tooltip问题也不大

**Comment by markyun** [comment]
@fikyair  PD觉得不OK...

**Comment by joriewong** [comment]
Echarts的表现：
![image](https://user-images.githubusercontent.com/11408040/54731058-20a88180-4bc7-11e9-9603-87f6d52514f2.png)

**Comment by xile611** [comment]
@weepy3641 最新版已经解决
