### ISSUE TITLE
 core.min.js, simple.min.js 都有什么区别呢

### ISSUE THREAD

**Issue by kunl** [antvis/g2#1090]
dist 里面的 core.min.js, simple.min.js 都有什么区别呢，文档上没看到有介绍的地方

**Comment by aa1011372655** [comment]
可以关注一下源码库中的webpack配置，在这里简单说明一下：
core：只带有g2的api（这句话的意思是说，所有的geom内容都没有，如chart.line之类的api都是不支持的，你可以自己通过shape来开发自己想要的图库）
simple：带有g2的api并且支持三个geom（interval、line、point）
g2顾名思义，完整的g2库，支持canvas和svg渲染模式
