### ISSUE TITLE
g2 设置主题后，单个集合图形的 tooltip marker颜色有问题

### ISSUE THREAD

**Issue by PerseveranceZ** [antvis/g2#1091]
如图，marker的颜色遗留是默认的颜色，多组数据的情况下是没有问题的。

![116285388](https://user-images.githubusercontent.com/13193407/49438743-318cdd00-f7fa-11e8-91be-1384adc78cfc.png)
![116340627](https://user-images.githubusercontent.com/13193407/49438744-318cdd00-f7fa-11e8-969e-2f9a88cba5cf.png)

**Comment by aa1011372655** [comment]
@PerseveranceZ ，默认情况下，在只有一条数据的情况下，是不会走到colors和defaultColor判断中的，这里的主题声明需要完整的图形声明，如这样：
```javascript
G2.Global.registerTheme('test', {
  shape: {
    line: 
      {stroke: "red", lineWidth: 1, fill: null},
    point: 
      {stroke: "#fff", lineWidth: 1, fill: 'red'},
  },
  defaultColor: 'red',
  colors: [ 'red', 'blue', 'yello' ]
})

G2.Global.setTheme('test')
```

**Comment by PerseveranceZ** [comment]
@aa1011372655 感谢回复，我目前都 shape 里面的 storke 都删了，以为会走 defaultColor 呢，不过这样用户注册简单的主题，一条数据都需要改 shape ，会不会稍微麻烦了些，但从文档上面可能也找不出解决方法。

**Comment by aa1011372655** [comment]
https://github.com/antvis/g2/blob/master/src/theme/default.js
这个文件中，有所有主题配置信息，这里需要配置的是tooltip部分

**Comment by PerseveranceZ** [comment]
当前配置 加上文档 并不能完成修改 稍后会贴上配置。
不过如果修改单挑数据颜色都这么麻烦的话，我个人觉得，主题这个功能就变得鸡肋了很多。

**Comment by aa1011372655** [comment]
@PerseveranceZ ，这个暂时是这样走的，多维度数据的判断是另一套，需要整体考虑一下
@leungwensen 这里是不是要优化一下

**Comment by PerseveranceZ** [comment]
@aa1011372655 @leungwensen 那请问，目前有没有临时的解决办法或者代码呢
我们目前依据主题配置了好几套，但单数据的情况实际是非常多的。。。

**Comment by xile611** [comment]
G2 新版本会考虑这个新特性
