### ISSUE TITLE
动态更改饼图所在容器的宽度，就会出现label显示错乱的问题

### ISSUE THREAD

**Issue by DonChengCheng** [antvis/g2#1093]
* **G2 Version**:3.4.5
* **Platform**: Mac
* **Mini Showcase(like screenshots)**:
![15_05_24__12_04_2018](https://user-images.githubusercontent.com/17453366/49487431-46f71b00-f87d-11e8-8562-b6d721acbfd1.jpg)
* **CodePen Link**:

**Comment by aa1011372655** [comment]
请带上CodePen链接，这样能更好的定位问题，谢谢

**Comment by DonChengCheng** [comment]
已经解决了
