### ISSUE TITLE
地图的重新渲染导致浏览器卡死

### ISSUE THREAD

**Issue by carlosshilei** [antvis/g2#1098]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

世界地图初次加载，浏览器会有短暂卡顿。页面的其他元素（如图，表格的切换）向后端发送请求，导致页面的的重新渲染，浏览器此时会卡死，直到地图渲染完成。
![2018-12-07 4 35 44](https://user-images.githubusercontent.com/32117692/49636846-bbc58300-fa3e-11e8-8b2f-27fa5857ea0f.png)

有没有相关的API可以在地图数据没有变动的情况下，不进行重新渲染。

**Comment by leungwensen** [comment]
我推测你是使用类似 react 之类的技术编写页面，图表实例是和具体某个 react 组件绑定的，这个 react 组件在上层数据变化的时候重绘了，所以 G2 的 chart 实例被销毁重建了。这样的重绘，G2 是没办法控制的。

**Comment by leungwensen** [comment]
另外，貌似你使用了地图文本布局（map 类型的 label），这个比较耗性能，如果对文本遮罩不敏感，可以不用

**Comment by carlosshilei** [comment]
解决了。非常感谢。
附上解决办法，以供遇到同样问题的开发人员参考（我的页面是用react编写的）：
解决思路就是对比重绘前后的props，如果porps没有变化，则不进行重绘。可以在shouldComponentUpdate这一生命周期进行判断，同时要使用immutable进行比较props的异同。
参考链接:https://www.cnblogs.com/chris-oil/p/6159638.html
