### ISSUE TITLE
Display problem？

### ISSUE THREAD

**Issue by pengqiuyuan** [antvis/g2#11]
https://g2.alipay.com/demo/14-other/text-lable.html

### normal
![image](https://cloud.githubusercontent.com/assets/4953205/17798346/122d5380-6603-11e6-8d35-176f37399a44.png)

### position deviation （click `西藏自治区`）
![image](https://cloud.githubusercontent.com/assets/4953205/17798399/7427a8ba-6603-11e6-891c-587f26da99bf.png)

**Comment by dxq613** [comment]
这些文本是guide加入的，这个地方应该存在问题，最起码文本的位置不应该乱了。

**Comment by pengqiuyuan** [comment]
这里可以修复吗

**Comment by dxq613** [comment]
目前正在开发2.0版本，这个月底发布，这个问题我看看是在下个小版本修复还是在下个大版本发布的时候一起修复。

**Comment by pengqiuyuan** [comment]
先赞一个！希望能够尽快修复👍 ，要是能够 open full source code 就更好了！
