### ISSUE TITLE
图表在页面进行transform:scale之后，鼠标位置偏移

### ISSUE THREAD

**Issue by fuyongxia** [antvis/g2#1101]
* **G2 Version**:3.4.5
* **Platform**:windows10
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:  https://codepen.io/fuyongxia/pen/XoWvYg

页面进行一定的scale缩放后，图表上的鼠标位置发生偏移。

之前看到说是这个问题会在3.3.X版本得到修复，目前没有修复，请尽快修复

**Comment by leungwensen** [comment]
https://github.com/antvis/g2/issues/912
