### ISSUE TITLE
Tooltip inPlot 绘图区域属性失效。

### ISSUE THREAD

**Issue by PerseveranceZ** [antvis/g2#1103]
看了文档，inPlot 设置是否将 tooltip 限定在绘图区域内，默认为 true，即限定在绘图区域内。
但设置了之后并没有任何效果，tooltip依然限定在了绘图区域内。
关键代码：
```js
chart.tooltip({
  inPlot: false
});
```

**Comment by xile611** [comment]
inPlot 为 `true` 会调整tooltip的位置
inPlot 为 `false` 的时候，不会调整tooltip 的位置，如下图

![image](https://user-images.githubusercontent.com/6111424/63830450-bf1ee700-c99e-11e9-9275-20fd90ef4b5e.png)
