### ISSUE TITLE
如何调整颜色块的大小

### ISSUE THREAD

**Issue by qinyuhua** [antvis/g2#1104]
![image](https://user-images.githubusercontent.com/28893646/49844147-b3819500-fdfc-11e8-864b-1d5d66f88e8d.png)

**Comment by xile611** [comment]
如下设置颜色图例的大小
```js
  chart.legend(true, {
    width: 500,
  });

  chart.legend(true, {
    position: "right",
    height: 300,
  });
```

文档参考： https://www.yuque.com/antv/g2-docs/api-chart#f0053d7f
