### ISSUE TITLE
antv 柱状图tooltip鼠标移进移出显示存在bug，网页上代码不规范

### ISSUE THREAD

**Issue by DistantDream** [antvis/g2#1106]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/26541788/49918803-60ccd980-fedf-11e8-8b73-60ed180edfc6.png)
这是错误标签，
![image](https://user-images.githubusercontent.com/26541788/49918675-fd42ac00-fede-11e8-84b5-1c104a2c1b17.png)
鼠标移出后tooltip卡在里面显示，不隐藏

**Comment by keyaqi** [comment]
同问

**Comment by vickyliu95** [comment]
同问  有解决方法了吗

**Comment by aa1011372655** [comment]
安装最新版本可以修复这个问题，官网示例使用的3.5.1，@antv/component还未更新

**Comment by chenxwei** [comment]
页面上多个折线图时，鼠标在折线图之间移动，部分直线图的tooltip不隐藏。这个怎么解决？
