### ISSUE TITLE
zero

### ISSUE THREAD

**Issue by illumen** [antvis/g2#1108]
* **G2 Version**: ^3.3.3

It seems that the option zeroLineStyle on AxisGrid stopped working after version 3.3.2.

Example:
```
chart.axis('sales', {
  grid: { 
  	zeroLineStyle: {
    stroke: 'red',
    lineDash: [2, 4]
  	}
  }
});
```

This code is working in 3.3.2 but not 3.3.3.

**Comment by aa1011372655** [comment]
need to set parameters "hightLightZero" to true
```
chart.axis('sales', {
  grid: {
        hightLightZero: true,
  	zeroLineStyle: {
            stroke: 'red',
            lineDash: [2, 4]
  	}
  }
});
```

**Comment by bowencool** [comment]
where did you find these parameters? I did not see any `zero` at https://www.yuque.com/antv/g2-docs/api-chart#whc6bq

**Comment by aa1011372655** [comment]
> where did you find these parameters? I did not see any `zero` at https://www.yuque.com/antv/g2-docs/api-chart#whc6bq

Sorry, it should be that the documentation is not updated in time. This part of the configuration can be seen by reading the source code.
