### ISSUE TITLE
在设定了宽度自适应以后，拖拽改变宽度，导致图形模糊

### ISSUE THREAD

**Issue by yuyangvi** [antvis/g2#111]

**Comment by simaQ** [comment]
这个能提供下运行环境么？

1. 操作系统
2. 浏览器
3. 屏幕分辨率

**Comment by yuyangvi** [comment]
macbook pro15'' chrome

**Comment by dxq613** [comment]
拖拽改变窗口时，由于加了时间延迟，所以不会马上刷新图表的，只有当停下来的时候才会刷新。我在 macbook pro 的 chrome 上没有发现这个问题。
