### ISSUE TITLE
更新字云示例中的数据以触发leave动画后，纵向呈现的词语会先翻转至水平再退出

### ISSUE THREAD

**Issue by ahugh19** [antvis/g2#1112]
* **G2 Version**: 3.4.1
* **Platform**: Win10 Chrome
* **Mini Showcase(like screenshots)**:

**changeData前：**
![tim 20181217172800](https://user-images.githubusercontent.com/29140985/50078150-2afe5c80-0221-11e9-8909-703f8d1b0a19.jpg)
**changeData后：**
![tim 20181217172731](https://user-images.githubusercontent.com/29140985/50078178-42d5e080-0221-11e9-9e7a-c704dd3088d3.jpg)

* **Demo Link**: https://antv.alipay.com/zh-cn/g2/3.x/demo/other/word-cloud.html
在chart.render()后一行加上以下代码即可复现（注意：水平呈现的词语是正常的，纵向呈现的词语才会出问题）
```Javascript
setTimeout(() => {
    chart.changeData([]);
  }, 3000);
```

**Comment by xile611** [comment]
@ahugh19 问题没有重现，尝试一下最新版的G2是否已经解决这个问题
