### ISSUE TITLE
G2地图，GeoJson数据，如果存在空心的面，则无法正确绘制。

### ISSUE THREAD

**Issue by forbreak** [antvis/g2#1114]
* **G2 Version**:  3.4.5
* **Platform**:
* **Mini Showcase(like [screenshots)**:]
* **CodePen Link**:

GeoJson数据，如果存在空心的面，则无法正确绘制。
正常的图形
![test](https://user-images.githubusercontent.com/6947976/50192459-58582100-036d-11e9-8610-05c10f9db636.png)

g2画出来的
![g2-test](https://user-images.githubusercontent.com/6947976/50192472-6312b600-036d-11e9-8235-f160cc2b9d3f.png)

geoJson 数据

[test.json.zip](https://github.com/antvis/g2/files/2692867/test.json.zip)

**Comment by xile611** [comment]
@forbreak 麻烦确认一下最新版本时候还有这个问题，如果有，请补充一下重现这个问题的在线地址
