### ISSUE TITLE
轴支持配置toptitle

### ISSUE THREAD

**Issue by tianxuzhang** [antvis/g2#1115]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

G2 Version 3.4.5
需求描述：axis.title的offset希望支持数组或者x,y配置。实现轴的上方展示周的标题，从而减少左右空间占用，提升用户体验。
效果图：
![image](https://user-images.githubusercontent.com/4149550/50208641-a6404980-03ac-11e9-9af8-98e52e4f7518.png)

**Comment by xile611** [comment]
新特性，G2新版本统一考虑
