### ISSUE TITLE
tag-cloud 词云图 只有一条记录时显示不出来

### ISSUE THREAD

**Issue by seminelee** [antvis/g2#1116]
* **G2 Version**: 3.4.5
* **Platform**: windows
* **Mini Showcase(like screenshots)**:
![_20181220113332](https://user-images.githubusercontent.com/15016665/50262243-1c938900-044b-11e9-8ad9-3ea7a89990f1.png)
* **CodePen Link**:
 - [when data.length === 5](https://codepen.io/seminelee/pen/zyNqpe)
 - [when data.length === 1](https://codepen.io/seminelee/pen/xmgVJv)

**Comment by leungwensen** [comment]
当数据条数是1 的时候你需要调整一下词云布局里 fontsize 的设置：

```js
    fontSize: function fontSize(d) {
      if (d.value) {
        return (d.value - min) / (max - min) * (80 - 24) + 24;
      }
      return 0;
    }
```

这一段导致字号变成 infinity 了。

**Comment by seminelee** [comment]
thx
