### ISSUE TITLE
横向柱图，axis title无法设置textAlign,title始终居中 

### ISSUE THREAD

**Issue by yuyangvi** [antvis/g2#112]

**Comment by simaQ** [comment]
可以设置的。

```js
chart.axis('genre', {
  title: {
    textAlign: 'left' // textAlign 属性可取值 left right center
  }
});```

**Comment by yuyangvi** [comment]
![fireshot capture 56 - g2 - - https___antv alipay com_g2_demo_04-bar_h-bar html](https://cloud.githubusercontent.com/assets/386030/25261798/97563d3a-2686-11e7-9315-2865c15353f7.png)

**Comment by simaQ** [comment]
因为保留了 title, 文本的展示空间就会设定在title和坐标轴线之间，这个时候，你需要加大  titleOffset，

![snip20170421_7](https://cloud.githubusercontent.com/assets/6628666/25262344/0005e116-268a-11e7-96b9-d285d595bbba.png)

```js
chart.axis('province',{
        //title: null
        titleOffset: 100, // 标题距离坐标轴线的距离，默认是 60
        labelOffset: 90 , // 文本距离坐标轴线的距离，默认是 13
        labels: {
          autoRotate: false, // 关闭自动旋转功能
          label: {
            textAlign: 'left'
          }
        }
      });
```

![snip20170421_8](https://cloud.githubusercontent.com/assets/6628666/25262347/056ce33e-268a-11e7-819f-83b38fd8ab08.png)

**Comment by simaQ** [comment]
title 的话确实旋转不了。。。

**Comment by lcoder** [comment]
echart支持 旋转的，需求还是蛮强烈的，希望支持

**Comment by simaQ** [comment]
G2 3.0 版本支持了 https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_axis

**Comment by preservance717** [comment]
@simaQ 这个链接不存在了吗，它直接跳转到antv的首页啦？？
