### ISSUE TITLE
通过设置geom的active方法配置项style fill属性为高亮色不能覆盖opacity(field)

### ISSUE THREAD

**Issue by xuetian120** [antvis/G2#1122]
在做地区区域图表的时候，想hover上去该区块突出高亮显示出来（目前默认的效果对于hover效果非常弱，建议加强），通过设置设置geom的active方法配置项style fill属性为高亮色，因为同时也设置了opacity(field)方法，根据 field 字段的值计算透明度（这样默认就会也分布层次感），导致hover高亮效果也透明了，geom的active方法同时配置项style， fill: 'red'加上opacity: 1 无效，希望得到处理！

代码片段：
      userView.polygon().position('longitude*latitude').opacity('value').tooltip('name*num', (a, b) => {
        return {
          name: a,
          value: b
        };
      }).active(true, {
        highlight: false, // true 是否开启 highlight 效果，开启时没有激活的变灰
        style: {
          fill: '#f00',
          opacity: 1
        }
      }).animate({
        leave: {
          animation: 'fadeOut'
        }
      });

ps：因为使用opacity方法，导致无法做到真正的hover区块高亮。

**Comment by xuetian120** [comment]
请问什么时候可以解决这个bug呢

**Comment by simaQ** [comment]
使用 fillOpacity
