### ISSUE TITLE
希望支持 padding: auto 时元素不要溢出

### ISSUE THREAD

**Issue by ascoders** [antvis/g2#1125]
我知道 padding 设置为固定值可以解决问题，但固定值无法享受到 auto 的自动计算。然而 auto 自动计算还是会存在元素溢出问题，如下图：

![image](https://user-images.githubusercontent.com/7970947/50433375-c6bf5500-0912-11e9-9719-a02f213063d8.png)

推荐两种解决方案：

1. padding 支持 auto + 一个固定值，类似 css 的 calc。
2. padding: auto 时，解决元素溢出问题。

**Comment by xile611** [comment]
G2 新版本统一考虑
