### ISSUE TITLE
坐标轴文本被图形挡住

### ISSUE THREAD

**Issue by ilovedesert001** [antvis/G2#1127]
* **G2 Version**:3.4.8
* **Platform**:mac
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:https://codepen.io/ilovedesert001/pen/VqzwLR?editors=0010

使用 area 几何标记时，设置坐标轴文本在内部 ，会导致坐标轴文本被area 挡住，显示模糊

```

chart.axis('value', {
  position:'right',
  label: {
    offset:-10,
    textStyle: {
    textAlign: 'end'
    },
    formatter: function formatter(val) {
      return  'text text 文本'
    }
  }
}); 

```

**Comment by aa1011372655** [comment]
@leungwensen ，老哥这个问题是因为axis在backPlot里面渲染，设置的容器zIndex在frontPlot图表容器的下面，这个要调整吗？
@ilovedesert001 ，我提供一个思路，htmlTemplate可以设置label为dom节点，这个是在最上层的，具体样式可以自己实现

**Comment by leungwensen** [comment]
@ilovedesert001 这个问题暂时不会做调整，因为图形的优先级比 guide 类的组件高。参考 @aa1011372655 提供的思路做

**Comment by ilovedesert001** [comment]
```
 htmlTemplate: value => {
      return `<span>${value}</span>`;
 }
```

这样确实显示好了很多，但是这样每次刷新，创建那么多dom ， 会不会影响性能太多啊

**Comment by ilovedesert001** [comment]
解决了，控制 坐标轴刻度，尽量少显示，看起来没什么问题

**Comment by ilovedesert001** [comment]
使用 htmlTemplate 这样bug 更多
1.每次调用 render 后，坐标轴文本 不被回收 (也就是拖动窗口后，rerender 导致 有两排的 坐标轴文本 )

[https://codepen.io/ilovedesert001/pen/BvdQVg](url)

@aa1011372655 
@Leannechn

**Comment by simaQ** [comment]
考虑支持组件可选择渲染层级
