### ISSUE TITLE
折线图只显示x坐标对应的label

### ISSUE THREAD

**Issue by fenglu09** [antvis/g2#1132]
你好，在使用折线图的时候遇到了如下的问题：
需要在折线图上显示对应的值，但是数据量比较多，如果全部显示的话会很挤，如何实现只显示x轴tick对应点的label呢？
看了官方的[Demo](https://antv.alipay.com/zh-cn/g2/3.x/demo/line/line2.html)，可以通过传入方法判断，但是x轴显示的tick值是不确定的，如何实现呢？
求助~~~
* **G2 Version**: 3.0.12
* **Platform**: 
* **Mini Showcase(like screenshots)**: 
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/12250129/50506650-f0b07d00-0ab4-11e9-8f80-701894b50888.png)

**Comment by xile611** [comment]
新功能，后续统一考虑
