### ISSUE TITLE
如何动态更改坐标轴的显示隐藏？

### ISSUE THREAD

**Issue by Tomatoo** [antvis/g2#1139]
画折线图的时候（分类数据，不是连续诗句），如果分类非常多，那么X轴显示的内容就会重叠：
![2019-01-04 2 05 08](https://user-images.githubusercontent.com/15502063/50675550-c701d380-1029-11e9-8c32-b2698e8b4451.png)

我想在数据少的时候显示X轴，然后数据多的时候关闭Y轴，应该如何做到呢？谢谢。

* **G2 Version**:3.3.3
* **Platform**: Chrome

**Comment by leungwensen** [comment]
升级到最新版本，不用隐藏，可以自动抽稀：

```js
chart.axis('genre', {
  label: {
    autoRotate: false,
    autoHide: true
  }
});
```

![image](https://user-images.githubusercontent.com/1655789/50678811-71cebd80-103b-11e9-8a65-2fd6055e0aba.png)

**Comment by Tomatoo** [comment]
多谢，按照这个方案解决了。
