### ISSUE TITLE
chart render 后是否有类似 render complete 事件？ 

### ISSUE THREAD

**Issue by raisezhang** [antvis/g2#1141]
* **G2 Version**:
3.4.9
* **Platform**:
Mac Chrome
* **Mini Showcase(like screenshots)**:
类似
``` javascript
chart.render((success) => {
  console.log('渲染结果：' + success);
})
```
* **CodePen Link**:

**Comment by leungwensen** [comment]
你可以认为 render 函数是同步的。执行完那一刻就代表 render complete 了。

**Comment by raisezhang** [comment]
Thanks ~
