### ISSUE TITLE
Axis label autoRotate 结果不理想

### ISSUE THREAD

**Issue by leungwensen** [antvis/G2#1143]
https://codesandbox.io/s/28qz9pkqr

![image](https://user-images.githubusercontent.com/1655789/50949914-18570a80-14e3-11e9-8904-e761e21bcc2d.png)

* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
4.0 已支持坐标轴文本的自动隐藏、自动旋转以及自动省略。
