### ISSUE TITLE
韦恩图 label 不能使用 label type

### ISSUE THREAD

**Issue by leungwensen** [antvis/g2#1146]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

目前韦恩图走的是自己的 label 绘制逻辑，没有使用 geom 通用的 label，导致无法应用 label 布局算法

https://riddle.alibaba-inc.com/riddles/edd77bb2

**Comment by xile611** [comment]
这个问题好像已经解决了，Venn图label现在走的是统一 的label
