### ISSUE TITLE
饼状图不支持y轴值为null的情况

### ISSUE THREAD

**Issue by ylnbird** [antvis/g2#1148]
* **G2 Version**:3.4.10
将官网实例(https://antv.alipay.com/zh-cn/g2/3.x/demo/pie/innerlabel.html)
中的data中的任何一组的percent值改为null时,就报[Cannot read property 'length' of undefined at e.n._isToMiddle]的错误.

希望代码兼容null

**Comment by aa1011372655** [comment]
@leungwensen ，老哥，这个是因为getLabelPoint方法时，point不存在x这个属性，怎么处理好？我是准备直接这样处理：
```
if (!point.x) return {};
```
 
https://github.com/antvis/g2/blob/7ef382b3c55c313e186df48a313477d9fbd22a8a/src/geom/label/polar-labels.js#L98
https://github.com/antvis/g2/blob/7ef382b3c55c313e186df48a313477d9fbd22a8a/src/geom/label/polar-labels.js#L82

**Comment by aa1011372655** [comment]
> 不能直接 (!point.x) ，这样 point.x 是0也会出问题

ok，我用util处理一下
