### ISSUE TITLE
同时设置chart.legend和chart.guide().html()时存在lengend不显示的bug

### ISSUE THREAD

**Issue by ylnbird** [antvis/g2#1149]
* **G2 Version**:3.4.10
附件实例中:
chart.legend({position:'top'});由于其下行chart.guide().html()的存在而无法显示lengend;而3.4.8及之前版本可以.
另外3.4.9及以后版本chart.legend({position:'bottom'});时是可以显示lengend的.
[chart.zip](https://github.com/antvis/g2/files/2751806/chart.zip)

**Comment by huntcraft** [comment]
我也碰到这个问题了。
[codepen](https://codepen.io/hho9240/pen/wRZOqp)
