### ISSUE TITLE
请问有没有全局配置g2的显示字体

### ISSUE THREAD

**Issue by briefguo** [antvis/g2#115]
项目在重构中, 用起g2感觉很舒适, 声明式的去绘制一个图表,但是不知道怎么找到修改字体的地方

**Comment by simaQ** [comment]
这个会在下个 2.3.1 版本支持的

**Comment by briefguo** [comment]
可以的，加油支持

**Comment by simaQ** [comment]
2.3.1 版本已支持 `G2.Global.fontFamily`
