### ISSUE TITLE
guide.html 怎么修改和更新配置

### ISSUE THREAD

**Issue by huangchaofei** [antvis/g2#1159]
* **G2 Version**:3.2.8
* **Platform**:chrome
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

圆环图 我在圆环的interval:mouseenter(hover) 和interval:mouseleave(离开)回调函数里希望改变guide.html的position但是无效 g2也没有f2的guide.repaint()

**Comment by aa1011372655** [comment]
你好，可以尝试chart.repaint()
