### ISSUE TITLE
renderer为svg模式下,面积图配置尾部跟随lengend,在图表设有padding-top时legend位置不对

### ISSUE THREAD

**Issue by ylnbird** [antvis/g2#1162]
* **G2 Version**:3.4.1--3.4.10
官方图例:https://antv.alipay.com/zh-cn/g2/3.x/demo/line/line13.html
增加以下配置后,出现如题所述位置不正确的bug(legend位置下移了).
1.图例代码第81行:改为padding: [70, 70, 70, 50],同时增加renderer:'svg'
2.135行增加: chart.area().position('date*value').color('type').label('value');

**Comment by hustcc** [comment]
@ylnbird 目前我看是正常的。可以帮忙再确认一下，或者在 codepen 中复现示例。

![image](https://user-images.githubusercontent.com/7856674/63767576-a102a980-c900-11e9-8fe6-8780188810f9.png)
