### ISSUE TITLE
Facet 分面 fileds有问题，使用报错Please specify for the field for facet

### ISSUE THREAD

**Issue by nightkis** [antvis/g2#1163]
使用分面功能时报错
![1](https://user-images.githubusercontent.com/35192215/51667114-3bf97500-1ffa-11e9-8e2c-99b88183a92b.png)
对比示例后发现fileds写错了，应该是fields
![2](https://user-images.githubusercontent.com/35192215/51667175-65b29c00-1ffa-11e9-9df2-dca19c96edb5.png)
修改index.d.ts文件中的fileds，改为fields
再添加transpose?: boolean
图表才和示例一样正常显示

**Comment by hustcc** [comment]
类型定义已经在 commit 455dc2a99a0cd9946b4a3fb40dd065e45450e568 修复。
