### ISSUE TITLE
padding: auto 情况下，坐标轴 label 会存在溢出

### ISSUE THREAD

**Issue by BlackGanglion** [antvis/g2#1164]
* **G2 Version**: 3.4.10
* **Platform**: Mozilla 5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
* **CodePen Link**:
https://riddle.alibaba-inc.com/riddles/90740023

![image](https://user-images.githubusercontent.com/9314735/51669302-276bab80-1fff-11e9-95ea-5465055bc0cb.png)

```javascript
import G2 from '@antv/g2';

var data = [
  {"dim":"Jiangsu","value":6.059999999999998},
  {"dim":"上海","value":5.409999999999998},
  {"dim":"云南","value":1.56},
  {"dim":"内蒙古","value":21.579999999999995},
  {"dim":"北京","value":17.000000000000004},
  {"dim":"吉林","value":16.84},
  {"dim":"四川","value":4.259999999999999},
  {"dim":"天津","value":14.53999999999999},
  {"dim":"宁夏","value":4.349999999999999},
  {"dim":"安徽","value":15.61}
]
var chart = new G2.Chart({
  container: 'mountNode',
  forceFit: true,
  height: 200,
  padding: 'auto'
});
chart.source(data);
chart.interval().position('dim*value');
chart.render();
```

**Comment by mk-nickyang** [comment]
BizCharts也有类似问题，不过说要g2修复。请问g2这里有修复的打算吗？

Related BizCharts issue: https://github.com/alibaba/BizCharts/issues/378
Related g2 issue: https://github.com/antvis/g2/issues/1125

**Comment by hustcc** [comment]
看看是否已经修复了。描述中的 demo 实例：https://riddle.alibaba-inc.com/riddles/90740023

![image](https://user-images.githubusercontent.com/7856674/63823000-d3ee8100-c984-11e9-89e9-3fa4ebe19a23.png)

**Comment by DaDanLiu** [comment]
这个问题没解决吧，如果第一个横坐标长度为1,他的autoFit 计算方式仅依赖第一个的长度，之后字符过多还是会溢出；
比如上图在 jiangsu 前加一个 横坐标文案为 t 的 数据，jiangsu 会溢出 @hustcc
