### ISSUE TITLE
candle的stroke一直使用的默认颜色

### ISSUE THREAD

**Issue by weibobo** [antvis/g2#1168]
g2/schema.js里面，画蜡烛图的时候stroke不使用cfg.color，一直使用的默认颜色
function getFillAttrs(cfg) {
  const defaultAttrs = Global.shape.schema;
  const lineAttrs = Util.mix({}, defaultAttrs, cfg.style);
  ShapeUtil.addFillAttrs(lineAttrs, cfg);
  if (cfg.color) {
    lineAttrs.stroke = lineAttrs.stroke || cfg.color;  //<--- 这里应该是 lineAttrs.stroke =cfg.color || lineAttrs.stroke;
  }
  return lineAttrs;
}

**Comment by weibobo** [comment]
例子：https://antv.alipay.com/zh-cn/g2/3.x/demo/candlestick/basic.html

**Comment by illumen** [comment]
I've created a pull request for this. #1180
