### ISSUE TITLE
Tooltip从右侧划入的时候显示有问题。

### ISSUE THREAD

**Issue by Sql544** [antvis/g2#1171]
* **G2 Version**:3.4.9
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

官方的图例就可以复现这个bug 
从图例的右侧划入图例tooltip会有个样式动态改变的过程。从右下角划入停住有很大概率发生样式显示问题。

![image](https://user-images.githubusercontent.com/29001273/51953243-940afe00-2476-11e9-84d2-78c3fe2456ad.png)

**Comment by git-ming** [comment]
请问这个问题会在哪个版本修复呢？目前遇到同样的问题
