### ISSUE TITLE
api guide下的dataRegion配置无法渲染，使用region的时候却正常！

### ISSUE THREAD

**Issue by kinghoo5201** [antvis/g2#1172]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:https://codepen.io/kinghoo5201/pen/gqLmOw

![image](https://user-images.githubusercontent.com/25658415/51970011-c9344200-24b0-11e9-983b-f55659eafc1a.png)
当使用region的时候图形正常渲染，但是使用dataRegion的时候发现辅助区域无法正常展示

**Comment by hustcc** [comment]
一下配置可行：

```js
chart.guide().dataRegion({
    start: ['7', 'min'],
    end: ['9', 'max'],
    content: '数据区间标注',
    lineLength: 50,
  });
```

![image](https://user-images.githubusercontent.com/7856674/63832870-428f0700-c9a4-11e9-9664-9551accec9b0.png)

**Comment by 531431988** [comment]
这个能设置显示的方向吗？目前只找到往上标记的，不能往下

**Comment by 531431988** [comment]
direction: { string }, // 可选，朝向，默认为 upward，可选值为 'upward' 或者 'downward'
这个在官方演示上测试没效果
