### ISSUE TITLE
[brush] Support calling default behaviour when onBrushend set

### ISSUE THREAD

**Issue by Frezc** [antvis/g2#1173]
* **G2 Version**: latest
* **Platform**: all
* **Mini Showcase(like screenshots)**: 
* **CodePen Link**: 

我发现在brush里设置了onBrushend就不会默认执行clear，filter的代码了，可是很多时候我只是想响应一下brushend事件。
https://github.com/antvis/g2/blob/41c5ad27ca7aa35cffd122fe0a766104d7183afb/src/interaction/brush.js#L317-L319

我希望可以根据onBrushend的返回值来判断是否需要执行默认逻辑（比如返回true时才执行默认逻辑），如果觉得这个提议ok我可以发个pr。

**Comment by dengfuping** [comment]
@Frezc 感觉可以支持，`onBrushend` 返回 `true` 时执行默认框选逻辑，没有指定返回值默认返回 `false`，这样也能兼容之前的逻辑。@leungwensen @simaQ 的意见呢？

**Comment by simaQ** [comment]
默认对每种交互行为我们都有一个 onEnd 的钩子，是在交互行为全部结束之后触发的，即框选结束并且数据过滤之后，不知道能不能满足你的需求

**Comment by Frezc** [comment]
@simaQ  看了下不知道什么时候加的interaction文档，是指`onDragend`吗？

**Comment by simaQ** [comment]
https://github.com/antvis/g2/blob/77ec2abb31eeb3d260cbe968f7e5bb9419e6856d/src/interaction/base.js#L37

可以看下 Interaction 的基类，Interaction 文档还不够完善，忘记将这些钩子加上了，我去补充下

**Comment by Frezc** [comment]
我试了下不会返回brush选中的数据，这个不能满足我的需求啊

**Comment by jiananshi** [comment]
@dengfuping +1，即使是走 `onEnd` 也要给一个 interactionType 这样的参数，为何不能执行完默认逻辑后再执行 `onBrushend`？
