### ISSUE TITLE
real-time graph

### ISSUE THREAD

**Issue by komagic** [antvis/g2#1175]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://www.highcharts.com/demo/dynamic-update

想问下类似 https://www.highcharts.com/demo/dynamic-update 实时图能用g2实现吗？可否给一个例子?(别用f2的，感觉有问题)

**Comment by aa1011372655** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/demo/other/line-realtime.html
是否类似于这样？

**Comment by komagic** [comment]
> https://antv.alipay.com/zh-cn/g2/3.x/demo/other/line-realtime.html
> 是否类似于这样？

不行这个，这个一直往内存中加数据。
数据需要保持恒定个数（比方说小于200个），这个case200个后 动画 就错了。不信你可以把数字200改成一个较小值试下

**Comment by aa1011372655** [comment]
我的意思是，按照这个逻辑你就可以写出来了，这个是通过data的不断push的，你直接将新数据处理一下调整到合适的个数，不断执行changeData就行了

**Comment by komagic** [comment]
写出来动画不对啊

**Comment by aa1011372655** [comment]
我理解是过一段时间，动画的展示就发生变化了是吧？

> 写出来动画不对啊, 开始视觉是正常的从右往左移动，但是过了临界值，g2和f2的动画就会变成上下波动， 我发的文章链接https://bost.ocks.org/mike/path/ 里说明了原因了，你试下嘛。 把你发的链接里的200改成10试下，等一会儿看看动画是不是出现问题。因为我对antv不熟，所以想问下怎么按照我发的文章内容那样操作antv g2？

我理解，就是数据过一段时间以后，动画效果不一样了？

**Comment by hustcc** [comment]
@komagic 在 demo https://antv.alipay.com/zh-cn/g2/3.x/demo/other/line-realtime.html 中测试了，并不会遇到问题。

> 将 line 44 行中的数字改小一点，可以更快看到效果。

**Comment by Airkro** [comment]
这个问题一直都存在，如果用数据替换做横向推移的动画，是达不到预期的效果的。

**Comment by TommyCat008** [comment]
请问这个feature在哪个版本修复了，目前看到4.1.16版本仍然有此问题。
