### ISSUE TITLE
slider 拖动时，其两端的度量值，与横坐标最左和最右两端的值不对应，且差距明显

### ISSUE THREAD

**Issue by tyawei** [antvis/g2#1176]
比如，当横坐标的刻度值是由时间戳转成的日期格式，横坐标上同样也是。拖动 slider 两端，横坐标联动变化，此时横坐标最左和最右侧的时间应当与 slider 查询时间的两端保持一致。
不过，明显存在差距，HH:mm:ss 差距相对小一些，大概几秒，也是我方项目上复现的（我方项目用的 bizcharts，同时也给 bizcharts 提过 issue）。HH:mm 类型差距更明显，就像 G2 官网上的案例 https://antv.alipay.com/zh-cn/g2/3.x/demo/line/line-rain-and-flow.html ：
![g2](https://user-images.githubusercontent.com/25874165/52680319-fbdf3f80-2f72-11e9-9a0b-3adbcb090acb.png)
![g2](https://user-images.githubusercontent.com/25874165/52680321-ff72c680-2f72-11e9-917e-e78fad3c4fc8.png)

我方G2版本为：2.3.13，bizcharts版本为：3.4.1； 以上官网案例G2版本为：3.4.1

请确认是否是G2bug，以及处理计划或方案？

**Comment by tyawei** [comment]
补充一下，这是在 bizcharts处的讨论。还请看一下：https://github.com/alibaba/BizCharts/issues/723

**Comment by kuangshu** [comment]
我遇到同样问题，数据只有65条，我设置坐标使用index并设置slider的minSpan和maxSpan为4的情况下，最高的数据值为70并不是65

**Comment by hustcc** [comment]
这个问题在 g2 4.0 中修复吧，关于 slider 滑块直视数据偏移。
