### ISSUE TITLE
g2 position=x*y 当y有几个值时，一个图表会出现几个y轴，而且y轴是重叠的

### ISSUE THREAD

**Issue by 1053061407** [antvis/g2#1179]
* **G2 Version**:  latest
* **Platform**: 
* **Mini Showcase(like screenshots)**:  
![image](https://user-images.githubusercontent.com/22407482/52703398-379cf800-2fb9-11e9-8804-2b0dc2b3086a.png)

* **CodePen Link**:    https://antv.alipay.com/zh-cn/g2/3.x/demo/other/double-axes.html

链接就是如上的官方实例链接。源代码是
```
chart.interval().position('time*waiting').color('#3182bd');
chart.line().position('time*people').color('#fdae6b').size(3).shape('smooth');
chart.point().position('time*people').color('#fdae6b').size(3).shape('circle');
```

我在实例代码中多加了一行代码

```
chart.line().position('time*call').color('#ff8888').size(3);
```
此时position的参数中的y就有了waiting，people，call三个值。
此时就会出现3个y轴。而且右边的两个y轴会重叠，还会多很多y轴间隔线
如图
![image](https://user-images.githubusercontent.com/22407482/52703398-379cf800-2fb9-11e9-8804-2b0dc2b3086a.png)

希望实现的是实际场景中可能不只有三个指标，但是希望只显示其中的两个y轴，左边一个右边一个。有没有一个属性可以在执行
```
chart.line().position('x*y')
```
时，不会因为y的不同而额外的生成多个y轴。因为我看官方文档上写的是
![image](https://user-images.githubusercontent.com/22407482/52704154-de35c880-2fba-11e9-9954-2e6acc3b919a.png)
是根据position的y自动生成的

**Comment by aa1011372655** [comment]
可以通过多view来统一处理，每一个view单独绘制一种图，然后通过view.axis来独立控制每个view的坐标轴属性

**Comment by leungwensen** [comment]
你说的重叠、多生成的 grid 都好解决，但其实很不建议使用多 Y 轴图表。如果出现图形，又没有对应的标度，那会造成误导的。
如果非要把这些线重叠在一起，建议先合并字段，用 dataset 的 fold，统一字段之后再用 color 映射成不同的图形，这样比直接隐藏掉某个刻度要好

**Comment by 1053061407** [comment]
> 你说的重叠、多生成的 grid 都好解决，但其实很不建议使用多 Y 轴图表。如果出现图形，又没有对应的标度，那会造成误导的。
> 如果非要把这些线重叠在一起，建议先合并字段，用 dataset 的 fold，统一字段之后再用 color 映射成不同的图形，这样比直接隐藏掉某个刻度要好

```
const data = [
      {
        month: "Jan",
        Tokyo: 7.0,
        London: 3.9
      },
      {
        month: "Feb",
        Tokyo: 6.9,
        London: 4.2
      },
      {
        month: "Mar",
        Tokyo: 9.5,
        London: 5.7
      },
      {
        month: "Apr",
        Tokyo: 14.5,
        London: 8.5
      },
      {
        month: "May",
        Tokyo: 18.4,
        London: 11.9
      },
      {
        month: "Jun",
        Tokyo: 21.5,
        London: 15.2
      },
      {
        month: "Jul",
        Tokyo: 25.2,
        London: 17.0
      },
      {
        month: "Aug",
        Tokyo: 26.5,
        London: 16.6
      },
      {
        month: "Sep",
        Tokyo: 23.3,
        London: 14.2
      },
      {
        month: "Oct",
        Tokyo: 18.3,
        London: 10.3
      },
      {
        month: "Nov",
        Tokyo: 13.9,
        London: 6.6
      },
      {
        month: "Dec",
        Tokyo: 9.6,
        London: 4.8
      }
    ];
    const ds = new DataSet();
    const dv = ds.createView().source(data);
    dv.transform({
      type: "fold",
      fields: ["Tokyo", "London"],
      // 展开字段集
      key: "city",
      // key字段
      value: "temperature" // value字段
    });
```
比如我把上面的data通过dataset的fold映射成了temperature字段。
chart.line().position('month*temperature');
这样只能渲染出一种图形。我如何让Tokyo渲染成柱状图，London渲染成折线图呢。您说的用 color 映射成不同的图形是如何实现呢？
@leungwensen

**Comment by HongYangHT** [comment]
可以利用scale的sync属性来惊醒同步度量
