### ISSUE TITLE
2.3.0 环图点击 不会自动归位

### ISSUE THREAD

**Issue by chclock** [antvis/g2#118]
1. 当环图只有2个不同的数据时，先点击一个部分，再点击另一个时，原先的不会自动归位。
2. 请问如何关闭点击事件？

**Comment by simaQ** [comment]
hi~
1. 这个问题我这边重现了，我定位下哦~
2. 你是要关闭饼图的点击效果么? 如果是的话，只需要 `.selected(false)` 如下 
```js
chart.intervalStack()
        .position(Stat.summary.percent('value'))
        .color('name')
        .selected(false)
```

**Comment by simaQ** [comment]
你好，关于第一个问题其实是已经归位了，只是视觉差造成了这个误导。你点击另一个扇形的时候，之前选中的扇形会先归位然后被点击是扇形再展开，刚好这个空隙的大小是一样的，所以会认为木有归位...

**Comment by chclock** [comment]
好的，谢谢。
