### ISSUE TITLE
使用图没有数据的时候可以定制展示的样式吗？

### ISSUE THREAD

**Issue by fengmumu1** [antvis/g2#1181]
无数据状态下
![image](https://user-images.githubusercontent.com/37215225/52835499-9aa99e80-3121-11e9-8dc3-225e67091e0b.png)
有数据状态下
![image](https://user-images.githubusercontent.com/37215225/52835513-a8f7ba80-3121-11e9-851a-4fa3407937d1.png)

我想在无数据状态下展示文字 暂无数据，要如何做
![image](https://user-images.githubusercontent.com/37215225/52835541-d2b0e180-3121-11e9-8ccc-9e50263f0203.png)

**Comment by aa1011372655** [comment]
这里建议自行判断，首先判断数据是否为空（空的情况有很多种），直接展示暂无数据，有数据再渲染图表

**Comment by fengmumu1** [comment]
> 这里建议自行判断，首先判断数据是否为空（空的情况有很多种），直接展示暂无数据，有数据再渲染图表

我是一开始就给了一个空数据（意外情况有专门的处理），就只是想在数据是一个空数组的时候有图像，在有数据的时候显示数据
我是先构建了对应的图标实例，然后把他挂在再thi上，这样子一开始就有一个图表了，后面由用户操作去请求不同的数据，这时候调用更新数据的api图像就出来了
如果我一开始构建实例，只在有数据构建实例并且渲染，那么在用户多次更新数据的时候我就多次创建了图表，而且直接创建以一个新的 以前的仍会留下来
所以我目前计划是，先创建实例，然后有数据才去更新，没有数据就把图标用css隐藏，但是总觉得很麻烦，所以我就想问问有很么办法可以直接在图上定制，数据为空时候的显示

**Comment by aa1011372655** [comment]
> > 这里建议自行判断，首先判断数据是否为空（空的情况有很多种），直接展示暂无数据，有数据再渲染图表
> 
> 我是一开始就给了一个空数据（意外情况有专门的处理），就只是想在数据是一个空数组的时候有图像，在有数据的时候显示数据
> 我是先构建了对应的图标实例，然后把他挂在再thi上，这样子一开始就有一个图表了，后面由用户操作去请求不同的数据，这时候调用更新数据的api图像就出来了
> 如果我一开始构建实例，只在有数据构建实例并且渲染，那么在用户多次更新数据的时候我就多次创建了图表，而且直接创建以一个新的 以前的仍会留下来
> 所以我目前计划是，先创建实例，然后有数据才去更新，没有数据就把图标用css隐藏，但是总觉得很麻烦，所以我就想问问有很么办法可以直接在图上定制，数据为空时候的显示

之前的仍然保留是由于你没有销毁操作
```
chart. destroy();
chart = null;
```
最不济的方法时每次都销毁然后new一个Chart，最好的方法是通过判断尽量复用之前的chart实例

**Comment by fengmumu1** [comment]
明白啦，谢谢大佬
