### ISSUE TITLE
如何用G2绘制既有堆积又有分组的柱状图，就像echarts这样

### ISSUE THREAD

**Issue by mrKylinZhou** [antvis/g2#1182]
[bar-stack](https://echarts.baidu.com/examples/editor.html?c=bar-stack)

**Comment by mrKylinZhou** [comment]
在gemo的adjust调整时支持部分字段使用dodge 部分字段使用 stack
像这样

adjust([{
 type: 'dodge',
 dodgeFields: ['a', 'b']
}, {
  type: 'stack',
  stackFields: ['c', 'd']
}])

**Comment by charles8xu** [comment]
@mrKylinZhou 你好，绘制既有分组柱状图又有堆积图的方法找到了吗？
