### ISSUE TITLE
G2 多个指标时多次绘制会互相影响

### ISSUE THREAD

**Issue by mrKylinZhou** [antvis/g2#1185]
需求，柱状图和折线图想要在同一个图表里面，其中折线图正常绘制，柱状图做stack调整。单独绘制都没有问题，组合绘制之后图形渲染很诡异。
下面是demo
[codepen demo](https://codepen.io/mrkylinzhou/pen/JxwLjB)

**Comment by CasbaL** [comment]
@mrKylinZhou 
你这个问题解决了没，我也遇到这个问题，找不到解决方案
