### ISSUE TITLE
点图覆盖问题

### ISSUE THREAD

**Issue by liunian** [antvis/g2#1187]
* **G2 Version**: 3.4.1
* **Platform**: Chrome 72.0.3626.109 / macOS 10.14.2

点图在重叠时，无法 hover 展示小点的 tooltip，即使已对数据做来排序，把半径小的排在前面。

## 复现步骤

1. 访问官方 demo [带气泡的地图](https://antv.alipay.com/zh-cn/g2/3.x/demo/map/bubble-map.html)
2. 在 **transform map 后**再添加排序的 transform
```js
userData.transform({
  type: 'sort-by',
  fields: ['deaths'],
  order: 'ASC'
});
```
3. 图表 hover 图表中重叠的部分，观察 tooltip 的信息

## 希望结果

在不完全重叠的点中，hover 到小点中能展示小点的信息而不是最大点的信息。

## 实际结果

展示的是最大点的信息

**Comment by zongwenjian** [comment]
问题+1，大的气泡会覆盖在小的上面，如果完全覆盖的化，小气泡就永远没有办法展示tooltips

**Comment by hustcc** [comment]
@liunian @zongwenjian 对于这种大气泡遮挡小气泡的情况，没有非常完美的解决办法。

@liunian 你这边使用数据排序的方式是一个不错的方式，理论上是可行的，但是因为内部数据处理之后，可能数据顺序和渲染顺序有变。我们正在高速迭代 4.0 版本，会将散点图的这个问题考虑进去，感谢你的思路以及反馈。
