### ISSUE TITLE
官方热力图示例 label无法展示

### ISSUE THREAD

**Issue by orangeyyy** [antvis/g2#1192]
* **G2 Version**:
3.4.1
* **Platform**:
mac
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/19667299/53309688-2ff82000-38e4-11e9-9664-e9e6cea3e7f9.png)

* **CodePen Link**:

**Comment by leungwensen** [comment]
3.5.0-beta.3 已修复
