### ISSUE TITLE
关于浏览器的引入

### ISSUE THREAD

**Issue by LyShine** [antvis/g2#1193]
能不能github提供一个检出版本给下载, 或者一个在线地址?  想试用一下找文件找了半天没找到, 必须还要下载源码自己打包.

**Comment by LyShine** [comment]
官网提供的下载使用按钮是跳到首页, 文档中也没有给出在线地址

**Comment by aa1011372655** [comment]
官网的例子中给出了直接引入的方式：
https://gw.alipayobjects.com/os/antv/pkg/_antv.g2-3.4.1/dist/g2.min.js
可以直接查看示例，如：https://antv.alipay.com/zh-cn/g2/3.x/demo/line/basic.html

**Comment by LyShine** [comment]
> 官网的例子中给出了直接引入的方式：
> https://gw.alipayobjects.com/os/antv/pkg/_antv.g2-3.4.1/dist/g2.min.js
> 可以直接查看示例，如：https://antv.alipay.com/zh-cn/g2/3.x/demo/line/basic.html

谢谢, 已解决. 但是仍然建议能把文件放在一个明显的位置

**Comment by leungwensen** [comment]
多谢建议，官方文档已经补充链接

https://www.yuque.com/antv/g2-docs/get-started
