### ISSUE TITLE
legend在data传入&lt;无法正常触发

### ISSUE THREAD

**Issue by fangfangchen** [antvis/g2#1196]
* **G2 Version**:
version 3.2.7

* **Platform**:
MAC

* **Mini Showcase(like screenshots)**:
  * 1-1
![image](https://user-images.githubusercontent.com/7280294/53475792-d5112500-3aab-11e9-95a2-e20549562694.png)
  * 1-2
![image](https://user-images.githubusercontent.com/7280294/53475811-e0645080-3aab-11e9-8955-bc860e043705.png)
  * 2-1
![image](https://user-images.githubusercontent.com/7280294/53477628-0a1f7680-3ab0-11e9-8185-db45a5a6d8c5.png)

* **CodePen Link**:
  * 1-1
https://codepen.io/fangfangchen/pen/GeJRzZ?editors=1010
  * 2-1
https://codepen.io/fangfangchen/pen/LaVVrQ?editors=1010

1. 在环图中，传入的data项中包含`&lt;`会导致legned无法正常点击切换状态。

```js
// 数据
var data = [
    {level: "Skin age-Actual age<=2", count: 9},
    {level: "2&lt;Skin age-Actual age<=8", count: 6},
    {level: "Skin age-Actual age>8", count: 4}
]
```

2. 如果直接不转义传的话，`2<Skin age-Actual age<=8`会导致被解析为标签如下👇，
```html
<span class="g2-legend-text">2<skin age-actual="" age="" <="8</span"></skin></span>
```

```js
// 数据
var data = [
    {level: "Skin age-Actual age<=2", count: 9},
    {level: "2<Skin age-Actual age<=8", count: 6},
    {level: "Skin age-Actual age>8", count: 4}
]
```

期待回复

**Comment by aa1011372655** [comment]
同学你好，暂时可以通过这种方式解决：
1. 传入的data中都直接使用<>
2. 在legend配置中增加格式化函数
```
  formatter: (val) => {
    return val.replace(/\</g, '&lt;').replace(/\>/g, '&gt;');
  }
```
