### ISSUE TITLE
Error: Invalid Date in fecha.format 

### ISSUE THREAD

**Issue by luckhpy** [antvis/g2#1201]
通过错误日志收集到错误信息：Error: Invalid Date in fecha.format 

对应的错误信息UA是：
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1

暂时收集到的信息就这么多，不知道什么原因可能会导致Invalid Date in fecha.format 的错误！

**Comment by leungwensen** [comment]
请提供能复现的 codepen 链接，参考新建 issue 时的提示

**Comment by heiniuhaha** [comment]
已修复，查看以下Demo
bizcharts@3.x https://bizcharts.net/product/bizcharts/demo/525
bizcharts@4.x https://bizcharts.net/product/BizCharts4/demo/524
