### ISSUE TITLE
自定义legend.marker, 鼠标交互问题

### ISSUE THREAD

**Issue by qingxiao** [antvis/g2#1206]
https://github.com/antvis/g2/issues/1202 ,使用其他方式解决自定义legend的时候，遇到如下问题

- 使用该demo中代码 https://antv.alipay.com/zh-cn/g2/3.x/demo/column/column11.html，
 
- 代码：https://codepen.io/anon/pen/JzWogJ （主要代码在js块部分）， 添加legend中的marker为自定义函数，将部分图例前的图标进行差异处理

- 右侧图例部分开始显示正常

<img width="300" src="https://user-images.githubusercontent.com/3422905/53936188-fc877380-40e3-11e9-85c0-619b036b62ac.png"/>

- 当鼠标hover或者点击后
<img width="300" src="https://user-images.githubusercontent.com/3422905/53936236-2b9de500-40e4-11e9-9ed0-953d1c14c873.png"/>

**Comment by dengfuping** [comment]
@qingxiao g2 现在应该还不支持多种 legend-marker 类型。
