### ISSUE TITLE
数据为空时alias失效

### ISSUE THREAD

**Issue by ssfxz** [antvis/g2#1208]
数据集为空时，scale里配置的alias，体现在轴名称上就是显示了原始的字段名而非别名，
在有数据时正常

![image](https://user-images.githubusercontent.com/8744196/54016286-5445dd80-41bd-11e9-8821-896d77429674.png)

codepen: https://codepen.io/ssfxz/pen/PLmjbo

**Comment by kingecg** [comment]
同样碰到该问题，mark

**Comment by kingecg** [comment]
不仅仅是alias失效。数据类型为time的mask结果不对。mask: 'HH:mm:ss', 没有数据时应该不显示任何文字，但是实际上显示了一个值‘08:00:00’
