### ISSUE TITLE
纵轴滑块组件

### ISSUE THREAD

**Issue by fanlide** [antvis/g2#1211]
看示例与文档中都未提到纵轴的滑块实现，请问如何实现纵轴的滑块组件？谢谢

**Comment by hustcc** [comment]
slider interaction 配置中增加 `layout: 'vertical'` 的配置。

**Comment by Jeannie820** [comment]
4.0支持配置纵轴滑块了嘛？

**Comment by net027** [comment]
这个示例，如何用滑块滑动日期，
[https://g2.antv.vision/zh/examples/bar/basic#time-bar](url)
```javascript
......
// 加上滑块，只能滑动X轴的数据
chart.option('slider',{
  start:0.3,
  end:0.6
});

chart.render();
```
期待 v4.x，滑块支持纵轴，图表支持滚动条
