### ISSUE TITLE
label使用html模式渲染时，repaint、render没有销毁

### ISSUE THREAD

**Issue by qiaolei1973** [antvis/g2#1213]
G2 Version: 3.4.10
Platform:
Mini Showcase(like screenshots):
![radar](https://user-images.githubusercontent.com/20394320/54253344-97bb9580-4589-11e9-9cd3-30f6bb5594d2.jpg)
CodePen Link: https://riddle.alibaba-inc.com/riddles/80596d7f

**Comment by dxq613** [comment]
看了下 repaint 的时候文本内容销毁了，不过容器没有销毁

```js
![image](https://user-images.githubusercontent.com/1264678/59677181-dd78a180-91fb-11e9-8870-10de38b159ec.png)

```

**Comment by feijuncheng** [comment]
点击事件好像也没有抛出
