### ISSUE TITLE
venn图active事件设置为true交集部分被覆盖；tooltip显示不准确

### ISSUE THREAD

**Issue by Ma5k** [antvis/g2#1214]
* **G2 Version**:3.4.1
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:active代码：https://codepen.io/anon/pen/pYpzaV     
                               tooltip代码：https://codepen.io/anon/pen/EMoYRJ

韦恩图的active事件开启后激活显示效果只在单个集合有效，交集部分会被单个集合覆盖显示不出hover的效果

![venn](https://user-images.githubusercontent.com/24477079/54259026-651c9780-459f-11e9-8e16-d5aebbff74af.gif)

tooltip显示问题：如这里鼠标放在c区域却显示ab

![venn](https://user-images.githubusercontent.com/24477079/54273125-2b0fbd80-45c0-11e9-830e-d950a4691315.png)

**Comment by Ma5k** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/demo/other/venn.html

**Comment by dxq613** [comment]
venn 图把 active 设置成 false 就不会遮挡了，不过这个图本来就是生硬的加上去的，后面的版本应该还会拆出去，一点不符合图形语法。
