### ISSUE TITLE
通过dataView的transform改变数据和直接通过source改变数据引起的动画行为不一致

### ISSUE THREAD

**Issue by kingecg** [antvis/g2#1216]
filterCallback = (row) => {
        return row.time >= this.timeCurrent.getTime() && row.time <= Math.min(this.timeCurrent.getTime() + this.timeRange, this.timeEnd.getTime())
   }
通过filter transform过滤数据和直接把过滤结果数组通过dataView.source()更新的动画不一致

* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by kingecg** [comment]
该问题的核心在于，直接通过dataview的source方法改变数据通过改变dataset的状态引发dataview重新执行transform流程导致的结果不一样。
直接通过dataview的source方法改变数据，不会引发 Geom的动画
通过改变dataset的状态引发dataview重新执行transform流程，会引起Geom执行enter和leave动画。
如果把Geom的animate duration设置为0，则两种方式的效果一样

**Comment by leungwensen** [comment]
写个 codepen

**Comment by kingecg** [comment]
code pen
[https://codepen.io/kingecg/project/editor/AJRvnP#](https://codepen.io/kingecg/project/editor/AJRvnP#)
虽然无法重现，但是这个动画挺魔性的。
我的本意是通过改变起点时间来实现曲线向左平移。但是现在的动画是抖动加平移。

**Comment by leungwensen** [comment]
左移是 path clip 的做法，目前 g2 没有内置。你把动画关掉的话，和这个是最接近的。

**Comment by luckyyyyy** [comment]
> 左移是 path clip 的做法，目前 g2 没有内置。你把动画关掉的话，和这个是最接近的。

遇到同样的问题 有计划时间支持吗@leungwensen
