### ISSUE TITLE
G2发送bi.do请求，在增加了G2.track(false)和更新到3.4.10后仍然发送该请求

### ISSUE THREAD

**Issue by 734976581** [antvis/g2#1217]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by 734976581** [comment]
这个是不是可以提供一个解决方案，已经设置了不调用，仍然出现这个接口

**Comment by dxq613** [comment]
https://www.yuque.com/antv/g2-docs/api-g2#6v1pxn

老版本可以通过方法关闭，最新版本已经去掉。谢谢。

**Comment by leungwensen** [comment]
你检查一下是不是存在两个以上的版本。新版代码都删掉了，不可能发的
