### ISSUE TITLE
气泡图，同一个圈内点击气泡 getSnapRecords，获取数据不一致

### ISSUE THREAD

**Issue by Leannechn** [antvis/g2#1219]
* **G2 3.4.10**:
如题
![image](https://user-images.githubusercontent.com/6812138/54404910-e4c97400-470f-11e9-9418-28a686903ef0.png)
https://codepen.io/leanneCC/pen/LadYQV?editors=1111

**Comment by Leannechn** [comment]
ev.data._origin 这个值是稳定的。和这个API是什么关系？

**Comment by dxq613** [comment]
这个函数的含义是获取到最近的数据的信息，在气泡图下，有时候大气泡会覆盖小气泡，终以点击拾取到的图形为主。而 这个函数的意义在于可以获取到离鼠标最近的小气泡。
