### ISSUE TITLE
横坐标type是timeCat时，横坐标第一个值是0的时候，会变成当前时间

### ISSUE THREAD

**Issue by AlwaysSkylll** [antvis/g2#122]
@leungwensen  横坐标type是timeCat时，横坐标第一个值是0的时候，会变成当前时间，而且还会鼠标hover，数据还会实时更新 @lifesinger

**Comment by AlwaysSkylll** [comment]
强制第一个数据为'00:00' 还是一样的结果，显示了当前时间的分秒

**Comment by AlwaysSkylll** [comment]
var chartData = {
        0: 20,
        10: 20,
        20: 20,
        30: 20,
        40: 20,
        50: 20,
        60: 20,
        70: 20,
        80: 20,
        90: 20,
        100: 20,
        110: 20,
        120: 20,
        130: 20,
        140: 20,
        150: 20,
        160: 20,
        170: 20,
        180: 20,
        190: 20,
        200: 20,
        210: 20,
      }
      for (var i in chartData) {
        flowDayData.push({
          date: i * 1000,
          times: parseInt(chartData[i])
        });
      }

flowDayData作为数据元

**Comment by AlwaysSkylll** [comment]
![image](https://cloud.githubusercontent.com/assets/13064486/25839138/fe782f82-34c8-11e7-82a0-5f2806ebc74d.png)

**Comment by leungwensen** [comment]
@AlwaysSkylll 已经定位问题，多谢反馈！修复发布之后我回复你

**Comment by leungwensen** [comment]
@AlwaysSkylll 下周二会发一个新的小版本，更新之后就修复啦。

**Comment by AlwaysSkylll** [comment]
好的

**Comment by AlwaysSkylll** [comment]
提bug有没有奖励啊？考虑一下还是把源代码放出来吧，相信开源的力量，帮你们review一下代码。

**Comment by leungwensen** [comment]
@AlwaysSkylll 开源在排期中了，等我们准备好会开源的。这个bug已经修复啦，我关issue了。
