### ISSUE TITLE
开启Nice时 - Scales 计算有误

### ISSUE THREAD

**Issue by iNahooNya** [antvis/g2#1220]
* `@antv/g2@3.4.10`
* [Codepen](https://codepen.io/iNahoo/pen/MxQbNB)
目前这个bug已经在 `@antv/scale@0.1.1` 中修复
但是 `@antv/g2` 的 build 产物中依然使用旧版 `@antv/scale`，bug依然存在。

**Comment by leungwensen** [comment]
可以使用 3.5.0-beta.5 , 这个构建产物的依赖项是最新的

**Comment by zhoujiamin** [comment]
升级后，仍然有问题。
![image](https://user-images.githubusercontent.com/16118305/54428466-896fa400-4758-11e9-80b0-b74c04107317.png)
![image](https://user-images.githubusercontent.com/16118305/54428480-97bdc000-4758-11e9-9145-d5c4977f50ca.png)

**Comment by leungwensen** [comment]
3.5.2
