### ISSUE TITLE
堆叠图 ticks 设置无效

### ISSUE THREAD

**Issue by aprilandjan** [antvis/g2#1222]
* **G2 Version**: 3.4.1
* **CodePen Link**: <https://codepen.io/anon/pen/XGENEZ>

堆叠图直接设置 ticks 无效；但是当同时设置了 max 且 max 要大于数据的实际 y 轴最大值时, ticks 又生效了。

参见 https://github.com/alibaba/BizCharts/issues/755

**Comment by dxq613** [comment]
看起来是数据中的最大值大于 ticks 中设置的最大值时，就按照实际的最大值进行计算了，如果这时候设置 [0, 500] 是生效的，我看看怎么修改好一些。
应该是如果 用户设置的 ticks 后，不再走 nice: true 的逻辑。

**Comment by hustcc** [comment]
目前排查的问题是：scale.change 的时候会自动清空用户配置的 ticks，暂时没有特别优美的修复方式。

@aprilandjan 在你的场景中，暂时通过数据取得最大值临时满足你自己的需求吧，后面我们在 4.0 中处理并解决这个问题。
