### ISSUE TITLE
chart 没有开放mouseleave事件！

### ISSUE THREAD

**Issue by kingecg** [antvis/g2#1224]
chart 没有开放mouseleave事件！
mouseleave事件在chart/controller/event.js的onOut方法处理。
该方法只在很有限的条件下发出plotleave事件。其他情况下吃掉了mouseleave事件。

* **G2 Version**:3.4.10
* **Platform**: all
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by hustcc** [comment]
plotleave 是只有在 plotRange 范围内触发。
