### ISSUE TITLE
关于兼容性的文档建议

### ISSUE THREAD

**Issue by luocong2016** [antvis/g2#1226]
设计文档中没有说明版本的兼容性，包括兼容到哪个浏览器版本，手机端的系统及版本。在低端版本中是否IE，SVG 会内容溢出或高占用。希望能在文档中写入。

**Comment by hustcc** [comment]
@luocong2016 很好的反馈，我们现在高速迭代 4.0 版本，我们会在 4.0 版本中增加这部分文档，感谢你的反馈。

**Comment by quicklearning123** [comment]
2021了，在哪里可以看到兼容性文档说明呢？
