### ISSUE TITLE
当图表过小/tooltip过大的情况下，hover时tooltip会闪烁

### ISSUE THREAD

**Issue by ssfxz** [antvis/g2#1229]
https://riddle.alibaba-inc.com/riddles/8564e730

![1](https://user-images.githubusercontent.com/8744196/54670130-e8089980-4b2d-11e9-9dcf-c69fe35af407.gif)

<img width="472" alt="Image" src="https://user-images.githubusercontent.com/8744196/54669990-9e1fb380-4b2d-11e9-9b03-e472baabc729.png">
如图，当指针在红框范围内时就会触发该问题

**Comment by Esorakouki** [comment]
在htmlContent中定义tooltip构成时，最外层div加上class"g2-tooltip"可以解决。后续会在文档中补充说明。
