### ISSUE TITLE
自定义柱状Shape: 如何同时包含圆角和方角？

### ISSUE THREAD

**Issue by chclock** [antvis/g2#123]
默认的柱状图是四个方角，示例里显示了四个圆角的自定义Shape的Demo。
我现在需要实现上面2个圆角，地下2个方角的柱状图，请问如何自定义Shape?

**Comment by dxq613** [comment]
参考这个 demo http://antv.alipay.com/g2/demo/19-creations/rounded-stacked-bar.html

**Comment by chclock** [comment]
谢谢, 提供的demo解决了我的要求。

**Comment by lixingdecai** [comment]
@dxq613 demo的链接打不开了，help

**Comment by leungwensen** [comment]
@lixingdecai https://antv.alipay.com/zh-cn/g2/3.x/demo/other/rounded-stacked-column-chart.html

**Comment by lixingdecai** [comment]
@leungwensen 3q。
发现 https://antv.alipay.com/zh-cn/g2/3.x/tutorial/customize-shape.html
+ 
https://antv.alipay.com/zh-cn/vis/blog/make-rounded-column-chart.html#_%E5%9C%86%E8%A7%92%E6%9F%B1%E7%8A%B6%E5%9B%BE
就很详细了。
