### ISSUE TITLE
配置 regionfilter ，柱子一般大小颜色不生效。

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#1240]
https://codepen.io/anon/pen/oVRJaz
![image](https://user-images.githubusercontent.com/3838676/55067016-e56fec00-50b9-11e9-8176-44ab695ddb11.png)

**Comment by dengfuping** [comment]
- `regionfilter` 在柱状图下有问题

**Comment by dxq613** [comment]
这个问题不算是 bug，因为'1951' 就是柱子的中间，目前 guide 可以通过索引值定位，例如 0, 1,2,3 ，可以用 -0.5， 3.5 这类的值来实现这个效果，本质上分组柱状图也是这么实现的，不过就是不太好理解，除非我们后续再 guide 上加入 offset 的概念。

**Comment by dxq613** [comment]
![image](https://user-images.githubusercontent.com/1264678/59673834-90dd9800-91f4-11e9-9c52-c5d9617252ac.png)
