### ISSUE TITLE
[bug]颜色突变，通过csv文件，没有tooltip，无效！当前版本3.5.2

### ISSUE THREAD

**Issue by steady-join** [antvis/g2#1241]
![image](https://user-images.githubusercontent.com/29935583/55124023-c320b180-513f-11e9-9dbb-50f38c7d5c48.png)
------以下代码
import React, { Component } from 'react';
import DataSet from '@antv/data-set';
import G2 from '@antv/g2';
import Axios from 'axios';

class Charts extends Component {
  componentDidMount() {
    const ds = new DataSet({
      state: {
        currentState: 'WY',
      },
    });

    Axios.get('http://localhost:8080/csv').then(res => {
      const csv = res.data;
      const dvForAll = ds
        .createView('populationByAge', {
          watchingStates: [], // 用空数组，使得这个实例不监听 state 变化
        }) // 在 DataSet 实例下创建名为 populationByAge 的数据视图
        .source(csv, {
          type: 'csv', // 使用 CSV 类型的 Connector 装载 data
        });

      dvForAll.transform({
        type: 'fold',
        fields: ['小于5岁', '5至13岁', '14至17岁'],
        key: 'age',
        value: 'population',
      });

      const c1 = new G2.Chart({
        id: 'c1',
        forceFit: true,
        height: 400,
      });

      c1.source(dvForAll);

      c1.intervalDodge()
        .position('state*population')
        .color('age')
        .select(true, {
          mode: 'single',
          style: {
            stroke: 'red',
            strokeWidth: 5,
          },
        })
        .tooltip('population');

      c1.on('tooltip:change', function(evt) {
        console.log('tooltip:change ', evt);
        const items = evt.items || [];
        if (items[0]) {
          ds.setState('currentState', items[0].title);
        }
      });

      c1.render();

      const data = [
        { month: '一月', temperature: 5, city: '北京' },
        { month: '二月', temperature: 10, city: '北京' },
        { month: '一月', temperature: 8, city: '南京' },
        { month: '二月', temperature: 14, city: '南京' },
      ];
      const chart = new G2.Chart({
        id: 'c2',
        width: 400,
        height: 200,
      });
      chart.source(data);
      chart
        .interval()
        .position('month*temperature')
        .color('city', ['#1890FF', '#2FC25B']);
      chart.render();
    });
  }

  render() {
    return (
      <div>
        <div id="c1" />
        <div id="c2" />
      </div>
    );
  }
}

export default Charts;

**Comment by leungwensen** [comment]
请提供可复现问题的 codepen 链接

**Comment by steady-join** [comment]
@leungwensen 没有复现链接，有一个本地demo，跑一下




[ts-scaffold-charts.zip](https://github.com/antvis/g2/files/3015985/ts-scaffold-charts.zip)

**Comment by leungwensen** [comment]
因无法提供重现链接，并且提供的代码包也无法正确运行，关闭 issue

**Comment by steady-join** [comment]
@leungwensen 你可能没有跑mock服务，本地yarn start  和 yarn run mock

**Comment by joriewong** [comment]
@steady-join 你的mock服务需要[nodemon](https://www.npmjs.com/package/nodemon)依赖

**Comment by joriewong** [comment]
@steady-join `c1.intervalDodge().position('state*population')`State的首字母大写！！！
![image](https://user-images.githubusercontent.com/11408040/55135392-874d1280-5166-11e9-8649-f224639576b2.png)

**Comment by joriewong** [comment]
@leungwensen 已验证，来自issue作者的typo🤦‍♂️

**Comment by steady-join** [comment]
@joriewong 是的，我已发现了这个问题，但是产生出另外的问题，y轴的顺序似乎不对

**Comment by joriewong** [comment]
@steady-join 检查一下原始数据和数据处理过程吧

**Comment by steady-join** [comment]
@joriewong 谢谢您的帮助，需要手动进行排序。
