### ISSUE TITLE
支持像F2那样的饼图连接线

### ISSUE THREAD

**Issue by AKM36** [antvis/g2#1242]
G2 3.4.10

G2里面的饼图label的链接线不管多长都是直线，并且不会根据画布大小拐弯，太长就直接超出画布了，希望能像F2一样将链接线提供折线的功能

![下载](https://user-images.githubusercontent.com/36810290/55153491-84194d00-518d-11e9-80f5-f8c7438609fb.png)

**Comment by dengfuping** [comment]
可以先参考 https://antv.alipay.com/zh-cn/g2/3.x/demo/pie/pie8.html 这个例子自行实现

**Comment by AKM36** [comment]
多谢1
