### ISSUE TITLE
连续图例和分类图例不能合并吗？

### ISSUE THREAD

**Issue by steady-join** [antvis/g2#1244]
进行多Y轴配置时，一条采用分组柱状图，一条折线图，图例似乎只显示了分类图例，而缺失了连续图例，并没有看见这方面的文档例子，G2支持吗？

**Comment by aa1011372655** [comment]
麻烦按照issue模板提交问题，请提供复现代码，这样更容易回答您的问题，非常感谢

**Comment by dxq613** [comment]
不支持这种特性。
