### ISSUE TITLE
在k线图中，如何动态让折线与k线的y轴区间对齐?

### ISSUE THREAD

**Issue by lonelyleaf** [antvis/g2#1245]
* **G2 Version**: 3.5.2
* **Platform**: chrome
* **Mini Showcase(like screenshots)**: 
* **CodePen Link**: https://github.com/lonelyleaf/andv-demo/tree/y-axis-demo

由于k线的scale是range，而折线是单点，在同一幅图上绘制时会可能出现y轴区间无法对齐的情况（如下图所示）。我需要动态调整时间，所以不希望写死各个scale的min和max。

但我使用dataset时发现dataset与dataview中似乎也缺少能pick出单点（类似max或mix这类）的函数。

能能不能添加功能让多个scale的区间能自动对齐？或者能在view中添加能pick出单点到dataset的
函数，让用户能根据结构动态调整scale的max和min值？

![y轴对齐](https://user-images.githubusercontent.com/9879800/55466210-54f15880-5631-11e9-98d7-24d2d51ab0ae.png)
![y轴无法对齐](https://user-images.githubusercontent.com/9879800/55466230-5c186680-5631-11e9-8eeb-e79a141b5b68.png)

**Comment by aa1011372655** [comment]
如果你的两个view的scale键名相同，比如都叫做range，在设置了sync为true情况下会自动对齐，我看你的github已经处理了，麻烦关闭一下，非常感谢

**Comment by lonelyleaf** [comment]
sync是无效的，我demo你自己跑下就知道了

**Comment by lonelyleaf** [comment]
@aa1011372655 没有办法用同一个scale键名，因为k线的range是一个数组，而折线是单点，类型就不匹配。

**Comment by dxq613** [comment]
类型会检测数组中的值的，都会按照 linear 的，两个scale 都设置相同的 min,max 就能解决了。

**Comment by lonelyleaf** [comment]
> 类型会检测数组中的值的，都会按照 linear 的，两个scale 都设置相同的 min,max 就能解决了。

@dxq613 谢谢回复，但这样我要动态改变时间范围时，调整max和min就太麻烦了。我已经换echart了，就没有这个问题
