### ISSUE TITLE
[label]关于右侧label显示的数字可以右对齐吗？和下面的展示的图一样？求解决方法

### ISSUE THREAD

**Issue by fengyelan** [antvis/g2#1246]
![屏幕快照 2019-04-04 上午10 46 02](https://user-images.githubusercontent.com/8373010/55526292-1b6b2c80-56c7-11e9-90bd-88ddd5e1f111.png)

**Comment by aa1011372655** [comment]
提供三个思路供实现：
1. 使用guide.text直接展示
2. 直接使用label的htmlTemplate自定义实现
3. 声明一个自定义interval，使其顶点最高透明度为0，之后使用这个自定义的interval的label展示

期望提issue按照issue的提示规范提交，非常感谢

**Comment by fengyelan** [comment]
非常感谢
