### ISSUE TITLE
alias 为 id 时 axis title 有问题

### ISSUE THREAD

**Issue by BlackGanglion** [antvis/g2#1249]
* **G2 Version**: 3.5.2
* **Platform**: 
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

https://riddle.alibaba-inc.com/riddles/f0db54ee，别名设置为 “id” 无效，设置为 “idd” 就有效了

![image](https://user-images.githubusercontent.com/9314735/55694441-cdb43400-59e6-11e9-97c8-80a9e1aa59dd.png)

**Comment by army8735** [comment]
这是g2的，看成f2了……

**Comment by dxq613** [comment]
看了下应该是 padding: 'auto' 导致的，不但是 'id' ，所有 <= 2 个字符的情况下，padding: 'auto' 都显示不出来。
改成 svg 的版本后，发现已经绘制了，但是位置在画布外面，显示不出来。

**Comment by BlackGanglion** [comment]
@dxq613 那比较hack的解法就是当轴标题 <= 2 个字符的情况下，手动加一点padding

**Comment by dxq613** [comment]
我看看什么地方的问题，修复一下
