### ISSUE TITLE
g2-react 嵌套饼图在改变state后，不显示外圈饼图

### ISSUE THREAD

**Issue by dong894** [antvis/g2#125]
实在不好意思，由于g2-react那边好像没有人回答，只能到这边来问了

Version:
g2-react 1.2.0
g2 2.3.1

Link to minimal reproduction:
https://codepen.io/dong894/pen/XREJPR

Environment:
win10
chrome 58.0.3029.96 (64-bit)

Step to reproduce:
初始的state中data是空数组，点击refresh按钮，改变state

What is expected?
和官方demo一样能够正常显示内圈和外圈的饼图
![正确](http://opy0dgfaa.bkt.clouddn.com/8E8A3997-53F4-4184-8E71-8B6A65A69DBF.png)

What is actually happening?
内圈饼图显示出来了，但是外圈饼图不显示
![错误](http://opy0dgfaa.bkt.clouddn.com/0A1224AA-C9F1-4022-B032-915782463B74.png)

**Comment by leungwensen** [comment]
非常抱歉，应该及时在g2-react上回复的。

现在看来的问题在于：g2-react处理update相关的逻辑时有些问题。目前有个比较快的解决办法：你给Chart实例加一个unique的key，每次setState的时候顺便更新这个key，这样就能保证每次都画出你想要的图表了。当然这种方法比较hack，会每次销毁掉Chart实例重建。我们再看看在g2-react内部怎样比较好地解决这个问题。

http://codepen.io/leungwensen/pen/JNaZYG

**Comment by dong894** [comment]
谢谢
