### ISSUE TITLE
bar out of axisX range when both x and y axis are numbers

### ISSUE THREAD

**Issue by troy351** [antvis/g2#1251]
* **G2 Version**: 3.5.2
* **Platform**: Win 10 Chrome 73
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/8372385/55704082-edab1e00-5a0d-11e9-8ab4-06d30c6549b6.png)

* **CodePen Link**: https://jsfiddle.net/ozp45xs9/1/

**Comment by dxq613** [comment]
目前内置的逻辑是分类轴两边留白，如果你的 x 轴是连续的，可以在 scale 上设置 range，

```js
chart.scale('xfield', {
  range: [0.1, 0.9] // 这个范围可以动态计算， 比如[ 1 / (count * 2), 1- 1 / (count * 2)]
});
```
