### ISSUE TITLE
axis的label在type种类为1的时候不显示

### ISSUE THREAD

**Issue by tigerlove** [antvis/g2#1253]
* **G2 Version**: 2-3.4.1
* **Platform**: chrome
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/9425839/55707281-cc4e3000-5a15-11e9-913d-3fc48ac8ae9c.png)

* **CodePen [https://codepen.io/corleonelu/pen/vPgqdL](https://codepen.io/corleonelu/pen/vPgqdL)

当数据的type总数为1种的时候，不显示label，当数据type多于1种的时候显示正确
![image](https://user-images.githubusercontent.com/9425839/55707519-5c8c7500-5a16-11e9-9e9f-0494f1eb8646.png)

**Comment by xiaoweibaniu** [comment]
你好，我在使用中也遇到了该问题。麻烦问下你这边有没有找到解决方案

**Comment by dxq613** [comment]
我试了最新版本没有这个问题：
![image](https://user-images.githubusercontent.com/1264678/59482912-7ffff000-8e9d-11e9-985e-e462c17f9c91.png)
