### ISSUE TITLE
缺醒值显示问题

### ISSUE THREAD

**Issue by leehave** [antvis/g2#1256]
Echarts饼图所有值为0时是这样的
![image](https://user-images.githubusercontent.com/16717693/55766722-72e31100-5aa8-11e9-8d05-b44ddfebee46.png)
G2所有值为0时显示的是这样的
![image](https://user-images.githubusercontent.com/16717693/55766759-9e65fb80-5aa8-11e9-8911-7551d9d587be.png)
请问有没有什么方法去处理下缺醒值的问题

**Comment by dxq613** [comment]
全 0 G2 不会显示的，这是策略问题。
