### ISSUE TITLE
使用渐变色，l 后面传入角度，无效

### ISSUE THREAD

**Issue by coin17** [antvis/g2#1257]
API：

> https://www.yuque.com/antv/g2-docs/api-geom#4walds

示例代码：
`

    <script>/*Fixing iframe window.innerHeight 0 issue in Safari*/document.body.clientHeight;</script>
    <script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.g2-3.5.1/dist/g2.min.js"></script>
    <script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.10.1/dist/data-set.min.js"></script>

    <script>
        var data = [[0, 0, 10], [0, 1, 19], [0, 2, 8], [0, 3, 24], [0, 4, 67], [1, 0, 92], [1, 1, 58], [1, 2, 78], [1, 3, 117], [1, 4, 48], [2, 0, 35], [2, 1, 15], [2, 2, 123], [2, 3, 64], [2, 4, 52], [3, 0, 72], [3, 1, 132], [3, 2, 114], [3, 3, 19], [3, 4, 16], [4, 0, 38], [4, 1, 5], [4, 2, 8], [4, 3, 117], [4, 4, 115], [5, 0, 88], [5, 1, 32], [5, 2, 12], [5, 3, 6], [5, 4, 120], [6, 0, 13], [6, 1, 44], [6, 2, 88], [6, 3, 98], [6, 4, 96], [7, 0, 31], [7, 1, 1], [7, 2, 82], [7, 3, 32], [7, 4, 30], [8, 0, 85], [8, 1, 97], [8, 2, 123], [8, 3, 64], [8, 4, 84], [9, 0, 47], [9, 1, 114], [9, 2, 31], [9, 3, 48], [9, 4, 91]];
        var source = [];
        for (var i = 0; i < data.length; i++) {
            var item = data[i];
            var obj = {};
            obj.name = item[0];
            obj.day = item[1];
            obj.sales = item[2];
            source.push(obj);
        }
        var chart = new G2.Chart({
            container: 'mountNode',
            forceFit: true,
            height: window.innerHeight,
            padding: [20, 80, 120, 85]
        });
        chart.source(source, {
            name: {
                type: 'cat',
                values: ['Alexander', 'Marie', 'Maximilian', 'Sophia', 'Lukas', 'Maria', 'Leon', 'Anna', 'Tim', 'Laura']
            },
            day: {
                type: 'cat',
                values: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
            }
        });
        chart.axis('name', {
            tickLine: null,
            grid: {
                align: 'center',
                lineStyle: {
                    lineWidth: 1,
                    lineDash: null,
                    stroke: '#f0f0f0'
                }
            }
        });
        chart.axis('day', {
            title: null,
            grid: {
                align: 'center',
                lineStyle: {
                    lineWidth: 1,
                    lineDash: null,
                    stroke: '#f0f0f0'
                },
                showFirstLine: true
            }
        });

        chart.polygon().position('name*day').color('sales', 'l(270) 0:#FF0000 0.5:#00FF00 1:#0000FF');//无效
        //chart.polygon().position('name*day').color('sales', '#BAE7FF-#1890FF-#0050B3'); //有效
        //chart.polygon().position('name*day').color('sales', 'red-blue'); //有效
        chart.render();
    </script>

`
请问是不支持该写法了？

**Comment by leungwensen** [comment]
老版本应该也不支持的，应该是文档描述的问题，我们更正下。

这种语法的渐变色只支持在 style 里指定，或者直接指定，不支持数据映射。也就是这么写是可以的：

```js
.color('l(0) 0:#ffffff 0.5:#7ec2f3 1:#1890ff');
```
