### ISSUE TITLE
使用regionFilter时 折线图上的点颜色渲染有问题

### ISSUE THREAD

**Issue by huangchaofei** [antvis/g2#1258]
* **G2 Version**:3.4.10
* **Platform**:chrome72.0.3626.119
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/25143078/55863962-25e96280-5bae-11e9-8dcf-97da10dc18fb.png)
这是我的代码
curveChart.guide().regionFilter({
          top: true,
          start: ['min', Number(this.curveMax)+1],
          end: ['max', Number(this.curveMax)*Number(this.curveWarning)],
          color: '#fe9f11'
        });
为什么最后一个点会一半是黄一半是绿呢

**Comment by huangchaofei** [comment]
是min和max的范围没有把最左边的点和最右面的点包括进去,是bug吗

**Comment by leungwensen** [comment]
不用 min / max，用 start 和 end。

min / max 代表数据的最大最小值，start 和 end 代表画布的起始点和终止点

**Comment by huangchaofei** [comment]
我在官网调试例子还是会有问题@leungwensen
  chart.guide().regionFilter({
	top: true,
        start: ['start', 'start'],
        end: ['end', 'end'],
        color: '#fe9f11'
   })
![image](https://user-images.githubusercontent.com/25143078/55940394-9ce82f00-5c72-11e9-8259-ef8aaeeba419.png)
是哪里写的不对吗 最左边的和最右边的一个点还是有问题

**Comment by huangchaofei** [comment]
再配合调一个range 就可以了 不过不知道这样是不是合适的
range: [0.01, 0.99]

**Comment by leungwensen** [comment]
调 range 说明你已经意识到是什么问题了 orz。上面那个例子，是因为那俩点的圆心就是 start 和 end 的地方，但它画的时候又有一定的半径，所以有一半没在 clip 的范围内。你对 range 这个调整就是把“数据”本身压缩到画布内一个区域内，而不是和画布对齐，可以这么搞

**Comment by huangchaofei** [comment]
好的3q
