### ISSUE TITLE
Missing part of the image when chart.downloadImage()

### ISSUE THREAD

**Issue by irvinwang** [antvis/g2#126]
Use official demo as the base, add chart.downloadImage() after chart.render()
- Pie: IE part is missing
https://antv.alipay.com/g2/demo/05-pie/pie.html
![chart 12](https://cloud.githubusercontent.com/assets/4418459/26208489/d0f0f278-3c1c-11e7-997d-99a32bce70b0.png)

- Funel: 1st part is missing
https://antv.alipay.com/g2/demo/08-funnel/funnel-compare.html
![chart 13](https://cloud.githubusercontent.com/assets/4418459/26208617/1e7a98be-3c1d-11e7-8f00-6fe3aa8d0b0b.png)

**Comment by dxq613** [comment]
you can close the animate of chart

```js
chart.animate(false);
```
