### ISSUE TITLE
render twice error when padding: 'auto'

### ISSUE THREAD

**Issue by troy351** [antvis/g2#1262]
* **G2 Version**: 3.5.3
* **Platform**: Chrome 73
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/8372385/55946637-a5933200-5c7f-11e9-9cc9-c4b4cd0e869f.png)

* **CodePen Link**: https://jsfiddle.net/7n642oex/

**Comment by paleface001** [comment]
你好，现在auto padding的计算逻辑就是render两次，render的第一次取参与padding的各组件包围盒，否则取不到。

**Comment by troy351** [comment]
我知道，但是我手动执行2次render，相当于render了4次，后2次的结果和前2次不一样

**Comment by pppppppppppp12** [comment]
@paleface001  现在还是有这个问题，应该怎么处理？图表更新需要执行render，与初始状态不一样了
