### ISSUE TITLE
鼠标悬浮于条形图的时候，guide().text写的文字在鼠标悬浮的时候怎么改变样式？

### ISSUE THREAD

**Issue by fengyelan** [antvis/g2#1263]
![7AD0C59F-1227-46AC-92CA-3C5ED771C172](https://user-images.githubusercontent.com/8373010/55956515-bac78b00-5c96-11e9-88c5-3fe412c4639d.jpg)

**Comment by fengyelan** [comment]
鼠标悬浮于条上的时候，条显示蓝色的同时，旁边的文字怎么显示蓝色？
条显示蓝色：               
 geom.color('#DBDDE0')
                    .active(true, {
                        highlight: false, 
                        style: {
                            fill: '#4477FF'
                        }
                    });

文字的代码：
                chart.guide().text({
                    top: true,
                    position: ['视频资料', 'max'],
                    content:’458‘,
                    style: {
                        fill: '#333333',
                        fontSize: 12,
                        textAlign: 'left'
                    }
                });

**Comment by dxq613** [comment]
在 style 里面加个 cursor: 'pointer'
