### ISSUE TITLE
view 中使用 regionFilter 无效

### ISSUE THREAD

**Issue by maplor** [antvis/G2#1266]
* **G2 Version**: 3.5.3
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:  https://codepen.io/anon/pen/MROXyN

在 view 中使用 regionFilter 没有有任何效果。同样的设置在 chart 中使用可以生效。
示例中第 20 行的赋值语句改为 view 就能看到效果。

**Comment by maplor** [comment]
初步排查，是 https://github.com/antvis/g2/blob/master/src/component/guide/region-filter.js#L27 这里绑定的 afterpaint 回调在 view 绘制时没有触发。所以没有效果。

**Comment by Blankeer** [comment]
+1 我也踩到这个坑了。。。。😂

**Comment by Blankeer** [comment]
另外，貌似 http://riddle.alibaba-inc.com/riddles/cdadf85e 打不开？fq 了也不行？是网络运营商问题还是？

**Comment by maplor** [comment]
> 另外，貌似 http://riddle.alibaba-inc.com/riddles/cdadf85e 打不开？fq 了也不行？是网络运营商问题还是？

不好意思，这个是内网网址。。类似 codepen 的网站。
我贴一个外网的网址： https://codepen.io/anon/pen/MROXyN

**Comment by dxq613** [comment]
这个不太好解决，在设计这个特性的时候确实没考虑 view 的场景。

**Comment by maplor** [comment]
> 这个不太好解决，在设计这个特性的时候确实没考虑 view 的场景。

只看表面的话，解法可以在 regionFilter 中绑定 afterpaint 的地方做兼容判断。有点治标不治本的意思，其它需要事件触发的场景也会有相同的问题。

**Comment by dxq613** [comment]
嗯，整个生命周期还需要梳理一下，在下一个大版本中 view 无限级嵌套这个问题可能更严重。不过这个 guide 的方案本身就够 hack了。。。

**Comment by jiayangkai** [comment]
@maplor @dxq613 项目中使用bizcharts，现在踩到这个坑了，这个问题已经考虑在新版中解决了吗？还是通过另外的途径解决？

**Comment by maplor** [comment]
> @maplor @dxq613 项目中使用bizcharts，现在踩到这个坑了，这个问题已经考虑在新版中解决了吗？还是通过另外的途径解决？

目前我还没有找到解法。。也欢迎一起来解决。初步排查的代码部分在上面有链接。
