### ISSUE TITLE
TypeScript API 缺失等问题

### ISSUE THREAD

**Issue by Blankeer** [antvis/g2#1267]
* **G2 Version**: 3.5.3
* **Platform**: chrome
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

发现很多 ts api 和文档/demo对应不上或缺失的地方，比如：
1. ChartGuide 缺失 regionFilter 方法，详见：[index.d.ts](https://github.com/antvis/g2/blob/master/src/index.d.ts#L527)、[源 js](https://github.com/antvis/g2/blob/master/src/chart/controller/guide.js#L84)
2. legend 相关api，[index.d.ts](https://github.com/antvis/g2/blob/master/src/index.d.ts#L443),[demo](https://antv.alipay.com/zh-cn/g2/3.x/demo/other/double-axes.html)
3. view.changeVisible，文档是boolean，ts为何得传string？[index.d.ts](https://github.com/antvis/g2/blob/master/src/index.d.ts#L773),[doc](https://www.yuque.com/antv/g2-docs/api-chart#_changeVisible)

还有很多这类问题，不知道是啥原因，望解答。。
谢谢。

**Comment by troy351** [comment]
因为这个文件不是官方维护的。。我已经添加并且修复了部分。#1259

**Comment by troy351** [comment]
关于legend的api文档上也没有这个用法，只有例子里有
![image](https://user-images.githubusercontent.com/8372385/56191336-c3391080-605e-11e9-987e-2f1e7b2c4a9c.png)

**Comment by paleface001** [comment]
你好，g2 4.0版本全部基于typescript，目前尚未正式发布，欢迎关注4.0的动态。
