### ISSUE TITLE
玫瑰图-限定角度范围

### ISSUE THREAD

**Issue by bmsherry** [antvis/G2#1268]
* **G2 Version**:3.5.3
* **Platform**:chrome
* **Mini Showcase(like screenshots)**:无
* **CodePen Link**:无

玫瑰图-限定角度范围  上面的柱状图如何在鼠标移入的时候高亮或者换颜色，应该如何做呢，求教

**Comment by bmsherry** [comment]
![image](https://user-images.githubusercontent.com/23392280/56269666-c13a8480-6126-11e9-9a49-a9691ea45874.png)

还有鼠标移入右边的时候 为什么tooltip出来的是最左边的数据 是否是Bug 可否修复

**Comment by dxq613** [comment]
hover 高亮加个 .active(true) 方法就好了。
```js
chart.interval().position('type*value').color('type', 'rgb(252,143,72)-rgb(255,215,135)').label('value', {
    offset: -15,
    label: {
      textAlign: 'center',
      fill: '#000'
    }
  }).active(true)
```

**Comment by dxq613** [comment]
鼠标边界的计算问题，我看看什么原因。
