### ISSUE TITLE
官网站点 demo 挂了，bug

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#1269]
demo 链接
https://antv.alipay.com/zh-cn/g2/3.x/demo/component/guide-region-filter-realtime-data.html

![image](https://user-images.githubusercontent.com/3838676/56414648-d1d13300-62bd-11e9-861c-a22749b4209b.png)

**Comment by pddpd** [comment]
已修复，如果还有问题可以继续和我探讨，这个issue关了。
