### ISSUE TITLE
关于如何在jupyter notebook中使用

### ISSUE THREAD

**Issue by szzend** [antvis/g2#1270]
jupyter notebook中可以动态引入js包并执行js代码，所以有用ipython notebook内㠌d3或echarts做交互图展示的，如下示例代码：(https://github.com/twocucao/DataScience/blob/master/project_03_dianpin/simple_stat.ipynb)
`from IPython.display import HTML
chart_header_html = """
<div id="chart" style="width:800px; height:600px;"></div>
<script>
    require.config({
         paths:{
            echarts: '//cdn.bootcss.com/echarts/3.2.3/echarts.min',
         }
    });
    require(["echarts"],function(ec){
    //使用ec作图

    });
</script>
"""
HTML(
 chart_header_html
)`
我试过可以正常使用。 但是g2不可以？？ 是根本就不能正常引入
`%%javascript
require.config({
    paths:{G2:'//gw.alipayobjects.com/os/lib/antv/g2/3.5.3/dist/g2.min',}
});
require(['g2'],function(G2){
   alert(G2) 
}); `
以上代码不运行，为什么？ 有大佬试过吗， 引入方式不对？还是不符合什么包规范

**Comment by wangjun-sh** [comment]
我按照D3.js的方式，测试成功了。

首先引入g2库：

%%javascript
require.config({
    paths: {"g2": 'https://gw.alipayobjects.com/os/lib/antv/g2/4.0.4/dist/g2.min'}
});


然后，官方的入门的柱状图：
%%javascript
(function(element) {
    require(['g2'], function(g2) {   
        var data = [
        { genre: 'Sports', sold: 275 },
        { genre: 'Strategy', sold: 115 },
        { genre: 'Action', sold: 120 },
        { genre: 'Shooter', sold: 350 },
        { genre: 'Other', sold: 150 },
      ];

      // Step 1: 创建 Chart 对象
      var chart = new g2.Chart({
        container: element.get(0), // 指定图表容器 ID
        width: 600, // 指定图表宽度
        height: 300, // 指定图表高度
      });

      // Step 2: 载入数据源
      chart.data(data);

      // Step 3：创建图形语法，绘制柱状图
      chart.interval().position('genre*sold');

      // Step 4: 渲染图表
      chart.render();
    })
})(element);

注意这里加了：
(function(element) {
    require(['g2'], function(g2) {   

且在Chart前加了g2,  不是G2。 
这里我对javascript不熟，不明所以。但是可以成功运行。

常见的线图加钉子：
%%javascript
(function(element) {
    require(['g2'], function(g2) { 
        
        
const data = [
  { year: '1991', value: 3, upper: 5.2},
  { year: '1992', value: 4, upper: 6.5 },
  { year: '1993', value: 3.5, upper: 5 },
  { year: '1994', value: 5, upper: 7 },
  { year: '1995', value: 4.9, upper: 7.8 },
  { year: '1996', value: 6, upper: 9 },
  { year: '1997', value: 7, upper: 10 },
  { year: '1998', value: 9, upper: 9.8 },
  { year: '1999', value: 13, upper: 15 },
];
        
data.forEach(function(obj) {
    obj.range = [obj.value - (obj.upper - obj.value), obj.upper];
  });
        
const chart = new g2.Chart({
  container: element.get(0),
  //autoFit: true,
  height: 500,
  width: 800
});

chart.data(data);
chart.scale({
  year: {
    range: [0, 1],
  },
  value: {
    min: 0,
    nice: true,
  },
  upper: {
      min: 0,
      nice: true,
  }
});

chart.tooltip({
  showCrosshairs: true, // 展示 Tooltip 辅助线
  shared: true,
});

chart.line().position('year*value').label('value');
//chart.point().position('year*upper').shape("square").size(5);
chart.point().position('year*value').shape("circle").size(5);
chart.interval().position('year*range').size(8).shape('tick');


chart.render();

})
})(element);

**Comment by hustcc** [comment]
@szzend @wangjun-sh  

1. 可以直接使用 [PyG2Plot](https://github.com/hustcc/PyG2Plot)，封装好的图表
2. 如果一定要用 G2，可以参考 PyG2Plot 的方式，去封装一个包，应该不难的
