### ISSUE TITLE
使用渐变色后，tooltip的marker消失了

### ISSUE THREAD

**Issue by z784324922** [antvis/G2#1271]
![image](https://user-images.githubusercontent.com/31068244/56490418-bf523600-6517-11e9-86cc-4b7b5db69aef.png)

**Comment by pddpd** [comment]
感谢反馈。问题将在最新的PR中修复。目前可以先通过下列方法解决这个问题。
```
chart.tooltip({
    useHtml: false
});
```

**Comment by simaQ** [comment]
4.0 已支持
