### ISSUE TITLE
水波图 - 自定义路径 是不是应该是空心的？

### ISSUE THREAD

**Issue by xxbld** [antvis/g2#1272]
* **G2 Version**: 最近的
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
官网demo
[水波图 - 自定义路径](https://antv.alipay.com/zh-cn/g2/3.x/demo/other/liquid-fill-path.html)
上面多了一层蓝色的覆盖，这个是bug吗？该怎么删除这个覆盖层？

**Comment by xxbld** [comment]
style({fill:null})

**Comment by Luooooooo** [comment]
4.0访问不到上面的水波图网页
