### ISSUE TITLE
ToolTip 在图表很小时无法消失

### ISSUE THREAD

**Issue by focus7eleven** [antvis/g2#1275]
* **G2 Version**: latest version
* **Platform**: macOS
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/8576839/56582587-336d0680-660a-11e9-9726-30ce1775ed52.png)

* **CodePen Link**: https://codesandbox.io/s/moq9wl9wx8

如复现链接里面的例子所示，图表很小时，当指针从 ToolTip 划出时，ToolTip 无法正常消失

**Comment by aa1011372655** [comment]
这个问题，这里先给一个暂时方案：
```
.g2-tooltip {
    pointer-events: none;
}
```

**Comment by paleface001** [comment]
补充，图表展示空间较小时也可以考虑采用mini tooltip。
参见demo: https://antv.alipay.com/zh-cn/g2/3.x/demo/other/mini1.html
