### ISSUE TITLE
demo全都打不开

### ISSUE THREAD

**Issue by kane245** [antvis/g2#1276]
![image](https://user-images.githubusercontent.com/7390396/56648188-6ddfad80-66b5-11e9-9739-39664a839f3b.png)
 
还有，官网的demo里有些引用的json在哪看

**Comment by leungwensen** [comment]
本地看 demo 请执行

```
npm i && npm run demos-web
```

官网站点在 antvis/site ，数据文件在： https://github.com/antvis/site/tree/master/theme/default/assets/data
