### ISSUE TITLE
type为precent的时候，无法重命名里面的字段

### ISSUE THREAD

**Issue by jgx13245** [antvis/g2#1277]
dv.transform({

  type: 'percent',

  field: 'sold',           // 统计销量

  dimension: 'year',       // 每年的占比

  groupBy: [ 'category' ], // 以不同产品类别为分组，每个分组内部各自统计占比

  as: 'percent'            // 结果存储在 percent 字段

});

这里我修改其中的的字段值，比如吧year,sold之类的修改为我请求回来的数据的值，就不生效了，这是为什么

**Comment by jgx13245** [comment]
1

**Comment by aa1011372655** [comment]
你好，请附上复现地址，非常感谢，这样更好定位问题

**Comment by dxq613** [comment]
看不懂描述的问题，请附加代码，好快速解决问题。
