### ISSUE TITLE
SVG render mode bug: Tooltip 飘移

### ISSUE THREAD

**Issue by Acathur** [antvis/G2#1278]
* **G2 Version**: `3.5.3`
* **Platform**: Mac
* **Mini Showcase**: 
![Screen Recording 2019-04-26 at 23 13 39](https://user-images.githubusercontent.com/4847490/56818542-661d3600-687a-11e9-908a-d9d0ee5f6bf2.gif)
* **CodePen Link**: https://codepen.io/acathur/pen/PgVqVa

    仅在svg渲染模式下存在该问题

**Comment by simaQ** [comment]
欢迎使用/升级 4.0，已解决
