### ISSUE TITLE
关于 Tooltip 自定义 title

### ISSUE THREAD

**Issue by Acathur** [antvis/g2#1279]
参考文档 https://www.yuque.com/antv/g2-docs/api-tooltip

除了使用`htmlTooltip`以外貌似没有可以直接定义 tooltip title 的方法？

注: tooltip title 需与 Scale.formatter 格式不同

**Comment by dxq613** [comment]
那就别在 scale 上设置 formatter，参考这里的实现：https://www.yuque.com/antv/g2-docs/api-tooltip#l6NRE
