### ISSUE TITLE
Styling graphs: remove padding/margin between 'bars'

### ISSUE THREAD

**Issue by mirbon** [antvis/g2#1281]
Is there a way to remove padding/margin between 'bars' in the example below?

[https://jsfiddle.net/mirbon/nuqkg1zm/3/](https://jsfiddle.net/mirbon/nuqkg1zm/3/)

Thank you.

**Comment by Leannechn** [comment]
Try to set BarSize by `.size()`
https://www.yuque.com/antv/g2-docs/api-geom#c33bc7f4
