### ISSUE TITLE
自定义图例时，无法触发hover事件

### ISSUE THREAD

**Issue by AKM36** [antvis/G2#1285]
如下图所示代码段，这个判断并不总是为true的，分组柱图时，Y轴字段名相同，并不等于图例名（图例名可能是中文而Y轴字段名可能是统一的一个英文字段）
![1557137535798](https://user-images.githubusercontent.com/36810290/57219350-6069e200-702a-11e9-9094-4e8d67b24816.jpg)

**Comment by AKM36** [comment]
G2 Version: 3.5.3
Platform: Chrome

**Comment by dxq613** [comment]
@AKM36 是否因为格式化后所以对不上？能写个 codepen 么，便于快速定位问题和修复
