### ISSUE TITLE
折线图纵坐标生成9e-11

### ISSUE THREAD

**Issue by snoopy1996** [antvis/g2#1286]
* **G2 Version**: 3.5.2
* **Platform**: node 8.9.1
* **Mini Showcase(like screenshots)**:

![image](https://user-images.githubusercontent.com/22930284/57346295-87d2c300-7180-11e9-8915-537d3c7a2b0e.png)

* **CodePen Link**:
折线图
当数据出现 180w - 190w之间的数值，且y轴 tickCount 设置为 10 的时候，就会出现问题

**Comment by dxq613** [comment]
给我一下具体的 min,max ，否则不好重现。

**Comment by ssfxz** [comment]
这个情况很可能是js浮点运算出现的问题，你临时可以通过formatter为轴标签做格式化处理来规避这个问题。
