### ISSUE TITLE
bug: 配置主题colors属性不生效

### ISSUE THREAD

**Issue by SaundersDong** [antvis/g2#1288]
主题: {
  colors: COLOR_PLATE_8,
  colors_16: COLOR_PLATE_16,
  colors_24: COLOR_PLATE_24,
  colors_pie: COLOR_PIE,
  colors_pie_16: COLOR_PIE_16,
} 这几个colors配置不生效

**Comment by paleface001** [comment]
`const  { Global } = G2; // 获取 Global 全局对象
Global.registerTheme('newTheme', {
  colors: [ 'red', 'blue', 'yellow' ]
});
 Global.setTheme('newTheme');`

可以参考一下文档：
https://www.yuque.com/antv/g2-docs/tutorial-theme
