### ISSUE TITLE
如何去掉g2 click事件的累加绑定问题，点击一次会多次请求后端

### ISSUE THREAD

**Issue by stephanieDL** [antvis/g2#1289]
我在使用g2画出柱状图的时候，需要实现点击柱状图进行新图表渲染。所以将 dateHistogramChart = new G2.Chart({
    container: 'mountNode',
    forceFit: true,
    height: 300,
    });
放在compnentDidMount中，可是在点击柱状图的时候，会出现第一次点击请求后端接口一次，第二次点击请求后端接口两次，第三次点击会请求三次以此类推。
在网上查找可能是click事件累加绑定问题，我查找文档没有找到相关解决方式，请问是否有更好的方法去解决这个问题？期待大佬解答

下面是我的代码实现：

componentDidMount() {
    dateHistogramChart = new G2.Chart({
    container: 'mountNode',
    forceFit: true,
    height: 300,
    });
  }

componentWillReceiveProps(props) {
    const {
     data
    } = props;
    if (_.isEmpty(data)|| _.isEqual(preData, data)) return;
    preData=data;
    this.dateHistogram(data);
  }

dateHistogram = (data) => {
    dateHistogramChart.off('click');
    dateHistogramChart.source(data);

    dateHistogramChart.scale('timestamp', {
      type: 'cat',
      tickCount: 6,
      mask: 'YYYY-MM-DD HH:mm:ss.sss',
    });

    dateHistogramChart
      .interval()
      .position('timestamp*count')
      .color('logType')
      .adjust([
        {
          type: 'dodge',
          marginRatio: 1 / 32,
        },
      ]);

    if (sessionStorage.getItem('plusTime') !== '1') {
      dateHistogramChart.on('click', ev => {
        if (ev.data !== undefined && ev.data._origin !== undefined) {
          this.setState({ show: false });
          const { dispatch } = this.props;
          const startTime = getUnixTime(ev.data._origin.timestamp);
          const endTime = getEndTime(startTime);
          const xType = diffDate(startTime, endTime);
          countAction += 1;
          action.push({ startDate: startTime, endDate: endTime });
          console.log('actionClick', action);
          console.log('countActionClick', countAction);
          sessionStorage.setItem('behaviorStartDate', startTime);
          sessionStorage.setItem('behaviorEndDate', endTime);
          dispatch({
            type: 'aaaa/balalala',
            payload: {
             params:aaaaa,
            },
            callback: data => {
              if (data.code === 'A00000') {
                this.setState({ show: true });
              }
            },
          });
        }
      });
    }
   
    dateHistogramChart.render();

  };

render(){
return( <div id="mountNode" />);
}

**Comment by aa1011372655** [comment]
同学你好，我看了一下
![image](https://user-images.githubusercontent.com/8445734/57755525-be31b480-7723-11e9-9aeb-ebdc3f330286.png)
off这个方法第二个参数应该是不可省略的，尝试将回调函数做成非匿名函数，传入off第二个参数试试
```
callback = (ev) => {
  if (ev.data !== undefined && ev.data._origin !== undefined) {
      this.setState({ show: false });
      const { dispatch } = this.props;
      const startTime = getUnixTime(ev.data._origin.timestamp);
      const endTime = getEndTime(startTime);
      const xType = diffDate(startTime, endTime);
      countAction += 1;
      action.push({ startDate: startTime, endDate: endTime });
      console.log('actionClick', action);
      console.log('countActionClick', countAction);
      sessionStorage.setItem('behaviorStartDate', startTime);
      sessionStorage.setItem('behaviorEndDate', endTime);
      dispatch({
        type: 'aaaa/balalala',
        payload: {
         params:aaaaa,
        },
        callback: data => {
          if (data.code === 'A00000') {
            this.setState({ show: true });
          }
        },
      });
    }
}
componentDidMount() {
...
}
dateHistogram = (data) => {
   dateHistogramChart.off('click', this.callback);
   dateHistogramChart.on('click', this.callback);
}
```

**Comment by stephanieDL** [comment]
> 同学你好，我看了一下
> ![image](https://user-images.githubusercontent.com/8445734/57755925-b0c8fa00-7724-11e9-86f5-1afe2bd1fd19.png)
> 
> off这个方法第二个参数应该是不可省略的，尝试将回调函数做成非匿名函数，传入off第二个参数试试
> 
> ```
> callback = (ev) => {
>   if (ev.data !== undefined && ev.data._origin !== undefined) {
>       this.setState({ show: false });
>       const { dispatch } = this.props;
>       const startTime = getUnixTime(ev.data._origin.timestamp);
>       const endTime = getEndTime(startTime);
>       const xType = diffDate(startTime, endTime);
>       countAction += 1;
>       action.push({ startDate: startTime, endDate: endTime });
>       console.log('actionClick', action);
>       console.log('countActionClick', countAction);
>       sessionStorage.setItem('behaviorStartDate', startTime);
>       sessionStorage.setItem('behaviorEndDate', endTime);
>       dispatch({
>         type: 'aaaa/balalala',
>         payload: {
>          params:aaaaa,
>         },
>         callback: data => {
>           if (data.code === 'A00000') {
>             this.setState({ show: true });
>           }
>         },
>       });
>     }
> }
> componentDidMount() {
> ...
> }
> dateHistogram = (data) => {
>    dateHistogramChart.off('click', this.callback);
>    dateHistogramChart.on('click', this.callback);
> }
> ```
非常感谢！之前看文档说off那个不加第二参数是会终止一切click活动，果然不行的哦。非常感谢您的解答，比心(*^__^*)
