### ISSUE TITLE
timeCat的时候，为啥mask不起作用啊？

### ISSUE THREAD

**Issue by qsc555** [antvis/g2#1291]
jsonData = [
{'time':'2019-05-09 15:02:00','value':'100.20'},
{'time':'2019-04-09 15:02:00','value':'102.30'}
];
myChart.scale('time', {
						type: 'timeCat',
						mask: 'HH',//这里我想只显示小时，比如02,03...
						alias: '小时',						
						nice: true,
						ticks: jsonData.map(function (cur) {
							return cur.time;
						})
					});
myChart.interval().position('time*value').label('value', { offset: 6 }).size(20);
代码如上 ，我是希望x轴上所有时间都标出来，但是数据一多，还是被优化了，我是查48个小时，感觉不需要优化啊

**Comment by qsc555** [comment]
描述有些问题，代码的结果是，mask不起作用，会用完整的时间格式，然后我在jsonData.map（）的函数里自己返回小时01,20等，也不行，我感觉mask应该起作用，不用我去格式化ticks里面的数据了，要么就让我在ticks里自己格式化，这里感觉有问题

**Comment by aa1011372655** [comment]
同学你好，是否能够提供codepen复现，这样对我们更容易排查问题，https://codepen.io/leungwensen/pen/WXJgox

**Comment by dxq613** [comment]
我看了一下逻辑，timeCat 是会根据数值的个数进行计算，如果想显示所有的建议，改成 type: 'cat'，使用 formatter

```js
chart.scale('time', {
  type: 'cat',
  formatter(val) {
    return new Date(val).getHours()
  }
});
```
