### ISSUE TITLE
折线图点击线支持跳转链接吗？

### ISSUE THREAD

**Issue by yuexianqiang** [antvis/g2#1296]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by aa1011372655** [comment]
可以自行实现，查看文档：https://www.yuque.com/antv/g2-docs/api-chart#10b2761d
通过lineClick的回调

**Comment by yuexianqiang** [comment]
> 可以自行实现，查看文档：https://www.yuque.com/antv/g2-docs/api-chart#10b2761d
> 通过lineClick的回调

![antv](https://user-images.githubusercontent.com/27284446/57766014-32c31e00-7739-11e9-9111-5622d0fa3e16.png)
点击生成的折线，刚试了下没效果啊

**Comment by aa1011372655** [comment]
> > 可以自行实现，查看文档：https://www.yuque.com/antv/g2-docs/api-chart#10b2761d
> > 通过lineClick的回调
> 
> ![antv](https://user-images.githubusercontent.com/27284446/57766014-32c31e00-7739-11e9-9111-5622d0fa3e16.png)
> 点击生成的折线，刚试了下没效果啊

```
chart.on('line:click', ev => {console.log(ev)});
```
测试可用，能提供codepen吗？
https://codepen.io/leungwensen/pen/WXJgox
