### ISSUE TITLE
antv 什么时候可以做一个示例仓库

### ISSUE THREAD

**Issue by fattypanda** [antvis/g2#1297]
如题。
主要是每次可能会有一些自定义的图形，自己画又没有那么多时间去研究。
最好提供一个像echarts一样的大家可以提交自己自定义的示例，方便大家使用。
还有就是3D图表什么时候考虑一下呗。公司为了表现力，后期可能会用一些3D的。

**Comment by dxq613** [comment]
3D 图表目前在内部没有需求。最近整理所有的 issue 会把很多 demo 写到一个单独的仓库里面。
