### ISSUE TITLE
初始化数据源为空时报错

### ISSUE THREAD

**Issue by orangeyyy** [antvis/g2#130]
## 当不设置axis或者只设置一个的话没有问题：
```js
  this.chart.source([])
```
```js
  this.chart.source([], {
      label: {
        type: 'timeCat',
        mask: 'mm-dd',
        alias: '时间'
      }
    })
```
## 当设置两个axis时报错：
```js
  this.chart.source([], {
      label: {
        type: 'timeCat',
        mask: 'mm-dd',
        alias: '时间'
      },
      value: {
        alias: '数量'
      }
    })
```
![image](https://cloud.githubusercontent.com/assets/19667299/26777594/666db3c6-4a10-11e7-843d-1f8ddc0d34a0.png)
代码详见：https://github.com/orangeyyy/g2-test/blob/master/src/components/lineChart.js

**Comment by dxq613** [comment]
嗯，这个bug 已经有人反馈了，已经修复。这周四正式发布，如果着急可以用https://os.alipayobjects.com/rmsportal/ufxjwwrRWQbTChOUfhJu.js
