### ISSUE TITLE
热力图截取y轴，图表有溢出

### ISSUE THREAD

**Issue by sun-quan** [antvis/g2#1302]
![image](https://user-images.githubusercontent.com/20512025/58162113-19c7e900-7cb4-11e9-8b62-0505bc08ec2d.png)

**Comment by aa1011372655** [comment]
同学你好，能提供复现代码吗？这样能更好的排查问题，感谢

**Comment by sun-quan** [comment]
let resy = res.y;
resy = res.y.slice(0, 10);
在数据很多的情况下，单独的截取y轴的

**Comment by sun-quan** [comment]
现在修复了，把总数据也截取就好了

**Comment by dxq613** [comment]
看不懂，如果还有问题，自己写个 codepen 代码贴上来。https://codepen.io
