### ISSUE TITLE
zoom缩放的时候,tooltip有问题

### ISSUE THREAD

**Issue by 18402025768** [antvis/g2#1305]
容器有zoom这个属性,并且不为1,整个图表的tooltip就出现问题,说是3.3版本修复去年10月,但是现在已经5月了,3.5版本

**Comment by maplor** [comment]
说的是 #912 这个问题吗？我在里面提供了一个临时方案可以试一下。

**Comment by 18402025768** [comment]
> 说的是 #912 这个问题吗？我在里面提供了一个临时方案可以试一下。

好像有点效果,但是不是很准确

**Comment by lqy136362687** [comment]
希望气泡地图能有缩小放大的功能

**Comment by maplor** [comment]
> > 说的是 #912 这个问题吗？我在里面提供了一个临时方案可以试一下。
> 
> 好像有点效果,但是不是很准确

不准确应该是受其它样式影响了。这个需要自行检查。我这个版本仅考虑 css scale 的情况。

**Comment by lqy136362687** [comment]
嗯，收到啦，我试试，谢谢




------------------ 原始邮件 ------------------
发件人: "zzzzy"<notifications@github.com>;
发送时间: 2019年6月27日(星期四) 中午1:59
收件人: "antvis/g2"<g2@noreply.github.com>;
抄送: "廖沁悦"<2522824400@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [antvis/g2] zoom缩放的时候,tooltip有问题 (#1305)



  
说的是 #912 这个问题吗？我在里面提供了一个临时方案可以试一下。
  
好像有点效果,但是不是很准确
  
不准确应该是受其它样式影响了。这个需要自行检查。我这个版本仅考虑 css scale 的情况。

**Comment by ssfxz** [comment]
由于zoom不是css里的标准属性，因此在各种浏览器里可能会有不同实现，因此推荐使用标准属性scale来代替

**Comment by JdesEva** [comment]
最新 版本的tooltip，在geo地图开启拖拽(drag)时候有问题 
![image](https://user-images.githubusercontent.com/37232561/65004827-4c1ae780-d930-11e9-97ea-c9c13696f5e3.png)
