### ISSUE TITLE
柱状图单条数据会横跨多个坐标

### ISSUE THREAD

**Issue by kuangshu** [antvis/g2#1309]
* **G2 Version**:  3.5.1
* **Platform**:window 10 x64
* **CodePen Link**: https://codepen.io/kuangshu/pen/GaYrmM

当数据只有一条并且设置了x坐标的情况下会出现柱状图横跨多个坐标的情况，当有多条数据时并不会有问题。

**Comment by aa1011372655** [comment]
同学你好，可以通过size在只有一条数据时，强制设置size，解决这个问题，如：
```
...
  .interval()
  .position('month*count')
  .color('#4e82fb').size(10);
chart.render();
```

**Comment by kuangshu** [comment]
@aa1011372655 谢谢，这个倒是解决了，不过是否意味着类似柱状图表都需要设置size，并且在固定size的情况下也无法让柱状宽度自适应，当图表宽度过小的情况下，多个柱状会叠在一起，也就是需要按宽度情况设置不同的size才能正常展示。

**Comment by aa1011372655** [comment]
> @aa1011372655 谢谢，这个倒是解决了，不过是否意味着类似柱状图表都需要设置size，并且在固定size的情况下也无法让柱状宽度自适应，当图表宽度过小的情况下，多个柱状会叠在一起，也就是需要按宽度情况设置不同的size才能正常展示。

这个是能实现单个展示的时候，至于多个，确实可以向你说的那样实现，涉及到技术细节的话，较为复杂，建议只有单个数据的时候处理

**Comment by kuangshu** [comment]
> > @aa1011372655 谢谢，这个倒是解决了，不过是否意味着类似柱状图表都需要设置size，并且在固定size的情况下也无法让柱状宽度自适应，当图表宽度过小的情况下，多个柱状会叠在一起，也就是需要按宽度情况设置不同的size才能正常展示。
> 
> 这个是能实现单个展示的时候，至于多个，确实可以向你说的那样实现，涉及到技术细节的话，较为复杂，建议只有单个数据的时候处理

好的，我先这样处理了
