### ISSUE TITLE
连续图例 chart.legend  mode 设置多选 multiple 需要提供一个 默认展示图例配置

### ISSUE THREAD

**Issue by wenshan** [antvis/g2#131]
连续图例 chart.legend  mode 设置多选 multiple 需要提供一个 默认展示图例配置，不可能在所有的场景设置multiple展示所有图例，请参照echarts 的功能实现

**Comment by dxq613** [comment]
3.0 中开放自定义 html legend 的接口，所有的事件也可以自己定义。等 11月份 开源。
