### ISSUE TITLE
建议与优化 柱形图

### ISSUE THREAD

**Issue by bhabgs** [antvis/g2#1310]
G2 Version: 3.5.5
Platform: pcweb
Mini Showcase(like screenshots):
CodePen Link: no code
1. 建议增加
![QzpcVXNlcnNcREVMTFxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcMjg4ODI3NzIyX3YyXEltYWdlRmlsZXNcMTU1OTI2NjQyODA2NV85M0M1MEU4MS01OTYyLTRhYjItQUI3Ni00NTg3RTNGN0I5RUIucG5n](https://user-images.githubusercontent.com/19221378/58675510-34225680-8387-11e9-8395-fd04271b8aab.png)

**Comment by dxq613** [comment]
自己自定义 shape 去通过 path 实现，伪3D 效果 G2 暂时不提供。
