### ISSUE TITLE
 chart.interact('brush')功能

### ISSUE THREAD

**Issue by zhaohuaxuan** [antvis/g2#1312]
![image](https://user-images.githubusercontent.com/13183222/58678732-5a4df380-8393-11e9-81e1-fbf98dbbad0c.png)

我想了解一下这个红框内的功能，api文档没想找到，请问我通过什么途径可以了解到相关的信息

**Comment by paleface001** [comment]
您好，目前g2 3.x内置的interaction还没有形成文档，目前g2 3.x的文档在语雀，地址： https://www.yuque.com/antv/g2-docs。 请持续关注

**Comment by zhaohuaxuan** [comment]
谢谢您在百忙之中给我回复邮件，谢谢您！


 
---原始邮件---
发件人: "paleface001"<notifications@github.com>
发送时间: 2019年6月13日 20:10:49
收件人: "antvis/g2"<g2@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"MK"<1601661339@qq.com>;
主题: Re: [antvis/g2]  chart.interact('brush')功能 (#1312)



您好，目前g2 3.x内置的interaction还没有形成文档，目前g2 3.x的文档在语雀，地址： https://www.yuque.com/antv/g2-docs。 请持续关注
