### ISSUE TITLE
自定义图例，使用 useHtml: true时，点击图例，“legend-item:click”事件不会被响应

### ISSUE THREAD

**Issue by MrSeaWave** [antvis/g2#1313]
* **G2 Version**: 3.5.5
* **Platform**: Mac
* **Mini Showcase(like screenshots)**: 
如果
```
  chart.legend({
    useHtml: true,
  })

  chart.on('legend-item:click',(e)=>{console.log('e',e)})
```
图例点击事件不会被响应

如果
```
  // 图例
  chart.legend({
    useHtml: false,
  })

  chart.on('legend-item:click',(e)=>{console.log('e',e)})
```
点击事件会被响应
![image](https://user-images.githubusercontent.com/21967852/58691242-f55bc300-83bd-11e9-8c4e-0d98031cbd2d.png)

* **CodePen Link**: https://codepen.io/mrseawave/pen/byQvwo

**Comment by aa1011372655** [comment]
同学你好，这种绑定方式是适用于canvas渲染的情况，如果你使用了html模式，调用方式是这样的：
```
chart.legend({
    useHtml: true,
    onClick: (e) => {
      console.log('e',e)
    }
  })
```

**Comment by MrSeaWave** [comment]
> 同学你好，这种绑定方式是适用于canvas渲染的情况，如果你使用了html模式，调用方式是这样的：
> 
> ```
> chart.legend({
>     useHtml: true,
>     onClick: (e) => {
>       console.log('e',e)
>     }
>   })
> ```

https://github.com/antvis/g2/issues/746#issuecomment-404704962,
这条回复中说改掉了这种的事件实现，所以我才决定使用`chart.on('legend-item:click',(e)=>{console.log('e',e)})`,去监听`legend`的点击事件，而且G2文档中并没有说明这种绑定方式是适用于canvas渲染的情况吧，
- https://www.yuque.com/antv/g2-docs/api-chart#10b2761d
- https://www.yuque.com/antv/g2-docs/tutorial-chart-event

**Comment by mengayng** [comment]
想问下这种图是怎么绘制出来的？
![捕获](https://user-images.githubusercontent.com/44225405/58782412-1c5e0300-8611-11e9-9ceb-ba9ec914690c.PNG)

**Comment by dxq613** [comment]
@mengayng 自定义 shape 吧。不过不要想着用 G2 解决所有问题，你这个场景，用DOM和图片就够了。
