### ISSUE TITLE
how color transparent?

### ISSUE THREAD

**Issue by lokewei** [antvis/g2#1315]
if i use color method like this:

```javascript
chart.area().position('date*quantity').color('l(90) 0:#51E3FC 1:rgba(xxx,xxx,xxx, 0.x)')
```
it not working, but i can't find any simple way to get i wanted transparent gradient?

any suggestion?

**Comment by troy351** [comment]
![image](https://user-images.githubusercontent.com/8372385/58860328-72e54300-86de-11e9-8036-449a8fe4d135.png)
It works

**Comment by lokewei** [comment]
@troy351 oh it's my fault，it works now; thanks
