### ISSUE TITLE
子弹图坐标显示问题

### ISSUE THREAD

**Issue by Renoob** [antvis/g2#1316]
* **G2 Version**: 3.5.3
* **Platform**: windows

下图是正确的坐标显示：
![image](https://user-images.githubusercontent.com/41137122/58936740-1009af80-87a3-11e9-9270-1e58b1517fdf.png)

下图是错误的坐标显示：
![image](https://user-images.githubusercontent.com/41137122/58936793-2dd71480-87a3-11e9-83d3-5dc9096ece5e.png)

原因：
```javascript
view.source([data[i]], {
        gradeAvgScore: {
          type: 'linear',
          min: 0,
          max: fullScore,
          nice: false,    // 该字段为true时有问题
          tickCount: 5
        },
        classAvgScore: {
          min: 0,
          max: fullScore,
          nice: false  // 该字段为true时有问题
        },
});
```
```
对最大最小值优化的话，柱子的长度在显示上并没有优化
```

**Comment by dxq613** [comment]
这个问题是由于两个图形不是用同一个度量（字段）导致的，如果想行为完全一样，配置项必须一致，包括 min, max, tickCount ，你一个声明了 tickCount 另一个没声明肯定不会一致。

**Comment by Renoob** [comment]
明白了，感谢
