### ISSUE TITLE
关于词云设置图例不显示的问题？

### ISSUE THREAD

**Issue by yafangmaster** [antvis/g2#1317]
* **G2 Version**:3.5.1
* **Platform**:wamp64 3 64位
* **Mini Showcase(like screenshots)**:[![VUSFld.md.png](https://s2.ax1x.com/2019/06/05/VUSFld.md.png)](https://imgchr.com/i/VUSFld)
* **CodePen Link**:https://codepen.io/yafangmaster/pen/arxqpd

**Comment by dxq613** [comment]
没有设置padding
