### ISSUE TITLE
官网甜甜圈图错位

### ISSUE THREAD

**Issue by mostearly** [antvis/g2#1318]
* **G2 Version**: 3.5.1
* **CodePen Link**: https://codepen.io/nlst/pen/MdMXdd
* **Browser**: Chrome 75 Beta 
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/29162393/59096070-9d3c3800-894c-11e9-8eb4-6136680546a2.png)

CodePen和官网([https://antv.alipay.com/zh-cn/g2/3.x/demo/pie/donut.html](https://antv.alipay.com/zh-cn/g2/3.x/demo/pie/donut.html))的例子都有错位，请问这应该如何解决？

**Comment by dxq613** [comment]
@mostearly 你是指什么错位？图形是正常的，是图例的marker 和 文本不再一条线上么？

**Comment by dxq613** [comment]
我看懂了，你是指饼图不居中是吧？这个问题是由于默认 G2 的 padding 不对称
```js
plotCfg: {
    padding: [ 20, 20, 95, 80 ]
  },
```

```js
new Chart({
  padding: 40 // 设置成固定值就行了
});
```
