### ISSUE TITLE
shape - isCircle is not Effective

### ISSUE THREAD

**Issue by yuanguandong** [antvis/g2#1319]
shape - parsePath - isCircle is not Effective

codepen :   https://codepen.io/favori/pen/mYNMob

inline  28 & 58

**Comment by dxq613** [comment]
我看了下这个函数的定义，没有 isCircle 这个参数，islineToArc 这个参数看上去仅对极坐标生效（可能是为优化性能提供的方式）。原始的定义其实仅接受 path 一个参数
```js
 /**
   * 0～1 path 转 画布 path
   * @param  {path} path 路径
   * @param  {Boolean} islineToArc 是否转换成圆弧
   * @return {path} path 转换到画布坐标的path
   */
  parsePath(path, islineToArc) {
    const coord = this._coord;
    path = GPath.parsePathString(path);
    if (coord.isPolar && islineToArc !== false) {
      path = PathUtil.convertPolarPath(coord, path);
    } else {
      path = PathUtil.convertNormalPath(coord, path);
    }
    return path;
  },
```

回到你这个问题，应该是你的 path 绘制的有问题，而不是参数是否生效的问题。

**Comment by yuanguandong** [comment]
> ```js
> islineToArc
> ```
那就应该是文档比较老，的确看到是有个参数
https://www.yuque.com/antv/g2-docs/api-shape
![image](https://user-images.githubusercontent.com/13197560/59551883-b67b5f00-8fb2-11e9-8a96-41cd44103a79.png)

**Comment by yuanguandong** [comment]
> 我看了下这个函数的定义，没有 isCircle 这个参数，islineToArc 这个参数看上去仅对极坐标生效（可能是为优化性能提供的方式）。原始的定义其实仅接受 path 一个参数
> 
> ```js
>  /**
>    * 0～1 path 转 画布 path
>    * @param  {path} path 路径
>    * @param  {Boolean} islineToArc 是否转换成圆弧
>    * @return {path} path 转换到画布坐标的path
>    */
>   parsePath(path, islineToArc) {
>     const coord = this._coord;
>     path = GPath.parsePathString(path);
>     if (coord.isPolar && islineToArc !== false) {
>       path = PathUtil.convertPolarPath(coord, path);
>     } else {
>       path = PathUtil.convertNormalPath(coord, path);
>     }
>     return path;
>   },
> ```
> 
> 回到你这个问题，应该是你的 path 绘制的有问题，而不是参数是否生效的问题。

isPolar打印出来是true, 29行和31行打印出来的path是一样的，PathUtil.convertPolarPath没生效？
![image](https://user-images.githubusercontent.com/13197560/59552073-e297df80-8fb4-11e9-8f9a-f0061376bf09.png)
