### ISSUE TITLE
图表联动 g2怎么去实现 

### ISSUE THREAD

**Issue by r1005410078** [antvis/g2#132]

**Comment by r1005410078** [comment]
多个图表 辅助线 联动效果

**Comment by simaQ** [comment]
可以参照 https://antv.alipay.com/g2/demo/18-other/table-area.html

**Comment by maplor** [comment]
@simaQ  这个demo里的联动太黑科技了吧。。手动模拟了点和线。。。
@r1005410078  可以试下监听事件后，手动触发chart.showTooltip方法来联动。具体代码我还没有尝试，不过应该是可行的。

**Comment by netbeen** [comment]
@simaQ 这个链接已经失效了，可否提供一个新的demo？我也是卡在实现echart的connect这一步，谢谢

**Comment by simaQ** [comment]
http://antvis.github.io/g2/demo/18-other/table-area.html

**Comment by maplor** [comment]
@simaQ  你回复还真快。。话说不考虑一下现在的官网也加一个联动的示例么，在别的库里都是单独的一个功能列出来的，G2里就隐藏在api文档里了。

**Comment by simaQ** [comment]
恩，后面我们会在官网放出 g2 gallery，将这些富交互的例子放上

**Comment by maplor** [comment]
准备封装一个简单的connect函数，不然现在实现联动还挺麻烦的，联动添加的代码是源代码的两倍。。
https://riddle.alibaba-inc.com/riddles/e3233a7d

**Comment by netbeen** [comment]
@maplor Cool! 很棒的思路，plotmove+showTooltip，比官网的demo还要简洁，学习了！

**Comment by maplor** [comment]
@netbeen 之前不小心贴了riddle的地址，后来觉得外网访问不了就删掉了，没想你这么快就看到 =.=

**Comment by netbeen** [comment]
为了方便分享给其他人，我把connect的实现方法贴出，抛砖引玉。
```html
<!DOCTYPE html>
<html>
<body>
<div id="c1"></div>
<div id="c2"></div>
<script src="https://gw.alipayobjects.com/os/antv/assets/g2/3.0.4/g2.min.js"></script>
<script>
  const data = [{ genre: 'Sports', sold: 275 }, { genre: 'Strategy', sold: 115 }, { genre: 'Action', sold: 120 },];
  const chart1 = new G2.Chart({container: 'c1', height : 300 });
  const chart2 = new G2.Chart({container: 'c2', height : 300 });
  for(const chart of [chart1,chart2]){
    chart.source(data);
    chart.interval().position('genre*sold').color('genre')
    chart.render();
  }

  // 线表联动
  const connect = (...charts) => {
    // console.log(charts);
    for(const chartSrc of charts){
      for(const chartDest of charts){
        if(chartSrc === chartDest){
          continue;
        }
        chartSrc.on('plotmove', e => {chartDest.showTooltip(e);})
        chartSrc.on('plotleave', () => {chartDest.hideTooltip();})
      }
    }
  }
  
  connect(chart1,chart2);
</script>
</body>
</html>
```
![1](https://user-images.githubusercontent.com/1592533/36073503-c1a1e074-0f6c-11e8-9684-097634ff6b4d.gif)

**Comment by maplor** [comment]
@netbeen  多谢把代码贴出来了。
不过我在实现 g2-connect 的时候遇到了相当多的问题，这里列出来希望大家能共同讨论。

# g2-connect
## 基本功能

- 链接多个图表，使相互之间同时触发/消失tooltip。
- 取消链接。

### 事件优化

上面的实现中使用二重循环绑定事件，逻辑很简单，但是事件个数是 (n^2-n)*2，而且取消链接也很麻烦。理想中应该只有两个回调函数 handlePlotmove和handlePlotleave，内部由事件中心统一处理逻辑，这样可以比较方便的通过 chart.off 取消链接。

## 进阶

### 链接组

这里引入一个“组”（group）的概念，参考自 [Echarts connect](http://echarts.baidu.com/api.html#echarts.connect) ，即链接在一起的图表组成一个“链接组”。引入这个概念是为了让链接的功能更灵活。例如页面上有6个图表实例，可能会分为多组链接，组之间没有链接关系。
但是增加一个概念实现逻辑相对也会复杂很多，暂时没有细想具体实现。

- 向已经链接好的组添加新图表。
- 从已经链接好的组移除某个图表。

### 配合拖拽缩放

如果一个图表使用 [g2-brush](https://github.com/antvis/g2-brush) 实现拖拽缩放，目前的链接方式就会出现问题。
mousemove事件中得到的回调参数是画布的xy坐标，chart.showTooltip 接受的参数也是画布xy坐标，如果两者没有缩放是ok的，但是其中一个缩放后，两边的画布坐标就无法对应了。目前没有好的思路，希望大家能提一下自己的想法。

**Comment by geek4go** [comment]
mark
