### ISSUE TITLE
interact：brush 报错，获取不到起始点坐标

### ISSUE THREAD

**Issue by ye10** [antvis/g2#1321]
* **G2 Version**: 3.2.7
* **Mini Showcase(like screenshots)**:

<img width="963" alt="g2Brush" src="https://user-images.githubusercontent.com/19183494/59190897-89910b80-8bb0-11e9-80ac-4edb549a3a8f.png">

使用 brush 时，有时会报错，如图所示，然后 brush 留下的区域一直消失不掉。

**Comment by dxq613** [comment]
写个 codePen 给我，好定位问题，提高答疑的效率。

**Comment by afc163** [comment]
可以接入 https://github.com/ant-design/ant-bot，自动回复。https://github.com/ant-design/ant-design/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%A4%94+Need+Reproduce%22
