### ISSUE TITLE
tooltip的取值取自scale以后的值还是dataview?

### ISSUE THREAD

**Issue by ZhaoTim** [antvis/g2#1322]
发现ToolTip的取值很奇怪！
当我用`chart.scale({formatter: function(item) {
      return item;
    }});`时，item没有做任何操作，那么tooltip的值则是对应列的值，但是一旦我对item做加减乘除或者拼接成item + 'xxxx'时，tooltip就变成了变换后的值。。。这样的逻辑确认是对的吗？

**Comment by dxq613** [comment]
在 scale 里面设置了后，会影响 tooltip，legend 和 axis 上的信息展示，如果想只格式化 tooltip ，那么就在 tooltip 上单独格式化，而不用 scale 上格式化。
