### ISSUE TITLE
词云设置图例，模板的回调函数返回的 color 都是白色 #fff，无法自定义颜色

### ISSUE THREAD

**Issue by yafangmaster** [antvis/g2#1324]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:https://codepen.io/yafangmaster/pen/arxqpd?editors=1011

**Comment by dxq613** [comment]
我看了一下这个问题是由于 itemTpl 的回调函数中取的是 marker 的 fill 或者 stroke 的颜色，这时候由于使用的是点图，而点图默认的 marker 是 fill: '#fff', stroke: '颜色'。可以直接在 legend 上声明 marker。这个回调函数中的颜色我看看怎么处理的更完美一些。

```js
chart.legend({
            useHtml: true,
            // position: 'right',
            reactive: true,
            marker: 'circle',
            ....
});
```
