### ISSUE TITLE
G2多线和多堆叠统计图数据源解惑

### ISSUE THREAD

**Issue by GlodenBoy** [antvis/g2#1329]
各位大佬，初用G2，调试堆叠或多折叠统计图数据源半天，始终觉得变扭，求解惑~
我看所有的官方例子 数据源都是以展开形式体现比如：

`var data = [{
    "month": "Jan",
    "key": "series1",
    "value": 125
  }, {
    "month": "Jan",
    "key": "series2",
    "value": 51
  }, {
    "month": "Feb",
    "key": "series1",
    "value": 132
  }, {
    "month": "Feb",
    "key": "series2",
    "value": 91
  }]`

也就是说没有任何包括对象的形式：

`{ id:1, users:[1,2,3]},{id:2, users:[4,5,6]}`

但是 服务器要不是返回所有数据 要不就是如上那种groupBy 的数据。

比如如下场景：我想得到 以日期x ,uers为y的value, 相同日期上上显示不同user的多折线图

假如服务器返回是全部数据如下：

`var data = [{
    "time": "2019-1-2",
    "users": {
       A:30,
       B:1,
    },
  }, {
    "time": "2019-1-3",
     "users": {
       A:40,
    },
  }, {
    "time": "2019-1-2",
       "users": {
       c:30,
    },
  }, {
   "time": "2019-1-2",
      "users": {
       A:30,
    },
  }]`

我调试了半天始终不知道如何能以高性能的模式吧这个数据展开。不能各种循环插值吧。

**Comment by dxq613** [comment]
G2 默认支持展开的数据，你这种形式的数据不支持。需要自己进行转换，当然你可以通过自定义 shape 来实现这种数据格式的层叠柱状图，只是不同类型的柱子的颜色之类的需要你自己来设置。
