### ISSUE TITLE
图例太长,无法显示完整

### ISSUE THREAD

**Issue by yszsz** [antvis/g2#133]
图例太长，无法显示完整的时候，有没有方法可以显示一部分展示不完的.......

**Comment by simaQ** [comment]
这个是因为 margin 设置得太小了，你调整下 margin 参数。https://antv.alipay.com/g2/doc/tutorial/start/chart.html#二、图表样式

**Comment by yszsz** [comment]
想动态的设置margin值

**Comment by simaQ** [comment]
这个功能我们已经考虑加入了，目前你先手动调整下吧~
