### ISSUE TITLE
请问滑块怎么设置到自己想要的位置,用start，end好像都不起作用

### ISSUE THREAD

**Issue by TheBeard30** [antvis/g2#1330]
![@ PVZLRC~KLJU%A$R 3D9Z9](https://user-images.githubusercontent.com/21235442/59986813-f0abc700-966a-11e9-99be-8b505534a59b.png)

想要让滑块在初始状态下和图表保持一致

**Comment by dxq613** [comment]
好像滑块的设计仅考虑了连续（时间）轴的情况，没有考虑分类的情形。你把 x 轴改成时间试试。
