### ISSUE TITLE
Changelog missing

### ISSUE THREAD

**Issue by afc163** [antvis/G2#1332]
<img width="486" alt="image" src="https://user-images.githubusercontent.com/507615/60073502-3fcd2700-9753-11e9-9384-d014fb60bb74.png">

**Comment by simaQ** [comment]
已手工在 4.0.0 版本加上。这个有现成的机器人吗？

**Comment by afc163** [comment]
[np](https://npmjs.com/np) 或者 [release-it](https://npmjs.com/release-it) 可以根据 commits 自动生成，如果是手写的则需要手动编辑。
