### ISSUE TITLE
geom line with smooth dash

### ISSUE THREAD

**Issue by lokewei** [antvis/g2#1335]
in my tests, `smooth` and `dash` can work well stand alone; but I want a smooth dash, like this 
![image](https://user-images.githubusercontent.com/1223119/60262444-c11de880-9910-11e9-874f-d0da06d59c33.png)

the only way is to write a custom shape for `line` geom?

**Comment by ssfxz** [comment]
https://codepen.io/ssfxz/pen/MWgOdXQ

**Comment by aboutmydreams** [comment]
Thanks ssfxz. That’s useful
`
// create line plot
chart.line().position('year*value').shape('smooth').style({lineDash: [5,5]});
`
