### ISSUE TITLE
韦恩图无法绘制

### ISSUE THREAD

**Issue by dlpuzhangyue** [antvis/g2#1337]
* **G2 Version**:3.2
* **Platform**: angular5
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/29819173/60433588-c6907100-9c37-11e9-8687-b3a2d623aab6.png)
完全使用demo进行测试。无任何修改。是否与版本有关？

**Comment by aa1011372655** [comment]
同学，你好，请升级一下g2的版本， 你的版本貌似还没有增加韦恩图

**Comment by dlpuzhangyue** [comment]
> 同学，你好，请升级一下g2的版本， 你的版本貌似还没有增加韦恩图

感谢回复，由于系统架构的问题，升级g2需要进行大量回归测试，故放弃了Venn图。再次感谢🙏
