### ISSUE TITLE
Typescript 编译报错：Cannot assign to read only property 'constructor' of object '[object Object]'

### ISSUE THREAD

**Issue by nzbin** [antvis/g2#1339]
* **G2 Version**: 3.5.7
* **Platform**: Chrome
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/20625845/60557997-1aa36e80-9d7a-11e9-96d1-6589f11553f2.png)

* **CodePen Link**: 

直接在 Angular 中使用 G2 `import * as G2 from '@antv/g2'` 会出现这个错误。
开发环境没有问题，打包之后报错。
尝试多个版本都有这个问题。
初步判断是经过 TS 编译后出现的问题

**Comment by cipchk** [comment]
相同问题，不过用法不同，直接引用 `node_modules/@antv/g2/dist/g2.min.js`，但无法找到 `window.G2`。

> 另，我要非常严重吐槽一下，CHANGELOG.md 就是一个虚设，它是唯一让我知道更新什么了，我是不是得做什么调整唯一文档了，竟然严重脱节。

**Comment by zhuorenqiao** [comment]
相同的问题，环境是在angular8.0下面。
![image](https://user-images.githubusercontent.com/13296120/60563476-8b548600-9d8e-11e9-91a7-3a521f8f717f.png)

**Comment by cipchk** [comment]
@dxq613 好像是由于 Angular8 默认开启差异加载，并在使用 `script[type="module"]`  这导致必须使用 `strict` 模式，而 g2 好像并不支持。

**Comment by cipchk** [comment]
Angular8.1 已经修复第三方类库不强制使用 `type="module"` 模式 https://github.com/angular/angular-cli/issues/14952 不还是希望 G2 能支持 `strict` 模式。

**Comment by zhuorenqiao** [comment]
> Angular8.1 已经修复第三方类库不强制使用 `type="module"` 模式 [angular/angular-cli#14952](https://github.com/angular/angular-cli/issues/14952) 不还是希望 G2 能支持 `strict` 模式。

请问下如何调整呢？我升级到8.1还是不行，也不知道怎么设置。

**Comment by cipchk** [comment]
@zhuorenqiao 目前  `8.0.x` 版本是正常的，该特征是 `8.1.x` 新增的，后者只能等 14952 修复再用 `8.1.x`

**Comment by dasoncheng** [comment]
遇到此问题可通过更改`tsconfig.json`的`target`
This problem can be encountered by changing the 'target' of 'tsconfig.json'
```json
"target":  "es5"
```
关闭差异加载功能
Turn off differential loading

**Comment by nzbin** [comment]
@dasoncheng 确实可以，但是这样和 ng7 就没啥区别了，目前 8.2.x 已经没有问题

**Comment by wzengguang** [comment]
@nzbin 你8.2.x 几没有问题，为什么我8.2.3 引入ViserModule还是不行。

**Comment by nzbin** [comment]
> @nzbin 你8.2.x 几没有问题，为什么我8.2.3 引入ViserModule还是不行。

通过在 angular.json 的 script 中引入是没有问题的，import 的方式不行

**Comment by dxq613** [comment]
等待 4.0 版本，原生支持 typescript，11.22 预览版发布。

**Comment by dasoncheng** [comment]
@dxq613 g2是开源还是非开源，怎么没找到ts源码

**Comment by MisterAries** [comment]
我angular 8.3.x 也有这个问题，请问楼主的问题解决了吗，如果解决了的话能否告知一下解决方案啊，感谢！

**Comment by giscafer** [comment]
same issue on version `v3.5.11`

```json
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@antv/g2": "^3.5.11",
```

```ts
     const clientHeight = document.documentElement.clientHeight / 2 - 60 - 10;
    const clientWidth = document.documentElement.clientWidth * 0.85;

 this.chart = new G2.Chart({
     container: 'chart', // 指定图表容器 ID
     width: clientWidth, // 指定图表宽度
     height: clientHeight // 指定图表高度
 });
```

**Comment by giscafer** [comment]
> 遇到此问题可通过更改`tsconfig.json`的`target`
> This problem can be encountered by changing the 'target' of 'tsconfig.json'
> 
> 
> "target":  "es5"
> 关闭差异加载功能
> Turn off differential loading

关闭可以解决
