### ISSUE TITLE
官网中没有直接可以下载g2.js源码的地方吗？在github中也没找到

### ISSUE THREAD

**Issue by CodeDome** [antvis/g2#134]
官网中没有直接可以下载g2.js源码的地方吗？在github中也没找到

**Comment by CodeDome** [comment]
官网中没有直接可以下载g2.js源码的地方吗？在github中也没找到

**Comment by dxq613** [comment]
源代码还没放出来，预计9月份放出来，先用压缩的吧 https://github.com/antvis/g2/blob/master/index.js
