### ISSUE TITLE
如何使y轴刻度展示对应值

### ISSUE THREAD

**Issue by stephanieDL** [antvis/G2#1340]
如图，请问如何让y轴展示对应数据的类型值,或者可以固定展示刻度值？
![image](https://user-images.githubusercontent.com/35565670/60636950-1c893280-9e4b-11e9-8102-30b0798e015f.png)

代码如下:
renderG2 = data => {
    const { startDate, endDate } = this.state;
    const ds = new DataSet({
      state: {
        start: startDate,
        end: endDate,
      },
    });

    const dv = ds.createView('origin').source(data);
    dv.transform({
      type: 'filter',
      callback: function callback(obj) {
        const time = new Date(obj.createTime).getTime();
        return time >= ds.state.start && time <= ds.state.end;
      },
    });

    const chart = new G2.Chart({
      container: 'c1',
      forceFit: true,
      height: 420,
    });

    chart.source(dv);

    chart.axis('height', {
      tickLine: {
        stroke: '#C6C3C3',
        value: 5, 
      },
      line: {
        stroke: '#C6C3C3',
      },
      label: {
        offset: 20,
      },
    });
    chart.scale('height', {
      min: 0,
      formatter(e) {
        if (e === 4.8) {
          return '错误日志';
        }
        if (e === 5) {
          return '性能日志';
        }
        if (e === 10) {
          return '代码级日志';
        }
        if (e === 15) {
          return '崩溃日志';
        }
        if (e === 20) {
          return '用户行为';
        }
        return '';
      },
    });

    chart.scale('createTime', {
      type: 'time',
      tickCount: 4,
      mask: 'YYYY-MM-DD HH:mm:ss',
    });
    chart.tooltip({
      showTitle: false,
      crosshairs: {
        type: 'cross',
      },
    });
    chart
      .point()
      .position('createTime*height*type')
      .color('type', type => {
        if (type === '错误日志') {
          return '#FD1304';
        }
        if (type === '性能日志') {
          return '#5871EB';
        }
        if (type === '代码级日志') {
          return '#71EB58';
        }
        if (type === '崩溃日志') {
          return '#EB6A58';
        }
        if (type === '展示行为') {
          return '#257F8F';
        }
        if (type === '点触行为') {
          return '#6AD5D5';
        }
        if (type === '页面行为') {
          return '#EBA458';
        }
        if (type === '系统行为') {
          return '#58B3EB';
        }
      })
      .size(4)
      .shape('type', type => {
        if (type === '错误日志') {
          return 'circle';
        }
        if (type === '性能日志') {
          return 'square';
        }
        if (type === '代码级日志') {
          return 'triangle';
        }
        if (type === '崩溃日志') {
          return 'hexagon';
        }
        if (type === '展示行为') {
          return 'diamond';
        }
        if (type === '点触行为') {
          return 'hollowDiamond';
        }
        if (type === '页面行为') {
          return 'triangle-down';
        }
        if (type === '系统行为') {
          return 'hollowCircle';
        }
      })
      .tooltip('type*createTime');

    chart.on('click', ev => {
      if (ev.data !== undefined && ev.data._origin !== undefined) {
        window.open(
          `http://localhost:8000`,
          '_blank'
        );
      }
    });
    chart.render();

    chart.interact('slider', {
      container: 'slider',
      onChange: function onChange(ev) {
        const { startValue, endValue } = ev;
        ds.setState('start', startValue);
        ds.setState('end', endValue);
      },
    });
  };

**Comment by simaQ** [comment]
在列定义中定义ticks: https://g2-v3.antv.vision/en/docs/api/scale/#ticks
