### ISSUE TITLE
legend bug

### ISSUE THREAD

**Issue by southorange1228** [antvis/g2#1347]
* **G2 Version**: 3.4.10
* **Platform**: windows 10
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/1639617972/pen/YooMbV

legend的title和maker似乎有些问题。当我这是maker的时候，发现并没有效果，或者设置title为null的时候也没有任何效果

**Comment by pddpd** [comment]
这里的`title`设置为`null`是生效了的，你可以试试加上`title`的样式看看效果，比如：
```
title: {
  textAlign: 'center', 
}
```
第二个是因为`marker`拼写错误，少了个r，你可以看看。
