### ISSUE TITLE
多图表tooltip联动，最后的总计显示不正常

### ISSUE THREAD

**Issue by haisansui** [antvis/g2#1348]
![image](https://user-images.githubusercontent.com/42774015/61350764-39862280-a89b-11e9-827c-e485dcfa070b.png)

    .g2-guide-html {
        width: 20px;
        height: 20px;
        vertical-align: middle;
        line-height: 0.4
    }
这个样式的宽度应该设置为30，如果是20就会显示不正常

**Comment by zqlu** [comment]
@haisansui 可以在外层用CSS复写样式
