### ISSUE TITLE
tooltip 完全自定义样式 bug

### ISSUE THREAD

**Issue by yihuaxiang** [antvis/g2#1349]
背景：
  在完全自定义 tooltip 时，tooltip 设置的内容不显示
关键代码：
```
    chart.tooltip({ 
     useHtml:true, 
     htmlContent:function(title,items){
        return '<div class="g2-tooltip"><ul class="g2-tooltip-title"><li>.....</li></ul></div>'
     }
   }
```
  codeopen ： [https://codepen.io/yihuaxiang/pen/wVvmPZ](https://codepen.io/yihuaxiang/pen/wVvmPZ)
![image](https://user-images.githubusercontent.com/7598734/61460396-3ffec200-a9a1-11e9-8ed1-8712712da9f3.png)

  分析：通过审查元素发现 tooltip 设置的 dom 已经生成，但是缺少 css 属性 position:absolute; 导致位置显示异常，tooltip 配置中 follow 属性默认为 true ，当鼠标移动是 tooltip 对应的 dom 的 left、top 属性会跟着变化，所以判定为缺少 position:absolute; 这个 css 属性
  期望结果：
  当 tooltip 配置中 follow 属性为 true（默认值） 时 htmlContent 函数生成的 dom 自动加上css属性 position:absolute;

**Comment by simaQ** [comment]
你好，对于 `htmlContent` 属性，我们的策略是如果使用了该属性自定义 tooltip 结构，那么这个结构 的样式就要用户自己负责，所以这里建议你自己定义下样式。望理解。

```js
chart.tooltip(
   { 
     useHtml:true, 
     htmlContent:function(title,items){
        return '<div class="g2-tooltip" style="position: absolute;"><ul class="g2-tooltip-title"><li>.....</li></ul></div>'
     }
   }
)
```

**Comment by yihuaxiang** [comment]
> 你好，对于 `htmlContent` 属性，我们的策略是如果使用了该属性自定义 tooltip 结构，那么这个结构 的样式就要用户自己负责，所以这里建议你自己定义下样式。望理解。
> 
> ```js
> chart.tooltip(
>    { 
>      useHtml:true, 
>      htmlContent:function(title,items){
>         return '<div class="g2-tooltip" style="position: absolute;"><ul class="g2-tooltip-title"><li>.....</li></ul></div>'
>      }
>    }
> )
> ```

完全由我负责那我也能理解，但是

> tooltip 配置中 follow 属性默认为 true ，当鼠标移动是 tooltip 对应的 dom 的 left、top 属性会跟着变化

follow为true时，框架设置了left、top属性显然是想让dom跟随鼠标，显然是缺少了position属性

> 如果使用了该属性自定义 tooltip 结构，那么这个结构 的样式就要用户自己负责
既然用户自己负责样式，那为什么left、top框架给修改了？
