### ISSUE TITLE
层叠柱状图 style设置lineWidth = 0 无效

### ISSUE THREAD

**Issue by AlwaysSkylll** [antvis/g2#135]
层叠柱状图设置设置后默认两个数据间会有过渡颜色。
现在我的业务不需要这个过渡色，即数据为0时不应该有任何线条。于是设置了style方法，参数中lineWidth = 0，不奏效；stroke设置颜色正常。

**Comment by AlwaysSkylll** [comment]
@hi-caicai @leungwensen

**Comment by dxq613** [comment]
层叠柱状图本来就没边框吧。

![图片](https://gw.alipayobjects.com/zos/rmsportal/daIJpTbiIdWvxsqhQwdL.png)

**Comment by AlwaysSkylll** [comment]
![image](https://user-images.githubusercontent.com/13064486/27327274-a9d78f7a-55e0-11e7-8519-a290bd0910f3.png)

看这中间过渡的颜色，当数据是0的时候，会覆盖在横坐标上。style 设置只能改变这个过渡线的颜色，线宽无效

**Comment by dxq613** [comment]
这时候已经没有边框了，覆盖不是由于边框导致的。

例如层叠数据 [1,2], [2,3] 这时候你是无法防止 2 个地方发生重叠的，除非你在绘制这个柱子的时候各自留出 0.5 像素。

数据0的话建议你可以用 opacity 映射给去除掉

```js
chart.interval().position('x*y').opacity('y', function(y) { 
if(y==0} {return 0}
return 0.8;
});
```

**Comment by AlwaysSkylll** [comment]
Got it. Thank u.
