### ISSUE TITLE
堆叠图当Y长度过长的时候会出现样式错乱

### ISSUE THREAD

**Issue by zhuorenqiao** [antvis/g2#1350]
![image](https://user-images.githubusercontent.com/13296120/61460070-9cadad00-a9a0-11e9-8935-3a5c5b774dc1.png)

**Comment by zqlu** [comment]
这里是因为 State 值为 ['2014-04-22']，被自动识别为 time 格式，连续scale会默认占用整个轴；可以通过scale函数手动设置 State 的格式为 category。 见 https://codesandbox.io/s/g2-issue-1350-kitc6
