### ISSUE TITLE
图例翻页功能在one page多chart情况下的bug

### ISSUE THREAD

**Issue by KedAyAyA** [antvis/g2#1351]
* **G2 Version**: 3.5.8-beta.1
* **Platform**: Chrome
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/KedAyAyA/pen/YmPwqd

使用图例翻页功能时，在同一页面下如果有多个图表，均需要图例翻页，则只能为第一个图表添加图例翻页功能，且会将翻页器重复添加到第一个图表，bug具体表现见codepen。
pr已经提在依赖的component库里 https://github.com/antvis/component/pull/60。

**Comment by zqlu** [comment]
谢谢反馈
