### ISSUE TITLE
采用 Option 的写法能否支持重新设置 option

### ISSUE THREAD

**Issue by dd1994** [antvis/g2#1352]
使用文档中所写的[Options 配置项声明](https://www.yuque.com/antv/g2-docs/api-options)，如果 option 发生变化，是否有 API 重新设置 option, 而不是通过命令式的函数调用来修改。 我看 API 文档上没有写，后续是否有计划支持

**Comment by cs1707** [comment]
看这个测试用例应该是可以的
```
 xit('change', function() {
    chart.clear();
    const options = {
      geoms: [{
        type: 'area',
        position: 'genre*sold',
        color: { field: 'type' },
        adjust: 'stack',
        label: { field: 'sold' }
      }]
    };
    chart.changeOptions(options);
    chart.render();
  });
```
https://github.com/antvis/g2/blob/7aaf5ea366bc3c5eacefbbd1c0aa02ebdd36713e/test/unit/chart/chart-option-spec.js

**Comment by dd1994** [comment]
@cs1707 太坑了 文档里居然没写😳
