### ISSUE TITLE
toolTips 不消失

### ISSUE THREAD

**Issue by kimmerchen** [antvis/g2#1354]
![微信图片_20190720165054](https://user-images.githubusercontent.com/20125299/61590384-facdd080-abea-11e9-9771-9d25cbed49d8.png)

**Comment by TnWah** [comment]
同问，在多个图表间鼠标切换，或者鼠标快速出入都可能导致tooltip不会消失，看了一些老的issues说是已经解决过了，目前使用的是bizchats 3.5.4,react 16.8.6
