### ISSUE TITLE
如何修改饼图选中效果

### ISSUE THREAD

**Issue by ydd3064** [antvis/g2#1355]
想要和右侧饼图的选中效果一样
![微信截图_20190723104211](https://user-images.githubusercontent.com/28768793/61679205-11ce0900-ad38-11e9-990b-c52b626fa936.png)

**Comment by yangdongMC** [comment]
为啥就给关了呢？上面这个定制化很需要能自己控制，不知道能否提供入口来自定义选中的区块。
