### ISSUE TITLE
把 g2/lib/index.d.ts 改一下，不然报错

### ISSUE THREAD

**Issue by nczsl** [antvis/g2#1356]
export default G2;
//export = G2;  这行改成上面一行，就好了，不然老报错在打包编译的时候，
export as namespace G2;

declare namespace G2 {
  function track(option: boolean): void;
  const version: string;
  const Animate: Animate;
  const Util: Util;
  const Shape: Shape;

  class Global {
    setTheme(option: 'default' | 'dark'): void;
    version: string;
    trackable: boolean;
    animate: boolean;
    snapArray: number[];
    /**
     * 指定固定 tick 数的逼近值
     */

**Comment by nczsl** [comment]
这么简单的修改 为什么提了这么久还不进行啊

**Comment by Leannechn** [comment]
ts config 试试： "moduleResolution": "node"
报的啥错最好贴一下
