### ISSUE TITLE
计划何时发布4.0

### ISSUE THREAD

**Issue by TimuJiang** [antvis/g2#1357]
计划何时发布4.0

**Comment by afc163** [comment]
+1

**Comment by zqlu** [comment]
大概会11月完成4.0的第一版，可以在[这里](https://www.yuque.com/antv/g2-docs/nmzh8r)查看相关进度

**Comment by hustcc** [comment]
具体的时间点规划：https://www.yuque.com/antv/g2-docs/fnq91g
