### ISSUE TITLE
地图问题

### ISSUE THREAD

**Issue by linshuoe** [antvis/g2#1358]
请求有没有中国地图，上面带point的例子？

**Comment by zhoustudent** [comment]
你好，问一下你有没有遇到地图在更改浏览器窗口大小后，地图给变形的问题呢？

**Comment by maplor** [comment]
由于G2没有中国地图相关资质，所以示例都下掉了。

**Comment by linshuoe** [comment]
> 你好，问一下你有没有遇到地图在更改浏览器窗口大小后，地图给变形的问题呢？

我后端直接使用高德地图，没有发现这个问题

**Comment by zhoustudent** [comment]
这个已经解决了
