### ISSUE TITLE
和弦图在数据量较小时无法正常显示

### ISSUE THREAD

**Issue by travilyu** [antvis/g2#136]
节点到2-5个时，无法正常显示。

**Comment by allan2coder** [comment]
@travilyu 有截图吗？

**Comment by travilyu** [comment]
@allan2coder 

var nodes = [{id:1, name:'aa', value:20},{id:2, name:'bb', value:20}]; // 节点数据
var links = [{source:1, sourceWeight:10, target:2, targetWeight:10}, {source:2, sourceWeight:10, target:1, targetWeight:10}]; // 边数据
![128](https://user-images.githubusercontent.com/1902448/32130335-4bfec0ae-bbc9-11e7-827d-92c16b996855.jpg)

**Comment by dxq613** [comment]
试一下 g2 3.0 的和弦图是否还存在这个问题。

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/demo/relation/chord.html#
