### ISSUE TITLE
Geom colors映射多字段，Legend无法选择通过*拼接的field

### ISSUE THREAD

**Issue by xiaoleon** [antvis/g2#1360]
* **G2 Version**:
3.5.x

* **Platform**:
windows

* **Mini Showcase(like screenshots)**:

* **CodePen Link**:
https://codepen.io/xiaoleon/pen/OKRZQg?editors=0010

API中描述：
1. Legend配置项中的field属性依赖于Geom中color、shape和size定义的field
2. Geom中的color、shape和size描述field可以通过 * 号进行数据源中的字段拼接

问题：
当Geom中的 `color=['year*color', v => v]` 时，legend中的field能够识别出year字段，但无法识别出color字段

分析代码：
1.chart/chart.js文件中 `_renderLegends` 函数执行 `geom.getAttrsForLegend()` 方法时(229行)，未根据color、shape、size中拼接的field进行查找
2.geom/base.js文件中 `getAttrsForLegend` 函数(1127行)执行时，未对 attr.field 进行判断，而只判断了 attr.type，从而导致拼接得到的field在legend中失效

**Comment by zqlu** [comment]
感谢反馈。这个问题在4.0中支持多字段图例；目前可以先临时设置color=["color*year"来解决。
