### ISSUE TITLE
设置一个number类型的字段的scale为cat时，渲染异常

### ISSUE THREAD

**Issue by jzz4012650** [antvis/g2#1361]
* **G2 Version**:
* **Platform**: 
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/anon/pen/YmGbmv

1. 在指定scale时，将一个number类型的字段（例子中的dport）指定为cat类型
2. 并将geom.color设置为该字段（dport)
3. 此时渲染一个分组柱状图
结果：
- 发现无法区分不同的dport，只渲染了同一种颜色
- 虽然正确渲染了legend，但legend无法正常切换图形的显示隐藏

**Comment by dxq613** [comment]
G2 自 3.0 版本后，不再自动在内部转换数据类型，需要用户自己在外面转换数据，
* 声明成 cat 的数据要么是字符串，要么是number 数字但是需要自己指定 values，作为枚举类型使用。
* 声明成 linear 的数据不能是字符串

在 G2 2.x 的时候做过数据的自动转换，但是中间出现过不一致的情况，所以 3.0 就给不提供了。在外面 forEach 转换就好了。
