### ISSUE TITLE
安装完运行demo出错

### ISSUE THREAD

**Issue by lucialiang** [antvis/g2#1363]
Mac 系统，npm install完成后，npm run demos，报错
Uncaught Exception:
Error: Cannot find module 'lodash'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/Users/kaiqi/Downloads/g2-master/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)

**Comment by lucialiang** [comment]
安装过程中，几次提示相同error，不知道是否是安装的问题？

node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
node-pre-gyp ERR! stack     at exports.runInThisContext (vm.js:53:16)
node-pre-gyp ERR! stack     at Module._compile (module.js:373:25)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:416:10)
node-pre-gyp ERR! stack     at Module.load (module.js:343:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:300:12)
node-pre-gyp ERR! stack     at Module.require (module.js:353:17)
node-pre-gyp ERR! stack     at require (internal/module.js:12:17)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/kaiqi/Downloads/g2-master/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/debug/src/index.js:9:19)
node-pre-gyp ERR! stack     at Module._compile (module.js:409:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:416:10)
node-pre-gyp ERR! System Darwin 18.0.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/kaiqi/Downloads/g2-master/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/kaiqi/Downloads/g2-master/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
node-pre-gyp ERR! node -v v4.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm WARN optional dep failed, continuing fsevents@1.2.9

**Comment by Leannechn** [comment]
升级node 版本试试

**Comment by zqlu** [comment]
install过程错误以修复，目前去掉了demo
