### ISSUE TITLE
g2 3.5.2版本下画一个地图，当浏览器窗口更改后，地图会变形，宽高没有办法像echarts一样，等比例扩大和缩小

### ISSUE THREAD

**Issue by zhoustudent** [antvis/g2#1364]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by maplor** [comment]
先提一下：**画地图类还是建议使用高德/百度等有地图资质的sdk实现，否则按照国家地图法，所有公开地图都需要到测绘局审批，有审图号才可以对外开放。**

由于G2没有针对地图做特殊的适配，所以等比例缩放需要自行实现。我可以贴一段我的实现：
```javascript
  // start: 按照投影后尺寸比例调整图表的真实比例
  // bgMapDataView 为dataSet的view实例
  const longitudeRange = bgMapDataView.range('x');
  const latitudeRange = bgMapDataView.range('y');
  const ratio = (longitudeRange[1] - longitudeRange[0]) / (latitudeRange[1] - latitudeRange[0]);
  const { width: chartWidth, height: chartHeight } = chart._attrs;
  const chartRatio = chartWidth / chartHeight;

  let width = chartWidth;
  let height = chartHeight;
  if (chartRatio > ratio) {
    width = chartHeight * ratio;
  } else if (chartRatio < ratio) {
    height = chartWidth / ratio;
  }
  if (width !== chartWidth || height !== chartHeight) {
    chart.changeSize(width, height);
  }
  // end: 按照投影后尺寸比例调整图表的真实比例
```

**Comment by zhoustudent** [comment]
> 先提一下：**画地图类还是建议使用高德/百度等有地图资质的sdk实现，否则按照国家地图法，所有公开地图都需要到测绘局审批，有审图号才可以对外开放。**
> 
> 由于G2没有针对地图做特殊的适配，所以等比例缩放需要自行实现。我可以贴一段我的实现：
> 
> ```js
>   // start: 按照投影后尺寸比例调整图表的真实比例
>   // bgMapDataView 为dataSet的view实例
>   const longitudeRange = bgMapDataView.range('x');
>   const latitudeRange = bgMapDataView.range('y');
>   const ratio = (longitudeRange[1] - longitudeRange[0]) / (latitudeRange[1] - latitudeRange[0]);
>   const { width: chartWidth, height: chartHeight } = chart._attrs;
>   const chartRatio = chartWidth / chartHeight;
> 
>   let width = chartWidth;
>   let height = chartHeight;
>   if (chartRatio > ratio) {
>     width = chartHeight * ratio;
>   } else if (chartRatio < ratio) {
>     height = chartWidth / ratio;
>   }
>   if (width !== chartWidth || height !== chartHeight) {
>     chart.changeSize(width, height);
>   }
>   // end: 按照投影后尺寸比例调整图表的真实比例
> ```

我用的padding来动态控制来防止地图变形，不过这样就得需要加一个监听浏览器窗口改变的事件，增加监听事件无疑是非常消耗性能的一件事，这个应该怎么避免呀

**Comment by KedAyAyA** [comment]
监听窗口change没什么问题 g2本身forceFit在源码上也是通过监听window的resize来实现的 自己按照自身情况对callback做throttle或者debounce就可以吧~

**Comment by maplor** [comment]
> > 先提一下：**画地图类还是建议使用高德/百度等有地图资质的sdk实现，否则按照国家地图法，所有公开地图都需要到测绘局审批，有审图号才可以对外开放。**
> > 由于G2没有针对地图做特殊的适配，所以等比例缩放需要自行实现。我可以贴一段我的实现：
> > ```js
> >   // start: 按照投影后尺寸比例调整图表的真实比例
> >   // bgMapDataView 为dataSet的view实例
> >   const longitudeRange = bgMapDataView.range('x');
> >   const latitudeRange = bgMapDataView.range('y');
> >   const ratio = (longitudeRange[1] - longitudeRange[0]) / (latitudeRange[1] - latitudeRange[0]);
> >   const { width: chartWidth, height: chartHeight } = chart._attrs;
> >   const chartRatio = chartWidth / chartHeight;
> > 
> >   let width = chartWidth;
> >   let height = chartHeight;
> >   if (chartRatio > ratio) {
> >     width = chartHeight * ratio;
> >   } else if (chartRatio < ratio) {
> >     height = chartWidth / ratio;
> >   }
> >   if (width !== chartWidth || height !== chartHeight) {
> >     chart.changeSize(width, height);
> >   }
> >   // end: 按照投影后尺寸比例调整图表的真实比例
> > ```
> 
> 我用的padding来动态控制来防止地图变形，不过这样就得需要加一个监听浏览器窗口改变的事件，增加监听事件无疑是非常消耗性能的一件事，这个应该怎么避免呀

并没有什么问题，实测中做好节流性能影响并不大

**Comment by Hugo-seth** [comment]
> 先提一下：**画地图类还是建议使用高德/百度等有地图资质的sdk实现，否则按照国家地图法，所有公开地图都需要到测绘局审批，有审图号才可以对外开放。**
> 
> 由于G2没有针对地图做特殊的适配，所以等比例缩放需要自行实现。我可以贴一段我的实现：
> 
> ```js
>   // start: 按照投影后尺寸比例调整图表的真实比例
>   // bgMapDataView 为dataSet的view实例
>   const longitudeRange = bgMapDataView.range('x');
>   const latitudeRange = bgMapDataView.range('y');
>   const ratio = (longitudeRange[1] - longitudeRange[0]) / (latitudeRange[1] - latitudeRange[0]);
>   const { width: chartWidth, height: chartHeight } = chart._attrs;
>   const chartRatio = chartWidth / chartHeight;
> 
>   let width = chartWidth;
>   let height = chartHeight;
>   if (chartRatio > ratio) {
>     width = chartHeight * ratio;
>   } else if (chartRatio < ratio) {
>     height = chartWidth / ratio;
>   }
>   if (width !== chartWidth || height !== chartHeight) {
>     chart.changeSize(width, height);
>   }
>   // end: 按照投影后尺寸比例调整图表的真实比例
> ```

请问下 [官网例子](https://antv.alipay.com/zh-cn/g2/3.x/demo/map/choropleth-map.html) `DataView.range('x')` 和 `range('y')` 为什么返回的都是  `[undefined, undefined] `？ @maplor

**Comment by zqlu** [comment]
记录为feature，在G2新版本或G2-Plot实现

**Comment by maplor** [comment]
> 记录为feature，在G2新版本或G2-Plot实现

需要在dataView的实例上运行，在类上面运行肯定是没有返回值的
