### ISSUE TITLE
柱状图分组显示错误

### ISSUE THREAD

**Issue by 18402025768** [antvis/g2#1365]
![image](https://user-images.githubusercontent.com/20633660/62264866-68cc9000-b454-11e9-9b83-55bc1e75cb6d.png)

设置部分
chart.interval().position('_row*_val').color('_col').opacity(1).adjust([{
    type: 'dodge',
    marginRatio: 1 / 32
}]);

数据部分

[{"逾期":110,"租客":"梦港文化艺术发展有限公司","_col":"租金-逾期","费用类型":"电费","_val":0,"_row":"梦港文化艺术发展有限公司"},{"逾期":110,"租客":"梦港文化艺术发展有限公司","_col":"水费-逾期","费用类型":"电费","_val":0,"_row":"梦港文化艺术发展有限公司"},{"逾期":110,"租客":"梦港文化艺术发展有限公司","_col":"租金保证金-逾期","费用类型":"电费","_val":0,"_row":"梦港文化艺术发展有限公司"},{"逾期":110,"租客":"梦港文化艺术发展有限公司","_col":"物业费-逾期","费用类型":"电费","_val":0,"_row":"梦港文化艺术发展有限公司"},{"逾期":110,"租客":"梦港文化艺术发展有限公司","_col":"电费-逾期","费用类型":"电费","_val":110,"_row":"梦港文化艺术发展有限公司"},{"逾期":110,"租客":"梦港文化艺术发展有限公司","_col":"公摊水费-逾期","费用类型":"电费","_val":0,"_row":"梦港文化艺术发展有限公司"},{"逾期":110,"租客":"梦港文化艺术发展有限公司","_col":"入场费-逾期","费用类型":"电费","_val":0,"_row":"梦港文化艺术发展有限公司"},{"逾期":110,"租客":"梦港文化艺术发展有限公司","_col":"物业保证金-逾期","费用类型":"电费","_val":0,"_row":"梦港文化艺术发展有限公司"},{"逾期":110,"租客":"梦港文化艺术发展有限公司","_col":"公摊电费-逾期","费用类型":"电费","_val":0,"_row":"梦港文化艺术发展有限公司"},{"逾期":44,"租客":"力朗教育咨询有限公司","_col":"租金-逾期","费用类型":"公摊水费","_val":0,"_row":"力朗教育咨询有限公司"},{"逾期":44,"租客":"力朗教育咨询有限公司","_col":"水费-逾期","费用类型":"公摊水费","_val":0,"_row":"力朗教育咨询有限公司"},{"逾期":44,"租客":"力朗教育咨询有限公司","_col":"租金保证金-逾期","费用类型":"公摊水费","_val":0,"_row":"力朗教育咨询有限公司"},{"逾期":44,"租客":"力朗教育咨询有限公司","_col":"物业费-逾期","费用类型":"公摊水费","_val":0,"_row":"力朗教育咨询有限公司"},{"逾期":44,"租客":"力朗教育咨询有限公司","_col":"电费-逾期","费用类型":"公摊水费","_val":0,"_row":"力朗教育咨询有限公司"},{"逾期":44,"租客":"力朗教育咨询有限公司","_col":"公摊水费-逾期","费用类型":"公摊水费","_val":44,"_row":"力朗教育咨询有限公司"},{"逾期":44,"租客":"力朗教育咨询有限公司","_col":"入场费-逾期","费用类型":"公摊水费","_val":0,"_row":"力朗教育咨询有限公司"},{"逾期":44,"租客":"力朗教育咨询有限公司","_col":"物业保证金-逾期","费用类型":"公摊水费","_val":0,"_row":"力朗教育咨询有限公司"},{"逾期":44,"租客":"力朗教育咨询有限公司","_col":"公摊电费-逾期","费用类型":"公摊水费","_val":0,"_row":"力朗教育咨询有限公司"},{"逾期":44,"租客":"裕美佳贸易有限公司","_col":"租金-逾期","费用类型":"公摊水费","_val":0,"_row":"裕美佳贸易有限公司"},{"逾期":44,"租客":"裕美佳贸易有限公司","_col":"水费-逾期","费用类型":"公摊水费","_val":0,"_row":"裕美佳贸易有限公司"},{"逾期":44,"租客":"裕美佳贸易有限公司","_col":"租金保证金-逾期","费用类型":"公摊水费","_val":0,"_row":"裕美佳贸易有限公司"},{"逾期":44,"租客":"裕美佳贸易有限公司","_col":"物业费-逾期","费用类型":"公摊水费","_val":0,"_row":"裕美佳贸易有限公司"},{"逾期":44,"租客":"裕美佳贸易有限公司","_col":"电费-逾期","费用类型":"公摊水费","_val":0,"_row":"裕美佳贸易有限公司"},{"逾期":44,"租客":"裕美佳贸易有限公司","_col":"公摊水费-逾期","费用类型":"公摊水费","_val":44,"_row":"裕美佳贸易有限公司"},{"逾期":44,"租客":"裕美佳贸易有限公司","_col":"入场费-逾期","费用类型":"公摊水费","_val":0,"_row":"裕美佳贸易有限公司"},{"逾期":44,"租客":"裕美佳贸易有限公司","_col":"物业保证金-逾期","费用类型":"公摊水费","_val":0,"_row":"裕美佳贸易有限公司"},{"逾期":44,"租客":"裕美佳贸易有限公司","_col":"公摊电费-逾期","费用类型":"公摊水费","_val":0,"_row":"裕美佳贸易有限公司"},{"逾期":44,"租客":"区远程","_col":"租金-逾期","费用类型":"公摊水费","_val":0,"_row":"区远程"},{"逾期":44,"租客":"区远程","_col":"水费-逾期","费用类型":"公摊水费","_val":0,"_row":"区远程"},{"逾期":44,"租客":"区远程","_col":"租金保证金-逾期","费用类型":"公摊水费","_val":0,"_row":"区远程"},{"逾期":44,"租客":"区远程","_col":"物业费-逾期","费用类型":"公摊水费","_val":0,"_row":"区远程"},{"逾期":44,"租客":"区远程","_col":"电费-逾期","费用类型":"公摊水费","_val":0,"_row":"区远程"},{"逾期":44,"租客":"区远程","_col":"公摊水费-逾期","费用类型":"公摊水费","_val":44,"_row":"区远程"},{"逾期":44,"租客":"区远程","_col":"入场费-逾期","费用类型":"公摊水费","_val":0,"_row":"区远程"},{"逾期":44,"租客":"区远程","_col":"物业保证金-逾期","费用类型":"公摊水费","_val":0,"_row":"区远程"},{"逾期":44,"租客":"区远程","_col":"公摊电费-逾期","费用类型":"公摊水费","_val":0,"_row":"区远程"},{"逾期":44,"租客":"郭建","_col":"租金-逾期","费用类型":"公摊水费","_val":0,"_row":"郭建"},{"逾期":44,"租客":"郭建","_col":"水费-逾期","费用类型":"公摊水费","_val":0,"_row":"郭建"},{"逾期":44,"租客":"郭建","_col":"租金保证金-逾期","费用类型":"公摊水费","_val":0,"_row":"郭建"},{"逾期":44,"租客":"郭建","_col":"物业费-逾期","费用类型":"公摊水费","_val":0,"_row":"郭建"},{"逾期":44,"租客":"郭建","_col":"电费-逾期","费用类型":"公摊水费","_val":0,"_row":"郭建"},{"逾期":44,"租客":"郭建","_col":"公摊水费-逾期","费用类型":"公摊水费","_val":44,"_row":"郭建"},{"逾期":44,"租客":"郭建","_col":"入场费-逾期","费用类型":"公摊水费","_val":0,"_row":"郭建"},{"逾期":44,"租客":"郭建","_col":"物业保证金-逾期","费用类型":"公摊水费","_val":0,"_row":"郭建"},{"逾期":44,"租客":"郭建","_col":"公摊电费-逾期","费用类型":"公摊水费","_val":0,"_row":"郭建"},{"逾期":44,"租客":"韩家鹏","_col":"租金-逾期","费用类型":"公摊水费","_val":0,"_row":"韩家鹏"},{"逾期":44,"租客":"韩家鹏","_col":"水费-逾期","费用类型":"公摊水费","_val":0,"_row":"韩家鹏"},{"逾期":44,"租客":"韩家鹏","_col":"租金保证金-逾期","费用类型":"公摊水费","_val":0,"_row":"韩家鹏"},{"逾期":44,"租客":"韩家鹏","_col":"物业费-逾期","费用类型":"公摊水费","_val":0,"_row":"韩家鹏"},{"逾期":44,"租客":"韩家鹏","_col":"电费-逾期","费用类型":"公摊水费","_val":0,"_row":"韩家鹏"},{"逾期":44,"租客":"韩家鹏","_col":"公摊水费-逾期","费用类型":"公摊水费","_val":44,"_row":"韩家鹏"},{"逾期":44,"租客":"韩家鹏","_col":"入场费-逾期","费用类型":"公摊水费","_val":0,"_row":"韩家鹏"},{"逾期":44,"租客":"韩家鹏","_col":"物业保证金-逾期","费用类型":"公摊水费","_val":0,"_row":"韩家鹏"},{"逾期":44,"租客":"韩家鹏","_col":"公摊电费-逾期","费用类型":"公摊水费","_val":0,"_row":"韩家鹏"},{"逾期":44,"租客":"得信科技有限公司","_col":"租金-逾期","费用类型":"公摊水费","_val":0,"_row":"得信科技有限公司"},{"逾期":44,"租客":"得信科技有限公司","_col":"水费-逾期","费用类型":"公摊水费","_val":0,"_row":"得信科技有限公司"},{"逾期":44,"租客":"得信科技有限公司","_col":"租金保证金-逾期","费用类型":"公摊水费","_val":0,"_row":"得信科技有限公司"},{"逾期":44,"租客":"得信科技有限公司","_col":"物业费-逾期","费用类型":"公摊水费","_val":0,"_row":"得信科技有限公司"},{"逾期":44,"租客":"得信科技有限公司","_col":"电费-逾期","费用类型":"公摊水费","_val":0,"_row":"得信科技有限公司"},{"逾期":44,"租客":"得信科技有限公司","_col":"公摊水费-逾期","费用类型":"公摊水费","_val":44,"_row":"得信科技有限公司"},{"逾期":44,"租客":"得信科技有限公司","_col":"入场费-逾期","费用类型":"公摊水费","_val":0,"_row":"得信科技有限公司"},{"逾期":44,"租客":"得信科技有限公司","_col":"物业保证金-逾期","费用类型":"公摊水费","_val":0,"_row":"得信科技有限公司"},{"逾期":44,"租客":"得信科技有限公司","_col":"公摊电费-逾期","费用类型":"公摊水费","_val":0,"_row":"得信科技有限公司"},{"逾期":44,"租客":"梦港文化艺术发展有限公司","_col":"租金-逾期","费用类型":"公摊水费","_val":0,"_row":"梦港文化艺术发展有限公司"},{"逾期":44,"租客":"梦港文化艺术发展有限公司","_col":"水费-逾期","费用类型":"公摊水费","_val":0,"_row":"梦港文化艺术发展有限公司"},{"逾期":44,"租客":"梦港文化艺术发展有限公司","_col":"租金保证金-逾期","费用类型":"公摊水费","_val":0,"_row":"梦港文化艺术发展有限公司"},{"逾期":44,"租客":"梦港文化艺术发展有限公司","_col":"物业费-逾期","费用类型":"公摊水费","_val":0,"_row":"梦港文化艺术发展有限公司"},{"逾期":44,"租客":"梦港文化艺术发展有限公司","_col":"电费-逾期","费用类型":"公摊水费","_val":0,"_row":"梦港文化艺术发展有限公司"},{"逾期":44,"租客":"梦港文化艺术发展有限公司","_col":"公摊水费-逾期","费用类型":"公摊水费","_val":44,"_row":"梦港文化艺术发展有限公司"},{"逾期":44,"租客":"梦港文化艺术发展有限公司","_col":"入场费-逾期","费用类型":"公摊水费","_val":0,"_row":"梦港文化艺术发展有限公司"},{"逾期":44,"租客":"梦港文化艺术发展有限公司","_col":"物业保证金-逾期","费用类型":"公摊水费","_val":0,"_row":"梦港文化艺术发展有限公司"},{"逾期":44,"租客":"梦港文化艺术发展有限公司","_col":"公摊电费-逾期","费用类型":"公摊水费","_val":0,"_row":"梦港文化艺术发展有限公司"},{"逾期":44,"租客":"惠巢电子商务有限公司","_col":"租金-逾期","费用类型":"公摊水费","_val":0,"_row":"惠巢电子商务有限公司"},{"逾期":44,"租客":"惠巢电子商务有限公司","_col":"水费-逾期","费用类型":"公摊水费","_val":0,"_row":"惠巢电子商务有限公司"},{"逾期":44,"租客":"惠巢电子商务有限公司","_col":"租金保证金-逾期","费用类型":"公摊水费","_val":0,"_row":"惠巢电子商务有限公司"},{"逾期":44,"租客":"惠巢电子商务有限公司","_col":"物业费-逾期","费用类型":"公摊水费","_val":0,"_row":"惠巢电子商务有限公司"},{"逾期":44,"租客":"惠巢电子商务有限公司","_col":"电费-逾期","费用类型":"公摊水费","_val":0,"_row":"惠巢电子商务有限公司"},{"逾期":44,"租客":"惠巢电子商务有限公司","_col":"公摊水费-逾期","费用类型":"公摊水费","_val":44,"_row":"惠巢电子商务有限公司"},{"逾期":44,"租客":"惠巢电子商务有限公司","_col":"入场费-逾期","费用类型":"公摊水费","_val":0,"_row":"惠巢电子商务有限公司"},{"逾期":44,"租客":"惠巢电子商务有限公司","_col":"物业保证金-逾期","费用类型":"公摊水费","_val":0,"_row":"惠巢电子商务有限公司"},{"逾期":44,"租客":"惠巢电子商务有限公司","_col":"公摊电费-逾期","费用类型":"公摊水费","_val":0,"_row":"惠巢电子商务有限公司"}]

**Comment by dyx18539489507** [comment]
做个复现？两句代码怎么看
