### ISSUE TITLE
G2如何实现像echarts一样的数据缩放

### ISSUE THREAD

**Issue by 12345678starry** [antvis/g2#1366]
例子：https://echarts.baidu.com/examples/editor.html?c=line-tooltip-touch

**Comment by zhoustudent** [comment]
文档上有这部分内容好像是Transform进行数据转换，但没法像echarts一样可以返回上一步

**Comment by dengfuping** [comment]
- G2 3.x 版本需要通过 [g2-brush](https://github.com/antvis/g2-brush) 插件实现；
- `返回上一步`: 可以自行保存各个阶段的 filterData，然后按需回放即可实现
