### ISSUE TITLE
多折线图中 如何在初始化进入时,默认所有线条都取消选中状态

### ISSUE THREAD

**Issue by tangjing1989** [antvis/g2#1367]
G2 Version:3.5.3
Platform: vue 
有个场景 ,多条折线,需要在初始化页面时,做出类似 取消所有图例的选中状态.翻看文档没有找到类似的api

**Comment by dengfuping** [comment]
- 可以通过 `filter` 手动筛选，详细描述见 [FAQ-如何设置图例项的初始状态](https://www.yuque.com/antv/g2-docs/tutorial-faq#f9mgcv):
```js
chart.filter('field1', value => {
  return false;
});
```
