### ISSUE TITLE
混合图表中分组图如何单个隐藏或者显示

### ISSUE THREAD

**Issue by wangkun3877** [antvis/g2#1369]
* **G2 Version**: 3.5.7
* **Platform**:Web
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/40987646/62282652-7dc01800-b482-11e9-8b05-4fef399cfbc7.png)

混合图表（一个分组图【A和B】,二个折线图【折线图C和折线图D】）,并自定义图例（custom=true），然后在图例OnClick事件中 已经完成对折线图某个图例【C或D】点击隐藏显示自己（geom.show() Or geom.hide()）
请问如何对分组图geom(A或者B） 单个数据进行隐藏或者显示【比如点击图例A,实现A的柱状图隐藏，BCD继续显示，】，因为分组图中A和B的数据是在一起的（是同一个Geom），有什么方法吗来实现吗
谢谢！

**Comment by dyx18539489507** [comment]
做个复现？

**Comment by zqlu** [comment]
G2没有直接提供这样的操作。如果需要，可以通过interval geom getShapes函数获取所有shape，然后对shape进行hide，对canvas进行draw
