### ISSUE TITLE
两个连续图例对数据进行过滤，不能同时都生效。

### ISSUE THREAD

**Issue by liuxiaodong** [antvis/g2#137]
比如：图例 A 和 B

我先通过 A 过滤掉 70% 数据；再通过 B 过滤，B 又是在 100% 数据的基础上进行过滤的。

**Comment by dxq613** [comment]
你是怎么实现两个连续图例的？同一个图上两个连续图例的目的是什么，你想让他们产生什么样的组合效果？

**Comment by liuxiaodong** [comment]
chart.point().position('x*y').shape('circle').size('num1').color('#eee').size('num2')

 类似这样，通过两个 size 来实现的
