### ISSUE TITLE
自定义legend可否第二次点击后恢复状态

### ISSUE THREAD

**Issue by iwangx** [antvis/g2#1373]
官方示例地址：
[https://antv.alipay.com/zh-cn/g2/3.x/demo/line/line11.html](https://antv.alipay.com/zh-cn/g2/3.x/demo/line/line11.html)
可以点击右边的点然后隐藏线条，不过当第二次点击的时候样式没有恢复，不觉得这个是bug？

还有设计的不合理`itemTpl`返回的html里面必须要包含一个`class="g2-legend-marker"`的元素，否则会报一堆的错误，是不是设计的不合理？要是我不要自定义这个按钮怎么办？

**Comment by huzewei** [comment]
+1 目前也遇到这个问题

**Comment by huzewei** [comment]
我自己写了个监听方法搞好了， 看了下源码，自定义onclick后需要自己再去写数据筛选

**Comment by zqlu** [comment]
感谢反馈，母亲在使用itemTpl自定义html图例的时候，必须设置checked/color等属性，见https://codesandbox.io/s/g2-issue-1373-k60l3。

官方示例稍后更新。
