### ISSUE TITLE
使用svg渲染，再ie10ie11文本不显示

### ISSUE THREAD

**Issue by wangxin11411** [antvis/g2#1374]
* **G2 Version**:3.5.7
* **Platform**: win7 ie10 ie11
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

使用svg渲染图表，再ie10 和 ie11中测试坐标轴等tex标签中均没有文本内容，是否是bug或者需要开启某些配置。ie edge中无此问题

**Comment by zqlu** [comment]
@dengfuping g的svg版本浏览器支持是怎样的？

**Comment by zqlu** [comment]
> SVG 渲染，大多数浏览器都支持的，只不过部分浏览器存在一些差异，G 3.x 版本目前没有做这方面的兼容性处理，G 4.x 版本有计划做

在4.x版本支持
