### ISSUE TITLE
对线图加了shape('xxx')后多条线变为一条线

### ISSUE THREAD

**Issue by kevinpursuing** [antvis/g2#1375]
原本
![image](https://user-images.githubusercontent.com/20419163/62597389-77192100-b918-11e9-849d-9af04275de29.png)
加了shape
![image](https://user-images.githubusercontent.com/20419163/62597351-5650cb80-b918-11e9-9cbb-631d203fe60d.png)
![image](https://user-images.githubusercontent.com/20419163/62597360-5cdf4300-b918-11e9-842d-3bad17430297.png)

* **G2 Version**: 3.5.8-beta.1
* **Platform**:chrome

**Comment by dengfuping** [comment]
@kevinpursuing 无法重现，能否在 https://codesandbox.io 给出重现的例子?
