### ISSUE TITLE
select 和active配置互相影响，只配置select无效

### ISSUE THREAD

**Issue by Leannechn** [antvis/g2#1377]
API 文档这样描述
![image](https://user-images.githubusercontent.com/6812138/62762107-e7f83e80-baba-11e9-941b-7f7b771c7bba.png)
version 3.5.7
实际实现，官网demo，加select 和active配置
```js
  const geom = chart.interval().position('year*sales');
   geom.select(true, { style: { fill: 'red' } });
   geom.active(true)
```
https://antv.alipay.com/zh-cn/g2/3.x/demo/column/basic-column.html

![image](https://user-images.githubusercontent.com/6812138/62762262-458c8b00-babb-11e9-93b4-7a52a2dde946.png)

**Comment by zqlu** [comment]
在G2新版本3.5.8中已经修复，见https://codesandbox.io/s/g2-issue-1377-wm1ou
