### ISSUE TITLE
行分面和列分面的图形类表的顺序问题

### ISSUE THREAD

**Issue by menes127** [antvis/g2#138]
参考例子是https://antv.alipay.com/g2/demo/17-facet/row.html
行分面图第一个图是**SI1**
![aaa](https://user-images.githubusercontent.com/767234/27628923-22f753ca-5c23-11e7-9cb3-b692421ac054.png)

修改一行代码变成列分面图后，第一个图是**VS2**
chart.facet([,'clarity']);  =》  chart.facet(['clarity']);
![bbb](https://user-images.githubusercontent.com/767234/27628934-294a263a-5c23-11e7-8ff9-79e239bf4a79.png)

从上面两张图来看，第一张行分面图的顺序倒序了，请问如何优雅的解决？

**Comment by dxq613** [comment]
对于图表来说， y 轴的方向其实从下往上的，所以就出现了这个问题。这个是内置的顺序规则，没有开放出来配置
