### ISSUE TITLE
G2 如何获取线条的所有颜色

### ISSUE THREAD

**Issue by dd1994** [antvis/g2#1382]
![Screen Shot 2019-08-15 at 12 01 00](https://user-images.githubusercontent.com/4121510/63072106-9cc7ab00-bf54-11e9-847b-1fab211fab55.png)

如图，画出折线图后，如何获取到所有线条的颜色信息呢，因为需要在其它地方用到

**Comment by JumperMan** [comment]
![image](https://user-images.githubusercontent.com/3837430/63413260-eff59e00-c42b-11e9-8924-88e8b026f0b7.png)
`chart.line().position('month*temperature').color('city',['red','blue']);
  chart.point().position('month*temperature').color('city',['red','blue']).size(4)`

通过在line().color()里手动设置颜色, 这里的['red', 'blue']可以换为自定义参数/数组

**Comment by aa1011372655** [comment]
同学你好，首先我不太了解你的业务场景，仅就你想要的内容，给出以下源码，通过如下方式是能够获取的，
```
chart.getAllGeoms()[0].get('shapeContainer').get('children').forEach(c => {
  console.log(c.attr('stroke'));
});
```
另外如果你仅仅是想要默认的色值的话，theme中你能够得到你想要的https://github.com/antvis/g2/blob/a5387a08656108c25b4919efc8d7d4cf859cd0af/src/theme/default.js#L6

**Comment by dd1994** [comment]
我找到了 @aa1011372655 

```js
chart.getAllGeoms().forEach(geom => {
   console.log(geom.get("attrs").color.values)
})
```
