### ISSUE TITLE
带有分割空白的饼图显示错误

### ISSUE THREAD

**Issue by dengfuping** [antvis/g2#1384]
### Summary
官网给的一个例子中, 饼图中的环图显示,数字为0的在图上有显示颜色, 为1的反倒没有

### Environment
antv官方网址第三个,饼图的第三个环图
https://antv.alipay.com/zh-cn/g2/3.x/demo/pie/pie-slice.html
![image](https://user-images.githubusercontent.com/8602772/62442295-1c51bf00-b78a-11e9-9839-90d0e8f756ce.png)

### Expected behavior
数字为1的红色能出现在饼图中

### Actual behavior
数字0的在并图中有显示, 数字为1的反而没有

### Steps to reproduce the behavior
将 `data` 设置为:
```js
var data = [{
    type: '分类一',
    value: 52
  }, {
    type: '分类二',
    value: 17
  }, {
    type: '分类三',
    value: 30
  }, {
    type: '分类四',
    value: 0
  }, {
    type: 'Other',
    value: 1
  }];
```
- 点击运行

**Comment by zqlu** [comment]
新版本中已经修复
