### ISSUE TITLE
当折线图X轴上的数值远远小于设置的辅助线数值, 无法显示完整的辅助线

### ISSUE THREAD

**Issue by JumperMan** [antvis/g2#1385]
G2 Version: 3.0.11

Platform: win10, Chrome

Mini Showcase(like screenshots):
![image](https://user-images.githubusercontent.com/3837430/63411843-fcc4c280-c428-11e9-8141-cb3557468584.png)

![image](https://user-images.githubusercontent.com/3837430/63411713-b66f6380-c428-11e9-81b4-f457c9db22b7.png)

CodePen Link:

**Comment by aa1011372655** [comment]
同学你好，guide中的start和end就相当于数据的坐标，你的y坐标远远大于y轴值时才会出现这种情况，另外数据最大值是9840，不要超过这个数据，万只是一个标识位

**Comment by JumperMan** [comment]
> 同学你好，guide中的start和end就相当于数据的坐标，你的y坐标远远大于y轴值时才会出现这种情况，另外数据最大值是9840，不要超过这个数据，万只是一个标识位

hi, 目前有需求, 例子类似辅助线是300°C, 而Y坐标是室温, 如10°C至40°C的值, 这时候, 实际的辅助线远远大于Y轴的值, 导致辅助线显示不全, 希望的解决方案之一是: 将折线图缩放, 以便显示出辅助线

**Comment by aa1011372655** [comment]
> > 同学你好，guide中的start和end就相当于数据的坐标，你的y坐标远远大于y轴值时才会出现这种情况，另外数据最大值是9840，不要超过这个数据，万只是一个标识位
> 
> hi, 目前有需求, 例子类似辅助线是300°C, 而Y坐标是室温, 如10°C至40°C的值, 这时候, 实际的辅助线远远大于Y轴的值, 导致辅助线显示不全, 希望的解决方案之一是: 将折线图缩放, 以便显示出辅助线

可以通过设置y轴的最大值来解决这个问题，如https://www.yuque.com/antv/g2-docs/tutorial-scale#linear
设置max值就可以了，比如说300，线会自动根据y轴坐标自适应，缺陷就是最大值会变动，你要根据变化设置

**Comment by JumperMan** [comment]
@aa1011372655 thx!!
