### ISSUE TITLE
图表的 container 宽度改变，图表宽度不能自适应

### ISSUE THREAD

**Issue by ye10** [antvis/g2#1388]
* **G2 Version**:
3.5.8-beta.1

如题，浏览器窗口宽度改变，图表可自适应改变宽度；但是图表 container 的宽度改变不能自适应。

**Comment by aa1011372655** [comment]
同学你好，这部分建议自行监听后，调用changeWidth来实现
文档：https://www.yuque.com/antv/g2-docs/api-chart#changeWidth
