### ISSUE TITLE
【BUG】日历热力图，每个列的最后一个格子都无法触发 tips.

### ISSUE THREAD

**Issue by GlodenBoy** [antvis/g2#1389]
谷歌浏览器版本： 版本 76.0.3809.100（正式版本） （64 位）

BUG 地址： [https://antv.alipay.com/zh-cn/g2/3.x/demo/heatmap/calendar.html](url)

官方的热力图：

每个列的最后一个格子都无法触发 tips.

![image](https://user-images.githubusercontent.com/2329528/63581887-937cb500-c5ca-11e9-9b09-9fb81fd0b127.png)

**Comment by aa1011372655** [comment]
同学你好，这里是day的问题，如下修改可以修复：
```
// 加工数据
    // 增加涨幅、跌幅
    // 添加所属月、周几、每个月的第几周
    data.forEach(function(obj) {
      var date = new Date(obj['日期']);
      var month = date.getMonth();
      obj.month = month;
      // 这里需要减1，让day从零开始
      obj.day = date.getDay() - 1;
      obj.week = getMonthWeek(date).toString();
    });
```

**Comment by GlodenBoy** [comment]
多谢，辛苦 答疑~！
