### ISSUE TITLE
G2 4.0 新特性要求

### ISSUE THREAD

**Issue by dxq613** [antvis/G2#1394]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

* size 能否支持设置最大宽度，及百分比配置。https://github.com/antvis/g2/issues/474
* how to make nested facets：https://github.com/antvis/g2/issues/255
* 时间轴按照整月显示：https://github.com/antvis/g2/issues/455

**Comment by simaQ** [comment]
* Hive Plot https://github.com/antvis/g2/issues/694
* 多维数据分析，支持 view 的嵌套：https://github.com/antvis/g2/issues/786
* 如何支持图表与交互组件的联动：https://github.com/antvis/g2/issues/777

**Comment by hustcc** [comment]
- [ ] 纵向缩略轴能力 https://github.com/antvis/g2/issues/1211
- [ ] 数据更新的图形动画 https://github.com/antvis/g2/issues/1175 更新动画的效果不太好，视觉上是上下跳动的感觉（参考 https://bost.ocks.org/mike/path/）
- [ ] 组件的层级位置，完全有用户定义，上层可以给一个推荐位置 https://github.com/antvis/g2/issues/1177

**Comment by zqlu** [comment]
- [ ] G2 4.0 Roadmap #1357 
- [ ] 地图等比例缩放 #1364 
- [ ] 鼠标滚轮放大缩小功能 #1371

**Comment by dxq613** [comment]
图例反选需求：#477
