### ISSUE TITLE
字云中纵向词语的leave动画不连贯

### ISSUE THREAD

**Issue by ahugh19** [antvis/G2#1397]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv.alipay.com/zh-cn/g2/3.x/demo/other/word-cloud.html](https://antv.alipay.com/zh-cn/g2/3.x/demo/other/word-cloud.html)

### Steps to reproduce
在官网词云示例代码的最后一行chart.render()后一行加上以下代码用以触发leave动画
```Javascript
setTimeout(() => {
    chart.changeData([]);
  }, 3000);
```
点击运行，等待3s，留意词云leave时纵向排列的单词的动画。（注意：水平呈现的词语是正常的，纵向呈现的词语才会出问题）

### What is expected?
更新字云示例中的数据以触发leave动画后，纵向呈现的词语不应该先翻转至水平再退出，动画应该连贯。

### What is actually happening?
更新字云示例中的数据以触发leave动画后，纵向呈现的词语会先翻转至水平再退出，动画不连贯
![词云issue---AntV---Google-Chrome-2019-08-28-15-01-01-1](https://user-images.githubusercontent.com/29140985/63837802-b6cea800-c9ae-11e9-94ee-55939fd7323f.gif)
![词云issue---AntV---Google-Chrome-2019-08-28-15-01-01-2](https://user-images.githubusercontent.com/29140985/63837803-b7673e80-c9ae-11e9-8a38-5fc3f11a22ba.gif)

| Environment | Info |
|---|---|
| g2 | 3.5.7 |
| System | windows |
| Browser | Chrome 76.0.3809.100（正式版本） （64 位） |

---
这个问题是一个 [老issue](https://github.com/antvis/g2/issues/1112) ，刚才被关闭了，回复是无法复现，但我按照我的描述试了一下还是有问题，试了现在的3.5.7版本也一样。详见前面的动图，如果不清晰可以看这里的[录屏视频](https://pan.baidu.com/s/1ie3wlp-MGDvNPeHZkS3Gpw) 提取码: jpqg

**Comment by simaQ** [comment]
4.0 已解决
