### ISSUE TITLE
facet的rowTitle是否支持自定义 html 文本

### ISSUE THREAD

**Issue by menes127** [antvis/g2#140]
参考 https://antv.alipay.com/g2/api/chart.html#facet

facet的rowTitle是否支持自定义 html 文本，比如像https://antv.alipay.com/g2/doc/tutorial/start/label.html#自定义-html-文本  一样自定义renderer？

**Comment by dxq613** [comment]
不支持，考虑在新版本重构的时候增加这个功能。
