### ISSUE TITLE
angular8下使用zoom和drag交互不正常

### ISSUE THREAD

**Issue by coloz** [antvis/g2#1400]
* **G2 Version**:3.5.8-beta.1
* **Platform**:PC+chrome+angular8
* **Mini Showcase(like screenshots)**:
```
this.chart.interact('drag').interact('zoom');
```
* **CodePen Link**:

我直接使用drag和zoom，没有修改其他配置，zoom只能放大，不能缩小；
drag只能向前拖拽，向后拖拽，图表数据就会消失。
很是奇怪，不知道其他angular用户正常。

**Comment by dxq613** [comment]
不熟悉 angular，试试非 angular 环境下。

**Comment by zhaopeiym** [comment]
@coloz  请问你是怎么使用的，我也是angular 使用npm 导入的 @antv/g2@3.5.17，为什么ts提示找不到interact 方法。

![image](https://user-images.githubusercontent.com/5820324/110411665-f1e28900-80c5-11eb-8533-96d3388991e2.png)


安装的是3.5.17 ts文件显示的是3.0.4
![image](https://user-images.githubusercontent.com/5820324/110411732-09217680-80c6-11eb-8f32-020cec3e8df6.png)

难道使用npm安装使用的是阉割版？

**Comment by coloz** [comment]
@zhaopeiym import * as G2 from '@antv/g2' ，然后和js里一样用法

**Comment by zhaopeiym** [comment]
![image](https://user-images.githubusercontent.com/5820324/110416287-69b4b180-80ce-11eb-9c17-0e27fa040cf0.png)

![](https://user-images.githubusercontent.com/5820324/110411665-f1e28900-80c5-11eb-8533-96d3388991e2.png)

是的，为啥我的找不到interact 方法呢？

**Comment by zhaopeiym** [comment]
@coloz 

![image](https://user-images.githubusercontent.com/5820324/110416442-b3050100-80ce-11eb-9e8e-63ca55264437.png)

你的G2.Chart 点进去 ts文件显示的是什么版本？

**Comment by hustcc** [comment]
3.5 的写法，应该是：

```ts
import G2 from '@antv/g2';
```

不知道这个是不是带来这个问题的原因。@zhaopeiym 另外不建议翻历史不相关的 issue，给其他人带来打扰。
