### ISSUE TITLE
x 轴坐标最后一个值被挡住, 显示不全

### ISSUE THREAD

**Issue by liaocaiming** [antvis/G2#1402]
x 轴坐标最后一个值如果长度太长会( 如: 2019-12-12, 只能显示2019-1 )被挡住, 显示不全

**Comment by simaQ** [comment]
4.0 已经解决。可以 `chart.scale()` 接口中为时间类型的字段配置 `showLast` 属性

**Comment by ColinChen2** [comment]
> 4.0 已经解决。可以 `chart.scale()` 接口中为时间类型的字段配置 `showLast` 属性

type: 'timeCat' 也会有这个问题，showLast可以也支持一下？

**Comment by JuneYaooo** [comment]
> > 4.0 已经解决。可以 `chart.scale()` 接口中为时间类型的字段配置 `showLast` 属性
> 
> type: 'timeCat' 也会有这个问题，showLast可以也支持一下？

可以的：
chart.scale('date', {
    type: 'timeCat',
    showLast: true
  });
