### ISSUE TITLE
图标示例中的基础面积图无法显示

### ISSUE THREAD

**Issue by alwaysBillly** [antvis/G2#1403]
* **G2 Version**: 3.5.3
* **Platform**: windows 10, Firfox 70.0b1 (64 位)
![TIM图片20190902114535](https://user-images.githubusercontent.com/22104460/64089129-37a6ee80-cd77-11e9-9b22-17eee7858335.png)

* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

https://antv.alipay.com/zh-cn/g2/3.x/demo/area/area1.html, 
此页面的基础面积图, "某公司烟花国内累计销售额趋势", 这张图在FireFox浏览器中无法显示,

**Comment by simaQ** [comment]
怀疑是时间类型的问题，尝试将下面代码中的 `type: 'timeCat'` 删除试试：

```ts
chart.scale('Data', {
      range: [0, 1],
      tickCount: 10,
      type: 'timeCat' // 删除这句定义
    });
```
