### ISSUE TITLE
Brush选取起点在图表之外的时候报错

### ISSUE THREAD

**Issue by Hao8816** [antvis/G2#1405]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv.alipay.com/zh-cn/g2/3.x/demo/other/brush-line.html](https://antv.alipay.com/zh-cn/g2/3.x/demo/other/brush-line.html)

### Steps to reproduce
当选择的起点在图表外的时候，鼠标按下-> 移动-> 松开，就会发现startPoint为null的错误

### What is expected?
不应该报错

### What is actually happening?
报错了

| Environment | Info |
|---|---|
| g2 | 3.5.3 |
| System | Macos 10.13.6 |
| Browser | Chrome 75.0.3770.100（正式版本） （64 位） |

**Comment by yinyiGit** [comment]
遇到同样的问题，望尽快修复

**Comment by Leannechn** [comment]
forceFit 后，plotRange 没有更新。新增区域无法绘制

**Comment by simaQ** [comment]
试试 4.0 的 `chart.interaciton('brush');`
