### ISSUE TITLE
鼠标框选放大区域，柱状图会超出边界

### ISSUE THREAD

**Issue by DevilViy** [antvis/g2#141]
如图所示：
![image](https://user-images.githubusercontent.com/21967852/28005213-f9d5933c-657b-11e7-86b9-2cbc70443a64.png)

**Comment by kuangyunsheng** [comment]
所有类型的图表在放大时，其中的“几何标记 geom“都有可能超出几何标记应绘制的区域

**Comment by dxq613** [comment]
因为 x 轴是时间类型，时间类型的坐标轴两边没有留空白，所以这时候可以考虑将 x 轴对应的字段声明成 type: 'timeCat' 这时两边会留下绘制柱状图的空白
