### ISSUE TITLE
label的折线如何随着宽度变化而自适应

### ISSUE THREAD

**Issue by Sayid1** [antvis/G2#1412]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/amazing-turing-eik2x)

### Steps to reproduce
官网的[示例](https://antv.alipay.com/zh-cn/g2/3.x/demo/pie/pie8.html)，label的折线可以随着宽度变化而自适应，但是我复制到本地运行，打开F12改变窗口宽度的时候，label的折线位置没有变化

### What is expected?
折线位置能随宽度自适应，像官网示例应用

### What is actually happening?
宽度变化，折线位置保持不变

| Environment | Info |
|---|---|
| g2 | 3.5.7 |
| System | masOS |
| Browser | chrome最新 |

**Comment by Sayid1** [comment]
没有人吗 @paleface001 @

**Comment by simaQ** [comment]
官方实例是在 chart.render() 即图表绘制后通过 G 来实现的，所以不再 G2 的图表渲染流程中，如果需要响应图表宽度变化的话，你需要监听图表窗口变化，然后重新渲染 label.
