### ISSUE TITLE
自定义 Tooltip 鼠标无法进入内部，enterable 已设置为 true

### ISSUE THREAD

**Issue by ye10** [antvis/g2#1414]
* **G2 Version**:
3.5.8-beta.1

Tooltip 设置：
      shared: true,
      crosshairs: true,
      inPlot: true,
      enterable: true,
      offset: 16,

如下图所示，tooltip 和鼠标之间的间距比较大，移动鼠标时，tooltip 就会变化，无法进入想要进入的 tooltip
![image](https://user-images.githubusercontent.com/19183494/64399346-b0b98500-d09a-11e9-8a61-acfeff0f9b46.png)

**Comment by simaQ** [comment]
https://github.com/antvis/component/pull/65

**Comment by simaQ** [comment]
已修复，发布  @antv/components  0.3.5 版本，重新安装下 G2 依赖
