### ISSUE TITLE
官方示例半圆进度条bug

### ISSUE THREAD

**Issue by Pasoul** [antvis/G2#1417]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv.alipay.com/zh-cn/f2/3.x/demo/gallery/simple-gauge.html](https://antv.alipay.com/zh-cn/f2/3.x/demo/gallery/simple-gauge.html)

### Steps to reproduce
1秒后延迟改变数据

### What is expected?
半圆进度条从75回退到0

### What is actually happening?
半圆进度条跑了一圈回到0

| Environment | Info |
|---|---|
| g2 | 3.5.7 |
| System | Mac 10.14.3 |
| Browser | chrome 版本 76.0.3809.100（正式版本） （64 位） |

效果：
![image](https://user-images.githubusercontent.com/22902187/64473491-3112df80-d19a-11e9-8fc8-883e5114ab40.png)

**Comment by simaQ** [comment]
这个是动画的问题，demo 上是通过自定义动画实现的，没有考虑数据更新的场景，如果需要支持数据更新，你按照 demo 或者 API 文档完善下动画即可。

F2 的问题，建议到 F2 仓库下提交。
