### ISSUE TITLE
请问如何动态切换皮肤

### ISSUE THREAD

**Issue by KellenHe** [antvis/g2#1422]
* **G2 Version**:
3.4.8
* **Platform**:
angular8
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

使用G2.Global.setTheme设置全局皮肤后，必须要刷新浏览器才可以更改吗？
请问有没有方法可以直接改变图形的皮肤。

**Comment by hustcc** [comment]
可以参考 issue：https://github.com/antvis/g2/issues/1468
