### ISSUE TITLE
htmlContent + drag + zoom ，缩放操作后tooltip - htmlContent会失效。

### ISSUE THREAD

**Issue by Leannechn** [antvis/G2#1424]
version ： 3.5.1

htmlContent + drag + zoom ，缩放操作后tooltip - htmlContent会失效。

demo htmlContent ：
 https://antv.alipay.com/zh-cn/g2/3.x/demo/component/tooltip-html-content.html#
加上drag & zoom
  chart.interact('drag', {
      type: 'XY'
    }).interact('zoom', {
      type: 'XY'
    });

**Comment by JdesEva** [comment]
GEO地图开启drag会出现tooltip显示问题
![image](https://user-images.githubusercontent.com/37232561/65004750-18d85880-d930-11e9-803b-bf288b285402.png)
