### ISSUE TITLE
图例legend可以显示但点击无筛选效果可能是什么原因

### ISSUE THREAD

**Issue by lvovl** [antvis/g2#143]
如下简单设置 chart.legend({ position: "bottom" } );
值是改变默认位置，有可能是什么原因使得legend不能筛选，legend 上hover是有鼠标变化效果的

**Comment by dxq613** [comment]
有个选项  leaveChecked,保证了会留下一项不被取消选中，你可以改成 false

chart.legend({
  position: 'bottom',
  leaveChecked: false
});

**Comment by lvovl** [comment]
加上了还是没有效果，图例呈现一种点什么都没有毫无反应的效果 pity T T

**Comment by lvovl** [comment]
版本过低 更新后没有这种问题了
