### ISSUE TITLE
关于数据更变后的处理的bug

### ISSUE THREAD

**Issue by lzxb** [antvis/g2#145]
### 场景
图表初始化的时候，是有数据的，但是图表的数据更改后为[]数组的时候，页面会绘制报错

### 几种尝试，均为失败
第一种： `chart.changeData([])`时，有的图表会报错，绘制失败

第二种：我尝试在数组为[]时，对图表进行`chart.clear()`，等图表数据不为[]时再进行chart.repaint()重绘

第三种：我尝试在数组为[]时，对图表进行`chart.destroy()`，等图表数据不为[]时再重新new一个新的实例，但是我发现在`chart.destroy()`时，dom节点也被销毁了，其实chart不应该去把dom节点给删除掉，假如这个dom节点是由react、vue创建的，g2对他进行删除，可能会造成dom节点和第三方框架之前的关联造成错误

**Comment by dxq613** [comment]
更新到最新版本试试

**Comment by lzxb** [comment]
已经是最新的`2.3.6`版本

**Comment by dxq613** [comment]
changeData([]) 我测试过 折线图、区域图、柱状图、饼图都没报错，哪些图表报错？

**Comment by lzxb** [comment]
我目前测到的是饼状图会，` dodge is not support linear attribute, please use category attribute!`

**Comment by lzxb** [comment]
似乎还有其他的，但是我现在也记不得了。我现在使用的方法是手动在vue中添加一个dom，等数据为`[]`时则销毁到图表，有数据的时候再重新初始化

**Comment by dxq613** [comment]
饼图不会有 dodge 的，那说明是 intervalDodge。没有数据的话，不知道参与dodge 的数据类型，所以这时候你可以定义一下数据类型

```js
chart .source([], {
 fieldA: {type: 'cat'}
})

```

**Comment by dxq613** [comment]
我测试了下 intervalDodge 确实会报错，明天发布2.3.7 来不及修复，2.3.8 进行修复

**Comment by lzxb** [comment]
嗯，刚才我也测了一下，确实还会报错。随时关注！只是不知道官方啥时候把源码放出来，有时间学习一下。

**Comment by dxq613** [comment]
本来是要下个月开源的，事情太多，网站之类的也需要重新做，各种开源文档之类的，推迟到11月份正式开源。

**Comment by lzxb** [comment]
666坐等放大招
