### ISSUE TITLE
组件浮窗不消失

### ISSUE THREAD

**Issue by Ethan92** [antvis/g2#1450]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://preview.pro.ant.design/dashboard/analysis](https://preview.pro.ant.design/dashboard/analysis)

### Steps to reproduce
鼠标移动到组件上，等浮窗出现后，快速移动鼠标离开组件

### What is expected?
鼠标离开组件后浮窗马上消失

### What is actually happening?
如果组件比较多，排列比较紧密，鼠标快速移动后会有浮窗留在上面，影响整个页面的显示

| Environment | Info |
|---|---|
| g2 | 3.5.7 |
| System | macOS Mojave 10.14.6 |
| Browser | Google Chrome  76.0.3809.132 |

如图，鼠标移动快时，浮窗会一直停留

![image](https://user-images.githubusercontent.com/19512080/64931940-4361dd00-d86e-11e9-874a-d130b8472477.png)

![image](https://user-images.githubusercontent.com/19512080/64931943-48bf2780-d86e-11e9-9168-7d942da8a733.png)

**Comment by dxq613** [comment]
3.5.9-beta.2 已经修复
