### ISSUE TITLE
圆角柱状图数据差距显示不正确

### ISSUE THREAD

**Issue by fengfengyaya** [antvis/g2#1455]
![image](https://user-images.githubusercontent.com/50482406/65131166-55d84400-da31-11e9-9fd6-48ce6fbe3765.png)
官网中圆角柱状图 数据差的过大时圆角显示不正确

**Comment by dxq613** [comment]
这个demo 是自定义 shape 实现的，可以在代码中判断数据的大小，控制弧度显示。也可以增大图表的高度，这个不是 G2 本身的问题。
