### ISSUE TITLE
如果值为小数的情况下很容易出现y轴 2.00000000000000000001 这样的情况

### ISSUE THREAD

**Issue by appLhui** [antvis/g2#146]
数据如果是比较接近的小数的情况下，折线图的y轴 很容易出现小数 失精度 的情况 这样的情况如何解？

**Comment by dxq613** [comment]
这个问题是浏览器的浮点数计算的问题：

这是浏览器中的运算结果
```js
21.6 + 0.3 

21.900000000000002
```
可以在列定义里面 加个formatter，格式化一下数据。
