### ISSUE TITLE
饼图如何控制位置

### ISSUE THREAD

**Issue by kuangyanit** [antvis/g2#1460]
### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g2-reproduction-template-1fr2y)

### Steps to reproduce
见repo

### What is expected?
如何控制repo中饼图的位置，期望可以偏左（或是可以自由控制）

### What is actually happening?
似乎无法控制饼图位置

| Environment | Info |
|---|---|
| g2 | 3.5.7 |
| System | macOS Mojave 10.14.6 |
| Browser | Google Chrome 78.0.3904.9 |

**Comment by hustcc** [comment]
You can have a try with `padding` config.

```diff
var chart = new G2.Chart({
  container: "root",
  forceFit: true,
  height: 400,
+ padding: [0, 150, 0, 0] // top, right, bottom, left
});
```
