### ISSUE TITLE
g2当列过多时 是否可以定义滚动条

### ISSUE THREAD

**Issue by xz-zhang** [antvis/g2#147]
带滚动条的Chart： [](url)http://jsfiddle.net/mbhavfwm/

**Comment by dxq613** [comment]
这个功能做到 g2 里面不太合适

**Comment by xz-zhang** [comment]
额~ 但是列过多时 柱状图每列会缩得很小，如果设置了size 又会堆叠在一起...

**Comment by dxq613** [comment]
可以考虑增加 Chart 的宽度，外层容器进行滚动

**Comment by xz-zhang** [comment]
谢谢~ @dxq613
