### ISSUE TITLE
隐藏 X/Y label 时去除留白

### ISSUE THREAD

**Issue by HenryQW** [antvis/g2#1488]
- [X] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
隐藏 X/Y label 时留白过大，无法有效利用空间
![image](https://user-images.githubusercontent.com/5896343/65559162-77559600-df31-11e9-9541-88378ad9a52d.png)

### What does the proposed API look like?
暂无。希望在 label 和 legend 未开启的状态下，chart 可以利用目前的留白空间。

**Comment by hustcc** [comment]
```diff
var chart = new G2.Chart({
    container: 'mountNode',
    forceFit: true,
    height: window.innerHeight,
+   padding: 0,
});
```

加上 padding = 0 试试看~

**Comment by HenryQW** [comment]
非常感谢！居然在文档里漏掉了这个属性。。
