### ISSUE TITLE
type definitions typo

### ISSUE THREAD

**Issue by kagawagao** [antvis/g2#1489]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/antvis/g2/blob/41c934fe20528966e0aacb18742be87012f6a102/src/index.d.ts#L369](https://github.com/antvis/g2/blob/41c934fe20528966e0aacb18742be87012f6a102/src/index.d.ts#L369)

### Steps to reproduce
https://github.com/antvis/g2/blob/41c934fe20528966e0aacb18742be87012f6a102/src/index.d.ts#L369

### What is expected?
`AxisTitle`

### What is actually happening?
`AxisTile`

| Environment | Info |
|---|---|
| g2 | 3.5.7 |
| System | MacOS 10.15 |
| Browser | Chrome Canary 79.0.3922.0 |

**Comment by hustcc** [comment]
@kagawagao Do you have time to join in and contribute with a pr?
