### ISSUE TITLE
G2 4.0 第一次 CR

### ISSUE THREAD

**Issue by hustcc** [antvis/g2#1511]
### code style

- [ ] tsdoc 格式、lint
- [ ] 各类注释规范

### chart / view

- [x] nit: 三层 group 显式 zIndex 设置
- [x] typescript 私有属性和方法都使用 private 标识，不需要 _ 开头
- [x] chart constant 放到外面，统一只有一个 constant 文件
- [x] Datum 结构值 any（通用类型定义放到顶层的 interface 中）
- [x] AxisCfg ScaleCfg 等用户传入的配置都叫做 xxxOption
- [x] Chart View 类中的属性：三层 group protected，viewBBox、filteredData、coordinateBBox、themeObject private
- [x] view 中设置配置的 API，链式调用
- [x] view.coordinate 方法中，创建 coordinate 实例。view.coordinate(‘rect’).scale();
- [x] renderComponent 中组件 layer 的处理 
- [x] 父子 view 共享 data 数据，父 view.changeData，需要遍历子 view.changeData
- [x] 父子数据共享：data、coordinate、scale（参考之前的）
- [x] view.clear() 清空计算属性、缓存属性
- [x] view.destroy 需要清空三层 group
- [x] chart.destroy 需要销毁 g.Canvas（super）
- [x] removeView 需要 view.destroy
- [x] view 生命周期事件
- [x] view.setCoordinate 删除

### geometry

- [x] Geometry.color 方法类型定义拆成多行
- [x] 重复调用 render，绘图有 bug

**Comment by simaQ** [comment]
**Geometry** code review 如下：
- 一些更好的代码写法： https://github.com/antvis/g2/pull/1503
- private 不使用 _
- Element 构造函数初始化
- Geometry 属性的类型定义 tooltipOption 等
- Geometry 构造函数传参类型定义 + 初始化属性
+ Geometry 图形属性方法设置使用 _.set()
+ init() rename initial()
+ ScaleUtil export 每个函数

**Comment by hustcc** [comment]
先关闭了，文档格式统一搞。
