### ISSUE TITLE
请问K线图（蜡烛图）如何添加guid标记？

### ISSUE THREAD

**Issue by yinxiaorong** [antvis/g2#1515]
请问K线图（蜡烛图）如何添加guid标记？

![avatar](http://tva1.sinaimg.cn/large/007X8olVly1g7e6dtb0sfj307g06w0sr.jpg)

**Comment by dxq613** [comment]
通过 guide().html() 来自定义 guide,https://www.yuque.com/antv/g2-docs/api-chart#a002edda
