### ISSUE TITLE
请问K线图（蜡烛图）如何添加guid标记？ 

### ISSUE THREAD

**Issue by yinxiaorong** [antvis/g2#1516]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以为K线图添加标记

### What does the proposed API look like?
类似这样的  ![avatar](http://tva1.sinaimg.cn/large/007X8olVly1g7e6dtb0sfj307g06w0sr.jpg)

**Comment by dxq613** [comment]
用 guide().html() 既可以解决这个问题。https://www.yuque.com/antv/g2-docs/api-chart#a002edda

**Comment by yinxiaorong** [comment]
> 用 guide().html() 既可以解决这个问题。https://www.yuque.com/antv/g2-docs/api-chart#a002edda

这个我尝试了，只能打一个标记，我这边有个需求是动态在指定的点加上maskpoint

**Comment by yinxiaorong** [comment]
> 用 guide().html() 既可以解决这个问题。https://www.yuque.com/antv/g2-docs/api-chart#a002edda

而且html方式需要手动指定位置，我想在蜡烛图上动态标记，而且还需要支持放大缩小，这样的话实现起来太麻烦了
