### ISSUE TITLE
 Tooltip默认过滤掉value为null 的内容，是否能够增加配置

### ISSUE THREAD

**Issue by xile611** [antvis/G2#1518]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
数值为null，仍然需要在tooltip中展示对应的文案，如下图的场景

![image](https://user-images.githubusercontent.com/6111424/65760995-9c741f80-e150-11e9-9b66-743ac13ff922.png)

### What does the proposed API look like?
tooltip.showNil

### 相关代码

https://github.com/antvis/g2/blob/a79580977cd308c3f0b0e867607753750db5b87c/src/geom/mixin/tooltip.js#L426

https://github.com/antvis/g2/blob/a79580977cd308c3f0b0e867607753750db5b87c/src/geom/mixin/tooltip.js#L436

**Comment by hustcc** [comment]
@xile611 好的，我感觉是很不错的配置，建议你后面有这些 feature 诉求，直接提 PR 即可，这样的效率是最高的。
