### ISSUE TITLE
legend左侧位置不显示

### ISSUE THREAD

**Issue by huxiaoyun** [antvis/G2#1525]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/huxiaoyun/g2Bug/blob/master/leftLegendInvisibile.html](https://github.com/huxiaoyun/g2Bug/blob/master/leftLegendInvisibile.html)

### Steps to reproduce
直接打开 html 文件即可

### What is expected?
legend在左侧正确显示

### What is actually happening?
legend位置超出canvas范围不可见

| Environment | Info |
|---|---|
| g2 | 3.5.8 |
| System | mac |
| Browser | chrome |

**Comment by huxiaoyun** [comment]
https://github.com/antvis/g2/blob/master/src/chart/controller/legend.js#L382 
看源码应该是这里计算有问题。

**Comment by simaQ** [comment]
4.0 已解决，欢迎使用。
