### ISSUE TITLE
面积图为什么x轴坐标会多出来

### ISSUE THREAD

**Issue by huangchaofei** [antvis/g2#1529]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。
如图所示 示例上是好的
![image](https://user-images.githubusercontent.com/25143078/66449351-5b9cd480-ea87-11e9-9d20-8b1251107ea9.png)

**Comment by dxq613** [comment]
#1530 是同一个问题，x 轴对应的 scale 上加个 nice: false 就能解决问题
