### ISSUE TITLE
面积图x轴右边有空白

### ISSUE THREAD

**Issue by huangchaofei** [antvis/g2#1530]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g2-reproduction-template-6ipi1)

### Steps to reproduce
x轴右边会有空格

### What is expected?
x轴所有点都有数据

### What is actually happening?
x轴右边会有空格

| Environment | Info |
|---|---|
| g2 | 3.4.1 |
| System | window7 |
| Browser | chrome |

**Comment by simaQ** [comment]
请提供：
1. 能够说明问题的运行结果截图
2. 可完整复现的代码

如七天内为提供，该 issue 将会被关闭。感谢配合

**Comment by dxq613** [comment]
可以在 x 轴对应的 scale 上加上参数 nice: false 就不会有空白了
