### ISSUE TITLE
高频率绘制卡顿问题

### ISSUE THREAD

**Issue by Naclplus** [antvis/G2#1532]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv.alipay.com/zh-cn/f2/3.x/index.html](https://antv.alipay.com/zh-cn/f2/3.x/index.html)

### Steps to reproduce
历史数据有1000条，两组图表，一个分时线状图，一个成交量柱状图，通过Websocket大约每10-20毫秒就会刷新数据，频繁的调用changeData

### What is expected?
如何解决高频率传入数据导致的卡顿

### What is actually happening?
丢帧，卡顿严重
在低端机器会导致崩溃

| Environment | Info |
|---|---|
| g2 | 3.3.4 |
| System | IOS/Android |
| Browser | 默认原生/Safari/WebView |

**Comment by simaQ** [comment]
请移步至 F2 仓库：https://github.com/antvis/F2

**Comment by ZMY1005** [comment]
请问频繁调用changeData导致页面卡顿有办法优化吗
