### ISSUE TITLE
data=[] 空数据下，time 类型的Axis 会展示一个1970.

### ISSUE THREAD

**Issue by Leannechn** [antvis/G2#1533]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/484b3508](https://riddle.alibaba-inc.com/riddles/484b3508)

### Steps to reproduce
1. data = []
2. scale 设置为time

### What is expected?
希望无数据的时候坐标轴刻度为空

### What is actually happening?
空数据下展示了一个 1970的刻度

| Environment | Info |
|---|---|
| g2 | 3.5.8 |
| System | mac |
| Browser | chrome |

---
稍后补充codepen重现地址

**Comment by simaQ** [comment]
4.0 已解决
