### ISSUE TITLE
几何标记设置label为false时报错， 与文档描述不一致

### ISSUE THREAD

**Issue by fingerpan** [antvis/g2#1537]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g2-reproduction-template-ecoh8)

### Steps to reproduce
都可重现

### What is expected?
label 设置为 false, 应该不开启。

### What is actually happening?
语法报错

| Environment | Info |
|---|---|
| g2 | 3.5.8 |
| System | 所有 |
| Browser | 所有 |

---
文档中可设置label为false, 但实际上没有支持

**Comment by dxq613** [comment]
看了下源代码， label(false) 是不支持的，是 api 文档写错了，不声明 .label() 就没有 label 了。下个版本增加这个特性
