### ISSUE TITLE
边缘气泡tooltip内容换行

### ISSUE THREAD

**Issue by yinyiGit** [antvis/G2#1538]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv.alipay.com/zh-cn/g2/3.x/demo/point/bubble-text.html](https://antv.alipay.com/zh-cn/g2/3.x/demo/point/bubble-text.html)

### Steps to reproduce
鼠标从右下角进入最右侧气泡，立马停止

### What is expected?
针对边缘气泡，无论鼠标从哪个方向选中，其tooltip内容不折行

### What is actually happening?
tooltip内容换行

| Environment | Info |
|---|---|
| g2 | 3.5.3 |
| System | Macos 10.13.6 |
| Browser | Chrome 75.0.3770.100（正式版本） （64 位） |

---
双图联动效果（选中一个图的气泡，找到另一个图中相应的气泡）中，有根据气泡位置，手动触发气泡mousEnter，再显示tooltip的需求。但联动边缘气泡时，计算显示的tooltip内容换行，影响效果。

**Comment by luhaifeng666** [comment]
所以这个问题后来咋解决的OTZ...
