### ISSUE TITLE
请问圆饼图／圆环图，当所有数据都为0的时候，能不能显示图形，并且均等分，而不是消失？

### ISSUE THREAD

**Issue by mcuking** [antvis/g2#154]
请问圆饼图／圆环图，当所有数据都为0的时候，能不能显示图形，并且均等分，而不是消失？
图1为g2的，图2为echart的
![image](https://user-images.githubusercontent.com/22924912/28992240-7bfc5a88-79c9-11e7-8b45-c82e2f8c9140.png)

![image](https://user-images.githubusercontent.com/22924912/28992235-6efd0346-79c9-11e7-9c31-307888eefe01.png)

**Comment by dxq613** [comment]
这个是不同策略导致的，由于G2是数据到图形的映射，0 / sum 都是0 所以这时候强制有大小也不合理。你可以在外面做，判断都是0 的时候，所有的值都设置成一个值即可，无论多大、多小

**Comment by mcuking** [comment]
好的，谢谢啊

**Comment by liunian** [comment]
@dxq613 这种方案会有点小问题，展示数值会是自定义的非 0 值而不是实际的 0；占比也不是 0%
