### ISSUE TITLE
IE11浏览器使用折线图，控制台报错：对象不支持“remove”属性或方法

### ISSUE THREAD

**Issue by yuanzhian** [antvis/G2#1540]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7mqvg)

### Steps to reproduce
当鼠标在折线图左右滑动时候，鼠标上的竖线不跟着移动

### What is expected?
当鼠标在折线图左右滑动时候，鼠标上的竖线也跟着移动。即对象支持“remove”属性或方法。通过查阅资料解决方案：IE只支持removeNode方法。

### What is actually happening?
当鼠标在折线图左右滑动时候，鼠标上的竖线不跟着移动。控制台报错：对象不支持“remove”属性或方法。

| Environment | Info |
|---|---|
| g2 | 3.5.8 |
| System | windows |
| Browser | IE11 |

---
这个问题设计到我们的功能主流程，麻烦重视下，谢谢！
源代码报错部分如下：
_proto.clear = function clear() {
    var container = this.get('container');

    if (this.get('htmlContent')) {
      container && container.remove();
    } else {
      var titleDom = find(container, TITLE_CLASS);
      var listDom = find(container, LIST_CLASS);

      if (titleDom) {
        titleDom.innerHTML = '';
      }

      if (listDom) {
        listDom.innerHTML = '';
      }
    }
  };

**Comment by simaQ** [comment]
尝试升级到 3.x 最新版本。

**Comment by chenzio** [comment]
> 尝试升级到 3.x 最新版本。

升级到了3.5.12版本 但是在IE11上遇到了这个相同的问题 请问下这个问题是在哪个版本解决的
