### ISSUE TITLE
viser-vue使用问题：坐标轴标签密度不生效

### ISSUE THREAD

**Issue by zhangmengyi** [antvis/G2#1545]
你好，我在使用坐标轴配置时，想更改标签显示密度density，但是不生效。请问是否我使用有问题呢？求帮忙看下

配置如下：
`<v-chart :forceFit="true" :height="240" :padding="chartConfig.chartPadding" :data="lineData" :scale="chartConfig.scale" class="chartClass">
        <v-tooltip dataKey="key*used"/>
        <v-axis dataKey="key" :tick="chartConfig.tick" :line="chartConfig.lineStyle" :label="chartConfig.label"/>
        <v-line
          position="key*used"
          :size="2"/>
      </v-chart>`

`chartConfig = {
    lineStyle: {
      stroke: '#ddd'
    },
    chartPadding: [10, 48, 30, 48],
    tick: {
      ticks: ['2019-09-01'],
      tickCount: 6,
      tickInterval: 5
    },
    label: {
      density: 0.9,
      offset: -6,
      rotate: 90
    },
    scale: [
      {
        dataKey: 'value',
        alias: '存储信息',
        formatter(value: string | number) {
            return comdify(value)
        }
      },
      {
        dataKey: 'key',
        mask: 'YYYY-MM-DD'
      }
    ]
  };`

**Comment by simaQ** [comment]
tickCount 和 tickInterval 不可一起使用。
