### ISSUE TITLE
饼图PieLabel插件自定义label2样式

### ISSUE THREAD

**Issue by jiangzhenxiang** [antvis/g2#1549]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://antv.alipay.com/zh-cn/f2/3.x/demo/pie/pie-click.html
如此官方示例，当label的文字较长是，会被饼图盖住。我想自定义label2的宽高等样式，现在能实现吗

### What does the proposed API look like?
pie-label：  https://www.yuque.com/antv/f2/pie-label

**Comment by zqlu** [comment]
这是f2的demo，可以到f2仓库提issue
