### ISSUE TITLE
可否在图表事件中增加鼠标滚动事件

### ISSUE THREAD

**Issue by wanjiaHuang** [antvis/G2#1555]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
某种情况下，图表的数据量可能很大，但是展示的空间有限，所以用户可能某些时候只想看放大图表中某小部分的数据进行观看。Slider 滑块插件虽然可以某种程度上轻微地解决这个问题（此插件貌似只支持x轴地滑块，并且只支持鼠标拖动地模式），但是终究不够灵活。
图表事件api文档：https://www.yuque.com/antv/g2-docs/tutorial-chart-event
Slider滑块api文档：https://www.yuque.com/antv/g2-docs/api-slider

### What does the proposed API look like?
希望G2本身能集成滑动条这个功能（这是一种很常见地应用场景），可以分为滑动条显示（要不要展示滑动条），滑动条功能（要不要通过鼠标滚动来放大或缩小图表某部分数据）。如果暂时无法实现该功能。希望在图表事件中增加鼠标滚动事件，这样子某些希望有此功能的开发者，可以通过此事件来自定义控制滑块。

**Comment by zqlu** [comment]
缩略轴和滚动条将在https://github.com/antvis/g2plot提供。

**Comment by simaQ** [comment]
4.0 已支持
