### ISSUE TITLE
如何控制图例的顺序

### ISSUE THREAD

**Issue by lvvlan** [antvis/g2#1556]
看了下legend好像是根据数据顺序决定的展示顺序，如果我的数据是无序的，我想控制图例有序展示，该怎么做？

**Comment by zqlu** [comment]
目前没有配置项支持，考虑4.0支持。

**Comment by simaQ** [comment]
可以做到的，只是要通过 `chart.scale()` 接口，在列定义的 values 属性中指定数据的顺序: 

https://antvis.github.io/g2/zh/docs/manual/tutorial/scale#cat

![image](https://user-images.githubusercontent.com/6628666/69129052-99f6cc00-0ae8-11ea-94c2-15f255046e17.png)

**Comment by ZengZhenfei** [comment]
这个功能很有必要！！！

**Comment by ColinChen2** [comment]
@simaQ 写死的适用性不太好。比如需要对一段value进行统计函数AVG等，然后根据结果来排序图例。
