### ISSUE TITLE
基础图如何展示图例

### ISSUE THREAD

**Issue by lvvlan** [antvis/g2#1558]
官网中的基础折线图（https://antv.alipay.com/zh-cn/g2/3.x/demo/line/basic.html）
或基础柱状图该如何展示图例？直接加chart.legend(true)好像不会起作用。

**Comment by zqlu** [comment]
图例需要配合颜色、大小、形状区分不同的数据类型映射来使用，详见[文档](https://www.yuque.com/antv/g2-docs/tutorial-legend)。
