### ISSUE TITLE
在 v3 版本是否有等高线 (contour) 的实现 demo

### ISSUE THREAD

**Issue by JoshOY** [antvis/G2#1559]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
根据v3更新文档 https://www.yuque.com/antv/g2-docs/tutorial-g2-v3-changes ，等高线的旧 API chart.contour() 已经废弃并被 chart.polygon() 替代了，但是新版本的 Demo 中并没有给出相关的例子

### What does the proposed API look like?
在 Demo 中给出等高线相关的例子

**Comment by simaQ** [comment]
等高线目前暂未提供。
