### ISSUE TITLE
chart.guide().rect(from, to, [cfg])绘制辅助框可以使用渐变色吗？

### ISSUE THREAD

**Issue by devzhujiang** [antvis/g2#156]
请问，辅助框的显示样式配置cfg可以使用渐变色吗？

**Comment by dxq613** [comment]
可以设置 fill，参考渐变色的设置：https://antv.alipay.com/g2/api/canvas.html#通用属性值
```js
fill: 'l (45) 0:#ffff00 1:#00ffff'
```
![image](https://user-images.githubusercontent.com/1264678/29061968-67eb4578-7c52-11e7-928b-6a235bd8ec38.png)
