### ISSUE TITLE
双轴图表legend点击事件处理有问题

### ISSUE THREAD

**Issue by gonenoob** [antvis/G2#1560]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv.alipay.com/zh-cn/g2/3.x/demo/other/double-axes.html](https://antv.alipay.com/zh-cn/g2/3.x/demo/other/double-axes.html)

### Steps to reproduce
点击图表legend，显隐处理有问题

### What is expected?
正确处理显示图表隐藏

### What is actually happening?
图表隐藏后无法再通过点击显示

| Environment | Info |
|---|---|
| g2 | 3.5.1 |
| System | mac |
| Browser | chrome |

**Comment by simaQ** [comment]
可以使用 4.0 的交互语法实现，另外我们默认也封装了对应的交互行为。https://g2.antv.vision/zh/examples/interaction/component#legend-visible-filter
