### ISSUE TITLE
点击图例高亮对应的geom和legend

### ISSUE THREAD

**Issue by lvvlan** [antvis/G2#1565]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/static-uky2n)

### Steps to reproduce
如代码所示

### What is expected?
期望点击图例时，可以高亮当前的选择，其他的图例和对应的geom暗调

### What is actually happening?
没有任何反应

| Environment | Info |
|---|---|
| g2 | 3.5.9 |
| System | macos |
| Browser | chrome |

**Comment by simaQ** [comment]
4.0 已支持：https://g2.antv.vision/zh/examples/interaction/component#legend-highlight
