### ISSUE TITLE
F2和G2的API差别

### ISSUE THREAD

**Issue by xcs-go** [antvis/g2#1578]
G2和F2的API差别很大吗？之前有一个移动端的项目用了F2，现在想让pc端也使用这个项目的页面，发现原来在移动端可以点击的，但是放在pc上就点击不了了。

**Comment by simaQ** [comment]
图形语法部分差别基本没有，主要在交互还有图表组件的配置上，F2 是为移动端设计的，只支持移动端的事件，所以才如你描述的那样，点击不生效。

**Comment by shinyruo-nmsl** [comment]
> 图形语法部分差别基本没有，主要在交互还有图表组件的配置上，F2 是为移动端设计的，只支持移动端的事件，所以才如你描述的那样，点击不生效。

那在移动端使用g2会有问题吗？g2的打包体积是不是要比f2大一些

**Comment by hustcc** [comment]
> 那在移动端使用g2会有问题吗？g2的打包体积是不是要比f2大一些

G2 包会大一些，但是也可以支持移动端，F2 更偏重蓄势和数据显示，G2 更侧重数据分析。
