### ISSUE TITLE
数值类型的数据设置成category类型时图形绘制错误

### ISSUE THREAD

**Issue by zqlu** [antvis/G2#1579]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/g2plot-numeric-cateogry](https://stackblitz.com/edit/g2plot-numeric-cateogry)

### Steps to reproduce
x字段数据为number类型，scale type设置成category

### What is expected?
图形绘制准确，label正常 tooltip正常

### What is actually happening?
label错位，tooltip错误，图形错误

| Environment | Info |
|---|---|
| g2 | 3.5.9 |
| System | osx |
| Browser | * |

**Comment by dxq613** [comment]
这个在 g2 3.x 之前处理过，会自动的将数字转换成为分类。但是有两种情况一种确实是将数字展示成分类，还一种是用于枚举类型，所以这个地方就有了特殊的逻辑。如果忽视后一种情况，直接转换就行。

**Comment by zqlu** [comment]
> 这个在 g2 3.x 之前处理过，会自动的将数字转换成为分类。但是有两种情况一种确实是将数字展示成分类，还一种是用于枚举类型，所以这个地方就有了特殊的逻辑。如果忽视后一种情况，直接转换就行。

能不能把现在的numeric操作去掉，同时在tooltip findPoint地方需要[比较查找](https://github.com/antvis/g2/blob/725de128a0b6163b7ebfdd6b780a18d60c557d9f/packages/g2/src/element/controller/tooltip.ts#L128)的时候，用xScale.scale(xValue) > xScale.scale(lastXValue)来比较。这样修复可以不？

**Comment by zqlu** [comment]
@dxq613 @simaQ numeric操作还造成了下面例子的中bug：xFields中的`null`数据点没有画出来，在echarts和highcharts中均画出来了

![image](https://user-images.githubusercontent.com/1142242/67651278-437bef00-f97b-11e9-8b00-b36e5e693c23.png)

**Comment by hustcc** [comment]
这个问题 3.x 改风险很高，是否可以在 4.0 里面尝试改掉，主要看是否是一个合理的 feature？ @dxq613 @simaQ

**Comment by SunnySally** [comment]
这个问题好像还在。
可以先在buildIndexMap的时候把translateIndexMap的key值转换成字符串类型的吗，这样估计还是走原来的大逻辑整体改动不大？
主要是在一些用户输入的场景下，拿到的原始数据通常就是数字类型的，当然也可以在调用G2之前先做处理全部转换成字符串类型，但感觉G2内部可以对数值类型做个兼容比较好
