### ISSUE TITLE
#Legend  mode:’single‘ 模式有问题

### ISSUE THREAD

**Issue by EGBAR** [antvis/g2#158]
1 多组数据时， legend启用single mode，但是图表会一下子显示所有的columns而不是默认显示第一个被选中的。
![image](https://user-images.githubusercontent.com/16821601/29158479-c55c8be0-7ddd-11e7-9e1e-29e6e62ada02.png)
2 建议legend添加默认选中的API

**Comment by dxq613** [comment]
通过filter 初始化是否选中
```js
chart.filter('field', ['xxx']);
```
