### ISSUE TITLE
G2 4.X 事件机制问题

### ISSUE THREAD

**Issue by paleface001** [antvis/g2#1590]
```private initEvents() {
    // 三层 group 中的 shape 事件都会通过 G 冒泡上来的
    this.foregroundGroup.on('*', this.onEvents);
    this.middleGroup.on('*', this.onEvents);
    this.backgroundGroup.on('*', this.onEvents);
    // 自己监听事件，然后向上冒泡
    this.on('*', this.onViewEvents);
  }
```

这样的写法无法正常trigger view上的事件，因为底层G group上的事件是通过shape事件冒泡上来的。G2层的事件逻辑是：当鼠标移动到view上没有shape的区域，只要在viewRange内斗应该trigger事件，现在的写法是只有鼠标移动到view上被shape填充的区域才会trigger相应的事件。

**Comment by hustcc** [comment]
现在的 plot:mouseenter, plot:mousemove, plot:mouseout 三个事件是针对画布的（Coordinate 区域）。
