### ISSUE TITLE
[4.0] view 的 visibility 设置

### ISSUE THREAD

**Issue by paleface001** [antvis/G2#1592]
如题，view上是不是也需要提供show()和hide()方法，以及visibility属性

**Comment by hustcc** [comment]
之前 3.x 好像没有吧，这个 visibility 用在什么地方，怎么用？

**Comment by paleface001** [comment]
> 之前 3.x 好像没有吧，这个 visibility 用在什么地方，怎么用？

用来控制view的可见性，上层g2plot的图层有这样的需求

**Comment by simaQ** [comment]
交互场景用到比较多，geometry、Element 可能都需要

**Comment by hustcc** [comment]
@paleface001 好的，我看看怎么实现~

**Comment by simaQ** [comment]
和 #1763 同一个问题，先关闭，直接看 #1763
