### ISSUE TITLE
点击柱状图阴影时取不到data数据，旧版本是可以的

### ISSUE THREAD

**Issue by cy-luckey** [antvis/G2#1598]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https:
![image](https://user-images.githubusercontent.com/42604522/67848410-930b1800-fb3f-11e9-840e-1d23766e5850.png)
//antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。

**Comment by simaQ** [comment]
获取不到，你可以在点击之后，通过 https://g2-v3.antv.vision/zh/docs/api/chart/#getsnaprecords 接口获取对应的数据。

**Comment by chentianxin** [comment]
> 获取不到，你可以在点击之后，通过 https://g2-v3.antv.vision/zh/docs/api/chart/#getsnaprecords 接口获取对应的数据。

v4.1.35没这个api了 该怎么办呢

**Comment by duziten** [comment]
这个问题可以调整 Scale：
```js
chart.scale('value', {
    nice: true,
    type: 'log' // pow 都可以
});
```
