### ISSUE TITLE
极坐标系下，网格线配置hideLastLine配置项有歧义问题

### ISSUE THREAD

**Issue by fingerpan** [antvis/G2#1629]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g2-reproduction-template-kp27q)

### Steps to reproduce
1. 在极坐标系下的柱状图，
2. 配置 gird.align = 'center'

显示坐标系的玫瑰图

个人原因分析：
在极坐标系下，g2为了实现 align: 'center' 配置时，对倒数第二条网格线，处理成 1，导致产生了两条尾线。代码中如下：
if (!isLinear && nextValue === 1) {
      return 1;
 }
在components仓库中，对尾线的隐藏是采用 idx，忽略渲染数组中最后一个，所以其实，倒数第二条网格线，还是被渲染出来。

从严格意义上将，倒数第二条线应该不能处理为尾线，而应该直接忽略渲染。

### What is expected?
两条尾线能够正常隐藏

### What is actually happening?
出现两条尾线，导致只隐藏了一条尾线

| Environment | Info |
|---|---|
| g2 | 3.5.9 |
| System | 所有 |
| Browser | 所有 |

**Comment by fingerpan** [comment]
建议在 https://github.com/antvis/g2/blob/master/src/chart/controller/axis.js
96行 - 98行改为
 ` javascript
if (!isLinear && nextValue === 1) {
     return null;
}
`

**Comment by fingerpan** [comment]
https://codesandbox.io/s/g2-reproduction-template-kp27q
例子查看，
设置了隐藏最后一条网格线，并没有生效。

**Comment by simaQ** [comment]
欢迎直接提交 PR。
