### ISSUE TITLE
怎么取消掉框选select的默认行为？

### ISSUE THREAD

**Issue by PerezYuan** [antvis/g2#163]
版本：2.3.8
我用
```
chart.setMode('select');
chart.select('rangeX');
```
想在`rangeselectend`里面自己去做一些交互，但是chart自己会有一个缩放的行为，有办法去掉吗？

**Comment by dxq613** [comment]
这块功能实现的时候，其实我们也是比较纠结的，当时考虑过仅提供事件，让用户自己实现交互，但是真正实践过程中，发现用户的成本太高，而且大多数的场景都是进行数据过滤。

下面的版本中，我们会将所有的这些交互实现成工具栏插件，所有的行为用户都可以进行定制。

在 2.x 中如果想实现的话，只能自己监听dom 事件去处理了。
