### ISSUE TITLE
[4.0] chart.coordinate().xxx() 导致图表绘制失败

### ISSUE THREAD

**Issue by simaQ** [antvis/G2#1635]
单独使用 Geometry 创建是没有问题的。

定位到原因为：

https://github.com/antvis/g2/blob/4.x/src/chart/layout/index.ts#L109

坐标轴在坐标系发生 transpose 后，x 轴由原先的 bottom 变为 left，y 轴由原先的 left 变为 top  @hustcc

**Comment by hustcc** [comment]
已经解决。
