### ISSUE TITLE
带热力图的地图DEMO，开启tooltips，部分坐标内容显示异常

### ISSUE THREAD

**Issue by amoycode** [antvis/G2#1637]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv.alipay.com/zh-cn/g2/3.x/demo/map/with-heatmap.html](https://antv.alipay.com/zh-cn/g2/3.x/demo/map/with-heatmap.html)

### Steps to reproduce
```
chart.tooltip(true, {
    showTitle: false,
    itemTpl: '<li><span style="background-color:{color};" class="g2-tooltip-marker"></span>{name}: {value}</li>',
});

userView.heatmap().position('longitude*latitude').color('value', '#F51D27-#FA541C-#FF8C12-#FFC838-#FAFFA8-#80FF73-#12CCCC-#1890FF-#6E32C2').size(window.innerHeight / 20).style({
      blur: window.innerHeight / 15
 }).tooltip('name*value', (name, value) => {
    return { name, value };
});
```

### What is expected?
正常的显示效果：
![image](https://user-images.githubusercontent.com/18238708/68831598-b90cec80-06e9-11ea-8432-5a37b02ccb0f.png)

### What is actually happening?
部分坐标显示效果:
![image](https://user-images.githubusercontent.com/18238708/68831652-e063b980-06e9-11ea-90d8-be082a34ae40.png)

| Environment | Info |
|---|---|
| g2 | 3.5.9 |
| System | mac os |
| Browser | chrome 78 |

---
为什么会这样？如何不显示这些奇怪的tooltips？

**Comment by simaQ** [comment]
通过 Geometry.tooltip() 接口配置你想要显示的数值：https://g2-v3.antv.vision/zh/docs/api/geometry/#tooltip
