### ISSUE TITLE
如何调整分组柱状图(dodge)中单项内容间柱与柱之间的间距？

### ISSUE THREAD

**Issue by patsoncy** [antvis/g2#165]
使用 intervalDodge 处理分组柱状图时，未能找到调整柱形之间间距的配置，不支持自定义？
![issue](https://user-images.githubusercontent.com/10925753/29456949-7d03d15a-844a-11e7-9c69-9d2d48164192.png)

**Comment by dxq613** [comment]
等3.0 吧，已经开发完毕，内测中。公测版下个月应该会放出，11月份正式开源。

![image](https://user-images.githubusercontent.com/1264678/29704502-aa093bd8-89ac-11e7-9375-01a2b2a2750f.png)
