### ISSUE TITLE
[4.0]数据相关属性的统一命名

### ISSUE THREAD

**Issue by simaQ** [antvis/G2#1653]
## 问题描述：
目前存储原始数据、绘制数据以及映射后数据的属性命名感觉有些许混乱：

* 在 geometry 数据处理阶段：
    + `origin`: 存储映射后的数据，原始数据（_origin）以及关键点信息

结构如下：
```ts
 {
  /** 原始数据 */
  _origin: Datum;
  /** 关键点坐标集合 */
  points?: Point[];
  /** 下一个 shape 的关键点坐标集合 */
  nextPoints?: Point;
  x?: number[] | number;
  y?: number[] | number;
  color?: string;
  shape?: string;
  size?: number;
}
```
    + `_origin`: 存储原始数据

在 shape 绘制完毕之后，又会将全部的绘制信息存在 shape.get('origin') 中，而这里的 origin 结构如下，看结构，还会包含 `origin` 字段，即 `shape.get('origin').origin`...

```ts
 /** x 坐标 */
  x: number;
  /** y 坐标 */
  y: number | number[];
  /** 映射的 shape 类型 */
  shape?: string | undefined | null;
  /** size 映射值 */
  size?: number | undefined | null;
  /** 映射的颜色值 */
  color?: string | null | undefined;
  /** 样式 */
  style?: LooseObject | null;
  /** 是否在极坐标下 */
  isInCircle?: boolean | undefined;
  /** 对应的原始数据记录 */
  data?: Datum | Data;
  /** 进行图形映射后的数据记录 */
  origin?: Datum;
  /** 构成 shape 的关键点  */
  points?: ShapeVertices;
  /** 下一个数据集对应的关键点 */
  nextPoints?: ShapeVertices;
  /** Geometry.Text 需要 */
  text?: string | null;
  /** 数据是否发生层叠 */
  isStack?: boolean;
  /** 是否连接空值，对 Path Line Area 这三种 Geometry 生效 */
  connectNulls?: boolean;
```

另外在 tooltip、label 等组件中，还会使用 `point` 变量名来存储上述 origin 的数据... 相同的变量名，结构却不一致，相同的数据变量名却不一致，虽然目前只有 shape.get('origin') 是对外暴露的，但是这样混乱的命名也不太利于内部代码的维护。

### 方案

对外暴露的属性，即存储在 shape 上的数据仍然使用 `origin` 来命名，但是对于存储映射后的数据使用  `mappingData` 命名，使用 `data` 存储原始数据，但是仍会暴露  `_origin` 字段来存储原始数据。

**Comment by simaQ** [comment]
@dxq613 @hustcc @paleface001

**Comment by hustcc** [comment]
> 对外暴露的属性，即存储在 shape 上的数据仍然使用 origin 来命名，但是对于存储映射后的数据使用 mappingData 命名，使用 data 存储原始数据，但是仍会暴露 _origin 字段来存储原始数据。

是指 shape 的 origin 数据包含 两部分吗？

```ts
{
  mappingData,
  data
}
```

另外，如果 `_origin` 是需要用到的数据，就不用要 下划线了吧，给人感觉是很临时的取数。

**Comment by simaQ** [comment]
> > 对外暴露的属性，即存储在 shape 上的数据仍然使用 origin 来命名，但是对于存储映射后的数据使用 mappingData 命名，使用 data 存储原始数据，但是仍会暴露 _origin 字段来存储原始数据。
> 
> 是指 shape 的 origin 数据包含 两部分吗？
> 
> ```ts
> {
>   mappingData,
>   data
> }
> ```
> 
> 另外，如果 `_origin` 是需要用到的数据，就不用要 下划线了吧，给人感觉是很临时的取数。

恩，是的，3.x shape.get('origin') 的数据结构就包含映射后的数据和原始数据。而且 origin 的命名无法让人快速知道这份数据的内容，同时又同 _origin 混淆
