### ISSUE TITLE
交互机制以及交互行为整理

### ISSUE THREAD

**Issue by simaQ** [antvis/G2#1671]

**Comment by dxq613** [comment]
* 概要设计：https://www.yuque.com/antv/g2-docs/rmpuqz
* 详细设计：https://www.yuque.com/antv/g2-docs/bg5o88

**Comment by dxq613** [comment]
[ ]  tooltip
[ ] element 的 active
[ ] element 的 selected （仅单选）
[ ] element active 时的背景
[ ] 分类图例
[ ] 图例项 Hover, element 高亮
[ ] 图例项勾选, element 过滤
[ ] 连续图例
[ ] 过滤
[ ] 框选过滤
2.28
[ ] slider 交互
[ ] 框选（selected)
[ ] element active， axis, legend 对应的选项高亮
[ ] 面包屑交互
[ ] 指标卡交互
[ ] 滚轮 zoom 
[ ] scrollbar

**Comment by simaQ** [comment]
-  [ ] 连续图例与图形之间的交互联动

参考：https://www.echartsjs.com/examples/zh/editor.html?c=map-HK

![image](https://user-images.githubusercontent.com/6628666/71497873-0bb6f800-2895-11ea-8936-8ba8ee85085b.png)
![image](https://user-images.githubusercontent.com/6628666/71497889-24bfa900-2895-11ea-82d1-ba2a4525efbc.png)
