### ISSUE TITLE
图表组件完善及扩展

### ISSUE THREAD

**Issue by simaQ** [antvis/G2#1675]
* 需要新增的图表组件：
   - [x] Slider 缩略轴
   - [ ] 滚动条
   - [x] Region-filter
   - [x] data-marker
   - [x] data-region: [折线图 | G2](https://g2.antv.vision/zh/examples/gallery/line#line3)

* 完善的功能
- [x] 图例的翻页

**Comment by zhangyu1818** [comment]
大佬，滚动条现在是不是还暂时不支持呢？

**Comment by atdow** [comment]
缩略轴打包之后失效

**Comment by yehoan** [comment]
滚动条在折线图里面失效...  直方图 是OK 的 ...
