### ISSUE TITLE
BUG frame.rows参数问题

### ISSUE THREAD

**Issue by lvovl** [antvis/g2#168]
`frame.rows([3,"A", null]).s()`
与
`frame.rows([1,2,3]).s()`
得到结果相同
population	age	State	type
310504	Under 5 Years	AL	a
552339	5 to 13 Years	AL	a
259034	14 to 17 Years	AL	a

**Comment by dxq613** [comment]
frame.rows 其实在g2的图表内部没有真正的使用，
一直在思考 Frame 的功能，当时增加Frame 主要参考了 R语言的 dataframe ，但是在真正的使用过程中，更多的使用静态方法、进行统计。除了增大了开销外，其实没太大的好处。

所以我们在3.0 中，将所有的数据处理、所有的统计函数、布局算法等全部提取到一个 data-set 模块，除了实现 2.x 中的功能外，还提供了数据更新、图表交互的功能。

**Comment by lvovl** [comment]
赞 希望新版有更加优质的文档
