### ISSUE TITLE
htmlTemplate自定义label如何围绕饼图

### ISSUE THREAD

**Issue by Linefate** [antvis/g2#1685]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---
饼图使用 html 自定义 `label；`
![image](https://user-images.githubusercontent.com/38858428/69402610-4c21d400-0d33-11ea-93fd-e2e30c8a2b2e.png)
`label('percent', {
        // 自定义下方百分比文字
        formatter: function formatter(val, item,count) {
          // return item.point.range + ': ' + val+'\xa0\xa0\xa0'+count + '人'
          return item.point.range + ': ' + val
        },
        htmlTemplate: (text, item) => {
          const point = item.point // 每个弧度对应的点
          let count = point['count']
          return '<div style="color: #363636;font-size: 13px;white-space: nowrap;">' + text + '<span style="margin-left: 8px;margin-right:8px;color: '+ point.color+'">'+count+'人</span>' + '</div>' // 自定义 html 模板
        }
      })`
请问要如何才能将自定义的html模板围绕着饼图的label
![image](https://user-images.githubusercontent.com/38858428/69402717-a6229980-0d33-11ea-9991-751b98f90989.png)

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。

**Comment by simaQ** [comment]
并没有复现。
![image](https://user-images.githubusercontent.com/6628666/69508365-74e2dd00-0f70-11ea-9a35-6f9a8755ac5d.png)

PS： 一点小建议，提交 issue 的时候，请务必：

1. 提供版本号
2. 提交完整的可复现代码
3. 格式化代码

以方便我们快速定位、排查问题，谢谢、

**Comment by Linefate** [comment]
好的，谢谢




钱倩
仲恺农业工程学院


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"SimaQ"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月25日(星期一) 上午10:45
收件人:&nbsp;"antvis/g2"<g2@noreply.github.com&gt;;
抄送:&nbsp;"Line"<2754668951@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/g2] htmlTemplate自定义label如何围绕饼图 (#1685)




并没有复现。
 
 
PS： 一点小建议，提交 issue 的时候，请务必：
  
提供版本号
 
提交完整的可复现代码
 
格式化代码
  
以方便我们快速定位、排查问题，谢谢、
