### ISSUE TITLE
一个chart多个view的情况下，图例重复。

### ISSUE THREAD

**Issue by jiladahe1997** [antvis/G2#1698]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
此复现链接是官方图表简单修改而成：
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/boring-browser-eek0q?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
如上述链接中：我期望将一个chart使用两个view来绘制。 第一个view包含了除了中国以外的国家数据，第二个view只包含了中国的数据。

然而结果却产生了重复的图例，并且只有第一个图例有点击事件。

### What is expected?
图例不会重复 或者 两个图例都有各自的点击效果。

### What is actually happening?
图例重复显示，且只有一个图例有点击事件。

| Environment | Info |
|---|---|
| g2 | 3.5.11 |
| System | macOS: 10.14.5 |
| Browser | chrome 78.0.3904.108 |

---
业务场景：期望将南沙群岛单独绘制到中国地图的右下角：如此图所示: http://cimg2.163.com/sports/2007/3/24/2007032423285934312.jpg
故需要将数据分为两个view来绘制。

**Comment by simaQ** [comment]
4.0 已经解决
