### ISSUE TITLE
文档构建时有很多 error

### ISSUE THREAD

**Issue by afc163** [antvis/G2#1704]
应该是 markdown 里代码格式和对应语言不匹配的问题。

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/507615/69612338-742e7180-106a-11ea-8404-4c52b5b8f43f.png">

**Comment by simaQ** [comment]
阿吼吼吼吼... 被发现了，我这周抽空修改下，嘻嘻

**Comment by afc163** [comment]
提交时关联一下 issue，保持好的习惯。
