### ISSUE TITLE
g2文字云  所有value的值相同时  图表无法正常渲染

### ISSUE THREAD

**Issue by yutao331763646** [antvis/G2#1708]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g2-reproduction-template-6ipi1)

### Steps to reproduce
直接在g2,文字云官网例子中修改数据源，把所有value的值改为相同数值，图表无法正常渲染，原因如下：
````
  fontSize(d) {
        if (d.value) {
          return ((d.value - min) / (max - min)) * (80 - 24)   24;
        }
        return 0;
      }
````
如果所有value相同： max = min，  所以amx-min=0，造成所有fontsize=0，建议：
````
  fontSize(d) {
        if (d.value) {
          return ((d.value - min) / (max   1 - min)) * (80 - 24)   24;
        }
        return 0;
      }
````

### What is expected?
正常渲染图表

### What is actually happening?
无法正常渲染图表

| Environment | Info |
|---|---|
| g2 | 3.5.11 |
| System | ^3.5.8 |
| Browser | chrome 78 |

**Comment by yutao331763646** [comment]
`  fontSize(d) {
        if (d.value) {
          return ((d.value - min) / (max  + 1 - min)) * (80 - 24)   24;
        }
        return 0;
      }`

**Comment by yutao331763646** [comment]
````
  fontSize(d) {
        if (d.value) {
          return ((d.value - min) / (max   1 - min)) * (80 - 24)   24;
        }
        return 0;
      }
````

**Comment by simaQ** [comment]
感谢
