### ISSUE TITLE
4.0 文档及 demo 计划

### ISSUE THREAD

**Issue by simaQ** [antvis/G2#1709]
- [x] 文档结构及内容 @再飞 
   https://github.com/antvis/g2/tree/4.x/docs

- [x] demo 结构及内容 @ 逍为
   https://github.com/antvis/g2/tree/4.x/examples

**Comment by hustcc** [comment]
DEMO 分工

@hustcc 

 - [ ] 折线图
 - [ ] 面积图
 - [ ] 柱形图
 - [ ] 条形图

@simaQ 

 - [ ] 饼图
 - [ ] 雷达图
 - [ ] 仪表盘

以下不需要，g2plot 包装。或者是否提供 Geometry（不内置加载）？

 - [ ] 水波图
