### ISSUE TITLE
[4.0] bug & 优化汇总

### ISSUE THREAD

**Issue by hustcc** [antvis/G2#1715]
> 常驻、置顶，直到全部修复。所有 bugfix 的 pr ref 到这个 issue。

**Comment by 18402025768** [comment]
饼图数据传入为数值的时候,其中一个数值为负数的问题

const data = [
  { item: '事例一', percent: -0.4 },
  { item: '事例二', percent: 0.21 },
  { item: '事例三', percent: 0.17 },
  { item: '事例四', percent: 0.13 },
  { item: '事例五', percent: 0.09 }
];
const chart = new G2.Chart({
  container: 'container',
  forceFit: true,
  height: 500
});
chart.source(data, {
  percent: {
    formatter: val => {
      //val = (val * 100) + '%';
      return val;
    }
  }
});
chart.coord('theta', {
  radius: 0.75
});
chart.tooltip({
  showTitle: false,
  itemTpl: '<li><span style="background-color:{color};" class="g2-tooltip-marker"></span>{name}: {value}</li>'
});
chart.intervalStack()
  .position('percent')
  .color('item')
  .label('percent', {
    formatter: (val, item) => {
      return item.point.item + ': ' + val;
    }
  })
  .tooltip('item*percent', (item, percent) => {
    percent = percent * 100 + '%';
    return {
      name: item,
      value: percent
    };
  })
  .style({
    lineWidth: 1,
    stroke: '#fff'
  });
chart.render();

![image](https://user-images.githubusercontent.com/20633660/69770801-5590bd80-11c5-11ea-918b-0844aabebd3c.png)

**Comment by simaQ** [comment]
> axis line 和 grid 重叠的问题

这个应该是可以通过绘制顺序解决

**Comment by simaQ** [comment]
- [ ] 刻度线和文本没有对应

**Comment by simaQ** [comment]
- [ ] 当鼠标离开画布时，没有触发 plot:leave 事件 @hustcc 

如下图。右侧 padding 为 0，鼠标离开的时候没有触发 plot:leave 事件，导致 tooltip 没有隐藏
![image](https://user-images.githubusercontent.com/6628666/69786983-7d4c4980-11f6-11ea-94d6-4f11116baaea.png)

**Comment by simaQ** [comment]
- [ ] 饼图默认填充上 x 字段

**Comment by simaQ** [comment]
* 4.0 为了达到功能的最大化，已将 3.x 中的一些内置的 tooltip 的配置规则删除，即各个配置项之间不再存在耦合，用户可以按需设置配置项，带来自由度的同时降低了 3.x 开箱即用的便利，但是从 4.0 的定位以及给用户的灵活度来看，这种牺牲是可取的。
- [ ] tooltip 交互，需要等交互语法 @simaQ 
- [ ] 饼图 label @simaQ 
- [ ] @hustcc  设置了起始和结束角的 theta 坐标系，自动布局时出错，复现DEMO： http://localhost:8000/zh/examples/pie/basic#pie-ranged
```ts
chart.coordinate(‘theta’, {
  startAngle: Math.PI, /// 起始角度/
  endAngle: Math.PI * (3 / 2) /// 结束角度/
});
```
- [ ] 如何关闭自动布局？当用户手动设置了 padding，是否就应该按照用户设置的为准 @hustcc 
- [ ] 以下 3.x 接口目前不支持，为所有的图例进行配置，4.0 是否有必要支持？@hustcc
```ts
chart.legend({
  offsetY: -20
});
```
- [ ]  图例布局有误 @hustcc 
[image:0D9D3501-C2A6-43F3-A72D-50408560C551-1525-000010EC866E5F40/A6A74650-80BB-491F-B68D-15FF6F30DEA0.png]
- [ ] 饼图更新动画 @simaQ

**Comment by simaQ** [comment]
- [ ] http://localhost:8000/zh/examples/pie/rose#rose-ranged 网格线绘制错误 
- [ ] 确定 chart.annotation().arc() 的参数 @simaQ
- [ ] chart.scale({ sync: true })  不支持，demo: http://localhost:8000/zh/examples/gauge/gauge#tick

**Comment by simaQ** [comment]
- [ ] chart.changeSize() 的时候。annotation 更新有问题 @hustcc 
![image](https://user-images.githubusercontent.com/6628666/70134194-8cce0580-16c2-11ea-88bc-52c38cf4f02e.png)

**Comment by simaQ** [comment]
- [ ] 自定义图例如何在 chart.legend() 上进行配置，要同 3.x 保持一直吗？

**Comment by simaQ** [comment]
- [ ] 极坐标下半径坐标轴的文本应该展示在坐标轴左侧 @hustcc 
        复现 demo: http://localhost:8000/zh/examples/radar/radar#basic

![image](https://user-images.githubusercontent.com/6628666/70406240-09723280-1a7b-11ea-8b2c-cc6bddf93290.png)

- [ ]  极坐标弧轴的文本收尾重叠了，默认应该只展示一个文本即可。@hustcc
         复现 demo: http://localhost:8000/zh/examples/radar/radar#flower-line
![image](https://user-images.githubusercontent.com/6628666/70406185-d891fd80-1a7a-11ea-9106-f6c4efa5edb4.png)

**Comment by simaQ** [comment]
- [ ] 当图例设置为 position: 'right-bottom' 时，布局出错 @hustcc 
   复现 demo：http://localhost:8000/zh/examples/bar/dodge#bar4
![image](https://user-images.githubusercontent.com/6628666/70411569-94f4bf00-1a8d-11ea-885c-7ccb3c03ff3e.png)

**Comment by simaQ** [comment]
- [ ] chart.axis() 中 grid 支持 align: 'center' 吗？
- [ ] chart.annotation().text 支持 rotate 属性，目前 G 4.0 的 text 不再支持传入 rotate
- [ ] `chart.legend({ position: 'top-center' });` 设置失效  @hustcc 
         复现 demo: http://localhost:8000/zh/examples/gallery/bar#bar3

**Comment by simaQ** [comment]
- [ ]  极坐标弧轴的文本收尾重叠了，默认应该只展示一个文本即可。@hustcc
         复现 demo: http://localhost:8000/zh/examples/radar/radar#flower-line
![image](https://user-images.githubusercontent.com/6628666/70406185-d891fd80-1a7a-11ea-9106-f6c4efa5edb4.png)

**Comment by simaQ** [comment]
- [ ] 坐标轴文本绘制两次

复现 demo: http://localhost:8000/zh/examples/bar/basic#time-bar

![image](https://user-images.githubusercontent.com/6628666/71338619-904f0100-258b-11ea-90cf-74677bb9426f.png)

**Comment by simaQ** [comment]
- [ ] 条形图布局留白有问题

![image](https://user-images.githubusercontent.com/6628666/71334403-0c8c1900-2579-11ea-9726-8509b569f556.png)

```ts
const data = [
      { country: '巴西', population: 18203 },
      { country: '印尼', population: 23489 },
      { country: '美国', population: 29034 },
      { country: '印度', population: 104970 },
      { country: '中国', population: 131744 },
    ];

    const div = createDiv();
    div.style.display = 'inline-block';
    const chart = new G2.Chart({
      container: createDiv(),
      width: 250,
      height: 200,
    });

    chart.data(data);

    chart.coordinate().transpose();
    // chart.coordinate('polar').transpose();
    chart.interval().position('country*population');

    chart.render();
```

**Comment by simaQ** [comment]
- [ ] 自定义 shape 返回数组形式 

```ts
return ['image', imageMap[name]];
```

**Comment by simaQ** [comment]
- [ ] 坐标轴文本被剪切 http://localhost:8000/en/examples/line/step

![image](https://user-images.githubusercontent.com/6628666/71455459-19ef1080-27d0-11ea-9a59-d267cd1c1e3f.png)

**Comment by simaQ** [comment]
- [ ] chart.scale(‘x’, { sync: true }) 未支持

**Comment by simaQ** [comment]
- [ ] 'time' 类型的 scale 不支持 `mask` 属性
- [ ] @antv/scale 移除 moment 依赖

**Comment by simaQ** [comment]
- [ ] chart.axis() 不支持 position 设置 @hustcc

**Comment by simaQ** [comment]
- [ ] gird 是否支持 align: 'center' ？

**Comment by paleface001** [comment]
> * [ ]  gird 是否支持 align: 'center' ？
> 
> ```ts
> chart.axis('day', {
>   title: null,
>   grid: {
>     align: 'center',
>     lineStyle: {
>       lineWidth: 1,
>       lineDash: null,
>       stroke: '#f0f0f0'
>     },
>     showFirstLine: true
>   }
> });
> ```

还是要支持滴~ 色块图用的着

**Comment by simaQ** [comment]
- [ ] 分类图例是否支持倒序显示 @dxq613 
 
```ts
chart.legend({
  reversed: boolean,
});
```

**Comment by simaQ** [comment]
- [ ] slider 组件 @zqlu

**Comment by zqlu** [comment]
> * [ ]  slider 组件 @zqlu

@hustcc @dxq613 https://github.com/antvis/component/pull/118

**Comment by simaQ** [comment]
- [ ]  label 超出画布 @simaQ

**Comment by simaQ** [comment]
- [ ] 分类图例过滤问题 @hustcc

**Comment by simaQ** [comment]
- [ ] Tooltip 的 crosshairs 支持 canvas 版本的

**Comment by simaQ** [comment]
- [ ] chart.axis() 接口中，`label` 和  `grid` 属性支持回调

参考 https://yuque.antfin-inc.com/antv/g2-4/dlzf45#7e22ccf3

**Comment by simaQ** [comment]
- [ ] `geometry.label()` 中属性 `adjustType`  默认提供的几种类型的重命名，目前 3.x adjustType 提供的三种类型：
	1. `treemap` 根据包围盒大小计算，超出包围盒则不展示，这个其实不止适用于 treemap 图表，所以命名为 treemap 不太合适
	2. `scatter` 对重叠的文本进行调整，也不只是适用于散点图
	3. `map` 这个目前暂时可以只用于地图

**Comment by dxq613** [comment]
* [ ] element 状态量的配置目前使用起来太难用

**Comment by simaQ** [comment]
- [ ] 多 view 的 tooltip 交互问题
       http://localhost:8000/zh/examples/line/multiple#kernel-smooth-regression-2

![image](https://user-images.githubusercontent.com/6628666/69789386-6bb97080-11fb-11ea-9f14-94cc70cadb9e.png)

**Comment by simaQ** [comment]
- [ ] http://localhost:8000/zh/examples/area/basic#area-large  
	- [ ] 左侧坐标轴标题 undefined
	- [ ] 自定义图例没有生效
	- [ ] tooltip marker 颜色不支持渐变色 @dxq613 
![image](https://user-images.githubusercontent.com/6628666/71497071-81b96000-2891-11ea-8d0d-d853ef0a2e78.png)

**Comment by simaQ** [comment]
- [ ]  http://localhost:8000/zh/examples/area/stacked#streamgraph 绘制失败 @simaQ

**Comment by simaQ** [comment]
-[ ]  http://localhost:8000/zh/examples/bar/dodge#bar4 
	- [ ] 标题 undefined
	- [ ] 图例布局有问题

![image](https://user-images.githubusercontent.com/6628666/71497140-d6f57180-2891-11ea-8fa5-dcd09e221a5a.png)

**Comment by simaQ** [comment]
- [ ] Tooltip 交互的躲避有问题 @dxq613

**Comment by simaQ** [comment]
- [ ] http://localhost:8000/zh/examples/pie/rose#rose-ranged
   - [ ] 网格线
   - [ ] 坐标轴文本方向

![image](https://user-images.githubusercontent.com/6628666/71497208-23d94800-2892-11ea-9b93-c8ab1c4e8a67.png)

**Comment by simaQ** [comment]
- [ ] http://localhost:8000/zh/examples/box/box#one-dim 一维箱型图绘制出错 @simaQ

**Comment by simaQ** [comment]
- [ ] http://localhost:8000/zh/examples/box/box#with-error 点图 y 轴为数组时有问题。padding 也出问题了 @simaQ

**Comment by simaQ** [comment]
- [ ] http://localhost:8000/zh/examples/candlestick/demo
	- [ ] 多 view 的图例
	- [ ] 出现多坐标轴 
![image](https://user-images.githubusercontent.com/6628666/71497304-934f3780-2892-11ea-8826-3326c0f04afc.png)

**Comment by simaQ** [comment]
- [ ] http://localhost:8000/zh/examples/component/component#label-treemap @simaQ 

定位到是由 clone() 函数导致

**Comment by simaQ** [comment]
- [ ] http://localhost:8000/zh/examples/component/component#legend-size 绘制有卡顿 @simaQ

**Comment by simaQ** [comment]
- [ ] http://localhost:8000/zh/examples/point/scatter#time-bubble 

log scale 导致的

```ts
chart.scale('exp_amo', {
  type: 'log',
  ticks: [225, 1000000, 2000000, 4000000, 6000000]
});
```

**Comment by dxq613** [comment]
* [ ] 框选过滤时，如果未框选到任何元素时 chart.filter() 全部清理后，无效

**Comment by simaQ** [comment]
- [ ] 坐标轴没有考虑坐标系发生 reflect 的情况， 目前坐标系支持 `chart.coordinate().reflect('x')`, `chart.coordinate().reflect('y')`

![image](https://user-images.githubusercontent.com/6628666/71510341-8ac62380-28c9-11ea-81d7-645f984fee91.png)

**Comment by simaQ** [comment]
- [ ] 漏斗图图例太亲密 @hustcc 

http://localhost:8000/zh/examples/funnel/funnel#basic

![image](https://user-images.githubusercontent.com/6628666/71511525-a59a9700-28cd-11ea-9f49-98249029b0fa.png)

**Comment by simaQ** [comment]
- [ ] chart.coordinate().reflect() 未生效

http://localhost:8000/zh/examples/map/map#bubble-map
![image](https://user-images.githubusercontent.com/6628666/71511793-894b2a00-28ce-11ea-8ab9-dd41cab28d5c.png)

**Comment by simaQ** [comment]
- [ ] 地图绘制错误 http://localhost:8000/zh/examples/map/map#choropleth-map @simaQ 

http://localhost:8000/zh/examples/map/map#choropleth-map

**Comment by simaQ** [comment]
- [ ] chart.scale() sync 有问题

http://localhost:8000/zh/examples/map/map#us-states-hex

![image](https://user-images.githubusercontent.com/6628666/71512336-a7b22500-28d0-11ea-8e21-95abf14a058d.png)

**Comment by simaQ** [comment]
- [ ] http://localhost:8000/zh/examples/gallery/area#area7 绘制出错  @simaQ

**Comment by simaQ** [comment]
- [ ] grid 为 ci'rcle 类型时，坐标轴线和网格线不一致...

http://localhost:8000/zh/examples/box/box#radial-box

![image](https://user-images.githubusercontent.com/6628666/71571266-66aa5280-2b14-11ea-946b-2dd93612c390.png)

**Comment by hustcc** [comment]
> http://localhost:8000/zh/examples/bar/basic#time-bar

scale 中的 time 返回的 ticks 有问题，不是对应的日期，而是返回的小时。然后导致 tick 有相同，触发 component 的错误。这个我改成传入 component 加上 id 解决。time scale 的问题在 scale 修复之后自动解决。

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/71575157-d9bcc480-2b26-11ea-8493-037438b74ad2.png)

http://localhost:8000/zh/examples/bar/basic#time-bar

 - [ ] scale 之后，布局错误导致图例遮挡。

**Comment by simaQ** [comment]
- [ ] 当两个 view 的绘制区域相同时，一个 view 有图例，一个 view 没有图例，自动布局后两个 view  没有重合，默认对于绘制区域相同的 view，应该做一下 coordinateBBox 的同步。

复现 demo: http://localhost:8000/zh/examples/gallery/area#area7

**Comment by hustcc** [comment]
> http://localhost:8000/zh/examples/box/box#radial-box

这个我测试是 ok 的，有什么特殊的复现步骤吗？

**Comment by simaQ** [comment]
* [ ] chart.filter() 后 chart.render(true) 的图例状态同步

**Comment by simaQ** [comment]
> > http://localhost:8000/zh/examples/box/box#radial-box
> 
> 这个我测试是 ok 的，有什么特殊的复现步骤吗？

DEMO 代码有更新，合掉我的分支~~~

```ts
import { DataView } from '@antv/data-set';
import { Chart } from '@antv/g2';

const data = [
  { x: 'Oceania', low: 1, q1: 9, median: 16, q3: 22, high: 24 },
  { x: 'East Europe', low: 1, q1: 5, median: 8, q3: 12, high: 16 },
  { x: 'Australia', low: 1, q1: 8, median: 12, q3: 19, high: 26 },
  { x: 'South America', low: 2, q1: 8, median: 12, q3: 21, high: 28 },
  { x: 'North Africa', low: 1, q1: 8, median: 14, q3: 18, high: 24 },
  { x: 'North America', low: 3, q1: 10, median: 17, q3: 28, high: 30 },
  { x: 'West Europe', low: 1, q1: 7, median: 10, q3: 17, high: 22 },
  { x: 'West Africa', low: 1, q1: 6, median: 8, q3: 13, high: 16 },
];
const dv = new DataView().source(data);
dv.transform({
  type: 'map',
  callback: (obj) => {
    obj.range = [obj.low, obj.q1, obj.median, obj.q3, obj.high];
    return obj;
  },
});
const chart = new Chart({
  container: 'container',
  autoFit: true,
  height: 500,
});
chart.data(dv.rows);
chart.scale('range', {
  max: 35,
});
chart.axis('range', {
  grid: {
    line: {
      type: 'circle',
    },
  },
});
chart.tooltip({
  showTitle: false,
  itemTpl:
    '<li class="g2-tooltip-list-item" data-index={index} style="margin-bottom:4px;">' +
    '<span style="background-color:{color};" class="g2-tooltip-marker"></span>' +
    '{name}<br/>' +
    '<span style="padding-left: 16px">最大值：{high}</span><br/>' +
    '<span style="padding-left: 16px">上四分位数：{q3}</span><br/>' +
    '<span style="padding-left: 16px">中位数：{median}</span><br/>' +
    '<span style="padding-left: 16px">下四分位数：{q1}</span><br/>' +
    '<span style="padding-left: 16px">最小值：{low}</span><br/>' +
    '</li>',
});
chart.coordinate('polar', { innerRadius: 0.5 });
chart
  .schema()
  .position('x*range')
  .shape('box')
  .size(60)
  .color('x')
  .tooltip('x*low*q1*median*q3*high', (x, low, q1, median, q3, high) => {
    return {
      name: x,
      low,
      q1,
      median,
      q3,
      high,
    };
  });
chart.render();
```

**Comment by simaQ** [comment]
- [ ] grid 更新动画没有生效

G2 会在 component.update() 方法中 https://github.com/antvis/G2/blob/4.x/src/chart/controller/axis.ts#L314  将 animate: true 以及 animateOption 的属性传入，但是 component 层并没有按照传入的配置将 animate 属性更新为 true.   

@dxq613

**Comment by simaQ** [comment]
> * [ ]   http://localhost:8000/zh/examples/area/stacked#streamgraph 绘制失败
> 
> 原因：
> 图例没有按照传入的 maxWidth 进行布局导致的。
> 
> ```ts
>  chart.legend(false);
> ```
> 
> 即可绘制正确。
> 
> ![image](https://user-images.githubusercontent.com/6628666/71638879-d8b2a100-2ca6-11ea-93ee-227fc3d9cad0.png)
> 
> @dxq613

https://github.com/antvis/g/issues/316

**Comment by hustcc** [comment]
组件 bbox 问题，导致轴被画布裁剪。@dxq613 求一起看看

![image](https://user-images.githubusercontent.com/7856674/71799428-37ee2800-3090-11ea-8c75-5df0b8b828ec.png)

**Comment by simaQ** [comment]
#### 交互行为相关问题整理

@dxq613 

- [ ] hightlight 交互，当鼠标移入 tooltip 再移入画布时，原先高亮的 shape 没有恢复至原始状态
![bug-1](https://user-images.githubusercontent.com/6628666/71967512-6d387880-323e-11ea-8d1b-80b8254843a0.gif)

- [ ] 图例项表现出被剪切的样子 http://localhost:8000/zh/examples/interaction/interaction#legend-active
![bug-2](https://user-images.githubusercontent.com/6628666/71967876-ec2db100-323e-11ea-8e68-c5f031c8f265.gif)

- [ ] 分类图例过滤有问题 http://localhost:8000/zh/examples/interaction/interaction#legend-filter
![bug-3](https://user-images.githubusercontent.com/6628666/71968173-56465600-323f-11ea-8267-1fd3d2fa33a7.gif)


- [ ] 连续图例过滤不生效，同时连续图例中间部分未提供拖拽功能 http://localhost:8000/zh/examples/interaction/interaction#continue-legend-filter

![2020-01-08 17-50-30 2020-01-08 18_01_39](https://user-images.githubusercontent.com/6628666/71969080-f355be80-3240-11ea-806e-1b4277e399d8.gif)

![image](https://user-images.githubusercontent.com/6628666/71968147-4cbcee00-323f-11ea-9bfb-c8e9b2c37428.png)

- [ ] 饼图选中的交互，在恢复原始状态时加上动画体验会更好
http://localhost:8000/zh/examples/interaction/interaction#pie-selected

![2020-01-08 18-02-46 2020-01-08 18_03_47](https://user-images.githubusercontent.com/6628666/71969245-3b74e100-3241-11ea-8e26-381f3cc37992.gif)

- [ ] 框选交互在空白处框选时，图表就卡住了，并且无法 reset 

http://localhost:8000/zh/examples/interaction/interaction#element-brush

![2020-01-08 18-05-18 2020-01-08 18_06_02](https://user-images.githubusercontent.com/6628666/71969404-8bec3e80-3241-11ea-9612-4eb2e6739380.gif)

- [ ] 拖拽交互没有生效 http://localhost:8000/zh/examples/interaction/interaction#drag-move
- [ ] 缩放交互亦没有生效 http://localhost:8000/zh/examples/interaction/interaction#zoom

**Comment by dxq613** [comment]
> #### 交互行为相关问题整理

我定位了一下：
* 1，2 ，4 是 G 的 bug，已经告诉诸岳，G 修复后升级即可
* 2 是 legend controller 生成、更新 items 时没有同步选中状态，我跟逍为一起解决
* 3 的 interaction 名称写错了，拖拽功能在 legend 上增加
* 5 拖拽交互待 scale 改造完成后增加
* 6 框选空白处卡死，是 bug

本周应该能够修复大部分，scale 相关的一起解决

**Comment by simaQ** [comment]
- [ ] chart.animate(false) 后，组件动画没有关闭  @simaQ

**Comment by simaQ** [comment]
- [ ] axis 更新动画

直接调用 chart.changeSize(); 复现，必现

![坐标轴更新 BUG](https://user-images.githubusercontent.com/6628666/72337214-25fa2e00-36fd-11ea-8886-09ce43d1fa92.gif)

**Comment by simaQ** [comment]
@hustcc 

- [ ] http://localhost:8000/zh/examples/pie/nested 嵌套饼图绘制出错 

![image](https://user-images.githubusercontent.com/6628666/72337277-488c4700-36fd-11ea-9f91-7cba8a7cd59d.png)

- [ ] 多 view padding 没有对齐 
http://localhost:8000/zh/examples/heatmap/heatmap#kernel-smooth-density

**Comment by simaQ** [comment]
- [ ] 图例被截取 @hustcc 

![image](https://user-images.githubusercontent.com/6628666/72321841-e53fec00-36df-11ea-8d93-d252aea3c17c.png)


复现 demo:

```ts
const data = [
      { genre: 'Sports', sold: 275 },
      { genre: 'Strategy', sold: 115 },
      { genre: 'Action', sold: 120 },
      { genre: 'Shooter', sold: 3500 },
      { genre: 'Other', sold: 150 }
    ];

    const chart = new Chart({
      container: createDiv(),
      autoFit: false,
      width: 380,
      height: 300,
    });

    chart.data(data);
    chart.scale('sold', {
      max: 3600,
      nice: false,
    });
    // chart.coordinate().transpose();
    chart.interval().position('genre*sold').color('genre').label('sold');

    chart.render();
```

**Comment by hustcc** [comment]
> * [zh/examples/pie/nested](http://localhost:8000/zh/examples/pie/nested)

chart 和子 view 之间的 coordinateBBox 不会进行 同步。但是有两个解法：

1. 分成 innerView 和 outerView 两个子 view，然后 padding 设置一样（或者 chart 设置即可）
2. chart 上绘制 inner，outerView 一个子 view，那么设置 outerView的 padding 设置为 0（现在是继承 chart 的 padding）

![image](https://user-images.githubusercontent.com/7856674/72410588-ae330e80-37a3-11ea-9b7f-a92e7628f0f8.png)

**Comment by simaQ** [comment]
https://github.com/antvis/G2/blob/237b4c7fee5e6199c47a410bd47d89d1356911ef/examples/component/component/demo/guide-region-filter-realtime-data.ts#L1-L6

---

###### This issue was generated by [todo](https://todo.jasonet.co) based on a `TODO` comment in 237b4c7fee5e6199c47a410bd47d89d1356911ef when #1937 was merged. cc @antvis.

**Comment by simaQ** [comment]
- [ ] mirror 类型 Facet，`showTitle` 配置未生效 @hustcc

**Comment by simaQ** [comment]
- [ ] facet title 的样式不美观~~~ @hustcc 

http://localhost:8000/zh/examples/funnel/funnel#symmetric

![image](https://user-images.githubusercontent.com/6628666/72674361-69afb780-3ab0-11ea-8e74-13c540a7639f.png)

**Comment by simaQ** [comment]
- [ ] http://localhost:8000/zh/examples/funnel/funnel#comparision 坐标系 scale 不生效 @hustcc 

```ts
chart
  .coordinate('rect')
  .transpose()
  .scale(1, -1);
```

![image](https://user-images.githubusercontent.com/6628666/72782047-c7353700-3c5d-11ea-8a9a-e7c625542a10.png)

**Comment by simaQ** [comment]
![image](https://user-images.githubusercontent.com/6628666/74995113-dee52280-548a-11ea-9118-faba9cf8e341.png)

伙伴们很给力，就此结贴！
