### ISSUE TITLE
饼图数据传入为数值的时候,其中一个数值为负数的问题

### ISSUE THREAD

**Issue by 18402025768** [antvis/g2#1718]
测试配置
const data = [
  { item: '事例一', percent: -0.4 },
  { item: '事例二', percent: 0.21 },
  { item: '事例三', percent: 0.17 },
  { item: '事例四', percent: 0.13 },
  { item: '事例五', percent: 0.09 }
];
const chart = new G2.Chart({
  container: 'container',
  forceFit: true,
  height: 500
});
chart.source(data, {
  percent: {
    formatter: val => {
      //val = (val * 100) + '%';
      return val;
    }
  }
});
chart.coord('theta', {
  radius: 0.75
});
chart.tooltip({
  showTitle: false,
  itemTpl: '<li><span style="background-color:{color};" class="g2-tooltip-marker"></span>{name}: {value}</li>'
});
chart.intervalStack()
  .position('percent')
  .color('item')
  .label('percent', {
    formatter: (val, item) => {
      return item.point.item + ': ' + val;
    }
  })
  .tooltip('item*percent', (item, percent) => {
    percent = percent * 100 + '%';
    return {
      name: item,
      value: percent
    };
  })
  .style({
    lineWidth: 1,
    stroke: '#fff'
  });
chart.render();

![image](https://user-images.githubusercontent.com/20633660/69770647-d7341b80-11c4-11ea-91fd-e335eddf3764.png)

**Comment by simaQ** [comment]
饼图表示各部分在整体的占比，不适合有负值的数据... 建议结合具体需求选择其他合适的图表
