### ISSUE TITLE
[建议] 是否对 TypeScript 更友好一些呢？

### ISSUE THREAD

**Issue by cipchk** [antvis/g2#172]
当下不管是：

```
npm install -save-dev @types/g2
```

抑或 G2 的 Npm 源也并未提供相应的声明文件。

**TypeScript高度依赖者，请也对 Ts 好一点嘛**，谢谢！

**Comment by dxq613** [comment]
目前没有计划，工作量太大，当前的工作还在 11月份的开源上。

**Comment by LinBoLen** [comment]
Roger that

**Comment by leungwensen** [comment]
We've got a definition file: https://github.com/antvis/g2/blob/master/src/index.d.ts

**Comment by LinBoLen** [comment]
beyond the definition file
