### ISSUE TITLE
如何给G2贡献代码

### ISSUE THREAD

**Issue by guanyun-helo** [antvis/G2#1726]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
- 有任何代码贡献的指南么？
- 是否接受外部人员贡献代码

### What does the proposed API look like?
- 有任何代码贡献的指南么？
- 是否接受外部人员贡献代码

**Comment by simaQ** [comment]
1. 代码贡献指南：https://github.com/antvis/G2/blob/master/CONTRIBUTING.zh-CN.md
2. 非常欢迎贡献代码~  也非常欢迎参与我们的文档建设~~~~

**Comment by guanyun-helo** [comment]
感谢，closed。
