### ISSUE TITLE
色块图，在google 浏览器出现这样的问题，能提供点思路么？

### ISSUE THREAD

**Issue by taoshi006** [antvis/g2#173]
![image](https://user-images.githubusercontent.com/14683560/29854544-34127194-8d79-11e7-9def-8340e53d59f1.png)

![image](https://user-images.githubusercontent.com/14683560/29854577-6b4703be-8d79-11e7-89f4-8c66b56d3896.png)

**Comment by dxq613** [comment]
是深色背景下图例显示不出来么？
