### ISSUE TITLE
环图： 更新guide().html进行repaint后mouseleave不会触发

### ISSUE THREAD

**Issue by alonePedestrian** [antvis/G2#1730]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g2-reproduction-template-ilwsf)

### Steps to reproduce

```
chart.on('interval:mouseenter', ev => {
        chart.guide().clear();
        chart.guide().html({
          position: [ '50%', '50%' ],
          html: `<div style="color:#8c8c8c;font-size: 14px;text-align: center;width: 10em;">总量<br><span style="color:#8c8c8c;font-size:20px">123</span></div>`,
        });
        chart.repaint();
});

chart.on('interval:mouseleave', ev => {
        chart.guide().clear();
        chart.guide().html({
          position: [ '50%', '50%' ],
          html: `<div style="color:#8c8c8c;font-size: 14px;text-align: center;width: 10em;">总量<br><span style="color:#8c8c8c;font-size:20px">456</span></div>`,
        });
        chart.repaint();
});
```

### What is expected?
正常执行interval:mouseleave

### What is actually happening?
不会触发interval:mouseleave，并且interval:mouseenter会一直被触发

| Environment | Info |
|---|---|
| g2 | 3.5.11 |
| System | mac 10.14.6 (18G95) |
| Browser | chrome  78.0.3904.108（正式版本） （64 位） |

**Comment by simaQ** [comment]
尝试升级下 4.0。
