### ISSUE TITLE
antv/util 的引用方式跟我们按需打包的方案冲突

### ISSUE THREAD

**Issue by dxq613** [antvis/G2#1740]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
按需打包

### What does the proposed API look like?
现在所有文件引用 @antv/util 都是 
```js
import * as _ from '@antv/util'
```
这种方式无法支持按需打包，需要全部改写成

```js
import {each, lowerCase} from '@antv/util';
```

**Comment by simaQ** [comment]
@hustcc  恩，这样就享受不到 tree shaking 带来的好处了~~~

这个由我统一改吧

**Comment by hustcc** [comment]
好的
