### ISSUE TITLE
polar 极坐标系下坐标轴的显示

### ISSUE THREAD

**Issue by fingerpan** [antvis/G2#1744]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
polar极坐标系下是否可以显示坐标轴

### What does the proposed API look like?
希望polar极坐标系可以展示坐标轴

是否可以做出如下图形

![image](https://user-images.githubusercontent.com/22525946/70198182-1b856580-1749-11ea-85b7-9b191a55691e.png)

**Comment by fingerpan** [comment]
从我的个人的理解
应该是polar极坐标系下，图形采用 intervel, 数据调整为stack 堆叠， 展示坐标系。
但是我发现坐标系展示不出。官方例子的坐标轴label也是用辅助元素模拟。

**Comment by dxq613** [comment]
极坐标系下 transpose 后的坐标系被默认隐藏了，这个功能会在 G2 4.0 版本中改回来，针对不同坐标系，不同图表的默认配置全部由用户设置。

**Comment by fingerpan** [comment]
默认隐藏在哪里可以配置显示出来吗？

**Comment by simaQ** [comment]
(⊙o⊙)…，G2 4.0 里面还是默认关闭了，不可以开启。

**Comment by fingerpan** [comment]
> (⊙o⊙)…，G2 4.0 里面还是默认关闭了，不可以开启。

很遗憾，可以说明一下为什么默认隐藏吗？ 是出于什么考量？

**Comment by simaQ** [comment]
主要是为了提高易用性，因为饼图使用的频率很高，而饼图默认是不需要坐标轴的，所以为了方便用户使用，就默认关闭了。不过用户无法就不太合适了，这个我我会支持下的。
