### ISSUE TITLE
[4.0] G2 4.0 clear 有问题

### ISSUE THREAD

**Issue by dxq613** [antvis/G2#1746]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

* 先绘制 interval ，再 clear 生成饼图时，报错。（如果直接创建饼图正常）
* 不 clear，直接修改 interval ，生成图形错误。
![image](https://user-images.githubusercontent.com/1264678/70212820-f9084200-1772-11ea-8ad4-5358887db5a4.png)

```js
      chart.coordinate('theta');
      inteval.position('1*value').color('year').adjust('stack');
      chart.render();
```

**Comment by dxq613** [comment]
转化坐标系也会出问题，如果绘制图表后，再调用 render：

```js
chart.coordinate('rect').transpose();
chart.render();
```
![image](https://user-images.githubusercontent.com/1264678/70293634-d1b97f80-181b-11ea-9052-7ab00e1af18d.png)

**Comment by hustcc** [comment]
以为是 view 那边 coordinate 的问题，排查是 shapeFactory cache 导致 coordinate 没有及时更新。我提 pr @simaQ
