### ISSUE TITLE
G2 3.5.8 Tooltip 多组值如何显示？

### ISSUE THREAD

**Issue by zhongwen-zhou** [antvis/G2#1747]
嗨，我们一直在用基于G2的框架做基础组件库开发，现在遇到一个棘手的问题，主要是tooltip

我们是希望 tooltip 能有 一个 title，然后多组 name 和 value 值，目前使用tooltip('a*b*c*d')，可以解决b\c\d各占一行，但是我们要对部分进行格式化，使用回调 也只能返回一组 name-value，请问有什么办法可以解决么？

谢谢

**Comment by dxq613** [comment]
a*b*c*d ，各占一行应该满足你们的需求吧，只是 a,b,c,d 几个字段需要格式化，那么可以在对应的 scale 上加 formatter

```js
chart.source(data, {
  a: {
  formatter() {}
}
});
```

还可以在 chart 的 tooltipchange 事件里面修改 items 的值

**Comment by zhongwen-zhou** [comment]
@dxq613 我试试看，谢谢哈，有结果回复你

**Comment by zhongwen-zhou** [comment]
@dxq613 嗨，谢谢你，我最后用的方法是：
      chart.tooltip({
        useHtml: true,
        htmlContent: function (title, items){          
          let selfItem = items[0]
          let domStr = `
            <div class="g2-tooltip">
              <div class="g2-tooltip-title" style="margin-bottom: 4px;">${title}</div>
              <div>${that.yAxisField.name}: ${items['x']}</div>
              <div>${同比}: ${items['y']}</div>
              <div>${环比}: ${items['z']}</div>
            </div>
          `
          return domStr
        }
      })

然后chart.tooltip('x*y*z', function(x,y,z){return {x,y,z}})

目前是可以解决这种问题
