### ISSUE TITLE
【RegionFilter】图表填充图片时，加载过程中，填充部分出现黑色

### ISSUE THREAD

**Issue by zhongwen-zhou** [antvis/G2#1748]
使用Guide().RegionFilter()时，对图表的部分填充 透明图片，在图片的加载过程中，被填充部分首先会变成黑色，然后才能正常，但是图片实际上是有的（通过webpack 打包成base64，1像素图），不用去下载
![image](https://user-images.githubusercontent.com/2158216/70291985-c2d0ce00-1817-11ea-8c29-faa8b70c6bb7.png)
但是大概500ms，之后，能够恢复正常

**Comment by simaQ** [comment]
请提供复现代码。暂时关闭。
