### ISSUE TITLE
在使用词云时,出现数据显示不全的问题

### ISSUE THREAD

**Issue by XinYueXiao** [antvis/G2#1749]
案例地址:https://codepen.io/xinyuexiao/pen/LYEVvBg?editors=1010
![image](https://user-images.githubusercontent.com/31272499/70300947-e7d33a00-1833-11ea-8420-efa4bd9348ac.png)

**Comment by simaQ** [comment]
你好，这个是由你定义的 fontSize 算法决定的：

```ts
fontSize(d) {
                if (d.value) {
                    return ((d.value - min) / (max - min)) * (84 - 24) + 24;
                }
                return 0;
            }
```

你尝试下直接返回 12 就可以看到所有的，所以你需要按需调整策略。

**Comment by pppppppppppp12** [comment]
> 你好，这个是由你定义的 fontSize 算法决定的：
> 
> ```ts
> fontSize(d) {
>                 if (d.value) {
>                     return ((d.value - min) / (max - min)) * (84 - 24) + 24;
>                 }
>                 return 0;
>             }
> ```
> 
> 你尝试下直接返回 12 就可以看到所有的，所以你需要按需调整策略。

这样不行吧，直接设置12就没法区分词的大小了
