### ISSUE TITLE
将g2绘制的图形, 保存为一张图片

### ISSUE THREAD

**Issue by leicj** [antvis/g2#175]
1. 目前我使用g2绘制图形, 使用createG2来创建基于react模块的图形.
2. 但是我想在前端, 将antv所绘制的图形保存为一张图片.
  不知道能否提供一个思路, 就是antv是如何将所绘制的图形保存为一张图片的.

**Comment by dxq613** [comment]
Chart 有个 接口来下载图片

https://antv.alipay.com/g2/api/chart.html#downloadimage
