### ISSUE TITLE
3.5.11 “alignWithLabel”不在类型“tickLine”中

### ISSUE THREAD

**Issue by Marvintang1001** [antvis/G2#1753]
version 3.5.11
示例代码（https://g2.antv.vision/zh/examples/gallery/column#column3）
在本机测试中遇到以下报错。查看接口tickLine没有找到属性“alignWithLabel”

---------------------------------------------------------------------------
No overload matches this call.
  Overload 1 of 3, '(field: string, option: boolean): Chart', gave the following error.
    类型“{ label: { textStyle: { fill: string; }; }; tickLine: { alignWithLabel: boolean; length: number; }; }”的参数不能赋给类型“boolean”的参数。
  Overload 2 of 3, '(field: string, axisConfig: ChartAxisConfig): Chart', gave the following error.
    不能将类型“{ alignWithLabel: boolean; length: number; }”分配给类型“tickLine”。
      对象文字可以只指定已知属性，并且“alignWithLabel”不在类型“tickLine”中。

**Comment by simaQ** [comment]
类型定义的问题，是支持的。
