### ISSUE TITLE
rounded corners

### ISSUE THREAD

**Issue by InbarTakdim** [antvis/G2#1761]
How can I do border-radius to columns in g2.chart contractor?

				const chart = new G2.Chart({
						container: 'container',
						height: 220,
						padding: [30, 20, 30, 60],
						forceFit: true,
						fill: '#fff',
					});

**Comment by simaQ** [comment]
see this demo: https://g2-v3.antv.vision/zh/examples/column/stack

**Comment by Pacheco95** [comment]
@simaQ how can I change the border color?

**Comment by tolgayildizz** [comment]
How can I apply this process for pie chart?
