### ISSUE TITLE
[4.0] 补充交互需要的接口

### ISSUE THREAD

**Issue by simaQ** [antvis/G2#1763]

**Comment by dxq613** [comment]
* Element，Geometry，View 的 show, hide
* Element 的 getBBox() ，目前使用 element.shape.getCanvasBBox()

**Comment by simaQ** [comment]
Element 的 getBBox() 方法的话，因为 Element 默认会包含 shape，shape 对应的 label，以及 label 关联的 labelLine，所以返回 shape + labelShape + labelLine 的整体包围盒怎么样？
