### ISSUE TITLE
只有一种数据为什么没有legend(图例)？比如我创建了一个柱状图，只有一种数据，图例设置了显示也不会起作用，再加上一种数据就可以显示了

### ISSUE THREAD

**Issue by ZengZhenfei** [antvis/G2#1764]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。

**Comment by dxq613** [comment]
你要声明  .color('field') 指定一个字段，就根据这个字段生成图例了

**Comment by ZengZhenfei** [comment]
> 你要声明 .color('field') 指定一个字段，就根据这个字段生成图例了

谢谢！为什么显示的是渐变色的？可以修改吗？
const data = [
  { type: '未知', value: 654, percent: 0.02 },
  { type: '17 岁以下', value: 654, percent: 0.02 },
  { type: '18-24 岁', value: 4400, percent: 0.2 },
  { type: '25-29 岁', value: 5300, percent: 0.24 },
  { type: '30-39 岁', value: 6200, percent: 0.28 },
  { type: '40-49 岁', value: 3300, percent: 0.14 },
  { type: '50 岁以上', value: 1500, percent: 0.06 }
];

const chart = new G2.Chart({
  container: 'container',
  forceFit: true,
  height: 500,
  padding: [ 20, 20, 80, 20 ]
});
chart.source(data);
chart.scale('value', {
  alias: '销售额(万)'
});
chart.axis('type', {
  label: {
    textStyle: {
      fill: '#aaaaaa'
    }
  },
  tickLine: {
    alignWithLabel: false,
    length: 0
  }
});
chart.axis('value', false);
chart.tooltip({
  share: true
});

chart.guide().dataMarker({
  top: true,
  content: '因政策调整导致销量下滑',
  position: [ '2014-01', 1750 ],
  style: {
    text: {
      fontSize: 13
    }
  },
  lineLength: 30
});

chart.interval().position('type*value').color('value').opacity(1)
  .label('value', {
    useHtml: true,
    htmlTemplate: (text, item) => {
      const a = item.point;
      a.percent = String(parseInt(a.percent * 100)) + '%';
      return '<span class="g2-label-item"><p class="g2-label-item-value">' + a.value + '</p><p class="g2-label-item-percent">' + a.percent + '</p></div>';
    }
  });
chart.render();

**Comment by weiyin1123** [comment]
官网示例修改结果：
![image](https://user-images.githubusercontent.com/36982966/70963783-811c0f00-20c4-11ea-87a2-f169753f178f.png)
![image](https://user-images.githubusercontent.com/36982966/70963796-8bd6a400-20c4-11ea-804b-c6095987b43b.png)

我只想底部展示正常的数据标识
![image](https://user-images.githubusercontent.com/36982966/70963841-add02680-20c4-11ea-9004-41e4df37b321.png)


> 你要声明 .color('field') 指定一个字段，就根据这个字段生成图例了

**Comment by luichooy** [comment]
同问？
![image](https://user-images.githubusercontent.com/26423033/72676732-6e379880-3acf-11ea-841b-beb612d7e724.png)

进场人数 单独使用右侧 y 坐标轴，这种情况下，进场人数的图例不显示

**Comment by simaQ** [comment]
G2 是根据你数据的类型自动生成图例的，如果是数值则对应连续图例，如果是离散类型则对应分类图例。
