### ISSUE TITLE
chart.facet()单类型分面不显示

### ISSUE THREAD

**Issue by jakesavetheworld** [antvis/g2#177]
使用chart.facet()分面操作，group by出多个类型正常显示，但若只有单个类型则不显示。（数据是动态且无法预知的，实际场景需要均显示分面出来的类型）
![image](https://user-images.githubusercontent.com/24551615/30309708-4d75d78e-97bf-11e7-95b7-0052b798d594.png)

![image](https://user-images.githubusercontent.com/24551615/30309694-3a5bdc84-97bf-11e7-8456-38fdc88f759a.png)

**Comment by dxq613** [comment]
facet 本来就是基于数据生成的，如果你有这种固定类型的需求的话，自己创建多个 view 好了。

更新数据时，根据对应的view 设置数据即可。

**Comment by jakesavetheworld** [comment]
@dxq613 就实现而言，确实可以动态生成view，但毕竟facet是个现成的方案嘛~
并且：facet分面即使只有1个种类，legend也会显示这单个的种类，那为什么右侧的种类rowType不能显示呢？

**Comment by dxq613** [comment]
这个问题在 3.0 中解决吧，3.0 的版本基本稳定了，内部试用通过后放出。

```js
chart.facet('rect', {
  fields: [null, 'c'],
  eachView(view, facet) {
     // 图形
     // 标题
     // 坐标轴的设置
  }
});
```
将所有的控制都开放了
