### ISSUE TITLE
[4.0] autoFit 默认关闭

### ISSUE THREAD

**Issue by simaQ** [antvis/G2#1785]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。

**Comment by hustcc** [comment]
梳理下逻辑：

1. 如果是 autoFit，则使用容器大小作为宽高，如果宽高有存在 0 的，则使用默认 100
2. 如果不是 autoFit，则完全使用 开发者指定的 width、height，如果宽高有存在 0 的，则使用默认 100

----

这样存在的问题是：

```ts
// 这种写法，绘制出来的大小是 100 * 500。我们的所有 demo 都需要修改
const chart = new Chart({
   height: 500,
});

// 这种写法，开发指定的 width、height 是没有任何意义的
const chart = new Chart({
  autoFit: true,
  width: 500,
  height: 400,
});
```

**Comment by simaQ** [comment]
> > autoFit 默认关闭掉。
> 
> 梳理下 width、height 逻辑：
> 
> 1. 如果是 autoFit，则使用容器大小作为宽高，如果宽高有存在 0 的，则使用默认 100
> 2. 如果不是 autoFit，则完全使用 开发者指定的 width、height，如果宽高有存在 0 的，则使用默认 100
> 
> 这样存在的问题是：
> 
> ```ts
> // 这种写法，绘制出来的大小是 100 * 500。我们的所有 demo 都需要修改
> const chart = new Chart({
>    height: 500,
> });
> 
> // 这种写法，开发指定的 width、height 是没有任何意义的
> const chart = new Chart({
>   autoFit: true,
>   width: 500,
>   height: 400,
> });
> ```

I'm okay, very good!

**Comment by hustcc** [comment]
那我把所有的 demo 的 width、height 都调整为 600*500 ~ 网站的容器高度是 0，使用 autoFit 绘制出来肯定会有问题。

**Comment by simaQ** [comment]
1. autoFit 默认为 false，用户需要手动设置 width 和 height
2. autFit: true 时，会取图表容器的宽高，如果用户设置了 height，那么会以用户设置的 height 为准
