### ISSUE TITLE
使用select model，changeData图像会覆盖。

### ISSUE THREAD

**Issue by jason19659** [antvis/g2#179]
`
flowChart.setMode('select');
flowChart.select('rangeX');
`
使用鼠标选取一段数据后自动放大
`
flowChart.changeData(data)
flowChart.repaint()
`
原数据会覆盖到新数据上，旧数据未消失

**Comment by ycjcl868** [comment]
+1，也遇到这个问题

**Comment by leungwensen** [comment]
能不能参考这个 codepen 写一个能复现的 demo？

**Comment by dxq613** [comment]
可以不用 chart.changeData

```js
chart.clear();
chart.source(data);
chart.line()... // 语法重新声明一次
chart.render();
```

**Comment by ycjcl868** [comment]
解决了，参考这个 [https://antvis.github.io/g2-react/examples/higherWrapper.html](https://antvis.github.io/g2-react/examples/higherWrapper.html)  

```diff
class HigherChart extends Component {

  constructor(props, ...others) {
    super(props, ...others);
    this.Chart = createG2(chart => {
      this.chart = chart;
      chart.line().position('time*price').color('name').shape(props.shape).size(2);
      chart.render();
    });
  }

+  componentWillReceiveProps(nextProps) {
+    if (nextProps.shape !== this.props.shape) {
+      this.chart.clear();
+      this.chart.line().position('time*price').color('name').shape(nextProps.shape).size(2);
+      this.chart.render();
+    }
+  }

  render() {
    return (<this.Chart {...this.props} />);
  }
}

```

**Comment by jason19659** [comment]
> 解决了，@jason19659 参考这个 https://antvis.github.io/g2-react/examples/higherWrapper.html
> 
> ```diff
> class HigherChart extends Component {
> 
>   constructor(props, ...others) {
>     super(props, ...others);
>     this.Chart = createG2(chart => {
>       this.chart = chart;
>       chart.setMode('select');
>       chart.select('rangeX');
>       chart.line().position('time*price').color('name').shape(props.shape).size(2);
>       chart.render();
>     });
>   }
> 
> +  componentWillReceiveProps(nextProps) {
> +    if (nextProps.shape !== this.props.shape) {
> +      this.chart.get('options').filters = {}; // 清空 filters
> +      this.chart.repaint();
> +    }
> +  }
> 
>   render() {
>     return (<this.Chart {...this.props} />);
>   }
> }
> ```

你升级最新版本了吗。。最新版本好像没有这个功能了
