### ISSUE TITLE
矩形树图动画bug

### ISSUE THREAD

**Issue by w3313003** [antvis/G2#1792]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://118.25.16.229/public/upload/image/2019/12/16/20191216_b4d7e6002239b_demo.gif](http://118.25.16.229/public/upload/image/2019/12/16/20191216_b4d7e6002239b_demo.gif)

### Steps to reproduce
- 打开https://antv-g2.gitee.io/zh/examples/component/component#label-treemap
- 配置animate为 true
- 在初始化动画出现时, 鼠标快速移动到图表默认蓝色背景上

### What is expected?
节点颜色正常显示

### What is actually happening?
所有节点都被绘制成了蓝色

| Environment | Info |
|---|---|
| g2 | 3.5.11 |
| System | MAC OS 10.15 |
| Browser | CHROME 79 |

**Comment by simaQ** [comment]
因为我们把根节点对应的矩形也渲染了。鼠标 hover 到图形后获取到了根节点对应的矩形，所以就看上去全部变成了蓝色。在数据处理节点，剔除根节点数据就可以了 ，或者不渲染根节点数据
