### ISSUE TITLE
brush 双击无法恢复并 this._init is not a function报错

### ISSUE THREAD

**Issue by Dawnthy** [antvis/G2#1799]
Tbrush 双击无法恢复并 this._init is not a function报错

**Comment by Leannechn** [comment]
> Tbrush 双击无法恢复并 this._init is not a function报错

告知报错版本号，最新版应该已修复。

**Comment by Dawnthy** [comment]
3.5.10,3.5.11 版本未修复次 bug

**Comment by jiananshi** [comment]
3.5.11 未修复

**Comment by jiananshi** [comment]
目前通过 `chart.getInteractions().brush._init = () => {}` 绕过去了
