### ISSUE TITLE
代码里有innerHTML 函数，被报有xss 漏洞风险

### ISSUE THREAD

**Issue by appLhui** [antvis/g2#180]
公司的安全检查里 发现代码里有 innerHTML 函数，

**Comment by dxq613** [comment]
只有在自定义文本，将默认的行为转换成 html 时才会调用html 相关的函数。坐标轴上的文本，tooltip 的文本，如果使用默认的 canvas 渲染的话，不会调用到相关函数。

不过对于图表来说，不接受输入，所以这种安全问题应该在输入端控制，而非在输出端控制。

**Comment by dxq613** [comment]
G2 不接受输入，所以输出需要业务方自己实现。如果你们有这方面限制，可以在后面开源版本出来后，自己进行修改。

**Comment by weizongqi1990** [comment]
@dxq613 这是不合理的，我们不能控制用户输入什么内容，但是我们可以控制给用户呈现的是什么内容。
在G2内部有一个简易的模版引擎，可以在里面进行做xss防范是可以的。

**Comment by LinFeng1997** [comment]
@dxq613 建议模板引擎里对 htm l进行消毒操作，因为在 tooltip 的数据源是可以在用户输入的情况下，造成存储型 XSS 攻击。
