### ISSUE TITLE
legend 点击后重绘没有重计算padding

### ISSUE THREAD

**Issue by Leannechn** [antvis/G2#1800]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://riddle.alibaba-inc.com/riddles/1b29ea0a](http://riddle.alibaba-inc.com/riddles/1b29ea0a)

### Steps to reproduce
https://user-images.githubusercontent.com/6812138/70983126-2948cc80-20f3-11ea-8522-a7c04cf74dd1.png

### What is expected?
重新计算

### What is actually happening?
没有重新计算

| Environment | Info |
|---|---|
| g2 | 3.5.11 |
| System | mac |
| Browser | chrome |

---
https://user-images.githubusercontent.com/6812138/70983126-2948cc80-20f3-11ea-8522-a7c04cf74dd1.png

**Comment by simaQ** [comment]
可以升级使用 G2 4.0.0
