### ISSUE TITLE
在angular8中使用g2， chart.guide().dataMarker()提示dataMarker不存在

### ISSUE THREAD

**Issue by tony-yyj** [antvis/G2#1801]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/angular-g2-6bg8i)

### Steps to reproduce
angular项目，引入g2库（版本3.5.11），使用`chart.guide().dataMarker()`ts会提示`dataMarker`方法不存在

### What is expected?
ts可以识别`guide().dataMarker`方法

### What is actually happening?
`chart.guide().dataMarker()`ts会提示`dataMarker`方法不存在

| Environment | Info |
|---|---|
| g2 | 3.5.11 |
| System | macOS |
| Browser | chrome |

---
业务不影响，但是ts会报错，只能加上`//@ts-ignore`来忽略，但是这个在g2的src文件中有这个方法，需要再对应的index.d.ts文件中声明。

**Comment by simaQ** [comment]
欢迎使用 G2 4.0.0，整个项目使用 TS 编写，同时提供了完整的类型定义。
