### ISSUE TITLE
鼠标离开图表了，ToolTip仍然显示

### ISSUE THREAD

**Issue by ZengZhenfei** [antvis/G2#1817]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g2-reproduction-template-6ipi1 在这个环境又没测出来)

### Steps to reproduce
鼠标放在创建的chart上面左右移动，总是能重现这个错误

### What is expected?
鼠标离开chart, 不会再出现tooltip

### What is actually happening?
偶尔总是会出现

| Environment | Info |
|---|---|
| g2 | 3.5.11 |
| System | Mac和Win都能重现这个错误 |
| Browser | Chrome |

**Comment by ZengZhenfei** [comment]
https://codesandbox.io/s/g2-reproduction-template-6ipi1
![image](https://user-images.githubusercontent.com/29648356/71181049-5ab9c780-22ae-11ea-9908-81438d2d2bc1.png)
![image](https://user-images.githubusercontent.com/29648356/71181059-5ee5e500-22ae-11ea-8b2d-77f7090e1eb8.png)

**Comment by ZengZhenfei** [comment]
![image](https://user-images.githubusercontent.com/29648356/71181183-948ace00-22ae-11ea-9a1a-80570112aef2.png)

**Comment by ZengZhenfei** [comment]
![image](https://user-images.githubusercontent.com/29648356/71184489-cb63e280-22b4-11ea-963a-0c5c9bf23d8e.png)

**Comment by simaQ** [comment]
这，升级到 3.x 最新版本也有问题吗？

临时方案：监听事件手动 chart.hideTooltip()
