### ISSUE TITLE
关于放大缩小功能

### ISSUE THREAD

**Issue by prpr2012** [antvis/G2#1819]
能够通过鼠标点击按钮，进行放大缩小的控制

**Comment by simaQ** [comment]
G2 开放了 zoom 交互行为 https://antv-g2.gitee.io/zh/docs/api/interaction/#zoom-%E7%BC%A9%E6%94%BE，你可以自己监听下事件然后调用 chart.interaction('zoom')

**Comment by prpr2012** [comment]
能否通过鼠标点击，不是通过滚动进行放大缩小

**Comment by prpr2012** [comment]
TypeError: Cannot read property 'points' of undefined
(anonymous function)
node_modules/@antv/g2/build/g2.js:2320
  2317 |     var nextData = dataArray[index + 1];
  2318 | 
  2319 |     if (nextData) {
> 2320 |       data[0].nextPoints = nextData[0].points;
       | ^  2321 |     }
  2322 |   });
  2323 | }

**Comment by prpr2012** [comment]
这个问题是放大缩小后导致的，需要怎么处理？
