### ISSUE TITLE
G2图表样式调整问题 

### ISSUE THREAD

**Issue by GavinYIN1991** [antvis/g2#182]
最近我们使用了G2的图表做后台可视化开发，现在遇到了几个问题，不知道怎么处理，查阅教程文档也没有找到相关注释：
1.使用线图时，边界间距语法未生效。
https://antv.alipay.com/g2/demo/02-line/simple-line.html
![jietu20171010-113424](https://user-images.githubusercontent.com/10275967/31368233-ff2fcf0c-adae-11e7-832d-aa7464e328e4.png)
如上图，代码如下所示：
> ` forceFit: true,
      height: 380,
      plotCfg: {
        margin: [20,0,40,40]// 上，右，下，左
      }`

2.图表的标题title，图例legend，提示信息tooltip 如何修改样式？未找到相关说明。

**Comment by simaQ** [comment]
1. 边距设置问题，这个问题我没有复现，你的代码建议把注释去了
```js
forceFit: true, height: 380, plotCfg: { margin: [20,0,40,40] }
```
2. G2 不支持图表标题，图表的标题建议使用 html 实现

图例样式的设置教程:https://antv.alipay.com/g2/doc/tutorial/start/legend.html#图例样式设置
 图例的 api: https://antv.alipay.com/g2/api/chart.html#legend

提示信息 tooltip 的样式如果想要自定义，请使用 html 渲染形式： https://antv.alipay.com/g2/doc/tutorial/start/tooltip.html#3-html-内容

tooltip 的 api： https://antv.alipay.com/g2/api/chart.html#tooltip

**Comment by zhaodongyu** [comment]
@simaQ 配置 plotCfg 的时候，会警告说 plotCfg 不支持修改，请问怎么处理

**Comment by simaQ** [comment]
这个警告忽略即可

**Comment by GavinYIN1991** [comment]
```
chart.tooltip(true, {
    custom: true, // 使用自定义的 tooltip,
    html:  '<div style="position:absolute;visibility:hidden;border-radius: 5px;background-color:#fff;padding:20px;box-shadow: 4px 4px 40px rgba(0,0,0,.05)"><h4 class="ac-title"></h4><table class="ac-list custom-table"></table></div>',
    itemTpl: '<tr><td style="font-size: 14px;height: 32px;color:{color}">{name}</td><td style="font-size: 14px;height: 32px;">{value}</td></tr>',
    offset: 5
  });
```
按照你给的建议修改tooltip，效果如图所示。

![jietu20171023-205427](https://user-images.githubusercontent.com/10275967/31890031-6318c764-b834-11e7-88fd-c81fdecf8c56.png)

请问如何修改tooltip 的 title 样式？以及图例的marker是否就无法显示了？

**Comment by dxq613** [comment]
等 11月22 号的 3.0 吧，这些东西都开放了。
