### ISSUE TITLE
能给图表加上title(标题)吗？

### ISSUE THREAD

**Issue by ZengZhenfei** [antvis/G2#1820]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。

**Comment by simaQ** [comment]
G2 没有提供 title 组件，但是你可以通过以下方案给图表加上标题：

1. 使用 chart.guide().text() 
2. 使用外部 dom

**Comment by ZengZhenfei** [comment]
谢谢！
