### ISSUE TITLE
图例legend有个属性itemFormatter，是个回调函数，我怎么知道这个回调函数有哪些参数可以使用？

### ISSUE THREAD

**Issue by ZengZhenfei** [antvis/G2#1824]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。

**Comment by sunui** [comment]
只有一个图例名称一个参数

**Comment by simaQ** [comment]
先翻文档

![image](https://user-images.githubusercontent.com/6628666/75990312-b13eb580-5f2f-11ea-8356-a5ab8e00b4cc.png)
