### ISSUE TITLE
line的color和shape回调不能改变线的部分颜色

### ISSUE THREAD

**Issue by ayaka209** [antvis/G2#1828]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lucid-panini-bi9zk)

### Steps to reproduce
```
chart
  .line()
  .position("x*y")
  .color("y",function(y){
    return Math.random() > 0.5 ? "red" :"yellow";
  });
```

### What is expected?
颜色根据回调函数结果发生变化

### What is actually happening?
颜色只取其中一个值，没有进行变化

| Environment | Info |
|---|---|
| g2 | 3.5.11 |
| System | win 10 1909 |
| Browser | Chrome 79 |

---
类似的方法使用shape也不可以。

期望能根据值的变化，改变线的【部分颜色】和【部分形状】

**Comment by ayaka209** [comment]
在2018年发现了一个类似issue但是已被关闭且当时留的demo已无法访问。

**Comment by onepieceASL** [comment]
我也有类似问题，shape方法想用回调根据数据不同时间显示dot或者smooth,但是其实只能有1个，如果有dot了就算符合smooth的条件line也不会变成smooth了，style()，size(),color()函数也是类似问题

**Comment by simaQ** [comment]
目前不支持在一条折线上映射多段颜色
