### ISSUE TITLE
Stat.summary.percent方法有误

### ISSUE THREAD

**Issue by yitengruntu** [antvis/g2#183]
我想实现类似g2官网上「帕累托图」中的累积百分比，但是图例列表的样式是对的，代码详情里的百分比是错误的
https://antv.alipay.com/g2/demo/18-other/pareto-chart.html
<img width="370" alt="wx20171011-104527 2x" src="https://user-images.githubusercontent.com/12508042/31419992-86b79bc6-ae04-11e7-9d65-6a2c74800963.png">
<img width="595" alt="wx20171011-104549 2x" src="https://user-images.githubusercontent.com/12508042/31419994-8903614e-ae04-11e7-94b6-331ae09faa01.png">

**Comment by simaQ** [comment]
恩，你看下你的数据中参与的字段的数值是不是 '343' 这样的数字字符串，如果是，转换成数字就可以了

**Comment by yitengruntu** [comment]
不是啊，就是数字，而且官网上代码示例也是数字
<img width="1026" alt="wx20171011-223111 2x" src="https://user-images.githubusercontent.com/12508042/31447242-21ade29a-ae67-11e7-8c34-5efadb1fdd54.png">

**Comment by simaQ** [comment]
哦哦，尴尬了，好的，我了解了

**Comment by yitengruntu** [comment]
你可以查一下以前代码，我现在使用的是2.3.4，图表是正确的，但是tooltip显示有bug，我邮件你我的联系方式了

**Comment by dxq613** [comment]
这个是由于后面给 percent 函数加了个参数导致的

Stat.summary.percent(field, innerCompare);
是否在同一个分组中计算百分比，因为这个地方引起百分比层叠区域图的bug，所以将这个参数默认设置成了 false，你把这个参数改成 true 即可。

```js
chart.line().position(Stat.summary.cumulative(Stat.summary.percent('factor*times', true)))
        .size(2)
        .tooltip('..percent');
```
