### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by zwmmm** [antvis/G2#1835]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-f2.gitee.io/zh/docs/api/chart/tooltip/#xtip-ytip%E5%9B%9E%E8%B0%83%E5%87%BD%E6%95%B0%E7%94%A8%E6%B3%95](https://antv-f2.gitee.io/zh/docs/api/chart/tooltip/#xtip-ytip%E5%9B%9E%E8%B0%83%E5%87%BD%E6%95%B0%E7%94%A8%E6%B3%95)

### Steps to reproduce
打开文档就可以看到
![image](https://user-images.githubusercontent.com/30194521/71341329-7c5bcd00-2594-11ea-8bae-254bd5f2eaff.png)

### What is expected?
文档格式正确

### What is actually happening?
文档格式错乱，md未转换

| Environment | Info |
|---|---|
| g2 | 3.5.11 |
| System | window 10 |
| Browser | chrome |

**Comment by simaQ** [comment]
这个是 F2 的文档， @zengyue

**Comment by zwmmm** [comment]
发错地方了...
