### ISSUE TITLE
G2 3.6 版本的这个写法会导致 uglify 后逻辑错误

### ISSUE THREAD

**Issue by RaoHai** [antvis/G2#1848]
- [x]  I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/antvis/G2/blob/v3.6.x/packages/g2/src/animate/index.ts#L224](https://github.com/antvis/G2/blob/v3.6.x/packages/g2/src/animate/index.ts#L224)

### Steps to reproduce
https://github.com/antvis/G2/blob/v3.6.x/packages/g2/src/animate/index.ts#L224

以 lib 形式引用，混淆后 function name 会丢。导致动画逻辑走入另一分支，报错。

类似这种 

* https://github.com/antvis/G2Plot/issues/345
* https://github.com/antvis/G2Plot/issues/361
* https://github.com/antvis/G2Plot/issues/381

都是这个锅

### What is expected?
要判断 function.name 需要手动指定 name。

### What is actually happening?
不报错

| Environment | Info |
|---|---|
| g2 | 3.6.x |
| System | ALL |
| Browser | ALL |

**Comment by paleface001** [comment]
真相只有一个，犯人竟然是它！☠️

**Comment by simaQ** [comment]
楼上太中二了！

这个尽然会导致这种问题... 我的锅我的锅

**Comment by RaoHai** [comment]
> 楼上太中二了！
> 
> 这个尽然会导致这种问题... 我的锅我的锅

最小成本的改动就是在声明的地方 

```js
function groupScaleInX(....)
```

补一句

```js
groupScaleInX.name = 'groupScaleInX'; 
```

就好了。

**Comment by simaQ** [comment]
> > 楼上太中二了！
> > 这个尽然会导致这种问题... 我的锅我的锅
> 
> 最小成本的改动就是在声明的地方
> 
> ```js
> function groupScaleInX(....)
> ```
> 
> 补一句
> 
> ```js
> groupScaleInX.name = 'groupScaleInX'; 
> ```
> 
> 就好了。

秋生哥提个 PR 吧！

**Comment by hustcc** [comment]
代码提交了，看看吧，这个问题 G2Plot 里面好几个相关的。
