### ISSUE TITLE
多个图表共享图例

### ISSUE THREAD

**Issue by HenryQW** [antvis/G2#1849]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
N/A

### Steps to reproduce
N/A

### What is expected?
多个图表（同类型或不同类型）之间的图例共享。
在一些情况下同样的数据需要用不同的图表进行可视化，一个全局共享的图例可以节省屏幕空间。图例现有的filtering也可以共享，在所有的图表中过滤某一数据dimension。

### What is actually happening?
该功能待实现

| Environment | Info |
|---|---|
| g2 | 3.5.11 |
| System | macOS |
| Browser | Chrome latest |

**Comment by simaQ** [comment]
试用下 4.0

**Comment by HenryQW** [comment]
有相关文档吗？好多文档链接都404了。
https://g2.antv.vision/zh/docs/api/g2/interfaces/legendcfg

![image](https://user-images.githubusercontent.com/5896343/76129934-c899a380-6000-11ea-80fd-6bbe0df7342d.png)

**Comment by simaQ** [comment]
多个图表使用 View 视图创建即可，参考 https://g2.antv.vision/en/examples/candlestick/candlestick#k-and-column。


文档是链接的问题，我反馈下
