### ISSUE TITLE
图表容器外层添加transform样式时交互受影响

### ISSUE THREAD

**Issue by gracelinmumu** [antvis/G2#1850]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g2.gitee.io/zh/examples/column/basic](https://antv-g2.gitee.io/zh/examples/column/basic)

### Steps to reproduce
打开控制台，选中id="container"容器节点，手动添加style样式 transform: scale(0.8);

### What is expected?
鼠标hover时正常显示对应的tooltip

### What is actually happening?
鼠标hover显示的并非对应的tooltip，而是其他数据项的提示框，推测transform样式影响了坐标到数据的转换

| Environment | Info |
|---|---|
| g2 | 3.5.11 |
| System | Mac |
| Browser | 79.0.3945.88 |

**Comment by gracelinmumu** [comment]
![image](https://user-images.githubusercontent.com/7775683/71431368-5f4a0a00-270c-11ea-8a4c-46bb5e0747b2.png)
鼠标hover1958数据项时，tooltip显示1957相关数据

**Comment by simaQ** [comment]
关联 https://github.com/antvis/g/issues/333

**Comment by kisstherain** [comment]
貌似还没有解决啊

**Comment by hustcc** [comment]
G2 4.1.0-beta.13 版本已解决，最近 2 周内我们会发布 4.1 正式版
