### ISSUE TITLE
实时更新数据的折线图内存泄漏

### ISSUE THREAD

**Issue by ABoat365** [antvis/G2#1853]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/other/other#line-realtime](https://g2.antv.vision/zh/examples/other/other#line-realtime)

### Steps to reproduce
将[示例HTML代码](https://g2.antv.vision/zh/examples/other/other#line-realtime)创建一个html页面，用Chrome打开，在浏览器DevTools Memory中间隔打印快照，发现内存占用将越来越大。

### What is expected?
网页内存占用保持稳定

### What is actually happening?
网页内存占用越来越大

| Environment | Info |
|---|---|
| g2 | 3.5.11 |
| System | windows 10 |
| Browser | Google Chrome 版本 78.0.3904.108（正式版本） （64 位） |

**Comment by hustcc** [comment]
请使用 G2 4.0，感谢反馈 ^_^
