### ISSUE TITLE
地图显示变形问题，怎么设置长宽比例

### ISSUE THREAD

**Issue by huangyingwen** [antvis/g2#187]
地图显示变形问题，怎么设置长宽比例

**Comment by dxq613** [comment]
其实这种情况主要有两种方案：

1. 一种是自己动态调整 width,height
2. 另一种是动态调整列定义的 min,max

这里有个动态调整宽高的示例：https://antv.alipay.com/zh-cn/g2/3.x/demo/map/drill-down.html
