### ISSUE TITLE
自定义tooltip遮盖住了图，图上滑动不能改变tooltip的内容

### ISSUE THREAD

**Issue by lvovl** [antvis/g2#188]
使用自定义tooltip。
tooltip内容较多，tooltip面积比较大，遮盖住了部分图。
使用原生tooltip时，及时遮盖依旧可以更改tooltip内容。
自定义tooltip在canvas上层，有什么办法可以解决吗？

**Comment by dxq613** [comment]
这个，只能是允许 tooltip 移动到画布外面，保证鼠标不能移动到 tooltip 才能解决这个问题。2.3 不打算改了，3.0 中处理这个问题。
