### ISSUE TITLE
堆叠柱状图，当文本的label重叠在一起，有什么好的办法解决吗？

### ISSUE THREAD

**Issue by ZengZhenfei** [antvis/G2#1884]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。

**Comment by ZengZhenfei** [comment]
地址：https://codesandbox.io/s/wonderful-rgb-kr8t3

**Comment by simaQ** [comment]
这是因为 type: 'B' 的数据太小导致的，可以考虑隐藏部分文本：

```ts
pgChart
  .intervalStack()
  .position("time*value")
  .color("type", ["#FFFF00", "#F87C29", "#705dc8", "#38A0FF"])
  .opacity(1)
  .label("value", {
    type: 'treemap'
  })
```
