### ISSUE TITLE
重复图例 legend问题

### ISSUE THREAD

**Issue by zhaopeiym** [antvis/G2#1886]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kind-johnson-t8doo)

### Steps to reproduce
- 1、代码来自Antv G2使用文档 https://g2.antv.vision/zh/docs/manual/faq#%E5%A6%82%E4%BD%95%E7%BB%98%E5%88%B6%E5%A4%9A-y-%E8%BD%B4%E5%9B%BE%E8%A1%A8
- 2、怎么出现了两个“温度”图例。如果需要画线和点，并在只显示一个图例，有没有办法。
- 3、点击第二个“温度”图例（也就是“点”的温度图例），点击第二次的时候那个点消失了，文字还在。  
![image](https://user-images.githubusercontent.com/5820324/71657465-e9cce200-2d7a-11ea-96ae-e4d3e23f57bc.png)

### What is expected?
- 不管是画line、point、interval 如果position 里面的参数是一样的，只画一个图例。像这个效果 https://g2.antv.vision/zh/examples/line/double

### What is actually happening?
- 出现了多余的图例，且点击两次会有内容消息现象。

| Environment | Info |
|---|---|
| g2 | 3.5.11 |
| System | win10 |
| Browser | Chrome 78.0.3904.108 |

**Comment by simaQ** [comment]
使用自定义图例
