### ISSUE TITLE
官网文档是否有问题，示例代码好多“undefined”字符

### ISSUE THREAD

**Issue by CNAHYZ** [antvis/G2#1896]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g2.gitee.io/zh/docs/manual/tutorial/legend/#%E4%BD%BF%E7%94%A8-html-%E6%B8%B2%E6%9F%93%E5%9B%BE%E4%BE%8B](https://antv-g2.gitee.io/zh/docs/manual/tutorial/legend/#%E4%BD%BF%E7%94%A8-html-%E6%B8%B2%E6%9F%93%E5%9B%BE%E4%BE%8B)

### Steps to reproduce
直接打开

### What is expected?
去除无关字符

### What is actually happening?
如图

| Environment | Info |
|---|---|
| g2 | 3.5.11 |
| System | windows10 |
| Browser | firefox和Chrome均出现 |

---
图片链接
[https://imgchr.com/i/lse11g](https://imgchr.com/i/lse11g)

[https://imgchr.com/i/lse2Ax](https://imgchr.com/i/lse2Ax)

**Comment by simaQ** [comment]
我解决下

**Comment by afc163** [comment]
https://github.com/gatsbyjs/gatsby/issues/20270

**Comment by afc163** [comment]
1. <img width="490" alt="image" src="https://user-images.githubusercontent.com/507615/71872572-ced1e780-3157-11ea-8776-203aaa03a8cd.png"> inline block 的问题重新安装 node_modules 升级 `gatsby-remark-prismjs` 就可以了。
2. 其他地方检察一下代码类型是否准确：https://github.com/antvis/G2Plot/pull/472#discussion_r363599500

**Comment by simaQ** [comment]
感谢反馈，已解决！
