### ISSUE TITLE
饼图的label是否可以增加点击事件

### ISSUE THREAD

**Issue by shauvet** [antvis/g2#190]
由于我们饼图放置了比较多的数据，而且数据的量级差距也比较大，部分数据比较小时，鼠标没办法点击到图块，从而做操作。

因此希望可以支持label点击。在官方文档没找到这个api，貌似是不支持，希望可以支持下，谢谢。

**Comment by shauvet** [comment]
看了3.0的releasenote 貌似仍然不支持label点击啊？！难道不准备支持吗？同类图表很多都有这个的啊。。。为什么不支持下呢？

**Comment by dxq613** [comment]
3.0 将图表上的所有的图形的事件都放出来了，图形 + 事件名可以自由的组合。

```js
chart.on('label:click', function(ev) {
  console.log(ev.shape);
})；
```

![事件](https://gw.alipayobjects.com/zos/rmsportal/eFRpBGmvDRAhYnCcrnnh.png)

**Comment by shauvet** [comment]
感谢大佬，手动点赞
