### ISSUE TITLE
G2柱状图没法直接设置圆角显示，希望能提供配置参数

### ISSUE THREAD

**Issue by robin71** [antvis/G2#1904]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。

**Comment by simaQ** [comment]
因为我们的柱状图是通过 path 绘制的，所以目前无法通过样式配置参数设置。但是你可以通过自定义 shape 来实现哦，参考这个例子：https://g2.antv.vision/zh/examples/column/stack
