### ISSUE TITLE
legend中添加onClick后，chart.intervalStack()不执行

### ISSUE THREAD

**Issue by LPDLKBN** [antvis/G2#1909]
想实现点击对应的饼图项后，百分比重新计算，于是想在点击后手动改变数据百分比，发现在legend中添加onClick后，chart.intervalStack()不执行

**Comment by jamesjianpeng** [comment]
目前我也遇到这个问题，
1. 在没用使用 Legend onClick 事件的时候，点击 Legend  的一项，饼图会有对应的交互效果，但是总数不会变
2. 在使用 Legend onClick 之后，点击 Legend  的一项，饼图没有产生对应的变化

**Comment by simaQ** [comment]
请提供复现 demo。先将 issue 关闭，待回复后再跟进。
