### ISSUE TITLE
在散点图中，两点过于相近时，调用showTooltip，显示内容与选中不符。

### ISSUE THREAD

**Issue by OPY-bbt** [antvis/g2#191]
例如下面两个点
{x: 108.898603408, y: 251.98992}
{x: 108.884068884, y: 251.999776}
showTooltip 就会显示错误。

**Comment by dxq613** [comment]
showToolitp 方法跟鼠标移动到对应的位置显示的图形一致。由于点图存在半径，绘制在后面的会覆盖前面的，所以showTooltip 时，仅显示上面的点的信息（后绘制的点）。

**Comment by OPY-bbt** [comment]
哪有没有可以显示指定点的tooltip的方法呢

**Comment by dxq613** [comment]
现在查找点的原理是，谁在最上面能够捕捉到鼠标，就是谁。除非你动态调整节点的位置，否则临近的点，肯定是谁在上面谁被捕捉。

**Comment by dxq613** [comment]
chart 上有个 getSnapRecords 方法，可以得到最近的数据，你可以不使用 tooltip ，自己用Html 来显示对应的内容。

**Comment by OPY-bbt** [comment]
谢啦 现在用的方法是调整数据
