### ISSUE TITLE
条形统计图顶端带圆角，点击legend后，圆角边会消失

### ISSUE THREAD

**Issue by lbwhaha** [antvis/G2#1910]
function getFillAttrs(cfg) {
  const attrs = Util.mix(cfg.style, {
    fill: cfg.color,
    fillOpacity: cfg.opacity
  });
  return attrs;
}
function getRectPath(points) {
  const path = [];
  for (let i = 0; i < points.length; i++) {
    const point = points[i];
    if (point) {
      const action = i === 0 ? 'M' : 'L';
      path.push([ action, point.x, point.y ]);
    }
  }
  const first = points[0];
  path.push([ 'L', first.x, first.y ]);
  path.push([ 'z' ]);
  return path;
}
// 顶边带圆角
Shape.registerShape('interval', 'top', {
  draw(cfg, container) {
    const attrs = getFillAttrs(cfg);
    let path = getRectPath(cfg.points);
    path = this.parsePath(path); // 将 0 - 1 的值转换为画布坐标
    const radius = (path[2][1] - path[1][1]) / 2;
    const temp = [];
    temp.push([ 'M', path[0][1], path[0][2] ]);
    temp.push([ 'L', path[1][1], path[1][2] + radius ]);
    temp.push([ 'A', radius, radius, 90, 0, 1, path[1][1] + radius, path[1][2] ]);
    temp.push([ 'L', path[2][1] - radius, path[2][2] ]);
    temp.push([ 'A', radius, radius, 90, 0, 1, path[2][1], path[2][2] + radius ]);
    temp.push([ 'L', path[3][1], path[3][2] ]);
    temp.push([ 'Z' ]);
    return container.addShape('path', {
      attrs: Util.mix(attrs, {
        path: temp
      })
    });
  }
});
这是官方文档堆叠柱状图 顶端带圆角的图例，实际运用到条形统计图有部分修改，但在点击legend显示部分数据后 统计图的顶端圆角再不显示，求实际解决方案，官方文档中没有条形统计图带圆角的案例

**Comment by simaQ** [comment]
条形图的话， shape path 的参数需要更新下
