### ISSUE TITLE
legend 和Axis label 重叠

### ISSUE THREAD

**Issue by Leannechn** [antvis/G2#1917]
version: 3.5.9到最新版本存在问题，之前正常
https://antv-g2.gitee.io/zh/examples/gallery/column#column10
![image](https://user-images.githubusercontent.com/6812138/72157433-e11b8200-33f2-11ea-9969-74dd86cb31ca.png)

**Comment by simaQ** [comment]
试试 chart.legend({ position: 'top-left' });
