### ISSUE TITLE
动画能否重复播放

### ISSUE THREAD

**Issue by superlbr** [antvis/G2#1918]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
图标动画只能执行一次

### What does the proposed API look like?
```
<animate repeatCount="indefinite" />
```

**Comment by simaQ** [comment]
可以。 参考这个 demo，https://g2-v3.antv.vision/en/examples/gallery/line#line8

![image](https://user-images.githubusercontent.com/6628666/75988706-f7464a00-5f2c-11ea-9904-11655b7ec6b1.png)

往 G 的图形属性中设置 repeat: true

**Comment by superlbr** [comment]
1. 没有在这个demo里看到repeat的效果
2. 代码里貌似也没对repeat的处理
