### ISSUE TITLE
G2怎么实现水波图？

### ISSUE THREAD

**Issue by robin71** [antvis/G2#1919]
官网上没有找到水波图的列子，那G2怎么实现水波图？
![image](https://user-images.githubusercontent.com/7088782/72231408-3a9fce80-35f6-11ea-9f01-df600961e996.png)

**Comment by simaQ** [comment]
支持，参考 https://g2.antv.vision/en/examples/other/other#liquid-fill-gauge

**Comment by robin71** [comment]
好的，谢谢了

**Comment by li1164267803** [comment]
现在已经删除这个了

**Comment by li1164267803** [comment]
同求楼主是怎么用4.x的版本解决的水波图

**Comment by hurricane1998** [comment]
有人用G2实现过水波图吗？现在G2好像找不到水波图的例子了
