### ISSUE TITLE
蚂蚁金服可视化团队招聘

### ISSUE THREAD

**Issue by dxq613** [antvis/g2#192]
招可视化工程师、数据开发工程师

有想加入蚂蚁可视化团队发送简历到：antv@antfin.com

招聘简介：https://weibo.com/6196268597/Fxkt8aRwl

**Comment by shauvet** [comment]
G2用户支持下，表示达不到要求 (逃

**Comment by chenshuai2144** [comment]
正在面试antd 哈哈

**Comment by foreverwing99** [comment]
请问一下，G6可以应用与vue工程中吗？初学前端，不是很了解。

**Comment by chenshuai2144** [comment]
只要是js都可以
