### ISSUE TITLE
[4.0] 极坐标系下圆弧坐标轴文本支持可展示在内圆中

### ISSUE THREAD

**Issue by simaQ** [antvis/G2#1934]
如图所示：

![image](https://user-images.githubusercontent.com/6628666/72578670-b1e4a380-3911-11ea-8205-d0ba7130ff2d.png)

**Comment by hustcc** [comment]
这个做了嘛？是不是 axis 的 factor 配置？

**Comment by simaQ** [comment]
> 这个做了嘛？是不是 axis 的 factor 配置？

还咩有，先关闭，后面有机会再加上
