### ISSUE TITLE
官方文档示列代码有问题

### ISSUE THREAD

**Issue by wzx-3015** [antvis/G2#1953]
![TIM截图20200120140245](https://user-images.githubusercontent.com/29293904/72702452-b4ebc800-3b8d-11ea-8676-e6fbb54efa36.png)

# 示列地址：https://g2.antv.vision/zh/examples/gallery/column#column4

**Comment by simaQ** [comment]
抱歉对你造成困扰了，确实是 `shared`，同时这个 demo 里面不需要做这个配置，因为单柱状图不需要配置 shared tooltip，我改正下，谢谢反馈！
