### ISSUE TITLE
How do you update a chart with new data

### ISSUE THREAD

**Issue by Ali-hd** [antvis/G2#1955]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/falling-hill-iuini)

### Steps to reproduce
I want to update an existing chart with new data 

### What is expected?
A chart is generated with the new data without creating a new chart under the old chart

### What is actually happening?
a new chart is getting created under the old chart when i try to run my chart function again to use the new data

| Environment | Info |
|---|---|
| g2 | 3.5.11 |
| System | macOS Catalina |
| Browser | chrome |

**Comment by Ali-hd** [comment]
I found a solution! I gave the chart component a different key value for each data so the component will mount again and the old chart will be replaced

**Comment by super-commet** [comment]
I'm not sure
can you please show me the example?

**Comment by super-commet** [comment]
@Ali-hd 
I'm getting same issue. so I'm looking for a solution. can you show me the example of your solution?

**Comment by Ali-hd** [comment]
> @Ali-hd
> I'm getting same issue. so I'm looking for a solution. can you show me the example of your solution?

I used it for a date filter. so when I switch between 1/3/6 months I get different data. And make the key value of the chart component equal to the time period. When I change the time period the key will change and the component will remount.

**Comment by super-commet** [comment]
I'm not sure what you mean.

**Comment by super-commet** [comment]
```
const data = [
  { genre: 'Sports', sold: 275 },
  { genre: 'Strategy', sold: 115 },
  { genre: 'Action', sold: 120 },
  { genre: 'Shooter', sold: 350 },
  { genre: 'Other', sold: 150 },
];
```

**Comment by super-commet** [comment]
this is static data

**Comment by super-commet** [comment]
but I'm getting this data as props.
and according to the filter options, this data is changed.
but the old chart is not removed.

**Comment by super-commet** [comment]
how can I resolve this issue?

**Comment by Ali-hd** [comment]
show me the part when your passing the props to the chart component

**Comment by JonasJonny** [comment]
**Data Update**
_There are three main approaches to update data:_
```
• Just update data for the chart
• Clear and redraw
• Update with DataView
```

[G2 Documents > How to Load Data](https://www.yuque.com/antv/g2-docs-en/tutorial-loading-data#7ctibz)
