### ISSUE TITLE
tooltip 的 containerTpl 能否使用方法动态获取html，不仅仅是字符串

### ISSUE THREAD

**Issue by holidaypenguin** [antvis/G2#1956]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/docs/api/tooltip/#htmltooltip-%E5%B1%9E%E6%80%A7](https://g2.antv.vision/zh/docs/api/tooltip/#htmltooltip-%E5%B1%9E%E6%80%A7)

### Steps to reproduce
目前当用动态变量如startDate 或者 endDate 变化时，不能自动更新

itemTpl 也是如此，能否使用方法动态获取html

### What is expected?
containerTpl: () => {
  return `<div class="p-chart-tooltip">
                <div>${this.startDate} - ${this.endDate}</div>
                <div class="p-chart-tooltip-title g2-tooltip-title"></div>
                <ul class="p-chart-tooltip-list g2-tooltip-list"></ul>
             </div>`
}

### What is actually happening?
containerTpl: `<div class="p-chart-tooltip">
              <div>${this.startDate} - ${this.endDate}</div>
              <div class="p-chart-tooltip-title g2-tooltip-title"></div>
              <ul class="p-chart-tooltip-list g2-tooltip-list"></ul>
            </div>`

| Environment | Info |
|---|---|
| g2 | 3.5.11 |
| System | Win10 |
| Browser | Chrome |

**Comment by simaQ** [comment]
可以，配合 geometry.tooltip() 接口：https://g2-v3.antv.vision/en/docs/api/geometry/#tooltipfield-callback

**Comment by holidaypenguin** [comment]
https://g2.antv.vision/zh/docs/api/interfaces/tooltipcfg#code-classlanguage-textoptionalcode-containertpl

文档更新了，我指的是这个属性，你前面说的仅仅能动态更新 `<ul class="g2-tooltip-list"></ul>`其中的变量，在这里之外的将不能得到更新

假如页面上有时间选项，时间变化后当鼠标移入图表上，显示的tootip中在 class=g2-tooltip-list 之外的时间变量得不到更新，显示的还是老数据，所以该属性支持方法，将可动态指定需要显示数据。
