### ISSUE TITLE
同一个点表现形式不一样

### ISSUE THREAD

**Issue by jason19659** [antvis/g2#199]
<img width="687" alt="1" src="https://user-images.githubusercontent.com/3355273/32816676-9a5002ea-c97f-11e7-9073-bbedda21bca3.png">
有的有尖角，有的是平的

**Comment by dxq613** [comment]
这是canvas 本身关于线的属性导致的：http://www.w3school.com.cn/tags/canvas_linejoin.asp，跟线交叉地方的斜率相关，可以通过 .style 方法改一下这个属性

```
chart.line().style({lineJoin:'round'});
```
