### ISSUE TITLE
G2Plot 迁移 G2 4.0 遇到的问题汇总

### ISSUE THREAD

**Issue by paleface001** [antvis/G2#2005]
版本： 4.0.0-beta.12

- [x] tooltip设为follow的情况下对鼠标的躲避不灵敏，速度快的时候经常hover到上面
![tooltip](https://user-images.githubusercontent.com/5888974/74203484-bf8c0f80-4caa-11ea-8176-fb12b9c0a475.gif)

- [x] tooltip配置crosshair的情况下，吸附效果有问题
<img width="231" alt="屏幕快照 2020-02-11 上午8 52 44" src="https://user-images.githubusercontent.com/5888974/74203860-01698580-4cac-11ea-91be-ea6b64a3e7f5.png">

**Comment by simaQ** [comment]
法爷，给个复现的 demo 吧

**Comment by paleface001** [comment]
3、4的复现demo: https://riddle.alibaba-inc.com/riddles/faf7e6f2
1、2在riddle上复现不出来，很神奇

**Comment by paleface001** [comment]
#2018

**Comment by paleface001** [comment]
view增加cliper: https://github.com/antvis/scale/issues/32

**Comment by paleface001** [comment]
scale自动补齐：

```
{
  type:'interval',
   position:['value']
}
```
这样的写法报错

**Comment by paleface001** [comment]
grid绘制在图形上方

<img width="576" alt="屏幕快照 2020-02-12 下午4 08 24" src="https://user-images.githubusercontent.com/5888974/74315238-f9940900-4db1-11ea-90bb-00390679ce00.png">

**Comment by paleface001** [comment]
label错误绘制在图形下方
<img width="424" alt="屏幕快照 2020-02-12 下午4 23 39" src="https://user-images.githubusercontent.com/5888974/74316432-7b853180-4db4-11ea-9680-a60f3e49362b.png">

**Comment by hustcc** [comment]
@simaQ 因为 tooltip css 样式导致 g2plot 在网站中会渲染两次。（tooltip 的 dom 撑大容器，然后触发重新渲染）

之前 3.6.x 中也修复的，参考：https://github.com/antvis/G2/pull/1654

另外，这个 tooltip 样式的 pr，也可以看下在 4.0 是否也会存在问题 https://github.com/antvis/G2/pull/1649

**Comment by paleface001** [comment]
记录一下疑似G的bug： path动画无中间插值效果，待riddle复现

**Comment by BlackGanglion** [comment]
G2 4.x 无法拿到组件级别的渲染实例，例如：坐标轴标签，这样原本的一些测试逻辑无法实现，能否想之前一样挂载上去？

from [G2Plot#631](https://github.com/antvis/G2Plot/pull/631)

**Comment by paleface001** [comment]
这里也记录一下：
坐标系转置的情况下，分组interval的图形顺序与tooltip顺序不匹配 #2068

**Comment by simaQ** [comment]
> G2 4.x 无法拿到组件级别的渲染实例，例如：坐标轴标签，这样原本的一些测试逻辑无法实现，能否想之前一样挂载上去？
> 
> from [G2Plot#631](https://github.com/antvis/G2Plot/pull/631)

哟，可以拿到的。有这么几个方案：

1. 如果是拿 Component 实例，可以这样

```ts
const controller = chart.getController('axis');

// 获取所有 Component 实例
const components  = controller.getComponents();
```

2. 拿 shape 的话，可以直接从对应的图层进行查找

```ts
const regionShape = chart.backgroundGroup.findAll((el) => {
      // 根据 shape name 进行查找
      return el.get('name') === 'active-region';
    })[0];
```

**Comment by paleface001** [comment]
> > G2 4.x 无法拿到组件级别的渲染实例，例如：坐标轴标签，这样原本的一些测试逻辑无法实现，能否想之前一样挂载上去？
> > from [G2Plot#631](https://github.com/antvis/G2Plot/pull/631)
> 
> 哟，可以拿到的。有这么几个方案：
> 
> 1. 如果是拿 Component 实例，可以这样
> 
> ```ts
> const controller = chart.getController('axis');
> 
> // 获取所有 Component 实例
> const components  = controller.getComponents();
> ```
> 
> 1. 拿 shape 的话，可以直接从对应的图层进行查找
> 
> ```ts
> const regionShape = chart.backgroundGroup.findAll((el) => {
>       // 根据 shape name 进行查找
>       return el.get('name') === 'active-region';
>     })[0];
> ```

哟哟，棒呆

**Comment by paleface001** [comment]
@BlackGanglion  感觉取components shape的咱可以封成几个util方法，写单测的时候调用~

**Comment by BlackGanglion** [comment]
G2 4.0 未与 3.6.x 一样对 'null' 值进行处理，导致 getShape 时报错，这个G2、G2Plot 是否需要处理，在哪里处理？

https://riddle.alibaba-inc.com/riddles/c4078fa1

**Comment by paleface001** [comment]
> G2 4.0 未与 3.6.x 一样对 'null' 值进行处理，导致 getShape 时报错，这个G2、G2Plot 是否需要处理，在哪里处理？
> 
> https://riddle.alibaba-inc.com/riddles/c4078fa1

可以在 G2Plo t的 `processData` 方法里处理，对null值这一行数据直接剔除

**Comment by BlackGanglion** [comment]
散点图 point hover 现象，是否是配置问题？

https://riddle.alibaba-inc.com/riddles/19505374

![image](https://user-images.githubusercontent.com/9314735/75015618-03112580-54c4-11ea-93bb-5f4b00dd1be7.png)

**Comment by BlackGanglion** [comment]
> > G2 4.0 未与 3.6.x 一样对 'null' 值进行处理，导致 getShape 时报错，这个G2、G2Plot 是否需要处理，在哪里处理？
> > https://riddle.alibaba-inc.com/riddles/c4078fa1
> 
> 可以在 G2Plo t的 `processData` 方法里处理，对null值这一行数据直接剔除

恩，我调整一下

**Comment by paleface001** [comment]
> 散点图 point hover 现象，是否是配置问题？
> 
> https://riddle.alibaba-inc.com/riddles/19505374
> 
> ![image](https://user-images.githubusercontent.com/9314735/75015618-03112580-54c4-11ea-93bb-5f4b00dd1be7.png)

在g2plot的`getDefaultOptions`里配置tooltip，去掉marker:
```
tooltip:{
  showMarkers: false
}
```

**Comment by BlackGanglion** [comment]
> 使用 alternateColor 为网格设置交替的颜色，指定一个值则先渲染奇数层，两个值则交替渲染

grid alternateColor，3.x 是奇数层先渲染，4.0 是偶数层先渲染

**Comment by simaQ** [comment]
先关闭了。有问题单独提 issue 吧~
