### ISSUE TITLE
点图更新时有些点没有销毁

### ISSUE THREAD

**Issue by dxq613** [antvis/G2#2016]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。
![drag-scale1](https://user-images.githubusercontent.com/1264678/74224629-300b4e80-4cf4-11ea-8bf2-462d521467cc.gif)

**Comment by simaQ** [comment]
是由于数据源中存在重叠数据导致的，Geometry 在初始化绘制的时候没有处理这种情况~~~~~
