### ISSUE TITLE
如何调整label位置?

### ISSUE THREAD

**Issue by Bkhxq** [antvis/G2#2019]
做时间线图，一条直线有很多节点，遇到一个问题。因为节点比较密集，节点还需要加label描述，因此在某些区域出现label落一起的情况。label还不能删除，有什么办法调整label的位置吗？之前在excel中实现过，是读取point的坐标，得到对应label框的坐标和尺寸。然后根据算法，多次调整label位置。请问g2有途径调整吗，在api中未看到可以操作label的接口

**Comment by simaQ** [comment]
试下:

```ts
label('xxx', {
  type: 'map' // 或者 type: 'scatter'
})
```

https://g2.antv.vision/en/docs/api/geometry/#code-classlanguage-texttypecode-string

**Comment by Bkhxq** [comment]
试过了，会把一些label删了。我需要保留所有label. 谢谢！

**Comment by Bkhxq** [comment]
下图是采用map选项后的效果，很多节点的label没有了：
![image](https://user-images.githubusercontent.com/60950807/74297354-925e6080-4d81-11ea-9492-07f2415ad3c7.png)
之前用excel实现的效果：
![image](https://user-images.githubusercontent.com/60950807/74297839-fe8d9400-4d82-11ea-95c6-45a5d4b3e415.png)
能否添加这个功能，或者至少接口可以操作label

**Comment by simaQ** [comment]
可以使用 G2  4.0，开放了自定义 label 布局的功能，你可以完全按照自己的需求定制
