### ISSUE TITLE
view 上需要增加 clip 选项支持

### ISSUE THREAD

**Issue by dxq613** [antvis/G2#2020]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。

* 在缩放和拖拽画布时，图形会画到 view 外部，需要 view 上支持 clip

**Comment by paleface001** [comment]
之前迁移scale 3.0也遇到了这个需求，cc: https://github.com/antvis/scale/issues/32

**Comment by simaQ** [comment]
是不是在 Geometry 上粒度更细一些，可控性会强一点？

**Comment by paleface001** [comment]
> 是不是在 Geometry 上粒度更细一些，可控性会强一点？

不能在view上，会一起clip掉组件

**Comment by simaQ** [comment]
> > 是不是在 Geometry 上粒度更细一些，可控性会强一点？
> 
> 不能在view上，会一起clip掉组件

有哪些组件会在 view 的绘图区域的吗？

**Comment by paleface001** [comment]
> > > 是不是在 Geometry 上粒度更细一些，可控性会强一点？
> > 
> > 
> > 不能在view上，会一起clip掉组件
> 
> 有哪些组件会在 view 的绘图区域的吗？

看G2现在的设计了，3.x版本会把label和annotation截掉

**Comment by simaQ** [comment]
> > > > 是不是在 Geometry 上粒度更细一些，可控性会强一点？
> > > 
> > > 
> > > 不能在view上，会一起clip掉组件
> > 
> > 
> > 有哪些组件会在 view 的绘图区域的吗？
> 
> 看G2现在的设计了，3.x版本会把label和annotation截掉

哦哦，这个确实是的。不过即使在 Geometry 上设置 clip，因为 label 和 Annotation 还是跟图形数据的，一样会有问题。在 G2 4.0 里面，这个问题是交给 label 和 Annotation 自己解决，让他们在限定区域内自己进行调整。

**Comment by paleface001** [comment]
> > > > > 是不是在 Geometry 上粒度更细一些，可控性会强一点？
> > > > 
> > > > 
> > > > 不能在view上，会一起clip掉组件
> > > 
> > > 
> > > 有哪些组件会在 view 的绘图区域的吗？
> > 
> > 
> > 看G2现在的设计了，3.x版本会把label和annotation截掉
> 
> 哦哦，这个确实是的。不过即使在 Geometry 上设置 clip，因为 label 和 Annotation 还是跟图形数据的，一样会有问题。在 G2 4.0 里面，这个问题是交给 label 和 Annotation 自己解决，让他们在限定区域内自己进行调整。

如果geometry的shapes和label & annotation的container是分开的，那么只对geometry-shapeContainer做clip，其他组件应该不会受影响

**Comment by simaQ** [comment]
> > > > > > 是不是在 Geometry 上粒度更细一些，可控性会强一点？
> > > > > 
> > > > > 
> > > > > 不能在view上，会一起clip掉组件
> > > > 
> > > > 
> > > > 有哪些组件会在 view 的绘图区域的吗？
> > > 
> > > 
> > > 看G2现在的设计了，3.x版本会把label和annotation截掉
> > 
> > 
> > 哦哦，这个确实是的。不过即使在 Geometry 上设置 clip，因为 label 和 Annotation 还是跟图形数据的，一样会有问题。在 G2 4.0 里面，这个问题是交给 label 和 Annotation 自己解决，让他们在限定区域内自己进行调整。
> 
> 如果geometry的shapes和label & annotation的container是分开的，那么只对geometry-shapeContainer做clip，其他组件应该不会受影响

就拿带 label 的线图举例，单单把  line 给 clip 了，线上的 label 没有 clip，那么超出去的 label 不是看着就很怪吗？
