### ISSUE TITLE
默认的 slider 怎么关闭？

### ISSUE THREAD

**Issue by ppJuan** [antvis/G2#2039]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。

**Comment by ppJuan** [comment]
https://g2.antv.vision/zh/examples/heatmap/heatmap 官网上例子的热力图，滑块可以关闭吗？

**Comment by simaQ** [comment]
这个是默认生成的连续图例，可以关闭：

`chart.legend(false);`
