### ISSUE TITLE
legend 连续过滤时 scale 有问题，导致图越变越小

### ISSUE THREAD

**Issue by dxq613** [antvis/G2#2044]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。
![legend-error](https://user-images.githubusercontent.com/1264678/74508825-f5472780-4f3a-11ea-9c60-ed54961c6070.gif)

交互可以增加
```js
chart.interaction('legend-filter');
```
最新分支包含了内置 interactions 的不需要加

**Comment by hustcc** [comment]
复现 demo：http://localhost:8001/zh/examples/bar/dodge

原因：因为布局完成之后，会更新 coordinate 的 start、end，但是设置 scale、rotate 会在设置属性的时候就就更新 matrix，然后更新 coordinate 的 start、end 的时候，matrix 并没有更新，导致chart.update 的时候，布局乱掉的。

解决办法：

1. 参考 reflect 和 transpose，都做延迟执行 action（在 convert 的时候，再去执行）。
2. 执行 adjust start end 的时候，重新执行 scale、rotate 的 action

个人感觉第一个方案相对好一些，@simaQ 之前有解决办法吗？

**Comment by dxq613** [comment]
不明觉厉，感觉有些看不懂

**Comment by hustcc** [comment]
描述太复杂了~核心就是coordinate 的 scale rotate action 是直接作用到 matrix 了，所以 coordinate 在布局完成之后会更新 start end 的时候，matrix 并没有更新，导致在有 scale rotate 的时候，画布有偏移。

> 不明觉厉，感觉有些看不懂

**Comment by simaQ** [comment]
用第一种方案吧

**Comment by hustcc** [comment]
如果重新执行的话，那就需要考虑增加一个方法是 resetMatrix，在执行 action?
