### ISSUE TITLE
geom.label() 中使用 html 时不响应 tooltip

### ISSUE THREAD

**Issue by ppJuan** [antvis/G2#2053]
例子：https://antv-g2.gitee.io/zh/examples/heatmap/heatmap
将 `chart.polygon()` 部分改为以下代码后，鼠标移到数字上时没有 tooltip
```javascript
chart.polygon()
  .position('name*day')
  .color('sales', '#BAE7FF-#1890FF-#0050B3')
  .label('sales', {
  	   useHtml: true,
	   htmlContent: (sales) => `<span>${sales}</span>`,
  })
```

**Comment by ppJuan** [comment]
我想在热力图的格子中间显示图片，使用 html label 会有上述问题，还有其他方法吗？

**Comment by simaQ** [comment]
鼠标如果 hover 到 html label 的话，就离开了 canvas，事件就无法捕获了。

你可以自己监听该 html label 上的事件，然后手动调用 chart.showTooltip(); 来临时解决下。

**Comment by ppJuan** [comment]
> 鼠标如果 hover 到 html label 的话，就离开了 canvas，事件就无法捕获了。
> 
> 你可以自己监听该 html label 上的事件，然后手动调用 chart.showTooltip(); 来临时解决下。

html 形式不能用 react 写法，不好监听。已经改用 echarts 解决了
