### ISSUE TITLE
G2 交互问题以及 BUG  记录

### ISSUE THREAD

**Issue by simaQ** [antvis/G2#2054]
## 图例过滤问题

- [x] 分类图例过滤，当图例只有一个处于被选中状态时，再次点击，图表出错

![2020-02-15 16-17-14 2020-02-15 16_17_44](https://user-images.githubusercontent.com/6628666/74584559-bb475580-500e-11ea-8553-ed6f34e3dc30.gif)

- [x] element-visible-filter 对自定义图例不生效

http://riddle.alibaba-inc.com/riddles/a858ca95

- [x] 股票图图例过滤交互失败

http://riddle.alibaba-inc.com/riddles/d2ce2ffd

- [x] 热力图过滤后，坐标轴文本渲染不符合预期

http://riddle.alibaba-inc.com/riddles/abdbcacc

- [x] 漏斗图图例过滤有问题

http://riddle.alibaba-inc.com/riddles/d72ffe5f

- [x] 分面漏斗图过滤失败

http://riddle.alibaba-inc.com/riddles/e4eb938c

- [x] 多View 地图图例过滤失败

http://riddle.alibaba-inc.com/riddles/fc8fd89c

- [x] 地图过滤，将背景地图也过滤掉了

http://riddle.alibaba-inc.com/riddles/b879c5ae

- [x] 分类图例过滤失败
http://riddle.alibaba-inc.com/riddles/9914a21e

**Comment by simaQ** [comment]
- [ ] 折线图的 tooltip  和 active 不同步，体验不是很好，是否可以优化下

![2020-02-15 16-19-23 2020-02-15 16_19_50](https://user-images.githubusercontent.com/6628666/74584584-0497a500-500f-11ea-8786-7012e2b3f6cc.gif)

**Comment by simaQ** [comment]
- [ ] chart.interaction('active-region'); 不生效


http://riddle.alibaba-inc.com/riddles/c155b5fc

**Comment by simaQ** [comment]
- [ ] 极坐标系下分组柱状图的 active-region 背景框显示错误，未包围整个分组 

http://riddle.alibaba-inc.com/riddles/fd6c052f

![image](https://user-images.githubusercontent.com/6628666/74588586-ab446b80-5038-11ea-886f-2823b4454749.png)

**Comment by simaQ** [comment]
- [ ] 鼠标 hover 到 tooltip 上，一直闪烁，体验很不好

![2020-02-15 21-20-13 2020-02-15 21_21_11](https://user-images.githubusercontent.com/6628666/74588629-1beb8800-5039-11ea-8729-48d3c2b6aec4.gif)

**Comment by simaQ** [comment]
- [ ] 层叠柱状图的 element-highlight 是否可以优化为，相同分类的高亮，而不是单个

http://riddle.alibaba-inc.com/riddles/c930b5e


![image](https://user-images.githubusercontent.com/6628666/74588844-ee074300-503a-11ea-8a02-84943f6204bd.png)

**Comment by simaQ** [comment]
- [ ] 直方图的 active-region 宽度计算错误，预期应该是同直方图等宽

http://riddle.alibaba-inc.com/riddles/8a24fcf8

![image](https://user-images.githubusercontent.com/6628666/74588956-10e62700-503c-11ea-8504-da43b5369fc5.png)

**Comment by simaQ** [comment]
- [ ] 饼图更新动画待完善

**Comment by simaQ** [comment]
- [ ] 面积图默认的的 tooltip + active 效果不是很好

**Comment by simaQ** [comment]
- [ ] element-visible-filter 对自定义图例不生效

http://riddle.alibaba-inc.com/riddles/a858ca95

**Comment by simaQ** [comment]
- [ ] 分页图例布局计算出错

![image](https://user-images.githubusercontent.com/6628666/74601681-d207ae00-50db-11ea-9d8f-7a8d2e72ed8f.png)

**Comment by simaQ** [comment]
- [ ] 股票图图例过滤交互失败

http://localhost:8000/zh/examples/candlestick/candlestick#basic

**Comment by simaQ** [comment]
- [ ] 热力图过滤后，坐标轴文本渲染不符合预期

http://riddle.alibaba-inc.com/riddles/abdbcacc

**Comment by simaQ** [comment]
- [ ] 漏斗图图例过滤有问题

http://riddle.alibaba-inc.com/riddles/d72ffe5f

- [ ] 分面漏斗图过滤失败

http://riddle.alibaba-inc.com/riddles/e4eb938c

**Comment by simaQ** [comment]
- [ ] 多View 地图图例过滤失败

http://riddle.alibaba-inc.com/riddles/fc8fd89c

**Comment by simaQ** [comment]
- [ ] 地图过滤，将背景地图也过滤掉了

**Comment by simaQ** [comment]
- [ ] 分类图例过滤失败 
http://riddle.alibaba-inc.com/riddles/9914a21e

**Comment by simaQ** [comment]
- [ ] 分类图例过滤失败 
http://riddle.alibaba-inc.com/riddles/9914a21e

**Comment by simaQ** [comment]
- [ ] zoom 操作一下就卡顿

**Comment by simaQ** [comment]
- [ ]  brush mask 应该限制在当前 view 内
![2020-02-17 14-26-24 2020-02-17 14_26_49](https://user-images.githubusercontent.com/6628666/74628835-97f8e380-5191-11ea-8128-415b8591137f.gif)

**Comment by hustcc** [comment]
> * [ ]  分页图例布局计算出错
> 
> ![image](https://user-images.githubusercontent.com/6628666/74601681-d207ae00-50db-11ea-9d8f-7a8d2e72ed8f.png)
> 
> http://localhost:8000/zh/examples/area/streamgraph

@dxq613 排查了一下，问题在于当有 maxWidth 的时候，图例的 bbox.width 就直接等于 maxWidth 了，最好的直接等于 item 中最大的宽度。

![image](https://user-images.githubusercontent.com/7856674/74698184-efea2580-5237-11ea-8e73-c035ef9bf10e.png)

此时 maxWidth 等于画布的宽度 * 0.3，然后被直接返回成为 layoutBbox，宽度是 157，导致右侧空白很多。

**Comment by dxq613** [comment]
* [ ] 多view的时候， chart 上没有 geometry 时，crosshair 的位置不对
![image](https://user-images.githubusercontent.com/1264678/74729254-1e3f2380-527f-11ea-912d-cb3c2e51c539.png)

**Comment by simaQ** [comment]
> * [ ]  多view的时候， chart 上没有 geometry 时，crosshair 的位置不对
>   ![image](https://user-images.githubusercontent.com/1264678/74729254-1e3f2380-527f-11ea-912d-cb3c2e51c539.png)

原因：因为 chart 上的 padding 是 0，两个子 view 的 padding 不是 0，而 tooltip 又是挂载在 chart 上的，自然就取 chart 的坐标系范围... 所以就超出了。 

所以子 view 的 padding 问题还是要找时间解决下~~~  @hustcc

**Comment by simaQ** [comment]
- [ ] legend-highlight 交互，在图例被取消选中后仍然生效，预期不生效

![2020-02-21 17-49-38 2020-02-21 17_52_07](https://user-images.githubusercontent.com/6628666/75023528-e7f9e200-54d2-11ea-9142-4f121034b0f6.gif)

**Comment by simaQ** [comment]
- [ ] element 上关于状态的 action，当鼠标 hover 到文本图形的时候，失效了 @dxq613 

 
![2020-02-23 00-25-53 2020-02-23 00_27_17](https://user-images.githubusercontent.com/6628666/75095748-44dcc180-55d3-11ea-96bd-d10e7370be59.gif)

**Comment by mrh-code-star** [comment]
分面使用changeData实现动态更新数据，页面渲染出错，没有办法只能用data+render的方法进行数据更新，但是这种方法页面更新时页面会闪动
