### ISSUE TITLE
crosshairs: rect 的 tooltip 位置怎么设置跟随数据位置？

### ISSUE THREAD

**Issue by ppJuan** [antvis/G2#2055]
crosshairs: rect 的 tooltip 位置怎么设置跟随条形图位置？
目前当鼠标hover到 crosshair 上时，tooltip 默认固定在图像右侧，而鼠标hover到条形图上，tooltip 默认跟随数据位置。导致鼠标在x轴上移动时，tooltip 有一种乱跑的感觉，容易给人误解。

![001](https://user-images.githubusercontent.com/13941067/74585720-c0aa9d00-501a-11ea-9bc2-ab897561961c.gif)

```javascrip
const data = [
  { country: '巴西', population: 282030 },
  { country: '印尼', population: 234890 },
  { country: '美国', population: 290340 },
  { country: '印度', population: 204970 },
  { country: '中国', population: 231744 }
];
const chart = new G2.Chart({
  container: 'container',
  width: 300,
  height: 300
});
chart.tooltip({
  position: 'right',
  inPlot: false,
})
chart.source(data);
chart.interval().position('country*population');
chart.render();
```

**Comment by simaQ** [comment]
```ts
chart.tooltip({
  position: 'top',
  inPlot: false
});
```

**Comment by ppJuan** [comment]
> ```ts
> chart.tooltip({
>   position: 'top',
>   inPlot: false
> });
> ```

没有解决。在鼠标连续 rect 背景时，tooltip还是会变到图形上方。导致连续经过 rect 和条形时，tooltip 位置飘忽不定。
