### ISSUE TITLE
tooltip item marker支持渐变色

### ISSUE THREAD

**Issue by paleface001** [antvis/G2#2060]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。

这个问题是3.x时代就有的，不知道4.0能不能解。
复现riddle: https://riddle.alibaba-inc.com/riddles/26906008

os: interval上出现了迷之切割痕迹
<img width="265" alt="屏幕快照 2020-02-17 下午4 05 51" src="https://user-images.githubusercontent.com/5888974/74634728-6a1a9b80-519f-11ea-9c60-c38d6bf089ad.png">

**Comment by simaQ** [comment]
https://github.com/antvis/component/pull/139

**Comment by simaQ** [comment]
![image](https://user-images.githubusercontent.com/6628666/74807025-62cfcb00-5322-11ea-8288-265cd2d737ef.png)

升级 @antv/component 到 beta.29 即可~~~
