### ISSUE TITLE
坐标系转置的情况下，分组interval的图形顺序与tooltip顺序不匹配

### ISSUE THREAD

**Issue by paleface001** [antvis/G2#2068]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。

不好意思我又来了~ 如题~
<img width="700" alt="屏幕快照 2020-02-18 下午6 16 01" src="https://user-images.githubusercontent.com/5888974/74726717-e8983b80-527a-11ea-9cc2-044ecd23e82d.png">

**Comment by simaQ** [comment]
这个问题好像一直存在。。。 

但是如果是在 G2PLOT 里面，还是有解决方案的，建议使用：

```ts
chart
  .coordinate()
  .transpose()
  .scale(1, -1);
```

代替：

```ts
chart
  .coordinate()
  .transpose();
```

这样就完美解决了~ 秒，就是这样！

**Comment by paleface001** [comment]
ok，我配置一下~  
貌似legend也是反的，在plot里通过配置scale解的~
喵喵喵

**Comment by simaQ** [comment]
![image](https://user-images.githubusercontent.com/6628666/74790675-3fd9f280-52f3-11ea-8fe8-66e5df4a514b.png)

这样配置了之后都一致了。

还有个办法就是通过 scale 的 values 解决，4.0 里面解决了 3.x 的一个问题，当用户通过 scale 定义 values 后，geometry 也需要按照 values 对数据进行分组了~~~
