### ISSUE TITLE
Guide 事件支持区分单一实例

### ISSUE THREAD

**Issue by arcthur** [antvis/g2#207]
Guide 在 event 返回中没有字段支持只识别某一个实例作更精细的操作，建议增加唯一 key 来区分

**Comment by dxq613** [comment]
还没想好用什么方式来分别，正在讨论实现方案，目前对于一般的 geometry 来说 origin 的数据能够分辨，对于 axis,legend，guide 之类的有几种方式可以来分辨。

* 在每个 guide 、axis 中配置 events, 直接写回调函数
* 在配置项增加一个字段 （key、name）之类的名字，在 event.name、event.key 的方式来辨别
* 扩展 chart.on('xxx:click') 的前缀定制能力，用户可以自己定制某些组件的前缀

**Comment by simaQ** [comment]
supported at version 3.0.1，see details at [PR 228](https://github.com/antvis/g2/pull/228)

```js
chart.guide().line({
  appendInfo: {
    myid: 'suga'
  }
});

chart.on('guide-line:click', ev => {
  console.log('guide-line:click', ev.appendInfo);
});
```
