### ISSUE TITLE
tooltip 自定义htmlContent 与enterable 同时使用失效bug

### ISSUE THREAD

**Issue by Leannechn** [antvis/G2#2072]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g2.gitee.io/zh/examples/gallery/line#line1](https://antv-g2.gitee.io/zh/examples/gallery/line#line1)

### Steps to reproduce
打开官网任意demo，同时使用上诉两个api
```
 enterable: true,
 htmlContent: () => '<div style="position: absolute;"></div>'
```

### What is expected?
tooltip生效，enterable 生效

### What is actually happening?
tooltip异常

| Environment | Info |
|---|---|
| g2 | 3.5.12 |
| System | mac |
| Browser | chrome |

**Comment by simaQ** [comment]
请提供 demo

**Comment by Leannechn** [comment]
> 请提供 demo
1. 官网开任意demo，tooltip配置 复制那两行就出现了。可以注释一下，或者配置一下调试。
2. 官网的demo 上面的 riddle，sandbox，打开都是无效的。创建一个，不如打开给你的链接，直接调试。

**Comment by simaQ** [comment]
需要给你自定义的 html 的 div 加上 class="g2-tooltip"
