### ISSUE TITLE
如何修改鼠标移入辅助线上点的样式，使其和point的shape一致

### ISSUE THREAD

**Issue by BovineBoy** [antvis/G2#2074]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---
![image](https://user-images.githubusercontent.com/41846364/74911430-8c0e5b00-53f7-11ea-9062-35e15621e0a1.png)

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。

**Comment by simaQ** [comment]
参考下这个 demo: https://github.com/antvis/G2/blob/master/demos/area-line-stack.html

**Comment by BovineBoy** [comment]
> area-line-stack.html

已解决，感谢
