### ISSUE TITLE
怎么修改Legend的文本的颜色？

### ISSUE THREAD

**Issue by ZengZhenfei** [antvis/G2#2079]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
修改Legend的文本的颜色

### What does the proposed API look like?
可以修改Legend的文本的颜色

**Comment by simaQ** [comment]
3.x 版本不支持，建议使用最新发布的 G2 4.0.0 版本，在 `chart.legend()` 接口中配置：

```ts
// 4.0.0 版本
chart.legend({
  itemName: {
    style: {}
  }
});
```
