### ISSUE TITLE
axis 显示 title 支持value是 true

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#208]
### Summary
axis 显示 title 支持value是 true

### Expected behavior
chart.axis('field', {
  title:true
})
### Actual behavior
实际需要写成 obj，轴的 title 才显示。
chart.axis('field', {
  title:{}
})

**Comment by dxq613** [comment]
这个问题主要是新版本的视觉设置要求默认不显示坐标轴引起的，本来默认显示的，设置成 title: null 没人感觉到不舒服。但是反过来就有问题了，title: true 、title: {} 的问题不仅仅是 axis 自己的问题， title: true， title: false 的方式 axis, legend 都要进行支持，包括 tooltip 目前使用的是 showTitle 都存在不一致的问题。

这些不一致和不顺利在后面的版本中处理。

**Comment by dxq613** [comment]
已经修复，周四正式发布。

**Comment by simaQ** [comment]
supported at verison 3.0.1, see detail at 
 [7f4cf307](https://github.com/antvis/g2/commit/7f4cf30788c70d2137c62ca41de569b4c61cc15f)
