### ISSUE TITLE
Fail to display tooltip near sparse points when point x-axis intervals are different. 数据稀疏部分的tooltip很难用鼠标定位到显示。

### ISSUE THREAD

**Issue by bunnyxt** [antvis/G2#2080]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/inspiring-heisenberg-7rpvn?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
左侧数据点稀疏，鼠标只有精确移动到点附近时才会出现tooltip，鼠标移动过程中tooltip显示时断时续；右侧数据点密集，鼠标移动过程中tooltip很少出现不显示的情况。

### What is expected?
提供设置项，设置为true之后，在整个图表中，无论鼠标移动到哪里，都会显示最接近的数据点的tooltip，鼠标移动过程中tooltip不会时断时续。

### What is actually happening?
左侧数据稀疏部分很难定位到数据点附近显示tooltip.

| Environment | Info |
|---|---|
| g2 | 3.5.12 |
| System | macOS 10.15 & Windows 10 |
| Browser | Safari 13.0.5 & Chrome 79.0.3945.130 |

---
业务网站：https://tdd.bunnyxt.com/video/av2129461  可以看到下方「历史趋势」表左侧出现tooltip很难定位，时断时续的现象。

**Comment by simaQ** [comment]
我点进去体验了下，并没有看到你描述的现象。
