### ISSUE TITLE
修改 Slider配置,增加minSpan配置,但是没有效果 

### ISSUE THREAD

**Issue by siaron** [antvis/G2#2083]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/other/other/](https://g2.antv.vision/zh/examples/other/other/)

### Steps to reproduce
- 修改 Slider配置,增加minSpan配置,但是没有效果 
```
chart.interact('slider', { container: 'slider', data: dv.rows, start: ds.state.start, // 和状态量对应 end: ds.state.end, scales: scale, xAxis: 'time', yAxis: 'flow', minSpan: 1 * 60 * 60 * 1000, maxSpan: 6 * 60 * 60 * 1000, backgroundChart: { type: 'line', color: 'grey' },
```

### What is expected?
配置项可以自定义设置.底层滑动栏最小间隔为设置的.minSpan: 1 * 60 * 60 * 1000, maxSpan: 6 * 60 * 60 * 1000

### What is actually happening?
配置没有起效

| Environment | Info |
|---|---|
| g2 | 3.5.9 |
| System | windows10 |
| Browser | 版本 78.0.3904.108（正式版本） （64 位） |

**Comment by curryhh** [comment]
请问一下怎么解决的？

**Comment by hustcc** [comment]
不支持这个配置。
