### ISSUE TITLE
interact slider 没有提供更新方法，无法更新数据

### ISSUE THREAD

**Issue by hoythan** [antvis/G2#2087]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
之前的 new Slider 可以通过 slider.update 进行数据的更新，但是  chart.interaction('slider') 无法使用此方法。示例和 api 文档均未提供相关方法。

### What does the proposed API look like?
允许 slider 进行数据更新

**Comment by Airkro** [comment]
slider 的问题已经一年多了，使用起来非常困难

**Comment by simaQ** [comment]
可以使用 G2 4.0，参考 https://g2.antv.vision/zh/examples/area/basic#area-large

**Comment by 307god** [comment]
> 可以使用 G2 4.0，参考 https://g2.antv.vision/zh/examples/area/basic#area-large

请问示例中，chart.option的配置项哪里看到的？谢谢

**Comment by sworlife** [comment]
> slider 的问题已经一年多了，使用起来非常困难

```
const slider = chart.getInteractions().slider;
slider.data = this.data;
slider.start = this.ds.state.start;
slider.end = this.ds.state.end;
slider.repaint();
```
我用以上方法来更新数据，希望可以解决你的问题
