### ISSUE TITLE
Uncaught TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by pigletfly** [antvis/g2#209]
### Summary
when mouse moves over a line chart , an error occurs
### Environment
chrome 62.0.3202.94  g2 2.3.13
```
            __setEvn: function(t) {
                var e = this;
                t.__cfg.parent = e,
                t.__cfg.context = e.__cfg.context,
                t.__cfg.canvas = e.__cfg.canvas,
                t.__cfg.totalMatrix = null;
                var n = t.__attrs.clip;
                n && (n.setSilent("parent", e),
                n.setSilent("context", e.get("context")));
                var i = t.__cfg.children;
                i && a.each(i, function(e) {
                    t.__setEvn(e)
                })
            },
```
I use chrome devtools to inspect, it highlights this line `t.__cfg.totalMatrix = null;`
Also I am using G2 with React
### Steps to reproduce the behavior

**Comment by dxq613** [comment]
I think this may be caused by react's life cycle，you can use viser.  https://viserjs.github.io/.

**Comment by pigletfly** [comment]
when g2-react will be compatible with G2 3.0.0 ?

**Comment by dxq613** [comment]
你还可以使用 bizchart 也是使用 g2 封装的 ,比 g2-react 更适合react

https://alibaba.github.io/BizCharts/index.html

g2-react 后面我们不打算升级到支持 3.0 了，毕竟这种简单的封装，问题太多。

**Comment by pigletfly** [comment]
I will have a try
