### ISSUE TITLE
Uncaught TypeError: chart.interaction is not a function

### ISSUE THREAD

**Issue by Yeba** [antvis/G2#2091]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kind-bhaskara-ptuby?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
i just run the index.html, but it has no graph. the console of chrome show: Uncaught TypeError: chartYear.interaction is not a function

### What is expected?
show as this: https://f2.antv.vision/zh/examples/line/basic#pan-smooth

### What is actually happening?
no graph

| Environment | Info |
|---|---|
| g2 | 3.4.2 |
| System | android;windows |
| Browser | android system webview 80;chrome 79 |

---
i run it in h5 way, so i did not use import, i use <script src="https://gw.alipayobjects.com/os/antv/assets/f2/3.4.2/f2.js"></script> in html

**Comment by simaQ** [comment]
`<script src="https://gw.alipayobjects.com/os/antv/assets/f2/3.4.2/f2.js"></script>` did not offer chart ineractions for package size consideration. You should use `<script src="https://unpkg.com/@antv/f2@3.4.2/dist/f2-all.min.js"></script>`.

By the  way, it is recommended to submit this issue to the F2 repo: https://github.com/antvis/f2.
