### ISSUE TITLE
legend未选中字体大小怎么改？

### ISSUE THREAD

**Issue by nuintun** [antvis/g2#21]
![qq 20161013104937](https://cloud.githubusercontent.com/assets/1730277/19335236/622e0ba2-9134-11e6-90e6-483fa4b50bba.png)

如图：
```js
chart.legend('name', {
  word: {
    fill: '#424242',
    fontSize: 14
  },
  itemWrap: true,
  position: 'bottom'
});
```
未选中的不生效！
如果开源还能自己去找找源码，现在完全无头绪:joy:

**Comment by TomHuangCN** [comment]
是个bug，下周四更新修复

**Comment by nuintun** [comment]
:ok_hand: 坐等真正开源~
