### ISSUE TITLE
我看样例里面没有找到这种树形数据的图

### ISSUE THREAD

**Issue by zhaoxiongfei** [antvis/g2#210]
<img width="798" alt="_9b30c48d-24a7-43a1-9457-2df243b276f3" src="https://user-images.githubusercontent.com/1306392/33166108-0e13863e-d074-11e7-804d-79b1fb42c321.png">

**Comment by leungwensen** [comment]
关系图我们推荐用 G6 来画： https://antv.alipay.com/zh-cn/g6/1.x/demo/gallery/us-cpi.html

**Comment by zhaoxiongfei** [comment]
感谢这么快回复，没的说，非常棒
