### ISSUE TITLE
G2 4.0 饼图圆心坐标获取有偏差

### ISSUE THREAD

**Issue by Me-Momo** [antvis/G2#2100]
复现地址：https://riddle.alibaba-inc.com/riddles/94fc296f

**Comment by simaQ** [comment]
并没有存在偏差，是你绘制的 rect 问题，rect 的起点是左上角，就是圆心的位置.

![image](https://user-images.githubusercontent.com/6628666/76145116-78cee100-60c1-11ea-99bb-eade8371618b.png)

**Comment by Me-Momo** [comment]
![image](https://user-images.githubusercontent.com/15646325/76146351-e2a0b800-60cc-11ea-92cf-8b09f1356dfa.png)
![image](https://user-images.githubusercontent.com/15646325/76146360-ef251080-60cc-11ea-83ce-e42c1ff8e371.png)

奇怪了，我上次是这样的...
