### ISSUE TITLE
可以实现金字塔类型的这种报表吗？

### ISSUE THREAD

**Issue by ZengZhenfei** [antvis/G2#2101]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by ZengZhenfei** [comment]
![image](https://user-images.githubusercontent.com/29648356/75511859-7d90f680-5a2a-11ea-8c80-27cb5bc718b1.png)

**Comment by simaQ** [comment]
https://github.com/antvis/G2/issues/2105
