### ISSUE TITLE
饼图label支持折线

### ISSUE THREAD

**Issue by cztflove** [antvis/G2#2110]
希望饼图label的连接线可以支持下图这样的折线
如果有demo可以实现类似效果也可
issue中有一条类似的问题，但demo访问地址已经失效
![image](https://user-images.githubusercontent.com/36810290/55153491-84194d00-518d-11e9-80f5-f8c7438609fb.png)

**Comment by simaQ** [comment]
3.x 的demo地址： https://antv-2018.alipay.com/zh-cn/g2/3.x/demo/pie/pie8.html

G2 4.0 后续会支持
