### ISSUE TITLE
当鼠标在图标上时 页面无法滚动

### ISSUE THREAD

**Issue by xiaoyu-tamu** [antvis/G2#2111]
我最近刚开始用G2， 不确定这个是feature还是bug 当鼠标放在饼图的时候滑动滚轮， 此时无法滚动页面。我尝试搜了issues和docs 似乎并没有发现相关的配置。 

可以尝试这个demo https://g2.antv.vision/en/examples/pie/basic 当tooltip显示的时候尝试滑动鼠标

线图也会这样 如果把鼠标放到mark上时 无法滚动页面

* **G2 Version**: 4.0
* **Platform**: React
* **Mini Showcase(like screenshots)**: 静图无法表示
* **CodePen Link**:

**Comment by dxq613** [comment]
因为有些交互是滚动鼠标滑轮，缩放图表，还有自定义的滚动条组件。所以在图表上触发 scroll 事件时，preventDefault 了，阻止了滚轮默认的行为。

**Comment by aqzas** [comment]
同问，现在的话可以通过哪个配置调节这个行为？

**Comment by dxq613** [comment]
已经提交了 MR，合并了，下周新版本发布。
