### ISSUE TITLE
【4.x】雷达图 point 上的标签设为 interval 后设置 position 报错

### ISSUE THREAD

**Issue by BlackGanglion** [antvis/G2#2113]
* **G2 Version**: G2 4.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://riddle.alibaba-inc.com/riddles/347a5ad1

雷达图使用 polar 标签布局比较奇怪，设置 interval 后配置 position 会报错

From https://github.com/antvis/G2Plot/pull/692

**Comment by simaQ** [comment]
oh my god! 我的天哪！

为什么要在 point 上硬套  interval 类型的 label...  你们是想要什么效果？

**Comment by paleface001** [comment]
雷达图为啥要套interbal类型的。。

**Comment by BlackGanglion** [comment]
> oh my god! 我的天哪！
> 
> 为什么要在 point 上硬套 interval 类型的 label... 你们是想要什么效果？

雷达图标签这样径向布局不是很奇怪么。。。

**Comment by paleface001** [comment]
<img width="521" alt="屏幕快照 2020-03-03 下午2 09 57" src="https://user-images.githubusercontent.com/5888974/75747758-be557c00-5d58-11ea-856b-e5f0b333abdf.png">
用默认label就可以

**Comment by paleface001** [comment]
@simaQ  所以我觉得g2层label按coord+geom做细分很有必要，以前那些判断坐标系的layout逻辑都可以细分拆出来，对用户也更好理解、更完备

**Comment by BlackGanglion** [comment]
> <img alt="屏幕快照 2020-03-03 下午2 09 57" width="521" src="https://user-images.githubusercontent.com/5888974/75747758-be557c00-5d58-11ea-856b-e5f0b333abdf.png">
> 
> 用默认label就可以

![image](https://user-images.githubusercontent.com/9314735/75747900-1be9c880-5d59-11ea-84dc-90d5c049045c.png)
我感觉要按照 point 去排布标签，而不是 coord

**Comment by BlackGanglion** [comment]
当然这里用 interval 确实不合理

**Comment by BlackGanglion** [comment]
> 雷达图为啥要套interval类型的。。

是的，这里用 interval 确实不合理，但似乎没有其他解法，要不就是 plot 层用自己的 point label，后面雷达图麦芽也设计了一些 label 的规则，可以在 plot 中自定义

**Comment by BlackGanglion** [comment]
```js
{
  type: 'polar',
  autoRotate: false
}
```
