### ISSUE TITLE
G2的图表，日期数据从闰年29号开始（第一条数据），存在数据处理bug

### ISSUE THREAD

**Issue by junxtx** [antvis/G2#2115]
![image](https://user-images.githubusercontent.com/10458463/75775420-e9f25980-5d8c-11ea-96ed-b09d6a4e449b.png)
数据源第一条数据为闰年2月29号时，导致数据判定无效，整个图表渲染失败，引起页面雪崩

本人项目中使用3.x
去官方4.x测试同样存在这个问题

**Comment by junxtx** [comment]
补充个测试数据
```
[{
    "date": "20200229",
   "count": 2
      },{
      "date": "20200301",
       "count": 2
      }, {
     "date": "20200302",
     "count": 2
}]
```

**Comment by simaQ** [comment]
使用 'YYYY-MM-DD' 时间格式吧

**Comment by junxtx** [comment]
> 使用 'YYYY-MM-DD' 时间格式吧

意思是不支持YYYYMMDD的时间格式了

**Comment by simaQ** [comment]
> > 使用 'YYYY-MM-DD' 时间格式吧
> 
> 意思是不支持YYYYMMDD的时间格式了

支持，但是你可以现在项目上暂时用这个方案解决。

**Comment by simaQ** [comment]
https://github.com/antvis/scale/issues/37

**Comment by skywi** [comment]
I solved this problem by adding a space to zero before the date;
Eg. '20200229' -> ' 20200229'
Hope to fix this bug soon!

**Comment by skywi** [comment]
I am adding a space before the date to fix this temporarily;
Eg. '20200229' -> ' 20200229'
Hope to fix this bug soon!

**Comment by skywi** [comment]
I am adding a space before the date to fix this temporarily;
Eg. '20200229' -> '  20200229'
Hope to fix this bug soon!

**Comment by Leannechn** [comment]
已发布 @3.5.13 #2127
