### ISSUE TITLE
不知道玉玦图的圆角是怎么画出来的

### ISSUE THREAD

**Issue by EdikWang** [antvis/g2#212]
通过自定义shape也没搞出来

**Comment by chenshuai2144** [comment]
应该给个图例的.

**Comment by simaQ** [comment]
[示例链接](https://antv.alipay.com/zh-cn/vis/blog/make-rounded-column-chart.html#_最后，极坐标下的圆角矩形) 参考下这篇 blog

**Comment by EdikWang** [comment]
谢谢！
