### ISSUE TITLE
如何实现自定义象形图

### ISSUE THREAD

**Issue by fingerpan** [antvis/G2#2124]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

如题，开发中自定义图形的变异柱状图需求还是很大。
想请教一下，如何实现类似图形。
![image](https://user-images.githubusercontent.com/22525946/76077121-156a8380-5fdb-11ea-9741-2b3b0bbac9af.png)

绘制引擎G中，如果我有SVG paths（Path2D）路径，能在G的shape 渲染出来吗？感觉转换为 path shape 的解析数组对象行不通。

**Comment by simaQ** [comment]
有一个思路：利用 clip 剪切，为柱状图的 rect 矩形设置象形图形状的 clip.

**Comment by fingerpan** [comment]
> 有一个思路：利用 clip 剪切，为柱状图的 rect 矩形设置象形图形状的 clip.

clip 方式剪切是 绘制引擎 G 提供的吗？ 还是需要拿到canvas 对象自己绘制？

**Comment by simaQ** [comment]
G 提供的，https://g.antv.vision/zh/docs/api/general/element#setclipclip

```ts
import * as G from '@antv/g-canvas';

const canvas = new G.Canvas({
  container: 'mountNode',
  width: 300,
  height: 300,
});

// 创建一个 group,往里面添加 path,然后对 group 设置 clip，做 clip 动画
const container = canvas.addGroup();

// container 设置一个 clip 区域
container.setClip({
  type: 'rect',
  attrs: {
    x: 20,
    y: 20,
    width: 150,
    height: 200,
  },
});

// container 中添加一个 shape
container.addShape({
  type: 'path',
  attrs: {
    path: [
      ['M', 10, 10],
      ['L', 33, 15],
      ['L', 65, 10],
      ['L', 140, 60],
      ['L', 200, 250],
    ],
    stroke: 'red',
    lineWidth: 2,
  },
});
```
