### ISSUE TITLE
尖底漏斗图显示问题

### ISSUE THREAD

**Issue by hsiaosiyuan0** [antvis/g2#213]
* **G2 Version**: 线上 demo 可重现，见下方链接
* **Platform**: chrome Version 62.0.3202.94 (Official Build) (64-bit)
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

https://antv.alipay.com/zh-cn/g2/3.x/demo/funnel/pyramid.html?theme=default

<img src="http://og9g58alt.bkt.clouddn.com/WX20171124-112047@2x.png" width="300">

bug 如上图

复现步骤:

1. 对于上图中标注项，从右往左依次取消选中
2. 再从左往右依次勾选

**Comment by simaQ** [comment]
这个是动画变化的问题，下次迭代修复下，目前可以通过 `chart.animate(fale)` 将动画关闭，就没有问题了。

**Comment by hsiaosiyuan0** [comment]
插科打诨一下，黑白的头像比较适合放自己讨厌的人 :-p
