### ISSUE TITLE
建议增加下钻功能.

### ISSUE THREAD

**Issue by chenshuai2144** [antvis/g2#214]
钻取是改变展现数据维度的层次，变换分析的粒度。它包括向上钻取（drillup）和向下钻取（drilldown）

这里是简单的示例 
https://code.hcharts.cn/highcharts/hhhhys

如果要展示丰富的数据维度.这个功能是最好的实现

**Comment by simaQ** [comment]
我们正在丰富交互功能

**Comment by chenshuai2144** [comment]
你们最近有计划加入这个功能吗?
我不是很了解这个项目的api,如果要pr需要一段时间上手.
如果没有计划,我可以pr一下.也不会和你们的计划冲突

**Comment by simaQ** [comment]
有计划的，而且优先级最高

**Comment by chenshuai2144** [comment]
期待! pr需要好好看一下这个项目了.  
我是CRLF 你们是LF.
你们的是怎么查看预览的呢?直接通过demo?

**Comment by dxq613** [comment]
你可以看一下 data-set ，这个库对数据的交互，图表的上钻、下钻都能很好的支持。

**Comment by chenshuai2144** [comment]
@dxq613 那就相当于自己进行数据拼装和实现了.动画之类的就不是很好了

**Comment by dxq613** [comment]
通过 dataset 的状态量，动画之类的都是自动的。
