### ISSUE TITLE
legend设置custom为true后设置自定义item后showTitle无效，怎么才能显示图例的标题，并且可以自定义标题的文本

### ISSUE THREAD

**Issue by 13615817501** [antvis/G2#2140]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
legend设置custom为true后设置自定义item后showTitle无效，怎么才能显示图例的标题，并且可以自定义标题的文本

### What does the proposed API look like?
legend设置custom为true后设置自定义item后showTitle无效，怎么才能显示图例的标题，并且可以自定义标题的文本

**Comment by simaQ** [comment]
请提供版本信息

**Comment by embaobao** [comment]
4.0.2 我再使用个时候想自定义 图例区域 现在无法做到吗？取消了自定义Html的共能吗，有没有主动触发图例事件的方法，在图表外做到呐？

**Comment by simaQ** [comment]
已在 https://github.com/antvis/G2/issues/2205 回复。
