### ISSUE TITLE
浏览器端使用发现出现明显虚边

### ISSUE THREAD

**Issue by VKingi** [antvis/G2#2142]
测试实例：
- [官方实例地址](https://g2.antv.vision/zh/examples/gallery/pie#pie3)
具体问题参考如下：
![image](https://user-images.githubusercontent.com/16144561/76279791-e8fc8300-62ca-11ea-8551-77528736bb4f.png)
![image](https://user-images.githubusercontent.com/16144561/76279808-f6b20880-62ca-11ea-8688-ef35748e94f3.png)
![image](https://user-images.githubusercontent.com/16144561/76279825-02053400-62cb-11ea-915e-a189446094cc.png)

请问这个什么情况，感谢官方的积极处理 ^^

**Comment by simaQ** [comment]
这是因为绘图引擎支持了局部刷新，是局部刷新的问题，我们跟进修复的。

现在你可以临时在 chart 上将局部刷新关闭：

```ts
const chart = new Chart({
  container: 'container',
  autoFit: true,
  height: 500,
  localRefresh: false, // 关闭局部刷新机制
});
```

**Comment by VKingi** [comment]
> 这是因为绘图引擎支持了局部刷新，是局部刷新的问题，我们跟进修复的。
> 
> 现在你可以临时在 chart 上将局部刷新关闭：
> 
> ```ts
> const chart = new Chart({
>   container: 'container',
>   autoFit: true,
>   height: 500,
>   localRefresh: false, // 关闭局部刷新机制
> });
> ```

感谢，可以解决当前遇到的问题
