### ISSUE TITLE
关于配置项的几项疑问

### ISSUE THREAD

**Issue by fingerpan** [antvis/G2#2145]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

图例：
1.  是否可以开放图例图形半径 （marker.radius）配置，在大屏幕显示不友好。好像在3.X还可以通过Global.legendMarkerRadius配置，但是4.x是完全关闭了么？
2. 目前图例 MarkerSymbols 图形只能是point shape下几种选项，有点限制，比如要显示`曲线`图形图例只能配置marker = null 或者自定义marker Function来实现。但是其实G2内部是已经实现了，是否可以全部开放。

坐标轴：
1. 坐标轴的grid是自动隐藏收尾线是在4.0删除了吗？会形成坐标轴线 出现一条轴线，和一条网格线，有点逼死强迫症。

**Comment by simaQ** [comment]
1. 关于图例

都是可以配置的，在 G2 的类型定义中都已经定义了（API 文档给漏了， 我补充下）：

https://github.com/antvis/G2/blob/master/src/interface.ts#L744

```ts
chart.legend({
  marker: {
    symbol: (x: number, y: number, r: number) => PathCommand
    style: {
      r: number
    }
  }
});
```

2. 坐标轴

移除了，但是 4.0 组件渲染层级调整过后，axis-grid 是渲染在 axis-line 下面的，应该是看不到 grid 的吧
