### ISSUE TITLE
G2 4.0 桑基图 label 的 autoRotate 失效

### ISSUE THREAD

**Issue by ShaofeiZi** [antvis/G2#2149]
riddle : https://riddle.alibaba-inc.com/riddles/76d2c925

### 建议：
* 希望可以自动调整位置或者有可以配置的地方
* style里直接配置fontSize 不能根据情况变动。
* 比如左边和中间区块 文字在右，右边区块 文字在左。这种

**Comment by simaQ** [comment]
1. label() 接口的 `autoRotate` 属性目前只对 polar 极坐标系下的图形生效，但是可以手动指定 rotate 属性，详见下面代码示例。
2. style 属性是可以按需变动的，你可以使用 label() 接口的回调用法：

```ts

```

nodeView
  .polygon()
  .position('x*y')
  .color('name')
  .label('name', name => {
    // 使用回调，根据 name 的不同配置不同的属性
    if (name.length > 3) {
      return {
        style: {
          fill: '#545454',
          textAlign: 'center',
          fontSize: 20,
        },
        offset: 0,
        rotate: Math.PI * 0.5, // 设置文本的旋转弧度
        content: obj => `${obj.name}  `,
      };
    }
    return {
      style: {
        fill: '#545454',
        fontSize: 40,
      },
      offset: 0,
      content: obj => `${obj.name}  `,
    };
  })
  .tooltip(false)
  .style({
    stroke: '#ccc',
  });

3. 另外，也可以通过自定义 label 布局函数来满足你的需求：https://g2.antv.vision/zh/docs/manual/developer/registerlabel/#%E8%87%AA%E5%AE%9A%E4%B9%89-label-%E5%B8%83%E5%B1%80%E5%87%BD%E6%95%B0
