### ISSUE TITLE
是否可以在一个图表上显示2种类型

### ISSUE THREAD

**Issue by npm-ued** [antvis/g2#215]
* **G2 Version**: 3.0.0
* **Platform**: mac chrome
* **Mini Showcase(like screenshots)**: 
* **CodePen Link**: 

是否可以在一个图表上显示2种类型，比如有柱状体和曲线图，两个y轴，左右各一个

**Comment by xian107** [comment]
同问

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/tutorial/fqas.html#_如何绘制多-y-轴图表
