### ISSUE TITLE
图表 vue 第一次显示，路由跳转再返回后图表空白，刷新后显示。

### ISSUE THREAD

**Issue by bmy5585** [antvis/G2#2153]
图表 vue 第一次显示，路由跳转再返回后图表空白，刷新后显示。

请问是我路由问题，还是图表使用不当造成？

**Comment by simaQ** [comment]
看看是不是数据为空

**Comment by bmy5585** [comment]
> 看看是不是数据为空

现在看和数据没有关系，我现在还是模拟json做的。

**Comment by hustcc** [comment]
@bmy5585 看看组件在挂载和更新的时候，是否调用 render 吧？
