### ISSUE TITLE
vue开发下chart.tooltip自定义htmlContent渲染无效

### ISSUE THREAD

**Issue by HeaventTso** [antvis/G2#2154]
使用vue调动g2图表实例时，chart.tooltip自定义htmlContent返回的html字符串无法被正确渲染，实际上定义的htmlContent方法是有被执行的。

* **G2 Version**: "@antv/g2": "^3.5.1"
* **Platform**: win10x64, node8.12.0, vue2.6.10
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
参考官网tooltip自定义htmlContent案例
https://antv-2018.alipay.com/zh-cn/g2/3.x/demo/component/tooltip-html-content.html#

**Comment by hustcc** [comment]
> 使用vue调动g2图表实例时，chart.tooltip自定义htmlContent返回的html字符串无法被正确渲染，实际上定义的htmlContent方法是有被执行的。
> 
> * **G2 Version**: "@antv/g2": "^3.5.1"
> * **Platform**: win10x64, node8.12.0, vue2.6.10
> * **Mini Showcase(like screenshots)**:
> * **CodePen Link**:
>   参考官网tooltip自定义htmlContent案例
>   https://antv-2018.alipay.com/zh-cn/g2/3.x/demo/component/tooltip-html-content.html#

是否可以尝试使用 G2 4.0 看看？

**Comment by zqlu** [comment]
4.x 的 htmlContent 还没有支持，准备在 https://github.com/antvis/component/pull/160 支持
