### ISSUE TITLE
g2 4.0 registerInteraction后 interaction 报错

### ISSUE THREAD

**Issue by ShaofeiZi** [antvis/G2#2155]
riddle https://riddle.alibaba-inc.com/riddles/f2700af8
copy 对象 https://g2.antv.vision/zh/examples/interaction/element#element-link

**Comment by simaQ** [comment]
![image](https://user-images.githubusercontent.com/6628666/76426133-98c61380-63e5-11ea-8490-23f628983b55.png)

单词拼写错误：  element-single-selected  ~~element-single-seleted~~
