### ISSUE TITLE
Canvas 高度 500px 情况下，父容器是 505px

### ISSUE THREAD

**Issue by hustcc** [antvis/G2#2159]
理论上，所有的 G2 版本都有这个问题， 带来的问题：

每次 resize 触发的时候，因为 canvas 大小有父容器大小决定，所以 resize 都会导致图形比之前的高度大 5px。

### 解决办法：

对 canvas 设置 css 样式。

1. 设置 display: inline;
2. 设置 vertical-align: center (只要不是 baseline 即可)

可以在 G 层解决掉，也可以在 G2 层创建 G.Canvas 之后，再设置样式。

![image](https://user-images.githubusercontent.com/7856674/76493567-e25a4100-646d-11ea-8c18-1bfd91f0c79a.png)

**Comment by hustcc** [comment]
这个应该是一个老问题了。di 中做到自动做了容器大小变化的时候触发 图表 resize，然后在 G2 中图表 resize 又会导致容器大小变化，然后就死循环了。

**Comment by simaQ** [comment]
是否可以在 G 上解决 @dengfuping

**Comment by hustcc** [comment]
暂时业务中设置样式吧~

**Comment by yangwenhaowenhe** [comment]
forcefit设置了还是会死循环，
