### ISSUE TITLE
G2[3.5.13版本]编译后页面打开出现Uncaught TypeError: Cannot assign to read only property 'constructor' of object '#<e>'     

### ISSUE THREAD

**Issue by JimmieMax** [antvis/G2#2166]
![image](https://user-images.githubusercontent.com/19659812/76588058-fad76380-6520-11ea-919e-053b38dd1778.png)
查看代码是这里报的错，这是编译压缩后的js文件，shi是antv/g2中的模块
![image](https://user-images.githubusercontent.com/19659812/76588116-24908a80-6521-11ea-9f49-2e98e90f6fdc.png)

**Comment by simaQ** [comment]
这个问题，以前好像遇到过: https://github.com/antvis/G2/pull/1641

**Comment by JimmieMax** [comment]
没有看到解决办法呀

**Comment by JimmieMax** [comment]
我用的是vue

**Comment by JimmieMax** [comment]
解决了，原来是我们项目里build的时候加了 --modern
