### ISSUE TITLE
[4.X问题]请问堆叠柱状图为什么保存了HTML代码后显示一片空白?

### ISSUE THREAD

**Issue by djhuahao** [antvis/G2#2167]
https://g2.antv.vision/zh/examples/column/stack#rounded-stacked

1、如上链接，我在页面中点击"保存HTML代码“
2、然后修改  const chart = new Chart({   为    const chart = new G2.Chart({
3、之后保存为demo.html，但是打开是一片空白，请问是哪里有问题嘛？我试了其他的类型都是好的。谢谢

**Comment by simaQ** [comment]
你好，参考下 https://github.com/antvis/G2/issues/2130#issuecomment-596381794，同时 html 文件中也有提示：

![image](https://user-images.githubusercontent.com/6628666/76700175-f57c4380-66ef-11ea-8b69-b46987ff4db8.png)

**Comment by djhuahao** [comment]
原来是registerShape的问题，非常感谢。SORRY问了个很低级的问题。 @simaQ
