### ISSUE TITLE
如何实现添加多个 Field 的 Legend 

### ISSUE THREAD

**Issue by Kaijun** [antvis/g2#217]
比如我有如下一组数据，默认情况下可以直接添加 `key` 为 作为 Legend

```
[{key: 'x', value: 'y', feild1: 'otherFields', feild2: 'otherFields'} ... ]
```

但是我想再添加一个 以 `feild1` 以及 `feild2` 分类的 Legend, 

```
chart.legend('feild1', {...})
chart.legend('feild2', {...})
```

发现 feild2 的 legend 并不会被添加，不知道是否符合预期？

**Comment by zouwenhuagit** [comment]
你是哪位？




发自网易邮箱大师
在2017年11月26日 23:08，Kaijun Chen 写道：

Reopened #217.

**Comment by leungwensen** [comment]
@Kaijun 

`chart.legend` 是个比较特殊的 API，它只用于配置图例，而不用于“生成”图例。某个 `field` 是否能生成图例，这是图形语法已经确定了的（因为图例一般用于标示 / 过滤图形，如果某个字段没有映射到图形属性，那它没法生成图例）。举个例子：

```js
chart.interval().position('x*y').color('a').shape('b');
```

这个例子里，映射到 color 和 shape 的 a 和 b 属性才能生成图例，你配置 chart.legend('c', config) 是没法生成新的图例的

**Comment by Kaijun** [comment]
@leungwensen 了解，感谢解答
