### ISSUE TITLE
[Help]请教堆叠柱状图的求和和排序的问题，谢谢

### ISSUE THREAD

**Issue by djhuahao** [antvis/G2#2171]
小白用户想请教个两个问题，

1、关于如图中的label我可以额外在最上面显示两个值的总和嘛？也就是12和13
2、另外，我如何做到整体的排序按照两个值的总和嘛？好像是用Frame，但我没有看懂。
以上问题请指教，谢谢。

![demo](https://user-images.githubusercontent.com/9102683/76731367-3cbe0f00-6798-11ea-87c3-1f0e5be96f6e.png)

<!DOCTYPE html>
        <html>
          <head>
            <meta charset="UTF-8">
            <title>圆角堆叠柱状图</title>
          </head>
          <body>
		  <table id="tbl" border=1 width="800px" height="50px" frame=void >

            <div id="container" />
            <script src="https://gw.alipayobjects.com/os/lib/antv/g2/4.0.1/dist/g2.min.js"></script>
            <script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.11.1/dist/data-set.js"></script>
            <script>
            
                function getFillAttrs(cfg) {
      return {
        ...cfg.defaultStyle,
        ...cfg.style,
        fill: cfg.color,
        fillOpacity: cfg.opacity,
      };
    }
    function getRectPath(points) {
      const path = [];
      for (let i = 0; i < points.length; i++) {
        const point = points[i];
        if (point) {
          const action = i === 0 ? 'M' : 'L';
          path.push([action, point.x, point.y]);
        }
      }
      const first = points[0];
      path.push(['L', first.x, first.y]);
      path.push(['z']);
      return path;
    }

    // 顶边带圆角
    G2.registerShape('interval', 'top', {
      draw(cfg, container) {
        const attrs = getFillAttrs(cfg);
        let path = getRectPath(cfg.points);
        path = this.parsePath(path); // 将 0 - 1 的值转换为画布坐标
        const radius = (path[2][1] - path[1][1]) / 2;
        const temp = [];
        temp.push(['M', path[0][1], path[0][2]]);
        temp.push(['L', path[1][1], path[1][2] + radius]);
        temp.push(['A', radius, radius, 90, 0, 1, path[1][1] + radius, path[1][2]]);
        temp.push(['L', path[2][1] - radius, path[2][2]]);
        temp.push(['A', radius, radius, 90, 0, 1, path[2][1], path[2][2] + radius]);
        temp.push(['L', path[3][1], path[3][2]]);
        temp.push(['Z']);

        const group = container.addGroup();
        group.addShape('path', {
          attrs: {
            ...attrs,
            path: temp,
          },
        });

        return group;
      },
    });

    // 底边带圆角
    G2.registerShape('interval', 'bottom', {
      draw(cfg, container) {
        const attrs = getFillAttrs(cfg);
        let path = getRectPath(cfg.points);
        path = this.parsePath(path);
        const radius = (path[2][1] - path[1][1]) / 2;
        const temp = [];
        temp.push(['M', path[0][1] + radius, path[0][2]]);
        temp.push(['A', radius, radius, 90, 0, 1, path[0][1], path[0][2] - radius]);
        temp.push(['L', path[1][1], path[1][2]]);
        temp.push(['L', path[2][1], path[2][2]]);
        temp.push(['L', path[3][1], path[3][2] - radius]);
        temp.push(['A', radius, radius, 90, 0, 1, path[3][1] - radius, path[3][2]]);
        temp.push(['Z']);

        const group = container.addGroup();
        group.addShape('path', {
          attrs: {
            ...attrs,
            path: temp,
          },
        });

        return group;
      },
    });

    const data = [{'name': 'user1', 'value': 11, 'cat': 'd1'},
                          {'name': 'user1', 'value': 1, 'cat': 'd2'}, 
                          {'name': 'user2', 'value': 10, 'cat': 'd1'}, 
                          {'name': 'user2', 'value': 3, 'cat': 'd2'}];
	
	  
     const chart = new G2.Chart({
      container: 'container',
      autoFit: true,
      height: 500,
      padding: [50,30,100,50]

    });

    chart.data(data);
    chart.scale({
      sales: {
        tickInterval: 600,
        nice: true,
      },
    });

    const axisCfg = {
      title: null,
      label: {
        style: {
          fontFamily: 'Monospace',
          fontWeight: 700,
          fontSize: 14,
          fill: '#545454',
        },
      },
      grid: {
        line: {
          style: {
            lineDash: null,
            stroke: '#545454',
          },
        },
      },
      line: {
        style: {
          lineDash: null,
          stroke: '#545454',
        },
      },
    };

	
	
	chart.axis('name', {
    label: {
      textStyle: {
        fill: '#aaaaaa'
      }
    },
    tickLine: {
      alignWithLabel: false,
      length: 0
    }
  });
  

    chart.tooltip({
      showMarkers: false
    });

	  chart.axis('value', {
    label: {
      textStyle: {
        fill: '#aaaaaa'
      },
      formatter: function formatter(text) {
        return text.replace(/(\d)(?=(?:\d{3})+$)/g, '$1,');
      }
    },
    title: {
      offset: 70
    }
  });
  
  
    chart
      .interval()
      .position('name*value')
      .color('cat')
      .size(35)
      .label('value')
	  
	  

	
      .shape('cat', (val) => {
        if (val === 'd2') {
          // 顶部圆角
          return 'bottom';
        } else if (val === 'd1') {
          // 底部圆角
          return 'top';
        }
      })
      .style({
        stroke: '#545454',
        lineWidth: 2,
      })
      .adjust({type: 'stack', reverseOrder: true});

    chart.interaction('element-highlight-by-color');

    chart.render();
            </script>
		</table>
          </body>
        </html>

**Comment by djhuahao** [comment]
@dxq613 @simaQ 求指教，谢谢。

**Comment by djhuahao** [comment]
Hi @simaQ ，可否帮忙看一下这个问题，谢谢。

**Comment by simaQ** [comment]
> 1、关于如图中的label我可以额外在最上面显示两个值的总和嘛？也就是12和13
> 2、另外，我如何做到整体的排序按照两个值的总和嘛？好像是用Frame，但我没有看懂。

这个需要自己在外部处理下数据：按照你的需求，对数据进行分组，计算出总和，然后按照总和对数据进行排序后，再传入 G2 进行绘制。至于需要在 label 的基础上显示总和，你可以额外使用 chart.annotation().text() 进行绘制，直接传入 x 轴对应的分类值和 y 轴对应的总和值就可以了。

**Comment by djhuahao** [comment]
@simaQ 明白了，非常感谢您~
