### ISSUE TITLE
图例问题，见图片

### ISSUE THREAD

**Issue by TwoPens** [antvis/G2#2172]
https://m.qpic.cn/psc?/V14XRsE03yc9WI/8YUQ4vKPKp.vxIKbDZcdtqlejHy2N2J.8SGOIV.J845wjeGIG5XELWkQFR8zS2Xjx76W9kZqzv9Qv6s1zcmHMA!!/mnull&bo=UAVpAQAAAAADBx8!&rf=photolist&t=5

这是图片。分类图例、连续图例都出现了。出现双图例 重叠了，怎么隐藏其中一个，或者区分开。
通过配置项实现的
options.legends = {
            layout: 'horizontal',
            position: 'top',
            title: {
              spacing: 50,
              text: 'title'
            }
          }

**Comment by TwoPens** [comment]
![微信截图_20200316125105](https://user-images.githubusercontent.com/62087166/76724405-d8924f80-6785-11ea-9e37-d06909b686a2.png)

**Comment by TwoPens** [comment]
![微信截图_20200316131709](https://user-images.githubusercontent.com/62087166/76725211-7555ec80-6788-11ea-877e-e0048ccf7891.png)
图例的标题也出现了两个，重叠了

**Comment by djhuahao** [comment]
padding:'auto' 可以么？

**Comment by TwoPens** [comment]
哪个位置加padding auto

**Comment by simaQ** [comment]
隐藏图例的方法 API 里面写明了：


`chart.legend('图例字段名', false);`

配置项同理：

```js
legends: {
  '图例字段名': false
}
```
