### ISSUE TITLE
4.0.2版本   legend  itemFormatter不生效，求解决啊着急！！！！！！

### ISSUE THREAD

**Issue by wangjingithub** [antvis/G2#2176]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by wangjingithub** [comment]
chart.legend({
				itemFormatter: function(val){
					return val+'%'
				}
			})

**Comment by simaQ** [comment]
4.0 属性变化了，可以具体翻翻 API：

```ts
chart.legend({
  itemName: {
    formatter: (va) => va + '%',
  }
});
```

**Comment by wangjingithub** [comment]
> 4.0 属性变化了，可以具体翻翻 API：
> 
> ```ts
> chart.legend({
>   itemName: {
>     formatter: (va) => va + '%',
>   }
> });
> ```

感谢，但api页面打不开啊
