### ISSUE TITLE
G2中如何能在饼图中绘制： 图形内部标记百分比，在外部标记其他数据？

### ISSUE THREAD

**Issue by hyisboy** [antvis/G2#2177]
* **G2 Version**: 4.01
* **Platform**: vue
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/42001846/76731082-8528fd00-6797-11ea-9138-a8ebf7d38c47.png)

**Comment by wangjingithub** [comment]
你这个legend可以格式化吗

**Comment by hyisboy** [comment]
> 你这个legend可以格式化吗
格式化legend啥意思？

**Comment by wangjingithub** [comment]
> > 你这个legend可以格式化吗
> > 格式化legend啥意思？

chart.legend({
				itemFormatter: function(val){
					return val+'%'
				},
			})
这样不起作用啊

**Comment by hyisboy** [comment]
请·

> > > 你这个legend可以格式化吗
> > > 格式化legend啥意思？
> 
> chart.legend({
> itemFormatter: function(val){
> return val+'%'
> },
> })
> 这样不起作用啊
我想弄个拉线， 不知道怎么拉， 目前是这样的
![image](https://user-images.githubusercontent.com/42001846/76733313-84926580-679b-11ea-9f2f-7d717c441bfe.png)

我使用的是 chart.label 来实现的， 但是内部与外部 只是一个 offset的区别，也就是说设置了内部就无法设置外部了。
![image](https://user-images.githubusercontent.com/42001846/76733449-cd4a1e80-679b-11ea-9114-609d88089c18.png)

想实现这种效果： 
![image](https://user-images.githubusercontent.com/42001846/76733512-ec48b080-679b-11ea-92af-5bb5a2b80250.png)
内部外部都有文本的这种

**Comment by simaQ** [comment]
目前使用 label 无法做到内外部同时显示，你可以使用 chart.annotation().text() 来绘制内部文本，label() 来绘制外部文本。但是目前的 label 拉线不支持你给出图表中的折线形式。
