### ISSUE TITLE
【4.0】更新问题，vue项目父组件为tab切换dataList，子组件图表可以接收到数据，但是图例不能切换更新，我watch监听dataList报错!!!!!!!求解，着急！！！

### ISSUE THREAD

**Issue by wangjingithub** [antvis/G2#2179]
父组件<BarChart :btData="btData" :id="type"/>
子组件
<template>
	<div :id="id"></div>	      
</template>

<script>
import { Chart } from '@antv/g2';
export default{
	props: {
    btData:{
			type: Array
		},
		id: String,
  },
	data(){    
		return {
      chart:{}
		}
  },	
  watch: {
    btData: function (val, oldVal) {    
      console.log('watch',val)
      if(JSON.stringify(val)!==JSON.stringify(oldVal)){
        this.getDrawing(val);
      }			
		}
	},
	methods:{
		getDrawing(data){
			let _this = this;	
      _this.chart && _this.chart.destroy()
      console.log('getDrawing----')
			_this.chart = new Chart({
				container: _this.id,
				autoFit: true,
				height: 300,
			});
			_this.chart.data(data);
			_this.chart.scale('count', {
        nice: true,
      });
			_this.chart.tooltip({
        showMarkers: false
      });
			_this.chart.interaction('active-region');
      _this.chart.interval().position('item*count');
			_this.chart.render();
		}
	},
	mounted() {
		//console.log(this.id,'id')
    this.getDrawing(this.btData);
    // const e = document.createEvent('Event')
    // e.initEvent('resize', true, true)
    // window.dispatchEvent(e)
	},
	
}
</script>

这样tab切换时报错Vue warn]: Error in callback for watcher "btData": "TypeError: Cannot read property 'appendChild' of null" 
不能正常显示

-

**Comment by simaQ** [comment]
报这个错误："TypeError: Cannot read property 'appendChild' of null"

一般是 G2 找不到绘制图表的 DOM，你检查下是不是 new Chart 那里  container 的  dom id 没有传对。
