### ISSUE TITLE
开发调试脚本优化

### ISSUE THREAD

**Issue by simaQ** [antvis/g2#218]
```bash
$ npm run dev
```
同时升级 G F2 G6 等其他项目

**Comment by leungwensen** [comment]
@simaQ `npm run dev` 的时候，是希望启动 demos 进程还是测试进程，还是都要？

**Comment by simaQ** [comment]
能够让我们能够跑起示例并且能调试就可以了，不需要都要，按照 test-live 的那种模式就可以了

**Comment by leungwensen** [comment]
也就是，现在是 `npm run dev` + `npm run test-live`，你希望合成一个？

**Comment by simaQ** [comment]
恩
