### ISSUE TITLE
G2的时间条形图X轴显示的颗粒度如何调整

### ISSUE THREAD

**Issue by maomi20150102** [antvis/G2#2180]
现在X轴数值最小显示到天，能否支持显示到小时或者分钟
[https://g2.antv.vision/zh/examples/bar/basic#time-bar](url)

**Comment by maomi20150102** [comment]
![15844235618763](https://user-images.githubusercontent.com/15665502/76825728-a819e680-6855-11ea-9370-f617b7d1618e.png)

**Comment by maomi20150102** [comment]
![15844235618763](https://user-images.githubusercontent.com/15665502/76825809-d8618500-6855-11ea-85ce-f22069cb4708.png)
如图

**Comment by simaQ** [comment]
可以支持，在 `chart.scale()` 接口中设置下时间格式就行。

```ts
chart.scale('range', {
  mask: 'YYYY-MM-DD HH:mm:ss'
});
```
