### ISSUE TITLE
柱状图，怎么对数据进行 升序或者降序

### ISSUE THREAD

**Issue by TwoPens** [antvis/G2#2185]
我通过 transform处理， dv.rows数据以及排序了，结果  changeData(dv.rows)，没效果

**Comment by TwoPens** [comment]
横坐标是 日期格式的  year  。换成字符串类型的数据，又可以排序的。 想问下，日期格式的，怎么排序生效啊

**Comment by simaQ** [comment]
需要在绘制前。对数据进行排序预处理哦、
