### ISSUE TITLE
【4.0版本】鼠标移出区域后，tooltip 不消失 

### ISSUE THREAD

**Issue by FlyDreame** [antvis/G2#2187]
## 重现示例
直接用 g2 官网上的示例
https://g2.antv.vision/zh/examples/column/basic

## 重现步骤
鼠标移到柱状图上，显示 tooltip，然后鼠标移动到 tooltip 上，点击（click） tooltip，从 tooltip 上移出画布， tooltip 不消失
![bug](https://user-images.githubusercontent.com/9284212/76845927-a3b3f480-687a-11ea-9bf5-860627aa0b09.gif)

**Comment by simaQ** [comment]
已知问题，#2184 中已修复。

**Comment by FlyDreame** [comment]
好的，感谢
