### ISSUE TITLE
柱状图.color(function)，使用回调方法，怎么返回颜色数组。

### ISSUE THREAD

**Issue by TwoPens** [antvis/G2#2189]
柱状图.color(function)，使用回调方法，怎么返回颜色数组。
没有更新4.0之前，直接return空，就会使用 默认的颜色集合。
更新4.0之后，return空会报错。这里需要怎么返回数据

**Comment by TwoPens** [comment]
函数中，不满足规则的，我想使用默认的颜色集合。现在没有实现，我只能暂定一种颜色，总不能自己写个函数，随机分配颜色吧。

**Comment by simaQ** [comment]
可否提供可复现代码？我会帮忙排查

**Comment by TwoPens** [comment]
import { Chart } from '@antv/g2';

const data = [
        {
          Year: '2016',
          Deaths: 34676,
          Injuries: 39851,
          c: 'a34676',
          x: 'a2016',
          s: 'Number of incidents',
          y: 13488
        },
        {
          Year: '2015',
          Deaths: 38464,
          Injuries: 43960,
          c: 'a38464',
          x: 'a2015',
          s: 'Number of incidents',
          y: 14852
        },
        {
          Year: '2014',
          Deaths: 43566,
          Injuries: 41061,
          c: 'a43566',
          x: 'a2014',
          s: 'Number of incidents',
          y: 16860
        },
        {
          Year: '2013',
          Deaths: 22234,
          Injuries: 37666,
          c: 'a22234',
          x: 'a2013',
          s: 'Number of incidents',
          y: 11996
        },
        {
          Year: '2014',
          Deaths: 22134,
          Injuries: 37666,
          c: 'a222341',
          x: 'c2013',
          s: 'Number of incidents',
          y: 11996
        },
        {
          Year: '2013',
          Deaths: 22234,
          Injuries: 37666,
          c: 'a222344',
          x: 'b2013',
          s: 'Number of incidents',
          y: 11996
        }
      ];

const chart = new Chart({
  container: 'container',
  autoFit: true,
  height: 500,
});

chart.coordinate('theta', {
  radius: 0.75,
});

chart.data(data);

chart.scale('percent', {
  formatter: (val) => {
    val = val * 100 + '%';
    return val;
  },
});

chart.scale('y', {
        formatter: val => {
          val = val * 100 + '%'
          return val
        }
      });
chart.tooltip({
        showTitle: false,
        showMarkers: false
      });

chart
        .interval()
        .adjust('stack')
        .position('y')
        // .color('x')
        .color('x*y', (x, y) => {
          if (x == 'b2013') {
            return 'red'
          } else {
            return 'green'
          }
        })
        .label('y', {
          offset: -40,
          style: {
            textAlign: 'center',
            fontSize: 16,
            shadowBlur: 2,
            shadowColor: 'rgba(0, 0, 0, .45)',
            fill: '#fff'
          }
        })
        .tooltip('x*y', (x, y) => {
          y = y * 100 + '%'
          return {
            name: x,
            value: y
          }
        });

chart.interaction('element-active');

chart.render();

**Comment by TwoPens** [comment]
> 可否提供可复现代码？我会帮忙排查

我的代码可以在官网示例里面跑。https://g2.antv.vision/zh/examples/pie/basic
![微信截图_20200320171005](https://user-images.githubusercontent.com/62087166/77149931-ab1f0c00-6acd-11ea-9c83-c79c1d6d502a.png)
![微信截图_20200320171005](https://user-images.githubusercontent.com/62087166/77149947-b2461a00-6acd-11ea-82cb-bb76b8247c63.png)

**Comment by TwoPens** [comment]
放不了图片，看看这个截图问题
https://m.qpic.cn/psc?/V14XRsE03yc9WI/8YUQ4vKPKp.vxIKbDZcdtlKfyuNkOfGt*KOpeTXJ9aYIJ*eK0W1RCFkCriWjh38BkBvH3DNNefrefUNfprquqA!!/b&bo=1AShAgAAAAADB1E!&rf=viewer_4

**Comment by simaQ** [comment]
定义了回调函数的话，所有颜色都要自己设置。如果想要使用官方颜色。可以这样：

chart.interval().color('x*y', (x, y) => {
  if (x ==='xxx') return 'red';

  const defaultColors = chart.getTheme().colors10;
  return defaultColors[x];
})
