### ISSUE TITLE
支持下 ts

### ISSUE THREAD

**Issue by arcthur** [antvis/g2#219]
请求增加下 g2 的全局 types 定义

**Comment by leungwensen** [comment]
@arcthur  你是不是写了一份？求 PR 啊

**Comment by arcthur** [comment]
我写的那份是针对配置的，不是针对 G2 API 的，内部实现看过才好写，推荐参考~

**Comment by dxq613** [comment]
@RaoHai  把你写的提个 MR

**Comment by chenshuai2144** [comment]
.d.ts的文件实现是否是只要实现api的调用,参数的匹配就好了.还是需要说模拟内部的结构来写.
g2也是使用类继承的方式写的.是否需要类继承关系也理清楚.

**Comment by leungwensen** [comment]
https://github.com/antvis/g2/pull/271
