### ISSUE TITLE
Chart设置autoFit不能自动充满容器

### ISSUE THREAD

**Issue by GiorgioPeng** [antvis/G2#2195]
<img width="552" alt="截屏2020-03-19下午1 57 22" src="https://user-images.githubusercontent.com/34415646/77036223-910bfd80-69e9-11ea-8448-f722ac0460b2.png">
<img width="643" alt="截屏2020-03-19下午1 58 07" src="https://user-images.githubusercontent.com/34415646/77036259-aaad4500-69e9-11ea-8732-7c7987522b1d.png">
<img width="1338" alt="截屏2020-03-19下午1 58 46" src="https://user-images.githubusercontent.com/34415646/77036293-c1ec3280-69e9-11ea-8849-a7bd873cf264.png">
如图，如题

[复现 demo](https://codesandbox.io/s/great-mclaren-y9p21)

**Comment by LancelotLewis** [comment]
同样有这个问题，不过只在 4.02 下有，4.01版本正常

**Comment by hustcc** [comment]
@LancelotLewis 已经发现问题，是内部创建 div，没有自动设置为容器的大小。
