### ISSUE TITLE
3.x 版本中的chart.forceFit() 在4.x中没有找到对应方法

### ISSUE THREAD

**Issue by kooriookami** [antvis/G2#2197]
* **G2 Version**:
4.0.2
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by hustcc** [comment]
可以手动自己获取容器的宽高，然后:

```ts
chart.changeSize(w, h);
```

后者直接在创建 chart 的时候开启：

```ts
new Chart({
  // ...
  autoFit: true,
});
```

**Comment by kooriookami** [comment]
autoFit: true属性只能检测到窗口大小的改变，容器尺寸改变了就不行了。

**Comment by hustcc** [comment]
@kooriookami 是的，目前是使用的 window resize 事件。

业务中使用，可以尝试使用 [size-sensor](https://github.com/hustcc/size-sensor) 去处理容器变化。大概逻辑为：

```ts
const div;

const chart = new Chart({
  container: div,
  // ...
});

// 绘制图形

bind(div, () => {
  // 获得容器 div 的宽高
  chart.changeSize(w, h);
})
```

**Comment by kooriookami** [comment]
好的呢，说到底还是要手动获取容器的大小调用changeSize()方法，要是能有一个autoFit()方法就方便了

**Comment by hustcc** [comment]
> 好的呢，说到底还是要手动获取容器的大小调用changeSize()方法，要是能有一个autoFit()方法就方便了

@simaQ 是否在 chart 上增加这个 api？

**Comment by simaQ** [comment]
> > 好的呢，说到底还是要手动获取容器的大小调用changeSize()方法，要是能有一个autoFit()方法就方便了
> 
> @simaQ 是否在 chart 上增加这个 api？

可
