### ISSUE TITLE
我设置交互行为 interactions[{type: 'element-highlight'}]，出现柱状图描边

### ISSUE THREAD

**Issue by TwoPens** [antvis/G2#2201]
options.interactions: [{type: 'element-highlight'}]
高亮时，柱状图描边，怎么去掉
如下截图，红色箭头
![微信截图_20200319193422](https://user-images.githubusercontent.com/62087166/77063437-a9dfd780-6a18-11ea-9e4f-5eea606da54f.png)

**Comment by TwoPens** [comment]
![微信截图_20200319193422](https://user-images.githubusercontent.com/62087166/77063507-c67c0f80-6a18-11ea-8296-f4b704548f72.png)

**Comment by simaQ** [comment]
使用 https://g2.antv.vision/zh/docs/api/classes/geometry/#state 方法自定义下 active 的样式：

```ts
chart.interval().state({
  active: {
    style: {

   }
  }
})
```
