### ISSUE TITLE
4.0.2 我在使用G2时想自定义图例区域 legend 现在无法做到吗？取消了自定义Html的共能吗，有没有主动触发图例事件的方法，在图表外做到呐？

### ISSUE THREAD

**Issue by embaobao** [antvis/G2#2205]
4.0.2 我在使用G2时想自定义图例区域 legend 现在无法做到吗？取消了自定义Html的功能吗，有没有主动触发图例事件的方法，在图表外去做到呐？

**Comment by hustcc** [comment]
是指通过 chart API 设置图例的选中和取消选中吗？

**Comment by simaQ** [comment]
自定义 html 图例的功能在 4.0 取消了。如果想要主动触发图例事件的话，可以监听图例上的事件：`chart.on('legend:click')`

**Comment by yumanfeng** [comment]
> 是指通过 chart API 设置图例的选中和取消选中吗？

![image](https://user-images.githubusercontent.com/13445900/88126155-7e0d7200-cc03-11ea-9b46-23e426782c13.png)
设置 g2 的 legend 隐藏后，
在外部用 html 自定义 legend，如何模拟点击 legend 点击后，对应分类的图表的隐藏与显示？
![image](https://user-images.githubusercontent.com/13445900/88126075-56b6a500-cc03-11ea-9b07-8fa86be006c9.png)

**Comment by hustcc** [comment]
onClick 的时候，去支持 chart.filter(data => xxxx(data))

**Comment by yumanfeng** [comment]
> onClick 的时候，去执行 chart.filter(data => xxxx(data))

chart.filter 第二个参数，传入的回调不会执行

版本："@antv/g2": "^4.0.12",

代码：
https://codesandbox.io/s/romantic-wozniak-eclky?file=/src/RingDiagram.tsx

![image](https://user-images.githubusercontent.com/13445900/88148863-d22f4b00-cc31-11ea-8419-0161fbb25f5a.png)

**Comment by woliwa1** [comment]
请问一下，版本4.0.15，想自定义legend html 文本显示怎么操作？有没有新的文档可以提供参考？ @simaQ

**Comment by monijiang** [comment]
遇到了类似的场景，需在chart.filter方法后，增加语句chart.render(true)。触发render,才会进行filter方法的调用。
chart.filter作用，只是增加筛选器，并不执行调用
