### ISSUE TITLE
【bug】其它图形元素和分组柱状图/堆叠柱状图共存时，Legend无法显示

### ISSUE THREAD

**Issue by chenyiqiao** [antvis/G2#2213]
* **G2 Version**:  3.5.8
* **Platform**: windows7
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/11814589/77386201-401f4f00-6dc5-11ea-8ea3-1cfc6243f093.png)

* **CodePen Link**: https://codepen.io/chenyiqiao/pen/wvaEjmg

我尝试自定义legend,但是发现分组柱状图的两根柱子实际同属于一个interval的图形元素，因此没法分别显示/隐藏。

**Comment by chenyiqiao** [comment]
@simaQ @hustcc 可以先给一个workaround吗，现在我考虑自定义legend：
```js
      chart.legend({
        custom: true,
        items: [
          { value: 'a', marker: {symbol: 'square', radius: 5} },
          { value: 'b', marker: {symbol: 'hyphen', radius: 5, lineWidth: 3} ,
          { value: 'c', marker: {symbol: 'hyphen', radius: 5, lineWidth: 3}
        ],
        onClick: ev => {
          const item = ev.item
          const value = item.value
          const checked = ev.checked
          const geoms = this.chart.getAllGeoms()
          for (let i = 0; i < geoms.length; i++) {
            const geom = geoms[i]
            if (geom.getYScale().value=== value) {
              if (checked) {
                geom.show()
              } else {
                geom.hide()
              }
            }
          }
        }
      })
```

但是分组柱状图的geom实际上只有一个，也就是我只能同时显示或者隐藏两根柱子，我需要精确控制分组柱状图里的两根柱子。

**Comment by simaQ** [comment]
> @simaQ @hustcc 可以先给一个workaround吗，现在我考虑自定义legend：
> 
> ```js
>       chart.legend({
>         custom: true,
>         items: [
>           { value: 'a', marker: {symbol: 'square', radius: 5} },
>           { value: 'b', marker: {symbol: 'hyphen', radius: 5, lineWidth: 3} ,
>           { value: 'c', marker: {symbol: 'hyphen', radius: 5, lineWidth: 3}
>         ],
>         onClick: ev => {
>           const item = ev.item
>           const value = item.value
>           const checked = ev.checked
>           const geoms = chart.getAllGeoms()
>           for (let i = 0; i < geoms.length; i++) {
>             const geom = geoms[i]
>             if (geom.getYScale().field === value) {
>               if (checked) {
>                 geom.show()
>               } else {
>                 geom.hide()
>               }
>             }
>           }
>         }
>       })
> ```
> 
> 但是分组柱状图的geom实际上只有一个，也就是我只能同时显示或者隐藏两根柱子，我需要精确控制分组柱状图里的两根柱子。geom上面应该是有方法用来hide/show分组柱状图吧？
> 
> https://codepen.io/chenyiqiao/pen/VwLERwp

你可以拿到所有的 shape, geometry.getShapes()，然后通过 shape.get('origin') 获取的 shape 上的原始数据，这样就可以区分两根柱子了，shape 上也有 show() 和 hide() 方法

**Comment by chenyiqiao** [comment]
> > @simaQ @hustcc 可以先给一个workaround吗，现在我考虑自定义legend：
> > ```js
> >       chart.legend({
> >         custom: true,
> >         items: [
> >           { value: 'a', marker: {symbol: 'square', radius: 5} },
> >           { value: 'b', marker: {symbol: 'hyphen', radius: 5, lineWidth: 3} ,
> >           { value: 'c', marker: {symbol: 'hyphen', radius: 5, lineWidth: 3}
> >         ],
> >         onClick: ev => {
> >           const item = ev.item
> >           const value = item.value
> >           const checked = ev.checked
> >           const geoms = chart.getAllGeoms()
> >           for (let i = 0; i < geoms.length; i++) {
> >             const geom = geoms[i]
> >             if (geom.getYScale().field === value) {
> >               if (checked) {
> >                 geom.show()
> >               } else {
> >                 geom.hide()
> >               }
> >             }
> >           }
> >         }
> >       })
> > ```
> > 
> > 
> > 但是分组柱状图的geom实际上只有一个，也就是我只能同时显示或者隐藏两根柱子，我需要精确控制分组柱状图里的两根柱子。geom上面应该是有方法用来hide/show分组柱状图吧？
> > https://codepen.io/chenyiqiao/pen/VwLERwp
> 
> 你可以拿到所有的 shape, geometry.getShapes()，然后通过 shape.get('origin') 获取的 shape 上的原始数据，这样就可以区分两根柱子了，shape 上也有 show() 和 hide() 方法

别关掉了吧。。还是 应该默认是要展示所有的legend的

**Comment by chenyiqiao** [comment]
别关掉了吧。。还是 应该默认是要展示所有的legend的
