### ISSUE TITLE
Pie 的data部分的min-width如何调整 

### ISSUE THREAD

**Issue by afeiluo** [antvis/G2#2219]
![77281352-c6725d00-6d01-11ea-8981-13b6deb7ce0b](https://user-images.githubusercontent.com/6848479/77414219-9dce8e00-6dfb-11ea-81e5-f8b3b8c237c7.png)

后面的数字太长导致和 data 的百分比重合了

**Comment by simaQ** [comment]
chart.legend() 中的 itemWidth 属性或者maxWidth 属性
