### ISSUE TITLE
画线或者点的时候，能否做到空值（比如null, undefined）不渲染？

### ISSUE THREAD

**Issue by Kaijun** [antvis/g2#222]
在某些数据中，可能有空值，希望不会被渲染在图表上

以及画线的时候，空值的话期望**不会被线连接**。像 HighCharts 会有一个 `connectNulls (boolean)` 的选项。不知道 G2 是否支持？

目前在文档上没有找到相关描述

**Comment by simaQ** [comment]
目前 G2 没有提供这个配置项，我们默认会将其断开，不过可以考虑加入这个配置项

**Comment by Kaijun** [comment]
@simaQ 那在什么情况下 会断开呢？值是 null/undefined 的情况吗？

**Comment by Kaijun** [comment]
@simaQ 可以自定义某些值不渲染吗？比如 0值，""值，等等

**Comment by 123geshuai** [comment]
在改页面中测试：
http://antv.alipay.com/zh-cn/g2/3.x/demo/line/basic.html

null/undefined断开，0是一个数字不断开，“”作为0处理，不断开（没读源码，不知原因）

**Comment by 123geshuai** [comment]
在下面的页面中测试：
http://antv.alipay.com/zh-cn/g2/3.x/demo/line/basic.html

null/undefined断开，0是一个数字不断开，“”作为0处理，不断开（没读源码，不知原因）

**Comment by simaQ** [comment]
1. `null` `undefined` 会断开
2. 如果需要某些值不渲染，针对线图，你可以在数据处理阶段将数据过滤掉，我们的 dataset 提供的 
filter 这个 transform 就很方便

**Comment by Kaijun** [comment]
@simaQ 感谢

**Comment by 100cm** [comment]
不好意思 再问一下。。我现在对于横轴有些空值 想直接把前一个值和后一个值连起来。这个是否可以做到呢？

**Comment by simaQ** [comment]
> 不好意思 再问一下。。我现在对于横轴有些空值 想直接把前一个值和后一个值连起来。这个是否可以做到呢？

可以，见图

![image](https://user-images.githubusercontent.com/6628666/76928980-f7c3e500-691d-11ea-87ce-786f0e65a9cd.png)

**Comment by 100cm** [comment]
谢谢，请问viserjs 这种对应的实现表现是一致的吧？

**Comment by simaQ** [comment]
> 谢谢，请问viserjs 这种对应的实现表现是一致的吧？

看它基于的版本，这个在 G2 3.x 里面也有这个属性，只不过要这么使用：G2.Global.connectNulls = true;

**Comment by LHC8888** [comment]
> > 谢谢，请问viserjs 这种对应的实现表现是一致的吧？
> 
> 看它基于的版本，这个在 G2 3.x 里面也有这个属性，只不过要这么使用：G2.Global.connectNulls = true;

请问从3.几开始支持设置G2.Global.connectNulls呀？

**Comment by fancymo** [comment]
> > 不好意思 再问一下。。我现在对于横轴有些空值 想直接把前一个值和后一个值连起来。这个是否可以做到呢？
> 
> 可以，见图
> 
> ![image](https://user-images.githubusercontent.com/6628666/76928980-f7c3e500-691d-11ea-87ce-786f0e65a9cd.png)
我在使用line，传入connectNulls 空值不会自动连接

**Comment by fancymo** [comment]
> > > 不好意思 再问一下。。我现在对于横轴有些空值 想直接把前一个值和后一个值连起来。这个是否可以做到呢？
> > 
> > 
> > 可以，见图
> > ![image](https://user-images.githubusercontent.com/6628666/76928980-f7c3e500-691d-11ea-87ce-786f0e65a9cd.png)
> > 我在使用line，传入connectNulls 空值不会自动连接

是需要额外的配置吗
