### ISSUE TITLE
桑基图权重回调不执行

### ISSUE THREAD

**Issue by ShaofeiZi** [antvis/G2#2220]
文档地址 ：https://g2.antv.vision/zh/docs/manual/dataset/transform/#diagramsankey-%E6%A1%91%E5%9F%BA%E5%9B%BE

![image](https://user-images.githubusercontent.com/19340899/77499499-395c0f00-6e8d-11ea-83f2-fb5501e19e05.png)

![image](https://user-images.githubusercontent.com/19340899/77499553-64466300-6e8d-11ea-96c3-6524e1931348.png)

codepen: https://codepen.io/shaofeizi/pen/abORQNN
求设置排序的方式

**Comment by simaQ** [comment]
目前不支持 value 属性，文档错误，排序的方式可以使用 [sort](https://g2.antv.vision/zh/docs/manual/dataset/transform/#sort-%E6%95%B0%E6%8D%AE%E6%8E%92%E5%BA%8F) 或者 [sort-by](https://g2.antv.vision/zh/docs/manual/dataset/transform/#sort-by-%E6%8C%89%E5%AD%97%E6%AE%B5%E6%8E%92%E5%BA%8F)

**Comment by ShaofeiZi** [comment]
> 目前不支持 value 属性，文档错误，排序的方式可以使用 [sort](https://g2.antv.vision/zh/docs/manual/dataset/transform/#sort-%E6%95%B0%E6%8D%AE%E6%8E%92%E5%BA%8F) 或者 [sort-by](https://g2.antv.vision/zh/docs/manual/dataset/transform/#sort-by-%E6%8C%89%E5%AD%97%E6%AE%B5%E6%8E%92%E5%BA%8F)

未能生效，可否举个栗子
![image](https://user-images.githubusercontent.com/19340899/77874475-9be34f80-727f-11ea-9cb8-d109c69b165c.png)
