### ISSUE TITLE
3.x和4.x柱状图以时间(YYYY-MM-DD)为X轴时最左侧和最右侧的图形溢出问题

### ISSUE THREAD

**Issue by TP026787** [antvis/G2#2224]
* **G2 Version**:3.x & 4.x
* **Platform**:
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/15964615/77621430-6ab10980-6f77-11ea-8c3d-ff8ce557e8dd.png)

* **CodePen Link**:https://codepen.io/lmgs123/pen/LYVXLBL

柱状图中如果使用以时间(YYYY-MM-DD)为X轴的刻度时会出现这个bug，应该是柱状图每根柱子的中心作为了X轴的起始点的问题，折线图就没有这个问题，顺便使用ticks的话刻度和时间的位置也是对不准的

**Comment by simaQ** [comment]
是这样的，time 类型的 range: [0, 1]，有两种解法：

1. 使用  timeCat 类型
2. 设置 range 属性

**Comment by TP026787** [comment]
> 是这样的，time 类型的 range: [0, 1]，有两种解法：
> 
> 1. 使用  timeCat 类型
> 
> ```
> chart.scale('字段名', {
>   type: 'timeCat'
> });
> ```
> 
> 1. 设置 range 属性
> 
> ```
> chart.scale('字段名', {
>   range: [ 0.1, 0.9]
> });
> ```

设置timeCat类型确实能解决，但是这个刻度的位置和手动设置tickCount或者ticks一样是偏的
![image](https://user-images.githubusercontent.com/15964615/77624328-9a164500-6f7c-11ea-8ec5-36dca2c61236.png)

**Comment by simaQ** [comment]
这是因为我们默认的 tickCount 是 5，你设置下 tickCount 等于数据数试下

**Comment by TP026787** [comment]
> 这是因为我们默认的 tickCount 是 5，你设置下 tickCount 等于数据数试下

![image](https://user-images.githubusercontent.com/15964615/77717148-a8b33980-701a-11ea-9161-995d457e3a60.png)
其实我想实现类似于折线图这种效果，折线图的时间都是对应的上的。因为涉及30天数据tick设置30的话全部显示出来了就会很难看

**Comment by simaQ** [comment]
默认就是对应的，请看下面代码：

```ts
import DataSet from '@antv/data-set';
import { Chart } from '@antv/g2';

const data = [
  { year: '2020-01-01', value: 10 },
  { year: '2020-01-02', value: 20 },
  { year: '2020-01-03', value: 50 },
  { year: '2020-01-04', value: 40 },
  { year: '2020-01-05', value: 50 },
  { year: '2020-01-06', value: 20 },
  { year: '2020-01-07', value: 25 }
];

const chart = new Chart({
  container: 'container',
  autoFit: true,
  height: 500,
  padding: [20, 40],
});
chart.data(data);
chart.scale({
  year: {
    type: 'timeCat',
    //tickCount: 3
  },
});

chart.interval().position('year*value');
chart.render();
```

我看了你链接的代码....  你是不是做了多余的操作

**Comment by TP026787** [comment]
> ```ts
> const data = [
>   { year: '2020-01-01', value: 10 },
>   { year: '2020-01-02', value: 20 },
>   { year: '2020-01-03', value: 50 },
>   { year: '2020-01-04', value: 40 },
>   { year: '2020-01-05', value: 50 },
>   { year: '2020-01-06', value: 20 },
>   { year: '2020-01-07', value: 25 }
> ];
> 
> const chart = new Chart({
>   container: 'container',
>   autoFit: true,
>   height: 500,
>   padding: [20, 40],
> });
> chart.data(data);
> chart.scale({
>   year: {
>     type: 'timeCat',
>     //tickCount: 3
>   },
> });
> 
> chart.interval().position('year*value');
> chart.render();
> ```

我的意思是30条数据的话，如果全部显示的话是对应的，只显示6个刻度的话，就是偏移的

**Comment by TP026787** [comment]
> 默认就是对应的，请看下面代码：
> 
> ```ts
> import DataSet from '@antv/data-set';
> import { Chart } from '@antv/g2';
> 
> const data = [
>   { year: '2020-01-01', value: 10 },
>   { year: '2020-01-02', value: 20 },
>   { year: '2020-01-03', value: 50 },
>   { year: '2020-01-04', value: 40 },
>   { year: '2020-01-05', value: 50 },
>   { year: '2020-01-06', value: 20 },
>   { year: '2020-01-07', value: 25 }
> ];
> 
> const chart = new Chart({
>   container: 'container',
>   autoFit: true,
>   height: 500,
>   padding: [20, 40],
> });
> chart.data(data);
> chart.scale({
>   year: {
>     type: 'timeCat',
>     //tickCount: 3
>   },
> });
> 
> chart.interval().position('year*value');
> chart.render();
> ```
> 
> 我看了你链接的代码.... 你是不是做了多余的操作

抱歉，我在做图形变换的时候，公共方法里有个设置
tickLine: {
        alignWithLabel: false,
        length: 0
 }
的属性导致刻度偏移了，谢谢解答问题
