### ISSUE TITLE
需求建议-G2社区

### ISSUE THREAD

**Issue by xstxhjh** [antvis/G2#2225]
能不能搭建一个G2的图表社区，让用户可以上传自己实现的G2图表，用户可以从中获取到优秀的图表进行二次开发。

**Comment by simaQ** [comment]
目前可以直接往 G2 仓库提交 PR，所有的 demo 都在 examples 目录下，可以新加一个文件夹，用于存储社区贡献的图表~~~~

**Comment by xstxhjh** [comment]
建议还是把文档挂在阿里云上面吧，看你们能不能申请一下，国内访问github pages不稳定。
其实搭建社区平台，用户可以上传图表代码，然后展示、提出问题，这样也方便你们定位问题。这方面后期可以考虑吗？

**Comment by simaQ** [comment]
> 建议还是把文档挂在阿里云上面吧，看你们能不能申请一下，国内访问github pages不稳定。
> 其实搭建社区平台，用户可以上传图表代码，然后展示、提出问题，这样也方便你们定位问题。这方面后期可以考虑吗？

我们有部署国内镜像的，gitee 上 https://antv-g2.gitee.io/en/

社区这个我们看看有什么快速搭建的方法

**Comment by hustcc** [comment]
> > 建议还是把文档挂在阿里云上面吧，看你们能不能申请一下，国内访问github pages不稳定。
> > 其实搭建社区平台，用户可以上传图表代码，然后展示、提出问题，这样也方便你们定位问题。这方面后期可以考虑吗？
> 
> 我们有部署国内镜像的，gitee 上 https://antv-g2.gitee.io/en/
> 
> 社区这个我们看看有什么快速搭建的方法

@xstxhjh 感谢你这个非常不错的想法，不过短期来看，可能不会做社区功能，这个 issue 先暂时关闭到了。

后面有想法也欢迎来这个交流。
