### ISSUE TITLE
v3版本地图数据重绘repaint属性，v4版本没有了。有可支持的重绘属性吗？v4 paint不生效

### ISSUE THREAD

**Issue by liangchaofei** [antvis/G2#2229]
* **G2 Version**: v4
* **Platform**:mac
* **Mini Showcase(like screenshots)**:v3版本地图数据重绘repaint属性，v4版本没有了。有可支持的重绘属性吗？v4 paint不生效
* **CodePen Link**:

**Comment by simaQ** [comment]
chart.render(true);

**Comment by liangchaofei** [comment]
> render

用了这个api,没有生效哈。场景是切换国家地图，切换完，地图会变小。

**Comment by liangchaofei** [comment]
更新数据代码如下：但是切换国家地图，地图会变小
 updataData = (userData: MapItem[], filters: FilterItems) => {
    const { bgDv, userDv } = this.initData(userData, filters);
    this.chart.render(true);
    this.bgView.changeData(bgDv.rows);
    this.pointView.changeData(userDv.rows);
  };

**Comment by liangchaofei** [comment]
> chart.render(true);
> 
> 在升级文档有说明。

更新数据代码如下：但是切换国家地图，地图会变小
updataData = (userData: MapItem[], filters: FilterItems) => {
const { bgDv, userDv } = this.initData(userData, filters);
this.chart.render(true);
this.bgView.changeData(bgDv.rows);
this.pointView.changeData(userDv.rows);
};

**Comment by simaQ** [comment]
恩，这个问题应该和 #2232  是一个问题，下周我们会修复掉

**Comment by liangchaofei** [comment]
> 恩，这个问题应该和 #2232 是一个问题，下周我们会修复掉

感谢，辛苦修复后同步下

**Comment by hustcc** [comment]
> > 恩，这个问题应该和 #2232 是一个问题，下周我们会修复掉
> 
> 感谢，辛苦修复后同步下

已修复，请查验。
