### ISSUE TITLE
请问，g2.js网络上是不是还没有非压缩代码？

### ISSUE THREAD

**Issue by 123geshuai** [antvis/g2#223]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by afc163** [comment]
https://github.com/antvis/g2/tree/master/src 

。。。。。。。。。。。。。。。。。。。。。。。

**Comment by leungwensen** [comment]
如果需要构建后、可以直接用的非压缩版本代码，可以用 https://unpkg.com/@antv/g2@3.0.0/build/g2.js
