### ISSUE TITLE
master 最新代码，分面图例过滤规程中，图例项会减少

### ISSUE THREAD

**Issue by simaQ** [antvis/G2#2232]
![分面图例过滤 BUG](https://user-images.githubusercontent.com/6628666/77725862-88db4000-7031-11ea-8870-6a674646175d.gif)

**Comment by hustcc** [comment]
类似问题 #2204

**Comment by dxq613** [comment]
都是同一个问题出现的，现在两个方案：
1. 生成 legend 的view 缓存一下，更新的时候，从 view 上重新获取数据即可
2.直接读取 chart 上 sync 后的 scale

**Comment by hustcc** [comment]
> 都是同一个问题出现的，现在两个方案：
> 
> 1. 生成 legend 的view 缓存一下，更新的时候，从 view 上重新获取数据即可
>    2.直接读取 chart 上 sync 后的 scale

发现这个问题和 下午你说的那个还不是一个问题。分面中图例项减少的原因是：

因为之前 facet subview 没有做 update，所以每次 chart.render(true) 的时候，实际上是销魂 facet subviews，然后重新创建，所以设置进去的 filter 都没有清理了。
