### ISSUE TITLE
G2的移动端能力

### ISSUE THREAD

**Issue by paleface001** [antvis/G2#2233]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

- [x] G2的移动端事件

- [x] 移动端基础交互能力的支持

**Comment by simaQ** [comment]
https://github.com/antvis/G2/pull/2250 移动端事件已支持

**Comment by paleface001** [comment]
> #2250 移动端事件已支持

NICE 🔥
