### ISSUE TITLE
Go

### ISSUE THREAD

**Issue by yhc1990518** [antvis/G2#2234]
* **G2 Version**: 4.x
* **Platform**: macOS / Windows
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/24221476/77746017-4167aa80-7057-11ea-83f3-eaac61f056b5.png)
![image](https://user-images.githubusercontent.com/24221476/77746041-4c223f80-7057-11ea-958a-99c5bf267e34.png)

你好，我在使用G2绘制线图时希望grid的线是虚线，找了很多demo，发现都是如截图中展示的样子：外面缩略图是虚线，但是实际demo中并没有体现虚线grid的逻辑。

**Comment by simaQ** [comment]
抱歉，G2 4.0 默认主题里将 grid 的样式设置为实线了。你可以在代码离这么配置：

```ts
chart.axis('坐标轴对应的字段名', {
  grid: {
    line: {
      lineDash: [ 2 ]
    }
  }
});
```

**Comment by yhc1990518** [comment]
你好，假如我希望Y轴刻度是虚线，但是我的值有好几种字段应该怎么办？

**Comment by yhc1990518** [comment]
`
    view2.line().position('Date*SUMdisplayNumber').color('#115285').tooltip('SUMdisplayNumber');
    view2.area().position('Date*SUMdisplayNumber').color('l(100) 0:#2875b1 1:#fee5d9').tooltip(false);
    view2.line().position('Date*SUMclkNumber').color('#794411').tooltip('SUMclkNumber');
    view2.area().position('Date*SUMclkNumber').color('l(100) 0:#9d5f23 1:#daa169').tooltip(false);
    this.chart.axis('value', { grid: { line: {lineDash:[2, 2]}}});
`
写value似乎不起作用
