### ISSUE TITLE
如何设置柱形图中单个柱形的宽度

### ISSUE THREAD

**Issue by lingmissing** [antvis/G2#2237]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by curryhh** [comment]
解决了吗？我也遇到这样的问题

**Comment by MrChen2016-08-27** [comment]
请问解决了吗，我也遇到了这个问题

**Comment by iShawnWang** [comment]
should be reopend
