### ISSUE TITLE
g2.底层 antv/g 中 PathUtil.catmullRomToBezier 传入 两个点的时候 生成曲线会有NaN 比如 , pathUtil.catmullRomToBezier([100, 120, 200, 180]), 会得到 ["C", NaN, NaN, 183.33333333333334, 170, 200, 180] 

### ISSUE THREAD

**Issue by liuwuyue** [antvis/g2#224]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by leungwensen** [comment]
catmullRom 是 四个点 的。为了性能，这个频繁调用的底层函数我们没有做参数校验。

https://en.wikipedia.org/wiki/Centripetal_Catmull%E2%80%93Rom_spline

https://en.wikipedia.org/wiki/B%C3%A9zier_curve
