### ISSUE TITLE
词云图

### ISSUE THREAD

**Issue by houwenli123** [antvis/G2#2242]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
G2 官网 demo 有提供，多翻一翻。

https://g2.antv.vision/en/examples/other/other#word-cloud

https://g2.antv.vision/en/examples/other/other#word-cloud-mask

**Comment by xiaoyu-tamu** [comment]
example挂了
