### ISSUE TITLE
桑基图如何进行自定义排序

### ISSUE THREAD

**Issue by ShaofeiZi** [antvis/G2#2243]
来自 ：[2220](https://github.com/antvis/G2/issues/2220)
 sort 或者 sort-by
未能生效，可否举个栗子
![image](https://user-images.githubusercontent.com/19340899/77922129-391ba380-72d3-11ea-9f51-00f63ba0b54a.png)

**Comment by simaQ** [comment]
你具体的需求是什么，数据进行 sankey 布局后进行排序？

**Comment by ShaofeiZi** [comment]
> 你具体的需求是什么，数据进行 sankey 布局后进行排序？

根据数值大小进行从上往下的排序
其中某几个节点需要一直置底
![image](https://user-images.githubusercontent.com/19340899/77980917-2ccb3100-733b-11ea-9851-50ea4c59f532.png)

**Comment by dbl520** [comment]
咋解决的
