### ISSUE TITLE
请问4.x版本堆叠柱状图如果取sum之后数值作为label

### ISSUE THREAD

**Issue by lanbosm** [antvis/G2#2244]
官方例子没有 请问label有什么参数 
或者是自己算出sum然后用annotation画上去

**Comment by simaQ** [comment]
2.x 版本是可以通过直接在 label() 方法中设置统计函数实现，但是出于种种考虑从 3.x 开始将统计函数移除了。

现在的话，就像你提到的，可以通过 chart.annotation().text() 绘制上去，还是蛮方便的...
