### ISSUE TITLE
在4.0.3版本上注册shape时 不能使用parsePoint() （按照官网示例也会报错）

### ISSUE THREAD

**Issue by zhoustudent** [antvis/G2#2247]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

G2 Version:4.0.3
Platform: mac
Mini Showcase(like screenshots): 无
CodePen Link: 无

**Comment by simaQ** [comment]
报错的代码来一下

**Comment by zhoustudent** [comment]
> 报错的代码来一下
解决了，他们的registerShape 没有声明parsePoint这个方法，因此在registerShape中使用this.parsePoint会导致ts过不去，需要加ignore才能过去
