### ISSUE TITLE
 【chart.annotation()无法识别】[Vue warn]: Error in mounted hook: "TypeError: this.chart.annotation is not a function"

### ISSUE THREAD

**Issue by arraycto** [antvis/G2#2249]
* **G2 Version**:
4.0.3最新版本

* **Platform**:
win10 ，Chrome
* **Mini Showcase(like screenshots)**:
`vue.esm.js?915d:628 [Vue warn]: Error in mounted hook: "TypeError: this.chart.annotation is not a function"`
* **CodePen Link**:

官方的例子，其他都好使，就是使用chart.annotation().text({})不识别

**Comment by simaQ** [comment]
... 你给我的信息，无从下手排查...

**Comment by arraycto** [comment]
npm的仓库版本  "@antv/g2": "^3.5.14",为啥不是4.0.3的版本，我自查了一下，好像不支持4.0.3版本的。guide不报错但是text不显示。
