### ISSUE TITLE
鼠标移到第一根柱子左半边不能显示tooltip

### ISSUE THREAD

**Issue by xsjohn0306** [antvis/g2#225]
问题描述: 鼠标移到第一根柱子左半边不能显示tooltip, 柱子左半边超出绘图区域所以不能显示tooltip?
demo地址: https://jsfiddle.net/xsjohn/muk6uoaq/
截图:
![image](https://user-images.githubusercontent.com/8650758/33360103-236ff754-d50d-11e7-94a5-66a790b5ca4f.png)

**Comment by leungwensen** [comment]
这个 demo 建议可以把 X 轴的字段由 time 类型改为 timeCat 类型，这样就可以保证柱子的绘制都在画布响应区域了：

```js
chart.source(data, {
  // ...
  time: {
    type: 'timeCat',
    // ...
  },
});
```
