### ISSUE TITLE
4.0.2 主题配置并没生效

### ISSUE THREAD

**Issue by embaobao** [antvis/G2#2251]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
请提供可复现的例子帮助我们定位问题，否则超过三天无回复，issue 将会关闭，谢谢配合。

**Comment by embaobao** [comment]
`const theme = {
  defaultColor: 'red',
  padding: [100, 100, 100, 100],
  colors: chartsColors,
  colors_20: chartsColors,
  maxColumnWidth: 56
};

const chart = new Chart({
      container: chartContainer.current,
      autoFit: true,
      height: 400
    });
    chart.theme(theme);

// 主题颜色不生效 

//定制
import { Chart, registerTheme, registerGeometryLabelLayout } from '@antv/g2';
  registerTheme('saGraphics', theme);
//主题的配置
    this.chart.theme('saGraphics');
//也无效

`

**Comment by embaobao** [comment]
`import { Chart, Util } from '@antv/g2';
const chartsColors = [
  '#488BFF',
  '#26CEBA',
  '#FFC069',
  '#FD6865',
  '#6D7EE4',
  '#FF9C6E',
  '#81C785',
  '#B47FEC',
  '#62A5F6',
  '#FF85C0',
  '#A47D79',
  '#AED581',
  '#FEB7B7',
  '#82A9DA',
  '#FFC069',
  '#A5A5F1',
  '#FC9186',
  '#66D1E8',
  '#79A493',
  '#EDB496'
];

const theme = {
  defaultColor: 'red',
  padding: [100, 100, 100, 100],
  colors: chartsColors,
  colors_20: chartsColors,
  maxColumnWidth: 56
  }
const data = [
  { type: '一线城市', value: 0.19 },
  { type: '二线城市', value: 0.21 },
  { type: '三线城市', value: 0.27 },
  { type: '四线及以下', value: 0.33 },
];
const chart = new Chart({
  container: 'container',
  autoFit: true,
  height: 500,
});
chart.data(data);
//chart.legend(false);
chart.coordinate('theta', {
  radius: 0.75,
  innerRadius: 0.4
});
chart.tooltip({
  showMarkers: false
});

chart.theme(theme);
const interval = chart
  .interval()
  .adjust('stack')
  .position('value')
  .color('type', ['#063d8a', '#1770d6', '#47abfc', '#38c060'])
  .style({ opacity: 0.4 })
  .state({
    active: {
      style: (element) => {
        const shape = element.shape;
        return {
          matrix: Util.zoom(shape, 1.1),
        }
      }
    }
  })
  .label('type', (val) => {
    const opacity = val === '四线及以下' ? 1 : 0.5;
    return {
      offset: -30,
      style: {
        opacity,
        fill: 'white',
        fontSize: 12,
        shadowBlur: 2,
        shadowColor: 'rgba(0, 0, 0, .45)',
      },
      content: (obj) => {
        return obj.type + '\n' + obj.value + '%';
      },
    };
  });

chart.interaction('legend-active');

chart.render();

`

**Comment by simaQ** [comment]
> `const theme = {
> defaultColor: 'red',
> padding: [100, 100, 100, 100],
> colors: chartsColors,
> colors_20: chartsColors,
> maxColumnWidth: 56
> };
> 
> const chart = new Chart({
> container: chartContainer.current,
> autoFit: true,
> height: 400
> });
> chart.theme(theme);
> 
> // 主题颜色不生效
> 
> //定制
> import { Chart, registerTheme, registerGeometryLabelLayout } from '@antv/g2';
> registerTheme('saGraphics', theme);
> //主题的配置
> this.chart.theme('saGraphics');
> //也无效
> 
> `

一个小 tip，块状代码请使用：


\`\`\`js

\`\`\`

**Comment by embaobao** [comment]
```
import { Chart, Util } from '@antv/g2';
const chartsColors = [
'#488BFF',
'#26CEBA',
'#FFC069',
'#FD6865',
'#6D7EE4',
'#FF9C6E',
'#81C785',
'#B47FEC',
'#62A5F6',
'#FF85C0',
'#A47D79',
'#AED581',
'#FEB7B7',
'#82A9DA',
'#FFC069',
'#A5A5F1',
'#FC9186',
'#66D1E8',
'#79A493',
'#EDB496'
];

const theme = {
defaultColor: 'red',
padding: [100, 100, 100, 100],
colors: chartsColors,
colors_20: chartsColors,
maxColumnWidth: 56
}
const data = [
{ type: '一线城市', value: 0.19 },
{ type: '二线城市', value: 0.21 },
{ type: '三线城市', value: 0.27 },
{ type: '四线及以下', value: 0.33 },
];
const chart = new Chart({
container: 'container',
autoFit: true,
height: 500,
});
chart.data(data);
//chart.legend(false);
chart.coordinate('theta', {
radius: 0.75,
innerRadius: 0.4
});
chart.tooltip({
showMarkers: false
});

chart.theme(theme);
const interval = chart
.interval()
.adjust('stack')
.position('value')
.color('type', ['#063d8a', '#1770d6', '#47abfc', '#38c060'])
.style({ opacity: 0.4 })
.state({
active: {
style: (element) => {
const shape = element.shape;
return {
matrix: Util.zoom(shape, 1.1),
}
}
}
})
.label('type', (val) => {
const opacity = val === '四线及以下' ? 1 : 0.5;
return {
offset: -30,
style: {
opacity,
fill: 'white',
fontSize: 12,
shadowBlur: 2,
shadowColor: 'rgba(0, 0, 0, .45)',
},
content: (obj) => {
return obj.type + '\n' + obj.value + '%';
},
};
});

chart.interaction('legend-active');

chart.render();
```

**Comment by simaQ** [comment]
抱歉我没有及时更新文档。这里有两个地方导致你主题没有生效：

1. 主题属性错误，正确属性名见下图
![image](https://user-images.githubusercontent.com/6628666/78206118-93358800-74d0-11ea-8b06-2dafc7769333.png)

2. 如果在 color() 中指定了颜色，就会以指定的颜色为准，所以如果你想要你的主题颜色生效，就要把这个颜色数组删除，另外如果只是改一下当前图表的颜色的话，可以直接通过这个方法更改，不需要通过自定义主题。

![image](https://user-images.githubusercontent.com/6628666/78206228-d4c63300-74d0-11ea-9720-b668d9c55423.png)
