### ISSUE TITLE
tooltip支持排序和搜索

### ISSUE THREAD

**Issue by c625473164** [antvis/G2#2252]
tooltip是否支持排序和搜索

**Comment by simaQ** [comment]
默认不提供，但是可以自定义 tooltip container

**Comment by c625473164** [comment]
tooltip的container的定义方法我在文档里没找到，可以提供一下吗，谢谢

**Comment by c625473164** [comment]
> 默认不提供，但是可以自定义 tooltip container

tooltip的container的定义方法我在文档里没找到，可以提供一下吗，谢谢
