### ISSUE TITLE
配置了annotation以后，chart.clear()并没有把辅助文本清空；

### ISSUE THREAD

**Issue by sunmmerOne** [antvis/G2#2253]
* **G2 Version**:4.x
* **Platform**:mac chrome
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

   chart
      .annotation()
      .text({
        position: ['50%', '50%'],
        content: title,
        style: {
          fontSize: 14,
          fill: '#8c8c8c',
          textAlign: 'center',
        },
        offsetY: -20,
      })

    chart.clear();

使用了clear以后，辅助文字仍然存在，在下次渲染组件时，文字重影；

**Comment by simaQ** [comment]
https://g2.antv.vision/zh/docs/manual/tutorial/annotation/#%E6%B8%85%E7%A9%BA%E5%9B%BE%E5%BD%A2%E6%A0%87%E6%B3%A8

> chart.annotation().clear(true) 清空所有的图形标注同时清空配置。

**Comment by sunmmerOne** [comment]
好了，多谢
