### ISSUE TITLE
我在使用 G2 图表的时候遇到一个严重BUG。

### ISSUE THREAD

**Issue by hexu6788** [antvis/G2#2254]
我在使用 G2 图表的时候遇到一个严重BUG。
我先设置一个id=‘div_content’高度为500，宽度为500的div。然后在这个div中使用G2饼图。代码运行后，图表正确显示。当我使用 js 更新了 div_content 的宽度为200后，  G2的图表不能跟随 div_content 的大小进行自适应。 
![image](https://user-images.githubusercontent.com/4196818/78118052-fecc1680-7438-11ea-93bf-3ef75cfbc80d.png)
![image](https://user-images.githubusercontent.com/4196818/78118077-0ab7d880-7439-11ea-8b03-ae1791078007.png)

![image](https://user-images.githubusercontent.com/4196818/78117976-e4923880-7438-11ea-89d9-e0c54808ab24.png)

**Comment by hustcc** [comment]
目前 G2 只监听的 window resize 事件去做 chart resize。

你可自己监听 div 的大小变化，然后调用：

```ts
chart.forceFit();
```

**Comment by hexu6788** [comment]
感谢
