### ISSUE TITLE
4.x 如何注册主题， 如何动态切换主题

### ISSUE THREAD

**Issue by VanquisherMe** [antvis/G2#2258]
* **G2 Version**:4.0.3
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

https://antv-g2.gitee.io/zh/docs/manual/tutorial/theme
按照文档无法注册主题，并且动态切换他
能否提供一个思路
官网没有提供主题模板，通过全局的getTheme可以看到主题参数，我该怎么做？
复制 getTheme的结果json 保存到本机文件？

**Comment by simaQ** [comment]
1. 如何动态切换主题？

```ts
chart.theme('dark');
chart.render(true); // 关键一步，需要手动更新
```

2. 如何获取主题模板?

    是可以通过 `chart.getTheme()` 获取全部的属性结构，在开发者教程中，已经比较详细说明了：
    * [自定义主题](https://antv-g2.gitee.io/zh/docs/manual/developer/registertheme)
    * [G2 主题配置项详解](https://antv-g2.gitee.io/zh/docs/manual/developer/dive-into-theme)

---
抱歉，文档没有补充完整，等下我补充下。

**Comment by VanquisherMe** [comment]
![G((O5HLQNX(QFR3H 3BWBFC](https://user-images.githubusercontent.com/4927398/78207128-59b24c00-74d3-11ea-91c9-646f6ab44f21.png)
![LTPE$D2@PLBP )6JCEAP@G](https://user-images.githubusercontent.com/4927398/78207134-5cad3c80-74d3-11ea-8fd5-16c11bfbf627.png)
我是这么做的对吗
问题：初始化的时候 clone 多次感觉会很慢？
文档里面是写的是colors 但是实际好像是colors10

**Comment by simaQ** [comment]
恩，文档我在更新了。

目前主题设置这里有个问题，就是如果传入 chart.theme() 方法的参数是字符串，即已经注册的主题名的话 ，内部还会和默认的主题 merge 一边，这样在你这个场景下就增加了一倍对象复制开销，这个我今天修复一下。

另外如果支持更新色板的话，可以直接:

```ts
chart.theme({
  defaultColor: '',
  colors10: [],
});
```

**Comment by VanquisherMe** [comment]
![WNN@HG7E39OH7}C)H9UMH1D](https://user-images.githubusercontent.com/4927398/78209154-d562c780-74d8-11ea-8981-106051328dcc.png)
![HRVW1TMEH%_V(US5)`)CYIJ](https://user-images.githubusercontent.com/4927398/78209174-e3b0e380-74d8-11ea-8de9-c4b0412b1443.png)
尝试使用这个方式但是好像并不对
![%(2T8S9GBPPZ~(OD~PY$1X7](https://user-images.githubusercontent.com/4927398/78209269-1e1a8080-74d9-11ea-94c6-9e3325324846.png)
这个对了，大致理解

**Comment by simaQ** [comment]
恩，是个 BUG， 4.0.4 版本会修复

**Comment by VanquisherMe** [comment]
@simaQ #2260
能不能给个思路尝试了几种都不行
