### ISSUE TITLE
svg模式在ie里所有text中文字都渲染不出来

### ISSUE THREAD

**Issue by camille-yu** [antvis/G2#2259]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by hustcc** [comment]
@camille-yu IE 版本可以告知一下吗？

@dengfuping G 有做过明确的 浏览器版本兼容 说明吗？

**Comment by dengfuping** [comment]
- 目前没有明确的浏览器兼容说明，之前遇到过 canvas 版本在 IE 下的文本渲染问题，SVG 的暂时还没有遇到过。 @camille-yu 能否提供下 IE 的版本？我这边看下

**Comment by camille-yu** [comment]
ie11，在demo站点里也可以重现这个问题

**Comment by camille-yu** [comment]
![G2-chart-svg](https://user-images.githubusercontent.com/55227697/79109467-f960bb80-7daa-11ea-9385-7e93aab665b8.png)

**Comment by hustcc** [comment]
@camille-yu G2 4.0 已经解决了，可以使用看看，这里先关闭掉了。感谢反馈^_^
