### ISSUE TITLE
color by 

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#226]
http://riddle.alibaba-inc.com/riddles/c98385d7

类似这种 demo，多 geom 组合的 chart 中，用户很简单的想要每组 geom  都有对应的 legend 可以操作。
但legend 必须用 colorby 去实现，同时当字段中只有一个值时，没有 legend 出来。需要很扭曲的造一个空的字段值才可以。

**Comment by simaQ** [comment]
这个可以通过自定义图例实现, https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_legend 

![image](https://user-images.githubusercontent.com/6628666/33413416-69bc58d2-d5cc-11e7-8210-8a466560252f.png)


```js
chart.legend({
  custom: true
})
```

**Comment by weepy3641** [comment]
好滴，3q。
