### ISSUE TITLE
官网的柱状图，鼠标在柱状图和图例之间相互移动时，出现的这样的报错

### ISSUE THREAD

**Issue by forestMrchen** [antvis/G2#2265]
![25afdb888538ef025ea33aa5fa640bf](https://user-images.githubusercontent.com/33618753/78313983-259a6200-758b-11ea-87e7-1296ad6f258b.png)

Thank you for reporting an issue.

1. It's RECOMMENDED to submit PR for typo or tiny bug fix.
2. If this's a FEATURE request, please provide: details, pseudo codes if necessary.
3. If this's a BUG, please provide: course repetition, error log and configuration. Fill in as much of the template below as you're able.
4. It will be nice to use to provide a CodePen Link which can reproduce the issue, we provide a CodePen template [g2-github-issue](https://codepen.io/leungwensen/pen/WXJgox).

感谢您向我们反馈问题。

1. 提交问题前，请先阅读 https://antv.alipay.com/zh-cn/g2/3.x/index.html 上的文档。
2. 我们推荐如果是小问题（错别字修改，小的 bug fix）直接提交 PR。
3. 如果是一个新需求，请提供：详细需求描述，最好是有伪代码实现。
4. 如果是一个 BUG，请提供：复现步骤，错误日志以及相关配置，并尽量填写下面的模板中的条目。
5. 如果可以，请提供尽可能精简的 CodePen 链接，可使用 CodePen 模板 https://codepen.io/leungwensen/pen/WXJgox，方便我们排查问题。
6. 扩展阅读：[如何向开源项目提交无法解答的问题](https://zhuanlan.zhihu.com/p/25795393)
-->

* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by forestMrchen** [comment]
9state.ts:8 Uncaught TypeError: Cannot read property 'item' of undefined
    at Xc (state.ts:8)
    at o.i.setStateEnable (state.ts:72)
    at o.i.setState (state-base.ts:44)
    at o.active (active.ts:14)
    at ra (grammar-interaction.ts:28)
    at grammar-interaction.ts:349
    at c (each.js:13)
    at o.s (grammar-interaction.ts:348)
    at a (index.js:86)
    at o.t.emit (index.js:90)

**Comment by camille-yu** [comment]
同款报错，在饼状图，图例和图之间来回滑动，会报错

**Comment by hustcc** [comment]
@forestMrchen @camille-yu  新官网上看应该已经修复了 https://g2.antv.vision/zh/examples/column/dodge#grouped
