### ISSUE TITLE
柱状图设置lineWidth，会压盖横坐标轴

### ISSUE THREAD

**Issue by BuggMaker** [antvis/G2#2266]
问题描述
柱状图设置了stroke和lineWidht之后，会压盖坐标轴；如果stroke是白色，恰好有一条数据未0，就会导致坐标轴看似断开了。
![image](https://user-images.githubusercontent.com/25820633/78319397-ac563b80-7599-11ea-8d50-b45c8454aa27.png)

复现链接：https://g2.antv.vision/zh/examples/gallery/column#column2

**Comment by simaQ** [comment]
符合预期，这种情况下，建议使用 style() 回调，当数值过低时，不设置 lineWidth

**Comment by BuggMaker** [comment]
如果边框不是白色或者堆叠柱状图呢 因为一条数据为0，其他数据展示也要受影响？
![image](https://user-images.githubusercontent.com/25820633/78319888-bfb5d680-759a-11ea-855a-0c4b23cb7253.png)

**Comment by simaQ** [comment]
这个也是符合预期的，图形的图层位于坐标轴线上方，所以当你设置边框后就会压盖坐标轴

**Comment by simaQ** [comment]
这个后面考虑支持调整坐标轴图层的功能。

**Comment by BuggMaker** [comment]
好的 THX
