### ISSUE TITLE
Looking for Download Options and Download Title Customization

### ISSUE THREAD

**Issue by srimanabimanyu** [antvis/G2#2269]
I am looking for Pie chart download option. I have my piechart in my dashboard. I want to download and store that as an image and also the title of the download should be customized.

**Comment by simaQ** [comment]
We do not offer API, but there is a solution you can consider: https://g2.antv.vision/zh/docs/manual/faq#%E5%A6%82%E4%BD%95%E5%AF%BC%E5%87%BA%E5%9B%BE%E7%89%87

If you do not understand english, just click here, read the code: 
![image](https://user-images.githubusercontent.com/6628666/78326470-15937a00-75ad-11ea-801a-172366487405.png)
