### ISSUE TITLE
高度自适应

### ISSUE THREAD

**Issue by jingsam** [antvis/g2#227]
forceFit可以实现宽度自适应，但没有高度自适应，是否考虑支持。

另外，只有当window.resize的时候才会触发forceFit，是否考虑监测container的尺寸来触发forceFit，这样更精确一些。这方面有一些开源库，如https://github.com/KyleAMathews/element-resize-event 。 并且Chrome已经尝试实现 [ResizeObserver](https://developers.google.com/web/updates/2016/10/resizeobserver)

**Comment by Jelly38214** [comment]
设置height为挂载点的clientHeight试试

**Comment by jingsam** [comment]
clientHeight只保证初始化的时候和容器同高，但容器尺寸变化时，仍然会保持原有的高度，不会自适应变化

**Comment by dxq613** [comment]
一般场景下图表基本都是作为一个区块显示的，自适应宽的需求是强需求，自适应高很麻烦。一般来说表格控件都有这种功能，但是对于图表来说不是必要的。所以我们在设计 forceFit 的时候才仅仅适应了宽度，对于流程图之类的场景来说，作为主要的工作空间，自适应高是强需求。

所以这种功能在 G2 上就不提供了，如果真的有需求，就使用 changeHeight(h) 接口好了

**Comment by dxq613** [comment]
resizeObserver 的兼容性太差了，https://caniuse.com/#search=resize， 只有chrome 的最近几个版本才支持，等到主流浏览器都支持了再说吧。

**Comment by xiongsongsong** [comment]
太需要这个功能了，因为图表所在区域全是flex布局。

**Comment by PerseveranceZ** [comment]
太需要这个功能了。

**Comment by zhentaoo** [comment]
无语，echarts都有这个功能，粉转路

**Comment by ericjjj** [comment]
4.x changeHeight 函数去掉了

**Comment by wzbooks** [comment]
4.x先用 changeSize(width, height) 函数吧

**Comment by Phyday** [comment]
现在我试了下，autoFit: true,forceFit: true,同时使用可以根据外框高度宽度自适应了，大佬们可以试下

**Comment by hustcc** [comment]
快 4 年的 issue 了，怎么还有回复。

> G2 的 forceFit 以及 4.0 的 autoFit 都是仅仅针对 window.reisze 事件进行处理的。（历史原因）最新的 [G2Plot](https://github.com/antvis/G2Plot) 才做了针对容器的自动适配。

所以在 G2 中要两个方案可以实现：

1. 业务监听容器变化，然后触发手动触发一下 window.resize 事件（如果其他地方也监听了 resize，可能带来副作用）
2. 业务监听容器变化，然后去执行 chart.changeSize(w, h)

而  **业务监听容器变化** 可以使用 [size-sensor](https://github.com/hustcc/size-sensor) 轻量，已经做了浏览器兼容。G2Plot 中已经使用这个。

最后，对于大部分的业务场景，更建议直接使用 G2Plot，内置不少优化。
