### ISSUE TITLE
柱状图可以实现类似饼图的label吗？

### ISSUE THREAD

**Issue by ZengZhenfei** [antvis/G2#2271]
柱状图可以实现类似饼图的label吗？
![image](https://user-images.githubusercontent.com/29648356/78354088-ca458f80-75dd-11ea-9adf-7b95cf70d5d6.png)

**Comment by ZengZhenfei** [comment]
因为数据量很小的时候，如果label显示在图形里面，会造成重叠或不美观

**Comment by ZengZhenfei** [comment]
谁有具体的实现思路吗？

**Comment by Me-Momo** [comment]
类似带迁移线是吧，这里还涉及到 标签布局的问题，目前应该是不好做通用 label 的。
可以考虑在render之后，自己拿到每个shape，绘制 label shape

**Comment by simaQ** [comment]
可以参考这个 demo ： https://antv-g2.gitee.io/zh/examples/column/stack#ripple
