### ISSUE TITLE
饼图数据存在null值 无法展示

### ISSUE THREAD

**Issue by Me-Momo** [antvis/G2#2272]
复现地址: https://riddle.alibaba-inc.com/riddles/1bb17906
期望不要自己过滤null值，因为图例希望也展示

**Comment by simaQ** [comment]
这里面有两个问题：

1. 局部刷新问题：当数据中存在 null 值，通过 G2 的图形语法映射后生成的 shape 的 bbox 就会存在 NaN，而 G 目前的局部刷新策略对于这种情况的处理就是整个画布不绘制，这种策略不太符合预期，不能因为单个 shape 的 bbox 为 NaN，就让这个画布不绘制，关联  issue: https://github.com/antvis/g/issues/343 @dengfuping 麻烦尽快解决下
2. label bug，未过滤 value: null 的数据。如果 issue 中给出的代码不绘制 label，然后把 `localRefresh: false` 关闭，那么就符合预期了。

**Comment by Me-Momo** [comment]
G2 3.6.x 有办法修复吗
