### ISSUE TITLE
添加滑块，图表（分组柱状图）初始时不会按设置的起点和终点进行渲染

### ISSUE THREAD

**Issue by wzl281158150** [antvis/G2#2273]
* **G2 Version**: 4.0.4
* **Platform**: Chrome 80.0.3987.163 

这里采用[官方文档的例子](https://antv-g2.gitee.io/zh/examples/area/basic#area-large)演示

**此处的图表显示为全部数据**
![image](https://user-images.githubusercontent.com/22830541/78500322-4ed41180-7788-11ea-8fb2-3cc9b9cbb261.png)
**当我拖动滑块或者在代码中执行两次render时，渲染结果正确**
![image](https://user-images.githubusercontent.com/22830541/78500361-7c20bf80-7788-11ea-83ca-12b84e4c7b69.png)

**Comment by hustcc** [comment]
已经修复，没有关闭 issue。
