### ISSUE TITLE
4.0 padding计算问题，

### ISSUE THREAD

**Issue by Leannechn** [antvis/G2#2274]
* **G2 Version**: 4.0.2
![image](https://user-images.githubusercontent.com/6812138/78624880-44676400-78bd-11ea-8bf9-49f3fb37c901.png)

https://codepen.io/leanneCC/pen/gOpVoVm

**Comment by simaQ** [comment]
@hustcc 我们加一个 appendPadding 来解决下？https://github.com/antvis/G2/blob/v3.5.x/src/chart/chart.js#L64

**Comment by hustcc** [comment]
可以的~

**Comment by valaxy** [comment]
有啥hack方案没，在fix没上之前先临时解决一下

**Comment by valaxy** [comment]
找到一个办法，可以暂时用「设置坐标系两端留白」来fix，https://g2.antv.vision/zh/docs/manual/tutorial/axis

**Comment by hustcc** [comment]
appendPadding 已经增加。

```ts
new Chart({
  ...
  appendPadding: 10,
})
```
