### ISSUE TITLE
Y轴坐标未显示负数

### ISSUE THREAD

**Issue by doudou003** [antvis/G2#2275]
# 问题
最基本使用出现无法直观可视化数据，严重时出现误读

# 复现1
复现：https://codesandbox.io/s/g0ztw

问题：容易误读数据

# 复现2
复现：https://codesandbox.io/s/9sgtl

问题：反向数据也无法判断出数据包含正数

# 复现3
复现：https://codesandbox.io/s/i315i

问题：正负混合数据，Y轴显示过于简单（下限和上限呢？）

# 期望
虽然可以手动调整，但图表库最基本状态应该满足。
避免数据误读，不要违背可视化图表存在的最基本原则！

**Comment by simaQ** [comment]
这个和 scale 内的算法有关，可以手动设置下 nice: `view1.scale('Deaths', { nice: true })`

**Comment by doudou003** [comment]
## 理解可配
可以另行配置是可以理解的，不能设置就有鬼了；


## 还是期望
但期望效果是在优化数值范围均匀分布的基础上，尽可能完整表达出数据含义，而不是非A即B（提供可配置就将就）。


## 是否应默认优化
尤其还是默认配置


## 数据含义大于一切
优化了均匀分布，却掩盖了数据本来含义意，是优化还是误导；


## 借鉴一下
看一下值得点赞的（负值优化）
- 负值位置
- 负值精度0.00001都ok
- X轴视觉位置
![image](https://user-images.githubusercontent.com/62648044/78993857-4eb18880-7b71-11ea-91e3-f03bd2165f48.png)
@simaQ
