### ISSUE TITLE
Tooltip，在窗口大小变化后可能出现被挤压或超出画布的问题

### ISSUE THREAD

**Issue by wzl281158150** [antvis/G2#2279]
* **G2 Version**: 4.0.4
* **Platform**: Chrome 80.0.3987.163
* **Mini Showcase(like screenshots)**:
![tooltip](https://user-images.githubusercontent.com/22830541/78635715-6b339380-78d9-11ea-8397-79ae93e1957d.gif)

若直接在小尺寸上渲染图表tooltip不会有问题，但在缩小窗口（尤其是大幅度）时可能会导致最右侧几个数据的tooltip在显示时被挤压或直接超出画布，再大幅度增大窗口之后问题可能会消失。

**Comment by AkatQuas** [comment]
resize 事件发生后，wrapperElement 的大小没有变化，但是canvas是会发生变化的，

**Comment by simaQ** [comment]
> resize 事件发生后，wrapperElement 的大小没有变化，但是canvas是会发生变化的，

4.0.4 版本应该修复了吧

**Comment by AkatQuas** [comment]
![Screen Shot 2020-04-08 at 10 09 40](https://user-images.githubusercontent.com/24731539/78737059-3d098e80-7981-11ea-8a73-f162c1463239.png)

当没有加入下面的折线图的时候，表现是正常的。

![Screen Shot 2020-04-08 at 10 10 20](https://user-images.githubusercontent.com/24731539/78737064-40047f00-7981-11ea-9a70-518ed71e0743.png)

加入折线图后，就发生了微妙的变化。

布局如下：

```html
<div nz-row nzType="flex" nzJustify="space-between" [nzGutter]="8">
  <div nz-col nzSpan="8">
    <app-mock-warning-area></app-mock-warning-area>
  </div>
  <div nz-col nzSpan="8">
    <app-mock-warning-staff></app-mock-warning-staff>
  </div>
  <div nz-col nzSpan="8">
    <app-mock-warning-type></app-mock-warning-type>
  </div>
  <div nz-col nzSpan="24">
    <app-mock-warning-line></app-mock-warning-line>
  </div>
</div>
```

**Comment by wzl281158150** [comment]
在我这里的显示效果wrapperElement与Canvas应该是等宽的
![tooltip](https://user-images.githubusercontent.com/22830541/78738082-835fed00-7983-11ea-93fc-0a36c03bdf91.gif)

**Comment by AkatQuas** [comment]
> 在我这里的显示效果wrapperElement与Canvas应该是等宽的
> ![tooltip](https://user-images.githubusercontent.com/22830541/78738082-835fed00-7983-11ea-93fc-0a36c03bdf91.gif)

你这个挺好的，在我这里，canvas 是原始包裹div的大小，但是第二层的 wrapperElement 它就会大很多，而且每一次 resize  事件的发生，都会将其拉长。

**Comment by simaQ** [comment]
升级到最新版本吧
