### ISSUE TITLE
IE下报错不支持includes方法

### ISSUE THREAD

**Issue by 546200350** [antvis/G2#2282]
官方教程 浏览器引入<script src="https://gw.alipayobjects.com/os/lib/antv/g2/4.0.4/dist/g2.min.js"></script>
在IE 11下运行报错 
![image](https://user-images.githubusercontent.com/16091917/78656282-bc537f80-78f9-11ea-9797-0ae39bb2b577.png)

**Comment by hustcc** [comment]
@546200350 自己在项目中引入一下 polyfill 包。

**Comment by 546200350** [comment]
@hustcc 非工程化项目静态页面那就还得自己打包么

**Comment by hustcc** [comment]
可以用 script 标签引入 polyfill 的，看上面回复的地址，里面有引入但是。
