### ISSUE TITLE
4.0.4版本在IE下不显示

### ISSUE THREAD

**Issue by 546200350** [antvis/G2#2285]
已引入polyfill
<script src="https://cdn.bootcss.com/babel-polyfill/7.8.7/polyfill.js"></script>
在4.0.4版本，IE11正常，IE10和IE9空白，有tooltip显示。控制台未报错
3.5.11版本是OK的
![image](https://user-images.githubusercontent.com/16091917/78739404-c53e6280-7986-11ea-8ccf-37073a7e8920.png)
代码：
http://jsrun.net/LGfKp/edit

发现SVG模式可以的

**Comment by simaQ** [comment]
是所有图表还是单个图？如果是单个图，给一下复现代码

**Comment by 546200350** [comment]
@simaQ http://jsrun.net/LGfKp/edit

**Comment by 546200350** [comment]
@simaQ Help

**Comment by hustcc** [comment]
@dengfuping G svg 是否测试 IE 上的表现，求验证。

**Comment by hustcc** [comment]
ref https://github.com/antvis/G2/issues/3186
