### ISSUE TITLE
两条直线使用同一X轴时，直线起始位置不同。

### ISSUE THREAD

**Issue by Sneaken** [antvis/G2#2288]
G2 Version: 4.0.4
Platform: Chrome  81.0.4044.92（正式版本）（64 位）
CodePen Link: https://codepen.io/sneaken/pen/mdebmxm
1. x轴坐标相同时，两条直线起始位置不同。
2. 同一x轴坐标下，两条直线的y轴数据不在一条垂直线上

G2 Version: 4.0.4
Platform: 360极速浏览器 9.5.0.138 内核版本63.0.3239.132
CodePen Link: https://codepen.io/sneaken/pen/mdebmxm
1. yesterday数据 发生错位。 
2. 360极速浏览器 更新到最新版时 无数据错位发生

**Comment by simaQ** [comment]
设置下 range 属性吧

```ts
chart.scale({
  yesterday: {
    sync: "value",
    range: [0, 1]
  },
  today: {
    sync: "value",
    range: [0, 1]
  },
  value: {
    nice: true
  }
});
```
