### ISSUE TITLE
npm install 失败

### ISSUE THREAD

**Issue by OPY-bbt** [antvis/g2#229]
* **g2 v3.0.0**:
* **node v9.2.0**:

###### 卡在此处
> electron@1.6.15 postinstall /Users/zy/Desktop/modules/g2/node_modules/electron
> node install.js

######  退出运行 demos
> 提示：Electron failed to install correctly, please delete node_modules/electron and try installing again

**Comment by leungwensen** [comment]
这个 post install 的脚本做的事情是 下载 electron app。这个 app 是 [github release](https://github.com/electron/electron/releases) 里的，下载不了的话可以尝试开一下 vpn ？或者可以尝试用 cnpm 源（ `npm install @antv/g2 --save  --registry=https://registry.npm.taobao.org` ）

**Comment by OPY-bbt** [comment]
![image](https://user-images.githubusercontent.com/16717283/33420369-43416004-d5e9-11e7-9625-7414f949b9e5.png) 原因是速度太慢。。

**Comment by afc163** [comment]
用 `cnpm install` 就解决了。

**Comment by OPY-bbt** [comment]
用的就是cnpm。。。 最近公司网不好
