### ISSUE TITLE
图表留白问题，源码如下，我new Chart()里，加了padding，但是图例会和内容重叠

### ISSUE THREAD

**Issue by TwoPens** [antvis/G2#2291]
import { Chart } from '@antv/g2';

const data = [
  { time: '03-19', type: '101-1000', value: 32000 },
  { time: '03-19', type: '31-100', value: 30000 },
  { time: '03-19', type: '11-30', value: 27000 },
  { time: '03-19', type: '1-10', value: 24000 },
  { time: '03-20', type: '101-1000', value: 35000 },
  { time: '03-20', type: '31-100', value: 32000 },
  { time: '03-20', type: '11-30', value: 30000 },
  { time: '03-20', type: '1-10', value: 27000 },
  { time: '03-21', type: '101-1000', value: 39000 },
  { time: '03-21', type: '31-100', value: 37000 },
  { time: '03-21', type: '11-30', value: 34000 },
  { time: '03-21', type: '1-10', value: 30000 },
  { time: '03-22', type: '101-1000', value: 44000 },
  { time: '03-22', type: '31-100', value: 42000 },
  { time: '03-22', type: '11-30', value: 38000 },
  { time: '03-22', type: '1-10', value: 34000 },
  { time: '03-23', type: '101-1000', value: 47000 },
  { time: '03-23', type: '31-100', value: 44000 },
  { time: '03-23', type: '11-30', value: 40000 },
  { time: '03-23', type: '1-10', value: 36000 },
  { time: '03-24', type: '101-1000', value: 48000 },
  { time: '03-24', type: '31-100', value: 46000 },
  { time: '03-24', type: '11-30', value: 42000 },
  { time: '03-24', type: '1-10', value: 38000 },
  { time: '03-25', type: '101-1000', value: 50000 },
  { time: '03-25', type: '31-100', value: 48000 },
  { time: '03-25', type: '11-30', value: 44000 },
  { time: '03-25', type: '1-10', value: 38000 }
];

const chart = new Chart({
  container: 'container',
  autoFit: true,
  height: 500,
  padding: 10 // 我需要留白，不然有些数据看不到
});
chart.data(data);
chart.scale('value', {
  alias: '金额(元)'
});
chart.axis('time', {
  tickLine: null,
});

chart.axis('value', {
  label: {
    formatter: text => {
      return text.replace(/(\d)(?=(?:\d{3})+$)/g, '$1,');
    }
  },
  title: {
    offset: 80,
    style: {
      fill: '#aaaaaa'
    },
  }
});
chart.legend({
  position: 'right',
});

chart.tooltip({
  shared: true,
  showMarkers: false,
});
chart.interaction('active-region');

chart
  .interval()
  .adjust('stack')
  .position('time*value')
  .color('type', ['#40a9ff', '#1890ff', '#096dd9', '#0050b3']);

chart.render();

**Comment by TwoPens** [comment]
图表示例里的代码，我只在new Chart(）中添加了 padding。
我的目的，就是给图表留白，图例调整到右侧，图表会自适应缩放。
问题：添加padding留白之后，图表不会自适应缩放了。

**Comment by TwoPens** [comment]
![微信截图_20200408172720](https://user-images.githubusercontent.com/62087166/78768232-3baa8700-79be-11ea-906b-ec85790a3e3a.png)
@simaQ

**Comment by simaQ** [comment]
这是因为 padding 加少了，加大一点就好了

**Comment by TwoPens** [comment]
> 这是因为 padding 加少了，加大一点就好了

我可以加到100+，如果图例名称过长，还是会撑开。而且设置了padding，右侧不显示图例就很空

**Comment by hustcc** [comment]
padding = 'auto' 不行吗？@TwoPens
