### ISSUE TITLE
自定义tooltip，itemTpl中设置{index}不生效

### ISSUE THREAD

**Issue by luhaifeng666** [antvis/G2#2293]
* **G2 Version**: 4.0.4
* **Platform**: 81.0.4044.92（正式版本） （64 位）
* **CodePen Link**: https://codepen.io/luhaifeng666/pen/pojoNZO

如题。

**Comment by simaQ** [comment]
你需要在 Geometry 的 tooltip 方法中配置返回 index 属性值，参考 https://g2.antv.vision/zh/docs/manual/tutorial/tooltip#%E5%86%85%E5%AE%B9%E9%85%8D%E7%BD%AE
