### ISSUE TITLE
饼状图在label中设置layout有bug，该怎么解决饼状图文本重叠问题

### ISSUE THREAD

**Issue by houwenli123** [antvis/G2#2294]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
layout: 'overlap' 并不适用于饼图，你可以使用自定义 label 布局函数来解决重叠问题，https://g2.antv.vision/zh/docs/manual/developer/registerlabel#%E8%87%AA%E5%AE%9A%E4%B9%89-label-%E5%B8%83%E5%B1%80%E5%87%BD%E6%95%B0
