### ISSUE TITLE
运行的时候为什么报错

### ISSUE THREAD

**Issue by bigGoodMan** [antvis/G2#2299]
* **G2 Version**:
4.0.4
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/21271880/79044526-335d8080-7c38-11ea-87ac-410989311cb9.png)
为什么运行的时候出现这个问题

**Comment by hustcc** [comment]
ref #2317, 这里先关闭了，感谢反馈。
