### ISSUE TITLE
data数据格式问题{time: "08-10", expValue: "20", realValue: "19"}

### ISSUE THREAD

**Issue by ymqq** [antvis/g2#23]
折线图，如何展示{time: "08-10", expValue: "20", realValue: "19"}这样格式的数据。

难道要处理成：[{time: "08-10", value: "20"}, {time: "08-10", value: "19"}]这样的数据？

看着就不是很合理的数据整合。

**Comment by simaQ** [comment]
https://g2.alipay.com/tutorial/frame.html#合并多列-frame-combincolumns

针对这种情况，我们提供了  Frame.combinColumns 方法，通过

```
      var  data = [{time: "08-10", expValue: "20", realValue: "19"}];
      var Frame = G2.Frame;
      var frame = new Frame(data);
      frame =   Frame.combinColumns(frame, ['expValue', 'realValue'], 'value', 'type');
      console.log(frame.toJSON());
```
就可以把你的数据处理成：

![image](https://cloud.githubusercontent.com/assets/6628666/19991596/9b8e4a8a-a271-11e6-9373-089bda583834.png)


然后 `chart.line().position('time*value').color('type')`
