### ISSUE TITLE
G2 3.0的滑动块编写的html在PC端浏览器可以自由滑动  把html加载到安卓端的浏览器时，滑动块无法自由滑动

### ISSUE THREAD

**Issue by xujie0686** [antvis/g2#230]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
当初在写这个插件的时候并没有考虑到移动端的浏览器，你们在用 G2 绘制移动端的图表么？

**Comment by xujie0686** [comment]
我们做的项目是希望图表可以在移动端和PC端共同显示

**Comment by dxq613** [comment]
建议使用 F2
