### ISSUE TITLE
Site: Switch language doesnt work

### ISSUE THREAD

**Issue by sspilleman** [antvis/G2#2300]
Hi.

I click the menu item on your site to switch from chinese to english, it doesn't work, only the menu changes it looks like.

I attached a screenshot. This is what I see. Only the menu bar is different, the left aside and main area's are still very much unreadable :-(

Kind Regards,

Sander Spilleman

![image](https://user-images.githubusercontent.com/592486/79069872-f940bd00-7cd1-11ea-9e13-1c3d88b0ac77.png)

**Comment by simaQ** [comment]
sorry, english documents are under construction.

**Comment by sspilleman** [comment]
Ok, clear. I really like your library, keep up the good work! I hope this gets resolved soon as it will definitely make it easier to find some "hidden features".

**Comment by hustcc** [comment]
ref #2353,  close here. ^_^
