### ISSUE TITLE
scale有什么方式可以不对YYYY-MM-DD这种格式的数据进行特殊处理

### ISSUE THREAD

**Issue by camille-yu** [antvis/G2#2303]
changeData时change后的数据和之前的数据格式不一致，渲染时会报错（或者可不可以恢复成默认type）；同一组数据不完全是YYYY-MM-DD会报错，之前说是formate处理，可不可以给个demo

**Comment by simaQ** [comment]
G2 会根据字段的第一个数据进行类型推导，如果同一组数据中存在不同格式的数据的话，建议手动指定要 type
