### ISSUE TITLE
坐标轴label过长时，是否可以换行或...显示

### ISSUE THREAD

**Issue by camille-yu** [antvis/G2#2304]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
没有现成的，但是有机制提供，使用自定义 label layout 布局函数： https://g2.antv.vision/zh/docs/manual/developer/registerlabel#%E8%87%AA%E5%AE%9A%E4%B9%89-label-%E5%B8%83%E5%B1%80%E5%87%BD%E6%95%B0

**Comment by ZengZhenfei** [comment]
比如饼图，当container的宽高固定的时候，如果label过长，可以增加自动换行的机制吗？真的很需要！

**Comment by ayuechuan** [comment]
全是问题  我感觉这插件

**Comment by ayuechuan** [comment]
自定义lenged也不支持useHtml    表头也没得   啥也没有    还不如几年不更新的echarts
