### ISSUE TITLE
无法配置 legend 的初始化状态

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#231]
比如离散的 legend，内容有多个，无法指定 legend 初始状态为 某些是选中状态，某些是非选中状态。

**Comment by simaQ** [comment]
参考这个链接：
https://antv.alipay.com/zh-cn/g2/3.x/tutorial/fqas.html#_如何设置图例项的初始状态

**Comment by weepy3641** [comment]
filter 是可以做到。 用户成本稍高。
