### ISSUE TITLE
On Rendered / done event

### ISSUE THREAD

**Issue by przemo098** [antvis/G2#2310]
Hello guys I'm trying to capture base64Image from canvas, like this:
```
   chart.render();
   const base64Url = document.getElementsByTagName('canvas')[0].toDataURL();
```
It returns black value... (it seems that it's still not rendered)

However this value is valid after some time after calling:
```
   chart.render();
   setTimeout(() => {
      const base64Url = document.getElementsByTagName('canvas')[0].toDataURL();
    }, 1500);
```
Is there any hook / callback / event when the chart is rendered ?
I've found few events in documentation however I stuck..

Also it would be great to add functionality to render exactly to base64 skiping the canvas rendring
( I saw that you guys got SVG / Canvas renderers)

* **G2 Version**: 4.06
* **Platform**: Chrome

I saw simillar issue:
https://github.com/antvis/G2/issues/1141
It seems that something is wrong...

**Comment by hustcc** [comment]
G 4.0 is the dependence of G2 4.0, in new G version, add 1 cfg:

 - autoDraw: default is true

When `autoDraw = true`, the render is async. So you can solve by 2 ways:

1. set autoDraw = false
2. call toDataURL after 16ms

----

@dxq613 @dengfuping  Mabbe we need a emit event when async render done.
