### ISSUE TITLE
X轴的label如何显示不一样的style?

### ISSUE THREAD

**Issue by baiyidjp** [antvis/G2#2313]
我需要对x轴的label做一些区别，但是不知道怎设置不一样的颜色或者大小
![image](https://user-images.githubusercontent.com/12672573/79210268-25497300-7e77-11ea-81d5-ee49c8f2dceb.png)

**Comment by baiyidjp** [comment]
我看demo好像只可以使用 chart.axis() 这个方法设置，但是这个方法好像是整体设置的

**Comment by simaQ** [comment]
这个需要 label 支持回调，关联 #2230

**Comment by baiyidjp** [comment]
看不太懂啊。是要使用另外一个库吗？ 我是业余前端。。。

**Comment by hustcc** [comment]
请关注 #2230，最近我会加上，并告知实现方式，这里先关闭掉了。^_^

**Comment by RephoneYin** [comment]
期待你们加上， 加上的时候， 一定要允许添加支持图片等功能呀。
