### ISSUE TITLE
4.0.6  element-active bug 

### ISSUE THREAD

**Issue by Leannechn** [antvis/G2#2314]
version 4.0.6

4.0.5 正常
https://antv-g2.gitee.io/zh/examples/pie/basic

4.0.6 鼠标在扇形区域移动可复现问题。active不消失。
https://g2.antv.vision/zh/examples/pie/basic#labelline

**Comment by simaQ** [comment]
已知 BUG，关联 #2307。是因为底层绘图引擎 G 的 mouseleave 事件问题，正在修复
