### ISSUE TITLE
雷达图如何实现下图tooltip效果?

### ISSUE THREAD

**Issue by meguoe** [antvis/G2#2318]
下图是百度的雷达图，想在G2上实现类似效果，请大神不吝赐教！
<img width="626" alt="6C4470CA-F100-4E56-B359-33F180CA2CEA" src="https://user-images.githubusercontent.com/45955794/79304499-179df700-7f24-11ea-8e6c-3963d4a3d993.png">

**Comment by simaQ** [comment]
样式吗？可以通过 `chart.tooltip({ domStyles: {}})` 属性配置
