### ISSUE TITLE
G2 3.0 设置padding,无论大小，x轴 y轴都会被隐藏？

### ISSUE THREAD

**Issue by heke1994** [antvis/g2#232]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by dxq613** [comment]
x轴 y轴不会隐藏，只是 默认的 title 隐藏了吧？

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/tutorial/axes.html#_%E5%9D%90%E6%A0%87%E8%BD%B4%E6%A0%87%E9%A2%98-title
