### ISSUE TITLE
分面图表在数据经过 transform 之后产生的字段的无法映射到 color

### ISSUE THREAD

**Issue by kagawagao** [antvis/G2#2320]
* **G2 Version**:  `v4.0.6` 与 `v3.5.13`
* **Platform**: Chrome Canary 84.0.4114.0
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/6930280/79324244-e3393380-7f41-11ea-9e98-6c69bcb3f258.png)

* **CodePen Link**:
[![Edit autumn-sun-idifm](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/autumn-sun-idifm?fontsize=14&hidenavigation=1&theme=dark)

**Comment by kagawagao** [comment]
在示例中，将 `clarity` 重命名为 `type` 之后，`color` 无效

除 `rename` 之外，诸如 `fold` 之类产生的新的字段均无法实现 `color` 映射

**Comment by simaQ** [comment]
重命名后，`type` 需要同 `clarity` 一样同步下：

```ts
chart.scale({
    carat: {
      sync: true
    },
    price: {
      sync: true,
      tickCount: 3,
      nice: true
    },
    clarity: {
      sync: true
    },
    type: {
      sync: true
    }
  });
```
