### ISSUE TITLE
iOS angle render bug

### ISSUE THREAD

**Issue by matheuslbenachio** [antvis/G2#2321]
* **G2 Version**: 4.0.6
* **Platform**: iOS Mobile
* **Mini Showcase(like screenshots)**: 

### Expected:
![image](https://user-images.githubusercontent.com/36608338/79365023-79f4f880-7f20-11ea-966c-f10bbe56559c.png)

### Result:
![image](https://user-images.githubusercontent.com/36608338/79366852-42d41680-7f23-11ea-88c4-f4192dc3ede0.png)

* **CodePen Link**: https://codepen.io/matheuslbenachio/pen/RwWrVvO

In Iphone in some cases the start angle and end angle bug out, and a little 'spike' appears in the start of the angle.

This only happen if you specify 'startAngle' and 'endAngle', if the chart is a full circle this doesn't happen.

It only happens in chrome and safari iOS, not android.

**Comment by hustcc** [comment]
fixed.
