### ISSUE TITLE
桑基图的值为负值，label显示不全是什么问题？如何对图表的节点进行排序？

### ISSUE THREAD

**Issue by jing1810** [antvis/G2#2323]
let nodesArr =[{name: "2013年", indexLevel: 0},
 {name: "2013年1季度", indexLevel: 1},
 {name: "2013年2季度", indexLevel: 1},
 {name: "2013年3季度", indexLevel: 1},
 {name: "2013年4季度", indexLevel: 1},
 {name: "2013年01月", indexLevel: 2},
 {name: "2013年02月", indexLevel: 2},
 {name: "2013年03月", indexLevel: 2},
 {name: "2013年04月", indexLevel: 2},
 {name: "2013年05月", indexLevel: 2},
 {name: "2013年06月", indexLevel: 2},
 {name: "2013年07月", indexLevel: 2},
 {name: "2013年08月", indexLevel: 2},
 {name: "2013年09月", indexLevel: 2},
 {name: "2013年10月", indexLevel: 2},
 {name: "2013年11月", indexLevel: 2},
 {name: "2013年12月", indexLevel: 2}];
let linksCopy =[{source: 0, target: 1, value: -8749.87},
            {source: 1, target: 5, value: -5804.59},
            {source: 1, target: 6, value: -1410.48},
            {source: 1, target: 7, value: -1534.8},
            {source: 0, target: 2, value: -4273.7},
            {source: 2, target: 8, value: -1753.9},
            {source: 2, target: 9, value: -1436.37},
            {source: 2, target: 10, value: -1083.43},
            {source: 0, target: 3, value: -2172.58},
            {source: 3, target: 11, value: -838.85},
            {source: 3, target: 12, value: -949.35},
            {source: 3, target: 13, value: -384.38},
            {source: 0, target: 4, value: -3802.81},
            {source: 4, target: 14, value: -836.82},
            {source: 4, target: 15, value: -1427},
            {source: 4, target: 16, value: -1538.99}];
 let data = {
      nodes:[],
      links:[]
    };
    data.nodes = nodesArr ;
    data.links = linksCopy;
  const ds = new DataSet();
    const dv = ds.createView().source(data, {
      type: 'graph',
      edges: d => d.links
    });
    dv.transform({
      type: 'diagram.sankey'
    });
    const chart = new G2.Chart({
      container: 'container',
      forceFit: true,
      height: 500,
      padding: [ 40, 80 ]
    });
  chart.legend(false);
    chart.tooltip({
      showTitle: false
    });
    chart.axis(false);
    chart.scale({
      x: { sync: true },
      y: { sync: true }
    });

    // edge view
    const edgeView = chart.view();
    edgeView.source(dv.edges);
    edgeView.edge()
      .position('x*y')
      .shape('arc')
      .color('#bbb')
      .opacity(0.6)
      .tooltip('target*source*value', (target, source, value) => {
        return {
          name: source.name + ' to ' + target.name + '</span>',
          value
        };
      });

    // node view
    const nodeView = chart.view();
    nodeView.source(dv.nodes);
    nodeView.polygon()
      .position('x*y') // nodes数据的x、y由layout方法计算得出
      .color('name')
      .label('name', {
        textStyle: {
          fill: '#545454',
          textAlign: 'start'
        },
        offset: 0,
        formatter: val => {
          return '  ' + val;
        }
      })
      .tooltip(false)
      .style({
        stroke: '#ccc'
      });
    chart.render();

**Comment by simaQ** [comment]
排序使用 sort 属性， https://g2.antv.vision/en/docs/manual/dataset/transform#diagramsankey-%E6%A1%91%E5%9F%BA%E5%9B%BE

**Comment by jing1810** [comment]
那桑基图的值为负值，label显示不全是什么问题？
