### ISSUE TITLE
桑基图的edge的shape形状宽直线样式怎么做？

### ISSUE THREAD

**Issue by jing1810** [antvis/G2#2324]
网址：https://g2-v3.antv.vision/zh/examples/relation/relation#sankey

.shape('arc')，这个是曲线，shape（‘line')是直线，但不是宽直线，我想要的是类似于qucik bi 上的直线样式。

**Comment by simaQ** [comment]
可以参考下 arc 的实现，自定义一个宽直线: https://github.com/antvis/G2/blob/master/src/geometry/shape/edge/arc.ts
