### ISSUE TITLE
g2 2.0 有滚动图例吗

### ISSUE THREAD

**Issue by yangguangmingman** [antvis/g2#233]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by yangguangmingman** [comment]
当图例过长时且不换行时，滚动图例是个不错的解决办法

**Comment by leungwensen** [comment]
https://codepen.io/leungwensen/pen/yPGbYB?editors=0110
