### ISSUE TITLE
饼图显示了直角坐标系 y轴 tick 标签

### ISSUE THREAD

**Issue by kakusx** [antvis/G2#2333]
* **G2 Version**: 4.0.7
* **Platform**:Chrome 81.0.4044.113 / MacOS 10.15.4
* **Mini Showcase(like screenshots)**:
![UTOOLS1587298413114.png](https://user-gold-cdn.xitu.io/2020/4/19/171925babe85b0f5?w=497&h=377&f=png&s=26059)

* **复现环境**:
https://kakus.cn/VisualApi/
进页面点击获取数据，选择饼图，state * positive，绘制图形
（数据太多可以添加过滤条件：positive > 20000，不影响问题复现）
然后选择柱状图，state * positive，绘制图形
然后，选择饼图，绘制图形，此时饼图上就会出现tick标签

页面代码处理逻辑：
绘图都在同一个div，每次重绘时先清空div
$("div").empty();

**Comment by simaQ** [comment]
你是不是在柱状图的代码中，配置了数值对应的坐标轴？你可以在饼图的代码里面，加上 `chart.axis(false)` 强制关闭下，默认我们是关闭的，应该是图表类型切换过程中，配置项窜了。
