### ISSUE TITLE
圆角柱状图改变v-coord direction后，图表不显示问题

### ISSUE THREAD

**Issue by lufuly88** [antvis/G2#2335]
<template>
  <div>
    <v-chart :forceFit="true" :height="400" :data="data" :padding="[0, 90, 20, 52]" :scale="scale">
      <v-tooltip/>
      <v-axis dataKey="city" :label="label" :tickLine="tickLine"/>
      <v-axis dataKey="value" :label="label" :title="title"/>
      <v-legend position='right-bottom'></v-legend>
      <v-coord direction='LB' type='rect'/>//想做成横向圆角，加了这行图形显示不出来
      <v-interval position="city*value" :opacity="1" color="type" shape="borderRadius"/>
    </v-chart>
  </div>
</template>

<script>
import { registerShape } from 'viser-vue';

registerShape('interval', 'borderRadius', {
  draw(cfg, container) {console.log(cfg)
    const points = cfg.points;
    let path = [];
    path.push(['M', points[0].x, points[0].y]);
    path.push(['L', points[1].x, points[1].y]);
    path.push(['L', points[2].x, points[2].y]);
    path.push(['L', points[3].x, points[3].y]);
    path.push('Z');
    path = this.parsePath(path); // 将 0 - 1 转化为画布坐标
    return container.addShape('rect', {
      attrs: {
        x: path[1][1], // 矩形起始点为左上角
        y: path[1][2],
        width: path[2][1] - path[1][1],
        height: path[0][2] - path[1][2],
        fill: cfg.color,
        radius: (path[2][1] - path[1][1]) / 2,
      }
    });
  }
});

const data = [{
  city: '石家庄',
  type: '水果',
  value: 14500
},];

const scale = [{
  dataKey: 'value',
  max: 20000,
  min: 0.0,
  nice: false,
  alias: '销售额（万）'
}];

const label = {
  textStyle: {
    fill: '#aaaaaa'
  }
}

const tickLine = {
  alignWithLabel: false,
  length: 0
}

const title = {
  offset: 30,
  textStyle: {
    fontSize: 14,
    fontWeight: 300
  }
}

const adjust = [{
  type: 'dodge',
  marginRatio: 0.3
}]

  export default {
    data() {
      return {
        data,
        scale,
        label,
        tickLine,
        title,
        adjust
      };
    }
  };
</script>

**Comment by hustcc** [comment]
请排版一下 issue 的内容被 ^_^!! 最好能直接提供一个在线的 codepen 直接运行 demo。
