### ISSUE TITLE
[REQUEST] Add src/**/*.ts to "files" in package.json for source map support

### ISSUE THREAD

**Issue by martijnthe** [antvis/G2#2338]
* **G2 Version**: 4.0.4
* **Platform**: any
* **Mini Showcase(like screenshots)**: N/A
* **CodePen Link**: N/A

Sourcemap (`.map`) files are included in the published npm package, but they refer to `../src/*.ts`. When debugging a project that includes G2 from npm, the sourcemaps do not work because the `.ts` files are not included in the npm package.

To fix this, the `src` folder would need to be added to `"files"` in each `package.json` file.

Would you be open to change this?

**Comment by zqlu** [comment]
Try to inline sources to sourceMap files. #2348
