### ISSUE TITLE
气泡图横坐标及label再次绘制不出现的情况

### ISSUE THREAD

**Issue by ZhengHuang-20** [antvis/G2#2342]
* **G2 Version**:4.0.5
* **Platform**:mac && vue
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

https://antv-g2.gitee.io/zh/examples/point/bubble#bubble-image
想问下这个横坐标如何绘制出来的，我在代码中出现了第一次加载绘制成功第二次绘制横坐标消失，第三次再出现的情况，所以想搞明白这个横坐标是如何绘制出来的

**Comment by hustcc** [comment]
没有看懂描述的问题，求详细描述~
