### ISSUE TITLE
气泡图size映射，但数据为[] 的时候出现计算报错。

### ISSUE THREAD

**Issue by Leannechn** [antvis/G2#2345]
version：4.0.7

复现：修改demo中的 data 为空数组即可复现。
https://g2.antv.vision/zh/examples/point/bubble

**Comment by hustcc** [comment]
@dxq613 scale 中的 pretty 遇到问题，看看能否从 scale 底层直接容错掉！

**Comment by hustcc** [comment]
已经解决，issue 关闭。
