### ISSUE TITLE
[4.x]饼图密集区域Label布局错乱

### ISSUE THREAD

**Issue by iNahooNya** [antvis/G2#2347]
* **G2 Version**: 4.0.7
* **Platform**: PC Chrome 80

官网Demo链接改个数就能复现
https://g2.antv.vision/zh/examples/pie/basic
```javascript
const data = [
  { item: '事例一', count: 400, percent: 0.9 },
  { item: '事例二', count: 21, percent: 0.21 },
  { item: '事例三', count: 17, percent: 0.17 },
  { item: '事例四', count: 1, percent: 0.01 },
  { item: '事例五', count: 1, percent: 0.01 },
];
```
![image](https://user-images.githubusercontent.com/12727349/79900031-2f074380-8440-11ea-935e-65c5aae8de93.png)

---
说来有趣，你看延伸出去的线条似乎是没问题的，但是文字的位置有问题
是不是算线条时的偏移量忘了给文本加上？

---
期望：足以容纳时可以正确展示
无法容纳时舍弃部分点的展示(同v3.x)

**Comment by 0Yinchen0** [comment]
有解了吗，我也遇到这个问题

**Comment by hustcc** [comment]
@simaQ @Me-Momo 是否需要将之前的拼图方案沉淀一套到 G2 来。

**Comment by Me-Momo** [comment]
有没有自定义注册的demo 看看成本

**Comment by JLoveI** [comment]
同求 
![image](https://user-images.githubusercontent.com/21192807/80578397-f87e8980-8a3a-11ea-97b8-efddd5e1ed96.png)

**Comment by 0Yinchen0** [comment]
> 同求
> ![image](https://user-images.githubusercontent.com/21192807/80578397-f87e8980-8a3a-11ea-97b8-efddd5e1ed96.png)

你可以用G2 Plot试试，那个不重叠

**Comment by hustcc** [comment]
> 有没有自定义注册的demo 看看成本

直接看内置的 label 写法就可以了。名字叫 overlap …

**Comment by simaQ** [comment]
> @simaQ @Me-Momo 是否需要将之前的拼图方案沉淀一套到 G2 来。

有必要，之前就提过这个，将一些 g2plot 的 label 方案沉淀到 G2 来。

**Comment by Me-Momo** [comment]
> > 有没有自定义注册的demo 看看成本
> 
> 直接看内置的 label 写法就可以了。名字叫 overlap …

👌这周安排上

**Comment by Me-Momo** [comment]
先用以下方式，对重叠的标签进行隐藏
```
const chart = new Chart({
  container: 'container',
  autoFit: true,
  height: 500,
  // 关闭局部渲染
  localRefresh: false,
});

chart.label('xxx', {
    layout: {
        type: 'fixed-overlap'
   }
})
```
