### ISSUE TITLE
在view层中设置tooltip不生效

### ISSUE THREAD

**Issue by yuanyayi** [antvis/G2#2349]
官方示例：https://antv-g2.gitee.io/zh/examples/gallery/pie
![image](https://user-images.githubusercontent.com/19421507/79970536-a632eb00-84c5-11ea-85fa-feea958e61e9.png)
将`chart.tooltip({ showMarkers: false })`删除，改写到view层，可以看到饼图上依然有tooltip的Marker小圆点标记。设置未生效。
另，尝试在view中直接设置为`options: { tooltip: false }`是可以生效的。

**Comment by simaQ** [comment]
这个问题比较复杂，因为我们将 tooltip 的交互行为是挂载在 Chart 实例下的，所以内部只读取到了 chart 上的 tooltip 配置，你可以通过下面的方案临时解决下：

1. 首先移除 chart 实例上的 tooltip 交互行为

```ts
chart.removeInteraction('tooltip')
```

2. 在 view 上调用 tooltip 交互行为，同时进行 tooltip 配置

```ts
view.tooltip({
  showMarkers: false
});

view.interaction('tooltip');
```

**Comment by yuanyayi** [comment]
解决方案可行，非常感谢～
