### ISSUE TITLE
hideMarkders 设置无效

### ISSUE THREAD

**Issue by cipchk** [antvis/g2#235]
* **CodePen Link**: https://codepen.io/cipchk/pen/YEBavM

`hideMarkders` 设置无效。

> 对于 line、area、path 这三种几何图形，我们在渲染 tooltip 时会自动渲染 `tooltipMarker` ，通过声明该属性值为 `false` 来关闭 tooltipMarker。

**Comment by leungwensen** [comment]
多谢反馈！这部分逻辑有改过，我们更新一下

**Comment by simaQ** [comment]
![snip20171204_1](https://user-images.githubusercontent.com/6628666/33532313-957f8a02-d8d3-11e7-9afc-1cce9bf9c8b6.png)

您好，拼写错误 😄  `hideMarkers`

**Comment by leungwensen** [comment]
已更新文档： https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_tooltip

**Comment by cipchk** [comment]
我依然有疑问，不管是 `true` 亦或 `false`，都会显示。

jpg:

![tim 20171204112706](https://user-images.githubusercontent.com/2987467/33535039-2119df2e-d8e6-11e7-8d60-cf0f95e6885d.png)

难道属此不是指这里的吗？

**Comment by leungwensen** [comment]
你看一下文档？

「对于 line、area、path 这三种几何图形，我们在渲染 tooltip 时会自动渲染 tooltipMarker ![inline](https://gw.alipayobjects.com/zos/rmsportal/BlTPaZMgrTjZINmXExtm.png)，通过声明该属性值为 true 来关闭 tooltipMarker。」

如果需要定制 tooltip 容器样式，你可以参考一下文档接下来部分关于 HTML 定制的内容： https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_tooltip

**Comment by cipchk** [comment]
了解，谢谢

**Comment by AnonymousArthur** [comment]
@leungwensen 链接挂了，我发现搜索的结果链接都跳转到首页了，你们是不是改了路由。

**Comment by leungwensen** [comment]
@AnonymousArthur 文档迁移到语雀了  https://www.yuque.com/antv/g2-docs/api-chart#tooltip
