### ISSUE TITLE
Enable all strict type checking options in tsconfig.json

### ISSUE THREAD

**Issue by xiaoxiangmoe** [antvis/G2#2351]
Enable all strict type checking options.

https://www.typescriptlang.org/v2/en/tsconfig#strict

---

现在的很多类型报错都是因为库没有开启 strict 而用户开启了。比如： https://github.com/antvis/G2/issues/2317 ， https://github.com/antvis/G2/issues/2326 。 如果开启 strict，会让这类问题在开发中就暴露。如果需要开启，建议全部 antv 的库的 strict选项。

**Comment by hustcc** [comment]
@xiaoxiangmoe 可以，欣然接受，来给我们一个 pr 吧~
