### ISSUE TITLE
how to change the fillStyle and fillOpacity in Chart?

### ISSUE THREAD

**Issue by maestropu** [antvis/G2#2352]
`const chart = new G2.Chart({
        container: 'c1', // 指定图表容器 ID
        width: 600, // 指定图表宽度
        height: 300, // 指定图表高度
        background: {
        fillOpacity: 1,
        fillStyle: "#fff"}
      });`
![image](https://user-images.githubusercontent.com/24562371/80008192-fb88ef80-84f9-11ea-94f2-b5bbec78c99e.png)
I have set background in Chart init, but it didn't work.thank you.

**Comment by simaQ** [comment]
which version do you use? G2 4.0 do not support this feature, but you can set the background by changing the dom's css.
