### ISSUE TITLE
Tool tip 中 show事件 的context中 items 无法显示 柱图经过相同区域 分组后的数据  

### ISSUE THREAD

**Issue by embaobao** [antvis/G2#2354]
Tool tip 中 show 的context中 items 无法显示 柱图经过相同区域 分组后的数据  
建议 tooltip 的事件中给出可以显示的数据集合

**Comment by hustcc** [comment]
是指在堆叠图形中，显示一个 stack 的数据吗？

可以给一个实际的例子和截图，也可以方便其他遇到同类问题的同学看明白你的意思~~
