### ISSUE TITLE
G2@4.x 柱状图更改图表大小时，最大值对应的柱子不会自适应

### ISSUE THREAD

**Issue by BuggMaker** [antvis/G2#2356]
* **G2 Version**:4.x
* **Platform**: MaxOS
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/25820633/80080607-70087080-8584-11ea-9d7f-0e0fa270253f.png)

* **CodePen Link**: https://codesandbox.io/s/s4evs

当动态改变图表size的时候，最大值对应的柱子显示有问题，不会根据图表大小自适应。

![Kapture 2020-04-23 at 16 53 05](https://user-images.githubusercontent.com/25820633/80080370-1a33c880-8584-11ea-8eff-3623eccfaea2.gif)

**Comment by hustcc** [comment]
@simaQ 这个帮忙看看呗，感觉像是一个大问题。

**Comment by simaQ** [comment]
> @simaQ 这个帮忙看看呗，感觉像是一个大问题。

恩，是的大问题，已经定位到原因了，但是没这么快修复，节后第一周回去提交 PR
