### ISSUE TITLE
内网部署

### ISSUE THREAD

**Issue by zcolin** [antvis/G2#2357]
请问有4.0内网部署的站点文档么？

**Comment by simaQ** [comment]
4.0 的文档是对外的，没有内网一说~ 所有的文档都在 https://g2.antv.vision/ 站点下。

**Comment by hustcc** [comment]
@zcolin 可以 clone G2 代码，然后运行 npm run site:build 就可以打包为本地站点。但是建议使用我们的主页地址  https://g2.antv.vision/ 。
