### ISSUE TITLE
国际化问题

### ISSUE THREAD

**Issue by yangdengcheng** [antvis/G2#2362]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

请教一下如果在tooltip中使用了i18n对文案进行自定义，如何在切换语言的时候更新视图？

**Comment by hustcc** [comment]
@yangdengcheng  现在 tooltip 中应该没有需要写死的中文或者英文文案。想字段名这种你可以按照业务的国际化方式，重试绘制 chart即可。

```ts
chart.scale({ city: { alias: i18n('city'), ... } });

chart.render();
```

cc @dxq613
