### ISSUE TITLE
雷达图coordinate设置rotate，label无法跟随旋转

### ISSUE THREAD

**Issue by 530893915** [antvis/G2#2365]
* **G2 Version**:4.0.7
* **Platform**: react 15
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/38284163/80303155-fb7e3d80-87e0-11ea-8bd0-bc2054d4699c.png)
* **CodePen Link**:

雷达图coordinate设置rotate，label无法跟随旋转（见上方截图），没找到有任何相关的参数，请问有办法能实现吗

**Comment by simaQ** [comment]
这个是 circle 类型的坐标轴文本未旋转。

**Comment by 530893915** [comment]
> 这个是 circle 类型的坐标轴文本未旋转。

请问这个问题大概多久可以解决呢？时间长的话这边好和产品协商一下
