### ISSUE TITLE
饼图，饼图各数据都为0时，饼图会消失

### ISSUE THREAD

**Issue by akitsukiWong** [antvis/G2#2366]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
![image](https://user-images.githubusercontent.com/23179691/80304192-05a33a80-87e7-11ea-9a0f-5fb9422e274f.png)

页面上的标示都还存在，但是饼图消失了，页面上不好看，体验也不好，Echarts那边如果为0的话饼图还是会存在的，建议改善，或者告诉我解决方法

### What does the proposed API look like?
希望饼图各数据都为0时，页面上显示均分的饼图或者灰色的饼图

**Comment by hustcc** [comment]
这种情况下，期望效果是均分饼图吗？

有点像是特殊逻辑的感觉，业务中可以针对这种全 0 的场景，复写为全 1， 然后对于 tooltip ，label 的渲染，格式化显示为 0 即可。

**Comment by chuckWu1989** [comment]
Why this issue was been closed? I still have this problem in 2023
