### ISSUE TITLE
一个时间点展现多个柱图时，slider 滑动时同一个时间点对应的柱图不能同时消失或展现

### ISSUE THREAD

**Issue by qingranEvent** [antvis/G2#2367]
没有滑动时：
![image](https://user-images.githubusercontent.com/26160063/80309675-14024e00-8809-11ea-8235-964b658bbeb5.png)
滑动一点距离时：
![image](https://user-images.githubusercontent.com/26160063/80309696-38f6c100-8809-11ea-935c-1cfd2307cf6b.png)
期望的效果：三个柱子同时属于一个时间节点，应该随滑块滑动一起出现一起消失。

可否在 slider 的配置中支持自定义过滤方法
源码实现：
```
// 增加 x 轴的过滤器
this.view.filter(xScale.field, function (value, datum, idx) { return isBetween(idx, minIndex, maxIndex); });

```

已有的实现思路：将过滤掉的数据中的 X 轴对应的 field 字段组成一个数组 -- filteredFieldArr，在第一次过滤后的数据中进行二次过滤后再 render
`finalData = data.filter(item => !filteredFieldArr.includes(item[field]));
render(finalData)；
`

**Comment by hustcc** [comment]
@qingranEvent 

> 期望的效果：三个柱子同时属于一个时间节点，应该随滑块滑动一起出现一起消失。

这个期望是合理的，应该是需要一起隐藏和显示。我这边先看原因。

**Comment by hustcc** [comment]
我这边根据代码，大概估计原因是：

1. 你的数据中 x 日期字段，是一个秒粒度的数据，然后在图形渲染的时候，指定为 YYYY-MM-DD，然后绘制图形，使用日期粒度进行分组。
2. slider 这边每次变更，还是返回的秒粒度的数据进行过滤，导致一个分组中部分数据被过滤掉了
