### ISSUE TITLE
数据库支持？

### ISSUE THREAD

**Issue by LuckyXavier** [antvis/g2#237]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

支持或者未来会支持直接从数据库读取数据吗？

**Comment by leungwensen** [comment]
这是上层封装需要做的事情，G2 目前就能处理数据库表格式的数据，但数据库连接层不会纳入 G2 体系内。可能未来可以通过扩展 `connector` 的方式来做支持（[antv/data-set](https://github.com/antvis/data-set)）
