### ISSUE TITLE
g2如何实现尺寸自适应

### ISSUE THREAD

**Issue by sjxhgjxf** [antvis/G2#2370]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by hustcc** [comment]
在外部调用使用 ResizeObserver 兼容容器的大小，获取 width height，然后调用：

```ts
chart.changeSize(width, height);
```

可以参考：https://github.com/hustcc/echarts-for-react/blob/master/src/core.jsx#L90
