### ISSUE TITLE
饼图点击图例，隐藏最后一个的时候报错，然后无法正常显示

### ISSUE THREAD

**Issue by wxq851685279** [antvis/G2#2371]
![image](https://user-images.githubusercontent.com/29041799/80355697-fab1de00-88aa-11ea-995b-c62425544f93.png)
官方示例 https://antv-g2.gitee.io/zh/examples/gallery/pie#pie3
![image](https://user-images.githubusercontent.com/29041799/80355895-3cdb1f80-88ab-11ea-9354-84a111c6d447.png)
![image](https://user-images.githubusercontent.com/29041799/80356191-ad823c00-88ab-11ea-9fb0-3aed9331f4a4.png)

**Comment by BlueBuluBulu** [comment]
这个问题修复了吗
