### ISSUE TITLE
4.x 版本，当图例过多时，如何给图例增加滚动条啊

### ISSUE THREAD

**Issue by sea-robbers** [antvis/G2#2372]
3.x 版本可以自定义图例，通过 useHtml api配置，而 **4.x** 版本后，取消了这个api，那当图例过多时，4.x如何给**图例增加滚动条**啊

**Comment by paleface001** [comment]
4.x可以给图例设置翻页，flipPage: true

**Comment by sea-robbers** [comment]
嗯呢，看到这个API了，但为了符合产品的需求需要给图例增加滚动条，目前 4.0.7 可以实现吗

**Comment by paleface001** [comment]
暂时没有这个功能呢

**Comment by sea-robbers** [comment]
后面的版本，会考虑吗，不仅有内置的翻页，也可以有滚动条，或者类似于3.x 版本的 useHtml 这种API

**Comment by simaQ** [comment]
目前不考虑提供，可以尝试自己通过 html 实现。

**Comment by zhouyu1993** [comment]
flipPage: true

分页按钮的样式怎么修改

**Comment by Alisa0026** [comment]
> 目前不考虑提供，可以尝试自己通过 html 实现。

flipPage: true

你好，分页按钮箭头的样式怎么修改

**Comment by hustcc** [comment]
> > 目前不考虑提供，可以尝试自己通过 html 实现。
> 
> flipPage: true
> 
> 你好，分页按钮箭头的样式怎么修改

目前暂时还不能修改~

**Comment by FourLeafClover** [comment]
useHtml API挺好的。为什么要去掉呢。是因为html不可控因素太多会影响到原有的charts渲染吗？
