### ISSUE TITLE
一个页面渲染20个图表时，页面崩溃

### ISSUE THREAD

**Issue by sunmmerOne** [antvis/G2#2373]
人群系统，跑的淘宝用户分析，通过api获取多图表数据，渲染时页面崩溃；

canvas实现应该是非操作dom的，不清楚具体原因，望解答。

**Comment by hustcc** [comment]
可以告知一下版本，图形数据量，是否有截图，是否有动画。

**Comment by simaQ** [comment]
长期未回复提供相关信息帮助排查，故先关闭
