### ISSUE TITLE
无法控制抖动轴偏差

### ISSUE THREAD

**Issue by Ajaay** [antvis/G2#2375]
* **G2 Version**: 3.5.15
* **Mini Showcase(like screenshots)**:

<img width="606" alt="Screen Shot 2020-04-28 at 09 14 15" src="https://user-images.githubusercontent.com/6141375/80465685-5c1d8f80-8933-11ea-911e-88ea6ac807af.png">

抱歉，我已经从英语翻译了。

当使用adjust =“ jitter”时，有没有一种方法可以控制向哪个轴添加方差？

理想情况下，我希望在X轴上添加方差，而在Y轴上添加零值或最小值，以使其尽可能接近真实值。

如您在屏幕快照中所见，数据值的方差越大，这个问题就越严重。数据值的差异越大，它绘制的Y轴值就越远。

我想这将需要更改@ antv / adjust包才能实现。

例如当值是0且最小比例值也是0时，这也是一个问题，该点通常在图形上绘制，如低于0。

任何帮助将不胜感激。

谢谢

**Comment by hustcc** [comment]
@dxq613 帮忙看下，这个是否在 jitter 中实现，或者是不是已经有了。

**Comment by simaQ** [comment]
目前不支持
