### ISSUE TITLE
autoFit (aka forceFit) does not work when parent dom element is resized

### ISSUE THREAD

**Issue by jer-sen** [antvis/G2#2376]
* **G2 Version**: 3.5.15

G2 uses `window.addEventListener('resize', this.onResize)` to detect a change in parent dom element's size. But if the element is resized without resizing the browser's window, the chart's size is not updated.
G2 should use a package such as `react-resize-detector` instead.

Also, it would be nice if we could configure a ratio (eg. 16/10) instead of a height when using `autoFit`.

**Comment by hustcc** [comment]
Almost all the chart library only supply API `changeSize` pr `resize` instead of auto resize with `ResizeObserver`.

The size listener should be added in your biz code.

**Comment by hustcc** [comment]
@simaQ 我建议要么直接去掉 resize + autoFit，要么这个 autoFit 是监听容器变化，而不是 resize 事件。

**Comment by jer-sen** [comment]
@hustcc if don't change anything in G2 code, you should at least change the doc here https://bizcharts.net/product/bizcharts/category/7/page/24#forcefit-span-classlightbooleanspan

**Comment by hustcc** [comment]
> https://bizcharts.net/product/bizcharts/category/7/page/24#forcefit-span-classlightbooleanspan

Thanks for your feedback, I will send send this to bizcharts.

**Comment by hustcc** [comment]
> @hustcc if don't change anything in G2 code, you should at least change the doc here https://bizcharts.net/product/bizcharts/category/7/page/24#forcefit-span-classlightbooleanspan

see [here](https://github.com/alibaba/BizCharts/pull/807/files), bizcharts supports with resize observer, the latest version will be add soon.

**Comment by Leannechn** [comment]
Switched to branch v3.5.x, corresponding to g2@3.5.15

**Comment by Leannechn** [comment]
Switched to branch v3.5.x in bizcharts , corresponding to g2@3.5.15
