### ISSUE TITLE
Bad label position for small last pie slice

### ISSUE THREAD

**Issue by sirlantis** [antvis/G2#2378]
* **G2 Version**: 4.0.8
* **Platform**: Any
* **Mini Showcase**:

![Screenshot 2020-04-28 at 17 29 51](https://user-images.githubusercontent.com/56807/80506446-e4248900-8975-11ea-90f7-fe3efd7148a5.png)

* **CodePen Link**: https://codesandbox.io/s/silent-lake-htoz7?file=/src/index.ts

The line goes to the right (correctly) but the label appears on the left (colliding with the other label).

**Comment by simaQ** [comment]
same with #2347, we will solve it in this week.

**Comment by sirlantis** [comment]
Sorry for posting a duplicate - didn't see the other one when looking for existing issues. Thanks!
