### ISSUE TITLE
4.x版本中，legend的hoverable、onHover接口无效

### ISSUE THREAD

**Issue by qq1198437442** [antvis/G2#2383]
* **G2 Version**:4.0.7
* **Platform**:Windows10
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

在版本变迁日志中，并没有声明移除这两个接口，但是按照3.x版本的调用方法，在4.x中是无效的。

**Comment by hustcc** [comment]
应该是文档上么有处理好，不好意思。使用以下方式试试看。

```ts
chart.on('legend:mousemove', () => {});
```

其中事件为 name:event，name 为 UI 组件的名字，包含有很多类别。

**Comment by simaQ** [comment]
我更新下文档
