### ISSUE TITLE
【bug or 优化】关系图label不显示

### ISSUE THREAD

**Issue by doraemon0522** [antvis/G2#2384]
G2 Version：
^4.0.3

当data数据里面，children里面有值是0时，label会显示不出来，鼠标移动上去有显示了，一度以为是动画效果不兼容，最后发现去掉0值就正常了。
mobiles = [
          {
            "name":"其他",
            "brand":"其他",
            "value":25.09647118932181,
            "children":[
              {
                "name":"其他",
                "value":25.0965
              }
            ]
          },{
            "name":"小米",
            "brand":"小米",
            "value":8.168930119898944,
            "children":[
              {
                "name":"小米手机M3",
                "value":0
              },
              {
                "name":"小米手机2S",
                "value":1.6483
              },
              {
                "name":"小米手机M4",
                "value":1.5656
              },
              {
                "name":"小米手机M2",
                "value":0
              },
              {
                "name":"小米手机2A",
                "value":0.4249
              },
              {
                "name":"小米手机1s",
                "value":0.3743
              },
              {
                "name":"小米手机M1",
                "value":0.3527
              },
              {
                "name":"小米Note",
                "value":0.3486
              },
              {
                "name":"小米平板",
                "value":0.2879
              },
              {
                "name":"其他",
                "value":0.1195
              }
            ]
          },{
            "name":"红米",
            "brand":"红米",
            "value":6.860016513545617,
            "children":[
              {
                "name":"红米手机1s",
                "value":0
              },
              {
                "name":"红米note",
                "value":1.9054
              },
              {
                "name":"红米手机",
                "value":0
              },
              {
                "name":"红米Note 1s",
                "value":0.8712
              },
              {
                "name":"红米HM2a",
                "value":0.6083
              },
              {
                "name":"红米1S",
                "value":0.377
              },
              {
                "name":"其他",
                "value":0.047
              }
            ]
          },
        ]

![image](https://user-images.githubusercontent.com/7713296/80664250-daf80100-8ac8-11ea-9e50-db6e94135d2b.png)

疑惑：要是对于0值不能兼容应该报错，说明传入数据错误，要么就兼容此状态。此坑踩着很痛。看起来像是动画等问题，容易误导判断方向。望有更好的提示等给予！！

**Comment by simaQ** [comment]
请升级至最新版本，该问题已修复：4.0.7
