### ISSUE TITLE
自定义label如何添加图片？

### ISSUE THREAD

**Issue by gengchen528** [antvis/G2#2385]
* **G2 Version**: 4.0.2
* **Platform**:  mac
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/20028566/80685854-63db6080-8afa-11ea-8927-0deb72699a5a.png)

* **CodePen Link**:
label目前不支持html了么，我看新的版本是可以自定义label的，目前我是想是实现label是图片，但是没有一个完整的demo可以参考，请问有做过的么

**Comment by paleface001** [comment]
这个需求不需要通过label解决，另外增加一个point geometry就可以了。
可以参考这个示例： https://g2.antv.vision/zh/examples/point/bubble#bubble-image

**Comment by gengchen528** [comment]
非常感谢，属于刚使用阶段，有些配置还没完全吃透
