### ISSUE TITLE
辅助线，可以填充满图表吗。怎么只能设置到存在的值

### ISSUE THREAD

**Issue by TwoPens** [antvis/G2#2386]
![微信截图_20200430162924](https://user-images.githubusercontent.com/62087166/80689431-ed416180-8aff-11ea-989d-01e4d1a25b89.png)

**Comment by TwoPens** [comment]
![微信截图_20200430163140](https://user-images.githubusercontent.com/62087166/80689539-182bb580-8b00-11ea-8009-7d3789f011fa.png)
目标效果，最大值这个字，放在最右侧。
代码
Chart.annotation().line({
          start: ['min', Maximum],
          end: ['max', Maximum]
}）

**Comment by TwoPens** [comment]
@simaQ

**Comment by simaQ** [comment]
可以使用 'start' 和 'end' 的关键字：

```ts
chart.annotation().line({
  start: ['start', Maximum],
  end: ['end', Maximum]
});
```

**Comment by TwoPens** [comment]
> ```ts
> end
> ```

这样子，辅助线填充的问题是解决了。但是图二截图，右侧的红圈。辅助线的文本，怎么放到最右侧
