### ISSUE TITLE
g2 4.0移除Global后，没有setTheme(theme) 了

### ISSUE THREAD

**Issue by ahuigo** [antvis/G2#2390]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/en/docs/manual/upgrade#%E4%B8%8D%E5%85%BC%E5%AE%B9%E6%94%B9%E5%8A%A8](https://g2.antv.vision/en/docs/manual/upgrade#%E4%B8%8D%E5%85%BC%E5%AE%B9%E6%94%B9%E5%8A%A8)

### Steps to reproduce
import G2 from '@antv/g2';
G2.Global.setTheme("dark")

### What is expected?
全局设置theme

### What is actually happening?
setTheme undefined

| Environment | Info |
|---|---|
| g2 | 4.0.7 |
| System | Mac osx |
| Browser | Chrome latest |

---
g2 4.0没有移除了   Global.setTheme(theme)

**Comment by hustcc** [comment]
目前没有全局设置 theme，但是有其他更好更合适的方式实现：

1. 注册自定义主题

```ts
import { registerTheme } from '@antv/g2';
registerTheme('xxx', { ... });
```

2. 在创建图表实例的时候使用自定义出题

```ts
import { Chart } from '@antv/g2';

const chart  = new Chart({
  theme: 'xxx',
  // ... 其他配置项
});
```

3. 更新主题并生效

```ts
chart.theme('new-theme-name');

chart.render(); // 重新渲染
```

----

为什么现在的方式更好？

1. 更符合 API 设计，之前的全局 setTheme，让所有的 chart instance 刷新生效，有一点反模式的感觉。
2. 可以实现页面无刷新切换主题（之前 setTheme 之后，要么记录所有 chart 实例，然后重新渲染；要么页面刷新这两种方式来实现）
3. Global 主题其实是一个业务概念，再切换 Global 主题的时候，一般跟随的业务页面也会跟着一起切换，所以Global 主题 更好的方式是业务来管理和维护，而不是有各个业务组件，业务组件仅提供能力。

**Comment by ahuigo** [comment]
@hustcc 我觉得global theme还是需要的。我现在的业务就需要一个global setTheme. 否则一个个修改chart 加theme 是很麻烦的事。

不是刷新所有的char instance, 而是这样一个全局默认配置方法：
```
const defaultOpition = {
     theme:"dark",
}
function newChart(option:Opition = {}){
     return new Chart({...default, ...option});
}
```

**Comment by guoguolong** [comment]
> @hustcc 我觉得global theme还是需要的。我现在的业务就需要一个global setTheme. 否则一个个修改chart 加theme 是很麻烦的事。
> 
> 不是刷新所有的char instance, 而是这样一个全局默认配置方法：
> 
> ```
> const defaultOpition = {
>      theme:"dark",
> }
> function newChart(option:Opition = {}){
>      return new Chart({...default, ...option});
> }
> ```

覆盖默认主题的方法是：
```js
G2.registerTheme('default', {
  "styleSheet": {
    "brandColor": "orange"
  }
});
```
因为默认theme是'default'，所以上述代码可以部分定制default，形成自己项目的default主题
