### ISSUE TITLE
数字标签，标签布局，重叠问题

### ISSUE THREAD

**Issue by TwoPens** [antvis/G2#2405]
柱状图、折线图都出现这个问题
![微信截图_20200506113604](https://user-images.githubusercontent.com/62087166/81136349-e8f8c680-8f8d-11ea-8397-9918a070caba.png)
![微信截图_20200506113721](https://user-images.githubusercontent.com/62087166/81136367-f6ae4c00-8f8d-11ea-9a23-13d21818468d.png)
@simaQ

**Comment by simaQ** [comment]
自定义 label 布局：https://g2.antv.vision/en/docs/manual/developer/registerlabel#%E8%87%AA%E5%AE%9A%E4%B9%89-label-%E5%B8%83%E5%B1%80%E5%87%BD%E6%95%B0

**Comment by TwoPens** [comment]
这个教程的例子，使用不了

**Comment by TwoPens** [comment]
.label('y', {
            layout: {
              type: 'fixed-overlap'
            }
          })
直接设置对象，避免重叠的设置有效。但是 如果是 使用函数返回对象，这个 “避免重叠”设置无效

**Comment by TwoPens** [comment]
我的数字标签，需要做函数处理的。 .label('x*y', ()=>{ return 对象 })。这个对象的layout设置没有效果
