### ISSUE TITLE
自定义shape，在点击隐藏图例时没有清除，并且交互报错

### ISSUE THREAD

**Issue by EddieUp** [antvis/G2#2406]
* **G2 Version**: 4.0.7
* **Platform**:
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/19686692/81140898-8a3b4900-8f9d-11ea-9f5f-c74ccf6ee5f6.png)
![image](https://user-images.githubusercontent.com/19686692/81140934-a3dc9080-8f9d-11ea-9a03-2416bc60c184.png)

* **CodePen Link**: https://codepen.io/eddieup/pen/zYvROmG?editors=1111

使用registerShape注册了一个image的Shape，代替了命中了的pointer shape，legend-active的交互时会报toFront的错误，并且点击隐藏图例时没有清除

**Comment by simaQ** [comment]
自定义 shape 的时候需要将 shape 返回：
![image](https://user-images.githubusercontent.com/6628666/81142056-0e430000-8fa1-11ea-9d25-7646e7eada26.png)

**Comment by EddieUp** [comment]
已解决，感谢
