### ISSUE TITLE
Bug, please fixe issue asap for angular 8: An accessor cannot be declared in an ambient context. 

### ISSUE THREAD

**Issue by yangke2911** [antvis/G2#2407]
ERROR in node_modules/@antv/g2/lib/chart/controller/annotation.d.ts:14:9 - error TS1086: An accessor cannot be declared in an ambient context.

14 get name(): string;
~~~~
node_modules/@antv/g2/lib/chart/controller/base.d.ts:20:18 - error TS1086: An accessor cannot be declared in an ambient context.

20 abstract get name(): string;
~~~~
node_modules/@antv/g2/lib/chart/controller/gesture.d.ts:18:9 - error TS1086: An accessor cannot be declared in an ambient context.

18 get name(): string;
~~~~
node_modules/@antv/g2/lib/chart/event.d.ts:19:9 - error TS1086: An accessor cannot be declared in an ambient context.

19 get target(): IShape;
~~~~~~
node_modules/@antv/g2/lib/chart/event.d.ts:21:9 - error TS1086: An accessor cannot be declared in an ambient context.

21 get event(): any;
~~~~~
node_modules/@antv/g2/lib/chart/event.d.ts:23:9 - error TS1086: An accessor cannot be declared in an ambient context.

23 get x(): number;
~
node_modules/@antv/g2/lib/chart/event.d.ts:25:9 - error TS1086: An accessor cannot be declared in an ambient context.

25 get y(): number;
~
node_modules/@antv/g2/lib/chart/event.d.ts:27:9 - error TS1086: An accessor cannot be declared in an ambient context.

27 get clientX(): number;
~~~~~~~
node_modules/@antv/g2/lib/chart/event.d.ts:29:93m9 - error TS1086: An accessor cannot be declared in an ambient context.

29 get clientY(): number;
~~~~~~~
node_modules/@antv/g2/lib/util/bbox.d.ts:17:9 - error TS1086: An accessor cannot be declared in an ambient context.

17 get minX(): number;
~~~~
node_modules/@antv/g2/lib/util/bbox.d.ts:18:9 - error TS1086: An accessor cannot be declared in an ambient context.

18 get maxX(): number;
~~~~
node_modules/@antv/g2/lib/util/bbox.d.ts:19:9 - error TS1086: An accessor cannot be declared in an ambient context.

19 get minY(): number;
~~~~
node_modules/@antv/g2/lib/util/bbox.d.ts:20:9 - error TS1086: An accessor cannot be declared in an ambient context.

20 get maxY(): number;
~~~~
node_modules/@antv/g2/lib/util/bbox.d.ts:21:9 - error TS1086: An accessor cannot be declared in an ambient context.

21 get tl(): Point;
~~
node_modules/@antv/g2/lib/util/bbox.d.ts:22:9 - error TS1086: An accessor cannot be declared in an ambient context.

22 get tr(): Point;
~~
node_modules/@antv/g2/lib/util/bbox.d.ts:23:9 - error TS1086: An accessor cannot be declared in an ambient context.

23 get bl(): Point;
~~
node_modules/@antv/g2/lib/util/bbox.d.ts:24:9 - error TS1086: An accessor cannot be declared in an ambient context.

24 get br(): Point;
~~
node_modules/@antv/g2/lib/util/bbox.d.ts:25:9 - error TS1086: An accessor cannot be declared in an ambient context.

25 get top(): Point;
~~~
node_modules/@antv/g2/lib/util/bbox.d.ts:26:9 - error TS1086: An accessor cannot be declared in an ambient context.

26 get right(): Point;
~~~~~
node_modules/@antv/g2/lib/util/bbox.d.ts:27:9 - error TS1086: An accessor cannot be declared in an ambient context.

27 get bottom(): Point;
~~~~~~
node_modules/@antv/g2/lib/util/bbox.d.ts:28:9 - error TS1086: An accessor cannot be declared in an ambient context.

28 get left(): Point;
~~~~
node_modules/@antv/g2plot/lib/dependents.d.ts:14:8 - error TS1192: Module '"D:/Guru/GURU_UI/node_modules/@antv/component/lib/tooltip/css-const"' has no default export.

14 import TooltipCssConst from '@antv/component/lib/tooltip/css-const';
~~~~~~~~~~~~~~~
node_modules/@antv/g2plot/lib/util/bbox.d.ts:14:9 - error TS1086: An accessor cannot be declared in an ambient context.

14 get minX(): number;
~~~~
node_modules/@antv/g2plot/lib/util/bbox.d.ts:15:9 - error TS1086: An accessor cannot be declared in an ambient context.

15 get maxX(): number;
~~~~
node_modules/@antv/g2plot/lib/util/bbox.d.ts:16:9 - error TS1086: An accessor cannot be declared in an ambient context.

16 get minY(): number;
~~~~
node_modules/@antv/g2plot/lib/util/bbox.d.ts:17:9 - error TS1086: An accessor cannot be declared in an ambient context.

17 get maxY(): number;
~~~~
node_modules/@antv/g2plot/lib/util/bbox.d.ts:18:9 - error TS1086: An accessor cannot be declared in an ambient context.

18 get tl(): {
~~
node_modules/@antv/g2plot/lib/util/bbox.d.ts:22:9 - error TS1086: An accessor cannot be declared in an ambient context.

22 get tr(): {
~~
node_modules/@antv/g2plot/lib/util/bbox.d.ts:26:9 - error TS1086: An accessor cannot be declared in an ambient context.

26 get bl(): {
~~
node_modules/@antv/g2plot/lib/util/bbox.d.ts:30:9 - error TS1086: An accessor cannot be declared in an ambient context.

30 get br(): {

**Comment by yangke2911** [comment]
Reference: http://www.webyuweb.com/a/renwu/19638.html

Our project using angular8, and can not upgraded to angular 9 as some dependence.
Please just spend 2 minus, and  update several G2 coding to fxied it.   Thanks!

**Comment by jlxzl** [comment]
please fixe issue asap for angular 8: An accessor cannot be declared in an ambient context

**Comment by YMQ258000** [comment]
我也是这个问题  楼主你解决了嘛 ？

**Comment by hustcc** [comment]
see here: https://stackoverflow.com/questions/60092642/ts1086-an-accessor-cannot-be-declared-in-ambient-context
