### ISSUE TITLE
图例的标题，被遮挡

### ISSUE THREAD

**Issue by TwoPens** [antvis/G2#2408]
![微信图片_20200506170021](https://user-images.githubusercontent.com/62087166/81159016-20ca3300-8fbb-11ea-9366-7d96a946bcc8.png)

直接修改 柱状图图例，重现的问题 
![微信截图_20200506170143](https://user-images.githubusercontent.com/62087166/81159170-49eac380-8fbb-11ea-8947-545937eb3c59.png)
源码如下，

import { Chart } from '@antv/g2';

const data = [
  { time: '03-19', type: '101-1000', value: 32000 },
  { time: '03-19', type: '31-100', value: 30000 },
  { time: '03-19', type: '11-30', value: 27000 },
  { time: '03-19', type: '1-10', value: 24000 },
  { time: '03-20', type: '101-1000', value: 35000 },
  { time: '03-20', type: '31-100', value: 32000 },
  { time: '03-20', type: '11-30', value: 30000 },
  { time: '03-20', type: '1-10', value: 27000 },
  { time: '03-21', type: '101-1000', value: 39000 },
  { time: '03-21', type: '31-100', value: 37000 },
  { time: '03-21', type: '11-30', value: 34000 },
  { time: '03-21', type: '1-10', value: 30000 },
  { time: '03-22', type: '101-1000', value: 44000 },
  { time: '03-22', type: '31-100', value: 42000 },
  { time: '03-22', type: '11-30', value: 38000 },
  { time: '03-22', type: '1-10', value: 34000 },
  { time: '03-23', type: '101-1000', value: 47000 },
  { time: '03-23', type: '31-100', value: 44000 },
  { time: '03-23', type: '11-30', value: 40000 },
  { time: '03-23', type: '1-10', value: 36000 },
  { time: '03-24', type: '101-1000', value: 48000 },
  { time: '03-24', type: '31-100', value: 46000 },
  { time: '03-24', type: '11-30', value: 42000 },
  { time: '03-24', type: '1-10', value: 38000 },
  { time: '03-25', type: '101-1000', value: 50000 },
  { time: '03-25', type: '31-100', value: 48000 },
  { time: '03-25', type: '11-30', value: 44000 },
  { time: '03-25', type: '1-10', value: 38000 }
];

const chart = new Chart({
  container: 'container',
  autoFit: true,
  height: 500,
});
chart.data(data);
chart.scale('value', {
  alias: '金额(元)'
});
chart.axis('time', {
  tickLine: null,
});

chart.axis('value', {
  label: {
    formatter: text => {
      return text.replace(/(\d)(?=(?:\d{3})+$)/g, '$1,');
    }
  },
  title: {
    offset: 80,
    style: {
      fill: '#aaaaaa'
    },
  }
});
chart.legend({
  position: 'top',
  layout: 'horizontal',
  title: {
    text: '我是图例',
    style: {
      fontSize: 20
    }
  }
});

chart.tooltip({
  shared: true,
  showMarkers: false,
});
chart.interaction('active-region');

chart
  .interval()
  .adjust('stack')
  .position('time*value')
  .color('type', ['#40a9ff', '#1890ff', '#096dd9', '#0050b3']);

chart.render();

**Comment by TwoPens** [comment]
@simaQ

**Comment by simaQ** [comment]
> @simaQ

Hi，其实不需要手动 @ 我的呢，你可以在这里 assign 给我~~ 
![image](https://user-images.githubusercontent.com/6628666/81160005-296f3900-8fbc-11ea-9192-c7240d85c3ca.png)

还有个小请求，就是能不能格式化下代码？大的代码片段的话，可以如下图：

![image](https://user-images.githubusercontent.com/6628666/81160208-5cb1c800-8fbc-11ea-8e0d-0feb0b94b8f3.png)

**Comment by TwoPens** [comment]
不会assign，之前几个问题都是大佬您帮忙解决的。我忍不住@你了。

**Comment by TwoPens** [comment]
你发的图片，看不到

**Comment by simaQ** [comment]
自己调整下padding

**Comment by TwoPens** [comment]
title样式的 padding吗

**Comment by TwoPens** [comment]
设置new Chart的padding，没效果。字体上边还是被遮挡
