### ISSUE TITLE
柱状图，x轴上的刻度，可以使用换行的形式吗

### ISSUE THREAD

**Issue by TwoPens** [antvis/G2#2410]
![微信截图_20200506172025](https://user-images.githubusercontent.com/62087166/81161309-f5951300-8fbd-11ea-9ee2-4d914ff79f1d.png)

目前是，x轴的数值过长，直接就倾斜了。我想改成换行

**Comment by simaQ** [comment]
不支持

**Comment by TwoPens** [comment]
添加样式，也不支持换行吗
