### ISSUE TITLE
数字标签的重叠问题

### ISSUE THREAD

**Issue by TwoPens** [antvis/G2#2413]
试了下，直接设置 .label('x*y', {})，layout是有效的。
我的数字标签，需要做函数处理的。 .label('x*y', ()=>{ return 对象 })。这个对象的layout设置没有效果。
![微信图片_20200506205448](https://user-images.githubusercontent.com/62087166/81179156-dad19700-8fdb-11ea-8a38-aa8ccffe8263.png)

**Comment by TwoPens** [comment]
@simaQ  没看到有Assignees这个设置，是不是我没权限

**Comment by paleface001** [comment]
<img width="508" alt="屏幕快照 2020-05-07 上午10 56 39" src="https://user-images.githubusercontent.com/5888974/81249548-78b37900-9051-11ea-9fdb-52e7e02e39bd.png">

**Comment by TwoPens** [comment]
![微信图片_20200507105901](https://user-images.githubusercontent.com/62087166/81249673-c9c36d00-9051-11ea-9672-67249dd8252d.png)
