### ISSUE TITLE
饼图label重叠

### ISSUE THREAD

**Issue by iiicon** [antvis/G2#2418]
* **G2 Version**: 4.0.7
* **Platform**: pc 
* **Mini Showcase(like screenshots)**: 和3.x的对比
![ee523092f5dbc73aef5997a0cb6ed99.png](https://i.loli.net/2020/05/07/32cW8IHiNGS9o6a.png)
![eda6e084a6d34aa284cf1396a30e39f.png](https://i.loli.net/2020/05/07/CIfUYoHjK3nWdGQ.png)
* **CodePen Link**:

**Comment by iiicon** [comment]
![ee523092f5dbc73aef5997a0cb6ed99](https://user-images.githubusercontent.com/19875237/81261675-0f426300-906f-11ea-9e2d-82c159e1e6c2.png)
![Uploading eda6e084a6d34aa284cf1396a30e39f.png…]()

**Comment by iiicon** [comment]
![eda6e084a6d34aa284cf1396a30e39f](https://user-images.githubusercontent.com/19875237/81262419-6c8ae400-9070-11ea-892b-e8757781b3eb.png)

**Comment by webaifei** [comment]
@iiicon 解决了么

**Comment by Me-Momo** [comment]
这个问题要等到六月份左右解决哈



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 饭团儿 <notifications@github.com&gt;
发送时间: 2020年5月14日 13:33
收件人: antvis/G2 <G2@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[antvis/G2] 饼图label重叠 (#2418)

**Comment by webaifei** [comment]
👌

**Comment by tangsj** [comment]
新版本解决了吗？

**Comment by iiicon** [comment]
> 新版本解决了吗？

刚升级了，还没有解决

**Comment by wxkgihub123** [comment]
同问题，还没有解决。

**Comment by iiicon** [comment]
> 这个问题要等到六月份左右解决哈 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 饭团儿 <notifications@github.com&gt; 发送时间: 2020年5月14日 13:33 收件人: antvis/G2 <G2@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[antvis/G2] 饼图label重叠 (#2418)

这个问题是不是忘了呀

**Comment by Me-Momo** [comment]
给一个复现地址？

**Comment by Me-Momo** [comment]
> * **G2 Version**: 4.0.7
> * **Platform**: pc
> * **Mini Showcase(like screenshots)**: 和3.x的对比
>   ![ee523092f5dbc73aef5997a0cb6ed99.png](https://camo.githubusercontent.com/3087a6d5136cca1b590fcfded1e2cff7842ad500/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30352f30372f33326357384948694e4753396f36612e706e67)
>   ![eda6e084a6d34aa284cf1396a30e39f.png](https://camo.githubusercontent.com/2256a871e0ef13fd52a094f3fcad97dbaeddb936/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30352f30372f43496655596f486a4b336e576447512e706e67)
> * **CodePen Link**:

可以提供复现 demo 地址吗？等 #2726 发版之后，可以配置一下：
```javascript
lable: {
   layout: { type: 'pie-outer' },
}
```
