### ISSUE TITLE
legend 交互默认选中的问题

### ISSUE THREAD

**Issue by iiicon** [antvis/G2#2419]
* **G2 Version**: 4.0.7
* **Platform**: pc
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/19875237/81264328-c93bce00-9073-11ea-9f5c-88880cb2651f.png)

* **CodePen Link**:

**Comment by iiicon** [comment]
没有交互的时候  会偶尔会选中  偶现的情况

**Comment by Aiyanahy** [comment]
解决了吗？我好像也遇到了类似的问题。这个不是偶现，鼠标悬浮在某个legend上直接滑动鼠标就会复现

**Comment by hustcc** [comment]
有复现的 demo 吗？

**Comment by visiky** [comment]
> 解决了吗？我好像也遇到了类似的问题。这个不是偶现，鼠标悬浮在某个legend上直接滑动鼠标就会复现

移除图例某个交互就行，内置下面的交互，会导致 图例 item hover 时候，触发元素选中 `element-acitve`

```ts
// legend hover，element active
registerInteraction('legend-active', {
  start: [{ trigger: 'legend-item:mouseenter', action: ['list-active:active', 'element-active:active'] }],
  end: [{ trigger: 'legend-item:mouseleave', action: ['list-active:reset', 'element-active:reset'] }],
});
```
