### ISSUE TITLE
数据为空数组的时候，或者legend全部置灰时，labels是空的，出现报错。

### ISSUE THREAD

**Issue by Leannechn** [antvis/G2#2421]
G2 version：4.0.7
数据为空数组的时候，或者legend全部置灰时，labels是空的，见报错。
![image](https://user-images.githubusercontent.com/6812138/81276553-bfbb6180-9085-11ea-850c-0d4457f99225.png)

**Comment by paleface001** [comment]
没数据labels肯定是空的呀，这里做一下判断就好了
