### ISSUE TITLE
g2 在ts项目中报生命错误

### ISSUE THREAD

**Issue by nan1010082085** [antvis/G2#2423]
* **G2 Version**:  4.0.7
* **Platform**:  pc
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/26052449/81278967-09597b80-9089-11ea-8b02-11f032cf8f76.png)

* **CodePen Link**:

**Comment by simaQ** [comment]
#2371 相同的问题，正在解决中
