### ISSUE TITLE
itemTpl自定义tooltip时可以使用非x,y 轴data吗

### ISSUE THREAD

**Issue by lori99-data** [antvis/G2#2427]
比如我需要写{事件}在{日期}发生了{次数}，事件是y轴，次数是x轴，这样情况下我还可以包括日期在tooltip里吗

**Comment by paleface001** [comment]
tooltip可以指定显示字段的，例如：

```
chart.line.position('x*y').tooltip('x*y*date');

```

**Comment by paleface001** [comment]
可以参考这个例子里的tooltip使用方法： https://g2.antv.vision/zh/examples/point/bubble#bubble
