### ISSUE TITLE
G2 4.0 Geometry shape

### ISSUE THREAD

**Issue by ch-daisy** [antvis/G2#2429]
* **G2 Version**: 4.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

hollow-circle  中间不是空心的，而是有白色的实心圆（貌似其他hollow-XXX）也有这个问题
![image](https://user-images.githubusercontent.com/10071628/81466779-c0c7cc80-9206-11ea-99f9-a476bcbd6f36.png)

circle 多了一圈白边希望能去掉，否则颜色不受控，如果不能去掉，希望能开接口支持配置颜色
![image](https://user-images.githubusercontent.com/10071628/81466727-60388f80-9206-11ea-80ef-392670a4352e.png)

**Comment by hustcc** [comment]
```ts
chart.point()
  .xxx()
  .style({}) // 用这个试试看
```

**Comment by visiky** [comment]
没有复现
![Uploading image.png…]()
