### ISSUE TITLE
 legend 与 slider 重叠, 多条折线与slider结合使用时，slider拖动会有折线渲染不全

### ISSUE THREAD

**Issue by guiguzigang** [antvis/G2#2433]
G2 version: 4.x;
win10-chrome浏览器;

如图所示：
![81491879-b8829680-92c5-11ea-98a4-e7be6c7781c](https://user-images.githubusercontent.com/22783404/81492021-f633ef00-92c6-11ea-94c1-1d7817ce15d9.jpg)

[官网在线例子地址](https://g2.antv.vision/zh/examples/line/basic#curved)
`chart.render()` 之前添加代码：`chart.option('slider', {})`

**Comment by BuggMaker** [comment]
+1

**Comment by seap** [comment]
+1

**Comment by Rabbitzzc** [comment]
重叠问题没法解决了，是么？

**Comment by Rabbitzzc** [comment]
> 图例跟tooltip重叠问题是暂时还没有方案解决么？？

已找到替代方案：如果开启滑块，可以设置图例在顶部，否则设置在底部，可以暂时解决重叠问题。

**Comment by bunnyxt** [comment]
临时解决方法：将`height`设置为负数，例如`-30`，并相应地调整`chart`的`padding`即可，不过里面的线**会颠倒**，需要手动重新设置`trendCfg: { data: sliderLine }`

同样的[官网在线地址](https://g2.antv.vision/zh/examples/line/basic#curved)，在`chart.render();`之前添加如下代码

```
const sliderLine = data
  .filter(x => x.city === 'Tokyo')
  .map(x => -x.temperature)
chart.option('slider', {
  height: -30,
  trendCfg: {
    data: sliderLine
  }
})
```

<img width="939" alt="1" src="https://user-images.githubusercontent.com/32478279/91638271-b6913e80-ea40-11ea-8dc2-b1340bd7882c.png">

**Comment by Rabbitzzc** [comment]
> 临时解决方法：将`height`设置为负数，例如`-30`，并相应地调整`chart`的`padding`即可，不过里面的线**会颠倒**，需要手动重新设置`trendCfg: { data: sliderLine }`
> 
> 同样的[官网在线地址](https://g2.antv.vision/zh/examples/line/basic#curved)，在`chart.render();`之前添加如下代码
> 
> ```
> const sliderLine = data
>   .filter(x => x.city === 'Tokyo')
>   .map(x => -x.temperature)
> chart.option('slider', {
>   height: -30,
>   trendCfg: {
>     data: sliderLine
>   }
> })
> ```
> 
> <img alt="1" width="939" src="https://user-images.githubusercontent.com/32478279/91638271-b6913e80-ea40-11ea-8dc2-b1340bd7882c.png">

你这个没太看懂，似乎去掉 `sliderLine` 没有啥影响

**Comment by bunnyxt** [comment]
> > 临时解决方法：将`height`设置为负数，例如`-30`，并相应地调整`chart`的`padding`即可，不过里面的线**会颠倒**，需要手动重新设置`trendCfg: { data: sliderLine }`
> > 同样的[官网在线地址](https://g2.antv.vision/zh/examples/line/basic#curved)，在`chart.render();`之前添加如下代码
> > ```
> > const sliderLine = data
> >   .filter(x => x.city === 'Tokyo')
> >   .map(x => -x.temperature)
> > chart.option('slider', {
> >   height: -30,
> >   trendCfg: {
> >     data: sliderLine
> >   }
> > })
> > ```
> > 
> > 
> > <img alt="1" width="939" src="https://user-images.githubusercontent.com/32478279/91638271-b6913e80-ea40-11ea-8dc2-b1340bd7882c.png">
> 
> 你这个没太看懂，似乎去掉 `sliderLine` 没有啥影响


@Rabbitzzc  不设置的话slider里面的线会**上下颠倒**，不过也可以设置`data: []`直接不要里面这跟线了

<img width="1062" alt="QQ20200903-145840@2x" src="https://user-images.githubusercontent.com/32478279/92081711-16e3ff80-edf6-11ea-862d-d934eb8a8381.png">

**Comment by hustcc** [comment]
别临时方案了，我现在就修复掉。 @所有人

**Comment by hustcc** [comment]
原来这个在最新的 4.1.0-beta.1 中已经修复。

**Comment by Rabbitzzc** [comment]
> 原来这个在最新的 4.1.0-beta.1 中已经修复。

棒！啥时候发布？

**Comment by Rabbitzzc** [comment]
> > 原来这个在最新的 4.1.0-beta.1 中已经修复。
> 
> 棒！啥时候发布release？

**Comment by hustcc** [comment]
4.1.0-beta.1 已经发布，v4.1.0 的正式版大概在 930 发布。

**Comment by wangjingithub** [comment]
现在版本还是4.0.15啊

**Comment by hustcc** [comment]
> 现在版本还是4.0.15啊

之前表达错了，目前还在内测中，等内部 BI 产品上线验证没问题了，就发布了，现在的 beta 也可以直接用的，基本改动不大了。

**Comment by wangjingithub** [comment]
大佬beta1版本，重叠问题解决了，但是刚进去那个可以拖动的右侧的小方型滑块没有显示，需要拖动一下才显示

**Comment by wangjingithub** [comment]
大佬默认显示有空求修复下啊

**Comment by hustcc** [comment]
> 大佬beta1版本，重叠问题解决了，但是刚进去那个可以拖动的右侧的小方型滑块没有显示，需要拖动一下才显示

具体是什么问题？有 demo 吗？

**Comment by wangjingithub** [comment]
![1606723423](https://user-images.githubusercontent.com/32031683/100587283-52299800-332b-11eb-96bc-5ca7301fafe6.png)

**Comment by wangjingithub** [comment]
![1606723423](https://user-images.githubusercontent.com/32031683/100587365-6a99b280-332b-11eb-9d4b-c4a75172e0d2.png)

**Comment by wangjingithub** [comment]
![1606723423](https://user-images.githubusercontent.com/32031683/100587414-7d13ec00-332b-11eb-8818-5b3193798cfa.png)
刚进来这样显示的
