### ISSUE TITLE
关于tooltip domStyles配置的问题

### ISSUE THREAD

**Issue by cx741041875** [antvis/G2#2439]
您好、我在Vue中使用G2组件 想修改一下默认tooltip的背景色 看API发现有一个domStyles属性可以修改 我是这么写的
 chart.tooltip({
        showCrosshairs: true, // 展示 Tooltip 辅助线
        domStyles: {
          "g2-tooltop": {
            backgroundColor: "red"
          }
        }
      }); 
怎么没有效果 显示还是默认的白色 是哪里写错了吗

**Comment by cx741041875** [comment]
![too](https://user-images.githubusercontent.com/48713520/81537857-6bbfbe00-93a0-11ea-8ad3-1fb48202f40b.png)
![bg](https://user-images.githubusercontent.com/48713520/81537980-a164a700-93a0-11ea-97ab-7a9684d9e227.png)

**Comment by simaQ** [comment]
g2-tooltip，单词拼写错误

**Comment by cx741041875** [comment]
![zmcw](https://user-images.githubusercontent.com/48713520/81630317-d96af900-9437-11ea-9e37-a50538df2b73.png)
 您好 我又去看了一下文档 发现文档是g2-tooltop 可以的话麻烦您们修改一下

**Comment by cx741041875** [comment]
![zmcw](https://user-images.githubusercontent.com/48713520/81630404-1505c300-9438-11ea-992e-0389f55f751b.png)
 您好 我又去看了一下文档 发现文档是g2-tooltop 可以的话麻烦您们修改一下

**Comment by simaQ** [comment]
> ![zmcw](https://user-images.githubusercontent.com/48713520/81630404-1505c300-9438-11ea-992e-0389f55f751b.png)
> 您好 我又去看了一下文档 发现文档是g2-tooltop 可以的话麻烦您们修改一下

欢迎直接提交 PR

**Comment by ash09227123** [comment]
@cx741041875 你改了之后生效吗？为啥我还是没有效果   3.X吗？

**Comment by ash09227123** [comment]
4.X才支持这个api
