### ISSUE TITLE
能否提供动态修改 chart padding 的接口

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#244]
如题，如果需要修改已经创建好 chart 的 padding 属性，必须要重建一个新的chart

**Comment by leungwensen** [comment]
padding, height, width 这些属性是初始化 chart 的时候传入的，如果 repaint 里考虑这些初始化属性，那其实重绘的成本和 “销毁 chart，再重新创建 chart 就一样了”

**Comment by weepy3641** [comment]
好，那我这里解决吧。重建个chart。
