### ISSUE TITLE
连续型图例颜色不对

### ISSUE THREAD

**Issue by OuyangQianba** [antvis/G2#2440]
* **G2 Version**:
4.0.8
* **Platform**:
All
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/17270099/81537477-d45a6b00-939f-11ea-9f6a-f0678f24f4f9.png)

* **CodePen Link**:

正确的渐变：
![image](https://user-images.githubusercontent.com/17270099/81537651-1d122400-93a0-11ea-81a2-20da253cb1a2.png)
问题出在：
![image](https://user-images.githubusercontent.com/17270099/81538400-4da68d80-93a1-11ea-8fbe-a8658f797de1.png)

高亮处应为：
```
        attrValue: attr.mapping(scale.invert(1)).join(''),
        color: attr.mapping(scale.invert(1)).join(''),
```

**Comment by hustcc** [comment]
已经修复，issue 关闭。
