### ISSUE TITLE
import DataSet from '@antv/data-set'; 导入DataSet 报错

### ISSUE THREAD

**Issue by qiuyunzhao** [antvis/G2#2441]
angualr7中使用堆叠条形图
npm install @antv/data-set --save
import DataSet from '@antv/data-set';

编译报错：
error TS1192: Module '"E:/InspurWorkSpace/Angular/boostgoui/node_modules/@antv/data-set/lib/index"' has no default export.

可是实例 https://g2.antv.vision/zh/examples/bar/stack#stacked 中就是这样用的呀

**Comment by hustcc** [comment]
@Jeffy2012  我看最新版本的 data-set 中的导出方式是：

```ts
import { DataSet } from './data-set';

export = DataSet;
```

不知道是不是语法导致的这个 issue。
