### ISSUE TITLE
g2 v4 文档中的按需加载是要开发者自己构建吗

### ISSUE THREAD

**Issue by webaifei** [antvis/G2#2448]
* **G2 v4**:

https://g2.antv.vision/zh/docs/manual/developer/require 
文档中介绍的按需加载是要开发者自己去构建自己的版本吗

**Comment by hustcc** [comment]
是的，按需有两种：

 - 写代码按需

在业务代码中，参考 index.ts 的引入方式，去按照自己的需求引入对应的模块。

 - 页面按需选择包

会提供一个页面，然后根据选择的功能，去打包出一个按需的 g2.min.js 包。

> 但是第二个目前还没有做。

**Comment by webaifei** [comment]
👌， 第二个方案有计划吗？
