### ISSUE TITLE
vue开发antv的时候 走new Chart构造函数后 函数没有data方法

### ISSUE THREAD

**Issue by q378532364** [antvis/G2#2451]
![Uploading image.png…]()
后面也就都没有效果了...

**Comment by iNahooNya** [comment]
chart.data() 是 v4 才有的新API，v3-是没有的。
[G2 4.0 升级指南](https://g2.antv.vision/zh/docs/manual/upgrade)

方便提供一下 antv 的版本以及复现demo吗？

**Comment by q378532364** [comment]
版本是^3.5.16 的  我是在 [https://g2.antv.vision/zh/examples/gallery/column](g2) 看到的例子拿来用的...直接npm 下载的就是这个版本

**Comment by Joanna0001** [comment]
![image](https://user-images.githubusercontent.com/35752466/81911454-e9cdd000-95ff-11ea-8f20-24b6937ea55a.png)
改成v3版本的chart.source就好了

**Comment by q378532364** [comment]
const data = [
      { type: '未知', value: 654, percent: 0.02 },
      { type: '17 岁以下', value: 654, percent: 0.02 },
      { type: '18-24 岁', value: 4400, percent: 0.2 },
      { type: '25-29 岁', value: 5300, percent: 0.24 },
      { type: '30-39 岁', value: 6200, percent: 0.28 },
      { type: '40-49 岁', value: 3300, percent: 0.14 },
      { type: '50 岁以上', value: 1500, percent: 0.06 }
    ]

    const chart = new Chart({
      container: 'container',
      autoFit: true,
      height: 500,
      padding: [50, 20, 50, 20]
    })
    chart.source(data)
    chart.scale('value', {
      alias: '销售额(万)'
    })

    chart.axis('value', {
      label: {
        style: {
          textAlign: 'center'
        } // 设置坐标轴文本样式
      },
      line: {
        style: {
          stroke: '#E9E9E9',
          lineDash: [3, 3]
        } // 设置坐标轴线样式
      },
      grid: {
        line: {
          style: {
            lineDash: [3, 3]
          }
        } // 设置坐标系栅格样式
      }
    })

这个是不是要学下g2然后自己画啊。。。我感觉比ecahrts好看想用下的，demo使用cdn引入new g2.char是可以的,

**Comment by Godlike-meteor** [comment]
因为npm 上稳定版本是^3.5.16，同遇到问题，这里不仔细看还真找不到问题

**Comment by lianghx-319** [comment]
ts typed check 还是有问题
version 4.0.12

source 有，但是 data 没有

![image](https://user-images.githubusercontent.com/27187946/86485523-7c325a80-bd8b-11ea-97fc-520cac564fe4.png)
![image](https://user-images.githubusercontent.com/27187946/86485566-966c3880-bd8b-11ea-9314-b474dcd8742b.png)

**Comment by hustcc** [comment]
一定是你的环境中有不同的版本，导致类型定义文件串了。4.x 版本，一定会有 .data 等 api 的类型定义。
