### ISSUE TITLE
[DOCS] 几个中英文文档链接返回404

### ISSUE THREAD

**Issue by felipefdl** [antvis/G2#2453]
Oi pessoal,

Gostaria de reportar um bug na doc, tanto em chinês quanto em inglês está retornando 404.

Estou escrevendo esse issue em português, pq o time do G2, pelo visto so responde issues escrita em língua local, no caso meu caso é português. Seria bom para todos usar uma língua global no caso ingles. mas não custa usar algum tradutor não é mesmo.

Se conseguir arrumar os links da doc fico agradecido, obrigado! excelente trabalho a proposito!

Exemplo de links com erro:

https://antv.vision/en/docs/manual/middle/elements/nodes/image/#gatsby-focus-wrapper
https://antv.gitee.io/en/docs/manual/middle/svg/#gatsby-focus-wrapper
https://antv.gitee.io/en/docs/api/Custom/#g6registernodenodename-options-extendnodename
https://antv.gitee.io/en/examples/case/metroLines/#gatsby-focus-wrapper

e varios outros, a maior parte é link que estão no search, mas tem em outros lugares também.

Obrigado || Thank you || 谢谢

**Comment by ArranZeyuWang** [comment]
We've revised the 404 errors in Tutorials and updated our API docs.

Please re-enter our [website](https://g2.antv.vision/) for visiting the newest version.

Since there are still some leakages, the docs will be further improved soon.
