### ISSUE TITLE
BUG - Heatmap image being cut off

### ISSUE THREAD

**Issue by matheuslbenachio** [antvis/G2#2454]
* **G2 Version**: 4.0.7
* **Platform**: MacOS Chrome
* **Mini Showcase(like screenshots)**:

![image](https://user-images.githubusercontent.com/36608338/81832562-0d681c00-9515-11ea-9cd1-ac05d569920f.png)

* **CodePen Link**:
```js
import { Chart } from '@antv/g2';

const data = [
  { g: 0, l: 0, tmp: 100 },
]

const chart = new Chart({
  container: 'container',
  autoFit: true,
  height: 500,
  padding: [0, 30, 60, 30]
});
chart.data(data);
chart.scale({
  tmp: { nice: true }
});
chart.tooltip({
  showTitle: false
});
chart.axis(false);
chart.legend({
  offset: 10
});
chart.heatmap()
  .position('g*l')
  .color('tmp', '#F51D27-#FA541C-#FF8C12-#FFC838-#FAFFA8-#80FF73-#12CCCC-#1890FF-#6E32C2');
chart.annotation().image({
  start: ['min', 'max'],
  end: ['max', 'min'],
  src: 'https://gw.alipayobjects.com/zos/rmsportal/NeUTMwKtPcPxIFNTWZOZ.png',
});
chart.render();

```

The example above is from the G2 heat map example: https://g2.antv.vision/en/examples/heatmap/heatmap

If you only have a single point in a heat map chart, the heat map image isn't rendered correctly. In fact, it's totally being cut off.

As an user, I expect the image to always be rendered, even though we have no points in the chart.

@simaQ How do I fix this?

**Comment by hustcc** [comment]
when data is empty or .length = 1, the scale will be only 0 / 1 key. so set the scale range, min, max will fix it.

```ts
chart.scale({
      l: { range: [0, 1], min: 0, max: 1 },
      g: { range: [0, 1], min: 0, max: 1 },
    });
```
