### ISSUE TITLE
BUG - heatmap zoom and drag is very slow

### ISSUE THREAD

**Issue by matheuslbenachio** [antvis/G2#2455]
* **G2 Version**: 4.0.7
* **Platform**: MacOS Chrome
* **Mini Showcase(like screenshots)**:

![May-13-2020 12-33-34](https://user-images.githubusercontent.com/36608338/81833360-fc6bda80-9515-11ea-94dc-4bf1c512f3c8.gif)

* **CodePen Link**:
```js
import { Chart } from '@antv/g2';

fetch('https://g2.antv.vision/en/examples/data/heatmap.json')
  .then(res => res.json())
  .then(data => {
    const chart = new Chart({
      container: 'container',
      autoFit: true,
      height: 500,
      padding: [0, 30, 60, 30]
    });
    chart.data(data);
    chart.scale({
      tmp: { nice: true }
    });
    chart.tooltip({
      showTitle: false
    });
    chart.axis(false);
    chart.legend({
      offset: 10
    });
    chart.heatmap()
      .position('g*l')
      .color('tmp', '#F51D27-#FA541C-#FF8C12-#FFC838-#FAFFA8-#80FF73-#12CCCC-#1890FF-#6E32C2');
    chart.annotation().image({
      start: ['min', 'max'],
      end: ['max', 'min'],
      src: 'https://gw.alipayobjects.com/zos/rmsportal/NeUTMwKtPcPxIFNTWZOZ.png',
    });
    chart.render();
  });
```

When you add the code `chart.interaction('view-zoom');` to a heat map, the zoom and drag become very very slow. This doesn't happen with other charts such as the line chart or bar chart.

@simaQ How can I fix this?

**Comment by hustcc** [comment]
Sorry, due to problems in the program's architecture design, we are unable to effectively fix the issues. You can have a try with G2 [v5](https://g2.antv.antgroup.com/examples/general/heatmap/#heatmap).
