### ISSUE TITLE
LegendMarkerCfg中的spacing无效

### ISSUE THREAD

**Issue by qq1198437442** [antvis/G2#2456]
* **G2 Version**: 4.0.7
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
代码：
`items: [
               { 
                    name: this.$t('store.customerCount'), 
                    value: 'customer', 
                    marker: { 
                        symbol: 'line', 
                        spacing: 200, 
                        style: { 
                            stroke: '#35AE98', 
                            lineWidth: 30, 
                        } 
                    } 
                },
            ],
`

  因为需求让减小Marker跟后面name的间距，但是发现spacing并不起作用。此外，此时style里边的x也不起作用，但是y有效。
效果图：
![image](https://user-images.githubusercontent.com/49434482/81881643-4a8ae780-95c3-11ea-8cbc-23154aceaa57.png)

**Comment by paleface001** [comment]
```
chart.legend({
  marker:{
    spacing:0
  }
});
```
