### ISSUE TITLE
G2堆叠柱状图：多条数据出现重复key值的话柱状图会出现白色条纹

### ISSUE THREAD

**Issue by lkq0119** [antvis/G2#2457]
目前业务是实现堆叠柱状图功能，根据返回的数据构造官网数据结构，发现多数据情况下出现重复key值，柱状图上会出现白色的条纹。

**Comment by hustcc** [comment]
具体是什么数据格式，这样的 issue 很难发现问题。盲猜一下：

如果数据的 x 轴相同的话，那么只能在传入 G2 之前进行数据的合并，这个在数据分析上也是合理的，要么就是 sum，max 或者其他的聚合方式！
