### ISSUE TITLE
Legend 排序问题

### ISSUE THREAD

**Issue by hackerliang** [antvis/G2#2463]
如图所示，现在顺序是Cover第一，Death第二， Alive第三
如果想更换显示顺序呢？
比如是Death第一，Cover第二，Alive第三
官方文档中好像没有提及
![图片](https://user-images.githubusercontent.com/32356999/82153329-4c8dc880-9899-11ea-9f5b-6a399d490e71.png)

**Comment by paleface001** [comment]
可以在chart.scale里通过value指定显示顺序，例如：

```
chart.scale('type',{
  values:['south','north']
});
```
