### ISSUE TITLE
作为第三方库，打包后请别全局用[].includes之类的方法了

### ISSUE THREAD

**Issue by 1215904405a** [antvis/G2#2464]
请暂时别用[].includes之类的方法了，低版本浏览器不支持，搞到后来就直接引用
import 'core-js/stable';
import 'regenerator-runtime/runtime';

虽然问题不大 ，只是文件大了点，看着别扭

**Comment by hustcc** [comment]
在业务系统中，自己引入 babel-polyfill 即可，底层模块不适合自动打包进去。
