### ISSUE TITLE
折线图重新渲染图表canvas位置错误

### ISSUE THREAD

**Issue by Evelyn77777** [antvis/G2#2466]
在一个页面渲染两个折线图图表的时候，第一个渲染的位置是好的，但是第二个会位置会网上走
![image](https://user-images.githubusercontent.com/50935812/82172134-dc8f3a80-98b8-11ea-9c38-b9cb70d7194f.png)而且当我从后台获取不同的数据返回渲染的时候，平滑的折线图的线变得曲折
![image](https://user-images.githubusercontent.com/50935812/82172222-1b24f500-98b9-11ea-8a78-63876d017fa4.png)环形图建议在数据全为0的时候显示的均分环形图而不是什么都没有

**Comment by paleface001** [comment]
请提供复现demo

**Comment by Evelyn77777** [comment]
这是封装的子组件
这是父组件
从后台拿到数据之后渲染第一次就会折线图错位
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"paleface001"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月18日(星期一) 下午2:42
收件人:&nbsp;"antvis/G2"<G2@noreply.github.com&gt;;
抄送:&nbsp;"他偏爱长发"<562911744@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/G2] 折线图重新渲染图表canvas位置错误 (#2466)





 
请提供复现demo

**Comment by hustcc** [comment]
4.x 已经解决这个问题。
