### ISSUE TITLE
G2 4.0 axis tickline 被axis label 控制

### ISSUE THREAD

**Issue by ch-daisy** [antvis/G2#2467]
* **G2 Version**: 4.0 
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

G2 4.0 axis tickline 被axis label 控制，当配置 label：null时，tickline 也不显示了
riddle 地址：http://riddle.alibaba-inc.com/riddles/60ff2722

**Comment by paleface001** [comment]
配置：
```
  tickLine:{
    displayWithLabel: false
  },
```
