### ISSUE TITLE
G2 4.0 axis subTickline 被 axis tickline 控制

### ISSUE THREAD

**Issue by ch-daisy** [antvis/G2#2468]
* **G2 Version**: 4.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

G2 4.0 axis subTickline 被 axis tickline 控制，当配置 tickLine: null 时，subTickLine 也不显示了
Riddle地址：http://riddle.alibaba-inc.com/riddles/8655e275

**Comment by paleface001** [comment]
这个是by design的，如果不显示tickLine，那么subTickLine也没有意义了。如果一定要这么做的话，建议手动把tickLine透明度设为0.
