### ISSUE TITLE
How to avoid axis label & grid line overlap/intersection?

### ISSUE THREAD

**Issue by aseemgautam** [antvis/G2#2471]
We can set offset or text alignment to axis label. -
```
chart.axis('value', {
	label: {
		// offset: -5,
		style: {
			// textAlign: 'left',
			// x: 50
		}
	}
});
```
Works, but when the label is moved inside the chart, **it intersects with the grid line**. Is there any way to move the label a few pixels up (Y offset) so it does not intersects with the grid line.
<img width="406" alt="Screenshot 2020-05-18 at 7 02 36 PM" src="https://user-images.githubusercontent.com/3583020/82219883-89aa9700-993b-11ea-8adc-791220a4b637.png">

There is an option `alignTick` in the `grid configuration`. Result is not good.
```
grid: {
    alignTick: false,
}, 
```

Any way to avoid this overlapping/intersection of the axis label & grid line?

**Comment by paleface001** [comment]
the offsetX and offsetY can be set separately.

```
chart.axis('value',{
  offsetX: 20,
  offsetY: -20
});
```
<img width="628" alt="屏幕快照 2020-05-19 上午11 07 49" src="https://user-images.githubusercontent.com/5888974/82280403-65919900-99c1-11ea-8417-b19e92ae4b60.png">
