### ISSUE TITLE
G2 4.0 legend marker symbol 线条类型的形状不显示（line、cross等）

### ISSUE THREAD

**Issue by ch-daisy** [antvis/G2#2474]
* **G2 Version**: 4.0
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

G2 4.0 legend marker symbol 线条类型的形状不显示，例如： "cross" | "tick" | "plus" | "hyphen" | "line"等
riddle 地址：https://riddle.alibaba-inc.com/riddles/6b662177

**Comment by Me-Momo** [comment]
ref: https://github.com/antvis/G2Plot/issues/1205
