### ISSUE TITLE
help

### ISSUE THREAD

**Issue by songjiaqi1** [antvis/G2#2475]
官网上日历热力图中月份的分割线会被后面的 element 挡住一半这个有比较好的解决方法吗？
![image](https://user-images.githubusercontent.com/22426345/82301658-22e4b680-99eb-11ea-863d-dd705d54f59f.png)
g2版本：4.0.7

https://g2.antv.vision/en/examples/heatmap/calendar#calendar-horizontal

**Comment by paleface001** [comment]
这是因为axis绘制在了背景层，目前貌似是没有开放层级配置的：https://github.com/antvis/G2/blob/master/src/chart/controller/axis.ts#L55

这个后续要开放吗？ @hustcc  @simaQ @zqlu

**Comment by songjiaqi1** [comment]
试过 zIndex 但是不起作用，换了一个思路，把分割线画到了下个月的第一周，谢谢！
