### ISSUE TITLE
g2中如何实现多级x轴的图表？

### ISSUE THREAD

**Issue by peacejj** [antvis/G2#2477]
详细需求：现在的柱状图折线图只有X轴上只有一个层级，如何实现多个？如下图所示的样子。
![image](https://user-images.githubusercontent.com/27217020/82396897-ba94e400-9a81-11ea-88bd-02b02586ac54.png)

**Comment by paleface001** [comment]
这个是分类子母轴，目前只能在chart.render()之后自己用G去画，后续我们会支持一套默认的

**Comment by peacejj** [comment]
@paleface001 谢谢，期待~
