### ISSUE TITLE
饼图legend设置custom=true，onClick事件怎样达到和默认的clickable相同的效果

### ISSUE THREAD

**Issue by jrjljf** [antvis/G2#2478]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by jrjljf** [comment]
默认效果：点击legend的某一项，该项的数据在饼图中不渲染。自定义的onClick事件怎样写呢，数据重置的话，legend会随着数据源变动而变动呢

**Comment by Me-Momo** [comment]
调用chart.filter方法
