### ISSUE TITLE
canvas与svg清晰度不一致

### ISSUE THREAD

**Issue by hackerliang** [antvis/G2#2479]
可以在官网随便找个例子

canvas的清晰度简直不忍直视

但是如果是svg清晰度就非常的好

不清楚是bug还是就是这样的

```javascript
const chart = new Chart({
  container: 'container',
  autoFit: true,
  height: 500,
  renderer: 'svg',
});

```

**Comment by hackerliang** [comment]
文字的清晰度最为明显

**Comment by hustcc** [comment]
可以帮忙看看你的屏幕分辨率吗？是 4k 屏吗

**Comment by hackerliang** [comment]
> 可以帮忙看看你的屏幕分辨率吗？是 4k 屏吗

1920*1080
但是windows系统设置了125%的缩放 不知道是不是这个原因

**Comment by hustcc** [comment]
应该是这个原因，你的缩放是在 meta 中增加的缩放吗？

**Comment by hackerliang** [comment]
Windows系统设置里的，研究下？不清楚这个windows的缩放原理
![图片](https://user-images.githubusercontent.com/32356999/83319248-50452600-a26f-11ea-92a9-fa49faa5bdae.png)

**Comment by hustcc** [comment]
可以在浏览器控制台 window.devicePixelRatio，帮忙看看是多少

**Comment by hackerliang** [comment]
![图片](https://user-images.githubusercontent.com/32356999/83319295-d3ff1280-a26f-11ea-9a95-c78db87d7e0b.png)

**Comment by hustcc** [comment]
https://github.com/antvis/g/issues/544

**Comment by hustcc** [comment]
@SophinQ @hackerliang 应该已经修复了。
