### ISSUE TITLE
G2的3.x怎么实现Y（左）轴和Y（右）轴分别显示multiple-bar和multiple-line

### ISSUE THREAD

**Issue by xian107** [antvis/g2#248]
![image](https://user-images.githubusercontent.com/13252682/33652863-e474052e-daa5-11e7-9259-6e3d89ef2c18.png)
就是两个轴左右不一样的刻度

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/tutorial/fqas.html#_如何绘制多-y-轴图表
