### ISSUE TITLE
[BUG] view下regionFilter失效

### ISSUE THREAD

**Issue by liuxuan1-1** [antvis/G2#2481]
版本: 4.0.7

```js
    chart.data(chartData.data);
    chart
      .area()
      .position('日期*汇总实际每日达成')
      .color(`l(90) 0:${COLOR.budgetGraphBlue} 1:#ffffff`);
    chart.annotation().regionFilter({
      top: true,
      start: ['4.6', 'max'],
      end: ['4.8', 0],
      color: `l(90) 0:${COLOR.budgetGraphPink} 1:#ffffff`,
    });
```
这样正常
![image](https://user-images.githubusercontent.com/24970282/82454549-7981eb80-9ae4-11ea-89a0-55f269e8a110.png)

----------------------------

```js
    const areaView = chart.createView();
    areaView.data(chartData.data);
    areaView
      .area()
      .position('日期*汇总实际每日达成')
      .color(`l(90) 0:${COLOR.budgetGraphBlue} 1:#ffffff`);
    areaView.annotation().regionFilter({
      top: true,
      start: ['4.6', 'max'],
      end: ['4.8', 0],
     color: `l(90) 0:${COLOR.budgetGraphPink} 1:#ffffff`,
    });
```
写在view中失效

![image](https://user-images.githubusercontent.com/24970282/82454692-a6360300-9ae4-11ea-8284-6fddc7fc4a29.png)

**Comment by TheKiteRunners** [comment]
这个需求我就是想再某个X点之后的区域全部换一种颜色, 用color去设置的话怎么搞?

```javascript
 .color('日期', (date) => {
    if (date > xxxx) {
        return    `l(90) 0:${COLOR.budgetGraphBlue} 1:#ffffff`);
   }
        return    `l(90) 0:${COLOR.budgetGraphPink} 1:#ffffff`);
})
```

如果采用上实例代码去设置的话, 图表区域没颜色, 下面这里有张图

![image](https://user-images.githubusercontent.com/24970282/82455621-b9959e00-9ae5-11ea-961a-15581bdd0e8a.png)

上面是个图片

**Comment by maplor** [comment]
这个bug 3.x 就有了，没想到继承了下来。当时也没有找到合适的解决方案。

**Comment by hustcc** [comment]
非常不好意思，因为程序架构设计上的问题，导致我们无法很好的修复问题，可以试试 [G2 5.0](https://g2.antv.antgroup.com/examples/annotation/range/#line-range) 中相关的能力。
