### ISSUE TITLE
柱状图数据太小不能触发点击

### ISSUE THREAD

**Issue by mengxuhui** [antvis/G2#2482]
![image](https://user-images.githubusercontent.com/20699670/82514168-969bd600-9b47-11ea-8d56-93b59c565aa0.png)

**Comment by hustcc** [comment]
图形高度和数据大小直接映射，不能违背可视化数据准确性的准则。如果非要违背，可以尝试在数据传入之前，进行一个小数据的处理。

**Comment by YYL1999** [comment]
这个问题可以通过设置axes解决
