### ISSUE TITLE
我vue的项目，为啥按照官网的引入步骤渲染不出来？

### ISSUE THREAD

**Issue by hnx469** [antvis/G2#2487]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by hnx469** [comment]
最后找了很久,特么和这官网的引入使用步骤根本不一样，代码如下:
1. 引入 import * as G2 from '@ant/g2'
2. 定义数据data = []
3. 创建chart对象:  let chart = new G2.chart({ container: 'container' .... })
4. 载入数据(就是这个方法，它官网上是data,就是不行) chart.source(data)
5. 创建图形 chart.render()

**Comment by hustcc** [comment]
什么版本的 G2

**Comment by liubaicai** [comment]
"chart.source": This method will be removed at G2 V4.1. Please use chart.data() instead.
你的g2版本太旧了，新版添加了data方法，4.1source放假就会移除
