### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by MarkLyck** [antvis/G2#2491]
* **G2 Version**: 4.0.8
* **Platform**: React
* **Mini Showcase(like screenshots)**:

<img width="569" alt="Screen Shot 2020-05-24 at 11 26 48 AM" src="https://user-images.githubusercontent.com/6841110/82757956-9acb2c00-9db1-11ea-9144-fa420d34108c.png">

When resizing a normal line chart I get the following error:

`Uncaught TypeError: Cannot read property 'style' of undefined`

looking at the source code, it looks like element (el) is undefined, while it's trying read/set new styles on it.

**Comment by hustcc** [comment]
has any live demo or code?
