### ISSUE TITLE
为什么地图使用交互view-zoom只能缩小

### ISSUE THREAD

**Issue by WangGuanJie1** [antvis/G2#2492]
const worldGeo = ds.createView().source(worldData, {
            type: 'GeoJSON',
        });
        const mapView = chart.createView();
        mapView.data(worldGeo.rows);
        mapView
            .polygon()
            .position('longitude*latitude')
            .style({
                fill: 'rgba(255,255,255)',
                lineWidth: 1,
                stroke: 'rgba(0,0,0,.3)',
                shadowColor: 'rgba(0,0,0,.06)',
                shadowOffsetX: 5,
                shadowOffsetY: 20,
            })
            .tooltip(false)
            .animate({
                appear: {
                    animation: 'grow-in-xy',
                    duration: 500
                }
            });
        mapView.interaction('view-zoom');

**Comment by maplor** [comment]
之前也遇到了这个问题，复现链接：https://riddle.alibaba-inc.com/riddles/f90a5e6c

排查原因是缩放bgView，但其他图层 scale 不变，导致无法放大。理论上通过修改 sync: 'syncKey' 可以解决这个问题。

等测试成功了再来回复。
