### ISSUE TITLE
K-chart doesn't show tooltip on hover anywhere on chart.

### ISSUE THREAD

**Issue by MarkLyck** [antvis/G2#2493]
G2 Version**:4.0.8
* **Platform**:any
* **Mini Showcase(like screenshots)**:
https://g2.antv.vision/en/examples/candlestick/candlestick#basic

On any normal charts you can hover anywhere and the tooltip will show.

However for K-chart you have to specifically hover over the candlestick to see the tooltip.

The only way I see to make it work anywhere on the chart is with `shared: true`. However I can't think of a single scenario where you'd want to see shared data in a candlestick chart.

See this example for shared:true
https://g2.antv.vision/en/examples/candlestick/candlestick#k-and-area

**Comment by hustcc** [comment]
fixed.
