### ISSUE TITLE
version-3.x 饼图 生成位置右上角

### ISSUE THREAD

**Issue by wlichee** [antvis/G2#2498]
官网url：https://g2-v3.antv.vision/zh/examples/pie/basic
生成的饼图没有居中实现，在右上角，在 version-4.x 中可以实现居中，但是需要用到version-3.x  上label 的 htmlTemplate 属性实现自定义 指示线 内容，这个在 version-4.x中没有支持

**Comment by charanjit-singh** [comment]
English: Official website url: https://g2-v3.antv.vision/zh/examples/pie/basic The generated pie chart is not centered. In the upper right corner, it can be centered in version-4.x, but you need to use the htmlTemplate attribute of the label on version-3.x to implement the custom indicator line content. This is in version-4. No support in x**
**
