### ISSUE TITLE
version-3.x 分组柱状图加折线图后鼠标悬浮active-region效果bug

### ISSUE THREAD

**Issue by JettWoo** [antvis/G2#2499]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

根据官网文档实例https://g2-v3.antv.vision/zh/examples/column/dodge，当鼠标悬浮时，悬浮的active-region阴影效果正常，但是加了chart.line().position('月份*月均降雨量');折线图效果后悬浮的效果变窄了。
![正常](https://user-images.githubusercontent.com/45837361/83010635-214e6a80-a04b-11ea-9f02-96d706f726bc.png)
![加折线](https://user-images.githubusercontent.com/45837361/83010662-2ca19600-a04b-11ea-88af-89617243efac.png)

**Comment by hustcc** [comment]
4.x 中已经不存在这个问题，关闭。https://g2.antv.vision/zh/examples/column/dodge#grouped
