### ISSUE TITLE
重新调用chart.render(),图例跑到左上角

### ISSUE THREAD

**Issue by Hilbertangers** [antvis/G2#2500]
* **G2 Version**: 4.0.8
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/21299424/83016399-75aa1800-a054-11ea-903e-74e3f61207a2.png)
![image](https://user-images.githubusercontent.com/21299424/83017075-97f06580-a055-11ea-860b-bab4d9510f97.png)

```
      draw() {
        this.chart = new Chart({
          container: 'order-intercept',
          height: 300,
          autoFit: true,
          padding: [30, 50, 50, 60],
          options: {
            data: mock,
            // todo
          },
        });
        this.chart.render();
      },
      update(y, time) {
        // todo
        this.chart.render();
      },
```

**Comment by hustcc** [comment]
4.0.9 修复了，试试看~
