### ISSUE TITLE
请问如何修改坐标轴文字的字号

### ISSUE THREAD

**Issue by zyd0113** [antvis/G2#2503]
![image](https://user-images.githubusercontent.com/52477117/83089614-54374380-a0c9-11ea-9b97-bf8447615b3f.png)

**Comment by zyd0113** [comment]
文字太宽了，在移动端影响观看，希望能得到回复，谢谢

**Comment by simaQ** [comment]
```ts
chart.axis('xxx', {
  label: {
    style: {
      fontSize: 12
    }
  }
});
```
