### ISSUE TITLE
dark theme 不生效

### ISSUE THREAD

**Issue by hustcc** [antvis/G2#2505]
![image](https://user-images.githubusercontent.com/7856674/83097916-d3ce0e00-a0db-11ea-840c-7136ca18487e.png)

**Comment by simaQ** [comment]
其实已经生效了。只是没有深色背景来衬托，你设置下 canvas 父容器的背景色就出来了。

PS: 这真的是我编码生涯里上的一个很失败的 feature，羞愧！

![image](https://user-images.githubusercontent.com/6628666/83211727-78118c80-a190-11ea-9eb3-453c4dfd28dd.png)
