### ISSUE TITLE
双Y轴的Legend问题

### ISSUE THREAD

**Issue by guiguzigang** [antvis/G2#2506]
- G2 Version: 4.0.x
- Platform:
- Mini Showcase(like screenshots):
- CodePen Link:

[官网在线例子](https://g2.antv.vision/zh/examples/area/basic#area-large)

1. 点击legendItem没有交互效果，猜测应该是legend设置为`custom: true`导致的；
2. 添加其它的图表交互配置，如：`chart.interaction('legend-highlight')`，也是没有交互效果

如下图：
![image](https://user-images.githubusercontent.com/22783404/83104335-18ad7100-a0eb-11ea-9336-a5d2abc6f8c8.png)

3. legend的配置不设置为`custom: true, items: []`，legend不能显示，如下图：
![image](https://user-images.githubusercontent.com/22783404/83104923-4e068e80-a0ec-11ea-9b29-2e2eac75f2c0.png)

**Comment by simaQ** [comment]
这个示例通过不符合图形语法生成图例的算法https://g2.antv.vision/zh/docs/manual/tutorial/legend，所以我们使用自定义图例来创建图例，但是自定义图例的接口并不提供图例相关的交互。

默认提供的图例相关的交互行为目前还没有很好得支持这种自定义图例。建议直接通过交互语法自己封装一套，
