### ISSUE TITLE
饼状图Lable的layout属性设置为limit-in-shape后，部分场景下0%的Label没有被隐藏

### ISSUE THREAD

**Issue by BlueSky1997AL** [antvis/G2#2508]
* **G2 Version**: 4.0.9
* **Platform**: macOS
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/28924863/83118323-cbd49500-a100-11ea-8dcd-7bd3aaf4198d.png)
* **CodePen Link**: [CodePen](https://codepen.io/blue_sky1997/pen/yLYdLgq?editors=0010)

**Comment by simaQ** [comment]
limit-in-shape 的算法不是用于饼图，因为这个是根据最后 shape 的 bbox 包围盒来计算的。

**Comment by simaQ** [comment]
这里你通过 label 回调，判断一下吧，如果值为 0 不显示即可。

**Comment by BlueSky1997AL** [comment]
好的，谢谢～
