### ISSUE TITLE
当图例较多时无法完整显示

### ISSUE THREAD

**Issue by onlinelemon** [antvis/g2#251]
* **G2 Version**:3.0
* **Platform**: Win PC
* **Mini Showcase(like screenshots)**:
![](https://raw.githubusercontent.com/onlinelemon/images/master/1.png)
只显示了前10个图例
* **CodePen Link**:

可否考虑水平或者垂直滚动图例

**Comment by leungwensen** [comment]
可以用 HTML，参考这个 demo： https://antv.alipay.com/zh-cn/g2/3.x/demo/other/streamgraph.html

以及这个文档： https://antv.alipay.com/zh-cn/g2/3.x/tutorial/legend.html#_使用-html-渲染图例

**Comment by luoluoluoluoluoluo** [comment]
请问解决了吗？
![image](https://user-images.githubusercontent.com/15343300/34564514-e3bf9870-f191-11e7-9aa7-7b43f8ecbf83.png)
该示例的html模板是指？

**Comment by chenmy0917** [comment]
> 可以用 HTML，参考这个 demo： https://antv.alipay.com/zh-cn/g2/3.x/demo/other/streamgraph.html
> 
> 以及这个文档： [https://antv.alipay.com/zh-cn/g2/3.x/tutorial/legend.html#_使用-html-渲染图例](https://antv.alipay.com/zh-cn/g2/3.x/tutorial/legend.html#_%E4%BD%BF%E7%94%A8-html-%E6%B8%B2%E6%9F%93%E5%9B%BE%E4%BE%8B)

示例和文档都404了，3.0是下架滚动图例了吗？
