### ISSUE TITLE
在changeData后，如果axis Y轴label变长，axis Y轴的位置不会进行自适应调整

### ISSUE THREAD

**Issue by lumozx** [antvis/G2#2514]
* **G2 Version**:4.0.8、4.0.9
* **Platform**:macos
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/22993852/83239553-a613c280-a1ca-11ea-8edf-1152aa6c6723.png)
![image](https://user-images.githubusercontent.com/22993852/83239568-aca23a00-a1ca-11ea-85e1-605c6fea38d6.png)

* **CodePen Link**:https://codesandbox.io/s/naughty-platform-32jer?file=/src/App.vue

**Comment by lumozx** [comment]
4.0.7无此问题

**Comment by windwhinny** [comment]
同样有此问题，4.0.9

**Comment by Slanemy** [comment]
4.0.15也有这个问题

**Comment by INTMIN** [comment]
4.0.15也有这个问题

**Comment by hustcc** [comment]
4.1.x 已经解决。亲自使用 issue 中的 live demo 测试
