### ISSUE TITLE
G24.0图例取消了html配置项，改如何实现3.0版本中自定义html的效果

### ISSUE THREAD

**Issue by NiuZW** [antvis/G2#2515]
![image](https://user-images.githubusercontent.com/66161915/83324522-57ccf500-a298-11ea-9b07-5544bd280e4c.png)

G23.0版本图例有containerTpl、itemTpl等html配置项。但4.0版本中取消了这些属性。那我改怎么去实现这种效果

**Comment by raisezhang** [comment]
想实现对 value 做一些格式化，比如  10000.00  格式化为  10,000.00 之类，  
之前是通过 itemTpl 实现，
那现在要格式化这个数据，好像也没有看到对 tooltip 上的 value 做格式化的 api， 
itemTpl 也删掉了，那现在应该怎么实现？

**Comment by hustcc** [comment]
从图表中回去数据，然后在图表的外部使用 html 去绘制右边这部分内容。
