### ISSUE TITLE
v4.0.7 图例项的 marker 图标的配置，如何配置成实心圆？

### ISSUE THREAD

**Issue by villasme** [antvis/G2#2516]
```js
{
   marker: {
    symbol: 'circle'
   }
}

```

**Comment by svonme** [comment]
使用自定义图例

{
  custom: true,
  items: [
    {
      name: 'name', 
      value: 'value', 
      marker: { 
        symbol: 'circle', 
        style: { 
          fill: 'red'
        }
      }
    }, {
      name: 'name', 
      value: 'value', 
      marker: { 
        symbol: 'circle', 
        style: { 
          fill: 'blue'
        }
      }
    }
  ]
}

**Comment by hustcc** [comment]
@Me-Momo 求回复一下这个 issue~

**Comment by hustcc** [comment]
目前暂不支持。后续支持。

**Comment by visiky** [comment]
![image](https://user-images.githubusercontent.com/15646325/106352200-f58f2d00-631b-11eb-86ee-8e6ab05208fa.png)

我自己试了一下，好像是可以的？

**Comment by visiky** [comment]
你遇到的问题应该是这个吧？实心是可以的，只是颜色无法du对应上
![image](https://user-images.githubusercontent.com/15646325/106352491-90890680-631e-11eb-8bef-340f259791d4.png)
