### ISSUE TITLE
图例分页+移动端页面下滑

### ISSUE THREAD

**Issue by zyd0113** [antvis/G2#2517]
两个问题
第一个问题，如何配置图例让图例不分页显示，显示不下得图例换行显示
![image](https://user-images.githubusercontent.com/52477117/83381715-f3cf3b80-a413-11ea-9907-d266dfdf6757.png)
第二个问题，在移动端使用antv时，在图表上进行下滑操作，页面不会向下移动，请问如何解决？

**Comment by Alisa0026** [comment]
这个分页箭头的颜色可以调整吗

**Comment by hustcc** [comment]
1. chart.legend({ flipPage：false })
2. 图表上会监听事件，去做 tooltip，所以没有只能吃掉事件了，可以在页面留下边距，用于下滑
3. 已经记录 https://www.yuque.com/antv/g2plot/egkghc
