### ISSUE TITLE
Help - Create gradient colors or add icons ?

### ISSUE THREAD

**Issue by ChristopherTrimboli** [antvis/G2#2533]
Example:

<img width="709" alt="Screen Shot 2020-06-02 at 10 17 10 AM" src="https://user-images.githubusercontent.com/27584221/83549875-d608e180-a4ba-11ea-9d63-520e13b0d82a.png">
<img width="892" alt="Screen Shot 2020-06-02 at 10 17 30 AM" src="https://user-images.githubusercontent.com/27584221/83549886-d99c6880-a4ba-11ea-80f9-d86d0aa42a05.png">

Is there a way to color charts like this?

Trying to use the `.color()` function.

I would like to do custom gradient color in Heatmap.

**Comment by hustcc** [comment]
see here: https://g2plot.antv.vision/zh/docs/api/graphic-style#%E9%85%8D%E7%BD%AE%E6%B8%90%E5%8F%98%E8%89%B2
