### ISSUE TITLE
Chart slider option set start and end value can not become effective when chart has rendered.

### ISSUE THREAD

**Issue by 1ncounter** [antvis/G2#2535]
* **G2 Version**: 4.0.7
* **Platform**: MacOS Chrome
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/19562558/83585878-8b9c6900-a57d-11ea-91ad-79c8a5e4194e.png)
![image](https://user-images.githubusercontent.com/19562558/83585908-a53db080-a57d-11ea-83f1-f465c4b81b67.png)
![image](https://user-images.githubusercontent.com/19562558/83585928-b5559000-a57d-11ea-9fb1-67bc09a7d83e.png)

* **CodePen Link**: https://g2.antv.vision/zh/examples/area/basic#area-large

Chart slider option set start and end value can not become effective when chart has rendered. The chart shows full range of graphs.

```js
chart.option('slider', {
      start: 0.1,
      end: 0.8,
      trendCfg: {
        isArea: false,
      },
   });
```

**Comment by hustcc** [comment]
fixed in 4.1.x
