### ISSUE TITLE
饼图/环图 Legend支持显示标签的数值

### ISSUE THREAD

**Issue by pslean** [antvis/g2#254]
![858235293430968990](https://user-images.githubusercontent.com/22412030/33694948-cb5e450a-db35-11e7-9f05-18396552ef05.jpg)

像上面图片这样，如果需要，我可以提PR，把legend的itemFormatter优化下

* **G2 Version**: 3.0.1
* **Platform**: windows 10

**Comment by pslean** [comment]
我找到方法了，可以用useHtml解决

**Comment by Aladdin-ADD** [comment]
希望这个能提供一个方法, eg:
```js

const data = [
  {name: 'n1', value: 0},
  {name: 'n2', value: 2},
];

//...

chart.legend('name', {
  alias: (val, index) => val+index
});
```
