### ISSUE TITLE
饼图 点legend全部点掉之后回不去了

### ISSUE THREAD

**Issue by lokbryxy** [antvis/G2#2540]
点击前：
![image](https://user-images.githubusercontent.com/31504231/83737844-22ece380-a686-11ea-8668-42a05865e4c3.png)
点击后：
![image](https://user-images.githubusercontent.com/31504231/83737902-35ffb380-a686-11ea-8c40-3e496c67ff71.png)
再点击已没有反应：
![image](https://user-images.githubusercontent.com/31504231/83737976-4ca60a80-a686-11ea-85c8-0b2b5cfb1e03.png)

**Comment by zetianul** [comment]
控制台报错了，去掉label就好了，我想把这个点击筛选的功能去掉，但是没找到配置，楼主有解决方法吗

**Comment by zetianul** [comment]
翻了一下issue，这个问题在4.0.8修复了 https://github.com/antvis/G2/issues/2430
