### ISSUE TITLE
按需引入时TS类型有问题

### ISSUE THREAD

**Issue by cg24** [antvis/G2#2543]
G2 Version: 4.0.9
CodePen Link： https://codesandbox.io/s/mystifying-surf-vuihq?file=/index.ts
![image](https://user-images.githubusercontent.com/10056850/84112891-2bfdfc00-aa5c-11ea-9b97-9659aabb0a24.png)

**Comment by hustcc** [comment]
如果你引入 core 的话，需要自己手动去按需引入 Geometry。可以参考 index.ts 中的写法。
