### ISSUE TITLE
手势事件不生效 

### ISSUE THREAD

**Issue by leegang** [antvis/G2#2544]
https://github.com/antvis/G2/commit/2c459853885b4f4e23c0d33c6542d5b83b527df8

因为我是产品客串前端，看了这个手势支持文档，不是很明白。有人可以帮忙稍作解释吗？

**Comment by leegang** [comment]
代码在这里。
https://codepen.io/leegang-the-vuer/pen/BajjXRE

**Comment by hustcc** [comment]
具体不明白的地方在哪里？

**Comment by leegang** [comment]
> 具体不明白的地方在哪里？

已经解决了。应该注册时间之后还要注册交互、并调用交互才有效，我第一次只注册了手势事件，所以没起作用。
