### ISSUE TITLE
维度值为cat类型，设置图表的趋势线，浏览器老崩溃，是怎么回事？？？

### ISSUE THREAD

**Issue by jing1810** [antvis/G2#2545]
<!DOCTYPE html>
        <html>
          <head>
            <meta charset="UTF-8">
            <title>趋势线测试</title>
          </head>
          <body>
            <div id="container" />
            <script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.g2-3.5.11/dist/g2.min.js"></script>
            <script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.10.2/dist/data-set.min.js"></script>
            <script>
          const data = [
            { year: '2002年1月', value: 10 },
            { year: '2003年1月', value: 20 },
            { year: '2004年1月', value: 50 },
            { year: '2005年1月', value: 40 },
            { year: '2006年1月', value: 50 },
            { year: '2007年1月', value: 20 },
            { year: '2008年1月', value: 25 },
            { year: '2009年1月', value: 70 },
            { year: '2010年1月', value: 120 },
            { year: '2011年1月', value: 140 },
            { year: '2012年1月', value: 80 },
            { year: '2013年1月', value: 250 },
            { year: '2014年1月', value: 280 },
            { year: '2015年1月', value: 400 },
            ];

                const ds = new DataSet();
                const dv1 = ds.createView().source(data);
                                dv1.transform({
                                  type: 'regression',
                                  method: 'polynomial',
                                  fields: [ 'year', 'value'],
                                  bandwidth: 0.1,
                                  as: [ 'x', 'y' ]
                                });

                const chart = new G2.Chart({
                container: 'container',
                forceFit: true,
                height: 500
                });

                
                const view1 = chart.view();
                        view1.axis(false);
                        view1.source(dv1,{
                            'x':{
                                type: 'cat', 
                            }
                        });
                        view1.line().position('x*y').style({
                          stroke: 'yellow',
                          lineDash: [ 3, 3 ]
                        })
                        .tooltip(false);

                    chart.source(data,{
                        'year':{
                            type:'cat'
                        }
                    });
            
                    chart.scale('value', {
                      min: 0
                    });
                    chart.scale('year', {
                        range: [ 0, 1 ]
                    });
                    chart.tooltip({
                        crosshairs: {
                            type: 'line'
                        }
                    });
                    chart.line().position('year*value');
                    chart.point().position('year*value')
                    .size(4)
                    .shape('circle')
                    .style({
                        stroke: '#fff',
                        lineWidth: 1
                    });
                    chart.render();

            </script>
          </body>
        </html>

**Comment by liyunfei0302** [comment]
+1

**Comment by hustcc** [comment]
对于 x 轴是分类字段的，暂时不要用这个辅助线。拟合代码中对于 x 轴是文本进行处理。
