### ISSUE TITLE
[feature] 3.x版本  南丁格尔玫瑰图能否支持两个维度的数据展示

### ISSUE THREAD

**Issue by muyucanqiu** [antvis/G2#2546]
南丁格尔玫瑰图
目前在官网只看到了以半径长短展示一个value的例子
但如果有两个value 能否其中一个以角度展示 另一个以半径展示

**Comment by leegang** [comment]
加一个view 就好了

**Comment by muyucanqiu** [comment]
> 加一个view 就好了

能给个简单的demo吗，文档着实不太好查，查不到。
数据格式是这样的[{name: 'a', data1: 10, data2: 20},{name: 'b', data1: 20, data2: 40}]
![1](https://user-images.githubusercontent.com/15388391/83987944-5eccc500-a974-11ea-95f9-d1f8fbbd8807.jpg)
期望的是data1数据以角度展示 data2数据以半径长短展示

**Comment by leegang** [comment]
之前看错了，你这个不是直接
 ```
chart.interval(). position('data1*data2');

就行了吗

**Comment by muyucanqiu** [comment]
> 之前看错了，你这个不是直接
> 
> ```
> chart.interval(). position('data1*data2');
> ```
> 
> 就行了吗

我可能没说太明白，下面是官网的例子 反应的是year*population 半径反应population的值的大小 但是我现在需要加一个指标进去 比如是age 我想用每个扇形的角度反应age的大小（官网的是均分的 每个扇形角度一致 无法满足我的需求）
![2](https://user-images.githubusercontent.com/15388391/84363126-d9117980-ac00-11ea-852f-e2ffc0393cae.jpg)

**Comment by leegang** [comment]
> > 之前看错了，你这个不是直接
> > ```
> > chart.interval(). position('data1*data2');
> > ```
> > 
> > 
> > 就行了吗
> 
> 我可能没说太明白，下面是官网的例子 反应的是year*population 半径反应population的值的大小 但是我现在需要加一个指标进去 比如是age 我想用每个扇形的角度反应age的大小（官网的是均分的 每个扇形角度一致 无法满足我的需求）
> ![2](https://user-images.githubusercontent.com/15388391/84363126-d9117980-ac00-11ea-852f-e2ffc0393cae.jpg)

对啊，你直接chart.interval(). position('age*population');

**Comment by leegang** [comment]
> > 之前看错了，你这个不是直接
> > ```
> > chart.interval(). position('data1*data2');
> > ```
> > 
> > 
> > 就行了吗
> 
> 我可能没说太明白，下面是官网的例子 反应的是year*population 半径反应population的值的大小 但是我现在需要加一个指标进去 比如是age 我想用每个扇形的角度反应age的大小（官网的是均分的 每个扇形角度一致 无法满足我的需求）
> ![2](https://user-images.githubusercontent.com/15388391/84363126-d9117980-ac00-11ea-852f-e2ffc0393cae.jpg)

你发的例子之所以是均分的，就是因为 year 这个字段是平均在增加的

**Comment by muyucanqiu** [comment]
> > > 之前看错了，你这个不是直接
> > > ```
> > > chart.interval(). position('data1*data2');
> > > ```
> > > 
> > > 
> > > 就行了吗
> > 
> > 
> > 我可能没说太明白，下面是官网的例子 反应的是year*population 半径反应population的值的大小 但是我现在需要加一个指标进去 比如是age 我想用每个扇形的角度反应age的大小（官网的是均分的 每个扇形角度一致 无法满足我的需求）
> > ![2](https://user-images.githubusercontent.com/15388391/84363126-d9117980-ac00-11ea-852f-e2ffc0393cae.jpg)
> 
> 你发的例子之所以是均分的，就是因为 year 这个字段是平均在增加的

age字段是需要做处理是吧，直接使用是不能正常显示的
![3](https://user-images.githubusercontent.com/15388391/84365348-e5e39c80-ac03-11ea-9e65-865e5e4741ca.jpg)

**Comment by leegang** [comment]
> > > > 之前看错了，你这个不是直接
> > > > ```
> > > > chart.interval(). position('data1*data2');
> > > > ```
> > > > 
> > > > 
> > > > 就行了吗
> > > 
> > > 
> > > 我可能没说太明白，下面是官网的例子 反应的是year*population 半径反应population的值的大小 但是我现在需要加一个指标进去 比如是age 我想用每个扇形的角度反应age的大小（官网的是均分的 每个扇形角度一致 无法满足我的需求）
> > > ![2](https://user-images.githubusercontent.com/15388391/84363126-d9117980-ac00-11ea-852f-e2ffc0393cae.jpg)
> > 
> > 
> > 你发的例子之所以是均分的，就是因为 year 这个字段是平均在增加的
> 
> age字段是需要做处理是吧，直接使用是不能正常显示的
> ![3](https://user-images.githubusercontent.com/15388391/84365348-e5e39c80-ac03-11ea-9e65-865e5e4741ca.jpg)

往前累加

**Comment by muyucanqiu** [comment]
> > > > > 之前看错了，你这个不是直接
> > > > > ```
> > > > > chart.interval(). position('data1*data2');
> > > > > ```
> > > > > 
> > > > > 
> > > > > 就行了吗
> > > > 
> > > > 
> > > > 我可能没说太明白，下面是官网的例子 反应的是year*population 半径反应population的值的大小 但是我现在需要加一个指标进去 比如是age 我想用每个扇形的角度反应age的大小（官网的是均分的 每个扇形角度一致 无法满足我的需求）
> > > > ![2](https://user-images.githubusercontent.com/15388391/84363126-d9117980-ac00-11ea-852f-e2ffc0393cae.jpg)
> > > 
> > > 
> > > 你发的例子之所以是均分的，就是因为 year 这个字段是平均在增加的
> > 
> > 
> > age字段是需要做处理是吧，直接使用是不能正常显示的
> > ![3](https://user-images.githubusercontent.com/15388391/84365348-e5e39c80-ac03-11ea-9e65-865e5e4741ca.jpg)
> 
> 往前累加

试了一下 这其实是个柱状图转换坐标系转过来的 所以你说的方法只不过是改变每个小扇形的位置 并不能改变小扇形的角度 本身的角度还是均分的。所以还是不行。

**Comment by hustcc** [comment]
使用 size 通道。

chart.interval().position(x*y).size(v).color(....
