### ISSUE TITLE
Edge endArrow 与数据点重叠

### ISSUE THREAD

**Issue by HenryQW** [antvis/G2#2548]
如何避免 edge 的 endArrow 与数据点重叠的问题？

![image](https://user-images.githubusercontent.com/5896343/83926643-590f8d80-a782-11ea-8247-1bdab88b49a6.png)

MVP:
https://stackblitz.com/edit/react-pgqkno?embed=1&file=src/index.js

**Comment by hustcc** [comment]
1. 计算数据，然后进行一些数据调整
2. 自定义 edge shape，去除数据点的像素大小

**Comment by hustcc** [comment]
另外，这样的图形，建议使用 antv/g6 / x6 进行绘制，能力和布局会强大很多
