### ISSUE TITLE
changeData数据由有到无时，之前的坐标轴数据还存在，不会清空

### ISSUE THREAD

**Issue by fancyboynet** [antvis/G2#2550]
* **G2 Version**: 4.0.9
* **Platform**: win10
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/fancyboynet/pen/bGEdPyb

点击demo中的changeData按钮可以看到效果

**Comment by INTMIN** [comment]
我这边也出现了这个问题， @fancyboynet 你们后来怎么解决的，我现在是强行每次渲染吧x轴整个数据以及chart全部更新，但是还是会遗留部分数据重叠

**Comment by fancyboynet** [comment]
@INTMIN 还没解决

**Comment by hustcc** [comment]
@INTMIN @fancyboynet 这个没有清空的不是坐标轴数据，而是你根据 data 添加的 annotation.text 信息。

你在 changeData 的时候，需要重新根据 data 生成 annotation。底层的 annotation 已经创建好了，不会在根据 data 去自动执行那个段 forEach 逻辑。

**Comment by hustcc** [comment]
```ts
const btn = document.querySelector('button')
btn.addEventListener('click', function(){
  chart.getController('annotation').clear(true); // clear annotation, true = includeOptions
  chart.changeData([])
})
```

**Comment by wsw2000** [comment]
annotation清除了，x轴怎么清除呢，没数据了，还是原来的x轴？
