### ISSUE TITLE
轴线line 缺少type配置能力

### ISSUE THREAD

**Issue by Leannechn** [antvis/G2#2551]
version 4.0.9
![image](https://user-images.githubusercontent.com/6812138/84006964-365bbf80-a9a2-11ea-85bd-51bcf7500f21.png)

![image](https://user-images.githubusercontent.com/6812138/84007025-50959d80-a9a2-11ea-9939-a432361c9b5b.png)

绘制如下雷达图无法实现
![image](https://user-images.githubusercontent.com/6812138/84007075-686d2180-a9a2-11ea-98dd-ce03731cd596.png)

**Comment by YYL1999** [comment]
这个好像是可以的吧

**Comment by hustcc** [comment]
可以的，极坐标下，圆弧和直线都支持。

**Comment by xiaoxiaodonghua** [comment]
怎么实现能贴一下代码嘛，也同问这个问题，极坐标系找了好久，示例图也没有展示这种图，4.x版本是有的
