### ISSUE TITLE
请问annotation标注怎么更新？

### ISSUE THREAD

**Issue by SophinQ** [antvis/G2#2552]
Version 4.0+
如 annotation.line() / annotation.dataMaker() 如何分别更新？
还有就是scale 在type为time时，设置最大值和最小值以及范围会报错。

**Comment by SophinQ** [comment]
第一条已解决

**Comment by spicyboiledfish** [comment]
请问第一条怎么解决的？

**Comment by hustcc** [comment]
第二条有具体的报错吗。

另外不建议使用 time scale，而是直接使用 cat 类型，time scale 的 bug 很多，会进行一个大重构。
