### ISSUE TITLE
v4 slider使用过程中遇到的问题

### ISSUE THREAD

**Issue by 15531400827** [antvis/G2#2553]
* **G2 Version**: 4.0.7

https://codesandbox.io/s/suspicious-fire-v4ikd

1、v4 slider 组件在堆叠柱状图 或者分组折线图中使用时没有以组为单位变化
看到其他issue也提过这个问题， 但是并没有找到解决方案。

2、而且以上示例拖动窗口会发现Slider没有自适应，V3中是没问题的

我觉得这两个是很明显的问题， 其他issue提了好久了没人解决， 是我的用法有问题吗

**Comment by YYL1999** [comment]
这个是指datazoom 也就是拖动条控制展示内容嘛

**Comment by 15531400827** [comment]
是的echarts的dataZoom， g2的slider， v3版本还是好的， v4变成内置的slider后拖动滑块柱子不是一组一组变化的， 感觉问题比较明显， 不知道为啥没人管唉。。。。

**Comment by YYL1999** [comment]
哦哦  我瞅瞅

**Comment by YYL1999** [comment]
这个问题我修复了 我提个PR吧

**Comment by 15531400827** [comment]
厉害， 折线图也是有这个问题的

**Comment by YYL1999** [comment]
> 厉害， 折线图也是有这个问题的

有codesandBox嘛 我测试看看折线图是否修复了

**Comment by 15531400827** [comment]
https://codesandbox.io/s/gallant-firefly-4r9tp?file=/index.html
我刚试了下这个现在好像没问题了，上个月用的时候是有问题的，但是拖动窗口slider还是不能自适应

**Comment by 15531400827** [comment]
拖动慢点会发现还是有问题， 同一个x上的两个点并不是同时消失同时出现， 还是一个一个的

**Comment by YYL1999** [comment]
> 拖动慢点会发现还是有问题， 同一个x上的两个点并不是同时消失同时出现， 还是一个一个的

这个看了下  我都修复了 晚点我提个PR

**Comment by 15531400827** [comment]
@YYL1999 非常感谢

**Comment by 15531400827** [comment]
@YYL1999 这PR一般要多久才能合啊， 看两个都提了一个星期了。。。

**Comment by legendstory** [comment]
> https://codesandbox.io/s/gallant-firefly-4r9tp?file=/index.html
> 我刚试了下这个现在好像没问题了，上个月用的时候是有问题的，但是拖动窗口slider还是不能自适应

您好问一下，没问题的版本是哪一个？我看最新的版本4.0.12仍然存在不能自适应的问题

**Comment by YYL1999** [comment]
> > https://codesandbox.io/s/gallant-firefly-4r9tp?file=/index.html
> > 我刚试了下这个现在好像没问题了，上个月用的时候是有问题的，但是拖动窗口slider还是不能自适应
> 
> 您好问一下，没问题的版本是哪一个？我看最新的版本4.0.12仍然存在不能自适应的问题

我的pr还没合进去呢  至于自适应的问题 你new Chart时加个autoFit参数就OK了

**Comment by 15531400827** [comment]
> > > https://codesandbox.io/s/gallant-firefly-4r9tp?file=/index.html
> > > 我刚试了下这个现在好像没问题了，上个月用的时候是有问题的，但是拖动窗口slider还是不能自适应
> > 
> > 
> > 您好问一下，没问题的版本是哪一个？我看最新的版本4.0.12仍然存在不能自适应的问题
> 
> 我的pr还没合进去呢 至于自适应的问题 你new Chart时加个autoFit参数就OK了
autoFit 我一直加着呢， 图表是可以自适应， 但是加上slider后 ， 那个slider 不会自适应。。。

**Comment by xiaoxiaoting** [comment]
滑块handlerStyle, img设置为空的问题，请问怎么解决？

**Comment by xiaoxiaoting** [comment]
@YYL1999 滑块handlerStyle, img设置为空的问题，请问怎么解决？

**Comment by xiaoxiaoting** [comment]
@YYL1999 有点急，求解答
