### ISSUE TITLE
legend 分页失效

### ISSUE THREAD

**Issue by qiaolei1973** [antvis/G2#2556]
* **G2 Version**: latest
* **Platform**: macos
* **Mini Showcase(like screenshots)**:  
![image](https://user-images.githubusercontent.com/20394320/84105263-5fd02600-aa4a-11ea-9fd0-685422ad7554.png)
![image](https://user-images.githubusercontent.com/20394320/84105269-65c60700-aa4a-11ea-9003-a29ed2db6c25.png)
![image](https://user-images.githubusercontent.com/20394320/84105273-6a8abb00-aa4a-11ea-917e-334a80613550.png)
页数变了，legend 显示不变

![image](https://user-images.githubusercontent.com/20394320/84105313-7f674e80-aa4a-11ea-8466-76fa8b514ca5.png)

* **CodePen Link**:

**Comment by qiaolei1973** [comment]
![image](https://user-images.githubusercontent.com/20394320/84105346-9a39c300-aa4a-11ea-9320-a031e3b5ff8d.png)

**Comment by paleface001** [comment]
哥们牛逼啊，内网钉钉的对话带着真名和花名就敢贴到github，怎么我是哪里得罪你了吗
