### ISSUE TITLE
legend 分页选择后没有更新条目

### ISSUE THREAD

**Issue by qiaolei1973** [antvis/G2#2558]
* **G2 Version**: latest
* **Platform**: macos
* **Mini Showcase(like screenshots)**: 
step1: 
![image](https://user-images.githubusercontent.com/20394320/84117891-cd894b80-aa64-11ea-9b2d-18d31efbfae9.png)
step2:
![image](https://user-images.githubusercontent.com/20394320/84117919-d5e18680-aa64-11ea-953a-d3270890fb84.png)
step3:
![image](https://user-images.githubusercontent.com/20394320/84117951-e134b200-aa64-11ea-9383-3f205876d6b5.png)

**Comment by paleface001** [comment]
没有复现出来，riddle提供一下复现案例吧
