### ISSUE TITLE
关于G2饼图配置问题

### ISSUE THREAD

**Issue by xiemingtao** [antvis/G2#2562]
我在网上浏览的时候偶然看到G2的图标组件,感觉UI风格挺好,所以在最新的项目中 我引入了G2,现在发现遇到几个问题.
1. 图表组件好像无法定义title,也就是图表标题.目前 我在使用饼图,无法使用
2. 饼图的颜色分配,如果一个自定义颜色其他的如果没有自定义,其他分类的颜色 颜色就是相同的,没有自动分配颜色
![微信图片_20200610160943](https://user-images.githubusercontent.com/39074823/84243501-e19c7e00-ab34-11ea-96bf-1d7a7a9c3d8c.png)
![微信截图_20200610161050](https://user-images.githubusercontent.com/39074823/84243577-fd078900-ab34-11ea-85c9-2df0ff3fe594.png)
麻烦大佬们解决下

**Comment by Me-Momo** [comment]
1）无法设置 title 的可以提供复现demo吗
2）color 一旦使用自定义的字段映射，其他的也需要自己去处理，if item 2 return color2 等等
