### ISSUE TITLE
【bug】形如'2020.1.1'格式的日期数据在Firefox中会报错

### ISSUE THREAD

**Issue by TimZhang2090** [antvis/G2#2565]
* **G2 Version**: 官网线上
* **Platform**: Windows

![image](https://user-images.githubusercontent.com/8032719/84259154-9c834680-ab4a-11ea-9895-a1c64e9ef2c2.png)

![image](https://user-images.githubusercontent.com/8032719/84259169-a311be00-ab4a-11ea-9415-b9c28e5ef482.png)

Firefox版本：73.0.1 (64 位)

**Comment by hustcc** [comment]
试试最新版本 4.1.x 应该已经解决了。
