### ISSUE TITLE
Axis labels blocked by Area

### ISSUE THREAD

**Issue by MarkLyck** [antvis/G2#2567]
* **G2 Version**:4.0.9
* **Mini Showcase(like screenshots)**:
<img width="821" alt="Screen Shot 2020-06-10 at 7 43 25 PM" src="https://user-images.githubusercontent.com/6841110/84332534-c6d90200-ab52-11ea-931b-1f632afb93d1.png">

I want my Axis labels to be `white` on top of the dark gray area chart I have.

However, I haven't found any method to be able to render the label on top of the chart area instead of underneath it.

In the above screenshot the labels are `red` to demonstrate how it's being covered by the 2 areas.

Please fix this so labels can show on top of charts in their proper color without being obscured.

**Comment by hustcc** [comment]
```ts
chart.axis('year', {
  top: true,
  verticalFactor: 1
});
```

but now, `top` does not work, I will fix it.

**Comment by hustcc** [comment]
@MarkLyck axis default in the bottom layer is by design.

You can use chart.annotation to get your design.

```ts
// 添加文本标注
data.forEach((item) => {
  chart
    .annotation()
    .text({
      position: [item.type, item.value],
      content: item.value,
      style: {
        textAlign: 'center',
      },
      offsetY: -30,
    })
    .text({
      position: [item.type, item.value],
      content: (item.percent * 100).toFixed(0) + '%',
      style: {
        textAlign: 'center',
      },
      offsetY: -12,
    });
});
chart.render();
```
