### ISSUE TITLE
Slider可更新吗？HandlerStyle里配置图片无效

### ISSUE THREAD

**Issue by SophinQ** [antvis/G2#2568]
G2 Version 0.4.9
请问slider更新配置项吗？比如start，end。
handlerStyle里配置图片无效，还是显示默认图片。如handlerStyle{ img: require('../'), width: 10, height: 10 }

另外，我发现tooltip在图表更新的时候还是会有空内容的情况。

**Comment by xiaoxiaoting** [comment]
图片设置为空的问题，我也遇到了，请问解决了嘛？
