### ISSUE TITLE
slider如何更新？handlerStyle里配置图片无效

### ISSUE THREAD

**Issue by SophinQ** [antvis/G2#2569]
G2 Version 0.4.9

配置handlerStyle为 { img: require('../'), width: 10, height: 10 }，还是显示默认配置的图片。
还有就是slider如何更新，是否可以单独拿出来不作为内置的组件进行配置呢？

另外就是之前我有看到tooltip会出现空内容的情况，也是在更新图表后，会出现一瞬间的空内容。

**Comment by xiaoxiaoting** [comment]
图片设置为空的问题，我也遇到了，请问解决了嘛？

**Comment by hustcc** [comment]
4.x 的 slider 暂时不支持 img 配置。ref https://github.com/antvis/G2/issues/2946
