### ISSUE TITLE
G2 坐标轴type: pow 抛异常

### ISSUE THREAD

**Issue by iiicon** [antvis/G2#2573]
* **G2 Version**:  V4.0.8
* **Platform**: PC
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/19875237/84482553-8a301680-acca-11ea-9671-df7dcfba00b7.png)

* **CodePen Link**: 

* **desc**: 图表为指数型坐标轴 type:'pow'的时候，如果数据为空，会报错

**Comment by iiicon** [comment]
这个bug依然在

**Comment by hustcc** [comment]
@iiicon 我在 G2 官网测试数据为空情况下，y scale type 设置 pow 没有问题。麻烦确认一下~~~
