### ISSUE TITLE
通过cdn的形式引入g2,如何引用createThemeByStylesheet

### ISSUE THREAD

**Issue by babycannotsay** [antvis/G2#2581]
* **G2 Version**:4.0.9
* **Platform**:mac
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

线上demo，想通过createThemeByStylesheet，直接更改已有主题的部分属性样式

**Comment by hustcc** [comment]
不建议使用这个内部 API，可能会后续导致不兼容。
