### ISSUE TITLE
分组柱状图设置size后marginRatio失效问题解决了吗？

### ISSUE THREAD

**Issue by muyucanqiu** [antvis/G2#2582]
使用的3.x的版本 分组柱状图设置size后 两个柱子就不能紧挨着了 设置的marginRatio为0不生效了 请问这个问题解决了吗。
我这边的需求是下面这样的图
![企业咚咚20200616220237](https://user-images.githubusercontent.com/15388391/84784645-26388580-b01d-11ea-8a4c-d6b773bf7707.jpg)
但是当我设置size后中间就出现了间隔
![企业咚咚20200616220403](https://user-images.githubusercontent.com/15388391/84784804-508a4300-b01d-11ea-9e2b-572d818c00fb.jpg)
请问有办法解决这个问题吗？

**Comment by zyr940427** [comment]
+1

**Comment by hustcc** [comment]
相同 https://github.com/antvis/G2/issues/2582 还没有解决
