### ISSUE TITLE
官网Slider演示示例初次渲染的区域和配置的不一致

### ISSUE THREAD

**Issue by zhangyu1818** [antvis/G2#2584]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
https://g2.antv.vision/zh/examples/area/basic#area-large

```
   chart.option('slider', {
      start: 0.1,
      end: 0.8,
      trendCfg: {
        isArea: false,
      },
    });
```

官网配置的是从0.1到0.8，但是实际显示的是全部，轻微拖动一下slider条就可以看出来

初次渲染的区域不应该是配置的区域吗
是我的理解不够，还是这是bug？

**Comment by Gavin-Gong** [comment]
我也发现这个问题了，我觉得是 bug。

**Comment by bald-newcomer** [comment]
这个bug，基本上slider功能就没法用了

**Comment by elvira1112** [comment]
chart.getController('slider').onValueChanged([0, 0.3]);

可以自己在 chart.render(); 后调用一次 valueChanged 方法。
