### ISSUE TITLE
文档中view有legend方法，但是给view设置legend并没有作用。

### ISSUE THREAD

**Issue by yeqisong** [antvis/G2#2586]
根据官方demo修改，
import { Chart } from '@antv/g2';

const data = [
  { name: 'London', 月份: 'Jan.', 月均降雨量: 18.9 },
  { name: 'London', 月份: 'Feb.', 月均降雨量: 28.8 },
  { name: 'London', 月份: 'Mar.', 月均降雨量: 39.3 },
  { name: 'London', 月份: 'Apr.', 月均降雨量: 81.4 },
  { name: 'London', 月份: 'May', 月均降雨量: 47 },
  { name: 'London', 月份: 'Jun.', 月均降雨量: 20.3 },
  { name: 'London', 月份: 'Jul.', 月均降雨量: 24 },
  { name: 'London', 月份: 'Aug.', 月均降雨量: 35.6 },
  { name: 'Berlin', 月份: 'Jan.', 月均降雨量: 12.4 },
  { name: 'Berlin', 月份: 'Feb.', 月均降雨量: 23.2 },
  { name: 'Berlin', 月份: 'Mar.', 月均降雨量: 34.5 },
  { name: 'Berlin', 月份: 'Apr.', 月均降雨量: 99.7 },
  { name: 'Berlin', 月份: 'May', 月均降雨量: 52.6 },
  { name: 'Berlin', 月份: 'Jun.', 月均降雨量: 35.5 },
  { name: 'Berlin', 月份: 'Jul.', 月均降雨量: 37.4 },
  { name: 'Berlin', 月份: 'Aug.', 月均降雨量: 42.4 },
];

const chart = new Chart({
  container: 'container',
  autoFit: true,
  height: 500,
});

//chart.data(data);
//chart.scale('月均降雨量', {
//  nice: true,
//});
chart.tooltip({
  showMarkers: false,
  shared: true,
});

var view = chart.createView();
view.data(data);

view
  .interval()
  .position('月份*月均降雨量')
  .color('name')
  .adjust([
    {
      type: 'dodge',
      marginRatio: 0,
    },
  ]);
chart.legend(false);
view.legend({
  position: 'bottom'
})

chart.interaction('active-region');

chart.render();

**Comment by hustcc** [comment]
目前确实是对于非根 view，不处理 legend

```ts
const isRootView = this.view.getRootView() === this.view;
// 非根 view，不处理 legend
if (!isRootView) {
  return;
}
```

会存在其他很多的问题。
