### ISSUE TITLE
4.x如何获取图例项是否选中？

### ISSUE THREAD

**Issue by candy-Tong** [antvis/G2#2589]
在4.x文档中的LegendCfg，已找不到onclick的选项。
在文档也没看到如何获得图例选项是否选中，想用自定义图例，控制折现是否显示。
我在legend-item:click 事件的event对象中，找到了一个unchecked属性，但是有没有更加简单的方法可以获取到是否选中的值？
```
chart.on('legend-item:click', ev => { console.log(ev); });
```
![image](https://user-images.githubusercontent.com/20377280/84986106-85f37580-b170-11ea-8ca8-ce2a34ea1334.png)

* **G2 Version**:
4.x
* **Platform**:
win10
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by hustcc** [comment]
确实目前没有提供一个 api 来判断是否选中图例，你可以根据截图中的变量来处理。
