### ISSUE TITLE
折线图，坐标轴设置timeCat  showLast  x轴会发生重叠现象

### ISSUE THREAD

**Issue by zyrepo** [antvis/G2#2592]
* **G2 Version**: 4.0.7^
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by zyrepo** [comment]
![image](https://user-images.githubusercontent.com/22114645/85245630-c9a0f480-b47a-11ea-904c-ed61efde9978.png)

**Comment by MrBiscuit** [comment]
这个我看demo里是将其中一个轴的grid设为null了

**Comment by hustcc** [comment]
有具体复现的代码或者 live demo 吗？

**Comment by ColinChen2** [comment]
我也遇到了type:"timeCat"
![Screen Shot 2020-10-26 at 5 38 15 PM](https://user-images.githubusercontent.com/7310875/97156782-28bca000-17b2-11eb-88f4-07c0dfd18efb.png)

可以设置不显示最后一个tick的label?

**Comment by zqlu** [comment]
在 component 层修复：https://github.com/antvis/component/pull/203

**Comment by zyrepo** [comment]
@zqlu  这个现在的逻辑是什么呢， 如果离得太近显示，还是最后一个固定距离不会重叠了

**Comment by zyrepo** [comment]
@zqlu 最好是 使用showlast的时候，最后一个固定在那里，不要去算距离

**Comment by zqlu** [comment]
> @zqlu 最好是 使用showlast的时候，最后一个固定在那里，不要去算距离

这个逻辑是看怎么配置 label 的 layout

1. 默认配置下，会开启轴标签的自动隐藏，会首先对轴标签均匀抽样进行隐藏，然后对不均匀的 tick/label (这个 issue 的 timeCat 情况) 进行再次的重叠判断，隐藏发生重叠的轴标签：

```
xAxis: {
  label: {
    autoHide: true
}
```

2. 在其他的配置下，会根据不同的 autoHide 逻辑来判断：
```
xAxis: {
  label: {
    // 可选配置： 'reserveFirst', 'reserveLast', 'reserveBoth', 'equidistanceWithReverseBoth'
    autoHide: 'equidistanceWithReverseBoth'
}
```
不同的配置对这个issue中的轴标签重叠处理会稍有不同

**Comment by zyrepo** [comment]
@zqlu  强，感谢
