### ISSUE TITLE
‘点图’ 不能触发 ‘更新动画’ (Point chart doesn't trigger update animation)

### ISSUE THREAD

**Issue by RephoneYin** [antvis/G2#2596]
* **G2 Version**: 4.0.11
* **Platform**: Mac OS, Chrome 83
* **Mini Showcase(like screenshots)**:
![屏幕录制2020-06-23 下午5](https://user-images.githubusercontent.com/8410037/85390486-76fb3180-b57b-11ea-9d65-2c10c24dc4dc.gif)

* **CodePen Link**: None

在使用过程中， 当为点图设置自定义动画的时候， 可以触发"appear", "leave", "enter", 但是不能触发"update"。

以官方的“动态图表”(https://g2.antv.vision/zh/examples/gallery/dynamic#dynamic-bar ) 案例为例,做了一个GIF，希望可以以此能表达自己的意思。 

不知是自己使用有误， 还是对G2的理解有误。

 通过```console.log()``` 打印调试了一下， 发现确实如此。

以下为代码片段：
```javascript

registerAnimation('point-appear', (element, animateCfg, cfg) => {
    console.log("point-appear");
});
registerAnimation('point-enter', (element, animateCfg, cfg) => {
    console.log("point-enter");
});
registerAnimation('point-update', (element, animateCfg, cfg) => {
    console.log("point-update");
});
registerAnimation('point-leave', (element, animateCfg, cfg) => {
    console.log("point-leave");
});

chart.point()
    .position("countryName*value")
    .size(20)
    .shape("circle")
    .animate({
        appear: {
            animation: 'point-appear',
            delay: 0,
            duration: 1000,
            easing: 'easeLinear'
        },
        enter: {
            animation: 'point-enter',
            delay: 0,
            duration: 1000,
            easing: 'easeLinear'
        },
        update: {
            animation: 'point-update',
            delay: 0,
            duration: 1000,
            easing: 'easeLinear'
        },
        leave: {
            animation: 'point-leave',
            delay: 0,
            duration: 1000,
            easing: 'easeLinear'
        },
    })
```
输出结果：
![image](https://user-images.githubusercontent.com/8410037/85390779-e07b4000-b57b-11ea-8237-3b340af60028.png)

期待你们的评论， 万分感谢！
![image](https://user-images.githubusercontent.com/8410037/85391606-fb9a7f80-b57c-11ea-8168-9ee42396b110.png)

**Comment by hustcc** [comment]
update 是在 changeData 的时候才会调用。
