### ISSUE TITLE
Grid API malfunction

### ISSUE THREAD

**Issue by MrBiscuit** [antvis/G2#2597]
* **G2 Version**: 4.0
* **Platform**: Web

All attributes on grid doesn’t work aside from visibility, this is frustrating since its default opacity is too low to display clearly on dark backgrounds, and the documentation ends before touching on grid.

My team have tried setting all the style(object) properties on grid to no avail.
Expected a fix on the grid API as well as the documentation.

**Comment by DarrenPei** [comment]
```js
chart.axis("sold", {
  grid: {
    line: {
      style: {
        lineDash: [3, 3],
        lineWidth: 1,
        stroke: "red"
      }
    }
  }
});
```
Please see the Demo 
https://codesandbox.io/s/vibrant-rosalind-guhgq?file=/src/index.js

API 
https://g2.antv.vision/zh/docs/api/axis
