### ISSUE TITLE
padding为‘auto’，window resize触发图表重新渲染时，coordinateBBox计算错误

### ISSUE THREAD

**Issue by BuggMaker** [antvis/G2#2598]
* **G2 Version**: 4.0.10
* **Platform**: MacOS, Chrome 83.0.4103.106
* **Mini Showcase(like screenshots)**:
![g2_rerender_coordinate_bbox_error](https://user-images.githubusercontent.com/25820633/85493733-03543580-b60a-11ea-90d8-e9d767b7e880.gif)

* **CodePen Link**: 
通过debug源码，发现在layout部分计算coordinateBBox的时候有点问题，会导致坐标轴超出图表范围并压盖图例（position：bottom）。
![image](https://user-images.githubusercontent.com/25820633/85493051-c76ca080-b608-11ea-81c6-375256891823.png)

**Comment by hustcc** [comment]
已经解决了。
