### ISSUE TITLE
请问目前有哪些产品用了G2，你们和echarts有什么优势，有什么分别

### ISSUE THREAD

**Issue by iloveyo123u1** [antvis/g2#26]

**Comment by hustcer** [comment]
搭车问下有没有源码开源计划？

**Comment by dxq613** [comment]
开源是肯定要的，只是我们先满足内部业务，继续开发1，2个版本后，再考虑开源。

跟Echarts 最大的差异在于可视化的出发点不太一样
* G2 全部以数据和图形的映射为核心，只要想清楚了数据的流转，数据和图形的映射，就可以绘制出你想要的任何图形
* G2的语法偏向于语义组合，再搭配自定义shape的能力，扩展性更强，配置项也会少很多
* 本来是为了在线数据分析开发的图形语法，所以对统计分析做了大量的支持，后面也会探索统计、回归、聚类等数据分析领域的结合点

跟echarts 比不足的地方

* 交互比较弱，插件功能不足，demo跟业务有一定的距离
* 大家都熟悉了配置的模式，这种组合型的语法需要一定时间的学习成本

**Comment by hustcer** [comment]
期待进一步完善交互和开源。

**Comment by dxq613** [comment]
好的，我们也在尽力争取开源
