### ISSUE TITLE
六边形分箱 legend bug

### ISSUE THREAD

**Issue by arcthur** [antvis/g2#260]
![image](https://user-images.githubusercontent.com/322331/33715894-21485dc6-db8f-11e7-9cfd-9d5de04d41a2.png)

六边形分箱 demo 拖动 legend 会出现这种值

**Comment by leungwensen** [comment]
重现步骤和代码是怎么样的？官网那个例子我没试出来

**Comment by arcthur** [comment]
反复拉那个 legend，有一瞬间会出现一个长串，在靠近 0 附近，就试着很慢拖动就出现了

**Comment by dxq613** [comment]
这个其实不是bug ，由于滑动条是连续的，理论上可以拖出任何值，这块可以看看，是否支持 step 功能，就是拖拽出来的数字不是任意的。
