### ISSUE TITLE
antv/G2的API文档真的需要改改了。

### ISSUE THREAD

**Issue by spicyboiledfish** [antvis/G2#2602]
请麻烦将antv/G2的API文档规范，什么属性对应什么效果或者样式，案例是什么。麻烦清晰的整理表达出来。目前的文档想找一个属性真的很难找，连google都很难去搜到相关的踩坑经验，真的很炸头。
之前是一直用echarts的，看到G2的交互效果很赞，另外数据格式比较友好才入坑的，不过这个文档确实让人头疼。
比方，我现在因为饼图，上面的label重叠了，想找一个属性可以解决此问题，例如echart里面的avoidLabelOverlap。但是试了fixed-overlap，limitInShape，fixedOverlap，overlap。这四种都无法解决。很头疼。而且竟然没有可以设置饼图最小比例的属性，比方echart里面的minAngle。

![460C6E9C-59CF-470D-A263-7A21F40343F1](https://user-images.githubusercontent.com/18587093/85517034-71602300-b631-11ea-94d9-06f3bf4561d4.png)

`registerTheme('pieTheme', {
      colors10: ColorTheme,
    });

    this.chart = new Chart({
      container: this.pieRef.current,
      autoFit: true,
      height: 300,
      width: 500,
    });

    this.chart.coordinate('theta', {
      radius: 0.75,
    });

    this.chart.scale('percent', {
      formatter: (val: any) => {
        val = (val * 100).toFixed(2) + '%';
        return val;
      },
    });

    this.chart.tooltip({
      showTitle: false,
      showMarkers: false,
    });

    this.chart
      .interval()
      .position('percent')
      .color('value')
      .label('percent', {
        content: (data: any) => {
          return `${data.value}`;
        },
      })
      .adjust('stack');
    this.chart.interaction('element-active');
    this.chart.theme('pieTheme');
  };`

**Comment by kurilee** [comment]
这个文档真心需要优化

**Comment by Echo-pain-killer** [comment]
这个估计是BUG

**Comment by Echo-pain-killer** [comment]
我也遇到了label重叠的问题，把版本降成4.0.7就可以

**Comment by Rabbitzzc** [comment]
+1

**Comment by ArranZeyuWang** [comment]
关于文档的问题，目前已经上线了新版的[API文档](https://g2.antv.vision/zh/docs/api/chart)，目前还在继续完善更新。

教程文档也在同步迭代，预计八月中会上线一个针对目前问题全局优化的版本。

**Comment by unnhao** [comment]
theme到底怎麼用阿，我的Area Chart都改不了顏色 太難了我

**Comment by simaQ** [comment]
> theme到底怎麼用阿，我的Area Chart都改不了顏色 太難了我

具体什么问题

**Comment by Me-Momo** [comment]
具体问题是饼图标签问题还是主题还是其他

**Comment by unnhao** [comment]
> > theme到底怎麼用阿，我的Area Chart都改不了顏色 太難了我
> 
> 具体什么问题

沒事了，犯蠢了我，謝謝。

**Comment by hustcc** [comment]
重复 issue，具体看：https://github.com/antvis/G2/issues/2804#issuecomment-693764222
