### ISSUE TITLE
tooltip初始false，后续更新配置也不能显示

### ISSUE THREAD

**Issue by BuggMaker** [antvis/G2#2603]
* **G2 Version**: 4.0.11
* **Platform**: MacOS
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/25820633/85518188-9012e980-b632-11ea-8977-29ea5290d255.png)
![image](https://user-images.githubusercontent.com/25820633/85518216-986b2480-b632-11ea-8d61-37d408c3e4c4.png)
![image](https://user-images.githubusercontent.com/25820633/85518486-dd8f5680-b632-11ea-9dda-011591c7744f.png)

* **CodePen Link**:

 tooltip controller里面的isVisible属性只初始化了一次，后续更新没有跟着更新；结果tooltip初始化为false，后续更新tooltip配置之后，isVisible没有更新为true，所以在showTooltip的时候直接return了，导致tooltip显示不出来。

**Comment by hustcc** [comment]
已经修复。
