### ISSUE TITLE
关于容器元素添加transform scale变形，鼠标交互错位的问题，修复了吗？用4.x版本的依旧有这个问题

### ISSUE THREAD

**Issue by fanaiai** [antvis/G2#2605]
关于容器元素添加transform scale变形，鼠标交互错位的问题，修复了吗？用4.x版本的依旧有这个问题，需要专门调用什么方法么？文档里没有说明

**Comment by fancyboynet** [comment]
我也遇到同样的问题了，希望能尽快修复

**Comment by Me-Momo** [comment]
这个问题应该解决了，等发正式版
