### ISSUE TITLE
如何绘制一个空数据的柱状图

### ISSUE THREAD

**Issue by spicyboiledfish** [antvis/G2#2608]
现在想要一个展示一个空数据的柱状图。类似于下面这种的，带网格的。但是我试了grid属性，没有办法绘制，必须至少得有一条数据有值才行。另外会跟之前的有数据的图有冲突。
![image](https://user-images.githubusercontent.com/18587093/85941340-e9418c80-b954-11ea-8211-68900de8790e.png)
`
grid: {
          line: {
              type: 'line',
              style: {
                fill: '#fc5f20',
                stoke: '#fc5f20',
              }
          }
      },`

**Comment by hustcc** [comment]
空数据的时候，自动生成的 x y scale 都是空的。所以在空数据的时候，需要置顶 x y scale 的内容。具体为：

```ts
chart.scale('x_field', { 
  values: ['03:03', ...],
});

chart.scale('y_field', {
  min: -1,
  max: 1,
})
```
