### ISSUE TITLE
changeData is not working properly with candlestick

### ISSUE THREAD

**Issue by karimhossenbux** [antvis/g2#261]
* **G2 Version**: 3.0.0 and 3.0.2-beta1
* **Platform**: Chrome Version 62.0.3202.94
* **CodePen Link**: https://codepen.io/karimhossenbux/pen/GObrwG?editors=0011

changeData() is not working properly when I try to update chandlestick chart.
There is a codepen for testing purpose. There is a setInterval which should update the data adding 2 more candles but nothing is happening.

```
setInterval(function () {
  // This will add 3 more green candles 
  console.log('changeData')
  chart.changeData(updatedData)
}, 5000)
```

Am I doing something wrong? Or is this a bug?

Thank for helping and this awesome library!

**Comment by karimhossenbux** [comment]
doing `dv.source(updatedData)` in the setInterval update the chart, it that normal behaviour?

**Comment by leungwensen** [comment]
You drew the plot with `kView`, not `chart`, so changing the data for `chart` is meaningless.

try `kView.changeData()`

**Comment by karimhossenbux** [comment]
Thanks for you help!
I've tried with `kView.changeData()` but makes everything invisible. The tooltip hover is still working .

* **New codepen:** https://codepen.io/karimhossenbux/pen/vWqboK?editors=0011

**Comment by leungwensen** [comment]
you should keep the data structure the same (the new data does not have `range` field).

simplest solution: `kView.changeData(data) => dv.source(data)`

```js
setInterval(function () {
  // This will add 3 more green candles 
  dv.source(updatedData);
  // kView.changeData(updatedData)
}, 5000)
```

**Comment by karimhossenbux** [comment]
Thanks! I'll will hack around that 👍
