### ISSUE TITLE
v4版本的文档何时可以更新下呢？

### ISSUE THREAD

**Issue by fanaiai** [antvis/G2#2610]
原来用的是v3，文档还算较为清晰，近期想要升级到v4，完全没法入手，不知道哪些属性还有效哪些是无效的，我是做bi可视化系统，当初选库的时候觉得G2的语法更灵活所以选的G2，那时候还没有发布4.x，现在想尝试升级根本升不了，有那么些后悔用G2了

**Comment by spicyboiledfish** [comment]
+1 同样后悔。项目已经做到大半了。下个项目不想再用G2了

**Comment by simaQ** [comment]
非常抱歉！目前文档正在优化，优化之前我们会快速在语雀上快速上一个可用版本，最迟下周！

**Comment by BBSQQ** [comment]
现API文档部分已全面更新上线，一些内容也会持续补充更新。
