### ISSUE TITLE
柱状图设置了adjust之后怎么用修改legend内容？

### ISSUE THREAD

**Issue by curryhh** [antvis/G2#2613]
设置了一个adjust之后会将adjust的name设为legend，之后又设置了一条折现图line，我想line也出现在在legend，怎么实现呢？

* **G2 Version**:3.4.10
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by hustcc** [comment]
需要使用自定义图例：

```ts
chart.legend({
  custom: true,
  items: [...]
})

```
