### ISSUE TITLE
饼图的主题色值theme小概率不生效，饼图的色值都变成了黑色

### ISSUE THREAD

**Issue by spicyboiledfish** [antvis/G2#2614]
![image](https://user-images.githubusercontent.com/18587093/86102348-ff368500-baed-11ea-8823-32c66795d787.png)
`
const ColorTheme = [
  '#05a6ee',
  '#ed808c',
  '#f3a290',
  '#c8c6fd',
  '#e5c6fd',
  '#fbbb27',
  '#4cdfc0'];
registerTheme('pieTheme', {
      colors10: ColorTheme,
    });
`

**Comment by Me-Momo** [comment]
有复现的 demo 吗，这边 [demo](https://codepen.io/kasmine/pen/vYLrzWo) 是可以的

**Comment by spicyboiledfish** [comment]
> 有复现的 demo 吗，这边 [demo](https://codepen.io/kasmine/pen/vYLrzWo) 是可以的

我找到原因了，是用了这句this.chart.forceFit();导致的。如果删掉就会好了。因为会经常遇到饼图的图例会超出容器外遮挡住，一刷新下就会好，多次刷新就又会出现问题。

**Comment by hustcc** [comment]
> > 有复现的 demo 吗，这边 [demo](https://codepen.io/kasmine/pen/vYLrzWo) 是可以的
> 
> 
> 
> 我找到原因了，是用了这句this.chart.forceFit();导致的。如果删掉就会好了。因为会经常遇到饼图的图例会超出容器外遮挡住，一刷新下就会好，多次刷新就又会出现问题。

理论上这个不会和主题又啥关系，如果还能出现，求一个 demo。
