### ISSUE TITLE
柱状图的高亮，可以通过代码指定参数高亮吗

### ISSUE THREAD

**Issue by TwoPens** [antvis/G2#2616]

**Comment by TwoPens** [comment]
我想通过参数过滤之类的，指定某些柱子高亮

**Comment by Me-Momo** [comment]
使用setState

**Comment by leochen-g** [comment]
> docs: https://g2.antv.vision/zh/docs/manual/concepts/element/#element-%E8%81%8C%E8%B4%A3
> 
> 1. 如何获取 Element 实例
> 
> ```ts
> // 创建 Interval
> const interval = chart.interval().position('x*y');
> 
> chart.render();
> 
> // 获取 Interval 下的 Element 实例
> const elements = interval.elements;
> 
> // 根据特定的条件查找 Element 实例
> const someElements = interval.getElementsBy((element) => {
>   const data = element.getData();
>   return data.x === 'a';
> });
> ```
> 
> 2. 通过 Element 操纵图形状态
> 
> ```ts
> const interval = chart.interval().position('x*y');
> 
> // 将 Interval 的第一个 Element 实例设置为 active 状态
> interval.elements[0].setState('active', false);
> ```
> 
> 3. 修改 Element 图形元素的状态样式
> 
> ```ts
> chart
>   .interval()
>   .position('x*y')
>   .state({
>     active: {
>       style: {
>         lineWidth: 2,
>         stroke: '#000',
>       },
>     },
>   });
> ```

饼图的话如何操作呢，按照这个试了一下elements都是空

**Comment by mrh-code-star** [comment]
此处element的所有操作都在调用render方法后才会有数据
