### ISSUE TITLE
Barchart rendering as linear scale with (string,count) where string is integer

### ISSUE THREAD

**Issue by recaph** [antvis/G2#2618]
* **G2 Version**: 3.1.2
* **Platform**: Angular 4.2.4
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/704289/86204981-6ffd9180-bb2e-11ea-82b2-d3ec0db06e4a.png)
* **CodePen Link**: none

I am trying to create a simple bar chart from the values of an integer column. I want to display the count of each integer value. But the chart is getting created with both axes as a linear scale instead of just count. 

Chart with following input renders as :
```
       const chatObjects= chartLabelsTemp.map(function (d, i) {
      return {
        ERRCODE: d,
        count: chartDataTemp[i] || 0
      };
    });

    const sortedChartObjects = chatObjects.sort(function (a, b) {
      return b.count - a.count;
    });

```
![image](https://user-images.githubusercontent.com/704289/86205749-48a7c400-bb30-11ea-85a1-133d3832a7c9.png)

While Chart with the following input renders correctly:

```
    const chatObjects= chartLabelsTemp.map(function (d, i) {
      return {
        ERRCODE: d + "",                                                                         <----------- change
        count: chartDataTemp[i] || 0
      };
    });

    const sortedChartObjects = chatObjects.sort(function (a, b) {
      return b.count - a.count;
    });
```
![image](https://user-images.githubusercontent.com/704289/86205850-9290aa00-bb30-11ea-9440-e806ee880fc6.png)

Can you suggest a solution?

**Comment by hustcc** [comment]
强制制定为分类，而不是自动识别为连续

chart.scale('xfield', { type: 'cat' });
