### ISSUE TITLE
图标数据改变，渲染出现多条折线的问题

### ISSUE THREAD

**Issue by yanruoxinb** [antvis/g2#262]
首先我ng-init的时候定义了一个图标，
       $scope.chart = new G2.Chart({
            container: 'mountNode',
            forceFit: true,
            height: 400
        });
       $scope.chart.scale('cnt', {
            });
       $scope.chart.scale('fdate', {
                range: [0, 1]
            });
        $scope.chart.tooltip({
                crosshairs: {
                    type: 'line'
                }
          });
        $scope.chart.line().position('fdate*cnt');
        $scope.chart.point().position('fdate*cnt').size(4).shape('hv').style({
                stroke: '#fff',
                lineWidth: 1
        });
然后每次数据$scope.tableData变化时，都会调用这个renderChart()函数，
       $scope.renderChart = function () {
            $scope.chart.source($scope.tableData);
            $scope.chart.render();
        }
   然后就会出现两条折线都存在的情况，并且坐标数据错乱的情况，如果这时改变浏览器大小，就会重新改为一条，并且坐标数据显示正确。

* **G2 Version**:3.0.0
* **Platform**: Google浏览器，IE也有相同情况

![2](https://user-images.githubusercontent.com/19534231/33749726-528ea766-dc0a-11e7-9b92-71e768b1af44.png)

![1](https://user-images.githubusercontent.com/19534231/33749729-5bfaedfa-dc0a-11e7-898e-66765b0fc477.png)

**Comment by leungwensen** [comment]
请直接调用 changeData() 接口，不要用 chart.source + chart.render

https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_changeData
