### ISSUE TITLE
究竟怎么提issues才能得到回复？

### ISSUE THREAD

**Issue by leegang** [antvis/G2#2620]
换了好几种姿势提issue都没能得到回复。
一开始我还以为是我姿势不对，但是我看这里大部分issue都没有得到过回复，这是为什么？

**Comment by spicyboiledfish** [comment]
+1 同意楼上。我最近一直在用G2, 提了好多issue了，没有一个人回复

**Comment by leegang** [comment]
> +1 同意楼上。我最近一直在用G2, 提了好多issue了，没有一个人回复

https://zhuanlan.zhihu.com/p/25795393
他们充满嘲讽的issues要求在这，按照这个要求来提也是石沉大海。

**Comment by ntscshen** [comment]
I use G2Plot, and the problem you mentioned appears, maybe as you said, the posture is wrong~
========= ========= ========= ========= ========= ========= ========= 
我用的是G2Plot，也出现了你提到的问题，也许正如你所说是姿势不对~

**Comment by hustcc** [comment]
不好意思，因为开源只是兼职开发，所以业务忙的时候，会顾不过来。这个 issue 先关闭，后面的问题，我会即时跟进。
