### ISSUE TITLE
slider 默认值 start end 设置无效

### ISSUE THREAD

**Issue by Gavin-Gong** [antvis/G2#2622]
在存在 slider  start end 默认值得情况下，图表初始化依然会展示全部，而不是默认 start end 设置的部分，需要略微拖动才会展示正常。

将官方 [demo](https://g2.antv.vision/zh/examples/area/basic#area-large) 的 slider 配置改为如下即可复现

``` js
chart.option('slider', {
      start: 0.8,
      end: 1,
      trendCfg: {
        isArea: false,
      },
    });
```

**Comment by ZTrainWilliams** [comment]
同上

**Comment by Gavin-Gong** [comment]
解决方案：换 `Echarts`
