### ISSUE TITLE
[Feature Request] 允许GeometryTooltipOption.callback返回数组

### ISSUE THREAD

**Issue by SentretC** [antvis/G2#2623]
在`Geometry.tooltip`中指定多个字段，可以实现一个数据点对应多个tooltip items的效果
比如[官方文档](https://g2.antv.vision/zh/docs/manual/tutorial/tooltip#%E5%86%85%E5%AE%B9%E9%85%8D%E7%BD%AE)中给出的这个例子：
![图片](https://user-images.githubusercontent.com/44996835/86425189-10160f00-bd17-11ea-8619-315f6e27d343.png)

另外，用户还可以提供一个回调函数，进一步定制展示内容
然而G2要求该回调函数返回一个对象，这便意味着一个数据点只能对应一个tooltip item，在提供更高自由度的同时又丧失了另一些可能性
是否可以增加在该函数返回一个数组的情况下，将数组的每个元素对应为一个tooltip item的功能呢？

**Comment by hustcc** [comment]
这个配置应该是你想要的：

```ts
chart.tooltip({
  customItems: (items) => newItems,
});
```
