### ISSUE TITLE
汉字label高度计算有误

### ISSUE THREAD

**Issue by BuggMaker** [antvis/G2#2627]
* **G2 Version**:4.x
* **Platform**:
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/25820633/86554404-15c25d80-bf80-11ea-8f7e-90c694094073.png)

* **CodePen Link**:
https://bizcharts.net/gist/2lTXuGH9TnS

**Comment by Me-Momo** [comment]
方便说下这个label设置了多大吗

**Comment by hustcc** [comment]
已经解决。使用了精确计算，而不是使用之前的 fontSize 做非精确计算。
