### ISSUE TITLE
G2的3.5.5版本html自定义tooltip没问题，3.5.17版本自定义图例一直定位在图表的左下角

### ISSUE THREAD

**Issue by majinquan123** [antvis/G2#2628]
3.5.5版本
  chart.tooltip({
    useHtml: true,
    htmlContent: function htmlContent(title, items) {
      const selfItem = items;
      const html = '<div>';
      const titleDom = `<div class="g2-tooltip-title" style="margin-bottom: 4px;">${title}</div>`;
      const sumDom = `<span style="background-color:${options.intervalColor};width:8px;height:8px;border-radius:50%;display:inline-block;margin-right:8px;"></span>`
      + `${selfItem[0].value}<span class="g2-tooltip-value" style="margin-left:20px;font-size:12px">${options.tooltipActual}</span>`
      + '<br/>'
      + `<span style="background-color:${options.lineColor};width:8px;height:8px;border-radius:50%;display:inline-block;margin-right:8px;"></span>`
      + `${selfItem[1].value}<span class="g2-tooltip-value" style="margin-left:20px;font-size:12px">${options.tooltipPlan}</span>`;
      return `${html + titleDom + sumDom}</div>`;
    }
  });
![QzpcVXNlcnNcREVMTFxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcNDc2NTYyMzQ2X3YyXEltYWdlRmlsZXNcMTU5NDAyODUyMTY4Nl8yQjk0OTNFNS1FRTA5LTQ1ZTAtODAyQy1BNEZDMUVDOEMzRTAucG5n](https://user-images.githubusercontent.com/56501285/86579611-21c61380-bfb0-11ea-95ba-b8585cfa2aec.png)
3.5.17版本相同代码
![QzpcVXNlcnNcREVMTFxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcNDc2NTYyMzQ2X3YyXEltYWdlRmlsZXNcMTU5NDAyODQ5ODg2NV9BN0YxODM4Qy05QTY0LTQzNDItQUEyNC1DRTAxMDdCNDQwQTEucG5n](https://user-images.githubusercontent.com/56501285/86579703-3e624b80-bfb0-11ea-8910-f94356f724d5.png)

**Comment by Leannechn** [comment]
加一个position absolute 的样式即可

**Comment by hustcc** [comment]
应该是外部的 css 样式影响到 g2-tooltip 了，重新设置一下即可。
