### ISSUE TITLE
4.0.9版本下折线图数据量很多的时候，tooltip超出屏幕，可以多列展示吗

### ISSUE THREAD

**Issue by liujunyang** [antvis/G2#2630]
* **G2 Version**:4.0.9
* **Platform**:vue2.6.11
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

如题

**Comment by Me-Momo** [comment]
自定义tooltip 设置 tooltip enterable，

**Comment by Me-Momo** [comment]
> 自定义tooltip 设置 tooltip enterable，
