### ISSUE TITLE
G2 Tooltip不能阻止XSS攻击

### ISSUE THREAD

**Issue by gonenoob** [antvis/G2#2632]
* **G2 Version**: latest
* **Platform**: Mac
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: [https://codepen.io/gonenoob/pen/QWymqaX](https://codepen.io/gonenoob/pen/QWymqaX)

G2 Tooltip不能阻止XSS攻击，基于react开发的项目会频繁遇到安全检查不通过；能否处理下这种情况？

**Comment by SentretC** [comment]
看起来像是我在antvis/component那边[issue #175](https://github.com/antvis/component/issues/175)里提到的问题

**Comment by gonenoob** [comment]
> 看起来像是我在antvis/component那边[issue #175](https://github.com/antvis/component/issues/175)里提到的问题
> 不知道会不会、什么时候能解决（我自己的话不是很有信心……），通过自定义tooltip内容或其他方式自己把涉及用户输入的内容转义一下是否可行？

通过自定义内容是可以解决的。但是这样太繁琐了，每个图表都要去改，因为每个图表使用的name字段都可能不一样。
G2其实是可以做掉这部分工作的，这是个通用的需求.

**Comment by Me-Momo** [comment]
在数据源的时候就对数据进行一下转义会更好

**Comment by SentretC** [comment]
> 
> 
> 在数据源的时候就对数据进行一下转义会更好

这没什么道理吧……而且G2大部分组件不是HTML的，在数据源转义的话图例之类的显示可能就不对了

**Comment by hustcc** [comment]
这个业务层自己处理吧，业务层会有各种 xss 模块去处理这个。
