### ISSUE TITLE
图表数据量过大时，怎么实现沿 x 轴水平拖动查看

### ISSUE THREAD

**Issue by eleanors** [antvis/G2#2636]
* **G2 Version**:   4.0 +
* **Platform**:  mobile
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

图表数据量过大时，怎么实现沿 x 轴水平拖动查看

**Comment by F-loat** [comment]
https://antv-g2plot.gitee.io/zh/examples/column/basic#column-scrollbar
