### ISSUE TITLE
重影，多次渲染饼图里面的文字，文字出现重影

### ISSUE THREAD

**Issue by CrazyApple1** [antvis/G2#2637]
1.我采用官方提供的demo画了一个饼图
2.`this.chartRef
          .annotation()
          .text({
            position: ['50%', '50%'],
            content: percent,
            style: {
              fontSize: 28,
              fill: 'rgba(0,0,0,0.90)',
              textAlign: 'center'
            },
            offsetY: -10
          })` 采用这种方式设置了里面数值，但是我的content 的值 precent是会一直变化，我每次渲染整个饼图和文字前都会调用
     this.chartRef.clear(true);清理里面的值，
3.重复渲染后出现如下图片的情况
![饼图重影](https://user-images.githubusercontent.com/13821431/86920708-be2d1900-c15c-11ea-964f-74336b8b3b9a.png)

是不是我这边配置不对，还是其他原因啊？？？？

**Comment by CrazyApple1** [comment]
![饼图重影](https://user-images.githubusercontent.com/13821431/86920853-e61c7c80-c15c-11ea-8412-cb021ec4013c.png)

**Comment by simaQ** [comment]
在绘制 annotation().text() 之前调用下 this.chartRef.annotation().clear(true)
