### ISSUE TITLE
使用拖拽+缩放交互时无法回滚到初始状态

### ISSUE THREAD

**Issue by Lerchar** [antvis/G2#2642]
我在用g2实现拖拽＋缩放的时候发现了一个问题，如果先进行拖拽再进行缩放的话，通过rollback 回滚时，还原的状态是拖拽后的状态而不是最初始的状态，请问我如何能还原成最初始的状态？

G2 Version: 4.0.12
CodePen Link: https://codepen.io/lerchar/pen/ExPRPYE

另外，我在使用reset-button去做交互时也是如此。

对于reset-button默认生成的按钮现在只支持show()和hide()方法，什么时候可以自定义按钮的文字及样式等内容呢？

**Comment by Lerchar** [comment]
还有个小问题。。我在使用chart.guide().html() 的时候为什么提示chart.guide(...).html is not a function ?

**Comment by simaQ** [comment]
https://g2.antv.vision/en/docs/manual/upgrade#%E4%B8%8D%E5%85%BC%E5%AE%B9%E6%94%B9%E5%8A%A8 

![image](https://user-images.githubusercontent.com/6628666/87167940-4ef02a00-c300-11ea-8c02-b43303148872.png)

**Comment by Rabbitzzc** [comment]
> https://g2.antv.vision/en/docs/manual/upgrade#%E4%B8%8D%E5%85%BC%E5%AE%B9%E6%94%B9%E5%8A%A8
> 
> ![image](https://user-images.githubusercontent.com/6628666/87167940-4ef02a00-c300-11ea-8c02-b43303148872.png)

不再支持`html`，有新的API适配么？

**Comment by hustcc** [comment]
已经增加 chart.annotation().html()
