### ISSUE TITLE
当 connectNulls 为 true 且 y 轴数据全为 null 时报错

### ISSUE THREAD

**Issue by iczzZero** [antvis/G2#2649]
* **G2 Version**: latest
* **Platform**: 
* **Mini Showcase(like screenshots)**:

line chart
![image](https://user-images.githubusercontent.com/1570124/87371603-4c1f5e80-c5b8-11ea-96be-1842dbfdb3bb.png)

area chart
![image](https://user-images.githubusercontent.com/1570124/87371731-8db00980-c5b8-11ea-9cce-8c690f22cd53.png)

* **CodePen Link**: https://codepen.io/iczzzero/pen/vYLrGMW

期望：仍能够展示坐标轴
实际：js 报错，页面上没有任何渲染

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/106410569-0fe11c00-647e-11eb-9140-921be03c3c04.png)

> 4.1.9 版本中不存在这个问题。
