### ISSUE TITLE
图表交互问题

### ISSUE THREAD

**Issue by lihui1603** [antvis/g2#265]
在使用环形图雷达图等图表时，我们能否在初始化及重绘时使其单个节点高亮（例如环形图等环状部分只能鼠标点击才能弹出 能否在初始化的时候自动弹出）
感谢～

**Comment by simaQ** [comment]
默认高亮的方法目前有，但是接口不友好，下个小版本我优化下。

**Comment by dxq613** [comment]
已经增加了 geom.setSelected(obj) 接口
