### ISSUE TITLE
4.x版本不再支持`chart.guide().html()`，请问如何平滑升级

### ISSUE THREAD

**Issue by Rabbitzzc** [antvis/G2#2651]
目前项目中利用html属性还是蛮多的，但是
了解到4.x版本不再支持`chart.guide().html()`，请问如何平滑升级？

**Comment by hustcc** [comment]
可以介绍下你具体怎么使用的吗？为啥现在的 annotation 无法满足？

**Comment by Rabbitzzc** [comment]
![image](https://user-images.githubusercontent.com/26913511/93416093-a2ba5900-f8d7-11ea-9403-12a02ac629c5.png)
使用 `html` 标记比较方便，定义样式等等，我看 `guide` 支持 `html` 配置，但是 `annotation` 不支持。但是在升级的时候，目前的办法需要拆解 `html` 配置，使用 `chart.annotation().func(config)`。

**Comment by hustcc** [comment]
已经增加:

1. chart.annotation().html 自定义 html
2. chart.annotation().shape 自定义 G shape

**Comment by Rabbitzzc** [comment]
厉害啦，棒
