### ISSUE TITLE
纵坐标 line 设置默认展示样式和横坐标不一样么？？ 还有 grid 怎么改成虚线？

### ISSUE THREAD

**Issue by Rabbitzzc** [antvis/G2#2653]
![image](https://user-images.githubusercontent.com/26913511/87373628-9d315180-c5bc-11ea-8290-6765ca1f2b81.png)
纵坐标 line 设置默认展示样式和横坐标不一样么？？ 还有 grid 怎么改成虚线？
拜托官方文档丰富一下吧，哎

**Comment by Rabbitzzc** [comment]
升个级都直接卡死在文档上了

**Comment by qiuguomuhai** [comment]
这个问题怎么关闭了?  我用哦4.0.11版本页遇到了同样的问题, 也简单compare changes to 目前最新的版本4.0.14并没有发现相关的更新.

**Comment by Rabbitzzc** [comment]
> 这个问题怎么关闭了? 我用4.0.11版本也遇到了同样的问题, 也简单compare changes to 目前最新的版本4.0.14并没有发现相关的更新.
> 在随便一个官方示例代码中加入
> 
> ```
> grid: {
>         line: {
>           type: 'line',
>           lineDash: [4,4],
>           stroke: '#e2e2e2',
>           lineWidth: 1
>       }
> ```
> 
> 或
> 
> ```
> grid: {
>         line: {
>           type: 'line',
>           lineStyle: {
>             lineDash: [4,4],
>             stroke: '#e2e2e2',
>             lineWidth: 1
>           }
>       }
> ```
> 
> 都未达预期显示效果, 并且在codesandbox中提示lineDash: number[] is not assignable to the type of GripLineCfg,
> 链接: https://codesandbox.io/s/0lfju?file=/index.ts
> 
> 由于官方文档并未详细说明grid的配置项, 所以我看了下源码, 把上面的代码改为
> 
> ```
> grid: {
>         line: {
>           type: 'line',
>           style: {
>             lineDash: [4,4],
>             stroke: '#e2e2e2',
>             lineWidth: 1
>         }
>       }
> ```
> 
> 显示即可达预期效果.

关掉是后面是找到了解决方案了。这个应该没问题，应该是通过`lineDash`与`line`来区别虚线与实线的；对于样式问题，都是统一放在`style`属性里面
