### ISSUE TITLE
g2饼图v3版本，labelLine: false, // 不显示文本的连接线，这个API没有生效

### ISSUE THREAD

**Issue by wangzhen429** [antvis/G2#2656]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by wangzhen429** [comment]
![image](https://user-images.githubusercontent.com/42830575/87411984-08017d80-c5fb-11ea-9e04-4a5fe77f6afe.png)

**Comment by wangzhen429** [comment]
![image](https://user-images.githubusercontent.com/42830575/87412073-21a2c500-c5fb-11ea-872e-42b362aea342.png)

**Comment by xiao15934831580** [comment]
可以用：
{
labelLine:{
          style:{
                      lineWidth:0,
                    }
   },
}
配置在label使引线隐藏

**Comment by Me-Momo** [comment]
4.x 该问题已解决
