### ISSUE TITLE
滑块会影响图例的位置

### ISSUE THREAD

**Issue by Rabbitzzc** [antvis/G2#2657]
####  基本信息
* G2  version： 4.0.12
* Platform: Macos + Chrome

##### 问题1
在给折线图或者柱状图设置滑块的时候，发现滑块与图例默认会重叠
![image](https://user-images.githubusercontent.com/26913511/87422017-76017100-c60a-11ea-9cca-e6c8f728ecd5.png)

##### 问题2
随后，为了解决上述问题，所以设置图了例的位置（偏移量）：
```js
this.chart.legend('type', {
          offsetY: -30,
})
```
设置了 `offsetY: -530`的偏移量

**但是当滑动滑块的时候，图例的位置会发生变化**
【滑动之前】
![image](https://user-images.githubusercontent.com/26913511/87422370-1d7ea380-c60b-11ea-9749-ded68f28a96c.png)
【滑动以后】
![image](https://user-images.githubusercontent.com/26913511/87422384-22435780-c60b-11ea-87a1-4a423ea9917a.png)

请问如何解决

**Comment by hustcc** [comment]
最新的 4.1.x 版本已经解决这个布局问题。
