### ISSUE TITLE
G2 环图下面的 labelLine 会弯曲的问题

### ISSUE THREAD

**Issue by yumanfeng** [antvis/G2#2661]
![image](https://user-images.githubusercontent.com/13445900/87532535-e3260c80-c6c5-11ea-90ac-3b1df21de82b.png)
如图：环图下面的 labelLine 会弯曲，即使下面设置很大的 padding，也会弯曲

**Comment by YYL1999** [comment]
不要设padding 把图表高度设置大一点呢 试试呢

**Comment by Me-Momo** [comment]
缩小半径看下

**Comment by yumanfeng** [comment]
> 缩小半径看下；给 demo 链接

缩小半径确实可以，但需求是想布满画布，不想缩小图表
https://codesandbox.io/s/optimistic-gould-5efsj?file=/src/RingDiagram.tsx

**Comment by hustcc** [comment]
> > 缩小半径看下；给 demo 链接
> 
> 缩小半径确实可以，但需求是想布满画布，不想缩小图表
> https://codesandbox.io/s/optimistic-gould-5efsj?file=/src/RingDiagram.tsx

看了 demo 和代码逻辑是符合的，饼图区域的绘制是去除 legend 之后然后剩余画布的快高最小值作为直径，这个时候下方的标签 label 只能转弯，除非调整饼图的半径小一些，留出一些位置给 label

![image](https://user-images.githubusercontent.com/7856674/88137224-aace8300-cc1d-11ea-835e-0dd15039360b.png)

**Comment by Me-Momo** [comment]
饼图半径设置为 1 时，底部的标签必然会由于空间不足，进行偏移；建议设置半径的时候，可以计算下预留饼图上下空间给标签展示：比如容器高度为 400px时，除掉上线padding 还有图例位置，假设图形区域 360px，设置半径 0.85 的话，上下各预留 27px 供标签文本 + 标签拉线展示

不过这个问题，在新的布局算法下，应该会比较好解决，可以关注这个 PR: [G2Plot #1380](https://github.com/antvis/G2Plot/pull/1380)
