### ISSUE TITLE
饼图 label content 设置为 空字符串时，报错

### ISSUE THREAD

**Issue by visiky** [antvis/G2#2663]
**现象**
![image](https://user-images.githubusercontent.com/15646325/87556674-83415d00-c6e9-11ea-9253-98d5cbd4b26a.png)

**复现**
官网 demo 设置 `label.content` 即可

**Comment by pearmini** [comment]
目前看起来没有问题了
![image](https://user-images.githubusercontent.com/49330279/130176203-46f51617-0cd1-4e2e-88a8-35b2f78db0cd.png)
