### ISSUE TITLE
请问分面rect中，如何设置一个滑块拖动整个分面， 而不是每个分面分别拖动

### ISSUE THREAD

**Issue by chengqiaoli** [antvis/G2#2664]
请问分面rect中，如何设置一个滑块拖动整个分面， 而不是每个分面分别拖动？？？
view,option('slider', {
end: 0.1,
})
这块滑动组件的监听事件也没找到，，，

**Comment by minghaoye** [comment]
有同样的需求，4.0的slider太不灵活了

**Comment by hustcc** [comment]
ref:  https://github.com/antvis/G2/issues/2331
