### ISSUE TITLE
legend的position设为right无效

### ISSUE THREAD

**Issue by areyouse7en** [antvis/g2#267]
* **G2 Version 3.0.1**:
* **Platform  windows**:
* **CodePen Link  https://codepen.io/areyouse7en/pen/NXKbEb?editors=0010**:
在[官网示例](https://antv.alipay.com/zh-cn/g2/3.x/demo/pie/labelline.html)的基础上修改的

期望，position设置为right，legend应该出现在右侧

**Comment by areyouse7en** [comment]
title设置也无效

**Comment by leungwensen** [comment]
legend 被图形区域盖住了。你可以在 new chart 的时候设置 padding 为 [0, 100, 0, 0] 试试。

另外，title 的配置项是一个对象： https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#________参数

**Comment by areyouse7en** [comment]
ok，加了padding显示了。
那title内容怎么写怎么显示呢

**Comment by dxq613** [comment]
```js
chart.axis('filed', {title:{fill: '#ccc' }})
```
3.0.1 版本后支持

```js
chart.axis('filed', {title: true})
```

**Comment by areyouse7en** [comment]
我意思是。。title文字怎么设置呢。。

**Comment by dxq613** [comment]
3.0 中坐标轴上的 title 是默认不显示的。
