### ISSUE TITLE
多折线图中提供多Y轴

### ISSUE THREAD

**Issue by kuye-kuye** [antvis/G2#2671]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在使用多折线的时候，不同折线的值域相差过大，造成可观性过差。目前多折线图的不同折线是以type进行区分，在数据源中都只在一个‘value’字段，当我需要用折线图展示一个对象不同时间的状态时，时间作为x轴，对象的多个属性需要被拆成数据源中的多个元素并配置不同的type。麻烦倒不至于麻烦，问题就在于对象的多个属性相差过大（类似如下，a的值域在（0,10】b的值域在【10000000，20000000】，c的值域在【100,1000】时，a的折线将在视觉上与x轴重合）。如果提供多Y轴，多折线的每条折线可以映射数据源中一个对象的一个字段，并且可以给不同Y轴设置自己的刻度范围来精准展示
```
object{
a:0.1,
b:10000000,
c: 200
}
```

### What does the proposed API look like?
```
data:[
  {  
    a: 1,           // X轴
    b: 100,         // Y0轴
    c: 0.1,         // Y1轴    
    d: 1000000      // Y2轴
    ...
  }
]
```

**Comment by hustcc** [comment]
1. 数据转化一下:

```ts
{
   a: 1
   type: 'b',
   value: 100, 
},
{
   a: 1
   type: 'c',
   value: 0.1, 
},
{
   a: 1
   type: 'd',
   value: 100000, 
},
```

 - 绘制

```ts
chart.data(data);

chart.line('a*value').color('type');

chart.render();
```
