### ISSUE TITLE
关于饼图的颜色问题

### ISSUE THREAD

**Issue by insov** [antvis/G2#2672]
* **G2 Version**:4.0.12
* **Platform**: win10 edge
* **Mini Showcase(like screenshots)**:

![image](https://user-images.githubusercontent.com/3804453/87911176-c3b02a80-ca9d-11ea-814f-b093b0acce28.png)

* **CodePen Link**:
https://g2.antv.vision/zh/examples/pie/basic#labelline

饼图指定颜色后，实际渲染的颜色与指定的颜色不同。使用网站上的例子，添加颜色[ '#2593fc', '#38c060', '#27c1c1', '#705dc8',  '#f9cb34' ]。 实际看到的颜色是 ['#3099fc','#42c368','#32c4c3','#7765cb','#f9ce3e']

**Comment by hustcc** [comment]
```ts
.color('item', ['red', 'green', 'blue'])
```
