### ISSUE TITLE
饼图 label 点击legend 出现图形残留

### ISSUE THREAD

**Issue by guishilike** [antvis/G2#2674]
测试案例
官方基础饼图：
修改数据为
const data = [
  { item: '事例一', count: 1, percent: 0.01 },
  { item: '事例二', count: 40, percent: 0.40 },
];
点击legend,label从饼图上方移动到下方时出现图形残留
![1595238935(1)](https://user-images.githubusercontent.com/51023060/87925734-498aa080-cab3-11ea-82c6-8c7ad9b9f0f2.png)
![image](https://user-images.githubusercontent.com/51023060/87925775-58715300-cab3-11ea-8f7c-5ef3858b1dc1.png)

**Comment by guishilike** [comment]
基本信息
G2 version： 4.0.12
Platform: Chrome
link: https://antv-g2.gitee.io/zh/examples/pie/basic

**Comment by hustcc** [comment]
试试添加下面的配置：

```ts
new Chart({
  localRefresh: false,
});
```

**Comment by guishilike** [comment]
使用之后确实不会再出现，但这个是什么原因导致的，之后会解决吗

**Comment by hustcc** [comment]
> 使用之后确实不会再出现，但这个是什么原因导致的，之后会解决吗

底层渲染引擎在局部渲染上存在一些问题，会解决的。

**Comment by czh740132583** [comment]
> > 使用之后确实不会再出现，但这个是什么原因导致的，之后会解决吗
> 
> 底层渲染引擎在局部渲染上存在一些问题，会解决的。
雷达图也有这个问题呢 4.1.32
