### ISSUE TITLE
4.0版本中有没有类似echarts中通过调用dispatchAction后触发某个事件的方法呢？🤔

### ISSUE THREAD

**Issue by LukeCG** [antvis/G2#2675]
4.0版本中有没有类似echarts中通过调用dispatchAction后触发某个事件的方法呢？🤔
产品的要求是，图表初始化后，自动选中某一项数据
类似该案例：https://gallery.echartsjs.com/editor.html?c=xEG1fyp-v

ps：是我的理解能力太差了吗，G2的说明文档看得心好累😫

**Comment by LukeCG** [comment]
终于在view.ts里面找到了getXY和showTooltip方法;
问题解决了....

**Comment by riyueweiyi** [comment]
> 终于在view.ts里面找到了getXY和showTooltip方法;
> 问题解决了....

老哥有没有例子参考一下

**Comment by hustcc** [comment]
你们提 issue 的时候描述一下你们遇到的问题。不一定解决某一个问题，就一定按照 echarts 的方式来实现，可能已经有更好的方式，但是文档没有透出清楚而已。

**Comment by riyueweiyi** [comment]
> 你们提 issue 的时候描述一下你们遇到的问题。不一定解决某一个问题，就一定按照 echarts 的方式来实现，可能已经有更好的方式，但是文档没有透出清楚而已。

对于官网上的[饼图示例](https://g2.antv.vision/zh/examples/gallery/pie#pie3)，在缺少X轴时，如何获取chart 的 X，Y坐标点？

**Comment by hustcc** [comment]
x y 的坐标点是指什么的坐标？

**Comment by Me-Momo** [comment]
```
    const angleScale = chart.getScaleByField(angleField);
    const colorScale = chart.getScaleByField(colorField);

   x = colorScale.scale(data[colorField]);
   y = angleScale.scale(data[angleField]);

  coordinate.convert({ x, y }) // 坐标轴位置
```

**Comment by riyueweiyi** [comment]
> x y 的坐标点是指什么的坐标？

就是 chart.getXY 方法的返回值，但是饼图position只设置一个值的话，x坐标获取不到值

**Comment by psyprogrammer** [comment]
> 终于在view.ts里面找到了getXY和showTooltip方法; 问题解决了....

老哥，getXY里面怎么传的参啊，看文档没有，自己传报错

**Comment by zoushujun** [comment]
老哥们，饼图通过getXY()获取坐标的问题解决了吗
