### ISSUE TITLE
异步加载问题

### ISSUE THREAD

**Issue by yanruoxinb** [antvis/g2#268]
数据是按条件异步获取的，并且有多条数据需要显示，怎么重新改变数据，然后进行渲染呢？ 试了一下changeData()不行啊。

**Comment by leungwensen** [comment]
麻烦提供一下代码

**Comment by yanruoxinb** [comment]
const ds = new DataSet({
                state:{
                }
            });
            const dv = ds.createView().source($scope.tableData);
            dv.transform({
                type: 'fold',
                fields: $scope.field,//是个数组
                key: 'key',
                value: 'value'
            })

            $scope.chart = new G2.Chart({
                container: 'mountNode',
                forceFit: true,
                height: 400
            });

            $scope.chart.source(dv, {
                fdate: {
                    range: [0, 1]
                }
            });
            $scope.chart.tooltip({
                crosshairs: {
                    type: 'line'
                }
            });

            $scope.chart.line().position('fdate*value').color('key');
            $scope.chart.point().position('fdate*value').color('key').size(4).shape('circle').style({
                stroke: '#f5f55f',
                lineWidth: 1
            });
            $scope.chart.render();


  然后想要改变他的数据 $scope.chart.changeData($scope.tableData)，但是会报错啊

**Comment by leungwensen** [comment]
具体报什么错，前后两个 tableData 数据结构一致吗？

**Comment by yanruoxinb** [comment]
数据结构一致，报的是 changeData is undefined

**Comment by dxq613** [comment]
典型的找不到 chart 的引用，看看上下文上是否有 chart 的对象。

**Comment by yanruoxinb** [comment]
![1](https://user-images.githubusercontent.com/19534231/33870116-52f0e242-df47-11e7-811b-e60cba17174f.png)

像这样的数据结构怎么画多条线出来？

**Comment by leungwensen** [comment]
先用 data-set 的 [map transform](https://antv.alipay.com/zh-cn/g2/3.x/api/transform.html#_map-数据加工) 把数据结构处理为扁平的数据表形式，也就是每一条数据应该是这样的：

```js
{ fdate: '20171201', cnt: 10151, uids: 18139 }
```

然后就可以 

```js
chart.line('fdate*cnt') // xxx
chart.line('fdate*uids') // xxx
```

G2 接受的数据是类似数据库表的结构，没有多层结构的。

**Comment by yanruoxinb** [comment]
但是我要的是数组的每一项都可以画两条线cnt和uids的，就是说如果数组长度为5，就会有10条线啊

**Comment by leungwensen** [comment]
还是要拍平，但可以给每一条数据加一个 key，也就是

```js
{ fdate: '20171201', cnt: 10151, uids: 18139, key: 'android' }
```

要根据不同的 key 画多条线就更简单了：

```js
chart.line('fdate*cnt').color('key');
```

**Comment by yanruoxinb** [comment]
const data = [
                { month: 'Jan', Tokyo: 7.0, London: 3.9 },
                { month: 'Feb', Tokyo: 6.9, London: 4.2 },
                { month: 'Mar', Tokyo: 9.5, London: 5.7 },
                { month: 'Apr', Tokyo: 14.5, London: 8.5 },
                { month: 'May', Tokyo: 18.4, London: 11.9 },
                { month: 'Jun', Tokyo: 21.5, London: 15.2 },
                { month: 'Jul', Tokyo: 25.2, London: 17.0 },
                { month: 'Aug', Tokyo: 26.5, London: 16.6 },
                { month: 'Sep', Tokyo: 23.3, London: 14.2 },
                { month: 'Oct', Tokyo: 18.3, London: 10.3 },
                { month: 'Nov', Tokyo: 13.9, London: 6.6 },
                { month: 'Dec', Tokyo: 9.6, London: 4.8 }
            ];
            const ds = new DataSet();
            const dv = ds.createView().source(data);
            dv.transform({
                type: 'fold',
                fields: [ 'Tokyo', 'London' ], // 展开字段集
                key: 'city', // key字段
                value: 'temperature', // value字段
            });
            const chart = new G2.Chart({
                container: 'mountNode',
                forceFit: true,
                height: 500
            });
            chart.source(dv, {
                month: {
                    range: [ 0, 1 ]
                }
            });
            chart.tooltip({
                crosshairs: {
                    type: 'line'
                }
            });
            chart.axis('temperature', {
                label: {
                    formatter: val => {
                    return val + '°C';
            }
            }
        });
            chart.line().position('month*temperature').color('city');
            chart.point().position('month*temperature').color('city').size(4).shape('circle').style({
                stroke: '#fff',
                lineWidth: 1
            });
            chart.render();


            const data22 = [
                { month: 'Jan', Tokyo: 7.0, London: 3.9 },
                { month: 'Feb', Tokyo: 6.9, London: 4.2 },
                { month: 'Mar', Tokyo: 9.5, London: 5.7 },
                { month: 'Apr', Tokyo: 14.5, London: 3 },
                { month: 'May', Tokyo: 18.4, London: 11.9 },
                { month: 'Jun', Tokyo: 21.5, London:5 },
                { month: 'Jul', Tokyo: 25.2, London: 7.0 },
                { month: 'Aug', Tokyo: 26.5, London: 5.6 },
                { month: 'Sep', Tokyo: 23.3, London: 4},
                { month: 'Oct', Tokyo: 18.3, London: 5 },
                { month: 'Nov', Tokyo: 13.9, London: 6 },
                { month: 'Dec', Tokyo: 9.6, London: 4.8 }
            ];

           
            chart.changeData(data22);

这样changeData()不行啊，最后就剩几个点了

**Comment by leungwensen** [comment]
changeData 要保证数据同构。你在调用 changeData 之前，chart 的数据源是 DataSet.View 的实例，而 changeData 传入的则是一个普通对象数组。这个场景你不用调用 chart.changeData，可以直接用：

```js
dv.source(data22);
```

**Comment by yanruoxinb** [comment]
好的 感谢感谢大神的指点，如果数据结构变化，有什么方法可以使用？

**Comment by leungwensen** [comment]
数据结构变化，然后画全新的图吗？那可以 [chart.clear()](https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_clear) 之后重新走一遍数据映射和渲染流程：

```js
chart.clear();
chart.source(newData);
chart.line().position('x*y');
// ...
```

**Comment by yanruoxinb** [comment]
感谢感谢  解决了我一直困扰的问题  大神么么哒~~~~~
