### ISSUE TITLE
shape 不生效

### ISSUE THREAD

**Issue by JoeABCDEF** [antvis/G2#2682]
* **G2 Version**: 4.0.13
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

为什么相同代码 一个圆角生效一个不生效呢
https://g2.antv.vision/zh/examples/column/stack#stacked-percentage
https://codesandbox.io/s/nostalgic-austin-rffum?file=/src/index.js

**Comment by hustcc** [comment]
`border-radius` 这个 shape 确实不存在，需要自定义注册一个圆角的 interval shape。

**Comment by hustcc** [comment]
可以看看这个：https://g2.antv.vision/zh/examples/column/stack#rounded-stacked

**Comment by JoeABCDEF** [comment]
> `border-radius` 这个 shape 确实内置中是不存在，需要自定义注册一个圆角的 interval shape。可以参考 demo~

你好这个 关于 registerShape 的 有文档吗
