### ISSUE TITLE
图表可以设置位于在画布的最左侧吗？目前看起来始终是位于画布的中间

### ISSUE THREAD

**Issue by yumanfeng** [antvis/G2#2683]
图表可以设置位于在画布的最左侧吗？目前看起来始终是位于画布的中间
![image](https://user-images.githubusercontent.com/13445900/88128806-47d2f100-cc09-11ea-8d8c-1ca59bc46447.png)

**Comment by hustcc** [comment]
new Chart({
  region: {
    start: { x, y },
    end: { x, y },
  }
});

其中 x y 是按照比例的 0 ~ 1 的值。

**Comment by yumanfeng** [comment]
> ```ts
> new Chart({
>   region: {
>     start: { x, y },
>     end: { x, y },
>   }
> });
> ```
> 
> 其中 x y 是按照比例的 0 ~ 1 的值。


ChartCfg 中没有 region 属性
![Uploading image.png…]()

版本：
"@antv/g2": "^4.0.12"
