### ISSUE TITLE
G2官网文档链接404

### ISSUE THREAD

**Issue by Young-Wang** [antvis/G2#2684]
[G2教程文档](https://antv-g2.gitee.io/zh/docs/manual/about-g2)内的许多跳转链接存在404的问题，比如DataSet  [Transform API](https://antv-g2.gitee.io/zh/docs/manual/dataset/dataset/transform)的链接地址就是404，作为一个专业的数据可视化团队，我觉得产品文档存在这样的问题还是不太能接受的，希望antv团队能重视一下文档更新的问题。

**Comment by ArranZeyuWang** [comment]
文档中的404问题已经进行了修正，中文镜像同步有延迟，目前已经更新[Transform API
](https://antv-g2.gitee.io/zh/docs/manual/dataset/transform)
G2新版API文档已经更新上线，可以在.vision官网直接访问[API文档](https://g2.antv.vision/en/docs/api/chart)，中文镜像会延迟同步，后续我们还会继续补充完善
