### ISSUE TITLE
`border-radius` 这个 shape 确实内置中是不存在，需要自定义注册一个圆角的 interval shape。可以参考 demo~

### ISSUE THREAD

**Issue by JoeABCDEF** [antvis/G2#2685]
`border-radius` 这个 shape 确实内置中是不存在，需要自定义注册一个圆角的 interval shape。可以参考 demo~

_Originally posted by @hustcc in https://github.com/antvis/G2/issues/2682#issuecomment-662249915_

你好  有这块的文档吗

**Comment by hustcc** [comment]
这个关闭，在原 issue 中继续回复。
