### ISSUE TITLE
环图设置自定义颜色后，图例legend 只能在下面，设置不了其他位置了，比如图例放在右边

### ISSUE THREAD

**Issue by liudekang** [antvis/G2#2686]
环图设置自定义颜色后，图例legend 只能在下面，设置不了其他位置了，比如图例放在右边

  const data = [
    {item:"成功",keys:"success",colors:"#29CC29","count":11},
    {item:"失败",keys:"failed",colors:"#F65555","count":3},
    {item:"异常",keys:"error",colors:"#FF822E","count":0}
  ];

const chart = new G2.Chart({
  container: 'container',
  forceFit: true,
    height: 280,
      animate: true,
     // padding: [20, 100, 20, 20]
});
chart.source(data );
   chart.legend('item', {
      position: 'right',
 // offsetX:160,  
   layout:'vertical', 
    });
chart.coord('theta', {
  radius: 0.75,
  innerRadius: 0.6
});
chart.tooltip({
  showTitle: false,
  itemTpl: '<li><span style="background-color:{color};" class="g2-tooltip-marker"></span>{name}: {value}</li>'
});
// 辅助文本
chart.guide().html({
  position: [ '50%', '50%' ],
  html: '<div style="color:#8c8c8c;font-size: 14px;text-align: center;width: 10em;">主机<br><span style="color:#8c8c8c;font-size:20px">200</span>台</div>',
  alignX: 'middle',
  alignY: 'middle'
});
const interval = chart.intervalStack()
  .position('count')
 // .color('item')
.color('colors', (ev) => {
        return ev
      })
  .label('count', {
    formatter: (val, item) => {
      return item.point.item + ': ' + val;
    }
  })
  .tooltip('item*count', (item, count) => {
   
    return {
      name: item,
      value: count
    };
  })
  .style({
    lineWidth: 1,
    stroke: '#fff'
  });
chart.render();

**Comment by Me-Momo** [comment]
不是 G2 4.x 版本吗
