### ISSUE TITLE
rendering in queue

### ISSUE THREAD

**Issue by chenshuai2144** [antvis/g2#269]
一个页面上有太多的图标的是否,渲染是并行的,可否将render放入一个队列.
这样多个render 进行 渲染时可以很好的提升性能.

类似于
```
  renderToCanvas(page: number) {
   // 初始化渲染类
    var renderAction = new RenderToCanvasLoop(page);
    /**
     * 如果有正在渲染的.
     * 将其放入队列
     */
    if (this.isRenderIng) {
      this.renderList = this.renderList.push(renderAction);
    } else {
      // 如果没有当前渲染,直接进行渲染.
      this.isRenderIng = true;
      this.runRenderAction(renderAction);
    }
  }
```

**Comment by leungwensen** [comment]
这个逻辑目前可以封装到业务代码里。因为具体业务场景需求可能很不一样，有些需要图表进入可见区域才渲染，有些需要并发，有些需要串行，有些还需要异步等。这是比较偏业务需求的场景，目前 G2 没有内置处理。

**Comment by chenshuai2144** [comment]
@leungwensen  业务代码封装只能重写你们的render方法了
我做了一个方法叫queueRender.
是否可以提供另外一个api... 类似于queueRender
直接重写并不是多好的解决方案.

**Comment by leungwensen** [comment]
不需要重写 render 方法呀，你可以把生成的 chart 实例丢到一个队列里，然后挨个执行 chart.render

**Comment by chenshuai2144** [comment]
图省事了,
queueRender 就是和你用的方法一样.
只是直接挂到g2对象上了

**Comment by leungwensen** [comment]
嗯，render 的过程是同步的，并且并不能 “并行”，因为 js 是单线程的。你这个方法不一定能有效解决多图表情况下页面卡顿的问题。建议可以加一些类似 “懒加载” 之类的逻辑，异步创建 chart 实例，异步渲染，这样可能性能好一点

**Comment by chenshuai2144** [comment]
配合一下 requestAnimationFrame 
10个图表.
帧率能到30..也能接受了,只有一个界面是这样的.

大屏图表用了 Web Workers.+queueRender..帧率还是上不去.
还有什么办法能优化?

**Comment by leungwensen** [comment]
大屏如果要做极致的优化的话，甚至可以先用 electron 或者更上层的产品（譬如 nightmare）给每个图表截图，用截图做图表容器的背景，然后按照你想要的频率来逐个渲染就好

**Comment by chenshuai2144** [comment]
我试试  nightmare,特别感谢
