### ISSUE TITLE
折线图 data存在null值，在 geometry上设置tooltip，空值位置依旧会显示

### ISSUE THREAD

**Issue by guishilike** [antvis/G2#2691]
* **G2 Version**:4.0.12
* **Platform**:chrome
* **Link**:https://antv-g2.gitee.io/zh/examples/line/basic
官方基础折线图
* **image**
![image](https://user-images.githubusercontent.com/51023060/88271116-4b4da180-cd09-11ea-83ab-931b0a863cf7.png)
* **Code**
import { Chart } from '@antv/g2';

```
 const data = [
  { year: '1991', value: 3 },
  { year: '1992', value: null },
  { year: '1993', value: 3.5 },
  { year: '1994', value: 5 },
  { year: '1995', value: 4.9 },
  { year: '1996', value: 6 },
  { year: '1997', value: 7 },
  { year: '1998', value: 9 },
  { year: '1999', value: 13 },
];
const chart = new Chart({
  container: 'container',
  autoFit: true,
  height: 500,
});

chart.data(data);
chart.scale({
  year: {
    range: [0, 1],
  },
  value: {
    min: 0,
    nice: true,
  },
});

chart.tooltip({
  showCrosshairs: true, // 展示 Tooltip 辅助线
  shared: true,
});

chart.line().position('year*value').label('value').tooltip('year*value',(x,y)=>{return{title:x,name:'value',value:y}});
chart.point().position('year*value');

chart.render();

```

**Comment by guishilike** [comment]
![image](https://user-images.githubusercontent.com/51023060/88535745-16a95500-d03d-11ea-81c2-6ea22ca57478.png)
tooltip name value重复

**Comment by hustcc** [comment]
我在最新版本中测试是 ok 的，没有上述问题。

![image](https://user-images.githubusercontent.com/7856674/106259495-4b9b9c00-625a-11eb-9235-c7e923a30722.png)
