### ISSUE TITLE
【bug】slider默认设置的start，end和图表渲染不一致

### ISSUE THREAD

**Issue by TheBaldGirl** [antvis/G2#2693]
关于slider的使用，有几个问题：

**1.slider默认设置的start，end和图表渲染不一致，等到拖动之后才会对应；**
**2.即使配置了padding：auto，设置slider后还是会和图例重叠，并且默认滚动条和轴的距离是按照最长的轴值渲染的，后续拖动滚动条之后并没有自适应；**
**3.针对轴值、图例、轴标题、slider有没有自适应的方案？**

* **G2 Version**:  4.0.13
* **CodePen Link**: https://codepen.io/thebaldgirl/pen/NWxJged

**Comment by hustcc** [comment]
对于第三点，自适应方案是指什么？

**Comment by TheBaldGirl** [comment]
最新版本第二个问题已经解决了，第三个问题的话，轴值倾斜的情况下轴标题仍然会重叠。

重现链接: https://codepen.io/thebaldgirl/pen/WNwyBjq

**Comment by hustcc** [comment]
1 2 问题在 4.1 beta 版本中解决，大概 930 会发布正式版本。 问题 3 抽空看一下，我在新版本中发现也没有问题的。

![image](https://user-images.githubusercontent.com/7856674/93412660-2a03ce80-f8d0-11ea-97b5-85131987938d.png)

**Comment by TheBaldGirl** [comment]
> 1 2 问题在 4.1 beta 版本中解决，大概 930 会发布正式版本。 问题 3 抽空看一下，我在新版本中发现也没有问题的。
> 
> ![image](https://user-images.githubusercontent.com/7856674/93412660-2a03ce80-f8d0-11ea-97b5-85131987938d.png)

 好嘞！谢谢！问题三是我是在轴值倾斜的情况下重现出来的。
