### ISSUE TITLE
分组柱状图设置size属性的时候回导致视图堆叠

### ISSUE THREAD

**Issue by seafronthu** [antvis/G2#2695]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/staging-https-u975u?file=/src/index.js)

### Steps to reproduce
添加柱状图大小 size
https://codesandbox.io/s/staging-https-u975u?file=/src/index.js
| Environment | Info |
|---|---|
| g2 | 4.0.13 |
| System | macOs |
| Browser | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 |

---
在chart.interval(...).color(...).size(50) 设置之后会导致分组柱状图图形重叠在一起

期望：就是不要重叠在一起

**Comment by hustcc** [comment]
因为 size(n) 中的 n 是像素值，所以设置过大的时候，在画布小数据多的时候一定会导致重叠。
