### ISSUE TITLE
怎么获取axis中label的宽高

### ISSUE THREAD

**Issue by TheBaldGirl** [antvis/G2#2696]
怎么获取x、y轴轴值的最大高度和宽度？

**Comment by DarrenPei** [comment]
https://g2.antv.vision/zh/docs/api/chart-func

**Comment by hustcc** [comment]
> https://g2.antv.vision/zh/docs/api/chart-func

可以在回复详细一下，直接我代码，甚至 live demo~

**Comment by TheBaldGirl** [comment]
最开始是因为图表轴值、标题、图例、滚动条等会重叠，所以想要获取轴值的高度去计算padding达到不重叠的效果，但是不知道怎么才能获取到...

不过，目前的版本基本上重叠问题已经解决了~

**Comment by hustcc** [comment]
那 issue 关闭了。^_^
