### ISSUE TITLE
4.x 缺少水波图示例

### ISSUE THREAD

**Issue by cipchk** [antvis/G2#2697]
* **G2 Version**: latest
* **Platform**: All
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

麻烦提供一个基于 4.x 的水波图示例。

**Comment by hustcc** [comment]
我们会在 [G2Plot](https://g2plot-v2-beta.antv.vision/zh/examples/liquid/basic) 中提供可用的版本，在 G2 中暂不提供。c

**Comment by li1164267803** [comment]
> 我们会在 [G2Plot](https://g2plot-v2-beta.antv.vision/zh/examples/liquid/basic) 中提供可用的版本，在 G2 中暂不提供。G2Plot v2 正式版本大概在 930 发布。

在 G2Plot 提供的话，我们项目中还要在安装一个 G2Plot ，不太友好哇

**Comment by hustcc** [comment]
> > 我们会在 [G2Plot](https://g2plot-v2-beta.antv.vision/zh/examples/liquid/basic) 中提供可用的版本，在 G2 中暂不提供。G2Plot v2 正式版本大概在 930 发布。
> 
> 在 G2Plot 提供的话，我们项目中还要在安装一个 G2Plot ，不太友好哇

可以参考直接 G2Plot 的代码 copy 过去就可以了。水波图的代码还是有点多，直接放 demo 中也不是很合适。

**Comment by li1164267803** [comment]
> > > 我们会在 [G2Plot](https://g2plot-v2-beta.antv.vision/zh/examples/liquid/basic) 中提供可用的版本，在 G2 中暂不提供。G2Plot v2 正式版本大概在 930 发布。
> > 
> > 
> > 在 G2Plot 提供的话，我们项目中还要在安装一个 G2Plot ，不太友好哇
> 
> 可以参考直接 G2Plot 的代码 copy 过去就可以了。水波图的代码还是有点多，直接放 demo 中也不是很合适。

我看过了。。。。里面各种引用的代码太多了，而且现在一般公司代码都是使用js去编写，查看ts编译后的js，引用的文件属实是有点多

**Comment by hurricane1998** [comment]
大佬，可以说一下copy哪些代码放到哪些位置吗？我把liquid.ts文件里的大部分函数都拿过去了还是什么都没有渲染出来
