### ISSUE TITLE
legend 若开启 custom 会导致 legend-filter 数据过滤交互失效

### ISSUE THREAD

**Issue by cipchk** [antvis/G2#2698]
* **G2 Version**: laster
* **Platform**: All
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**点击 legend 无法自动调整数据。**

> StackBlitz 无法运行示例，以下是完整代码，可以打开官网任意页面，例如[legend-visible-filter示例](https://g2.antv.vision/zh/examples/interaction/component#legend-visible-filter)，复制以下代码即可以复现。

```ts
import { Chart } from '@antv/g2';

const data = [
  { month: 'Jan', city: 'Tokyo', temperature: 7 },
  { month: 'Jan', city: 'London', temperature: 3.9 },
  { month: 'Feb', city: 'Tokyo', temperature: 6.9 },
  { month: 'Feb', city: 'London', temperature: 4.2 },
  { month: 'Mar', city: 'Tokyo', temperature: 9.5 },
  { month: 'Mar', city: 'London', temperature: 5.7 },
  { month: 'Apr', city: 'Tokyo', temperature: 14.5 },
  { month: 'Apr', city: 'London', temperature: 8.5 },
  { month: 'May', city: 'Tokyo', temperature: 18.4 },
  { month: 'May', city: 'London', temperature: 11.9 },
  { month: 'Jun', city: 'Tokyo', temperature: 21.5 },
  { month: 'Jun', city: 'London', temperature: 15.2 },
  { month: 'Jul', city: 'Tokyo', temperature: 25.2 },
  { month: 'Jul', city: 'London', temperature: 17 },
  { month: 'Aug', city: 'Tokyo', temperature: 26.5 },
  { month: 'Aug', city: 'London', temperature: 16.6 },
  { month: 'Sep', city: 'Tokyo', temperature: 23.3 },
  { month: 'Sep', city: 'London', temperature: 14.2 },
  { month: 'Oct', city: 'Tokyo', temperature: 18.3 },
  { month: 'Oct', city: 'London', temperature: 10.3 },
  { month: 'Nov', city: 'Tokyo', temperature: 13.9 },
  { month: 'Nov', city: 'London', temperature: 6.6 },
  { month: 'Dec', city: 'Tokyo', temperature: 9.6 },
  { month: 'Dec', city: 'London', temperature: 4.8 },
];

const chart = new Chart({
  container: 'container',
  autoFit: true,
  height: 500,
});

chart.data(data);
chart.scale({
  month: {
    range: [0, 1],
  },
  temperature: {
    nice: true,
  },
});

chart.tooltip({
  showCrosshairs: true,
  shared: true,
});

chart.axis('temperature', {
  label: {
    formatter: (val) => {
      return val + ' °C';
    },
  },
});

chart
  .line()
  .position('month*temperature')
  .color('city')
  .shape('smooth');

chart
  .point()
  .position('month*temperature')
  .color('city')
  .shape('circle')
  .style({
    stroke: '#fff',
    lineWidth: 1,
  });

chart.legend({
  position: 'top',
  custom: true,
  items: [
    { name: 'Tokyo', value: 'Tokyo' },
    { name: '伦敦', value: 'London' }
  ]
});


chart.render();
```

**Comment by xiaobindebingo** [comment]
我看了下源码，关于custom为true的时候会调用getCustomLegendItems，这个方法，查了一下并没有bind相关filter事件，个人感觉你这个写法挺奇怪的，要不试试这样应该也满足你的要求吧
`
import { Chart } from '@antv/g2';

const data = [
  { month: 'Jan', city: 'Tokyo', temperature: 7 },
  { month: 'Jan', city: 'London', temperature: 3.9 },
  { month: 'Feb', city: 'Tokyo', temperature: 6.9 },
  { month: 'Feb', city: 'London', temperature: 4.2 },
  { month: 'Mar', city: 'Tokyo', temperature: 9.5 },
  { month: 'Mar', city: 'London', temperature: 5.7 },
  { month: 'Apr', city: 'Tokyo', temperature: 14.5 },
  { month: 'Apr', city: 'London', temperature: 8.5 },
  { month: 'May', city: 'Tokyo', temperature: 18.4 },
  { month: 'May', city: 'London', temperature: 11.9 },
  { month: 'Jun', city: 'Tokyo', temperature: 21.5 },
  { month: 'Jun', city: 'London', temperature: 15.2 },
  { month: 'Jul', city: 'Tokyo', temperature: 25.2 },
  { month: 'Jul', city: 'London', temperature: 17 },
  { month: 'Aug', city: 'Tokyo', temperature: 26.5 },
  { month: 'Aug', city: 'London', temperature: 16.6 },
  { month: 'Sep', city: 'Tokyo', temperature: 23.3 },
  { month: 'Sep', city: 'London', temperature: 14.2 },
  { month: 'Oct', city: 'Tokyo', temperature: 18.3 },
  { month: 'Oct', city: 'London', temperature: 10.3 },
  { month: 'Nov', city: 'Tokyo', temperature: 13.9 },
  { month: 'Nov', city: 'London', temperature: 6.6 },
  { month: 'Dec', city: 'Tokyo', temperature: 9.6 },
  { month: 'Dec', city: 'London', temperature: 4.8 },
];
const filterData = data.map(item=>{
  if(item.city === 'London'){
    return {...item, city: "伦敦"}
  }
  return item
})
const chart = new Chart({
  container: 'container',
  autoFit: true,
  height: 500,
});

chart.data(filterData);
chart.scale({
  month: {
    range: [0, 1],
  },
  temperature: {
    nice: true,
  },
});

chart.tooltip({
  showCrosshairs: true,
  shared: true,
});

chart.axis('temperature', {
  label: {
    formatter: (val) => {
      return val + ' °C';
    },
  },
});

chart
  .line()
  .position('month*temperature')
  .color('city')
  .shape('smooth');

chart
  .point()
  .position('month*temperature')
  .color('city')
  .shape('circle')
  .style({
    stroke: '#fff',
    lineWidth: 1,
  });
chart.legend({
  position: 'top',
});


chart.render();
`

**Comment by xiaobindebingo** [comment]
`let a =1`

**Comment by cipchk** [comment]
目前找到比较适合的方案就是利用 `legend-item:click` 事件，调整隐藏或显示。

```ts
chart.on(`legend-item:click`, (ev: Event) => {
  const item = ev?.target?.get('delegateObject').item;
  const id = item?.id;
  const line = chart.geometries.find(w => w.getAttribute('position').getFields()[1] === id);
  if (line) {
    line.changeVisible(!item.unchecked);
  }
});
```
