### ISSUE TITLE
在使用了combinColumns后如何修改图例文字

### ISSUE THREAD

**Issue by xiehurricane** [antvis/g2#27]
frame = Frame.combinColumns(frame, ['highPress', 'lowPress', 'pulseRate'], 'value', 'vv', 'date');

highPress这些需要显示中文(⊙﹏⊙)b
在source方法 defs 里面设置type：cat value：xx 不行
使用chart.legend 没看到有这个设置

**Comment by xiehurricane** [comment]
暂时自己循环data数组，给每一项新加了中文属性……

**Comment by TomHuangCN** [comment]
试试defs 里 formatter 方法
