### ISSUE TITLE
How to emit a single event on  a facet `interval` char 

### ISSUE THREAD

**Issue by NoraGithub** [antvis/g2#270]
1. We are constructing a  Grouped/Stacked bar char.
I am wondering how to emit one exact event on different legend?

![dingtalk20171212102438](https://user-images.githubusercontent.com/7700016/33864614-885fecda-df28-11e7-991d-588f01ba0aff.png)
![dingtalk20171212102511](https://user-images.githubusercontent.com/7700016/33864619-8f487d32-df28-11e7-9044-6531e09c0de4.png)

The closet way from the doc may be the `interval` event? However, it track 2 or more events one time.

2. Actually, we are constructing   Grouped/Stacked bar chars by different facets
 
It's facing a similar issue that it emits too many events even in a faceted unstacked/ungrouped view.

![dingtalk20171212103212](https://user-images.githubusercontent.com/7700016/33864642-aa9e014c-df28-11e7-8e34-b2bdbf7f0c6b.png)

And there would be more events when stacked/grouped because describe above.

Hope to get some suggestions about how to emit an detailed event from you.(It would also be OK even in a hack way)

**Comment by leungwensen** [comment]
You can get origin data from the event object:

```js
chart.on('interval:click', evt => {
   const originData = evt.data._origin;
});
```

**Comment by dxq613** [comment]
In a faceted unstacked/ungrouped view, you  can use view's event.

view.on('interval:click', evt => {
   const originData = evt.data._origin;
});

**Comment by NoraGithub** [comment]
I see. I made some mistakes on the `1`, because I tested it in the facet view .

What `2` matters is that it emits too many repeated events.
I modified the faceted char [here](https://antv.alipay.com/zh-cn/g2/3.x/demo/facet/row.html)by the code below.
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,height=device-height">
    <title>行分面</title>
    <style>::-webkit-scrollbar{display:none;}html,body{overflow:hidden;height:100%;}</style>
</head>
<body>
<div id="mountNode"></div>
<script>/*Fixing iframe window.innerHeight 0 issue in Safari*/document.body.clientHeight;</script>
<script src="https://gw.alipayobjects.com/os/antv/assets/g2/3.0.0/g2.min.js"></script>
<script src="https://gw.alipayobjects.com/os/antv/assets/data-set/0.7.0/data-set.min.js"></script>
<script src="https://gw.alipayobjects.com/os/antv/assets/lib/jquery-3.2.1.min.js"></script>
<script>
  $.getJSON('/assets/data/diamond.json', function(data) {
    const chart = new G2.Chart({
      container: 'mountNode',
      forceFit: true,
      height: window.innerHeight,
      padding: [40, 80, 80, 80]
    });
    chart.source(data, {
      carat: {
        sync: true
      },
      price: {
        sync: true,
        tickCount: 3
      },
      clarity: {
        sync: true
      }
    });
    chart.facet('rect', {
      fields: [ null, 'clarity' ],
      eachView(view) {
        view.interval()
          .position('carat*price')
          .color('clarity')
          .opacity(0.3)
          .size(3);
        view.on('interval:click',ev=>{
              console.log('click',ev.data._origin)
            })
      }
    });
    chart.render();
  });
</script>
</body>
</html>

```

It emits 8 events every single click.

![dingtalk20171212121631](https://user-images.githubusercontent.com/7700016/33867241-53ac78ba-df36-11e7-914d-3e0807a2763b.png)

How should  I fix this?

**Comment by NoraGithub** [comment]
I think it out after lunch.
```
chart.facet(..)
chart.on(...)
```
Your answer is clear. My wrong

**Comment by dxq613** [comment]
thanks !
view.on has a bug, it must emit once. I should fixed it next version.
