### ISSUE TITLE
坐标轴旋转后 padding 计算有误

### ISSUE THREAD

**Issue by simaQ** [antvis/G2#2702]
* 如图：
![image](https://user-images.githubusercontent.com/6628666/88515904-008c9c00-d01f-11ea-9782-7ce5019e7a4f.png)

* 复现链接： http://riddle.alibaba-inc.com/riddles/38c3715c

* 如图：
![2020-07-27 19-36-31 2020-07-27 19_38_09](https://user-images.githubusercontent.com/6628666/88537814-d3e97c00-d040-11ea-8bd2-425915a8ea8a.gif)

* 复现链接：http://riddle.alibaba-inc.com/riddles/e1d59a33

![image](https://user-images.githubusercontent.com/6628666/88563776-f2fa0500-d064-11ea-8f37-cdc0e8507bc0.png)

**Comment by hustcc** [comment]
无法修复，只能不设置旋转。从 3.x 延续到 4.x 的无法解决的 bug。只待 5.x 去解决了。
