### ISSUE TITLE
legend设置offsetY属性时，点击图例时图例位置会发生偏移

### ISSUE THREAD

**Issue by TheBaldGirl** [antvis/G2#2714]
问题描述：如题，给legend设置offsetY图例 y 方向的偏移，希望达到的效果是默认状态就有这个偏移，现在的效果是点击图例时会位置会发生偏移。如果图表设置了slider，拖动slider时也会有偏移。

* **G2 Version**: 4.0.14
* **CodePen Link**: https://codepen.io/thebaldgirl/pen/dyGEBrj

**Comment by Sai0514** [comment]
同问

**Comment by hustcc** [comment]
重复问题：https://github.com/antvis/G2/issues/2621
