### ISSUE TITLE
G2 宽度自适应好像并不是根据父类容器宽度变化自适应的

### ISSUE THREAD

**Issue by Rabbitzzc** [antvis/G2#2715]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/gallery/line#line1](https://g2.antv.vision/zh/examples/gallery/line#line1)

### Steps to reproduce
1. 打开官网任意一个图表案例
2. 打开控制台，隐藏侧边栏
3. 观察图表自适应情况
![image](https://user-images.githubusercontent.com/26913511/88902094-4e560e00-d284-11ea-9e52-65b271478a41.png)

| Environment | Info |
|---|---|
| g2 | 4.0.14 |
| System | mac os |
| Browser | chrome83 |

**Comment by Rabbitzzc** [comment]
理想中的效果：应该是这种根据父类块大小自适应的：https://gallery.echartsjs.com/editor.html?c=xXbP45bsC

**Comment by Rabbitzzc** [comment]
源码中是通过
```js
window.addListener('resize', func)
```
对于父类容器如果宽度变化，而窗口未变化，则不会触发

**Comment by hustcc** [comment]
> 源码中是通过
> 
> ```js
> window.addListener('resize', func)
> ```
> 
> 对于父类容器如果宽度变化，而窗口未变化，则不会触发

暂时可以在外部使用 [ResizeObserve](https://github.com/hustcc/size-sensor) 去监听容器，然后获得容器大小之后调用 chart.changeSize(w, h)

**Comment by hustcc** [comment]
后续不排除在 G2 中直接支持掉，但是时间上不能确定。

**Comment by Rabbitzzc** [comment]
> > 源码中是通过
> > ```js
> > window.addListener('resize', func)
> > ```
> > 
> > 
> > 对于父类容器如果宽度变化，而窗口未变化，则不会触发
> 
> 暂时可以在外部使用 [ResizeObserve](https://github.com/hustcc/size-sensor) 去监听容器，然后获得容器大小之后调用 chart.changeSize(w, h)

是，我看`Chart.js`是使用`ResizeObserve `的，不过兼容性确实是问题。但我理解都涉及到图表展示了，浏览器版本一般都不是问题

**Comment by Rabbitzzc** [comment]
> > > 源码中是通过
> > > ```js
> > > window.addListener('resize', func)
> > > ```
> > > 
> > > 
> > > 对于父类容器如果宽度变化，而窗口未变化，则不会触发
> > 
> > 
> > 暂时可以在外部使用 [ResizeObserve](https://github.com/hustcc/size-sensor) 去监听容器，然后获得容器大小之后调用 chart.changeSize(w, h)
> 
> 是，我看`Chart.js`是使用`ResizeObserve `的，不过兼容性确实是问题。但我理解都涉及到图表展示了，浏览器版本一般都不是问题

**Comment by Rabbitzzc** [comment]
> > 源码中是通过
> > ```js
> > window.addListener('resize', func)
> > ```
> > 
> > 
> > 对于父类容器如果宽度变化，而窗口未变化，则不会触发
> 
> 暂时可以在外部使用 [ResizeObserve](https://github.com/hustcc/size-sensor) 去监听容器，然后获得容器大小之后调用 chart.changeSize(w, h)

不推荐使用`changeSize`，应该用`onResize`函数，`changeSize`效果会有白屏

**Comment by hustcc** [comment]
> > > 源码中是通过
> > > ```js
> > > window.addListener('resize', func)
> > > ```
> > > 
> > > 
> > > 对于父类容器如果宽度变化，而窗口未变化，则不会触发
> > 
> > 
> > 暂时可以在外部使用 [ResizeObserve](https://github.com/hustcc/size-sensor) 去监听容器，然后获得容器大小之后调用 chart.changeSize(w, h)
> 
> 是，我看`Chart.js`是使用`ResizeObserve `的，不过兼容性确实是问题。但我理解都涉及到图表展示了，浏览器版本一般都不是问题

那也不对，使用 canvas 的图表，可以到 ie9，原生 ResizeObserve 可到不了 ie9, ie11 可能都不支持（加上 polyfill 即可）。
