### ISSUE TITLE
The size of the circle should be mapped to its area, not its radius（圆形尺寸应该映射为面积而非半径）

### ISSUE THREAD

**Issue by jiazhewang** [antvis/G2#2716]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
"The human visual system naturally experiences a disk's size in terms of its area. And the area of a disk—unlike its diameter or circumference—is not proportional to its radius, but to the square of the radius. So if one chooses to scale the disks' radii to the third data values directly, then the apparent size differences among the disks will be non-linear (quadratic) and misleading. To get a properly weighted scale, one must scale each disk's radius to the square root of the corresponding data value "

quoted from https://en.wikipedia.org/wiki/Bubble_chart

### What does the proposed API look like?
The api does not need to be changed, it is recommended to modify the internal logic

**Comment by Me-Momo** [comment]
确实应该映射为面积，这里 point 映射 size 通道，应该将 sqrt(size) 作为半径

**Comment by jiazhewang** [comment]
包括 heatmap 里面的自定义 shape：square 这些，也都应该映射为面积。

@simaQ  @hustcc 看看如何，我们如果统一下心智的话 G2 栈相应的实现、文档都可以更新一下

**Comment by hustcc** [comment]
从图形映射来看，确实是映射到半径了（文档上明确 size 就是指半径即可），但是从业务理解上看，数据映射到面积。

所以在用 G2 这一层:

```ts
chart.point().size('value', (size) => sqrt(size))
```

但是在 G2Plot 这一层，就直接内部包掉，默认用户不感知。

---

在 echarts 中，也是指定半径大小，然后开发者自己去转数据。

![image](https://user-images.githubusercontent.com/7856674/89169708-25e65080-d5b1-11ea-92eb-26ae5e1c485e.png)

**Comment by jiazhewang** [comment]
> 从图形映射来看，确实是映射到半径了（文档上明确 size 就是指半径即可），但是从业务理解上看，数据映射到面积。
> 
> 所以在用 G2 这一层:
> 
> ```ts
> chart.point().size('value', (size) => sqrt(size))
> ```
> 
> 但是在 G2Plot 这一层，就直接内部包掉，默认用户不感知。
> 
> 在 echarts 中，也是指定半径大小，然后开发者自己去转数据。
> 
> ![image](https://user-images.githubusercontent.com/7856674/89169708-25e65080-d5b1-11ea-92eb-26ae5e1c485e.png)

结论是？

G2 这层让用户自己去做映射操作，G2Plot 这一层我们默认处理为 sqrt （映射到面积）是么？

**Comment by hustcc** [comment]
是的，我是这想法。

**Comment by jiazhewang** [comment]
> 是的，我是这想法。

可以，如果没有反对意见，我们就这么搞吧！
