### ISSUE TITLE
g2 4.X geometry.label() 接口更新，不再支持 html 类型的 label 以后要怎么自定义html类型的label 可以支持react写法么？

### ISSUE THREAD

**Issue by lgy1159** [antvis/G2#2719]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by lgy1159** [comment]
@ @simaQ

**Comment by hustcc** [comment]
@lgy1159 可以告知一下你的使用场景吗？

**Comment by hustcc** [comment]
4.x 中暂时不再支持，后面是否支持会看具体的使用场景。
