### ISSUE TITLE
区块图有波浪性质的效果

### ISSUE THREAD

**Issue by yangbin1994** [antvis/g2#272]
![image](https://user-images.githubusercontent.com/12080165/33867945-df2fe422-df3a-11e7-90b7-eb98fff17555.png)

如图，数据是平滑的，但是却出现了波浪的感觉
 "g2": "^2.3.8",
 "g2-react": "^1.3.0",

**Comment by dxq613** [comment]
什么区块图？写一下对应图表的语法

**Comment by yangbin1994** [comment]
@dxq613 不好意思，是[色块图](http://antv.alipay.com/zh-cn/g2/3.x/demo/heatmap/basic.html)
我刚升级到3.0，问题解决了，api有些变化，还得改一改～3q

**Comment by dxq613** [comment]
OK
