### ISSUE TITLE
G2  饼图的百分比计算是否有问题

### ISSUE THREAD

**Issue by JasonSubMara** [antvis/G2#2720]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/determined-hamilton-e1z54)

### Steps to reproduce
饼图的数据似乎在占比为奇数的时候，算出来的一个百分比数值有问题。

| Environment | Info |
|---|---|
| g2 | 4.0.14 |
| System | Windows 10 |
| Browser | Google Chrome 版本 84.0.4147.105（正式版本） （64 位） |

### BUG截图：
![bug01](https://user-images.githubusercontent.com/30927318/89013142-f384eb00-d345-11ea-8bea-54010738a1d6.png)

---
期望结果：优化计算精度。

**Comment by hustcc** [comment]
可以在 formatter 中自定义的去做一个 toFix(2)

**Comment by JasonSubMara** [comment]
> 可以在 formatter 中自定义的去做一个 toFix(2)

可以这么做，对于可视化比较感兴趣，但是目前只做到了能够比较熟练得使用Echarts，正在一步步转到AntV这边，在公司团队内也已经劝服设计师使用ChartCube 来出一些设计稿，现在有些困惑得是这个bug产生得原因，因为在大部分偶数情况下得分布则不会出现我给的图中得问题，不知道是因为G2团队底层得计算精度不足还是因为图表自身得原因。有些迷糊。

**Comment by hustcc** [comment]
> > 可以在 formatter 中自定义的去做一个 toFix(2)
> 
> 可以这么做，对于可视化比较感兴趣，但是目前只做到了能够比较熟练得使用Echarts，正在一步步转到AntV这边，在公司团队内也已经劝服设计师使用ChartCube 来出一些设计稿，现在有些困惑得是这个bug产生得原因，因为在大部分偶数情况下得分布则不会出现我给的图中得问题，不知道是因为G2团队底层得计算精度不足还是因为图表自身得原因。有些迷糊。

这个是 js 的浮点数极端进度问题，举例就是 0.1 + 0.2 = 0.30000000000000004 这类问题。要是底层解决的话，主要要办法：

1. 所有的四则运算都使用精度运算
2. 所有的数据显示的地方都默认 formatter 掉

但是这两种方式底层直接处理都不是很好（方法 2 基本算可行），所以最好还是业务来处理。

---- 

另外，如果对 G2/G2Plot 整个图表栈感兴趣，欢迎来贡献啊。可以先从这个入手 https://github.com/antvis/G2Plot/issues/1384
