### ISSUE TITLE
矩形树图label颜色设置失效

### ISSUE THREAD

**Issue by luguanrui** [antvis/G2#2724]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g2plot-reproduction-template-syxrk?file=/src/index.js)

### Steps to reproduce
  label: {
    visible: true,
    style: {
      fontSize: "13",
      fill: "#fff"
    }
  }

| Environment | Info |
|---|---|
| g2 | 4.0.14 |
| System | - |
| Browser | - |

**Comment by liuzhenying** [comment]
看语法你使用是g2 plot v1 版本？

**Comment by liuzhenying** [comment]
g2 
```
.label('name', {
    style: {
      fill: "#f00"
    },
  });
```

g2 plot  v2 是
```
  label: {
    style: {
      fill: '#f00'
    } 
  }
```
都是有效的
g2 plot v1 不再维护
