### ISSUE TITLE
type.d.ts can use English comments?

### ISSUE THREAD

**Issue by unnhao** [antvis/G2#2728]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Becuase a lot of developer isn't chinese, so... I think english is more better.

### What does the proposed API look like?
skip

**Comment by simaQ** [comment]
@BBSQQ 支持下？

**Comment by hustcc** [comment]
代码中的中文注释，我们会尽量做到双语，但是这个优先级会很低很低，毕竟我们现在文档都做不好。 issue 先关闭了~~
