### ISSUE TITLE
tooltip上可以添加按钮吗，怎么绑定点击事件

### ISSUE THREAD

**Issue by yangleiup** [antvis/G2#2729]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
tooltip上可以添加按钮吗，怎么绑定点击事件

### What does the proposed API look like?
tooltip上可以添加按钮吗，怎么绑定点击事件

**Comment by hustcc** [comment]
使用 [container](https://github.com/antvis/G2/blob/master/src/interface.ts#L1170) 指定一个自己创建的 dom 节点，然后在这个 dom 节点中，自己去绘制 tooltip 的 按钮，事件绑定也有自己来决定。
