### ISSUE TITLE
How to prevent the default zoom behaviour when range selected? 

### ISSUE THREAD

**Issue by dengfuping** [antvis/g2#273]
Is there such a method for chart, like this

`chart.on('rangeselectend', e => e.preventDefault())`

to prevent the zoom behavior. If not, hope to add the feature for some special needs.

**Comment by weifansc** [comment]
My issue is the opposite... I am trying to enable the zoom behavior, but cannot find it in G2 3.0, at least not from the docs.

**Comment by leungwensen** [comment]
@weifansc https://github.com/antvis/g2-brush
