### ISSUE TITLE
官网说明网站好慢

### ISSUE THREAD

**Issue by ckmilse** [antvis/G2#2730]
* **G2 Version**:
https://g2-v3.antv.vision/zh/examples/gallery
猜测依赖 https://g2-v3.antv.vision/page-data/zh/examples/gallery/column/page-data.json 这个接口。
网站打开翻页好慢
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by hustcc** [comment]
G2 v3 的官网，都在 GitHub 的 gh-pages，确实对国内部分网络会比较忙，建议：

1. “网路助手”
2. clone [v3 网站仓库](https://github.com/antvis/g2-3.x-site)，然后本地运行起来。
