### ISSUE TITLE
4.0中使用配置项创建图表，首次能实现coordinate的配置，用updateOptions更改coordinate的配置然后render不成功

### ISSUE THREAD

**Issue by FishChung** [antvis/G2#2731]
* **G2 Version**: 4.0
* **Platform**: 
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by simaQ** [comment]
提供一个可以复现的 demo?

**Comment by laukin** [comment]
我也出现这个问题。
在线示例： [http://jsrun.net/BfLKp/edit](url)
