### ISSUE TITLE
x轴可以定义两条

### ISSUE THREAD

**Issue by zsirfs** [antvis/G2#2736]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在一些对比数据图表中，希望直观的在x轴显示两个数据对比的维度

### What does the proposed API look like?
定义多个axis，并从data中获取到这个维度的数据, 具体的API的话，还是由专业的同学来决定吧。

**Comment by hustcc** [comment]
能有一个具体的数据例子吗？看不出不同 x 维值怎么对比。

我知道的场景，比如本周七天和上周七天的利润趋势对比，但是这个场景中，两个 x 轴还是有共性的。

**Comment by zsirfs** [comment]
@huacnlee 你在蚂蚁吗？我找你沟通

**Comment by zsirfs** [comment]
钉钉我找你沟通
