### ISSUE TITLE
guide 使用改进需求

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#274]
http://riddle.alibaba-inc.com/riddles/ddba3daa

![image](https://user-images.githubusercontent.com/3838676/33873633-bdfcc010-df56-11e7-9e65-b8db1cf437db.png)

这种常见图表，用户很常用的需求是，legend 点击的时候，线以及该线对应的平均线一起隐藏，用 G2 可以实现，但不是特别好做。 需要在 legend 的交互事件监听函数中，记录各种状态，将 geom 对应的线隐藏掉。

有没有更方便的用户去满足这种常见图表的需求。

**Comment by dxq613** [comment]
问题是怎么将 guide  和图例自然的结合到一起呢？又得使得语法很自然

**Comment by weepy3641** [comment]
@dxq613   @leungwensen 

思考这种情况下，为什么用户想要用 legend 同时操作 geom 和 guide。

对于用户来说，他不明白 多条线的产生是应为 colorby 对数据分组了，分组后每组数据都用 line 展现了。同时 legend 的显示实际上是 colorby 的视觉展现。

他仅仅想要用 legend 同时操作线图及这跟线对应的平均值。

我觉得这里的根源是：  guide 的数据源是分组后某一组数据的均值，单个线图的数据源是分组后的某一组数据。
离散 legend 的交互操作实际上是在对不同分组的数据进行筛选，也就是展现不同分组的数据。
因此这种图表上联动的交互，本质上还是数据的关联性体现。
这个地方legend 的交互，线会消失，实际上就是我这个组下的数据都已经被过滤了，那么这组数据的平均值还要显示吗？还会显示吗？

所以更好的 api 去做这类事情，应该是朝这个方向的。

例如有没有途径能够让 guide 的数据源 跟 geom 的数据源关联起来，那么 legend 的交互操作(过滤数据)的时候自然就跟 guide 绑定在一起了。

**Comment by dxq613** [comment]
如果按照这种思路的话，可能需要在 Geometry 的层次上增加 guilde 了，因为这些均值、最大值之类的是对单个 geometry 的数据有意义的。但是这样去实现问题也很多，不太好理解。

```js

chart.line().position('x*y').color('type')
         .guide({
            type: 'line',
            from: ['min', 'mean'],
            to: ['max', 'mean']
         })
```
标记 from to 的字段需要使用统计值来标识，不是很好理解。

还有另外一种方案，就是这些虚线不适用 guide 而是自定义 shape  ，自己定义一个 'line-with-mean'  的shape ，在绘制了直线之外，额外绘制一条虚线。

**Comment by weepy3641** [comment]
或者有没有办法可以去指定 Guide 数据源为分组数据，对于数据的操作是 mean，用 guide line 去绘制，有点类似geom的描述。

guideline.data(data).color()

ggplot：
ggplot(pd.melt(meat, id_vars=['date']), aes(x='date', y='value', color='variable')) +\
    geom_line() + ge o m

**Comment by LinFeng1997** [comment]
@weepy3641 链接打不开了，请问哪里可以看到这个例子
