### ISSUE TITLE
g2 legend api文档打开404

### ISSUE THREAD

**Issue by aminwangaa** [antvis/G2#2740]
https://g2.antv.vision/zh/docs/api/classes/chart/#legend
g2 legend api文档打开404

**Comment by hustcc** [comment]
这个地址是从哪里点击进去的？

**Comment by lvSally** [comment]
> 这个地址是从哪里点击进去的？

https://g2.antv.vision/zh/docs/manual/tutorial/legend
` API`入口点击404， 。

**Comment by hustcc** [comment]
API 文档已经重新梳理。
