### ISSUE TITLE
chart.annotation().line({}) 不支持动态图形标注

### ISSUE THREAD

**Issue by zhouyu1993** [antvis/G2#2754]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如果数据发生改变，可以动态更新 annotation().line

### What does the proposed API look like?
chart.annotation().line({}) 支持动态图形标注，其 start、end 类似 chart.annotation().dataMarker({}) 的 position 是回调函数，函数原型： function(xScale, yScales) {return [];}
xScale, yScales 分别对应 x 轴的度量和所有 y 轴的度量。而且 xScale, yScales 允许数字或字符串

**Comment by zhouyu1993** [comment]
https://g2.antv.vision/zh/docs/manual/tutorial/annotation#%E5%8A%A8%E6%80%81%E5%9B%BE%E5%BD%A2%E6%A0%87%E6%B3%A8

这里提到「辅助标记一旦生成后就是固定了位置，如果数据发生改变，辅助标记就需要删除掉重新创建。」

怎么删除掉重新创建？

**Comment by simaQ** [comment]
start 和 end 也同样支持回调的呀，试过没有？

**Comment by simaQ** [comment]
> https://g2.antv.vision/zh/docs/manual/tutorial/annotation#%E5%8A%A8%E6%80%81%E5%9B%BE%E5%BD%A2%E6%A0%87%E6%B3%A8
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/13276621/90514343-a4d3af80-e193-11ea-987c-ff53b4654663.png)
> 
> 
> 
> 这里提到「辅助标记一旦生成后就是固定了位置，如果数据发生改变，辅助标记就需要删除掉重新创建。」
> 
> 
> 
> 怎么删除掉重新创建？

清空图形标志里写明了……

**Comment by zhouyu1993** [comment]
我的数据，x轴的值是时间字符串，类似 xValue = '00:00'

start: () => [xValue, yValue]，这是不行的，ts 限制 xValue 为 number 了

刚刚试了下，可以把 xValue 写死为 0

start: () => [0, yValue]

**Comment by zhouyu1993** [comment]
学到了。x轴、y轴数据还是尽量保持数字形式，把字符串形式作为拓展字段。。。

data: [
  {
    x: number, // 假如 x 为时间戳
    xFormat: string, // xFormat 这个是必要的，因为目前 toolTip 的 title 不支持格式化函数
    y: number
  }
]

**Comment by Me-Momo** [comment]
支持回调的，可以再详细看下文档；如果还不清楚怎么写的话，可以提供一个 demo 链接，帮忙给一些指导
