### ISSUE TITLE
饼图在值都为0时应该按个数平均绘制

### ISSUE THREAD

**Issue by lgy1159** [antvis/G2#2756]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/45023840/90607227-86bd8c00-e233-11ea-8c26-10a6e53e51c1.png)

**Comment by lgy1159** [comment]
@simaQ

**Comment by simaQ** [comment]
这个不符合可视化的准确表达，如果业务需要这种方案，建议自行构造数据封装。
