### ISSUE TITLE
 tooltip 的样式修改无效

### ISSUE THREAD

**Issue by Raven2049** [antvis/G2#2757]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g2.gitee.io/zh/examples/gallery/line#line6](https://antv-g2.gitee.io/zh/examples/gallery/line#line6)

### Steps to reproduce
我开发的时候出现了该情况，class 'g2-tooltip-title'可以正常的设置样式，而 class 'g2-tooltip'却不行，最后我直接用官网上的示范代码修改，仍有同样的问题
![6VV8Z4ES5(T9G4X~@M9~PPX](https://user-images.githubusercontent.com/33887949/90617694-947a0e00-e241-11ea-90fc-2eaa924819e6.png)

| Environment | Info |
|---|---|
| g2 | 4.0.14 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
因为 g2-tooltip class 上的默认样式都是直接写到 attribute.style 中的，优先级比较好。所以如下加上 important：

```css
.g2-tooltip {
    color: red!important;
}
```

![image](https://user-images.githubusercontent.com/7856674/91244209-5c615680-e77e-11ea-8bf3-d79b0a22bf38.png)
