### ISSUE TITLE
IE11下兼容问题

### ISSUE THREAD

**Issue by SophinQ** [antvis/G2#2758]
G2 Version: 4.0.9
IE不支持Number.parseFloat，目前发现scale有使用这个。

**Comment by hustcc** [comment]
确实是一个问题，有兴趣来 pr 吗。解法很简单，直接改用 window 上的 parseFloat，或者判断下 Number下是否存在，存在就用，不存在就用全局。

**Comment by hustcc** [comment]
或者自己在业务代码中加 polyfill。
