### ISSUE TITLE
adjust 分组问题

### ISSUE THREAD

**Issue by ZhengJohn** [antvis/g2#276]
![image](https://user-images.githubusercontent.com/25143160/33879156-898b77ce-df68-11e7-882c-ff28510c77f5.png)

能否实现这种图表  有一组数据a  一组数据b  a柱子数据堆叠  b柱子与a柱子重合
使用adjust dodge分组 并堆叠  调成marginRatio为-1时  两组又堆叠了

**Comment by dxq613** [comment]
看看这个 demo 是否符合你的需求：

http://antv.alipay.com/zh-cn/g2/3.x/demo/other/clustered-stacked.html
