### ISSUE TITLE
通过 legend 隐藏图例时，折现上对应的 annotation 没有被隐藏

### ISSUE THREAD

**Issue by wspl** [antvis/G2#2769]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/component/annotation#line5](https://g2.antv.vision/zh/examples/component/annotation#line5)

### Steps to reproduce
通过下面的 legend 图表隐藏图例，图表上的 annotation 还在并且错位了

或者说有没有办法监听 legend 的设置事件，让我清理 annotation 并重绘？

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | - |

**Comment by bunnyxt** [comment]
可以参考[为图表配置交互](https://g2.antv.vision/zh/docs/manual/tutorial/interaction)和[自定义交互](https://g2.antv.vision/zh/docs/manual/developer/registerinteraction)，自定义`legend-filter`交互触发`legend-item:click`时的`action`。

**Comment by Me-Momo** [comment]
监听legend-item click事件，移除annotation
