### ISSUE TITLE
图表padding使用问题

### ISSUE THREAD

**Issue by onlinelemon** [antvis/g2#277]
* **G2 Version**:G2 V3.0
* **Platform**: PC Win Chrome

> chat默认padding会根据数据自适应调整。
当修改padding-right，必须设置padding-left、top、bottom，失去自适应，需要根据数据计算padding值;
**可否增加padding:{left:‘auto’,...}**

**Comment by leungwensen** [comment]
这个已经在迭代计划里了，不过可能要等一段时间

**Comment by dxq613** [comment]
这块的实现有些复杂，特别是在坐标系允许 旋转、缩放，再加上图例的情况更加复杂

**Comment by dxq613** [comment]
3.0.3 已经支持

```js
padding: 'auto'
padding: [10, 'auto', 20, 'auto']
```
