### ISSUE TITLE
分面 每个分面内能再次使用其他图表吗？比如在一个分面内使用双折线图，另一个使用柱状图。

### ISSUE THREAD

**Issue by ufoozhenghao** [antvis/G2#2770]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
这样两个分面可以共用一个tooltip 时间轴一致。 dataset内包含多个需要以同一个时间轴对比的数据

### What does the proposed API look like?
在分面组件中再次调用其他绘图组件

**Comment by hustcc** [comment]
可以，参考这个 [demo](https://g2.antv.vision/zh/examples/facet/facet#matrix)。
