### ISSUE TITLE
弧长链接图的中的某些线，无法触发tooltip，就没办法显示提示信息，线也不变粗

### ISSUE THREAD

**Issue by postblue** [antvis/G2#2775]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/relation/relation#arc](https://g2.antv.vision/zh/examples/relation/relation#arc)

### Steps to reproduce
打开官网小例子，鼠标在每条线上过一下，你会发现有的线条变粗，然后会有提示信息；有的不会变粗，也不会有提示信息。
当改变浏览器大小，触发重新渲染后，再重复上面的操作，你会发现，可能刚才部分有提示信息的变成线不会变粗也没有提示信息了，而刚才没有提示信息的，突然就有提示信息了。

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | chrome 84.0.4147.135 |

**Comment by hustcc** [comment]
所以这个问题是已经不存在了嘛？

**Comment by postblue** [comment]
> 所以这个问题是已经不存在了嘛？

请问与哪个重复了？

**Comment by hustcc** [comment]
本质是鼠标事件的拾取问题，在图形比较多，且有层次的时候，会有一部分被盖住的图形选中不了，这个在散点图中更加容易体现出来，大圆和小圆在一起，大圆在上层，那么小圆就一直选不中。
