### ISSUE TITLE
饼图交互click事件有概率丢失数据

### ISSUE THREAD

**Issue by WhyStart** [antvis/G2#2778]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antvg2-bingtujiaohuclickshijiangailudiushishuju-ccce0)

### Steps to reproduce
随机点击饼图触发click事件，回调参数ev.data.data，概率为undefined丢失数据

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | macos/windows |
| Browser | chrome |
![9B67EC79-19C4-4351-B40B-02319426EFFF](https://user-images.githubusercontent.com/54924160/91536314-20c5b880-e947-11ea-8034-29490dc4e3a6.png)

**Comment by Me-Momo** [comment]
点击到 label 上就丢失数据了 @simaQ @hustcc 需要在 label 上加上事件不

**Comment by simaQ** [comment]
> 点击到 label 上就丢失数据了 @simaQ @hustcc 需要在 label 上加上事件不

label 上有事件的，估计是事件冒泡或者捕获的问题
