### ISSUE TITLE
官网文档缺失

### ISSUE THREAD

**Issue by shadowmoom** [antvis/G2#2779]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
你好， 我在查阅官网API文档的时候，发现官网页面404
 地址如下：https://g2.antv.vision/zh/docs/manual/concepts-overview/tutorial/legend

### What does the proposed API look like?
文档相关

**Comment by bunnyxt** [comment]
G2升级4.0之后很多文档的URL地址变更了，但是链接没有及时更新，你要找的或许是这个 ⬇️
[https://g2.antv.vision/zh/docs/manual/tutorial/legend](https://g2.antv.vision/zh/docs/manual/tutorial/legend)

**Comment by shadowmoom** [comment]
关闭
