### ISSUE TITLE
如何添加图表标题

### ISSUE THREAD

**Issue by onlinelemon** [antvis/g2#278]
* **G2 Version**:G2 V3.0
* **Platform**:PC Win Chrome
* **Mini Showcase(like screenshots)**:
如下图
![](https://raw.githubusercontent.com/onlinelemon/images/master/2.png)

**Comment by onlinelemon** [comment]
这里使用html拼装实现了，想问图表是否考虑支持或者有其他方式。
还有个问题**图表是否有loading状态和事件？**

**Comment by simaQ** [comment]
可以考虑使用 guide
