### ISSUE TITLE
指定ticks数组下的分组顺序不被识别

### ISSUE THREAD

**Issue by yukilzw** [antvis/G2#2780]
* **G2 Version**: 4.0.x
* **Platform**: *
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
![image](https://user-images.githubusercontent.com/21005519/91715977-507ff500-ebc1-11ea-8ed9-667587f1177b.png)

想要根据年份的顺序来展示，但是年份并非连续，如果使用线性ticks会有两个问题：
       1. 是造成分组报错；
       2. 会展示不需要的度量。

所以想到手动指定分组cat与ticks顺序，但是看起来这个顺序并没有生效，图表的度量会根据数据源出现的顺序展示，目前只有先排序数据源。

**Comment by hustcc** [comment]
怎么指定的？使用 G2

Chart.scale(xField, {
  values: [],
})
