### ISSUE TITLE
数据切换后重新render，tooltip为空

### ISSUE THREAD

**Issue by jane-gao** [antvis/G2#2784]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wonderful-http-y94uv?file=/src/App.vue)

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | win10 |
| Browser | Google Chrome(84.0.4147.135) |

### Steps to reproduce
 1. 查看本周周一数据tooltip（保证是切换前最后一次查看）
 2. 切换到本月数据，不查看任何tooltip
 3. 切回本周数据，直接查看周一tooltip（不要从别的数据处划过去），就能看到tooltip为空。
ps: 切换前后查看的数据项一致，tooltip为空必现。查看的数据项不一致则不会出现
![image](https://user-images.githubusercontent.com/42766064/91839513-c2b80e80-ec81-11ea-9563-86a6f8860bf4.png)

---
 - 背景：业务需要查看不同的数据，比如本周，本月，本年等，通过单选方式查看。
 - 期望：此种数据变更有两种方式，一种是使用changeData，另一种是updateOptions后render，两种方式都有点问题，希望能够修复其中一种

**Comment by AegonITargaryen** [comment]
遇到相同的问题。

**Comment by ColinChen2** [comment]
我们也遇到了这个问题。排查下来。是这块代码的问题：
`
...
const distance = getXDistance(geometry.getXScale()); // 每个分类间的平均间距
  if (!rst && Math.abs(xScale.translate(last[FIELD_ORIGIN][xField]) - xValue) <= distance / 2) {
    rst = last;
  }
...
`
getXDistance有缓存，但是根据geometry的scale来设置的
`const getXDistance = memoize((scale: Scale) => {
  if (scale.isCategory) {
    return 1;
  } ...
`
比如以前data里有100个数据，后来update之后就只有10个数据。但是distance却没有变化。
所以tooltip很难命中。

@hustcc 帮忙看一下？

**Comment by ColinChen2** [comment]
已解决。
设置时间类型为type: 'timeCat'。
因为我的时间间隔会变化，因此不能认为是连续性数据，应该属于分类性数据
😆

**Comment by rosie597** [comment]
遇到一样的问题

**Comment by rosie597** [comment]
遇到差不多的问题，数据切换成只有一个数据项的时候 tooltip 内容为空

**Comment by hustcc** [comment]
```ts
       // 2.重新渲染，查看周一tooltip，然后切换到本月数据，不查看tooltip再切回本周数据“直接”查看周一，必现tooltip为空
      // this.chart.updateOptions({ data: this.data });
      this.chart.changeData(this.data);
      // this.chart.render();
```

@jane-gao  不要使用 updateOptions，直接使用 changeData

**Comment by hustcc** [comment]
@jane-gao  @rosie597 @ColinChen2 @AegonITargaryen 我本地使用 4.1.9 版本， 已经复现不出来。

@jane-gao 在你提供的 codesandbox 中使用 4.1.9 版本，也无法复现。
