### ISSUE TITLE
如何给条形图、柱形图以及其他图添加背景色（柱子背景色，非柱子的颜色）

### ISSUE THREAD

**Issue by wangjiahan** [antvis/G2#2786]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
用户使用时，数据对比更明显，效果更好

### What does the proposed API look like?
文档清晰、详细、完整
![image](https://user-images.githubusercontent.com/30687129/91929964-2e49bc80-ed12-11ea-9770-a7a6d3bb53ce.png)

**Comment by warmhug** [comment]
+1， 非常疑惑、这么常见的简单的 demo 官方都没想到吗？

**Comment by hustcc** [comment]
> +1， 非常疑惑、这么常见的简单的 demo 官方都没想到吗？

我们很少见到要给柱图的每一个柱子加一个背景色。不知道是什么样的需求，而且这个需求使用 G2 就是两个柱图层叠，底下的柱子宽一些就可以了。不是最佳时间，没有放到 demo 也是合理的。

我们知道有很多的需求是，在分组柱图中，鼠标 hover 的时候，需要加一个分组的背景，这个我们是有 demo 的。

**Comment by visiky** [comment]
目前支持下面这种形式设置, 文档暂未透出
![image](https://user-images.githubusercontent.com/15646325/105569548-6e6f1180-5d7d-11eb-9bc0-de0b5e8b5492.png)

另外：G2Plot 有更佳易用的例子：https://g2plot.antv.vision/en/docs/api/plots/column#columnbackgroundstyle

**Comment by JayMi1002** [comment]
> 目前支持下面这种形式设置, 文档暂未透出
> ![image](https://user-images.githubusercontent.com/15646325/105569548-6e6f1180-5d7d-11eb-9bc0-de0b5e8b5492.png)
> 
> 另外：G2Plot 有更佳易用的例子：https://g2plot.antv.vision/en/docs/api/plots/column#columnbackgroundstyle

这个支持跟版本有关吗, 我4.0.11 的版本，设置background 无任何效果。

**Comment by liuzhaoxu1996** [comment]
如何修改hover的柱子背景色？

**Comment by Pentium286** [comment]
g2解决了吗？

**Comment by hustcc** [comment]
见：https://github.com/antvis/G2/discussions/5110?converting=1

**Comment by deerLoves** [comment]
> 如何修改hover的柱子背景色？

interactions: [{ type: 'active-region', enable: false }]
