### ISSUE TITLE
图表条数过多时，下面的图例显示不全

### ISSUE THREAD

**Issue by yanruoxinb** [antvis/g2#279]
![1](https://user-images.githubusercontent.com/19534231/33936554-ef1ddece-e03a-11e7-95d1-dab056f0f3fb.png)

图表条数过多时，下面的图例显示不全；

**Comment by simaQ** [comment]
参照这个例子，https://antv.alipay.com/zh-cn/g2/3.x/demo/other/streamgraph.html 使用 html 渲染图例
