### ISSUE TITLE
饼图的标签文字重叠在一起

### ISSUE THREAD

**Issue by dear-lizhihua** [antvis/G2#2804]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g2.gitee.io/zh/examples/gallery/pie#pie2](https://antv-g2.gitee.io/zh/examples/gallery/pie#pie2)

### Steps to reproduce
把最后两条数据的 value 都改成 0.01

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | - |

如图
![image](https://user-images.githubusercontent.com/15142680/92430641-f803b580-f1c7-11ea-96cd-1867eb52fcce.png)

**Comment by dear-lizhihua** [comment]
#2602 有类似的问题

**Comment by hustcc** [comment]
@Me-Momo  应该在 4.1 的 beta 中已经解决，大概在 930 发布正式版本。

**Comment by Vocal2019** [comment]
> @Me-Momo 应该在 4.1 的 beta 中已经解决，大概在 930 发布正式版本。

start 了 能收到版本发布的邮件推送吗
