### ISSUE TITLE
鼠标悬浮时只显示辅助线和交叉点，而不要显示 tooltip；悬浮时的交叉点样式怎么定制

### ISSUE THREAD

**Issue by elewen** [antvis/G2#2806]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
更多的控制配置

### What does the proposed API look like?
能够单独控制鼠标悬浮时辅助线、交叉点、tooltip的可见性及各自的样式

**Comment by hustcc** [comment]
参考散点图 demo： https://g2.antv.vision/zh/examples/point/scatter#scatter-shapes
