### ISSUE TITLE
g2 grid 设置null不生效 还是存在 网格线  折腾了半天

### ISSUE THREAD

**Issue by Arthas-xu** [antvis/G2#2807]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/gallery/bar](https://g2.antv.vision/zh/examples/gallery/bar)

### Steps to reproduce
const floorArr = ['一层', '二层', '三层', '四层', '五层', '六层']
      this.chart = new Chart({
        container: 'floorCharts',
        autoFit: true
      })
      this.chart.data(this.chartsData)
      this.chart.scale({
        floor: {
          formatter: val => {
            return floorArr[Number(val)   1]
          }
        },
        amount: {
          alias: '检测次数',
          formatter: val => {
            return val   '次'
          },
          nice: true
        }
      })
      this.chart.axis('floor', {
        title: null,
        tickLine: null,
        subTickLine: null,
        line: null,
        grid: null
      })
      this.chart.axis('amount', {
        tickLine: null,
        subTickLine: null,
        gird: null,
        line: null
      })
      this.chart.coordinate().transpose()
      this.chart.interval().size(26)
        .position('floor*amount')
        .label('amount', {
          style: {
            fill: '#fff'
          }
        })
      this.chart.interaction('element-active')
      this.chart.render()

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/92596546-8f582e00-f2d8-11ea-8029-32bf488d685a.png)

你拼写错了。
