### ISSUE TITLE
options配置下facet无效

### ISSUE THREAD

**Issue by zhangJunBa** [antvis/G2#2808]
![2020-09-08_181149](https://user-images.githubusercontent.com/70947651/92464094-44b6b300-f1ff-11ea-913a-d8653c820b91.png)

**Comment by simaQ** [comment]
看看类型定义：https://github.com/antvis/G2/blob/master/src/interface.ts#L1463

```ts
facets: [
  {type: 'mirror', ...}
]
```

**Comment by zhangJunBa** [comment]
看文档 弄感觉还是不对，出不来效果，头蒙，望指教一下
![Uploading def4d3e11b3ab789592f6fbd8c4559e.png…]()

**Comment by zhangJunBa** [comment]
![Uploading image.png…]()
