### ISSUE TITLE
G2 TrendLine 实现讨论

### ISSUE THREAD

**Issue by lxfu1** [antvis/G2#2809]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
- feat: 新功能，服务

### What does the proposed API look like?
- https://github.com/antvis/G2/blob/feat%2Ftrendline/src/chart/controller/trend-line.ts

**Comment by hustcc** [comment]
我的想法是做到 annotation 中，作为其中一种类型，另外额外加一个 symbol 类型的 annotation ，用于自定义 path 画标记。

**Comment by Me-Momo** [comment]
1、G2 的 controller 不是这么使用的，尽量不要新增 controller 的类型，可以做扩展做其他；
2、如果可以使用 annotation 的话，可以减少生命周期的维护，感觉也较好

**Comment by simaQ** [comment]
是用于实现散点图的趋势线吗？

这个在我原本的计划里面，是通过：统计语法 + Geometry来实现的。TrendLine 你可以把他当做一个 Geometry（由经过统计后的数据经过图形映射后绘制的），这个目前是我想到最好的方式，映射、创建、更新目前的框架层基本可以吃掉。

另外关于目前讨论的方案：
1. Controller 是用于图表组件的，TrendLine 是一种辅助图形，并不是图表组件
2. 如果作为 Annotation 的话，有一个问题，那就是数据变化后，或者图表更新时，这个 path 要如何更新？这个 path 是跟着数据走的，是让用户做，还是框架层解决？

**Comment by simaQ** [comment]
@lxfu1 建议新功能可以先将想法或者设计抛出，一起讨论后再编码

**Comment by lxfu1** [comment]
> 是用于实现散点图的趋势线吗？
> 
> 这个在我原本的计划里面，是通过：统计语法 + Geometry来实现的。TrendLine 你可以把他当做一个 Geometry（由经过统计后的数据经过图形映射后绘制的），这个目前是我想到最好的方式，映射、创建、更新目前的框架层基本可以吃掉。
> 
> 另外关于目前讨论的方案：
> 
> 1. Controller 是用于图表组件的，TrendLine 是一种辅助图形，并不是图表组件
> 2. 如果作为 Annotation 的话，有一个问题，那就是数据变化后，或者图表更新时，这个 path 要如何更新？这个 path 是跟着数据走的，是让用户做，还是框架层解决？

是的， 散点图的趋势线。

**Comment by Me-Momo** [comment]
> 是用于实现散点图的趋势线吗？
> 
> 这个在我原本的计划里面，是通过：统计语法 + Geometry来实现的。TrendLine 你可以把他当做一个 Geometry（由经过统计后的数据经过图形映射后绘制的），这个目前是我想到最好的方式，映射、创建、更新目前的框架层基本可以吃掉。
> 
> 另外关于目前讨论的方案：
> 
> 1. Controller 是用于图表组件的，TrendLine 是一种辅助图形，并不是图表组件
> 2. 如果作为 Annotation 的话，有一个问题，那就是数据变化后，或者图表更新时，这个 path 要如何更新？这个 path 是跟着数据走的，是让用户做，还是框架层解决？

饼图的指标卡中心文本也是跟着数据变化的，也是通过 anntation 绘制

**Comment by simaQ** [comment]
> > 是用于实现散点图的趋势线吗？
> > 这个在我原本的计划里面，是通过：统计语法 + Geometry来实现的。TrendLine 你可以把他当做一个 Geometry（由经过统计后的数据经过图形映射后绘制的），这个目前是我想到最好的方式，映射、创建、更新目前的框架层基本可以吃掉。
> > 另外关于目前讨论的方案：
> > 
> > 1. Controller 是用于图表组件的，TrendLine 是一种辅助图形，并不是图表组件
> > 2. 如果作为 Annotation 的话，有一个问题，那就是数据变化后，或者图表更新时，这个 path 要如何更新？这个 path 是跟着数据走的，是让用户做，还是框架层解决？
> 
> 饼图的指标卡中心文本也是跟着数据变化的，也是通过 anntation 绘制

恩，我们的更新机制本身就支持 Annotation 的更新，理论上是支持的，不过这块是要注意下的。

**Comment by hustcc** [comment]
> 是用于实现散点图的趋势线吗？
> 
> 这个在我原本的计划里面，是通过：统计语法 + Geometry来实现的。TrendLine 你可以把他当做一个 Geometry（由经过统计后的数据经过图形映射后绘制的），这个目前是我想到最好的方式，映射、创建、更新目前的框架层基本可以吃掉。
> 
> 另外关于目前讨论的方案：
> 
> 1. Controller 是用于图表组件的，TrendLine 是一种辅助图形，并不是图表组件
> 2. 如果作为 Annotation 的话，有一个问题，那就是数据变化后，或者图表更新时，这个 path 要如何更新？这个 path 是跟着数据走的，是让用户做，还是框架层解决？

---

对于第二点关于实现，就和环图的中心文本一样，通过回调的方式，动态计算 path。相比通过 geometry 来实现，geometry 的坏处在于，趋势线的信息来自于原 geometry，相当于两个 geometry 有先后的依赖关系里面，容易出现生命周期扯不清楚的问题。

而 annotation 中也有 line 类型，趋势图和 line 的本质其实是一样的，都是辅助看数据的，而且 line 的 median 等定位方式也是包含有简单的数据统计逻辑的。相比 geometry 实现，annotation 理论上逻辑会简单很多，是否可以做到对外 API 是统计语法，内部使用使用 annotation？

> 还有另外一个重要的点，在真是的 bi 中，散点数据起始只是查询的部分数据，而真实绘制的拟合线，需要使用后端通过全量数据拟合出来的公式，所以这个 path 的计算，不会仅仅使用前端数据去做统计计算。

**Comment by Me-Momo** [comment]
如，如果要弄一个新的辅助图形，考虑后续辅助图形可以用同样的方式来绘制～ 统一机制

**Comment by simaQ** [comment]
> > 是用于实现散点图的趋势线吗？
> > 这个在我原本的计划里面，是通过：统计语法 + Geometry来实现的。TrendLine 你可以把他当做一个 Geometry（由经过统计后的数据经过图形映射后绘制的），这个目前是我想到最好的方式，映射、创建、更新目前的框架层基本可以吃掉。
> > 另外关于目前讨论的方案：
> > 
> > 1. Controller 是用于图表组件的，TrendLine 是一种辅助图形，并不是图表组件
> > 2. 如果作为 Annotation 的话，有一个问题，那就是数据变化后，或者图表更新时，这个 path 要如何更新？这个 path 是跟着数据走的，是让用户做，还是框架层解决？
> 
> 是的， 散点图的趋势线。

目前还有一个方案，就是通过多 View 的方式，Geometry 的方式的话必须要相同数据源。

**Comment by Me-Momo** [comment]
不同数据源的话，是不是多view就行了？

**Comment by simaQ** [comment]
> 不同数据源的话，是不是多view就行了？ 不过 view 的布局位置要看下？

这个场景下，布局不成问题吧，刚好验证下。

**Comment by simaQ** [comment]
> > 是用于实现散点图的趋势线吗？
> > 这个在我原本的计划里面，是通过：统计语法 + Geometry来实现的。TrendLine 你可以把他当做一个 Geometry（由经过统计后的数据经过图形映射后绘制的），这个目前是我想到最好的方式，映射、创建、更新目前的框架层基本可以吃掉。
> > 另外关于目前讨论的方案：
> > 
> > 1. Controller 是用于图表组件的，TrendLine 是一种辅助图形，并不是图表组件
> > 2. 如果作为 Annotation 的话，有一个问题，那就是数据变化后，或者图表更新时，这个 path 要如何更新？这个 path 是跟着数据走的，是让用户做，还是框架层解决？
> 
> 对于第二点关于实现，就和环图的中心文本一样，通过回调的方式，动态计算 path。相比通过 geometry 来实现，geometry 的坏处在于，趋势线的信息来自于原 geometry，相当于两个 geometry 有先后的依赖关系里面，容易出现生命周期扯不清楚的问题。
> 
> 而 annotation 中也有 line 类型，趋势图和 line 的本质其实是一样的，都是辅助看数据的，而且 line 的 median 等定位方式也是包含有简单的数据统计逻辑的。相比 geometry 实现，annotation 理论上逻辑会简单很多，是否可以做到对外 API 是统计语法，内部使用使用 annotation？
> 
> > 还有另外一个重要的点，在真是的 bi 中，散点数据起始只是查询的部分数据，而真实绘制的拟合线，需要使用后端通过全量数据拟合出来的公式，所以这个 path 的计算，不会仅仅使用前端数据去做统计计算。

恩，BI 怎么样不代表用户就这么用~ 这些是个人建议以及根据经验的一些鼓励，酌情参考即可。

**Comment by hustcc** [comment]
BI 怎么样不代表用户就这么用是对的，但是需要开放有地方可以做这种自定义计算。

**Comment by lxfu1** [comment]
Annotation  是在 layout 里面进行初始化的， 然而 trend-line 依赖于 Scale 绘制完成， 需要放到 afterpaint 后面。

**Comment by Me-Momo** [comment]
annotation 之前，scale 已经ok了

**Comment by hustcc** [comment]
结论是啥？[鞠躬]

**Comment by Me-Momo** [comment]
可以给一个想要实现的效果嘛？或者描述最后想要达到的内容？

**Comment by lxfu1** [comment]
期望效果： https://github.com/HarryStevens/d3-regression

**Comment by lxfu1** [comment]
Annotation OR  统计语法 + Geometry ，如果效果相同的话建议成本最低原则， 结论是啥？

**Comment by hustcc** [comment]
现在有两种方式实现 趋势线：

1. 使用 统计语法 + geometry 的方式
2. 使用 annotation，自定义 shape 的 annotation，然后基于自定义 shape + d3-reg 去做趋势线的 shape

> 如果决定 1 作为长久的最终方案，那么对于 1 @simaQ 评估一下时间 ，如果时间比较久，建议先实现 2 中自定义 shape 的 annotation，然后在 g2plot 层引入 d3-reg 去计算数据生成 shape。

**Comment by simaQ** [comment]
> 现在有两种方式实现 趋势线：
> 
> 1. 使用 统计语法 + geometry 的方式
> 2. 使用 annotation，自定义 shape 的 annotation，然后基于自定义 shape + d3-reg 去做趋势线的 shape
> 
> > 如果决定 1 作为长久的最终方案，那么对于 1 @simaQ 评估一下时间 ，如果时间比较久，建议先实现 2 中自定义 shape 的 annotation，然后在 g2plot 层引入 d3-reg 去计算数据生成 shape。

那就使用 2 吧
