### ISSUE TITLE
Add ability to sort legend items

### ISSUE THREAD

**Issue by lxfu1** [antvis/G2#2810]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-charts/issues/188](https://github.com/ant-design/ant-design-charts/issues/188)

### Steps to reproduce
新需求。

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
同需要这个能力，你自己来个 pr 不？^_^

**Comment by lxfu1** [comment]
等我来 PR  :^_^:

**Comment by hustcc** [comment]
```ts
chart.legend({
  reversed: true,
})
```
