### ISSUE TITLE
[文档优化] API 文档生成时有很多多余的 br

### ISSUE THREAD

**Issue by afc163** [antvis/G2#2812]
显得文档非常不紧凑，这些 br 应该去掉。

https://g2.antv.vision/zh/docs/api/element

<img width="370" alt="image" src="https://user-images.githubusercontent.com/507615/92580474-fcf86000-f2c0-11ea-8a6d-6fad67744a3a.png">

<img width="269" alt="image" src="https://user-images.githubusercontent.com/507615/92580547-139eb700-f2c1-11ea-855d-351b79707187.png">

**Comment by BBSQQ** [comment]
内容已全面改版
