### ISSUE TITLE
G2初始化时支持传入 canvas 对象的 context 上下文

### ISSUE THREAD

**Issue by chuyun** [antvis/G2#2817]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
对于 node 及 deno 等调用时，由于不能提供 DOM 节点，所以无法直接使用G2 进行图表渲染，希望G2 可以支持直接传入canvas 的上下文对象, 或者提供一下直接传递context的方法，谢谢

参考 antv-F2: https://f2.antv.vision/zh/docs/tutorial/manual/node-env

### What does the proposed API look like?
```javascript
const chart = new G2.Chart({
    el: canvas, // canvas ctx
    width: 920,
    height: 880
  })
```

**Comment by hustcc** [comment]
@chuyun 你的场景是在 node 环境，传入 node canvas context 然后在 node 环境生成可视化图表的图片吗？

因为除了这里会用到 dom 之外，还有 tooltip、annotation 等也会用到 dom，所以可能即时这么做了之后，在 node 环境生成的图也是不是完整的，tooltip annotation 丢失。

**Comment by chuyun** [comment]
> @chuyun 你的场景是在 node 环境，传入 node canvas context 然后在 node 环境生成可视化图表的图片吗？
> 
> 因为除了这里会用到 dom 之外，还有 tooltip、annotation 等也会用到 dom，所以可能即时这么做了之后，在 node 环境生成的图也是不是完整的，tooltip annotation 丢失。

@hustcc   谢谢。我的场景是在 deno 环境下，和 node 环境差不多，期望在 deno 环境下生成可视化图表。我之前也看到在G2中有使用 dom 的情况，我们目前并不打算在库中增加完整的 dom 实现，所以暂时不会考虑使用 G2 去做可视化图表生成了。
