### ISSUE TITLE
是否支持首次渲染图表时默认只显示部分图例

### ISSUE THREAD

**Issue by yukilzw** [antvis/G2#2819]
* **G2 Version**:4.0.x
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
![image](https://user-images.githubusercontent.com/21005519/92730357-39ea5280-f3a6-11ea-9188-d326c7274f27.png)

目前是否支持生成图表的时候默认选中部分图例，或者说在图表外部调用chart实例下的方法来现实隐藏不同图例的曲线？
因为多条曲线在同一张图上的差值过大会造成数据的变化不明显。

**Comment by Me-Momo** [comment]
通过chart filterData 来设置

**Comment by belerweb** [comment]
没有文档啊？

**Comment by 583849487** [comment]
貌似目前@5.2版本的filterData已不支持了
