### ISSUE TITLE
给annotation的region绑定点击事件，获取的event对象中的start和end与传入的start和end不同。

### ISSUE THREAD

**Issue by Echo-pain-killer** [antvis/G2#2820]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/staging-breeze-vyztc?file=/src/index.js)

### Steps to reproduce
使用annotation().region()绘制区域，给区域绑定点击事件，在得到的event对象中获取开始和结束时间，发现和传入的不一致

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | window10 |
| Browser | chorme版本 80.0.3987.132（正式版本） （64 位） |

---
期望获取的时间和传入的时间能一致

**Comment by xuhen** [comment]
how do you use region?

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/106255862-86e79c00-6255-11eb-8283-75b45c35cdc5.png)


seem right?
