### ISSUE TITLE
网格插件无法正确显示

### ISSUE THREAD

**Issue by wsb260** [antvis/G2#2821]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/antvis/G6/blob/b8480940ac285c06bd5c6abecc6333a322051f56/src/plugins/grid/index.ts#L33](https://github.com/antvis/G6/blob/b8480940ac285c06bd5c6abecc6333a322051f56/src/plugins/grid/index.ts#L33)

### Steps to reproduce
1. const grid = new G6.Grid();实例化Grid插件
2. plugins: [grid] 在实例中添加插件
3. Grid插件无法显示，在官方提供的使用例子里依然如此，在源码中看到Grid的层级为index:-1,导致被遮挡，如果手动调整到上层，会导致画布被遮盖

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | window |
| Browser | Google |

---
Grid插件的层级导致无法正常显示

**Comment by hustcc** [comment]
G6 issue 到 G6 的项目中提吧~~~
