### ISSUE TITLE
遇到的图表渲染的一个问题，我根据输入的时间段不同从后端获取不同的数据

### ISSUE THREAD

**Issue by Roxannej** [antvis/G2#2827]
遇到的图表渲染的一个问题，我根据输入的时间段不同从后端获取不同的数据，但是当我第二次点击时间选择器，选择时间，获取新的数据，绘制出的图竟然是重叠在第一次点击时间后出现的图表的上面，第三次也是这样，我也清空了数据，根据后端传来的数据也没有问题，我不知道怎么解决这个问题

**Comment by hustcc** [comment]
你具体的代码是什么样的？

**Comment by Roxannej** [comment]
// 图表
getKeepType(data) {
      this.mTypeData = []
      upkeepType(data).then((res) => {
        const { status, obj } = res.data
        if (status === 200) {
          this.mTypeData = obj
          MyCharts.ChartOptionTemplates.BarEasy('maintain-type', this.mTypeData)
        }
      })
    },
// 调用
 onChangeTwo(date, dateString) {
      dateString.map((item, index, arr) => {
        if (index === 0) {
          this.startTwo = item
        } else {
          this.endTwo = item
        }
      })
      const data = [this.startTwo, this.endTwo]
      this.getKeepType(data)
      this.getKeepState(data)
      this.getKeepExecutor(data)
    },

**Comment by Roxannej** [comment]
> 你具体的代码是什么样的？
// 图表
getKeepType(data) {
this.mTypeData = []
upkeepType(data).then((res) => {
const { status, obj } = res.data
if (status === 200) {
this.mTypeData = obj
MyCharts.ChartOptionTemplates.BarEasy('maintain-type', this.mTypeData)
}
})
},
// 调用
onChangeTwo(date, dateString) {
dateString.map((item, index, arr) => {
if (index === 0) {
this.startTwo = item
} else {
this.endTwo = item
}
})
const data = [this.startTwo, this.endTwo]
this.getKeepType(data)
this.getKeepState(data)
this.getKeepExecutor(data)
},

**Comment by hustcc** [comment]
这代码看不懂。

**Comment by Roxannej** [comment]
> 这代码看不懂。

// 时间选择器
    onChange(date, dateString) {
      dateString.map((item, index, arr) => {
        if (index === 0) {
          this.start = item
        } else {
          this.end = item
        }
      })
      const data = [this.start, this.end]
      this.getType(data)
    },
// 图表
 getType(data) {
      this.typeData = []
      // 类型
      orderType(data).then((res) => {
        const { obj, status } = res.data
        console.log('数据', obj)
        if (status === 200) {
          this.typeData = obj
            var chart = new Chart({
              container: 'type',
              autoFit: true,
              height: 280,
              padding: [30, 20, 60, 60]
            })
          chart.data(this.typeData)
          chart.interval().position('type*amount')
          chart.render()
        }
      })
    },

**Comment by Roxannej** [comment]
> 这代码看不懂。
我又重新发了另一段代码，不知道你能不能看明白

**Comment by hustcc** [comment]
可能是米生成了多个chart，每次更新销毁之前的chart。
