### ISSUE TITLE
请问用guide().line()绘制辅助线只能是虚线吗？

### ISSUE THREAD

**Issue by zhengshuai1001** [antvis/g2#283]
画一个汽车仪表盘。最后绘制指针时，需求是白色直线，我在极坐标上使用guide().line()，画的是虚线？文档上没找到改成实线的方法，请问有解决办法吗？谢谢

![snipaste_20171214_094413](https://user-images.githubusercontent.com/9513530/33971563-f3258e1c-e0b3-11e7-8f66-e599fb948fbf.jpg)

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_chart.guide-.line-cfg-

配置 `lineStyle`，把 `lineDash` 配置为 null 即可

```js
    lineStyle: {
      lineDash: null,
    }
```

**Comment by zhengshuai1001** [comment]
@leungwensen 非常感谢
