### ISSUE TITLE
chart.scale "sync" is not working

### ISSUE THREAD

**Issue by InbarTakdim** [antvis/G2#2830]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/typescript-fmgcbm?file=index.ts](https://stackblitz.com/edit/typescript-fmgcbm?file=index.ts)

### Steps to reproduce
please look on the stackblitz 

| Environment | Info |
|---|---|
| g2 | 3.5.17 |
| System | mac |
| Browser | chrome |

---
I want that the "siteLimit" and "field2" will be on the same axis, therefore I used the sync, but in the results it open new axis in the right side for the "line" I added

**Comment by hustcc** [comment]
> chart.axis('field2', false);

**Comment by InbarTakdim** [comment]
ok now it doesn't show the ais but it put the line of "300" in "200" of the "field2" axis

**Comment by hustcc** [comment]
> ok now it doesn't show the ais but it put the line of "300" in "200" of the "field2" axis.
> "field2" and "siteLimit" needs to share the same axis with the same ticks

your live demo can not work.

**Comment by InbarTakdim** [comment]
ngAfterViewInit() {
		const data = [
			{name: 'London', field1: 'Jan.', field2: 18.9, siteLimit: 300, utilityLimit: 10, batteryLimit: 30},
			{name: 'London', field1: 'Feb.', field2: 28.8, siteLimit: 300, utilityLimit: 30, batteryLimit: 70},
			{name: 'London', field1: 'Mar.', field2: 39.3, siteLimit: 300, utilityLimit: 80, batteryLimit: 70},
			{name: 'London', field1: 'Apr.', field2: 81.4, siteLimit: 300, utilityLimit: 60, batteryLimit: 40},
			{name: 'London', field1: 'May', field2: 47, siteLimit: 300, utilityLimit: 60, batteryLimit: 30},
			{name: 'London', field1: 'Jun.', field2: 20.3, siteLimit: 300, utilityLimit: 60, batteryLimit: 40},
			{name: 'London', field1: 'Jul.', field2: 24, siteLimit: 300, utilityLimit: 70, batteryLimit: 30},
			{name: 'London', field1: 'Aug.', field2: 35.6, siteLimit: 300, utilityLimit: 70, batteryLimit: 40},
			{name: 'Berlin', field1: 'Jan.', field2: 12.4, siteLimit: 300, utilityLimit: 10, batteryLimit: 30},
			{name: 'Berlin', field1: 'Feb.', field2: 23.2, siteLimit: 300, utilityLimit: 30, batteryLimit: 70},
			{name: 'Berlin', field1: 'Mar.', field2: 34.5, siteLimit: 300, utilityLimit: 80, batteryLimit: 70},
			{name: 'Berlin', field1: 'Apr.', field2: 99.7, siteLimit: 300, utilityLimit: 60, batteryLimit: 40},
			{name: 'Berlin', field1: 'May', field2: 52.6, siteLimit: 300, utilityLimit: 60, batteryLimit: 30},
			{name: 'Berlin', field1: 'Jun.', field2: 35.5, siteLimit: 300, utilityLimit: 60, batteryLimit: 40},
			{name: 'Berlin', field1: 'Jul.', field2: 37.4, siteLimit: 300, utilityLimit: 70, batteryLimit: 30},
			{name: 'Berlin', field1: 'Aug.', field2: 42.4, siteLimit: 300, utilityLimit: 70, batteryLimit: 40},
		];

		let chart = new G2.Chart({
			container: 'container',
			autoFit: true,
			forceFit: true,
			autoAdjust: false,
			padding: [50, 60, 80, 50]
		});

		chart.source(data);
		chart.axis('siteLimit', false);
		chart.tooltip({
			shared: true,
			showMarkers: false,
		});


		chart
			.interval()
			.position('field1*field2')
			.color('name')
			.adjust('stack')


		chart
			.line()
			.position('field1*siteLimit')
			.shape('hv').color('#cccccc')

		chart.render();

	}

**Comment by InbarTakdim** [comment]
<img width="877" alt="Screen Shot 2020-09-15 at 16 02 30" src="https://user-images.githubusercontent.com/15275755/93213694-e0e73980-f76c-11ea-88eb-4c1183ffea4b.png">
 the green line should be in 300

**Comment by InbarTakdim** [comment]
@hustcc  I really appreciate your quick response, it's a bug in production

**Comment by hustcc** [comment]
@InbarTakdim  you G2 version is 3.5.x?

**Comment by hustcc** [comment]
You may want to draw the plot like below:
```ts
import { Chart } from '@antv/g2@3.5';

const data = [
  {name: 'London', field1: 'Jan.', field2: 18.9, siteLimit: 300, utilityLimit: 10, batteryLimit: 30},
  {name: 'London', field1: 'Feb.', field2: 28.8, siteLimit: 300, utilityLimit: 30, batteryLimit: 70},
  {name: 'London', field1: 'Mar.', field2: 39.3, siteLimit: 300, utilityLimit: 80, batteryLimit: 70},
  {name: 'London', field1: 'Apr.', field2: 81.4, siteLimit: 300, utilityLimit: 60, batteryLimit: 40},
  {name: 'London', field1: 'May', field2: 47, siteLimit: 300, utilityLimit: 60, batteryLimit: 30},
  {name: 'London', field1: 'Jun.', field2: 20.3, siteLimit: 300, utilityLimit: 60, batteryLimit: 40},
  {name: 'London', field1: 'Jul.', field2: 24, siteLimit: 300, utilityLimit: 70, batteryLimit: 30},
  {name: 'London', field1: 'Aug.', field2: 35.6, siteLimit: 300, utilityLimit: 70, batteryLimit: 40},
  {name: 'Berlin', field1: 'Jan.', field2: 12.4, siteLimit: 300, utilityLimit: 10, batteryLimit: 30},
  {name: 'Berlin', field1: 'Feb.', field2: 23.2, siteLimit: 300, utilityLimit: 30, batteryLimit: 70},
  {name: 'Berlin', field1: 'Mar.', field2: 34.5, siteLimit: 300, utilityLimit: 80, batteryLimit: 70},
  {name: 'Berlin', field1: 'Apr.', field2: 99.7, siteLimit: 300, utilityLimit: 60, batteryLimit: 40},
  {name: 'Berlin', field1: 'May', field2: 52.6, siteLimit: 300, utilityLimit: 60, batteryLimit: 30},
  {name: 'Berlin', field1: 'Jun.', field2: 35.5, siteLimit: 300, utilityLimit: 60, batteryLimit: 40},
  {name: 'Berlin', field1: 'Jul.', field2: 37.4, siteLimit: 300, utilityLimit: 70, batteryLimit: 30},
  {name: 'Berlin', field1: 'Aug.', field2: 42.4, siteLimit: 300, utilityLimit: 70, batteryLimit: 40},
];

let chart = new Chart({
  container: 'mountNode',
  autoFit: true,
  forceFit: true,
  width: 500,
  height: 400,
});

chart.source(data, {
  field2: {
    sync: true,
    max: 320, // should > 300
  },
});
chart.tooltip({
  shared: true,
  showMarkers: false,
});


chart
  .interval()
  .position('field1*field2')
  .color('name')
  .adjust('stack')


chart
  .guide()
  .line({
  start: ['min', 300],
  end: ['max', 300],
  text: {
    position: 'start',
    style: {
      fill: '#8c8c8c',
      fontSize: 12,
      fontWeight: 300
    },
    content: 'limit size',
    offsetY: -5
  }
});


chart.render();
```

**Comment by InbarTakdim** [comment]
it's not always constant line it needs to be dynamic like here:
<img width="659" alt="Screen Shot 2020-09-16 at 9 56 08" src="https://user-images.githubusercontent.com/15275755/93302563-decfba00-f802-11ea-9fa6-6eaf8068cf45.png">

**Comment by InbarTakdim** [comment]
> @InbarTakdim you G2 version is 3.5.x?

3.5.17

**Comment by hustcc** [comment]
g3.5.x only support sync same field name in different view. in g2 4.x, we support all kind of scale sync.

> demo in G2 4.x below

![image](https://user-images.githubusercontent.com/7856674/93304394-89f66880-f82f-11ea-9c83-e4c03f2880ce.png)

**Comment by InbarTakdim** [comment]
I tried to upgrade to 4.0.15 and got the error:
92% additional asset processing scripts-webpack-plugin✖ ｢wdm｣: Error: ENOENT: no such file or directory, open '/Users/web/src/main/web/node_modules/@antv/g2/build/g2.js'

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/93329046-309e3180-f84f-11ea-8e15-cc6e626c6d89.png)

there is no entry at `build/g2.js`

**Comment by InbarTakdim** [comment]
in which file?

**Comment by hustcc** [comment]
I don't have any valid information.

**Comment by InbarTakdim** [comment]
I have this in angular.json:
		"scripts": [
							"node_modules/@antv/g2/build/g2.js",
							"node_modules/@antv/data-set/dist/data-set.min.js",
							"node_modules/@antv/g2-plugin-slider/dist/g2-plugin-slider.min.js"]

**Comment by hustcc** [comment]
"node_modules/@antv/g2/dist/g2.min.js",

**Comment by InbarTakdim** [comment]
ERROR in node_modules/@antv/component/lib/abstract/group-component.d.ts:110:142 - error TS2304: Cannot find name 'Omit'.

110     protected addComponent<C extends GroupComponentCfg = GroupComponentCfg, CT extends GroupComponent = GroupComponent>(parent: IGroup, cfg: Omit<C, 'container'> &

**Comment by hustcc** [comment]
> ERROR in node_modules/@antv/component/lib/abstract/group-component.d.ts:110:142 - error TS2304: Cannot find name 'Omit'.
> 
> 110 protected addComponent(parent: IGroup, cfg: Omit<C, 'container'> &

这是你的工程问题了，自己解决吧，这个问题应该是你的 typescript 版本太低了。
