### ISSUE TITLE
pie-spider 这几把毛怎么用啊，我尼玛直接复制下来都没有示例的蜘蛛脚，搞鸡毛呢，咋几把就那么烂呢？咋几把用啊，环形图的那个demo都挂了，改改啊，快点更新啊！

### ISSUE THREAD

**Issue by yeahliv** [antvis/G2#2836]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/pie/basic#pie-spider-label](https://g2.antv.vision/zh/examples/pie/basic#pie-spider-label)

### Steps to reproduce
https://g2.antv.vision/zh/examples/pie/basic#pie-spider-label

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
口吐芬芳的人不配用 G2！

**Comment by Me-Momo** [comment]
老哥老姐，就你这说话的态度，自己行自己上
