### ISSUE TITLE
chart stacked后多图的bug，很新鲜的！

### ISSUE THREAD

**Issue by arcsin1** [antvis/G2#2837]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/eager-feynman-f6ufd?file=/index.html)

### Steps to reproduce
第2个geometry图形颜色对不上

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | mac |
| Browser | 谷歌84 |

**Comment by arcsin1** [comment]
@lxfu1  很新鲜 😸

**Comment by hustcc** [comment]
是指第二个 geometry 的 color 颜色顺序是反的是吗？

![image](https://user-images.githubusercontent.com/7856674/93546773-220e6200-f996-11ea-9a83-0040b8878eac.png)

**Comment by Me-Momo** [comment]
这主要是坐标系转置倒置的；不太记得之前有一个装置的规则了

**Comment by arcsin1** [comment]
> 是指第二个 geometry 的 color 颜色顺序是反的是吗？
> 
> ![image](https://user-images.githubusercontent.com/7856674/93546773-220e6200-f996-11ea-9a83-0040b8878eac.png)

是的
