### ISSUE TITLE
请教一个问题，我按照官方实例直接复制代码到本地去运行，为什么还是得不到蜘蛛图，那个line很短很短，请问如何解决？

### ISSUE THREAD

**Issue by Vocal2019** [antvis/G2#2839]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/pie/basic#pie-spider-label](https://g2.antv.vision/zh/examples/pie/basic#pie-spider-label)

### Steps to reproduce
https://g2.antv.vision/zh/examples/pie/basic#pie-spider-label

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | Windows10 |
| Browser | Chrome最新 |

**Comment by hustcc** [comment]
@Vocal2019 这个 demo 中的数据原因，都在左侧导致看不出蜘蛛形状。改成下面数据试试看：

```ts
const data = [
  { type: '微博', value: 1.33 },
  { type: '其他', value: 1.67 },
  { type: '论坛', value: 1.77 },
  { type: '网站', value: 1.44 },
  { type: '微信', value: 1.12 },
  { type: '客户端', value: 1.05 },
  { type: '新闻', value: 0.81 },
  { type: '视频', value: 0.39 },
  { type: '博客', value: 0.37 },
  { type: '报刊', value: 0.17 },
];
```

**Comment by Me-Momo** [comment]
![image](https://user-images.githubusercontent.com/15646325/93445044-6a307480-f903-11ea-97f7-515e3f5a2dc5.png)
这个不是吗

**Comment by Vocal2019** [comment]
> @Vocal2019 这个 demo 中的数据原因，都在左侧导致看不出蜘蛛形状。改成下面数据试试看：
> 
> ```ts
> const data = [
>   { type: '微博', value: 1.33 },
>   { type: '其他', value: 1.67 },
>   { type: '论坛', value: 1.77 },
>   { type: '网站', value: 1.44 },
>   { type: '微信', value: 1.12 },
>   { type: '客户端', value: 1.05 },
>   { type: '新闻', value: 0.81 },
>   { type: '视频', value: 0.39 },
>   { type: '博客', value: 0.37 },
>   { type: '报刊', value: 0.17 },
> ];
> ```



> ![image](https://user-images.githubusercontent.com/15646325/93445044-6a307480-f903-11ea-97f7-515e3f5a2dc5.png)
> 这个不是吗

不行啊！
![微信截图_20200917163932](https://user-images.githubusercontent.com/52631716/93447196-b92ad980-f904-11ea-9c5e-b0fc332053f2.png)
```javascript
// 控制图形间隔
      const sliceNumber = 0.01
      registerShape('interval', 'slice-shape', {
        draw(cfg, container) {
          const points = cfg.points
          let path = []
          path.push(['M', points[0].x, points[0].y])
          path.push(['L', points[1].x, points[1].y - sliceNumber])
          path.push(['L', points[2].x, points[2].y - sliceNumber])
          path.push(['L', points[3].x, points[3].y])
          path.push('Z')
          path = this.parsePath(path)
          return container.addShape('path', {
            attrs: {
              fill: cfg.color,
              path,
            },
          })
        },
      })
      // new Chart 对象
      const chart = new Chart({
        container: 'gross-pie-canvas',
        autoFit: true,
        height: 400,
      })
      // 装载数据
      chart.data(data)
      // 设置圆环
      chart.coordinate('theta', {
        radius: 0.75,
        innerRadius: 0.5,
      })
      // 设置标题
      chart.tooltip({
        showTitle: false,
        showMarkers: false,
      })
      chart
        .interval()
        .position('sum')
        .color('alias_en')
        .label('alias_en*sum', {
          layout: { type: 'pie-spider' },
          offset: 20,
          style: {
            fontSize: 16,
            fontWeight: 'bold'
          },
          labelHeight: 270,
          content: (obj) => {
            let money = commafy(toNumber(obj.sum), { digits: 0 })
            let text = ''
            if (obj.sum !== 0) {
              text = `${obj.alias_en}:` + ' ' + `￥${money}`
            }
            return text
          },
          labelLine: {
            style: {
              lineWidth: 0.5
            },
          },
        })
        .adjust('stack')
        .shape('slice-shape')
        .tooltip('alias_en*sum', (alias_en, sum) => {
          return {
            name: alias_en,
            value: '￥' + commafy(toNumber(sum), { digits: 0 }),
          }
        })

      chart.interaction('element-active')

      chart.render()

      this.canvas = chart
```

**Comment by Vocal2019** [comment]
> @Vocal2019 这个 demo 中的数据原因，都在左侧导致看不出蜘蛛形状。改成下面数据试试看：
> 
> ```ts
> const data = [
>   { type: '微博', value: 1.33 },
>   { type: '其他', value: 1.67 },
>   { type: '论坛', value: 1.77 },
>   { type: '网站', value: 1.44 },
>   { type: '微信', value: 1.12 },
>   { type: '客户端', value: 1.05 },
>   { type: '新闻', value: 0.81 },
>   { type: '视频', value: 0.39 },
>   { type: '博客', value: 0.37 },
>   { type: '报刊', value: 0.17 },
> ];
> ```


import { Chart, registerShape } from '@antv/g2'
我只引用了这两个，还有其他的要引用吗？

**Comment by Vocal2019** [comment]
> ![image](https://user-images.githubusercontent.com/15646325/93445044-6a307480-f903-11ea-97f7-515e3f5a2dc5.png)
> 这个不是吗

![微信截图_20200917164651](https://user-images.githubusercontent.com/52631716/93447816-6d2c6480-f905-11ea-8d8d-356e81bac1ed.png)
到我这里就变成这样了

**Comment by Me-Momo** [comment]
版本是？

**Comment by Vocal2019** [comment]
> 版本是？

@4.0.15

**Comment by Me-Momo** [comment]
> > 版本是？
> 
> @4.0.15

升级到 4.1.0-beta.1 看下

**Comment by Vocal2019** [comment]
> > > 版本是？
> > 
> > 
> > @4.0.15
> 
> 升级到 4.1.0-beta.1 看下

![微信截图_20200917170400](https://user-images.githubusercontent.com/52631716/93449864-d8773600-f907-11ea-8046-8a8723322643.png)
变成这样了

**Comment by Vocal2019** [comment]
> > > 版本是？
> > 
> > 
> > @4.0.15
> 
> 升级到 4.1.0-beta.1 看下

![微信截图_20200917170554](https://user-images.githubusercontent.com/52631716/93450068-170cf080-f908-11ea-9199-267cb09fc3dd.png)
用官方d的示例就有

**Comment by Vocal2019** [comment]
> > > 版本是？
> > 
> > 
> > @4.0.15
> 
> 升级到 4.1.0-beta.1 看下

测试版会在初始化的时候报错
![微信截图_20200917171103](https://user-images.githubusercontent.com/52631716/93450680-d2358980-f908-11ea-9611-4e03df61d49e.png)
![微信截图_20200917171153](https://user-images.githubusercontent.com/52631716/93450737-e5e0f000-f908-11ea-949f-b32506139d90.png)

是antv报的错

**Comment by Vocal2019** [comment]
> > > 版本是？
> > 
> > 
> > @4.0.15
> 
> 升级到 4.1.0-beta.1 看下

我放弃使用蜘蛛图了，但是有个问题，label 重叠怎么办？
![微信截图_20200917183120](https://user-images.githubusercontent.com/52631716/93459235-01052d00-f914-11ea-9cc0-0bf9bb2c25bb.png)

**Comment by Me-Momo** [comment]
label: {
  layout: {
   type: 'pie-outer' // or. 'hide-overlap'
  }
}

**Comment by Vocal2019** [comment]
> label: {
> layout: {
> type: 'pie-outer' // or. 'hide-overlap'
> }
> }

我用beta版本，只显示了两个label
![微信截图_20200917194846](https://user-images.githubusercontent.com/52631716/93466483-e2f0fa00-f91e-11ea-86c1-57f8434a826d.png)
这是我的数据
![微信截图_20200917195018](https://user-images.githubusercontent.com/52631716/93466560-074cd680-f91f-11ea-9413-5fa1172243d7.png)

**Comment by zhongwenqiang** [comment]
蜘蛛图布局始终不生效，有弄清楚是什么原因吗？直接copy的官方代码，也把版本升级到了4.1.0-beta.1，仍然没用，咋解决
