### ISSUE TITLE
请教一个问题，如何解决饼图label遮挡重叠的问题，已经设置上了 layout: { type: 'hide-overlap' }

### ISSUE THREAD

**Issue by Vocal2019** [antvis/G2#2842]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决饼图label重叠

### What does the proposed API look like?
无

![微信截图_20200918140052](https://user-images.githubusercontent.com/52631716/93562020-cf45a200-f9b7-11ea-83f2-519b7874fc1e.png)

**Comment by Vocal2019** [comment]
shanghai的数据和beijing的重叠了，请教一下，如何解决这个问题，有什么其他属性需要设置的吗？

**Comment by Me-Momo** [comment]
给 复现 demo，方便做问题优化；目前可以尝试加一个 label: { labelHeight }

**Comment by Vocal2019** [comment]
> 给 复现 demo，方便做问题优化；目前可以尝试加一个 label: { labelHeight }

我用了 pie-spider 加上 labelHeight 就可以 正常看到蜘蛛图了，搞清楚问题了，昨天蜘蛛图做不了是因为我labelHeight 不小心设置了 200，现在我用的是 beta 版本，感谢
