### ISSUE TITLE
chart.updateOptions 调用后图表白屏

### ISSUE THREAD

**Issue by liuzhenying** [antvis/G2#2844]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/e60ecf1d](https://riddle.alibaba-inc.com/riddles/e60ecf1d)

### Steps to reproduce
https://riddle.alibaba-inc.com/riddles/e60ecf1d  2s 后调用 updateOptions, 白屏

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | mac |
| Browser | chrome |

**Comment by NicolaCage** [comment]
我也遇到了同样的问题
