### ISSUE TITLE
内置Slider的start设置与展示数据不一致的bug

### ISSUE THREAD

**Issue by joker0910** [antvis/G2#2847]
官网demo链接：https://antv-g2.gitee.io/zh/examples/area/basic#area-large
![image](https://user-images.githubusercontent.com/29895229/93714186-9bbf6f00-fb93-11ea-9bc7-1448cf7ded94.png)
拖动start或者end后会展示正常

**Comment by bhabgs** [comment]
内置的

**Comment by bhabgs** [comment]
我也遇到了类似问题，并且发现内置的 sider 不能与chart下的view 关联。
``` js
chart.option("slider", {'config'})
```

**Comment by elvira1112** [comment]
我也遇到了一样的问题

**Comment by elvira1112** [comment]
chart.getController('slider').onValueChanged([0, 0.3]);

可以自己在 chart.render(); 后调用一次 valueChanged 方法。

**Comment by hustcc** [comment]
我们在 v4.1.0-beta 中解决这些问题了，但是正式版本暂未发布。稍等 930 我们会发布正式版本。
