### ISSUE TITLE
changeData不触发annotation更新

### ISSUE THREAD

**Issue by Zonciu** [antvis/G2#2851]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jovial-hill-uiwwp?file=/index.html)

### Steps to reproduce
复现demo改造自[官方折线图案例](https://antv-g2.gitee.io/zh/examples/gallery/line#line8)，用途是实时数据的监测预警
1. 新建两个chart，设定数据标注
2. 定时插入数据
3. 分别调用render和changeData更新数据

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | Windows 10 |
| Browser | Microsoft Edge 85.0.564.51 |

---
1. 使用changeData更新数据时折线不会根据annotation.regionFilter的配置来变色，调用render才会变色，这是有意的设计吗？
2. 数据动态更新时，要保持标注更新的话，正确的方式是怎样？

**Comment by wgf4242** [comment]
同问我的也是这样。。标注不更新。。

**Comment by hustcc** [comment]
这几天统一解决这个问题，我们自己也遇到这个问题！
