### ISSUE TITLE
分面 chart.interaction('active-region') 报错

### ISSUE THREAD

**Issue by lxfu1** [antvis/G2#2853]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/facet/facet#mirror-transpose](https://g2.antv.vision/zh/examples/facet/facet#mirror-transpose)

### Steps to reproduce
1、 示例添加 chart.interaction('active-region') ； 2、打开控制台。

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | - |

**Comment by hanai** [comment]
遇到了同样的问题 `TypeError: Cannot read property 'field' of null`

![image](https://user-images.githubusercontent.com/1222115/99433185-2a5c2c80-2948-11eb-8091-1e98088ab522.png)

**Comment by hanai** [comment]
@lxfu1 你遇到的问题一样么？

**Comment by Dante-dan** [comment]
你们解决了吗
