### ISSUE TITLE
axis>label>rotate属性只能以文本中心为旋转原点, 需求以文本左侧为旋转原点 

### ISSUE THREAD

**Issue by GanYuan1024** [antvis/G2#2857]
axis>label>rotate属性只能以文本中心为旋转原点, 旋转过后的文本与柱状图不对齐
![Snipaste_2020-09-23_01-53-38](https://user-images.githubusercontent.com/52742207/93918927-9f8ff480-fd3f-11ea-9698-c649c3eec5d0.jpg)

**Comment by hustcc** [comment]
```ts
chart.axis('year', {
    label: {
        rotate: -Math.PI/4,
        style: {
            textAlign: 'right',
            textBaseline: 'top'
        }
        
    }
});
```

![image](https://user-images.githubusercontent.com/7856674/93952617-dd127300-fd7b-11ea-835c-108783b632b5.png)

**Comment by GanYuan1024** [comment]
完美解决, 谢谢!
