### ISSUE TITLE
牛眼图的标签在链接上没有显示 （官方代码，未做改变）

### ISSUE THREAD

**Issue by xiao15934831580** [antvis/G2#2859]
问题1：标签在链接上没有显示
问题2：标签在afterrender之后，所以图表发生切换大小的交互之后，标签并没有根据图表的大小发生改变，所以有什么方法可以实时的交互吗

https://codepen.io/xiao15934831580/pen/GRZPBLX

**Comment by DarrenPei** [comment]
你这个环境Util.polarToCartesian函数没有识别,前面加上G2.
```js
      const point1 = G2.Util.polarToCartesian(center.x, center.y, pointRadius, - 3 * Math.PI / 8 + (Math.PI / 8) * i);
```

https://g2.antv.vision/zh/examples/column/stack#ripple
