### ISSUE TITLE
g-base 这个库，EventController 对象鼠标和滚轮事件addEventListener加入 { passive: true }

### ISSUE THREAD

**Issue by qiuyeduxin** [antvis/G2#2860]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当大盘同时有多个图表加载时候，滚动页面会非常卡顿，浏览器也会大量的报no-passive警告，加入这个可以解决卡顿，记得兼容哦

### What does the proposed API look like?
无

**Comment by hustcc** [comment]
可以在这里介绍和普及一下这个参数的含义嘛？

**Comment by Fiv5** [comment]
这个库没人维护了吗？ g-base 这个包目前只能找到一个 npm 的链接，也没有 git 仓库...

**Comment by visiky** [comment]
在 antv/g 中，monorepo的方式

**Comment by Fiv5** [comment]
> 在 @antv/g 中，monorepo的方式

这个我有找过，但还是没找到在哪😂  https://github.dev/antvis/g/blob/next/packages/g/package.json
![image](https://user-images.githubusercontent.com/23014093/147623964-8607be8e-7d86-478c-9440-4ade4d6fdb6a.png)

**Comment by visiky** [comment]
master 分支，next 分支是 G 5.0 对应 https://g-next.antv.vision

**Comment by Fiv5** [comment]
> master 分支，next 分支是 G 5.0 对应 https://g-next.antv.vision

感谢，找到了。那么关于 passive 这个，当前版本有计划吗？

**Comment by Fiv5** [comment]
`g-base` 的 `event-controller`，会绑定 document 的 mousemove 事件，在页面有多个 bizCharts 实例时，鼠标移动都会造成明显卡顿。
![image](https://user-images.githubusercontent.com/23014093/147819934-3cfe93d0-f1ba-4d45-b37f-b8efe26a1f8e.png)

**Comment by hustcc** [comment]
@xiaoiver 这个问题我印象中已经解决了？麻烦看一下。

**Comment by pearmini** [comment]
目前 4.x G 不会维护了，可以使用 5.x 的 G：https://github.com/antvis/G 。
