### ISSUE TITLE
G2 tooltip的样式 被 *全局样式“污染”

### ISSUE THREAD

**Issue by GoldMemory** [antvis/G2#2861]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://goldmemory.github.io/G2_tooltip.html](https://goldmemory.github.io/G2_tooltip.html)

### Steps to reproduce
访问“重现DEMO链接”即可重现。    “重现DEMO链接”的html文件是从AntV_G2网站上的案例html文件完整复制的，然后在页面头部添加了下面的全局样式，然后tooltip样式就乱了。
 <style type="text/css">
        * {
            margin: 0px;
            height: 0px;
        }
 </style>

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | win8.1 |
| Browser | chrome   版本 81.0.4044.122（正式版本） （64 位） |

---
页面里的其它样式都是用了全局 样式（没有margin、padding）,如果改全局样式，页面其它地方就乱了，所以希望antv能解决tooltip样式被“污染”的问题。

**Comment by Me-Momo** [comment]
tooltip也是html的一部分，可以考虑在tooltip domStyles中加一个样式处理，或者全部样式 * 改成 *:not(.g2-tooltip)
