### ISSUE TITLE
label该如何实现这种曲折线条 以及环图如何加入阴影

### ISSUE THREAD

**Issue by Elderkly** [antvis/G2#2862]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
更简易得实现功能需求

### What does the proposed API look like?
labelLine: {
                            style: {
                                line:2,
                                degrees: 120
                            }
                        },

![image](https://user-images.githubusercontent.com/32736776/94013768-25ae4880-fddd-11ea-8222-2b48797e045d.png)

**Comment by DarrenPei** [comment]
能贴下你的代码吗

**Comment by Elderkly** [comment]
> 能贴下你的代码吗
` 
const windowWidth = document.documentElement.clientWidth
                const chart = new Chart({
                    container: 'c1',
                    autoFit: true,
                    height: windowWidth * 0.11,
                });
                chart.data(this.list1);
                chart.scale('percent', {
                    formatter: (val) => {
                        val = val * 100 + '%';
                        return val;
                    },
                });
                chart.coordinate('theta', {
                    radius: 0.75,
                    innerRadius: 0.6,
                });

                //  提示
                chart.tooltip(false);

                //  图例
                chart.legend(false);

                chart
                    .interval()
                    .adjust('stack')
                    .position('percent')
                    .color('item',['#4da6bf','#ed6046'])
                    // .label('percent', (percent) => {
                    //     return {
                    //         content: (data) => {
                    //             return `${data.item}: <span>${percent * 100}%</span>`;
                    //         },
                    //     };
                    // })
                    .label('percent', {
                        layout: [{ type: 'pie-spider' }, { type: 'hide-overlap' }],
                        offset: 35,
                        labelHeight: 38,
                        content: (obj, item) => {
                            const G = getEngine('canvas');
                            const group = new G.Group({});
                            // 了解 shape 的绘制原理：y0 左下起点 y1 右上起点
                            const [y0, y1] = item.y || [0, 0];
                            const inRight = y0 < y1;
                            const textAlign = inRight ? 'left' : 'right';

                            const topFontSize = windowWidth * 0.00729166;
                            const bottomFontSize = windowWidth * 0.009375;
                            group.addShape({
                                type: 'text',
                                attrs: {
                                    x: 0,
                                    y: 0,
                                    text: obj.item,
                                    fill: 'rgba(255, 255, 255, 0.5)',
                                    fontSize: topFontSize,
                                    textAlign,
                                },
                            });

                            group.addShape({
                                type: 'text',
                                attrs: {
                                    x: 0,
                                    y: 4,
                                    text: `${obj.count}(${(obj.percent * 100).toFixed(2)}%)`,
                                    textAlign,
                                    textBaseline: 'top',
                                    fill: 'rgba(255, 255, 255, 0.8)',
                                    fontWeight: 700,
                                    fontSize: bottomFontSize,
                                },
                            });

                            if (!inRight) {
                                group.translate(group.getBBox().width, 0);
                            }
                            group.translate(0, topFontSize);
                            return group;
                        },
                        labelLine: {
                            style: {
                                lineWidth: 1.5,
                                stroke: 'rgba(255, 255, 255, .8)',
                            },
                        },
                    })

                chart.interaction('element-active');

                chart.render();
`
目前实现的效果是这样的
![image](https://user-images.githubusercontent.com/32736776/94284810-7a8cc300-ff85-11ea-8cea-3bb14881674e.png)

**Comment by Elderkly** [comment]
> 能贴下你的代码吗
` const windowWidth = document.documentElement.clientWidth
                const chart = new Chart({
                    container: 'c1',
                    autoFit: true,
                    height: windowWidth * 0.11,
                });
                chart.data(this.list1);
                chart.scale('percent', {
                    formatter: (val) => {
                        val = val * 100 + '%';
                        return val;
                    },
                });
                chart.coordinate('theta', {
                    radius: 0.75,
                    innerRadius: 0.6,
                });

                //  提示
                chart.tooltip(false);

                //  图例
                chart.legend(false);

                chart
                    .interval()
                    .adjust('stack')
                    .position('percent')
                    .color('item',['#4da6bf','#ed6046'])
                    // .label('percent', (percent) => {
                    //     return {
                    //         content: (data) => {
                    //             return `${data.item}: <span>${percent * 100}%</span>`;
                    //         },
                    //     };
                    // })
                    .label('percent', {
                        layout: [{ type: 'pie-spider' }, { type: 'hide-overlap' }],
                        offset: 35,
                        labelHeight: 38,
                        content: (obj, item) => {
                            const G = getEngine('canvas');
                            const group = new G.Group({});
                            // 了解 shape 的绘制原理：y0 左下起点 y1 右上起点
                            const [y0, y1] = item.y || [0, 0];
                            const inRight = y0 < y1;
                            const textAlign = inRight ? 'left' : 'right';

                            const topFontSize = windowWidth * 0.00729166;
                            const bottomFontSize = windowWidth * 0.009375;
                            group.addShape({
                                type: 'text',
                                attrs: {
                                    x: 0,
                                    y: 0,
                                    text: obj.item,
                                    fill: 'rgba(255, 255, 255, 0.5)',
                                    fontSize: topFontSize,
                                    textAlign,
                                },
                            });

                            group.addShape({
                                type: 'text',
                                attrs: {
                                    x: 0,
                                    y: 4,
                                    text: `${obj.count}(${(obj.percent * 100).toFixed(2)}%)`,
                                    textAlign,
                                    textBaseline: 'top',
                                    fill: 'rgba(255, 255, 255, 0.8)',
                                    fontWeight: 700,
                                    fontSize: bottomFontSize,
                                },
                            });

                            if (!inRight) {
                                group.translate(group.getBBox().width, 0);
                            }
                            group.translate(0, topFontSize);
                            return group;
                        },
                        labelLine: {
                            style: {
                                lineWidth: 1.5,
                                stroke: 'rgba(255, 255, 255, .8)',
                            },
                        },
                    })

                chart.interaction('element-active');

                chart.render();`
目前实现的效果是这样的
![image](https://user-images.githubusercontent.com/32736776/94284890-9728fb00-ff85-11ea-9676-18901a428089.png)

**Comment by Me-Momo** [comment]
目前没有，但可以尝试下: label: { layout: { type: 'spider-label'} }

**Comment by Me-Momo** [comment]
环图添加阴影：
```
chart
  .interval({
    theme: {
      background: "#000",
      geometries: {
        interval: {
          rect: {
            default: {
              style: {
                lineWidth: 0,
                shadowBlur: 20,
                shadowColor: "rgba(255, 255, 255, 0.45)"
              }
            }
          }
        }
      }
    }
  })
```
或者使用 [自定义主题](https://g2.antv.vision/en/docs/manual/developer/registertheme#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%BB%E9%A2%98%E6%A0%B7%E5%BC%8F%E8%A1%A8)
