### ISSUE TITLE
自定义主题theme中的defaultColor是不是应该改为background

### ISSUE THREAD

**Issue by DarrenPei** [antvis/G2#2865]
G2文档自定义主题https://g2.antv.vision/zh/docs/manual/developer/registertheme
这里的defaultColor是不是应该改为background
```js
import { registerTheme, Chart } from '@antv/g2';

// Step 1: 注册主题
registerTheme('newTheme', {
  defaultColor: 'red',
});

// Step 2: 使用
chart.theme('newTheme');
chart.render();
```

演示效果 https://codesandbox.io/s/boring-bell-ffrcb?file=/src/index.js
但就是坐标轴和刻度都不见了，没找到别的好方法

参考资料
https://g2-v3.antv.vision/zh/docs/manual/tutorial/creating-chart   图标的样式部分background
https://github.com/antvis/G2/blob/master/tests/unit/theme/background-spec.ts
https://github.com/antvis/G2/blob/master/tests/bugs/2258-spec.ts

**Comment by Me-Momo** [comment]
api使用错了 可以支持background的

**Comment by hustcc** [comment]
@DarrenPei @Me-Momo 问题可能是 background shape 的层级太高，所以挡住 axis 了

**Comment by simaQ** [comment]
4.0.x 是有这个问题的，升级到 4.1.x 就好了，目前 beta 版本 4.1.0-beta.9
