### ISSUE TITLE
当数据数组的纵坐标值都为null时出错

### ISSUE THREAD

**Issue by gjbigger** [antvis/G2#2875]
const chart = new Chart({
                container: 'container',
                autoFit: true,
                height: 230,
            });
            chart.data([
                 {datetime:'01', total:null, type: '收款'},
                 {datetime:'02', total:null, type: '收款'},
                 {datetime:'01', total:null, type: '退款'},
                 {datetime:'02', total:null, type: '退款'},
            ]);
            chart.axis('total', {
                type:"log",
                label: {
                    formatter: (val) => {
                        return val + ' 元';
                    },
                },
            });
            chart
                .interval()
                .position('datetime*total')
                .color('type')
                .adjust([
                    {
                        type: 'dodge',
                        marginRatio: 0,
                    },
                ]);
            chart.render();

当我的data对象数组中，纵坐标值total的数据全为null时，渲染出问题
![QQ截图20200928100053](https://user-images.githubusercontent.com/24708765/94383176-e03da280-0171-11eb-8b4c-59e73448dfb4.png)

**Comment by hustcc** [comment]
建议在业务层做一层数据过滤，底层不会无限兼容各种业务数据的异常情况。
