### ISSUE TITLE
单组数据显示切换时候，tooltip数据没有显示出来

### ISSUE THREAD

**Issue by llz1990** [antvis/G2#2880]
![image](https://user-images.githubusercontent.com/27805503/94528578-2d516f80-026b-11eb-8dc0-13e13242211b.png)
![image](https://user-images.githubusercontent.com/27805503/94528605-38a49b00-026b-11eb-83a6-fd2a8786cb30.png)

**Comment by Me-Momo** [comment]
可以给一个复现 demo 吗，看下你的 tooltip 怎么写的

**Comment by ColinChen2** [comment]
link with  #2784
