### ISSUE TITLE
g2legend 好想没有设置字体颜色选项  还有  混合画图  图例 不能显示

### ISSUE THREAD

**Issue by Arthas-xu** [antvis/G2#2883]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
个性化颜色 或者背景颜色 比较深  看起来不明显

### What does the proposed API look like?
希望api 是那种对象式点开查看 这样 比较方便点

**Comment by hustcc** [comment]
same with https://github.com/antvis/G2/issues/2886
