### ISSUE TITLE
g2官方示例饼图中的嵌套饼图，tooltip有错误

### ISSUE THREAD

**Issue by wzgeda** [antvis/G2#2884]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/pie/nested](https://g2.antv.vision/zh/examples/pie/nested)

### Steps to reproduce
.tooltip('name*percent'中的name要改成type

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | - |

**Comment by DarrenPei** [comment]
up
