### ISSUE TITLE
g2 lenged 没有设置字体颜色的属性

### ISSUE THREAD

**Issue by yuwenyaxing** [antvis/G2#2886]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by Arthas-xu** [comment]
同求  我也想解决这个问题

**Comment by simaQ** [comment]
```ts
chart.legend({
  itemName: {
    style: {
      fill: 'red'
    }
  }
})
```

**Comment by yuwenyaxing** [comment]
可以了，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月30日(星期三) 下午3:28
收件人:&nbsp;"antvis/G2"<G2@noreply.github.com&gt;;
抄送:&nbsp;"右右&amp;贝贝"<1226927073@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/G2] g2 lenged 没有设置字体颜色的属性 (#2886)





 chart.legend({   itemName: {     style: {       fill: 'red'     }   } })

**Comment by yuwenyaxing** [comment]
您好，请问G2可以做立体柱图么，有没有文档

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月9日(星期五) 上午9:07
收件人:&nbsp;"antvis/G2"<G2@noreply.github.com&gt;;
抄送:&nbsp;"右右&amp;贝贝"<1226927073@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/G2] g2 lenged 没有设置字体颜色的属性 (#2886)





 
Closed #2886.

**Comment by yuwenyaxing** [comment]
您好，请问您两个关于G2的问题
1、可以做立体柱图么，有没有文档
2、设置tooltip左对齐，没有生效，应该怎么设置？
chart.tooltip({
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;position:&nbsp;'left',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;showCrosshairs:&nbsp;true,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;shared:&nbsp;true
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;})




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "antvis/G2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月9日(星期五) 上午9:07
收件人:&nbsp;"antvis/G2"<G2@noreply.github.com&gt;;
抄送:&nbsp;"右右&amp;贝贝"<1226927073@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/G2] g2 lenged 没有设置字体颜色的属性 (#2886)





 
Closed #2886.
