### ISSUE TITLE
多views 如何合并 tooltip?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [antvis/G2#2893]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
![image](https://user-images.githubusercontent.com/33362998/95392472-6ff3f700-08be-11eb-9298-c452b0c52623.png)

绘制此图用了4个view， 上层2个 ( stack column + line ) 下层2个 ( stack column + line )

请问是否有办法 可以把上层的2个view 的tooltip 数据展示在一起？ 或者有什么更好的解决办法吗？

**Comment by Me-Momo** [comment]
可以尝试自定义交互，参考下这个：https://github.com/antvis/G2Plot/pull/1337

**Comment by xiaoyu-tamu** [comment]
感谢 @Me-Momo
