### ISSUE TITLE
请问plugin支持npm方式安装吗？

### ISSUE THREAD

**Issue by oxcafebabe** [antvis/g2#29]
由于使用了webpack，直接引用线上地址无效，所以想问一下是否有通过npm安装插件的方法，谢谢。

**Comment by TomHuangCN** [comment]
g2 暂时木有完善的插件机制。npm 安装方式暂时没有

**Comment by lulu27753** [comment]
使用`npm install @antv/g2`  命令会报错，请问有解决办法吗

`源文本中存在无法识别的标记。
所在位置 行:1 字符: 13
+ npm install  <<<< @antv/g2
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordEx
   ception
    + FullyQualifiedErrorId : UnrecognizedToken
`

**Comment by simaQ** [comment]
检查下你环境的 node 版本，建议使用 v8 哦
