### ISSUE TITLE
 希望在tooltip提供一个显示合计的需求

### ISSUE THREAD

**Issue by nxboo** [antvis/G2#2903]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我们在做一个堆积面积图,希望在tooltip显示一条合计信息。希望能实现该功能。如果已经实现，还请指点一下，感谢  
https://antv-g2plot.gitee.io/zh/examples/area/stacked#basic

### What does the proposed API look like?
无

**Comment by hustcc** [comment]
使用 tooltip.customContent 配置实现。

```ts
chart.tooltip({
    customContent: (a, b) => {
      console.log(a, b);
      return `
      <div class="g2-tooltip-title">2019-03</div>
      <ul class="g2-tooltip-list">
        <li class="g2-tooltip-list-item">
          <span class="g2-tooltip-marker" style="background: rgb(91, 143, 249); width: 8px; height: 8px; border-radius: 50%; display: inline-block; margin-right: 8px;"></span>
          <span class="g2-tooltip-name">uv</span>:
          <span class="g2-tooltip-value">350</span>
        </li>
       <li class="g2-tooltip-list-item">
          <span class="g2-tooltip-marker" style="background: rgb(91, 143, 249); width: 8px; height: 8px; border-radius: 50%; display: inline-block; margin-right: 8px;"></span>
          <span class="g2-tooltip-name">总计</span>:
          <span class="g2-tooltip-value"> 1000</span>
        </li>
      </ul>
      `;
    },
  })
```

![image](https://user-images.githubusercontent.com/7856674/95642609-179a4080-0adc-11eb-9385-f9ee7c0cce1b.png)

**Comment by zaite** [comment]
附议此需求，项目中急需此功能

**Comment by Cj50353** [comment]
> 使用 tooltip.customContent 配置实现。
> 
> ```ts
> chart.tooltip({
>     customContent: (a, b) => {
>       console.log(a, b);
>       return `
>       <div class="g2-tooltip-title">2019-03</div>
>       <ul class="g2-tooltip-list">
>         <li class="g2-tooltip-list-item">
>           <span class="g2-tooltip-marker" style="background: rgb(91, 143, 249); width: 8px; height: 8px; border-radius: 50%; display: inline-block; margin-right: 8px;"></span>
>           <span class="g2-tooltip-name">uv</span>:
>           <span class="g2-tooltip-value">350</span>
>         </li>
>        <li class="g2-tooltip-list-item">
>           <span class="g2-tooltip-marker" style="background: rgb(91, 143, 249); width: 8px; height: 8px; border-radius: 50%; display: inline-block; margin-right: 8px;"></span>
>           <span class="g2-tooltip-name">总计</span>:
>           <span class="g2-tooltip-value"> 1000</span>
>         </li>
>       </ul>
>       `;
>     },
>   })
> ```
> 
> ![image](https://user-images.githubusercontent.com/7856674/95642609-179a4080-0adc-11eb-9385-f9ee7c0cce1b.png)



> 使用 tooltip.customContent 配置实现。
> 
> ```ts
> chart.tooltip({
>     customContent: (a, b) => {
>       console.log(a, b);
>       return `
>       <div class="g2-tooltip-title">2019-03</div>
>       <ul class="g2-tooltip-list">
>         <li class="g2-tooltip-list-item">
>           <span class="g2-tooltip-marker" style="background: rgb(91, 143, 249); width: 8px; height: 8px; border-radius: 50%; display: inline-block; margin-right: 8px;"></span>
>           <span class="g2-tooltip-name">uv</span>:
>           <span class="g2-tooltip-value">350</span>
>         </li>
>        <li class="g2-tooltip-list-item">
>           <span class="g2-tooltip-marker" style="background: rgb(91, 143, 249); width: 8px; height: 8px; border-radius: 50%; display: inline-block; margin-right: 8px;"></span>
>           <span class="g2-tooltip-name">总计</span>:
>           <span class="g2-tooltip-value"> 1000</span>
>         </li>
>       </ul>
>       `;
>     },
>   })
> ```
> 
> ![image](https://user-images.githubusercontent.com/7856674/95642609-179a4080-0adc-11eb-9385-f9ee7c0cce1b.png)

谢谢,在你的基础上改了下
```ts
	tooltip: {
		customContent: (title, items) => {
			console.log('customContent', title, items)
			let html = ``
			let liText = ``
			let sumContent = {
				name: '总计',
				value: 0,
				color: 'transparent',
			}
			const getLiText = value => {
				return `<li class="g2-tooltip-list-item">
				<span class="g2-tooltip-marker" style="background: ${value.color}; width: 8px; height: 8px; border-radius: 50%; display: inline-block; margin-right: 8px;"></span>
				<span class="g2-tooltip-name">${value.name}</span>:
				<span class="g2-tooltip-value">${value.value}</span>
			</li>`
			}
			html += `<div class="g2-tooltip-title">${title}</div><ul class="g2-tooltip-list">`

			items.forEach((item, index) => {
				sumContent.value += Number(item.value)
				liText += getLiText(item)
				// 最后一次
				if (index + 1 === items.length) liText = getLiText(sumContent) + liText
			})
			html += liText
			html += `</ul>`
			return html
		},
	},
 ```
![image](https://user-images.githubusercontent.com/11425503/180913053-3c52cee9-a335-402c-b64e-145d1337e8fa.png)
