### ISSUE TITLE
单词拼写错误

### ISSUE THREAD

**Issue by aminwangaa** [antvis/G2#2904]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/docs/api/legend](https://g2.antv.vision/zh/docs/api/legend)

### Steps to reproduce
LegendCfg.maker 搜索这个  应该是marker 弄了老半天才发现单词错误

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
@aminwangaa 有兴趣来一个 pr 直接解决吗，直接全文搜索替换这个就可以了。

**Comment by hustcc** [comment]
想来 pr 有很多途径啊，比如写文档，文档迁移，写单侧等。
