### ISSUE TITLE
关于自定义shape的bug或者是设计缺陷。

### ISSUE THREAD

**Issue by ColinCLL** [antvis/G2#2905]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/docs/manual/developer/registershape/#gatsby-focus-wrapper](https://g2.antv.vision/zh/docs/manual/developer/registershape/#gatsby-focus-wrapper)

### Steps to reproduce
直接运行就能发现无柱状出现。

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | win10 |
| Browser | latest Google |

---

### 关于原来文档例子

![image](https://user-images.githubusercontent.com/19434659/95651238-8e0a6300-0b1b-11eb-862e-b6a7ef2a04bb.png)

根据原教程配图所示，柱状图所有柱子的颜色都是不一样的，可能是因为同类型柱子颜色不应该不一样这个bug的修改，做了其他特殊处理去掉的color，所以后面的`getDrawCfg`和`getShapeInfo`都取不到`color`属性，最后导致取不到color也许是正常情况，所以没有继续往color这个方向思考。

我自己看了源码，发现自定义的shape，在createElement （[代码这行](https://github.com/antvis/G2/blob/master/src/geometry/base.ts#L1389)）传入的`mappingData`就是不带有color属性的

官网上这个例子我猜测应该是前几个版本的了。

### 现有`registerShape`缺陷

`registerShape`的`draw`方法的回调参数`cfg`没有默认`color`属性和`defaultStyle`属性

`color`属性必须使用`chart`实例的`color`方法定义才有。使用自定义的就要传入color值，要不就没有颜色，同时也不好设置默认fill，但官方的shape有`defaultStyle`

导致使用默认官方shape和自定义shape，存在使用方式上的差别，这样第一次调试自定义shape的人会很懵，加一行`.shape("xxx")`之后发现不行第一个想到的不会是去加`.color()`方法，而是去调试shape的空间位置关系

### 解决建议

到`defaultStyle`属性，获取的shape的主题色（[代码这行](https://github.com/antvis/G2/blob/master/src/geometry/base.ts#L1368-L1369)）默认了几个内置`defaultStyle`。`registerShape`在没在文档中发现可以添加自定义shape的默认主题色。

· 建议使用自定义shape时候找不到默认theme可以自动取`theme`的第一个作为自定义shape的主题（[代码在这](https://github.com/antvis/G2/blob/master/src/geometry/base.ts#L1368-L1369)）

· 或者多内置一个或几个通用的主题样式（[代码在这](https://github.com/antvis/G2/blob/master/src/util/theme.ts)），找不到`shapeName`的时候就根据情况使用通用主题样式（[代码在这](https://github.com/antvis/G2/blob/master/src/geometry/base.ts#L1368-L1369)）

**Comment by hustcc** [comment]
资深用户，来提个 pr 吧，非常欢迎。

**Comment by Me-Momo** [comment]
我在自定义瀑布图 shape 也遇到这个问题了

**Comment by ColinCLL** [comment]
效率高啊，这就PR修复了。
