### ISSUE TITLE
Tooltip title support format function

### ISSUE THREAD

**Issue by maplor** [antvis/G2#2907]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
now `TooltipCfg.title` accept a string, I hope it can accept a function to dynamic format tooltip title. I have try `TooltipCfg.customContent` but it can't cache dom and renderer frequently.
if TooltipCfg.title can accept a function, it can more flexible and high performance.

### What does the proposed API look like?
TooltipCfg.title accept a function like:
```typescript
chart.tooltip({
  title(title: string, items: LooseObject[]) {
    return 'my custom title';
  },
});
```

if thie feature is reasonable, I can also make a PR, code looks in `/src/util/tooltip.ts` function getTooltipTitle.

**Comment by solovieff** [comment]
I suppose it was there but moved somewhere: https://github.com/antvis/g2/issues/40

**Comment by maplor** [comment]
> I suppose it was there but moved somewhere: #40

the scale formatter will affect legend, tooltip and axis. It can't only format the tooltip or calculate with other field data。

In G2 4.x，`TooltipCfg.title` set a string will make some format but not flexible, I hope a function type so.

**Comment by hustcc** [comment]
supported in the latest version, see the website.
