### ISSUE TITLE
g2折线图分组展示

### ISSUE THREAD

**Issue by shihangbo** [antvis/G2#2908]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
效果：根据数据分类，给多条折线图进行分组绘制；
例如：总共有16条数据，分为4组，每组的4条曲线分别可自定义（颜色/宽度等），每组的样式相同；
如图：
<img width="2438" alt="WeChatd7fd452bde6e26da984c399367a8dcf7" src="https://user-images.githubusercontent.com/19473390/95729428-76fc7a00-0caf-11eb-9511-d8e4cca4267a.png">

### What does the proposed API look like?
chart.line().group((data)=>{...})

**Comment by Me-Momo** [comment]
参考下这个：https://g2plot.antv.vision/en/examples/gallery/trend
