### ISSUE TITLE
饼图的图例文字只显示一个字，后面都是省略号

### ISSUE THREAD

**Issue by darknoll** [antvis/G2#2910]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
this.chart = new Chart({
        container: container,
        smooth: true,
        autoFit: true,
        width: 260,
        height: 250
      })
      this.chart.coordinate('theta', {
        radius: 0.75,
        innerRadius: 0.6
      })
      this.chart.legend({
        visible: true,
        position: 'top',
        flipPage: true
      })

![饼图.png](https://i.loli.net/2020/10/13/YVXxt5E26HIDv1T.png)
| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | win10 |
| Browser | chrome 85.0.4183.121 |

**Comment by Me-Momo** [comment]
提供复现版本，应该是容器太小了

**Comment by jialinhome** [comment]
我也遇到这个问题了，请问这个最终解决了嘛？

**Comment by QSBin** [comment]
![_16052622477616](https://user-images.githubusercontent.com/17582861/99060981-d4038c80-25db-11eb-81ed-db96dc165219.png)
![_16052622717760](https://user-images.githubusercontent.com/17582861/99060993-d6fe7d00-25db-11eb-9bd2-0fe92a878b68.png)
position不设置位置 ，使用空字符 默认显示左上角 能够显示完全 
![图片](https://user-images.githubusercontent.com/17582861/99061111-044b2b00-25dc-11eb-8b66-a4a39e6c2dd1.png)
![图片](https://user-images.githubusercontent.com/17582861/99061130-0b723900-25dc-11eb-801b-a9da94f26239.png)
position设置位置，就显示不全

**Comment by hustcc** [comment]
使用 4.1.0-beta.17，近期发布 4.1 正式版本。
