### ISSUE TITLE
图表内容超出，刷新时不能自适应

### ISSUE THREAD

**Issue by woliwa1** [antvis/G2#2913]
* **G2 Version**:4.0.15
* **Platform**: 
* **Mini Showcase(like screenshots)**: <img width="310" alt="屏幕快照 2020-10-13 下午11 49 46" src="https://user-images.githubusercontent.com/20971540/95884591-e1e0aa80-0dae-11eb-8c7b-9ae8979306f7.png">
* **CodePen Link**:

图表设置autoFit: true时，每次刷新图表内容都会超出，调用chart.forceFit()方法也没有帮助；移动窗口时，图表就显示正常！请求帮助！

const chart = new Chart({
        container: id,
        height: 264,
        autoFit: true,
        padding: [0, 0, 60, 0]
      });
      chart.source(this.pieChartData);
      chart.coord("polar", { innerRadius: 0.2 });
      chart.axis(false);
      chart.animate(false);
      chart
        .interval()
        .position("name*value")
        .color("name", color);
      chart.render();
      chart.forceFit();

**Comment by atdow** [comment]
旧版本存在这个问题，更新到`4.1.0-beta.14`版本修复了这个问题，演示链接：`https://codesandbox.io/s/vue-g2-forked-nhv66?file=/src/components/HelloWorld.vue`。
> 在依赖里面切换ant/g2的版本到`4.0.15`会重现你描述的bug，切换到`4.1.0-beta.14`可以解决该问题(右边数字问题是我自己自定义的问题，与组件库无关)

**Comment by woliwa1** [comment]
还是有这样的问题！
![0](https://user-images.githubusercontent.com/20971540/98196111-429e7580-1f5e-11eb-9c52-ed79bd4bd390.png)
![1](https://user-images.githubusercontent.com/20971540/98196400-fbfd4b00-1f5e-11eb-8a87-2eacaa7fd1ac.png)
![2](https://user-images.githubusercontent.com/20971540/98196135-50ec9180-1f5e-11eb-82ad-f45e409bd25d.png)
当我折叠目录时，图表外面的div 宽度发生了改变，不过图表没有自适应

**Comment by woliwa1** [comment]
"@antv/g2": "^4.1.0-beta.14"
@atdow
