### ISSUE TITLE
本地跑不起来这个项目

### ISSUE THREAD

**Issue by mxy2316868975javascript** [antvis/G2#2914]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://new-issue.antv.vision/](https://new-issue.antv.vision/)

### Steps to reproduce
本地跑不起来这个项目

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | - |

![image](https://user-images.githubusercontent.com/15233384/95890067-dc3a9300-0db5-11eb-848d-e84ef5d9b939.png)

**Comment by mxy2316868975javascript** [comment]
fatal error: 'vips/vips8' file not found, 请问社区大佬如何解决

**Comment by mxy2316868975javascript** [comment]
fatal error: 'vips/vips8' file not found, 请问社区大佬如何解决

**Comment by hustcc** [comment]
本地环境问题，可以搜索 google，应该很多解决办法。https://github.com/libvips/libvips/issues/1434

**Comment by newghost** [comment]
可以使用代理来解决:

    export http_proxy:127.0.0.1:1087
    export https_proxy:127.0.0.1:1087
