### ISSUE TITLE
图算法 webWorker 支持

### ISSUE THREAD

**Issue by zuiidea** [antvis/G2#2915]
### What problem does this feature solve?
图算法可能耗时较长，导致页面卡住，如 pageRank 算法，一是需要webWorker支持，其次是异步支持。当前 pageRank 算法内应用到了graph 实例的一些API，graph 实例在copy到worker上可能有点问题，看能否提供一个纯算法的API。

### What does the proposed API look like?
例如：
`getPageRank(graph, epsilon, linkProb).then(result => console.log(result))`

**Comment by hustcc** [comment]
G2 的issue吗？

**Comment by zuiidea** [comment]
搞错了 G6 的，通过 https://antv-issue-helper.surge.sh/ 生成时，默认第一个是G2，没有注意
