### ISSUE TITLE
怎么设置图表标题

### ISSUE THREAD

**Issue by CHAACC** [antvis/g2#292]
在文档上找不到设置标题的属性

**Comment by leungwensen** [comment]
目前图表没有总体的 “标题”，需要用户自己用 DOM 或者其他方式添加

**Comment by yukinotech** [comment]
那现在支持吗？

**Comment by hustcc** [comment]
https://github.com/antvis/g2plot 基于 g2 的图表库，这个是支持 title 的

**Comment by simaQ** [comment]
> 2年过去了，那现在支持吗？

[g2plot](https://github.com/antvis/g2plot )，你值得拥有！

**Comment by yohanceli** [comment]
g2plot 2.x版本又没有title和description的配置了，文档中没有找到
