### ISSUE TITLE
tooltip数值部分格式化设置配置

### ISSUE THREAD

**Issue by bunnyxt** [antvis/G2#2920]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有时候需要对tooltip的数值部分的展示进行格式化，例如对于某个x，y值为`1234567`，但我希望tooltip展示的是格式化后的数字，例如`1,234,567`，现有的TooltipCfg.itemTpl接口一改就整个全改了，而且还需要与`chart.tooltip()`接口配合，不够友好

### What does the proposed API look like?
```js
chart.tooltip({
  formatter: y => y.toLocaleString()
});
```

**Comment by riyueweiyi** [comment]
```
tooltip('name*value*needFormat', (name, value, needFormat) => {
          return {
            name,
            value: needFormat ? value.toLocaleString() : value
          };
        })
```

**Comment by bunnyxt** [comment]
> 一种不太优雅的解决方式。
> 
> ```
> tooltip('name*value*needFormat', (name, value, needFormat) => {
>           return {
>             name,
>             value: needFormat ? value.toLocaleString() : value
>           };
>         })
> ```

谢谢！折腾了一会儿之后搞清楚了`'x*y'`字符串以及返回的对象的格式，已经解决了！

我的数据是类似

```js
[
  {added: 1, prop: 'a', value: 12345}, 
  {added: 1, prop: 'b', value: 23456}, 
  {added: 1, prop: 'c', value: 34567}, 
  {added: 2, prop: 'a', value: 12346}, 
  {added: 2, prop: 'b', value: 23457}, 
  {added: 2, prop: 'c', value: 34568}, 
  // ...
]
```

应该这样配置

```js
chart.line()
  .position('added*value')
  .color('prop')
  .shape('smooth')
  .tooltip('prop*value', (prop, value) => {  // here, prop*value
    return {
      name: prop,  // return name with value prop
      value: value.toLocaleString(),
    };
  });
```
