### ISSUE TITLE
G2Plot Pie 设置legend的offsetX后点击操作图例里的选项会位置重置 #1729

### ISSUE THREAD

**Issue by Me-Momo** [antvis/G2#2921]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bingtutuli-offsetx-bug-elp4w)

### Steps to reproduce
设置 legend offsetX 后，点击图例筛选，位置会变化

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | - |

**Comment by Me-Momo** [comment]
![image](https://user-images.githubusercontent.com/15646325/96133979-ac160000-0f2d-11eb-8671-9591ba9f9d43.png)

**Comment by peamed** [comment]
请问怎么解决
