### ISSUE TITLE
Pie chart legend item names have no option for text overflow

### ISSUE THREAD

**Issue by cromat** [antvis/G2#2923]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/young-cdn-e4lct?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Just render the chart

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | Firefox, Chrome |

---
When rendering pie chart, legend item names are automatically trimmed (e.g. Label1 becomes Lab...). It would be nice to have an option to set text-overflow manually or maximum item name text width. Also, it would be great to have chart rotated horizontally by default if there is 100% item on chart like in this case.

![image](https://user-images.githubusercontent.com/3780307/96144333-58db8780-0f04-11eb-8e24-7d2b89db2aef.png)

**Comment by pmtu95** [comment]
I have the same issue, you can resolve it by setting 'itemWidth' or 'maxItemWidth', but if you set legend layout by vertical, the text will be cut out at last...
<img width="107" alt="Screen Shot 2020-12-10 at 10 44 01" src="https://user-images.githubusercontent.com/33753111/101718845-a1fb2280-3ad4-11eb-9e9d-29f5df773126.png">
