### ISSUE TITLE
Webpack 5 Warning

### ISSUE THREAD

**Issue by xiaoyu-tamu** [antvis/G2#2928]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
不算bug

### Steps to reproduce
    "@antv/g2": "4.1.0-beta.12",
    "webpack": "5.1.3",
    "webpack-cli": "4.0.0",
    "webpack-dev-server": "3.11.0"

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | - |

---
WARNING in ./node_modules/@antv/g-canvas/esm/index.js 5:0-29
The requested module './interfaces' contains conflicting star exports for the name '__esModule' with the previous requested module './types'
 @ ./node_modules/@antv/g2/esm/index.js 7:0-47 10:25-37

WARNING in ./node_modules/@antv/g-svg/esm/index.js 5:0-29
The requested module './interfaces' contains conflicting star exports for the name '__esModule' with the previous requested module './types'
 @ ./node_modules/@antv/g2/esm/index.js 8:0-41 11:22-31

**Comment by xiaoyu-tamu** [comment]
我是在antvis/g 通过提供的issues link创建的  不知道为什么跑到这个repo来了。。

**Comment by damianthekreeeytor** [comment]
I am also experiencing these warnings.

**Comment by YanYuanFE** [comment]
+1

**Comment by UntilGone** [comment]
+1 共有8个warning
