### ISSUE TITLE
Frame 处理数组方式是否可以调整下？

### ISSUE THREAD

**Issue by bzl132** [antvis/g2#293]
1.使用场景：
       使用 堆叠柱状图时，用Frame处理后台获取到的数组格式的数据，然后交由Chart组件使用。
2.问题：
        当数组中第一个实体的堆叠数组不完全时，不管后续实体是否完全，渲染出的图表都不完整。
        从页面中的代码看可能是这段的问题
`colNames: function() {
    var t = this, e = t.names;
    if (!e) {
        var n = this.data
            , r = n[0];
        e = [],
        r && i.each(r, function(t, n) {
            e.push(n)
        }),
    	t.names = e
    }
    return e
}`
r = n[0]     直接从数据的第一个实体中取names导致的。
3.能不能用其它方式取names或者提供外部设置names的方法来处理这个地方

* **G2 Version**:2.3.13
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by dxq613** [comment]
你可以切换成 G2 3.0 或者在 2.3 的列定义里面指定数据的类型。

```js
chart.source(data, {
  a: {type: 'linear'}
});
```

**Comment by bzl132** [comment]
好的，谢谢
