### ISSUE TITLE
饼图数据 NaN 导致页面崩溃

### ISSUE THREAD

**Issue by caolinjian** [antvis/G2#2930]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/icy-dew-nepr7?file=/index.js)

### Steps to reproduce
毕现， coordinate theta或helix时，数据存在NaN就崩溃

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
先过滤数据避开，后面对异常数据统一处理。
