### ISSUE TITLE
如何偏移图表的位置？

### ISSUE THREAD

**Issue by Vocal2019** [antvis/G2#2933]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
偏移图表位置

### What does the proposed API look like?
设置 offsetX

请教一个问题，如图所示，我希望图表能对齐到左边，找不到文档在哪里设置

![微信截图_20201020153446](https://user-images.githubusercontent.com/52631716/96555098-edb9f880-12e9-11eb-9790-2e08e941de34.png)

**Comment by Vocal2019** [comment]
还有 legend 被省略了，怎么解决？

**Comment by maplor** [comment]
+1  饼图图例左右布局时排列会很奇怪

**Comment by guanyun-helo** [comment]
是的，如何做到 geometry 在坐标系上的偏移，不和 tick 对齐

**Comment by maplor** [comment]
今天尝试了一下，似乎可以用 chart 的 leftPadding + legend rightPadding 来实现 geometry 偏移，但还没想清楚用什么规则做自动计算
![image](https://user-images.githubusercontent.com/5591805/96874167-6797e080-14a8-11eb-9563-b8af13a39d1e.png)

**Comment by maplor** [comment]
今天我尝试用 coordinate translate 来偏移饼图中心点，然后饼图就变形了，难怪 types 定义里没有 translate 这个操作。。。

![截屏2020-11-20 下午7 38 28](https://user-images.githubusercontent.com/5591805/99796231-15f67a80-2b68-11eb-9625-e5bd5884917b.png)

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/106253764-e2645a80-6252-11eb-9618-77cc13812a35.png)


左移 50px。
