### ISSUE TITLE
How to set default enabled legends? 如何设置默认启用的图例？

### ISSUE THREAD

**Issue by bunnyxt** [antvis/G2#2939]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
包括折线图在内的很多图标，可以通过点击图例显示/隐藏某一类的数据，现在我希望我的图在渲染出来的时候就是有部分类别的数据是未启用（灰色）的，该如何设置？

### What does the proposed API look like?
经过DataSet变化后的数据
```
[
  { 'added': 1, 'prop': 'prop1', 'value': '1' }, 
  { 'added': 1, 'prop': 'prop2', 'value': '2' }, 
  { 'added': 1, 'prop': 'prop3', 'value': '3' }, 
  { 'added': 2, 'prop': 'prop1', 'value': '4' }, 
  { 'added': 2, 'prop': 'prop2', 'value': '5' }, 
  { 'added': 2, 'prop': 'prop3', 'value': '6' }, 
  // ...
]
```

声明接口
```
chart.line()
  .position('added*value')
  .color('prop')  // 3 categories, prop1, prop2 and prop3
  .legend({
    enable: ['prop1', 'prop2'],  // <- here! I want to just show prop1 and prop2 category data, disable prop3
  })
  .shape('smooth');
```

**Comment by bunnyxt** [comment]
希望这样配置后，默认渲染出的图表是这样的

![QQ20201021-215724](https://user-images.githubusercontent.com/32478279/96730137-7c14a400-13e8-11eb-93fb-72960b7701da.png)

prop3默认就是灰色的未启用的状态

**Comment by maplor** [comment]
可以试试 chart.filter ：https://antv-g2.gitee.io/zh/docs/api/chart-func#chartfilterfield-string-condition-filtercondition--null-view

**Comment by bunnyxt** [comment]
> 可以试试 chart.filter ：https://antv-g2.gitee.io/zh/docs/api/chart-func#chartfilterfield-string-condition-filtercondition--null-view

啊就是这个！十分感谢！

**Comment by belerweb** [comment]
文档打不开了，有新的链接吗？

**Comment by chenchuan01** [comment]
文档打不开了，有新的链接吗？

**Comment by maplor** [comment]
截至 2021-01-04，文档中chart实例的api被全部删掉了，我去反馈一下。

**Comment by maplor** [comment]
新的链接：https://antv-g2.gitee.io/zh/docs/api/general/chart

**Comment by lvming6816077** [comment]
打不开找不到了

**Comment by maplor** [comment]
5.0 的 api 已经更新，我也暂时没找到具体方法。4.0 版本 api 可以在老版本官网找到。
