### ISSUE TITLE
make the shadow cover only one single row when hovered

### ISSUE THREAD

**Issue by NoraGithub** [antvis/g2#294]
Would there be a way I could make the shadow cover only one single row in `list` facet? And how could I do that?
![dingtalk20171219050751](https://user-images.githubusercontent.com/7700016/34128244-00dadbe6-e47b-11e7-88b8-88c25d3b26ae.png)
 As far as I read the `tooltip` part, there would not be suitable configs for that. What I want to do is to give accurate feedback for interaction, and now it would be easy to misunderstand I haven't hover on the right bar.
If I missed anything in the doc, please let me know.

**Comment by leungwensen** [comment]
It is a bug of `interval` geometry, we'll fix it.
