### ISSUE TITLE
双y轴无法图列显示不全

### ISSUE THREAD

**Issue by aosirmaxsir** [antvis/G2#2941]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/en/examples/other/other#double-axes](https://g2.antv.vision/en/examples/other/other#double-axes)

### Steps to reproduce
官方demo的双y轴 点击图列都无法隐藏数据，
我自己的清空是第一个Y轴有5条数据 这5条数据的图列显示了也可以正常隐藏，但是另外一个Y轴的字段没有显示在图列上

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | - |

---
希望修复这个问题，17年就有人提了这个问题。而不是在官方demo上用 chart.removeInteraction('legend-filter'); // 自定义图例，移除默认的分类图例筛选交互 来自欺欺人
双y轴都不需要你多此一举移除交互 本来就不支持

**Comment by Surongbin** [comment]
说的没错

**Comment by wangjingithub** [comment]
为啥还没修复啊

**Comment by hustcc** [comment]
标准图形语法的图例是响应分类字段的。而在双轴图中，并没有分类字段，而是多指标。

所以这个做法必然是使用自定义的图例（图例项根据指标来决定），然后监听图例事件去对数据和 geometry 进行过滤，比不是自欺欺人，而是合理做法。

如果懒得处理这一套，想要开箱即用，为什么不用 [G2Plot 封装好的双轴图](https://g2plot.antv.vision/zh/examples/dual-axes/stacked-column-line#stacked-column-line) ？
