### ISSUE TITLE
多层饼图展示所有图例时样式问题

### ISSUE THREAD

**Issue by webliuxiang** [antvis/G2#2943]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/webliuxiang/pen/ZEOBaKp](https://codepen.io/webliuxiang/pen/ZEOBaKp)
问题：
![image](https://user-images.githubusercontent.com/25944130/96851084-36101c80-148a-11eb-9c9d-f01c0bb83e5f.png)
期望：
![image](https://user-images.githubusercontent.com/25944130/96851306-753e6d80-148a-11eb-821f-a864939fdca6.png)

### Steps to reproduce
多组图例可以合并成一组吗？使用html生成图例也会生成多组。

| Environment | Info |
|---|---|
| g2 | 3.5.11 |
| System | win10 |
| Browser | chrome |

**Comment by webliuxiang** [comment]
@leungwensen

**Comment by hustcc** [comment]
如果需要生成到一起，只能使用:

```ts
chart.legend({
  custom: true,
  items: [...]
})
```
