### ISSUE TITLE
滑块Slider里handlerStyle里的Img设置无效请问该如何解决

### ISSUE THREAD

**Issue by xiaoxiaoting** [antvis/G2#2946]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/patient-moon-dpxvs?file=/src/App.js)

### Steps to reproduce
覆盖默认的滑块操作块样式时，滑块Slider里handlerStyle里的Img设置无效

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
不支持  handlerStyle.img 配置啊~

**Comment by xiaoxiaoting** [comment]
> 不支持 handlerStyle.img 配置啊~

那要怎么设置自定义的icon呢？

**Comment by hustcc** [comment]
> > 不支持 handlerStyle.img 配置啊~
> 
> 那要怎么设置自定义的icon呢？

暂不支持，你从什么渠道得知这么配置的？

**Comment by xiaoxiaoting** [comment]
从https://github.com/antvis/g2-plugin-slider里看到的配置，有img这个属性，如果不支持的话还有其他的方法嘛，我们的UI设计稿里icon是类似暂停播放键那样的圆形图案

**Comment by xiaoxiaoting** [comment]
> > > 不支持 handlerStyle.img 配置啊~
> > 
> > 
> > 那要怎么设置自定义的icon呢？
> 
> 暂不支持，你从什么渠道得知这么配置的？

从https://github.com/antvis/g2-plugin-slider里看到的配置，有img这个属性，如果不支持的话还有其他的方法嘛，我们的UI设计稿里icon是类似暂停播放键那样的圆形图案

**Comment by xiaoxiaoting** [comment]
> > > > 不支持 handlerStyle.img 配置啊~
> > > 
> > > 
> > > 那要怎么设置自定义的icon呢？
> > 
> > 
> > 暂不支持，你从什么渠道得知这么配置的？
> 
> 从[https://github.com/antvis/g2-plugin-slider里看到的配置，有img这个属性，如果不支持的话还有其他的方法嘛，我们的UI设计稿里icon是类似暂停播放键那样的圆形图案](https://github.com/antvis/g2-plugin-slider%E9%87%8C%E7%9C%8B%E5%88%B0%E7%9A%84%E9%85%8D%E7%BD%AE%EF%BC%8C%E6%9C%89img%E8%BF%99%E4%B8%AA%E5%B1%9E%E6%80%A7%EF%BC%8C%E5%A6%82%E6%9E%9C%E4%B8%8D%E6%94%AF%E6%8C%81%E7%9A%84%E8%AF%9D%E8%BF%98%E6%9C%89%E5%85%B6%E4%BB%96%E7%9A%84%E6%96%B9%E6%B3%95%E5%98%9B%EF%BC%8C%E6%88%91%E4%BB%AC%E7%9A%84UI%E8%AE%BE%E8%AE%A1%E7%A8%BF%E9%87%8Cicon%E6%98%AF%E7%B1%BB%E4%BC%BC%E6%9A%82%E5%81%9C%E6%92%AD%E6%94%BE%E9%94%AE%E9%82%A3%E6%A0%B7%E7%9A%84%E5%9C%86%E5%BD%A2%E5%9B%BE%E6%A1%88)

不知道handlerStyle里的具体属性可以在哪里看到，目前设置的宽高属性是可以的

**Comment by hustcc** [comment]
看api文档中的slider部分。

**Comment by xiaoxiaoting** [comment]
文档介绍太简单了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hustcc <notifications@github.com&gt;
发送时间: 2020年10月22日 22:07
收件人: antvis/G2 <G2@noreply.github.com&gt;
抄送: Crystal <1062764645@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[antvis/G2] 滑块Slider里handlerStyle里的Img设置无效请问该如何解决 (#2946)





 
看api文档中的slider部分。

**Comment by bigbigqiang** [comment]
![image](https://user-images.githubusercontent.com/25946840/103326161-03862f80-4a8a-11eb-8fbd-d40be00f34a5.png)
![image](https://user-images.githubusercontent.com/25946840/103326475-76dc7100-4a8b-11eb-9df1-1e8e38a30132.png)

这个是源码配置项，只有宽度和高度，没有其他配置项，看来这个图标库并不完善

**Comment by hustcc** [comment]
4.x 中的 slider 还不支持 img 滑块配置！
