### ISSUE TITLE
关于“堆叠柱状图”圆角问题

### ISSUE THREAD

**Issue by S96412** [antvis/G2#2952]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g2.gitee.io/zh/examples/column/stack#rounded-stacked](https://antv-g2.gitee.io/zh/examples/column/stack#rounded-stacked)

### Steps to reproduce
当数据为0时，画出的图形会出现“被裁剪的部分”
![image](https://user-images.githubusercontent.com/15974281/96992788-efd7bd80-155c-11eb-8dc0-05d5c9a5ad0d.png)
| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
https://antv-g2.gitee.io/zh/examples/column/stack#rounded-stacked 这个 demo 中的自定义 shape 逻辑修改一下。修改高度包含有圆弧的高度。
