### ISSUE TITLE
请问如何在V4上实现V3的柱状图hover到背景上依然显示Tooltip

### ISSUE THREAD

**Issue by chuxiaorong** [antvis/G2#2959]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
从V3.X版本升级，柱状图中，原先 Hover 在背景上，也会出现背景阴影，并且出现 Tooltip，现在是只能 Hover 到 Element 上才会出现，虽然可以设置 "active-region"，不过依然无法满足，不知道有何方法解决这个问题

### What does the proposed API look like?
是否存在一些简单配置即可实现？

**Comment by Demian1996** [comment]
@chuxiaorong 
### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/blissful-banzai-qsbm8)

我刚才也遇到了这个问题，翻了下官方示例，发现在tooltipConfig中加上shared，就可以hover背景出现阴影了。

![image](https://user-images.githubusercontent.com/21359263/104567467-c759ee00-5689-11eb-839a-90820fb9fb48.png)
![image](https://user-images.githubusercontent.com/21359263/104567643-f96b5000-5689-11eb-8ea5-c60f12189134.png)
