### ISSUE TITLE
热力图自定义背景，不能使用本地图片，使用url图片存在跨域问题

### ISSUE THREAD

**Issue by fancy-cat** [antvis/G2#2961]
this.chart.annotation().image({src: '图片地址'})
1. 图片地址不能使用本地图片，
2. 使用url图片存在跨域问题，或者有允许跨域的参数配置吗

**Comment by hustcc** [comment]
有报错，有 demo 吗？

**Comment by fancy-cat** [comment]
> 有报错，有 demo 吗？

我把官网demo的src地址改成了自己的图片地址 
`https://greenvalley.oss-cn-shanghai.aliyuncs.com/condition/48e85b876fe8404086d53f8f64ab4689_750_1000.jpg`
报错如下：
`Access to image at 'https://greenvalley.oss-cn-shanghai.aliyuncs.com/condition/48e85b876fe8404086d53f8f64ab4689_750_1000.jpg' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`

如果是用本地图片的话 ，不报错，但是页面图片不显示

**Comment by hustcc** [comment]
你使用这个地址 https://gw.alipayobjects.com/zos/rmsportal/mweUsJpBWucJRixSfWVP.png 去使用应该就是 ok 的，你看下是是否是因为一些 cdn 设置原因导致的。

**Comment by fancy-cat** [comment]
> 你使用这个地址 https://gw.alipayobjects.com/zos/rmsportal/mweUsJpBWucJRixSfWVP.png 去使用应该就是 ok 的，你看下是是否是因为一些 cdn 设置原因导致的。

**Comment by suzhou3685** [comment]
最后怎么解决的啊
