### ISSUE TITLE
Create a legend for a line geometry

### ISSUE THREAD

**Issue by C5H8NNaO4** [antvis/G2#2976]
How can I add a legend that hides the mean line in the candlestick chart example?

I looked through tutorials the API and the source, but I can't seem to find a way to hide a column.

It only displays legends for categories.

Google Translate:
如何添加图例以隐藏烛台图表示例中的中线？

我浏览了教程的API和源代码，但似乎找不到隐藏列的方法。

它仅显示类别的图例。

* **CodePen Link**: https://jsfiddle.net/kq9gspbz/

~~Edit: I found a solution using a custom legend and an interaction that reacts on a legend:click and executes `line.hide/show()` I'm not sure if that's the right way, but it seems to be working. ~~

I just can't get the legend to show a candle marker like the ones in the example. 

Ok, that's messing with the entire chart as I have to set the color of the line to the same name as the scale. There should be an easy way to do this, but I can't find anything in the docs.

**Comment by hustcc** [comment]
use custom legend, when clicked, call geometry.setVisible(false)
