### ISSUE TITLE
分组柱状图间隔过大，设置 marginRatio: 0 仍无效

### ISSUE THREAD

**Issue by rosie597** [antvis/G2#2977]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nostalgic-sunset-6dhfr?file=/src/index.js)

### Steps to reproduce
当我设置了分组柱状图表的最大宽度，同时限制了图表横坐标的 range，marginRatio 会失效，随着数据量的减少分组柱状图不同柱子间距会变得越来越大，超出了坐标系范围

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | macbook pro |
| Browser | chrome 86.0.4240.111 |

**Comment by hustcc** [comment]
range 和 maxColumnWidth 对于 marginRatio 互相干扰。类似于 https://github.com/antvis/G2/issues/2980

**Comment by lumia2046** [comment]
感觉是不能设置range，设置的话，就会有问题，不设置，就没问题，感觉好奇怪
