### ISSUE TITLE
热力图不同颜色透明度不一样

### ISSUE THREAD

**Issue by fancy-cat** [antvis/G2#2978]
`this.chart.heatmap().position('x*y') .color('value', ['#2206FF', '#1543FC', '#0C6EF9', '#019FF6', '#5BC5F9', '#FFFFFF', '#FEFDC7', '#FBF82E', '#FCC607', '#FD7404', '#FF0500'])`

我的value范围是-10到10的 ，想实现一个过度效果，现在有个问题

> value值越小透明度越低，到-10以后，透明度直接是0了，而不是我想要的`#2206FF`

我希望他们透明度都是一样的

**Comment by hustcc** [comment]
有具体的复现 demo 吗？方便进行调试和快速修复。

**Comment by Mr-jili** [comment]
现在就是只要是0或者数据中最小值，都会是没有颜色的，应该展示是颜色色块的第一个颜色
