### ISSUE TITLE
分组柱状图同时设置size，marginRatio, 分组柱之间间距不生效

### ISSUE THREAD

**Issue by stareny** [antvis/G2#2980]
分组柱状图同时设置size，marginRatio, 分组柱之间间距不生效， 如下图：
![image](https://user-images.githubusercontent.com/11330230/98318050-ba30db00-2018-11eb-8d0b-52f184d8ecd4.png)

**Comment by Chengchcc** [comment]
+1

**Comment by hustcc** [comment]
这种情况，确实是一种无法满足的情况。有以下显示：

1. 分组柱子有自己分组的宽度
2. 单个柱子有自己的宽度
3. 分组中的柱子均分分组宽度

在这三个约束下，size 和 marginRatio 本身就是冲突的。无法两全，你可以想象一下自己期望的是什么样子？

**Comment by BangKk** [comment]
> 这种情况，确实是一种无法满足的情况。有以下显示：
> 
> 1. 分组柱子有自己分组的宽度
> 2. 单个柱子有自己的宽度
> 3. 分组中的柱子均分分组宽度
> 
> 在这三个约束下，size 和 marginRatio 本身就是冲突的。无法两全，你可以想象一下自己期望的是什么样子？

您好，没看懂这三个约束下，为什么 size 和 marginRatio 就冲突了。
marginRatio 基于柱子宽度 size，改了 size，marginRatio 失效，那柱间距并不是 marginRatio 控制？文档里是不是应该特别标注出来，不然很多开发者应该都会踩坑。

查了半天文档，只知道另外这两个优先级更高。

![image](https://user-images.githubusercontent.com/13979818/120884379-7b4a1e80-c615-11eb-9157-83ae7c47053c.png)

至于期望的样子，就是不至于挤出分组宽度的两根柱子能挨在一起，这是一种特殊的场景？
