### ISSUE TITLE
view chart double padding/View图表双倍padding问题

### ISSUE THREAD

**Issue by maplor** [antvis/G2#2983]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g2.gitee.io/zh/examples/map/map#choropleth-map](https://antv-g2.gitee.io/zh/examples/map/map#choropleth-map)

### Steps to reproduce
直接看官网示例，手动设置padding，实际表现是双倍的大小。

![doublepadding](https://user-images.githubusercontent.com/5591805/98324147-793fc300-2026-11eb-84e8-183746c7bcab.png)

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | - |

---
目前使用场景不多，但确实是个bug

**Comment by hustcc** [comment]
子 view 会继承父 view 的 padding 设置，所以将子 view 的 padding 设置为 0 即可。
