### ISSUE TITLE
How to make Pyramid by the funnel?

### ISSUE THREAD

**Issue by david66l** [antvis/G2#2989]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to use the funnel or pyramid shape to make a 3D data pyramid 

### What does the proposed API look like?
I want to have a shape like 3D image that can make the 3D image easily

**Comment by hustcc** [comment]
Now not support 3D data pyramid. For a long time, we won't support it.
