### ISSUE TITLE
G2 3.0设置坐标轴标题显示样式无效

### ISSUE THREAD

**Issue by zmiaozzz** [antvis/g2#299]
* **G2 Version**:3.0.2
* **Platform**:mac
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:[https://codepen.io/zmiaozzz/pen/ypOerp](https://codepen.io/zmiaozzz/pen/ypOerp)

如题，按以下设置，label可按照设置项显示，但坐标轴标题只是显示出来了，相关样式并没有生效。具体demo：[https://codepen.io/zmiaozzz/pen/ypOerp](https://codepen.io/zmiaozzz/pen/ypOerp)

```
chart.axis('value', {
  label: {
    textStyle: {
      rotate: 30
    }
  },
  title: {
    position: 'start',
    textStyle: {
      rotate: 90,
      fontSize: 14, // 文本大小
      textAlign: 'center', // 文本对齐方式
      fill: '#ff8800', // 文本颜色
      // ...
    }
  }
})
```

**Comment by simaQ** [comment]
这个功能是支持的，应该是传参的时候出错了，我修复下，谢谢反馈~
