### ISSUE TITLE
使用回调函数进行颜色值的自定义报错

### ISSUE THREAD

**Issue by fancy-cat** [antvis/G2#2993]
代码如下：
this.chart.heatmap().position('x*y').color('value', (value) => {
            if(value) {
              return 'red'
            } else {
              return 'blue'
            }
          })
报错如下：
Cannot read property '0' of undefined at getValue 

// 源码getValue
// 获取颜色之间的插值
var getValue = function (start, end, percent, index) {
    return start[index] + (end[index] - start[index]) * percent;
};

麻烦看下是什么原因导致的

**Comment by hustcc** [comment]
求完整的数据和现场，目前看不出什么问题。
