### ISSUE TITLE
基础饼图-蜘蛛标签显示样式异常

### ISSUE THREAD

**Issue by dravenxiaokai** [antvis/G2#2994]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/pie/basic#pie-spider-label](https://g2.antv.vision/zh/examples/pie/basic#pie-spider-label)

### Steps to reproduce
图表示例链接中的显示是正常的，antd-design-vue-pro项目中引入封装组件时，蜘蛛标签重叠展示不全

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | win10 |
| Browser | chrome 86.0.4240.183（正式版本）（64 位） |

**Comment by Me-Momo** [comment]
spider 布局对于溢出标签做了默认隐藏；你可以提供下你们场景的示例数据 demo，我们会看清楚优化布局，提供不进行默认隐藏的布局
