### ISSUE TITLE
Chart interaction "active-region" grows in width as datum grows in value, when it shouldn't

### ISSUE THREAD

**Issue by fnune** [antvis/G2#2999]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nervous-sinoussi-vqvbs?file=/src/index.js)

### Steps to reproduce
1. Create a chart with the "active-region" interaction.
2. See how the width of the hovered active region changes depending on the Y-axis value of the datum, which it shouldn't (I think?)

On my minimally-reproducible example:
1. Hover Tuesday or Wednesday and confirm that the hovered area is very big
2. Hover Thursday and confirm that the hovered area is correct (the size of the datum)

Correct:
![image](https://user-images.githubusercontent.com/16181067/98806042-df5a8a80-2418-11eb-9120-25b7102b009e.png)

Wrong:
![image](https://user-images.githubusercontent.com/16181067/98805996-c81b9d00-2418-11eb-9c85-c0a43e75db4a.png)

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | Ubuntu 20.04.1 LTS |
| Browser | Firefox 82.0.3 |

**Comment by hustcc** [comment]
Sorry, due to problems in the program's architecture design, we are unable to effectively fix the issues. You can has a try with [G2 5.0](https://g2.antv.antgroup.com/zh/examples/interaction/interaction/#highlight).
