### ISSUE TITLE
tooltip如何自定义额外数据

### ISSUE THREAD

**Issue by pansila** [antvis/g2#3]
我已经查过了教程中tooltip的用法，并实现了在tooltip中画另一张图，现在想添加额外数据到tooltip的文字描述里，请问有相应的办法么？

**Comment by simaQ** [comment]
额外的数据指的是数据源中其他的字段，还是另一个数据源？ 如果是数据源中其他的字段的话，直接用 geom 中的 tooltip('dimA*dimB*dimC') 就行。类似下面这样的代码：

```js
chart.point().position('height*weight').tooltip('gender*height*weight');
```
