### ISSUE TITLE
有考虑过宽度自适应吗

### ISSUE THREAD

**Issue by ketuzhong** [antvis/g2#30]
如题

**Comment by simaQ** [comment]
```js
var chart = new G2.Chart({
  id: 'c1',
  forceFit: true, // 宽度自适应
  height: 400
});
```

**Comment by ketuzhong** [comment]
嗯，谢谢

**Comment by stanleyxu2005** [comment]
我也在找类似的配置，目前我只能关掉forceFit，但是还没有找到如何定义每根柱子的宽度。g2的文档里面似乎没有啊。

![chart1](https://user-images.githubusercontent.com/5162687/37587380-21e8911e-2b9a-11e8-9833-f429a9f48ffb.PNG)
