### ISSUE TITLE
基础条形图-线条被遮挡

### ISSUE THREAD

**Issue by zhangyubin1** [antvis/G2#3001]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/bar/basic#radial-line](https://g2.antv.vision/zh/examples/bar/basic#radial-line)

### Steps to reproduce
查看示例

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | - |

---
4.0.12不存在此问题

**Comment by hustcc** [comment]
4.1.0-beta.18 已经解决，最近会发布正式版本。
