### ISSUE TITLE
slider filter data bug

### ISSUE THREAD

**Issue by Slanemy** [antvis/G2#3003]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pedantic-worker-m5ux3?file=/src/index.js)

### Steps to reproduce
传入x轴数据为number类型，slider滑块失效。

### 补充
查看了master代码，发现这slider的changeViewData部分代码有问题：xValues是一个字符串数组，而filter函数获取的value是原始数据，为number类型，此时indexOf始终返回-1。
![image](https://user-images.githubusercontent.com/33260895/99029015-52483a80-25ac-11eb-9b8a-32f030152173.png)

| Environment | Info |
|---|---|
| g2 | 4.1.0-beta.10 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
x 设置 cat 类型吧。

chart.axis('xField', { type: 'cat' })
