### ISSUE TITLE
如何在散点图中绘制一条 y=x 的直线?

### ISSUE THREAD

**Issue by Inuyashaaaaa** [antvis/G2#3006]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以解决一些需要不根据数据绘制图表的问题

### What does the proposed API look like?
在line的绘制里面可以指定函数绘制

**Comment by hustcc** [comment]
G2 是一个图形语法的可视化引擎。要实现这个需求，有几种办法：

1. 多 view，一个 view 绘制散点，一个 view 绘制折线图，然后两个 view 的 region 保持一致，视觉上就是两个图重叠一起
2. annotation 辅助元素

```ts
chart.annotation().line({ position: [start, end] });
```
3. ~~统计语法，规划中，暂时未提供~~
