### ISSUE TITLE
Grouped column chart labels display overlap

### ISSUE THREAD

**Issue by kousuutetu** [antvis/G2#3007]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-9liju9?file=src/App.js](https://stackblitz.com/edit/react-9liju9?file=src/App.js)

### Steps to reproduce
If the label values are similar, they overlap
Reproduction code
https://stackblitz.com/edit/react-9liju9?file=src/App.js

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | macOS Mojave 10.14.6 |
| Browser | Google Chrome Version 86.0.4240.183 (x86_64) |

**Comment by hustcc** [comment]
```ts
chart
        .interval()
        .position('年龄*身高')
        .label('身高', {}, { 
          layout: [{ type: 'fixed-overlap' }] // <----------
        })
        .color('name')
        .adjust([
          {
            type: 'dodge',
            marginRatio: 0,
          },
        ]);
```

![image](https://user-images.githubusercontent.com/7856674/106250956-513fb480-624f-11eb-9c51-07b24bcdaa55.png)

文档： https://g2.antv.vision/zh/docs/api/general/label/#geometrylabelcfglayout
