### ISSUE TITLE
custom font dislocation width localRefresh / 自定义字体在局部刷新时会错位

### ISSUE THREAD

**Issue by maplor** [antvis/G2#3008]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/7c2264d1?mode=jsx](https://riddle.alibaba-inc.com/riddles/7c2264d1?mode=jsx)

### Steps to reproduce
使用自定义字体，会在字体加载后局部刷新，此时会错位。如图，第一秒是正常显示，刷新页面后先显示默认字体，自定义字体加载后触发局部刷新，字体错位。

![Nov-16-2020 16-40-56](https://user-images.githubusercontent.com/5591805/99232915-81b9aa00-282d-11eb-924f-61f738637d59.gif)

在 riddle 这类平台行为还不一样，字体加载后不刷新，需要任意操作触发新的render才会显示自定义字体。

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
localeRefresh 设置为 false 吧。

**Comment by maplor** [comment]
> localeRefresh 设置为 false 吧。

我知道关掉可以生效，但这个bug有办法修复么？或者在外部手动触发一次重绘？

**Comment by hustcc** [comment]
> > localeRefresh 设置为 false 吧。
> 
> 
> 
> 我知道关掉可以生效，但这个bug有办法修复么？或者在外部手动触发一次重绘？

目前暂时无解，底层问题。

**Comment by maplor** [comment]
> > > localeRefresh 设置为 false 吧。
> > 
> > 
> > 我知道关掉可以生效，但这个bug有办法修复么？或者在外部手动触发一次重绘？
> 
> 目前暂时无解，底层问题。

OK
