### ISSUE TITLE
autoFit, autoPadding情况下坐标轴横纵数值均发生溢出

### ISSUE THREAD

**Issue by keleqnma** [antvis/G2#3009]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/snowy-moon-17ulf?file=/src/index.js)

### Steps to reproduce
点进进入沙盒（沙盒好像有些bug），一直说Chart没有初始化，但是代码应该是没问题的，重点看date这行数据，在这里作为横坐标轴，会发生溢出，以及value作为纵坐标轴也会发生溢出。

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | macOS 10.15.7 |
| Browser | 86.0.4240.193 |
 
![             の 人  人 哦の    ](https://user-images.githubusercontent.com/37303292/99248501-82f5d180-2843-11eb-94ab-4f00e58db357.png)

**Comment by keleqnma** [comment]
看到一个类似的问题连接，里面说已经修复了，但是我这里还是有这个问题：https://github.com/antvis/g2/issues/1164

**Comment by hustcc** [comment]
@keleqnma 使用最新版本的 4.1.x 应该解决的。

**Comment by dwb1994** [comment]
> 看到一个类似的问题连接，里面说已经修复了，但是我这里还是有这个问题：#1164

我升级到 4.1.9 后还是有问题
