### ISSUE TITLE
使用colorMap自定义颜色，图例legend颜色与图表对应不上

### ISSUE THREAD

**Issue by WhyStart** [antvis/G2#3012]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/laughing-field-e04o4)

### Steps to reproduce
chart
  .interval()
  .adjust('stack')
  .position('percent')
  .color('name*type', (name,type) => colorMap[type])

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | macos/windows |
| Browser | chrome |

---
.color('name*type') 把type放在左边就可以和图例颜色对应上，但是图例的值就是type的了，只想要name作为图例值，然后根据type自定义颜色

![image](https://user-images.githubusercontent.com/54924160/99359606-4cbf5d00-28ea-11eb-9410-3f8938223609.png)
![image](https://user-images.githubusercontent.com/54924160/99359753-82644600-28ea-11eb-8558-b2cb4174cbaa.png)

**Comment by hustcc** [comment]
应该这么写：

>   .color("type", (type) => colorMap[type])
