### ISSUE TITLE
registerShape point 在图表宽高变化后位置不更新，错位

### ISSUE THREAD

**Issue by xinple** [antvis/G2#3017]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g2.gitee.io/zh/examples/case/line#line8](https://antv-g2.gitee.io/zh/examples/case/line#line8)

### Steps to reproduce
比如官网案例中，拖拽改变图表宽高，可以看到那个 breath-point 错位了。

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | Chrome Version 86.0.4240.198 (Official Build) (x86_64) |

---
chart.annotation().regionFilter() 也有此问题，但是官网上例子试了下不会因为图表宽高改变错位，是不是新版已经修复了？

**Comment by hustcc** [comment]
4.1.0-beta 版本已经修复，最近会发布 4.1 正式版

**Comment by xinple** [comment]
谢谢

**Comment by charleskun** [comment]
Great！
