### ISSUE TITLE
在animate的appear下增加animation配置 则图表动画失效

### ISSUE THREAD

**Issue by lswl66** [antvis/G2#3020]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/lswl66/pen/wvWbMoV ](https://codepen.io/lswl66/pen/wvWbMoV )

### Steps to reproduce
默认是有动画的， line 74 注释打开后 则动画消失

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | - |

---
期望结果：出现配置对应的动画

**Comment by Taylorroger** [comment]
文档中内置动画名称和G2库中实现的不一样，比如pathIn， 实际应该传入'path-in'

**Comment by hustcc** [comment]
@Taylorroger  @lswl66  感谢反馈，也希望你们在发现文档问题的时候，有空的话，可以直接帮我们提交 pr，我想这部分应该不会存在技术门槛。
