### ISSUE TITLE
动态设置 setLayout 无效（当触发chart点击事件时，需要修改Chart的padding值）

### ISSUE THREAD

**Issue by bhabgs** [antvis/G2#3022]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/bhabgs-the-lessful/pen/mdEYPPy](https://codepen.io/bhabgs-the-lessful/pen/mdEYPPy)

### Steps to reproduce
初始化 Chart 时，没有设置padding， 当触发chart点击事件时，需要修改Chart的padding值，但是通过setLayout无法完成。

[官方源码位置](https://github.com/antvis/G2/blob/e7471d70b8293ef91a50e33a98c893f2dfb1c619/src/chart/view.ts#L195) 
![image](https://user-images.githubusercontent.com/19221378/99635828-82e11600-2a7d-11eb-8621-43cc3a2db847.png)

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | mac |
| Browser | chrome |

**Comment by bhabgs** [comment]
### 直接在chart上设置padding 成功
> 但是有个问题 就是首次触发 `interaction('element-single-selected')` 有显示问题

``` js
// 直接设置 成功
this.Chart.padding = [0, 80, 0, 0];

```

**Comment by hustcc** [comment]
不要用 setLayout 方法。

**Comment by hustcc** [comment]
> 不要用 setLayout 方法。

回复不是很详细，重新回复一下。对于自定义布局，G2 4.x 版本设置了两个机制：

- setLayout

在 G2 4.x 版本中，确实设计了 setLayout  让用户来自定义自己的布局函数，期望是美好的，耦合也算基本解除了，内部的布局函数也是走的 setLayout（默认布局函数），**但是**实际的执行过程中，发现对于开发者来说，理解成本还是太高了，

具体可以看内部默认的布局函数：[defaultLayout](https://github.com/antvis/G2/blob/master/src/chart/layout/index.ts#L20)，看起来简单，其实这个里面需要去理解 G2 可视化组件（axis、legend、slider 等等）的绘制逻辑，生命周期。并且目前没有进行业务上的试用，所以为了避免开发者踩坑，增加我们的答疑成本，暂时建议不要使用。

- syncViewPadding

G2 的布局，最终其实是计算图形的 padding 值，通过 syncViewPadding 的回调，可以设置不同 view 的 padding 值。本来这个是为了给分面图、多 view 图进行同步他们的 padding，保证图形是对齐的。这个对于开发者来说，成本比较低一些，但是能力也是有限。

----

后续的解法：

要实现自定义布局，最终还是要形成 setLayout 的机制的，只不过需要：

1. 将组件层的开发统一：让用户只感知到这些只是组件，而不需要感知他是具体的 axis、legend、slider 等。具体做法：抽象和统一组件的开发方式
2. 布局逻辑数学化：目前的布局逻辑，是代码命令式的控制，一方面是没有办法通过约束编程的思想来解耦，另一方面也不利于自定义。如果采用 **约束布局的方式**，那么就可以将布局逻辑变成数据表达式求解，代码做不到解耦，就做不到公式化。

上面 1，2 需要配合才能完成好让开发者低成本的自定义。改动很大，难，已经在孵化中了...不过还得等挺久的~~
