### ISSUE TITLE
Hope that the forms of data can be more flexible

### ISSUE THREAD

**Issue by hujianhang2996** [antvis/G2#3034]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
 The forms of data is like this:
[{x:1, y:1}, {x:2, y:1.2}, {x:3, y:2.1}......]
but My data is like this:
{x:[1,2,3,......], y[1,1.2,2.1,......]}
or like this(multiple xs):
{x1:[1,2,3,......], y1[1,1.2,2.1,......],x2:[7,8,9,......], y2[1.3,3.3,7,......]}
And the length of x and y is too large, it takes time to transpose it into the required form. So I hope that the form of data can be more flexible

### What does the proposed API look like?
columnData

**Comment by hustcc** [comment]
The data structure you describe is not a data structure that is convenient for data analysis. But we are.
