### ISSUE TITLE
用户指定了height，但是canvas的高度却会变化，不能固定在用户的height

### ISSUE THREAD

**Issue by atdow** [antvis/G2#3037]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g2.gitee.io/zh/examples/case/column#column2](https://antv-g2.gitee.io/zh/examples/case/column#column2)

### Steps to reproduce
https://antv-g2.gitee.io/zh/examples/case/column#column2，F12查看dom canvas的高度

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | - |
| Browser | - |

---
有时候用户指定了高度，拖动适应的时候，高度会一直增加，导致图形变形

**Comment by hustcc** [comment]
操作了，并没有复现，可以截图或者 gif 看下是什么样的表现吗？

**Comment by 18710123784** [comment]
> 操作了，并没有复现，可以截图或者 gif 看下是什么样的表现吗？

![image](https://user-images.githubusercontent.com/23441784/100334660-0d41f080-300f-11eb-99b1-f91f29a5c037.png)

**Comment by atdow** [comment]
![image](https://user-images.githubusercontent.com/52809115/100843840-ecb5e280-34b5-11eb-95f1-5faa6ee74934.png)

**Comment by moxuanluo** [comment]
我遇到了同样的问题，指定了高度，但是只要按下F11，canvas高度就会自动增加，然后切屏也会增个不停

**Comment by atdow** [comment]
canvas无限增加的问题解决思路：g2挂载dom的父节点的高度必须指定，可以是px或者rem单位。无限增加的高度一般是由于挂载dom的父节点的高度根本无法确定的情况才会出现，也可以解释为挂载dom的父节点的高度由子节点撑开（挂载dom的父节点不是g2挂载的容器，而是g2挂载的容器的父节点）。

**Comment by hustcc** [comment]
要理解一下其中的逻辑：

1. autoFit: true 的意思就是适应容器的大小，这个时候，你的容器需要有自己的高度和宽度，canvas 会自动使用容器的大小，这种情况一般在搭建产品中的卡片
2. autoFit: false 的时候，canvas 的大小就完全由开发者自己设置
