### ISSUE TITLE
两个view时，scale的sync设置boolean不生效，设置为字符串生效

### ISSUE THREAD

**Issue by MrSmallLiu** [antvis/G2#3038]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gallant-voice-qg6d2?file=/index.html)

### Steps to reproduce
无

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | windows |
| Browser | chrome86.0.4240.198 |

**Comment by hustcc** [comment]
sync: true 的意思是 sync: fieldName，只是一种快捷用法。
