### ISSUE TITLE
g2 有没有 直接保存成图片的 api

### ISSUE THREAD

**Issue by lihawhaw** [antvis/G2#3039]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以直接保存图片

### What does the proposed API look like?
可以像g6那样直接调一个方法就可以转换成图片下载

**Comment by hustcc** [comment]
没有内置，建议业务封装，拿到 canvas 实例，获取dataUrl，然后保存文件。
