### ISSUE TITLE
什么时候发布最新版本啊 现在急需syncViewPadding这个属性 目前最新的4.0.15版本没有这个属性吧

### ISSUE THREAD

**Issue by xiaolongGitHub1498** [antvis/G2#3041]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
两个view的padding问题

### What does the proposed API look like?
syncViewPadding: true

**Comment by hustcc** [comment]
使用 4.1.0-beta.18 版本吧，本周会发布正式版本。
