### ISSUE TITLE
如果chart 生成在一个modal 弹出层里 宽度无法100%自适应

### ISSUE THREAD

**Issue by neozhu** [antvis/G2#3042]
现在只能固定宽度，有朋友遇到这样问题有解决吗

**Comment by hustcc** [comment]
1. 外部监听容器变化，然后调用 changeSize。
2. 使用 G2Plot

**Comment by neozhu** [comment]
随便问一下G2 和G2Plot 有什么区别，是升级版吗

> 1. 外部监听容器变化，然后调用 changeSize。
> 2. 使用 G2Plot，G2Plot 封装了上面的

**Comment by Me-Momo** [comment]
G2Plot 是在 G2 基础上，屏蔽复杂概念的前提下，保留 G2 强大图形能力，封装出业务上常用的统计图表库。
G2Plot 官网：https://g2plot.antv.vision/zh
