### ISSUE TITLE
G2 视觉通道color自定义颜色回调支持Partial<ShapeAttrs>

### ISSUE THREAD

**Issue by boborua** [antvis/G2#3045]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

使用color来区分series时，回调目前应该只支持返回color: string，是否可以支持返回 ShapeAttrs来支持更丰富的颜色效果（例如纹理和渐变）

**Comment by hustcc** [comment]
通过 .style 视觉通道，跟你需求是一样的。

**Comment by boborua** [comment]
> 通过 .style 视觉通道，跟你需求是一样的。

@hustcc 
通过.style无法支持回调，来区分不同属性的data（目前测试下来是这样）

**Comment by boborua** [comment]
> > 通过 .style 视觉通道，跟你需求是一样的。
> 
> @hustcc
> 通过.style无法支持回调，来区分不同属性的data（目前测试下来是这样）

@hustcc style这个api没有找到相关的doc，其他issue里有提及过，我测试下来只能配置一个全局的style属性。any ideas?

**Comment by hustcc** [comment]
> > > 通过 .style 视觉通道，跟你需求是一样的。
> 
> > 
> 
> > @hustcc
> 
> > 通过.style无法支持回调，来区分不同属性的data（目前测试下来是这样）
> 
> 
> 
> @hustcc style这个api没有找到相关的doc，其他issue里有提及过，我测试下来只能配置一个全局的style属性。any ideas?

.style('field1*field2', () => {})
