### ISSUE TITLE
Center-aligning label and description in modelRect node

### ISSUE THREAD

**Issue by francisfeng** [antvis/G2#3049]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Basically I want to put label and description in the center of the container in accordance with other types of nodes. 

[Example: Current Style](https://imgur.com/fYFm0iz)

I do know that I can add custom node to do whatever I want. But for my speific needs, current modelRect node is good enough and complete customization looks like a little bit of hassle.

I found this issue similar to my situation: https://github.com/antvis/G6/issues/2331

So I think I can update node style afterward since I can manually position label and description. But it seems that description is always left aligned with label.

### What does the proposed API look like?
Just a `offset` attribute in `descriptionCfg` would be enough. Adding a option to center-align label and description would be even better.

**Comment by hustcc** [comment]
You can send issue in G6， here is G2.
