### ISSUE TITLE
如何点击饼图生成一个柱状图

### ISSUE THREAD

**Issue by yangguangmingman** [antvis/g2#305]
就是类似下钻功能，changeData（data）data 的数据结构需要同原始的数据结构保持一致。还有别的都方法吗？
G2 Version：^2.3.9

**Comment by leungwensen** [comment]
能详细描述一下需求吗，是同一个图还是两个图？数据是怎么样的？

另外，能直接用 G2 3.0 吗？

**Comment by yangguangmingman** [comment]
同一个图有办法做到吗？就是下钻功能，2.X版本实现下钻功能是通过changeData（）是吗？3.0有集成下钻功能？类似于hightchart下钻的那种（haighchart下钻可以实现多级下钻和返回上级，还有改变图表类型的下钻）

**Comment by leungwensen** [comment]
highcharts 的下钻是在配置和数据里指定关联的 id 来关联下一份数据和配置来实现的。G2 3.0 可以通过切换不同的 view 和使用 data-set 来实现类似的功能。

**Comment by dxq613** [comment]
这种功能，你直接 clear 重新设置数据源，声明语法就好了。

```js
chart.clear();
chart.source(newData);
chart.interval().position('x*y');
chart.render();

```
