### ISSUE TITLE
相同的长宽设置 但是多个图表 显示的实际图表宽度不同，无法填满盒子

### ISSUE THREAD

**Issue by KekeORSJ** [antvis/G2#3050]
G2 4.0.15 
相同的长宽设置 但是多个图表 显示的实际图表宽度不同；无法把宽度填满；
设置属性都为：
```
new Chart({
          container: "xxx",
          // autoFit: true,
          width: 1800,
          height: 1080
        });
```
![image](https://user-images.githubusercontent.com/28330361/100420133-db896200-30c0-11eb-94e3-0e1b42faf888.png)
![image](https://user-images.githubusercontent.com/28330361/100420785-01633680-30c2-11eb-92bb-86e113423c5c.png)
![image](https://user-images.githubusercontent.com/28330361/100420803-0922db00-30c2-11eb-90bd-45f568895bf0.png)
![image](https://user-images.githubusercontent.com/28330361/100420815-10e27f80-30c2-11eb-96ee-9b848cb0ecfb.png)
这是什么造成的，怎么解决！尝试增加宽度会相对的增加 比较像被缩小了

**Comment by hustcc** [comment]
看下 canvas 的父层 div 容器是宽，理论是和父容器宽度一致的。

另外，可以提供一个 live demo 或者可以复现的 代码，方便我们定位和修复。
