### ISSUE TITLE
syncViewPadding在changeData的时候位置错乱

### ISSUE THREAD

**Issue by xiaolongGitHub1498** [antvis/G2#3052]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/docs/manual/concepts/view/#%E5%A4%9A-view-%E5%8F%A0%E5%8A%A0](https://g2.antv.vision/zh/docs/manual/concepts/view/#%E5%A4%9A-view-%E5%8F%A0%E5%8A%A0)

### Steps to reproduce
两个view画左右y轴 设置了syncViewPadding 初始化的时候位置是正确的
![image](https://user-images.githubusercontent.com/26108004/100530751-b0258500-3230-11eb-97a3-b288239f253c.png)

当changeData更新两个view的数据时 位置发生错乱
![image](https://user-images.githubusercontent.com/26108004/100530771-f1b63000-3230-11eb-86ac-4ddbd8baf769.png)

| Environment | Info |
|---|---|
| g2 | 4.1.0-beta.21 |
| System | Macos Big Sur 11.0.1 |
| Browser | Google Chrome 86.0.4240.198 |

**Comment by hustcc** [comment]
@xiaolongGitHub1498 可以来一个在线复现的 demo 吗？

**Comment by xiaolongGitHub1498** [comment]
@hustcc 
[复现demo](http://jsrun.net/ArwKp/edit)

**Comment by maplor** [comment]
可以试试在changeData 后手动调用 chart.render()

**Comment by xiaolongGitHub1498** [comment]
@maplor 
这样试了一下样式没问题了 但是曲线的位置在第一次changeData的时候不对 第二次changeData的时候又好了 如此反复 详见[demo](http://jsrun.net/ArwKp/edit)

**Comment by maplor** [comment]
> @maplor
> 这样试了一下样式没问题了 但是曲线的位置在第一次changeData的时候不对 第二次changeData的时候又好了 如此反复 详见[demo](http://jsrun.net/ArwKp/edit)

我也注意到了，很奇怪。我这边用的时候没有遇到这个问题。

**Comment by xiaolongGitHub1498** [comment]
@maplor 请问下这个后期需要解决吗 还是说我这边使用的问题

**Comment by hustcc** [comment]
我来解决。

**Comment by hustcc** [comment]
在 多 view 情况下，如果子 view 的数据不一样，建议做法是 使用 v.data(newData)

.changeData 和 .data 的区别在于 changeData 会自动执行 render，但是实际上你的逻辑上需要在 chart 上执行 redner，所以没有必要使用 v.changeData。
