### ISSUE TITLE
使用source-map-lodaer后控制台报很多waring log:Failed to parse source map from ''Error: ENOENT: no such file or directory,

### ISSUE THREAD

**Issue by YanYuanFE** [antvis/G2#3053]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
如下
![image](https://user-images.githubusercontent.com/17774285/100537135-d531ec00-3260-11eb-901e-3703f8132121.png)

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | mac |
| Browser | chrome87 |

猜想应该是sourcemap文件没有提交发布到npm下

**Comment by hustcc** [comment]
应该是的，欢迎去 antvis/utils 中去 pr 加上 sourcemap 吧~

**Comment by YanYuanFE** [comment]
刚刚检查了下，source map文件有发布上来，但是js.map文件中的sources里面的源文件没有发布上来。
![image](https://user-images.githubusercontent.com/17774285/101463236-22584100-3978-11eb-9645-a97fb2cb893e.png)
包下面只有esm和lib，没有src

**Comment by hustcc** [comment]
> 刚刚检查了下，source map文件有发布上来，但是js.map文件中的sources里面的源文件没有发布上来。
> ![image](https://user-images.githubusercontent.com/17774285/101463236-22584100-3978-11eb-9645-a97fb2cb893e.png)
> 包下面只有esm和lib，没有src

直接在 files 中加上，欢迎来 PR~~

**Comment by YanYuanFE** [comment]
PR已提

**Comment by YanYuanFE** [comment]
老哥，@antv下面的包里面都没有把src发布出来[Emm]
