### ISSUE TITLE
针对scale[x].type=time。折线图针对连续性数据有断点数据

### ISSUE THREAD

**Issue by William-Cai** [antvis/G2#3058]
* **G2 Version**: 4.x
* **Platform**: mac 
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:https://codepen.io/William-cai/pen/wvzBZLy

x轴scale的type为time的情况下：
问题一：折线图，2020-11-20的x轴没有显示，且数据看起来是连续的
问题二：2020-11-24的黄色线是没有数据的

以上都不能体现数据的断采的效果

**Comment by zqlu** [comment]
time 类型的 scale 是连续类型的 scale， 作为折线图的 X 轴，建议使用 category 或者 timeCat
