### ISSUE TITLE
多次调用绘图函数时，每次调用都增加一个一模一样的图，上次调用的图销毁不掉

### ISSUE THREAD

**Issue by wprintstar** [antvis/G2#3061]
调用draw（）时，每次增加一个chart
draw(){
        const chartline = new Chart({
          container: 'cl',
          width: 900,
          height: 200,
        });
        const dataline = [
          { year: '41周', sales: 38 },
          { year: '42周', sales: 41 },
          { year: '43周', sales: 39 },
          { year: '44周', sales: 37 },
          { year: '45周', sales: 40 },
          { year: '46周', sales: 37 },
          { year: '47周', sales: 39 },
          { year: '48周', sales: 38 },
        ];
        chartline.data(dataline);
        chartline.scale('sales', {
          nice: true,
        });
        chartline.tooltip({
          showMarkers: false
        });
        chartline.interaction('active-region');
       
        chartline
          .line()
          .position('year*sales')
          .shape('smooth');
        chartline.area().position('year*sales').shape('smooth');
        chartline.render();

![image](https://user-images.githubusercontent.com/49421617/100695131-8c4a7680-33cb-11eb-806c-db54e20ae436.png)

**Comment by zqlu** [comment]
是有问题：draw 函数里面每次都 new 了一个charts， 需要在 draw 函数里面先把之前的 chart 销毁掉， chart.destroy

**Comment by wprintstar** [comment]
![image](https://user-images.githubusercontent.com/49421617/100834328-aad17000-34a6-11eb-8154-a1580209cbb0.png)
