### ISSUE TITLE
why id of data can't be number?

### ISSUE THREAD

**Issue by beizhedenglong** [antvis/G2#3063]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g6-ix66f)

### Steps to reproduce
just open the demo link

| Environment | Info |
|---|---|
| g2 | 4.0.2 |
| System | - |
| Browser | - |

**Comment by zqlu** [comment]
The demo provided is for G6.
