### ISSUE TITLE
legend 宽度设置不成功, itemValue 显示..., 请问如何设置，谢谢！

### ISSUE THREAD

**Issue by Bigredorange** [antvis/G2#3064]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/admiring-mestorf-5ucn0)

### Steps to reproduce
legend 宽度设置不成功, itemValue 显示..., 请问如何设置， 谢谢！

| Environment | Info |
|---|---|
| g2 | 4.0.15 |
| System | windows |
| Browser | chrome  版本 86.0.4240.111（正式版本） |

**Comment by zqlu** [comment]
是用 `maxItemWidth` 设置。
