### ISSUE TITLE
无法限制轴的最大宽度/高度

### ISSUE THREAD

**Issue by zqlu** [antvis/G2#3071]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/1142242/100820877-2cff6b80-348a-11eb-925f-56ed3bc52733.png)

**Comment by hustcc** [comment]
```ts
chart.axis('xField', {
  verticalLimitLength: 48, // 显示轴的纵向高/宽度度
});
```

![image](https://user-images.githubusercontent.com/7856674/101458211-8c211c80-3971-11eb-8d31-df070436d0a1.png)
