### ISSUE TITLE
微信PC客户端内置浏览器 使用 chart.annotation() 后整个图表无法渲染

### ISSUE THREAD

**Issue by gloomyzerg** [antvis/G2#3072]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://s0r1w.csb.app/](https://s0r1w.csb.app/)

### Steps to reproduce
将此代码保存后运行   在chrome中显示正常   在微信PC版内置浏览器中  显示空白
去除chart.annotation() 后显示正常 
调用 chart.annotation() 下所有API均会出现此问题

| Environment | Info |
|---|---|
| g2 | 4.1.0 |
| System | - |
| Browser | 微信PC浏览器 |

**Comment by hustcc** [comment]
是微信浏览器，不是微信小程序吧？希望能够给出具体的报错信息。

可能的原因：是否没有在你的业务代码中增加 babel-polyfill。

**Comment by gloomyzerg** [comment]
微信浏览器  增加babel-polyfill后已解决
