### ISSUE TITLE
设置legend属性clickable和hoverable为false，无效

### ISSUE THREAD

**Issue by isexists** [antvis/G2#3083]
* **G2 Version**:  4.x
* **代码**：

const chart = new Chart({
  container: 'container',
  autoFit: true,
  height: 500,
});

chart.data(data);
chart.legend({
  marker: {
    symbol: 'circle'
  },
  clickable: false,
  hoverable: false
});
chart.scale({
  sales: {
    max: 2400,
    tickInterval: 600,
    nice: true,
  },
});

chart.tooltip({
  showMarkers: false
});

chart
  .interval()
  .position('year*sales')
  .color('type')
  .adjust('stack');

chart.render();

**Comment by Me-Momo** [comment]
G2 4.x [升级指南](https://g2.antv.vision/zh/docs/manual/upgrade#%E9%85%8D%E7%BD%AE%E9%A1%B9%E4%BB%A5%E5%8F%8A%E6%8E%A5%E5%8F%A3%E5%8F%98%E6%9B%B4)

**Comment by yehoan** [comment]
请问 legend 怎么设置不可点击marker
