### ISSUE TITLE
g2 V4.1.1 时间条形图 无法渲染

### ISSUE THREAD

**Issue by fanlogfei** [antvis/G2#3085]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g2.gitee.io/zh/examples/bar/basic#time-bar](https://antv-g2.gitee.io/zh/examples/bar/basic#time-bar)

### Steps to reproduce
官方 网站的 时间条形图 无法 渲染；

| Environment | Info |
|---|---|
| g2 | 4.1.1 |
| System | win10 |
| Browser | 86.0.4240.193 |

**Comment by zqlu** [comment]
原因为 4.1 更改了时间类型字段的默认 scale type，可以通过直接指定字段的 scale 类型：https://codesandbox.io/s/friendly-liskov-f224s

DEMO 我这边来 PR 修复。

**Comment by fanlogfei** [comment]
好的，非常感谢！
