### ISSUE TITLE
chart.legend设置marker 为长方形

### ISSUE THREAD

**Issue by treeandgrass** [antvis/G2#3086]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
自定义图例的maker支持长方形

### What does the proposed API look like?
设置生效
chart.legend({
  custom: true,
  items: [
    {
      name: 'sasas',
      marker: {
        symbol:'square',
        style: {
          width: 30,
          height: 20
        }
      }
    }
  ]
})

**Comment by zjp123** [comment]
兄弟你这样搞可以？ style里面有width  height两个属性吗
