### ISSUE TITLE
饼图Tooltip会显示空白框

### ISSUE THREAD

**Issue by lushushu137** [antvis/G2#3088]
* **G2 Version**: 4.1.0
* **Platform**: macOS 10.15.7 
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
![image](https://user-images.githubusercontent.com/60133071/101301009-711bb300-3872-11eb-90f3-c07f7d29cc94.png)

**Comment by Me-Momo** [comment]
有复现链接吗？你的 tooltip 是怎么配置的

**Comment by lushushu137** [comment]
> 有复现链接吗？你的 tooltip 是怎么配置的

不好意思，刚看了一下，应该是BizChart的问题，配置在这里 https://bizcharts.alibaba-inc.com/gist/2AqFArO3D8Q
