### ISSUE TITLE
4.0版本如何支持自定义图例，如使用html自定义图例

### ISSUE THREAD

**Issue by mark3h** [antvis/G2#3089]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
图例滚动条展示

### What does the proposed API look like?
类似文档的useHTML方式

**Comment by zqlu** [comment]
自定义图形可以指定 legend: { custom: true, item: [ /* 自定义 items */] } 来配置； 4.x 不支持 html 图例。

**Comment by mark3h** [comment]
> 自定义图形可以指定 legend: { custom: true, item: [ /* 自定义 items */] } 来配置； 4.x 不支持 html 图例。

没有计划支持HTML图例吗

**Comment by kongkgng** [comment]
提示支持自定义，图例目前没有，搞了半天 ，一直以为自己搞错了
