### ISSUE TITLE
示例代码 与运行的代码不一致

### ISSUE THREAD

**Issue by tk231321** [antvis/g2#309]
![image](https://user-images.githubusercontent.com/19486247/34236079-acc4d572-e630-11e7-9b49-6a85313d4478.png)
https://antv.alipay.com/zh-cn/g2/3.x/tutorial/data-set.html

**Comment by leungwensen** [comment]
这个地方是因为我们 CDN 服务器不能传 csv，所以实际运行的代码不一致。你在本地按照示例代码的指示执行是没问题的。

**Comment by tk231321** [comment]
希望能在文档中着重强调一下watchingState的使用，我找了好久，着实困惑了一番
