### ISSUE TITLE
升级后Slider的start和end与展示数据不一致的bug

### ISSUE THREAD

**Issue by isexists** [antvis/G2#3090]
* **G2 Version**: 4.1.1
参考 #2847 升级到4.1.1之后，该bug仍然存在

**Comment by hustcc** [comment]
最新版本已经解决。

![image](https://user-images.githubusercontent.com/7856674/106247592-b9d86280-624a-11eb-8068-3ff64ccab04e.png)

看看是否满足你的期望。
