### ISSUE TITLE
使用addChild新增节点时新增的子节点展开但是会立马收回，重复添加则永远有一个节点不显示但是占位

### ISSUE THREAD

**Issue by Lcjcode9413** [antvis/G2#3093]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/silent-star-rpwvw?file=/index.js)

### Steps to reproduce
随意点击某个节点即可重现

| Environment | Info |
|---|---|
| g2 | 4.0.3 |
| System | win |
| Browser | chrome |

**Comment by Me-Momo** [comment]
麻烦提到 https://github.com/antvis/G6/issues
