### ISSUE TITLE
TypeError: Object.values is not a function

### ISSUE THREAD

**Issue by eomis** [antvis/G2#3094]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/antvis/G2/search?q=Object.values](https://github.com/antvis/G2/search?q=Object.values)

### Steps to reproduce
源代码中的Object.values并未进行babel转义。导致低版本浏览器报错，无法渲染

| Environment | Info |
|---|---|
| g2 | 4.1.1 |
| System | windows |
| Browser | Chrome/49.0.2623.112 |

---
建议调整babel适配级别，感谢

**Comment by hustcc** [comment]
需要在业务代码中引入 babel-polyfill。否则即使 G2 不出错，其他的一些三方库依赖也会出错的。
