### ISSUE TITLE
文档问题

### ISSUE THREAD

**Issue by luyouxin84** [antvis/G2#3096]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/case/pie#pie3](https://g2.antv.vision/zh/examples/case/pie#pie3)

### Steps to reproduce
关于传入数据，是否需要乘100，否则显示百分比有问题

| Environment | Info |
|---|---|
| g2 | 4.1.1 |
| System | - |
| Browser | - |
![image](https://user-images.githubusercontent.com/19262102/101465560-0c984b00-397b-11eb-8b24-2ef0d165e6e3.png)

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/101466468-26865d80-397c-11eb-8ef8-1a7543442e96.png)


不需要，在这里格式化成百分比的。
