### ISSUE TITLE
调用updateOptions 后  当前调用的 view 会消失

### ISSUE THREAD

**Issue by Zigei** [antvis/G2#3097]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gifted-chebyshev-b82xr?file=/src/index.js)

### Steps to reproduce
      view1.updateOptions({
        coordinate: {
          type: 'theta',
          actions: [['rotate', -Math.PI * 0.25]],
        },
      });

| Environment | Info |
|---|---|
| g2 | 4.1.1 |
| System |  macos |
| Browser | chrome 版本 86.0.4240.198（正式版本） (x86_64) |

---
想要修改 当前图表的 旋转角度  但是 调用updateOptions  和 coordinate 里面的 update 都无法满足

**Comment by hustcc** [comment]
调用之后需要执行 chart.render()

```ts
setTimeout(() => {
    view1.coordinate('theta', {
      radius: 0.7,
      startAngle: 0 + otherOffsetAngle,
      endAngle: Math.PI * 2 + otherOffsetAngle,
    }).rotate(-Math.PI * 0.25);

    chart.render()
  }, 3000);
```
