### ISSUE TITLE
设置坐标系旋转，轴标题出现镜像展示怎么解决？

### ISSUE THREAD

**Issue by pd1246** [antvis/G2#3098]
![g2ZH](https://user-images.githubusercontent.com/52770443/101593420-d6b29f80-3a2a-11eb-8abd-fb977e30c585.png)

**Comment by hustcc** [comment]
旋转的时候，轴标题也会跟着旋转，这个时候，你设置一下轴标题的 rotate 即可。上图表现是符合预期的。
