### ISSUE TITLE
Can you provide data statistics components such as [waterwave graph, progress]

### ISSUE THREAD

**Issue by hello-stranger-welcome** [antvis/G2#3100]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The function is similar to the existing [Dashboard] component

### What does the proposed API look like?
The related api can be similar to [Dashboard]

**Comment by Me-Momo** [comment]
why not to try [G2Plot](https://g2plot.antv.vision/zh/examples/) 
- G2Plot [liquid plot](https://g2plot.antv.vision/zh/examples/liquid/basic#basic)
- G2Plot [progress](https://g2plot.antv.vision/zh/examples/tiny/progress#progress)
- G2Plot [ring progress](https://g2plot.antv.vision/zh/examples/tiny/ring-progress#ring-progress)
