### ISSUE TITLE
主题的配置是否有计划支持可视化导出

### ISSUE THREAD

**Issue by hanzhangyu** [antvis/G2#3101]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以打通设计师与开发在主题配置中的壁垒

### What does the proposed API look like?
官网提供主题配置导出的能力

**Comment by visiky** [comment]
> * [x]  I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.
> 
> ### What problem does this feature solve?
> 可以打通设计师与开发在主题配置中的壁垒
> 
> ### What does the proposed API look like?
> 官网提供主题配置导出的能力

可以直接访问：https://theme-set.antv.vision
