### ISSUE TITLE
自定义布局 G6.registerLayout 中 getDefaultCfg() 不起作用. 

### ISSUE THREAD

**Issue by jxj322991** [antvis/G2#3103]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/great-fog-gnc5d)

### Steps to reproduce
重现代码上的112行 (getDefaultCfg) 不起作用.

| Environment | Info |
|---|---|
| g2 | 4.1.1 |
| System | win10 |
| Browser | chrome |

---
即使摘抄文档:
https://antv-g6.gitee.io/zh/docs/manual/middle/layout/custom-layout#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B8%83%E5%B1%80
中的代码,进行demo实验依然不起作用?
即使认为getDefaultCfg是最低优先级,里面的参数依旧不会生效,是否api已经被废弃?

demo实验:https://codesandbox.io/s/stoic-bush-i13lc?file=/index.js

**Comment by hustcc** [comment]
提错地方了。
