### ISSUE TITLE
请问Pie的图例如何才能占满画布本身的宽度呢？

### ISSUE THREAD

**Issue by wood3n** [antvis/G2#3105]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
autoFit的时候画布本身宽度其实很大，想让图例做到宽度占满画布的效果，但是itemWidth设置到一定程度以后就不生效了

![image](https://user-images.githubusercontent.com/31716713/101854930-80b23900-3b9d-11eb-90a6-669ee9b0c12b.png)

### What does the proposed API look like?
能否通过`itemWidth:'100%'`这样的配置来让`layout:'vertical'`的时候每行图例的宽度占满画布底部的区域，相关demo：
[![Edit bitter-voice-ni6cr](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bitter-voice-ni6cr?fontsize=14&hidenavigation=1&theme=dark)

**Comment by hustcc** [comment]
你需要什么效果，图例还是分三行，每一行都是沾满所有宽度，那 icon 文本 百分比怎么布局？ 均分吗？

**Comment by hustcc** [comment]
你去掉 vertical 就是下图

![Uploading image.png…]()

**Comment by wood3n** [comment]
@hustcc 对，我就是要`vertical`的效果，然后每行占满画布宽度，因为我只有三条数据，`itemName`和`itemValue`的布局类似于`justify-content: 'space-between'`那样的效果，`itemName`居左，`itemValue`居右

**Comment by hustcc** [comment]
这个确实做不到，而且也不好看啊，如果确实设计师这么设计的，可以在图表下方预留 24px，去用 html 绘制这个类似指标卡的 UI。

**Comment by wood3n** [comment]
@hustcc 那不是没交互效果了嘛 🤣🤣

**Comment by hustcc** [comment]
> @hustcc 那不是没交互效果了嘛 🤣🤣

也可以做交互效果的，自定义的图例点击后，调用 chart.filter 过滤数据即可。

**Comment by wood3n** [comment]
@hustcc 好，我试试，完了反馈给你

**Comment by wood3n** [comment]
@hustcc 你说的这个方法是这么用的吗？好像没什么效果呢，g2的文档我没找到在哪有

[![Edit bitter-voice-ni6cr](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bitter-voice-ni6cr?fontsize=14&hidenavigation=1&theme=dark)
