### ISSUE TITLE
自定义shape存在动画，resize时shape无法跟随重新绘制

### ISSUE THREAD

**Issue by Me-Momo** [antvis/G2#3111]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/8d2d202e](https://riddle.alibaba-inc.com/riddles/8d2d202e)

### Steps to reproduce
- https://riddle.alibaba-inc.com/riddles/8d2d202e resize 的时候，可以看到控制台报错且自定义shape的 point 不会跟随变化

| Environment | Info |
|---|---|
| g2 | 4.1.2 |
| System | - |
| Browser | - |

**Comment by Aircity** [comment]
+1
