### ISSUE TITLE
图表外层容器div如果设置缩放属性，如transform:scale(0.5)，图表鼠标移动上去的hover效果（tooltip）会出现偏移

### ISSUE THREAD

**Issue by paozi528** [antvis/G2#3115]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by ImagineZzf** [comment]
+1
如果在body上设置zoom: 0.83，同样会出现偏移，应该是一个原因

**Comment by machen8812** [comment]
大佬，有修复计划吗？ @zqlu

**Comment by gongtiexin** [comment]
你好，这个问题好像还是存在，官网的demo设置zoom就能复现。请问，有什么好的解决方法吗？

**Comment by hustcc** [comment]
> 你好，这个问题好像还是存在，官网的demo设置zoom就能复现。请问，有什么好的解决方法吗？

看你上面这条回复。

**Comment by gongtiexin** [comment]
> > 你好，这个问题好像还是存在，官网的demo设置zoom就能复现。请问，有什么好的解决方法吗？
> 
> 看你上面这条回复。

![Uploading image.png…]()
设置了也是无效的

**Comment by hustcc** [comment]
![Uploading image.png…]()

**Comment by gongtiexin** [comment]
![image](https://user-images.githubusercontent.com/24401876/110782808-8d305580-82a2-11eb-90e3-3a4caec6a68e.png)

**Comment by christingliu** [comment]
同样的问题设置了 supportCSSTransform:true问题依然存在。
