### ISSUE TITLE
G2 3.0中 正态分布图该如何实现

### ISSUE THREAD

**Issue by huanglong6828** [antvis/g2#312]

**Comment by leungwensen** [comment]
正太分布也就是高斯分布，可以用 DataSet 的这个 transform 来做：

https://antv.alipay.com/zh-cn/g2/3.x/api/transform.html#_kernel-smooth.density-%E6%A0%B8%E5%87%BD%E6%95%B0%E6%A6%82%E7%8E%87%E5%AF%86%E5%BA%A6%E5%88%86%E5%B8%83

图表示例：

https://antv.alipay.com/zh-cn/g2/3.x/demo/other/kernel-smooth-regression-2.html
