### ISSUE TITLE
使用autoFit属性，页面初次渲染时出现chart的横坐标溢出父容器

### ISSUE THREAD

**Issue by honey-HL** [antvis/G2#3120]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.
![image](https://user-images.githubusercontent.com/24320882/102302062-2b0dd000-3f93-11eb-9e24-4c3baaaa6350.png)

import { Chart } from '@antv/g2';

const SECOND = 1000;
const MINUTE = 1000 * 60;
const HOUR = 60 * MINUTE;
const DAY = 24 * HOUR;

function toInteger(number, fix = 1) {
  if (Math.round(number) === number) {
    return number;
  }
  return Number(number).toFixed(fix);
}

function humanizeDuration(duration, fix = 1) {
  if (duration === 0) {
    return '0';
  }
  if (duration < MINUTE) {
    return toInteger(duration / SECOND, fix) + ' 秒';
  }
  if (duration < HOUR) {
    return toInteger(duration / MINUTE, fix) + ' 分';
  }
  if (duration < DAY) {
    return toInteger(duration / HOUR, fix) + '小时';
  }
  return toInteger(duration / HOUR / 24, fix) + ' 天';
}

const data = [
  { date: 1489593600000, pv: 17, time: 12351000 },
  { date: 1489680000000, pv: 10, time: 18000 },
  { date: 1489766400000, pv: 3, time: 0 },
  { date: 1489852800000, pv: 3, time: 0 },
  { date: 1489939200000, pv: 18, time: 21157000 },
  { date: 1490025600000, pv: 32, time: 3543000 },
  { date: 1490112000000, pv: 25, time: 10000 },
  { date: 1490198400000, pv: 23, time: 24000 },
  { date: 1490284800000, pv: 7, time: 0 },
];

const chart = new Chart({
  container: 'container',
  autoFit: true,
  height: 500,
});

chart.data(data);
chart.scale({
  date: {
    alias: '日期',
    type: 'time',
  },
  pv: {
    alias: '进入次数',
    min: 0,
    sync: true, // 将 pv 字段数值同 time 字段数值进行同步
    nice: true,
  },
  time: {
    alias: '平均时长',
    formatter: (value) => {
      return humanizeDuration(value, 0);
    },
    sync: true,  // 将 pv 字段数值同 time 字段数值进行同步
    nice: true,
  },
  count: {
    alias: '次数',
  },
});

chart.axis('time', {
  grid: null,
  title: {},
});
chart.axis('pv', {
  title: {},
});

chart.tooltip({
  showCrosshairs: true,
  shared: true,
});

chart
  .line()
  .position('date*pv')
  .color('#4FAAEB');
chart
  .line()
  .position('date*time')
  .color('#9AD681')
  .shape('dash');
chart.theme({ "styleSheet": { "brandColor": "#5B8FF9", "paletteQualitative10": ["#5B8FF9", "#61DDAA", "#65789B", "#F6BD16", "#6F5EF9", "#78D3F8", "#9661BC", "#F6903D", "#008685", "#F08BB4"], "paletteQualitative20": ["#5B8FF9", "#CDDDFD", "#61DDAA", "#CDF3E4", "#65789B", "#CED4DE", "#F6BD16", "#FCEBB9", "#6F5EF9", "#D3CEFD", "#78D3F8", "#D3EEF9", "#9661BC", "#DECFEA", "#F6903D", "#FFE0C7", "#008685", "#BBDEDE", "#F08BB4", "#FFE0ED"] } });
chart.render();

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kxm37)

### Steps to reproduce
**复制上面的代码在浏览器运行**

| Environment | Info |
|---|---|
| g2 | 4.1.2 |
| System | - |
| Browser | - |

**Comment by honey-HL** [comment]
![image](https://user-images.githubusercontent.com/24320882/102301978-00237c00-3f93-11eb-857f-ca81b4f1885c.png)

**Comment by GPL1** [comment]
遇到相同问题，如何解决？

**Comment by GPL1** [comment]
页面完成后，延迟加载组件，暂时这么解决的

**Comment by hustcc** [comment]
autoFit 是监听 window.resize 事件才会触发画布的 changeSize，但是页面容器在渲染过程中，div 的 size 变化，不会触发图表 changeSize，所以导致这个问题，两个解法：

1. 在容器的宽高固定之后，手动执行一个 changeSize（不建议）
2. 不使用内置的 autoFit，而是业务层自己监听容器 div 的变化（ [size-sensor](https://github.com/hustcc/size-sensor) ），然后在变化的时候，执行 chart.forceFit() 即可

当然，你可以直接使用 G2Plot，基于 G2 封装的各种通用图表，G2Plot 使用的就是方式 2。
