### ISSUE TITLE
能否添加一个使用TypeScript编写的demo

### ISSUE THREAD

**Issue by PmcFizz** [antvis/G2#3121]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
各位大佬好， 我是TS新手，现在 在Vue， TypeScript 环境下，使用ts写法，不知道从那个文件里引入types，是有一个同一个的入口吗？ 如Data，View， ChartCfg

### What does the proposed API look like?
能够提供一个TS编写的Demo，

@simaQ  @afc163

**Comment by zqlu** [comment]
不需要额外的配置，ts 中也同样是 import { Chart }  from '@antv/g2'，类型定义会自动加上
