### ISSUE TITLE
支持跳线

### ISSUE THREAD

**Issue by hellobq** [antvis/G2#3122]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
多节点之间的连线会出现交叉情形，能支持边的类型有“跳线”吗？

### What does the proposed API look like?
type: 'jumpover'

**Comment by zqlu** [comment]
有示例吗？

**Comment by hellobq** [comment]
> 有示例吗？
类似贵公司 x6 里的跳线这种
https://x6.antv.vision/zh/examples/gallery#category-%E8%BF%9E%E7%BA%BF
![image](https://user-images.githubusercontent.com/29953650/102473750-cb96e980-4092-11eb-8817-768ef74f3374.png)

**Comment by hustcc** [comment]
要看你的具体图形场景，感觉更适合使用 x6 去做这个事情。
