### ISSUE TITLE
多个View时，能否以某个view的scale为基准？

### ISSUE THREAD

**Issue by lin2006yuo** [antvis/G2#3125]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://codesandbox.io/s/fervent-banzai-yr2vz  
多个view时，如果某个view存在脏数据，那么就会出现大片的空白。如上面的demo，经纬度[0,0]是脏数据，导致地图出现大片的空白。我想过过滤掉脏数据，但是出现新的问题是我不知道这个经纬度是否超过范围

### What does the proposed API look like?
-

**Comment by hustcc** [comment]
4.x 中提供了 scale sync 的配置，用来做 scale 的同步。

```ts
chart.scale('field', {
  sync: 'syncKey',
});
```

指定字段的 scale 中 sync 配置，这个配置为作为同步 scale 的 key / id，对于 key 相同的 scale，会同步成一个 scale 实例。
