### ISSUE TITLE
请问ScaleOption.mask 的值有哪些？

### ISSUE THREAD

**Issue by PmcFizz** [antvis/G2#3126]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
请问ScaleOption.mask 的值有哪些？

### What does the proposed API look like?
https://g2.antv.vision/zh/docs/api/general/scale#scaleoptionmask

文档应该补充mask的值

**Comment by hustcc** [comment]
### ScaleOption.mask

<description> _string_ **optional**</description>

时间度量 time, timeCat 时有效。底层使用 [fecha](https://github.com/taylorhakes/fecha#formatting-tokens) 进行日期的格式，所以对于 mask 的字符串可以直接参考其写法。
