### ISSUE TITLE
图例超出隐藏怎么取消

### ISSUE THREAD

**Issue by 766aya** [antvis/G2#3128]
图例超出隐藏怎么取消

自定义图例不行
使用itemName formatter也不行
itemValue formtter也一样不行
![image](https://user-images.githubusercontent.com/28217435/102373041-c2f2d480-3ffa-11eb-890a-98240b67b6e1.png)

**Comment by PmcFizz** [comment]
遇到同样的问题了， 请问你是怎么解决的？  还有tick 超出了 也无法隐藏

**Comment by 766aya** [comment]
> 遇到同样的问题了， 请问你是怎么解决的？ 还有tick 超出了 也无法隐藏

我还没有解决呢 只能想办法绕过 稍微改点需求 难搞哦

**Comment by PmcFizz** [comment]
难搞哦

**Comment by maplor** [comment]
我看了源码，legend controller 中有一段最大宽高的判断逻辑（ getCategoryLegendSizeCfg https://github.com/antvis/G2/blob/master/src/chart/controller/legend.ts#L538 ），而且值不能改，所以图例宽度超过 0.25图表宽度就会触发自动隐藏。。
