### ISSUE TITLE
分组柱状图混合折线图，如何把折线图的图例也显示出来？

### ISSUE THREAD

**Issue by chenxwei** [antvis/G2#3130]
![image](https://user-images.githubusercontent.com/33630555/102440448-34fb0600-405b-11eb-87a2-7d0bff622130.png)
自定义图例，拿到的是三个geom，分别是柱状图和折线和点。
如果不加color()，柱状图又不会分组。不知道怎么弄，求大神帮忙。

**Comment by PmcFizz** [comment]
不加color 是不会分组的， 好像官方设计如此， 你可以试试多个画多个柱状图，设置不同的颜色，但这样就没有图例了

**Comment by hustcc** [comment]
legend 的生成就是按照 color shape size 字段来的。没有这些字段当然不会生成图例。

另外你这个图，建议直接使用 G2Plot 封装好的双轴图，双轴图是一个业务图表，用 G2 封装本身是有不少工作量的。 DEMO 在这里：https://g2plot.antv.vision/zh/examples/dual-axes/stacked-column-line#stacked-column-multi-line

**Comment by yehoan** [comment]
请问你怎么做成分组柱状图+折线图得组合得

**Comment by hustcc** [comment]
- G2

```ts
// 分组柱形图
v1 = chart.view()
v1.interval().position()...

// 折线图

v2 = chart.view()
v2.line().position()...
```

- G2Plot

```ts
const duax = new DuaxAxis()
```

**Comment by yehoan** [comment]
你这个是只能做一条的折线图 如果有需求是这样的呢  
![image](https://user-images.githubusercontent.com/22631753/142833440-b5a72886-6876-4e38-98b7-046dd4e21e7b.png)
这个怎么每一个柱状图都做一个线条呢
