### ISSUE TITLE
Area根据G2生成的颜色设置渐变

### ISSUE THREAD

**Issue by mark3h** [antvis/G2#3134]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望根据G2分配好的颜色，设置渐变，不需要考虑设置渐变时的颜色

### What does the proposed API look like?
.position('x*y'),color('type', () => {return ${color}})

**Comment by PmcFizz** [comment]
你好，我也遇到了这个问题，如果一个图表由多个图例，area的颜色值只能用 一个值来表示.这个问题能否通过画多个区域来解决啊？
比如这样

```js
chart.area()
      .position('x*y1')
      .color('l(100) 0:#206EF7FF 1:#206EF700')
      
chart.area()
      .position('x*y2')
      .color('l(100) 0:#206EF7FF 1:#206EF700')
```

但这样写了之后就不存在图例了

**Comment by hustcc** [comment]
```ts
chart.area()
      .position('x*y2')
      .color('type')
      .style('type', (type) => {
         return { fill: 'xxxx' };
      })
```

**Comment by mark3h** [comment]
能否在回调中获取到分配的颜色?

**Comment by PmcFizz** [comment]
> 能否在回调中获取到分配的颜色?

可以在回调里设置颜色， 你要获取颜色干嘛？ .color('type'，['206EF7FF', '206EF700'] ) 在color函数里，可以指定颜色，根据type的属性来匹配的

**Comment by mark3h** [comment]
> > 能否在回调中获取到分配的颜色?
> 
> 可以在回调里设置颜色， 你要获取颜色干嘛？ .color('type'，['206EF7FF', '206EF700'] ) 在color函数里，可以指定颜色，根据type的属性来匹配的

因为设置渐变的语法是这样的
 .color('l(100) 0:#206EF7FF 1:#206EF700')

我希望根据分配的颜色，设置统一的渐变色，也就是下面的方式

 .color('l(100) 0:${color}1:#fff')

**Comment by Me-Momo** [comment]
颜色和主题的颜色是一致的；主题颜色从 chart.getTheme()获取；官网搜索下 colors10，colors20 介绍

**Comment by mark3h** [comment]
> 颜色和主题的颜色是一致的，按顺序取色；主题颜色从 chart.getTheme()获取；官网搜索下 colors10，colors20 介绍

好的，内部规则是不是如下方式：
图例数< 10，则获取colors10分配
图例数>=10，则获取colors20
