### ISSUE TITLE
g2 在Bar图中，当数值较低时如何设置柱子的最小高度

### ISSUE THREAD

**Issue by YC725968** [antvis/G2#3138]
### What problem does this feature solve?
g2 在Bar图中，当数值较低时如何设置柱子的最小高度

### What does the proposed API look like?
g2 在Bar图中，当数值较低时如何设置柱子的最小高度

**Comment by hustcc** [comment]
不符合数据准确性的原则，如果确实要这么做，可以修改数据大小，然后对于 label、tooltip 等 formater 成实际的数据。

**Comment by jxj666** [comment]
这样是可以但是毕竟数据被改变了,再计算坐标轴的时候很有可能出错
