### ISSUE TITLE
饼形图有三个维度选择时，有一个维度的数据为空，点击另外两个维度会将数据显示到为空的维度内

### ISSUE THREAD

**Issue by chengzl** [antvis/g2#314]
Version

3.0.2

Environment

win7,google,v6.9.5

Reproduction link

[https://preview.pro.ant.design/#/dashboard/analysis)

Steps to reproduce

将“销售额类别占比”中“全部渠道”的数据设置为空，然后刷新，点击“线上”或“门店”再点击“全部渠道”，发现本为空的数据，会把“线上”或“门店”的数据显示到“全部渠道”中

What is expected?

为空就显示空，不应受其他维度的影响

What is actually happening?

为空的维度里会显示其他维度中的图形

**Comment by leungwensen** [comment]
你这个是使用 antd-pro 时遇到的问题？没有 G2 相关的代码我复现不出来。请提供具体的可执行代码。

**Comment by leungwensen** [comment]
如果是 antd-pro 的问题，请把 issue 转到 https://github.com/ant-design/ant-design-pro/issues 。他们下周会发布 1.0，底层图表的实现会替换掉，可以升级试试看。

**Comment by chengzl** [comment]
@leungwensen 是用的antd-pro

**Comment by chengzl** [comment]
@leungwensen 用antd-pro官方提供的模板也会这样，已在antd-pro中提了这问题，有人建议我到g2来寻求帮助

**Comment by nikogu** [comment]
@chengzl 那个数据是假的。。。。你自己看看 mock 的数据就好，然后自己也可以换成自己的数据。三个图表是没有关联关系的。你可以每次把数据打出来看看，图表的展示跟数据是一样的。

**Comment by chengzl** [comment]
@nikogu官方例子和我自己项目都有这问题，能加Q帮忙看下吗？
