### ISSUE TITLE
麻烦，把墨者学院里面的带两个纵坐标轴的Demo发一下看看，谢谢

### ISSUE THREAD

**Issue by wxmdsh** [antvis/g2#315]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by leungwensen** [comment]
请问具体是哪个图？

**Comment by wxmdsh** [comment]
![image](https://user-images.githubusercontent.com/33385371/34249843-13b9560a-e676-11e7-88ab-22d8fca46d82.png)

**Comment by leungwensen** [comment]
如果是一份数据，可以参考这个： https://antv.alipay.com/zh-cn/g2/3.x/tutorial/fqas.html#_%E5%A6%82%E4%BD%95%E7%BB%98%E5%88%B6%E5%A4%9A-y-%E8%BD%B4%E5%9B%BE%E8%A1%A8

**Comment by leungwensen** [comment]
这是哪个 url 里的图？看样子页面里直接有代码的。

**Comment by wxmdsh** [comment]
墨者学院那的呀，好的  我看看你的链接，谢谢了，看不到代码的

**Comment by leungwensen** [comment]
view-source:https://antv.alipay.com/zh-cn/vis/chart/line.html

右键“显示网页源代码”，在第 8 行开始。
