### ISSUE TITLE
漏斗图 labelLine 不显示

### ISSUE THREAD

**Issue by xierenyuan** [antvis/G2#3151]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2-v4.antv.vision/zh/examples/funnel/funnel#basic](https://g2-v4.antv.vision/zh/examples/funnel/funnel#basic)

### Steps to reproduce
官网列子即可复现 老的版本是显示的 详见 https://g2-v3.antv.vision/zh/examples/funnel/funnel

| Environment | Info |
|---|---|
| g2 | 4.1.4 |
| System | - |
| Browser | - |

**Comment by jefferyssy** [comment]
遇到相同的问题

**Comment by tywei90** [comment]
+1 求尽快修复

**Comment by yearPassYear** [comment]
+1 求尽快修复

**Comment by suntiger035** [comment]
到现在还没修复，求尽快修复

**Comment by AnnaAllen** [comment]
麻烦修复一下。 都到了2023年了

**Comment by hustcc** [comment]
rel: https://github.com/antvis/G2/issues/3151
