### ISSUE TITLE
饼图matrix动画不正常缩放问题 (有没有好兄弟帮忙看一看）

### ISSUE THREAD

**Issue by Break-2020** [antvis/G2#3153]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/case/pie#pie3](https://g2.antv.vision/zh/examples/case/pie#pie3)

### Steps to reproduce
问题是这样的：我在饼图设置了点击shape会旋转的这么一个功能，是用的matrix做动画，但是在旋转过程中，饼图会有一个缩放（非预期），现在想解决这个问题，让它保持原比例进行旋转
在demo中，往render前加了一段代码（在底下，element:click这段），用来点击饼图后实现shapes的旋转
可以直接复制我底下这段代码到官方demo里面来复现这个问题

现在的想要的是希望饼图保持原比例进行旋转，想问一下是什么原因导致的

```
chart.on('element:click', (event) => {
    let coordinate = chart.getCoordinate();
    let center = coordinate.getCenter();
    let shapes = [];
    let geoms = chart.geometries;
    for(let geom of geoms){
          let elements = geom.getElementsBy(()=>true);
          for(let element of elements){
              shapes.push(element.shape);
          }
    }
    let promises = [];
    for(let shape of shapes){
        let matrix = shape.getMatrix();
        let newMatrix = Util.transform(matrix, [
            ['t', -center.x, -center.y],
            ['r', -360/10],
            ['t', center.x, center.y],
        ]);

        let promise = new Promise((resolve)=>{
            shape.animate({
                matrix: newMatrix,
            }, 1000, "easeQuadInOut", resolve, 10);
        });
        promises.push(promise);
    }
    Promise.all(promises)
})

```

| Environment | Info |
|---|---|
| g2 | 4.1.4 |
| System | win10 |
| Browser | chrome 87.0.4280.88（正式版本） （64 位） |

**Comment by hustcc** [comment]
建议这个的做法是这个区设置 Coordinate 的 start 和 end。加上一下代码：

```ts
setTimeout(() => {
  chart.coordinate('theta', {
    radius: 0.75,
    startAngle: 0,
    endAngle: 2*Math.PI
  });

  chart.render(true);
}, 1000)
```

当然在 theta 的动画效果不是很好，建议暂时关闭动画。
