### ISSUE TITLE
组合图表legend显示异常

### ISSUE THREAD

**Issue by jzyzxx** [antvis/G2#3154]
核心代码:
```
const data = [
            { name: '累计投资', 月份: 'Jan.', value: 18.9 },
            { name: '累计投资', 月份: 'Feb.', value: 28.8 },
            { name: '累计投资', 月份: 'Mar.', value: 39.3 },
            { name: '累计投资', 月份: 'Apr.', value: 81.4 },
            { name: '累计投资', 月份: 'May', value: 47 },
            { name: '累计投资', 月份: 'Jun.', value: 20.3 },
            { name: '累计投资', 月份: 'Jul.', value: 24 },
            { name: '累计投资', 月份: 'Aug.', value: 35.6 },
            { name: '累计支付', 月份: 'Jan.', value: 10.4 },
            { name: '累计支付', 月份: 'Feb.', value: 23.2 },
            { name: '累计支付', 月份: 'Mar.', value: 34.5 },
            { name: '累计支付', 月份: 'Apr.', value: 99.7 },
            { name: '累计支付', 月份: 'May', value: 52.6 },
            { name: '累计支付', 月份: 'Jun.', value: 35.5 },
            { name: '累计支付', 月份: 'Jul.', value: 37.4 },
            { name: '累计支付', 月份: 'Aug.', value: 42.4 },
            { name: '投资计划', 月份: 'Jan.', value: 15.4 },
            { name: '投资计划', 月份: 'Feb.', value: 21.2 },
            { name: '投资计划', 月份: 'Mar.', value: 39.5 },
            { name: '投资计划', 月份: 'Apr.', value: 89.7 },
            { name: '投资计划', 月份: 'May', value: 42.6 },
            { name: '投资计划', 月份: 'Jun.', value: 35.5 },
            { name: '投资计划', 月份: 'Jul.', value: 57.4 },
            { name: '投资计划', 月份: 'Aug.', value: 32.4 },
            { name: '实际支付', 月份: 'Jan.', value: 25.4 },
            { name: '实际支付', 月份: 'Feb.', value: 24.2 },
            { name: '实际支付', 月份: 'Mar.', value: 29.5 },
            { name: '实际支付', 月份: 'Apr.', value: 79.7 },
            { name: '实际支付', 月份: 'May', value: 46.6 },
            { name: '实际支付', 月份: 'Jun.', value: 32.5 },
            { name: '实际支付', 月份: 'Jul.', value: 59.4 },
            { name: '实际支付', 月份: 'Aug.', value: 35.4 },
            { name: '施工图预算', 月份: 'Jan.', value: 15.4 },
            { name: '施工图预算', 月份: 'Feb.', value: 34.2 },
            { name: '施工图预算', 月份: 'Mar.', value: 59.5 },
            { name: '施工图预算', 月份: 'Apr.', value: 49.7 },
            { name: '施工图预算', 月份: 'May', value: 66.6 },
            { name: '施工图预算', 月份: 'Jun.', value: 42.5 },
            { name: '施工图预算', 月份: 'Jul.', value: 79.4 },
            { name: '施工图预算', 月份: 'Aug.', value: 45.4 },
        ];

        const chart = new Chart({
            container: 'chart3',
            autoFit: true,
            height: 500,
        });
        chart.scale('value', {
            nice: true,
        });
        chart.tooltip({
            showMarkers: false,
            shared: true,
        });
        const dv1 = new DataSet.DataView().source(data);
        dv1.transform({
            type: 'filter',
            callback(row) {
                return row.name == "投资计划" || row.name == "实际支付";
            },
        });
        const view1 = chart.createView();
        view1.data(dv1.rows);
        view1
            .interval()
            .position('月份*value')
            .color('name')
            .adjust([
                {
                    type: 'dodge',
                    marginRatio: 0,
                },
            ]);
            view1.legend("name")
        const dv2 = new DataSet.DataView().source(data);
        dv2.transform({
            type: 'filter',
            callback(row) {
                return row.name != "投资计划" && row.name != "实际支付";
            },
        });
        const view2 = chart.createView();
        view2.data(dv2.rows)
        view2
            .line()
            .position('月份*value')
            .color('name')
            view2.legend("name")
        chart.interaction('active-region');

        chart.render();
```
![1608715027(1)](https://user-images.githubusercontent.com/24405119/102980567-bc0c1a80-4542-11eb-86f3-73d48df1ab5e.jpg)

**Comment by jzyzxx** [comment]
主要问题有两个:1.筛选异常,2.图例缺失

**Comment by hustcc** [comment]
建议直接使用 G2Plot 封装好的双轴图，这个图使用 G2 去做的时候，在图例上还是需要做不少事情的。DEMO 在这里： https://g2plot.antv.vision/zh/examples/dual-axes/stacked-column-line#stacked-column-multi-line

**Comment by Kelier** [comment]
> 建议直接使用 G2Plot 封装好的双轴图，这个图使用 G2 去做的时候，在图例上还是需要做不少事情的。DEMO 在这里： https://g2plot.antv.vision/zh/examples/dual-axes/stacked-column-line#stacked-column-multi-line
> 
> 而这个问题不能算是 G2 的 bug，G2 层对复合图表，因为考虑的要很多，所以很难做到直接就体验优秀。

感觉不能这样定性吧，这样G2和Plot就是混合着用了，两套api，感觉很混乱

**Comment by visiky** [comment]
> > 建议直接使用 G2Plot 封装好的双轴图，这个图使用 G2 去做的时候，在图例上还是需要做不少事情的。DEMO 在这里： https://g2plot.antv.vision/zh/examples/dual-axes/stacked-column-line#stacked-column-multi-line
> > 而这个问题不能算是 G2 的 bug，G2 层对复合图表，因为考虑的要很多，所以很难做到直接就体验优秀。
> 
> 感觉不能这样定性吧，这样G2和Plot就是混合着用了，两套api，感觉很混乱

如果业务上实际需要用到 G2, 又不想 G2、G2Plot 混合使用的话，有两种方案：
1、完全使用 G2，对于这些体验问题，可以自己在业务层参考 G2Plot 处理混合图例的方式去实现
2、完全使用 G2Plot，对于 G2Plot 没有内置的图表，考虑使用[自定义机制](https://g2plot.antv.vision/zh/docs/manual/plugin/) 去绘制一个图表，保持同样的 API。

**Comment by visiky** [comment]
> 主要问题有两个:1.筛选异常,2.图例缺失

**问题 1:**

view1, view2 的分类 color 字段，不要使用同一个字段 key 值，作如下转换:
```
view2.data(dv2.rows.map(d => ({ ...d, name1: d.name, })));
view2.line().position('月份*value').color('name1');
view1.legend('name1');
```

**问题2**
1、移除 chart 默认的图例筛选交互
```
chart.removeInteraction('legend-filter');
```
2、自定义图例点击事件监听和筛选；参考 G2Plot 处理（取到具体的 view，调用 view.filter ）

**Comment by Kelier** [comment]
> > 主要问题有两个:1.筛选异常,2.图例缺失
> 
> **问题 1:**
> 
> view1, view2 的分类 color 字段，不要使用同一个字段 key 值，作如下转换:
> 
> ```
> view2.data(dv2.rows.map(d => ({ ...d, name1: d.name, })));
> view2.line().position('月份*value').color('name1');
> view1.legend('name1');
> ```
> 
> **问题2**
> 1、移除 chart 默认的图例筛选交互
> 
> ```
> chart.removeInteraction('legend-filter');
> ```
> 
> 2、自定义图例点击事件监听和筛选；参考 G2Plot 处理（取到具体的 view，调用 view.filter ）



> > > 建议直接使用 G2Plot 封装好的双轴图，这个图使用 G2 去做的时候，在图例上还是需要做不少事情的。DEMO 在这里： https://g2plot.antv.vision/zh/examples/dual-axes/stacked-column-line#stacked-column-multi-line
> > > 而这个问题不能算是 G2 的 bug，G2 层对复合图表，因为考虑的要很多，所以很难做到直接就体验优秀。
> > 
> > 
> > 感觉不能这样定性吧，这样G2和Plot就是混合着用了，两套api，感觉很混乱
> 
> 如果业务上实际需要用到 G2, 又不想 G2、G2Plot 混合使用的话，有两种方案：
> 1、完全使用 G2，对于这些体验问题，可以自己在业务层参考 G2Plot 处理混合图例的方式去实现
> 2、完全使用 G2Plot，对于 G2Plot 没有内置的图表，考虑使用[自定义机制](https://g2plot.antv.vision/zh/docs/manual/plugin/) 去绘制一个图表，保持同样的 API。

那我想问问G2Plot现在支持多图层分别不同的legend么？

**Comment by darkleaf** [comment]
@hustcc did you say about this code in g2plot? https://github.com/antvis/G2plot/blob/master/src/plots/dual-axes/adaptor.ts#L352-L420
I guess this code merges two legends into a single one, doesn't it?

Do you have plans to add the merging-legends feature to the G2 project?
