### ISSUE TITLE
slider配合regionFilter使用出现问题

### ISSUE THREAD

**Issue by IMLaoJI** [antvis/G2#3155]
* **G2 Version**:
4.1.1
* **Platform**:
windows chrome84
* **Mini Showcase(like screenshots)**:

![image](https://user-images.githubusercontent.com/16029951/102980982-54a29a80-4543-11eb-8c7d-6794588f2103.png)

![image](https://user-images.githubusercontent.com/16029951/102980965-4e142300-4543-11eb-9305-7f038ec66a42.png)

* **CodePen Link**:

如上图，我使用slider配合regionFilter使用过程中，发现我在拖动slider时，regionFilter区域出现问题，稍等手动在拖动一点(start、end不变)就恢复了 请问是bug还是使用问题

**Comment by hustcc** [comment]
最新版本已经修复， demo 请看： https://g2.antv.vision/zh/examples/case/line#line8
