### ISSUE TITLE
双y轴的情况下 view-zoom缩放对右y轴不起作用

### ISSUE THREAD

**Issue by xiaolongGitHub1498** [antvis/G2#3157]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/line/basic#double-y-axes](https://g2.antv.vision/zh/examples/line/basic#double-y-axes)

双y轴的情况下 view-zoom缩放, drag-move拖拽, brush选框对右y轴不起作用
是不是interaction交互对右y都不起作用?

| Environment | Info |
|---|---|
| g2 | 4.1.4 |
| System | MacOS Big Sur 11.1 |
| Browser | Google Chrom 87.0.4280.67 |

**Comment by bancangyanyu** [comment]
借楼也问个问题：双y轴的情况下，scale中设置 tickCount 也不生效

**Comment by bhabgs** [comment]
高通，你把y轴 设置成number 类型， 就好了

**Comment by xiaolongGitHub1498** [comment]
已解决 自定义action继承transform类并重写getScale方法 默认只处理了一条轴的

**Comment by yehoan** [comment]
双X轴怎么处理

**Comment by yehoan** [comment]
用过双X轴嘛
