### ISSUE TITLE
Module '"../../scale/lib"' has no exported member 'Tick'.

### ISSUE THREAD

**Issue by aisujian** [antvis/G2#3158]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/antvis/G2](https://github.com/antvis/G2)

### Steps to reproduce
This error will appear in @antv/g2/lib/dependents.d.ts.

Module '"../../scale/lib"' has no exported member 'Tick'.

export { getScale, registerScale, Scale, ScaleConfig, Tick } from '@antv/scale';

The reason is that { Tick } is not imported

| Environment | Info |
|---|---|
| g2 | 4.1.4 |
| System | macos 11.1 |
| Browser | chrome  87.0.4280.88 |

**Comment by aisujian** [comment]
![image](https://user-images.githubusercontent.com/33425635/103058881-5bcab680-45de-11eb-8356-1c8b2b2d6bab.png)
![image](https://user-images.githubusercontent.com/33425635/103058904-70a74a00-45de-11eb-9a6d-4383b3998c89.png)
![image](https://user-images.githubusercontent.com/33425635/103058913-7735c180-45de-11eb-89b9-5623d87d2ffc.png)

**Comment by hustcc** [comment]
upgrade @antv/scale module to latest version.
