### ISSUE TITLE
仪表盘在 iOS 微信上打开有问题

### ISSUE THREAD

**Issue by jinzhanye** [antvis/G2#3161]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/gauge/gauge#basic](https://g2.antv.vision/zh/examples/gauge/gauge#basic)

### Steps to reproduce
随便用一台苹果手机，微信扫码以下页面，打开后会出现仪表盘缺角的情况。
https://g2.antv.vision/zh/examples/gauge/gauge#basic

| Environment | Info |
|---|---|
| g2 | 4.1.4 |
| System | - |
| Browser | - |

---
我自己的 APP 用的是 X5 内核与微信浏览器是同样内核，也遇到同样的问题。
https://x5.tencent.com/

**Comment by hustcc** [comment]
ref https://github.com/antvis/G2/issues/3186
