### ISSUE TITLE
g2 中国地图 南海 九段线怎么展示的呢？

### ISSUE THREAD

**Issue by 120011676** [antvis/G2#3163]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/gallery#category-%E5%9C%B0%E5%9B%BE](https://g2.antv.vision/zh/examples/gallery#category-%E5%9C%B0%E5%9B%BE)

### Steps to reproduce
g2地图 南海 九段线怎么展示的呢？

| Environment | Info |
|---|---|
| g2 | 4.1.4 |
| System | - |
| Browser | - |

![image](https://user-images.githubusercontent.com/1992933/103131019-083d9300-46da-11eb-8d28-e716a6dfab94.png)

想要下图方式的
![image](https://user-images.githubusercontent.com/1992933/103131681-ad596b00-46dc-11eb-821c-4bfe24217a66.png)

**Comment by maplor** [comment]
我自己的方法是放一个南海诸岛的svg图形。
可以到自然资源部的网站下载标准中国行政区划的矢量图，将里面南海诸岛部分导出为svg

**Comment by 120011676** [comment]
@maplor 嗯嗯，在找找更好的方式
