### ISSUE TITLE
4.x 设置 自定义图例需要通过 cutom 和 items 进行设置， 后续自定义图例的默认 filter 会失效。

### ISSUE THREAD

**Issue by Cccccl** [antvis/G2#3164]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/interaction/component#legend-visible-filter](https://g2.antv.vision/zh/examples/interaction/component#legend-visible-filter)

### Steps to reproduce
```
添加 chart.legend 的代码
chart.legend({
  position: 'top',
  custom: true,
  items: [{
   name: '测试',
   marker: {
     symbol: 'square',
   }
  }
  ]
})

自定义图例需要通过 cutom 和 items 进行设置， 后续自定义图例的默认 filter 会失效。
```

| Environment | Info |
|---|---|
| g2 | 4.1.4 |
| System | mac |
| Browser | 谷歌浏览器 |

---
4.x 设置自定义图例需要通过 cutom 和 items 进行设置， 后续自定义图例的默认 filter 会失效。

**Comment by maplor** [comment]
我自己测了一下，开启 custom 为 true 后确实无效了，即使补全了 items 所需的属性：
```
chart.legend({
  position: 'top',
  // 关闭 custom 后效果正常
  // custom: true,
  items: [{
   id: 'London',
   name: 'London',
   value: 'London',
   unchecked: false,
   marker: {
     symbol: 'square',
   }
  },
  {
   id: 'Tokyo',
   name: 'Tokyo',
   value: 'Tokyo',
   unchecked: false,
   marker: {
     symbol: 'square',
   }
  }]
});
```

**Comment by hustcc** [comment]
是指默认的 unchecked 状态吧？

**Comment by maplor** [comment]
> 是指默认的 unchecked 状态吧？

图例的unchecked状态无法切换，data filter 也失效。

**Comment by visiky** [comment]
自定义图例，需要通过监听事件来自行处理 filter 行为；关于图例事件监听，搜索文档 API 中的 **事件**

**Comment by visiky** [comment]
Duplicate #3182

**Comment by bin-sun** [comment]
能否在demo里写一个例子示范下啊，api中的事件文档也不全，一概而略
