### ISSUE TITLE
显示自定义坐标轴（范围以及格式），并且在数据为空数组时，坐标轴每个刻度位置不会重叠

### ISSUE THREAD

**Issue by cai-zhuo** [antvis/G2#3166]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
对坐标轴进行自定义渲染

### What does the proposed API look like?
显示自定义坐标轴（范围以及格式），并且在数据为空数组时，坐标轴每个刻度位置不会重叠

**Comment by hustcc** [comment]
请具体描述你的场景和问题，不然很难作答。尝试猜测你的意图是进行自定义的 tick 计算方法。

```ts
chart.scale('xField', {
  tickMethod: (sc: ScaleConfig) => any[]; // 返回 ticks 的数组即可
});
```
