### ISSUE TITLE
label在autoRotate的情况下在一些宽度下无法正常旋转

### ISSUE THREAD

**Issue by KedAyAyA** [antvis/G2#3167]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/case/line#line7](https://g2.antv.vision/zh/examples/case/line#line7)

### Steps to reproduce
label设置为autoRotate

```ts
 chart.axis('Date', {
      label: {
        formatter: text => {
          const dataStrings = text.split('.');
          return dataStrings[2]   '-'   dataStrings[1]   '-'   dataStrings[0];
        },
        autoHide: true,
        autoRotate: true,
      }
    });
```

#container宽度为619px

| Environment | Info |
|---|---|
| g2 | 4.1.4 |
| System | mac |
| Browser | chrome latest |

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/103623005-70aa3100-4f72-11eb-999b-afb510aee22e.png)

autoRotate 只有在宽度不够 axis label 显示的时候，才会去自动 rotate。

**Comment by KedAyAyA** [comment]
![image](https://user-images.githubusercontent.com/25747437/105123757-9bb88700-5b13-11eb-96b2-21af6a72f840.png)
抱歉描述不是很清楚，如上图所示在坐标轴判断刚好可以旋转的状态下 这个旋转是有问题的，会遮挡。这个在3.x时代也有这个现象。

**Comment by donglegend** [comment]
> ![image](https://user-images.githubusercontent.com/25747437/105123757-9bb88700-5b13-11eb-96b2-21af6a72f840.png)
> 抱歉描述不是很清楚，如上图所示在坐标轴判断刚好可以旋转的状态下 这个旋转是有问题的，会遮挡。这个在3.x时代也有这个现象。

遇到同样的问题，在某个size上，旋转之后，刚好无法容纳label展示，被遮挡了

**Comment by Arco1ris** [comment]
所以这个问题解决了吗，遇到了同样了问题

**Comment by visiky** [comment]
添加下：axis: { verticalLimitLength: 20 } 这样子

**Comment by weber-cd** [comment]
现在问题依然存在，设置了verticalLimitLength也没有作用
