### ISSUE TITLE
鼠标滚动后，Legend高亮效果依然存在

### ISSUE THREAD

**Issue by Aiyanahy** [antvis/G2#3168]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g2.gitee.io/zh/examples/interaction/component#legend-highlight](https://antv-g2.gitee.io/zh/examples/interaction/component#legend-highlight)

### Steps to reproduce
1、鼠标悬浮在某个legend上，悬浮效果正常展现；
2、鼠标直接滚动，此时legend悬浮还在，

| Environment | Info |
|---|---|
| g2 | 4.1.1 |
| System | - |
| Browser | - |

---
鼠标滚动后按理应该恢复图表默认展示

**Comment by hustcc** [comment]
@Aiyanahy 具体怎么复现？ 在什么情况下滚动鼠标？

**Comment by Aiyanahy** [comment]
复现需要在界面可以滚动的前提下，鼠标悬浮在某个图例上，然后直接滚动当前界面。如录屏所示。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "antvis/G2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月5日(星期二) 下午4:19
收件人:&nbsp;"antvis/G2"<G2@noreply.github.com&gt;;
抄送:&nbsp;"Aiyana"<924319132@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [antvis/G2] 鼠标滚动后，Legend高亮效果依然存在 (#3168)





 
@Aiyanahy 具体怎么复现？ 在什么情况下滚动鼠标？

**Comment by maplor** [comment]
我猜是说：
1、鼠标hover到legend上，触发高亮效果
2、此时不移动鼠标，上下滚动。即使滚动后鼠标移出legend，高亮效果和鼠标手型会一直存在。

这个是 interaction 的配置导致的吧，只绑定了 legend-item:mouseleave，没有处理滚动事件。如果对这个很看重，可以覆盖默认的 legend-highlight 这个 interaction，自己加额外的处理逻辑。
