### ISSUE TITLE
PathCommand 有没有示例？或者外链的文档？

### ISSUE THREAD

**Issue by sjmlsxp** [antvis/G2#3169]
文档地址： https://g2.antv.vision/zh/docs/api/general/legend/#markersymbol-1
里面关于marker.symbol：
> 回调的方式为：(x: number, y: number, r: number) => PathCommand；

这个PathCommand不知道是什么，能不能给的资料？

**Comment by hustcc** [comment]
暂时文档没有透出这个，可以这么理解这个 PathCommand：

1. PathCommand 是用来描述一个 svg path 的
2. 将 path string 转为成二维数组
3. 举个例子：

```ts
const path = 'M 100 100 L 200 200';

// 对应的 PathCommand 就是
const pm = [
  ['M', 100, 100],
  ['L', 200, 200],
];
```
