### ISSUE TITLE
有没有办法去掉饼图高亮时的黑色边框？

### ISSUE THREAD

**Issue by chenkai0520** [antvis/G2#3178]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://s3.ax1x.com/2021/01/06/sEnkgf.png](https://s3.ax1x.com/2021/01/06/sEnkgf.png)

### Steps to reproduce
![https://s3.ax1x.com/2021/01/06/sEnkgf.png]( https://s3.ax1x.com/2021/01/06/sEnkgf.png)
| Environment | Info |
|---|---|
| g2 | 4.1.4 |
| System | macos |
| Browser | chrome |

**Comment by woody-li** [comment]
为什么close这个问题呢，这个黑框真的不是很好看，还是喜欢之前3.x版本的hover高亮样式。

**Comment by visiky** [comment]
我影响有类似 issue，有解决方案了

**Comment by woody-li** [comment]
@chenkai0520 非常感谢，我是这么改的
```javascript
chart.state({
  active: {
    style: {
      'lineWidth': 0,
    }
  }
});
```

**Comment by AnzhiZhang** [comment]
设置 `lineWidth: 0` 之后，会有一个出现边框再渐变消失的情况，如果按照 #3185 设置与背景相同的颜色，未免太不优雅，是否有更好的解决方案呢？
