### ISSUE TITLE
viser 使用滑动条的时候报错

### ISSUE THREAD

**Issue by MiaoJianxue** [antvis/G2#3179]
viser 使用滑动条的时候报 Type error:converting circur struture to JSON的问题，不知道怎么解决，不知道有没有遇到类似问题的

**Comment by MiaoJianxue** [comment]
https://viserjs.github.io/demo.html#/viser/event/rainfall-traffic-contrast
viser的示例代码也报错
![image](https://user-images.githubusercontent.com/23316362/103965680-3a9ac600-5199-11eb-87ee-991033d7403c.png)

**Comment by hustcc** [comment]
请使用 G2 或者 G2Plot，viser 不确定具体的版本和问题。

**Comment by hustcc** [comment]
@MiaoJianxue 从报错来看，大概率是 viser 中在对配置进行比较是否更新，然后用到 JSON.stringify，然后这个 配置中又存在循环的引用，所以报错。建议去 viser 提 issue。
