### ISSUE TITLE
滚动条怎么样自定义样式？

### ISSUE THREAD

**Issue by BigBigger** [antvis/G2#3184]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://g2.antv.vision/zh/docs/api/general/scrollbar
默认颜色只适合在白色背景下，其它主题怎么改变滚动条的颜色呢？

### What does the proposed API look like?
文档内并没有找打如何自定义配置样式，希望可以自定义颜色之类的。

**Comment by Demian1996** [comment]
![image](https://user-images.githubusercontent.com/21359263/103879175-776faa00-5112-11eb-98c6-df015049b6f6.png)
源码里看到有取slider的主题色，所以我之前的做法是覆盖slider的主题色做的。
```js
new Chart({
  theme: {
    components: {
      slider: {
        common: {
          theme: {
            default: {
              thumbColor: 'rgba(255,255,255,0.3)',
              size: 8,
              lineCap: 'round',
            },
            hover: {
              thumbColor: 'rgba(255,255,255,0.4)',
            },
          },
        },
      },
    },
  },
})
```
