### ISSUE TITLE
鼠标hover 柱状图有黑边 chart.interaction('element-active')

### ISSUE THREAD

**Issue by JavaScriptam** [antvis/G2#3185]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/case/column#column2](https://g2.antv.vision/zh/examples/case/column#column2)

### Steps to reproduce
鼠标hover到柱子上之后 有黑边。这个是专门内置的动画吗。感觉看起来很粗糙啊

| Environment | Info |
|---|---|
| g2 | 4.1.5 |
| System | macos big sur |
| Browser | 版本 87.0.4280.88（正式版本） (x86_64) |

**Comment by JavaScriptam** [comment]
浏览器 是chrome 版本 87.0.4280.88（正式版本） (x86_64)

**Comment by JavaScriptam** [comment]
![image](https://user-images.githubusercontent.com/25917806/103891071-2799de80-5124-11eb-964d-db2d0cb1723b.png)
为啥会有这么突兀的黑边

**Comment by maplor** [comment]
对，这个是内置 active 的样式效果。。。可以在配置中改掉。

**Comment by JavaScriptam** [comment]
@maplor  兄弟 怎么在配置中改。要重新注册 action么。通过他们的 registerInteraction registerAction 这种方法给改吗？有相对快捷的方式么

**Comment by JavaScriptam** [comment]
chart
  .interval()
  .position('year*value')
  .state({
    selected: {
      style: {
        fill: 'yellow',
      }
    }
  });

chart.interaction('element-selected');
用了这种方式实现了

**Comment by blackhu** [comment]
`.state({
                active: {
                  style: {
                    stroke: '#eee',
                    lineWidth: 1
                  }
                }
              })`


难道hover的状态，改变黑色描边属性 不应该是这么配置么

**Comment by AnzhiZhang** [comment]
设置 `lineWidth: 0` 之后

> `.state({ active: { style: { stroke: '#eee', lineWidth: 1 } } })`
> 
> 难道hover的状态，改变黑色描边属性 不应该是这么配置么

这仍然没有删掉边框，只是改为了和背景一样的颜色
