### ISSUE TITLE
请问在哪里能看到浏览器版本兼容性说明

### ISSUE THREAD

**Issue by quicklearning123** [antvis/G2#3186]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
2019有人提过。https://github.com/antvis/g2/issues/1226
2021了，还是没有找到。

### What does the proposed API look like?
说明IE兼容到xxx，chrome到xxx等等

**Comment by hustcc** [comment]
不好意思，最近会做性能、兼容等规范出来。并按照你说的这样，放到官网上。
