### ISSUE TITLE
设置了滚动条scrollbar的时候，数据变化了，坐标轴的竖轴不会变

### ISSUE THREAD

**Issue by zhengyn0001** [antvis/G2#3189]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g2.gitee.io/zh/examples/column/basic#basic](https://antv-g2.gitee.io/zh/examples/column/basic#basic)

### Steps to reproduce
在示例的render之后加上以下代码，执行就可以复现
setTimeout(()=>{
  chart.changeData([
     { year: '1951 年', sales: 12312300 },
  { year: '1952 年', sales: 1042400 },
  { year: '1956 年', sales: 61 },
  { year: '1957 年', sales: 145 },
  { year: '1958 年', sales: 48 },
  { year: '1959 年', sales: 38 },
  { year: '1960 年', sales: 38 },
  { year: '1962 年', sales: 38 },
  { year: '1963 年', sales: 38 },
  { year: '1964 年', sales: 38 },
  { year: '1965 年', sales: 38 },
  { year: '1966 年', sales: 38 },
  { year: '1967 年', sales: 38 },
  { year: '1968 年', sales: 38888888 },
  { year: '1979 年', sales: 38 },
  { year: '1970 年', sales: 38 },
  { year: '1970 年', sales: 38 },
  { year: '1972 年', sales: 38 },
  { year: '1973 年', sales: 38 },
  { year: '1974 年', sales: 38 },
  { year: '1975 年', sales: 38 },
  { year: '1976 年', sales: 38 },
  { year: '1977 年', sales: 38 },
  { year: '1978 年', sales: 38 },
  { year: '1979 年', sales: 38 },
  { year: '1980 年', sales: 38 },
  ])
  chart.option('scrollbar', { type: 'horizontal' })
},10000)

| Environment | Info |
|---|---|
| g2 | 4.1.6 |
| System | - |
| Browser | - |

![1](https://user-images.githubusercontent.com/51322469/103997966-9afc2880-51d6-11eb-994d-fa1bcbc8750b.png)

**Comment by hustcc** [comment]
changeData 只是去影响数据，如果你同时还修改了配置，那么一定需要调用：

> chart.rener();
