### ISSUE TITLE
希望补充style的支持配置

### ISSUE THREAD

**Issue by tk231321** [antvis/g2#319]
https://antv.alipay.com/zh-cn/g2/3.x/tutorial/geom.html

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/api/geom.html#_style 链接没更新。到时候更新一下。

**Comment by dxq613** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/api/graphic.html

这些属性都支持
