### ISSUE TITLE
折线图在IE11无法展示

### ISSUE THREAD

**Issue by quicklearning123** [antvis/G2#3190]
* **G2 Version**: 4.0
* **Platform**: IE11 windows
* **Mini Showcase(like screenshots)**: https://g2.antv.vision/zh/examples/case/line#line1
* **CodePen Link**:https://g2.antv.vision/zh/examples/case/line#line1

官网demo示例无法正常显示

**Comment by quicklearning123** [comment]
@xiaobindebingo

**Comment by quicklearning123** [comment]
![Uploading image.png…]()

**Comment by quicklearning123** [comment]
![image](https://user-images.githubusercontent.com/70048681/104173754-342e7780-5441-11eb-8bd2-06a7b6b4d590.png)

**Comment by hustcc** [comment]
ref https://github.com/antvis/G2/issues/3186
