### ISSUE TITLE
🧐[问题] 怎么合并横坐标相同的数据？

### ISSUE THREAD

**Issue by bowencool** [antvis/G2#3191]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如图，我想让这两个点的数据累加，图表显示成一个整体，因为他们的横坐标相同
![image](https://user-images.githubusercontent.com/20217146/104080464-fb38ac00-5262-11eb-8360-5393e8fd2aa6.png)

### What does the proposed API look like?
-

**Comment by SandyluCH** [comment]
可以用adjust('stack'), 可以看下数据调整的api  (https://g2.antv.vision/zh/docs/api/general/adjust)

**Comment by bowencool** [comment]
> 可以用adjust('stack'), 可以看下数据调整的api (https://g2.antv.vision/zh/docs/api/general/adjust)

没有用啊，这个示例就是这么写的 https://g2.antv.vision/zh/examples/case/pie#pie3

**Comment by SandyluCH** [comment]
方式一： 格式化data, 该合并的合并，合并完了再画图；
方式二： 修改tooltip的显示；

**Comment by hustcc** [comment]
在传入之前自己保证数据是去重的，因为每一条记录都要有一个标识，而对于饼图、柱图，标识就是 x 轴的数据，也可以想象一下，对于 柱形图，x 轴位置相同，y 轴位置不相同，到底应该绘制成什么？

**Comment by bowencool** [comment]
可以是可以，但这种解决方案倒不如建议我手动画图，还用啥图表库。我想问的其实是配置或API，不是自己处理这种临时解决方案。

**Comment by hustcc** [comment]
> 我想问的其实是配置或API，不是自己处理这种临时解决方案。

自己处理数据不是临时方案，而就是合理，正常，对的做法。

你可以在你的业务代码中封装一层组件，包掉这个数据处理逻辑，然后用这个组件，就可以传入重复的数据了。
至于逻辑怎么处理重复数据，就按照你自己的业务需求。

**Comment by bowencool** [comment]
> 自己处理数据不是临时方案，而就是合理，正常，对的做法。
> 
> 你可以在你的业务代码中封装一层组件，包掉这个数据处理逻辑，然后用这个组件，就可以传入重复的数据了。
> 至于逻辑怎么处理重复数据，就按照你自己的业务需求。

我是这么做的，我以为图表库有内置这种功能的
