### ISSUE TITLE
演示代码修改保存后不生效

### ISSUE THREAD

**Issue by KedAyAyA** [antvis/G2#3192]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://localhost:8000/zh/examples/line/basic#base](http://localhost:8000/zh/examples/line/basic#base)

### Steps to reproduce
1. npm start
2. 更改examples/line/basic/demo/curved.ts代码，比如删除掉smooth，保存
3. 与未修改一致

| Environment | Info |
|---|---|
| g2 | 4.1.6 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
有时候修改代码之后，本地网站的 demo 没有同步更新，这个是网站的 bug，可能需要重新一下 npm start。
