### ISSUE TITLE
xField data should be sorted when xAxis.type is time or timeCat

### ISSUE THREAD

**Issue by dengfuping** [antvis/G2#3194]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/1c7f4794](https://riddle.alibaba-inc.com/riddles/1c7f4794)

### Steps to reproduce
| 4.1.5 `(Expected)` | 4.1.6 |  |
| :-- | :-- | --- |
| ![image](https://user-images.githubusercontent.com/14918822/104181072-2381ff80-5449-11eb-99cb-84dd4998d9cf.png) | ![image](https://user-images.githubusercontent.com/14918822/104180997-02b9aa00-5449-11eb-83c8-f94a6d8878f7.png)|

| Environment | Info |
|---|---|
| g2 | 4.1.6 |
| System | MacOS 10.15.5 |
| Browser | Chrome 81.0.4044.138 |

**Comment by dengfuping** [comment]
- Result by https://github.com/antvis/G2/pull/3188.

**Comment by hustcc** [comment]
```ts
chart.line({
  sortable: true,
}).position('timestamp*value').color('target');
```

这个是 scale time / timeCat 自己的问题，默认开启性能上受不了。后续 scale 重构中会在 scale 解决掉这个问题。解法有两个：

1. 开启 sortable
2. 数据在传入之前自行做好排序和格式化，然后传入 G2

**Comment by dengfuping** [comment]
- 但这样就不属于兼容性变更了，对业务的影响还挺大的。对于 time/timeCat 自动去做排序，也应该是合理的需求。

**Comment by hustcc** [comment]
> - 但这样就不属于兼容性变更了，对业务的影响还挺大的。对于 time/timeCat 自动去做排序，也应该是合理的需求。

确实是不兼容，这个是之前的做法不合理，打补丁支持排序了。也没办法为了这个而升级大版本。🙇

**Comment by hustcc** [comment]
另外现在也不建议用 time timeCat，很多 bug，还容易死循环，栈溢出，di 遇到多次。

**Comment by dengfuping** [comment]
> > * 但这样就不属于兼容性变更了，对业务的影响还挺大的。对于 time/timeCat 自动去做排序，也应该是合理的需求。
> 
> 确实是不兼容，这个是之前的做法不合理，打补丁支持排序了。也没办法为了这个而升级大版本。🙇

- 至少发个中间版本，而且需要在文档中做下说明。不过奇怪的是，没有看到相关的问题反馈，难道只有我的使用姿势不对? (通常不会对数据预排序，依赖 time 类型内部自动排序)

**Comment by hustcc** [comment]
> > > * 但这样就不属于兼容性变更了，对业务的影响还挺大的。对于 time/timeCat 自动去做排序，也应该是合理的需求。
> > 
> > 
> > 确实是不兼容，这个是之前的做法不合理，打补丁支持排序了。也没办法为了这个而升级大版本。🙇
> 
> * 至少发个中间版本，而且需要在文档中做下说明。不过奇怪的是，没有看到相关的问题反馈，难道只有我的使用姿势不对? (通常不会对数据预排序，依赖 time 类型内部自动排序)

底层的逻辑不是根据 timeCat 排序，而是根据数值排序，正好你的时间是一个 timestamp，是一个数字，所以会进行排序。而实际的处理逻辑，应该是 timeCat scale 进行 scale invert 的时候做好排序和缓存。

这样功能实现，且性能也是高的。现在是一种补丁做法，留的越久，带来的包袱越重！

**Comment by mark3h** [comment]
![image](https://user-images.githubusercontent.com/16110230/104399137-05bcb380-558b-11eb-8128-6e2c21e3540e.png)

#3195

**Comment by hustcc** [comment]
> ![image](https://user-images.githubusercontent.com/16110230/104399137-05bcb380-558b-11eb-8128-6e2c21e3540e.png)
> 
> #3195

reply in #3195
