### ISSUE TITLE
折线图存在断点数据，但是依然连接

### ISSUE THREAD

**Issue by mark3h** [antvis/G2#3195]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

#### 2020-11-24的黄色线是没有数据的
[https://codepen.io/William-cai/pen/wvzBZLy](https://codepen.io/William-cai/pen/wvzBZLy)

### Steps to reproduce
绿色的线存在断点数据，但是G2将两段断点数据依然进行了连接处理

#### G2错误的图
![image](https://user-images.githubusercontent.com/16110230/104312329-6c04f000-5511-11eb-9d51-84bcde86720b.png)

#### 正确的图
![image](https://user-images.githubusercontent.com/16110230/104312346-71623a80-5511-11eb-9e60-8c31fd818730.png)

将date的scale设置为timeCat后，依然无效

| Environment | Info |
|---|---|
| g2 | 4.1.6 |
| System | MacOS |
| Browser | - |

**Comment by hustcc** [comment]
两种办法：

1. 需要对 x 轴的数据进行排序。
2. chart.line({ sortable: true })

**Comment by hustcc** [comment]
ref: https://github.com/antvis/G2/issues/3194

**Comment by mark3h** [comment]
> 两种办法：
> 
> 1. 需要对 x 轴的数据进行排序。
> 2. chart.line({ sortable: true })

在例子中设置了第二种办法，11-24的数据依然连接了。

![Uploading image.png…]()

**Comment by mark3h** [comment]
![image](https://user-images.githubusercontent.com/16110230/104399022-d443e800-558a-11eb-9aa1-0fa20ff1ad93.png)

**Comment by webpawn** [comment]
可以将数据处理为 null 或者 undefined ，这样就会有断开的效果

**Comment by hustcc** [comment]
connectNulls 配置是对 null 和 undefined 处理连接和不连接。如果数据都没有了，那么是不会有断开效果的。
