### ISSUE TITLE
当数据过多时，有些坐标文本就会省略！！

### ISSUE THREAD

**Issue by DZTZ** [antvis/G2#3198]
<img width="431" alt="WeChatb8db33dedbefdc5ba4f54923b50ce199" src="https://user-images.githubusercontent.com/46846745/104417168-ed12c480-55af-11eb-8d34-a300aee150e2.png">

请问怎么让下面所有坐标文本强制全部都显示出来？

**Comment by Quelle-0** [comment]
可以试下使用tickCount去手动设置，比如
```myChart.scale( xPropName, {
          tickCount: data.length, // 手动设置tick个数避免自动省略
         // ...
        });
```
我是这样子写的，然后就不会省略了

**Comment by isexists** [comment]
配置axis->label->autoHide为false。

**Comment by shenzhenSk** [comment]
> 配置axis->label->autoHide为false。

data length >=400，哪怕label没有重叠遮挡，也会隔行显示
