### ISSUE TITLE
Error when using scrollbar in area chart

### ISSUE THREAD

**Issue by Demian1996** [antvis/G2#3201]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cool-babbage-vqhb7)

### Steps to reproduce
this demo has been an error

| Environment | Info |
|---|---|
| g2 | 4.1.6 |
| System | - |
| Browser | - |

---
(translated by chrome)
This error will be reported when I use the scroll bar in the area chart。

This problem seems to be resolved in this [PR](https://github.com/antvis/G2/pull/3137). So when do you update the master branch? 

## Error screenshot
![image](https://user-images.githubusercontent.com/21359263/104431096-78955100-55c2-11eb-8d62-3418bea41ed7.png)

## related link
https://github.com/antvis/G2/pull/3137

**Comment by hustcc** [comment]
Due to problems in the program's architecture design, we are unable to effectively fix the issues. But it is fixed in G2 5.0, you can have a try.
