### ISSUE TITLE
预警线超出坐标系

### ISSUE THREAD

**Issue by Moyoung-Li** [antvis/G2#3205]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g2.gitee.io/zh/examples/case/line#line8](https://antv-g2.gitee.io/zh/examples/case/line#line8)

### Steps to reproduce
1、在demo的基础上添加下面代码
    chart.render();   //此行是demo中原有的代码
    //添加下面代码在其后
    chart.interaction("view-zoom");    //缩放
    chart.getCanvas().on("mousewheel", ev => {
      ev.preventDefault();
    });
2、编译，然后缩放，预警会超出X轴，与X轴刻度融合在一起了

| Environment | Info |
|---|---|
| g2 | 4.1.7 |
| System | mac 11.0.1 |
| Browser | Chrome |

---
期望结果：预警线不要超出X轴显示

**Comment by hustcc** [comment]
有具体的截图信息吗？

**Comment by Moyoung-Li** [comment]
> 有具体的截图信息吗？
<img width="1435" alt="WechatIMG214" src="https://user-images.githubusercontent.com/37606111/106430410-b6411780-64a6-11eb-9f9f-94a801fc8f7e.png">

**Comment by hustcc** [comment]
chart 实例化的时候，设置：

{
  // ...
  limitInPlot: true,
}
