### ISSUE TITLE
请问怎么修改legend翻页箭头的颜色？箭头在dark theme下，不明显

### ISSUE THREAD

**Issue by xunmeng2015** [antvis/G2#3206]
* **G2 Version**: 4.x
* **Platform**: win10
* **Mini Showcase(like screenshots)**: 
* **CodePen Link**:

**Comment by wenqi73** [comment]
https://github.com/antvis/G2/blob/c77b5cbafad3124bce0f1a8e7ac98fb3930ab5cf/src/theme/style-sheet/dark.ts#L211
