### ISSUE TITLE
词云图数据丢失问题

### ISSUE THREAD

**Issue by pppppppppppp12** [antvis/G2#3207]
![image](https://user-images.githubusercontent.com/15646325/49476736-c07b1300-f855-11e8-99bd-083f202196ab.png)

![image](https://user-images.githubusercontent.com/15646325/49476694-a3dedb00-f855-11e8-9a9f-254bc8a7629a.png)

_Originally posted by @visiky in https://github.com/antvis/G2/issues/1084#issuecomment-444281240_

**Comment by pppppppppppp12** [comment]
size缩小画布后，有些词会不显示，数据丢失了

**Comment by hustcc** [comment]
因为在限制了文字大小范围，和画布范围的情况下， 一定会出现文字没有空间可以渲染，只能舍去，这个在所有的词云图中都有这样的逻辑的。
