### ISSUE TITLE
图表增加标题的需求

### ISSUE THREAD

**Issue by cuteCloud** [antvis/G2#3212]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1.现在我看你们的解答都是说用html去自己写，问题是图表大部分都需要做导出为图片，canvas to img ，html部分是无法导出出来的
2.现在虽然说可以用个chart.guide去模拟标题 但始终还是太麻烦，期待像其他图表库一样提供标题配置这个基本需求，主要还是解决1中国提到的图片导出问题，不然导出一个没有标题的图谁也看不懂呢

### What does the proposed API look like?
图片提供标题配置

**Comment by hustcc** [comment]
使用 antd 在业务层封装一层 title，一定会比 canvas 绘制标题更加简单，样式也更加丰富。

对于截图，可以使用 html2image 去导出即可。
