### ISSUE TITLE
容器不可见时图表宽度会变为2,然后图标无法显示

### ISSUE THREAD

**Issue by MichaelJokAr** [antvis/G2#3215]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/antvis/G2/issues/new/choose](https://github.com/antvis/G2/issues/new/choose)

### Steps to reproduce
使用tab，tab下的tabpane放入chart，除了第一个tab的图表可见，其他的图表的width都为2

| Environment | Info |
|---|---|
| g2 | 4.0.14 |
| System | - |
| Browser | Chrome |

**Comment by hustcc** [comment]
G2 中的 autoFit 是监听 window resize 事件的，而 tab 的隐藏和显示不会触发 autoFit。建议：

1. 通用图表使用 [G2Plot](https://github.com/antvis/G2Plot)，已经内置这个逻辑
2. 非通用图表，使用 G2Plot 的 plugin 开发方式，基于 G2 开发
3. 如果非常定制的图表，使用 G2 封装图表之后，监听容器大小变化，自动 resize，参考实现 https://github.com/antvis/G2Plot/blob/master/src/core/plot.ts#L4

**Comment by MichaelJokAr** [comment]
使用```this.chart.forceFit()```生效了，但是需要延迟执行，是在获取宽度么？
