### ISSUE TITLE
在图表选中图形时，如何设置未被选中图形的样式

### ISSUE THREAD

**Issue by Break-2020** [antvis/G2#3222]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/interaction/element#element-selected](https://g2.antv.vision/zh/examples/interaction/element#element-selected)

### Steps to reproduce
设置选中的颜色可以用  
chart
  .interval()
  .position('year*value')
  .state({
    selected: {
      style: {
        fill: '#E8684A',
      }
    }
  });
但是怎么设置有选中shape的时候，未选中shape的样式？
想要select的部分鼠标移走后还是高亮

| Environment | Info |
|---|---|
| g2 | 4.1.7 |
| System | win10 |
| Browser | chrome |

**Comment by Break-2020** [comment]
或者换个思路，想在select的同时也active需要怎么做？

**Comment by visiky** [comment]
搭配 element-selected 和 element-highlight, 
```
state: {
    selected: { style: {} },
    active: { style: {} },
   inactive: { style: {}},
}

```
