### ISSUE TITLE
some Chinese docs page go 404

### ISSUE THREAD

**Issue by kataji** [antvis/G2#3223]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g6.gitee.io/zh/docs/design/component/componentOverview](https://antv-g6.gitee.io/zh/docs/design/component/componentOverview)

### Steps to reproduce
click the link and see the 404 page

| Environment | Info |
|---|---|
| g2 | 4.1.3 |
| System | - |
| Browser | Chrome 87.0.4280.141 |

---
errrr if this is not the right place to report a docs 404 problem please hint where it should be

**Comment by hustcc** [comment]
好像是 g6 的文档问题，可以去 g6 提一下。这里先关闭了。
