### ISSUE TITLE
chart.line().color()中，color的字段不能使用YYYY-MM-DD

### ISSUE THREAD

**Issue by RyanLiu0235** [antvis/G2#3225]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/48e23965](https://riddle.alibaba-inc.com/riddles/48e23965)

### Steps to reproduce
如Riddle示例，51行，指定了color的字段为`date`，`date`是格式为`YYYY-MM-DD`的字符串，这样就会导致界面渲染出错。但是如果给date后面加一个空格之类，就ok了。

| Environment | Info |
|---|---|
| g2 | 4.1.7 |
| System | macOS Mojave |
| Browser | Chrome 87.0.4280.141 |

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/106240586-77f5ef00-623f-11eb-9fde-4c1cd4b3bc8d.png)

我这边打开是 ok 的。解决办法是将 date 的类型设置的 cat，新版本已经默认为 cat 了

> chart.scale('date', { type: 'cat' })

原因我大概知道，因为日期格式化的字符串会自动生成 timeCat scale，而底层的 timeCat scale 是一个垃圾，很可能死循环了，近期会对 scale 进行替换和重构。

**Comment by RyanLiu0235** [comment]
Well done, mate.
