### ISSUE TITLE
G2 详细手册中缺少 tooltip 的 customContent 配置项描述

### ISSUE THREAD

**Issue by wayneee188** [antvis/G2#3231]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在教程部分的tooltip部分，我们可以看到关于“customContent”相关的内容。而在api部分，未收录此部分内容，在实际使用中，不能很好的了解此部分特性，建议修改一下文档。
“customContent”描述：G2 支持使用 customContent 自定义展示 tooltip。

教程网站的截图：
![image](https://user-images.githubusercontent.com/38581778/105441207-02b87600-5ca3-11eb-8056-761dcb24eee1.png)
G2 详细手册网站截图：
![image](https://user-images.githubusercontent.com/38581778/105441179-f502f080-5ca2-11eb-8b63-810d053f71e4.png)

### What does the proposed API look like?
建议在 https://g2.antv.vision/zh/docs/api/general/tooltip 此部分文档中添加缺失的customContent 内容。

参考网址：
教程：https://g2.antv.vision/zh/docs/manual/tutorial/tooltip
G2 详细手册：https://g2.antv.vision/zh/docs/api/general/tooltip

**Comment by hustcc** [comment]
已增加：https://g2.antv.vision/zh/docs/manual/tutorial/tooltip#%E8%87%AA%E5%AE%9A%E4%B9%89-tooltip
