### ISSUE TITLE
pie changeData from 空数据 to real available data, will become black

### ISSUE THREAD

**Issue by visiky** [antvis/G2#3232]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/28ff2cea](https://riddle.alibaba-inc.com/riddles/28ff2cea)

### Steps to reproduce
https://riddle.alibaba-inc.com/riddles/28ff2cea

| Environment | Info |
|---|---|
| g2 | 4.1.7 |
| System | - |
| Browser | - |

解决方案：业务层上从空数据转变的话，先不使用 changeData

![image](https://user-images.githubusercontent.com/15646325/105465486-ee3da300-5ccd-11eb-96c9-3eb2622f084e.png)

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/234155435-2d083ce3-2f33-4dfb-b65a-3aab4b40dc62.png)

已经b被解决。
