### ISSUE TITLE
【bug】使用itemWidth和maxWidth修改legend的宽度无效

### ISSUE THREAD

**Issue by imyuxh** [antvis/G2#3237]
* **G2 Version**:4.0.12
* **Platform**:
* **Mini Showcase(like screenshots)**:
* 
![image](https://user-images.githubusercontent.com/15729365/105634851-0282cb00-5e9b-11eb-9d2b-104ee262062e.png)

* **CodePen Link**:https://codepen.io/imyuxh/pen/qBazOrV

 当图例名字过长的时候，设置itemWidth或者maxWidth都不管用，仿佛是内置了一个最大值

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/106239501-af639c00-623d-11eb-99d1-0ffbfd81fba6.png)

问题：

1. 你设置了 固定的 padding 值，所以右侧的留白永远是设置的右侧 padding 值
2. 我使用 4.1.x 测试是 ok 的，具体看上图。
