### ISSUE TITLE
饼图getXY方法返回undefined

### ISSUE THREAD

**Issue by SpongeDad** [antvis/G2#3238]
https://codesandbox.io/s/runtime-mountain-sy625?file=/src/index.js

期望能根据元数据拿到point坐标

**Comment by wuwenyuan111** [comment]
参数改下就行了。
const position = chart.getXY({ 1: 1, value: data.value });

**Comment by zoushujun** [comment]
const position = chart.getXY({ 1: 1, value: data.value }); 这个方法拿到的坐标，在图上展示的位置不对，全部提示都在一个区域内，能详细讲下饼图中getXY怎么传参么

**Comment by wuwenyuan111** [comment]
> const position = chart.getXY({ 1: 1, value: data.value }); 这个方法拿到的坐标，在图上展示的位置不对，全部提示都在一个区域内，能详细讲下饼图中getXY怎么传参么

这是个玄学，没有文档，这个方法也是BizCharts开源互助3群里的官方人员给的，全凭经验....

**Comment by zoushujun** [comment]
那么饼图想实现下tooltip轮播展示，这个有方法能实现吗，柱状图之类的可以通过getXY()来弄，饼图的话坐标对不上

**Comment by wuwenyuan111** [comment]
> 那么饼图想实现下tooltip轮播展示，这个有方法能实现吗，柱状图之类的可以通过getXY()来弄，饼图的话坐标对不上

对不上的原因可能是设置了饼图的各个饼块的border导致的，建议去掉。
