### ISSUE TITLE
data里面数据在数字过大的时候，渲染非常缓慢，还会导致页面错乱

### ISSUE THREAD

**Issue by han88829** [antvis/g2#324]
![image](https://user-images.githubusercontent.com/25733502/34317614-94799b10-e7ed-11e7-9ded-54280361cbb0.png)
data里面sales数量10的时候渲染正常，改成20000直接造成页面卡顿，渲染错乱
以下是错乱渲染截图
![Uploading image.png…]()

**Comment by han88829** [comment]
![image](https://user-images.githubusercontent.com/25733502/34317634-0c8de2b4-e7ee-11e7-9dd8-12df44aca127.png)
渲染截图

**Comment by leungwensen** [comment]
贴一下代码吧

**Comment by han88829** [comment]
@leungwensen `const data = [
            { year: '1951 年', sales: 38 },
            { year: '1952 年', sales: 52 },
            { year: '1956 年', sales: 61 },
            { year: '1957 年', sales: 2000000 },
            { year: '1958 年', sales: 48 },
            { year: '1959 年', sales: 38 },
            { year: '1960 年', sales: 38 },
            { year: '1962 年', sales: 38 },
        ];
        const chart = new G2.Chart({
            container: 'situationTotal',
            forceFit: true,
            height: 350,
            padding: 56
        });
        chart.source(data);
        chart.scale('sales', {
            tickInterval: 20
        });
        chart.interval().position('year*sales');
        chart.render();`

看下这个，我只修改了其中一条数据，数值两百万图就出不来，改为二十万，就是我上方贴的图片那样
我实在react中使用的

**Comment by han88829** [comment]
@leungwensen 
![image](https://user-images.githubusercontent.com/25733502/34331066-6840dd66-e95e-11e7-86ba-51be84898765.png)

**Comment by leungwensen** [comment]
如果已经两万条数据了，建议不要用柱状图： https://antv.alipay.com/zh-cn/vis/chart/bar.html#_%E4%B8%8D%E9%80%82%E5%90%88%E7%9A%84%E5%9C%BA%E6%99%AF

可以换用折线图等。但两万条数据还是太多了，你这个图可视化的目的是找出什么规律？如果数据太密集，人眼都看不到规律，那就没有意义了。

**Comment by leungwensen** [comment]
这是因为数值太离散，计算 scale 的时候生成的坐标轴刻度太多的缘故。这个 demo 的 scale 定义里设置了 tickInterval 为 20，所以最大值是 200000 的时候会生成 10000 个坐标刻度。

1. 数值相差悬殊的时候，你不要指定 tickInterval
2. 可以试试 log 类型的 scale

```js
  chart.scale('sales', {
    type: 'log'
  });
```
