### ISSUE TITLE
请问维度为 Cat 类型的图表，怎么做趋势线？？

### ISSUE THREAD

**Issue by jing1810** [antvis/G2#3243]

**Comment by hustcc** [comment]
内容描述不够清晰，数据是 cat 或者 timecat 本身影响不大。

**Comment by jing1810** [comment]
详见 #2545，我的需求是维度使用分类字段时，如何做趋势线？

**Comment by hustcc** [comment]
> 详见 #2545，我的需求是维度使用分类字段时，如何做趋势线？

已经回复了。
