### ISSUE TITLE
label fontFamily 不合法的时候，fontSize 不生效

### ISSUE THREAD

**Issue by visiky** [antvis/G2#3253]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/5841c1d5](https://riddle.alibaba-inc.com/riddles/5841c1d5)

### Steps to reproduce
https://riddle.alibaba-inc.com/riddles/5841c1d5

```
import { Chart } from '@antv/g2';

const data = [
  { type: '未知', value: 654, percent: 0.02 },
  { type: '17 岁以下', value: 654, percent: 0.02 },
  { type: '18-24 岁', value: 4400, percent: 0.2 },
  { type: '25-29 岁', value: 5300, percent: 0.24 },
  { type: '30-39 岁', value: 6200, percent: 0.28 },
  { type: '40-49 岁', value: 3300, percent: 0.14 },
  { type: '50 岁以上', value: 1500, percent: 0.06 },
];

const chart = new Chart({
  container: 'container',
  autoFit: true,
  height: 500,
  padding: [50, 20, 50, 20],
});
chart.data(data);
chart.scale('value', {
  alias: '销售额(万)',
});

chart.tooltip({
  showMarkers: false,
});
chart.interval().position('type*value').label('type', {
  style: {
    // fontFamily: 'roboto-regular',
    // fontFamily: 'xxx', // fontSize works
    fontFamily: '{xxx}', // fontSize not works
    fontSize: 20
  }
});
chart.interaction('element-active');
chart.render();
```

| Environment | Info |
|---|---|
| g2 | 4.1.9 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
```html
<!DOCTYPE html>
<html>
<body>

<canvas id="myCanvas" width="200" height="100" style="border:1px solid #d3d3d3;">
Your browser does not support the HTML canvas tag.</canvas>

<script>
var c = document.getElementById("myCanvas");
var ctx = c.getContext("2d");
ctx.font = "30px {Arial}";
ctx.fillText("Hello World",10,50);
</script>

</body>
</html>
```

浏览器底层的 canvas 就存在这个问题。

**Comment by yangguansen** [comment]
> ```
> <!DOCTYPE html>
> <html>
> <body>
> 
> <canvas id="myCanvas" width="200" height="100" style="border:1px solid #d3d3d3;">
> Your browser does not support the HTML canvas tag.</canvas>
> 
> <script>
> var c = document.getElementById("myCanvas");
> var ctx = c.getContext("2d");
> ctx.font = "30px {Arial}";
> ctx.fillText("Hello World",10,50);
> </script>
> 
> </body>
> </html>
> ```
> 
> ![image](https://user-images.githubusercontent.com/7856674/106430882-70388380-64a7-11eb-9e3b-f66c0c9f655c.png)
> 
> 浏览器底层的 canvas 就存在这个问题。

如果是浏览器底层问题的话，可以在fontFamily为空时，给个警告提示，起码对于不知道这一底层BUG的开发者来说，更加友好，也更容易debug, 在g-base库里设置字体时
```
export function assembleFont(attrs) {
    if( !attrs.fontFamily ) console.warn('文本字体无效，请检查文本字体');
    var fontSize = attrs.fontSize, fontFamily = attrs.fontFamily, fontWeight = attrs.fontWeight, fontStyle = attrs.fontStyle, fontVariant = attrs.fontVariant;
    return [fontStyle, fontVariant, fontWeight, fontSize + "px", fontFamily].join(' ').trim();
}
```
如果允许的话，我会给g库提个PR，请问是否接受这样的改进方法？

**Comment by hustcc** [comment]
PR 怎么提？现在是浏览器底层没有兼容 {font} 这种写法，如果这都早去 G 兼容，那做不完了，比如(font), <>, [], €£ 等等，兼容不完的。

这个问题很简单，传入的时候保证是有效的字体名字即可，不要复杂化了。

**Comment by visiky** [comment]
问题是无法枚举浏览器无法接受的fontFamily，你想提的这个pr也没啥用处
