### ISSUE TITLE
有没有分组堆叠条形图？

### ISSUE THREAD

**Issue by Petter-li** [antvis/G2#3254]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

就是把 分组层叠柱状图 横纵坐标交换一下。

**Comment by visiky** [comment]
自己设置下 coordinate.transpose()

**Comment by hustcc** [comment]
@Petter-li 我看官网的 demo 中是有的，我就不贴地址了，很容易找，直接搜索也能搜到。
