### ISSUE TITLE
曲线图出现首尾连接问题

### ISSUE THREAD

**Issue by Moyoung-Li** [antvis/G2#3255]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g2.gitee.io/zh/examples/line/basic#curved](https://antv-g2.gitee.io/zh/examples/line/basic#curved)

### Steps to reproduce
请查看截图

| Environment | Info |
|---|---|
| g2 | 4.1.9 |
| System | mac 11.0.1 |
| Browser | Chrome |

**Comment by Moyoung-Li** [comment]
![311612169099_ pic_hd](https://user-images.githubusercontent.com/37606111/106440400-c90e1900-64b3-11eb-8061-a77f1a2bfd7b.jpg)
![321612169099_ pic_hd](https://user-images.githubusercontent.com/37606111/106440426-ce6b6380-64b3-11eb-9547-ae20ee1382ac.jpg)
![331612169100_ pic_hd](https://user-images.githubusercontent.com/37606111/106440433-d1feea80-64b3-11eb-932c-327a09840072.jpg)
![341612169100_ pic_hd](https://user-images.githubusercontent.com/37606111/106440451-d75c3500-64b3-11eb-88d6-5468669924e5.jpg)

**Comment by Moyoung-Li** [comment]
![image](https://user-images.githubusercontent.com/37606111/106442235-fe1b6b00-64b5-11eb-8546-fc80571b0978.png)

//新增预警线
chart.annotation().line({
      start: ['min', 5],
      end: ['max', 5],
      style: {
        stroke: '#ff4d4f',
        lineWidth: 1,
        lineDash: [3, 3],
      },
      text: {
        position: 'start',
        style: {
          fill: '#8c8c8c',
          fontSize: 15,
          fontWeight: 'normal',
        },
        content: '预警线 85%',
        offsetY: -5,
      },
});
//limitInPlot: true  //上面初始化新增了此行代码
chart.interaction('view-zoom');  //新增代码
chart.render();
// 阻止默认事件，否则会整个窗口滚动
chart.getCanvas().on('mousewheel', ev=> {ev.preventDefault();})   //新增代码

demo链接：
https://antv-g2.gitee.io/zh/examples/line/basic#curved

**Comment by potatozerg** [comment]
Chinese input is not working... I have the same issue with line charts for G2Plot. Already created an issue for G2plot.
![image](https://user-images.githubusercontent.com/3282773/112197231-39970380-8be2-11eb-8097-16171c7d0047.png)

**Comment by pearmini** [comment]
关于这个问题可以提供一个简单的复现 demo 吗？不同的问题提在不同的 issue 最好🤣

**Comment by hustcc** [comment]
我猜测这个数据应该是 x 轴是数字，然后传入的数据没有经过排序导致的。
