### ISSUE TITLE
折线图4.1.6及之后版本绘图错误

### ISSUE THREAD

**Issue by mawienan123** [antvis/G2#3264]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/16c535b4 ](https://riddle.alibaba-inc.com/riddles/16c535b4 )

### Steps to reproduce
将packjson的g2版本改成4.1.5就没问题

| Environment | Info |
|---|---|
| g2 | 4.1.6 |
| System | - |
| Browser | - |

---
这个bug的复现场景为data排序为时间的时候const data =[
{
"cnt": 1326,
"day": "2021-01-29"
},

{
"cnt": 1543,
"day": "2021-01-31"
},
{
"cnt": 1965,
"day": "2021-02-01"
},
{
"cnt": 1104,
"day": "2021-02-02"
},
{
"cnt": 1382,
"day": "2021-01-30"
},
]
如果不是按照日期大小进行排序就会出现这个问题

**Comment by mawienan123** [comment]
![Uploading image.png…]()错误图例

![Uploading image.png…]()正确图例

**Comment by mawienan123** [comment]
正确图例![image](https://user-images.githubusercontent.com/29793986/106689449-f7523c80-660a-11eb-9527-20253fd2ab2e.png)
错误图列
![image](https://user-images.githubusercontent.com/29793986/106689494-09cc7600-660b-11eb-8b02-2e2e39d217b4.png)

**Comment by hustcc** [comment]
之前 scale 的 bug，最近重构，解法：

1. 设置类型

```ts
chart.scale({
  day: {
    type: 'cat',
  }
});
```

2. 设置排序

```ts
chart.line({ sortable: true })..
```

两个方法选择一个即可。

**Comment by mawienan123** [comment]
> 之前scale的bug，最近重构，解法：
> 
> 1. 设置类型
> 
> ```ts
> 图表。规模（{ 
>   day：{ 
>     type：'cat' ，
>   } 
> } ）;
> ```
> 
> 1. 设置等级
> 
> ```ts
> 图表。行（{  sortable：true  } ）。。
> ```
> 
> 两个方法选择一个即可。

感谢

**Comment by hustcc** [comment]
还有一个，就是业务层进行数据排序。 @mawienan123
