### ISSUE TITLE
chart 关闭animate后再开启动画效果失效

### ISSUE THREAD

**Issue by SpongeDad** [antvis/G2#3268]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wonderful-williamson-fqisl?file=/index.js)

### Steps to reproduce
先关闭动画 chart.animate(false)
再在一个异步方法或事件回调中开启动画 chart.animate(true)
结果：动画未开启成功，仍是无动画的状态
期望能重新开启动画

| Environment | Info |
|---|---|
| g2 | 4.1.10 |
| System | - |
| Browser | - |

**Comment by pearmini** [comment]
等合并到主分支之后，直接运行下面的代码即可。

```js
// ...
chart.animate(false);
chart.render();
chart.animate(true):
```
