### ISSUE TITLE
3.0.3-beta.1 版本，轴绘制有问题

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#327]
https://antv.alipay.com/zh-cn/g2/3.x/demo/gauge/text.html

将这个 demo 换成 3.0.3-beta.1 版本，然后注释掉  chart.axis('1', false); 这行代码。

图表会有 bug ，‘1’ 这个轴绘制出错，之前版本是好的。

**Comment by leungwensen** [comment]
@antv/g2@3.0.3 已经发布
