### ISSUE TITLE
折线图现在有从右往左滚动的功能吗，不只是线条移动，还有上面折线上的点和坐标轴刻度/文本等一起移动

### ISSUE THREAD

**Issue by Break-2020** [antvis/G2#3270]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
数据多的时候能循环展示

### What does the proposed API look like?
增加一个预设的动画类型

**Comment by hustcc** [comment]
具体是指什么？

https://g2plot.antv.vision/zh/examples/dynamic-plots/basic#dynamic-spline 这个 demo 类似的吗？

**Comment by Break-2020** [comment]
> 具体是指什么？
> 
> https://g2plot.antv.vision/zh/examples/dynamic-plots/basic#dynamic-spline 这个 demo 类似的吗？

这个动画看着有些奇怪，有平移的那种吗

**Comment by Break-2020** [comment]
> 具体是指什么？
> 
> https://g2plot.antv.vision/zh/examples/dynamic-plots/basic#dynamic-spline 这个 demo 类似的吗？

element/index.js里面的syncShapeStyle方法感觉有点问题啊。如果我改变数据前后，sourceShape和targetShape都为group，但是里面具体shape的数量不一致，前一个多，后一个少，那么 newChildren[i]就是undefinded，之后就会报错，是不是应该考虑一下当sourceShape,和targetShape数量不一致的情况下同步样式的动画
