### ISSUE TITLE
饼图的交互问题

### ISSUE THREAD

**Issue by jing1810** [antvis/G2#3274]
https://g2.antv.vision/zh/examples/case/pie#pie3
针对饼图的交互，我不仅需要饼图的选中效果，还想有选中高亮，其他的蒙版的效果，请问怎么实现。
交互前：
![image](https://user-images.githubusercontent.com/47776028/107018331-4353db80-67db-11eb-96ff-8fbc4980eef5.png)
交互后：
![image](https://user-images.githubusercontent.com/47776028/107018362-4d75da00-67db-11eb-9229-22292f5412b6.png)

**Comment by visiky** [comment]
高亮：`chart.interaction('element-highlight');`

切片移出，参考：https://g2.antv.vision/en/examples/interaction/element#pie-selected

**Comment by Moonquakesss** [comment]
> 高亮：`chart.interaction('element-highlight');`
> 
> 切片移出，参考：https://g2.antv.vision/en/examples/interaction/element#pie-selected

您好，这个链接已失效～有其他参考吗
