### ISSUE TITLE
雷达图，设置弧度半圆，两者axis.grid(line、circle)行为不一致

### ISSUE THREAD

**Issue by ntscshen** [antvis/G2#3278]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/ntscshen/pen/bGBpYxV?editors=1010](https://codepen.io/ntscshen/pen/bGBpYxV?editors=1010)

### Steps to reproduce
Demo

| Environment | Info |
|---|---|
| g2 | 4.1.8 |
| System | 10.15.3 |
| Browser |  88.0.4324.146 |

---

在半圆雷达图的场景下，axis.grid 无论是线或圆，希望它们行为是一致的

**Comment by hustcc** [comment]
什么意思？

**Comment by ntscshen** [comment]
这个左侧画的圆是不是应该只画一半，和右侧的一样
```js
chart.coordinate('polar', {
  radius: 0.8,
  startAngle: (Math.PI * 0) / 180,
  endAngle: (Math.PI * 180) / 180,
});
```

**Comment by hustcc** [comment]
哦，懂了，circle 没有画半圆，line 画半圆了。我来排查一下~

**Comment by hustcc** [comment]
```ts
chart.axis('score', {
    grid: {
      line: {
        type: 'circle'
      },
      closed: false, // 加这个配置！
    },
});
```
