### ISSUE TITLE
建议提供自定义绘制接口

### ISSUE THREAD

**Issue by ForeseeBear** [antvis/G2#3285]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
虽然antv提供了很多可视化及分析的图形解决方案，但还是有很多场景下满足不了需求，这时自定义绘制图形尤为重要，开发人员可根据多场景场景、特殊场景实现很多有特殊的效果，如2.5d类图形

### What does the proposed API look like?
自定义绘制提供一个方法，用户能根据自己特殊需求绘制不同的图形，可参考echarts提供type:custom；参考地址：https://echarts.apache.org/zh/option.html#series-custom.renderItem
renderItem: function (params, api) {
            var categoryIndex = api.value(0);
            var start = api.coord([api.value(1), categoryIndex]);
            var end = api.coord([api.value(2), categoryIndex]);
            var height = api.size([0, 1])[1] * 0.6;

            var rectShape = echarts.graphic.clipRectByRect({
                x: start[0],
                y: start[1] - height / 2,
                width: end[0] - start[0],
                height: height
            }, {
                x: params.coordSys.x,
                y: params.coordSys.y,
                width: params.coordSys.width,
                height: params.coordSys.height
            });

            return rectShape && {
                type: 'rect',
                shape: rectShape,
                style: api.style()
            };
        }

**Comment by visiky** [comment]
registerShape 了解下？

**Comment by visiky** [comment]
另外，也可以参考下 G2Plot 的自定义扩展机制：https://g2plot.antv.vision/zh/docs/manual/plugin
在这里边就有一些基于自定义图形的案例

**Comment by ForeseeBear** [comment]
> registerShape 了解下？https://g2.antv.vision/en/docs/api/advanced/register-shape

多谢多谢，看文档没看仔细

**Comment by ForeseeBear** [comment]
> 另外，也可以参考下 G2Plot 的自定义扩展机制：https://g2plot.antv.vision/zh/docs/manual/plugin
> 在这里边就有一些基于自定义图形的案例

谢谢啦！
