### ISSUE TITLE
draw返回的cfg配置颜色问题

### ISSUE THREAD

**Issue by NameIsEward** [antvis/g2#329]
在注册一个shape时:
![image](https://user-images.githubusercontent.com/8791349/34335509-411a671c-e98a-11e7-9069-e6bc9ad06a75.png)
这里的cfg中color无论怎么打印都是下图中的"category"
![image](https://user-images.githubusercontent.com/8791349/34335495-2b523acc-e98a-11e7-94d7-c1b73f4d1b74.png)

**Comment by leungwensen** [comment]
请发完整数据和代码。官网的 词云 demo 并不会有这个问题。
