### ISSUE TITLE
在Column图中如果dodgeBy 有空格，Column没有错开

### ISSUE THREAD

**Issue by JunYang-tes** [antvis/G2#3296]
* **G2 Version**:
4.1.11 
* **Platform**:
Chrome 88.0.4324.182 (Official Build) (x86_64)
* **Mini Showcase(like screenshots)**:
**有空格 👇**
![image](https://user-images.githubusercontent.com/17270099/108590680-cf4f3100-739f-11eb-8829-8382cf3dcf0d.png)
**没空格👇**
![image](https://user-images.githubusercontent.com/17270099/108590807-69af7480-73a0-11eb-9720-d165a2452c73.png)

* **CodePen Link**:

上图中代码如下：

```
import { Chart } from '@antv/g2';
const data = [
  { 'C C':'L', name: 'London', 月份: 'Jan.', 月均降雨量: 18.9 },
  { 'C C':'B', name: 'Berlin', 月份: 'Jan.', 月均降雨量: 12.4 },
];
const chart = new Chart({
  container: 'container',
  autoFit: true,
  height: 500,
});
chart.data(data);
chart
  .interval()
  .position('月份*月均降雨量')
  .color('C C')
  .adjust([
    {
      type: 'dodge',
      dodgeBy: 'C C',
      marginRatio: 0,
    },
  ]);
chart.interaction('active-region');
chart.render();
```

**Comment by hustcc** [comment]
确实存在这个问题，因为 G2 4.0 中对于字段会进行一些解析，带来的数据异常，但是再 5.0 中，避免了这类字段解析的问题，可以试试。这个问题不在 4.0 中去处理了，不好意思。
