### ISSUE TITLE
[bug] 自定图形的container获取不到canvas对象

### ISSUE THREAD

**Issue by alphabetabc** [antvis/G2#3303]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g2.gitee.io/zh/examples/point/bubble#bubble-image](https://antv-g2.gitee.io/zh/examples/point/bubble#bubble-image)
![image](https://user-images.githubusercontent.com/29876424/109280242-b8a05280-7855-11eb-8cde-9558dcb60855.png)

### Steps to reproduce
- 打开上面个的链接，一看就知道 ( ╯□╰ )

| Environment | Info |
|---|---|
| g2 | 4.1.12 |
| System | win |
| Browser | chrome |

```js
// 用到的一段代码
console.log('log----',container.getCanvas());
```

**Comment by hustcc** [comment]
为啥要获取 canvas。因为这个时候 ui 结构还没有添加到树形结构中，所以还没有赋予 canvas。

**Comment by alphabetabc** [comment]
@hustcc  您再左右拖一拖，触发一下resize，渲染的图片咋更多了 😂

**Comment by hustcc** [comment]
问题描述：自定义 shape 的时候，如果出发重新渲染，有 shape 没有清除。

**Comment by pearmini** [comment]
4.0 的这个 Bug 不会修复了，5.0 直接提供了 Image Mark 绘制图形，可以参考这个例子：https://g2.antv.antgroup.com/examples/general/image/#logo
