### ISSUE TITLE
自动 padding 计算问题

### ISSUE THREAD

**Issue by simaQ** [antvis/G2#3307]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/cccf697c](https://riddle.alibaba-inc.com/riddles/cccf697c)

### Steps to reproduce
resize 窗口即可复现。

![image](https://user-images.githubusercontent.com/6628666/109482132-95c1a880-7ab8-11eb-9ea1-18552aea53d4.png)

| Environment | Info |
|---|---|
| g2 | 4.1.12 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
在收缩过程中，因为 y axis 占了宽度，导致 x axis 放不下了，自动旋转导致。这个是 3.x 到 4.x 一直存在的问题，目前的布局解决不掉。
