### ISSUE TITLE
当文本换行时，采用 labelHeight 作为高度会导致文本碰撞

### ISSUE THREAD

**Issue by simaQ** [antvis/G2#3309]
https://github.com/antvis/G2/blob/d0a73c2256ff133e5bf66d82464b8c6ba541f011/src/geometry/label/layout/pie/outer.ts#L165

应该取整个 labelShape 包围盒的高度，同时考虑下可设置 label 与 label 之间的 margin，饼图其他布局也有类似的问题。

* demo 地址：https://antv-g2.gitee.io/zh/examples/pie/basic#pie-spider-label

![image](https://user-images.githubusercontent.com/6628666/109585992-673ae080-7b3f-11eb-846f-80ac92c278ec.png)

**Comment by visiky** [comment]
换行的时候 将labelHeight设置为更大，如 18*2=36
内部从性能考虑 暂不计算

**Comment by simaQ** [comment]
> 换行的时候 将labelHeight设置为更大，如 18*2=36
> 内部从性能考虑 暂不计算

恩，临时方案我了解，不过想请教下，从性能考虑如果采用包围盒折损多少，性能的瓶颈点在这里吗？

**Comment by visiky** [comment]
也不算临时方案把，labelHeight 之前的定义就是整个 label 的高度。
大数据量遍历计算包围盒，会增加多少折损时间，暂时没去衡量，后面可以看时间处理下
