### ISSUE TITLE
自定义样式会影响 tooltip 样式

### ISSUE THREAD

**Issue by wenqi73** [antvis/G2#3314]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/00uym)

### Steps to reproduce
查看 tooltip

### 正常情况
![image](https://user-images.githubusercontent.com/23337087/110292112-b4c7b980-8027-11eb-9284-92572e6f4cd5.png)

### 加上自定义样式后
![image](https://user-images.githubusercontent.com/23337087/110292207-ce690100-8027-11eb-8051-5174464acec8.png)

| Environment | Info |
|---|---|
| g2 | 4.1.12 |
| System | mac |
| Browser | chrome |

**Comment by huanledeniuduzi** [comment]
请问这个问题您解决了么？

**Comment by wenqi73** [comment]
弄个全量样式表（参考 https://github.com/antvis/g2/blob/master/src/theme/style-sheet/dark.ts ），然后注册即可

**Comment by huanledeniuduzi** [comment]
我就是想把背景弄成白色，tooltip背景是黑色，tooltip文字是白色也要弄全量样式表么？

**Comment by wenqi73** [comment]
好像是的哇
