### ISSUE TITLE
npm安装的@antv/g2@3.5.17为什么没有interaction的api ？

### ISSUE THREAD

**Issue by zhaopeiym** [antvis/G2#3315]
1、npm安装v 3.5.17 ts文件里显示3.0.4
![AKPE)CXPQT_AN@1(S1HB1 B](https://user-images.githubusercontent.com/5820324/110408065-f3a94e00-80bf-11eb-88b7-a267d8ce3a35.png)
![~WI{5QQY9(4I0YCJO}C16G0](https://user-images.githubusercontent.com/5820324/110408071-f60ba800-80bf-11eb-8b2a-1cc041414185.png)

2、chart找不到interact方法
![%1(6K~@}KOU28 Z0CT6}Z11](https://user-images.githubusercontent.com/5820324/110408099-002da680-80c0-11eb-88e9-7f118a1d300f.png)

**Comment by hustcc** [comment]
3.x 是 js 写的，类型定义是额外提供的，如果只是类型定义报错，可以先 ts-ignore 掉。

**Comment by zhaopeiym** [comment]
嗯，那应该ts没有进行同步更新。感谢回复。
