### ISSUE TITLE
希望有tooltip-crosshairs的点击事件

### ISSUE THREAD

**Issue by redclown** [antvis/g2#332]
现在我们公司有个需求就是，做柱状图的点击，
但是因为有的柱状图特别低，单纯的点击interval，点击不到，
如果能点击后面的背景就好了，查了一下文档，所有的都试过了，还是没找到，能不能加一下，谢谢~

**Comment by NoraGithub** [comment]
这个需求加一个 rect 的 crosshairs 应该可以解决吧。

**Comment by NoraGithub** [comment]
的确不行，我也有这个需求，希望 hover 能出现crosshairs，然后点击该 crosshairs 有事件。

**Comment by dxq613** [comment]
其实可以使用

```js
chart.getSnapRecords(point); 可以获取到邻近的记录，这个范围就是 后面 阴影的范围
```

**Comment by leungwensen** [comment]
@dxq613 具体怎么监听阴影部分的点击事件？

**Comment by dxq613** [comment]
你直接使用 chart.on('plotclick', ) 就行了，能够拿得到 x,y信息，传入进去就可以了

**Comment by leungwensen** [comment]
https://github.com/antvis/g2/issues/341
