### ISSUE TITLE
g2 支持类似于echarts 的toolbox 一样的工具栏吗

### ISSUE THREAD

**Issue by 2012shenghua** [antvis/G2#3322]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by 2012shenghua** [comment]
点击图标开启框选这样的功能

**Comment by hustcc** [comment]
暂时没有的。

**Comment by 2012shenghua** [comment]
有方案可以做到这个toolbar吗，最好找个例子看下

**Comment by hustcc** [comment]
本质方式，就是外部使用 html 绘制，然后在 html 中拌操作的时候，对应的 charts 做一些操作，无外乎筛选，高亮，联动。
