### ISSUE TITLE
当renderer设置为"canvas"时，graph.toDataURL()生成空白页

### ISSUE THREAD

**Issue by Lcyame** [antvis/G2#3323]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g6.gitee.io/zh/examples/item/defaultNodes#circle](https://antv-g6.gitee.io/zh/examples/item/defaultNodes#circle)

### Steps to reproduce
将'renderer'设置为'canvas',然后在graph.render();之后添加'let dataurl = graph.toDataURL()',生成的url为空白页面

| Environment | Info |
|---|---|
| g2 | 4.1.12 |
| System | win10 |
| Browser | chrome89 |

---
将'renderer'设置为'svg'时正常

**Comment by hustcc** [comment]
到 G6 提个 issue 吧，G2 没有提供这样的 API。
