### ISSUE TITLE
示例实际效果与示意图不符

### ISSUE THREAD

**Issue by liusir0215** [antvis/G2#3326]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/interaction/others#pie-legend](https://g2.antv.vision/zh/examples/interaction/others#pie-legend)

### Steps to reproduce
如视频所示

| Environment | Info |
|---|---|
| g2 | 4.1.12 |
| System | macos |
| Browser | - |

**Comment by liusir0215** [comment]
https://user-images.githubusercontent.com/8552713/111255165-7fd3ec00-8651-11eb-9265-19aa8c65c33a.mov

在环形图中滑动到不同数据时，没有出现状态变化的交互；当只有一条数据时鼠标 hover 有 bug

**Comment by hustcc** [comment]
@liusir0215 这个问题已经修复，可以再试试看。
