### ISSUE TITLE
🌹玫瑰图🌹，点击取消部分图例，玫瑰不会自动合并

### ISSUE THREAD

**Issue by ntscshen** [antvis/G2#3328]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/pie/rose#color-rose](https://g2.antv.vision/zh/examples/pie/rose#color-rose)

### Steps to reproduce
官网Demo，点击部分图例，玫瑰图不会自动合并

| Environment | Info |
|---|---|
| g2 | 4.1.12 |

---
这可能不是一个问题，如果有其他的配置项可以设置它，我没有找到它，这个小功能值得在默认的案例中存在。
如果没有可以设置的参数，期待这个功能优化。
值得参考的案例: https://echarts.apache.org/examples/zh/editor.html?c=pie-roseType-simple

**Comment by pearmini** [comment]
试试 5.0 的玫瑰图: https://g2.antv.antgroup.com/zh/examples/general/rose/#rose
