### ISSUE TITLE
Scrollbar效果出不来

### ISSUE THREAD

**Issue by zhangjiajia123** [antvis/G2#3335]
* **G2 Version**: 4.0+
* **Platform**: PC
* **code**:
```
initChart() {
      const _self = this
      _self.chart = new Chart({
        container: _self.chartID,
        autoFit: true,
        height: 440,
        padding: [16, 32, 64, 32],
      })
      _self.chart.data(_self.lineChartData)
      // 滚动条不起作用
      _self.chart.option('scrollbar', {
        type: 'horizontal',
      })
      _self.chart.scale('rainfall', {
        nice: true,
      })

      _self.chart.tooltip({
        showMarkers: false,
        shared: true,
      })
      _self.chart.axis('rate', {
        position: 'right',
        line: {},
        grid: null,
        tickLine: {
          alignTick: true,
        },
        subTickLine: {
          count: 20,
        },
        label: {
          formatter: (val) => {
            return val + '%'
          },
        },
      })
      _self.chart.scale('rate', {
        min: -10,
        max: 100,
        nice: true,
      })
      _self.chart.axis('rainfall', {
        position: 'left',
        line: {},
        tickLine: {
          alignTick: true,
        },
        label: {
          formatter: (val) => {
            if (_self.unit == '%') {
              return +val * 100 + `${_self.unit}`
            } else {
              return +val + `${_self.unit}`
            }
          },
        },
      })
      _self.chart
        .interval()
        .position('month*rainfall')
        .color('name')
        .adjust([
          {
            type: 'dodge',
            marginRatio: 0,
          },
        ])
      _self.chart.interaction('active-region')
      // _self.chart.line().position('month*rate').label('rate').shape('smooth').color('name')
      _self.chart.line().position('month*rate').color('name').shape('smooth')
      _self.chart.render()
    }

```
* **CodePen Link**:在ant-design-pro框架中使用的(vue版本)

**Comment by zhangjiagithub** [comment]
![image](https://user-images.githubusercontent.com/48313333/111949876-6e408780-8b1c-11eb-973a-ce172d1fe429.png)

**Comment by zhangjiagithub** [comment]
而且会导致柱状图无法显示

**Comment by hustcc** [comment]
双轴图目前的滚动条确实是有问题的。

**Comment by yehoan** [comment]
请问折线图的滚动条 不起作用这个 处理的怎么样了

**Comment by yehoan** [comment]
import { Chart } from '@antv/g2';

const data = [
  { year: '1991', value: 3 },
  { year: '1992', value: 4 },
  { year: '1993', value: 3.5 },
  { year: '1994', value: 5 },
  { year: '1995', value: 4.9 },
];
const chart = new Chart({
  container: 'container',
  autoFit: true,
  height: 500,
});

chart.data(data);
chart.scale({
  year: {
    range: [0, 1],
  },
  value: {
    min: 0,
    nice: true,
  },
});

chart.tooltip({
  showCrosshairs: true, // 展示 Tooltip 辅助线
  shared: true,
});

chart.line().position('year*value').label('value');
chart.point().position('year*value');
setTimeout(()=>{
  chart.changeData([
       { year: '1991', value: 3 },
  { year: '1992', value: 4 },
  { year: '1993', value: 3.5 },
  { year: '1994', value: 5 },
  { year: '1995', value: 4.9 },
  { year: '1996', value: 6 },
  { year: '1997', value: 7 },
  { year: '1998', value: 9 },
  { year: '1999', value: 13 },
  { year: '2000', value: 3 },
  { year: '2001', value: 4 },
  { year: '2002', value: 3.5 },
  { year: '2003', value: 5 },
  { year: '2004', value: 4.9 },
  { year: '2005', value: 6 },
  { year: '2006', value: 7 },
  { year: '2007', value: 9 },
  { year: '2008', value: 13 },
    { year: '2009', value: 3 },
  { year: '2010', value: 4 },
  { year: '2011', value: 3.5 },
  { year: '2012', value: 5 },
  { year: '2013', value: 4.9 },
  { year: '2014', value: 6 },
  { year: '2015', value: 7 },
  { year: '2016', value: 9 },
  { year: '2017', value: 13 },
  { year: '2018', value: 3 },
  { year: '2019', value: 4 },
  { year: '2020', value: 3.5 },
  { year: '2021', value: 5 },
  { year: '2022', value: 4.9 },
  { year: '2023', value: 6 },
  { year: '2024', value: 7 },
  { year: '2025', value: 9 },
  { year: '2026', value: 13 },
    { year: '2027', value: 9 },
  { year: '2028', value: 13 },
  { year: '2029', value: 3 },
  { year: '2030', value: 4 },
  { year: '2031', value: 3.5 },
  { year: '2032', value: 5 },
  { year: '2033', value: 4.9 },
  { year: '2034', value: 6 },
  { year: '2035', value: 7 },
  { year: '2036', value: 9 },
  { year: '2037', value: 13 },
  ])
  chart.option("scrollbar", { type: "horizontal" });
  chart.render()
}, 1000)

chart.render();
我发现折线图也是这样啊 大佬

**Comment by yehoan** [comment]
@hustcc  大佬怎么说呢
