### ISSUE TITLE
dataMarker text 样式设置不生效

### ISSUE THREAD

**Issue by visiky** [antvis/G2#3337]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
![image](https://user-images.githubusercontent.com/15646325/112074672-c4133f00-8bb1-11eb-9d58-7840ec8d3270.png)

| Environment | Info |
|---|---|
| g2 | 4.1.13 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
G2 5.0 中修复了。
