### ISSUE TITLE
G2 折线图 根据不同Type展示不同颜色的线，同时不同年份Type相同也要展示不同的线 

### ISSUE THREAD

**Issue by zhangjiagithub** [antvis/G2#3344]
* **G2 Version**: G2 4.0+
* 
* **Platform**:web端
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by hustcc** [comment]
按照这个要求，你画个设计图给我看看~

**Comment by zhangjiagithub** [comment]
![image](https://user-images.githubusercontent.com/48313333/112433831-c4f8cc00-8d7d-11eb-99fd-2a29203503ca.png)

**Comment by hustcc** [comment]
参考这个：https://g2plot.antv.vision/zh/examples/line/multiple#marker-active

这个图实际上是：

1. 线和点的混合
2. 线根据不同的 type 颜色不一样
3. 点根据不同的 type 形状不一样
