### ISSUE TITLE
不支持 ie 的问题

### ISSUE THREAD

**Issue by zhfanrui** [antvis/g2#335]
* **G2 Version**: latest
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

dataview 的 transform 不支持 ie，在 callback 函数处报错。

**Comment by leungwensen** [comment]
具体哪个 transform，IE 的版本是？

**Comment by zhfanrui** [comment]
``` js
dv.transform({
                type: 'sort',
                callback(a, b) { // 排序依据，和原生js的排序callback一致
                    return a.log10 - b.log10;
                }
            });
```
ie 11.1106

**Comment by leungwensen** [comment]
具体怎么报错？贴一下错误信息吧

**Comment by zhfanrui** [comment]
![image](https://user-images.githubusercontent.com/6560377/34353025-d2a6dd38-ea60-11e7-879c-b297cfbd17b4.png)

**Comment by leungwensen** [comment]
你在 IE 11 里不能用对象的属性简写。 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer
