### ISSUE TITLE
运行 site:build 命令报错？

### ISSUE THREAD

**Issue by jefferyssy** [antvis/G2#3352]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/antvis/G2/pull/3349/checks?check_run_id=2200261016](https://github.com/antvis/G2/pull/3349/checks?check_run_id=2200261016)

### Steps to reproduce
npm install && npm start site:build

| Environment | Info |
|---|---|
| g2 | 4.1.13 |
| System | - |
| Browser | - |

**Comment by xrkffgg** [comment]
这个 Action 目前有点问题，可以先不用管。

**Comment by visiky** [comment]
这个是因为 webpack 修改了，以及加了 .babelrc，本地跑 `npm start` 也有问题；暂时先不管，本地需要开发的话，手动先忽略 babelrc，后续再修改
