### ISSUE TITLE
slider 需要外部控制范围

### ISSUE THREAD

**Issue by ValueLan** [antvis/G2#3354]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
slider 需要外部控制范围

### What does the proposed API look like?
slider 需要外部控制范围

**Comment by hustcc** [comment]
盲猜一下，应该是这个：https://g2.antv.antgroup.com/manual/core/slider
