### ISSUE TITLE
地图图表中getXY获取到的坐标为NaN

### ISSUE THREAD

**Issue by pigjs** [antvis/G2#3359]
例子如下：
const point = chart.getXY(data[0])
chart.showTooltip(point)

其中获取到的point坐标为NaN，在其他图表中能正常获取的

**Comment by maplor** [comment]
如果用了 view，需要在对应的 view 调用：
```
view.getXY(data);
```

**Comment by psyprogrammer** [comment]
> 如果用了 view，需要在对应的 view 调用：
> 
> ```
> view.getXY(data);
> ```

没用到view，还是NaN
