### ISSUE TITLE
漏斗图 annotation 文字无法居中

### ISSUE THREAD

**Issue by ZHNLN0** [antvis/G2#3373]
* **G2 Version**: 4.1.14
* **Platform**: MacOS 11.2.3
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codesandbox.io/s/quizzical-platform-npyn8

漏斗图 annotation 文字无法居中，仅按照官网代码修改了数据
原demo地址   https://g2.antv.vision/zh/examples/funnel/funnel#basic

**Comment by pearmini** [comment]
已经修复
