### ISSUE TITLE
全局配置 axis 的 label 为 html 绘制

### ISSUE THREAD

**Issue by ajsdhf** [antvis/g2#338]
* **G2 Version**: 3.x
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![default](https://user-images.githubusercontent.com/3477307/34378035-fd140a86-eb2e-11e7-8a1c-f0517c3669f6.png)

目前 G2 的大小和 padding 都要手动传入，很容易出现图示 axis 的 label 展示不全的情况。

是否可以提供一个全局的配置，能使所有的 axis 的 label 都使用 html 来绘制

**Comment by leungwensen** [comment]
@ajsdhf 祯老板，我暂时不加 API 的话，可以用这种方式来支持，你看看够不够用：
```js
    G2.Global.setTheme({
      axis: {
        bottom: {
          label: {
            htmlTemplate(text, item, index) {
              return text; // 返回组装好的 HTML
            }
          }
        }
      }
    });
```

**Comment by ajsdhf** [comment]
👍 够用
