### ISSUE TITLE
BUG: 图标超出容器，autoFix失效

### ISSUE THREAD

**Issue by Jokerdeath** [antvis/G2#3380]
1.容易设置宽高，width="100%",height="400px"
2.new chart()设置autoFix为true
3.打开页面，图表超出容器，溢出到屏幕之外

**Comment by hustcc** [comment]
autoFit 不是 autoFix！

**Comment by Jokerdeath** [comment]
进行更改，sorry，是autoFit,描述打错了

**Comment by Jokerdeath** [comment]
// 修改autoFix第一次渲染超出父级容器的问题
    const e = document.createEvent('Event')
    e.initEvent('resize', true, true)
    window.dispatchEvent(e)

我使用了以上方法手动修复

**Comment by Jokerdeath** [comment]
![image](https://user-images.githubusercontent.com/54066483/115204230-d5a52380-a12a-11eb-8eaa-32207031d2f4.png)
