### ISSUE TITLE
图表超出容器，4.1.12版本

### ISSUE THREAD

**Issue by Jokerdeath** [antvis/G2#3381]
先上图：
![image](https://user-images.githubusercontent.com/54066483/115204550-2fa5e900-a12b-11eb-9d6e-4c5f2641e3c5.png)
![image](https://user-images.githubusercontent.com/54066483/115204715-611eb480-a12b-11eb-8e7a-0cc7544058bf.png)

问题描述：
设置容器宽度100%，设置autoFit: true
图标超出容器

这里进行了手动修复：
// 修改autoFit第一次渲染超出父级容器的问题
    const e = document.createEvent('Event')
    e.initEvent('resize', true, true)
    window.dispatchEvent(e)

版本：4.1.12

**Comment by Jokerdeath** [comment]
初次渲染会有，再次渲染消失

**Comment by hustcc** [comment]
一定是的你 外部 容器就是这么大的。调试一下图表大小和图表容器的大小，图表是跟随容器大小的！

**Comment by lgy1159** [comment]
我也遇到了这个问题，确认外部容器宽度 是600 画布宽度不知道为什么是1200 ，用了 changeSize 去改变宽度也没有用
