### ISSUE TITLE
G2传入数据精度过高时使用scale的r-pretty的tick-method会卡死

### ISSUE THREAD

**Issue by KedAyAyA** [antvis/G2#3392]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/KedAyAyA/pen/LYxqdgM](https://codepen.io/KedAyAyA/pen/LYxqdgM)

### Steps to reproduce
1. 点击button
2. 卡死，循环动画不再播放

| Environment | Info |
|---|---|
| g2 | 4.1.14 |
| System | Mac |
| Browser | Chrome latest |

**Comment by pearmini** [comment]
@yuzhanglong 这个问题现在 scale 0.3.x 的版本解决了吗？

**Comment by pearmini** [comment]
目前这个问题在最新版本里面的 g2 已经修复了。
