### ISSUE TITLE
条形图scale设置nice:true时，不显示annotation

### ISSUE THREAD

**Issue by quicklearning123** [antvis/G2#3408]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/case/bar#bar1](https://g2.antv.vision/zh/examples/case/bar#bar1)

### Steps to reproduce
设置 chart.scale('value', { nice: true }); 时 必现

期望在红框处显示实际的value

![image](https://user-images.githubusercontent.com/70048681/117398596-3e650c00-af31-11eb-8b9f-aef0a7f27361.png)

| Environment | Info |
|---|---|
| g2 | 4.1.16 |
| System | mac |
| Browser | chrome |

**Comment by quicklearning123** [comment]
![image](https://user-images.githubusercontent.com/70048681/117398655-5e94cb00-af31-11eb-86bb-a5737aface8f.png)

**Comment by pearmini** [comment]
下面这样写没有问题：

```js
chart.scale({
  value: {
    max: 1400,
    min: 0,
    nice: true
  }
});
```
你后面对 value 的配置覆盖了之前的，导致 max：1000，所以将金融保险的 label 绘制在可视区域之外了。

**Comment by quicklearning123** [comment]
![image](https://user-images.githubusercontent.com/70048681/120599745-7735c980-c47a-11eb-8dd9-3c684acf4a0b.png)
这就是我提的问题啊，为啥没解决就关掉了……

**Comment by pearmini** [comment]
之前太久没有回复所以就把 issue 关了，可以设置 scale 的 range，使用方法如下：

```js
chart.scale({
  value: {
    range: [0, 0.9],
    alias: '销量（百万）',
  },
});
```
这个问题和 nice 关系不大，在官方网站案例中你把 max: 1400 去掉后，有没有 nice 都会出现问题，上面的 range 的意思是在这个范围内绘制图形：`[width * 0, width * 0.9]`。
