### ISSUE TITLE
调用 chart.legend() 进行图例的配置，autoWrap选项无效

### ISSUE THREAD

**Issue by since92x** [antvis/G2#3409]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/line/basic#curved](https://g2.antv.vision/zh/examples/line/basic#curved)

### Steps to reproduce
chart.legend({
  autoWrap: true,
});

| Environment | Info |
|---|---|
| g2 | 4.1.16 |
| System | - |
| Browser | - |

**Comment by ai-qing-hai** [comment]
> * [ ] 我已经搜索了这个存储库的[问题](https://github.com/antvis/g2/issues)，并相信这不是重复的。
> 
> ### 转载链接
> https://g2.antv.vision/zh/examples/line/basic#curved
> 
> ### 重现步骤
> chart.legend({
> autoWrap: true,
> });
> 
> 环境	信息
> g2	4.1.16
> 系统	——
> 浏览器	——

好像 legend 并没有 autoWrap 的配置吧

**Comment by visiky** [comment]
G2 4.0 不提供
