### ISSUE TITLE
How to emit an event when clicking the blank

### ISSUE THREAD

**Issue by NoraGithub** [antvis/g2#341]
When we are using the tool, we would click the blank to cancel the selection. So how can I emit such an event? I can only find to way to emit an event when clicking the geom. And the chart is drawn by canvas, the jquery doesn't help.

Would you please give a suggestion for that?

**Comment by dxq613** [comment]
```
chart.on('plotclick',function(ev){
  if(!ev.shape){
    // to do something
  }
});
```

**Comment by dxq613** [comment]
```js
chart.on('click',function(ev){
  if(!ev.shape){
    // to do something
  }
});
```

all the region can trigger click event.

**Comment by NoraGithub** [comment]
Thank @dxq613 .  It's such an elegant solution. 
As it's marked with labels, it depends on you whether to close it. @leungwensen

**Comment by NoraGithub** [comment]
@dxq613 
请问现在 ev.shape 是不是不能判断空白处的点击时间了呢？我升级以后发现失效了

**Comment by ruofee** [comment]
https://github.com/antvis/g2/issues/831
