### ISSUE TITLE
chart.scale()里面的参数max为NaN的时候导致浏览器崩溃

### ISSUE THREAD

**Issue by Break-2020** [antvis/G2#3413]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/bar/basic#basic](https://g2.antv.vision/zh/examples/bar/basic#basic)

### Steps to reproduce
chart.scale('population', { nice: true , max:NaN});
只要max是NaN，就会引发崩溃，这种情况应该只让这个图表绘制不出报错什么的就可以了吧。

![image](https://user-images.githubusercontent.com/73464509/117775086-bb172380-b26c-11eb-8d91-1c1a3ab33c92.png)

![image](https://user-images.githubusercontent.com/73464509/117774918-8acf8500-b26c-11eb-8690-1a5f7c5bdf95.png)

| Environment | Info |
|---|---|
| g2 | 4.1.16 |
| System |  90.0.4430.93（正式版本） （64 位） |
| Browser | Chrome |

**Comment by yuzhanglong** [comment]
这个 bug 在新版的 scale 已经修复。

**Comment by yuzhanglong** [comment]
> > [antvis/scale#117](https://github.com/antvis/scale/pull/117)
> 
> 哦哦，那现在4.1.16上也修复了吗

暂时没有，等下我会处理~

**Comment by yuzhanglong** [comment]
已修复，最新版本 0.3.10

**Comment by Break-2020** [comment]
> 已修复，最新 scale 版本 0.3.10。直接本地重新安装依赖，保证底层 scale 版本是 0.3.10 即可。

好的
