### ISSUE TITLE
雷达图折线连接错误

### ISSUE THREAD

**Issue by atdow** [antvis/G2#3423]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kind-mclean-95czm?file=/src/index.js)

### Steps to reproduce
折线连接是有问题的，如下图所示：
![image](https://user-images.githubusercontent.com/52809115/118465037-1301ce80-b734-11eb-89e1-1073952ff802.png)

| Environment | Info |
|---|---|
| g2 | 4.1.16 |
| System | win10 |
| Browser | choreme |

**Comment by hustcc** [comment]
```ts
chart.line({
  connectNulls: true,
}).position("item*score");
```

对于有 null 的，注意看看自己的需求，是否需要 connectNulls。
