### ISSUE TITLE
雷达图为0的数据有些有tooltip虚线，有些没有

### ISSUE THREAD

**Issue by atdow** [antvis/G2#3425]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wizardly-microservice-m5mvp?file=/src/index.js)

### Steps to reproduce
如下图所示：
![image](https://user-images.githubusercontent.com/52809115/118600301-65e68f00-b7e3-11eb-8721-da9e85ce78c8.png)

| Environment | Info |
|---|---|
| g2 | 4.1.16 |
| System | win10 |
| Browser | choreme |

**Comment by hustcc** [comment]
确实是有问题的，目测应该是因为数据点为 0，所以直接识别成 tooltip 的线防线为向右的。临时解决：

```ts
chart.scale("score", {
  min: -0.01,
  max: 5
});
```

我明天来看看具体的原因。

**Comment by atdow** [comment]
> 确实是有问题的，目测应该是因为数据点为 0，所以直接识别成 tooltip 的线防线为向右的。临时解决：
> 
> ```ts
> chart.scale("score", {
>   min: -0.01,
>   max: 5
> });
> ```
> 
> 我明天来看看具体的原因。
好的，非常感谢

**Comment by jefferyssy** [comment]
请问下 这个问题后来有没有解决。我看了下最新的G2版本还有这个问题

**Comment by jefferyssy** [comment]
@hustcc 麻烦问下，这个问题有解决吗？我看了下最新的G2还是这样。如果设置了min=-0.01 展示效果又不对，中间有个圈
