### ISSUE TITLE
streamgraph 展示出错

### ISSUE THREAD

**Issue by visiky** [antvis/G2#3434]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/en/examples/area/streamgraph#streamgraph](https://g2.antv.vision/en/examples/area/streamgraph#streamgraph)

### Steps to reproduce
https://g2.antv.vision/en/examples/area/streamgraph#streamgraph

 | Expected | Actually |
| ---|---|
| ![image](https://user-images.githubusercontent.com/15646325/119263243-ce34d680-bc10-11eb-8c86-137372a008d1.png)| ![image](https://user-images.githubusercontent.com/15646325/119263255-e86eb480-bc10-11eb-883d-b6c315d23fd4.png) |

| Environment | Info |
|---|---|
| g2 | 4.1.16 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
```diff
+ .area({sortable: true})
```

我在 demo 中提一个 pr。
