### ISSUE TITLE
折线图Line 如何动态控制label的展示与消失

### ISSUE THREAD

**Issue by songjoe** [antvis/G2#3443]
鼠标移到折线上展示label
鼠标移出的时候label消失
不要chart重新渲染

请问有什么方法可以实现

**Comment by hustcc** [comment]
这不就是 tooltip 嘛？😀 直接用自定义 tooltip 中的 customContent 配置就可以实现。参考官网：https://g2.antv.vision/zh/docs/manual/tutorial/tooltip/#%E8%87%AA%E5%AE%9A%E4%B9%89-tooltip
