### ISSUE TITLE
Heat Map add extra legend in each render

### ISSUE THREAD

**Issue by red010182** [antvis/g2#345]
I need to update data multiple times on a heat map, however, every time the chart rendered again, an extra unnecessarily legend generated. 

* **G2 Version**: 3.0.2
* **Platform**: OSX, Chrome
* **Mini Showcase(like screenshots)**:  ![](https://i.imgur.com/6F29M7s.png)
* **CodePen Link**: https://codepen.io/alstontsao/pen/QapveN

**Comment by leungwensen** [comment]
It is a bug caused by the lifecycle management before version 3.0.3, you can upgrade to 3.0.3 (or above) to solve this problem.
