### ISSUE TITLE
The "brush" interaction doesn't work correctly

### ISSUE THREAD

**Issue by mostopalove** [antvis/G2#3453]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/mostopalove/pen/jOBZYRE](https://codepen.io/mostopalove/pen/jOBZYRE)

### Steps to reproduce
1) Select any part of chart
Expected result: Part of the diagram is displayed
Actual result: Nothing is displayed

| Environment | Info |
|---|---|
| g2 | 4.1.17 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
Sorry, due to problems in the program's architecture design, we are unable to effectively fix the issues. But fixed in G2 5.0, you can have a try.
