### ISSUE TITLE
legend中itemValue使用alignRight内容过长时内容会翻转展示

### ISSUE THREAD

**Issue by Josephineisis** [antvis/G2#3454]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/relaxed-shadow-w8fcm?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
`// 设置了item宽度 itemValue配置alignRight为true 其中某些值的内容较长`

![image](https://user-images.githubusercontent.com/23067473/120582639-6166db00-c45f-11eb-91c6-1d4f78d9d928.png)

`// 内容不超出默认长度时正常显示只是右对齐，内容较长时文字翻转了%符号在前`
![image](https://user-images.githubusercontent.com/23067473/120582818-b99ddd00-c45f-11eb-8828-3cb6fe1bddbb.png)

| Environment | Info |
|---|---|
| g2 | 4.1.17 |
| System | - |
| Browser |  Google Chrome 90.0.4430.212 |

**Comment by yehoan** [comment]
想问你一下 为什么我设置了alignRight 然后他直接出去了  itemValue 直接出去了

**Comment by Josephineisis** [comment]
> 想问你一下 为什么我设置了alignRight 然后他直接出去了 itemValue 直接出去了

有例子吗不是太能分析到你的问题

**Comment by pearmini** [comment]
> > 想问你一下 为什么我设置了alignRight 然后他直接出去了 itemValue 直接出去了
> 
> 有例子吗不是太能分析到你的问题

我看你之前提的这个问题已经解决了？

**Comment by Josephineisis** [comment]
> > > 想问你一下 为什么我设置了alignRight 然后他直接出去了 itemValue 直接出去了
> > 
> > 
> > 有例子吗不是太能分析到你的问题
> 
> 我看你之前提的这个问题已经解决了？

还没有 官方没有处理也没有回复

**Comment by pearmini** [comment]
目前这样符合你的预期吗？
![image](https://user-images.githubusercontent.com/49330279/132186114-6ed3ffc1-6600-4514-b8f2-dc235a0d9b29.png)

**Comment by Josephineisis** [comment]
> 目前这样符合你的预期吗？
> ![image](https://user-images.githubusercontent.com/49330279/132186114-6ed3ffc1-6600-4514-b8f2-dc235a0d9b29.png)

目前这样是当数值较小时没有问题，如果count值较大就会出现我所叙述的问题，因为数据值是不确定的，暂时无法避免这个情况出现

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/132187290-107dbae5-5c70-45f1-940e-6ad9eb9b1b49.png)
怎么控制itemValue 的偏移值 别那么大

**Comment by yehoan** [comment]
我这个都超出去了

**Comment by yehoan** [comment]
知道怎么设置吗   这个太难看了 隔了十万八千里

**Comment by Josephineisis** [comment]
> 知道怎么设置吗 这个太难看了 隔了十万八千里

![image](https://user-images.githubusercontent.com/23067473/132187752-5262e2ed-819b-4689-8560-3785f643ba85.png)
我的代码例子中这里可以设置legend X轴的偏移量

**Comment by yehoan** [comment]
这个是全部的把 我知道这个但是我要的是单独设置itemValue的偏移量

**Comment by yehoan** [comment]
你这个是设置整体的

**Comment by yehoan** [comment]
我现在的问题是因为itemValue 和item 的间距太大了

**Comment by Josephineisis** [comment]
> 我现在的问题是因为itemValue 和item 的间距太大了

https://g2.antv.vision/zh/docs/api/general/legend#legendoptionitemwidth 你可以看看是不是你itemWidth过宽

**Comment by yehoan** [comment]
好的 谢谢我去试试

**Comment by yehoan** [comment]
我在苹果的一体机上 发现了这个问题... 就是%XX的问题  在windows 的电脑上又是正常的
