### ISSUE TITLE
双y轴的刻度线怎么设置对齐

### ISSUE THREAD

**Issue by bancangyanyu** [antvis/G2#3459]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
双y轴的刻度线对齐

### What does the proposed API look like?
双y轴的刻度线对齐

**Comment by hustcc** [comment]
目前暂时无法做到，这个算法比较复杂。当前解法暂时为以下两种：

1. 同步 双轴的 max min 范围，这样自然是对其的
2. 关闭其中一层，防止 grid 线条会很混乱

**Comment by hustcc** [comment]
@pearmini 可以考虑下两个 scale 同步 ticks 的算法~

**Comment by pearmini** [comment]
好的，我去了解一下

**Comment by BraveHead** [comment]
@bancangyanyu 要是你的对应Y轴上的 `scale` 中的 `tickCount` 的数量是自定义设置的话，那么双 `Y`轴上的 `tickCount`可以设置相同，可以解决不对齐的问题。

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/165254248-4697534e-a54a-4b25-b375-94b5a4678a9d.png)

**Comment by yehoan** [comment]
不知道为什么会这样...

**Comment by yehoan** [comment]
我看示例的 不是这样的啊 至少刻度线是统一的才对啊

**Comment by cdx111** [comment]
可以参考我的做法
 meta: {
      tt: {
        alias: '在租天数',
        sync: true,
        min: 0,
        max: max1,
        tickInterval: getNumber(max1) / 5,
        tickCount: 5,
      },
      amount: {
        alias: '新增订单金额',
        sync: true,
        min: 0,
        max: max2,
        tickInterval: getNumber(max2) / 5,
        tickCount: 5,
      },
    }

**Comment by Calmio-Y** [comment]
> 可以参考我的做法 meta: { tt: { alias: '在租天数', sync: true, min: 0, max: max1, tickInterval: getNumber(max1) / 5, tickCount: 5, }, amount: { alias: '新增订单金额', sync: true, min: 0, max: max2, tickInterval: getNumber(max2) / 5, tickCount: 5, }, }

getNumber是什么方法

**Comment by cdx111** [comment]
> getNumber

一个普通字符串转number的方法

**Comment by pearmini** [comment]
可以参考一下这个 PR https://github.com/antvis/G2/pull/6380
