### ISSUE TITLE
How does it possible to get value of point by click? Not data of whole chart.

### ISSUE THREAD

**Issue by mostopalove** [antvis/G2#3464]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/mostopalove/pen/XWMEwLV](https://codepen.io/mostopalove/pen/XWMEwLV)

### Steps to reproduce
1) Click on some point of chart
Expected result: You received data of point
Actual result: You received data of whole chart

| Environment | Info |
|---|---|
| g2 | 4.1.17 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
对于线图，每一个 element 对应的是一条线，如果确实要选中点，可以额外加一个 point geometry，然后监听事件 point:click。
