### ISSUE TITLE
Chart图表空数据的显示左右没对齐

### ISSUE THREAD

**Issue by NicolaCage** [antvis/G2#3471]
![image](https://user-images.githubusercontent.com/37568394/121478216-5ed62980-c9fb-11eb-8a87-5d9532fb28ed.png)
如图，有数据时左边有刻度还好，没有数据时区别很明显

**Comment by hustcc** [comment]
代码是什么样了，设置 padding 了？

**Comment by NicolaCage** [comment]
是我们这边问题的，这边之前设置了默认的padding
