### ISSUE TITLE
🐛 [BUG] Tree Facet render error when changeData

### ISSUE THREAD

**Issue by visiky** [antvis/G2#3477]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.
- [ ] fix: https://github.com/antvis/G2Plot/issues/2638

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/facet-changedata-8v9hf?file=/src/index.js)

### Steps to reproduce
https://codesandbox.io/s/facet-changedata-8v9hf?file=/src/index.js

| Environment | Info |
|---|---|
| g2 | 4.1.18 |
| System | - |
| Browser | - |

**Comment by KedAyAyA** [comment]
#3339
