### ISSUE TITLE
Pie chart left align

### ISSUE THREAD

**Issue by truedrug** [antvis/G2#3481]
* **G2 Version**: 4.1.7
* **Platform**: macos
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/19340495/122416416-5905b880-cfa6-11eb-9176-d544fcfa9e9e.png)

* **CodePen Link**: NA

I have a container inside of which I have a pie chart rendered. On a wider viewport, the pie is looking fine at the center with the legend being at the right. But if I start to look at in a smaller device or I shrink the browser width, then the legend starts overlapping on the chart

I am using media queries to decrease the font-size of the legend text, setting offsetX values and trying different things, just wanted to check, if we can left align the chart using any existing config

Any help will be greatly appreciated

TIA

**Comment by hustcc** [comment]
Determine the position of the legend based on the width of your screen.

- When on a wider viewport, show legend right
- Else bottom
