### ISSUE TITLE
求助 混合柱状图 与折线的配合使用

### ISSUE THREAD

**Issue by tk231321** [antvis/g2#349]
比如我有2组数据，其中2组作为分组柱状图，剩下2个折线
如：[
  {day:'1天',a:1,b:11,c:21,d:21},
  {day:'2天',a:2,b:13,c:11,d:31},
  {day:'3天',a:3,b:11,c:51,d:11},
  {day:'4天',a:4,b:12,c:11,d:21}
]
a，b混合柱状。c，d单独

**Comment by sunscheung** [comment]
@vickmeng  这个柱状图 与折线是如何展示的
