### ISSUE TITLE
chart 图的缩放问题

### ISSUE THREAD

**Issue by NicolaCage** [antvis/G2#3494]
![image](https://user-images.githubusercontent.com/37568394/123401561-80c5d380-d5d9-11eb-82a5-7a0c1a7670f1.png)
复现步骤（100%能复现的）
1. 长按选中一直往下拖到鼠标光标离开chart区域
2. 离开区域后，发现未触发图标的缩放事件，并且选中状态框一直存在，就卡住了

**Comment by NicolaCage** [comment]
之前在群里问过这个问题，当时有人回复说X轴的数据类型是number的问题，但是我toString了，问题还是存在

**Comment by NicolaCage** [comment]
还需要提供什么信息吗

**Comment by hustcc** [comment]
需要具体的代码 ，最好直接使用 codepen 提供一个 live demo。
