### ISSUE TITLE
堆叠条形图axis下的label被遮挡

### ISSUE THREAD

**Issue by Fitz-Wen** [antvis/G2#3498]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3h0kb.csb.app/](https://3h0kb.csb.app/)

### Steps to reproduce
axis的label被遮挡

| Environment | Info |
|---|---|
| g2 | 4.1.19 |
| System | - |
| Browser | - |

![image](https://user-images.githubusercontent.com/26396034/124423187-3beb2b00-dd97-11eb-8ae4-01a70db782bc.png)
![image](https://user-images.githubusercontent.com/26396034/124423213-473e5680-dd97-11eb-9f43-dd360857b409.png)

**Comment by hustcc** [comment]
下面这个图的 label 不是没有被遮挡吗？自己解决问题了吗？
