### ISSUE TITLE
官方实例的问题

### ISSUE THREAD

**Issue by tk231321** [antvis/g2#350]
示例中为何没有展示代码中的legend？？
![image](https://user-images.githubusercontent.com/19486247/34477889-61124626-efd8-11e7-969e-df7d88717aec.png)
![image](https://user-images.githubusercontent.com/19486247/34477931-a03377d0-efd8-11e7-8a9b-42e3912655a1.png)

**Comment by dxq613** [comment]
这种混合的图表，需要自己自定义 legend 

https://antv.alipay.com/zh-cn/g2/3.x/demo/other/double-axes.html

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/gallery/g2/double-axes.html
