### ISSUE TITLE
词云图配置state会出现渲染错误

### ISSUE THREAD

**Issue by wenbin-im** [antvis/G2#3500]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/relaxed-https-ynig1?file=/index.ts)

### Steps to reproduce
1、在词云图上point配置active state
2、鼠标悬浮到g、y上
3、字体的baseline下不会响应state的样式

![image](https://user-images.githubusercontent.com/11540271/124450779-56cd9780-ddb7-11eb-95d0-0e2a3a1581fe.png)

| Environment | Info |
|---|---|
| g2 | 4.1.19 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
看起来是 g y 等字母的 stroke 样式上有问题。

**Comment by hustcc** [comment]
在 G2 5.0 中解决。参考：https://g2.antv.antgroup.com/examples/general/text/#wordCloud-mask
