### ISSUE TITLE
The head of the titles are cuted

### ISSUE THREAD

**Issue by jinairenshi** [antvis/G2#3503]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g2-reproduction-template-6ipi1)

### Steps to reproduce
When I was using chart.facet('rect', cfg: FacetCfg)时，the head of columnTitle is cuted

| Environment | Info |
|---|---|
| g2 | 4.1.11 |
| System | - |
| Browser | - |

![image](https://user-images.githubusercontent.com/57122054/124464258-8768fd80-ddc6-11eb-962e-b6ddc9d8e2ef.png)
![image](https://user-images.githubusercontent.com/57122054/124464314-a2d40880-ddc6-11eb-819a-7e28bb52446f.png)

**Comment by hustcc** [comment]
The codepen is error.
