### ISSUE TITLE
tooltip:change事件，tooltip显示不正常

### ISSUE THREAD

**Issue by zmiaozzz** [antvis/g2#351]
* **G2 Version**:3.0.2
* **Platform**:mac
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:https://codepen.io/zmiaozzz/pen/eyRqgM

如题，例子：https://codepen.io/zmiaozzz/pen/eyRqgM
按照官网的例子，设置state状态量来实现图表的联动，柱图tooltip change的时候更新饼图数据，但是hover的时候tooltip显示不稳定，一直抖动，抖动完之后tooltip消失。发现是ds.setState('currentState', items[0].title)的问题，好像图表在一直刷新一样。

**Comment by leungwensen** [comment]
监听 tooltip 事件的图表关联的数据不要监听 state 变化就好了

```js
var dvForAll = ds
    .createView('populationByAge', {
        watchingStates: [], // 用空数组，使得这个实例不监听 state 变化
    }) // 在 DataSet 实例下创建名为 populationByAge 的数据视图
    .source(data);
```
