### ISSUE TITLE
🐛 大数据量 interval 填充色存在透明度的感觉

### ISSUE THREAD

**Issue by visiky** [antvis/G2#3521]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.
- [ ] fix: https://github.com/antvis/G2Plot/issues/2702

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g2plot-2702-gy2pw)

### Steps to reproduce
https://codesandbox.io/s/g2plot-2702-gy2pw

| Environment | Info |
|---|---|
| g2 | 4.1.20 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
这应该是视觉问题 或者 屏幕硬件的处理逻辑，数据量已经大于屏幕像素了，而柱子和柱子之间是有白色空隙，所以处理逻辑就是一个像素既要显示白色，又要显示设置的红色。

所以视觉上感觉是有透明度。
