### ISSUE TITLE
画板基线annotation().line问题

### ISSUE THREAD

**Issue by NicolaCage** [antvis/G2#3524]
![image](https://user-images.githubusercontent.com/37568394/126098500-0becef74-b6bf-4ecb-854d-11989317fc59.png)
如果设置的基线小于当前刻度的最小数，annotation().line基线会显示在画板下面，这个目前有办法处理吗？这个刻度最小数可以动态获取吗？

**Comment by hustcc** [comment]
```ts
chart.scale('y-field', { min: Math.min(数据中最小值， annotaion 的最小值) });
```
