### ISSUE TITLE
pie chart animaion

### ISSUE THREAD

**Issue by Kun8018** [antvis/G2#3526]
![2](https://user-images.githubusercontent.com/41263766/126137017-71b934a5-21a9-4f3a-8e12-c1044a00ffb9.png)

饼图出现这种不规则动画，只是动画过程中有问题，加载完是正常的，加了forcefit()动画完全无效了，请问这样是数据有问题还是样式有问题？

**Comment by hustcc** [comment]
麻烦提供一个复现的 DEMO 地址或者代码。
