### ISSUE TITLE
折线图的点击事件，能返回单个点吗？现在这个target是返回所有的点

### ISSUE THREAD

**Issue by visiky** [antvis/G2#3528]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/antvis/component/issues/174](https://github.com/antvis/component/issues/174)

### Steps to reproduce
https://github.com/antvis/component/issues/174

| Environment | Info |
|---|---|
| g2 | 4.1.20 |
| System | - |
| Browser | - |

**Comment by imyuxh** [comment]
> 

您好 请问具体要如何 根据 xy 用 coordinate 转数据呢 文档里貌似没有相关介绍

**Comment by hustcc** [comment]
给个伪代码：

```ts
chart.on('line:click', (e) => {
  const { x, y } = e;
  const { X, Y } = coordinate.invert({ x, y }); // x y 是 0 ~ 1 之间的值
  const idx = Math.floor(x / (1 / data.length)); // data.length 就是折线图数据点的个数。 
})
```
