### ISSUE TITLE
柱状图 如果数据差异很大 例如有多个个位数和一个四位数 如果限制高度 四位数的数字标注无法显示

### ISSUE THREAD

**Issue by luoluoluoluoluoluo** [antvis/g2#354]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/15343300/34553745-2e541736-f164-11e7-9a72-5461d177a4d7.png)
当数据差异很大时，如果不限制高度，三万多的DRM很高，但是其他的都很低，而且看起来差不多，没有差异。如果限制高度，三万多的DRM数字标注无法显示。
请问是否有很好的解决方案？谢谢

**Comment by leungwensen** [comment]
https://github.com/antvis/g2/issues/324#issuecomment-353822442

连续数据，数据值非常离散的时候，可以试试用 log 之类的 scale https://antv.alipay.com/zh-cn/g2/3.x/tutorial/scale.html#_log-%E5%BA%A6%E9%87%8F%E7%9A%84%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF
