### ISSUE TITLE
柱状图 数据差异太大 多个个位数和一个四位数同时存在的话 限制图的高度的话四位数的数据标识无法显示

### ISSUE THREAD

**Issue by luoluoluoluoluoluo** [antvis/g2#355]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/15343300/34555283-cfb51010-f16b-11e7-8190-62c2129cb392.png)
r如果不限制图的高度，由于最高的一项与其他数据差异太大，其他各位数据看不出差异。限制图的高度，则四位数的纵轴数据标注无法显示。
是否有好的解决方案，谢谢！

**Comment by leungwensen** [comment]
https://github.com/antvis/g2/issues/354

https://github.com/antvis/g2/issues/324#issuecomment-353822442

连续数据，数据值非常离散的时候，可以试试用 log 之类的 scale https://antv.alipay.com/zh-cn/g2/3.x/tutorial/scale.html#_log-%E5%BA%A6%E9%87%8F%E7%9A%84%E4%BD%BF%E7%94%A8%E5%9C%BA%E6%99%AF
 
请不要重复提交 issue
