### ISSUE TITLE
ipad 的ipados15bate4系统 或者 macbook 最新系统版本，g2 会死循环，导致页面失去响应

### ISSUE THREAD

**Issue by vickey-chen** [antvis/G2#3556]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g2-reproduction-template-6ipi1?file=/src/index.js:7-9)

### Steps to reproduce
1、将ipadOs 14 升级到 15 版本
2、chrome 或者 safari 打开 含G2图表的页面
3、执行渲染（chart.render)
4、浏览器失去响应
---
官方的barchart 就可以复现。逻辑执行到 chart.render() 后，浏览器才失去响应的。

| Environment | Info |
|---|---|
| g2 | 4.1.22 |
| System | ios 最新版本：  ipadOs 15 bate4 / macos 12 |
| Browser | chrome / safari 均存在 |

**Comment by potato-sauce** [comment]
iPhone上同样存在这个问题。
iPhone11 ios15.0(19A5318f)
访问官网的饼图就会导致页面奔溃失去响应，intervalView.interval().position执行到这一段就会崩溃

**Comment by Darsoon** [comment]
现在有解决方案吗，访问 G2 页面都会崩溃

**Comment by pearmini** [comment]
> 现在有解决方案吗，访问 G2 页面都会崩溃

也是手机吗？

**Comment by Darsoon** [comment]
> > 现在有解决方案吗，访问 G2 页面都会崩溃
> 
> 也是手机吗？

是呀 iOS 15

**Comment by visiky** [comment]
尝试降级看下哪个版本才出现的问题？

**Comment by potato-sauce** [comment]
> 尝试降级看下哪个版本才出现的问题？

ios15 RC出了后也是验证不OK的

iPhone8 iOS 14.6(18F72) 验证OK的，升级iOS 15.0(19A344) 就不行了
iPhone12Pro Max iOS 15.0(19A344) 验证不OK

**Comment by potato-sauce** [comment]
> 尝试降级看下哪个版本才出现的问题？

15.0RC出了还是会存在这个问题，下周就会推ios就会推送15.0正式版本的更新了，影响还是很大的，直接让整个页面无响应了

**Comment by pearmini** [comment]
已经修复：https://github.com/antvis/G2/pull/3640
