### ISSUE TITLE
图例信息过多显示不全的问题

### ISSUE THREAD

**Issue by luoluoluoluoluoluo** [antvis/g2#356]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/15343300/34561045-33d7d9a8-f183-11e7-94b2-a1755b609696.png)

  https://antv.alipay.com/zh-cn/g2/3.x/demo/other/streamgraph.html
![image](https://user-images.githubusercontent.com/15343300/34564466-c0782e4a-f191-11e7-8561-572dd52e3dd8.png)

该示例的html模板是？

**Comment by leungwensen** [comment]
模版是默认模版，要自定义的画请看文档： https://antv.alipay.com/zh-cn/g2/3.x/tutorial/legend.html#_%E4%BD%BF%E7%94%A8-html-%E6%B8%B2%E6%9F%93%E5%9B%BE%E4%BE%8B
