### ISSUE TITLE
chart line don't render when data is exist null

### ISSUE THREAD

**Issue by speanut-land** [antvis/G2#3565]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/speanut-land/pen/vYmvjqG](https://codepen.io/speanut-land/pen/vYmvjqG)

### Steps to reproduce
Wait for the timer to change the data to Null, then need to manually hover, the chart will be re-rendered, 

| Environment | Info |
|---|---|
| g2 | 4.1.23 |
| System | - |
| Browser | - |

---
1.Note that the chart animation needs to be turned off, otherwise, re-render, no expected effect
2.When the data is null, expect to behave as a breakpoint and chart re-render

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/135417137-9131da5c-ae1a-4219-b5f6-d67f2c835f30.png)

**Comment by speanut-land** [comment]
设置了connectNulls并不能解决问题，example中数据通过setTimeout修改了俩次，"不包含Null" - "包含Null" - "不包含Null"，在最后一次的"不包含Null"图表没有渲染出来，debug底层g-Canvas查看是数据变成NaN导致局部渲染出现了问题
