### ISSUE TITLE
饼图容器通过transform：scale缩放后，legend分页器无法点击

### ISSUE THREAD

**Issue by guohongshan** [antvis/G2#3567]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/interaction/others#pie-legend](https://g2.antv.vision/zh/examples/interaction/others#pie-legend)

### Steps to reproduce
1、增加data数据至legend出现分页
2、打开控制台给图标父容器添加样式：transform：scale（0.5）
3、点击分页器
4、发现无法点击

| Environment | Info |
|---|---|
| g2 | 4.1.23 |
| System | windows, mac |
| Browser | chrome92 |

---
transform：scale后，地图点击事件也是如此， 无法准确获取到点击的地区

**Comment by wenjingyuer** [comment]
不建议用scale，你这个效果是可以通过更改width height并配置chat的自适应实现的

**Comment by guohongshan** [comment]
> 不建议用scale，你这个效果是可以通过更改width height并配置chat的自适应实现的

历史原因，是图表的一个祖先元素用了scale。通过width height配置的话，很多组件要适配

**Comment by cnyballk** [comment]
const chart = new Chart({
      supportCSSTransform: true,
    });
这样就可以
