### ISSUE TITLE
散点图展示图例不完整

### ISSUE THREAD

**Issue by wenbin-im** [antvis/G2#3568]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
![image](https://user-images.githubusercontent.com/11540271/129311769-6054bddb-4459-4dd4-9338-ff781870889c.png)

[https://48ole.csb.app/](https://48ole.csb.app/)

### Steps to reproduce
1. 打开demo
2. 见图例

| Environment | Info |
|---|---|
| g2 | 4.1.23 |
| System | - |
| Browser | - |

---
数据中有‘2021-07-27’ ‘2021-07-29’ ‘2021-08-02’ ‘2021-08-04’，但是在图例中没有显示

**Comment by wenjingyuer** [comment]
这个是因为你的日期格式不标准，你手动制动p_date为cat类型就好了，另外你的scale配置写的很奇怪，哪里来的width和height？
https://codesandbox.io/s/brave-leakey-b60h6?file=/index.js

**Comment by wenjingyuer** [comment]
@wenbin-im
