### ISSUE TITLE
在angular中，无法使用fruchterman布局

### ISSUE THREAD

**Issue by yxzyxzyxz** [antvis/G2#3573]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://gitee.com/yxzyxz/g6-chart-hull.git](https://gitee.com/yxzyxz/g6-chart-hull.git)

### Steps to reproduce
启动angular后，发现fruchterman布局没有反应，配置如下
 `  const graph = new G6.Graph({
      container: 'container',
      width,
      defaultNode: {
        type: 'image',
        size: [100],
        clipCfg: {
          show: true,
          type: 'circle',
          r: 20
        },
        labelCfg: {
          position: 'bottom',
          offset: 10,
          style: {
            fill: '#666',
          },
        },
      },
      animate: true,
      height,
      modes: {
        default: ['drag-canvas', 'zoom-canvas', 'lasso-select'],
      },
      layout: {
        type: 'fruchterman',
        gravity: 2,
        preventOverlap: true,
        speed: 5,
        clustering: true,
        linkDistance: 60,
        nodeStrength: -10,
        edgeStrength: 0.1,
        gpuEnabled: true,
        workerEnabled: true
      },
    });`
| Environment | Info |
|---|---|
| g2 | 4.1.24 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
应该题错位置了，你使用的是 G6。
