### ISSUE TITLE
geojson取得的centroid点和高德地图里行政区域里的中心点不是同一个

### ISSUE THREAD

**Issue by Break-2020** [antvis/G2#3575]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/docs/manual/dataset/connector#geojson](https://g2.antv.vision/zh/docs/manual/dataset/connector#geojson)

### Steps to reproduce
在高德地图输入一个区域，如达川区，对应的点是行政区所在的中心点（107.511985,31.196365）。而通过

dv.source(geojsonData, {
  type: 'GeoJSON', // 别名 geo / geojson
});

这种方式取得的centroidX, centroidY 得到的是（107.41513947891403,31.11078512409564）。两者对应的不是一个位置。
请问如何能取到行政区域的中心点？看了代码好像这边并不能传什么参数去更改生成genjson中取得的中心点

![image](https://user-images.githubusercontent.com/73464509/129654927-1c6f443e-a9ab-45cd-9e29-3ce3cfadc379.png)

| Environment | Info |
|---|---|
| g2 | 4.1.24 |
| System |  90.0.4430.93（正式版本） （64 位） |
| Browser | Chrome |

**Comment by hustcc** [comment]
这个是 geo 数据上的问题。好像没有很好的解决办法。
