### ISSUE TITLE
annotation().line() 在有数据表现正常，无数据的无法显示

### ISSUE THREAD

**Issue by NicolaCage** [antvis/G2#3576]
先贴代码哈，实现思路是这样，根据用户自己输入的baseLine参数，设置成三条刻度线，中间为参考线
```
chartInstance.scale('value', { ticks: [0, baseLine, Math.round(baseLine * 1.5) ] });
chartInstance.annotation().line({
        start: ['min', baseLine],
        end: ['max', baseLine],
        style: {
          stroke: '#e6522b',
          lineWidth: 1,
          lineDash: [3, 3],
          zIndex: 999,
        },
```

**版本："@antv/g2": "^4.1.22"**

这是没有数据的时候
![image](https://user-images.githubusercontent.com/37568394/129832045-b5a91bcb-ac84-4d76-b0bc-ff6312ed5906.png)这是有数据的时候
![image](https://user-images.githubusercontent.com/37568394/129831839-16cb9a11-04d4-4972-b952-d98c9230718f.png)
排查的时候发现其实就是在没有数据的时候annotation().line没有生效，我想问下这是g2自身的逻辑吗？还是算一个bug？如果是本身就是这样设计的话，那我们这边需要单独做处理了

**Comment by hustcc** [comment]
没看懂问题是什么？可以再解释下嘛？
