### ISSUE TITLE
feat:  component legend needs more postion options

### ISSUE THREAD

**Issue by huxiaoyun** [antvis/g2#358]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

in our projects,   designers always make legend  lays from left to right , it is much more convinient for user to read the chart.    but g2 only provide four options includes  left , right , top , bottom, if g2 can provide more specific position opts like  ' left top' ,  'right bottom ' .   it would be consummate  and suit more cases . 

![image](https://user-images.githubusercontent.com/4345248/34595067-d2433ace-f20f-11e7-9871-e09f01026c8f.png)

thank u ~

**Comment by maplor** [comment]
我个人的解决方案是使用 html legend，然后关闭 autoPosition，就可以用自定义的样式控制位置 =.=

**Comment by dxq613** [comment]
当初设置 legend 位置的时候考虑过 8 个方向都支持，但是由于几个原因仅实现了 4 个方向：

* 大多数图表的图例位置在  top-center, bottom-center, right-bottom 
* 存在多个图例的情况，目前的这种排布方式，可以方便的错开多个图例进行摆放，如果 8 个方向都支持这些摆放是个很大的问题
* 目前图例支持 offsetX，offsetY 的方式，可以进行一些偏移

后面可以考虑支持 position 设置百分比位置的功能： position: [0%, 50%] 之类的但是这种方式是以画布作为比例依据，还是以绘图区域作为比例依据需要考虑。

**Comment by huxiaoyun** [comment]
ok,  maybe  use  html  legend is the only way ...   most chart libary didnot consider this situation.

echarts  provides this little convient.. chart can change  its padding with data,  legend can change its position with data.

![image](https://user-images.githubusercontent.com/4345248/34765245-f6ec8d2e-f62b-11e7-8cf0-5dfe94f5af0b.png)

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#________%E5%8F%82%E6%95%B0
