### ISSUE TITLE
分组折线图，slider滑动，折线图显示不正确

### ISSUE THREAD

**Issue by keke195** [antvis/G2#3587]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ecstatic-feather-sgokn?file=/index.html)

### Steps to reproduce
滑动slider滑块，分组的数据显示不正确，只有第一条分组显示了滑块对应的数据，另外的分组没有变化

| Environment | Info |
|---|---|
| g2 | 4.1.24 |
| System | - |
| Browser | - |

![image](https://user-images.githubusercontent.com/19198738/130602759-34b19b66-2ca8-4dab-a90e-d1e159a79dc1.png)

**Comment by keke195** [comment]
![image](https://user-images.githubusercontent.com/19198738/130745058-4625b89b-79b9-4db0-8837-6a520b6d6a23.png)
er'q而且slider滚动条结束值也跟坐标轴不对，并且拉到中间滚动条显示异常：
![image](https://user-images.githubusercontent.com/19198738/130745290-61225dac-15f2-4c35-b632-bb574dff0cd3.png)

**Comment by YYL1999** [comment]
这个问题之前修过 不知道怎么又有了 emm  害 https://github.com/antvis/G2/issues/2553#issuecomment-714460019

**Comment by keke195** [comment]
请问哪个版本能正常使用，我现在很急这个问题

**Comment by keke195** [comment]
> 这个问题之前修过 不知道怎么又有了 emm 害 [#2553 (comment)](https://github.com/antvis/G2/issues/2553#issuecomment-714460019)

请问哪个版本能正常使用，我现在很急这个问题

**Comment by YYL1999** [comment]
> > 这个问题之前修过 不知道怎么又有了 emm 害 [#2553 (comment)](https://github.com/antvis/G2/issues/2553#issuecomment-714460019)
> 
> 请问哪个版本能正常使用，我现在很急这个问题
> 我也不知道  问问开发者

**Comment by keke195** [comment]
我知道问题了，后台给的每个服务器的统计时间不统一，差了几秒导致的
