### ISSUE TITLE
怎么设置x轴总是显示在y轴的0刻度上？

### ISSUE THREAD

**Issue by JasonDung** [antvis/g2#359]
您好：
      我在api文档上并没有看到有该这是的选项，请问如何设置x轴总是显示在y轴的0刻度上？

**Comment by dxq613** [comment]
不支持这种设置，如果 x 轴在 0 的刻度线上，文本如果挨着坐标轴会导致图形的遮挡，如果文本远离坐标轴，那么刻度线和文本的距离使得用户需要来回转移目光。

**Comment by JasonDung** [comment]
真诚的感谢您百忙之中抽空解答，非常感谢，那有没有办法可以加深x轴对应y轴0刻度上的坐标轴线line的线条高亮呢？

**Comment by JasonDung** [comment]
@dxq613

**Comment by dxq613** [comment]
可以用 chart.guide().line() 来绘制 y 轴对应 0 的一条线。

https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_guide
