### ISSUE TITLE
使用slider时，slider位置在图例下面，有什么方法可以调整slider的位置呢？想要slider位于图例上方

### ISSUE THREAD

**Issue by xiangchunyu** [antvis/G2#3595]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/muddy-framework-9djjb?file=/index.ts)

### Steps to reproduce
默认slider位于图例下方

| Environment | Info |
|---|---|
| g2 | 4.1.25 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
目前暂时不支持再同一方向的时候，自定义位置。
