### ISSUE TITLE
拖拽和缩放的时候根据图表中的数值限制图形位置

### ISSUE THREAD

**Issue by JamesRupy** [antvis/G2#3597]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
实现类似MT4/5和其它交易软件的图表功能.
即在拖拽和缩放的时候,图表自动根据可视范围内的数据最大值和最小值作为限制,只可水平活动.
图表可视范围的最小值就是可视范围内的数据的最小值,或者更小一点,可视范围内的最大值与之相反.

### What does the proposed API look like?
暂时没有具体想法,如果有可以基于现有代码实现的示例demo,我可以先用自定义的交互实现一下

**Comment by hustcc** [comment]
又一些相关 demo 可以看到具体是什么效果嘛？不太清楚你说的效果是什么？

**Comment by JamesRupy** [comment]
> 
> 
> 又一些相关 demo 可以看到具体是什么效果嘛？不太清楚你说的效果是什么？

交易软件的图标功能

**Comment by JamesRupy** [comment]
> 
> 
> 又一些相关 demo 可以看到具体是什么效果嘛？不太清楚你说的效果是什么？

理解起来真的很难吗?交易软件用过没有?就是那样的图表显示功能

**Comment by hustcc** [comment]
> > 又一些相关 demo 可以看到具体是什么效果嘛？不太清楚你说的效果是什么？
> 
> 理解起来真的很难吗?交易软件用过没有?就是那样的图表显示功能

没有用过，你可以截图个，圈出来就很容易理解了。

**Comment by hustcc** [comment]
不方便录屏吗？

**Comment by hustcc** [comment]
k 线拖动之后，我要具体去看什么？

**Comment by JamesRupy** [comment]
> 
> 
> 不方便录屏吗？k 线拖动之后，我要具体去看什么？

结合我的文字应该可以看得懂

**Comment by hustcc** [comment]
> 结合我的文字应该可以看得懂

大哥，我结合你的文字，能够看懂，就不会继续问了。

**Comment by visiky** [comment]
> > 
> 
> > 
> 
> > > 结合我的文字应该可以看得懂
> 
> > 
> 
> > 大哥，我结合你的文字，能够看懂，就不会继续问了。
> 
> 
> 
> 只看文字看不懂,看参考软件看不懂,结合文字看参考软件也看不懂.
> 
> 
> 
> 我不是你大哥,你当我没说就行了.
> 
> 
> 
> 老的echarts项目我还是简单升级版本再小改一下吧,不用重构工作量还小了不少,甚是高兴

学会说话 学会表达，或许事情可以解决dei更快。站在别人的角度想想，把你表达的东西给其他人看下，是否能够看懂，判断是别人的理解问题还是自己的表达问题。
anyway，最终自己开心就行。

**Comment by JamesRupy** [comment]
> 
> 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > > 结合我的文字应该可以看得懂
> > 
> > 
> > > 
> > 
> > 
> > > 大哥，我结合你的文字，能够看懂，就不会继续问了。
> > 
> > 
> > 只看文字看不懂,看参考软件看不懂,结合文字看参考软件也看不懂.
> > 我不是你大哥,你当我没说就行了.
> > 老的echarts项目我还是简单升级版本再小改一下吧,不用重构工作量还小了不少,甚是高兴
> 
> 学会说话 学会表达，或许事情可以解决dei更快。站在别人的角度想想（不是每个人都是在特定领域专业的，不是每个人都拥有你说的那些软件app）把你表达的东西给其他人看下，是否能够看懂，判断是别人的理解问题还是自己的表达问题。 anyway，最终自己开心就行。

你觉得站在道德的制高点说话特别爽吗?

中国人之间说话,特别是大陆人,请用汉语,尊重自己的文化,尊重先辈们的浴血奋战.

阿里巴巴大又怎样,你们的软件产品真的是完美的吗?文档真的是无懈可击的吗?我用阿里系的产品,光文档错误就找到过好几处,有些能导致代码错误,有些文档所述和现实完全不一样.义务帮助阿里巴巴完善了文档.

语言只是工具,不是高人一等的资本.公司只是个平台,不是你说教的基础.

所谓的看不懂是因为你们没做过交易软件,也没用过交易软件,不熟悉常用操作,不了解用户需求,更看不出差异.

任何一个有交易软件开发经验的人都可以明白我说的用户需求,而如果要较一个外行的人彻底明白,只有当面说,外加比划了,而不是我表达的的有问题.至于为什么我用外行这个词,请看看你们的中文文档,竟然用**烛形图**这么小众的词
![图片](https://user-images.githubusercontent.com/1284261/136676309-e681bc68-a359-4ebc-b369-f70eb5e11a65.png)

而英文文档却是 **K Chart**
![图片](https://user-images.githubusercontent.com/1284261/136676405-a3047958-df8f-48d5-9153-e76bd9a95e45.png)

你们几个没经验的说看不懂,找过有经验的人过吗?上来就甩锅,这样的项目,是觉得开发者没事干,来让你们甩锅的吗?

此等项目,不用也罢,

你们和你们的公司以及项目都没什么大不了的,

把你们自己的位置放平,多创造条件理解用户需求,有助于你们的成长和提高,而不是处处以你们自己的想法为中心,以自己看不懂为基本点,觉得别人的表达有问题,甩锅是最低级的沟通方式

**Comment by JamesRupy** [comment]
> 
> 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > > 结合我的文字应该可以看得懂
> > 
> > 
> > > 
> > 
> > 
> > > 大哥，我结合你的文字，能够看懂，就不会继续问了。
> > 
> > 
> > 只看文字看不懂,看参考软件看不懂,结合文字看参考软件也看不懂.
> > 我不是你大哥,你当我没说就行了.
> > 老的echarts项目我还是简单升级版本再小改一下吧,不用重构工作量还小了不少,甚是高兴
> 
> 学会说话 学会表达，或许事情可以解决dei更快。站在别人的角度想想（不是每个人都是在特定领域专业的，不是每个人都拥有你说的那些软件app）把你表达的东西给其他人看下，是否能够看懂，判断是别人的理解问题还是自己的表达问题。 anyway，最终自己开心就行。

"不是每个人都拥有你说的那些软件app"这句话的意思是啥?我前面说过,发文字你们说看不懂,推荐几个参考软件,教你们用正经的交易软件作为参考,结合我的文字理解一下.

那么我是不是可以认为你们压根就没对比正经的交易软件,结合你们之前看不懂的纯文字去理解?

这些软件都是可以免费测试用的,都是业界普遍在用的,你们是否有一丁点深入理解用户需求的积极性,能静下心来去理解,去找到差异.

在我看来你们擅长的就是甩锅甩锅甩锅

**Comment by pearmini** [comment]
@JamesRupy 那你感兴趣去提一个 PR 改一下吗？如果没有的话我就去改了（蹭 PR）🤣

**Comment by JamesRupy** [comment]
@pearmini 我对这个项目不感兴趣了,你提吧.继续用echarts,省时省力,完美
