### ISSUE TITLE
[Question] 🐛 Image Annotation 的 position、start、end 如何理解 !!! 看不懂

### ISSUE THREAD

**Issue by visiky** [antvis/G2#3598]
![image](https://user-images.githubusercontent.com/15646325/131310714-bdee47ef-2859-4a4b-90d5-226c33f59ed0.png)

![image](https://user-images.githubusercontent.com/15646325/131310730-dec5c089-94a7-4878-9987-fcf7094d30bd.png)

**Comment by cnyballk** [comment]
+1

**Comment by hustcc** [comment]
Sorry, due to problems in the program's architecture design, we are unable to effectively fix the issues. But it fixed in G2 5.0, you can have a try.
