### ISSUE TITLE
facet  view 的标题不显示，点击 legend 才显示，并且多次点击后标题会重续渲染，颜色加深

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#361]
https://antv.alipay.com/zh-cn/g2/3.x/demo/facet/list.html

如题。

**Comment by zhuscat** [comment]
`3.0.2-beta.1` 有该问题，使用了[官方示例](https://antv.alipay.com/zh-cn/vis/chart/color-map.html) 的例子2 的代码，发现月份标题不显示。

**Comment by dxq613** [comment]
貌似在 3.0.3 后出现的这个问题。应该是前面改 padding: 'auto' 时，修改了一些事件的顺序，我定位修复下。
