### ISSUE TITLE
safari 15 g2 无法正常渲染

### ISSUE THREAD

**Issue by Deguang** [antvis/G2#3635]
* **G2 Version**: latest
* **Platform**: Mac safari 15， iphone safari 15
* **Mini Showcase(like screenshots)**:  https://g2.antv.vision/zh/examples/
* **CodePen Link**:

升级 safari 15后，g2 无法渲染，g2 官网 demo 也无法正常展示

**Comment by kalcaddle** [comment]
页面全面崩溃,全部卡死.  后果非常严重.

**Comment by hustcc** [comment]
在处理中了，有更详细的报错信息，都截图放上来吧。

**Comment by Deguang** [comment]
业务中使用的 2.x 3.x 版本也存在问题

**Comment by kalcaddle** [comment]
> 在处理中了，有更详细的报错信息，都截图放上来吧。
浏览器卡死, 只要调用了render就会触发,应该是代码有死循环.

**Comment by hustcc** [comment]
已经解决，原因是因为苹果新系统对于 apple-system 字体下，中文支持有问题。这个问题在 apple support 也有相关类似的问题，可以[查看和反馈](https://developer.apple.com/forums/thread/684843)一下。

解决办法就是将 -apple-system 字体删除，参考 #3640：

- 针对 G2 4.x，G2Plot 2.x 的用户

升级版本，重装依赖即可。

- 针对 G2 2.x 3.x 的用户

在自己业务层修改自己的图表字体，去掉 -apple-system 字体即可。如果修改，参考相关版本的文档。

-----

iOS 15，Safari 15 版本太新，遇到不少问题，大家自己业务产品还有遇到其他问题，建议用户转 chrome。

**Comment by dcdlove** [comment]
> 已经解决，原因是因为苹果新系统对于 apple-system 字体下，中文支持有问题。这个问题在 apple support 也有相关类似的问题，可以[查看和反馈](https://developer.apple.com/forums/thread/684843)一下。
> 
> 解决办法就是将 -apple-system 字体删除，参考 #3640：
> 
> * 针对 G2 4.x，G2Plot 2.x 的用户
> 
> 升级版本，重装依赖即可。
> 
> * 针对 G2 2.x 3.x 的用户
> 
> 在自己业务层修改自己的图表字体，去掉 -apple-system 字体即可。如果修改，参考相关版本的文档。
> 
> iOS 15，Safari 15 版本太新，遇到不少问题，大家自己业务产品还有遇到其他问题，建议用户转 chrome。

iOS 15的手机浏览器或对应web view内嵌应用没法换浏览器访问

**Comment by feijuncheng** [comment]
我找了一圈，没找到能够完美全局替换的

**Comment by hustcc** [comment]
> 我找了一圈，没找到能够完美全局替换fontFamily的

使用的什么版本？

**Comment by visiky** [comment]
4.x 的话可以用下面的方式：
```js
{
  theme: {
    styleSheet: {
      fontFamily: 'Avenir'
    }
  }
}
```

**Comment by qieshitianxia666** [comment]
> 已经解决，原因是因为苹果新系统对于 apple-system 字体下，中文支持有问题。这个问题在 apple support 也有相关类似的问题，可以[查看和反馈](https://developer.apple.com/forums/thread/684843)一下。
> 
> 解决办法就是将 -apple-system 字体删除，参考 #3640：
> 
> * 针对 G2 4.x，G2Plot 2.x 的用户
> 
> 升级版本，重装依赖即可。
> 
> * 针对 G2 2.x 3.x 的用户
> 
> 在自己业务层修改自己的图表字体，去掉 -apple-system 字体即可。如何修改？参考相关版本的文档。
> 
> iOS 15，Safari 15 版本太新，遇到不少问题，大家自己业务产品还有遇到其他问题，建议用户转 chrome。

全局配置删掉fontFamily的-apple-system 字体也没用，通过设置Chart的rederer='svg'解决了这个问题

**Comment by hustcc** [comment]
> 全局配置删掉fontFamily的-apple-system 字体也没用，通过设置Chart的rederer='svg'解决了这个问题

发一下你的代码。

**Comment by yoyo837** [comment]
> Chart的rederer='svg'解决了这个问题

这个方法我这边无效, `G2.Global.render = 'svg'` 可以, 但有一堆警告和错误.  https://github.com/alibaba/BizCharts/issues/1456#issuecomment-930752426
