### ISSUE TITLE
分组柱状图的排序可以不根据legend的顺序，根据数据源的顺序吗

### ISSUE THREAD

**Issue by yumanfeng** [antvis/G2#3653]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/summer-river-pmqq6)

### Steps to reproduce
第二个分组柱状图，期望的顺序，是按照数据源的顺序，目前看起来是按照legend的顺序进行了第二次排序
![image](https://user-images.githubusercontent.com/13445900/135241500-f606f299-0e6c-4019-acde-7b621f85cf34.png)

| Environment | Info |
|---|---|
| g2 | 4.0.12 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
图例是看图形的辅助元素，所以图例的顺序一定是和数据相同的。

上图中第二组有异常的原因是：提供的色板数量少于分组数，导致颜色重复了。

**Comment by zss7819** [comment]
请问解决了吗，遇到相同的业务问题@yumanfeng
