### ISSUE TITLE
热力图的legend如何去掉显示的数字

### ISSUE THREAD

**Issue by yangbin1994** [antvis/g2#366]
![image](https://user-images.githubusercontent.com/12080165/34662584-ad77b01a-f48c-11e7-8f98-09a0565ddaae.png)

**Comment by leungwensen** [comment]
目前没有开放这个连续图例 legend 文本显示的删除接口，可以通过配置文本格式来隐藏：

```js
  chart.legend(true, {
    textStyle: {
      opacity: 0
    }
  });
```
