### ISSUE TITLE
3.x版本Tooltip中follow与htmlContent一同使用会闪动

### ISSUE THREAD

**Issue by BoleLee** [antvis/G2#3660]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g2-vue-z72gq?file=/src/App.vue)

### Steps to reproduce
查看demo，鼠标hover图表区域，Tooltip闪动

| Environment | Info |
|---|---|
| g2 | 3.5.18 |
| System | MacOS 10.15.7  |
| Browser | Chrome 94.0.4606.61 |

---
除此问题外，还想请教下，Tooltip中的元素点击事件，如何监听比较合理？（Demo中也有写上事件）

**Comment by hustcc** [comment]
@BoleLee 我来试试看，为啥你们还在用 3.x 的版本，抽空可以升级到 4.x 了。

**Comment by BoleLee** [comment]
> @BoleLee 我来试试看，为啥你们还在用 3.x 的版本，抽空可以升级到 4.x 了。

我也很想升级，但项目略复杂，是多个小项目组合编译为一个的，antv的版本被全局指定为3.5.8-beta.1, 动版本影响范围较大，其他人的代码也会动到，后续会抽空找合适方案升级

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/136640368-e647f621-6c73-4ba5-b0e1-ce9cf2008ac9.png)

直接外部设置 自定义 tooltip dom 的 css 样式，加一个间距就就没有问题了。

**Comment by hustcc** [comment]
你把自定义 tooltip 容器的 css 样式加上变换动画（延迟）。不然鼠标没有办法移动到上面。

```css
transition: visibility 0.2s cubic-bezier(0.23, 1, 0.32, 1) 0s, left 0.4s cubic-bezier(0.23, 1, 0.32, 1) 0s, top 0.4s cubic-bezier(0.23, 1, 0.32, 1) 0s;
    background-color: rgba(255, 255, 255, 0.9);
```

**Comment by BoleLee** [comment]
@hustcc Hi，这边终于有时间把G2升级到4.x了，自定义tooltip 这里遇到个问题，麻烦你帮忙看下：
https://codesandbox.io/s/g2-4-x-vue2-custom-tooltip-xvdpdp

用的container来绑定自定义的html，然后数据是在 tooltip:change 时赋值的，上述demo存在2个问题：
1）加上 tooltip:change 后，tooltip出现变得很卡，这个问题在我项目中没有出现，只在demo出现了，我把它暂时注释了；
2）自定义的Tooltip上，点击穿透按钮后，会用新的数据和设置重新绘制图表，调用了chart.destroy(), 然后重新走一遍绘制，问题是：重绘后自定义的Tooltip就不出现了。我在项目中查看，是自定义Tooltip的html被拿走了，但是我console.log(this.$refs.customTooltip)是还有拿到的

以上，麻烦重点帮忙看下问题2，应该怎么解决
