### ISSUE TITLE
> 因为这个数据中，有一些城市没有某一些分类值。

### ISSUE THREAD

**Issue by yumanfeng** [antvis/g2#3668]
> 因为这个数据中，有一些城市没有某一些分类值。
> 
> 你的意思是需要：如果没有这个分类值，也需要吧位置预留出来嘛？

位置预留出来，指的是没有的legend，会有空白的柱状图吗？这里不希望有空白的柱状图占位，如果没有legend，就不渲染，但是柱状图的顺序还是希望是按照数据源的顺序。
需求现状是：每一组 x，不会包含所有的 legend，只含有部分 legend，且每组x的 legend 不相同。

_Originally posted by @yumanfeng in https://github.com/antvis/G2/issues/3653#issuecomment-939239506_

**Comment by zss7819** [comment]
请问解决了吗，遇到相同的业务问题
