### ISSUE TITLE
tranform的疑问

### ISSUE THREAD

**Issue by vickmeng** [antvis/g2#367]
假如我想进行两两一组的分类，除了进行两次tranform有没有其他更好的写法
const data = [
{ month: 'Jan', Tokyo: 7.0, London: 3.9 , shanghai:3.2, dalian:13.2},
{ month: 'Feb', Tokyo: 6.9, London: 4.2 , shanghai:3.3, dalian:23.2},
{ month: 'Mar', Tokyo: 9.5, London: 5.7 , shanghai:8.2, dalian:31.2},
{ month: 'Apr', Tokyo: 14.5, London: 8.5 , shanghai:10.1, dalian:13.2},
{ month: 'May', Tokyo: 18.4, London: 11.9, shanghai:5.2, dalian:13.2}
];
const ds = new DataSet();
const dv = ds.createView().source(data);
dv.transform({
type: 'fold',
fields: [ 'Tokyo', 'London'], // 展开字段集
key: '国外城市', // key字段
value: '国外气温', // value字段
});
dv.transform({
type: 'fold',
fields: [ 'shanghai', 'dalian'], // 展开字段集
key: '国内城市', // key字段
value: '国内气温', // value字段
});

**Comment by leungwensen** [comment]
最终是想怎么用这个数据？现在你执行的这个数据结果有不少冗余的数据。

我的建议是把数据分成两个子集，使用两个 View。https://antv.alipay.com/zh-cn/g2/3.x/api/transform.html#_subset-%E8%8E%B7%E5%8F%96%E5%AD%90%E9%9B%86
