### ISSUE TITLE
"tooltip:change" 事件触发机制

### ISSUE THREAD

**Issue by fancymo** [antvis/g2#368]
* **G2 Version**: 3.0
* **Platform**: Mac
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

鼠标在同一个 tooltip 上也就是当前 tooltip 仅仅是位置修改则触发了 change 事件，这个事件的触发是不是放在当前选中的条目发生变化后触发会更好

**Comment by leungwensen** [comment]
这是个 bug，多谢反馈

**Comment by fancymo** [comment]
很高兴能够发现这么好的图表数据处理，概念学习中
