### ISSUE TITLE
chart的forceFit属性设置后会产生非预期行为

### ISSUE THREAD

**Issue by myplist** [antvis/g2#369]
* **G2 Version**: 3.0.2
* **Platform**: Mac，Chrome
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

现状：设置forceFit为true时，chart会响应resize事件重绘图表。针对多tab页并且每个tab页都有图表的情况，非active tab页在发生resize事件后，因为容器元素width为0从而导致图表不可见

预期：针对不可见的情况，设置forceFit的chart应该忽略width为0的resize事件重绘响应

**Comment by dxq613** [comment]
仅仅是width: 0 的时候不响应事件依然有问题，tab 切换回来时图表的大小依然不合适。我会对 width：0的情况下进行一些处理，建议切换回tab 的时候，手工调用一下 chart.forceFit();
