### ISSUE TITLE
g2 关系图 / 结构树中，当一个点时位置偏移问题

### ISSUE THREAD

**Issue by justQing00** [antvis/g2#37]
g2 关系图 / 结构树中，当只有一个或者两个节点时，节点会偏移到左下角，
此时 应该默认竖直居中比较合适

链接如下
[https://g2.alipay.com/demo/13-link/tree.html](https://g2.alipay.com/demo/13-link/tree.html)

1、当仅有一个节点时
```
      var data = [{
        "name": "flare",
      }];
```

2、当有两个节点时
```
      var data = [{
        "name": "flare",
        "children": [{
             "name": "child",
        }]
      }];
```

**Comment by dxq613** [comment]
确实有这个问题，下个版本修复

**Comment by dxq613** [comment]
下周发布新版本修复
