### ISSUE TITLE
关于图表区域较小时很多数据量时折线图的处理

### ISSUE THREAD

**Issue by YanYuanFE** [antvis/g2#370]
![_147](https://user-images.githubusercontent.com/17774285/34702355-3f24b6ca-f528-11e7-9ebd-3463b5e62d21.png)

如上图，通过api限制横坐标的数量，因为横坐标轴上的点是字符串，用tickInterval无法设置间隔，有没有API可以设置图上的点的数量。

**Comment by leungwensen** [comment]
“设置图上的点的数量”是什么意思？

**Comment by YanYuanFE** [comment]
this.chart.source(dv, {
      time: {
        range: [ 0, 1 ],
        tickCount: 7
      }
    });
this.chart.line().position('time*count').color('type', ['#ffbb5e', '#f69482', '#7da7eb', '#36d99a']).shape('smooth').style({
      lineWidth: 4
    });
    this.chart.point().position('time*count').color('type', ['#ffbb5e', '#f69482', '#7da7eb', '#36d99a']).size(6).opacity(0.5).shape('circle').style({
      stroke: '#FFFFFF',
      lineWidth: 1
    });

**Comment by YanYuanFE** [comment]
现在的代码是上面的，tickCount只能控制横坐标的数量，有没有api可以控制point的数量跟横坐标一样，30个点挨在一起太难看了

**Comment by YanYuanFE** [comment]
图上的点是横纵坐标交点，this.chart.point().position('timecount')，绘图区域太小所有的点就会挨在一起

**Comment by dxq613** [comment]
你可以在 size 里面写个回调函数
```js
 this.chart.point().size('xxx', function(xxx) {
  if () return 2; else return 0; 
});
```

0 的就不显示了

**Comment by leungwensen** [comment]
如果只想要显示某些坐标刻度对应的点，可以这么做：坐标刻度直接手动设置（ticks），然后把数据过滤一下，只留下坐标刻度对应的点。
