### ISSUE TITLE
🐛 [BUG]漏斗图在一些情况下转化率显示不全

### ISSUE THREAD

**Issue by Eve-Sama** [antvis/G2#3700]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elated-wing-m2xh8?file=/index.ts)

### Steps to reproduce
看demo链接, 调整容器宽度也没用
![图片](https://user-images.githubusercontent.com/30228406/139206991-d5e9096b-e803-4a88-9205-960ebd1078eb.png)

| Environment | Info |
|---|---|
| g2 | 4.1.32 |
| System | - |
| Browser | - |

**Comment by Eve-Sama** [comment]
谢谢

**Comment by Eve-Sama** [comment]
padding的方案我认为是下下策. 我认为容器有多大, 那么里面的内容是绝对不可以超越这个容器的. 虽然楼上提到了用padding来挤压内部, 但是这终究不是一个一劳永逸的方法. 因为生产环境下又有客户反馈显示不全的问题, 那我继续加大padding吗? 

这个问题是不是应该由g2/g2plot内部去处理更合适?

**Comment by hustcc** [comment]
@Eve-Sama 对于标签的 auto padding 确实技术上比较难实现，目前也只是做到的组件的 auto padding，这个的前提是组件的布局是不会和图形重叠的，但是数据标签本质是 float 在上面的。
