### ISSUE TITLE
折线图添加brush交互后，线点击事件只能触发一次，之后再也不可以触发

### ISSUE THREAD

**Issue by observerzy** [antvis/G2#3705]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/case/line#line8](https://g2.antv.vision/zh/examples/case/line#line8)

### Steps to reproduce
折线图添加代码    
`
chart.interaction('brush')
chart.on("line:click",()=>{
  console.log("click line")
})
`

| Environment | Info |
|---|---|
| g2 | 4.1.32 |
| System | mac |
| Browser | chrome |

![image](https://user-images.githubusercontent.com/33326500/140018726-660c8267-90ac-4f92-ace2-a2f588795dde.png)

设置了brush后，图表上line:click、plot:click事件触发一次后就不再触发，但是其mouseenter事件正常

**Comment by WHChen-Alex** [comment]
+1，我也遇到相同的问题了👀

**Comment by zzyundragon** [comment]
+1
设置了brush后可以判断获取到的width，width为0是就是单击事件。。🐶

**Comment by Dawnwangzi** [comment]
+1，我也遇到相同的问题了👀

**Comment by renjihua** [comment]
> +1 设置了brush后可以判断获取到的width，width为0是就是单击事件，可以每次都触发。。🐶

demo写出来了, 之后, 怎么获取到点击的是哪个point?

**Comment by pearmini** [comment]
可以看看 G2 5.0 的案例是否有相同的问题。
