### ISSUE TITLE
改变浏览器显示大小，环图中间文字显示异样

### ISSUE THREAD

**Issue by BabyFriedCake** [antvis/G2#3706]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/case/pie#pie7](https://g2.antv.vision/zh/examples/case/pie#pie7)

### Steps to reproduce
改变浏览器显示大小，环图中间文字显示异样
![image](https://user-images.githubusercontent.com/33448924/140251625-f102ae68-3c09-4e0f-b5b2-b7d03d6f9a8d.png)

| Environment | Info |
|---|---|
| g2 | 4.1.21 |
| System | windows |
| Browser | 谷歌 |

**Comment by break520** [comment]
animate(false) 可以解决这个问题，但就是没动画了
