### ISSUE TITLE
slider 可以选择X轴数据或者Y轴数据数据控制

### ISSUE THREAD

**Issue by vanness30214** [antvis/G2#3707]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://echarts.apache.org/examples/zh/editor.html?c=custom-profile
需求场景：以时间为单位主体对每个时间段，发生的状态进行轴体横向显示，并且slider可以进行时间范围控制，如上方例子基本上符合功能需求；但Echart对自定义Annotation功能比较弱，所以还是需要antv G2来实现；

轴体基本上能实现，但slider并不呢控制选择X轴范围控制或者选择Y周范围控制，导致无法进行单根时间轴时间控制筛选；并且能支持鼠标滚动进行缩放功能

### What does the proposed API look like?
https://echarts.apache.org/examples/zh/editor.html?c=custom-profile

**Comment by hustcc** [comment]
Sorry, due to problems in the program's architecture design, we are unable to effectively fix the issues. But it fixed in [G2 5.0](https://g2.antv.antgroup.com/examples/interaction/interaction/#slider), you can have a try.
