### ISSUE TITLE
世界地图的数据里没有新加坡

### ISSUE THREAD

**Issue by liuxuewei** [antvis/G2#3713]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://gw.alipayobjects.com/os/antvdemo/assets/data/world.geo.json](https://gw.alipayobjects.com/os/antvdemo/assets/data/world.geo.json)

### Steps to reproduce
地图数据接口中没有新加坡，导致渲染的地图也没有新加坡

| Environment | Info |
|---|---|
| g2 | 4.1.34 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
geoJSON 请使用先关真实数据，demo 样例中的不一定保证准确和时效。
