### ISSUE TITLE
文档里Axis下label里的autoHide默认值写错了,默认值写的false,实际为true

### ISSUE THREAD

**Issue by as299999** [antvis/G2#3716]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/docs/api/general/axis#axisoptionlabel](https://g2.antv.vision/zh/docs/api/general/axis#axisoptionlabel)

### Steps to reproduce
文档里Axis下label里的autoHide默认值写错了,默认值写的false,实际为true

| Environment | Info |
|---|---|
| g2 | 4.1.34 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
有兴趣来 PR 改掉吗？
