### ISSUE TITLE
饼图不支持在ie11 

### ISSUE THREAD

**Issue by yangmeiz** [antvis/g2#372]
1. const { DataView } = DataSet;  这个标签应该是不支持在ie11中，我写了一个环形图但是不能展示。
2.词云能否添加一个点击事件，点击每个词可以跳转到另外一个页面

**Comment by leungwensen** [comment]
1. 这是 IE11 对 ES6 支持不完善的问题
2. 可以这样加事件

```js
chart.on('point:click', evt => {
    console.log(evt);
});
```

**Comment by yangmeiz** [comment]
我把es6语法转换位es5可以正常显示，但是在ie9为什么他又报  “引发了异常但未捕获data-set.min.js (1,30929)”
this.dataSet);else if(Array.isArray(n))this.origin=n;else{if(!f(n)||!n.type)  这是data-set.min.js中的那行代码

**Comment by leungwensen** [comment]
嗯嗯，这个特性其实在 IE9 是部分支持的，应该执行没问题。这样吧，你到 DataSet 项目里提个 issue ？https://github.com/antvis/data-set/issues/new
