### ISSUE TITLE
dataMarker 和 slider一起使用的时候，当标记点不属于当前缩略轴显示的范围之中时，图表左上角会出现一个小点标记

### ISSUE THREAD

**Issue by qiaoyuwen** [antvis/G2#3723]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cranky-rubin-kdsqx)

### Steps to reproduce
1. 拖动滑块范围，使标记点移出当前显示范围；
2. 这时候在图表左上角会出现一个小点

![7DCD00FF-401F-4E1E-A11A-18C326CB600E](https://user-images.githubusercontent.com/8097860/143205504-db812303-3417-4aac-916a-37d959d518fb.png)

![6E3B3CC9-C3D7-4C27-ADCC-D6B989CDFBED](https://user-images.githubusercontent.com/8097860/143205521-b434dc5b-3a53-4c63-89ff-f29e787eda14.png)

| Environment | Info |
|---|---|
| g2 | 4.1.34 |
| System | - |
| Browser | Microsoft Edge 版本 94.0.992.31 (官方内部版本) (x86_64) |

**Comment by qiaoyuwen** [comment]
调试了一下，问题是 https://github.com/antvis/G2/blob/master/src/chart/controller/annotation.ts#L379 该行计算标记点的坐标时，因为超出了当前视图，计算出来的坐标是NaN，所以渲染到了（0, 0）点坐标。看看能不能提个pr

**Comment by visiky** [comment]
这个的主要原因还是因为，图表重绘之后，没有重新执行图表标注的绘制
