### ISSUE TITLE
Chorme 67版本图标Line底部月份会被截取

### ISSUE THREAD

**Issue by EdisonVan** [antvis/G2#3724]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/determined-shaw-8pdbv)

### Steps to reproduce
底部月份会被截取一部分，Chorme 90以上版本均正常

| Environment | Info |
|---|---|
| g2 | 4.1.29 |
| System | windows |
| Browser | Chorem 67.0.3386.62 |

**Comment by EdisonVan** [comment]
依赖包升级到4.1.34版本，此问题仍旧存在

**Comment by hustcc** [comment]
现在应该不会了。

![image](https://user-images.githubusercontent.com/7856674/174983699-7aac6789-4b97-43ef-a69b-c7552538d9e8.png)

另外你也可以设置一个 appendPadding: 8 增加一些空位置。
