### ISSUE TITLE
图例在分页时，跳转第二页点击图例marker ，会使整个图例右移

### ISSUE THREAD

**Issue by RichieChoo** [antvis/G2#3726]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/clever-boyd-o6406?file=/src/index.js)

### Steps to reproduce
跳转第二页点击图例marker ，会使整个图例右移

| Environment | Info |
|---|---|
| g2 | 4.1.34 |
| System | - |
| Browser | - |

**Comment by qiaoyuwen** [comment]
调试了一下，问题是出在图例分页的间距上，每一页的宽度是图例宽度加上设置的间距，而由于最后一页没有间距了，所以渲染的时候宽度就会变窄，造成偏移，目前临时的办法是把间距手动设置为0
```
chart.legend({
  position: "right",
  flipPage: true,
  itemSpacing: 0 // 手动设置为0，不设置默认是24
});
```
