### ISSUE TITLE
【基础柱状图】当数据量较少时，滚动条滚轮事件会导致柱状图消失

### ISSUE THREAD

**Issue by yumcc-com** [antvis/G2#3739]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fervent-roentgen-ni68j?file=/index.ts)

### Steps to reproduce
代码基于官方案例【基础柱状图】，仅添加了滚动条相关的代码【已标记注释】，鼠标置于表内滚动即可复现

| Environment | Info |
|---|---|
| g2 | 4.1.34 |
| System | - |
| Browser | - |

**Comment by mrh-code-star** [comment]
这个问题解决了吗？
