### ISSUE TITLE
[Bug] Enterable tooltip cannot disappear when mouse leave chart from tooltip

### ISSUE THREAD

**Issue by dengfuping** [antvis/G2#3741]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dry-cloud-60eer)

### Steps to reproduce
- Mouse leave chart from tooltip.
![image](https://user-images.githubusercontent.com/14918822/145819641-09bedd6f-65ad-41fd-93a6-3f6c1d9da6dd.png)

| Environment | Info |
|---|---|
| g2 | 4.1.34 |
| System | MacOS 11.5.1 |
| Browser | Chrome 96.0.4664.93 |

**Comment by pearmini** [comment]
可以试试下面 V5 的版本有没有这个问题哈：

```js
import { Chart } from '@antv/g2';

const data = [
  { year: '1991', value: 3 },
  { year: '1992', value: 4 },
  { year: '1993', value: 3.5 },
  { year: '1994', value: 5 },
  { year: '1995', value: 4.9 },
  { year: '1996', value: 6 },
  { year: '1997', value: 7 },
  { year: '1998', value: 9 },
  { year: '1999', value: 13 },
];

const chart = new Chart({
  container: 'container',
  autoFit: true,
});

chart
  .data(data)
  .encode('x', 'year')
  .encode('y', 'value')
  .scale('x', {
    range: [0, 1],
  })
  .scale('y', {
    domainMin: 0,
    nice: true,
  });

chart.line().label({
  text: 'value',
  style: {
    dx: -10,
    dy: -12,
  },
});

chart.point().style('fill', 'white').tooltip(false);

chart.interaction("tooltip", {enterable:true})

chart.render();
```
