### ISSUE TITLE
how to dynamic set chart padding or another attributes?

### ISSUE THREAD

**Issue by JobinJia** [antvis/G2#3742]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
if create a chart, sometimes need to change the chart padding or another config attributes.
maybe refactor `changeSize(width, height)` function to `changeConfig(ChartCfg)` then the initial config can be changed with runtime ?

### What does the proposed API look like?
changeConfig(config: ChartCfg)

**Comment by hustcc** [comment]
```ts
chart.padding = [/*...*/];
```
