### ISSUE TITLE
如何衡量G2的性能，有没有相关BenchMark数据？

### ISSUE THREAD

**Issue by TimRChen** [antvis/G2#3752]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://charts.ant.design/zh/examples/line/multiple#line-large-data](https://charts.ant.design/zh/examples/line/multiple#line-large-data)

### Steps to reproduce
点击链接，如何量化分析渲染性能？

| Environment | Info |
|---|---|
| g2 | 4.1.35 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
可以看看这个： https://git.hust.cc/charts-perf/

**Comment by TimRChen** [comment]
> 可以看看这个： https://git.hust.cc/charts-perf/

感谢
