### ISSUE TITLE
Axis的line如何调整它的stroke-width粗细属性？

### ISSUE THREAD

**Issue by soupor** [antvis/G2#3753]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
业务上需要调整坐标轴线的粗细，但配置项并无法更改它的stroke-width属性

### What does the proposed API look like?
添加stroke-width的配置项

**Comment by rainy-25Ghz** [comment]
G2 提供了坐标轴的配置接口，主要用于坐标轴样式的配置：
```js
chart.axis("sales",{
  line:{
    style:{
      lineWidth:4,//线宽为4
      stroke:"rgba(217,217,217,1)"//灰色
    }
  }
})
```
调整AxisOption.line的style属性即可

[演示例子](https://stackblitz.com/edit/react-vgzhbg?file=index.js)
