### ISSUE TITLE
官网示例似乎有一个bug

### ISSUE THREAD

**Issue by vickmeng** [antvis/g2#376]
https://antv.alipay.com/zh-cn/g2/3.x/demo/other/kernel-smooth-regression-2.html
我显示了line的坐标，发现其Y轴与point的Y轴并没有在同一纬度，这是否是一个BUG？
另外，我想的得知不同形状的数据集如何共享同一个Y轴？

![_20180111140401](https://user-images.githubusercontent.com/19486247/34810763-49d58214-f6d8-11e7-9600-7681d31d515f.png)

**Comment by leungwensen** [comment]
只要设置了字段 sync: true 就可以了，这是上个版本的 bug，更新版本就好了。
