### ISSUE TITLE
设置supportCSSTransform: true后，在移动端没有效果

### ISSUE THREAD

**Issue by sage-wen** [antvis/G2#3760]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://zperb.csb.app/](https://zperb.csb.app/)

### Steps to reproduce
切换到移动端调试模式，鼠标拖动显示tooltip的位置和鼠标位置不符。坐标轴的滚动条也无法准确拖动

| Environment | Info |
|---|---|
| g2 | 4.1.36 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
@sage-wen 你是只需要什么样的效果？

**Comment by sage-wen** [comment]
统计图在pad上显示，因为父级节点存在transform: scale属性，导致统计图无法准确的交互，如SandBox的例子所表现的X轴拖动条无法拖动

**Comment by hustcc** [comment]
你是怎么添加的，我们这边产品也有类似的需求，添加 supportCSSTransform 之后可以解决的。

**Comment by sage-wen** [comment]
测试地址 https://zperb.csb.app/ 如下图所示打开移动端调试，滚动条无法拖动
![image](https://user-images.githubusercontent.com/40239058/174960946-1f7cf5b4-6f1e-479b-a373-e49aa1f0acd8.png)

**Comment by hustcc** [comment]
复现了， 应该是 slider 的 touch 事件没有处理好。
