### ISSUE TITLE
线性图设置别名问题

### ISSUE THREAD

**Issue by Shruan** [antvis/g2#377]
不改变数据源的情况下 修改下方显示的字段

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_chart.axis-false-  配置 label 属性的 formatter

**Comment by Shruan** [comment]
![image](https://user-images.githubusercontent.com/28869029/34810804-75f7acfa-f6d8-11e7-84a2-7c88c3d427d2.png)

**Comment by leungwensen** [comment]
这是 legend，你在官网搜一下 legend 的 API，类似的。

**Comment by kingmoumoumou** [comment]
http://note.youdao.com/noteshare?id=397ce180ee8551d3cdafb1fbac9a64fa&sub=09573EDB707F439092DE5C60F88F6C47
