### ISSUE TITLE
View 中的 annotation().regionFilter() 在 brush-x 交互后不会重绘

### ISSUE THREAD

**Issue by FlatMapIO** [antvis/G2#3772]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/epic-colden-t9zwi?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. 创建 Chart
2. 在 chart 上创建 view
3. 绘图，并在 view 上创建 regiionFilter
3. 给 view 加入 brush-x 交互
4. 框选视图，视图重绘， annotation 丢失

| Environment | Info |
|---|---|
| g2 | 4.1.37 |
| System | macOS |
| Browser | Chrome |

**Comment by visiky** [comment]
brush-x 交互后，应该会触发 afterrender 事件，然后重新绘制 regionFilter。

我看了这个 [demo](https://codesandbox.io/s/regionfilter-brushx-s52i3?file=/index.ts) 是正常的，你可以提供下复现 case 吗？看下是怎么使用的

**Comment by FlatMapIO** [comment]
我提交的 Issue 里有 Demo：https://codesandbox.io/embed/epic-colden-t9zwi?fontsize=14&hidenavigation=1&theme=dark
我没有使用根 chart  绘制 annotation
