### ISSUE TITLE
limitInPlot属性无法屏蔽一些后出现的状态

### ISSUE THREAD

**Issue by qiansheng1989** [antvis/G2#3788]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2plot.antv.vision/zh/examples/line/multiple#line-large-data](https://g2plot.antv.vision/zh/examples/line/multiple#line-large-data)

### Steps to reproduce
limitInPlot属性无法屏蔽一些后出现的状态.

Required Link to minimal reproduction:
📷 Step to reproduce
limitInPlot: true 设置了屏蔽图表外的显示但是折线图的active还是会显示

🏞 Expected result
坐标轴以外的不显示

🚑 Any additional [like screenshots]
![image](https://user-images.githubusercontent.com/37897917/149914641-1c8b0dc9-8c5d-49ac-817a-0c565355c429.png)

| Environment | Info |
|---|---|
| g2 | 4.1.40 |
| System | window10 |
| Browser | Google Chrome |

**Comment by hustcc** [comment]
我这里测试 ok 的，没有出现这个问题。G2 4.2.x 版本。

![image](https://user-images.githubusercontent.com/7856674/233987870-22a1c327-a390-4b05-8aca-8a1c6f4b2f46.png)
