### ISSUE TITLE
chart.line.connectNulls 支持将 null/undefined 转换为 0

### ISSUE THREAD

**Issue by xiaoshuangLi** [antvis/G2#3789]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
实际监控数据中存在数据丢失残缺的情况，这种时候用户可以选择将此条数据当作0来展示

### What does the proposed API look like?
```tsx 
nullPointMode: 'zero' | 'null' | 'connected' 
```

**Comment by hustcc** [comment]
相比 null 数据是否跳过连接还是断开，Null 转化为 0 这个逻辑，其实挺业务属性的，建议做法是在可视化之前自己进行一波数据业务逻辑的处理。
