### ISSUE TITLE
3.0版本没有绘制原版本的中国地图的示例啊 能不能提供非省市下钻的示例。

### ISSUE THREAD

**Issue by muyucanqiu** [antvis/g2#379]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by maplor** [comment]
应该是因为不符合 测绘法 所以都下线了。。。

**Comment by dxq613** [comment]
根据国家的相关政策，我们没有提供地图的资质，所以所有跟国家地图相关的都不能提供。

**Comment by gudufy** [comment]
我去，什么鬼政策
