### ISSUE TITLE
Adjust可能将数据调整到坐标轴有效范围之外

### ISSUE THREAD

**Issue by ouyuran** [antvis/G2#3791]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hopeful-booth-y3izi?file=/index.ts)

### Steps to reproduce
如demo，
因为adjust在 /-0.5范围内调整，如果一个data的值正接近scale所定义的min/max，那么此data可能被调整到有效坐标外面。
而且会事实上处于不能响应鼠标的状态。
![image](https://user-images.githubusercontent.com/50813733/150285697-ee1c899a-bb27-41b6-b203-c2088e74c890.png)

| Environment | Info |
|---|---|
| g2 | 4.1.40 |
| System | - |
| Browser | - |

**Comment by pearmini** [comment]
可以 G2 5.0 是否还有这个问题
