### ISSUE TITLE
平行坐标图 支持

### ISSUE THREAD

**Issue by taoistwar** [antvis/G2#3796]
平行坐标图 是一种非常有用的分析图表，有计划添加支持吗？

https://zhuanlan.zhihu.com/p/196681832

**Comment by hustcc** [comment]
已经在考虑中了，在目前 4.x 版本中比较难支持～

**Comment by hustcc** [comment]
[G2 5.0 ](http://g2-next.antv.vision/coordinate#parallel)已经支持，等待 8 月份发布版本就可以试用。
