### ISSUE TITLE
changeData之后重绘问题

### ISSUE THREAD

**Issue by kchjxxgh** [antvis/g2#38]
我用的是2.1.3，调用changeData之后，有一定概率不能重绘，试了很多次，发现重绘失败的概率大概是10%左右，当重绘失败（停止）之后，如果将鼠标移动到canvas区域，会继续重绘成功。
如所附图片，changeData之后，如果重绘失败了，会卡在动画的途中，仔细看每个柱子的下方，发现重绘已经开始了，只是没有完成，卡在这了。
![qq 20161116171249](https://cloud.githubusercontent.com/assets/19234718/20341314/a56e94e8-ac20-11e6-909b-d6ca3e832cba.png)

`  var data = [
    {action: '访问', visitor: 500},
    {action: '浏览', visitor: 400},
    {action: '交互', visitor: 300},
    {action: '下单', visitor: 200},
    {action: '付款', visitor: 100}
  ];
  var chart = new G2.Chart({
    id: 'root',
    width : 800,
    height : 400
  }); // 创建图表
  chart.source(data); // 载入数据源
  chart.interval().position('action*visitor').color('action'); // 使用图形语法绘制柱状图
  chart.render();
  
  data = [
    {action: '访问', visitor: 200},
    {action: '浏览', visitor: 300},
    {action: '交互', visitor: 350},
    {action: '下单', visitor: 400},
    {action: '付款', visitor: 120}
  ];
  setTimeout(function(){
	chart.changeData(data);
  }, 1000);`

**Comment by kchjxxgh** [comment]
[demo.txt](https://github.com/antvis/g2/files/594154/demo.txt)
这个是本地测试页面（txt->html），用的是Win10+Chrome浏览器

**Comment by dxq613** [comment]
2.1版本改了下动画，可能是动画的问题，我们去查找一下

**Comment by TomHuangCN** [comment]
下载下来的文件没东西，直接这里贴一下。 @kchjxxgh

**Comment by TomHuangCN** [comment]
定位问题了，感谢反馈🙏

**Comment by yszsz** [comment]
如何解决重绘？100%失败
