### ISSUE TITLE
xAxis tick label animation bug with multi view and timeCat scale

### ISSUE THREAD

**Issue by maplor** [antvis/g2#380]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:  https://codepen.io/anon/pen/qpYdGy

In my codepen, first use view to draw a chart, then set the xAxis scale type as timeCat.
when I update data, the animation of the xAxis tick label is so bad, a long text move from right to left every time.

In my test, if the scale type is time or cat, everything is ok, but timeCat is bad.

**Comment by dxq613** [comment]
已经记在在 #378 中了，下个小版本中修复
