### ISSUE TITLE
🚀 [Perf]: 数据超过约 3 万条数据时，渲染超过 1 s

### ISSUE THREAD

**Issue by visiky** [antvis/G2#3808]
<img width="223" alt="image" src="https://user-images.githubusercontent.com/15646325/153998894-833c82ed-449b-4619-9ac3-cbce1e2bfd35.png">

[Codesandbox](https://codesandbox.io/s/large-data-76cpf?file=/index.ts)

**Comment by hustcc** [comment]
这个关闭到了哈~
