### ISSUE TITLE
分组柱状图，数据类型（数字和货币）不一致的那组数据出不来

### ISSUE THREAD

**Issue by FightingJane** [antvis/g2#381]
* **G2 Version**:3.0.2-beta.1
* **Platform**:PC
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/FightingJane/pen/WdJQYZ

分组柱状图，每一组的最后一列数据类型不一致（前面为数字，后面为货币），会出现2个y轴
1、呈现的效果如CodePen Link 链接所示，最后一个分组的数据只展示了其中一个
2、y轴数据类型不管设不设置为cat类型都值展示其中一个
3、右边的y轴信息显示不全
是bug吗？还是有别的解决方法？

**Comment by leungwensen** [comment]
柱状图的 Y 轴的确只能用数值来映射，用字符串没有意义的
