### ISSUE TITLE
legend 自定义，name和value希望可以增加横向排列和竖向排列

### ISSUE THREAD

**Issue by guijue-code** [antvis/G2#3812]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
统计看起来更直观。图表展示占比，图例展示数量

### What does the proposed API look like?
chart.legend({
items:data.map((item,index)=>{
     name:item.name,
    value:item.value,
   // 这里增加
    layout:vertical | horizontal,
    .........
}) 
})

**Comment by hustcc** [comment]
可以发一个截图看看你希望的效果吗？

**Comment by guijue-code** [comment]
[
![Uploading image.png…]()
](url)

**Comment by guijue-code** [comment]
![A5D74A18-713D-4F5C-8D61-C9153B815782](https://user-images.githubusercontent.com/66724249/175205645-38276595-8cc0-446c-9b89-c32e1e22a947.png)

**Comment by pearmini** [comment]
这个能力暂时内置不会支持，可以试试自定义图例
