### ISSUE TITLE
希望折线图能支持离群点的绘制

### ISSUE THREAD

**Issue by Valar103769** [antvis/G2#3820]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
某些极值数据(离群点),会导致y轴范围很大, 而正常数据只显示在某一个区域, 不利于观测正常数据,希望离群点能单独绘制在一个图标上方

### What does the proposed API look like?
随便

**Comment by hustcc** [comment]
有两种方案可以选择：

1. 使用 log 类型的 y 轴
2. 在渲染之前检测出异常数据点，然后排除之后绘制图形，然后用其他方案（比如 annotation）讲异常点画到图形中
