### ISSUE TITLE
当特殊标记点dataMarker的位置处于图表边界时，文字会超出容器

### ISSUE THREAD

**Issue by TheBaldGirl** [antvis/G2#3821]
目前使用特殊标记点做最大最小值标志时，发现当该标记点的位置距坐标轴最大值距离很近时，文字会超出容器，无法展示全部。尝试配置limitInPlot仍未解决。

预期效果：标记点及文字展示在图表容器内部

* **G2 Version**: 4.1.16
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/63590555/156317119-013d25a1-0749-428c-a4c1-78513de812ca.png)

* **CodePen Link**: 
      https://codesandbox.io/s/stupefied-wind-emqmoj?file=/index.ts

**Comment by TomorrowLM** [comment]
+1

**Comment by mrh-code-star** [comment]
+1,我这里是条形图末端需要添加文本标签，但是如果用度量（scale）自适应的话最长的条形图的文本会超出容器边界

**Comment by pearmini** [comment]
这个是不可避免的，可以通过设置 padding 解决问题。
