### ISSUE TITLE
Radar chart, tooltip crosshair line, 在数值为零的时候角度错误

### ISSUE THREAD

**Issue by myou** [antvis/G2#3828]
* **G2 Version**: 4.1.45
* **Platform**: 官网 examples
* **Mini Showcase(like screenshots)**:
* ![image](https://user-images.githubusercontent.com/385167/158926256-d64b03fa-bc2b-4d04-91b6-78ca66f13edb.png)
* **CodePen Link**:
https://g2.antv.vision/en/examples/radar/radar#basic

To reproduce:
把任意数值改成零，比如 development -> a，然后 hover over 显示 tooltip，会发现画的 crosshair line 角度永远是 0（向右）

**Comment by hustcc** [comment]
感谢，很好的反馈。我们来看看修复掉。

**Comment by ai-qing-hai** [comment]
@myou  可以暂时 加上 0.025 的内半径

**Comment by hustcc** [comment]
本质是极小数对交互事件拾取带来的问题。
