### ISSUE TITLE
https://new-issue.antv.vision/ version dropdown 为空，无法 submit issue

### ISSUE THREAD

**Issue by myou** [antvis/G2#3829]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

https://new-issue.antv.vision/
![image](https://user-images.githubusercontent.com/385167/158926191-2fd6c4be-e92b-48b5-985b-c7067fe9e6d7.png)

**Comment by visiky** [comment]
先用这个解决下：
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/15646325/160050211-2231c57c-b8eb-4e20-81e7-6ff965460704.png">
