### ISSUE TITLE
npm run demos 后,assets资源404。

### ISSUE THREAD

**Issue by wu38607** [antvis/g2#383]
os：ubuntu16.04
node：8.9.4
npm：5.6.0

Request URL:http://127.0.0.1:33707/demos/assets/screenshots/map-drill-down.png
Request Method:GET
Status Code:404 Not Found
Remote Address:127.0.0.1:33707
Referrer Policy:no-referrer-when-downgrade

**Comment by leungwensen** [comment]
需要自行截图：`npm run screenshot`
