### ISSUE TITLE
基础条形图数据有一条为0时，tooltip没有提示

### ISSUE THREAD

**Issue by suran101** [antvis/G2#3835]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/bar/basic#basic](https://g2.antv.vision/zh/examples/bar/basic#basic)

### Steps to reproduce
把基础条形图中的一个值改成 0
![image](https://user-images.githubusercontent.com/55876086/159648070-31efac7a-b45e-437b-832d-e9e06830e274.png)

| Environment | Info |
|---|---|
| g2 | 4.1.48 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
算是合理的，因为事件的拾取是根据图形来的，数据为 0，所以图形也是看不到的。不过可以改变拾取的方式：

```ts
chart.tooltip({
  showMarkers: false,
  shared: true,
});
```

![image](https://github.com/antvis/G2/assets/7856674/79522533-a4a5-4e60-9ead-1a09d432a525)
