### ISSUE TITLE
when data=[] point chart occur undefined bug

### ISSUE THREAD

**Issue by huxiaoyun** [antvis/g2#384]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

https://antv.alipay.com/zh-cn/g2/3.x/demo/point/bubble.html

in this demo, when i  change data = [] ,   chart.render occurs  a bug 

![image](https://user-images.githubusercontent.com/4345248/34833977-b5e1652e-f72b-11e7-9574-efe7f0824b59.png)

I traced this bug , it probably  occurs by  renderLegend .

**Comment by dxq613** [comment]
I had fixed this bug, see #311
