### ISSUE TITLE
G2 可以实现多个x轴吗？如果x轴有二级分类怎么实现呢？

### ISSUE THREAD

**Issue by FightingJane** [antvis/g2#385]
* **G2 Version**:3.0.2-beta.1
* **Platform**:PC
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

下图所示的X轴有二级分类的可以实现吗？按照实现多y轴的方式试了下好像不行。。。
![image](https://user-images.githubusercontent.com/13446642/34855828-c768fdce-f77c-11e7-9a08-608125538550.png)

**Comment by leungwensen** [comment]
暂时不支持二级坐标轴

**Comment by dxq613** [comment]
直接使用分面（facet) 功能：

https://antv.alipay.com/zh-cn/g2/3.x/demo/facet/column.html

**Comment by FightingJane** [comment]
谢谢啦，也是一种方法，但是不是很满足用户的需求，他们想要连续的图形
