### ISSUE TITLE
缩略轴手柄重合

### ISSUE THREAD

**Issue by zailushang5011** [antvis/G2#3853]
使用缩略轴筛选的时候往右拖两个手柄需要重合才能筛选出最右边的一条数据，往左拖就不需要重合就能筛选出最左边的一条数据
<img width="642" alt="lQLPDhtOfGdoo-zNArjNBQSwzBpe7fAgSn0CUUO7oMABAA_1284_696" src="https://user-images.githubusercontent.com/57588659/162109800-34d2ba9e-cea3-489e-ad55-760fe9beebfd.png">
<img width="649" alt="lQLPDhtOfGdoo3fNApTNBRKwvt_TjzBQ5oQCUUO7nkAeAA_1298_660" src="https://user-images.githubusercontent.com/57588659/162109808-e9768e03-c021-4c50-bbf0-85b8ae55012b.png">

**Comment by visiky** [comment]
没有使用二分法，向上取整向下取整导致的；可以深入到源码中，修改下
