### ISSUE TITLE
label支持点击穿透

### ISSUE THREAD

**Issue by zailushang5011** [antvis/G2#3859]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
柱状图label超出element后，可能会覆盖在另一个element之上，hover到超出到另一个element的label是效果是另一个element的hover效果，但是点击的时候还是当前这个label；

### What does the proposed API look like?
label中加入一个配置，点击是否穿透

**Comment by hustcc** [comment]
已经有这个，可能文档上没有表达出来。

```ts
chart
  .line()
  //...
  .label('value', {
    style: { capture: false }, // 👈🏻 不捕获事件，点击会穿透
  })
```
