### ISSUE TITLE
g2实例调用clear方法，clear代码报错

### ISSUE THREAD

**Issue by yyidota** [antvis/g2#386]
* **G2 Version**:
3.0.3
* **Platform**:
mac
* **Mini Showcase(like screenshots)**:
代码出错：
![image](https://user-images.githubusercontent.com/11712852/34857839-ece05e16-f787-11e7-9272-0a0dfc9cba43.png)
实例打印：
![image](https://user-images.githubusercontent.com/11712852/34857886-30c96f8c-f788-11e7-84cc-7a68f69eba74.png)

* **CodePen Link**:
https://codepen.io/yami12345/pen/YYLOwq?editors=1111
第92行代码

打印实例，它下面是有clear方法的，调用的时候发现，clear方法内部var options = this.get('options'); 当这里获取到的options为undefined的时候，代码报错，中断后面代码执行。

**Comment by dxq613** [comment]
你给的 codepen 跟你描述的问题不一致吧？

**Comment by leungwensen** [comment]
这个 issue 是因为全局变量的问题。已在钉钉上沟通解决

**Comment by dxq613** [comment]
我说呢，调试了半天，各种情况下 clear 没出现
