### ISSUE TITLE
希望tooltip组件增加项目的合计功能

### ISSUE THREAD

**Issue by zaite** [antvis/G2#3866]
![image](https://user-images.githubusercontent.com/22079456/163111023-8e0a8523-c389-48e7-b3af-d84ac8d508e6.png)

以上是自己研究实现的，但是不太美观达不到理想的需求

**Comment by hustcc** [comment]
感谢反馈，建议这类都直接走 tooltip 的自定义，因为对于聚合方式，数据来源都不太一样，很难 G2 统一做掉。
