### ISSUE TITLE
图例Legend的maxWidth小于maxItemWidth，造成图例项LegendItem显示不全

### ISSUE THREAD

**Issue by qiaoyuwen** [antvis/G2#3868]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[重现链接](https://codesandbox.io/s/ecstatic-lovelace-hmzc9m)

### Steps to reproduce
![屏幕快照 2022-04-13 下午4 10 08](https://user-images.githubusercontent.com/8097860/163130793-29e41556-5332-411c-ac5a-4031e531fc9d.png)

| Environment | Info |
|---|---|
| g2 | 4.1.50 |
| System | - |
| Browser | - |

**Comment by qiaoyuwen** [comment]
https://github.com/antvis/G2/blob/dc5863164daeef4f2472b811cbbce0576dd1a28d/src/chart/controller/legend.ts#L504

获取分类图例的配置项这里会出现maxWidth > maxItemWidth的情况

**Comment by yehoan** [comment]
我这边也遇到类似的麻烦 我这个是 items 显示不全 设置了itemWidth的话直接就一小部分被隐藏了

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/164883510-4f723bef-ccc5-43a2-bad4-4f66012445be.png)

**Comment by pearmini** [comment]
可以试试 5.0，这个地方的图例应该会缩略。
