### ISSUE TITLE
中文文字遮挡

### ISSUE THREAD

**Issue by break520** [antvis/G2#3877]
![image](https://user-images.githubusercontent.com/103712406/163508073-28dba795-4a54-42c5-a221-8cf39d6476f9.png)
官网demo饼图添加数据，只有legend出现翻页，中文上方就会遮挡一点；

![image](https://user-images.githubusercontent.com/103712406/163508357-4e0cccb2-727f-4bbf-815a-a2bf3f20287d.png)
官网柱状图第一项文字过长时，中英文都有所遮挡

**Comment by hustcc** [comment]
是否设置了固定的 padding，另外，可以把你运行的代码也贴一下，我来复现后排查。
