### ISSUE TITLE
bug 柱形图 使用 scrollbar 缩略轴时渲染不了

### ISSUE THREAD

**Issue by amipei** [antvis/G2#3895]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/column/basic#scrollbar](https://g2.antv.vision/zh/examples/column/basic#scrollbar)

### Steps to reproduce
默认不给数据 ，使用changeData改变数据会导致无法渲染

| Environment | Info |
|---|---|
| g2 | 4.2.0 |
| System | window |
| Browser | 谷歌 版本 100.0.4896.127（正式版本） （64 位） |

**Comment by hustcc** [comment]
有更多信息吗？或者直接可复现的 demo？
