### ISSUE TITLE
Frame.model(frame, x)，众数应该是mode吧，是因为mode方法另有用途么？

### ISSUE THREAD

**Issue by kchjxxgh** [antvis/g2#39]
看文档里面看到了这个方法，虽然这好像不是开源的一部分，但是求众数的英文单词应该是mode，这里为什么用model呢？是因为mode和其他什么冲突么？

**Comment by dxq613** [comment]
抱歉，我看了看，是文档上写错了，应该是Frame.mode

**Comment by redmed** [comment]
不过文档上还没有改过来呢
