### ISSUE TITLE
期望饼图支持图例文字 数字显示对齐，并支持文字超长截断&数字不截断

### ISSUE THREAD

**Issue by smiler158** [antvis/G2#3911]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/antvis/G2](https://github.com/antvis/G2)

### Steps to reproduce
1.设置饼图的文字+数字图例

2.期望达到的效果图： 支持文字超长截断 右边数字不截断
![image](https://user-images.githubusercontent.com/4092586/167762874-e236f181-6af4-435e-91bd-1b59dd754656.png)
![image](https://user-images.githubusercontent.com/4092586/167762911-9795e5b3-78f1-4dd4-a698-8c867756be74.png)

3.实际效果图：要么文字截断不支持hover  要么数字截断了
![image](https://user-images.githubusercontent.com/4092586/167762511-06534d39-4ac6-4291-b208-5546906415e8.png)

| Environment | Info |
|---|---|
| g2 | 4.2.1 |
| System | - |
| Browser | - |

**Comment by maplor** [comment]
重复 Issue #3908
