### ISSUE TITLE
userView.changeData报错

### ISSUE THREAD

**Issue by l17424255** [antvis/G2#3914]
* **G2 Version**: 4.1.13
* **Platform**:
* **Mini Showcase(like screenshots)**:
<img width="973" alt="image" src="https://user-images.githubusercontent.com/10347159/168048835-7c234081-28bd-4626-b937-dc8ff985ba63.png">

更新数据时，数据更新成功，但是重新渲染Label的时候报错
userView.changeData(userData)
-----
.label('num', (value) => {
        return {
          content: value > 0 ? `${value}处` : '',
          offsetY: 20,
          style: {
            fontSize: 24,
            fontFamily: 'PangMenZhengDao',
            fill: '#05F8E5'
          }
        }
      })
自定义label注释以后就不会报错

**Comment by hustcc** [comment]
可以方便提供一个在线 demo 吗？
