### ISSUE TITLE
two-axis chart

### ISSUE THREAD

**Issue by asweetonion** [antvis/g2#392]
I want a two-axis chart showing the grouping histogram and two line chart, how to do it?

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/tutorial/fqas.html#_%E5%A6%82%E4%BD%95%E7%BB%98%E5%88%B6%E5%A4%9A-y-%E8%BD%B4%E5%9B%BE%E8%A1%A8

**Comment by asweetonion** [comment]
thanks for your attention,and what about a two-axis chart showing the Grouped Column Chart and a line chart?

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/demo/bar/grouped-column.html

https://antv.alipay.com/zh-cn/g2/3.x/demo/line/series.html

We do not have exactly the same chart you want, but if you seek a little deeper into these demos, you can find the answer to your question.
