### ISSUE TITLE
TreeMap 显示parent title

### ISSUE THREAD

**Issue by meyergin** [antvis/G2#3925]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如果是Nested Treemap，建议增加能显示父类目的title polygon，类似finviz的效果（https://finviz.com/map.ashx）
![image](https://user-images.githubusercontent.com/7495191/168728371-661fdb70-84eb-47ad-ba8a-2faf8f5a7595.png)

### What does the proposed API look like?
现在的api 好像没有办法支持多级level的逻辑，position和color

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/169194487-03c4b46c-a35a-43e0-8ba3-11c4903eb53e.png)

是指这个吗？ @meyergin

**Comment by meyergin** [comment]
> ![image](https://user-images.githubusercontent.com/7856674/169194487-03c4b46c-a35a-43e0-8ba3-11c4903eb53e.png)
> 
> 是指这个吗？ @meyergin
是的，这个是二级类目，上面的Technology是一级类目，见下图，我框出来了
![image](https://user-images.githubusercontent.com/7495191/169198562-c3b6783d-0d24-4def-adda-cfc5a2b52128.png)

**Comment by hustcc** [comment]
这个多 label 情况，当前 4.x 不是特别好做，但是在新版本 5.0 中比较[容易实现](https://g2.antv.antgroup.com/examples/general/interval#bar-marimekko)。

**Comment by meyergin** [comment]
> @meyergin finviz是不是直接用d3实现的？

应该不是，d3的treemap很简单
