### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by asolas** [antvis/g2#393]
antv/data-set@0.8.3
antv/g2@3.0.4-beta.3
webpack@2.7.0

正常引入，"Cannot find module **"报错
直接从build路径引入可以：
```
import G2 from '@antv/g2/build/g2';
import { DataSet } from '@antv/data-set/build/data-set';
```

**Comment by leungwensen** [comment]
pkg 定义里 main 字段指向的就是 './build/g2' 应该和你写的是一样的。

你说的“正常引入”是怎么写的？

**Comment by asolas** [comment]
@leungwensen 
文档里的方法
```
import G2 from '@antv/g2';
import { DataSet } from '@antv/data-set';
```
import之后直接找到index.js了，导致很多'./src'路径报错，package.json里面的设置似乎没生效

**Comment by leungwensen** [comment]
@asolas  `module` 字段指向的 index.js 是存在的，是打包前的源码。之所以设置这个字段，是考虑到有依赖源码做打包的需求（譬如避免 lodash 这样的模块重复打包）。这个引用方法应该也是没问题的。具体报错的日志可以贴上来吗？

**Comment by leungwensen** [comment]
譬如 BizCharts 里的引用就是源码引用： https://github.com/alibaba/BizCharts/blob/master/src/index.jsx#L1

**Comment by asolas** [comment]
@leungwensen 

大致就是DataSet组件的index.js里require的'./src'文件路径缺失：
```
ERROR in ./~/@antv/data-set/index.js
Module not found: Error: Can't resolve './src/data-set' in '/Users/***/node_modules/@antv/data-set'
 @ ./~/@antv/data-set/index.js 64:17-42

ERROR in ./~/@antv/data-set/index.js
Module not found: Error: Can't resolve './src/api/geo' in '/Users/***/node_modules/@antv/data-set'
 @ ./~/@antv/data-set/index.js 2:0-24

......
```
试了下G2是可以，问题在DataSet组件
如果直接调用index.js，需要把src也打包进来了

**Comment by leungwensen** [comment]
@asolas 是最近的小版本误加了 npmignore 的缘故，已经加回来了，你更新一下 @antv/data-set@0.8.4

**Comment by asolas** [comment]
@leungwensen 

```
ERROR in ./~/@antv/data-set/index.js
Module not found: Error: Can't resolve './src/transform/bin/quantile' in '/Users/***/node_modules/@antv/data-set'
 @ ./~/@antv/data-set/index.js 42:0-39

......
```

./src/transform/bin 这个也需要恢复下

**Comment by leungwensen** [comment]
抱歉，改好了 @asolas `@antv/data-set@0.8.5`

**Comment by asolas** [comment]
@leungwensen 

可以了 (•̀ᴗ•́)و ̑̑  ，thank you！

**Comment by ShawshankLin** [comment]
我也是报了这个错，，怎么改呢？，按照官网的demo引进就报错了

**Comment by asolas** [comment]
@ShawshankLin 

先试试从build引入
`import G2 from '@antv/g2/build/g2';
import { DataSet } from '@antv/data-set/build/data-set';`
