### ISSUE TITLE
右击操作

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#394]
是否考虑在图表库里支持右击事件呢
比如onItemContextMenu

https://github.com/alibaba/BizCharts/issues/101

**Comment by dxq613** [comment]
图表库上加右键事件感觉意义不大吧。流程图 G6 是有这种强需求的，统计图表看感觉必要性不大。

**Comment by weepy3641** [comment]
不一定的，在很多 bi 软件中，右键操作弹操作菜单是很常见的。
比如在某个 interval geom 上点击右键，弹出一些操作菜单，排除、保留柱子啥的，甚至是上卷、下钻，很常见。

**Comment by paleface001** [comment]
4.0支持右键事件了

**Comment by zhensherlock** [comment]
4.0支持右键事件了???你哪里看到了

**Comment by zhensherlock** [comment]
那4.0什么时候发布？
