### ISSUE TITLE
区间面积图开启slider未生效

### ISSUE THREAD

**Issue by victorting** [antvis/G2#3948]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/happy-chatelet-yy0hts)

### Steps to reproduce
看文档说slider在4.x版本已经内置，按照文档的示例demo在区间面积图中开启slider没有起作用，不知道是我代码问题还是功能性问题

| Environment | Info |
|---|---|
| g2 | 4.2.2 |
| System | window10 |
| Browser | Chrome 100 |

**Comment by hustcc** [comment]
4.x 中 多 view 的 slider 确实有一些问题，目前不支持。或者实现起来会比较麻烦，需要给 view1 设置 slider，然后 slider change 的时候，给 v2 过滤数据。
