### ISSUE TITLE
关于折线图的2个疑问

### ISSUE THREAD

**Issue by radicalviva** [antvis/g2#396]
1. 是否可以支持2个 Y 轴坐标系？
2. Y 轴刻度值是否可以不展示啊，就用折线展示趋势？

希望能回答下啊，目前在 `G2` 和 `Echarts` 的选型中。。。

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/tutorial/fqas.html#_%E5%A6%82%E4%BD%95%E7%BB%98%E5%88%B6%E5%A4%9A-y-%E8%BD%B4%E5%9B%BE%E8%A1%A8

https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_chart.axis-false-
