### ISSUE TITLE
可以让x轴固定不偏移吗

### ISSUE THREAD

**Issue by Dawnwangzi** [antvis/G2#3989]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://g2.antv.vision/zh/examples/line/basic#curved](https://g2.antv.vision/zh/examples/line/basic#curved)

### Steps to reproduce
- 把 https://g2.antv.vision/zh/examples/line/basic#curved 中的数据随便改一个改成很大的比如12000.
- 点击图例隐藏掉有很大数据的那条线
- 可以看到x轴发生向左向右的偏移

| Environment | Info |
|---|---|
| g2 | 4.2.3 |
| System | - |
| Browser | - |

---
- 能理解因为y轴的数值是发生变化了的，所以x轴被挤了一下有平移，但是可不可以把y轴位置固定住，不让发生数值较大变化的时候有轴的偏移呢？
- 期望能把轴固定住不动，给y轴左侧文字留一个固定大小的位置或者y轴超过一定宽度了之后再去压图的大小

**Comment by hustcc** [comment]
```ts
const chart = new Chart({
  container: 'container',
  autoFit: true,
  height: 500,
  padding: [0, 50, 50, 50], // 这里
});
```

不设置 padding 的时候，padding 是自动根据四周的组件大小计算的，所以数值大的时候，y 轴占用宽，所以 x 轴有一些偏移，只要固定左侧边距就可以了。
