### ISSUE TITLE
堆叠图形的堆叠顺序现在固定是逆序的，体验很不好，可以提供配置吗？

### ISSUE THREAD

**Issue by tianlaixhh** [antvis/g2#399]
＃＃我的需求/我的问题
我在使用堆叠柱状图时发现堆叠是按照数据逆序的排列的，与图例刚好相反

＃＃ 数据及问题的源代码
请以官网上为例：https://antv.alipay.com/zh-cn/g2/3.x/demo/bar/stacked-percentage-column.html

为什么Europe的数据在上面，而Asia的数据在下面，很不合理，与highchart和Excel画出的图相反。

＃＃我的期望
能改成正顺或者提供配置吗？就像盖房子，从下到上一层一层的来，而不是现在看起来很别扭（用户体验很差）。

**Comment by leungwensen** [comment]
如果你把 legend 放到右边的时候，你会发现，legend 的顺序和图的顺序是一致的：

![image](https://user-images.githubusercontent.com/1655789/35033337-43a22c2c-fba5-11e7-874e-d11c4601e7f8.png)

事实上，仔细的话，这个顺序和 hightCharts 是一致的呀

**Comment by leungwensen** [comment]
![image](https://user-images.githubusercontent.com/1655789/35033471-bea05e26-fba5-11e7-8f83-a661d9d4eac2.png)

![image](https://user-images.githubusercontent.com/1655789/35033493-d382e99e-fba5-11e7-9e88-f5871c8d1bff.png)

**Comment by tianlaixhh** [comment]
无论是不是一致，highchart里面可配置。我看另一位同学提的你已经加入plan了，跟我的要求是一样的。
