### ISSUE TITLE
堆叠柱状图能否加一个配置可以像highcharts那样设置堆叠的顺序？

### ISSUE THREAD

**Issue by FightingJane** [antvis/g2#400]
* **G2 Version**:3.0.2-beta.1
* **Platform**:PC
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

一组数据，有展示堆叠顺序的要求，发现g2只能从上往下堆叠，不能逆序。如果手动把数据顺序改变的话，图例顺序也会改变。请问：

1、能否加个设置堆叠顺序的参数，不改变图例的顺序？
2、能否设置当某个柱子的颜色为透明的时候不显示图例？

想要的效果：
![image](https://user-images.githubusercontent.com/13446642/35034407-0760915a-fba9-11e7-956c-1e26ef5d8ebd.png)

实际的效果：
![image](https://user-images.githubusercontent.com/13446642/35034392-f8b5b8e2-fba8-11e7-9e43-881d1d0e32da.png)

**Comment by leungwensen** [comment]
目前可以通过设置 scale 的方式来指定 legend 的顺序。譬如这个 demo

https://antv.alipay.com/zh-cn/g2/3.x/demo/bar/stacked-percentage-column.html

指定字段 `country` 的 scale 对应的 values 就可以实现逆序了：

```js
chart.scale('country', {
  values: [ 'Asia', 'Europe' ]
});
```

legend 的顺序将会和 values 指定的顺序一致。

**Comment by leungwensen** [comment]
@dxq613 make data adjust configurable.

**Comment by FightingJane** [comment]
但是这样只能改变图例的顺序，我想要的是堆叠顺序变，图例顺序不变。
看了你们源码，条形图可以设置reverseOrder，允悲。。为啥不让柱状图也可以呢，居然写死了。。。

**Comment by leungwensen** [comment]
嗯嗯，堆叠这个数据调整目前有点 bug，reverseOrder 配置项还没有开放出来，请稍等

**Comment by FightingJane** [comment]
请问这个啥时候发版呢？官网好像还不支持reverseOrder

**Comment by leungwensen** [comment]
明天会发一个小版本

**Comment by FightingJane** [comment]
貌似没有发版，请问啥时候发啊？这个顺序对视觉的影响还挺严重的

**Comment by leungwensen** [comment]
已经发了的，官网因为春节封网还没更新到最新版本。用最新的 `g2@3.0.5-beta.3` 是有这个特性的

**Comment by FightingJane** [comment]
好的，谢谢
