### ISSUE TITLE
1、按照限定的时间段渲染条形图；x轴是时间 2、能展示时间刻度，时间间隔最好是能均匀分布，或者自己设置

### ISSUE THREAD

**Issue by vuehl** [antvis/G2#4007]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

请问目前这个条形图支持么？按api文档测试没达到效果，不知道是不是属性设置的问题

### What problem does this feature solve?
优化了 x轴为时间格式有刻度设置的问题

### What does the proposed API look like?
属性

**Comment by hustcc** [comment]
```ts
chart.scale('date', { type: 'time' })
```
