### ISSUE TITLE
请问曲线折线图能自定义样式吗，如内容

### ISSUE THREAD

**Issue by chesongsong** [antvis/G2#4027]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
自定义样式

### What does the proposed API look like?
如图

![image](https://user-images.githubusercontent.com/21020093/177321228-9b8ffce2-d93e-40fc-a5d2-c63d40313354.png)

**Comment by hustcc** [comment]
这样样式的自定义不是很困难。

```
{
  lineWidth: 8,
  stroke: 'blue'
}
```
