### ISSUE TITLE
At first, i am here to lean how to use RegionFilter API. BUT, notice that you say that we need to use English in China version.Why? yep, some foreigners are using G2, but please be more POLITE!

### ISSUE THREAD

**Issue by Le-coder** [antvis/g2#4028]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
At first, i am here to lean how to use RegionFilter API. BUT, notice that you say that we need to use English in China version.Why? yep, some foreigners are using G2, but please be more POLITE!

### What does the proposed API look like?
At first, i am here to lean how to use RegionFilter API. BUT, notice that you say that we'd better use English in the China version. Why? yep, some foreigners are using G2, but please be more POLITE! POLITE to notice us!

**Comment by hustcc** [comment]
Sorry, at present, the percentage of foreigners is very few, and now the Chinese docs are not very good, there will be plans to translate them into English in the future after Chinese document ready.
