### ISSUE TITLE
多条折线图无法设置一条折线一条曲线

### ISSUE THREAD

**Issue by tianlaixhh** [antvis/g2#403]
＃＃ 我的需求/我的问题
分组折线图无法一条折线一条曲线。
类似的图表如分组柱状图、堆积面积图都不可以针对其中一个系列做特殊配置。

＃＃ 数据以及出现问题的源代码
以官网示例举个例子：https://antv.alipay.com/zh-cn/g2/3.x/demo/line/curved.html

  // shape设置为smooth则所有线都成了曲线
chart.line().position('month*temperature').color('city').shape('smooth');

＃＃ 我的期望
可以分别设置每条线的特性

**Comment by leungwensen** [comment]
像那个 demo，你可以把数据分拆成两份，伦敦的温度数据一份，东京的温度数据一份，然后用两个 view 来画就可以了。

**Comment by tianlaixhh** [comment]
首先，这样可以实现，但是就比较麻烦了，类似的面积图如果一个曲线一个折线也要分两个view，同时拆分数据。

看了下源码，shape可以传一个数组，
line.shape('type', [ 'line', 'smooth', 'hv' ]); // 指定线型

**Comment by dxq613** [comment]
shape 映射本身就是干这个的。

.shape('city', city => {if (city == 'Tokyo'){ return 'smooth' } else return 'line'})
