### ISSUE TITLE
坐标轴Axis的postion不可扩展（只有四个可选值），无法设置坐标轴交叉点的数值

### ISSUE THREAD

**Issue by tianlaixhh** [antvis/g2#404]
＃＃ 我的需求/我的问题
希望在笛卡尔坐标系的四个象限画出图表，而目前的Axis的position只能设置为top、bottom、left、right四个固定的值。

＃＃ 我的期望
希望可以设置x、y坐标轴交叉点的数值。

**Comment by dxq613** [comment]
你可以通过 guide 绘制出 x,y 是 0 的时候的线。

**Comment by tianlaixhh** [comment]
但是guide的线没有坐标值，与坐标轴的作用还是相差较大，我目前的需求是能够在四个象限画出图形。

Excel里面可以，highchart目前确实也不支持，希望G2能加入这个特性（其实是更接近数学中的笛卡尔坐标系），这样很多行业的图表都可以使用G2来画了。谢谢！

**Comment by dxq613** [comment]
这个最简单的方案是给 坐标轴增加 dx, dy 的偏移量，但是这种仅适合于固定大小的图表。真正的数学坐标轴，所有图表不支持的很大一个原因在于坐标轴和文本显示在中间，会导致文本被覆盖，另外两个坐标轴本来是可以分开绘制，但是这种坐标轴需要跟垂直的坐标轴进行耦合。

**Comment by tianlaixhh** [comment]
对你们的考虑表示理解。
