### ISSUE TITLE
point 图形下触发tooltip是否可以增加基于轴的逻辑

### ISSUE THREAD

**Issue by meyergin** [antvis/G2#4049]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
point图形现在鼠标触发的逻辑是靠近点，是否可以增加基于x或者y轴的触发，类似line图形的逻辑，用于cat等非散点的分类点展现

### What does the proposed API look like?
比如增加TooltipCfg.positon, 支持(x,y)点，(x)和(y)轴

**Comment by visiky** [comment]
这个在新版 G2 5.0会支持，旧版暂时没计划
