### ISSUE TITLE
饼图点击图例动画过程中label文字会有重影。只在canvas中存在

### ISSUE THREAD

**Issue by gugol-boor** [antvis/G2#4059]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://antv-g2.gitee.io/zh/examples/pie/basic#labelline](https://antv-g2.gitee.io/zh/examples/pie/basic#labelline)

### Steps to reproduce
点击饼图的图例

| Environment | Info |
|---|---|
| g2 | 4.2.5 |
| System | - |
| Browser | - |

**Comment by hustcc** [comment]
设置一下 localRefresh: flase

```ts
new Chart({
  localRefresh: false,
})
```
