### ISSUE TITLE
Release a new version to NPM

### ISSUE THREAD

**Issue by nicolas-besnard** [antvis/g2#407]
Last version is 2.3.4 which is quite old. Can you release 3.x.x on npm?

**Comment by dxq613** [comment]
You can use  @antv/g2, it is the lasted version.

**Comment by leungwensen** [comment]
@nicolas-besnard, the latest version of G2 on npm is `@antv/g2@3.0.4-beta.4`.

We added a prefix `@antv/` for g2 above 3.0
