### ISSUE TITLE
当图例显示不全收缩时，g2图表库可能会出现图例文字渲染不全

### ISSUE THREAD

**Issue by harrain** [antvis/G2#4080]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/harrain](https://github.com/harrain)

### Steps to reproduce
当图例显示不全收缩时，g2图表库可能会出现图例文字渲染不全；图例能全部显示，不会出现。

| Environment | Info |
|---|---|
| g2 | 4.2.5 |
| System | window10 |
| Browser | Version 97.0.4692.99 (Official Build) (64-bit) |
]

**Comment by hustcc** [comment]
求一个案例代码，或者至少一个截图说明一下。
