### ISSUE TITLE
能否支持复合饼图，复合条饼图？

### ISSUE THREAD

**Issue by tianlaixhh** [antvis/g2#409]
能否支持类似Excel中提供的复合饼图，复合条饼图？尝试用多View和Facet来做，关联线很难画出来

![2018-01-19 3 10 07](https://user-images.githubusercontent.com/12244208/35138878-7b5e7e5e-fd2b-11e7-9678-f7e302de193b.png)

这种场景在Highchart里面会采用下钻图的形式体现，但是体验也不好，希望G2可以支持类似Excel的效果。（实质是多极的饼图）

**Comment by dxq613** [comment]
要完成这个功能，需要饼图进行旋转，点击选中的放到右侧才行。还是使用两个 view 进行联动吧。
饼图本身有选中操作，然后附加的图使用柱状图，使用跟饼图相同的颜色即可。

一个交互只要有反馈，两个图中间使用颜色的对应关系，还是很好理解和使用的。

**Comment by tianlaixhh** [comment]
饼图的旋转可以默认将要分解的扇区放置在第一块，可以保证在最右侧；
使用两个view可以达到联动的效果，但是之间的连接线我很难画出来，试过guide，geom等各种，都没有达到效果，请问是否有办法灵活的画一下关联线（没必要像上图一样这么精准，能够告知用户，右侧是左侧哪一块的细分即可）？

**Comment by leungwensen** [comment]
有个很 hack 的做法，某一块图形区域的 BBox 可以这么算：

```js
chart.get('geoms')[0].get('shapeContainer').get('children')[0].calculateBox()
```

“复合饼图”并不是很标准，应该暂时不会内置。

**Comment by dxq613** [comment]
这个不会进行内置，但是后续可以提供个 demo
