### ISSUE TITLE
坐标轴能否支持分组？

### ISSUE THREAD

**Issue by tianlaixhh** [antvis/g2#410]
现实场景中有很多图表的源数据是分组的（或者是多极分组，即树状的），在展示时希望能在坐标轴上有所体现，类似Excel的效果：

![x](https://user-images.githubusercontent.com/12244208/35139209-1010b124-fd2d-11e7-86c4-522f81e6be03.jpg)

**Comment by dxq613** [comment]
你可以使用列表 分面 facet ，每个子图都有对应的 title，y 轴也可以统一

![image](https://user-images.githubusercontent.com/1264678/35141997-e555e85e-fd37-11e7-850e-43982c09903d.png)

**Comment by dxq613** [comment]
![image](https://user-images.githubusercontent.com/1264678/35143010-174d8ddc-fd3b-11e7-9809-2dafdaf160c7.png)

**Comment by tianlaixhh** [comment]
用分面对于两级结构是可以的，把标题展示在bottom位置就跟Excel的结构很类似了。

但是分面貌似是不能嵌套的，对于多极的结构就没办法再处理了；如果使用facet('tree') 的话样式好像就固定了（当然如果tree能够倒转也是接近效果的，不知道可不可以开放rotation的配置～）

**Comment by dxq613** [comment]
目前分面的位置信息是固定的，不过可以在 eachView 里面改。 titlte 的话可以通过 showTitle: false 关闭 title，用 guide 自己绘制 title

![image](https://user-images.githubusercontent.com/1264678/35145773-fe25bb96-fd43-11e7-9f43-eb856f83fc11.png)

```js
chart.facet('tree', {
      fields: ['clarity'],
      line: {
        stroke: '#c0d0e0'
      },
      lineSmooth: true,
      // padding: 0,
      eachView: (view, facet) => {
        var start = view.get('start');
        var end = view.get('end');
        start.y = 1 - start.y;
        end.y = 1 - end.y;
        const data = facet.data;
        const dv = new DataView();
        dv.source(data)
          .transform({
            type: 'aggregate',
            fields: [ 'price' ],
            operations: [ 'mean' ],
            as: [ 'mean' ],
            groupBy: [ 'cut' ]
          });
        view.source(dv);
        view.interval()
          .position('cut*mean')
          .color('cut');
      }
    });
```
