### ISSUE TITLE
多个渲染

### ISSUE THREAD

**Issue by wwb-xigua** [antvis/G2#4103]
同一个class内new Chart{}两个或多个，第二个之后的多个chart会在某一周期显示一次然后消失

**Comment by wwb-xigua** [comment]
是以函数的形式传入componentDidMount中进行实力化的

**Comment by visiky** [comment]
show code, talk is less.

**Comment by hustcc** [comment]
> 同一个class内new Chart{}两个或多个，第二个之后的多个chart会在某一周期显示一次然后消失

不同的 Chart 实例，用不用的 class 就好了，不然就是会出现问题。
