### ISSUE TITLE
饼图 legend 为日期类型，会缺失图例，也可能会出现NaN

### ISSUE THREAD

**Issue by th-wu** [antvis/G2#4105]
## 背景

- legend展示未展示全
- https://codesandbox.io/s/blazing-moon-i899qf

## 思路

- legend值识别为‘cat’而非‘timeCat’时，期望结果达成

**Comment by hustcc** [comment]
识别类型根据数据和一些规则来的，可能会有失误的情况，可以手动设置为 timeCat

```ts
chart.scale('legend-field', { type: 'timeCat' });
```
