### ISSUE TITLE
极坐标坐标轴axis label被遮挡

### ISSUE THREAD

**Issue by pyuyu** [antvis/G2#4107]
```ts
chart.axis('x-field', { top: true });
```

设置 top = true，可以让 axis 的内容绘制在图形的上层，防止被覆盖。

_Originally posted by @hustcc in https://github.com/antvis/G2/issues/3498#issuecomment-939239932_

`chart.axis('x-field', { top: true });`会导致geometry被坐标轴grid遮挡， 请问可以支持单独给axis的label设置top吗
<img width="542" alt="image" src="https://user-images.githubusercontent.com/16910913/186128666-0ab15e4a-47f2-47d3-a1cb-1dd4b4b1ebdf.png">

**Comment by TopAlien** [comment]
同需求，hover时点能全部显示，emm 不知道怎么弄的

**Comment by visiky** [comment]
4.x 版本无法支持，需要等 G2 5.x版本了
