### ISSUE TITLE
X轴的刻度个数是否能够图标宽度自适应改变

### ISSUE THREAD

**Issue by radicalviva** [antvis/g2#411]
目前是这样的情况，假如我要展示 30 天的折线图
希望在大屏幕下出现 15 个数据点
小屏幕下出现 10 个数据点
我一旦设置了 `ticks` 数组 或者设置 `tickCount`，都不会随着图表宽度的变化而改变。。
有什么办法可以支持自适应吗？
希望帮我解答下

**Comment by dxq613** [comment]
目前没有提供这种功能

**Comment by radicalviva** [comment]
后期，有考虑增加上这个功能吗？

**Comment by dxq613** [comment]
目前没加的最大的一个原因在于 ticks 的计算是在列定义里面定义的，而列定义生成的度量是在坐标轴生成之前创建的，所以流程上有些问题，而且还要依赖坐标轴上文本格式化后的长度。

**Comment by JasonDung** [comment]
我目前是这样处理的，根据屏幕的大小来赋予tickCount的个数。

**Comment by JasonDung** [comment]
可以根据屏幕的大小来设置tickCount

**Comment by JasonDung** [comment]
可以这样处理，当屏幕改变时，判断大小，设置tickCount为10或者15

**Comment by leungwensen** [comment]
同意 @JasonDung 这个是属于比较业务化的场景，很难给一个通用的方案出来
