### ISSUE TITLE
ScaleOption 的 mask 无法显示当前时区时间

### ISSUE THREAD

**Issue by fantasybye** [antvis/G2#4112]
##### Checklist

- [x] `npm test` passes
- [x] benchmarks are included
- [x] commit message follows commit guidelines
- [x] documents are updated

##### Description of change

目前 mask 之后显示的一直是格林威治时间，即使可以加上 TimeZone 但并不如直接显示当前时区的时间来的更加直观

**Comment by hustcc** [comment]
G2 底层的日期格式化直接使用 [fecha](https://www.npmjs.com/package/fecha)，所以 mask 的值，可以参考他的文档，应该是能满足你对日期格式显示的需求。
