### ISSUE TITLE
regionFilter设置渐变颜色 

### ISSUE THREAD

**Issue by viernevc** [antvis/G2#4118]
请问regionFilter可以设置填充渐变色吗， 设置style填充不生效

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/205908585-3e56f6d5-f3ac-4496-97db-308b8edf3bb9.png)

```ts
chart.annotation().regionFilter({
  top: true,
  start: [1700, 'min'],
  end: [1753, 'max'],
  color: 'l(0) 0:#ffffff 0.5:#7ec2f3 1:#1890ff', // 👈🏻
  apply: ['area'],
});
```

关于渐变色的写法，[参考文档这里](https://g2-v4.antv.vision/zh/docs/api/shape/shape-attrs#%E6%B8%90%E5%8F%98%E8%89%B2)。
