### ISSUE TITLE
基础面积图（有负值） ，在Chart, 设置padding：[35, 35, 35, 35]} 有异常

### ISSUE THREAD

**Issue by PancakeLa** [antvis/g2#414]
基础面积图（有负值） ，在Chart, 设置padding：[35, 35, 35, 35]} 有异常， 图片没有呗padding压进去，而是外溢了，望确认！

地址：https://antv.alipay.com/zh-cn/g2/3.x/demo/area/with-negative.html

**Comment by leungwensen** [comment]
默认的 padding 不是 0，而你设置的这个值比默认值小，所以出现这个现象

**Comment by PancakeLa** [comment]
没问题了，谢谢
