### ISSUE TITLE
数据变化后，重新render，label重叠

### ISSUE THREAD

**Issue by LMLGM** [antvis/G2#4148]
https://user-images.githubusercontent.com/58587791/190606331-6176ebdb-ddc3-4445-8c3b-e443c1d777f3.mov

![image](https://user-images.githubusercontent.com/58587791/190606575-297f0122-ab15-44a9-93d6-d3866ed50036.png)
在监听数据变化的useEffect里，执行了上图的代码

**Comment by lxliang912** [comment]
试试clear一下，然后再render
