### ISSUE TITLE
可否有相关api支持当某一年份数值为空时，线能连起来

### ISSUE THREAD

**Issue by JasonDung** [antvis/g2#415]
如图：
![image](https://user-images.githubusercontent.com/17819197/35212415-fd96a8b8-ff94-11e7-82dd-19f725164a2b.png)
当某一年份数值为null时或没有时，该线就连不起来了，是否有相关api支持连接成一个完整的折线？
谢谢。

**Comment by leungwensen** [comment]
如果这种情况需要连，可以直接数据把 null 值那行过滤掉就行

**Comment by JasonDung** [comment]
@leungwensen  这样的话我x轴不就看不到该年了嘛？从数值角度来说，我这一年是有的，只不过对应的值为null而已

**Comment by JasonDung** [comment]
能否跟highcharts或者echarts中那样有对应的connNulls属性设置

**Comment by dxq613** [comment]
可以在列定义里面加个 ticks: [] 设置所有的刻度值。

这个 connNulls 参数之前加过，但是后来发现没人使用，所以移除掉了。

**Comment by leungwensen** [comment]
可以在 scale 里配置 values，你找的那个例子加上这一段就 OK 了：

```js
  const values = data.map(row => row.year);
  values.push('1994');
  values.sort((a, b) => a - b);
  chart.scale('year', {
    range: [ 0 , 1 ],
    values
  });
```

**Comment by JasonDung** [comment]
@leungwensen  这样线是连不起来，我要是让线连起来的话，看来只能删除x轴对应的年数值了，不然会看着不好看。

**Comment by JasonDung** [comment]
非常感谢各位的回答，谢谢

**Comment by leungwensen** [comment]
就是先删除 null 数值的行，然后加那一段代码。或者先删除 null 数值的行，然后指定 ticks，这样都是能连起来的。@JasonDung 你试一下？

**Comment by dxq613** [comment]
已经增加了 G2.Global.connectNulls 的支持，设置  G2.Global.connectNulls = true 即可
