### ISSUE TITLE
折线图和面积图切换之后，图上的数据没有完全渲染

### ISSUE THREAD

**Issue by luyao2158** [antvis/G2#4158]
描述：

1. 数据量比较大，每次渲染都有2880条，第一次渲染的数据中有null的情况，第二次渲染的数据都是大于0的数据
2. 第一次渲染折线图是完全展示的（数据中有null），切换数据就会展示不全（数据中没有null），鼠标hover上去，折线图/面积图完全展示出来

效果展示：
https://user-images.githubusercontent.com/40731270/191162562-1d3f0a1d-324d-4786-8c2d-7aea35fd1294.mov

**Comment by hustcc** [comment]
试试这个：

```ts
new Chart({
  // ...
  localRefresh: false,
})
```
