### ISSUE TITLE
guide过大导致鼠标移动到guide，tooltip不触发

### ISSUE THREAD

**Issue by ajsdhf** [antvis/g2#416]
使用guide绘制div的时候，div会遮挡canvas，导致鼠标滑过guide，tooltip会隐藏

* **G2 Version**: 3.0.4
* **Platform**: mac
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/3477307/35214329-cfa8ecca-ff9b-11e7-9e66-faaf7788551b.png)

* **CodePen Link**:

**Comment by leungwensen** [comment]
大至急

**Comment by dxq613** [comment]
那只能通过设置 guide css 的 zIndex，放到 canvas 的下面。

**Comment by ajsdhf** [comment]
目前就是这么做的，但是这样会导致栅格线在guide的上面，如果guide是个带底色的块，就没法看了

**Comment by stanleyxu2005** [comment]
@dxq613 应该是提高tooltip的zIndex吧？

**Comment by dxq613** [comment]
新版本中不再支持 Html 的 guide，会开放自定义 guide (annotation) 的接口。
