### ISSUE TITLE
双轴图在1w条数据下渲染超过7s

### ISSUE THREAD

**Issue by 1208286395** [antvis/G2#4169]
![3D2AD560-F78B-4CD6-842E-CEA1999B309F](https://user-images.githubusercontent.com/49187033/191934067-9b57cf6b-79e6-4629-a3fb-7cf25f101f8e.png)
![D988AE4D-0744-4FB7-926E-42BB3671D67B](https://user-images.githubusercontent.com/49187033/191934146-948631c7-6fec-469a-87fc-7a9f40d9de86.png)

双轴图在1w条数据下渲染超过7秒
复现demo链接：https://codesandbox.io/s/dawn-waterfall-h6liu1?file=/index.js

这个问题能顺手修一下吗哈哈
https://github.com/antvis/G2Plot/issues/3350

**Comment by hustcc** [comment]
ref https://github.com/antvis/G2/issues/4846
