### ISSUE TITLE
饼图 更改别名没有效果？

### ISSUE THREAD

**Issue by xssj28** [antvis/G2#4170]
![饼图](https://user-images.githubusercontent.com/98073863/191935989-3ba28cb3-ba7c-4e7f-a74b-a72b731a30b7.png)

**Comment by hustcc** [comment]
这个改的是 percent 这个字段的别名，不是改某个字段里面值的别名。

**Comment by hustcc** [comment]
这个别名是 percent 字段中的名称，饼图 tooltip 中不会显示这个信息。
