### ISSUE TITLE
【请教】slider拖动结束事件和获取拖动后的最小值和最大值

### ISSUE THREAD

**Issue by chicAboo** [antvis/G2#4172]
问题1描述：有没有slider拖动结束后的事件？
现状：
 chart.on('slider:valuechanged', (e: any) => {
      console.log('drop', e.gEvent.target.cfg.timeline.current, e);
    });
现在使用valuechanged触发，每次改变都要触发一次，拖动结束后会执行多次回调，不满足需求；
希望：希望有一个slider拖动结束后的事件。

问题2描述：slider拖动事件结束后，怎么获取当前slider的最小值和最大值？

**Comment by hustcc** [comment]
```ts
// ...
chart.render()

chart.getComponents().filter(c => c.type === 'slider')[0].component.on('sliderchange', (e) => {
  console.log('drop', e);
});
```

这样拿到的就是 slider 起止位置。对于问题 1，可以增加一个 debounce。
