### ISSUE TITLE
对 donut 配置 guide 后导致 window.scroll 事件对 scrollTop 值计算出错

### ISSUE THREAD

**Issue by faremax1992** [antvis/g2#418]
guide 配置如下：
```
chart.guide().html({
    position: [ '50%', '50%' ],
    html: `<div style="color:#333;font-size:20px;text-align:center;width:40em;line-height:20px;">${state.totalNum}<br><span style="color:#333;font-size:12px;line-height:12px;">${state.fieldName}</span></div>`,
     alignX: 'middle',
     alignY: 'middle'
  });
```

* **G2 Version**: 3.0.4-beta.2
* **Platform**: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by dxq613** [comment]
scrollTop 的值跟整个 Html 页面的 DOM 元素相关，guide.html 是通过 position: absolute 进行定位的，所以没法避免会对页面造成影响。这个问题不是 G2 本身的问题，而是 html 元素对 window 窗口影响的问题。所以不会在 G2 中处理。
