### ISSUE TITLE
请问什么情况下 会出现两个视图 ，并且第一个视图是空白的，也会占高度。第二个视图，然后高度是变成自动的

### ISSUE THREAD

**Issue by xssj28** [antvis/G2#4184]
![image](https://user-images.githubusercontent.com/98073863/193176285-5e62781e-81ca-41a3-84ed-120d04a9e426.png)
![image](https://user-images.githubusercontent.com/98073863/193176632-7136bafe-4a7a-4a6a-a9ac-27b2d529c8a8.png)

**Comment by hustcc** [comment]
应该是业务代码中，导致创建了两个 Chart 实例。

**Comment by wangmin0314** [comment]
解决了吗？怎么解决的？

**Comment by hustcc** [comment]
可以发一下核心代码吗？只能盲猜是 React 中没有使用 useRef 导致多次创建实例。

**Comment by lxliang912** [comment]
每次更新内容前可以考虑是否需求进行clear操作，避免重新创建视图，或者在销毁组件前destroy图表
