### ISSUE TITLE
多折线图有4条折线图时其中2折线数据很大，另外两折线数据量很小时，两条数据量小的折线会重叠在坐标值为0的x轴上

### ISSUE THREAD

**Issue by love123724** [antvis/G2#4194]
##### Checklist

- [ ] `npm test` passes
- [ ] benchmarks are included
- [ ] commit message follows commit guidelines
- [ ] documents are updated

**Comment by hustcc** [comment]
是两种数据量级的数据嘛？如果是，可以 y 轴设置一下 `log` 类型。

**Comment by love123724** [comment]
是的，一种是数量到达十万级，另一种数据量是几十。好的，我试试看 谢谢大佬

**Comment by hustcc** [comment]
两种方法：

1. log
2. 使用[双轴图](https://g2.antv.vision/zh/examples/other/other#double-axes)

**Comment by love123724** [comment]
> 
请问怎么设置log呀，百度没搜索到

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/194790291-8cc5665e-937b-4ad2-948b-4f337812864b.png)

**Comment by love123724** [comment]
好的，谢谢大佬

**Comment by love123724** [comment]
解决了，谢谢大佬，哈哈

**Comment by love123724** [comment]
已解决
