### ISSUE TITLE
啥时候公开源代码

### ISSUE THREAD

**Issue by zhaoxiongfei** [antvis/g2#42]
我看 index.js 里还是 uglify 后的代码。

**Comment by dxq613** [comment]
按照计划，再开发一个大版本

**Comment by zhaoxiongfei** [comment]
很期待，这两天看你们的文档，感觉如沐春风，数据可视化介绍的很有条理。

**Comment by leungwensen** [comment]
已经开源啦，欢迎使用～～ https://github.com/antvis/g2
