### ISSUE TITLE
请问G2对三维图表的支持计划是怎样的？

### ISSUE THREAD

**Issue by tianlaixhh** [antvis/g2#420]
目前的G2能满足大多数二维图表的需求，且作为一种图形语言，可提供使用者自定义很多图表；但是目前还不支持三维图表，不知道对这块有没有计划？

**Comment by leungwensen** [comment]
就像我们在 SEE Conf 上宣布的那样，我们会等兄弟团队做的 3D 渲染引擎 R3 的稳定和开源，在 R3 ready 之后，3D 图表的支持会跟进，包括 3D 的统计图表、地图应用和大规模网络图等

**Comment by leungwensen** [comment]
PS：R3 会在 18 年开源

**Comment by RunningGrass** [comment]
@leungwensen  你好，请问现在R3的开源状态和g2对三维图表支持的进度和计划是什么样子的

**Comment by leungwensen** [comment]
@RunningGrass 有点遗憾，R3 的开源计划搁置了。。。目前 3D 图表方面，地图在如期推进，我们开源了 L7 库（ https://github.com/antvis/L7 ），其他统计图表、大规模网络图目前暂无进展。

**Comment by RunningGrass** [comment]
@leungwensen  好的。了解了，谢谢啦

**Comment by tolerance-go** [comment]
现在项目里 3d 用 echarts，其他用 g2，是什么，是信仰
