### ISSUE TITLE
多图表 mousemove 触发 tooltip 联动需求

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#421]
![image](https://user-images.githubusercontent.com/3838676/35265097-1c0bacd8-005a-11e8-8c6c-311ffe6cd9f0.png)

在左边的图表中移动，右侧的图表可以跟随左边图表一起出现 tooltip。

目前暂时没有暴露此类接口，实现起来非常麻烦。

**Comment by dxq613** [comment]
目前的 showTootip 是根据画布的像素点来计算的。对于 line,interval 之类的都是根据 x 坐标计算的，transpose 后按说应该可以按照 y 轴来显示。你调用一下chart.showTooltip(point) 试试

**Comment by weepy3641** [comment]
@dxq613  调用了没反应，而且一个 showTooltip 也不够用，还需要一个隐藏 tooltip 的接口。

**Comment by dxq613** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_hideTooltip

**Comment by weepy3641** [comment]
@dxq613  可以使用了，需要配合 chart.getXY() 用。
showTooltip(pos) 要求在 pos 所在的坐标下有 shape 才可以。
