### ISSUE TITLE
demo 不能正确展示

### ISSUE THREAD

**Issue by liu-minjie** [antvis/G2#4250]
##### Checklist

- [ ] `npm test` passes
- [ ] benchmarks are included
- [ ] commit message follows commit guidelines
- [ ] documents are updated

##### Description of change

https://g2.antv.vision/zh/examples/column/basic#custom-shape

这个demo不正确展示图

**Comment by hustcc** [comment]
已经修复，另外你打开的是 4.x 的官网，后面可以用这个[地址访问](https://g2-v4.antv.vision/zh/examples/column/basic#custom-shape)。
