### ISSUE TITLE
Is there any @types library for @antv/g2?

### ISSUE THREAD

**Issue by Somefive** [antvis/g2#426]
I am currently using typescript and looking around for types definition support for this brilliant library.
I was wondering if there is any declaration of it written by you smart guys or some third parties?

**Comment by leungwensen** [comment]
yep, this is it: https://github.com/antvis/g2/blob/master/src/index.d.ts

**Comment by Somefive** [comment]
Thanks!

**Comment by hustcc** [comment]
已经使用 typescript 开发了，默认在保重就有类型定义文件，lib 下。
