### ISSUE TITLE
facet分面图title无效

### ISSUE THREAD

**Issue by xbu** [antvis/g2#428]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

按照文档，facet分面图title是默认显示的，但点击运行后title没有显示，点击legend后才会显示title
https://antv.alipay.com/zh-cn/g2/3.x/demo/facet/rect.html

![image](https://user-images.githubusercontent.com/741724/35372515-62cbbb1e-01d5-11e8-8dd4-a7d1c8f07302.png)

**Comment by dxq613** [comment]
3.0.4 版本已经没有这个问题了。
