### ISSUE TITLE
能否提供图表的导出功能？

### ISSUE THREAD

**Issue by zachshelter** [antvis/g2#43]
其实导出功能还是很常用的一个功能。 

最好实例能够有一个API，以便获取图表的base64

非常感谢

**Comment by lfy55** [comment]
canvas本身就有导出的接口，应该能直接用`toDataURL`函数就能把canvas元素导出成base64吧，我尝试过可以的，但是一个图表有多个canvas元素的话还没有好的解决方法。

**Comment by dxq613** [comment]
图表确实是有三层，导出前，应该使用getImageData，drawImage把三层合成一层，再调用toDataURL

**Comment by dxq613** [comment]
2.2.0 已经增加 downloadImage接口，调用这个接口就会出现另存图片

**Comment by ZengZhenfei** [comment]
有没有直接获取到base64的功能？
