### ISSUE TITLE
柱状图或者条形图图例在右边时不显示

### ISSUE THREAD

**Issue by FightingJane** [antvis/g2#430]
* **G2 Version**:3.0.2-beta.1
* **Platform**:PC
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

官网的任意一柱图的例子，当图例在右边时均不显示，左上下正常

**Comment by leungwensen** [comment]
这是因为默认主题设置的 padding 没有给右边留足够的空间。你可以调一下 padding
