### ISSUE TITLE
图表的布局问题：不能灵活适应，经常超出画布

### ISSUE THREAD

**Issue by tianlaixhh** [antvis/g2#433]
我在使用G2创建t图表时，因为数据为动态获取，因此数据的条数和文本长度等是不可预知的，现在我将图例设置为垂直对齐（legend.layout='vertical'），会出现部分图例被遮盖的情况，如下图：
![default](https://user-images.githubusercontent.com/12244208/35429744-516f7870-02b0-11e8-98be-6c495ed91b27.jpg)
如果将图例放到右侧(position: right)直接被挡没了：
![default](https://user-images.githubusercontent.com/12244208/35430074-a8289d26-02b1-11e8-9508-5229a7094034.jpg)

类似场景下highcharts的效果供参考：
![2018-01-26 3 45 35](https://user-images.githubusercontent.com/12244208/35429745-51cd491e-02b0-11e8-95d1-f84eea3723b2.png)

如果全部使用offset来做的话是非常不灵活的，对于这种动态数据生成图表的需求很难设置。

希望G2的布局能够灵活适应，类似的布局问题还包括：多Y轴右侧被遮挡，各种加了标题的错位，文字长度超出被遮挡等，如：
![default](https://user-images.githubusercontent.com/12244208/35430835-f11a3bd6-02b4-11e8-96b1-471f714aa896.jpg)

望解决。

**Comment by kltsao** [comment]
同样的问题，求解决。

**Comment by leungwensen** [comment]
如果不想每个图表都配置 padding 之类的，可以指定 padding 为 auto

```js
const chart = new G2.Chart({
  padding: 'auto', 
  // ...
});
```
