### ISSUE TITLE
官方文档似乎有个笔误，关于 scale 的介绍

### ISSUE THREAD

**Issue by radicalviva** [antvis/g2#435]
![image](https://user-images.githubusercontent.com/15885774/35482075-b08d7dbe-046a-11e8-927d-14f885fbcd5b.png)
这边的示例代码应该是 `maxLimit` 吧？
想提交 `PR`，但是找不到源码的地方。。

**Comment by maplor** [comment]
官网的项目应该是这个  https://github.com/antvis/site

**Comment by leungwensen** [comment]
欢迎 PR

**Comment by leungwensen** [comment]
文档相关的 issue 可以提到 https://github.com/antvis/site/issues

**Comment by dxq613** [comment]
在 antv 的项目里面解决。
