### ISSUE TITLE
axis 的 title 有 position 和 offset 配置时， label 旋转了，且跟 title 重叠。

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#436]
https://antv.alipay.com/zh-cn/g2/3.x/demo/line/basic.html

在 如上 demo 中加入代码：

``` js
  chart.axis('value', {title:{
    offset:10,
    position:'end'
  }})
```

axis 的 title 和 label 之间的自适应布局导致的，效果不太好？

把label的autoRotate 关闭不会旋转。

**Comment by dxq613** [comment]
这个地方加个判定吧，如果旋转的角度 > 一定的角度就不旋转了
