### ISSUE TITLE
关于getContainerSize计算heightPadding的疑问

### ISSUE THREAD

**Issue by lxliang912** [antvis/G2#4360]
![image](https://user-images.githubusercontent.com/9337243/203888556-66091dca-4e37-4b16-98dd-211d91b3ff45.png)

在看v5的代码时，发现heightPadding的计算为什么不是 paddingBottom + paddingTop 值，按代码中的widthPadding和heightPadding没有区别？那这样的话padding设置不同值后，渲染是如何保证没有偏差的呢

另外，v5不支持webgl渲染配置吗？似乎没看到相关的入口

**Comment by pearmini** [comment]
webgl 的渲染方法文档还没有加，稍后加上。大概如下使用：

```js
import { Renderer } from '@antv/g-webgl';

const chart = new Chart({
  renderer: new Renderer()
})

// 声明可视化
// ...

chart.render()
```

**Comment by pepper-nice** [comment]
计算 `heightPadding` 的部分是 bug：
```js
const heightPadding = parseInt10(style.paddingTop) + parseInt10(style.paddingBottom);
```
如果你有参与 G2 共建的想法，可以提 PR 帮忙修改一下这个问题。

**Comment by hustcc** [comment]
@lxliang912 增加了 canvas、svg、webgl 的案例。PR 在这里 https://github.com/antvis/G2/pull/4361，今天会部署到官网上。
