### ISSUE TITLE
why pointStack() doesn`t work

### ISSUE THREAD

**Issue by vickmeng** [antvis/g2#437]
我把堆积柱状图改了个pointStack就挂了![image](https://user-images.githubusercontent.com/19486247/35497431-16f8f94e-0505-11e8-90aa-3d3e37ea81c9.png)
https://antv.alipay.com/zh-cn/g2/3.x/demo/bar/stacked-column.html

**Comment by dxq613** [comment]
没有提供默认的 pointStack，可以

```js
chart.point()
    .position('月份*月均降雨量')
    .color('name')
    .adjust('stack');
```

**Comment by vickmeng** [comment]
@dxq613 3ks very helpful，官网读起来有点误导呀。。。看起来就像是可以这么写的 （~‘—’）~

**Comment by dxq613** [comment]
其实是所有的都可以这样写， intervalStack 之类的都是简写，我正在加个 pointStack，今天应该就能提交，但是发布要等一下
