### ISSUE TITLE
V4文档无法打开一直在loading界面

### ISSUE THREAD

**Issue by PDieE** [antvis/G2#4371]
##### Checklist

- [ ] `npm test` passes
- [ ] benchmarks are included
- [ ] commit message follows commit guidelines
- [ ] documents are updated

##### Description of change

V4文档无法打开一直在loading界面
![image](https://user-images.githubusercontent.com/14084550/204482357-6ab2cdb3-36c6-41eb-b2c1-13e608dde399.png)

**Comment by hustcc** [comment]
v4 我们也部署到国内镜像吧，还需要持续维护。
