### ISSUE TITLE
G2 5.0 案例走查

### ISSUE THREAD

**Issue by visiky** [antvis/G2#4377]
案例走查在线地址：https://stackblitz.com/edit/g2-v5?file=src%2Findex.js

|对照组| 优化点 |
|---|---|
|<img width="804" alt="image" src="https://user-images.githubusercontent.com/15646325/204499000-6ae2446f-3d5e-4a40-add8-8d549fddb86f.png">|图例 marker 跟随 shape type|
|<img width="770" alt="image" src="https://user-images.githubusercontent.com/15646325/204498581-3b066c7b-0f97-4cd9-a134-6235364272db.png">| Badge 背景色跟随 color 映射，字体不跟随 color 映射 |
|<img width="798" alt="image" src="https://user-images.githubusercontent.com/15646325/204498779-c83de5e7-0a6c-4141-a6fc-7229d7e48bc8.png">| 优化 smooth path 绘制或增加 regionFilter annotation mark|

**Comment by hustcc** [comment]
第二个可能需要在讨论。另外两个放到 project 中了。
