### ISSUE TITLE
click line to repaint and mouse movement and click will result in errors

### ISSUE THREAD

**Issue by dengfuping** [antvis/g2#439]
![2018-01-29 15_27_11](https://user-images.githubusercontent.com/14918822/35498395-02a29492-0509-11e8-8abc-4ad7924aec43.gif)

Click line to repaint and mouse movement and click will result in errors. However, everything is all right if I listen the double click event.

**Comment by dxq613** [comment]
写一下你repaint 的方式，是changeData 还是怎么重绘的？

**Comment by j3r0lin** [comment]
遇到一样的问题，使用的Bizcharts，修改的Chart.data属性，内部应该用的changeData。cccd90b这次修改能够解决问题👍

**Comment by dengfuping** [comment]
@dxq613 是通过 `changeData` 进行重绘的。

**Comment by leungwensen** [comment]
已发布
