### ISSUE TITLE
line chart 的 event 交互無法明確取得 data element

### ISSUE THREAD

**Issue by Jazznight** [antvis/g2#44]
line 的 Geom 在 event的交互我遇到了以下問題：

1. plotclick事件是整個canvs的事件，如果data set有多個group/line，沒有明確點到data point會取不到data。

建議：因為多group的情境實際上每個event觸發點會有多個資料點(y)，那是否能只回傳x軸的值?

**Comment by dxq613** [comment]
是的，现在的情况确实是点、柱子、多边形返回的是具体的文本，如果是线、区域图的时候，返回的数据是线整体的数据，建议这时候通过另外一个计算tooltip的方法来获取当前的信息,如果有多条线的话也会显示多条数据值

```js
chart.getTooltipItems({x: ev.x, y: ev.y});
```

https://g2.alipay.com/api/#getTooltipItems

**Comment by Jazznight** [comment]
@dxq613 這招好!

g2真的很棒，期待每個新版!
