### ISSUE TITLE
new G2.Chart如何被父元素引用

### ISSUE THREAD

**Issue by tianhailong** [antvis/g2#440]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

`const chart = new G2.Chart({
        container: 'mountNode',
        forceFit: true,
        height: 480
    });`
我怎么才能在其他代码中引用这个对象呢，能否通过container等字段获取这个对象呢？改变父元素的长宽同步使图自适应。在父元素里无法直接获取new好的对象

**Comment by leungwensen** [comment]
G2 不会封装这么上层的 API。你这个场景有很多解法：

1. 用一个更全局的变量来缓存这样的 chart instance
2. 父元素变更之后，直接销毁这个对象重新画（譬如在 react 之类的场景）

**Comment by badbye** [comment]
在使用 viser 等这类二次封装的库里，如果没办法通过 container 获取对象，就比较难在父级做二次操作了。
缓存对象或者重新绘制这些解法，都很依赖于封装好的库有没有提供接口做这些事。

如果提供了这个接口，那不论使用怎样的封装库，总能通过原生的API获取到对象，再进一步操作。

**Comment by badbye** [comment]
> 在使用 viser 等这类二次封装的库里，如果没办法通过 container 获取对象，就比较难在父级做二次操作了。
> 缓存对象或者重新绘制这些解法，都很依赖于封装好的库有没有提供接口做这些事。
> 
> 如果提供了这个接口，那不论使用怎样的封装库，总能通过原生的API获取到对象，再进一步操作。

比如在使用viser 时， 要通过 https://github.com/antvis/g2/issues/132#issuecomment-364749277 这个思路去实现联动，就很无力。放弃 viser 从头搞也很费力。
