### ISSUE TITLE
facet using options api

### ISSUE THREAD

**Issue by timelyportfolio** [antvis/g2#441]
Thanks so much for this fantastic library.  Sorry for the English, and please let me know if this is better filed/asked somewhere else.

[codepen](https://codepen.io/timelyportfolio/pen/ddyKPL)

I am attempting to facet using the [options API](https://antv.alipay.com/zh-cn/g2/3.x/api/options.html#_%E9%85%8D%E7%BD%AE%E9%A1%B9%E5%B1%9E%E6%80%A7).  I do not get a chart, and I get no errors in console.  I read the source and inspected the `chart` and cannot determine what is happening.  The codepen tries to make two charts - one using the `.facet()` approach and the other with an object-like schema.

Thanks again.

**Comment by dxq613** [comment]
Sorry, because facet was originally a plugin for charts. So in the time of implementation, I did not consider the way options support. I will provide it in subsequent releases.

**Comment by timelyportfolio** [comment]
No problem at all, and I really appreciate the very fine work on `g2`.  For reference, I plan to build an `htmlwidget` wrapper for easy use in `R` and the options approach will be more straightforward.  See https://github.com/g2inr.
