### ISSUE TITLE
能问一下，在生成词云的时候，能不能根据一篇文章去生成词云

### ISSUE THREAD

**Issue by yangmeiz** [antvis/g2#442]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by leungwensen** [comment]
你需要的是一个能做分词（中文？英文？）并且能统计词频的工具，这个目前 DataSet 里没有内置提供。这是一个很大的领域，可用的工具也不少的，你可以搜索一下 `Segment` / `Text Corpus` 这样的关键字

**Comment by leungwensen** [comment]
我们后面做个 demo 出来吧。

**Comment by dxq613** [comment]
哈哈，这个就是个典型业务场景的解决方案了。
