### ISSUE TITLE
[5.x] Unknown Component: data.sort

### ISSUE THREAD

**Issue by Valar103769** [antvis/G2#4425]
```js
const renderChart = () => {
  const chart = new Chart({
    container: chartRef.value,
    autoFit: true,
  })
  const line1 = chart
    .line()
    .data({
      type: 'inline',
      value: response.data1,
      transform: [
        {
          type: 'filter',
          callback: (item) => {
            return item.hour.trim()
          },
        },
        {
          type: 'map',
          callback: (item: any) => ({
            ...item,
            x: dayjs(item.hour, 'YYYY-MM-DD HH').format('HH'),
          }),
        },
        {
          type: 'sort',
          callback: (a, b) => a.x - b.x,
        },
      ],
    })
    .encode('x', 'x')
    .encode('y', 'new_recharge_orders')
    .encode('shape', 'smooth')

```

Dose I should install these peerDependencies?
<img width="509" alt="image" src="https://user-images.githubusercontent.com/36926073/206424722-187c1978-f3b1-4fee-8dc6-8f5d5e3aa311.png">

**Comment by hustcc** [comment]
@xiaoiver 看看这个 peer 的问题。

@Valar103769 sort 当前还没有加，我今天加上，暂时可以使用 sortBy。

**Comment by xiaoiver** [comment]
可以提供安装运行环境么？

比如下面是在 stackblitz 上配合 vite 安装运行，不会出现类似问题：
https://stackblitz.com/edit/vitejs-vite-nnas74?file=package.json

**Comment by Valar103769** [comment]
> 可以麻烦提供具体的安装运行环境么（就是使用 pnpm 嘛）？
> 
> 比如下面是在 stackblitz 上配合 vite 安装运行，不会出现类似问题： https://stackblitz.com/edit/vitejs-vite-nnas74?file=package.json

pnpm + vite@3 

你的依赖
```js
   "@antv/g": "latest",
    "@antv/g-canvas": "latest",
    "@antv/g-svg": "latest",
    "@antv/g-webgl": "latest"
```

我的
```js
 "@antv/g2": "5.0.0-beta.3",

```

**Comment by xiaoiver** [comment]
npm + vite + @antv/g2：
https://stackblitz.com/edit/vitejs-vite-ysxcvz?file=package.json,src%2Fmain.ts

**Comment by Valar103769** [comment]
> npm + vite + @antv/g2 正常： https://stackblitz.com/edit/vitejs-vite-ysxcvz?file=package.json,src%2Fmain.ts
> 
> 的确是只有在 pnpm 下会报警告： [pnpm/pnpm#4183](https://github.com/pnpm/pnpm/issues/4183)
> 
> 我会在 G 里修改下 peerDependencies。

为什么pnpm会报错啊?

**Comment by xiaoiver** [comment]
原因就是 pnpm 对待 peerDependencies 比较严格。
感兴趣你可以看这一段：https://github.com/pnpm/pnpm/issues/4183#issuecomment-1008252214
> missing peer shows up but project works

**Comment by Valar103769** [comment]
这种依赖关系, 岂不是应该必须安装@antv/g-lite, 不然应该用不了吧?

**Comment by xiaoiver** [comment]
> 这种依赖关系, 岂不是应该必须安装@antv/g-lite, 不然应该用不了吧?

不会的，你可以看下 node_modules 下有个 `.pnpm` 文件夹，该有的依赖都不会少的。
