### ISSUE TITLE
ie 9适配问题

### ISSUE THREAD

**Issue by bingjianguo** [antvis/g2#444]
4. 如果是一个 BUG，请提供：复现步骤，错误日志以及相关配置，并尽量填写下面的模板中的条目。
* **G2 Version**: 3
* **Platform**: windows  ie9
* **Mini Showcase(like screenshots)**:  不支持自定义htmltemplate的legend
* **CodePen Link**:
https://riddle.alibaba-inc.com/riddles/b9a4ba

**Comment by simaQ** [comment]
基于 MR: https://github.com/antvis/g2/pull/448 的基础上， 不要使用 <table>，先用 <ul> 代替。
