### ISSUE TITLE
[v5] tooltip和point同时配置出现错误

### ISSUE THREAD

**Issue by lxliang912** [antvis/G2#4450]
![image](https://user-images.githubusercontent.com/9337243/207000499-84ef557e-f7f8-4793-94da-3010000f5cee.png)

- 同时开启interaction的tooltip和point，会出现截图的错误，没搞懂原因，有人知晓吗？
- tooltip目前发现只能在首次render前配置，render后再调用 chart.interaction({ type: 'tooltip'}) 不会生效（有重新render也不行），新版的特性吗？

**Comment by pearmini** [comment]
- 第一个问题是一个已知的 bug：会在这周修复，把 line 和 point 的声明顺序换一下试试？

```js
chart.line()
chart.point()
```
- 第二个问题是期望之中，只有在 `chart.render` 前声明可视化才能生效。

**Comment by lxliang912** [comment]
> * 第一个问题是一个已知的 bug：会在这周修复，把 line 和 point 的声明顺序换一下试试？
> 
> ```js
> chart.line()
> chart.point()
> ```
> 
> * 第二个问题是期望之中，只有在 `chart.render` 前声明可视化才能生效。
换顺序也是一样情况。

在v4版本中，许多方法在可以在render后执行，比如tooltip，scale，slider之类的配置，v5的设计都是在render前初始化配置才能生效吗？发现新版的改动蛮大的

**Comment by pearmini** [comment]
嗯嗯，内部架构发生了一些变化。目前 render 之前都是在声明可视化，内部会生成一个 JavaScript Object 描述图表，当调用 render 的时候才会去解析这个 JavaScript Object，然后渲染图表，所以 render 之后再声明可视化是不生效的，除非再调用一次 render（交互相关除外）。
