### ISSUE TITLE
V5 release timeline & guidance

### ISSUE THREAD

**Issue by cd-alexslater** [antvis/G2#4460]
We're going to be implementing G2 into our application, and I'm trying to make an informed decision about whether or not I should proceed with v5 or v4. I was wondering if there was anywhere I can find the following information:
- Release timeline / roadmap
- Feature differences between v4 and v5
- Breaking changes between v4 and v5
- Rough timeframe of when v5 will exit Beta

We want to use the latest version but are worried about using 'Beta' code in our production app. At the same time we would like to avoid writing all of our code based off the v4 and later having to rewrite it when we upgrade to v5. However, if the release of v5 is far enough in the future this isn't as much of an issue and we can just write it with a mind to a future migration. 

We're looking to begin our work within the next few months so any information would be greatly appreciated!

**Comment by hustcc** [comment]
@cd-alexslater Thanks for your issue.

We will release stable version at 2023-03-21, and the rough roadmap see [here](https://www.yuque.com/antv/g2-docs/dmir9gz9iq330zwq).

There are very large break changes in G2 5.0, which will lead to large costs of migration, but those break changes are very necessary.

We will write relevant introduction documents about features and differences in February 2023. Now you can see the [demo and example](https://g2.antv.antgroup.com/) from the website.

**Comment by pearmini** [comment]
There are two introductions can help you familiarize with features of G2 v5:

- https://observablehq.com/@antv/g2-introduction
- https://observablehq.com/@antv/g2-spec

**Comment by cd-alexslater** [comment]
Thank you for your help everyone - some really really useful information here, answered all my questions 👍
