### ISSUE TITLE
[v5] slider交互没反应

### ISSUE THREAD

**Issue by lxliang912** [antvis/G2#4467]
用的是这个 [例子](https://g2.antv.antgroup.com/zh/examples/general/interval/#bar-stacked)

- 发现slider操作后图表没反应，目前还未开发完吗，或者说这个版本的交互有其他变动？
![image](https://user-images.githubusercontent.com/9337243/207545196-0b57506f-5a50-43cd-9882-4077f5631859.png)

- 另外，调整窗口大小，slider的重新渲染有些问题，有时候x轴的slider甚至会消失
![image](https://user-images.githubusercontent.com/9337243/207545716-e2832431-f70c-4ead-bc99-ccc68c2b572e.png)

- 5.0.0-beta.4的包不支持slider调用吗？看了npm包源码是有这个方法，但是调用找不到这个方法（本地import使用，非上面的例子）

**Comment by pearmini** [comment]
目前 5.0.0-beta.4 不支持交互，应该会在12月26日发布的 beta 版本中支持。

**Comment by lxliang912** [comment]
> 目前 5.0.0-beta.4 不支持交互，应该会在12月26日发布的 beta 版本中支持。

好的，了解

**Comment by pearmini** [comment]
这个能力会推迟一周发布

**Comment by lxliang912** [comment]
> 这个能力会推迟一周发布

好的，了解
