### ISSUE TITLE
annotation.text 内的maxLength 意义不明

### ISSUE THREAD

**Issue by PDieE** [antvis/G2#4470]
如果将它看做是字数的话那么设置为1一定只会显示省略号
如果看做是字宽度的话，虽然在部分情况下能正常显示想要的几个字，但是，比如以下示例情况就很奇怪：
字号12的时候 maxLength=19 可以显示一个字 maxLength=36能显示三个字
https://codesandbox.io/s/24lxyi?file=/index.ts

**Comment by hustcc** [comment]
maxLength 是像素大小。

**Comment by PDieE** [comment]
原来如此
