### ISSUE TITLE
map-with-heatmap在3版本中没有对应的实现例子

### ISSUE THREAD

**Issue by LinFengYnu** [antvis/g2#449]
* **G2 Version**:3.0.4
* **Platform**:Windows

我在https://antvis.github.io/g2/demo/10-map/map-with-heatmap.html 看到了地图热力图的2.3版本实现，但是3版本没有对应的例子，因为文档说G2.Stat废弃了，应该使用DataView实现，能在3版本的图表示例里加一个这样的例子吗？

**Comment by dxq613** [comment]
移到 https://github.com/antvis/site/issues 里面处理。
