### ISSUE TITLE
next.js 使用 antv g2@5.0.0-beta.4 报错 Error [ERR_REQUIRE_ESM]

### ISSUE THREAD

**Issue by Jackeriss** [antvis/g2#4493]
next.js 使用 antv g2@5.0.0-beta.4 报错：
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /xxx/node_modules/.pnpm/d3-hierarchy@3.1.2/node_modules/d3-hierarchy/src/index.js from /xxx/node_modules/.pnpm/@antv+g2@5.0.0-beta.4/node_modules/@antv/g2/lib/mark/utils.js not supported.
Instead change the require of index.js in /xxx/node_modules/.pnpm/@antv+g2@5.0.0-beta.4/node_modules/@antv/g2/lib/mark/utils.js to a dynamic import() which is available in all CommonJS modules.
```
应该是d3-interpolate升级导致的。
相似问题：
https://github.com/FormidableLabs/victory/issues/1957

**Comment by visiky** [comment]
> ```json
> 1"
> ```

`d3-interpolate` 3.x 以下的貌似有漏洞，可以看下这个 PR：https://github.com/antvis/G/pull/1216

然后报错原因是因为 `d3-interpolate` 3.x 版本 export 的内容是：
```js
  "exports": {
    "umd": "./dist/d3-interpolate.min.js",
    "default": "./src/index.js"
  },
```
所以有两个解法：
1、设置 `'d3-interpolate': 'd3-interpolate/dist/d3-interpolate.min.js',`
2、将 `node_modules/d3-interpolate` 也编译处理为 es5 语法

**Comment by hengkx** [comment]
官方没有解决方法吗？

**Comment by timvalicenti** [comment]
Is anyone able to use antv with antd, react, and next.js? Getting a simple line chart throws all of these ES module d3-interpolate errors above. I don't think antv has been updated since July.

**Comment by hustcc** [comment]
关于 d3-interpolate 在 next 中的报错，也欢迎大家去 d3-interpolate 的 issue 中提交问题。这个问题需要他们官方去解决。
