### ISSUE TITLE
折线图无法点击

### ISSUE THREAD

**Issue by jackfengji** [antvis/g2#450]
折线图只能在点击point的时候有事件，line:click无效

https://codepen.io/anon/pen/gvpaJv

**Comment by CN-Sean** [comment]
点到point中心就无法触发事件，非常搞笑

**Comment by dxq613** [comment]
由于line 和 point 是两个图形，而 Point 又遮挡在上面，所以这时候点击只能触发 Point 的点击事件。你这种情况可以通过， plotclick 事件后，调用 chart.getSnapRecords 方法来获取邻近的数值。

```js
chart.on('plotclick', ev => {
  
  console.log(chart.getSnapRecords({x: ev.x, y: ev.y}))
});
```

https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_getSnapRecords
