### ISSUE TITLE
sample transform 实现问题

### ISSUE THREAD

**Issue by visiky** [antvis/G2#4505]
## 问题描述

在这个 case 中，想实现对 point 的抽样，发现 sample 之后，point 和 line 对应不上了

<img width="400" alt="image" src="https://user-images.githubusercontent.com/15646325/208904082-11ac9a5c-4de3-49bb-a6be-1e9810dddd6e.png">

- [CodeSandbox](https://codesandbox.io/s/line-point-lb3cxb?file=/index.html )

## 期望

```ts
.transform({
    type: 'sample',
    y: 'min',
})
```

group 之后取 y 值最小的点保留下来，x 坐标应该保持不变，效果如下：

|抽样前|抽样后|
|---|---|
|<img width="688" alt="image" src="https://user-images.githubusercontent.com/15646325/208903073-d5e0e90e-f8a1-4162-bb73-5ec2c7ec3141.png">|<img width="691" alt="image" src="https://user-images.githubusercontent.com/15646325/208903002-a3f950f5-78a5-4e84-b30d-cd57eebbb59b.png">|

**Comment by hustcc** [comment]
point 和 line 是使用了相同的 sample 吗？

**Comment by hustcc** [comment]
sample 还是建议放到 data.transform 中。具体见：https://github.com/antvis/G2/discussions/4393#discussioncomment-4500740

下周我来处理这个问题。
