### ISSUE TITLE
生成图表以后，页面如果最小化，或看其他页面，在打开时，图表就会消失

### ISSUE THREAD

**Issue by yangmeiz** [antvis/g2#451]
这是什么问题，我打开你们官网也发现了这个问题，就是官网的问题不明显。或是我可以把我写的项目网址给你们发过去，你们看看

**Comment by leungwensen** [comment]
能不能写个 codepen ？

**Comment by dxq613** [comment]
关掉 forceFit: true，设置固定的 width 试试，应该是图表窗口自适应大小导致的。
