### ISSUE TITLE
v5 beta 5: How to set the backgroundColor to transparent

### ISSUE THREAD

**Issue by sspilleman** [antvis/G2#4519]
Hi,

How can I set the Canvas to transparent? I'm using the dark theme, but currently it defaults to black, and I'm using a different color.

I already tried this: 
```javascript
chart.theme({ type: "dark",backgroundColor:"transparent" });
```
Thank you!

**Comment by visiky** [comment]
> Hi,
> 
> How can I set the Canvas to transparent? I'm using the dark theme, but currently it defaults to black, and I'm using a different color.
> 
> I already tried this:
> 
> ```js
> chart.theme({ type: "dark",backgroundColor:"transparent" });
> ```
> 
> Thank you!

Try as follow, we'll provide English documentations later. [Example](https://g2.antv.antgroup.com/examples/theme/theme/#layout-area)
```js
chart.theme({ type: 'dark', viewFill: 'transparent' });
```

**Comment by sspilleman** [comment]
Works great! Thanks a lot!
