### ISSUE TITLE
values of the scale not work as expect

### ISSUE THREAD

**Issue by orangeyyy** [antvis/g2#452]
I set a values props for the scale in the demo page, the label on the axis is affect but the line is dissapeared.
origin:
![image](https://user-images.githubusercontent.com/19667299/35664841-9cedda8c-075e-11e8-98d2-6938b13ab0c1.png)

after add the values:
![image](https://user-images.githubusercontent.com/19667299/35664871-c338f000-075e-11e8-8dab-0debd84588e5.png)

**Comment by dxq613** [comment]
你的原始数据里面是 "Jan", "Feb" 这种英文缩写，设置 values 跟这些值没法对应起来，那肯定是没法显示的。这里 values 的设置主要有两种作用：

*  可以设置数据在坐标轴上顺序
*  可以显示数据里面不存在的分类值

但是要求需要跟数据里面的文本保持一致，你这种情况更适合使用 formatter 函数。

**Comment by orangeyyy** [comment]
so what dose this example mean?
![image](https://user-images.githubusercontent.com/19667299/35774339-67b6ff88-09a7-11e8-96ed-f6ff23078436.png)
