### ISSUE TITLE
v5 beta 5: how to completely disable animation

### ISSUE THREAD

**Issue by sspilleman** [antvis/G2#4535]
Hi,

Is there a way to completely disable all animation? If not, I would like to enter this as an enhancement request 👍

Now I'm using:
```javascript
  .animate("enterDelay", 0)
  .animate("enterDuration", 0)
```
But I assume "some animation code" is still beging executed, potentially causing performance impact which I want to get rid of.

Thanks a lot,

Sander

**Comment by hustcc** [comment]
> .animate(false);
