### ISSUE TITLE
Bug - Broken auto fit container

### ISSUE THREAD

**Issue by cd-alexslater** [antvis/G2#4540]
Hey Everyone, 

Thought I'd mention this as the demo on the site is broken as well. 

When using autoFit: true in the new Chart() configuration, you get this:
<img width="447" alt="image" src="https://user-images.githubusercontent.com/114569661/209939011-1df8f820-57b9-4a77-9b77-593636ce53bd.png">

Steps to reproduce: 
1) Go to the 'Dual' demo in code sandbox:
https://codesandbox.io/s/q3t41i
2) Change the dependency version to the latest beta version (it's v5 code but the code sandbox is set to v4 for whatever reason)
3) Observe that nothing renders
4) Resize the window with the preview in code sandbox and it will reload, and you'll see the problem I pictured above.

**Comment by cd-alexslater** [comment]
Potentially related to https://github.com/antvis/G2/issues/4533 but I think that one relates to a broken UI after resize - in this case the chart fails to render (or does so improperly).

**Comment by pearmini** [comment]
I reproduce this problem, but you should specify the beta version of G2 explicitly as the latest tag is still point to v4.
 
```json
{
  "dependencies": {
    "@antv/g2": "5.0.0-beta.5"
  },
  "devDependencies": {
    "typescript": "latest"
  },
  "main": "index.ts"
}
```

**Comment by pearmini** [comment]
@pepper-nice https://codesandbox.io/s/vibrant-meninsky-t62zvc?file=/index.ts
