### ISSUE TITLE
交互Interaction不随.interval()数据更新而更新

### ISSUE THREAD

**Issue by zzh01028** [antvis/G2#4541]
function renderBarChart(container,data) { 
  const chart = new Chart({
    width: 880, // 图表高度
    height: 400, // 图表宽度
    container: container // 挂载容器的 ID
    // autoFit: true,
  });
  chart
    .line()
    .data(data) // 绑定数据
    .encode("x", "X") // 编码 x 通道
    .encode("y", "R"); // 编码 y 通道
  chart.interaction({ type: "tooltip" }); // 提示信息
  chart.render();
  return chart
}

 updateBarChart(newData) {
  let chart = this.chart;
  const interval = chart.getNodesByType('line')[0];
  // 模拟并且更新 Interval 的数据
  interval.data(newData); 
  // chart.interaction({ type: "tooltip" }); // 提示信息无论有无都无法刷新  
  
  chart.render();

}

**Comment by pearmini** [comment]
应该是刷新图表之后没有更新交互造成的，这 BUG 需要修复。下面是一些相关的 issue：

- https://github.com/antvis/G2/issues/4539
- https://github.com/antvis/G2/issues/4533
