### ISSUE TITLE
时间轴显示问题

### ISSUE THREAD

**Issue by Chemical-Romance** [antvis/g2#455]
如果x轴为时间戳，并且以“月”为刻度范围显示时，横轴会默认以30天做为时间间隔显示，如： 04-01, 05-01, 05-31, 06-30, 07-30, 08-28...  这种显示很不直观。应该智能处理为每月1号的节点。Highcharts 时间轴处理比友好。
![time issue](https://user-images.githubusercontent.com/20036355/35672105-6d598630-0778-11e8-8e77-efc5a79c2d5d.png)

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,height=device-height">
    <title>区间面积图</title>
    <style>::-webkit-scrollbar{display:none;}html,body{overflow:hidden;height:100%;}</style>
</head>
<body>
<div id="mountNode"></div>
<script>/*Fixing iframe window.innerHeight 0 issue in Safari*/document.body.clientHeight;</script>
<script src="https://gw.alipayobjects.com/os/antv/assets/g2/3.0.4/g2.min.js"></script>
<script src="https://gw.alipayobjects.com/os/antv/assets/data-set/0.8.5/data-set.min.js"></script>
<script>
  const data = [
    { time: 1490976000000, temperature: [ 14.3, 27.7 ] },
    { time: 1493568000000, temperature: [ 17.8, 25.7 ] },
    { time: 1496246400000, temperature: [ 14.5, 27.8 ] },
    { time: 1498838400000, temperature: [ 15.5, 29.6 ] },
    { time: 1501516800000, temperature: [ 16.7, 30.7 ] },
    { time: 1504195200000, temperature: [ 16.5, 25.0 ] }, ];

  const averages = [
    { time: 1490976000000, temperature: 21.5 },
    { time: 1493568000000, temperature: 21.3 },
    { time: 1496246400000, temperature: 22.1 },
    { time: 1498838400000, temperature: 23 },
    { time: 1501516800000, temperature: 23.8 },
    { time: 1504195200000, temperature: 21.4 },
  ];

  const chart = new G2.Chart({
    container: 'mountNode',
    forceFit: true,
    height: window.innerHeight
  });
  chart.scale({
    temperature: {
      sync: true
    },
    time: {
     // nice:true,
      type: 'time',
      mask: 'YYYY-MM-DD',
      //tickInterval: 24 * 3600 * 1000 * 30
    }
  });
  chart.tooltip({
    crosshairs: {
      type: 'line'
    }
  });
  const view1 = chart.view();
  view1.source(data);
  view1.area().position('time*temperature').tooltip(false);

  const view2 = chart.view();
  view2.source(averages);
  view2.axis(false);
  view2.line().position('time*temperature').size(2);
  view2.point().position('time*temperature').size(4).shape('circle').style({
    stroke: '#fff',
    lineWidth: 1,
    fillOpacity: 1
  });
  chart.render();
</script>
</body>
</html>

**Comment by dxq613** [comment]
我看了下时间坐标轴的计算这块的逻辑：
* 默认的 ticks 的个数是 6 
* 会根据 (endTime - startTime) / count 算出 interval ,然后判断 interval 是否大于 月如果大于 月，则按照月的倍数计算。

你提供的数据计算出来 interval: 27 天，这时候会根据你数据之中的最小间隔 30 作为 Interval 计算，所以就显示了这样的结果。

你如果增加一条10月份的数据计算的结果就不一样了。

```js
const averages = [
     { time: 1490976000000, temperature: 21.5 },
     { time: 1493568000000, temperature: 21.3 },
     { time: 1496246400000, temperature: 22.1 },
     { time: 1498838400000, temperature: 23 },
     { time: 1501516800000, temperature: 23.8 },
     { time: 1504195200000, temperature: 21.4 },
     { time: 1506787200000, temperature: 21.4 }, // 增加一条记录
  ];
```
![image](https://user-images.githubusercontent.com/1264678/35714505-fdfa9032-0807-11e8-8a28-73d2048da83d.png)

**Comment by Chemical-Romance** [comment]
数据有时候是没办法控制的，但是显示是强制要求的。所以如果计算出来 interval: 小于30天，又想显示成月，有没有什么配置强制显示呢？
另外我用同一组数据，在highcharts里，显示是正常的。是不是你们的算法也能优化一下？

**Comment by wangzhe1995** [comment]
我今天也遇到了这个问题
