### ISSUE TITLE
[v5] axis配置 labelTransforms: [{ type: 'hide' }] 出现x轴标签不显示

### ISSUE THREAD

**Issue by lxliang912** [antvis/G2#4555]
初始x轴标签渲染正常：
![image](https://user-images.githubusercontent.com/9337243/211230768-86b8eb03-76c2-41dd-bc26-015504d4abf3.png)

调整高度后标签不渲染：
![image](https://user-images.githubusercontent.com/9337243/211230836-32793c4e-fc89-4f12-bd76-716a737360cb.png)

调整宽度后标签也是不渲染：
![image](https://user-images.githubusercontent.com/9337243/211230887-86439b08-c637-4d95-bf2d-cd149e927d23.png)

**Comment by lxliang912** [comment]
如果保留两组数据，也会概率性出现标签不显示
![image](https://user-images.githubusercontent.com/9337243/211231196-8a396c57-85c7-438b-a4ac-059c481381b6.png)
![image](https://user-images.githubusercontent.com/9337243/211231222-fcdb8723-2b5b-46d5-a651-e92ac4fedb36.png)

**Comment by lxliang912** [comment]
另外，这个版本的clear方法要怎么用，貌似不能按v4的方式使用了（重新渲染不出来），没找到相关的使用介绍

**Comment by pearmini** [comment]
> 另外，这个版本的clear方法要怎么用，貌似不能按v4的方式使用了（重新渲染不出来），没找到相关的使用介绍

`chart.clear` 这个方法正在添加，这两周就可以用。@pepper-nice
