### ISSUE TITLE
legend 文字自定义后,溢出画布

### ISSUE THREAD

**Issue by kingmoumoumou** [antvis/g2#457]
![image](https://user-images.githubusercontent.com/8298993/35678444-646ae56c-078e-11e8-9d14-33e46c3ef157.png)

**Comment by kingmoumoumou** [comment]
const chart = new G2.Chart({
            container: 'payProportionChartInit',
            forceFit: true,
            height: 400
        });
        chart.source(dv, {
            num: {
                formatter: val => {
                    val = val.toFixed(2) + '%';
                    return val;
                }
            }
        });

**Comment by kingmoumoumou** [comment]
padding 设置 'atuo'后, 左边支付宝会显示不完整.
padding 设置 ['auto',10,'auto','auto'] 后,左右会被右边多出的10给挤不见一部分.

**Comment by dxq613** [comment]
padding 的 auto 仅自动适应坐标轴文本和图例，不会自动适应 label 的文本。上面的文本都是在 geometry(intervalStack) 上面定义的 label 文本，所以没有在 padding 的范围内。

**Comment by kingmoumoumou** [comment]
我应该如何处理溢出的那部分?

**Comment by dxq613** [comment]
除了下面的auto 外，其他的自己写一下宽度吧[xxx, 10,'auto',xxx]。后面看看是否也开放 图形和label 文本的自适应。

目前之所以只做了坐标轴和图例的自适应，是因为避免完全重绘两遍，如果图形和 label 也考虑自适应的话，整个图表得绘制一遍计算边距再重绘一遍了。
