### ISSUE TITLE
折线图的shape api里面有vh, hv等，但是文档里没有，文档的源文件在哪，如何pr啊？

### ISSUE THREAD

**Issue by galenjiang** [antvis/g2#458]
如题！

**Comment by maplor** [comment]
文档项目应该是这个吧，https://github.com/antvis/site  我看很多人都找不到。

**Comment by dxq613** [comment]
在这个文档里面修改：https://github.com/antvis/site/blob/master/site/zh-cn/g2/3.x/api/geom.md

欢迎提交 PR
