### ISSUE TITLE
Legend点击后,环形图会变化,鼠标移动到图后会报错 toAttrs' of undefined

### ISSUE THREAD

**Issue by kingmoumoumou** [antvis/g2#459]
![image](https://user-images.githubusercontent.com/8298993/35712481-2b565314-07fd-11e8-8bd3-df7b9a281d2b.png)

**Comment by kingmoumoumou** [comment]
我点击现金显示后,环形变化
![image](https://user-images.githubusercontent.com/8298993/35712557-8389758e-07fd-11e8-9b92-908ace28b311.png)
然后移动鼠标上去,就会出现undefined错误!

**Comment by leungwensen** [comment]
能给个 codepen 链接吗？

**Comment by kingmoumoumou** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/demo/pie/donut.html
这个是官网的列子,同样有这个问题!

**Comment by kingmoumoumou** [comment]
![image](https://user-images.githubusercontent.com/8298993/36705807-fcee3e7a-1ba1-11e8-9054-79b22f617397.png)

**Comment by dxq613** [comment]
已经修复

**Comment by mabelyong** [comment]
现在还要报错，点击图例的时候会触发，是还没有正式发布吗？如果G2修复了，viser是不是也同步修复了？
