### ISSUE TITLE
vue-cli 引入 g2 和 data-set 进行打包的时候报错 

### ISSUE THREAD

**Issue by dingyiming** [antvis/g2#460]
vue-cli 引入 g2 和 data-set 进行打包的时候报错 

![image](https://user-images.githubusercontent.com/12537013/35785786-26099246-0a5e-11e8-9788-75be1dffea85.png)

**Comment by evilucifero** [comment]
可以试一试g2的上层封装viser呢，支持vue的。

https://viserjs.github.io/

**Comment by dingyiming** [comment]
看了看，viser-vue 文档不如 g2 这边齐全，功能也不清楚，不想用viser，关键是团队已经引入了g2 做了功能

**Comment by leungwensen** [comment]
可能是因为 webpack 打包的时候用的是 G2 / DataSet 的源码，但 babel 的配置又忽略了 node_modules 文件夹，导致 G2 / DataSet 源码没有被编译。临时的解决方案有两种：

1. 引用的时候直接引用 dist 文件： `import DataSet from '@antv/data-set/build/data-set.js';`  `import DataSet from '@antv/g2/build/g2.js';`
2. 让 babel 编译 `node_modules/@antv/g2` 和 `node_modules/@antv/data-set` 文件夹
