### ISSUE TITLE
Circle Packing溢出问题

### ISSUE THREAD

**Issue by JeremyLyu** [antvis/g2#461]
我按照官方案例，从新配置了data. 然后就如下图所示，子元素的圆形超出了父元素的圆形。然后发生了画布溢出。
![wx20180205-123951](https://user-images.githubusercontent.com/8035331/35788660-afe121e2-0a71-11e8-82d7-d988c48d4406.png)

传入数据如下：
`data = {
                    "name": "flare",
                    "children": [
                        {
                            "name": "analytics",
                            "children": [
                                {
                                    "name": "软件工程",
                                    "value": 1200
                                },
                                {
                                    "name": "通信工程",
                                    "value": 1200
                                },
                                {
                                    "name": "计算机科学",
                                    "value": 1200
                                },
                                {
                                    "name": "网络安全",
                                    "value": 1200
                                },
                                {
                                    "name": "电子电路",
                                    "value": 1200
                                },
                                {
                                    "name": "视觉传达",
                                    "children": [
                                        {
                                            "name": "平面设计",
                                            "value": 3000
                                        },
                                        {
                                            "name": "UI设计",
                                            "value": 1000
                                        },
                                        {
                                            "name": "建筑设计",
                                            "value": 1000
                                        },
                                        {
                                            "name": "家装设计",
                                            "value": 1000
                                        }
                                    ]
                                }
                            ]
                        },
                    ]
                };`
不知道是否是使用的方式不对，或者由这方面的较为详细的文档可以阅读。

**Comment by lwl0812** [comment]
还没解决吗？

**Comment by dxq613** [comment]
这个地方不是 bug，而是 x,y 在 scale 计算中自动 nice 导致的，设置一下：

```js
chart.source(nodes, {
      x: {max:1},
      y: {max:1}
    });
```
![image](https://user-images.githubusercontent.com/1264678/60714055-d916ed00-9f4c-11e9-948c-f6bc4bbad202.png)

就好了。

**Comment by lwl0812** [comment]
> 这个地方不是 bug，而是 x,y 在 scale 计算中自动 nice 导致的，设置一下：
> 
> ```js
> chart.source(nodes, {
>       x: {max:1},
>       y: {max:1}
>     });
> ```
> 
> ![image](https://user-images.githubusercontent.com/1264678/60714055-d916ed00-9f4c-11e9-948c-f6bc4bbad202.png)
> 
> 就好了。

不好意思，我把数据改了下，发现渲染又有问题了，是不是和算法有关系？
数据如下：
const data = {
  name: 'circle-packing-demo',
  children: [
    {
      name: 'a',
      value: 0.2,
    },
    {
      name: 'b',
      value: 0.1,
    },
    {
      name: 'c',
      value: 0.3,
    }
  ]
};
替换下数据，就可以看到效果了。
https://antv.alipay.com/zh-cn/g2/3.x/demo/relation/circle-packing.html
