### ISSUE TITLE
Error reported in the new version

### ISSUE THREAD

**Issue by Whering** [antvis/G2#4622]
export 'Scale' (reexported as 'Scale') was not found in '@antv/scale' (possible exports: Band, Base, Constant, Continuous, DURATION_DAY, DURATION_HOUR, DURATION_MINUTE, DURATION_MONTH, DURATION_SECOND, DURATION_WEEK, DURATION_YEAR, Diverging, Identity, Linear, Log, Ordinal, Point, Pow, Quantile, Quantize, Sequential, Sqrt, Threshold, Time, createInterpolateColor, createInterpolateNumber, createInterpolateValue, d3Log, d3Ticks, d3Time, rPretty, wilkinsonExtended)

The terminal reported this error. Yesterday was still good. Could it be caused by today's update?

**Comment by pearmini** [comment]
What version of G2 are you using? V4 or V5？

**Comment by Whering** [comment]
> What version of G2 are you using? V4 or V5？

4.2.9

**Comment by pearmini** [comment]
Do use  G2Plot?  It has multiple versions of @antv/scale in the latest version. It now has been fixed by https://github.com/antvis/G2Plot/pull/3460

**Comment by manishteg** [comment]
export 'Scale' (reexported as 'Scale') was not found in '@antv/scale' (possible exports: Band, Base, Constant, Continuous, DURATION_DAY, DURATION_HOUR, DURATION_MINUTE, DURATION_MONTH, DURATION_SECOND, DURATION_WEEK, DURATION_YEAR, Diverging, Identity, Linear, Log, Ordinal, Point, Pow, Quantile, Quantize, Sequential, Sqrt, Threshold, Time, createInterpolateColor, createInterpolateNumber, createInterpolateValue, d3Log, d3Ticks, d3Time, rPretty, wilkinsonExtended)
getting this error
