### ISSUE TITLE
您好，能问一下，咱们G2有那个人物关系图的例子吗？如果没有的话，能出一个人物关系图的这种demo吗？

### ISSUE THREAD

**Issue by yangmeiz** [antvis/g2#464]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by leungwensen** [comment]
您好，目前 G2 不会专门做关系图的支持，它是“统计图表”领域的。会通过 DataSet 支持一些简单的关系图场景： https://antv.alipay.com/zh-cn/g2/3.x/demo/index.html#_%E5%85%B3%E7%B3%BB%E5%9B%BE

如果您想画的是复杂的关系图，可以尝试用我们专门做关系图可视化的库： https://antv.alipay.com/zh-cn/g6/1.x/index.html
