### ISSUE TITLE
基础面积图（有负值）是否可以提供不是0的基础点？

### ISSUE THREAD

**Issue by KaroseLiu** [antvis/g2#465]
请问有这种需求的实现吗，比如我的基点不是0

![ant](https://user-images.githubusercontent.com/8189801/35793067-12d0fcf0-0a8b-11e8-9e7b-fbade4b93fe4.png)

**Comment by leungwensen** [comment]
暂时不能。具体什么场景会用到这样的图？

**Comment by KaroseLiu** [comment]
没关系，我已经找到用另外一个图可以hack出来了。
这个场景其实很小众，就是用户的血压动态图，需要有两个基线，一个是高压135，一个是低压90的这两个基线
