### ISSUE TITLE
g2 4.xx 如何实现g2 5.xxbeta 的rangeX功能

### ISSUE THREAD

**Issue by tiehongji** [antvis/G2#4651]
##### Checklist

- [ ] `npm test` passes
- [ ] benchmarks are included
- [ ] commit message follows commit guidelines
- [ ] documents are updated

**Comment by tiehongji** [comment]
5.0下图例点击无效果且rangeX下使用tooltip异常

**Comment by hustcc** [comment]
@tiehongji G2 4.x 中没有 rangeX 的能力，只有 y 通道能够指定数组，相当于 rangeY。

> 5.0下图例点击无效果且rangeX下使用tooltip异常

针对 5.0 的 问题，@pearmini  跟进一下看看。

**Comment by pearmini** [comment]
> 5.0下图例点击无效果且rangeX下使用tooltip异常

图例点击无效，是因为目前需要显式设置图例相关的交互。

```js
chart.interaction({ type: 'legendFilter' });
```

rangeX tooltip 的异常具体是指？

**Comment by tiehongji** [comment]
@pearmini  tooltip显示空白，且鼠标跟随位置也有一定问题，item获取不到数据而去5.xx文档中item链接位http://localhost:8000/examples/interaction/interaction/#tooltip-custom

**Comment by pearmini** [comment]
@tiehongji 

- 链接问题已经在这个 PR：https://github.com/antvis/G2/pull/4647 里面修复了，正确的[链接](https://g2.antv.antgroup.com/examples/interaction/interaction/#tooltip-custom)是这个。
- rangeX 默认没有 tooltip 的信息，需要如下配置：

```js
chart.rangeX().encode('tooltip', fieldA).encode('tooltip', fieldB);
```
