### ISSUE TITLE
Symbo label not shown in darkmode

### ISSUE THREAD

**Issue by coader** [antvis/G2#4662]
![image](https://user-images.githubusercontent.com/3700498/219714229-263df65b-e3d3-49de-8330-d7e9dfd85043.png)

![image](https://user-images.githubusercontent.com/3700498/219714302-5d898ded-ef36-48d3-bb5c-c1d57f9960fc.png)

pleash see the topleft of image, the symbol of bar chart only show dot and label's color still be black

**Comment by pearmini** [comment]
这个问题已经修复了。
