### ISSUE TITLE
[v5] line transform groupX not works but it's ok in official example 

### ISSUE THREAD

**Issue by coader** [antvis/G2#4669]
![image](https://user-images.githubusercontent.com/3700498/220041830-940b128b-b713-41de-9b78-0435a82bac2d.png)

now I  use encode('series'...), is it the same effect?

**Comment by pearmini** [comment]
Can you give me a more complete example? 

Based on the information you provided, `GroupX` is for aggregating data rather than grouping data. **And aggregating is different from grouping**.  If you want to group lines for the line chart, you should specify `series` or `color ` channel  by `mark.encode(chanel, definition)`.

**Comment by coader** [comment]
I think I have made a mistake, but how can I  draw two lines in one chart?

**Comment by coader** [comment]
use .line() again to draw another line, I'll try it

**Comment by pearmini** [comment]
Here is an example.

```js
import { Chart } from '@antv/g2';

const chart = new Chart({
  container: 'container',
  autoFit: true,
  paddingLeft: 50,
});

chart
  .line()
  .data({
    type: 'fetch',
    value: 'https://assets.antv.antgroup.com/g2/indices.json',
  })
  .encode('x', (d) => new Date(d.Date))
  .encode('y', 'Close')
  .encode('color', 'Symbol') //  Color channel will group data by Symbol field, then draw one line for each group.
  .scale('y', { type: 'log' })
  .axis('y', { title: '↑ Change in price (%)' })
  .label({
    text: 'Symbol',
    selector: 'last',
    style: {
      fontSize: 10,
    },
  });

chart.render();

```

**Comment by pearmini** [comment]
> use .line() again to draw another line, I'll try it

This also works fine too, and it is useful if the two lines encode different data.

**Comment by pearmini** [comment]
Maybe there should be a more simple example to draw multiple lines in one chart on the example page.

**Comment by coader** [comment]
![image](https://user-images.githubusercontent.com/3700498/220050817-9d570a2d-29eb-4f45-82ef-7b4f8c84fbc0.png)

this is drawed by encode('color'...)
the series is shown, but the second line disappeared and show '02-16,02-17' in tooltips

**Comment by coader** [comment]
![image](https://user-images.githubusercontent.com/3700498/220051305-ec00abb7-b38e-4fe0-a2ed-7ce42d0ca1d2.png)
it's my data

**Comment by pearmini** [comment]
> ![image](https://user-images.githubusercontent.com/3700498/220051305-ec00abb7-b38e-4fe0-a2ed-7ce42d0ca1d2.png) it's my data

That's because there is only one datum for 02-17 in the "F" series, it can't draw a line with only one point. You can add more data with a date field equal to "02-17"  for the "F" series.

**Comment by coader** [comment]
but if missing data, the really x axis line can't be selected (02-19), so I have to fill those missing data by code?

![image](https://user-images.githubusercontent.com/3700498/220113019-8fdf3e83-977d-4593-8062-1b5e67f03482.png)

by the way, how to force axis tick only show integer number, and base from 0? 
![image](https://user-images.githubusercontent.com/3700498/220114082-5304a23c-0a68-4c3b-bae3-c3de7c086b87.png)
