### ISSUE TITLE
柱图x轴的数据类型为何只能为cat类型？

### ISSUE THREAD

**Issue by FightingJane** [antvis/g2#467]
* **G2 Version**:3.0.2-beta.1
* **Platform**:PC
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

柱图x轴的数据类型为何只能为cat类型?设置其他类型都报错
有一组时间戳是连续的，但是只能设置为timeCat类型，设置为time类型就报错
![image](https://user-images.githubusercontent.com/13446642/35844575-315687b2-0b49-11e8-975a-ff459955eb95.png)

**Comment by maplor** [comment]
柱状图的X轴只支持分类类型啊（cat、timeCat），这个图表特性决定的，连续型数据不应该用柱状图展示。
