### ISSUE TITLE
[v5] encode color by topN

### ISSUE THREAD

**Issue by coader** [antvis/G2#4674]
![image](https://user-images.githubusercontent.com/3700498/220115416-9da228ac-4f60-41f1-a3f0-7d1c1f8b9043.png)

it's not clear to show TopN, does encode color has callback function to do that?
encode('color',  ()=>....)

**Comment by pearmini** [comment]
Yes, make sure your data is sorted descending and then encode color as follows:

```js
import { Chart } from '@antv/g2';

const data = [
  { genre: 'Shooter', sold: 350 },
  { genre: 'Sports', sold: 275 },
  { genre: 'Other', sold: 150 },
  { genre: 'Action', sold: 120 },
  { genre: 'Strategy', sold: 115 },
];

const chart = new Chart({
  container: 'container',
});

const TOPN = 2;

chart
  .interval()
  .data(data)
  .encode('x', 'genre')
  .encode('y', 'sold')
  .encode('color', (_, index) => (index > TOPN - 1 ? 'low' : 'high'))
  .scale('color', {
    domain:['high', 'low'],
    range: ['red', 'blue'],
  });

chart.render();
```

Here is the output:

![image](https://user-images.githubusercontent.com/49330279/220118684-fdb45388-74cb-4a35-b03a-33e26d86e730.png)

**Comment by pearmini** [comment]
Do you use WeChat APP? Maybe we can use it to communicate more efficiently？

**Comment by coader** [comment]
already send mail to u

**Comment by pearmini** [comment]
> already send mail to u

OK, I've sent an invitation to you.
