### ISSUE TITLE
分组柱图X轴的数据为何不能为纯数字?

### ISSUE THREAD

**Issue by FightingJane** [antvis/g2#468]
* **G2 Version**:3.0.2-beta.1
* **Platform**:PC
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

分组柱图X轴的数据后台返回为纯数字，会报错，也是报类型错误：
![image](https://user-images.githubusercontent.com/13446642/35844683-a75bb8ba-0b49-11e8-8cfe-eefa033b968d.png)

不管是否设置为cat类型都一样

**Comment by leungwensen** [comment]
分组的 dodge 类型数据调整只能针对分类数据（字符串）
