### ISSUE TITLE
scale设置type为time显示异常

### ISSUE THREAD

**Issue by ShawshankLin** [antvis/g2#469]
设置const scale = [{
  dataKey: 'date',
  type: 'time',
  alias: '日期'
}
]的type为time后最后的日期显示不全，，，日期是字符串的
![image](https://user-images.githubusercontent.com/16248686/35846856-307e01a8-0b53-11e8-918a-d989574e0845.png)

**Comment by leungwensen** [comment]
设置一下图表的 padding，给绘图区域留够空间就好。 padding: 'auto'  可以支持大部分常用的场景
