### ISSUE TITLE
4.x 版本有自定义shape实现花瓣图或者饼图变形吗？谁能给出一个实例代码，谢谢！(3.x有但是不能移植到4.x)

### ISSUE THREAD

**Issue by soibhanZhangxb** [antvis/G2#4708]
4.x 版本有自定义shape实现花瓣图或者饼图变形吗？没有看到这样的示例，有几个都是 柱形图，和饼图差别感觉还是比较大。

3.x 里面有个花瓣图很漂亮，到时到了4.x 就无法运行了，而且示例也没有类似自定义。是能给出一个4.x版本的花瓣图啊？

**Comment by pearmini** [comment]
可以通过 4.x 的[自定义能力](https://g2-v4.antv.vision/zh/docs/api/advanced/register-shape)去实现一下？

**Comment by soibhanZhangxb** [comment]
> 可以通过 4.x 的[自定义能力](https://g2-v4.antv.vision/zh/docs/api/advanced/register-shape)去实现一下？

完全不会，因为里面示例都是条形相关，没有类似实例。能否给出示例啊，或者根据3.x里面的给予指点下，非常感谢！

**Comment by soibhanZhangxb** [comment]
> 可以通过 4.x 的[自定义能力](https://g2-v4.antv.vision/zh/docs/api/advanced/register-shape)去实现一下？

完全没有概念，示例都是矩形，没有饼图的自定义，是否能根据3.x给一个示例或者给些具体的提示也可以啊，非常感谢！

**Comment by pearmini** [comment]
其实思路也是一样的，你会拿到这个图形的控制点信息，默认应该是根据控制点画了一个扇形，现在需要画一个花瓣（这里面涉及到的计算可以参考 v3，然后渲染参考上面的例子）。

**Comment by pearmini** [comment]
- 链接：https://antv.antfin.com/zh-cn/g2/3.x/demo/pie/pie-platelets.html
