### ISSUE TITLE
图表的布局问题：图例位置调整导致互相遮盖

### ISSUE THREAD

**Issue by tianlaixhh** [antvis/g2#472]
如果图例位置不在默认的bottom位置，布局就会混乱，每次要通过各种padding、offset来修补，而业务中如果是动态数据，根本无法判断缩进的具体像素。
如下代码：
chart.legend({position: 'left' }); 
![2018-02-07 11 44 29](https://user-images.githubusercontent.com/12244208/35897571-d6252a06-0bfc-11e8-82d9-61acbb05f1dd.png)
如果chart设置了padding:'auto',图例直接进到图表内部，且底部X轴的文本都展示不全了
![2018-02-07 11 39 35](https://user-images.githubusercontent.com/12244208/35897592-ed304942-0bfc-11e8-8c37-a38c7e347d48.png)
望解答！

另外相关的问题，图例在左右时能否提供一个垂直居中的配置（就如同在bottom会默认水平居中一样）？期待回复！

**Comment by leungwensen** [comment]
legend、tooltip 这些是 component，padding auto 只是计算了主绘图区域（图形 + 坐标轴），没有考虑 component 的布局。目前只能手动设置 padding 来规避覆盖，因为具体的场景里 legend 和 坐标轴文本 都是不定的，这个不太好统一做。有个比较简单的方法：动态数据的话，你可以统计 legend 文本字符串的长度，以及 Y 轴最大数值的字符串长度，来决定图表的 padding

**Comment by rmabcft** [comment]
如果legend里面有隐藏的图例呢，图例有的并不显示，统计文本字符串的长度和y轴最大数值的字符串长度的方法好像也并不适用。

**Comment by dxq613** [comment]
padding: 'auto' 时左侧没有预留出足够多的空间确实是个问题，但是下部的文本被截断，是 antV demo 的高度设置的稍大，有一部分 canvas 被 iframe 遮盖住导致的。

**Comment by dxq613** [comment]
已经通过 padding: 'auto' 解决
