### ISSUE TITLE
5.x设置了supportsCSSTransform鼠标响应还是不正确

### ISSUE THREAD

**Issue by xiaochong44** [antvis/G2#4722]
##### Checklist

- [ ] `npm test` passes
- [ ] benchmarks are included
- [ ] commit message follows commit guidelines
- [ ] documents are updated

##### Description of change

5.x设置了supportsCSSTransform，父容器用css设置了transform:scale鼠标响应还是不正确

**Comment by pearmini** [comment]
可以给一个具体的代码片段和复现 demo 吗？

**Comment by xiaochong44** [comment]
@pearmini 我就在官网的例子上修改试的，我发现antv的几个产品升级到G5.x后都这样s2的next也是同样，会不会G5.x修改了什么

**Comment by xiaochong44** [comment]
@pearmini 我看源代码5.x没有了这个属性，4.x的还有这个属性，现在5.x有什么替代的解决方案吗

**Comment by xiaochong44** [comment]
supportCSSTransform这个属性，以前4.x的Chart有这个属性

**Comment by yyhdev** [comment]
我也碰到了这个问题，解决了吗

**Comment by hustcc** [comment]
具体是什么问题？

**Comment by yyhdev** [comment]
![image](https://github.com/user-attachments/assets/cc8795fe-cb8c-45c9-bf85-334382abb17a)
tooltip显示异常，外部容器设置了transform: translate(0px, 129.781px) scale(0.295573);
