### ISSUE TITLE
maginRatio is invaild

### ISSUE THREAD

**Issue by havywu** [antvis/g2#473]
![image](https://user-images.githubusercontent.com/29532857/35902645-f6047952-0c16-11e8-90ff-d3e64b322d63.png)

**Comment by leungwensen** [comment]
size 和 marginRatio 同时设置是不生效的。marginRatio 设置目前只对默认计算的宽度生效

**Comment by havywu** [comment]
@leungwensen 
那有没有什么办法可以同时设置柱宽和柱子之间的间距呢？

**Comment by leungwensen** [comment]
能同时设置百分比：

1. 所有分组柱子区域加起来占宽度的比例： `G2.Global.widthRatio.column = 0.75;`
2. 柱子之间的间距占柱子宽度的百分比： `marginRatio`

**Comment by havywu** [comment]
@leungwensen Ok，谢谢

**Comment by linlinNB** [comment]
@havywu 请问具体的写法是什么样子，我尝试了一下，好像没有生效。
