### ISSUE TITLE
size 能否支持设置最大宽度，及百分比配置。

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#474]
1、能否支持设置最大宽度，目前 g2 的布局规则，图表宽度固定时，数据量越少，柱子越宽，太宽了，柱状图不好看，但如果用户设置了固定 size，数据量一多又容易重叠，因此能否支持配置最大宽度，解决数据量少的时候，柱子太宽的问题。
2、size 能否配置为占比，分母为刻度间距。

https://github.com/alibaba/BizCharts/issues/148

**Comment by dxq613** [comment]
这个问题之前思索过，但是比较麻烦，不同的 geometry 的含义只有像素是统一的，对于度量是连续的百分比占比的含义不明确。
* 对于柱状图、多边形、schema 之类的间距的百分比可以计算出宽度
* point、 line、area 这个百分比的占比含义不明确
* 饼图下这个 size 又是什么含义

本来想着增加后缀的方式来实现 size 例如：
* 10 (直角坐标系下是像素、极坐标系下是角度）
* '50%' 间隔的占比
之类的进行这种占比的兼容，但是发现会增加很多概念和理解成本

目前想实现你的效果有两种方案：
* 1. 是实现 size 回调函数，根据图表的宽度和条数，自己计算宽度
* 2. 通过更改 G2.Global.widthRatio.column 的值，这个值默认是 1/2

**Comment by completeAutumn** [comment]
试了下两种实现方案，有一些问题
- 回调函数的方式实现，通过图表宽度-左右padding的合 / G2.Global.widthRatio.column / 柱子的数量是和不设置效果相同，但是adjust中设置的marginRatio也是百分比宽度设置间距，也就是说在分组柱状图中我设置了marginRatio为0的话，计算宽度大于以上公式的宽度柱子间则会有空白，小于则会重叠。

- 而直接修改G2.Global.widthRatio.column的值也不是很贴近要求，我也是想设置柱状图的最大宽度，方便在柱图数据量过小设置只有一根柱子的时候显示不是那么难看，而直接修改G2.Global.widthRatio.column在柱子较多或较少的出现两极分化的情况，太粗/太细。

如果能解决marginRatio这个问题第一个方案目前看来就完美了。

**Comment by dxq613** [comment]
延迟到新版本来解决这个问题。

**Comment by holyjunhui** [comment]
请问这个问题目前解决了吗

**Comment by dingdingtop** [comment]
请问有解决方案吗？

**Comment by simaQ** [comment]
会在 G2 4.0 支持

**Comment by liujunyang** [comment]
能介绍下”分组柱状图设置size回调之后，之前设置的柱间距就不起作用了“怎么解决吗？
直接看commit的代码也没有答案

**Comment by Max199909** [comment]
这个问题有解决方案吗？

**Comment by tywei90** [comment]
v4版本也没解决这个问题额

**Comment by Alisa0026** [comment]
> 会在 G2 4.0 支持

这个问题解决了嘛？

**Comment by jingjing20** [comment]
> 会在 G2 4.0 支持

嗨喽 这个问题最新版支持了吗？

**Comment by hustcc** [comment]
已经有 minColumnWidth，maxColumnWidth 可以做限制了。可以官网文档搜索一下。

**Comment by jingjing20** [comment]
> 已经有 minColumnWidth，maxColumnWidth 可以做限制了。可以官网文档搜索一下。

谢谢啦，还有一个问题请教一下你。分组条形图里面每条图形的宽度能配置吗？

**Comment by May-yfm** [comment]
> 已经有 minColumnWidth，maxColumnWidth 可以做限制了。可以官网文档搜索一下。

分组条形和分组柱状好像不适用呢，分组图形的宽度配置可以也解决一下吗？
