### ISSUE TITLE
x轴为cat, 影射的值为数值，显示不正常

### ISSUE THREAD

**Issue by galenjiang** [antvis/g2#475]
```
const  data =   [
    {type: '系列一', x: 1, y: 1},
    {type: '系列一', x: 2, y: 35},
    {type: '系列一', x: 3, y: 15},
    {type: '系列一', x: 4, y: 5},
    {type: '系列二', x: 1, y: 22},
    {type: '系列二', x: 2, y: 2},
    {type: '系列二', x: 3, y: 2},
    {type: '系列二', x: 4, y: 31},
    ]
 x: {
      type: 'cat',
 }
```
我猜可能是用了enum类型导致

**Comment by galenjiang** [comment]
![image](https://user-images.githubusercontent.com/12699258/35960325-3f28f982-0ce4-11e8-9a08-7bffc197243f.png)

**Comment by leungwensen** [comment]
画图之前加上这句试试。 `data.forEach(row => { row.x =  '' + row.x; })`

**Comment by galenjiang** [comment]
能否在判断cat类型是，自动转化下？

**Comment by leungwensen** [comment]
如果我们内部做转换，可能会引发新的问题的。“为啥我的数据被改了？”，所以还是让用户手动改比较好

**Comment by galenjiang** [comment]
@leungwensen 
但是现在这个问题是，数字导致的显示效果是bug的，用户就是想要数字作为category来显示出来，它最终应该是被toString过的。
另个问题我想问一下，哪一段代码会导致这样的渲染，我在源码里面没找到，能否指点一下。
