### ISSUE TITLE
柱图中当label的content值为负值时，显示在柱子的内部

### ISSUE THREAD

**Issue by FightingJane** [antvis/g2#476]
* **G2 Version**:3.0.2-beta.1
* **Platform**:PC
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

如图：
![image](https://user-images.githubusercontent.com/13446642/35961529-edcda5ce-0ce8-11e8-84f7-22aa6a230b51.png)

当label的content值为负值时，显示在柱子的内部。且当柱子很小的时候label就“离家出走“了
可以配置和正值的时候一样显示在柱子外部吗？
offset 只能设置正值，不支持设置负数

**Comment by dxq613** [comment]
offset 支持回调函数确实需要考虑。另外这块的逻辑确实没有思考数值正负的问题。

**Comment by dxq613** [comment]
已经修复
默认时：
![image](https://user-images.githubusercontent.com/1264678/65488989-cfae7880-dedc-11e9-883b-6f44460a0565.png)

transpose时：
![image](https://user-images.githubusercontent.com/1264678/65488919-a7267e80-dedc-11e9-9e4e-eb0c2c8f32b6.png)

y 是两个值时：
![image](https://user-images.githubusercontent.com/1264678/65488881-9249eb00-dedc-11e9-922a-701e47f577f5.png)
