### ISSUE TITLE
多线条 图例 反选 不一致

### ISSUE THREAD

**Issue by hzdjulytech** [antvis/g2#477]
* **G2 Version**:3.0.4
* **Platform**:
* **Mini Showcase(like screenshots)**:
 chart.line().position('x*y').color('gender');
![image](https://user-images.githubusercontent.com/36155555/35962474-86398ea6-0cec-11e8-8da3-6f5f6482d9ea.png)

* **CodePen Link**:

由于数据分类过多
![image](https://user-images.githubusercontent.com/36155555/35962553-d1935102-0cec-11e8-894a-289309e0a5f1.png)

 尝试加入反选 发现chart.filter 的行为和图例的行为不一致  剔除掉的数据对应的图例并没有变灰 
![image](https://user-images.githubusercontent.com/36155555/35963127-b6af3b2e-0cee-11e8-82c1-567d8395772d.png)
只显示第一根
![image](https://user-images.githubusercontent.com/36155555/35963148-c99b592a-0cee-11e8-9180-5b3c54c09cc8.png)
除第一根外全显示
![image](https://user-images.githubusercontent.com/36155555/35963228-12b6fa1a-0cef-11e8-9b17-bc8202a29d3d.png)
全显示
之后再点击图例 改变选中就会出错 （多发生在将图例点灰在点亮的时候），是我用错了还是咋回事
官方似乎没有提供批量改变的方法，希望提供一个全选 反选 批量选中 的方法 特定情况下会出现很多分类
![image](https://user-images.githubusercontent.com/36155555/35962882-f552ecb4-0ced-11e8-84eb-f1ad0c2ca954.png)

**Comment by maplor** [comment]
如果我没记错。。。图例配合filter可能会有逻辑问题，但是当时准备PR另一个问题就没有细看。

**Comment by dxq613** [comment]
这个新特性在 4.0 中提供吧！
