### ISSUE TITLE
English/Chinese Documentation Switching

### ISSUE THREAD

**Issue by tsaiDavid** [antvis/g2#478]
* **G2 Version**: N/A
* **Platform**: N/A
* **Mini Showcase(like screenshots)**: N/A
* **CodePen Link**: N/A

Hi, I'd love to get my team onboard with helping out with some translations, however - curious as to see what steps are required to get the ability to toggle between different languages like `ant-design` does for their documentation?

Additionally, are there plans to move documentation for `g2` into this repository, or will it be kept separate? How do we plan for keeping the code and documentation in sync?

**Comment by leungwensen** [comment]
Documentation for G2 will be kept in https://github.com/antvis/site, if we have any breaking change in APIs, we will keep it in sync. Functionality for switching between English/Chinese will be added soon.

Thanks again for your helping!

**Comment by tsaiDavid** [comment]
Sounds good, just wanted to ask. Will do!
