### ISSUE TITLE
f2官方文档无法打开

### ISSUE THREAD

**Issue by sky7131151** [antvis/G2#4782]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://f2.antv.vision/zh](https://f2.antv.vision/zh)

### Steps to reproduce
点击链接  无法访问  https://f2.antv.vision/zh

![image](https://user-images.githubusercontent.com/20431696/225873854-4e4a2c89-9457-4465-87b1-2b7a2d743ec8.png)

| Environment | Info |
|---|---|
| g2 | 4.2.10 |
| System | mac |
| Browser | google |

**Comment by hustcc** [comment]
f2.antv.antgroup.com
