### ISSUE TITLE
多次交互后出现内存泄漏问题，且动画丢失

### ISSUE THREAD

**Issue by Aarebecca** [antvis/G2#4796]
例：`peoplePointStacked`
动画丢失应该是卡顿导致的

<img width="873" alt="image" src="https://user-images.githubusercontent.com/25787943/226236824-91ad032d-c6f6-4507-a2b0-c021c7b8dbb6.png">

**Comment by xiaoiver** [comment]
OOM 已修复，升级到 `@antv/g@5.16.13` 后可重新验证：

下图为一个交互案例验证，多次交互后内存稳定，不会出现持续增长情况：

<img width="885" alt="截屏2023-04-03 下午1 30 05" src="https://user-images.githubusercontent.com/3608471/229419429-7687b553-0174-4be1-a53d-f4743a8e5a39.png">

**Comment by hustcc** [comment]
@Aarebecca 验证下，没问题就关闭 issue 吧~
