### ISSUE TITLE
柱图+多条线图的时候，线图会被覆盖

### ISSUE THREAD

**Issue by FightingJane** [antvis/g2#481]
* **G2 Version**:3.0.2-beta.1
* **Platform**:PC
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/13446642/36068880-5989227e-0f1a-11e8-8848-8a6b26aac26b.png)
如图，打开官网的柱图例子，然后在加两条线图，就出现图中的情况，第二条线图被覆盖了。

如果颜色很浅的，感觉都要看不见了。

请问怎么设置线图在最上层？

**Comment by FightingJane** [comment]
但是并不知道后台的返回顺序...

**Comment by leungwensen** [comment]
从贴图上看，似乎线图就是在饼图上方的，感觉被覆盖的原因只是用色的问题。综合一下：

1. 保证线图在最上层只能确保 `chart.line()` 最后声明，这个是语法和业务逻辑层面的
2. 不同的图（线和柱）如果要区分开来，尽量用对比度大的颜色或者透明度，这个可以通过 `.color()` 和 `.opacity()` 自行定义
