### ISSUE TITLE
[v5] 分页图例点击后面几页的图例，图例会自动跳转到第一页，并且消失

### ISSUE THREAD

**Issue by z-9527** [antvis/G2#4834]
[复现链接]：https://g2.antv.antgroup.com/examples/general/area#stacked-area
[复现步骤]：
1.点击图例第二页，随便点一个图例
![image](https://user-images.githubusercontent.com/32354710/227837578-fc5c339d-d826-4a29-becd-d6cbb36d7914.png)
2.点击过后的效果
![image](https://user-images.githubusercontent.com/32354710/227837687-926ccfad-f75e-4e30-a612-8932b12d867e.png)

**Comment by hustcc** [comment]
@Aarebecca 依然存在~~

**Comment by Deathsteps** [comment]
这个问题大概什么时候解决
