### ISSUE TITLE
分组柱状图设置marginRatio无效

### ISSUE THREAD

**Issue by FightingJane** [antvis/g2#484]
* **G2 Version**:3.0.2-beta.1
* **Platform**:PC
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

按照官网的例子改了下，这样设置marginRatio是无效的：
  chart.intervalDodge().position('月份*月均降雨量').color('name').adjust([{
    marginRatio: -0.1
 }]);
而这样设置就可以：
 chart.interval().position('月份*月均降雨量').color('name').adjust([{
    type: 'dodge',
    marginRatio: 1 / 32
  }]);
请问二者的区别在哪里？为甚第一种不可以？

**Comment by maplor** [comment]
因为是 intervalDodge 和 interval 的不同吧。

**Comment by leungwensen** [comment]
intervalDodge 等价于 interval().adjust(/* dodge 默认配置 */) ，是一个快捷方式，没法传配置参数。
