### ISSUE TITLE
annotation与slider 同时使用时，会出现超出显示区域情况

### ISSUE THREAD

**Issue by zhouchaoshunshun** [antvis/G2#4841]
[https://g2-v4.antv.vision/zh/examples/component/annotation#guide-region-filter1](url)

如图
<img width="908" alt="image" src="https://user-images.githubusercontent.com/129158904/228174208-bbc28f8b-74f5-44f1-a3aa-3bf73ccc9c68.png">

**Comment by hustcc** [comment]
感谢反馈，之前确实没有测试到这两个一起使用。

会显示的愿意还是因为做了标签的自动调整位置，建议你这边的处理办法是根据 slider 来过去 annotation 的内容。
