### ISSUE TITLE
legend marker 默认 shape 不符合

### ISSUE THREAD

**Issue by pearmini** [antvis/G2#4847]
测试案例在这：`__tests__/plots/static/score-by-item-area-radar.ts`

<img src="https://user-images.githubusercontent.com/49330279/228446110-0f213523-89ca-4507-9594-9beb987a4588.png" width=640 />

```ts
import { G2Spec } from '../../../src';
import { scoreByItem } from '../../data/score-by-item';

export function scoreByItemAreaRadar(): G2Spec {
  return {
    type: 'view',
    data: scoreByItem,
    coordinate: { type: 'polar' },
    axis: {
      x: { grid: true },
      y: { zIndex: 1, title: false, direction: 'center' },
    },
    scale: {
      x: { padding: 0.5, align: 0 },
      y: { tickCount: 5 },
    },
    legend: { color: { layout: { justifyContent: 'flex-start' } } },
    children: [
      {
        type: 'area',
        encode: { x: 'item', y: 'score', color: 'type' },
        style: { fillOpacity: 0.5 },
      },
      {
        type: 'line',
        encode: { x: 'item', y: 'score', color: 'type' },
        style: { lineWidth: 2 },
      },
    ],
  };
}
```

**Comment by pearmini** [comment]
4.0 中 area 的 default maker 是 square：https://g2-v4.antv.vision/zh/examples/area/stacked#stacked

<img src="https://user-images.githubusercontent.com/49330279/231348089-e482b9a4-9ad7-4ee6-bb69-e148319092d0.png" width=640 />

**Comment by hustcc** [comment]
![image](https://github.com/antvis/G2/assets/7856674/cafe5866-4963-4583-8769-96cfbf21e1ad)

这个问题已经修复了，但是 tooltip 中有类似的问题。

**Comment by pearmini** [comment]
> ![image](https://user-images.githubusercontent.com/7856674/237286509-cafe5866-4963-4583-8769-96cfbf21e1ad.png)
> 
> 这个问题已经修复了，但是 tooltip 中有类似的问题。

这个也许得调整 shape 接口：可以绑定 marker， 并且用 SVG path string 描述，这样 html 和 canvas 都可以使用。

**Comment by hustcc** [comment]
> 这个也许得调整 shape 接口：可以绑定 marker， 并且用 SVG path string 描述，这样 html 和 canvas 都可以使用。

至少得内置几种 marker，自定义都是很复杂的，无论是用 svg path string 还是 dom。

**Comment by hustcc** [comment]
related：https://github.com/antvis/G2/issues/4996 ，当前这个关闭了。
