### ISSUE TITLE
关于图表联动组件（g2-connect）的实现

### ISSUE THREAD

**Issue by maplor** [antvis/g2#485]
Hi all：
在 #132 中我们讨论了图表联动的部分实现细节，但是我认为如果要做一个真正的 `g2-connect` 组件需要大家参与进来讨论，所以将功能需求转移到该issue。

## 基本功能

- 链接多个图表，使相互之间同时触发/消失tooltip。
- 取消链接。

### 事件优化

上面的实现中使用二重循环绑定事件，逻辑很简单，但是事件个数是 (n^2-n)*2，而且取消链接也很麻烦。理想中应该只有两个回调函数 handlePlotmove和handlePlotleave，内部由事件中心统一处理逻辑，这样可以比较方便的通过 chart.off 取消链接。

### 链接组

这里引入一个“组”（group）的概念，参考自 [Echarts connect](http://echarts.baidu.com/api.html#echarts.connect) ，即链接在一起的图表组成一个“链接组”。引入这个概念是为了让链接的功能更灵活。例如页面上有6个图表实例，可能会分为多组链接，组之间没有链接关系。
但是增加一个概念实现逻辑相对也会复杂很多，暂时没有细想具体实现。

- 向已经链接好的组添加新图表。
- 从已经链接好的组移除某个图表。

### 配合拖拽缩放

如果一个图表使用 [g2-brush](https://github.com/antvis/g2-brush) 实现拖拽缩放，目前的链接方式就会出现问题。
mousemove事件中得到的回调参数是画布的xy坐标，chart.showTooltip 接受的参数也是画布xy坐标，如果两者没有缩放是ok的，但是其中一个缩放后，两边的画布坐标就无法对应了。

### 不同大小/类型图表的链接

目前的链接方式由于是 plotmove+showTooltip，所以如果两个图表的尺寸不一致 / 图表展现类型差别过大是无法有效联动的。

对于最后两点初步想法是 chart1.plotmove -> 获得xy坐标 -> chart1. getSnapRecords -> 传递数据集到新图表 -> chart2.getXY -> chart2.showTooltip。即以数据集为标准联动，理论上可以比较好的实现联动效果。

**Comment by winjeysong** [comment]
很赞！谢谢你的思路，让我实现了多图表联动

**Comment by maplor** [comment]
@winjeysong  其实我在公司内部实现了相关的插件，然而还没开源，所以就没放出来。不过思路都是一样的。

**Comment by 15531400827** [comment]
@maplor 请问一下现在有完整的组件可以实现联动了吗？我看官网上到现在还没做联动的例子

**Comment by 15531400827** [comment]
@maplor 又看到132里面贴的代码 那如果我用bizCharts要怎么做呢 像这样的例子：
https://codepen.io/15531400827/pen/pQWVyy

**Comment by dxq613** [comment]
先关闭，在新版本中实现。

**Comment by qgxcry** [comment]
多图联动有demo吗？
