### ISSUE TITLE
一个图可以有两个Tooltip吗？

### ISSUE THREAD

**Issue by luohaley** [antvis/G2#4859]
##### Checklist

- [ ] `npm test` passes
- [ ] benchmarks are included
- [ ] commit message follows commit guidelines
- [ ] documents are updated

**Comment by pearmini** [comment]
暂时不支持，v5 5月底会支持这个功能

**Comment by luohaley** [comment]
你好，v5没看见有基础面积图（有负值）的例子

**Comment by luohaley** [comment]
![image](https://github.com/antvis/G2/assets/104190152/d649c0b2-85b7-48a1-97d1-6ddde9260dd8)
像这个怎么加两个tooltip?

**Comment by pearmini** [comment]
> 暂时不支持，v5 5月底会支持这个功能

上诉需求可以通过分面实现，需要一个对称分面。

**Comment by pearmini** [comment]
@luohaley 我添加了一个例子：https://github.com/antvis/G2/pull/6318 ，你可以看看。
