### ISSUE TITLE
5.0的漏斗图无效

### ISSUE THREAD

**Issue by shield2018** [antvis/G2#4868]
https://g2.antv.antgroup.com/spec/mark/interval
文档关于interval的shape可以设定为funnel，但是无效。

看源码发现只有Funnel的坐标计算
https://github.com/antvis/G2/blob/d481921ad605672ee0f8b9f2ebde4dd0e5cb5bd9/src/shape/interval/color.ts#L40-L68
color.tx 中却使用了Rect 绘制。funnel类型绘制什么可以支持？

**Comment by pearmini** [comment]
嗯嗯，这里应该是一个 bug，color 没有消费 funnelPoints 这个参数，这里应该由 path 绘制才对。
