### ISSUE TITLE
vue3 里不显示 tooltip 且控制台有这个报错，大家有遇到过这个问题吗？

### ISSUE THREAD

**Issue by Wangtianq123** [antvis/G2#4878]
![image](https://user-images.githubusercontent.com/102778897/230573370-17a89586-6ec4-48dd-b72c-90b17b5f9644.png)

**Comment by Wangtianq123** [comment]
查阅说是vue3响应式声明chart 会有此现象，可是用了非响应式声明也不显示tooltip ，想问一下是和vue3不兼容的问题吗
![image](https://user-images.githubusercontent.com/102778897/230581426-ca2476cc-1d75-420a-b239-b9077c27aaeb.png)

**Comment by hustcc** [comment]
@Wangtianq123 可以来一个在线 demo 吗？看代码应该 4.x 版本？
