### ISSUE TITLE
Scale调整Opacity错误

### ISSUE THREAD

**Issue by xujingli** [antvis/G2#4883]
![image](https://user-images.githubusercontent.com/18068822/230869100-43db3c5b-7380-43ba-92e7-97d063f24fb6.png)

**Comment by pearmini** [comment]
如果希望 opacity 作为通道话，应该在 encode 里面指定。

```js
chart.options({
  type: 'interval',
  encode: {
    opacity: 'sold',
  },
  scale: {
    range: [0.1, 1] // 应该是一个线性比例尺
  },
})
```
