### ISSUE TITLE
自定义图例，点击图例不触发legend-item事件，非自定义图例可以触发

### ISSUE THREAD

**Issue by havywu** [antvis/g2#489]
![image](https://user-images.githubusercontent.com/29532857/36572767-898c8bd4-1878-11e8-8803-d6d6f1c783e5.png)

**Comment by dxq613** [comment]
自定义图例后可以直接使用 
```js
onClick: ev => {} 
```

回调函数来实现点击事件

**Comment by havywu** [comment]
@dxq613 用onClick回调点击事件时，点击图例，图形数据就不会被过滤掉了，本来只是想获取当前取消选中了哪些图例，现在还要自己写过滤事件。还有一个问题，是通过这个方法来过滤掉取消选中的图例吗？
