### ISSUE TITLE
data-set 被重复打包

### ISSUE THREAD

**Issue by shen-lan** [antvis/G2#4893]
![image](https://user-images.githubusercontent.com/21122615/232649237-eff0d99d-83ae-404c-9806-195acb28f192.png)

使用方法： 
```
import DataSet from '@antv/data-set'
```

**Comment by shen-lan** [comment]
```
import { DataSet } from '@antv/data-set'; 
```
也是一样重复 ，打包后有两个

**Comment by hustcc** [comment]
仅仅只是 import dataset 这个包，就出现两份吗？

**Comment by shen-lan** [comment]
@hustcc 
```
const chart = new DataSet.View().source(res.result)
```
代码里具体使用了

**Comment by hustcc** [comment]
@hustcc 可以来一个最小 demo 吗？看了 dataset 代码，不至于打两个包进去，可能的原因是业务代码中用到不同的库。

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/233982364-7da87718-73bf-4c50-a8f5-ac7fd4a0ef1a.png)

只是用一句，没有带来两个 data-set。@shen-lan

> import DataSet from '@antv/data-set';
