### ISSUE TITLE
G2 2.2.0 发布

### ISSUE THREAD

**Issue by simaQ** [antvis/g2#49]
G2 2.2.0,

『微小，但是美好的改变。』

# 一、丰富可视化交互形式

#### 选择: [图形的单选、多选](https://g2.alipay.com/tutorial/geom-select.html)以及[框选](https://g2.alipay.com/tutorial/rangeselect-event.html)；

![geom-select](https://zos.alipayobjects.com/rmsportal/drRAjaVYkpvOCICjOiwB.gif)

![geom-multiple](https://zos.alipayobjects.com/rmsportal/VpAHvfHhIbqhzAklYZjz.gif)

![range-select](https://zos.alipayobjects.com/rmsportal/DMDiRevwpVqDnGquxOyi.gif)

#### 筛选：[新添图例单选模式、连续图例筛选、混合图表图例筛选](https://g2.alipay.com/tutorial/legend-selectedmode.html)以及[数据范围选择条](https://g2.alipay.com/tutorial/plugin-slider.html)；

![legend-single](https://zos.alipayobjects.com/rmsportal/kIZbIDOUDMHlZxzPPlzh.gif)

![continous-legend](https://zos.alipayobjects.com/rmsportal/TFMrRhRcMaclRqqPrrnA.gif)

![multi-chart](https://zos.alipayobjects.com/rmsportal/IOIoagKRnknqUmAFitNU.gif)

![slider](https://zos.alipayobjects.com/rmsportal/YhtqkcZhqjgGNTaeYnLy.gif)

#### 高亮：支持图例鼠标 hover 高亮。

​![legend-hover](https://zos.alipayobjects.com/rmsportal/klfuOCzLgqkRznAuEGTg.gif)

# 二、丰富可视化表现形式

支持[弧长链接图](https://g2.alipay.com/demo/13-link/arcDiagram.html)、[和弦图](https://g2.alipay.com/demo/13-link/chordDiagram.html)以及[桑基图](https://g2.alipay.com/demo/13-link/sankey.html) 的绘制。

![QQ20161208-0](https://zos.alipayobjects.com/rmsportal/xVJoVYCYhkstBipyIwHl.png)
![QQ20161208-1](https://zos.alipayobjects.com/rmsportal/rhEGVagHaICszqApSMgS.png)
![QQ20161208-2](https://zos.alipayobjects.com/rmsportal/eRwsmzqfKmMtzvCdtTHC.png)
![QQ20161208-3](https://zos.alipayobjects.com/rmsportal/dbnHWGeHYPbOstlBuZPA.png)

详见 [更新日志](https://g2.alipay.com/download/changelog.html#2-2-0)。

# 说明： 2.2.0 版本完全向下兼容，请放心升级使用。

G2 为你而来
感谢所有关注和使用 G2 的朋友们！~

![g2-log](https://zos.alipayobjects.com/rmsportal/ahnAXGNFyRQTEcKBValk.png)

G2 官网： https://g2.alipay.com/

**Comment by winterJIE** [comment]
有源码开源的计划吗？

**Comment by dxq613** [comment]
计划 3.0 正式开源，本来的计划是 9月份，可能会延期一个月

**Comment by dxq613** [comment]
晴苑?

**Comment by leungwensen** [comment]
已经开源啦，欢迎使用～～ https://github.com/antvis/g2
