### ISSUE TITLE
期望在矩形树图中新增下钻功能

### ISSUE THREAD

**Issue by kuromi-yl** [antvis/G2#4902]
示例：https://echarts.apache.org/examples/zh/editor.html?c=treemap-drill-down

**Comment by pearmini** [comment]
嗯嗯，这个功能可以和 ：

- circlePack 
- 条形图

下钻功能一起考虑。同时5月份设计交互语法的时候也需要考虑。

**Comment by hustcc** [comment]
ref https://github.com/antvis/G2/issues/5055
