### ISSUE TITLE
如果给饼图或者环图设置一个初始角度，饼图或环图渲染有问题

### ISSUE THREAD

**Issue by rmabcft** [antvis/g2#491]
如图：设置startAngle=0时，这时总和还是100%，但是是扇形，不符合逻辑。highcharts就有自动补全的功能
chart.coord('theta',{startAngle:0});
![_20180224154933](https://user-images.githubusercontent.com/36733235/36627219-954e9112-197a-11e8-88c6-944fb00bae10.png)

**Comment by leungwensen** [comment]
需要自行指定 endAngle，保证 endAngle - startAngle == Math.PI * 2 就可以了。

**Comment by rmabcft** [comment]
` const { DataView } = DataSet;
  const data = [
    { value: 251, type: '大事例一', name: '子事例一' },
    { value: 1048, type: '大事例一', name: '子事例二' },
    { value: 610, type: '大事例二', name: '子事例三' },
    { value: 434, type: '大事例二', name: '子事例四' },
    { value: 335, type: '大事例三', name: '子事例五' },
    { value: 250, type: '大事例三', name: '子事例六' }
  ];
  const dv = new DataView();
  dv.source(data).transform({
    type: 'percent',
    field: 'value',
    dimension: 'type',
    as: 'percent'
  });
  const chart = new G2.Chart({
    container: 'mountNode',
    forceFit: true,
    height: window.innerHeight,
    padding: 0
  });
  chart.source(dv, {
    percent: {
      formatter: val => {
        val = (val * 100).toFixed(2) + '%';
        return val;
      }
    }
  });
  chart.coord('theta', {
    radius: 0.5,
    startAngle:0-90*Math.PI,
    endAngle:2*Math.PI-90*Math.PI,
  });
  chart.tooltip({
    showTitle: false,
    itemTpl: '<li><span style="background-color:{color};" class="g2-tooltip-marker"></span>{name}: {value}</li>'
  });
  chart.legend(false);
  chart.intervalStack()
    .position('percent')
    .color('type')
    .label('type', {
      offset: -10
    })
    .tooltip('name*percent', (item, percent) => {
      percent = (percent * 100).toFixed(2) + '%';
      return {
        name: item,
        value: percent
      };
    })
    .select(false)
    .style({
      lineWidth: 1,
      stroke: '#fff'
    });

  const outterView = chart.view();
  const dv1 = new DataView();
  dv1.source(data).transform({
    type: 'percent',
    field: 'value',
    dimension: 'name',
    as: 'percent'
  });
  outterView.source(dv1, {
    percent: {
      formatter: val => {
        val = (val * 100).toFixed(2) + '%';
        return val;
      }
    }
  });
  outterView.coord('theta', {
    innerRadius: 0.5 / 0.75,
    radius: 0.75,
    startAngle:0-90*Math.PI,
    endAngle:2*Math.PI-90*Math.PI,
  });
  outterView.intervalStack()
    .position('percent')
    .color('name', [ '#BAE7FF', '#7FC9FE', '#71E3E3', '#ABF5F5', '#8EE0A1', '#BAF5C4' ])
    .label('name')
    .tooltip('name*percent', (item, percent) => {
      percent = (percent * 100).toFixed(2) + '%';
      return {
        name: item,
        value: percent
      };
    })
    .select(false)
    .style({
      lineWidth: 1,
      stroke: '#fff'
    });

  chart.render();`
设置之后，饼图会变大？保证 endAngle - startAngle == Math.PI * 2 ，但是饼图大小发生了改变，此时改变的只是开始角度，结束角度。
