### ISSUE TITLE
G2的系列字段内容不能包含特殊字符，否则报错

### ISSUE THREAD

**Issue by tianlaixhh** [antvis/g2#493]
目前有个如下需求，系列为日期格式，会出现渲染异常，
以官网demo为例子，将city改为日期格式：
我不使用dataSet变换数据，直接静态数据，字符串中有下划线可以正常显示，如果有中划就会异常：
![default](https://user-images.githubusercontent.com/12244208/36649987-c7d27240-1adb-11e8-979d-571dd781a224.jpg)
![default](https://user-images.githubusercontent.com/12244208/36649990-c97fba6c-1adb-11e8-96ae-0b1d3c9efce1.jpg)
类似的，出现［/］[.] 等特殊字符都会异常。
测试数据：
let dataRows = [{"month": "Jan", "city": "2017-01-01", "temperature": 7}, {
        "month": "Jan",
        "city": "2018-01-01",
        "temperature": 3.9
    }, {"month": "Feb", "city": "2017-01-01", "temperature": 6.9}, {
        "month": "Feb",
        "city": "2018-01-01",
        "temperature": 4.2
    }, {"month": "Mar", "city": "2017-01-01", "temperature": 9.5}, {
        "month": "Mar",
        "city": "2018-01-01",
        "temperature": 5.7
    }]

实际场景如下：
使用G2（左边，已将［－］临时变更为［_］）和Highchart画出来分别是如下：
![2018-02-26 9 37 45](https://user-images.githubusercontent.com/12244208/36649581-43dfacb6-1ad9-11e8-8e11-6bf118cc8f9e.png)
存在几个个问题，一个是系列字段中划线导致异常，另外一个堆叠时顺序是反的，且无法设置（这个问题已经有人提了，但是目前还未解决，还有一个是负数的处理，hc默认转为正数，其实不准确，这也是我选用g2的原因），希望G2尽快解决上述问题，谢谢啦！

**Comment by leungwensen** [comment]
G2 目前计算 scale 回去匹配某个字段的字段类型，譬如你给的 `2018-02-18` 我们会认为它是一个 `日期字段`，如果改为 `2018_02_18` ，那我们会认为它是一个 `普通的分类字段`。这个情况可以手动设置 scale 类型：

```js
chart.scale('city', {
  type: 'cat'
});
```

堆叠顺序已经支持 reverseOrder，用最新的 `@antv/g2@3.0.5-beta.3`

**Comment by tianlaixhh** [comment]
那为什么日期类型就异常了的呢？日期不能作为系列属性吗？那么这样就是我要固定写死系列字段就是cat了

**Comment by leungwensen** [comment]
日期类型（time）内部处理的时候是按照连续数据处理的，所以你看到你用 `2018-02-18` 这个数据的时候，图里出现了一个 “连续图例过滤” 组件。日期类型有两种，你可以强制指定它用分类的方式处理：

`chart.scale('city', { type: 'timeCat' } )`

这样也可以。

原则上，是的，如果你想要有分类（多条线），想要有 “分类图例过滤” 组件，那字段类型也必须是分类字段。
