### ISSUE TITLE
slider缩略轴，初始位置在顶部，结束位置距离初始位置很近的时候， 文本描述覆盖。

### ISSUE THREAD

**Issue by controllerz** [antvis/G2#4931]
![image](https://user-images.githubusercontent.com/22693880/236098899-592fd6d3-d7f5-493c-bbfb-1ed5d3f49925.png)

没有可以单独判断是否展示的参数， 并且单独设置。
期待的结果是：
![image](https://user-images.githubusercontent.com/22693880/236099832-a75930f9-6960-411a-8c57-ab07dd6634dc.png)

**Comment by controllerz** [comment]
@pearmini 请问有解决方案吗？

**Comment by pearmini** [comment]
是希望在拖动过程中，可以隐藏藏和展示缩略轴的文本？

**Comment by controllerz** [comment]
是的， 默认现在是都展示， 所以就会出现距离接近的时候， 文本覆盖

**Comment by pearmini** [comment]
目前不支持这个能力，如果希望支持这个能力，一种办法就是增加 transform 属性，可以对 label 进行防止重叠处理：

```js
chart.slider('x', { transform: [ { type: 'autoHide' }] });
```

同时提供一些默认的防止重叠策略。

或者有啥更好的 API 设计思路吗？

**Comment by controllerz** [comment]
最好的就是自动隐藏。 或者是对文本描述加一些背景色， 做不透明处理。

**Comment by controllerz** [comment]
最好的就是自动隐藏。 或者是对文本描述加一些背景色， 做不透明处理。

**Comment by Aarebecca** [comment]
新增了 autoFitLabel 选项，将其置为 `false` 即可，同时需要保证两边留出足够的 padding 空间

**Comment by controllerz** [comment]
autoFitLabel 请问这个属性，现在发布了吗？在官网的例子里面测试，好想没有作用， 并且如何添加的文档也没有找到位置。
冒昧提一个建议， 文档可以像g2 plot 一样， 针对每一个组件， 或者公共块级别能力， 做具体文档阐述吗？antv 的组件很智能， 就是文档找起来，比较吃力。

**Comment by controllerz** [comment]
这个功能已经上线了吗？ 文档上没看到有autoFitLabel 这个体现
