### ISSUE TITLE
希望支持坐标轴交叉

### ISSUE THREAD

**Issue by tianlaixhh** [antvis/g2#494]
实际需求中有大量坐标轴交叉的场景，非常常用且有实际意义，如下图：
![2018-02-26 10 19 50](https://user-images.githubusercontent.com/12244208/36650881-b87e9a80-1ae0-11e8-8486-77babd2fe6df.png)
![2018-02-26 10 19 30](https://user-images.githubusercontent.com/12244208/36650883-b9d94ff6-1ae0-11e8-83a3-45529f9bc2ee.png)
![2018-02-26 10 19 00](https://user-images.githubusercontent.com/12244208/36650886-bb3237aa-1ae0-11e8-9243-befcdbc205b1.png)

望支持，谢谢！

**Comment by rmabcft** [comment]
是非常常用的场景,希望可以支持。谢谢。

**Comment by dxq613** [comment]
归并到 #404 中一起讨论，处理
