### ISSUE TITLE
【V5】showTooltip 不生效，如何通过事件控制 Tooltip 的显隐

### ISSUE THREAD

**Issue by Sallyfafafa** [antvis/G2#4950]
使用最新版的 g2，想通过事件控制 Tooltip 的显隐

复现代码如下：
https://codesandbox.io/s/mystifying-water-1i134l?file=/index.ts

**Comment by pearmini** [comment]
这个能力会在这两周支持

**Comment by Sallyfafafa** [comment]
> 
我把代码里面版本换成 "^4.2.8"，showTooltip 还是不生效，是怎么回事，能帮忙看下吗
https://codesandbox.io/s/mystifying-water-1i134l?file=/index.ts
