### ISSUE TITLE
v5性能问题

### ISSUE THREAD

**Issue by starrychan** [antvis/G2#4955]
版本：5.0.5

[demo地址](https://stackblitz.com/edit/js-tdbfhs?file=index.js)

现象描述：总共464条数据，渲染时间大概需要7s。

![企业微信截图_16835143924038](https://user-images.githubusercontent.com/11535980/236724277-6ff50722-239c-45a0-be33-ef13ab53b7e9.png)

![企业微信截图_16835144497032](https://user-images.githubusercontent.com/11535980/236724306-5abc749c-711a-4ded-b3a8-79d09a290cbc.png)

**Comment by pearmini** [comment]
简单看了一下，和图例以及坐标轴的关系比较大，把图例和坐标轴关闭之后，渲染时间就到比较偏正常的水平了。

```js
import { Chart } from '@antv/g2';

const chart = new Chart({
  container: 'container',
  theme: 'classic',
  autoFit: true,
});

chart.interaction('tooltip', {
  position: 'auto',
});

chart.options({
  type: 'interval',
  data: mockData,
  encode: {
    x: '地区',
    y: 'sale',
    color: '城市',
  },
  axis: false, // 关闭坐标轴
  legend: false, // 关闭图例
});

console.time('render');
const renderStart = new Date().getTime();
chart.render().then(() => {
  console.log('render complete', new Date().getTime() - renderStart);
  console.timeEnd('render');
});
```

**Comment by pearmini** [comment]
可以暂时先把图例关闭了，GUI 内部对于这种分页图例的渲染需要优化：懒计算和懒渲染，没有在首屏幕出现的图例是否还需要参与计算。

**Comment by hustcc** [comment]
ref https://github.com/antvis/G2/issues/4846
