### ISSUE TITLE
guide组件不跟随坐标系旋转

### ISSUE THREAD

**Issue by FightingJane** [antvis/g2#496]
* **G2 Version**:^3.0.2-beta.1
* **Platform**:PC
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

需要guide显示些辅助信息，添加如下代码：
![image](https://user-images.githubusercontent.com/13446642/36658899-856d4bfa-1b0d-11e8-84e1-21d34a2c03e9.png)
在默认坐标系下的柱状图显示正确，即显示在y轴的顶部位置：
![image](https://user-images.githubusercontent.com/13446642/36659090-3fa03d2a-1b0e-11e8-87d1-5886c153f973.png)
但是，当我变换坐标系时，guide的辅助信息并没有跟随坐标系走，还是显示在左上角。这里的文本的起始位置相对的点不是坐标系原点？旋转后效果如下：
![image](https://user-images.githubusercontent.com/13446642/36659465-875dd2b6-1b0f-11e8-9fc6-06f5b5476195.png)
而且，条形图也是这样：
![image](https://user-images.githubusercontent.com/13446642/36659655-209239ae-1b10-11e8-8d0d-79f60221edb5.png)
不是应该显示在箭头指向的地方才合乎常理吗？

**Comment by dxq613** [comment]
position 如果存在  '%'  时，不是以坐标系为基准的，而是以画布绘图区域为基准的，所以这个显示是正确的。如果你想跟着坐标系的旋转改变那么就直接使用数据表示位置

position: ['1951 年’, 150];
