### ISSUE TITLE
tickCount setting for time / timeCat scale is not working

### ISSUE THREAD

**Issue by leungwensen** [antvis/g2#499]
https://riddle.alibaba-inc.com/riddles/ac3b1273

**Comment by tianlaixhh** [comment]
Similarly, my 'ticks' cannot work, thanks!

**Comment by weepy3641** [comment]
@dxq613 
cat 类型的轴， tickCount  也有问题。
https://riddle.alibaba-inc.com/riddles/e2e9deec
这个 demo 中， x 轴是 cat，tickCount 配置几乎无效。
tickCount 配置为 10，显示 6 个刻度，配置为 6 显示 2 个刻度。

**Comment by dxq613** [comment]
timeCat 和 cat 都是用一个算法，我这两天改回来吧。 之前因为日期和分类没法被整除，被设计师喷的太厉害了，所以才向下取整找能够被整除的个数
