### ISSUE TITLE
保存为图片的功能？

### ISSUE THREAD

**Issue by NemoAlex** [antvis/g2#5]
像 Demo 中提供的功能，在右上角显示一个保存为图片的按钮。
目前是否提供这个功能？还是需要自己实现？

**Comment by dxq613** [comment]
这个功能不是G2本身的功能，是在页面上实现的。这种功能，搜索一下，一大堆实现方案

**Comment by NemoAlex** [comment]
这是一个很好的功能，建议考虑加入。

**Comment by XiaodiKong** [comment]
我用Nodejs发邮件，希望可以有图片保存功能，是否有实现方案？

**Comment by dxq613** [comment]
nodejs端可以使用 phantomjs 自动截屏。
