### ISSUE TITLE
图表类型排序不固定的问题求助

### ISSUE THREAD

**Issue by junmaqiang** [antvis/g2#50]
![01](https://cloud.githubusercontent.com/assets/1819457/21035644/85195790-bdfb-11e6-9177-74f87a1000fb.png)

![02](https://cloud.githubusercontent.com/assets/1819457/21035647/8e33bd34-bdfb-11e6-8bbd-4f43a380d0b1.png)

**Comment by junmaqiang** [comment]
<img width="953" alt="03" src="https://cloud.githubusercontent.com/assets/1819457/21035706/e8509bf2-bdfb-11e6-8454-800153351021.png">

**Comment by dxq613** [comment]
分类字段的顺序由在数据中的顺序决定的，如果希望固定顺序可以在列定义里面指定顺序：

```js
chart.source(frame, {
  type: {
    value: ['息前手数',xxxx,xxxx]
  }
});
```

**Comment by junmaqiang** [comment]
设置了无效，很奇怪

**Comment by simaQ** [comment]
你好，可以参考下 api: https://antv.alipay.com/g2/api/scale.html#cat
