### ISSUE TITLE
设置坐标系旋转时，Label组件不跟随旋转，只是文本旋转？希望支持Label组件跟着Coord旋转

### ISSUE THREAD

**Issue by rmabcft** [antvis/g2#500]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,height=device-height">
    <title>基础环图</title>
    <style>::-webkit-scrollbar{display:none;}html,body{overflow:hidden;height:100%;}</style>
</head>
<body>
<div id="mountNode"></div>
<script>/*Fixing iframe window.innerHeight 0 issue in Safari*/document.body.clientHeight;</script>
<script src="https://gw.alipayobjects.com/os/antv/assets/g2/3.0.4/g2.min.js"></script>
<script src="https://gw.alipayobjects.com/os/antv/assets/data-set/0.8.5/data-set.min.js"></script>
<script>
  const { DataView } = DataSet;
  const data = [
    { item: '事例一', count: 40 },
    { item: '事例二', count: 21 },
    { item: '事例三', count: 17 },
    { item: '事例四', count: 13 },
    { item: '事例五', count: 9 }
  ];
  const dv = new DataView();
  dv.source(data).transform({
    type: 'percent',
    field: 'count',
    dimension: 'item',
    as: 'percent'
  });
  const chart = new G2.Chart({
    container: 'mountNode',
    forceFit: true,
    height: window.innerHeight,
  });
  chart.source(dv, {
    percent: {
      formatter: val => {
        val = (val * 100) + '%';
        return val;
      }
    }
  });
  chart.coord('theta', {
    radius: 0.75,
    innerRadius: 0.6
  }).rotate(80);
  chart.tooltip({
    showTitle: false,
    itemTpl: '<li><span style="background-color:{color};" class="g2-tooltip-marker"></span>{name}: {value}</li>'
  });
  // 辅助文本
  chart.guide().html({
    position: [ '50%', '50%' ],
    html: '<div style="color:#8c8c8c;font-size: 14px;text-align: center;width: 10em;">主机<br><span style="color:#8c8c8c;font-size:20px">200</span>台</div>',
    alignX: 'middle',
    alignY: 'middle'
  });
  chart.intervalStack()
    .position('percent')
    .color('item')
    .label('percent', {
      formatter: (val, item) => {
        return item.point.item + ': ' + val;
      }
    })
    .tooltip('item*percent', (item, percent) => {
      percent = percent * 100 + '%';
      return {
        name: item,
        value: percent
      };
    })
    .style({
      lineWidth: 1,
      stroke: '#fff'
    });
  chart.render();
</script>
</body>
</html>

这种场景还是很常用的，希望可以支持

**Comment by dxq613** [comment]
可以先使用 startAngle 和 endAngle，等修复这个 bug 后再切换过去。

**Comment by rmabcft** [comment]
这个问题修复了吗？大概需要多久修复呢?用startAngle和endAngle在一些场景中也是有问题的。如图，里面俩层旋转的角度是不一样的，外面的饼旋转207-90度，里面的饼旋转209-90度。考虑分离度的时候就会有问题了。



![_20180301155738](https://user-images.githubusercontent.com/36733235/36834972-9a4d49da-1d6f-11e8-911d-6f34062e8e41.png)

**Comment by dxq613** [comment]
已经修复
