### ISSUE TITLE
折线point显隐时的bug

### ISSUE THREAD

**Issue by xujingli** [antvis/G2#5006]
如图，当前有三个children：line point interval，且三个animate设为false
![image](https://github.com/antvis/G2/assets/18068822/31426fc5-ce34-42bb-8343-807805ab1d3e)

当关闭point时，如图所示，有两个children: line interval，
所以有两个问题：
1. 为什么point没被关闭？
2. 为什么柱状图被隐藏了？
![image](https://github.com/antvis/G2/assets/18068822/763e6a3a-5c2c-4f1a-8a0a-6927dc4756e1)

animate设为true时，没有这样的问题

**Comment by pearmini** [comment]
这里应该是没有动画的时候，不同图形之间的更新有点问题。
