### ISSUE TITLE
数据为time类型时，负值的时间戳处理有问题

### ISSUE THREAD

**Issue by tianlaixhh** [antvis/g2#501]
当X轴数据为时间类型且为负值时，在formatter的回调中取得的text与原值有差异，
例如  data = [
                {
                    "y":5.1132164,
                    "x":-2209104000000
                },
                {
                    "y":5.219866,
                    "x":-2209100400000
                },
                {
                    "y":5.8201857,
                    "x":-2209096800000
                },
                {
                    "y":5.6507177,
                    "x":-2209093200000
                }]

x 为x轴，y为y轴，则
formatter(text){
// 此时拿到的text失真，如-2209104000000变成了-1861948800000
}
为排除mask的问题，已经将mask设置为 'YYYY-MM-DD hh:mm:ss'（设置前后无差异）
我的需求就是希望通过formatter进行格式转换，希望得到最原始的时间戳。
望解决。

**Comment by dxq613** [comment]
时间坐标轴的计算会自己计算间距，所以不会按照你输入的数据而输出坐标轴，如果想保持一致的话，在列定义里面将数据类型设置成 timeCat jike

```js
chart.source(data, {
  time: {type: 'timeCat'}
});
```

**Comment by tianlaixhh** [comment]
设置了timeCat也不对啊，精度就是有问题，而且用bizCharts的画还会报错Invalid Time： -2209104000000

**Comment by tianlaixhh** [comment]
如-2209104000000变成了-1861948800000，相差也太多了
