### ISSUE TITLE
数据精度有问题

### ISSUE THREAD

**Issue by tianlaixhh** [antvis/g2#503]
x轴数据为linear时，如-2209068000000实际变成了-2209060000000
time类型同样存在问题，参考issue  #501

**Comment by dxq613** [comment]
看起来像是坐标点计算的时候会进行刻度计算，不会直接把传入的数据作为坐标点。请给出原始的数据，我再确定问题。

**Comment by tianlaixhh** [comment]
参考  #501 的数据，就是因为设置为time有问题，改为linear也有问题，且数据没有越界。

**Comment by dxq613** [comment]
我试了下这个不是问题，因为坐标点计算的时候会整体考虑，会自动计算出间隔，然后根据间隔设置坐标点，所以你数据里面的 -2209068000000 不一定会显示。

![image](https://user-images.githubusercontent.com/1264678/37321249-8e6f89d8-26b2-11e8-88ce-21254d87ea64.png)

如果你想显示你数据中的坐标点，那么你可以自己设置 ticks
