### ISSUE TITLE
极坐标系自动调整大小

### ISSUE THREAD

**Issue by pearmini** [antvis/G2#5048]
- 问题：仪表盘没有充满图表
- 出现原因：非完整的几坐标系没有调整大小
- 实现思路：对于 polar 等 radial 坐标系，transform 里面计算角度，然后增加一个 scale 变换。
- 版本：5.0.7

<img src="https://github.com/antvis/G2/assets/49330279/93e7400b-5eb0-4c0e-baec-bcd04c72811d" width=640 />

```ts
export function gaugeCustomColor(): G2Spec {
  return {
    type: 'gauge',
    data: {
      value: {
        target: 120,
        total: 400,
        name: 'score',
        thresholds: [100, 200, 400],
      },
    },
    scale: {
      color: {
        range: ['#F4664A', '#FAAD14', 'green'],
      },
    },
  };
}
```

**Comment by hustcc** [comment]
![image](https://github.com/antvis/G2/assets/7856674/71de389d-5901-4e1d-8797-948b887cd458)
![image](https://github.com/antvis/G2/assets/7856674/53aa5e88-61bd-4c35-883e-0d96b463e2b4)
![image](https://github.com/antvis/G2/assets/7856674/8988ea4b-73b4-4176-9cb5-f741ab9544ae)
![image](https://github.com/antvis/G2/assets/7856674/3bb2bc5f-e7dc-45df-9e6e-b054369994a7)
![image](https://github.com/antvis/G2/assets/7856674/20be41e4-1192-4e6a-8b1b-26385ae45fb3)
![image](https://github.com/antvis/G2/assets/7856674/924d44ba-acb5-4575-9949-cc1278928787)

**Comment by pearmini** [comment]
相同问题：https://github.com/antvis/G2/issues/6118

**Comment by hustcc** [comment]
@pearmini 这个问题之前做了一半，coordinate 的 revert 没有办法处理，看看是否能解决。

**Comment by pearmini** [comment]
@hustcc 好
