### ISSUE TITLE
堆积条形图dataLlabel各种设置及优化问题

### ISSUE THREAD

**Issue by FightingJane** [antvis/g2#505]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/13446642/36835119-257aef9e-1d70-11e8-8dba-45210b1cd875.png)
1、如图，当第二个柱子很短时，两个柱子的label会重合，看不清数字，望优化

2、可否设置dataLlabel 默认显示在柱子的中间？因为并不知道柱子的长度offset 不能统一设置

3、可否支持dataLlabel 设置在柱子内部的上中下不同位置呢？

4、因修改字体颜色等需要使用htmlTemplate，但是当文本里面包含汉字时会垂直显示！！！
     给div加个宽度可以不垂直了，但是又会往柱子里面挤

下图为不加宽度的label样式:
![image](https://user-images.githubusercontent.com/13446642/36837494-8667f5fc-1d77-11e8-9397-f84ed87803c6.png)

下图为加了宽度的label样式：
![image](https://user-images.githubusercontent.com/13446642/36837562-b0e0627e-1d77-11e8-883e-1d7ccbe26068.png)

**Comment by dxq613** [comment]
这个在 label 模块重构时，支持动态 offset 来解决，也会增加 “防止文本覆盖”的逻辑

**Comment by rmabcft** [comment]
这个问题会不会在四月份的3.1版本中解决？

**Comment by leungwensen** [comment]
@rmabcft label 重构暂时没有列入 3.1 迭代计划，估计要六月份左右

**Comment by elaine1234** [comment]
已在3.4版本中添加动态label
