### ISSUE TITLE
交互补全

### ISSUE THREAD

**Issue by pearmini** [antvis/G2#5055]
# 补全交互

补全 4.0 相关的交互，一些交互的 bug 和图表相关的交互。

## 基础交互

- [x] elementHighlight: 地图的 bug
- [x] legendHighlight: 离散的部分有问题
- [x] legendHighlight: 连续
- [x] legendFilter: 连续
- [x] scrollbar
- [ ] drag
- [ ] zoom
- [x] tooltip marker 和 missing 的问题

## 图表交互

- [x] pack：下钻
- [ ] tree：收起和隐藏。
- [ ] treemap：下钻
- [ ] forceGraph：拖拽。

**Comment by Miantang** [comment]
这里的 “treemap：下钻”

是通过emit方法触发下钻行为吗，不知道是否什么时候能够支持？

**Comment by pearmini** [comment]
> 是通过emit方法触发下钻行为吗，不知道是否什么时候能够支持？


是点击图形的时候下钻，类似 emit 的方式可以通过 chart.changeData 加上 chart.render 实现。
