### ISSUE TITLE
折线图点击事件会返回所有数据

### ISSUE THREAD

**Issue by KuduroJS** [antvis/G2#5068]
![image](https://github.com/antvis/G2/assets/101621239/7423d943-61cd-495b-9996-4d838aca2f0a)

预期是返回点击项数据

另，面积图也有这个问题

复现代码：

```javascript
/**
 * A recreation of this demo: https://observablehq.com/@d3/line-chart
 */
import { Chart } from '@antv/g2';

const chart = new Chart({
  container: 'container',
  theme: 'classic',
  autoFit: true,
});

chart
  .line()
  .data({
    type: 'fetch',
    value:
      'https://gw.alipayobjects.com/os/bmw-prod/551d80c6-a6be-4f3c-a82a-abd739e12977.csv',
  })
  .encode('x', 'date')
  .encode('y', 'close');

chart.on('element:click', ev => {
  console.log('click...', ev)
})


chart.render();
```

**Comment by pearmini** [comment]
目前没有提供方法，目前可以通过在折线图上增加 point mark，然后监听 point 的点击事件，可以获取数据。

**Comment by atYty** [comment]
可以使用监听tooltip的变化，变相的实现点击获取对应数据
具体代码：
  const onReadyPie = (plot) => {
    let clickData;
    plot.on('tooltip:change', (e) => {
      clickData=e?.data?.items[0];
    });
    plot.on('element:click', (evt) => {
      console.log('click',clickData);
    });
  };
  。。。。
    <Line
              {...config}
              onReady={onReadyPie}
            />
