### ISSUE TITLE
【重构】统一 formatter 函数签名

### ISSUE THREAD

**Issue by hustcc** [antvis/G2#5069]
axis、legend、slider、scrollbar、tooltip、label 等组件都改成同样的签名吧。

```ts
formatter: (text, datum, idx, data) => string;
```

- [x] label https://github.com/antvis/G2/pull/5062
- [ ] axis
- [ ] legend
- [ ] slider
- [ ] scrollbar
- [ ] tooltip

**Comment by Deathsteps** [comment]
赞同

**Comment by pearmini** [comment]
相同的问题：https://github.com/antvis/G2/issues/5045

**Comment by pearmini** [comment]
这里其实存在问题：axis，legend，slider 和 scrollbar 其实并没有所谓的 `datum` 属性，它们绑定的数据不是可视化的数据，而是通道数据，是一个 primitive 数组: `text === datum`。

除非把别的一些属性加入组件的 datum，比如 id （说实话叫 id 很奇怪）和 color。

**Comment by pearmini** [comment]
更好的签名应该是：`(text, idx, data) => string`

**Comment by pearmini** [comment]
以下的 formatter 本来就是统一的：

- axis
- legend
- slider
- scrollbar

同时不需要和 label 保持统一，因为是两类元素，前者是 component，后者是 mark。
