### ISSUE TITLE
legend位置调整

### ISSUE THREAD

**Issue by rmabcft** [antvis/g2#511]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by dxq613** [comment]
legend 的位置目前仅支持 top,left,right,bottom,但是 top 和 bottom 是居中的，left 和 right 是靠下的。在 4月份后的 3.1 版本中会支持 8 个位置的支持。目前仅能通过 offsetX,offsetY 来调整。

**Comment by stanleyxu2005** [comment]
这个问题很恼人，期待新版本。

**Comment by momogugu** [comment]
@dxq613 请问图例显示位置不够的时候，如何动态调整margin呢？

**Comment by stanleyxu2005** [comment]
@momogugu 一般建议是预估一下多少个图例内容和文字宽度，可以做一个预先的配置。完全自动的实现效果不会很好。

**Comment by momogugu** [comment]
@stanleyxu2005 做了一个动态增加的图表，根据用户选择情况决定显示多少条图线....所以希望图例能够动态变化位置....

**Comment by dxq613** [comment]
已经支持 12 个位置
