### ISSUE TITLE
调节图例的offsetX和offsetY时兼容性有问题

### ISSUE THREAD

**Issue by rmabcft** [antvis/g2#513]

**Comment by dxq613** [comment]
什么兼容性问题，请描述清楚

**Comment by rmabcft** [comment]
在各个浏览器的位置看到是不太一样的

**Comment by rmabcft** [comment]
![image](https://user-images.githubusercontent.com/36733235/37199909-0605f704-23be-11e8-803e-7eaf78acac38.png)
开始打开浏览器时确实是不太一样的。safari和chrome浏览器。而且在view中使用start和end看到的图形大小也是有区别的。
