### ISSUE TITLE
new feature request of making setTheme applied to single chart object

### ISSUE THREAD

**Issue by shuson** [antvis/g2#514]
From the document https://antv.alipay.com/zh-cn/g2/3.x/tutorial/theme.html, we know setTheme is only applied to global scope.

If I may request a feature to make theme only applied to a single chart, for example:

chart.setTheme("xxx").

Thanks for your amazing library.

**Comment by dxq613** [comment]
已经支持了

```
var chart = new G2.Chart({
  container: 'mountNode',
  forceFit: true,
  height: window.innerHeight,
  theme: 'dark'
});
```

**Comment by PerseveranceZ** [comment]
@dxq613 这个 api 目前设置 defaultColor 失效，我会单独提个issue。
