### ISSUE TITLE
[BUG] setSelected设置后，图表无反馈

### ISSUE THREAD

**Issue by Feng-JY** [antvis/g2#515]
* **G2 Version**: 3.0.5-beta.4
* **Platform**: chrome64
* **Mini Showcase(like screenshots)**: 
1.  图表增加seleted样式，
2. 图表默认选中第一项数据
3.  希望图表展示选中项的样式, 但是结果如图，是否我使用错误？
![image](https://user-images.githubusercontent.com/13466494/37016765-dd39ce44-2148-11e8-8704-afb7469ded95.png)

**Comment by leungwensen** [comment]
不是无反馈，而是样式错了。途中白色的扇形就是 selected 的部分

**Comment by Feng-JY** [comment]
@leungwensen 为什么我点击会出现seleted样式，使用setSelected没有生效

**Comment by leungwensen** [comment]
嗯嗯，就是这个 bug

**Comment by dxq613** [comment]
怀疑还是由于初始状态下动画和选中动画一起出现导致的，建议关闭整个图表的动画试试，是否依然出现。

也可以 setSelected 先加个 setTimeout, 等修复这个 bug 后再改回来。

**Comment by xinggaung1996** [comment]
![image](https://user-images.githubusercontent.com/34599092/96677057-5fa14900-13a1-11eb-932f-2eac133dd528.png)为什么我的使用setSelected() 方法 提示未定义呢

**Comment by xinggaung1996** [comment]
我就是在官方教程里 饼状图 代码 的下面 加了 interval.setSelected(data[0]) 
源码错误提示 ：interval.setSelected is not a function
