### ISSUE TITLE
请问一下5.X版本升级后是不支持针对维度设置size通道了吗

### ISSUE THREAD

**Issue by zhouhe-1476452306** [antvis/g2#5156]
4.X 设置颜色通道根据不同year 散点的大小有改变
![image](https://github.com/antvis/G2/assets/75061709/8daeab2d-870d-4a5f-8201-fe2e34b3b437)
5.0.11  设置颜色通道为维度不是指标时，legendContinuous.js 该文件会有报错，再加上color通道也只能区分颜色大小没有改变
![image](https://github.com/antvis/G2/assets/75061709/912ecad6-c842-4e57-a1c3-cf020cf8a59f)

**Comment by hustcc** [comment]
5.0 中 size 仅仅支持数值类型，也就是连续的数据。可以这么做：

```ts
.encode('size', (d) => Number(d.year))
```
