### ISSUE TITLE
快速移动时报错，tagName 取不到。

### ISSUE THREAD

**Issue by Leannechn** [antvis/g2#516]
g2 version: 3.0.5-beta.4

on mouse out of canvas :
![image](https://user-images.githubusercontent.com/6812138/37030904-92c5030e-2177-11e8-8af3-aa965353e134.png)
重现方式：快速移动 in/out 图表，且超过web窗口。
可用console 遮一半图表，快速从图表移动到控制台，可非常稳定重现。

期望： .tagName 前加一个判断，out的时候不一定是domElement。

https://alibaba.github.io/ice/scaffold-preview/ice-design-cms.html#/

**Comment by dxq613** [comment]
已经修复，等待小版本发布即可

https://github.com/antvis/g2/blob/master/src/chart/controller/event.js#L174
