### ISSUE TITLE
当父元素宽度改变时，如何自动触发图表的自适应宽度

### ISSUE THREAD

**Issue by YanYuanFE** [antvis/g2#517]
页面布局如下：
![image](https://user-images.githubusercontent.com/17774285/37067265-fd4759d6-21e3-11e8-96f1-6b563017a9d0.png)
当点击左侧收起按钮时，隐藏左侧部分，右侧宽度占满，图表宽度没有改变，只有在手动改变窗口大小时才会触发图表自适应，使用window.resizeTo也没有作用。图表配置中已经设置了forceFit: true

![image](https://user-images.githubusercontent.com/17774285/37067247-ef5c9cdc-21e3-11e8-9bf0-b005f065f485.png)

**Comment by dxq613** [comment]
手工调用 chart.forceFit();

**Comment by YanYuanFE** [comment]
感谢回复

**Comment by chenhangbin** [comment]
你好，遇到了一样的问题，请问你解决了吗

**Comment by chenhangbin** [comment]
> 感谢回复

你好，遇到了一样的问题，请问你解决了吗
