### ISSUE TITLE
guide画的对象，不能动画吗？

### ISSUE THREAD

**Issue by Zendic** [antvis/g2#52]

**Comment by Zendic** [comment]
![image](https://cloud.githubusercontent.com/assets/5753854/21177138/bb4be422-c224-11e6-97fb-dfb4ab7d72f8.png)    

我画这样的一个图，似乎只能用guide一段一段的绘制。然后还想有个动画效果   

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://os.alipayobjects.com/s/prod/g2/static/doc-b57e62881a0344ecde9e68c4ce312143.css"/>
    <script src="https://a.alipayobjects.com/jquery/jquery/1.11.1/jquery.js"></script>
    <script src="https://a.alipayobjects.com/g/datavis/g2-mobile-all/2.1.7/index.js "></script>
  </head>
  <body>
    <canvas id="c1" style="width:416px;height:218px;"></canvas>
    <script>
      GM.Global.pixelRatio = 2;
      var Util = GM.Util;
      var data = [
        {"month":1, "value": 10,"type":2},
        {"month":2, "value": 22,"type":2},
        {"month":3, "value": 20,"type":1},
        {"month":4, "value": 26,"type":1},
        {"month":5, "value": 20,"type":1},
        {"month":6, "value": 26,"type":1},
        {"month":7, "value": 28,"type":1},
        {"month":8, "value": 20,"type":1},
        {"month":9, "value": 28,"type":1},
        {"month":10, "value": 28,"type":1},
        {"month":11, "value": 28,"type":1},
        {"month":12, "value": 28,"type":1},
      ];
      var chart = new GM.Chart({
        id: 'c1'
      });

      
     chart.axis('month',false);
     chart.axis('value',false);

     chart.source(data);

     
      var canvas = document.getElementById('c1');
      var linear_gradient = canvas.getContext('2d').createLinearGradient(0, 0, 0, 180);
      linear_gradient.addColorStop(0,"#d8e6f8");
	  linear_gradient.addColorStop(1,"white");
      
      
      
      // 绘制渐变色区域图
      chart.area().position('month*value').color('type',function(city){
        
      
          return linear_gradient;
      }).style({
        opacity: 0.6
      });
      
      
      
      // 绘制线图
      
      var dashLine = {
  stroke: '#518edd', 
  lineDash: [0, 2, 2], 
  lineWidth: 2
};
           var Line = {
lineWidth: 2,
    stroke: '#518edd',
             
  
};

      
      chart.guide().line([1,10],[2,22],dashLine);
      chart.guide().line([2,22],[3,20],dashLine);
      chart.guide().line([3,20],[4,26],dashLine);
      chart.guide().line([4,26],[5,20],dashLine);
      chart.guide().line([5,20],[6,26],dashLine);
      
      chart.guide().line([6,26],[7,28],Line);
      chart.guide().line([7,28],[8,20],Line);
      chart.guide().line([8,20],[9,28],Line);
      chart.guide().line([9,28],[10,28],Line);
      chart.guide().line([10,28],[11,28],Line);
      chart.guide().line([11,28],[12,28],Line);
      
      chart.point().position('month*value').color('#518edd').size(3);
      
      chart.animate().waveh();
      
      
      chart.render();
    </script>
  </body>
</html>

**Comment by dxq613** [comment]
何必这么麻烦呢，你完全可以给数据增加一个分类字段，将数据区分成两条直线，重叠处的记录重复一下即可：

```js
const data = [
  { time: '10:01', value: 20, type: 'type1', status: '切换前' },
  { time: '10:02', value: 20, type: 'type1', status: '切换前' },
  { time: '10:03', value: 20, type: 'type1', status: '切换前' },
  { time: '10:03', value: 20, type: 'type1', status: '切换后' },
  { time: '10:04', value: 10, type: 'type1', status: '切换后' },
  { time: '10:05', value: 10, type: 'type1', status: '切换后' },
  { time: '10:06', value: 10, type: 'type1', status: '切换后' }
];

// Step 1: 创建 Chart 对象
const chart = new G2.Chart({
  id: 'c1',  // 指定图表容器 ID
  height: 200,     // 指定图表高度
  forceFit: true,
});

// Step 2: 载入数据源
chart.source(data, {
  time: {
    alias: '时间', // 列定义，定义该属性显示的别名
  },
  value: {
    alias: '分流占比（%）',
    min: 0,
  },
});

// Step 3：创建图形语法，绘制柱状图，由 genre 和 sold 两个属性决定图形位置，genre 映射至 x 轴，sold 映射至 y 轴
chart.line()
     .position('time*value')
     .shape('status', ['line', 'dot']);

// Step 4: 渲染图表
chart.render();
```

最终效果如下：

![image](https://cloud.githubusercontent.com/assets/1264678/21215149/3139b190-c2da-11e6-916e-8fd73a29fb26.png)
