### ISSUE TITLE
堆积条形图数值为负不合理

### ISSUE THREAD

**Issue by rmabcft** [antvis/g2#523]
<script>
  const data = [
    { country: 'Europe', year: '1750', value: 163 },
    { country: 'Europe', year: '1800', value: 203 },
    { country: 'Europe', year: '1850', value: 200 },
    { country: 'Europe', year: '1900', value: 408 },
    { country: 'Europe', year: '1950', value: 547 },
    { country: 'Europe', year: '1999', value: 729 },
    { country: 'Europe', year: '2050', value: 628 },
    { country: 'Europe', year: '2100', value: 828 },
    { country: 'Asia', year: '1750', value: 502 },
    { country: 'Asia', year: '1800', value: 635 },
    { country: 'Asia', year: '1850', value: 1000 },
    { country: 'Asia', year: '1900', value: 947 },
    { country: 'Asia', year: '1950', value: 1402 },
    { country: 'hah', year: '1999', value: 3634 },
    { country: 'hah', year: '2050', value: 5268 },
    { country: 'hah', year: '2100', value: 7268 },
    { country: 'hah', year: '1750', value: 502 },
    { country: 'hah', year: '1800', value: 635 },
    { country: 'hah', year: '1850', value: -800 },
    { country: 'hah', year: '1900', value: 947 },
    { country: 'hah', year: '1950', value: 1402 },
    { country: 'hah', year: '1999', value: 3634 },
    { country: 'hah', year: '2050', value: 5268 },
    { country: 'hah', year: '2100', value: 7268 }
  ];
  const ds = new DataSet();
  const dv = ds.createView()
    .source(data)
    .transform({
      type: 'percent',
      field: 'value',       // 统计销量
      dimension: 'country',   // 每年的占比
      groupBy: [ 'year' ], // 以不同产品类别为分组
      as: 'percent'
    });

  const chart = new G2.Chart({
    container: 'mountNode',
    forceFit: true,
    height: window.innerHeight
  });
  chart.coord().transpose();
  chart.source(dv, {
    percent: {
      min: 0,
      formatter(val) {
        return (val * 100).toFixed(2) + '%';
      }
    }
  });
  chart.guide().line({
      start: [1750, -163],
      end: [2100,7268 ], 
      style: {
        stroke: '#999', 
        lineWidth: 3 
      } 
  });
  chart.intervalStack()
    .position('year*percent')
    .color('country');
  chart.render();
</script>
图一：
![image](https://user-images.githubusercontent.com/36733235/37193599-984096a6-23a5-11e8-8ee8-e08b022468f0.png)
图二：
![image](https://user-images.githubusercontent.com/36733235/37193632-b3c0de04-23a5-11e8-95cc-0777385442b9.png)
如图所示：图一是有负值的情况，图二是无负值的情况。当有负值时，柱子所占百分比不应该改变，只是柱子堆叠的方向改变。可是在这种情况下，柱子所占的百分比发生了改变，也就是说数值为负时，参与了计算。这样是不是不太合理？

**Comment by dxq613** [comment]
存在负值的情况下，压根不应该使用层叠柱状图，数值会相互抵消。如果你想实现那种一边正数，一边负数的场景，建议使用两个 view 分别取实现。
