### ISSUE TITLE
热力图的label颜色改不了

### ISSUE THREAD

**Issue by luoluoluoluoluoluo** [antvis/g2#524]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

热力图的小方块背景颜色为白色时，需要将其对应的字体颜色改为深色，但是代码没有生效。
![image](https://user-images.githubusercontent.com/15343300/37250026-0c66b1bc-252e-11e8-9422-ec6103ce9d93.png)
![image](https://user-images.githubusercontent.com/15343300/37250031-1dd0e4ea-252e-11e8-8594-da9d1377fb42.png)

**Comment by leungwensen** [comment]
![image](https://user-images.githubusercontent.com/1655789/37262415-feb5bb66-25dd-11e8-9256-9220b5fcd8b4.png)

我复现不了，请提供 codepen 链接

**Comment by luoluoluoluoluoluo** [comment]
g2版本问题，解决了，谢谢啦！
