### ISSUE TITLE
雷达图：鼠标进入demo雷达图会报错

### ISSUE THREAD

**Issue by adddddddddddddddddd** [antvis/G2#5248]
雷达图 demo 和柱线混合图鼠标移入报错。

**Comment by adddddddddddddddddd** [comment]
柱线混合同样的问题

**Comment by pearmini** [comment]
- https://g2.antv.antgroup.com/examples/general/radar/#radar

![image](https://github.com/antvis/G2/assets/49330279/dfd237fc-189b-48d8-afee-952d90700896)

@xiaoiver

**Comment by xiaoiver** [comment]
更新到 `@antv/g@5.18.2` 即可：

https://github.com/antvis/G/releases/tag/%40antv%2Fg%405.18.2

**Comment by adddddddddddddddddd** [comment]
好的
