### ISSUE TITLE
请问这种图叫做什么图，颜色相似，但是有层次

### ISSUE THREAD

**Issue by ShawshankLin** [antvis/g2#527]
![qq 20180312103723](https://user-images.githubusercontent.com/16248686/37263071-624c4750-25e1-11e8-9c9c-ae19cb367294.png)

**Comment by dxq613** [comment]
跟 G2 不相关

**Comment by ShawshankLin** [comment]
怎么跟g2不相关啊，，我就是要找g2有没有这样的图啊

**Comment by leungwensen** [comment]
其实就是一堆面积图？ https://antv.alipay.com/zh-cn/gallery/g2/area-horizon-graph.html

**Comment by ShawshankLin** [comment]
是的，，，viser好像没找到这个图

**Comment by ShawshankLin** [comment]
这种图没有轴线？
