### ISSUE TITLE
多张图表渲染时，开启padding：auto，若Y轴过高，会导致图表重叠，若设定margin或自定义padding，会导致label直接不见，自定义设定宽高超过自动生成的宽高时，也会有重叠现象

### ISSUE THREAD

**Issue by xiacandongxue** [antvis/G2#5292]
**目的：**
label值显示正确，及可以自定义动态图表中，每个图表之间的距离，可以自由设定图表的宽高

**情况再现：**

**设定padding：auto的情况：**
![image](https://github.com/antvis/G2/assets/138767660/7002b3bc-8e33-45ef-85bd-1f1b92353138)

**自定义margin和padding的情况：**
**paddingBottom = 120**
![image](https://github.com/antvis/G2/assets/138767660/3b371dc9-e8bd-4ad0-a353-8e2dd1f5934e)
**paddingBottom = 20**
![image](https://github.com/antvis/G2/assets/138767660/2ca495b4-19eb-48c1-8e3e-32111e4a71d4)

**自定义宽高的情况：**
      autoFit = false;
      height = '500';
      width = '2280';
![image](https://github.com/antvis/G2/assets/138767660/be02bd3e-7c86-4f79-b489-3c1fff39a257)

**Comment by pearmini** [comment]
提供一下复现的 demo

**Comment by xiacandongxue** [comment]
[{
		"padding": "auto",
		"children": [{
				"encode": {
					"color": "name",
					"x": "date",
					"y": "number"
				},
				"transform": [{
					"y": "mean",
					"type": "groupX"
				}],
				"data": [{
						"date": "2022-07",
						"number": 519531,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2022-08",
						"number": 508020,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2022-09",
						"number": 373598,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2022-10",
						"number": 390017,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2022-11",
						"number": 1830612,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2022-12",
						"number": 1350869,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2023-01",
						"number": 1667793,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2023-02",
						"number": 786837,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2023-03",
						"number": 866337,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2023-04",
						"number": 7169444,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2023-05",
						"number": 8487615,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2023-06",
						"number": 5260758,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2023-07",
						"number": 4,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2022-07",
						"number": 117504,
						"name": "商家应收未收单量"
					},
					{
						"date": "2022-08",
						"number": 117634,
						"name": "商家应收未收单量"
					},
					{
						"date": "2022-09",
						"number": 189697,
						"name": "商家应收未收单量"
					},
					{
						"date": "2022-10",
						"number": 136539,
						"name": "商家应收未收单量"
					},
					{
						"date": "2022-11",
						"number": 790642,
						"name": "商家应收未收单量"
					},
					{
						"date": "2022-12",
						"number": 316439,
						"name": "商家应收未收单量"
					},
					{
						"date": "2023-01",
						"number": 1051076,
						"name": "商家应收未收单量"
					},
					{
						"date": "2023-02",
						"number": 296733,
						"name": "商家应收未收单量"
					},
					{
						"date": "2023-03",
						"number": 399107,
						"name": "商家应收未收单量"
					},
					{
						"date": "2023-04",
						"number": 6918029,
						"name": "商家应收未收单量"
					},
					{
						"date": "2023-05",
						"number": 7921360,
						"name": "商家应收未收单量"
					},
					{
						"date": "2023-06",
						"number": 4168652,
						"name": "商家应收未收单量"
					},
					{
						"date": "2023-07",
						"number": 4,
						"name": "商家应收未收单量"
					},
					{
						"date": "2022-07",
						"number": 267862,
						"name": "cp应收未收单量"
					},
					{
						"date": "2022-08",
						"number": 154202,
						"name": "cp应收未收单量"
					},
					{
						"date": "2022-09",
						"number": 103838,
						"name": "cp应收未收单量"
					},
					{
						"date": "2022-10",
						"number": 179773,
						"name": "cp应收未收单量"
					},
					{
						"date": "2022-11",
						"number": 961202,
						"name": "cp应收未收单量"
					},
					{
						"date": "2022-12",
						"number": 960912,
						"name": "cp应收未收单量"
					},
					{
						"date": "2023-01",
						"number": 566862,
						"name": "cp应收未收单量"
					},
					{
						"date": "2023-02",
						"number": 485605,
						"name": "cp应收未收单量"
					},
					{
						"date": "2023-03",
						"number": 450236,
						"name": "cp应收未收单量"
					},
					{
						"date": "2023-04",
						"number": 159860,
						"name": "cp应收未收单量"
					},
					{
						"date": "2023-05",
						"number": 370454,
						"name": "cp应收未收单量"
					},
					{
						"date": "2023-06",
						"number": 675692,
						"name": "cp应收未收单量"
					},
					{
						"date": "2023-07",
						"number": 0,
						"name": "cp应收未收单量"
					},
					{
						"date": "2022-07",
						"number": 1036519,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2022-08",
						"number": 791103,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2022-09",
						"number": 613583,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2022-10",
						"number": 689176,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2022-11",
						"number": 3172058,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2022-12",
						"number": 2462018,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2023-01",
						"number": 2320530,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2023-02",
						"number": 1486512,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2023-03",
						"number": 1519837,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2023-04",
						"number": 8295212,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2023-05",
						"number": 9576995,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2023-06",
						"number": 6219255,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2023-07",
						"number": 4,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2022-07",
						"number": 1112745,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2022-08",
						"number": 938245,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2022-09",
						"number": 551072,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2022-10",
						"number": 716419,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2022-11",
						"number": 3316229,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2022-12",
						"number": 3183547,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2023-01",
						"number": 1816009,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2023-02",
						"number": 1712822,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2023-03",
						"number": 1599658,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2023-04",
						"number": 1697554,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2023-05",
						"number": 2394217,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2023-06",
						"number": 11671563,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2023-07",
						"number": 0,
						"name": "cp已收单未计费单量"
					}
				],
				"tooltip": {
					"items": [{
						"valueFormatter": ".1f",
						"channel": "y"
					}]
				},
				"axis": {
					"x": {
						"labelTransform": "rotate(-60)"
					}
				},
				"type": "line"
			},
			{
				"encode": {
					"color": "name",
					"shape": "point",
					"x": "date",
					"y": "number"
				},
				"transform": [{
					"y": "mean",
					"type": "groupX"
				}],
				"data": [{
						"date": "2022-07",
						"number": 519531,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2022-08",
						"number": 508020,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2022-09",
						"number": 373598,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2022-10",
						"number": 390017,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2022-11",
						"number": 1830612,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2022-12",
						"number": 1350869,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2023-01",
						"number": 1667793,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2023-02",
						"number": 786837,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2023-03",
						"number": 866337,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2023-04",
						"number": 7169444,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2023-05",
						"number": 8487615,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2023-06",
						"number": 5260758,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2023-07",
						"number": 4,
						"name": "商家-cp已计费单量差"
					},
					{
						"date": "2022-07",
						"number": 117504,
						"name": "商家应收未收单量"
					},
					{
						"date": "2022-08",
						"number": 117634,
						"name": "商家应收未收单量"
					},
					{
						"date": "2022-09",
						"number": 189697,
						"name": "商家应收未收单量"
					},
					{
						"date": "2022-10",
						"number": 136539,
						"name": "商家应收未收单量"
					},
					{
						"date": "2022-11",
						"number": 790642,
						"name": "商家应收未收单量"
					},
					{
						"date": "2022-12",
						"number": 316439,
						"name": "商家应收未收单量"
					},
					{
						"date": "2023-01",
						"number": 1051076,
						"name": "商家应收未收单量"
					},
					{
						"date": "2023-02",
						"number": 296733,
						"name": "商家应收未收单量"
					},
					{
						"date": "2023-03",
						"number": 399107,
						"name": "商家应收未收单量"
					},
					{
						"date": "2023-04",
						"number": 6918029,
						"name": "商家应收未收单量"
					},
					{
						"date": "2023-05",
						"number": 7921360,
						"name": "商家应收未收单量"
					},
					{
						"date": "2023-06",
						"number": 4168652,
						"name": "商家应收未收单量"
					},
					{
						"date": "2023-07",
						"number": 4,
						"name": "商家应收未收单量"
					},
					{
						"date": "2022-07",
						"number": 267862,
						"name": "cp应收未收单量"
					},
					{
						"date": "2022-08",
						"number": 154202,
						"name": "cp应收未收单量"
					},
					{
						"date": "2022-09",
						"number": 103838,
						"name": "cp应收未收单量"
					},
					{
						"date": "2022-10",
						"number": 179773,
						"name": "cp应收未收单量"
					},
					{
						"date": "2022-11",
						"number": 961202,
						"name": "cp应收未收单量"
					},
					{
						"date": "2022-12",
						"number": 960912,
						"name": "cp应收未收单量"
					},
					{
						"date": "2023-01",
						"number": 566862,
						"name": "cp应收未收单量"
					},
					{
						"date": "2023-02",
						"number": 485605,
						"name": "cp应收未收单量"
					},
					{
						"date": "2023-03",
						"number": 450236,
						"name": "cp应收未收单量"
					},
					{
						"date": "2023-04",
						"number": 159860,
						"name": "cp应收未收单量"
					},
					{
						"date": "2023-05",
						"number": 370454,
						"name": "cp应收未收单量"
					},
					{
						"date": "2023-06",
						"number": 675692,
						"name": "cp应收未收单量"
					},
					{
						"date": "2023-07",
						"number": 0,
						"name": "cp应收未收单量"
					},
					{
						"date": "2022-07",
						"number": 1036519,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2022-08",
						"number": 791103,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2022-09",
						"number": 613583,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2022-10",
						"number": 689176,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2022-11",
						"number": 3172058,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2022-12",
						"number": 2462018,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2023-01",
						"number": 2320530,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2023-02",
						"number": 1486512,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2023-03",
						"number": 1519837,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2023-04",
						"number": 8295212,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2023-05",
						"number": 9576995,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2023-06",
						"number": 6219255,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2023-07",
						"number": 4,
						"name": "商家已收单未计费单量"
					},
					{
						"date": "2022-07",
						"number": 1112745,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2022-08",
						"number": 938245,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2022-09",
						"number": 551072,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2022-10",
						"number": 716419,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2022-11",
						"number": 3316229,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2022-12",
						"number": 3183547,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2023-01",
						"number": 1816009,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2023-02",
						"number": 1712822,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2023-03",
						"number": 1599658,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2023-04",
						"number": 1697554,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2023-05",
						"number": 2394217,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2023-06",
						"number": 11671563,
						"name": "cp已收单未计费单量"
					},
					{
						"date": "2023-07",
						"number": 0,
						"name": "cp已收单未计费单量"
					}
				],
				"tooltip": false,
				"type": "point"
			},
			{
				"tooltip": false,
				"style": {
					"textBaseline": "middle",
					"textAlign": "center",
					"x": "100%",
					"y": "0%",
					"fontSize": 15,
					"text": "详情",
					"fill": "#284cc0"
				},
				"type": "text"
			}
		],
		"theme": "classic",
		"style": {
			"mainFill": "#fff",
			"plotFill": "#fff",
			"viewFill": "#fff",
			"contentFill": "#fff"
		},
		"autoFit": true,
		"type": "view",
		"title": "商家cp结算单量差异对比",
		"thumbnailCode": "acquirerChargedThumbnail3"
	},
	{
		"padding": "auto",
		"children": [{
				"encode": {
					"color": "name",
					"x": "date",
					"y": "number"
				},
				"transform": [{
					"y": "mean",
					"type": "groupX"
				}],
				"data": [{
						"date": "2022-07",
						"number": 37019802,
						"name": "CP已计费单量"
					},
					{
						"date": "2022-08",
						"number": 44367689,
						"name": "CP已计费单量"
					},
					{
						"date": "2022-09",
						"number": 43203104,
						"name": "CP已计费单量"
					},
					{
						"date": "2022-10",
						"number": 41555426,
						"name": "CP已计费单量"
					},
					{
						"date": "2022-11",
						"number": 79739708,
						"name": "CP已计费单量"
					},
					{
						"date": "2022-12",
						"number": 52081304,
						"name": "CP已计费单量"
					},
					{
						"date": "2023-01",
						"number": 44442872,
						"name": "CP已计费单量"
					},
					{
						"date": "2023-02",
						"number": 46982229,
						"name": "CP已计费单量"
					},
					{
						"date": "2023-03",
						"number": 43455696,
						"name": "CP已计费单量"
					},
					{
						"date": "2023-04",
						"number": 51007226,
						"name": "CP已计费单量"
					},
					{
						"date": "2023-05",
						"number": 52617507,
						"name": "CP已计费单量"
					},
					{
						"date": "2023-06",
						"number": 29457241,
						"name": "CP已计费单量"
					},
					{
						"date": "2023-07",
						"number": 4,
						"name": "CP已计费单量"
					},
					{
						"date": "2022-07",
						"number": 38129374,
						"name": "cp应收单量"
					},
					{
						"date": "2022-08",
						"number": 45303825,
						"name": "cp应收单量"
					},
					{
						"date": "2022-09",
						"number": 43745600,
						"name": "cp应收单量"
					},
					{
						"date": "2022-10",
						"number": 42268335,
						"name": "cp应收单量"
					},
					{
						"date": "2022-11",
						"number": 82922804,
						"name": "cp应收单量"
					},
					{
						"date": "2022-12",
						"number": 55248589,
						"name": "cp应收单量"
					},
					{
						"date": "2023-01",
						"number": 46244667,
						"name": "cp应收单量"
					},
					{
						"date": "2023-02",
						"number": 48685661,
						"name": "cp应收单量"
					},
					{
						"date": "2023-03",
						"number": 45049367,
						"name": "cp应收单量"
					},
					{
						"date": "2023-04",
						"number": 52696576,
						"name": "cp应收单量"
					},
					{
						"date": "2023-05",
						"number": 54950355,
						"name": "cp应收单量"
					},
					{
						"date": "2023-06",
						"number": 31828005,
						"name": "cp应收单量"
					},
					{
						"date": "2023-07",
						"number": 4,
						"name": "cp应收单量"
					},
					{
						"date": "2022-07",
						"number": 37867828,
						"name": "cp已收单量"
					},
					{
						"date": "2022-08",
						"number": 45151708,
						"name": "cp已收单量"
					},
					{
						"date": "2022-09",
						"number": 43650495,
						"name": "cp已收单量"
					},
					{
						"date": "2022-10",
						"number": 42091899,
						"name": "cp已收单量"
					},
					{
						"date": "2022-11",
						"number": 82100706,
						"name": "cp已收单量"
					},
					{
						"date": "2022-12",
						"number": 54304328,
						"name": "cp已收单量"
					},
					{
						"date": "2023-01",
						"number": 45692161,
						"name": "cp已收单量"
					},
					{
						"date": "2023-02",
						"number": 48209553,
						"name": "cp已收单量"
					},
					{
						"date": "2023-03",
						"number": 44605014,
						"name": "cp已收单量"
					},
					{
						"date": "2023-04",
						"number": 52544920,
						"name": "cp已收单量"
					},
					{
						"date": "2023-05",
						"number": 54586546,
						"name": "cp已收单量"
					},
					{
						"date": "2023-06",
						"number": 31156863,
						"name": "cp已收单量"
					},
					{
						"date": "2023-07",
						"number": 4,
						"name": "cp已收单量"
					}
				],
				"tooltip": {
					"items": [{
						"valueFormatter": ".1f",
						"channel": "y"
					}]
				},
				"axis": {
					"x": {
						"labelTransform": "rotate(-60)"
					}
				},
				"type": "line"
			},
			{
				"encode": {
					"color": "name",
					"shape": "point",
					"x": "date",
					"y": "number"
				},
				"transform": [{
					"y": "mean",
					"type": "groupX"
				}],
				"data": [{
						"date": "2022-07",
						"number": 37019802,
						"name": "CP已计费单量"
					},
					{
						"date": "2022-08",
						"number": 44367689,
						"name": "CP已计费单量"
					},
					{
						"date": "2022-09",
						"number": 43203104,
						"name": "CP已计费单量"
					},
					{
						"date": "2022-10",
						"number": 41555426,
						"name": "CP已计费单量"
					},
					{
						"date": "2022-11",
						"number": 79739708,
						"name": "CP已计费单量"
					},
					{
						"date": "2022-12",
						"number": 52081304,
						"name": "CP已计费单量"
					},
					{
						"date": "2023-01",
						"number": 44442872,
						"name": "CP已计费单量"
					},
					{
						"date": "2023-02",
						"number": 46982229,
						"name": "CP已计费单量"
					},
					{
						"date": "2023-03",
						"number": 43455696,
						"name": "CP已计费单量"
					},
					{
						"date": "2023-04",
						"number": 51007226,
						"name": "CP已计费单量"
					},
					{
						"date": "2023-05",
						"number": 52617507,
						"name": "CP已计费单量"
					},
					{
						"date": "2023-06",
						"number": 29457241,
						"name": "CP已计费单量"
					},
					{
						"date": "2023-07",
						"number": 4,
						"name": "CP已计费单量"
					},
					{
						"date": "2022-07",
						"number": 38129374,
						"name": "cp应收单量"
					},
					{
						"date": "2022-08",
						"number": 45303825,
						"name": "cp应收单量"
					},
					{
						"date": "2022-09",
						"number": 43745600,
						"name": "cp应收单量"
					},
					{
						"date": "2022-10",
						"number": 42268335,
						"name": "cp应收单量"
					},
					{
						"date": "2022-11",
						"number": 82922804,
						"name": "cp应收单量"
					},
					{
						"date": "2022-12",
						"number": 55248589,
						"name": "cp应收单量"
					},
					{
						"date": "2023-01",
						"number": 46244667,
						"name": "cp应收单量"
					},
					{
						"date": "2023-02",
						"number": 48685661,
						"name": "cp应收单量"
					},
					{
						"date": "2023-03",
						"number": 45049367,
						"name": "cp应收单量"
					},
					{
						"date": "2023-04",
						"number": 52696576,
						"name": "cp应收单量"
					},
					{
						"date": "2023-05",
						"number": 54950355,
						"name": "cp应收单量"
					},
					{
						"date": "2023-06",
						"number": 31828005,
						"name": "cp应收单量"
					},
					{
						"date": "2023-07",
						"number": 4,
						"name": "cp应收单量"
					},
					{
						"date": "2022-07",
						"number": 37867828,
						"name": "cp已收单量"
					},
					{
						"date": "2022-08",
						"number": 45151708,
						"name": "cp已收单量"
					},
					{
						"date": "2022-09",
						"number": 43650495,
						"name": "cp已收单量"
					},
					{
						"date": "2022-10",
						"number": 42091899,
						"name": "cp已收单量"
					},
					{
						"date": "2022-11",
						"number": 82100706,
						"name": "cp已收单量"
					},
					{
						"date": "2022-12",
						"number": 54304328,
						"name": "cp已收单量"
					},
					{
						"date": "2023-01",
						"number": 45692161,
						"name": "cp已收单量"
					},
					{
						"date": "2023-02",
						"number": 48209553,
						"name": "cp已收单量"
					},
					{
						"date": "2023-03",
						"number": 44605014,
						"name": "cp已收单量"
					},
					{
						"date": "2023-04",
						"number": 52544920,
						"name": "cp已收单量"
					},
					{
						"date": "2023-05",
						"number": 54586546,
						"name": "cp已收单量"
					},
					{
						"date": "2023-06",
						"number": 31156863,
						"name": "cp已收单量"
					},
					{
						"date": "2023-07",
						"number": 4,
						"name": "cp已收单量"
					}
				],
				"tooltip": false,
				"type": "point"
			},
			{
				"tooltip": false,
				"style": {
					"textBaseline": "middle",
					"textAlign": "center",
					"x": "100%",
					"y": "0%",
					"fontSize": 15,
					"text": "详情",
					"fill": "#284cc0"
				},
				"type": "text"
			}
		],
		"theme": "classic",
		"style": {
			"mainFill": "#fff",
			"plotFill": "#fff",
			"viewFill": "#fff",
			"contentFill": "#fff"
		},
		"autoFit": true,
		"type": "view",
		"title": "cp应收已收单量对比",
		"thumbnailCode": "acquirerChargedThumbnail2"
	},
	{
		"padding": "auto",
		"children": [{
				"encode": {
					"color": "name",
					"x": "date",
					"y": "number"
				},
				"transform": [{
					"y": "mean",
					"type": "groupX"
				}],
				"data": [{
						"date": "2022-07",
						"number": 36583619,
						"name": "商家已计费单量"
					},
					{
						"date": "2022-08",
						"number": 41710503,
						"name": "商家已计费单量"
					},
					{
						"date": "2022-09",
						"number": 42314179,
						"name": "商家已计费单量"
					},
					{
						"date": "2022-10",
						"number": 41473949,
						"name": "商家已计费单量"
					},
					{
						"date": "2022-11",
						"number": 78759910,
						"name": "商家已计费单量"
					},
					{
						"date": "2022-12",
						"number": 51719675,
						"name": "商家已计费单量"
					},
					{
						"date": "2023-01",
						"number": 43119789,
						"name": "商家已计费单量"
					},
					{
						"date": "2023-02",
						"number": 45639888,
						"name": "商家已计费单量"
					},
					{
						"date": "2023-03",
						"number": 41810598,
						"name": "商家已计费单量"
					},
					{
						"date": "2023-04",
						"number": 37866744,
						"name": "商家已计费单量"
					},
					{
						"date": "2023-05",
						"number": 38479483,
						"name": "商家已计费单量"
					},
					{
						"date": "2023-06",
						"number": 22032746,
						"name": "商家已计费单量"
					},
					{
						"date": "2023-07",
						"number": 0,
						"name": "商家已计费单量"
					},
					{
						"date": "2022-07",
						"number": 37618956,
						"name": "商家应收单量"
					},
					{
						"date": "2022-08",
						"number": 42502116,
						"name": "商家应收单量"
					},
					{
						"date": "2022-09",
						"number": 42913551,
						"name": "商家应收单量"
					},
					{
						"date": "2022-10",
						"number": 42162182,
						"name": "商家应收单量"
					},
					{
						"date": "2022-11",
						"number": 81816158,
						"name": "商家应收单量"
					},
					{
						"date": "2022-12",
						"number": 54191267,
						"name": "商家应收单量"
					},
					{
						"date": "2023-01",
						"number": 45376481,
						"name": "商家应收单量"
					},
					{
						"date": "2023-02",
						"number": 47136008,
						"name": "商家应收单量"
					},
					{
						"date": "2023-03",
						"number": 43332797,
						"name": "商家应收单量"
					},
					{
						"date": "2023-04",
						"number": 46174716,
						"name": "商家应收单量"
					},
					{
						"date": "2023-05",
						"number": 48053191,
						"name": "商家应收单量"
					},
					{
						"date": "2023-06",
						"number": 27333603,
						"name": "商家应收单量"
					},
					{
						"date": "2023-07",
						"number": 4,
						"name": "商家应收单量"
					},
					{
						"date": "2022-07",
						"number": 37504386,
						"name": "商家已收单量"
					},
					{
						"date": "2022-08",
						"number": 42385809,
						"name": "商家已收单量"
					},
					{
						"date": "2022-09",
						"number": 42725170,
						"name": "商家已收单量"
					},
					{
						"date": "2022-10",
						"number": 42026715,
						"name": "商家已收单量"
					},
					{
						"date": "2022-11",
						"number": 81097384,
						"name": "商家已收单量"
					},
					{
						"date": "2022-12",
						"number": 53876154,
						"name": "商家已收单量"
					},
					{
						"date": "2023-01",
						"number": 44326480,
						"name": "商家已收单量"
					},
					{
						"date": "2023-02",
						"number": 46841450,
						"name": "商家已收单量"
					},
					{
						"date": "2023-03",
						"number": 42936280,
						"name": "商家已收单量"
					},
					{
						"date": "2023-04",
						"number": 39297899,
						"name": "商家已收单量"
					},
					{
						"date": "2023-05",
						"number": 40159554,
						"name": "商家已收单量"
					},
					{
						"date": "2023-06",
						"number": 23167346,
						"name": "商家已收单量"
					},
					{
						"date": "2023-07",
						"number": 0,
						"name": "商家已收单量"
					}
				],
				"tooltip": {
					"items": [{
						"valueFormatter": ".1f",
						"channel": "y"
					}]
				},
				"axis": {
					"x": {
						"labelTransform": "rotate(-60)"
					}
				},
				"type": "line"
			},
			{
				"encode": {
					"color": "name",
					"shape": "point",
					"x": "date",
					"y": "number"
				},
				"transform": [{
					"y": "mean",
					"type": "groupX"
				}],
				"data": [{
						"date": "2022-07",
						"number": 36583619,
						"name": "商家已计费单量"
					},
					{
						"date": "2022-08",
						"number": 41710503,
						"name": "商家已计费单量"
					},
					{
						"date": "2022-09",
						"number": 42314179,
						"name": "商家已计费单量"
					},
					{
						"date": "2022-10",
						"number": 41473949,
						"name": "商家已计费单量"
					},
					{
						"date": "2022-11",
						"number": 78759910,
						"name": "商家已计费单量"
					},
					{
						"date": "2022-12",
						"number": 51719675,
						"name": "商家已计费单量"
					},
					{
						"date": "2023-01",
						"number": 43119789,
						"name": "商家已计费单量"
					},
					{
						"date": "2023-02",
						"number": 45639888,
						"name": "商家已计费单量"
					},
					{
						"date": "2023-03",
						"number": 41810598,
						"name": "商家已计费单量"
					},
					{
						"date": "2023-04",
						"number": 37866744,
						"name": "商家已计费单量"
					},
					{
						"date": "2023-05",
						"number": 38479483,
						"name": "商家已计费单量"
					},
					{
						"date": "2023-06",
						"number": 22032746,
						"name": "商家已计费单量"
					},
					{
						"date": "2023-07",
						"number": 0,
						"name": "商家已计费单量"
					},
					{
						"date": "2022-07",
						"number": 37618956,
						"name": "商家应收单量"
					},
					{
						"date": "2022-08",
						"number": 42502116,
						"name": "商家应收单量"
					},
					{
						"date": "2022-09",
						"number": 42913551,
						"name": "商家应收单量"
					},
					{
						"date": "2022-10",
						"number": 42162182,
						"name": "商家应收单量"
					},
					{
						"date": "2022-11",
						"number": 81816158,
						"name": "商家应收单量"
					},
					{
						"date": "2022-12",
						"number": 54191267,
						"name": "商家应收单量"
					},
					{
						"date": "2023-01",
						"number": 45376481,
						"name": "商家应收单量"
					},
					{
						"date": "2023-02",
						"number": 47136008,
						"name": "商家应收单量"
					},
					{
						"date": "2023-03",
						"number": 43332797,
						"name": "商家应收单量"
					},
					{
						"date": "2023-04",
						"number": 46174716,
						"name": "商家应收单量"
					},
					{
						"date": "2023-05",
						"number": 48053191,
						"name": "商家应收单量"
					},
					{
						"date": "2023-06",
						"number": 27333603,
						"name": "商家应收单量"
					},
					{
						"date": "2023-07",
						"number": 4,
						"name": "商家应收单量"
					},
					{
						"date": "2022-07",
						"number": 37504386,
						"name": "商家已收单量"
					},
					{
						"date": "2022-08",
						"number": 42385809,
						"name": "商家已收单量"
					},
					{
						"date": "2022-09",
						"number": 42725170,
						"name": "商家已收单量"
					},
					{
						"date": "2022-10",
						"number": 42026715,
						"name": "商家已收单量"
					},
					{
						"date": "2022-11",
						"number": 81097384,
						"name": "商家已收单量"
					},
					{
						"date": "2022-12",
						"number": 53876154,
						"name": "商家已收单量"
					},
					{
						"date": "2023-01",
						"number": 44326480,
						"name": "商家已收单量"
					},
					{
						"date": "2023-02",
						"number": 46841450,
						"name": "商家已收单量"
					},
					{
						"date": "2023-03",
						"number": 42936280,
						"name": "商家已收单量"
					},
					{
						"date": "2023-04",
						"number": 39297899,
						"name": "商家已收单量"
					},
					{
						"date": "2023-05",
						"number": 40159554,
						"name": "商家已收单量"
					},
					{
						"date": "2023-06",
						"number": 23167346,
						"name": "商家已收单量"
					},
					{
						"date": "2023-07",
						"number": 0,
						"name": "商家已收单量"
					}
				],
				"tooltip": false,
				"type": "point"
			},
			{
				"tooltip": false,
				"style": {
					"textBaseline": "middle",
					"textAlign": "center",
					"x": "100%",
					"y": "0%",
					"fontSize": 15,
					"text": "详情",
					"fill": "#284cc0"
				},
				"type": "text"
			}
		],
		"theme": "classic",
		"style": {
			"mainFill": "#fff",
			"plotFill": "#fff",
			"viewFill": "#fff",
			"contentFill": "#fff"
		},
		"autoFit": true,
		"type": "view",
		"title": "商家应收已收单量对比",
		"thumbnailCode": "acquirerChargedThumbnail1"
	}
]

**Comment by pearmini** [comment]
这个问题是使用了 flex 并且设置 axis 错误导致的，已经解决。
