### ISSUE TITLE
不能正确处理chart的data字段包含空格的情况

### ISSUE THREAD

**Issue by linhualai** [antvis/g2#53]
这种data可以正确处理：
```
    var data = [
      {action: '访问', visitor: 500},
      {action: '付款', visitor: 100}
    ];
    chart.interval().position('action*visitor').color('action'); 
```

如果JSON的key有<空格>或者\<tab> ：
```
    var data = [
      {'visitor action': '访问', 'visitor count': 500},
      {'visitor action': '付款', 'visitor count': 100}
    ];
    chart.interval().position('visitor action*visitor count').color('action'); 

```
这种会有问题。原因是g2在处理坐标轴的时候会将空白字符去除，不知道这样做的理由是什么呢？
是否可以把这个替换去掉？或者将坐标轴的处理和data JSON的处理统一。
<img width="524" alt="2016-12-15 3 01 10" src="https://cloud.githubusercontent.com/assets/1201463/21214960/f83450a4-c2d8-11e6-8148-3ace807907da.png">

**Comment by dxq613** [comment]
去掉这个空格的原因主要是怕用户在字段的两端增加空格如： 

```js
chart.interval().position('a * b')
chart.interval().position(' a * b ')
```

你这种字段名带有空格的场景在业务中遇到的并不多，无论是数据库命名的字段也好，server端的类定义也好，字段名带有空格不是一种好的命名方式。

**Comment by linhualai** [comment]
字段名带有空格确实不是一个良好的习惯，如果既有数据库已经是如此命名的话，也是需要兼容的。

如果可以的话, 改成先split，再两端trim空白是不是一个合理的trade off?

**Comment by dxq613** [comment]
这个建议可以采纳，当时没考虑字段名里面带有空格的场景。

**Comment by dxq613** [comment]
已经在 2.2.1版本后修复这个问题
