### ISSUE TITLE
G2 文档链接失效

### ISSUE THREAD

**Issue by jin5354** [antvis/g2#531]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_tooltip

tooltip api 介绍部分，第18个api `g2-tooltip-marker` 下图附近链接 [自定义 html 模板示例](https://antv.alipay.com/zh-cn/g2/3.x/demo/other/cutomize-tooltip.html) 失效。

**Comment by leungwensen** [comment]
已修复，等待站点发布
