### ISSUE TITLE
【V5】如何实现 TooltipMarker

### ISSUE THREAD

**Issue by BinghuiXie** [antvis/G2#5324]
- **G2 Version**: 5.0.16
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

![image](https://github.com/antvis/G2/assets/34343589/6fef03f1-c8b2-411b-b810-53e31f44b6b4)
图示是 V4 的效果
![image](https://github.com/antvis/G2/assets/34343589/a7089ce9-5e6c-4a3a-a46e-5de99bbc6a02)
上图是 V5 的效果，没有了 V4 的 `tooltipMarker`，这部分在 V5 应该怎么实现呢？

**Comment by BinghuiXie** [comment]
@pearmini

**Comment by pearmini** [comment]
这部分还没有添加，预计这两周加上
