### ISSUE TITLE
downloadImage接口无法导出自定义形状

### ISSUE THREAD

**Issue by chenmf6** [antvis/g2#533]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

问题描述：
使用G6.Graph画了一颗紧凑树，节点使用G6.registerNode注册的shape，由getHtml定义，然后使用downloadImage接口的时候导出的图片不完整，只有edge没有自定义的node。

观察生成的结果后发现自定义节点的部分是在一个独立的DOM节点里面的，没有包含在canvas里面，所以无法导出成图片。希望可以提供一个增强的导出图片接口，可以完整导出自定义形状。

**Comment by chenmf6** [comment]
使用G6.Graph画了一颗紧凑树，节点使用G6.registerNode注册的shape，由getHtml定义，然后使用downloadImage接口的时候导出的图片不完整，只有edge没有自定义的node。

观察生成的结果后发现自定义节点的部分是在一个独立的DOM节点里面的，没有包含在canvas里面，所以无法导出成图片。希望可以提供一个增强的导出图片接口，可以完整导出自定义形状。

**Comment by dxq613** [comment]
请去 G6 的issue 里面提这个问题，https://github.com/antvis/g6/issues
