### ISSUE TITLE
饼图如何选择性地显示label的labelLine

### ISSUE THREAD

**Issue by chenmf6** [antvis/g2#534]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

需求：在饼图中显示各部分的数据的占比（%），其中不为0的显示对应的label。
问题：labelLine无法跟label的内容一起不显示，

**Comment by rmabcft** [comment]
这种情况还是很常见的，希望支持

**Comment by dxq613** [comment]
目前 LabelLine 配置项不支持回调函数，后面可以增加回调函数的支持。

我先通过判断文本是否为空，控制是LabelLine 是否显示吧。
