### ISSUE TITLE
数据标签阴影设置

### ISSUE THREAD

**Issue by rmabcft** [antvis/g2#535]
设置label中的
textStyle={
                  fill:'#000',
                  rotate: 0,
                  textAlign: 'center',
                  shadowBlur: 4,
                  shadowColor: 'rgba(255, 255, 255, 1)'
                }

g2:
![image](https://user-images.githubusercontent.com/36733235/37326783-99082528-26ce-11e8-8cf9-9549efab6d93.png)
highCharts：
![image](https://user-images.githubusercontent.com/36733235/37327047-b7a76466-26cf-11e8-953c-e7cd1cf6406a.png

黑色字体，白色阴影，发现g2阴影很模糊，但是highCharts让就很明显。g2是否可以提供这样的用户体验优化，或者提供自定义设置数据标签样式阴影，并不仅仅限于label中的html方法。

**Comment by dxq613** [comment]
G2 使用的是浏览器 canvas 默认的阴影属性，不会提供额外的绘制阴影的方式。
