### ISSUE TITLE
分面中的padding是否会影响图形大小？

### ISSUE THREAD

**Issue by rmabcft** [antvis/g2#536]
chart.facet('mirror', {
      padding:-80,
      fields: [ 'gender' ],
      transpose: true,
      eachView(view) {
        view.interval().position('age*total_percentage')
          .color('gender', [ '#1890ff', '#f04864' ]);
      }
    });
设置完之后发现图形明显变大？

**Comment by dxq613** [comment]
padding 是不同分面 view 之间的间距，默认是：10， https://github.com/antvis/g2/blob/master/src/facet/base.js#L52

你改成 -80 肯定会增加每个 view 的大小，但是会导致 view 的重合，图形也会变大。
