### ISSUE TITLE
分组柱状图中距离和嵌套

### ISSUE THREAD

**Issue by rmabcft** [antvis/g2#537]
g2是否支持嵌套柱状图，highCharts是通过grouping判断是否嵌套，groupPadding控制分组距离？g2是如何控制同一组之间的padding值的？
![image](https://user-images.githubusercontent.com/36733235/37380382-79de78e6-2773-11e8-99fd-8197ebfd22a1.png)

**Comment by dxq613** [comment]
https://antv.alipay.com/zh-cn/gallery/g2/column-clustered-stacked.html

这个其实就是分组层叠，分别指定分组和层叠的字段即可，间距可以自己进行调整

**Comment by rmabcft** [comment]
你好，我看官网上marginRatio值为1/32,这个32是否是默认的柱状图的宽度，还是有什么其他意义，还有一个问题是如果marginRatio为负值，是嵌套的效果，但是这个时候会有一个z-index的问题，g2是否提供图形的层叠顺序？
.adjust([
      {
        type: 'dodge',
        marginRatio: 1/32// 分组中各个柱子之间不留空隙
      },
      {
        type: 'stack'
      }
    ]);

**Comment by dxq613** [comment]
这个比例其实是对比如当前柱状图宽度，之所以是个比例值，而不是固定值的原因在于，数据有可能是动态的，图表的宽度也是不定的。

没有提供 z-Index 的概念，图形的层叠顺序跟你数据中某个分类出现的顺序一致.

**Comment by rmabcft** [comment]
![image](https://user-images.githubusercontent.com/36733235/37500106-94f21530-2902-11e8-9f4b-75c44129861a.png)
这个图形里面既有分组又有重叠，要怎么样才能达到这种效果呢

**Comment by dxq613** [comment]
可以通过两个 view 来实现这个功能，一个 view 上分组柱状图，一个view 上显示汇总值的柱状图。
