### ISSUE TITLE
网格线颜色

### ISSUE THREAD

**Issue by leon9508** [antvis/G2#5382]
- **G2 Version**: 4.0.8
- **Platform**:
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:  https://codesandbox.io/s/silly-tereshkova-k9dkzg?file=/index.ts

水平网格线的颜色与设置的网格线的颜色不符合，且通过更改透明度的方式也不生效：

<img width="1422" alt="image" src="https://github.com/antvis/G2/assets/25746834/d758ab0a-7ff0-4f08-a3d8-de53c6f0d08b">

**Comment by hustcc** [comment]
![image](https://github.com/antvis/G2/assets/7856674/6a29ec7d-c7bd-45da-95bb-e3cc186978e4)


可以生效。
