### ISSUE TITLE
label.render option causes the font to become bold

### ISSUE THREAD

**Issue by jianjunyuu** [antvis/G2#5390]
- **G2 Version**: v5.0.18
- **Platform**: macos
- **Mini Showcase(like screenshots)**:
- **CodePen Link**: https://stackblitz.com/run?file=index.ts

这边使用g2 v5.0.18版本发现一个问题，使用了 label.render api后，窗口resize，label的dom数量线性递增，导致label展示文本效果是叠加的
文档地址：https://g2.antv.antgroup.com/spec/label/overview

这是初始化的文本：
![image](https://github.com/antvis/G2/assets/49601167/afd026a9-1599-4dc5-8cac-3074d091e898)

这是窗口变化后的效果
![image](https://github.com/antvis/G2/assets/49601167/fadd9eee-3a08-488f-884f-1512e262063f)

文本变粗了

import { Chart } from '@antv/g2';

const data = [
  { action: '浏览网站', pv: 50000 },
  { action: '放入购物车', pv: 35000 },
  { action: '生成订单', pv: 25000 },
  { action: '支付订单', pv: 15000 },
  { action: '完成交易', pv: 8000 },
];

const chart = new Chart({
  container: 'container',
  theme: 'classic',
  autoFit: true,
  paddingRight: 100,
});

chart.coordinate({
  transform: [{ type: 'transpose' }],
});

chart.data(data);

chart
  .interval()
  .encode('x', 'action')
  .encode('y', 'pv')
  .encode('color', 'action')
  .encode('shape', 'funnel')
  .transform({ type: 'symmetryY' })
  .scale('x', { padding: 0 })
  .animate('enter', { type: 'fadeIn' })
  .label({
    // text: (d) => `${d.action}\n${d.pv}`,
    render: (t, d) => `${d.action}\n${d.pv}`,
    position: 'inside',
    transform: [{ type: 'contrastReverse' }],
  })
  .axis(false);

chart.render();

**Comment by hustcc** [comment]
排查中了，原因是 resize 的时候重新渲染， html label 没有回收导致出现多个相同的 dom。
