### ISSUE TITLE
legend mode配置为single 默认选中第一个legend

### ISSUE THREAD

**Issue by momogugu** [antvis/g2#540]
* **G2 Version**:2.3.13
* **Platform**:
* **Mini Showcase(like screenshots)**:
![1521094708237](https://user-images.githubusercontent.com/20534564/37447206-f0c88d78-285b-11e8-88b4-3ed608d3a6da.jpg)

* **CodePen Link**:

配置了legend如下：

    chart.legend('key',{
      title: null, // 不展示图例的标题
      position: 'bottom',
      itemWrap: true,
      mode: 'single',
    });

显示两个或两个以上数据时默认出现上述选中第一个legend的情况，且点击其它legend无法实现切换。
在默认配置multiple时可以正常切换显示。

请问：可能是什么配置不对导致出现上述情况？？

期望结果：在legend：single时也可以正常切换legend

**Comment by dxq613** [comment]
可以调用下 chart.filter('xxx',callback) 过滤一下

**Comment by momogugu** [comment]
@dxq613  感谢
