### ISSUE TITLE
来吧！Ant Design Charts 升级 G2 5.0 正在进行中...

### ISSUE THREAD

**Issue by hustcc** [antvis/G2#5408]
### 说明

[G2 5.0](https://g2.antv.antgroup.com/) 从 2023.03.21 发布正式版本之后，形成了一套 [Spec](https://g2.antv.antgroup.com/manual/core/api) 形式的可视化语法一直在持续迭代，以及解决一些重点 Bug，当目前位置，基本已经有一定的稳定性。

关于 G2 5.0 的一系列特性和优势，不一一介绍了，大家可以去看看文章《[G2 5.0 来啦，伴着春天的脚步，从语言到思维](https://www.yuque.com/antv/blog/zgtv9ezu83r8nusr)》

![image](https://github.com/antvis/G2/assets/7856674/aa02a6f1-ee61-410c-af69-e83e14b6a45c)

接下来，为了让 React 以及 Ant Design 技术生态的用户能更好的享受到 G2 5.0 的优势，我们启动了专项 Ant Design Charts 的升级，这个升级包括了：

- Ant Design 组件库 5.0 的升级
- G2 5.0 的升级

antd + antv 两大 5.0 版本联合，一定会带来不一样效果。**诚邀社区上的同仁一起进来参加组件库的开发，你将获得：**

- Ant Design Charts 的 contributor 权限
- 数据可视化的一些手把手学习机会
- 了解开源项目的工程要求和运作方式
- 大型热门开源项目的参入经验

### 升级计划

![image](https://github.com/antvis/G2/assets/31396322/42490ebb-1d39-47ce-a3a4-affbf48a8d52)

### 工作内容

> 示例参考 [G2 5.0](https://g2.antv.antgroup.com/) 及 [G2Plot 2.0](https://g2.antv.antgroup.com/)

<table>
  <tr>
    <th>阶段</th>
    <th>内容</th>
    <th>详细内容</th>
    <th>计划完成时间</th>
    <th>贡献者</th>
    <th>进度</th>
  </tr>
  <tr>
    <td rowspan="2">设计</td>
    <td>案例验证</td>
    <td></td>
    <td></td>
    <td rowspan="2"><a href="https://github.com/lxfu1" target="_blank">lxfu1</a></td>
    <td>已完成</td>
  </tr>
  <tr>
    <td>架构设计</td>
    <td></td>
    <td></td>
    <td>已完成</td>
  </tr>
 <tr>
    <td rowspan="9">2.0.0-alpha.0</td>
    <td>Line</td>
    <td rowspan="8">1. 图表基础能力<br/>2.图表标注<br/>3.tooltip、label等<br/>4.示例</td>
    <td  rowspan="9">0831</td>
    <td rowspan="3"><a href="https://github.com/lxfu1" target="_blank">lxfu1</a></td>
    <td rowspan="3">开发中</td>
  </tr>
<tr>
    <td>Column</td>
  </tr>
<tr>
    <td>Bar</td>
  </tr>
<tr>
    <td>Pie</td>
    <td rowspan="2"><a href="https://github.com/ancyloce" target="_blank">lethe</a></td>
    <td rowspan="2">开发中</td>
  </tr>
 <tr>
    <td>Rose</td>
  </tr>
  <tr>
    <td>Area</td>
    <td><a href="https://github.com/ChenKun1997" target="_blank">ChenKun1997</a></td>
    <td>开发中</td>
  </tr>
  <tr>
    <td>Scatter</td>
    <td><a href="https://github.com/ai-qing-hai" target="_blank">ai-qing-hai</a></td>
    <td>开发中</td>
  </tr>
   <tr>
    <td>Radar</td>
    <td></td>
    <td>未开始</td>
  </tr>
   <tr>
    <td>语雀文档</td>
    <td>1.基本使用文档</td>
    <td></td>
    <td>未开始</td>
  </tr>
  
   <tr>
    <td rowspan="14">2.0.0-beta.1</td>
    <td>Liquid</td>
    <td rowspan="13">1. 图表功能完善<br/>2.图表附加功能<br/>3.交互<br/>4.文档、示例</td>
    <td  rowspan="14">0831</td>
    <td></td>
    <td>未开始</td>
  </tr>
<tr>
    <td>Progress</td>
    <td></td>
    <td>未开始</td>
  </tr>
  <tr>
    <td>DualAxes</td>
    <td></td>
    <td>未开始</td>
  </tr>
  <tr>
    <td>Facet</td>
    <td></td>
    <td>未开始</td>
  </tr>
  <tr>
    <td>Funnel</td>
    <td><a href="https://github.com/BinghuiXie" target="_blank">BinghuiXie</a></td>
    <td>未开始</td>
  </tr>
  <tr>
    <td>Gauge</td>
    <td></td>
    <td>未开始</td>
  </tr>
  <tr>
    <td>Bullet</td>
    <td></td>
    <td>未开始</td>
  </tr>
  <tr>
    <td>TinyLine</td>
    <td></td>
    <td>未开始</td>
  </tr>
  <tr>
    <td>TinyBar</td>
    <td></td>
    <td>未开始</td>
  </tr>
  <tr>
    <td>TinyColumn</td>
    <td></td>
    <td>未开始</td>
  </tr>
  <tr>
    <td>RingProgress</td>
    <td></td>
    <td>未开始</td>
  </tr>
  <tr>
    <td>Sankey</td>
    <td></td>
    <td>未开始</td>
  </tr>
   <tr>
    <td>Mix</td>
    <td></td>
    <td>未开始</td>
  </tr>
   <tr>
    <td>升级指南</td>
    <td>1. V1到V2变更梳理</td>
    <td></td>
    <td>未开始</td>
  </tr>
  
   <tr>
    <td rowspan="13">2.0.0-beta.2</td>
    <td>Chord</td>
    <td rowspan="13">1. 图表功能完善<br/>2.图表附加功能<br/>3.交互<br/>4.文档、示例</td>
    <td  rowspan="13">0930</td>
    <td></td>
    <td>未开始</td>
  </tr>
<tr>
    <td>Heatmap</td>
    <td></td>
    <td>未开始</td>
  </tr>
  <tr>
    <td>Treemap</td>
    <td></td>
    <td>未开始</td>
  </tr>
  <tr>
    <td>Waterfall</td>
    <td></td>
    <td>未开始</td>
  </tr>
  <tr>
    <td>WordCloud</td>
    <td></td>
    <td>未开始</td>
  </tr>
  <tr>
    <td>Histogram</td>
    <td></td>
    <td>未开始</td>
  </tr>
  <tr>
    <td>Sunburst</td>
    <td></td>
    <td>未开始</td>
  </tr>
  <tr>
    <td>BidirectionalBar</td>
    <td></td>
    <td>未开始</td>
  </tr>
  <tr>
    <td>RaidaBar</td>
    <td></td>
    <td>未开始</td>
  </tr>
  <tr>
    <td>Box</td>
    <td></td>
    <td>未开始</td>
  </tr>
  <tr>
    <td>Stock</td>
    <td></td>
    <td>未开始</td>
  </tr>
  <tr>
    <td>Venn</td>
    <td></td>
    <td>未开始</td>
  </tr>
  <tr>
    <td>CirclePacking</td>
    <td></td>
    <td>未开始</td>
  </tr>
  
   <tr>
    <td >2.0.0</td>
    <td>发布正式版本</td>
    <td >1.V1能力走查<br/>2.升级插件<br/>3.1122宣发文章<br/>4.单测覆盖<br/>5.官网</td>
    <td  >1122</td>
    <td></td>
    <td>未开始</td>
  </tr>
</table>

### 要求

不是无门槛都来参入，要求如下：

- 有一定的前端开发经验，最好有一些工程优质的开源项目（不看 star，看代码工程质量）
- 在学习、工作中有使用过 AntV 或者 Ant Design Charts 的库
- 能善始善终，兜底不如重写，我们宁愿教会你怎么做，也不愿意废弃你半途而废的工作而重写

### 怎么参入？

回复 issue 认领，并留下自己的联系账号（建议是钉钉，没有话也只能微信了，担心爬虫泄漏，加一个 [morse](https://atool.vip/morse/) 加密），即可。✿✿ヽ(°▽°)ノ✿

**Comment by BinghuiXie** [comment]
这个怎么参与呢

**Comment by hustcc** [comment]
> 这个怎么参与呢

正文内容已经补充参入方式。

**Comment by lxfu1** [comment]
> .----/---../---../...../.----/-----/--.../-..../.----/---../..... Funnel

钉钉开发群

![1692174073936](https://github.com/antvis/G2/assets/31396322/380db346-b4d7-4b81-a96c-562c168ad5e9)

**Comment by 2239058652** [comment]
就不能修复一下g25.1.0之后的版本吗，发布了俩个版本了都没发现有报错问题？？？使用cdn引入报错
![image](https://github.com/antvis/G2/assets/85220715/eda78088-8496-402f-ad33-a2306d21fc0d)

**Comment by pfdgithub** [comment]
> 就不能修复一下g25.1.0之后的版本吗，发布了俩个版本了都没发现有报错问题？？？使用cdn引入报错 ![image](https://user-images.githubusercontent.com/85220715/268221155-eda78088-8496-402f-ad33-a2306d21fc0d.png)

类似的报错，可能是同一个原因导致的。
```
scaleInY.ts:61 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'finished')
    at scaleInY.ts:61:15
    at plot.ts:1526:15
    at plot.ts:979:22
    at selection.ts:395:14
    at _Selection.each (selection.ts:372:7)
    at _Selection.transition (selection.ts:394:17)
    at plot.ts:978:14
    at _Selection.join (selection.ts:330:22)
    at plot.ts:970:8
    at Generator.next (<anonymous>)
```
