### ISSUE TITLE
图例能否声明使用分类图例而非连续图例

### ISSUE THREAD

**Issue by jin5354** [antvis/g2#545]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

如果X轴为连续数字，如123456，那么图例会自动变成连续图例。
有些情况下我不需要连续图例，可否提供一个配置项，声明使用分类图例？文档里我没有找到相关选项。

**Comment by dxq613** [comment]
有两种方案：
1. 将数据改成分类类型 1 => '1'
2. 自定义图例, https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_legend ,看看 custom 属性

**Comment by jin5354** [comment]
@dxq613 感谢回复，我摸索出第一种解决方案了。
另外有个需求就是图例可否开放更多事件：例如我需要 hover 时展示 tooltip，移出时隐藏 tooltip，也就是说需要 mouseenter 和 mouseleave，目前看文档里只有 onHover 是难以实现这个功能的, custom 也只有 hover 和 click 两种事件的自定义。

**Comment by jin5354** [comment]
@dxq613 如果X轴为 '2018-03-29 00:00:00'  这种连续日期，即使是字符串也是连续图例，而且存在bug一拖动就变成 NaN。
使用自定义图例，有没有办法方便的获取所有区块的颜色并赋值到 fill 里？我真的看了半天 geom 和 color 也没搞清楚，请教一下，我再读读文档去。。

**Comment by jin5354** [comment]
我 String() 处理一下 X 轴，再 + ' ' 就可以了，囧。
