### ISSUE TITLE
官网 lottie demo 显示出现异常

### ISSUE THREAD

**Issue by hustcc** [antvis/G2#5451]
- **G2 Version**: 5.0.20
- **Platform**: mac
- **Mini Showcase(like screenshots)**:
- **CodePen Link**: https://g2.antv.antgroup.com/examples/animation/lottie#lottie

![image](https://github.com/antvis/G2/assets/7856674/1f7d14b8-7540-482a-b0e1-9841e79e1571)

**Comment by xiaoiver** [comment]
很奇怪，在 G 官网以及 CodeSandbox 上和 G2 结合的例子都是 OK 的：
https://g.antv.antgroup.com/examples/ecosystem/lottie/#lottie-player-assets
