### ISSUE TITLE
柱状图横轴是日期的时候第一个柱子会侵占到y轴

### ISSUE THREAD

**Issue by qwemicheal** [antvis/g2#547]
* **G2 Version**: 3.0.5-beta.5
* **Platform**: chrome
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/14201792/37552615-cfe5d784-29f3-11e8-95d9-0467e5e67253.png)

* **CodePen Link**:

在使用堆叠柱状图的时候，当把例子中的year数据改成带日期的格式，出来的图表中第一个柱子就会侵占到Ｙ轴，使用文档中的例子就可以复现．

目前只发现日期格式会导致这个问题，当日期的格式从　YYYY-MM-DD变成YY-MM-DD,则不会出现这个问题．

**Comment by dxq613** [comment]
改成 timeCat 或者列定义里面设置 range

```js
chart.source(data, {
  time: {
    type: 'timeCat'
 }
});


chart.source(data, {
  time: {
     range: [ 1/count, 1-1/count] // 数据的条数
 }
});
```
