### ISSUE TITLE
外层容器添加transform缩放后，图表的悬浮、点击事件的位置错位失效

### ISSUE THREAD

**Issue by zhouhe-1476452306** [antvis/G2#5472]
![image](https://github.com/antvis/G2/assets/75061709/b2da1124-2bcd-43e9-9f4c-6b66f60f5acc)

**Comment by hustcc** [comment]
@xiaoiver 之前旧版本 G 中，需要手动设置 supportCSSTransform: true，新版本中也需要设置这个属性吗？

**Comment by xiaoiver** [comment]
https://github.com/antvis/G/issues/1161

**Comment by xyr550** [comment]
![image](https://github.com/antvis/G2/assets/73283715/e04d2380-ea86-4a81-b8f0-705a0e7ea14e)

大佬，设置了这个属性没有用，还是失效的，这个属性是这么用的吗

**Comment by pearmini** [comment]
@xyr550 这个配置还不支持哈，我这周支持一下

**Comment by hustcc** [comment]
> @xyr550 这个配置还不支持哈，我这周支持一下

是否可以默认 `supportsCSSTransform` 打开，不需要额外用户配置？@xiaoiver @pearmini

**Comment by pearmini** [comment]
@hustcc 还是需要用户显示地配置，因为这个属性会跳过 G 的处理流程，是不保证稳定的，所以按需使用。

如果真的是希望进行缩放，更好的做法是操作 G 里面的视图节点：

```js
chart.render().then(() => {
  const canvas = chart.getConext().canvas;
  const [view] = canvas.getElementsByClassName('view');
  view.style.transform = 'scale(1.5';
})
```

**Comment by pearmini** [comment]
@xyr550  你设置外层容器 style.transform 的场景是啥？

**Comment by zhouhe-1476452306** [comment]
整一个画布存在多个组件，当设置的画布大小不满足当前电脑的分辨率时 可以进行宽度适应、高度适应 ，添加transform属性将该画布进行缩放填充。针对于整一个画布，并不是单个的图表缩放。
![image](https://github.com/antvis/G2/assets/75061709/815cbc7f-2b72-42ac-94e5-9ea1806f617d)
