### ISSUE TITLE
[V5] 支持 3D Barchart

### ISSUE THREAD

**Issue by xiaoiver** [antvis/G2#5477]
参考 3D Scatter 实现 3D Barchart。扩展 `mark/interval3D`，使用 G 提供的 [CubeGeometry](https://g.antv.antgroup.com/api/3d/geometry#cubegeometry) 实现 `shape/interval3D/cube`。
可参考：
* [shape/point3D/cube](https://github.com/antvis/G2/blob/v5/src/shape/point3D/cube.ts)
* `chart-render-3d-scatter-plot` 示例

可暂不考虑 3D 交互（tooltip、crosshair），后续统一实现。

其他图表库支持的 3D Barchart：

* https://echarts.apache.org/examples/zh/index.html#chart-type-bar3D
* https://www.anychart.com/products/anychart/gallery/3D_Bar_Charts/Multi-Series_3D_Bar_Chart_with_Z_Distribution.php
* https://www.fusioncharts.com/charts/column-bar-charts/bar-chart-in-3d?framework=javascript
* https://matplotlib.org/stable/gallery/mplot3d/3d_bars.html

**Comment by pearmini** [comment]
🚀
