### ISSUE TITLE
柱状图项目太多，浮层被截断

### ISSUE THREAD

**Issue by forthedamn** [antvis/g2#55]
- 如图所示的问题，请问当下可有较好的解决办法？

![image](https://cloud.githubusercontent.com/assets/8744583/21284504/db448880-c457-11e6-8b7e-657b64a303f3.png)

**Comment by simaQ** [comment]
这种情况的话，你可以使用自定义 html 模板实现 tooltip，使用 inline-block 的方式展示。 
实例 demo: https://g2.alipay.com/tutorial/tooltip.html#自定义模板，缩进
