### ISSUE TITLE
对高德的geoJson 渲染path 有误

### ISSUE THREAD

**Issue by Leannechn** [antvis/g2#551]
g2version: 3.x
对高德的geoJson 渲染有问题。
复现：点击海域，切换到全国视图，可观察到陕西／甘肃／黑龙江／台湾等几个省有错误连线
https://antv.alipay.com/zh-cn/g2/3.x/demo/map/drill-down.html
问题定位：高德的高精度geoJson 中的coordinates是以一个三维数组，包含主区域以及部分小点。问题就是这些部分小点path绘制有误。以台湾为例，那条白线是两个岛屿连线。

**Comment by dxq613** [comment]
@leungwensen  这个有些严重，看看是 dataset 的问题还是我们 polygon 的绘制有问题

**Comment by Leannechn** [comment]
补充一点，该demo在处理数据过程中修改了这个geojson 对象，建议不要修改源数据json。

**Comment by leungwensen** [comment]
@dxq613 这个问题是这样的，某个地区的 GeoJSON 里存在多个闭合路径，但 dataset 解释出来的以及 polygon 能支持的只能是一个闭合路径，所以就出现这个问题

@Leannechn 你们那个应该是旧的，修改 GeoJSON 其实是高德地图自己的 API 做的事情，在新版官网上我已经修复这个问题里

**Comment by Leannechn** [comment]
好的，非常感谢～

**Comment by leungwensen** [comment]
后面可能需要对高德这样特殊的 GeoJSON 做一个处理？ @dxq613

**Comment by dxq613** [comment]
整理一下，跟高德的人一起过一下。后续地图不能这样下去

**Comment by dxq613** [comment]
后续我们地图的需求做个独立的框架出来后，G2 就做通用的那些地图需求，国内的地图需求，还是走跟高德合作的方案吧，这块一不小心就会采坑。

**Comment by leungwensen** [comment]
done 3.0.7
