### ISSUE TITLE
G2 5.1.2 umd 版本在 ob 上报错

### ISSUE THREAD

**Issue by pearmini** [antvis/G2#5548]
![image](https://github.com/antvis/G2/assets/49330279/a48c4052-bfdd-4af9-8e88-15ab5017e45f)

**Comment by pearmini** [comment]
可能是 target 从 es6 变成 es5 之后的问题。

**Comment by iceabing** [comment]
这个怎么解决的啊，我也遇到同样的问题

**Comment by 2239058652** [comment]
> 这个怎么解决啊，我也遇到同样的问题

他妈的，真是服了，切换成5.10   <script src="https://cdn.bootcdn.net/ajax/libs/antv-g2/5.1.0/g2.min.js"></script>版本就可以了，他妈的，他最近的俩个版本都是错误的

**Comment by 2239058652** [comment]
不仅仅是5.1.2，从5.1.0之后都是错误的，看了一下源码，会一直报_marks未定义的错误

**Comment by pearmini** [comment]
相同的问题：https://github.com/antvis/G2/issues/5552
