### ISSUE TITLE
刻度值字体颜色显示有误

### ISSUE THREAD

**Issue by devilmengcry** [antvis/g2#5554]
问题如图，设置成白色还是显示的灰色，适配不了深色主题
![image](https://github.com/antvis/G2/assets/6964329/69dd18cd-161e-4806-97dc-d4529665e4b9)

**Comment by kikashine** [comment]
越俎代庖地回答一下吧。

控制刻度文字颜色的参数是labelFill，例如： labelFill:"#fff"

labelStroke是文字阴影颜色。

可能是文档失误，但由来已久。

**Comment by pearmini** [comment]
@kikashine 有空 提个 PR 修复这个文档错误吗！

**Comment by kikashine** [comment]
> @kikashine 有空 提个 PR 修复这个文档错误吗！

可以，我研究一下怎么提。

**Comment by kikashine** [comment]
> @kikashine 非常感谢。

不客气

**Comment by hustcc** [comment]
> > @kikashine 有空 提个 PR 修复这个文档错误吗！
> 
> 可以，我研究一下怎么提。

参考下这个，里面介绍了，怎么启动。https://github.com/antvis/G2/blob/v5/CONTRIBUTING.zh-CN.md
