### ISSUE TITLE
[v5] 用v5版本g2如何实现 v4版本的 chart.annotation().arc(option)

### ISSUE THREAD

**Issue by jason-zuo** [antvis/G2#5561]
- **G2 Version**: 5.0.18
- **Platform**: mac
- **Mini Showcase(like screenshots)**:
- **CodePen Link**:

`chart.annotation().arc(option)`

**Comment by pearmini** [comment]
使用来画仪表盘？

**Comment by jason-zuo** [comment]
@pearmini 嗯是的，有定制化的仪表盘需求以前是用多个view配合arc实现的，现在v5我看mark里边没有arc了

**Comment by pearmini** [comment]
现在已经支持了仪表盘：https://g2.antv.antgroup.com/examples/general/gauge/#gauge-default，你看看满不满足需求。

**Comment by jason-zuo** [comment]
@pearmini 嗯我之前看过感觉不是太满足，需要好几个半圆，还要重新定义下指针样式,所以就想问下原来的arc现在咋实现

**Comment by pearmini** [comment]
是自定义 shape，可以参考 gauge 的实现：thub.com/antvis/G2/blob/v5/src/mark/gauge.ts

**Comment by jason-zuo** [comment]
@pearmini 好的谢谢，等完成之后我整理下提PR

**Comment by pearmini** [comment]
这个 issue 先关闭了，期待 PR！
