### ISSUE TITLE
建议加入一个类似于ECharts中‘timeline’的控件！

### ISSUE THREAD

**Issue by sainthyz** [antvis/g2#558]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

我现在做的数据可视化项目应用场景是大屏幕，需要随时间切换，ECharts中的‘timeline’使用非常方便，默认样式美观度也比较高，建议g2团队也可以考虑加入有一个类似‘timeline’的组件。

**Comment by elaine1234** [comment]
抱歉，目前暂无规划
