### ISSUE TITLE
折线图横轴比较密集的时候能做到自动划分区间么

### ISSUE THREAD

**Issue by zzwar2009** [antvis/g2#559]
折线图横轴比较密集的时候能做到自动划分区间么 ，比如横轴是两个月的每一天就有60个点，能有什么办法能自适应为每一个点是三天 或者5天这样显得横轴轴的点不是那么密集

**Comment by dxq613** [comment]
如果坐标轴类型是 cat 或者 timeCat, 你可以设置个 tickCount ,目前的策略是按照你设置的 tickCount 向下找一个能被你分类数量整除的数。

**Comment by zzwar2009** [comment]
ok . 多谢您

**Comment by leungwensen** [comment]
label、tick 和 grid 会根据空间采样，优先考虑 label 遮罩问题

**Comment by dxq613** [comment]
在 4.0 中重新设计
