### ISSUE TITLE
G2 多 bundle 包构建

### ISSUE THREAD

**Issue by hustcc** [antvis/G2#5592]
## 包构成

G2 的 bundle 包分成为两类：

- 直接可用的 umd 包
  - g2.lite.min.js：包含有插件 core
  - g2.min.js：包含有插件 core、plot、graph、geo
  - g2.full.min.js：包含有插件 core、plot、graph、geo、threed、auto
- G2 的插件包
  - lib.core.min.js
  - lib.plot.min.js
  - lib.graph.min.js
  - lib.geo.min.js
  - lib.threed.min.js
  - lib.auto.min.js

## UMD 使用方式

- g2.lite.min.js

仅使用基础包：

```html
<script src="..../g2.lite.min.js" />

const chart  = new Chart();
```

增加扩展包：

```html
<script src="..../g2.lite.min.js" />
<script src="..../lib.geo.min.js" />
<script src="..../lib.plot.min.js" />

const Chart = extend(Runtime， { ...a, ...b });

const chart = new Chart();
```

- g2.min.js

```html
<script src="..../g2.min.js" />
<script src="..../lib.auto.min.js" />
```

**Comment by pearmini** [comment]
closed by: https://github.com/antvis/G2/pull/5597
