### ISSUE TITLE
scrollbar 和 tooltip 同时配置时代码报错 不能正常显示

### ISSUE THREAD

**Issue by devilmengcry** [antvis/G2#5605]
![image](https://github.com/antvis/G2/assets/6964329/4150cebb-37d4-46f4-b4d9-24a633974b61)

复现 demo：https://codesandbox.io/s/purple-darkness-7vw24z

**Comment by pearmini** [comment]
这是一个 bug，可能和筛选逻辑有关。

**Comment by pearmini** [comment]
初步排查了一下，应该是和 tooltip 的 groupItems 有关系，普通的条形图（非分组条形图）是没有问题的。
