### ISSUE TITLE
分组柱状图图例数量过多时渲染浏览器崩溃

### ISSUE THREAD

**Issue by completeAutumn** [antvis/g2#562]
g2version: 3.0.4
代码：`chart.intervalDodge().position(`x*y`).color(color);`
问题：当图例数量过多时浏览器崩溃，调试源码发现崩溃发生在LegendController.prototype._addCategroyLegend方法中Util.each(ticks, function (tick) ,ticks数量4698，在缩小数据量之后渲染是正常的。
之前认为可能是图例中包含null/undefined的值导致的，修正空数据值为'NULL'字符串，仍然会崩溃。
最后发现是循环时间过长导致浏览器长时间无反应造成。
请问下这种情况有办法解决吗？或者如何让图表实现异步渲染？

**Comment by dxq613** [comment]
分类太多导致的，你可以在列定义里面加个 tickCount
