### ISSUE TITLE
使用facetCircle绘制时，月份的数据和具体图表对应不上诶

### ISSUE THREAD

**Issue by voiddiddvue** [antvis/G2#5624]
### AntV Open Source Contribution Plan（可选）

- [X] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

中级任务

### 任务介绍

使用[facetCircle绘制](https://g2.antv.antgroup.com/examples/composition/facet#circle)时，月份的数据和具体图表对应不上：

- 最后绘制出来的图，Jan在Jun那里。
- 另外，如果month的个数是奇数，就会出现刻度和图表对应不准的情况

```js
import { Chart } from '@antv/g2';

const M = [
  'Jan.',
  'Feb.',
  'Mar.',
  'Apr.',
  'May',
  'Jun.',
  'Jul.',
  'Aug.',
  'Sept.',
  'Oct.',
  'Nov.',
  'Dec.',
];
const N = ['A', 'B', 'C', 'D'];
const data = M.flatMap((month) =>
  N.map((name) => ({
    month,
    name,
    value: month === 'Jan.' ? 1 : 0 //这里指定数据
  })),
);

const chart = new Chart({
  container: 'container',
  width: 480,
  height: 480,
});

const facetCircle = chart.facetCircle().data(data).encode('position', 'month');

facetCircle
  .interval()
  .encode('x', 'name')
  .encode('y', 'value')
  .encode('color', 'name');

chart.render();
```

### 参考

- 可能和这个[函数](https://github.com/antvis/G2/blob/082982da29b6c359c5b09694a6c25cdaf0aee673/src/composition/facetCircle.ts#L52)有关系。

**Comment by pearmini** [comment]
这个感觉是个 bug，和这个[函数](https://github.com/antvis/G2/blob/082982da29b6c359c5b09694a6c25cdaf0aee673/src/composition/facetCircle.ts#L52)有关系，感兴趣来修复一下吗？

**Comment by voiddiddvue** [comment]
> 这个感觉是个 bug，和这个[函数](https://github.com/antvis/G2/blob/082982da29b6c359c5b09694a6c25cdaf0aee673/src/composition/facetCircle.ts#L52)有关系，感兴趣来修复一下吗？

好，有空了看看我能不能修复

**Comment by BENcorry** [comment]
【BENcorry 认领】

**Comment by pearmini** [comment]
closed by：https://github.com/antvis/G2/pull/5833
