### ISSUE TITLE
我设置了tickCount，但是为什么仍然不能锁死y轴的个数？

### ISSUE THREAD

**Issue by aa1011372655** [antvis/g2#563]
tickCount为5时，由于数值的不同，会出现6个坐标的情况？是正常现象吗？
另外，混合图，线图和柱图的组合，怎么保证两个y坐标都是5个，非常感谢

**Comment by dxq613** [comment]
tick 的计算需要计算出适合人阅读的间隔，所以会对数据范围进行调整，无法做到精确的 tickCount,目前能够做到误差一个，也就说 5 个坐标点，可能会出现 6 个的场景。

如果你想精确5个的话，可以自己设置 ticks

**Comment by leungwensen** [comment]
这块会在 3.1 版本里做改造

**Comment by aa1011372655** [comment]
这部分如果出现与tickcout不一致的情况，有时候 scale 会碰到除不尽的问题，只需要设置min为0即可，当前解决方案测试可行，非常感谢
