### ISSUE TITLE
实现正方形四角雷达图

### ISSUE THREAD

**Issue by jiojio-jx** [antvis/G2#5636]
### AntV Open Source Contribution Plan（可选）

- [X] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

中级任务

### 任务介绍

绘制如下的正方形雷达图：

<img src="https://github.com/antvis/G2/assets/49330279/4bca73de-082e-4a83-a82c-bdf680fc96ac" width=640 />

- 在 `__tests__/intergration/plots/static` 下面增加一个测试案例
- 在官网雷达图的地方增加这个 demo

### 参考

- https://observablehq.com/d/cc18257b8ecb13c2 这个实现部分能力，比较复杂的地方是后面的刻度线。看上去 [@antv/component](https://github.com/antvis/component) 的 gridConnect 在 line 的时候实效了，所以也许需要提交 @antv/component 的 PR。

**Comment by pearmini** [comment]
![image](https://github.com/antvis/G2/assets/49330279/4bca73de-082e-4a83-a82c-bdf680fc96ac)

**Comment by pearmini** [comment]
目前困难地方是后面的刻度线：https://observablehq.com/d/cc18257b8ecb13c2

**Comment by kun6696** [comment]
官方文档没有这个gridConnect  这个属性吧

**Comment by zhuyyafd** [comment]
zhuyyafd 认领

**Comment by kun6696** [comment]
@zhuyyafd   这位老兄，这个问题解了嘛，如果没有的话，我来提了pr吧。

**Comment by hustcc** [comment]
> @zhuyyafd 这位老兄，这个问题解了嘛，如果没有的话，我来提了pr吧。

你来吧，这个 issue 时间有点久了！
