### ISSUE TITLE
Slider 开始跟 X 开始不一致问题

### ISSUE THREAD

**Issue by fundon** [antvis/g2#564]
* **G2 Version**: 3.0.4
* **Platform**: 
* **Mini Showcase(like screenshots)**:
<img width="1204" alt="screen shot 2018-04-02 at 10 02 47" src="https://user-images.githubusercontent.com/27926/38180176-1042a38c-365d-11e8-915d-ad5fb45d5aed.png">
<img width="214" alt="screen shot 2018-04-02 at 10 03 37" src="https://user-images.githubusercontent.com/27926/38180184-22c17916-365d-11e8-9d5d-d121849951a7.png">

* **CodePen Link**:

X 轴从 1 到 12，但下面的 Slider 却从 0 开始，还需要什么配置吗？

我想要 Slider 的开始 1 顶到最左边

G2 新手

**Comment by leungwensen** [comment]
你的原始数据里  month 应该是个数字？遍历一遍数据，把数字改为字符串，去掉那个 scale 定义就好。

**Comment by fundon** [comment]
@leungwensen 谢谢，解决了。

另外一个问题，上面有连续的 4 张图表，他们公用一个 X 轴，我在想，鼠标移动的时候，4 个图表如何同时显示 Tooltip？

**Comment by leungwensen** [comment]
目前一个 chart 上 tooltip 只会有一个实例，但多个 view 或者 geom 的内容都会有的： https://antv.alipay.com/zh-cn/g2/3.x/demo/line/series.html
