### ISSUE TITLE
tooltip css属性无法实现动态更新，望下版本可优化此功能

### ISSUE THREAD

**Issue by 18211365467** [antvis/G2#5643]
### AntV Open Source Contribution Plan（可选）

- [X] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

中级任务

### 任务介绍

期望修改 tooltip css 的时候，可以实现样式的更新。

### 参考说明

相关代码：

https://github.com/antvis/G2/blob/v5/src/interaction/tooltip.ts#L91
https://github.com/antvis/G2/blob/v5/src/interaction/tooltip.ts#L133

**Comment by pearmini** [comment]
相关代码：

- https://github.com/antvis/G2/blob/v5/src/interaction/tooltip.ts#L91
- https://github.com/antvis/G2/blob/v5/src/interaction/tooltip.ts#L133

**Comment by BENcorry** [comment]
【BENcorry 认领】

**Comment by BENcorry** [comment]
> 相关代码：
> 
> * https://github.com/antvis/G2/blob/v5/src/interaction/tooltip.ts#L91
> * https://github.com/antvis/G2/blob/v5/src/interaction/tooltip.ts#L133

目前修改CSS的case是什么样子的，通过如下代码配置，然后render么，还是什么样的方式
```
chart.interaction('tooltip', {
      shared: true,
      css: {},
    });
```

**Comment by pearmini** [comment]
@BENcorry 就是你所说的样子：

```js
chart.interaction('tooltip', {
  shared: true,
  css: {}, // 动态修改 css
});
```

**Comment by BENcorry** [comment]
> @BENcorry 就是你所说的样子：
> 
> ```js
> chart.interaction('tooltip', {
>   shared: true,
>   css: {}, // 动态修改 css
> });
> ```

我看代码的流程，只要使用了chart.render()方法，就会触发createTooltip的方法，但是如果不使用render方法去渲染，css的配置就不会生效，但是官方文档中，只要配置了interaction的交互，那么交互相关的配置就会变动

所以现在的问题应该是在不手动执行render的情况下，需要配置css配置生效，我这样理解应该没问题吧

**Comment by pearmini** [comment]
这个问题我思考一下，我看看当时的诉求是什么

**Comment by pearmini** [comment]
@BENcorry 思考了一下，只要调用 render 之后 css 可以更新的话，应该就是满足需求的。抱歉发布了一个无效任务，你可以去这里：https://github.com/orgs/antvis/projects/25 挑选更多任务。

@18211365467 这里修改了之后需要调用 `chart.render` 就可以更新 css 样式。

**Comment by BENcorry** [comment]
> @BENcorry 思考了一下，只要调用 render 之后 css 可以更新的话，应该就是满足需求的。抱歉发布了一个无效任务，你可以去这里：https://github.com/orgs/antvis/projects/25 挑选更多任务。
> 
> @18211365467 这里修改了之后需要调用 `chart.render` 就可以更新 css 样式。

好勒，问题大不，OSCP相关G2的问题还是比较少的，我还是去看看有没有感兴趣的bug或者feature吧

**Comment by pearmini** [comment]
嗯嗯，我一会儿去多整理一点任务，你再看看！
