### ISSUE TITLE
您好，问下G2是否可用在商业用途上

### ISSUE THREAD

**Issue by Seagant** [antvis/G2#5674]
您好，问下G2是否可用在商业用途上？在网站哪里可以看见？谢谢~

**Comment by pearmini** [comment]
可以的，G2 的[协议](https://github.com/antvis/G2/blob/v5/LICENSE)是 MIT。

**Comment by Seagant** [comment]
你发过来的邮件怎么都是乱码啊，什么都看不到，再发一次吧。

**Comment by Seagant** [comment]
> 可以的，G2 的[协议](https://github.com/antvis/G2/blob/v5/LICENSE)是 MIT。

好的！感谢！
