### ISSUE TITLE
g2的官网使用体验差

### ISSUE THREAD

**Issue by Gpia** [antvis/g2#568]
首先，我觉得g2的官网，无法快速的概览一个图表的完整配置项，文档的搜索体验也一般。和echarts, highcharts的官网差距明显。

首先不管组件好不好，我使用的时候第一个接触的肯定是配置，一个完整的图支持哪些配置项，配置项取值是什么，我需要快速知道，这直接关系到使用体验。

g2的官网对配置的友好程度处于一个较低的水平。虽然有很多的demo，但是demo也只会用到部分配置，不是全的。

**Comment by leungwensen** [comment]
G2 的实现思路和 xxCharts 不太一样，不是以某个图表类和它的“配置项”为核心的，而是力求实现一套“数据驱动的高交互图形语法”。图形语法这个理论官网有个简单的介绍： https://antv.alipay.com/zh-cn/g2/3.x/tutorial/the-grammar-of-graphics.html

官网文档目前的确不够全面，你提到的类似 echarts 和 highcharts 等能快速定位图表对应配置以及取值的文档功能我们会认真考虑，在后续网站体验改进上体现

**Comment by leungwensen** [comment]
@dxq613 @Jason-Zhangine 我们看看六月中旬 3.1 发布后到六月底能不能改善一下

**Comment by perfect711** [comment]
IE11的体验很崩溃。最简单的pie都不能正常体验。本来已经引入到项目中，测了IE兼容性，准备放弃了。

**Comment by perfect711** [comment]
推荐的Viser，官网使用IE打开，也是不友好，有很多问题

**Comment by perfect711** [comment]
建议全面测试并修复官网提供的demo兼容性。不然使用者心里完全没有底~用呢不用呢行呢不行呢？

**Comment by dxq613** [comment]
网站 ie11 的兼容性是否因为 es6 写法导致的，按说 g2 本身对 ie11 的兼容性不应该有问题。

**Comment by leungwensen** [comment]
@perfect711 能截个图吗？

**Comment by dxq613** [comment]
等待新官网，今年 11.22 会发布。
