### ISSUE TITLE
折线图 line 的默认主题样式中增加 lineCap: 'round'

### ISSUE THREAD

**Issue by hustcc** [antvis/G2#5685]
### AntV Open Source Contribution Plan（可选）

- [x] 我同意将这个 Issue 参与 OSCP 计划

### Issue 难度

中等难度

### 任务介绍

主要有两个问题：

1. 当数据只有一条的时候，当前 lineCap 默认为 butt，为导致看不到任何图形，设置为 round，可以默认一个半径为 lineWidth 的远点。
2. 数据差异比较大的时候，round 不会显示出毛刺。

```ts
.style('lineCap', 'round')
```

主要修改方式，是在 theme 中入默认配置项。

### 参考说明

调式代码

```ts
import { Chart } from "@antv/g2";

const chart = new Chart({
  container: "container",
  autoFit: true
});

chart
  .line()
  .data([{ genre: 'Sports', sold: 100 }])
  .encode("x", "genre")
  .encode("y", "sold")
  .style('lineWidth', 4)
//  .style('lineCap', 'round')

chart.render();
```

![image](https://github.com/antvis/G2/assets/7856674/ac7d79dd-e203-45f2-84c0-7552d818d34a)

**Comment by liangchaofei** [comment]
[liangchaofei 认领]

**Comment by iamzone** [comment]
【iamzone 认领】

**Comment by pearmini** [comment]
已经完成：https://github.com/antvis/G2/pull/5717
