### ISSUE TITLE
4.x版本，在外部容器设置transform:scale(x.x)缩放之后，鼠标交互都会有偏移

### ISSUE THREAD

**Issue by jia1372100759** [antvis/G2#5690]
### 问题描述

在外部容器设置transform:scale(x.x)缩放之后，鼠标交互都会有偏移

### 重现步骤

1. 引入antv/g2，4.2.7版本
2. 随便创建一个有鼠标交互的图表
3. 在这个图表的图表容器外面设置样式style: transform: scale(2)
4. 现在在组件上进行交互，发现出现位置偏移

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by pearmini** [comment]
添加 supportCSSTransform 配置：`new Chart({ supportCSSTransform: true })`
