### ISSUE TITLE
使用分组柱状图，单条数据引起的渲染X轴位置不正确的问题

### ISSUE THREAD

**Issue by Jarvis-Q** [antvis/g2#57]
Geom使用intervalDodge(分组柱状图)时，X轴的tick分组使用'cat'类型时，如果传入的数组长度为1时，渲染的柱状位置没有映射到cat类型values对应的下标索引位置上。

示例：http://codepen.io/anon/pen/yVrOmX

**Comment by dxq613** [comment]
最新的 3.0 中已经解决，11月22号发布
