### ISSUE TITLE
手机调用html页面。

### ISSUE THREAD

**Issue by zhangjiaxin281** [antvis/g2#570]
当手机调用写好的html数据量大的时候x数据会有折叠 

![lalpbbcc1zgin3fnatdnbqa_1280_720 png_620x10000q90g](https://user-images.githubusercontent.com/11827996/38228128-5c2bfcc6-3734-11e8-801b-68f8738af48c.jpg)

能否跟amChar有个缩放尺，来放大缩小在手机上自由大小查看。
![ladpbbcc1zghcirnawznbba_1040_780 jpg_620x10000q90g](https://user-images.githubusercontent.com/11827996/38228182-a4cd5c18-3734-11e8-9f0f-c085aefa71b7.jpg)

**Comment by leungwensen** [comment]
可以用 slider： https://github.com/antvis/g2-plugin-slider

https://antv.alipay.com/zh-cn/gallery/g2/area-large.html
