### ISSUE TITLE
官网新增有中心文本的饼图案例

### ISSUE THREAD

**Issue by pearmini** [antvis/G2#5705]
### AntV Open Source Contribution Plan（可选）

- [X] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

初级任务

### 任务介绍

在官网上新类似如下一个 demo，并且放在饼图的分类下：

![image](https://github.com/antvis/G2/assets/49330279/eb0b59f1-7e5c-45a0-a9af-bb953546522c)

### 参考说明

- 测试案例的：[population2015-interval-donut-text-annotation-inset](https://github.com/antvis/G2/blob/b41c36b0ab6437cb0b060d6fc8a3f43f58950b44/__tests__/plots/static/population2015-interval-donut-text-annotation-inset.ts#L4)

**Comment by iamzone** [comment]
【iamzone 认领】
