### ISSUE TITLE
雷达图，配置 innerRadius 时，geom 为 area 时，area 的填充没有镂空显示，g2 2.x 是好的。

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#573]
如题，polay 坐标系下的雷达面积图，配置 innerRadius 时，geom 为 area 时，area 的填充没有镂空显示，g2 2.x 是好的。

3.x效果
![image](https://user-images.githubusercontent.com/3838676/38286959-acc1f21e-37fa-11e8-9987-aa7aa0ec3f16.png)

2.x 效果

![image](https://user-images.githubusercontent.com/3838676/38286932-8e9097be-37fa-11e8-821c-82d7f4ce9644.png)

**Comment by leungwensen** [comment]
3.0.7
