### ISSUE TITLE
堆叠柱状图，排序

### ISSUE THREAD

**Issue by i-smile** [antvis/g2#574]
* **3.0.5-beta.1**:
* **PC**:

柱状堆叠图，现在每一个堆叠行，行内的顺序是按照图例来的（图例顺序的正序或者倒序），且所有行都相同。但是我有一个需求，希望每一个堆叠行都是按行内从大到小（或从小到大）排序，即各个堆叠行的排序不再按照图例来了。这样的好处是可以一目了然的看清每个堆叠行内，分量比重大小。
我使用echart的时候也做过这个，它虽然没有自己提供，但是它有自定义绘制的功能，我还是可以实现的，G2上，我找不到方法～

**Comment by stanleyxu2005** [comment]
@leungwensen dataset很强大，可以提供各种数据清洗补全和聚合的功能。我想问的时候，使用dataset之后，内部会有一个叫origin还有一个叫rows。这看上去不是一个（虚拟的）逻辑计算关系，而是实实在在在dataset内部存了2份数据。这个在数据量上去的情况下，会不会有性能上的担忧啊。尤其是chart有destroy方法，dataset好像没有吧。

**Comment by leungwensen** [comment]
存两份数据是出于性能的考虑，否则每次取数据都需要重新运算。小数据量不用担心性能问题，相信 V8 的 GC 就好。大数据量（百万级？）后面我们会有优化，针对场景做 GPU 运算、web worker 甚至 webassembly。现在还没有发正式版本，有兴趣可以一起搞  https://github.com/antvis/data-set

**Comment by lx70770** [comment]
@i-smile hi  请问您如何解决堆叠柱状图升序或者降序排序的啊？

**Comment by dxq613** [comment]
堆叠柱状图有个参数 reverseOrder 来控制顺序

```js
chart.interval()
    .position('year*percent')
    .color('country')
    .adjust({type: 'stack', reverseOrder: false});
```

更多可以参考：https://www.yuque.com/antv/g2-docs/api-geom#adjust

**Comment by alonePedestrian** [comment]
> 堆叠柱状图有个参数 reverseOrder 来控制顺序
> 
> ```js
> chart.interval()
>     .position('year*percent')
>     .color('country')
>     .adjust({type: 'stack', reverseOrder: false});
> ```
> 
> 更多可以参考：https://www.yuque.com/antv/g2-docs/api-geom#adjust

分面图数据格式不是很统一会导致xy同时反转怎么解决？

**Comment by sexxOyxin** [comment]
chart.interval()
    .transform({"type": "stackY"})
我通过这种方法解决问题了
