### ISSUE TITLE
翻译官网进阶主题部分

### ISSUE THREAD

**Issue by pearmini** [antvis/G2#5744]
### AntV Open Source Contribution Plan（可选）

- [X] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

中级任务

## 目标

翻译官网**进阶主题下**的所有文章：https://g2.antv.antgroup.com/manual/extra-topics/use-in-framework ，从“在框架中使用”一直到“服务端渲染”。

## 方法

使用 translate 脚本翻译文章，并且人工校对（语句是否通顺，大小写是否合理）

如果希望翻译 ["开始使用"](https://g2.antv.antgroup.com/en/manual/introduction/getting-started)，可以输入如下的命令：

```bash
$ npx translate -d site/docs/manual/introduction/getting-started.zh.md
```

然后对生成的 `getting-started.en.md` 的内容进行校对，如果没有问题提 PR 即可。目前 `site/docs/manual/` 下的文档都是需要翻译的，命令格式如下：

```bash
$ npx translate -d path
```

## Deadline

**2023.11.13 日之前**

## 说明

- 可以提交多个 PR 完成任务，比如一个 PR 对应一篇或者多篇文章。
- 可以多个人（最多两个人）同时完成任务，每个人都算完成了中级任务。需要在这个 issue 下面协商各自翻译的部分。

**Comment by Runtus** [comment]
【Runtus 认领】

**Comment by Exlau** [comment]
Exlau 认领

**Comment by pearmini** [comment]
@Runtus @Exlau  一共有10篇，你们一人负责5篇如何？

- Runtus：“在框架中使用” ～ “自定义”
- Exlau：“按需打包” ～ “服务端渲染”

**Comment by Runtus** [comment]
好的，收到

**Comment by Exlau** [comment]
@pearmini  这似乎是“进阶主题”而不是“核心概念”
<img width="338" alt="image" src="https://github.com/antvis/G2/assets/56985055/89c02322-fc53-4fea-b752-33c8665e109a">

**Comment by pearmini** [comment]
> 这似乎是“进阶主题”而不是“核心概念”

@Exlau 我修改一下 issue 的描述。

**Comment by pearmini** [comment]
closed by:

- https://github.com/antvis/G2/pull/5781
- https://github.com/antvis/G2/pull/5771

**Comment by pearmini** [comment]
@Exlau @Runtus 

感谢对 G2 对贡献！欢迎加入下面的群，进一步贡献和了解更多：

<img src="https://github.com/antvis/G2/assets/49330279/fcee44fa-bc79-4f13-b1eb-12fa94164606" width=240 />
