### ISSUE TITLE
数据比较小时 坐标轴范围不能自适应

### ISSUE THREAD

**Issue by huanle0610** [antvis/g2#576]
数据是这样的, 如果数据比较大显示正常, 数据小时 就是一条水平线了.
`{ month: 'Jan', Tokyo: 3.9e+24, London: 3.9e-25 },`

![image](https://user-images.githubusercontent.com/953028/38356084-561cd9d6-38f1-11e8-991a-e65e28690082.png)
![image](https://user-images.githubusercontent.com/953028/38356100-6603ea24-38f1-11e8-9b20-390389cd2e38.png)

[CodePen 链接](https://codepen.io/huanle0610/pen/oqPQzx?editors=0010)

**Comment by stanleyxu2005** [comment]
快接近于0的数据显示在坐标轴上没有什么问题啊。你预期应该是什么样子的？

**Comment by huanle0610** [comment]
如果两条线，差值非常大。 数据很小的快接近于0是正常的。如果只是一条线数据都接近0，还是要显示出数据之间的差距。


![image](https://user-images.githubusercontent.com/953028/38630849-a6b7d6b8-3dea-11e8-99fa-63dde738f7cb.png)
[CodePen 链接](https://codepen.io/huanle0610/pen/ZxPNBg)
怎样写可以实现类似的操作体验呢？

**Comment by leungwensen** [comment]
我没看出来 g2 和 highcharts 这两个 demo 的差异在哪里。。。如果没有更多信息提供，issue 会在一星期内关闭

**Comment by huanle0610** [comment]
放到一个图里了, 这样对比明显. 两个控件给的数据是一样的, 不知道应该设置什么参数？
![screenshot from 2018-08-26 08-06-57](https://user-images.githubusercontent.com/953028/44623659-1ced9e80-a907-11e8-9241-b0ad504e57bd.png)

[CodePen 链接](https://codepen.io/huanle0610/pen/MqKBxO)

**Comment by leungwensen** [comment]
目前可以通过设置 scale 来解决这个问题，后面我们会改进一下 nice 算法，处理小数类 scale 计算的问题。多谢反馈！

```js
  chart.source(dv, {
    month: {
      range: [ 0, 1 ]
    },
    temperature: {
      min: 0,
      max: 2e-24,
      nice: false,
    }
  });
```

**Comment by dxq613** [comment]
4.0 中进行改造！
