### ISSUE TITLE
G2 slider组件在移动端设备上不能被滑动

### ISSUE THREAD

**Issue by zhouyanggodking** [antvis/g2#577]
* **G2 Version**: 3.0
* **Platform**: iOS
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

G2 slider组件在移动端设备上不能被滑动。

重现步骤： 用手机访问https://antv.alipay.com/zh-cn/g2/3.x/demo/index.html， 找到股票示例并尝试滑动滑块。

**Comment by suiyi8760** [comment]
+1 做响应式的管理系统时非常不方便,没理由再特意引入f2吧...

**Comment by leungwensen** [comment]
移动端的支持会在 3.1 版本之后逐步做上去。如果想要比较好的移动端体验，目前的建议就是使用 f2

**Comment by dxq613** [comment]
在 4.0 版本支持。
