### ISSUE TITLE
按需加载

### ISSUE THREAD

**Issue by lchunxiu** [antvis/g2#579]
你好，我们项目只有一个地方用到g2，但是g2的文件占比16.6%,请问如何实现部分文件加载？
下面是引入方式：
`import {Stat} from 'g2'`

**Comment by leungwensen** [comment]
你好，Stat 是 2.x 暴露的接口，2.x 后续不会做打的改动了，如果要使用按需加载特性，请等待 3.1 的 beta 版本

**Comment by lchunxiu** [comment]
好的，幸苦你们啦！

**Comment by Airkro** [comment]
tooltip 和 legend 能否也进一部分离呢
