### ISSUE TITLE
legend、slider、scrollbar 涉及到鼠标拖拽的，都需要设置鼠标样式为手型

### ISSUE THREAD

**Issue by hustcc** [antvis/G2#5791]
### AntV Open Source Contribution Plan（可选）

- [X] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

中级任务

### 任务介绍

![image](https://github.com/antvis/G2/assets/7856674/ba305d4e-c32a-4d63-8ff2-67a1bfe66cb8)

相关组件的鼠标样式需要设置为手型，需要在代码中找到对应的组件渲染的时候，加上样式，有可能需要到 [component](https://github.com/antvis/component) 中去修改。

```ts
{
  cursor: 'pointer',
}
```

### 参考说明

具体调式 DEMO：

- scrollbar：https://g2.antv.antgroup.com/zh/examples/component/scrollbar/#scrollbar
- legend：https://g2.antv.antgroup.com/zh/examples/component/legend/#continuous
- slider https://g2.antv.antgroup.com/zh/examples/annotation/line/#quadrant-scatter

**Comment by Runtus** [comment]
【Runtus 认领】

**Comment by Runtus** [comment]
@hustcc  您好，我想确认下，现在是需要把 `cursor: grab` 改成 `cursor: pointer`的形式是吗？ 
除此之外，**slider**中不同`MouseEvent`以及位置的不同它的`cursor`样式也不同，这种的话，是修改哪一部分呢？

**Comment by Runtus** [comment]
@hustcc 
我的操作系统是Macos 14，浏览器是Chrome - 118.0.5993.117
* 下面这张图是 scrollbar可拖拽控件的`cursor`样式
<img width="869" alt="image" src="https://github.com/antvis/G2/assets/48038769/2f9e0722-580d-44c0-a6dc-4a72ede66174">
* 下面三张图是 slider 里的几种不同的`cursor`样式
<img width="927" alt="image" src="https://github.com/antvis/G2/assets/48038769/b30a8629-6498-454a-9cd4-3fe067edc486">
<img width="1028" alt="image" src="https://github.com/antvis/G2/assets/48038769/c5f14ffd-6c0d-4b6a-a157-ee9472225255">
<img width="854" alt="image" src="https://github.com/antvis/G2/assets/48038769/409fad19-65c1-4813-8556-a98f13e31c4e">

**Comment by hustcc** [comment]
slider 确实在我这里是 ok 的，那 slider 不用处理。但是 scrollbar 和 legend 的在我这里样式不对。

**Comment by Runtus** [comment]
明白了，刚刚看了下，legend样式确实不对，scrollbar的样式只有在`click`后才会有`grab`的样式，我这里就对这两部分进行修改，感谢说明

**Comment by Runtus** [comment]
@hustcc  您好，我这边改好后，是直接给[component](https://github.com/antvis/component)提PR吧，这两处`cusror: pointer`修复我都没有改`G2`中的内容。
