### ISSUE TITLE
自定义形状为circle时，画出来的结果是椭圆

### ISSUE THREAD

**Issue by stanleyxu2005** [antvis/g2#580]
* **G2 Version**: 3.0.0-beta6
* **Platform**: Windows 7 (Chrome Stable)
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

我在做二次开发的时候，发现自定义形状为圆点的时候，画出来的是椭圆。（见图中半透明色的几个椭圆）
![dashing-vis/apple_watch_bar_chart](https://user-images.githubusercontent.com/5162687/38466097-8534fab6-3b56-11e8-843e-a082061f775a.png)

我自己做了一些改动，包括图表的宽度
```
    G2.Global.widthRatio.column = 1
/** Rounded bar looks like French baguette */
    G2.Shape.registerShape('interval', 'baguette', {
      draw(cfg, container) {
        const p0 = this.parsePoint(cfg.points[0])
        const p2 = this.parsePoint(cfg.points[2])
        const r = cfg.size / 2
        const h = p0.y - p2.y
        const w = p2.x - p0.x
        if (h < cfg.size) {
          return container.addShape('circle', {
            attrs: {
              x: p0.x + r,
              y: p0.y - r,
              r: r,
              fill: cfg.color,
              opacity: h === 0 ? .4 : 1
            }
          })
        }

        const p1 = this.parsePoint(cfg.points[1])
        return container.addShape('rect', {
          attrs: {
            x: p1.x,
            y: p1.y,
            width: cfg.size,
            height: h,
            radius: r,
            fill: cfg.color
          }
        })
      }
    })
```
基本思路是参考的https://antv.alipay.com/zh-cn/gallery/g2/column-rounded.html
```
// 省略重复部分，仅保留我修改的部分
        chart.interval()
          .position('x*y')
          .color('rgb(159,254,0)')
          .size(14)
          .shape('baguette')
```
如果把size换成4，几乎看不出椭圆，可以接受，但是变成14之类的大数字，就特别明显。
![image](https://user-images.githubusercontent.com/5162687/38466104-a01b6d2e-3b56-11e8-8df7-5efabda8f555.png)

**Comment by leungwensen** [comment]
给个 codepen 链接？我这边设置到 64 也没有问题啊

![image](https://user-images.githubusercontent.com/1655789/38466208-2509924e-3b58-11e8-8538-bb1744e8f8c6.png)

**Comment by stanleyxu2005** [comment]
CodePen https://codepen.io/stanleyxu2005/pen/jzQjMG

原因找到了，我是在angular里面实现的。图表渲染的时候，其实div的大小并非最终的大小，所以实际渲染的DIV大小和放到CodePen上的时候是不一样的。
我现在在配置里面把forceFit设置成了false，并在渲染之后调用一次chart.forceFit()解决了问题

**Comment by stanleyxu2005** [comment]
Codepen https://codepen.io/stanleyxu2005/pen/jzQjMG

感觉可能是我的angular 1.6和bootstrap在初始化div时候计算div宽度有问题吧。我现在用非angular方式实现，就没有这个问题。（就是图表如果超过了设置宽度，会自动张开，不能只能折叠）

**Comment by stanleyxu2005** [comment]
顺便上个图 

![image](https://user-images.githubusercontent.com/5162687/38469924-dbb27714-3b8e-11e8-8905-d28e0c71c7b3.png)
