### ISSUE TITLE
分组柱状图设置size回调之后，之前设置的柱间距就不起作用了

### ISSUE THREAD

**Issue by completeAutumn** [antvis/g2#581]
本来是想通过size回调函数控制柱状图的最大宽度，结果发现.adjust设置的marginRatio不起作用了，宽度过大时柱子还会重叠

**Comment by MrChen2016-08-27** [comment]
我也遇到了这个问题，宽度默认的label文字会重叠，宽度设置了， 柱状之间会重叠，目前有解决方案了吗

**Comment by dxq613** [comment]
marginRatio 是跟整个分类占比宽度相关的，这个放到 #474 里面一起讨论吧。
