### ISSUE TITLE
[V5] 组合图表(`line` `point`) 在设置缩略轴（`slider`） 后拖动缩略轴 `tooltip` 失效

### ISSUE THREAD

**Issue by codesyofo** [antvis/G2#5816]
### 问题描述

1.拖动左侧缩略轴，右侧不动
2.查看 `tooltip` 无效果

![image](https://github.com/antvis/G2/assets/49975575/8b0428d6-29f2-4087-9b2d-1330f9e49cf7)

无效果图
![image](https://github.com/antvis/G2/assets/49975575/d7cadeda-13b0-48c3-80d5-18aa7fefa893)

### 重现链接

https://codesandbox.io/s/flamboyant-frost-7wf2n9

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by pearmini** [comment]
这个 Bug 有点奇怪，也许和 clipPath 有关。
