### ISSUE TITLE
【v5】极坐标下，添加纹理回导致交互错乱

### ISSUE THREAD

**Issue by ai-qing-hai** [antvis/G2#5844]
### 问题描述

![image](https://github.com/antvis/G2/assets/65594180/5d30f6fa-5dd4-4344-aadb-498856ccf0df)

### 重现链接

https://g2.antv.vision/examples/style/pattern#lines-pattern

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by pearmini** [comment]
@xiaoiver 这个感觉是一个拾取错误的问题？

**Comment by xiaoiver** [comment]
> @xiaoiver 这个感觉是一个拾取错误的问题？

确实，我把 pattern 去掉还是存在

**Comment by pearmini** [comment]
G2 5.2.0 版本没有这个问题了，关闭这个 issue
