### ISSUE TITLE
如何移除mark area的stroke的左下右三边？

### ISSUE THREAD

**Issue by taoliujun** [antvis/G2#5865]
### 问题描述

![image](https://github.com/antvis/G2/assets/5689134/50b74bfc-f51b-45d6-8ec5-a609e30ba7cd)

如上图中，给mark area配置了stroke，area的四周都给描边了。但是希望只要上边的描边，不需要左下右边的描边。
大概需要如下的效果（用mark line模拟的，和area不能紧紧贴合，可能留有缝隙）。

![image](https://github.com/antvis/G2/assets/5689134/4871c940-da4d-49c6-9c60-82ce9e45741c)

### 任务类型

初级任务

**Comment by hustcc** [comment]
确实是一个好问题。我们开始设计的时候，想着如果需要有描边的面积图，是使用 area + line 组合的方式。参考这个 DEMO：https://g2.antv.antgroup.com/examples/general/area/#area-gradient

保留 stroke 是原始的含义。

**Comment by pearmini** [comment]
> 用mark line模拟的，和area不能紧紧贴合，可能留有缝隙

@taoliujun 这个缝隙在哪里？

**Comment by taoliujun** [comment]
> > 用mark line模拟的，和area不能紧紧贴合，可能留有缝隙
> 
> @taoliujun 这个缝隙在哪里？

line和area的边的贴合不紧密的情况。两者都设置了`.encode('shape', 'smooth')`。

![image](https://github.com/antvis/G2/assets/5689134/4787e146-f9ba-45d4-83b7-ce694026e149)
![image](https://github.com/antvis/G2/assets/5689134/1c72523c-1518-460a-a92c-d043db1fed62)

**Comment by taoliujun** [comment]
@pearmini 我不清楚curve的背景，不过我今天试试。

**Comment by taoliujun** [comment]
认领

**Comment by pearmini** [comment]
closed by: https://github.com/antvis/G2/pull/5877
