### ISSUE TITLE
Request for 'jitterY'

### ISSUE THREAD

**Issue by YiSiWang** [antvis/g2#5876]
## AntV Open Source Contribution Plan

- [X] 我同意将这个 Issue 参与 OSCP 计划

### 问题描述

为什么  transform 只有 jitterX 没有 jitterY ？（而且也没法用 jitter 实现 jitterY）
用场景：横向条形图和散点图 画在同一视图中，散点图被 coordinate 交换 XY ，需要用 jitterY 进行扰动

### Issue 类型

初级任务

### 任务描述

添加 jitterY

### 参考 

JitterX 的实现

**Comment by pearmini** [comment]
要不来贡献一下，很简单的，可以参考 [jitterX](https://github.com/antvis/G2/blob/v5/src/transform/jitterX.ts)

**Comment by kun6696** [comment]
认领

**Comment by kun6696** [comment]
![image](https://github.com/antvis/G2/assets/143773015/febde2ff-a2bd-4b09-ac75-4c6a3498669f)
![image](https://github.com/antvis/G2/assets/143773015/168cafd8-b452-446b-920a-43eadc9b549e)
![image](https://github.com/antvis/G2/assets/143773015/959c5921-f79c-4164-94d8-8a548b7781c8)
我看jitterX 也能实现y方向上面的扰动，是否有增加这个参数 算冗余？

**Comment by pearmini** [comment]
@kun6696 嗯嗯，我最开始也是这么想的，所以没有加 jitterY。但是同时绘制多个 Mark 的时候可能就有问题了，比如 issue 描述里面说的：

> 横向条形图和散点图 画在同一视图中，散点图被 coordinate 交换 XY ，需要用 jitterY 进行扰动

**Comment by kun6696** [comment]
@YiSiWang   可以把你这个issue例子代码贴出来嘛
