### ISSUE TITLE
uniapp 使用V3版本android兼容问题 3.8.10

### ISSUE THREAD

**Issue by paddingH** [antvis/G2#5878]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[alipays://platformapi/startapp?appId=2021004115681233&page=pages/index/index&query=token=token&certNo=91610323MA6XA2H575](alipays://platformapi/startapp?appId=2021004115681233&page=pages/index/index&query=token=token&certNo=91610323MA6XA2H575)

### Steps to reproduce
界面访问

| Environment | Info |
|---|---|
| g2 | 4.0.13 |
| System | android |
| Browser | - |

**Comment by hustcc** [comment]
有具体的报错信息吗 ?
