### ISSUE TITLE
饼图的data数据为0，图表不显示

### ISSUE THREAD

**Issue by zhaoyanbei** [antvis/g2#589]

**Comment by zhaoyanbei** [comment]
data: [
            {name: 'Microsoft Internet Explorer', value: 0 },
            {name: 'Chrome', value: 0},
            {name: 'Firefox', value: 0.0},
            {name: 'Safari',  value: 0},
            {name: 'Opera', value: 0},
            {name: 'Proprietary or Undetectable', value: 0}
          ],

**Comment by zhaoyanbei** [comment]
@leungwensen

**Comment by leungwensen** [comment]
都是 0 的话，的确没法显示的，一个扇形角度为 0 是没法画出来的。。。

**Comment by leungwensen** [comment]
![image](https://user-images.githubusercontent.com/1655789/38714830-9b2e39f6-3f0a-11e8-9aae-c511c938f33c.png)


比例为 0 的扇形只能是一根线了

**Comment by jerryyan1990** [comment]
全为0的话图都没有了，echarts全为0就会等分，然后数值显示0
