### ISSUE TITLE
迁移 4.0 简单面积图

### ISSUE THREAD

**Issue by pearmini** [antvis/G2#5897]
### AntV Open Source Contribution Plan（可选）

- [X] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

初级任务

### 任务介绍

将以下 4.0 面积图迁移到 5.0 的案例里面：

- https://github.com/antvis/G2/blob/master/examples/area/basic/demo/basic.ts
- https://github.com/antvis/G2/blob/master/examples/area/basic/demo/with-negative.ts
- https://github.com/antvis/G2/blob/master/examples/area/stacked/demo/stacked.ts
- https://github.com/antvis/G2/blob/master/examples/area/stacked/demo/percentage.ts
- https://github.com/antvis/G2/blob/master/examples/area/range/demo/range.ts 参考这个[例子](https://g2.antv.antgroup.com/examples/annotation/line/#anomaly-area-line)

### 参考说明

- 动机和注意事项：https://github.com/antvis/G2/issues/5894
- 相关 PR：https://github.com/antvis/G2/pull/5893

**Comment by foolvip** [comment]
认领面积图

**Comment by foolvip** [comment]
文件命名规则有要求吗，basic文件有的叫简单图有的叫基础图，有要求吗

**Comment by foolvip** [comment]
<img width="390" alt="image" src="https://github.com/antvis/G2/assets/63231148/0bc881b9-71e7-4f1a-b320-8daac2685985">

**Comment by pearmini** [comment]
你需要 fork 一下 G2 仓库：

<img width="1433" alt="image" src="https://github.com/antvis/G2/assets/49330279/dc63c6e8-086f-4faf-8f51-a61ef95775bb">
