### ISSUE TITLE
迁移 4.0 简单直方图

### ISSUE THREAD

**Issue by pearmini** [antvis/G2#5898]
### AntV Open Source Contribution Plan（可选）

- [x] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

初级任务

### 任务介绍

将以下 4.0 直方图迁移到 5.0 的案例里面：

- https://github.com/antvis/G2/blob/master/examples/column/histogram#histogram
- https://github.com/antvis/G2/blob/master/examples/column/histogram#histogram 把数据分成两份，绘制一个堆叠直方图

### 参考说明

- 动机和注意事项：https://github.com/antvis/G2/issues/5894
- 相关 PR：https://github.com/antvis/G2/pull/5893

**Comment by sunsunmonkey** [comment]
认领

**Comment by hustcc** [comment]
@sunsunmonkey 哈喽，还有进展吗？

**Comment by sunsunmonkey** [comment]
@hustcc 已提pr

**Comment by hustcc** [comment]
@sunsunmonkey 太迅速了~

**Comment by sunsunmonkey** [comment]
之前有点小问题，搞忘了～
