### ISSUE TITLE
迁移 4.0 简单饼图

### ISSUE THREAD

**Issue by pearmini** [antvis/G2#5899]
### AntV Open Source Contribution Plan（可选）

- [x] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

初级任务

### 任务介绍

将以下 4.0 饼图迁移到 5.0 的案例里面：

- https://github.com/antvis/G2/blob/master/examples/pie/basic/demo/labelline.ts
- https://github.com/antvis/G2/blob/master/examples/pie/donut/demo/donut.ts
- https://github.com/antvis/G2/blob/master/examples/case/pie/demo/pie7.ts 参考这个[例子](https://github.com/antvis/G2/blob/80d268bb36ae3e0d1bb205a51d578684c2a354c7/__tests__/plots/api/chart-change-data-facet.ts#L4)

### 参考说明

- 动机和注意事项：https://github.com/antvis/G2/issues/5894
- 相关 PR：https://github.com/antvis/G2/pull/5893

**Comment by li1615882553** [comment]
认领
