### ISSUE TITLE
迁移 4.0 简单玫瑰图

### ISSUE THREAD

**Issue by pearmini** [antvis/G2#5900]
### AntV Open Source Contribution Plan（可选）

- [X] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

初级任务

### 任务介绍

将以下 4.0 玫瑰图迁移到 5.0 的案例里面：

- https://github.com/antvis/G2/blob/master/examples/column/stack/demo/wind-rose.ts
- https://github.com/antvis/G2/blob/master/examples/pie/rose/demo/rose.ts
- https://github.com/antvis/G2/blob/master/examples/pie/rose/demo/donut-rose.ts
- https://github.com/antvis/G2/blob/master/examples/column/stack/demo/polar-stack.ts 使用 [fold](https://g2.antv.antgroup.com/spec/data/fold) transform

### 参考说明

- 动机和注意事项：https://github.com/antvis/G2/issues/5894
- 相关 PR：https://github.com/antvis/G2/pull/5893

**Comment by the-lemonboy** [comment]
认领
