### ISSUE TITLE
迁移 4.0 简单径向图

### ISSUE THREAD

**Issue by pearmini** [antvis/G2#5902]
### AntV Open Source Contribution Plan（可选）

- [x] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

初级任务

### 任务介绍

将以下 4.0 径向图迁移到 5.0 的案例里面：

- https://github.com/antvis/G2/blob/master/examples/bar/basic/demo/radial-bar-with-background.ts
- https://github.com/antvis/G2/blob/master/examples/bar/stack/demo/stacked.ts
- https://github.com/antvis/G2/blob/master/examples/bar/basic/demo/radial-line.ts

### 参考说明

- 动机和注意事项：https://github.com/antvis/G2/issues/5894
- 相关 PR：https://github.com/antvis/G2/pull/5893

**Comment by LonelySnowman** [comment]
认领
