### ISSUE TITLE
tooltip 展示信息不完整

### ISSUE THREAD

**Issue by Song-yi-Tao** [antvis/g2#5906]
### 问题描述

绘制两条线图，其中一条数据不完整，在不完整数据的最后一个点 hover 时，鼠标放置于 crosshairs 右侧时 tooltip 展示信息不完全。

### 重现链接

https://codesandbox.io/s/unruffled-sammet-f49xwl?file=/index.ts

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

<img width="720" alt="image" src="https://github.com/antvis/G2/assets/58683056/ab9aa8b8-ec5a-4306-b8df-c739ad25ac3f">

**Comment by pearmini** [comment]
这个其实是复合预期的，因为鼠标在该条直线范围的之外了，就不会拾取到对应的数据。

**Comment by pearmini** [comment]
@Song-yi-Tao 因为在左侧的时候鼠标是在该条直线范围之内？
