### ISSUE TITLE
折线图单条数据不显示tooltip

### ISSUE THREAD

**Issue by 200-tonnage-boy** [antvis/G2#5909]
### 问题描述

折线图在只有一条数据时不显示tooltip

### 重现链接

https://codesandbox.io/p/sandbox/beautiful-cartwright-9zm59s

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

<img width="787" alt="image" src="https://github.com/antvis/G2/assets/40828298/43e5d80d-646c-453f-90b8-77f09eb03fcd">
<img width="594" alt="image" src="https://github.com/antvis/G2/assets/40828298/563dd90d-3cfa-4a04-956c-b72c8c7e5529">

**Comment by Runtus** [comment]
定位到问题了，大概就是tooltip显示的有个前提是hover在整个“有渲染图表”内，而这个“有渲染图表”是根据最左侧和最右侧的x坐标来决定的，当只有一个点时，图表的minX和maxX是同一个值，就导致hover上去始终判定为在“有渲染图表”外，无法显示tooltip。
现在有个疑问时，如果只有折线图只有一个点的时候，预期是hover到点上会有tooltip显示还是说在一个范围内hover就会显示对应点的tooltip？
[src/interaction/tooltip.ts](https://github.com/antvis/G2/blob/1a28b3d8182b75a25cccf12a6d2a1f9ff8096f6d/src/interaction/tooltip.ts#L528)

**Comment by pearmini** [comment]
可以算一个：初级任务
