### ISSUE TITLE
tooltip:show回掉函数数据与tooltip显示数据不一致

### ISSUE THREAD

**Issue by 200-tonnage-boy** [antvis/G2#5910]
### 问题描述

折线图数据点密集时出现tooltip:show回掉函数中e.data.data的数据和页面tooltip显示的数据不一致的问题

### 重现链接

https://codesandbox.io/p/sandbox/suspicious-margulis-kmq6mm

### 重现步骤

1. 触发一个数据点tooltip；
2. 左右轻微晃动鼠标；
3. 此时tooltip显示数据没有变，回掉数据与页面显示不一致

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

<img width="343" alt="image" src="https://github.com/antvis/G2/assets/40828298/a3296c1b-944f-473f-b1f5-2c1b44bc35a9">

**Comment by pearmini** [comment]
两者之间可能有一定的关系：https://github.com/antvis/G2/issues/5912

**Comment by pearmini** [comment]
相同的问题：https://github.com/antvis/G2/issues/5912
