### ISSUE TITLE
手动控制tooltip:show显示错误

### ISSUE THREAD

**Issue by 200-tonnage-boy** [antvis/G2#5912]
### 问题描述

对数据比较密集的折线图，使用chat.emit('tooltip:show')控制tooltip显示，tooltip显示的值与代码中触发tooltip:show的数据不一致；

### 重现链接

https://codesandbox.io/p/sandbox/youthful-monad-963crv

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

<img width="1108" alt="image" src="https://github.com/antvis/G2/assets/40828298/f3a874d4-b39f-42ee-91f5-fbd78678319d">

### 补充说明（可选）

1. 相同数据下，线图数据点密集（or 容器宽度小）时容易复现，宽度拉宽后问题有一定缓解

**Comment by pearmini** [comment]
可能和拾取有关系。

**Comment by HuangLiangchen** [comment]
src/interaction/tooltip.ts:714
![image](https://github.com/antvis/G2/assets/31841883/f81ad5e5-8d98-4b66-b704-6790e32c8745)

获取定位的方法调整下,因为showTooltip的bounding定位也是用的这个方法
![image](https://github.com/antvis/G2/assets/31841883/d4374a70-47c9-4960-8c5a-9c8d20323c09)
