### ISSUE TITLE
图表示例中无图表显示

### ISSUE THREAD

**Issue by ZhoBudweiser** [antvis/G2#5925]
### 问题描述

在参与贡献的过程中，已经在本地运行起了官网代码，”文档“、”选项“、”API“等都可以正常显示（”主题“中的图表能正常显示），但是图表示例中无任何图表显示，点击基础图表、数据分析等下拉菜单，只发生了下拉箭头变化，没有下拉选项弹出。
![image](https://github.com/antvis/G2/assets/96937007/c9620b09-ef48-4286-87d6-b49cbc0642ea)

### 重现步骤

```
$ git clone git@github.com:antvis/G2.git
$ cd G2
$ npm install
$ cd site
$ npm install
$ npm start
```

### 预期行为

预期应该有类似这样的界面
![image](https://github.com/antvis/G2/assets/96937007/8a2bfd49-5b5b-4b62-815f-c1f59f192cee)

### 平台

- 操作系统: Windows
- 网页浏览器: Google Chrome, Microsoft Edge

**Comment by pearmini** [comment]
控制台有报错吗？

**Comment by ZhoBudweiser** [comment]
> 控制台有报错吗？

这是控制台的输出，有一些警告
![image](https://github.com/antvis/G2/assets/96937007/ac5e1c33-bcfd-463a-ac83-20210667f8ff)

**Comment by ai-qing-hai** [comment]
@ZhoBudweiser 你在哪个分支？ 这边一般使用 tnpm 
![image](https://github.com/antvis/G2/assets/65594180/64d5e7c7-ccd7-488e-82d2-25b6ef2d7078)

**Comment by ZhoBudweiser** [comment]
> @ZhoBudweiser 你在哪个分支？ 这边一般使用 tnpm ![image](https://private-user-images.githubusercontent.com/65594180/290099112-64d5e7c7-ccd7-488e-82d2-25b6ef2d7078.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTA0MjgsIm5iZiI6MTcwMjQ1MDEyOCwicGF0aCI6Ii82NTU5NDE4MC8yOTAwOTkxMTItNjRkNWU3YzctY2NkNy00ODhlLTgyZDItMjViNmVmMmQ3MDc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA2NDg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmYWYzYjk5MWU0YjRkMGRlY2YzNzMzYjQ4MGUyODc5YmEzYjE4MzhmYTZmOTI3MTQ2NDIxOGUxMjM2MjFlYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BinpOoSZn1MKY0cPaWYZfsWnEeSO_HSFhqjOZI1M0bI)

我在v5分支，[贡献文档](https://github.com/antvis/g2/blob/v5/CONTRIBUTING.zh-CN.md)里用的是npm

**Comment by ai-qing-hai** [comment]
@ZhoBudweiser  那你 node 的版本是多少？ 这个也会有影响好像

**Comment by ZhoBudweiser** [comment]
> @ZhoBudweiser 那你 node 的版本是多少？ 这个也会有影响好像

是v18.17.0，看样子可能版本太高了？

**Comment by ai-qing-hai** [comment]
@ZhoBudweiser 说是 widnows 的原因。 但这边没有 这个系统，没法复现。

**Comment by ZhoBudweiser** [comment]
> @ZhoBudweiser 说是 widnows 的原因。 但这边没有 这个系统，没法复现。

好的，我换个系统试试

**Comment by ZhoBudweiser** [comment]
@ai-qing-hai 在wsl下重新部署了项目，问题解决了，确实是系统的问题

**Comment by pearmini** [comment]
这里先关闭了
