### ISSUE TITLE
多轴图需优化拾取策略，实现tootip完整的数据获取和展示

### ISSUE THREAD

**Issue by 18211365467** [antvis/G2#5930]
### 问题描述

![image](https://github.com/antvis/G2/assets/79558944/440c211f-1e3c-4f90-a365-c8be338dca5e)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by pearmini** [comment]
应该需要统一 tooltip 的拾取策略为工具拾取。

**Comment by Rockyxiansheng** [comment]
> 应该需要统一 tooltip 的拾取策略为工具拾取。

具体如何实现："应该需要统一 tooltip 的拾取策略为工具拾取"，这个bug很严重的，一直未解决

**Comment by Rockyxiansheng** [comment]
@pearmini 具体如何解决这个问题？官方也没有给一个很好的demo

**Comment by pearmini** [comment]
@Rockyxiansheng 

这个严格来讲不算一个是 bug，目前的展示是符合代码预期的，只是有优化的空间。出现问题的原因是 interval 是通过元素拾取，line 是通过数据拾取的，解决办法是修改底层代码，统一数据拾取。

这个问题优先级不高，短期内不一定会优化，感兴趣尝试提 PR 解决一下。

**Comment by pearmini** [comment]
> @Rockyxiansheng
> 
> 这个严格来讲不算一个是 bug，目前的展示是符合代码预期的，只是有优化的空间。出现问题的原因是 interval 是通过元素拾取，line 是通过数据拾取的，解决办法是修改底层代码，统一数据拾取。
> 
> 这个问题优先级不高，短期内不一定会优化，感兴趣尝试提 PR 解决一下。

有发现一些和这个问题相关的问题，我这个月底前把这些问题（包含这个问题）一起优化一下。
