### ISSUE TITLE
图例点击事件

### ISSUE THREAD

**Issue by YY88Xu** [antvis/G2#5937]
### 问题描述

如果不是自定义实现图例，图例的点击事件是什么呢？有没有暴露出来可以直接监听的呢？

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by pearmini** [comment]
```js
chart.on("component:click", ()=> {
  console.log('hello')
})
```

**Comment by denglijuan** [comment]
怎么阻止事件冒泡呀
