### ISSUE TITLE
axis坐标轴无法精确定位

### ISSUE THREAD

**Issue by BambooSword** [antvis/g2#595]
![image](https://user-images.githubusercontent.com/18547539/38844608-d24d3ff8-4226-11e8-98cb-9eea2e5342c0.png)

如图，我设定的 y轴的title无法精确定位，我想让它向上平移，但是好像没有办法可以做到，offset只能实现 相对于坐标轴垂直的平移

**Comment by leungwensen** [comment]
将增加两个方向的 title offset 定位。

**Comment by simaQ** [comment]
可以使用 chart.guide().text() 来实现
