### ISSUE TITLE
官网中，右侧边栏较长的页面，当翻到底部时，有文字遮盖问题

### ISSUE THREAD

**Issue by kun6696** [antvis/G2#5969]
### 问题描述

官网中，右侧边栏较长的页面，当翻到底部时，有文字遮盖问题

### 重现链接

https://g2.antv.antgroup.com/spec/overview

### 重现步骤

1、进入页面
2、翻到底部，到右侧边栏

### 预期行为

正常未被遮盖

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]

### 屏幕截图或视频（可选）

![2023-12-21 18 38 22](https://github.com/antvis/G2/assets/143773015/3061333d-cd94-4c7e-9b02-1c1ae90f9e16)

### 补充说明（可选）

![image](https://github.com/antvis/G2/assets/143773015/8dca05a7-3994-4834-9c6c-0144da39336f)

**Comment by pearmini** [comment]
@ai-qing-hai 有空可以看看这个问题
