### ISSUE TITLE
facet axis issue with transform: [{ type: 'transpose' }]

### ISSUE THREAD

**Issue by YiSiWang** [antvis/G2#5972]
### 问题描述

https://g2.antv.antgroup.com/zh/examples/composition/facet/#rect-row

在 point view 中添加 .coordinate({ transform: [{ type: 'transpose' }] }) 后，轴线展示不对👇🏻
<img width="1508" alt="image" src="https://github.com/antvis/G2/assets/20316342/70c9732f-63be-4b0e-861a-b396725b5df5">

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by pearmini** [comment]
这里可以自己通过   `.axis('x', () => null);` 去设置，参考 https://github.com/antvis/G2/blob/a63e388532d89b8e3b1ed57c83b9c290b8861187/src/composition/facetRect.ts#L315
