### ISSUE TITLE
几个问题：条形图如何隐藏x，y轴的标题名？如何在chart实例化后修改chart的padding？如何给x轴添加竖线，如图

### ISSUE THREAD

**Issue by asz97665** [antvis/G2#5984]
### 问题描述

import { Chart } from '@antv/g2';

const data = [
  { year: '1951 年', sales: 38 },
  { year: '1952 年', sales: 52 },
  { year: '1956 年', sales: 61 },
  { year: '1957 年', sales: 145 },
  { year: '1958 年', sales: 48 },
  { year: '1959 年', sales: 38 },
  { year: '1960 年', sales: 38 },
  { year: '1962 年', sales: 38 },
];

const chart = new Chart({
  container: 'container',
  autoFit: true,
});

chart
  .interval()
  .coordinate({ transform: [{ type: 'transpose' }] })
  .data(data)
  .encode('x', 'year')
  .encode('y', 'sales');

chart.render();

这个例子我看x轴是有竖线的，怎么修改它的样式让他更加明显，以及标题的几个问题

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

![原型修改](https://github.com/antvis/G2/assets/45706771/f248db75-4d0b-4b46-82e4-51cff1bd6cdc)

**Comment by pearmini** [comment]
1. `chart.axis('x', { title: false }).axis('y', { title: false })`
2. `chart.attr('padding', 10)`
3. `chart.axis('x', { gridFill: 'black' })`
