### ISSUE TITLE
tooltip不展示标题在g2 5.1.6中如何操作

### ISSUE THREAD

**Issue by asz97665** [antvis/G2#5991]
### 问题描述
现在使用的是.tooltip((d)=>d)
如何最简便地不展示标题
![image](https://github.com/antvis/G2/assets/45706771/5b5dc681-62ce-41ad-a5d5-84ef9419df48)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by pearmini** [comment]
```js
.tooltip({ title: '' })
```
