### ISSUE TITLE
怎么设置图例全部不选中

### ISSUE THREAD

**Issue by YY88Xu** [antvis/G2#5997]
### 问题描述

<img width="1090" alt="image" src="https://github.com/antvis/G2/assets/14836228/5ee522a7-bdf9-4dfa-bb5b-6a947ea8cf5e">

### 重现步骤

```
import { Chart } from '@antv/g2';

const chart = new Chart({ container: 'container' });

chart
  .interval()
  .data([
    { genre: 'Sports', sold: 0 },
    { genre: 'Strategy', sold: 115 },
    { genre: 'Action', sold: 120 },
    { genre: 'Shooter', sold: 350 },
    { genre: 'Other', sold: 150 },
  ])
  .encode('x', 'genre')
  .encode('y', 'sold')
  .encode('color', 'genre')
  .style('minHeight', 50);

chart.render();

```
现在的问题是，只剩一个图例，点击后重新全部选中，怎么设置图例全部不选中呢？

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by pearmini** [comment]
这个能力目前还没有，感兴趣提一个 PR 吗？

**Comment by pearmini** [comment]
中级任务

**Comment by Runtus** [comment]
我来处理下

**Comment by pearmini** [comment]
中级任务

**Comment by Runtus** [comment]
老哥想问下，如果全部不选中，需要保留坐标轴吗 @pearmini

**Comment by pearmini** [comment]
@Runtus 应该是需要保留的，不然都没有了有点突兀。😄

**Comment by Runtus** [comment]
@pearmini  老哥，想问下如果要保留坐标轴的话，X轴如何去定义呢？因为全部不选中的情况下，X轴是没有值的，这个时候X轴是展示不了的，类似下图这种情况。
![9c9db840f304faa44b168908744bec50](https://github.com/user-attachments/assets/c079e448-adf9-47c4-9517-65e724473789)

**Comment by pearmini** [comment]
@Runtus 有几种解决办法：

- 不展示
- 只展示一个 title
- 展示 title 和对应的 ticks

目前看上去不展示是最合理的？你觉得呢？

**Comment by Runtus** [comment]
@pearmini 老哥，我觉得可能要分情况来看，我去看了下示例，现在这种分类可能有两种情况，它可能根据X轴进行分类，这个时候隐藏X轴确实是比较合理的选择（我去看了下Echarts好像也是这样做的），但如果它的分类和轴本身不相关，那么这个时候应该要保留XY轴。

**Comment by pearmini** [comment]
@Runtus 嗯嗯，那就按照你的想法来
