### ISSUE TITLE
如图，在折线图上如何实现点击折线上一个点后，保留tooltip的那根线以及展示x轴坐标在最顶端；以及如何修改提示点的样式为一个空心圆，提示线为虚线

### ISSUE THREAD

**Issue by asz97665** [antvis/G2#5999]
### 问题描述

![tooltip样式](https://github.com/antvis/G2/assets/45706771/440d47ec-254f-4821-b436-a9ad8ec11a67)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by pearmini** [comment]
> 在折线图上如何实现点击折线上一个点后，保留tooltip的那根线以及展示x轴坐标在最顶端

这个没有办法内置实现，期望这个效果可以自己自定义交互

> 如何修改提示点的样式为一个空心圆

这个能力还没有，感兴趣提一个 PR 吗？比如 

```js
chart.interaction("tooltip", { markerType: 'hollow' })
```

> 提示线为虚线

```js
chart.interaction("tooltip", { crosshairsLineDash: [3, 4] })
```

**Comment by pearmini** [comment]
@Runtus [3, 4] 中3表示线段的长度，4表示线段之间的间距，可以看看这里的[解释](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setLineDash)

**Comment by Runtus** [comment]
我认领这个任务

**Comment by pearmini** [comment]
@Runtus 这个算一个终极任务！

**Comment by Runtus** [comment]
@pearmini 老哥，需要改下官网文档描述吗，因为markerType属于`marker${StyleAttrs}`中的，如果不特殊说明一下话，用户可能无法感知`markerType: "hollow"`的存在。

**Comment by pearmini** [comment]
@Runtus 可以的
