### ISSUE TITLE
链式调用必须一次性写完？

### ISSUE THREAD

**Issue by feng5** [antvis/g2#60]
比如
```chart.point().position('height*weight').color('gender');```
能不能写成：
```
chart.point().position('height*weight')；
chart.color('gender');
```

**Comment by feng5** [comment]
比如我要写一个函数封装，根据参数是否传入来判断是否要做color或者shape等绘制，是不是要每个判断都要这样`chart.<geom>.color("z")`或者`chart.<geom>.color("z").shape('s')`?

**Comment by simaQ** [comment]
你可以先拿到  var geom = chart.<geom>(); 然后再调用 geom.position() ; geom.color(); geom.shape() 呀。

**Comment by feng5** [comment]
:+1: 谢谢

**Comment by feng5** [comment]
` var geom = chart.();`有`Uncaught SyntaxError: Unexpected token (`错误，能给个完整的例子看看么

**Comment by dxq613** [comment]
var geom = chart.point();
geom.position('x*y');
geom.size(10);
geom.color('z');
