### ISSUE TITLE
scale方法不传入第二个参数时会出现错误

### ISSUE THREAD

**Issue by gwallan** [antvis/g2#601]
* **G2 Version**: 3.0.4
* **Platform**: `MAC-CHROME`
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

`const data = [
    { year: '1951 年', sales: 38 },
    { year: '1952 年', sales: 52 },
    { year: '1956 年', sales: 61 },
    { year: '1957 年', sales: 145 },
    { year: '1958 年', sales: 48 },
    { year: '1959 年', sales: 38 },
    { year: '1960 年', sales: 38 },
    { year: '1962 年', sales: 38 },
  ];
  const chart = new G2.Chart({
    container: 'mountNode',
    forceFit: true,
    height: window.innerHeight
  });
  chart.source(data);
  chart.scale('sales');
  chart.interval().position('year*sales');
  chart.render();`
如上代码，当scale方法调用时不传入第二个参数时，会出现错误

**Comment by leungwensen** [comment]
如果需要用默认的 scale，你不用写 `chart.scale('sales');` ，第二个参数是必须的。
