### ISSUE TITLE
3.0.7版本，面积图显示有bug

### ISSUE THREAD

**Issue by xiechao1211** [antvis/g2#602]
bug复现地址：
https://antv.alipay.com/zh-cn/g2/3.x/demo/area/basic.html
将antv引用地址改为
<script src="https://gw.alipayobjects.com/os/antv/assets/g2/3.0.7/g2.min.js"></script>
即可看到。
0刻度线变成了最小值与最大值的连接线。
由于使用的是viser，通过npm安装会自动将antv升级到最新版，目前只能使用package-lock进行版本锁定降低antv版本使用了。

**Comment by xiechao1211** [comment]
@leungwensen

**Comment by leungwensen** [comment]
多谢反馈

**Comment by leungwensen** [comment]
更新到 3.0.8

**Comment by xiechao1211** [comment]
antv团队太赞！周末都在修bug，感谢！
