### ISSUE TITLE
有没有配置，柱状图为0不显示，但是可以显示tooltip, 像g2plot那样

### ISSUE THREAD

**Issue by gungun0613** [antvis/G2#6030]
```ts
.style('minHeight', 5)
```

为 0 的时候，数据映射成图形高度就是 0，符合预期的，如果实在需要显示出来，按照上面的配置。

_Originally posted by @hustcc in https://github.com/antvis/G2/issues/6028#issuecomment-1886558192_

**Comment by pearmini** [comment]
相同的问题：https://github.com/antvis/G2/issues/6044
