### ISSUE TITLE
柱状图的tooltip被遮挡，无法看到全部

### ISSUE THREAD

**Issue by gungun0613** [antvis/G2#6035]
### 问题描述

柱状图的tooltip被遮挡
相关配置如下：
chartPlot.current.options({
        type: 'interval',
        data: chartData,
        encode: {
          x: 'x',
          y: 'y',
        },
        axis: { x: false, y: false },
        style: {
          fill: '#6879BA',
          minHeight: 2,
        },
        tooltip: {
          title: '',
          items: [
            (d: any) => {
              return {
                color: '#6879BA',
                name: d.x,
                value: d.y,
              };
            },
          ],
        },
        interaction: {
          elementHighlight: {
            background: true,
          },
          tooltip: {
            mount: 'body',
            css: {
              '.g2-tooltip': {
                'z-index': 999,
              },
              '.g2-tooltip-list-item-value': {
                'white-space': 'pre',
              },
            },
          },
        },
      });

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

![Uploading image.png…]()

**Comment by hustcc** [comment]
有可以访问和复现的在线案例吗

**Comment by pearmini** [comment]
可能是 tooltip 太大了，没有办法调整。
