### ISSUE TITLE
tooltip 触发条件

### ISSUE THREAD

**Issue by YY88Xu** [antvis/G2#6044]
### 问题描述

https://echarts.apache.org/examples/zh/editor.html?c=bar-label-rotation
<img width="1861" alt="image" src="https://github.com/antvis/G2/assets/14836228/a1f1bcc0-d3b7-4148-8332-940de1dcd572">
有没有echarts 类似的功能，就是点击的是空白的地方也会出现 tooltip，现在柱状图需要hover到柱子才能出现 tooltip

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by YY88Xu** [comment]
<img width="1849" alt="image" src="https://github.com/antvis/G2/assets/14836228/5ab79f47-1082-45ac-a48c-dfcfd3275e04">
https://g2.antv.antgroup.com/zh/examples/general/interval/#bar-basic-grouped

**Comment by pearmini** [comment]
嗯嗯，这个目前需要优化，最快这个月底优化。

**Comment by Liugq5713** [comment]
> 嗯嗯，这个目前需要优化，最快这个月底优化。

优化完了吗 ? 怎么开启这个功能呢 ?

**Comment by CullenNg** [comment]
坐等优化，目前我是另外设置一个透明的interval，层级为最底层，这样另辟蹊径也大致达到这个效果🤣

**Comment by Liugq5713** [comment]
> 坐等优化，目前我是另外设置一个透明的interval，层级为最底层，这样另辟蹊径也大致达到这个效果🤣

怎么做的呀， 我也设置了透明的 interval , 但是这个柱状图会收到legend点选的影响，用户点了legend之后就出现颜色了。。

**Comment by pearmini** [comment]
@CullenNg @Liugq5713 @YY88Xu 这个 PR 已经优化了这个功能：https://github.com/antvis/G2/pull/6289
