### ISSUE TITLE
无法设置透明度

### ISSUE THREAD

**Issue by Jungzl** [antvis/G2#6058]
### 问题描述

```js
import { Chart } from '@antv/g2';
import { Renderer } from '@antv/g-svg';

const data = [
  { year: '1951 年', sales: 38 },
  { year: '1952 年', sales: 52 },
  { year: '1956 年', sales: 61 },
  { year: '1957 年', sales: 145 },
  { year: '1958 年', sales: 48 },
  { year: '1959 年', sales: 38 },
  { year: '1960 年', sales: 38 },
  { year: '1962 年', sales: 38 },
];

const chart = new Chart({
  container: 'container',
  autoFit: true,
  renderer: new Renderer(),
});

chart
.interval()
.data(data)
.encode('x', 'year')
.encode('y', 'sales')
.axis('x', { 
  labelFill: '#f00',
  labelFillOpacity: 1, // ⬅️ not working
 });

chart.render();

```
![image](https://github.com/antvis/G2/assets/35426360/282090b5-5120-4bf7-a27d-4a05da98fe7b)
![image](https://github.com/antvis/G2/assets/35426360/ba694af0-4f83-48eb-a1c9-fa1293c070bd)
![image](https://github.com/antvis/G2/assets/35426360/0189279c-3dbd-4676-9d16-23f73bd96f18)
透明度固定为0.45

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by hustcc** [comment]
设置 labelOpacity 呢，能生效吗？

**Comment by hustcc** [comment]
看 svg 中，fill 属性中确实是带了 opacity 信息的。

**Comment by Jungzl** [comment]
> 看 svg 中，fill 属性中确实是带了 opacity 信息的。

![image](https://github.com/antvis/G2/assets/35426360/98159b7a-e768-4fdc-82c4-933d8a234985)
此处应为 `labelOpacity`

**Comment by hustcc** [comment]
了解了，方便来提一个 PR 修复下嘛！

**Comment by Jungzl** [comment]
好的
