### ISSUE TITLE
G2 4.x版本，热力图展示问题，当数值为0时或者数值中的最小值时，会出现没有颜色的情况，期望通过设置最大最小透明度来控制

### ISSUE THREAD

**Issue by Mr-jili** [antvis/G2#6078]
### 问题描述

热力图当数值为0时或者数值中的最小值时，会出现没有颜色的情况，正常情况应该是当前设定color的第一个值

### 重现步骤

第一种情况：[{ x: 20, y: 30, value: 0 }, { x: 20, y: 30, value: 10 }]当value为0时不会显示颜色
第二种情况：[{ x: 20, y: 30, value: 450 }, { x: 20, y: 30, value: 10 }]当value为10时不会显示颜色

### 预期行为

期望展示设置color的第一个颜色,通过设置minOpactity及max，与heatmap.js一致的，设置最大最小值透明度来控制

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by hustcc** [comment]
使用的什么版本？

**Comment by Mr-jili** [comment]
G2 4.x版本是不是不支持heatMap设置minOpacity，只有G2 5.x才支持嘛

**Comment by hustcc** [comment]
> G2 4.x版本是不是不支持heatMap设置minOpacity，只有G2 5.x才支持嘛  G2 4.x版本有什么办法解决上述问题嘛

v4 不支持。没有暴露出来api。

**Comment by Mr-jili** [comment]
maxOpacity、minOpactity这个api后续会暴露嘛  因为ant-design-chart 1.4.2版本 还是常用的版本，他这个用的还是G2 4.x版本

**Comment by hustcc** [comment]
你可以来一个案例代码吗？不要一直开关 issue。

**Comment by Mr-jili** [comment]
[https://codesandbox.io/p/sandbox/practical-williams-zw8lwn?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clt8decgh0006356h9ddqzq1d%2522%252C%2522sizes%2522%253A%255B56.04034193036259%252C43.95965806963741%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clt8decgg0002356h7vp34f8c%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clt8decgg0003356hhz37lhh8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clt8decgg0005356h1h47kva0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clt8decgg0002356h7vp34f8c%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%252](url)

**Comment by pearmini** [comment]
@Mr-jili 这个确实不兼容哈。
