### ISSUE TITLE
能不能给提供各个图的数据模式！！！！

### ISSUE THREAD

**Issue by chenshuai2144** [antvis/g2#61]
我现在正在整分组数据，我能不能直接自己封装，不用你们的api

**Comment by feng5** [comment]
文档讲得很清楚，JSON数组或者Frame

**Comment by dxq613** [comment]
其实G2的数据本质上仅仅支持 标准的json 数组，在G2的内部会转换成列模式的Frame

https://g2.alipay.com/tutorial/data.html

唯一的例外，在实现树等关系图时，都需要外部的布局函数或者嵌入到语法中的统计函数对树形的数据进行加工，但是最终还是加工成了标准的Json 数组的格式。

**Comment by dxq613** [comment]
分组柱形图，本质上是在数据上加个 字段区分一下即可,会自动分组的

```js
var data = [
  {x: 'a', y: 1, type: '1'},
  {x: 'a', y: 2, type: '2'},
  {x: 'b', y: 2, type: '1'},
  {x: 'b', y: 3, type: '2'}
];

chart.intervalDodge().position('x*y').color('type');
```
就会自动生产成分组的柱状图，把intervalDodge改成intervalStack就会变成 层叠柱状图

**Comment by dxq613** [comment]
这个项目里面有更多的demo可以下载下去看看：https://github.com/antvis/G2-demo/tree/master/examples
