### ISSUE TITLE
怎么设置label文本字体大小

### ISSUE THREAD

**Issue by senlinmilelu** [antvis/G2#6100]
### 问题描述

treemap每一项数据 label文字大小怎么设置
 label={{
    style: {
       fontSize:20，//通过数据设置
   }
}}

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by hustcc** [comment]
配置一个回调方法。

**Comment by senlinmilelu** [comment]
> ```ts
> .style('labelFontSize', 10)
> .style('labelFontSize', (d) => 10)
> ```
> 
> 可以写一个具体的字体数字，也可以使用回调。


dv.source(datas, {
        type: 'hierarchy',
    }).transform({
        field: 'value',
        type: 'hierarchy.treemap',
        tile: 'treemapResquarify',
        as: ['x', 'y'],
    });
    
    return (
        <>
            <TreemapChart
                height={800}
                data={dv.rows.data}
                description={{visible: false}}
                colorField='name'
                label={{
                    style: {
                        textBaseline: 'middle',
                        // fontSize:20,
                    },
                }}
           </TreemapChart>
       </>
    )
请问在哪写回调
