### ISSUE TITLE
漏斗图最下面一个是矩形，有没有办法和上面一样显示梯形

### ISSUE THREAD

**Issue by JacobYChan** [antvis/g2#612]
现在漏斗图最下面一个是矩形，还有对称漏斗图最上面是一个矩形，有没有办法样显示成梯形，如下面的效果图
<img width="540" alt="2018-04-26 2 52 37" src="https://user-images.githubusercontent.com/18413888/39290439-1a58616e-4962-11e8-9465-3a1eb2809306.png">

**Comment by leungwensen** [comment]
目前只有底下是 矩形 和底下是 三角形 两种。因为漏斗图“梯形”的坡度是有含义的，所以我们不能给你平白补一条数据。

平底的漏斗图：https://antv.alipay.com/zh-cn/g2/3.x/demo/funnel/basic.html

尖底的漏斗图：https://antv.alipay.com/zh-cn/g2/3.x/demo/funnel/pyramid.html
