### ISSUE TITLE
【V5】axia 轴线标题如何实现位置偏移无法自定义位置吗？

### ISSUE THREAD

**Issue by rr210** [antvis/G2#6128]
### 问题描述

【V5】axia 轴线标题如何实现位置偏移无法自定义位置吗？

### 重现步骤

    chart.options({
      type: 'interval',
      theme: 'custom',
      autoFit: true,
      data: [
        { name: 'London', 月份: 'Jan.', 月均降雨量: 18.9 },
        { name: 'London', 月份: 'Feb.', 月均降雨量: 28.8 },
        { name: 'London', 月份: 'Mar.', 月均降雨量: 39.3 },
        { name: 'London', 月份: 'Apr.', 月均降雨量: 81.4 },
        { name: 'London', 月份: 'May', 月均降雨量: 47 },
        { name: 'London', 月份: 'Jun.', 月均降雨量: 20.3 },
        { name: 'London', 月份: 'Jul.', 月均降雨量: 24 },
        { name: 'London', 月份: 'Aug.', 月均降雨量: 35.6 },
        { name: 'Berlin', 月份: 'Jan.', 月均降雨量: 12.4 },
        { name: 'Berlin', 月份: 'Feb.', 月均降雨量: 23.2 },
        { name: 'Berlin', 月份: 'Mar.', 月均降雨量: 34.5 },
        { name: 'Berlin', 月份: 'Apr.', 月均降雨量: 99.7 },
        { name: 'Berlin', 月份: 'May', 月均降雨量: 52.6 },
        { name: 'Berlin', 月份: 'Jun.', 月均降雨量: 35.5 },
        { name: 'Berlin', 月份: 'Jul.', 月均降雨量: 37.4 },
        { name: 'Berlin', 月份: 'Aug.', 月均降雨量: 42.4 },
      ],
      encode: { x: '月份', y: '月均降雨量', color: 'name' },
      transform: [
        { type: 'stackY' },
        { type: 'sortX', by: 'y', reverse: true },
      ],
      coordinate: { transform: [{ type: 'transpose' }] },
      legend: {
        color: {
          position: 'right',
          itemMarker: 'circle',
          transform: `translate(0,-10)`,
          layout: {
            justifyContent: 'flex-end',
          },
        },
      },
      axis: {
        x: {
          line: false,
          tick: false,
          title: false,
          lineArrowSize: 8,
        },
        y: {
          titleSpacing: -32,
          titlePosition: 'tr',
          lineArrowSize: 4,
          line: true,
          arrow: true,
          title: 'xxx',
          titleFill: '#d4d4d49e',
          lineExtension: [50, 70], // 轴线两侧
        },
      },
    });

### 预期行为

我想y轴title向左移动一点

**Comment by xiaoiver** [comment]
可以使用 `titleTransform`:

```ts
axis: {
  y: {
    titleTransform: 'translate(-40, 0)',
  },
},
```

示例：https://codesandbox.io/p/sandbox/shi-yong-g-hui-zhi-path-forked-64vm8y?file=%2Findex.js%3A10%2C17
