### ISSUE TITLE
2.5D柱状图tooltip不显示

### ISSUE THREAD

**Issue by zcc19910728** [antvis/G2#6141]
### 问题描述

这是官网demo，https://g2.antv.antgroup.com/zh/examples/interesting/interesting/#25d-column,手动设置tooltip也不生效tooltip: {
        items: [
          (d, i, data, column) => ({
            name: 'test', // 指定 item 的名字
            value: 1111 // 使用 y 通道的值
          })
        ]
      }，

### 重现步骤

https://g2.antv.antgroup.com/zh/examples/interesting/interesting/#25d-column

### 预期行为

显示tooltip

### 平台

- 操作系统: [windos11]
- 网页浏览器: [Google Chrome122]

**Comment by pearmini** [comment]
这个 PR 已经修复了，明后天会发一个版本：https://github.com/antvis/G2/pull/6140

**Comment by pearmini** [comment]
可以试试这个版本：@antv/g2@5.1.17
