### ISSUE TITLE
面积图，图表数据全部为null时，如何不画线

### ISSUE THREAD

**Issue by shaner1204** [antvis/G2#6146]
- [x] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://f2.antv.antgroup.com/examples/area/area/#area](https://f2.antv.antgroup.com/examples/area/area/#area)

### Steps to reproduce
1、将面积图Y轴数据全部设置为null
2、图表中依然会展示一条

如图所示：
![image](https://github.com/antvis/G2/assets/39398324/95fe5aa3-e2bc-4255-be0f-a040368116b9)

| Environment | Info |
|---|---|
| g2 | 5.1.17 |
| System | - |
| Browser | - |

**Comment by pearmini** [comment]
这个是 F2，可以去 [F2](https://github.com/antvis/F2) 问问。
