### ISSUE TITLE
使用 timeCat，Error: Invalid Date in fecha.format

### ISSUE THREAD

**Issue by VanquisherMe** [antvis/g2#615]
* **G2 Version**: 3.0.6
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

数据源
![1e3ab215-b562-46f8-9eb0-3e65d231c25a](https://user-images.githubusercontent.com/4927398/39514104-df79a1c2-4e28-11e8-8d52-b125d509d171.png)
代码片段
![a690d6d6-efea-4096-a9a0-6ac802a95c35](https://user-images.githubusercontent.com/4927398/39514127-f3b5da34-4e28-11e8-9c39-b70a72baf40b.png)
报错信息
![1dfb1b05-6c12-4ed7-ad3c-1c37a7c54da2](https://user-images.githubusercontent.com/4927398/39514158-04f66a52-4e29-11e8-8eca-96def145b1f9.png)
x轴 是一个不连续的时间节点，
如文档描述
https://antv.alipay.com/zh-cn/g2/3.x/api/scale.html#_timeCat
做出如下尝试
```
const cols = {
            time:{
                nice:false,
                type: 'timeCat',
                mask: 'YYYY/MM/DD',

            }
        }
Error: Invalid Date in fecha.format
```
```
const cols = {
            time:{
                nice:false,
                type: 'time',
                mask: 'YYYY/MM/DD',

            }
        }
Error: Invalid Date in fecha.format
```
```
const cols = {
            time:{
                nice:true,
                type: 'time',
                mask: 'YYYY/MM/DD',

            }
        }
可以渲染
这里补全了前后时间节点，不太明白nice 参与后的算法规则
```
但是这里主要的问题是  timeCat 报了Error: Invalid Date in fecha.format

**Comment by leungwensen** [comment]
你先升级到 3.0.9 有可能是之前版本的一个问题。能不能脱敏之后写个 codepen 出来？我重现不了

**Comment by VanquisherMe** [comment]
@leungwensen 大致问题定位到 type:timeCat, data=[] 时没有处理？
测试
https://alibaba.github.io/BizCharts/demo-detail.html?code=demo/line/series
修改为
```
const { Chart, Axis, Geom, Tooltip, Legend } = window.BizCharts;
        const data = [];
      const ds = new DataSet();
      const dv = ds.createView().source(data);
      dv.transform({
        type: 'fold',
        fields: [ 'Tokyo', 'London' ], // 展开字段集
        key: 'city', // key字段
        value: 'temperature', // value字段
      });
      console.log(dv);
      const cols = {
        month: {
          type:"timeCat",
          range: [ 0, 1 ]
        }
      }
      ReactDOM.render((
        <Chart height={400} data={dv} scale={cols} forceFit>
          <Legend />
          <Axis name="month" />
          <Axis name="temperature" label={{formatter: val => `${val}°C`}}/>
          <Tooltip crosshairs={{type : "y"}}/>
          <Geom type="line" position="month*temperature" size={2} color={'city'} />
          <Geom type='point' position="month*temperature" size={4} shape={'circle'} color={'city'} style={{ stroke: '#fff', lineWidth: 1}} />
        </Chart>
      ), document.getElementById("mountNode"));
```

**Comment by leungwensen** [comment]
不用特殊处理，如果是 data 为空的问题，3.0.9 版本已经修复了，可以升级一下

**Comment by leungwensen** [comment]
不会吧，你在出问题的地方输出一下 G2.version 看看？

**Comment by VanquisherMe** [comment]
@leungwensen 我做一个最简 demo 尝试下
![image](https://user-images.githubusercontent.com/4927398/39567074-51359bfa-4ef0-11e8-9329-48d86a7622b7.png)

**Comment by leungwensen** [comment]
@VanquisherMe 多谢，之前是修复了 time 类型的。。。 timeCat 类型忽略了

**Comment by leungwensen** [comment]
你先按照之前的解法 hack 一下，3.0.10 会修复掉

**Comment by VanquisherMe** [comment]
ok

**Comment by heiniuhaha** [comment]
已修复，查看以下Demo
bizcharts@3.x https://bizcharts.net/product/bizcharts/demo/525
bizcharts@4.x https://bizcharts.net/product/BizCharts4/demo/524
