### ISSUE TITLE
当数据以万为单位开始，area 就显示成一条

### ISSUE THREAD

**Issue by migicHand0820** [antvis/G2#6155]
### 问题描述

动态获取数据，数据为 10万以上的数据开始就显示成一条直线

### 重现步骤

chart
    .area()
    .encode('x', 'time')
    .encode('y', 'value')
    .encode('shape', 'smooth')
    .style('fill', 'l(270) 0:rgba(255,255,255,0) 0.4:#EBD6DF 1:#EBD6DF')
    .style('fillOpacity', 1)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

<img width="210" alt="image" src="https://github.com/antvis/G2/assets/165501874/d23bc8d5-2b38-4416-9339-beb9d813da55">

**Comment by hustcc** [comment]
是什么版本，有复现的 demo 吗？
