### ISSUE TITLE
4.x版本折线图resize时tooltip失效

### ISSUE THREAD

**Issue by TaoziDeGitHub** [antvis/G2#6159]
### 问题描述

折线图forceFit时tooltip失效

### 重现链接

https://g2-v4.antv.vision/zh/examples/case/line#line1

### 重现步骤

4.x版本折线图forceFit时tooltip能正常显示

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

![失效](https://github.com/antvis/G2/assets/65647528/451282ba-ffa3-4e8a-a66e-6dc03da64a78)

**Comment by hustcc** [comment]
尽快升级到最新的 5.0 版本吧。
