### ISSUE TITLE
对称漏斗图左右移动鼠标时tooltip不更新数据

### ISSUE THREAD

**Issue by JacobYChan** [antvis/g2#616]
当鼠标从左边对比期平移到右边本期区域时，tooltip的内容没有更新，从右边区域移动到左边区域也一样，上下移动会更新，这是什么原因啊，麻烦看下

[在线查看问题](https://codepen.io/jacobychan/pen/jxmxPz)

**Comment by Leannechn** [comment]
估计和我是一个问题。
同一个geom下，同组数据间切换，没有触发更新，也没有触发跟新模版数据。geom上的tooltip函数是调用了，但是没有触发重新渲染。

**Comment by JacobYChan** [comment]
后来我发现tooltip的itemTpl的模板第一个字段名必须要是name才会触发更新

**Comment by leungwensen** [comment]
嗯嗯，目前 tooltip 变更的判断是回传数据里的 name / value / color / title 这样的字段发生变化才会更新。下个小版本里我们会开放这个标准，改为“所有非索引属性值”发生变化就会更新。

**Comment by heiniuhaha** [comment]
赞，绝云同学效率很高
