### ISSUE TITLE
5.1.15: tooltiip .g2-tooltip defaulting to Roboto-Regular

### ISSUE THREAD

**Issue by sspilleman** [antvis/G2#6161]
**How to reproduce:**
Take a simple barchart with a tooltip:
.g2-tooltip class is 'font-family': 'Roboto-Regular'
Which is not installed in my project so it looks inconsistent with e.g. legend and other fonts selected by default for the chart

**Expected**
'font-family': `inherit` OR whatever font is selected by default for other chart elements like legend

**Workaround:**
```typescript
chart.interaction('tooltip', {
	css: {
		'.g2-tooltip': {
			'font-family': `inherit` <------------
		}
	}
});
```

**Software**
macOS, Chrome

**Comment by sspilleman** [comment]
please comment and close if you don't think this is an issue....

**Comment by hustcc** [comment]
the font of tooltip and legend should be the same value.

**Comment by sspilleman** [comment]
> the font of tooltip and legend should be the same value.

Then its a bug ;-)
