### ISSUE TITLE
5.1.15: theme 'dark' applies black background color

### ISSUE THREAD

**Issue by sspilleman** [antvis/G2#6164]
**Problem Description:**
theme 'dark' applies black background color.
I think a lot of projects offering a dark mode use a different background color (than black).

Maybe you want to consider using 'transparent' by default instead? If i'm not mistaken, I think the 'light' theme already uses transparent by default.
Also see workaround below. I had to use 'none' to get rid of it... Using 'transparent' instead of 'none' feels more natural?

**Workaround:**
```typescript
chart.options({
	theme: {
		type: 'dark',
		view: {
			viewFill: 'none' <------------
		}
	},
});
```

**Comment by hustcc** [comment]
@pearmini +1

**Comment by sspilleman** [comment]
please comment and close if you don't think this is an issue....

**Comment by hustcc** [comment]
Can help us with a pr, and set the viewFill = transparent when dark mode.

**Comment by sspilleman** [comment]
Thanks @hustcc but this also required changing the documentation etc, and my chinese isn't great ;-)
