### ISSUE TITLE
Axis 轴 labelAutoRotate 旋转异常

### ISSUE THREAD

**Issue by CullenNg** [antvis/G2#6170]
### 问题描述

视图宽度缩小后，X轴的label全部转成90度，接着把宽度拉大，X轴的label不会恢复原状；

### 重现链接

https://codesandbox.io/p/sandbox/crazy-bhabha-lmd64k?file=%2Findex.ts

### 重现步骤

1. 进入页面
![image](https://github.com/antvis/G2/assets/16042958/a10c429b-dd7d-41ce-9567-da9e65c64d2d)

2. 缩小视图，label 角度变更
![image](https://github.com/antvis/G2/assets/16042958/a6dafe34-043e-49cd-9cac-234e38662d7a)

3. 再次恢复宽度，label 无法恢复原有的角度
![image](https://github.com/antvis/G2/assets/16042958/09d58326-ab1b-4188-af71-a489869d127e)

### 预期行为

宽度变更，label rotate角度恢复正常

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by pearmini** [comment]
可能是在更新的时候，配置的合并出了点问题，这个我看看

**Comment by pearmini** [comment]
@CullenNg 这周修复，下周发版本
