### ISSUE TITLE
g2能根据配置直接生成base64用于浏览器的打印吗

### ISSUE THREAD

**Issue by luobin365304** [antvis/G2#6174]
react+antv/g2能直接根据传人图表配置同步生成png图片的base64编码吗，用于PDF打印

**Comment by hustcc** [comment]
- 如果是 node 环境，使用 https://github.com/antvis/G2/discussions/5772 中的 ssr node。
- 如果是浏览器环境，只需要通过 chart 拿到 canvas，然后 getDataURL 即可。

**Comment by luobin365304** [comment]
不需要依赖服务端

> * 如果是节点环境，使用[👏🏻👏🏻👏🏻收集G2生态周边仓库收集G2相关项目 #5772](https://github.com/antvis/G2/discussions/5772)中的ssr节点。
> * 如果是浏览器环境，只需要通过chart获取canvas，然后getDataURL即可。

在浏览器环境，能提供一个简单的示例吗，G2 5.0版本

**Comment by hustcc** [comment]
```ts
const base64 = chart.getContext().canvas.getContextService().getContext().canvas.toDataURL();
```
