### ISSUE TITLE
antv/g2 5.0 移除了getCanvas等方法后怎么同步拿到画布内容

### ISSUE THREAD

**Issue by luobin365304** [antvis/G2#6176]
### 问题描述

由于chart.render方法是异步的，在render后获取到的画布canvas为空画布。有什么方法可以在render后立即同步拿到画布内容
![微信截图_20240416091621](https://github.com/antvis/G2/assets/33414842/7f8aae91-d3f3-4728-b953-65bc712ac002)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by hustcc** [comment]
render 是一个异步的 promise ，所以要么就是 .then，要么就是 await chart.render()。
