### ISSUE TITLE
折线图数据会自动填充是为什么？

### ISSUE THREAD

**Issue by onecorner** [antvis/g2#618]
![image](https://user-images.githubusercontent.com/11347680/39609836-7660faa8-4f7e-11e8-9f3e-5502210abc32.png)
在填充折现图的时候出现了这个问题，我把该折线图的渲染放在一个component里面了，通过url来实现不同的组建渲染不同的折线图，同一个页面，其他的折线图是ok的，就是这个，出现了这种莫名其妙的问题，他把我数据为0的值统统填充了第一个key的值，请问这是为什么？

**Comment by leungwensen** [comment]
G2 版本是多少，有没有复现 bug 的 codepen 链接？

**Comment by onecorner** [comment]
版本是3.0.1，刚刚我也提到了，同样页面执行代码一模一样，偏偏这组数据就有问题，所以很难复现，不过初步怀疑可能和数据有关系，因为当我在下面点击legend去除第一个数据的时候，也就是被copy的那个key值的时候，数据正常了，但是该数据看不出有什么问题。

**Comment by leungwensen** [comment]
我重现不了，你先检查一下是不是在 chart.source 之前自己改了数据？

**Comment by onecorner** [comment]
没有哦，那是我在source之前打印的，可能是数据问题，由于报表数据有变动，现在的展示又好了，然而我什么都没做，仅仅只是数据变动了！

**Comment by leungwensen** [comment]
那等有稳定重现的 codepen 之后再重开这个 issue 吧

**Comment by leungwensen** [comment]
```js
        .transform({
          type: 'map',
          callback(row) {
            row.value = parseInt(row.value);
            return row;
          }
        })
```
在 dv 那里加一段，把 value 统一处理成数字。你这个数据首行是字符串，然后又有很多值是 0 的数字，画的图是有问题的，tooltip 的判断也受了影响

**Comment by onecorner** [comment]
好的，谢谢了，所有的问题都已经ok了！
