### ISSUE TITLE
changeData更新数据。图例没有实时更新

### ISSUE THREAD

**Issue by Calmio-Y** [antvis/G2#6191]
### 问题描述

![image](https://github.com/antvis/G2/assets/30626950/ccff3ccc-b878-4ceb-a5b7-7948a79be167)

### 重现步骤

1.第一个渲染和第二次渲染的数据不同
2.使用的是changeData更新数据的

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by pearmini** [comment]
需要在图表重新渲染之后，同步渲染图例。

```js
chart.changeData().then(updateLegend)
```

**Comment by Calmio-Y** [comment]
updateLegend是？

**Comment by pearmini** [comment]
这个我先关闭了，就在 https://github.com/antvis/G2/discussions/6152 这里面讨论吧。
