### ISSUE TITLE
当 encode.series 指定了某一个值时， tooltip.items 自定义 name 会失效

### ISSUE THREAD

**Issue by CullenNg** [antvis/G2#6192]
### 问题描述

当我给 encode.series 指定了某一个值时， tooltip.items 自定义函数返回的 name 会失效，会强制返回为 series 指定的值；
`
items: [
  () => {
    return {
      name: '定制名字',  // 失败
     value: 10000, // 成功的
   }
  }
]`

### 重现链接

https://codesandbox.io/p/sandbox/youthful-mountain-ldxlgr

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by pearmini** [comment]
需要添加如下这一行：

```js
chart.interaction("tooltip", {groupName: false})
```
