### ISSUE TITLE
link mark 设置 lineWidth 的时候，箭头显示不对

### ISSUE THREAD

**Issue by hustcc** [antvis/G2#6198]
### 问题描述

![image](https://github.com/antvis/G2/assets/7856674/a8eb289f-e82a-4325-a892-23aa0af3fdd9)

### 重现链接

https://g2.antv.antgroup.com/examples/general/link/#link

### 重现步骤

点进去，设置 style lineWidth 为 20.

### 预期行为

箭头显示合理。

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by xiaoiver** [comment]
看着像是 Arrow 路径定义有问题，切到 SVG 渲染器下就能看到了：

```
M 236.31521706056873,-3.2987061671737345 L 235.37086230853296,3.2987061671737345 L 237.01747885758147,1.2021664452666063 M 235.37086230853296,3.2987061671737345 L 234.3785139238425,0.8244245444523002
```

**Comment by hustcc** [comment]
> 看着像是 Arrow 路径定义有问题，切到 SVG 渲染器下就能看到了：
> 
> ```
> M 236.31521706056873,-3.2987061671737345 L 235.37086230853296,3.2987061671737345 L 237.01747885758147,1.2021664452666063 M 235.37086230853296,3.2987061671737345 L 234.3785139238425,0.8244245444523002
> ```

嗯嗯，我来看看，应该是之前写法有问题。
