### ISSUE TITLE
Tooltip、Brush 等交互在 shadow dom 内失效

### ISSUE THREAD

**Issue by lvren** [antvis/G2#6201]
### 问题描述

Tooltip、Brush 等交互在 shadow dom 内失效

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by pearmini** [comment]
@lvren 方便提供一个复现 demo 吗？看看 G2 的版本是多少。

**Comment by lvren** [comment]
> @lvren 方便提供一个复现 demo 吗？看看 G2 的版本是多少。

@pearmini 不太方便复现 Demo，我是在开启 shadow dom 的微应用内使用的。可以尝试下用 web componet 一类的开启  shadow dom 的节点内使用。
版本是 5.1.18

**Comment by hustcc** [comment]
应该是相同问题：https://github.com/antvis/G2/issues/6213
