### ISSUE TITLE
设置x轴刻度数无效

### ISSUE THREAD

**Issue by luobin365304** [antvis/G2#6204]
### 问题描述

x轴为日期字符串，设置x轴刻度数无效

### 预期行为

x轴安卓设置的刻度数进行等分

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G2/assets/33414842/18b08bbe-1c94-4682-a0cb-7cad77fd5776)
![image](https://github.com/antvis/G2/assets/33414842/8d1ed63d-7e10-45c9-92d2-974942b9c64d)

**Comment by pearmini** [comment]
```js
chart.line().encode('x', d => new Date(d.time))
```
