### ISSUE TITLE
请问legend有没有类似echarts的selected的option?

### ISSUE THREAD

**Issue by onecorner** [antvis/g2#621]
如图，我想达到如上的效果，legend的部分显示，因为q全部显示，整个tooltip会被拉的很长，如果用echarts的话，又一个selectedItem的option，请问咱们的组件有类似的选项或者说配置吗？

**Comment by leungwensen** [comment]
用 chart.filter 接口： https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_filter

**Comment by leungwensen** [comment]
请提供 G2 版本、复现的代码（ codepen ）

**Comment by onecorner** [comment]
G2 Version: 3.0.0-beta6，
https://codepen.io/onecorner/pen/WJdewO
直接都不显示了

**Comment by leungwensen** [comment]
你可以打印一下实际的数据看看。执行了 DataSet 的 fold 之后，数据里已经没有那些 key 了，只有 type， value 和 date 三个字段

**Comment by leungwensen** [comment]
你要加的其实只有这一句： 

```js
chart.filter('area', val => parseInt(val) > 0);
```

**Comment by onecorner** [comment]
额，如你所说,不过还是不行！而且发现有个问题，我打印出来的val是key不是key对应的value。。。。
