### ISSUE TITLE
在shadow dom里，并且在多层容器下，tooltip位置出现偏离

### ISSUE THREAD

**Issue by SailorF** [antvis/G2#6213]
### 问题描述
在 shadow-dom 中，发现如果只有一个节点的情况下，Chart 的 tooltip 位置是正常的； 但是如果 Chart 位于多个容器下， tooltip 的位置就会出现偏移

### 复现地址
[复现地址](https://codesandbox.io/p/sandbox/jolly-tereshkova-gtzd5q?file=%2Findex.tsx%3A1%2C1-104%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvlruhxx00063b6nmiburwxu%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvlruhxx00023b6nikawpd3v%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvlruhxx00033b6no4trfsrw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvlruhxx00053b6nznlryvtl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvlruhxx00023b6nikawpd3v%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvlruhxw00013b6n1ae8q6x4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvlrv9v4003u3b6nr8mg9xol%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A23%252C%2522endLineNumber%2522%253A1%252C%2522endColumn%2522%253A23%257D%255D%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvlsmmz300023b6n9je2kks0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A86%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A86%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252FTextElement.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvlt2y2v00023b6i7ngim4sb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A104%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvlruhxx00023b6nikawpd3v%2522%252C%2522activeTabId%2522%253A%2522clvlt2y2v00023b6i7ngim4sb%2522%257D%252C%2522clvlruhxx00053b6nznlryvtl%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvlruhxx00043b6nymyyuu4x%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvlruhxx00053b6nznlryvtl%2522%252C%2522activeTabId%2522%253A%2522clvlruhxx00043b6nymyyuu4x%2522%257D%252C%2522clvlruhxx00033b6no4trfsrw%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvlruhxx00033b6no4trfsrw%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### 复现步骤

 - 鼠标移入上面 Chart 中，发现 tooltip 是正常的
 - 鼠标移入下面 Chart 中，发现 tooltip 是偏离的

### 复现录屏

https://github.com/antvis/G2/assets/24806389/b29212a8-0898-46c1-9ded-1da532d28d92

**Comment by SailorF** [comment]
@pearmini Help

**Comment by pearmini** [comment]
@SailorF 这个应该是拾取出了点问题，@xiaovier 有空帮忙看看嘛？

**Comment by xiaoiver** [comment]
G2 会设置 `supportsCSSTransform` 为 true，确实是 G 的 bug
复现方法也很简单：
https://codesandbox.io/p/sandbox/g-webcomponent-forked-667d4w?file=%2Findex.ts%3A44%2C2

**Comment by xiaoiver** [comment]
已发布：[@antv/g@6.0.4](https://github.com/antvis/G/releases/tag/%40antv%2Fg%406.0.4)
