### ISSUE TITLE
【🙋提问】添加tooltip的shared: true后，tootilp部分item的name自动变为series的值

### ISSUE THREAD

**Issue by hewitt99** [antvis/G2#6228]
### 问题描述

数据中通过measureName字段进行分组，希望同x值的图形共享一个tootip，添加shared字段后，发现tooltip.item的name自动变为了series的值。
请问是代码姿势不对吗？我应该如何解决呢？

### 重现链接

https://stackblitz.com/edit/react-g3sv8h?file=src%2Findex.js

### 重现步骤

![66E37F3E-FDC4-4F80-A105-E2E6BFBDBD17](https://github.com/antvis/G2/assets/81789871/036dc54e-6a2a-4630-81b8-b62880f92ca9)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by pearmini** [comment]
添加一下 groupName: false 的配置：

```js
chart
  .interaction('tooltip', {
    shared: true,
    groupName: false,
  })
  .interaction('elementHighlight', { background: true });
```
