### ISSUE TITLE
圆角柱状图显示与实际数据不同

### ISSUE THREAD

**Issue by YanYuanFE** [antvis/g2#624]
* **G2 Version**: 3.0.0
* **Platform**: PC
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/17774285/39853048-7999f3e0-5452-11e8-8908-1b70279621b8.png)
![image](https://user-images.githubusercontent.com/17774285/39853058-8cba2cce-5452-11e8-93ad-d134c02ca1d8.png)

* **CodePen Link**:
registerShape = () => {
    G2.Shape.registerShape('interval', 'borderRadius', {
      draw(cfg, container) {
        const points = cfg.points;
        let path = [];
        path.push(['M', points[0].x, points[0].y]);
        path.push(['L', points[1].x, points[1].y]);
        path.push(['L', points[2].x, points[2].y]);
        path.push(['L', points[3].x, points[3].y]);
        path.push('Z');
        path = this.parsePath(path); // 将 0 - 1 转化为画布坐标
        return container.addShape('rect', {
          attrs: {
            x: path[1][1] + (path[2][1] - path[1][1]) / 2 - 5, // 矩形起始点为左上角
            y: path[1][2],
            width: 10, // (path[2][1] - path[1][1]) / 2
            height: path[0][2] - path[1][2],
            fill: cfg.color,
            radius: 5
          }
        });
      }
    });
  };

draw = data => {
    console.log(data);
    const dv = new View();
    const { containerId } = this.props;
    dv.source(data);

    const maxdata = _.maxBy(data, function(item) {
      return item.expected;
    });
    const customInterval = _.divide(maxdata.expected, 10);
    // 将数据以10等分来区分刻度如果小于10等分则刻度为1
    const tickInterval = customInterval > 1 ? _.floor(customInterval) : 1;

    // if (this.chart) {
    //   this.chart.destroy();
    //
    //   this.chart = null;
    // }
    this.chart = new G2.Chart({
      container: containerId,
      forceFit: true,
      height: 400,
      padding: [20, 0, 50, 50]
    });
    this.chart.source(dv, {
      expected: {
        tickInterval: tickInterval,
        alias: '催收语音'
      },
      actual: {
        tickInterval: tickInterval,
        alias: '有效催收语音'
      }
    });
    this.chart.axis('actual', false);
    this.chart.axis('expected', {
      line: null,
      title: null,
      tickLine: null,
      labels: {
        label: {
          stroke: '#ccc'
        }
      },
      grid: {
        line: {
          stroke: '#ccc',
          lineDash: [6, 4]
        }
      },
      position: 'left',
    });
    this.chart.axis('city', {
      line: {
        lineWidth: 2,
        stroke: '#dee3e6'
      },
      label: {
        offset: 20,
        textStyle: {
          textAlign: 'center',
          fill: '#485465',
          fontSize: '12'
        }
      }
    });
    this.chart.legend({
      custom: 'true',
      clickable: false,
      useHtml: true,
      position: 'top',
      marker: 'circle',
      textStyle: {
        fill: '#37474f',
        fontSize: '14'
      },
      items: [
        {
          value: '有效催收语音',
          marker: { symbol: 'circle', fill: '#2ACD8F', radius: 5 }
        },
        {
          value: '催收语音',
          marker: { symbol: 'circle', fill: '#D4F5E9', radius: 5 }
        }
      ],
      containerTpl:
        '<div class="g2-legend">' +
        '<div class="g2-legend-list"></div>' +
        '</div>',
      itemTpl: (value, color, checked, index) => {
        checked = checked ? 'checked' : 'unChecked';
        return (
          '<div class="g2-legend-list-item item-' +
          index +
          ' ' +
          checked +
          '" data-value="' +
          value +
          '" data-color=' +
          color +
          ' style="cursor: pointer;font-size: 14px;">' +
          '<div><div><i class="g2-legend-marker" style="width:13px;height:13px;display:inline-block;margin-right:10px;background-color:' +
          color +
          ';"></i>' +
          '<span class="g2-legend-text">' +
          value +
          '</span></div></div>' +
          '</div>'
        );
      }
    });
    this.chart
      .interval()
      .position('city*expected')
      .color('#D4F5E9')
      .shape('borderRadius')
      .opacity(0.6)
      .tooltip('expected');
    this.chart
      .interval()
      .position('city*actual')
      .color('#2ACD8F')
      .shape('city*actual', function(item, val) {
        if (val === 0) {
          return false;
        }
        return 'borderRadius';
      })
      .tooltip('actual');
    this.chart.render();
  };`
`

**Comment by leungwensen** [comment]
那是因为你 Y 轴用了两个不同的字段（actual 和 expected），不同字段计算 scale 是不一样的。你可以先用 DataSet 的 fold transform 转换成一个字段，再画
