### ISSUE TITLE
当柱形图坐标系transpose为条形图时,x轴方向的slider和滚动事件冲突,滚动可以触发slider滚动但不生效

### ISSUE THREAD

**Issue by qtj4js** [antvis/G2#6247]
### 问题描述

如title所述
并且该现象在移动端更为严重,移动端条形图无法使用缩略轴

### 重现步骤

可以直接在官网示例通过如下配置复现:
import { Chart } from "@antv/g2";

const chart = new Chart({ container: "container" });

chart.options({
  type: "interval",
  autoFit: true,
  data: {
    type: "fetch",
    value:
      "https://gw.alipayobjects.com/os/bmw-prod/fb9db6b7-23a5-4c23-bbef-c54a55fee580.csv",
    format: "csv",
  },
  encode: { x: "letter", y: "frequency" },
  transform: [{ type: "sortX", reverse: true }],
  coordinate: { transform: [{ type: "transpose" }] },
  axis: { y: { labelFormatter: ".0%" } },
  slider: {
    x: {
    }
  },
  labels: [
    {
      text: "frequency",
      formatter: ".1%",
      textAlign: (d) => (+d.frequency > 0.008 ? "right" : "start"),
      fill: (d) => (+d.frequency > 0.008 ? "#fff" : "#000"),
      dx: (d) => (+d.frequency > 0.008 ? -5 : 5),
    },
  ],
});

chart.render();

拖动滚动轴,发现浏览器自带滚动事件和缩略轴滚动事件冲突

### 预期行为

预期: 
浏览器滚动事件不影响缩略轴滚动
实际:
互相影响

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G2/assets/47909978/c00c2ec5-30be-446f-8dd3-eb05c8788926)

**Comment by lxfu1** [comment]
`scrollable: false`
