### ISSUE TITLE
进行groupX聚合运算的图表，添加对应属性的数据标签label显示不正确

### ISSUE THREAD

**Issue by CODPHISH** [antvis/G2#6248]
### 问题描述

![image](https://github.com/antvis/G2/assets/65693818/c3a3b7c6-590c-4932-979f-a6a7f03fa4b4)
如图中所示，官方示例中仅添加.label({text: 'price'})，数据标签显示的仍是原始数据，而非聚合后的数据

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by pearmini** [comment]
这应该是一个 bug，我看看有没有办法解决。

**Comment by pearmini** [comment]
@CODPHISH 这个 PR https://github.com/antvis/G2/pull/6250 引入了新的 API 解决了这个问题：

```js
chart.interval().label({ 
  text: (d, i, data, channels) => channels.y[i]
})
```
