### ISSUE TITLE
为什么文档里找不到很多示例里所用的代码呀

### ISSUE THREAD

**Issue by ccinos** [antvis/g2#625]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

比如transform.tree 、getAllNodes、 getAllLinks之类，

**Comment by leungwensen** [comment]
树布局、网图布局这些，其实是为了验证 G2 能力的边界。推荐使用 G6 来画这些图，所以不加上相关的文档，以免带来后续使用和维护的问题
