### ISSUE TITLE
图与图之间的toolTip效果不一致

### ISSUE THREAD

**Issue by Sharang-heng** [antvis/G2#6259]
### 问题描述

条形图
https://g2.antv.antgroup.com/zh/examples/general/interval/#bar-basic-transposed
![image](https://github.com/antvis/G2/assets/69613396/5c98978c-d1ea-4956-9408-97dc1ef47cfa)
饼图
https://g2.antv.antgroup.com/zh/examples/general/pie/#donut-base
![image](https://github.com/antvis/G2/assets/69613396/a9f3ef0b-df4c-483f-9cb3-2b17ede91ba6)
拿的都是官网的链接，我希望能统一一下，我目前的需求是想和饼图的保持一致，不需要条形图的title

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by pearmini** [comment]
不同的图确实有不同的表现，如果不希望展示 title，可以设置 chart.interval().tooltip({title: null})
