### ISSUE TITLE
切换时候图表需要重绘

### ISSUE THREAD

**Issue by JulesCesar** [antvis/g2#627]
能否说一下重绘？的方法？ chart.source（）？

**Comment by dxq613** [comment]
有两种方案：
* chart.changeData(data) 重新更改一下数据就行了。
* 清除掉原先的，重新绘制， chart.clear(); chart.source(data); chart.interval()... 重新声明语法,再 chart.render()

**Comment by leungwensen** [comment]
hart.changeData(data)  会自动重绘
