### ISSUE TITLE
怎么让背景也能被hover？

### ISSUE THREAD

**Issue by lbqdly** [antvis/G2#6272]
### 问题描述

<img width="1188" alt="chart3" src="https://github.com/antvis/G2/assets/14069313/1608261d-c0fd-431e-bd0b-c3b795540ceb">

目前是不是只能hover红色区域，如何也让蓝色区域能够被hover？

### 重现步骤

条形图

### 预期行为

期望：让蓝色区域能够被hover，
现状：只有红色区域能被hover

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

<img width="1188" alt="chart3" src="https://github.com/antvis/G2/assets/14069313/70f34aa1-c01e-4023-aaf2-032c2408e7c6">

**Comment by hustcc** [comment]
同类问题 https://github.com/antvis/G2/issues/6257
