### ISSUE TITLE
【G2 多轴图】多个柱形+一个折线共用横坐标轴，tooltip框内容显示错误

### ISSUE THREAD

**Issue by RobinJason** [antvis/G2#6273]
### 问题描述

需求是要把多个柱子放在同一位置进行展示，方便比较柱子之间的差距，同时加上折线图显示百分比值。
目前问题出现在柱子两侧的tooltip上，正常情况下应该显示四个值，但是只显示了两个值，值出现的规律与柱形图注册顺序相关。
比如折线图是w，柱形图的注册顺序是：a，b，c。
在柱子左侧会显示：w、a。
柱子中间会显示：w、a、b、c。
在柱子右侧会显示：w、c

### 重现链接

https://stackblitz.com/edit/vitejs-vite-ze2cao?file=src%2Findex.js

### 重现步骤

1、将鼠标放在重现链接内的柱子左侧
![1](https://github.com/antvis/G2/assets/19620894/8c6efaaf-5797-41f1-9f45-d18210858b55)
2、顺着从左往右的方向继续滑动
![2](https://github.com/antvis/G2/assets/19620894/1c920b7c-fdc4-4149-919b-d8d5698f3031)
3、直到到达柱子右侧
![3](https://github.com/antvis/G2/assets/19620894/23986333-8597-411c-b8c3-f105468bf14e)

### 预期行为

期望无论是在哪个位置，都可以完整的显示y轴的值

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 补充说明（可选）

![image](https://github.com/antvis/G2/assets/19620894/9fef9ee8-772f-494d-a2b1-124989c14b33)

**Comment by amzfcy** [comment]
同，请问解决了吗

**Comment by pearmini** [comment]
@amzfcy  https://github.com/antvis/G2/pull/6295 解决了这个问题，过几天会发布

**Comment by RobinJason** [comment]
> @RobinJason @amzfcy #6295 解决了这个问题，过几天会发布

感谢修复🙏

**Comment by RobinJason** [comment]
> 同，请问解决了吗

我更新到了5.1.23版本，打开看已经OK了，发布的应该是这个版本，你也更新试试看吧
