### ISSUE TITLE
G2 官网增加 demo 案例

### ISSUE THREAD

**Issue by hustcc** [antvis/G2#6276]
![image](https://github.com/antvis/G2/assets/7856674/ae8ac3c5-be74-4e67-be55-a12d781aea32)

实现原理是通过两个 view 去叠加，背景效果不可交互即可。

**Comment by the-lemonboy** [comment]
这个可以我来做吗？ 目前有案例的数据吗？

**Comment by pearmini** [comment]
@the-lemonboy 非常欢迎！数据你可以自己 mock，或者官网上找相似的，或者通过 GPT 提取上面图片里面的数据！

**Comment by pearmini** [comment]
@the-lemonboy 不过这里不用“两个 view 去叠加“，可以直接用 range Mark，参考这个例子：https://g2.antv.antgroup.com/examples/annotation/line/#quadrant-scatter
