### ISSUE TITLE
Geom().hide()/show() not working

### ISSUE THREAD

**Issue by zhouyanggodking** [antvis/g2#629]
G2 Version 3.0.11:

reproduce step:

after created a line chart, just draw some points too. using:
const point= chart.point().position('x*y');

but when I want to hide/show these points, error occurred.
point.hide();

I just followed the document [here](https://antv.alipay.com/zh-cn/g2/3.x/api/geom.html#_show-%E6%98%BE%E7%A4%BA%EF%BC%8C%E9%BB%98%E8%AE%A4-geometry-%E6%98%BE%E7%A4%BA%EF%BC%8C%E5%A6%82%E6%9E%9C%E5%9C%A8%E5%88%9B%E5%BB%BA-geometry-%E6%97%B6%E8%AE%BE%E7%BD%AE-visible:-false)

But it's not working.

it seems that it throws errors.

you can quick use this demo page to test it.
https://antv.alipay.com/zh-cn/g2/3.x/demo/line/basic.html

**Comment by leungwensen** [comment]
You can call `point.hide()` after `chart.render()`. We will fix this.
