### ISSUE TITLE
饼图中心文本支持 html

### ISSUE THREAD

**Issue by juanhuang99** [antvis/G2#6293]
### 问题描述

![image](https://github.com/antvis/G2/assets/29769760/4e9f5ec4-3d7e-48be-8abc-841be68b58db)

中心文本目前只能传字符串，希望能支持html，实现上面的效果

![image](https://github.com/antvis/G2/assets/29769760/82bd588c-f298-4f79-bb49-3ce7370f0e77)

**Comment by hustcc** [comment]
[中级任务]

实现方式，对于 text mark 类型，增加一个 html 类型的 shape，然后可以使用 G.Html 组件渲染。参考：src/shape/text/text.ts

**Comment by hustcc** [comment]
```ts
.label({
  render: () => '<div>aaa</div>',
});
```

**Comment by airandou** [comment]
鼠标悬浮在图上时，中心文本内容动态改变，如何实现
