### ISSUE TITLE
Miss params on plotclick

### ISSUE THREAD

**Issue by yubozhao** [antvis/g2#63]
When click a chart, I expect following params
``` data: object, // 当前被点击的数据，存储的是经过映射处理的数据，原始的数据通过 data._origin 字段获取
  geom: object, // 被点击的几何标记对象
  shape: object, // 被点击的几何形状对象
  target: object, // 被点击的 canvas 元素
  toElement: htmlElement, // 目标 dom 元素
  views: array, // 当前被点击区域所在的视图
  x: number, // 鼠标点击的 x 坐标点
  y: number
```
For my react project, I received:
```
target: c
toElement: canvas#canvas_6
views: Array(1)
x: 333.578125
y: 63
```

Any help?  I am using g2  v2.2.0

**Comment by simaQ** [comment]
only if the mouse click on the geometry shape that we return `geom` and `shape`.  

![snip20161229_3](https://cloud.githubusercontent.com/assets/6628666/21534727/16c3669a-cda6-11e6-986d-9c5a24440457.png)
