### ISSUE TITLE
区域过滤颜色存在一些问题

### ISSUE THREAD

**Issue by dxq613** [antvis/g2#630]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

* 折线图的临界点会出现半像素的问题
* 柱状图的 min,max 不能到边缘
* 颜色覆盖时出现锯齿
* tooltip 的颜色是否随着数据的大小变化

**Comment by dxq613** [comment]
https://riddle.alibaba-inc.com/riddles/8881caaf

**Comment by paleface001** [comment]
好的，再优化一下
