### ISSUE TITLE
整个图表视图的字体像是蒙上一个蒙层 不太清晰，如图

### ISSUE THREAD

**Issue by yikai89827** [antvis/G2#6311]
### 问题描述

![image](https://github.com/antvis/G2/assets/55533597/b99d2e70-458a-4845-9ce8-9e76942e1567)

### 预期行为

字体清晰

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by yikai89827** [comment]
白色字体看着跟灰色一样

**Comment by pearmini** [comment]
设置 chart.axis('x', { labelFillOpacity: 1, labelStrokeOpacity: 1, labelOpacity: 1})，y 轴同理

**Comment by yikai89827** [comment]
> 设置 chart.axis('x', { labelFillOpacity: 1, labelStrokeOpacity: 1, labelOpacity: 1})，y 轴同理

感谢
