### ISSUE TITLE
带气泡的地图 legend 颜色没有和geom的颜色保持一致，地图模块需自动保持一致

### ISSUE THREAD

**Issue by heiniuhaha** [antvis/g2#632]
https://antv.alipay.com/zh-cn/g2/3.x/demo/map/bubble-map.html

![image](https://user-images.githubusercontent.com/668144/40099256-d891d57a-5911-11e8-99c6-3d0c7635b8c4.png)

**Comment by dxq613** [comment]
只有加了字段映射才会生成图例，你可以给你的颜色加个字段映射

```js
pointView.point().position('x*y')
      .shape('circle')
      .opacity(0.45)
      .color('deaths','#FFFFFF-#FF2F29')
      .size('deaths', [2, 30])
      .tooltip('date*location*lat*lng*deaths*magnitude');

```

![image](https://user-images.githubusercontent.com/1264678/40170721-c8526978-59fb-11e8-9f33-780bbb33ab36.png)

* 如果感觉起始的颜色太淡的话，可以自己取个较深的红色

**Comment by leungwensen** [comment]
嗯嗯，这是因为图例之前是 size 这个字段映射得来的，所以是默认的颜色。像萧庆哥的写法就是由颜色映射生成的 legend 了。 @heiniuhaha
