### ISSUE TITLE
柱形图间距问题

### ISSUE THREAD

**Issue by Dog-Lee** [antvis/g2#634]
`
chart = new G2.Chart({
   container: 'userChart',
   forceFit: true,
   height: 350,
})
chart.source(res.data.list);
chart.interval().position('date*count');
chart.render();`
![antv](https://user-images.githubusercontent.com/20838671/40120916-e543f884-5952-11e8-95ff-9bddb8d9230c.png)

**Comment by leungwensen** [comment]
date 字段数据格式是怎么样的？试试 `chart.scale('date', { type: 'timeCat' })`
