### ISSUE TITLE
官方示例中toolTip为false为什么还会有悬浮框显示

### ISSUE THREAD

**Issue by Sharang-heng** [antvis/G2#6345]
### 问题描述

![image](https://github.com/antvis/G2/assets/69613396/b11d94c7-ad76-4086-ba0d-a97b441b07c3)

### 重现链接

https://g2.antv.antgroup.com/examples/general/line#base

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by hustcc** [comment]
```ts
chart.interaction('tooltip', false)
```

interaction 的 tooltip 才是决定 ui 的，mark（point、line 等） API 中的 tooltip 是用来决定数据的。
