### ISSUE TITLE
柱折组合图。.scale('series', { independent: true })表示含义是什么

### ISSUE THREAD

**Issue by Calmio-Y** [antvis/G2#6349]
### 问题描述

import { Chart } from '@antv/g2';

const chart = new Chart({
  container: 'container',
  autoFit: true,
});

const data = [
  { time: '10:10', call: 4, waiting: 2, people: 2 },
  { time: '10:15', call: 2, waiting: 6, people: 3 },
  { time: '10:20', call: 13, waiting: 2, people: 5 },
  { time: '10:25', call: 9, waiting: 9, people: 1 },
  { time: '10:30', call: 5, waiting: 2, people: 3 },
  { time: '10:35', call: 8, waiting: 2, people: 1 },
  { time: '10:40', call: 13, waiting: 1, people: 2 },
];

chart.data(data);

chart
  .interval()
  .encode('x', 'time')
  .encode('y', 'waiting')
  .encode('color', () => 'waiting')
  .encode('series', () => 'waiting')
  .axis('y', { title: 'Waiting' })
  .scale('y', { nice: true });

// chart
//   .interval()
//   .encode('x', 'time')
//   .encode('y', 'people')
//   .encode('color', () => 'people')
//   .encode('series', () => 'people')
//   .scale('y', { independent: true })
//   .axis('y', { position: 'right', grid: null, title: 'People' });

chart
  .line()
  .encode('x', 'time')
  .encode('y', 'call')
  .encode('color', () => 'call') 
  .scale('series', { independent: true });

chart.render();

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

![image](https://github.com/antvis/G2/assets/30626950/f836b95a-a7ac-4f98-882e-078b79bb3a6e)

![image](https://github.com/antvis/G2/assets/30626950/a1c23a23-9f28-484b-bea0-43ff3aee9dbe)

### 补充说明（可选）

示例代码：
三个图混合tooltip显示正常
二个图混合tooltip显示异常
.scale('series', { independent: true })意义是什么？

**Comment by interstellarmt** [comment]
.scale('series', { independent: true })的含义是

**Comment by interstellarmt** [comment]
如果希望不同步（比如绘制双轴图的时候），就需要设置 scale.independent 为 true，设置了该属性的比例尺不会和任何比例尺同步。

**Comment by interstellarmt** [comment]
- 第一个问题
https://g2.antv.antgroup.com/manual/core/scale#%E6%AF%94%E4%BE%8B%E5%B0%BA%E4%B8%8D%E5%90%8C%E6%AD%A5
如果希望不同步（比如绘制双轴图的时候），就需要设置 scale.independent 为 true，设置了该属性的比例尺不会和任何比例尺同步
这里的.scale('series', { independent: true })含义是折线图series通道的比例尺不和任何比例尺同步，因为这里的两个柱状图为了分组使用了series通道。

- 第二个问题
二个图混合 折柱混合参考https://g2.antv.antgroup.com/zh/examples/general/dual/#line-bar
因为不涉及分组，所以没有设置series通道，只需要设置折线图y通道的比例尺不和任何比例尺同步  .scale('y', { independent: true })

**Comment by interstellarmt** [comment]
多轴图双轴图的用法之后会有更详细的文档，敬请期待～
