### ISSUE TITLE
使用3.x版本绘制中国地图省份的位置计算有偏差 坐标轴设定失效 求解答

### ISSUE THREAD

**Issue by muyucanqiu** [antvis/g2#636]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

使用3.x版本绘制中国地图省份的位置计算有偏差 使用chart.axis取消显示坐标轴不起作用 求解答
![map](https://user-images.githubusercontent.com/15388391/40128514-6397d154-5964-11e8-8391-302ff8a03c7e.jpg)
``

**Comment by leungwensen** [comment]
- 同步两个 view 的字段：

```js
    chart.scale({
        latitude: { sync: true, nice: false },
        longitude: { sync: true, nice: false }
    });
```

-     chart.axis(false);

参考官网的实例。另外，最好提供一下代码（codepen 链接等），否则定位问题效率太低

**Comment by muyucanqiu** [comment]
感谢回复。但是3.x的版本和2.x的对比 省份名字明显都有向上偏移 计算不准确。
`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>中国地图</title>
    <script src="chinaMap2.js"></script>
    <script src="g2.js"></script>
    <script src="dataSet.js"></script>
  </head>
  <body>
    <div id="c1" style="width:1000px"></div>
    <script>
    var maxNumber = 0;
    var minNumber = 999999999;
    var features = mapData.features;
    var bgData = []; // 用于地图背景层的绘制
    var usersData = [{"name":"甘肃","value":1,"per":"1%"},{"name":"青海","value":1,"per":"1%"},{"name":"广西","value":1,"per":"1%"},{"name":"贵州","value":1,"per":"1%"},{"name":"重庆","value":1,"per":"1%"},{"name":"北京","value":1,"per":"1%"},{"name":"福建","value":1,"per":"1%"},{"name":"安徽","value":1,"per":"1%"},{"name":"广东","value":1,"per":"1%"},{"name":"西藏","value":1,"per":"1%"},{"name":"新疆","value":1,"per":"1%"},{"name":"海南","value":1,"per":"1%"},{"name":"宁夏","value":1,"per":"1%"},{"name":"陕西","value":1,"per":"1%"},{"name":"山西","value":1,"per":"1%"},{"name":"湖北","value":1,"per":"1%"},{"name":"湖南","value":1,"per":"1%"},{"name":"四川","value":1,"per":"1%"},{"name":"云南","value":1,"per":"1%"},{"name":"河北","value":1,"per":"1%"},{"name":"河南","value":1,"per":"1%"},{"name":"辽宁","value":1,"per":"1%"},{"name":"山东","value":1,"per":"1%"},{"name":"天津","value":1,"per":"1%"},{"name":"江西","value":1,"per":"1%"},{"name":"江苏","value":1,"per":"1%"},{"name":"上海","value":1,"per":"1%"},{"name":"浙江","value":1,"per":"1%"},{"name":"吉林","value":1,"per":"1%"},{"name":"内蒙古","value":1,"per":"1%"},{"name":"黑龙江","value":1,"per":"1%"},{"name":"台湾","value":0,"per":""},{"name":"香港","value":0,"per":""},{"name":"澳门","value":0,"per":""},{"name":"南海诸岛","value":0,"per":""}]; 
    for(var i=0; i<features.length; i++) {
        var name = features[i].properties.name;
        bgData.push({
            'name': name
        });
    }

    var chart = new G2.Chart({
        id: 'c1',
        forceFit: true,
        height: 760
    });
    var ds = new DataSet();
    var chinaMap = ds.createView().source(mapData, {
        type: 'GeoJSON'
    });

    chart.legend(false);
    chart.tooltip(true, {
        showTitle: false
    });
    chart.scale({
        latitude: { sync: true, nice: false },
        longitude: { sync: true, nice: false }
    });
    chart.axis(false);
    //绘制展示数据
    var userDv = ds.createView().source(usersData).transform({
        geoDataView: chinaMap,
        field: 'name',
        type: 'geo.region',
        as: ['longitude', 'latitude']
    })

    let defs = {
        'name': {
            alias: '省份',
        },
        'value': {
            alias: '数量'
        },
        'per': {
            alias: '占比'
        }
    }

    var userView = chart.view();
    userView.source(userDv, defs);
    userView.polygon().position('longitude*latitude')
    .tooltip('name*per')
    .label('name', {textStyle: {fill: '#8C4817', shadowBlur: 5, shadowColor: '#fff'}})
    .style({
        stroke: '#333',
        lineWidth: 1
    });

    G2.track(false);
    chart.render();
    </script>
  </body>
</html>
`
mapData数据源自官网下载[http://antvis.github.io/static/data/china.json](url)

**Comment by muyucanqiu** [comment]
感谢回复 但是3.x版本和2.x版本相比省份名称位置明显偏上，计算有偏差。
`var maxNumber = 0;
    var minNumber = 999999999;
    var features = mapData.features;
    var bgData = []; // 用于地图背景层的绘制
    var usersData = [{"name":"甘肃","value":1,"per":"1%"},{"name":"青海","value":1,"per":"1%"},{"name":"广西","value":1,"per":"1%"},{"name":"贵州","value":1,"per":"1%"},{"name":"重庆","value":1,"per":"1%"},{"name":"北京","value":1,"per":"1%"},{"name":"福建","value":1,"per":"1%"},{"name":"安徽","value":1,"per":"1%"},{"name":"广东","value":1,"per":"1%"},{"name":"西藏","value":1,"per":"1%"},{"name":"新疆","value":1,"per":"1%"},{"name":"海南","value":1,"per":"1%"},{"name":"宁夏","value":1,"per":"1%"},{"name":"陕西","value":1,"per":"1%"},{"name":"山西","value":1,"per":"1%"},{"name":"湖北","value":1,"per":"1%"},{"name":"湖南","value":1,"per":"1%"},{"name":"四川","value":1,"per":"1%"},{"name":"云南","value":1,"per":"1%"},{"name":"河北","value":1,"per":"1%"},{"name":"河南","value":1,"per":"1%"},{"name":"辽宁","value":1,"per":"1%"},{"name":"山东","value":1,"per":"1%"},{"name":"天津","value":1,"per":"1%"},{"name":"江西","value":1,"per":"1%"},{"name":"江苏","value":1,"per":"1%"},{"name":"上海","value":1,"per":"1%"},{"name":"浙江","value":1,"per":"1%"},{"name":"吉林","value":1,"per":"1%"},{"name":"内蒙古","value":1,"per":"1%"},{"name":"黑龙江","value":1,"per":"1%"},{"name":"台湾","value":0,"per":""},{"name":"香港","value":0,"per":""},{"name":"澳门","value":0,"per":""},{"name":"南海诸岛","value":0,"per":""}]; 
    for(var i=0; i<features.length; i++) {
        var name = features[i].properties.name;
        bgData.push({
            'name': name
        });
    }

    var chart = new G2.Chart({
        id: 'c1',
        forceFit: true,
        height: 760
    });
    var ds = new DataSet();
    var chinaMap = ds.createView().source(mapData, {
        type: 'GeoJSON'
    });

    chart.legend(false);
    chart.tooltip(true, {
        showTitle: false
    });
    chart.scale({
        latitude: { sync: true, nice: false },
        longitude: { sync: true, nice: false }
    });
    chart.axis(false);
    //绘制展示数据
    var userDv = ds.createView().source(usersData).transform({
        geoDataView: chinaMap,
        field: 'name',
        type: 'geo.region',
        as: ['longitude', 'latitude']
    })

    let defs = {
        'name': {
            alias: '省份',
        },
        'value': {
            alias: '数量'
        },
        'per': {
            alias: '占比'
        }
    }

    var userView = chart.view();
    userView.source(userDv, defs);
    userView.polygon().position('longitude*latitude')
    .tooltip('name*per')
    .label('name', {textStyle: {fill: '#8C4817', shadowBlur: 5, shadowColor: '#fff'}})
    .style({
        stroke: '#333',
        lineWidth: 1
    });

    G2.track(false);
    chart.render();`
mapData数据来自官网[http://antvis.github.io/static/data/china.json](url)
