### ISSUE TITLE
分组条形图提示错误

### ISSUE THREAD

**Issue by yangmg233** [antvis/G2#6362]
### 问题描述

![image](https://github.com/user-attachments/assets/7dfe2791-200e-4b16-bff7-ba4a04008cc6)
官方示例中条形图提示错误什么时候能修复

### 重现步骤

官方图表示例：简单分组柱形图

### 预期行为

能正确提示数据信息

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by pearmini** [comment]
这个不是 bug，如果希望达到期望效果，如下：

```js
  .interaction("tooltip", { shared: true });
```
