### ISSUE TITLE
chrome 85版本 配置了polyfill之后饼图的tooltip依旧报错

### ISSUE THREAD

**Issue by lichencc** [antvis/G2#6363]
### 问题描述

**使用的是85版本的chrome浏览器，antv/g2版本5.1.18**
访问官网图表示例饼图，鼠标移入显示tooltip时报错，定位是replaceChildren方法报错，该api仅支持到chrome 85 版本以上
在提交记录中找到一个很久之前的feat的faq中显示g2兼容的chrome版本在85之下很多个版本
**并且在我的生产环境中配置了polyfill该api还是报错**
![image](https://github.com/user-attachments/assets/d924db23-770b-4f74-987a-9a7c9c142239)

### 重现步骤

1、进入https://www.browserling.com/，选择chrome85版本
2、访问图表示例https://g2.antv.antgroup.com/examples/general/pie/#pie-base
3、鼠标移入饼图，显示tooltip报错

### 预期行为

配置polyfill之后，在85或更低版本的浏览器能正常显示tooltip。
或是给出浏览器兼容性参考文档

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

![image](https://github.com/user-attachments/assets/afbcf6d0-e1a4-4f32-b383-b14ba2c2ca03)

**Comment by pearmini** [comment]
相同的问题：https://github.com/ant-design/ant-design-charts/issues/2614

**Comment by pearmini** [comment]
我去掉这个方法的使用。

**Comment by lichencc** [comment]
> 我去掉这个方法的使用。

感谢感谢~~

**Comment by lichencc** [comment]
> 我去掉这个方法的使用。

还想问一下，请问修复后是会发布一个新的小版本吗？

**Comment by pearmini** [comment]
@lichencc 嗯嗯，会发一个小版本，更新依赖就好了。

**Comment by lichencc** [comment]
> @lichencc 嗯嗯，会发一个小版本，更新依赖就好了。

好的非常感谢~

**Comment by pearmini** [comment]
@lichencc 

这个 PR 解决了这个问题：https://github.com/antvis/component/pull/319 ，但是 CI 存在一点问题。我这段时间没有办法解决这个问题了 😭，你有空要不来贡献一下，看看能不能解决这个问题？

**Comment by pearmini** [comment]
@lichencc 有开发者已经解决啦，看看他多久提 PR

**Comment by wangxingkang** [comment]
@pearmini  https://github.com/antvis/component/pull/320

**Comment by pearmini** [comment]
@lichencc 可以试试这个版本 @antv/component@2.0.2

**Comment by lichencc** [comment]
> @lichencc 可以试试这个版本 @antv/component@2.0.2

请问这个小版本什么时候可以同步到g2呢。我不太清楚如何直接使用@antv/component@2.0.2版本去测试🥲

**Comment by pearmini** [comment]
@lichencc 重新安装依赖即可。

**Comment by lichencc** [comment]
@pearmini em我的虚拟浏览器85环境只能访问生产环境地址，@antv/component是否有类似antv/g2一样的示例图表地址用来测试呢。而且我看g2内使用的@antv/component还是2.0.0版本，重新安装依赖好像并没有办法测试是否正常

**Comment by pearmini** [comment]
@hustcc 这里可能还需要给 G2 发一个新版本，umd

**Comment by lichencc** [comment]
> @hustcc 这里可能还需要给 G2 发一个新版本，umd

添麻烦了，十分感谢~

**Comment by lichencc** [comment]
> @hustcc 这里可能还需要给 G2 发一个新版本，umd

@pearmini 请问是否有预估的antv/g2新的小版本发布时间呢

**Comment by pearmini** [comment]
@lxfu1 该发一个新版本了，bro

**Comment by hustcc** [comment]
下周发布版本，之前没有修改完全🙁
