### ISSUE TITLE
【V5】legend itemMarker 的内置类型是否可以扩展？

### ISSUE THREAD

**Issue by wangxingkang** [antvis/G2#6368]
### 问题描述

看源码是有 [registerSymbol](https://github.com/antvis/G2/blob/v5/src/utils/marker.ts#L278)  方法的。但是并未导出，是什么考虑？ 

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by pearmini** [comment]
感兴趣提一个 PR 来增加这个功能吗？

**Comment by wangxingkang** [comment]
好的，我提个 PR

**Comment by wangxingkang** [comment]
@pearmini https://github.com/antvis/G2/pull/6381 看下是否可以
