### ISSUE TITLE
G2 V4 的 columnWidthRatio 配置，在 G2 V5 如何实现相似效果

### ISSUE THREAD

**Issue by wangxingkang** [antvis/G2#6386]
### 问题描述

v4 文档 https://g2-v4.antv.vision/zh/docs/api/advanced/register-theme/#%E4%B8%BB%E9%A2%98%E5%B1%9E%E6%80%A7

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by hustcc** [comment]
可以参考这些 demo：

- https://g2.antv.antgroup.com/examples/general/interval/#column-maxwidth
- https://g2.antv.antgroup.com/examples/general/interval#bar-fixed-cornered


@pearmini 我们是否给 interval 的 style 增加一个类似于 columnWidthRatio 的配置，现在是在 scale.padding 配置。

**Comment by wangxingkang** [comment]
@pearmini 这个后续会支持吗

**Comment by pearmini** [comment]
@wangxingkang 可以用 scale.x.padding 来实现，就像 @hustcc 说的一样。文档可以参考 [@antv/scale](https://github.com/antvis/scale/blob/master/docs/api/scales/band.md#options) 的文档。

**Comment by wangxingkang** [comment]
好的，我看下

**Comment by wangxingkang** [comment]
<img width="1135" alt="image" src="https://github.com/user-attachments/assets/7b0ca62f-f2fc-4a57-8ef1-aa85510358ba">
@pearmini 这块的背景有参数设置吗 需求是与蓝色柱状边距 8px

**Comment by wangxingkang** [comment]
@pearmini 有空解答下哈

**Comment by pearmini** [comment]
@wangxingkang  目前背景的宽度是没有办法调整的。

**Comment by wangxingkang** [comment]
好的 有没有相关的思路，通过增加配置解决，我这边尝试一下
