### ISSUE TITLE
如何调整条形图之间的间距

### ISSUE THREAD

**Issue by 37-Ricardo** [antvis/G2#6390]
### 问题描述

我在设置条形图的最大宽度后，发现条形图之间的间距变大了，如何调整条形图之间的间距，使其变得紧凑

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by hustcc** [comment]
> scale.x.padding = 0.5;

@lxfu1 可以把 columnWidthRatio 这个小配置先上了。

**Comment by hustcc** [comment]
https://github.com/antvis/G2/issues/6386
