### ISSUE TITLE
如何绑定颜色

### ISSUE THREAD

**Issue by 37-Ricardo** [antvis/G2#6391]
### 问题描述

文档中的颜色绑定为什么是数组？没法根据状态绑定颜色吗？使用数组绑定也太不严谨了吧，如何根据数组元素中某个字段的值进行颜色绑定？比如，type=0，绑定为蓝色,type=1,绑定为绿色,type=2，绑定为红色

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by tangtang12** [comment]
https://g2.antv.antgroup.com/manual/extra-topics/color
![Uploading WX20240807-172906.png…]()

**Comment by tangtang12** [comment]
https://g2.antv.antgroup.com/manual/extra-topics/color  使用 Relations指定颜色
