### ISSUE TITLE
条形图 坐标上的标签  可以这么实现吗

### ISSUE THREAD

**Issue by wangxingkang** [antvis/G2#6394]
### 问题描述

<img width="796" alt="image" src="https://github.com/user-attachments/assets/8e24fa35-e48b-4b95-9927-3476f31725ab">

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by hustcc** [comment]
可以通过 dx dy 去调整。

**Comment by wangxingkang** [comment]
好的，我试一试

**Comment by wangxingkang** [comment]
```ts
axis: {
      x: {
        size: 0,
        label: false,
        grid: false,
      },
    },
    label: {
      text: 'name',
      position: 'left',
      dy: -15,
    },
```

**Comment by wangxingkang** [comment]
@hustcc 大体效果实现了，要不要写个 demo 放在官网上

**Comment by hustcc** [comment]
> @hustcc 大体效果实现了，要不要写个 demo 放在官网上

来吧，欢迎来一个 PR 👍🏻

**Comment by wangxingkang** [comment]
好的 我这两天实现下
