### ISSUE TITLE
🐞bug: tootltip mount 在 body 上时，如果 chart 容器本身可滚动，tooltip 显示位置

### ISSUE THREAD

**Issue by wjgogogo** [antvis/G2#6399]
### 问题描述

g2 5.2.2在 mount  为 body 时，如果 chart 所在的容器是可以滚动的，在滚动后，tooltip的位置为错位

### 重现步骤

官方demo就能复现：https://g2.antv.antgroup.com/zh/examples/component/tooltip/#tooltip-crosshairs
1. 将 chart 容器增大到可滚动，比如 4000px
2. mount 设置为 body
![image](https://github.com/user-attachments/assets/f63bdd8d-6059-45e7-ad1c-8beaae5e9904)

![2024-08-15 10 00 12](https://github.com/user-attachments/assets/44890715-8b12-4541-af04-ca3431a25dfa)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by vxow** [comment]
一样的问题
