### ISSUE TITLE
饼图动画优化

### ISSUE THREAD

**Issue by wanghui2021** [antvis/G2#6404]
### 问题描述

点击图例时，饼图的显示/隐藏动画不太友好

### 重现链接

https://ant-design-charts.antgroup.com/examples/statistics/pie/#basic

### 重现步骤

1. 进入页面
2. 点击右上角的图例，当显示的图例从三个到两个或者从两个变到一个时，动画不太友好

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

G2:

https://github.com/user-attachments/assets/f4d4a343-018a-47bb-9c33-14c64ddfb957

echrats:

https://github.com/user-attachments/assets/f9c42a04-c4aa-422c-ba1f-5929b63af401

**Comment by hustcc** [comment]
```ts
.animate('enter', { type: 'waveIn' })
.animate('update', { type: 'waveIn' })
```
