### ISSUE TITLE
Transform fold无法展开csv文件的最后一列内容

### ISSUE THREAD

**Issue by tangtangtangtangtang** [antvis/g2#641]
* **G2 Version**:3.0.12
* **Platform**:windows
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
问题出现在CSV文件类型的transform操作fold展开字段，最后一个字段总是无法展开，json型没有出现这类问题。
展开代码：
```
                let fields = keys.slice(1, );
                states.chart.dv.transform({
                    type: method,
                    key: "key",
                    value: 'value',
                    fields,
                })
                keys = [keys[0], 'value', 'key']
                break;
```
dataview展开前的数据:
![image](https://user-images.githubusercontent.com/24206594/40222921-c4493c5e-5ab3-11e8-8b4b-de4970712a39.png)
dataview展开后的数据:
![image](https://user-images.githubusercontent.com/24206594/40222947-dbfec4e0-5ab3-11e8-9dd5-93b554a5bc59.png)
transform配置:
![image](https://user-images.githubusercontent.com/24206594/40222963-ed6b50f4-5ab3-11e8-9cab-a7aef818f0c2.png)

换一个csv文件发生同样的情况，其中”乡村住宅电话“为最后一列数据。同样没有展开，值为undefined
![image](https://user-images.githubusercontent.com/24206594/40223031-2e0ef9da-5ab4-11e8-9f69-e89e0a6dd54c.png)
![image](https://user-images.githubusercontent.com/24206594/40223046-3b69cdc6-5ab4-11e8-9d11-19c0992bf733.png)

**Comment by leungwensen** [comment]
麻烦提供一下重现代码和 csv 原本的内容。CSV 事实上我们是直接用 d3-dsv 模块做 parse 的，也是先转换成 JSON 的形式。你可以在做 transform 之前打印一下 dv.rows 看看原始数据转换有没有问题

**Comment by tangtangtangtangtang** [comment]
代码在这里
https://github.com/tangtangtangtangtang/Data-Visualization-Based-on-AntV/blob/master/react-app/src/components/Graph/industry/industry.js
那个csv文件我也放在根目录了

transform之前的dv.rows是没有问题的
你可以clone一下，server和react-app都install一下，build一下，启动一下项目
![image](https://user-images.githubusercontent.com/24206594/40227174-58a18288-5ac0-11e8-9a79-b1daf7af1a45.png)
“+”号选折线图
![image](https://user-images.githubusercontent.com/24206594/40227208-6b864816-5ac0-11e8-9bd9-8df9ee56936e.png)
打开面板“上传文件”，然后点一下“绘制”就是操作步骤
![image](https://user-images.githubusercontent.com/24206594/40227240-80272e0c-5ac0-11e8-96f3-aabfb06caf29.png)

**Comment by leungwensen** [comment]
你的项目我跑不起来，点上传数据文件的时候提示上传文件失败。你还是打印一下数据看看什么问题吧。fold 没做什么复杂操作，不会出现你说的问题的。。。

**Comment by leungwensen** [comment]
你可以看看 data-set 的源码，可以用 require('@antv/data-set/lib/index') 的方式引入 DataSet，然后调试这个文件 https://github.com/antvis/data-set/blob/master/src/transform/fold.js

**Comment by tangtangtangtangtang** [comment]
首先lodash.difference出错了，导致retain多出来一个字段
![image](https://user-images.githubusercontent.com/24206594/40230987-06d4ae38-5acc-11e8-8ce6-63d2e4cd421a.png)
![image](https://user-images.githubusercontent.com/24206594/40231005-1240c874-5acc-11e8-86cb-e9abc654e3a9.png)
![image](https://user-images.githubusercontent.com/24206594/40231018-1a146b0a-5acc-11e8-89a1-9b1c9f86f6d8.png)
即使多出来一个下面也应该正常运作，就是到最后一个的时候死活读不出值
![image](https://user-images.githubusercontent.com/24206594/40231480-e3bea320-5acd-11e8-8df9-5d85e3cb8ce7.png)
![image](https://user-images.githubusercontent.com/24206594/40231491-eef8d68e-5acd-11e8-822f-99ab82695c9c.png)
怎么说。。。。我如果发现了原因再说吧。。。。

**Comment by leungwensen** [comment]
Closing for no further information is provided
