### ISSUE TITLE
Data  支持语法糖

### ISSUE THREAD

**Issue by lxfu1** [antvis/G2#6421]
### AntV Open Source Contribution Plan（可选）

- [x] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

中级任务

### 任务介绍

新增 `min`、`max`、`median`、`mean `、 `rangeX`、`rangeY` 等语法糖功能。

https://g2-v4.antv.vision/zh/examples/component/annotation#guide-region-filter1

https://g2plot.antv.antgroup.com/examples/line/basic#line-annotation

**Comment by hustcc** [comment]
这个具体是什么？可以在 issue 描述中写清楚。min max 这些似乎不是 Data 的能力。

**Comment by hustcc** [comment]
- 重复 https://github.com/antvis/G2/issues/4572
