### ISSUE TITLE
螺旋坐标系

### ISSUE THREAD

**Issue by lxfu1** [antvis/g2#6423]
### AntV Open Source Contribution Plan（可选）

- [X] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

中级任务

### 任务介绍

参考一下内容提供螺旋坐标系示例

https://g2-v4.antv.vision/zh/examples/column/basic#helix-coordinate

https://observablehq.com/@antv/wow-antv-coord

**Comment by BQXBQX** [comment]
- 基础图
<img width="882" alt="image" src="https://github.com/user-attachments/assets/950e66e7-8def-4433-9d78-25740c7695ec">

- 基因比较图
<img width="724" alt="image" src="https://github.com/user-attachments/assets/e09d7ccd-dc15-4bfa-a244-d3901216846e">

**Comment by hustcc** [comment]
@BQXBQX 

- https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*dLT0TpvlFd4AAAAAAAAAAAAADmJ7AQ/fmt.webp
- https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*oTCKSYpIWBwAAAAAAAAAAAAADmJ7AQ/fmt.webp
