### ISSUE TITLE
分组柱形图表间距怎么调整

### ISSUE THREAD

**Issue by fangbao-0418** [antvis/G2#6429]
### 问题描述

设置柱形宽度后，分组两个柱子间隔很大
![image](https://github.com/user-attachments/assets/8f96830a-b6fd-4a48-b212-10457b11e2f6)

期望效果
![image](https://github.com/user-attachments/assets/a29b0d54-9d7b-4fdd-9b38-a264fe1c6bb4)
这是设置padding后的效果，但是保证不了柱子的宽度了

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by hustcc** [comment]
有一些案例示意图吗？
