### ISSUE TITLE
平滑后折线图，最高点并非真实数据。 贝塞尔曲线拟合是否可以优化？

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#643]
平滑后折线图，最高点并非真实数据。 贝塞尔曲线拟合是否可以优化？

![image](https://user-images.githubusercontent.com/3838676/40302070-8c087caa-5d20-11e8-81df-9f1298e272dc.png)

**Comment by dxq613** [comment]
目前的策略是超出了 y 轴的范围后才做裁剪，遇到这种情况，你可以 nice: false，会拍平的
