### ISSUE TITLE
y 轴字段 nice: false 后，没有刻度的位置不应该有栅格线

### ISSUE THREAD

**Issue by dxq613** [antvis/g2#644]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/1264678/40339084-4290db04-5dab-11e8-9796-2fea02928a94.png)

**Comment by simaQ** [comment]
这个主要是因为我们为了支持 gird 的 alternateColor 以及 align: 'center' 配置，默认会将补充首位两条线，所以导致坐标轴上本没有文本的地方出现网格线，详见 https://github.com/antvis/g2/blob/77ec2abb31eeb3d260cbe968f7e5bb9419e6856d/src/chart/controller/axis.js#L350，目前版本可以通过设置 `hideLastLine: true` 来隐藏，在 G2 4.0 中会将该问题在内部默认解决。

**Comment by simaQ** [comment]
4.0 以支持
