### ISSUE TITLE
示例 基础雷达图 tooltip出现数据重复错误

### ISSUE THREAD

**Issue by lx3xun** [antvis/g2#645]
当鼠标悬浮于两点其中一个点时，数据会有重复。
地址：https://antv.alipay.com/zh-cn/g2/3.x/demo/radar/basic.html

如图：

![image](https://user-images.githubusercontent.com/6147862/40346788-7c459bd0-5dd0-11e8-86ea-2d764c8a43f8.png)

**Comment by leungwensen** [comment]
G2 版本是多少？

**Comment by zxfOliver** [comment]
@antv/g2@3.0.12

**Comment by leungwensen** [comment]
多谢反馈！

**Comment by dxq613** [comment]
3.0.10 还没有，我试了试是鼠标移动到点上出现的。还得检查一下出重逻辑
