### ISSUE TITLE
Error: require() of ES Module

### ISSUE THREAD

**Issue by liulng** [antvis/G2#6456]
### 问题描述

在nextjs 14.2.5版本中import { Chart } from '@antv/g2';报错Error: require() of ES Module node_modules\.pnpm\d3-array@3.2.4\node_modules\d3-array\src\index.js from node_modules\.pnpm\@antv+g2@5.2.5\node_modules\@antv\g2\lib\transform\utils\order.js not supported.
这个错误我看之前有人提过，但是我现在是用的5.2.5的版本应该是比较新的了，不知道为什么还有这个问题

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by hustcc** [comment]
锁定 d3 相关库版本为 2，或者去 d3 上提交一个 issue 关联起来。
