### ISSUE TITLE
axis的labelFill颜色不是我给的颜色，请问我要如何调整

### ISSUE THREAD

**Issue by asz97665** [antvis/G2#6458]
### 问题描述

如图，我给的labelFill颜色是纯黑色，但出现的像是灰色

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

![image](https://github.com/user-attachments/assets/69c1a0e4-aa09-41b9-9dfc-7a1a8426f6db)

**Comment by hustcc** [comment]
有默认透明度，可以设置 labelOpacity 为 1 试试。
