### ISSUE TITLE
3.0.2 后，guide.text 被栅格线遮挡了。

### ISSUE THREAD

**Issue by dxq613** [antvis/g2#646]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/1264678/40355713-badc06ea-5de9-11e8-9965-f17f3fc869bd.png)

**Comment by dxq613** [comment]
我定位了下，发现是 guide 以前的时候是在 axis 绘制完成后绘制的，默认会在栅格的前面图形的后面，但是由于自定义 padding 的时候，更改了坐标轴和 guide 的绘制顺序，所以导致现在文本在栅格线后面了。

可以通过 top: true 调整到栅格线、图形的前面，但是这个地方仔细分析一下，应该有三个位置：
* 栅格线的后面（目前默认）
* 图形的前面 （top: true 后) 
* 图形的后面、栅格线的前面（3.0.2之前）

从这个意义上来看 top: true 这个参数不太合适。

**Comment by leungwensen** [comment]
这个需要在 3.1 发布前修掉吗
