### ISSUE TITLE
饼图 标签在设置了fontSize后并没有根据字体大小进行自适应隐藏

### ISSUE THREAD

**Issue by dudu824** [antvis/G2#6468]
### 问题描述

标签在设置了fontSize后并没有根据字体大小进行自适应隐藏

### 重现链接

https://codesandbox.io/p/sandbox/beautiful-chatelet-ydyj4h?file=%2Findex.ts

### 重现步骤

1. 打开饼图网页
2. 多搞几条饼图相同数据
3. 设置label 的 fontSize
4. 缩小浏览器窗口

### 预期行为

预期行为：标签不应该相互重叠遮挡
实际结果：标签应该自动隐藏从而达到最佳展示效果

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

![image](https://github.com/user-attachments/assets/dfd95c4c-1c98-493e-94ca-66f2e631d63b)

**Comment by hustcc** [comment]
```ts
.label({
    text: 'id',
    position: 'spider',
    connectorDistance: 0,
    fontWeight: 'bold',
    textBaseline: 'bottom',
    textAlign: (d) => (['c', 'sass'].includes(d.id) ? 'end' : 'start'),
    dy: -4,
    fontSize: 22,
    // 要加这个
    transform: [
      {
        type: 'overlapDodgeY',
      },
    ],
  })
```
