### ISSUE TITLE
柱状图点击事件问题

### ISSUE THREAD

**Issue by Dog-Lee** [antvis/g2#647]
![qq 20180522232452](https://user-images.githubusercontent.com/20838671/40372737-e12100ca-5e17-11e8-9c13-6721c8efe144.png)

```
chart.on('interval:click', ev => {
          var data = ev.data;
          if (data) {
            var date = data._origin.date;

          };
      })
```
使用interval:click触发点击事件后发现当柱状图高度很低或者为0时，很难去点击事件。能否点击灰色蒙层触发事件？文档上看不到相关的信息，所以过来issues了。还有是否可以增加柱状图鼠标移动到柱形时使用cursor:pointer以提示用户可以点击？

**Comment by leungwensen** [comment]
interval:click 事件本来就是在 interval 的 shape 上响应的。如果希望实现点击灰色区域也能获取对应的数据，可以监听 plot:click 事件，然后用 getSnapRecords 接口： https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_getSnapRecords  鼠标样式的变更需要自己监听事件进行定制。
