### ISSUE TITLE
labelAutoEllipsis属性在图表只有一条数据的时候似乎没有生效

### ISSUE THREAD

**Issue by MonsterXue** [antvis/G2#6493]
### 问题描述

labelAutoEllipsis、labelAutoWrap、labelAutoRotate等属性在图表只有一条数据的时候似乎没有生效，两条以上显示都是正常的，不知道是否时属性配置错误

### 重现步骤

![image](https://github.com/user-attachments/assets/bfe5e9c3-f251-4993-b17c-0ffae40f9c11)
![image](https://github.com/user-attachments/assets/bc83478e-7756-4ed1-b7b0-9a5feb2cd71f)

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by hustcc** [comment]
labelAutoEllipsis、labelAutoWrap、labelAutoRotate 这些策略只在设置了坐标轴的高度才生效。具体设置方法是：

- 如果是 x 轴，就设置图表的 paddingBottom
- 如果是 y 轴左侧，就设置图表的 paddingLeft
- 以此类推
