### ISSUE TITLE
Point style shape "triangleDown" and "hollowTriangleDown" is not applyes

### ISSUE THREAD

**Issue by SAScrazyAS** [antvis/G2#6494]
### 问题描述

Point style shape "triangleDown" and "hollowTriangleDown" is not applyed

### 重现步骤

1. Create chart as "Scatter".
2. Add point style.
3. Set the value of the shape property as "triangleDown" or "hollowTriangleDown"

### 预期行为

Actual result: The shape of the dots is like circle.
Expected result: Set the value of the shape property as triangleDown or hollowTriangleDown.

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

![triangleDown](https://github.com/user-attachments/assets/0b15a7e1-5c6b-4fe3-8ddd-cc64b314dde1)

**Comment by hustcc** [comment]
是不是使用的版本不对？看起来像是 v3 的官网。
