### ISSUE TITLE
柱状图数据值差异较大时，可点击区域太小

### ISSUE THREAD

**Issue by Amaz-Ning** [antvis/G2#6499]
### 问题描述

当差值在1万倍时还能勉强看见柱状图的区域，大于10万倍时几乎就看不见了，更不要说点击了。
所以我尝试通过点击柱状图上方的区域获取数据，发现V5版本中移除了getSnapRecords。
又尝试通过点击x轴的label获取数据，发现axis-label:click也被移除了。
请问还有什么方法能不直接点击柱状图的柱子 还能拿到柱状图的数据呢？

### 预期行为

期望通过点击空白地方拿到对应柱状图的数据

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

![image](https://github.com/user-attachments/assets/19f662f2-c2a2-46e0-80cc-8e8d8f61c773)

**Comment by Amaz-Ning** [comment]
难不成只能通过plot:click拿到x的值然后去硬算吗
补药啊

**Comment by hustcc** [comment]
配置下柱形图的 style.minHeight
