### ISSUE TITLE
柱状图的x轴为日期时，x轴数据与y轴数据不匹配如何解决

### ISSUE THREAD

**Issue by luoboYe** [antvis/g2#65]
柱状图的x轴为日期时，x轴会多出一些数据，x轴数据与y轴数据不匹配
演示效果http://runjs.cn/code/8bum8jhm

**Comment by afc163** [comment]
https://segmentfault.com/markdown

**Comment by luoboYe** [comment]
演示效果http://runjs.cn/code/8bum8jhm
