### ISSUE TITLE
V5 移除了事件 plot:contextmenu 吗

### ISSUE THREAD

**Issue by shiningstarts** [antvis/G2#6501]
### 问题描述

https://g2.antv.antgroup.com/manual/extra-topics/event
<img width="823" alt="image" src="https://github.com/user-attachments/assets/c677f829-1f44-41c9-bc8f-f9f88e90a25f">

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by hustcc** [comment]
好问题，两种方式可以解决：

1. POINTER_DOWN + 判断事件中的 button = 2，就是右键
2. 找到 html 中的 canvas dom，canvasEl..addEventListener('contextmenu', () => {})
