### ISSUE TITLE
请问这种根据数据值计算出来的刻度的 min、max 和 刻度间距 interval 的相关源码在哪一块啊。非常需要，麻烦告知下，感激不尽🙏

### ISSUE THREAD

**Issue by liqiuqiui** [antvis/G2#6503]
### 问题描述

<img width="1327" alt="image" src="https://github.com/user-attachments/assets/58211a58-b98e-48e8-a532-9dd64b5316a2">

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by hustcc** [comment]
看这个 https://github.com/antvis/scale

**Comment by liqiuqiui** [comment]
> 看这个 https://github.com/antvis/scale

有用，非常感谢！
