### ISSUE TITLE
guide html 的position 设置失效

### ISSUE THREAD

**Issue by huxiaoyun** [antvis/g2#651]
* **G2 Version**:  3.0
* **Platform**: 
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:
设置了[ 'max','max' ]   显示却在图像中间  
https://riddle.alibaba-inc.com/riddles/9037bbd8

**Comment by dxq613** [comment]
看了看是要根据 guide 的宽高进行定位，改成 <span> 或者 display:inline-block 就可以了。这个我看看是否默认加 css

**Comment by dxq613** [comment]
如果容器是 div 的话自己添加 display:inline-block  或者设置个宽度 width: 100px。
