### ISSUE TITLE
5.2.8版本热力图无法渲染

### ISSUE THREAD

**Issue by Hideinvirus** [antvis/G2#6512]
### 问题描述

@antv/g2版本^5.2.8，出现热力区域无法渲染的问题
![image](https://github.com/user-attachments/assets/d76a63bd-0d10-4843-9ffc-c1475d38bc61)

### 重现步骤

vue3项目，安装最新版本g2，复制官网热力图示例，图片正常展示，热力区域无法显示

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

### 屏幕截图或视频（可选）

![image](https://github.com/user-attachments/assets/c72cd2a5-696a-4bd4-98f8-b703318c1edb)

**Comment by 8502596** [comment]
me  too

**Comment by hustcc** [comment]
和 https://github.com/antvis/G2/issues/6510 这个是相同的问题吗？

**Comment by hustcc** [comment]
https://g2.antv.antgroup.com/examples/general/heatmap/#heatmap

官网 DEMO 打开是可行的，可以提供一个 codesandbox 的在线示例，我来调试一下。

**Comment by Hideinvirus** [comment]
> https://g2.antv.antgroup.com/examples/general/heatmap/#heatmap
> 
> 官网 DEMO 打开是可行的，可以提供一个 codesandbox 的在线示例，我来调试一下。

https://codesandbox.io/p/sandbox/happy-snowflake-23v6tr

**Comment by Hideinvirus** [comment]
> 和 #6510 这个是相同的问题吗？
是同一个问题

**Comment by 8502596** [comment]
似乎  5.1.17 可以  5.1.18  就不行了    5.1.18  升级成   @antv/g ^6.0.0  版本   升级的东西很多    新手表示根本不知道问题所在

**Comment by 8502596** [comment]
最新测试  定位到如下 组件  

g2  5.1.18 版本不行  
![image](https://github.com/user-attachments/assets/3eec13e2-1349-4d61-a1c9-a1c3392916d0)

组件下 @antv/g-canvas   2.0.17  版本不行  2.0.16 版本可以

![image](https://github.com/user-attachments/assets/8183c8d7-7346-4612-be77-7c6f217862b9)

组件下 @antv/g-plugin-canvas-renderer  2.1.1 版本不行  2.1.0 版本可以

![image](https://github.com/user-attachments/assets/d9308e70-3ceb-4a1b-891f-ad84649ce3d8)

 @antv/g-plugin-canvas-renderer  2.1.1  依赖 与 2.1.0 依赖有几处不同

![image](https://github.com/user-attachments/assets/14f5abdc-47d1-4afa-81b1-59198fa0a983)

降级不起作用

同时   @antv/g-plugin-canvas-renderer  2.1.0  升级为 

![image](https://github.com/user-attachments/assets/8db2b63f-b4af-463c-8ced-bfcc956bfebb)

报错如下  

![image](https://github.com/user-attachments/assets/a0cc21d9-9823-46f9-9465-b3c1cdcc72c6)


目前定位到  @antv/g-plugin-canvas-renderer  2.1.0 升级到 2.1.1 的代码  调用 

"@antv/g-lite": "2.1.1"   时有问题  同时 依赖多添加了 "@babel/runtime": "^7.25.6",   可能也能找到相关的调用

才开始接触vue  和  antv   以前对前端一窍不通，完全是抛砖引玉

**Comment by 8502596** [comment]
最新进展    大佬们都不吱声   只能自己研究着玩

初步判断  @antv/g-plugin-canvas-renderer 2.1.1  升级的代码 导致  渲染不了

升级的问题如下  @antv/g-canvas  只有 依赖升级
![image](https://github.com/user-attachments/assets/178794a6-0641-45ae-a5c9-797707cc6475)

@antv/g-plugin-canvas-renderer 关键代码升级

![image](https://github.com/user-attachments/assets/7bea0154-20ee-441f-a090-d0ec03e7ec01)

![image](https://github.com/user-attachments/assets/de1c4d24-b03b-4826-8b17-046c14e1ff1d)

@antv/g-plugin-image-loader    关键代码升级

![image](https://github.com/user-attachments/assets/ada7ba18-896c-425e-94af-f6a1fedc9ffa)

![image](https://github.com/user-attachments/assets/02d4019e-57f9-4750-a174-9b3d0dfb6850)

![image](https://github.com/user-attachments/assets/779876e9-9b0e-4bec-bc67-33808077048a)


新添加的代码  有很大问题  vue3  调试过程中  发现 根本不会 走以下代码  也就是 createImage
![image](https://github.com/user-attachments/assets/2359b972-5714-453e-ab28-e7c36e39ad0b)

修改此处代码  或屏蔽此处代码  调试运行后出现 一些问题   修改代码如下

![image](https://github.com/user-attachments/assets/6e865ef9-ccb9-4def-a88d-f9fead369a5c)

前端报错如下  

![image](https://github.com/user-attachments/assets/724337c1-b419-4717-8916-6800080e6faa)


至此 问题还没有完整解决

**Comment by 8502596** [comment]
> 最新进展 大佬们都不吱声 只能自己研究着玩
> 
> 初步判断 @antv/g-plugin-canvas-renderer 2.1.1 升级的代码 导致 渲染不了
> 
> 升级的问题如下 @antv/g-canvas 只有 依赖升级 ![image](https://private-user-images.githubusercontent.com/15864647/390696169-178794a6-0641-45ae-a5c9-797707cc6475.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NDAxMTUsIm5iZiI6MTczMjgzOTgxNSwicGF0aCI6Ii8xNTg2NDY0Ny8zOTA2OTYxNjktMTc4Nzk0YTYtMDY0MS00NWFlLWE1YzktNzk3NzA3Y2M2NDc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDAwMjMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzOTJlNGExMmEwZWMxOGEyNDIxM2IwMjRmM2NiZGQ1N2FjZmQ0MDY2MDNiNTU2NGE0MDQ5YjIyMjI2Mzg2MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cEq7cbLBTINMlcRYzrgJZXu6TEtn6FPvTnIVll3R9GQ)
> 
> @antv/g-plugin-canvas-renderer 关键代码升级
> 
> ![image](https://private-user-images.githubusercontent.com/15864647/390696726-7bea0154-20ee-441f-a090-d0ec03e7ec01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NDAxMTUsIm5iZiI6MTczMjgzOTgxNSwicGF0aCI6Ii8xNTg2NDY0Ny8zOTA2OTY3MjYtN2JlYTAxNTQtMjBlZS00NDFmLWEwOTAtZDBlYzAzZTdlYzAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDAwMjMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyYjAwOTJmN2U0ZDJlZDFiNWE0ZTc1YTUyMjcwMDEwODFjMjRhNDE3OWYyOTg4ODM0NTMzZjU2ZTBlNDAwMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PPkygIwQowc6ss4tCf7RFAIotocQnybNefOI89IX_To)
> 
> ![image](https://private-user-images.githubusercontent.com/15864647/390697598-de1c4d24-b03b-4826-8b17-046c14e1ff1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NDAxMTUsIm5iZiI6MTczMjgzOTgxNSwicGF0aCI6Ii8xNTg2NDY0Ny8zOTA2OTc1OTgtZGUxYzRkMjQtYjAzYi00ODI2LThiMTctMDQ2YzE0ZTFmZjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDAwMjMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNjkxNzM2ZWJjMjY2Nzg4ZGI0NTc1M2QwNmQxNTIyZTQ5NzBlYWVjZmE2N2I5Y2IxYTFhZWEzZDc5NTE3YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.N7sbHC0Ddp2Fk2AMWpR7OHINBfa60XsXDfpV6GrO_Bk)
> 
> @antv/g-plugin-image-loader 关键代码升级
> 
> ![image](https://private-user-images.githubusercontent.com/15864647/390698471-ada7ba18-896c-425e-94af-f6a1fedc9ffa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NDAxMTUsIm5iZiI6MTczMjgzOTgxNSwicGF0aCI6Ii8xNTg2NDY0Ny8zOTA2OTg0NzEtYWRhN2JhMTgtODk2Yy00MjVlLTk0YWYtZjZhMWZlZGM5ZmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDAwMjMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NTVkZjNmNDBiN2UzMWIwNTk5ZWU2MjA3MDRmNDkzM2FhODFkZGZkMDFjMzUzZWJkZjUzZDY0MDI0ZThiNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.m-AH5qUAGvMVylfsDbJewDwO1fDKj6L6CaMtJBUL17E)
> 
> ![image](https://private-user-images.githubusercontent.com/15864647/390699050-02d4019e-57f9-4750-a174-9b3d0dfb6850.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NDAxMTUsIm5iZiI6MTczMjgzOTgxNSwicGF0aCI6Ii8xNTg2NDY0Ny8zOTA2OTkwNTAtMDJkNDAxOWUtNTdmOS00NzUwLWExNzQtOWIzZDBkZmI2ODUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDAwMjMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5OGQzM2Y0MDczOTlmYWQ0YzQzZGQyM2Q1YWFhNDNlNWI0MzYyOTMwMGU1YTE5MzQ5NTkzNDBiM2YyOTc5NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.y3DfWsGr6DXK1JMJw-CTTfmtlwbOwZqPTuPc1wA0b9k)
> 
> ![image](https://private-user-images.githubusercontent.com/15864647/390699353-779876e9-9b0e-4bec-bc67-33808077048a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NDAxMTUsIm5iZiI6MTczMjgzOTgxNSwicGF0aCI6Ii8xNTg2NDY0Ny8zOTA2OTkzNTMtNzc5ODc2ZTktOWIwZS00YmVjLWJjNjctMzM4MDgwNzcwNDhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDAwMjMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMjhlZmE3Mjg4Y2M5MTY4NWJmNGVhMDgwMjBkNjFkMTE2MWE4ZTIwMTE5NzdkNGE3OTQzZjNlMzk4YmZhZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Dl2Azn3dQZPAAA3yBKUzO1zv2H5FF_csceP0lRsYngY)
> 
> 新添加的代码 有很大问题 vue3 调试过程中 发现 根本不会 走以下代码 也就是 createImage ![image](https://private-user-images.githubusercontent.com/15864647/390700578-2359b972-5714-453e-ab28-e7c36e39ad0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NDAxMTUsIm5iZiI6MTczMjgzOTgxNSwicGF0aCI6Ii8xNTg2NDY0Ny8zOTA3MDA1NzgtMjM1OWI5NzItNTcxNC00NTNlLWFiMjgtZTdjMzZlMzlhZDBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDAwMjMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyY2FjMjI2ZGI5MTU1OTBkYzc5ZmY0MTIyZWJjNzM2MjJmNzU2M2VkNzZhYTU1NjVlMTRlNTkxYTAzODhjY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PfXCj-3wqyRgbPvfx5SxKBoVpffgk1vZejN4KOAKUn4)
> 
> 修改此处代码 或屏蔽此处代码 调试运行后出现 一些问题 修改代码如下
> 
> ![image](https://private-user-images.githubusercontent.com/15864647/390701745-6e865ef9-ccb9-4def-a88d-f9fead369a5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NDAxMTUsIm5iZiI6MTczMjgzOTgxNSwicGF0aCI6Ii8xNTg2NDY0Ny8zOTA3MDE3NDUtNmU4NjVlZjktY2NiOS00ZGVmLWE4OGQtZjlmZWFkMzY5YTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDAwMjMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmN2U1ZWU4ZjI4NmIxYTE1OGRmMzFkN2FlZmFhNTFhMzkwOGIyMTkxZGIwZGZjMGI5NmQyYmMzZDdkZDE2MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ofKsMIlzMlCmoWPiOhsOcNS4LmsvKDbS-RZobS2sR-U)
> 
> 前端报错如下
> 
> ![image](https://private-user-images.githubusercontent.com/15864647/390705230-724337c1-b419-4717-8916-6800080e6faa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NDAxMTUsIm5iZiI6MTczMjgzOTgxNSwicGF0aCI6Ii8xNTg2NDY0Ny8zOTA3MDUyMzAtNzI0MzM3YzEtYjQxOS00NzE3LTg5MTYtNjgwMDA4MGU2ZmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDAwMjMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjNmM0NWZiYzM5YWVlOTIwNjdjMWI4MGRjZDA3NzE3MGVhN2MxYjMyNzI4ZGM1ZjBkYTczZjIyM2ZmYmJkOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GF8XG33eoWcg8lCBXJnZTcY3ndxSbP3KClyIRej8MC8)
> 
> 至此 问题还没有完整解决

经测试  @antv/g-plugin-image-loader  处代码 不需要改   修改 @antv/g-plugin-canvas-renderer    
packages/g-plugin-canvas-renderer/src/shapes/styles/Image.ts  代码即可  对比发现  2.1.0  升级 2.1.1 时 代码 判断
image 为 空后 直接返回  而 2.1.0  image 为空 后 赋值 为 src
 
![image](https://github.com/user-attachments/assets/5bdefbd7-7aa5-4c0f-a141-a908222880ca)

修改 Images.ts 代码如下  
![image](https://github.com/user-attachments/assets/cd9e2222-dcba-4736-8fdf-d9d879145458)

测试后发现  前端正常 渲染 并显示

![image](https://github.com/user-attachments/assets/6d935cea-06ac-441f-b919-c4ebbd2fabc2)

**Comment by 8502596** [comment]
@Hideinvirus  @xiaoiver @hustcc   帮忙看一下  是不是  这个问题   

@antv/g-plugin-canvas-renderer
packages/g-plugin-canvas-renderer/src/shapes/styles/Image.ts 代码即可 对比发现 2.1.0 升级 2.1.1 时 代码 判断
image 为 空后 直接返回 而 2.1.0 image 为空 后 赋值 为 src

![image](https://github.com/user-attachments/assets/00d66072-2c9d-4924-bdd7-c188bc439384)

**Comment by 8502596** [comment]
似乎 可以 终章了  如 不修改  @antv/g-plugin-canvas-renderer   2.1.1  Image.ts 代码   修改 
@antv/g-plugin-image-loader    2.0.12   ImagePool.ts 代码 如下  也可得到 正确的渲染效果 

![image](https://github.com/user-attachments/assets/a8bf2bb3-c40c-418a-a516-17c21b9afb59)

原因似乎是 因为 百度得知  canvas  标签没有  src 和 alt  属性  通过控制台打印  src 得到 那么

![image](https://github.com/user-attachments/assets/5b663313-c897-4600-984d-7a8804328c5f)

![image](https://github.com/user-attachments/assets/3c1224fc-3a6c-4347-8501-1f132c485ff6)

请大佬们  稍微关注一下   好像试过  用vue2  能正常显示  怀疑此处代码

![image](https://github.com/user-attachments/assets/63cf269c-21ba-4dbf-a8b4-7e46ec52ae96)

@antv/g-plugin-image-loader  2.1.11   ImagePool.ts   在此处代码 与 2.0.12 版本代码一致 

 请各位大佬百忙之中 抽出一点时间来看一下吧 

![image](https://github.com/user-attachments/assets/f7422ce1-c7c0-40de-b6b0-de914a42f2b4)

**Comment by 8502596** [comment]
终章之 风云再起  
@antv/g-plugin-image-loader 2.0.12 ImagePool.ts 代码 如下 也可得到 正确的渲染效果

![image](https://github.com/user-attachments/assets/740b1005-728f-475b-8d0d-b177e38a3474)

但其中的问题在于  imageSource  为空的 情况下  赋值为  "canvas"   字符串   但如果缓存 进去 如果有几个 热力图等

canvas 标签元素  那边 他的key  应该是一样的  

所以 修改如下   通过绑定 canvas 缓存 key + 容器ID 
![image](https://github.com/user-attachments/assets/a5b1028a-1ea9-4353-a893-00b44ca93a0b)

 我通过 webstorm 代码提示 得到了  此代码  但是 还是提示   id  没有这个属性   但是前端是正常显示的


![image](https://github.com/user-attachments/assets/13db861f-393a-4ad5-a8e7-619ccf9dd52e)


当然 前端 g2 调用  需要添加    当然不添加id  也不行的   但总感觉代码怪怪的 

望大佬百忙之中  给指明  怎么修改

![image](https://github.com/user-attachments/assets/d0e4497f-cfd0-4675-bb6c-5afd02c255ec)

**Comment by hustcc** [comment]
@8502596 已经分析到这个地步了， 直接来一个 PR 吧。我看你也在 G 提了 issue：https://github.com/antvis/G/issues/1864

**Comment by 8502596** [comment]
@hustcc  真不会提   😟   真的抱歉，对前端一窍不通  都不知道自己写的对不对   只是瞎写的。

**Comment by wang1212** [comment]
> @hustcc 真不会提 😟 真的抱歉，对前端一窍不通 都不知道自己写的对不对 只是瞎写的。

厉害啊，问题的原因你这边已经分析出来了，是因为底层升级时未考虑到 Image 元素的 `src` 属性可以直接传递 canvas 元素实例导致的，这两天会修复掉。

---

G2 中的关键代码：

```ts
export const Heatmap: SC<HeatmapOptions> = (options, context) => {
   // ...
  return (points: number[][], value, defaults) => {
    return select(document.createElement('image', {}))
      .call(applyStyle, defaults)
      .style('x', 0)
      .style('y', 0)
      .style('width', width)
      .style('height', height)
      .style('src', ctx.canvas)
      .style('transform', transform)
      .call(applyStyle, style)
      .node();
  }
}
```

其中，通过 `document.createElement('image', {})` 创建了 image 元素，并通过 `.style('src', ctx.canvas)` 将 canvas 实例赋值给了 `src` 属性。

**Comment by wang1212** [comment]
> 是不是这里改成传入 dataUrl 就可以了？如果可以的话，直接 G2 改掉也合理，G 层不做适配。

可以的，这样可能更符合规范标准，合理一些
