### ISSUE TITLE
无法自定义颜色吗？

### ISSUE THREAD

**Issue by Mrcxt** [antvis/G2#6521]
### 问题描述

想自定义柱状图、饼图等的颜色，目前是在style中根据判断设置的色值，但是tooltip和legend的中对应的色值却并未跟着改变，所以我想之后有没有一个字段可以统一自定义色值？

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by hustcc** [comment]
参考 [demo](https://g2.antv.antgroup.com/examples/general/interval/#bar-range) 使用 color encode 设置就可以统一修改了。
