### ISSUE TITLE
请问5.x的padding:'auto' 不生效了吗？

### ISSUE THREAD

**Issue by imyuxh** [antvis/G2#6526]
### 问题描述

5.x不论是省略padding不写，还是padding:auto，都不生效了，只会给我的图表区域加一个默认的padding:30。可是这个功能不是在4.x支持郝豪的吗？

### 预期行为

我期望能够根据我的axis的label宽度，自动调节padding大小，但是没有，只给了我默认的30

### 平台

- 操作系统: [macOS]
- 网页浏览器: [Google Chrome]
-"@antv/g2": "^5.2.8",

**Comment by hustcc** [comment]
默认就是 auto padding 的，然后如果指定确定的值，那就：

```ts
{
  padding: [16, 16, 16, 16],
}
```

这个 padding 位置就会给他图表的几个方位，用于防止 legend、axis 等组件。
