### ISSUE TITLE
请问5.X版本如何图表如何导出图片

### ISSUE THREAD

**Issue by BaiyanAlwaysOnline** [antvis/G2#6531]
### 问题描述

请问5.X版本如何图表如何导出图片

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by hustcc** [comment]
找到对应的 canvas，然后使用 canvas 的 API 导出图片即可。

```ts
const canvas = chart.getContext().canvas;
```
