### ISSUE TITLE
Support customing the fill attribute of the chart component

### ISSUE THREAD

**Issue by HelloAny** [antvis/G2#6534]
- [ ] I have searched the [issues](https://github.com/antvis/g2/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://github.com/antvis/F2/blob/e3659d21db9b7c540cad7f9e75664ee564a7028f/packages/f2/src/chart/index.tsx#L357

1. Help users more flexibly modify the background of the Chart component.
2. When I adapt to the company's hybrid container, will get some error when useing 'transparent'.

### What does the proposed API look like?
```
const { fillStyle } = props;

  <group
        ref={this.coordRef}
        style={{
          width: width,
          height: height,
          fill: fillStyle || 'transparent',
        }}
      >
...
 </group>
```

**Comment by HelloAny** [comment]
Sry, I make a mistake. The issue should be in F2 repo.😥

**Comment by hustcc** [comment]
![image](https://user-images.githubusercontent.com/7856674/392870095-c0c545d5-4fec-4842-98db-b50a78f9f157.jpeg)

如果有钉钉的话，加个群，交流更方便，进群备注为 GitHub id。
