### ISSUE TITLE
G2 V5.*如何实现数据标签(label)文字颜色自动调整

### ISSUE THREAD

**Issue by seven-sent** [antvis/G2#6539]
### 问题描述

G2 4.*可以设置数据标签文字颜色自动调整，G2 V5.*如何实现呢？
```
//G2 4.*
interval.label('y', {
	layout: [{ type: 'interval-adjust-position' }, {type: 'adjust-color' }]
})
```

### 预期行为

提供G2 V5.*实现数据标签文字颜色自动调整的方法

### 平台

- 操作系统: macOS
- 网页浏览器: Google Chrome

**Comment by hustcc** [comment]
- fixed in https://github.com/antvis/G2/pull/6536

等发包就可以了。
