### ISSUE TITLE
弧长链接图在特定link下出现弧线绘制错误的情况

### ISSUE THREAD

**Issue by slsyx** [antvis/g2#654]
* **G2 Version**:
3.0.12
* **Platform**:
windows edge chrome
* **Mini Showcase(like screenshots)**:

* **CodePen Link**:
https://codepen.io/anon/pen/KRjaEX

在绘制弧长链接图时，某些情况下，link的绘制出现问题
如5个node 1-4 2-5 会存在问题  0-5 2-4却又绘制正常

**Comment by leungwensen** [comment]
加上这一句就好了： 

```js
chart.scale({
  x: { sync: true },
})
```

因为你的应用场景边的 x 和点的 x 数值区间不一样（因为不是所有节点都关联了边），所以需要强制把 x 的数值区间统一掉
