### ISSUE TITLE
文档内容错误

### ISSUE THREAD

**Issue by wanghui2021** [antvis/G2#6552]
### 问题描述

类型和默认值位置写反了

<img width="1588" alt="image" src="https://github.com/user-attachments/assets/cc26040a-d37b-47c1-b578-f3cf2c0349e4" />

### 重现链接

https://g2.antv.antgroup.com/spec/interaction/tooltip

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by hustcc** [comment]
@wanghui2021 直接来一个 pr 改掉吧~ 👏🏻👏🏻👏🏻
