### ISSUE TITLE
直角坐标系中，如何使得坐标轴的标题放在轴线的顶端并旋转90度

### ISSUE THREAD

**Issue by sunbeamhub** [antvis/G2#6558]
### 问题描述

直角坐标系中，如何使得坐标轴的标题放在轴线的顶端并旋转90度

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by interstellarmt** [comment]
以官网示例为例 https://g2.antv.antgroup.com/zh/examples/general/interval/#bar-basic-transposed
如果要把x轴的year标题放在最上面，并且水平，可以添加 ：
 ```.axis('x', { titlePosition: 'top', titleTransform: 'rotate(0)' })```
但需要注意的是，要给标题留足够的位置，不然会显示不出来：
```  .attr('marginTop', 50)```

**Comment by sunbeamhub** [comment]
https://g2.antv.antgroup.com/spec/component/axis

缺少titleTransform字段的用法

**Comment by hustcc** [comment]
> https://g2.antv.antgroup.com/spec/component/axis
> 
> 缺少titleTransform字段的用法

感兴趣来一个 PR 吗？
