### ISSUE TITLE
请问如何禁用crosshairs触发mouse事件

### ISSUE THREAD

**Issue by aa1011372655** [antvis/g2#656]
* **G2 Version**:3.0.12
* **Platform**:mac
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/8445734/40542222-dbc3b44c-6051-11e8-8fda-6677d1010ed7.png)

* **CodePen Link**:https://codepen.io/anon/pen/deBeLO?editors=0010
当滑动到crosshairs的线上时，area的鼠标移入效果消失了
您好，我需要使用面积的mouseenter和mousemove实现一个滑动效果，结果crosshairs会导致无法触发area的mouse事件，我认为这不是一个bug，请问是否有办法不让crosshairs触发mouse事件

**Comment by dxq613** [comment]
@paleface001 跟进一下，生成这条线时设置一下 capture: fasle 就行了，https://github.com/antvis/g2/blob/master/src/component/tooltip/index.js#L319

**Comment by dxq613** [comment]
capture: false 不要设置到 attrs里面，要：

```js
group.addGroup({
  capture: false,
  attrs
});
```

**Comment by aa1011372655** [comment]
3.1.*版本生效，非常感谢
