### ISSUE TITLE
where is Cloud API descript?

### ISSUE THREAD

**Issue by ruoru** [antvis/g2#657]
i am using https://antv.alipay.com/zh-cn/g2/3.x/demo/other/word-cloud.html.
and there are not fined `Cloud` in https://antv.alipay.com/zh-cn/g2/3.x/api/index.html.

i want where config click words function?

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/api/transform.html#_tag-cloud-%E8%AF%8D%E4%BA%91%E5%B8%83%E5%B1%80

```js
  chart.on('point:click', ev => {
    console.log(ev);
  });
```

**Comment by ruoru** [comment]
this like DOM event bubbling,
my solution is 
```
this.textWordsCloud = new G2.Chart({...});
...

this.textWordsCloud.on('click', ev => {
  if(ev.shape && ev.shape.__attrs && ev.shape.__attrs.text && typeof callback == 'function' ) {
    callback(ev.shape.__attrs.text);
  }
});
```
