### ISSUE TITLE
图表放大后不清晰

### ISSUE THREAD

**Issue by ls3xun** [antvis/g2#661]
![image](https://user-images.githubusercontent.com/6147862/40830859-0cb431fe-65ba-11e8-8cdf-1ecd50beb58f.png)

如图，放大后图表变得虚幻了。

**Comment by leungwensen** [comment]
目前默认是用 canvas 进行渲染的（可以简单理解为类似位图），所以如果用 css 直接缩放图表，会带来失真。你的需求是什么？怎么缩放？

**Comment by leungwensen** [comment]
Closing for no further information is provided.

**Comment by stephanieDL** [comment]
@leungwensen  打扰，我也遇到了类似的问题，我是浏览器缩放的时候会出现坐标轴数据显示模糊的问题，请问有什么好的方法解决吗？非常期待您的解答，O(∩_∩)O谢谢
