### ISSUE TITLE
如何进行文档翻译的贡献？

### ISSUE THREAD

**Issue by renyuanz** [antvis/g2#662]
目前我所在的公司对Antvis的项目非常感兴趣，但是苦于没有英文文档，除了我们几个中国人其他同事无法参与使用，于是我们想请教维护该项目的同学，有没有正在进行的工作，如何参与到翻译文档的工作中？

感谢各位花时间维护这么棒的开源项目！👍

**Comment by leungwensen** [comment]
文档翻译计划在11月之前完成，目前正在调研方案。一旦方案确定了会及时通知。多谢关注！

**Comment by HanchengZhao** [comment]
同上，我们同事使用antd组件库的体验非常好，但是想尝试g2却没有完整的英文文档可供参考，希望尽快将这么优秀的库国际化

**Comment by dxq613** [comment]
@leungwensen Demo 我们可以稍后一点，文档的话，是不是可以在语雀上把仓库创建起来，让社区的朋友们帮我们开始翻译。

**Comment by simaQ** [comment]
初版 G2 英文文档已在语雀开放：https://www.yuque.com/antv/g2-docs-en，欢迎阅读校正
