### ISSUE TITLE
tooltip不能立即消失

### ISSUE THREAD

**Issue by Rabbitzzc** [antvis/g2#663]
您好，最近在使用G2的时候，发现了一个很烦恼的问题，就是当我快速的切换分组柱状图的时候,tooltip并不能立即消失，可能会在页面上停一会儿，甚至不会自动消失，点击也无法自动消失。

**Comment by leungwensen** [comment]
版本，重现代码？

**Comment by Rabbitzzc** [comment]
您好，感谢您能回复我，我应该用的是最新的G2，然后主要是写一个分组柱状图的模块，代码其实跟官网实例的一样，只是有时候当快速滑动柱图，然后突然鼠标移动到别的div，然后tooltip可能还在显示，我不知道该怎么监听tooltip事件，想让鼠标移出以后，能立马隐藏tooltip，不然会影响用户使用。

————还有一件事想请教一下
我想自定义tooltip，但是tooltip的自定义必须包含固定的list内容，我想格式化里面的内容怎么弄，比如插入图片之类的数组的信息之类的。。
我能想到的就是自己定义div，然后监听hover，但是不知道怎么监听，以及监听div的位置，请问有解决办法么

**Comment by lvovl** [comment]
同样遇到这个问题，highcharts用timer处理过，没看g2的源码，感觉可以提个pr

**Comment by lvovl** [comment]
* **G2 Version**: 3.1.0
* **Platform**: mac chrome 67.0.3396.87
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: [多图切换时tooltip不消失](https://codepen.io/tobeSSSfe/pen/PaQxBg)

**Comment by dxq613** [comment]
可以手工调用一下 chart.hideTooltip();

**Comment by lvovl** [comment]
@dxq613 这样吗
```
chart.on('mouseleave', ev => {
  console.log('mouseleave');
  chart.hideTooltip();
});
chart.on('plotleave', ev => {
  console.log('plotleave');
  chart.hideTooltip();
});
```
在两个图间滑动还是没有消失

**Comment by dxq613** [comment]
是否是这两个事件没触发？

**Comment by lvovl** [comment]
是的 在图间**快速**滑动没有触发，但是滑动到红色边框触发了plotleave

**Comment by dxq613** [comment]
应该已经解决了，通过判断 plotleave 和离开 canvas 容器两重判定。

**Comment by leungwensen** [comment]
下个次版本发 （3.3.x）

**Comment by yhaoao** [comment]
> @dxq613 这样吗
> 
> ```
> chart.on('mouseleave', ev => {
>   console.log('mouseleave');
>   chart.hideTooltip();
> });
> chart.on('plotleave', ev => {
>   console.log('plotleave');
>   chart.hideTooltip();
> });
> ```
> 
> 在两个图间滑动还是没有消失
> 我贴在了这里[多图切换时tooltip不消失](https://codepen.io/tobeSSSfe/pen/PaQxBg)

https://codepen.io/yhaoao/pen/JqWGQY

**Comment by chenxwei** [comment]
请问解决这个bug没？我也遇到一模一样的问题。版本是3.5.11
