### ISSUE TITLE
您好，在您官网的一个demo里添加alias别名配置，但并没有效果

### ISSUE THREAD

**Issue by zhuSass** [antvis/g2#666]
描述：https://antv.alipay.com/zh-cn/g2/3.x/demo/line/curved.html，我试图在这个demo里对国家名字进行中文别名，根据文档种给出的alias配置在方法source及transform的第二个参数里alias配置但运行结果并没有效果，添加代码如下：
<code>
dv.transform({
  type: 'fold',
  fields: ['Tokyo', 'London'], // 展开字段集
  key: 'city', // key字段
  Tokyo: { // 这是添加的代码
  	alias: '东京'
  },
  value: 'temperature' // value字段
});
</code>
or
<code>
chart.source(dv, {
  Tokyo: {
  	alias: '东京'
  },
  month: {
    range: [0, 1]
  }
});
</code>

**Comment by leungwensen** [comment]
fold transform 做完之后，数据里已经没有 Tokyo 这个字段了，只有 'city' 。你可以对 city 的值进行变更：

```js
chart.scale('city', {
  values: ['东京', '伦敦']
});
```

**Comment by jinjinma** [comment]
@zhuSass 参考这里https://github.com/alibaba/BizCharts/issues/107
