### ISSUE TITLE
关于图表更新是否有官方指导？

### ISSUE THREAD

**Issue by orangeyyy** [antvis/g2#667]
* **G2 Version**:
3.x
* **Platform**:
mac
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

最近一直在使用G2来进行一些图表相关的工作，想了解一下，关于g2的图表更新有官方文档吗？因为我发现对于不同的更新可能需要的操作会不一样：
* detroy图表，重新创建实例，例如图表的padding属性；
* clear然后repaint，例如geom的改变；
* 直接调用api接口，例如scale的改变；

**Comment by dxq613** [comment]
G2 更新数据的方式主要有三种：
* 仅仅是更新图表的数据
* 清理所有，重新绘制
* 使用 DataView 时的更新

### 更新数据

如果需要马上更新图表，使用 chart.changeData(data) 即可

```js
chart.changeData(newData);
```
* view 也支持 view.changeData(data);

如果仅仅是更新数据，而不需要马上更新可以调用 chart.source(data) 需要更新图表时调用 chart.repaint()

```js
chart.source(newData);

chart.guide().clear();// 清理guide
chart.repaint();
```

### 清理图形语法

更新数据时还可以清除图表上的所有元素，重新定义图形语法，重新绘制

```js
chart.line().position('x*y');

chart.render();

chart.clear(); // 清理所有
chart.interval().position('x*y').color('z');
chart.render();
```

### 使用 DataView  更新

由于 DataSet 支持状态量 state，一旦更改状态量，图表即一起刷新，详情查看 [DataSet 教程](https://antv.alipay.com/zh-cn/g2/3.x/tutorial/data-set.html)。

**Comment by orangeyyy** [comment]
@dxq613 那么除了数据更新之外的属性更新呢?
例如:图表的padding，scale，axis等等

**Comment by luguoeryi** [comment]
我用的是这个示例里面的 https://antv.alipay.com/zh-cn/g2/3.x/demo/line/series.html， 但是用changeData 不起作用，是不是因为用了DataSet 所以不起作用，关于这种数据的更新能不能给个demo？

**Comment by dxq613** [comment]
scale ,axis 重新调用对应的方法然后 repaint 就可以了，padding 的话，可以设置 'auto' 或者 chart.set('padding',xxx) 改一下。

```js
chart.render();

// 更改
chart.scale('x', {});
chart.axis('x', {});

chart.repaint();
```

**Comment by orangeyyy** [comment]
@dxq613 所以说这些信息都是通过口口相传的吗？

**Comment by ieasso** [comment]
> @dxq613
> 你好，，请问我在一个方法里面
> 
> ```
>   const chart = new G2.Chart({
>     container: 'mountNode',
>     forceFit: true,
>     height: window.innerHeight,
>     padding: [100, 80, 20, 50]
>   })
>   chart.source(data, {
>     day: {
>       type: 'cat',
>       ticks: ['day1', 'day2', 'day3', 'day4', 'day5', 'day6', 'day7', 'day8', 'day9', 'day10', 'day11', 'day12', 'day13', 'day14', 'day15', 'day30']
>     }
>   })
>   chart.line().position('day*value').color('date').size(2)
>   chart.render()
> ```
> 每次获取数据都去执行这个方法，但是每次都会创建一个新的图出来，而不是在原有图重绘，是为什么呢？我试了chart.clear(); 和chart.repaint();都没用，，只有每次都去 $('#mountNode').html('')才可以，要这样子的吗？

我也是碰到这个问题，不知怎么搞，你解决了吗？

**Comment by aa1011372655** [comment]
> > @dxq613
> > 你好，，请问我在一个方法里面
> > ```
> >   const chart = new G2.Chart({
> >     container: 'mountNode',
> >     forceFit: true,
> >     height: window.innerHeight,
> >     padding: [100, 80, 20, 50]
> >   })
> >   chart.source(data, {
> >     day: {
> >       type: 'cat',
> >       ticks: ['day1', 'day2', 'day3', 'day4', 'day5', 'day6', 'day7', 'day8', 'day9', 'day10', 'day11', 'day12', 'day13', 'day14', 'day15', 'day30']
> >     }
> >   })
> >   chart.line().position('day*value').color('date').size(2)
> >   chart.render()
> > ```
> > 每次获取数据都去执行这个方法，但是每次都会创建一个新的图出来，而不是在原有图重绘，是为什么呢？我试了chart.clear(); 和chart.repaint();都没用，，只有每次都去 $('#mountNode').html('')才可以，要这样子的吗？
> 
> 我也是碰到这个问题，不知怎么搞，你解决了吗？



> > @dxq613
> > 你好，，请问我在一个方法里面
> > ```
> >   const chart = new G2.Chart({
> >     container: 'mountNode',
> >     forceFit: true,
> >     height: window.innerHeight,
> >     padding: [100, 80, 20, 50]
> >   })
> >   chart.source(data, {
> >     day: {
> >       type: 'cat',
> >       ticks: ['day1', 'day2', 'day3', 'day4', 'day5', 'day6', 'day7', 'day8', 'day9', 'day10', 'day11', 'day12', 'day13', 'day14', 'day15', 'day30']
> >     }
> >   })
> >   chart.line().position('day*value').color('date').size(2)
> >   chart.render()
> > ```
> > 每次获取数据都去执行这个方法，但是每次都会创建一个新的图出来，而不是在原有图重绘，是为什么呢？我试了chart.clear(); 和chart.repaint();都没用，，只有每次都去 $('#mountNode').html('')才可以，要这样子的吗？
> 
> 我也是碰到这个问题，不知怎么搞，你解决了吗？

不要每次都去new Chart，将这个实例保存下来，例如：
```
this.chart = new Chart...
```
每次获取新的数据之后，请根据上面
https://github.com/antvis/g2/issues/667#issuecomment-394604042
所说的更新数据以及重绘，一种暴力的方式是不推荐的，每次new之前this.chart.destroy()
ps: 请使用规范的issue提交问题，非常感谢
