### ISSUE TITLE
Y轴区间下限默认取字段最小值还是0？

### ISSUE THREAD

**Issue by feng5** [antvis/g2#67]
比如https://g2.alipay.com/start/快速上手页面第一个柱形图，付款对应哪个100个访问就看不到
![g2](https://cloud.githubusercontent.com/assets/394134/21673225/bad2f22a-d362-11e6-9091-7d7fa9e36c97.png)

**Comment by feng5** [comment]
上限取字段最大值也是同样的，上限是否可以预留一定的区间

**Comment by dxq613** [comment]
指定列定义：

```js
chart.source(data, {
  value: {min: 0}
});

```

**Comment by feng5** [comment]
谢谢，看文档知道可以配置，意思是说默认使用0还是列最小值的问题

**Comment by dxq613** [comment]
默认值不是0，因为很多折线图要以用户的最小值为准。
