### ISSUE TITLE
使用了dataSet 后，scale的alias设置别名无效！

### ISSUE THREAD

**Issue by luguoeryi** [antvis/g2#671]
* **G2 Version*3.1.0*:
* **Platform*windows*:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by leungwensen** [comment]
请提供代码

**Comment by leungwensen** [comment]
@LinFeng1997 

1. 这个例子没有用 dataset
2. 这个例子别名设置是生效的

![image](https://user-images.githubusercontent.com/1655789/42985623-d9b6fb92-8c24-11e8-89fd-343f4909ae5b.png)

**Comment by LinFeng1997** [comment]
@leungwensen How to implement the result?
![image](https://user-images.githubusercontent.com/16188742/42994923-0cc26392-8c42-11e8-9d76-859e83b59e51.png)

**Comment by luguoeryi** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,height=device-height">
    <title>多条折线图</title>
    <style>::-webkit-scrollbar{display:none;}html,body{overflow:hidden;height:100%;margin:0;}</style>
</head>
<body>
<div id="mountNode"></div>
<script>/*Fixing iframe window.innerHeight 0 issue in Safari*/document.body.clientHeight;</script>
<script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.g2-3.2.4/dist/g2.min.js"></script>
<script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.8.9/dist/data-set.min.js"></script>
<script>
var data = [{
  month: 'Jan',
  Tokyo: 7.0,
  London: 3.9
}, {
  month: 'Feb',
  Tokyo: 6.9,
  London: 4.2
}, {
  month: 'Mar',
  Tokyo: 9.5,
  London: 5.7
}, {
  month: 'Apr',
  Tokyo: 14.5,
  London: 8.5
}, {
  month: 'May',
  Tokyo: 18.4,
  London: 11.9
}, {
  month: 'Jun',
  Tokyo: 21.5,
  London: 15.2
}, {
  month: 'Jul',
  Tokyo: 25.2,
  London: 17.0
}, {
  month: 'Aug',
  Tokyo: 26.5,
  London: 16.6
}, {
  month: 'Sep',
  Tokyo: 23.3,
  London: 14.2
}, {
  month: 'Oct',
  Tokyo: 18.3,
  London: 10.3
}, {
  month: 'Nov',
  Tokyo: 13.9,
  London: 6.6
}, {
  month: 'Dec',
  Tokyo: 9.6,
  London: 4.8
}];
var ds = new DataSet();
var dv = ds.createView().source(data);
dv.transform({
  type: 'fold',
  fields: ['Tokyo', 'London'], // 展开字段集
  key: 'city', // key字段
  value: 'temperature' // value字段
});
var chart = new G2.Chart({
  container: 'mountNode',
  forceFit: true,
  height: window.innerHeight
});
chart.source(dv, {
  month: {
    range: [0, 1]
  }
});
 chart.scale('Tokyo', {
  alias: '测试'
});
chart.tooltip({
  crosshairs: {
    type: 'line'
  }
});
chart.axis('temperature', {
  label: {
    formatter: function formatter(val) {
      return val + '°C';
    }
  }
});
chart.line().position('month*temperature').color('city');
chart.point().position('month*temperature').color('city').size(4).shape('circle').style({
  stroke: '#fff',
  lineWidth: 1
});
chart.render();
</script>
</body>
</html>


@leungwensen  以上这个是g2官方demo，我在上面试了chart.scale 是无效的，请问用了dataSet后应该怎么设置别名？

**Comment by jinjinma** [comment]
https://github.com/viserjs/viser/issues/136 在fold transform之前，rename transform一下
