### ISSUE TITLE
能否提供快速数据别名设置方式？

### ISSUE THREAD

**Issue by orangeyyy** [antvis/g2#672]
* **G2 Version**:
3.x
* **Platform**:
mac
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

现在对于scale已经提供了别名的设置方式，但是对于数据缺乏别名设置方式，例如官方文档的下面这个栗子：
https://antv.alipay.com/zh-cn/g2/3.x/demo/line/series.html
如果我希望将图例及tooltip中的Tokyo显示成东京、Landon显示成伦敦，只有将数据源中的数据字段换成对应的中文，感觉这种做法不是很合理，希望能够提供接口来设置这些数据别名。

**Comment by leungwensen** [comment]
可以在 scale 设置 values   https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#__%E7%A4%BA%E4%BE%8B

**Comment by orangeyyy** [comment]
@leungwensen 没太搞明白这values属性的作用，他只是一个数组，没有标明数据间的映射关系，例如上面我说的例子，我要如何将Tokyo映射到东京，将London映射到伦敦，根据values中值的顺序吗？

**Comment by hishamahamadeynos** [comment]
I believe this issue is related to my issue: https://github.com/antvis/g2/issues/1236
I too want data mapping, so I can show detailed information in the tooltip
