### ISSUE TITLE
带图片词云

### ISSUE THREAD

**Issue by ls3xun** [antvis/g2#673]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

您好，如图：
![image](https://user-images.githubusercontent.com/6147862/41136413-bc054528-6b08-11e8-8918-0919b32e94e6.png)
这类带图片遮罩的词云，可不可以将图片显示并围绕图片渲染词云呢？

**Comment by leungwensen** [comment]
这个例子： https://antv.alipay.com/zh-cn/g2/3.x/demo/other/word-cloud-mask.html

在 `chart.render()` 前加上下面的代码（用 guide 显示图片背景）

```js
    chart.guide().image({
      start: ['min', 'min'],
      end: ['max', 'max'],
      src: '/assets/image/logo-mask-16x9.png'
    });
```

效果是这样的：

![image](https://user-images.githubusercontent.com/1655789/41136989-7cc2f5d8-6b0b-11e8-8c50-8231b924aa90.png)

如果想要围绕图片像素布局词云，而不是在像素内，则需要额外准备一个图片。因为词云那个 transform 指定的 imageMask 就是取图片的“非透明或白色”的区域来布局的，所以需要自行准备一张镂空形状的图片。

**Comment by ls3xun** [comment]
我的两张图片（格式为jpg）为：
底图：
![image](https://user-images.githubusercontent.com/6147862/41142555-b2ac64aa-6b28-11e8-8583-ab591945ee33.png)
要显示的图片：
![image](https://user-images.githubusercontent.com/6147862/41142570-bd3733f0-6b28-11e8-8246-a042f9bf15e9.png)

transform 引入的是底图；guide引入的是要显示的图片，最后结果是这样的：
![image](https://user-images.githubusercontent.com/6147862/41142647-eff3bbce-6b28-11e8-9542-beb0d2b16413.png)

是图片做的不对吗？

**Comment by leungwensen** [comment]
你这是什么版本？

**Comment by ls3xun** [comment]
"@antv/g2": "^3.1.1"

**Comment by ls3xun** [comment]
是图片的问题，“ transform 指定的 imageMask 就是取图片的“非透明或白色”的区域来布局的” 白色、黑色都是不在渲染范围内的。
