### ISSUE TITLE
词云需求

### ISSUE THREAD

**Issue by lx3xun** [antvis/g2#676]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

如图：
![image](https://user-images.githubusercontent.com/6147862/41146832-3909e712-6b37-11e8-8b4c-e7aa3dbe4058.png)
类似这样的词云效果可以实现吗？如果可以具体实现步骤是怎么样的？

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/demo/other/word-cloud-mask.html 

准备两张图片，一张是你这个背景图，一张是 mask 图片。mask 图片是一张灰色图，中间扣除背景上的圆形
