### ISSUE TITLE
饼图支持实现隐藏其中一个选项？

### ISSUE THREAD

**Issue by luguoeryi** [antvis/g2#680]
* **G2 Version*3.1.0*:
* **Platform*win10*:
* **Mini Showcase(http://testm.jianzaogong.com/demo/chart.png)**:
* **CodePen Link*http://testm.jianzaogong.com/demo/chart.png*:

**Comment by dxq613** [comment]
直接通过 chart.filter() 方法将你想隐藏的选项隐藏掉即可，图例的项也会同步。
https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_filter

**Comment by luguoeryi** [comment]
这个应该会连饼图的那块扇形也一起隐藏了..，目标需求是：只隐藏那块扇形出来的线条和文字，扇形保留，这个我之前尝试的是操作label，（但是用了dataView, transform的type是percent）好像也是无效的，这个有什么方法吗？`var chart = this[chartName] || new G2.Chart({
                    container: id,
                    forceFit: true,
                    padding: [0, 20, 50, 20],
                    height: 200
                })

                chart.source(dv, {
                    percent: {
                        formatter: function formatter (val) {
                            val = parseInt(Math.round(val * 100)) + '%'
                            return val
                        }
                    }
                })

                chart.coord('theta', {
                    radius: 0.45
                })

                chart.tooltip(true, {
                    custom: true,
                    useHtml: true,
                    showTitle: false,
                    containerTpl: `<div class="g2-tooltip">
                                    <div class="g2-tooltip-title"></div>
                                    <ul class="g2-tooltip-list custom-table"></ul>
                                </div>`,
                    itemTpl: `<li data-index={index} style="padding-left:0;">
                                <span style="background:{color}" class="g2-list-item"></span> <span>{name}</span>
                                <span style="font-weight:500;">{value}</span>
                            </li>`
                })
                chart.legend({
                    // position: 'left',
                    // offsetX: 60,
                    // offsetY: -30,
                    textStyle: {
                        fill: '#373d41' // 文本的颜色
                    },
                    title: null
                })

                chart.clear() // 清理所有

                chart.intervalStack().position('percent').color(desArray[0], arrayColor).label('percent', {
                    formatter: function formatter (val, item) {
                        return item.point[desArray[0]] + ': ' + val
                    }
                }).tooltip(`${desArray[0]}*percent`, function (item, percent) {
                    percent = parseInt(Math.round(percent * 100)) + '%'
                    return {
                        name: '',
                        value: percent
                    }
                })

                [chart.render()`]([url]([url](url)))

**Comment by dxq613** [comment]
.label(fields, callback, {}) 的函数其实有三个参数，知识默认情况下 callback 都没有使用，所以你可以用 callback  return '' 就行了。
