### ISSUE TITLE
漏斗图每层数据一样时不再重复渲染，是就这样设计的吗？

### ISSUE THREAD

**Issue by JacobYChan** [antvis/g2#681]
当我为漏斗图配置数据时，如果几条数据一样，为什么不让渲染，而是只渲染一条数据
<img width="965" alt="2018-06-13 4 11 37" src="https://user-images.githubusercontent.com/18413888/41338545-112c16ec-6f25-11e8-823b-b1305e9e46bb.png">
如图中右边data，我改成了5条一样的数据，但是漏斗图只有一层，事实上只要action字段一样就不重复渲染了

**Comment by dxq613** [comment]
把你的数据和声明图表的语法写一下

**Comment by leungwensen** [comment]
@JacobYChan 你说的这个 case 是符合图形语法定义的，action 和 pv 映射到 position 属性，值一样的时候映射到同一个区域，这是正确的。如果不这样的话就有问题了。
