### ISSUE TITLE
多个维度（多chart.view）数据在一个表展示的问题，legend图例不显示问题~

### ISSUE THREAD

**Issue by anjorweb** [antvis/g2#682]
Version：3.1.2

产品需求是把多维度（客户下单数、支付金额、退单金额、转换率等）的数据展示到一个chart上，我的做法是创建多chart.view()，然后scale归一操作，可以画出折线，但是显示不出来legend图例了呢~望指教~

数据格式：
客户下单数：
`
[
{day: 1, type: "kedan", value: 14},
{day: 2, type: "kedan", value: 12},
{day: 3, type: "kedan", value: 149},
{day: 4, type: "kedan", value: 112},
{day: 5, type: "kedan", value: 131},
{day: 6, type: "kedan", value: 112}
]
`
支付金额：
`[
{day: 1, type: "pay_money", value: 10202},
{day: 2, type: "pay_money", value: 10201},
{day: 3, type: "pay_money", value: 12202},
{day: 4, type: "pay_money", value: 11202},
{day: 5, type: "pay_money", value: 10102},
{day: 6, type: "pay_money", value: 12923}
]`
其余维度也是这类格式，请问为什么不显示图例呢，是哪里写错了么~

**Comment by leungwensen** [comment]
这个数据不需要用多 view，可以这么写：

```js
chart.line().position('day*value').color('value');
```

这样就出来 legend 了。3.x 多个 view 不会生成 legend，只有 color、shape、size 这些属性映射到某个字段的时候才会生成图例。 https://antv.alipay.com/zh-cn/g2/3.x/tutorial/legend.html#

**Comment by luichooy** [comment]
> 这个数据不需要用多 view，可以这么写：
> 
> ```js
> chart.line().position('day*value').color('value');
> ```
> 
> 这样就出来 legend 了。3.x 多个 view 不会生成 legend，只有 color、shape、size 这些属性映射到某个字段的时候才会生成图例。 https://antv.alipay.com/zh-cn/g2/3.x/tutorial/legend.html#

假设一个chart中有 4 条折线，其中两条折线使用同一个 y 轴（例如这两条折线都表示人数，所以需要使用同一个 y 轴），剩下两条分别使用两条 y 轴（单标的含义不同，比如一个是金额，一个是百分比，多以需要分别使用不同的 y 轴），一共有 3 条 y 轴，那么这个时候，也是只能显示出共用 y 轴的两个折线的图例，单独使用一条 y 轴的折线的图例都不显示，请教一下  有什么办法吗

**Comment by SmaileLee** [comment]
![image](https://user-images.githubusercontent.com/52134354/79195737-5c148e80-7e61-11ea-8bb6-4e83ff3a5d96.png)
希望 自定义 legend 能加一个配置默认不选中，这个问题就可以解决了
