### ISSUE TITLE
Chart  的 padding  失效 （官网例子可看）

### ISSUE THREAD

**Issue by handyzhang** [antvis/g2#685]
![image](https://user-images.githubusercontent.com/32894109/41413237-0af2753c-7015-11e8-8005-182905387557.png)

**Comment by leungwensen** [comment]
并没有失效，只是图表上部分留给 legend 的空间太小了（20 px）。下方的空隙是分面内部布局造成的，和 padding 关系不大。你可以调一下 padding 的数值看看

**Comment by handyzhang** [comment]
Hi,绝云
    不只是分面会出现这个情况，我目前使用的是柱状图。在不为其设置任何内部布局时，legend 设置为top 就会被遮挡。我需要调整谁的padding，因为调整chart的padding 无法解决这个BUG?

**Comment by handyzhang** [comment]
![image](https://user-images.githubusercontent.com/32894109/41446550-c9e5a1a4-7082-11e8-9e4b-98ad74ae0b9a.png)
![image](https://user-images.githubusercontent.com/32894109/41446556-d09252d6-7082-11e8-8c37-b54199bd1fdb.png)

 // 设置图例
        chart.legend({
            // position: 'top',// 设置图例的显示位置
        });

**Comment by leungwensen** [comment]
加一个 padding: 'auto' 吧。

```js
const chart = new G2.Chart({
   // ...
   padding: 'auto'
});
```

**Comment by handyzhang** [comment]
3Q
