### ISSUE TITLE
【文档问题】装载数据部分表述

### ISSUE THREAD

**Issue by billfeller** [antvis/g2#687]
* **G2 Version**: 3.2.0-beta.3
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

[装载数据 -> 更新数据 -> 更新数据](https://antv.alipay.com/zh-cn/g2/3.x/tutorial/load-data.html#__%E6%9B%B4%E6%96%B0%E6%95%B0%E6%8D%AE)

~~如果仅仅是更新数据，而不需要马上更新可以调用 chart.source(data) 需要更新图表时调用 chart.repaint()~~

建议：

**如果仅仅是更新数据，而不需要马上更新图表，可以调用 chart.source(data)， 需要更新图表时调用 chart.repaint()**

![image](https://user-images.githubusercontent.com/998505/41504338-16d45e5a-721e-11e8-93f4-27eed5b1275b.png)

**Comment by leungwensen** [comment]
已修复
