### ISSUE TITLE
【文档问题】“图表类型和和图形形状” 多了一个“和”

### ISSUE THREAD

**Issue by billfeller** [antvis/g2#688]
* **G2 Version**:3.2.0-beta.3
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

[图表类型和和图形形状](https://antv.alipay.com/zh-cn/g2/3.x/tutorial/chart-type.html#_%E5%9B%BE%E8%A1%A8%E7%B1%BB%E5%9E%8B%E5%92%8C%E5%92%8C%E5%9B%BE%E5%BD%A2%E5%BD%A2%E7%8A%B6) 标题多了一个“和”

**Comment by leungwensen** [comment]
已修复
