### ISSUE TITLE
拆线图Y轴的度量问题

### ISSUE THREAD

**Issue by arronf2e** [antvis/g2#69]
比如我的数据是 2 ,5, 7, 9 ,10 ,11.89
然后y轴的自动度量是  2,4,6,8,10
导致 11.89那段线被遮挡了，怎么解决

**Comment by dxq613** [comment]
你是否指定了 列的 min ,max，否则不会出现超出的情况，或者你的y轴对应的数据是字符串

**Comment by arronf2e** [comment]
@dxq613  嗯，已找到原因，多谢回答
