### ISSUE TITLE
请问Guide.Region只支持水平方向的吗？ 没有垂直方向的吗？

### ISSUE THREAD

**Issue by houzip** [antvis/g2#690]
请问Guide.Region只支持水平方向的吗？ 没有垂直方向的吗？

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_chart.guide.region-cfg-  region 指定的是起始位置和终止位置，两个点确定一个矩形，没有所谓水平垂直的说法。
