### ISSUE TITLE
Transform 是否能够提供独立的调用的方式来处理数据，不基于DataSet

### ISSUE THREAD

**Issue by VanquisherMe** [antvis/g2#692]
* **G2 Version**:3.1.2
* **Platform**: react
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

在二次封装 g2 的过程中，我想把转换数据放在，图表的配置封装之外，但是发现 lengend操作后，依然拿到课上层组件的完整数据，现在的解决方案是再上一层组件再创建一个dv 然后传入 dv.rows 到组件中，但是这样感觉不太好，所以是否能够将 Transform 也能够以函数的形式独立引用，这样在图标封装以外我可以直接调用工具转换函数来处理数据。我尝试用过DataSet.getTransform 但是这个拿到的入参依然是 dv

**Comment by leungwensen** [comment]
"legend 操作后依然拿到完整数据"是什么意思，能不能提供 codepen 代码？

**Comment by VanquisherMe** [comment]
> "legend 操作后依然拿到完整数据"是什么意思，能不能提供 codepen 代码？
这是我自己的一个失误
但是希望能将 Transform 支持到独立函数调用，会更利于封装吧，这样g2 的封装中我可以完全只是配置项，比如在用dva.js 数据转换我放在了 model层 但是我需要在这里 new 一个dv，感觉没有必要，如果提供了独立的调用 Transform 的方式我这里只需要用这个对 数据做出处理就可以了.
之前用 bizcharts，但是这里有一些更新的问题，因为g2 的更新修复 bizcharts 引用的g2 版本不能及时更新，所以果断放弃只能自己做出封装，没有其他问题了
