### ISSUE TITLE
[question] hive plot

### ISSUE THREAD

**Issue by amcdnl** [antvis/g2#694]
Is a [hive plot](http://datavizproject.com/data-type/hive-plot/) something that is doable in this library?

**Comment by leungwensen** [comment]
not yet, will be included before version 3.5 (2018-10-15)

**Comment by amcdnl** [comment]
@leungwensen - Has any work started on it? If not, could you give me some pointers I'd love to help contribute.

**Comment by dxq613** [comment]
Move to the #1394 as a new feture of g2 4.0.
