### ISSUE TITLE
请问柱状图和时间条形图支持调节柱图之间的间距和柱的宽度吗

### ISSUE THREAD

**Issue by secreter** [antvis/g2#698]
请问柱状图和时间条形图支持调节柱图之间的间距和柱的宽度吗？文档中只有分组的可以调节。

**Comment by dxq613** [comment]
https://github.com/antvis/g2/blob/master/src/global.js#L18
这个参数可以控制全局的柱状图的宽度，没有在文档上放出来

**Comment by secreter** [comment]
非常感谢~问题解决了，g2是一个非常棒的可视化库，希望文档能逐渐更加完善，我会继续学习的！

**Comment by atdow** [comment]
https://github.com/antvis/g2/blob/master/src/global.js#L18 这个链接已经失效，请问是否还有可以访问的链接

**Comment by Alisa0026** [comment]
> https://github.com/antvis/g2/blob/master/src/global.js#L18
> 这个参数可以控制全局的柱状图的宽度，没有在文档上放出来

连接失效了，有可以访问的连接吗

**Comment by guojingwen** [comment]
同问
