### ISSUE TITLE
混合图形下面无法显示legend？

### ISSUE THREAD

**Issue by onecorner** [antvis/g2#699]
您好，这是我的demo，https://codepen.io/onecorner/pen/WJdewO
请问一下，这里面为什么只显示了两个legend？
还有就是y轴可以合并吗？且x轴发生了位移！

**Comment by leungwensen** [comment]
1. legend 是由字段映射到 size / shape / color 这样的通道形成的 https://antv.alipay.com/zh-cn/g2/3.x/tutorial/legend.html
2. x 轴因为柱状图用了两个字段，所以会有两个柱子对应一个位置所以看起来只有一个柱子的地方就像由偏移了

**Comment by onecorner** [comment]
文档看了，但是没有看懂，所以意思是说我需要将size，shape，color都设置一下，并且设置成不同的值吗？

**Comment by onecorner** [comment]
还是说我这里面只能生成两个图例，不能生成三个？因为我的数据源里面已经整合了两个字段？所以legend只能从这里面获取？如果是这样，有没有办法可以解决呢？
