### ISSUE TITLE
数据点浮在提示框上面去了

### ISSUE THREAD

**Issue by ycoe** [antvis/g2#70]
使用手机流浏览器打开：http://m.fangdd.com/sz/fangjia/   点下报表左边，很容易重现
![wechatimg1](https://cloud.githubusercontent.com/assets/985424/21881170/bf98f2de-d8dd-11e6-9b87-d3864252dccd.jpeg)

**Comment by simaQ** [comment]
恩，我复现了，感谢反馈，我们会尽快修复。

**Comment by CHAACC** [comment]
@ycoe 你这个tooltip怎么支持的mousemove事件的，我移动端不行，只能用click事件，麻烦告诉我一下

**Comment by ycoe** [comment]
@CHAACC 我没有特殊处理，默认报表都有呀
