### ISSUE TITLE
ticks设置后tickLine位置错误

### ISSUE THREAD

**Issue by lvovl** [antvis/g2#700]
[https://antv.alipay.com/zh-cn/g2/3.x/demo/line/basic.html](https://antv.alipay.com/zh-cn/g2/3.x/demo/line/basic.html)

ticks设置后tickLine位置错误
* **G2 Version**: 3.1.1 3.1.2
* **Platform**: chrome
* **Mini Showcase(like screenshots)**:
<img width="825" alt="wx20180625-114440 2x" src="https://user-images.githubusercontent.com/13954991/41829420-3a667e2a-786d-11e8-8252-23654e4adf76.png">

**Comment by leungwensen** [comment]
位置没错，这个是 3.1.x 后 cat 类型坐标轴 tickLine 的默认位置（tickLabel 在 tickLine 中间）

**Comment by lvovl** [comment]
fine
