### ISSUE TITLE
请教下，轴线如何偏移？

### ISSUE THREAD

**Issue by 285858315** [antvis/g2#702]
如图：![_20180625173543](https://user-images.githubusercontent.com/2813953/41842794-5b13e730-789e-11e8-8be0-2da4ece20fac.png)

**Comment by leungwensen** [comment]
发一下代码，是不是设置了 x 轴的 range？

**Comment by Me-Momo** [comment]
我看了一下，好像是因为time属于连续性数据类型，因此没有坐标轴没有左右留白的原因，手动设置x轴度量的type为timeCat就解决了。我的做法如下：
```
const defs = {
  ptime: {
    type: 'timeCat', 
  },
  count: { },
};
chart.source(data, defs);
```
G2官网的说法:
> timeCat 和 time 类型度量的差别和应用场景
> timeCat 是分类类型的度量，所以适合于显示 柱状图 或者固定时间内没有数据的场景（股票图）
> time 是连续类型的度量，更适合显示折线图、面积图，表现数据的趋势

但是在这种折线图+柱形图的情况下就出现问题了

**Comment by leungwensen** [comment]
cat 或者 timeCat 类型的会在两边留白，这个留白也是可以通过 range 来配置的。柱状图一般适用于 x 轴为 cat 或者 timeCat 的场景。
