### ISSUE TITLE
legend 上无法调整 title 的位置，想要 legend title 跟 legend 同行。

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#704]
如题。

![image](https://user-images.githubusercontent.com/3838676/41887229-6756d446-7932-11e8-85eb-068c2941a285.png)

**Comment by leungwensen** [comment]
目前比较简单的方法是使用 HTML 定制 legend： https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#________%E5%8F%82%E6%95%B0

**Comment by weepy3641** [comment]
嗯， 已经解决了。
