### ISSUE TITLE
feat: 数据设置nice=true的时候，能否控制与上边界的距离？

### ISSUE THREAD

**Issue by stanleyxu2005** [antvis/g2#705]
* **G2 Version**: 3.1.1
* **Platform**: Chrome v67
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

----

我在封装一个类似iOS 12那种Daily Activity Bar Chart。
![image](https://user-images.githubusercontent.com/5162687/41928356-7b7aff86-79a7-11e8-8ac8-340055570544.png)

----

初步实现并不难，就是细节上还是做不到1:1还原。目前遇到最大一个问题是，背景文字和数据柱有时候会碰到。比如截图里面右侧倒数第三根柱子和上面的6P是重叠了。
![image](https://user-images.githubusercontent.com/5162687/41927524-11266fe6-79a5-11e8-8406-f3b9405afafc.png)

我现在有一个思路是通过动态计算单根柱子数值的最大值然后通过乘以一个系数来设置y轴的max值。
比如说单根柱子最大值是100，我可以通过设置100*1.2给y轴留空。但是因为我希望背景文字大小根据图的大小变化，所以这个留空的计算其实还是蛮罗嗦的。（具体做法是plot的高度减去字体高度等于最大单柱高度，倒推出y轴的max）

不知道现在的版本有没有简单的办法做这个事情？如果不行的话，我想提一个feature request：将
```javascript
chart.source(myData, {
  y: {
    nice: true
  }
})
```
变成
```javascript
chart.source(myData, {
  y: {
    nice: {
       paddingTop: '20px'
    }
  }
}
```

**Comment by leungwensen** [comment]
nice true 的时候，并不能控制最高的“柱子”和画布上边界的距离，这个完全是看具体数据的。设置 nice false 的时候，最高的“柱子”一定是顶到上边界的。如果需要控制上边界，可以在 new chart 的时候设置 padding

**Comment by stanleyxu2005** [comment]
@leungwensen 用padding似乎解决不了这个问题，原因是图中的12A,6A,12P,6P包括背景色和垂直线是通过`chart.guide().region()`来生成的。padding是非plot的区域。region可以超出plot的区域吗？

**Comment by dxq613** [comment]
region 的 start，end 可以超出 plot ，数据比 max 大就行了。

**Comment by stanleyxu2005** [comment]
@dxq613 完美搞定。我把'max'改成了700，虽然不知道这个值是怎么计算的...
![image](https://user-images.githubusercontent.com/5162687/41961290-a4ec7bce-7a24-11e8-9665-3cd10fdc00fd.png)

**Comment by stanleyxu2005** [comment]
感觉还是需要能对y轴数据设置明确的top padding。原因是我通过复杂计算是可以给region绘制出对应当前s据合理的图形，但是如果数据改变了，调用了changeData，region要根据新的数据重新计算，这个计算非常繁琐，感觉就没意义了。

**Comment by maplor** [comment]
后续讨论转移到 https://github.com/antvis/scale/pull/2 内。欢迎大家提供自己的意见。
