### ISSUE TITLE
新功能：timelines

### ISSUE THREAD

**Issue by pinggod** [antvis/g2#71]
蚂蚁中间件团队最近在做的一个产品需要跟踪数据在不同产品之间的流动链路，但是目前 G2 没有提供该图例，请问是否有计划开发该图例或是否可以在此提出此种图表的需求。

![2017-01-16 14 35 29](https://cloud.githubusercontent.com/assets/9530963/21973109/25542922-dbf9-11e6-8e24-523e7284304c.png)

可以参考：

1. https://developers.google.com/chart/interactive/docs/gallery/timeline
2. chrome devtool network panel

**Comment by dxq613** [comment]
这种图，通过g2很容易封装起来的，我们钉钉上聊吧。 萧庆
