### ISSUE TITLE
padding auto 需要顶到边

### ISSUE THREAD

**Issue by leungwensen** [antvis/g2#710]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by maplor** [comment]
关于这一点有些疑议，不是所有情况下都希望 auto 顶边，希望能像 Highcharts 一样，可以设置 auto 后剩下的间距。

**Comment by dxq613** [comment]
有个属性没放出来： autoPaddingAppend，默认值是 5 ，可以将这个值设置成 0 就没有边距了，用户也可以改这个属性。

**Comment by leungwensen** [comment]
实践中九色鹿发现如果顶到边的话会有 tooltip 高亮圆点显示不全的问题，直接配置 autoPaddingAppend 即可

**Comment by dxq613** [comment]
文档上可以补充一下这个属性，当时以为用户用不到。

**Comment by maplor** [comment]
直接顶边确实是有问题的，例如左padding为 0 的话第一项数据的tooltip会无法触发。或者 tooltip marker 会无法完全显示等等。

**Comment by mynameismaosheng** [comment]
padding: auto,
autoPaddingAppend: 0,
会出现这样的情况 x轴的会隐藏掉一半
![f981930911c563bc20019228a0ad2b8](https://user-images.githubusercontent.com/19756360/59584240-0f143e80-9110-11e9-9294-8deb66756cfa.png)
