### ISSUE TITLE
请问g2无法识别YYYY-MM-DD HH:mm这种为time类型属于正常现象吗？

### ISSUE THREAD

**Issue by aa1011372655** [antvis/g2#714]
* **G2 Version**: 3.1.2
* **Platform**: mac
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/8445734/42082985-1c4153be-7bbc-11e8-9c10-1b2d5d545327.png)

* **CodePen Link**: https://codepen.io/anon/pen/rKoWya

请问我在使用g2时，传入的x轴值为YYYY-MM-DD HH:mm，我发现g2无法识别为time格式，导致数据过多时直接挤到了一团，本身我可以强制使用scale将类型转化为time类型，主要是想了解一下这是正常的吗？本身就不支持识别这种类型？

**Comment by leungwensen** [comment]
只支持标准的格式：  '2015-03-01', '2015-03-01 12:01:40', '2015/01/05','2015-03-01T16:00:00.000Z'

具体自定义的 format 没法枚举，所以得自己规范化一下

**Comment by aa1011372655** [comment]
ok，了解，多谢
