### ISSUE TITLE
折线图如何跟柱状图组合，支持多种图标的混合展现吗？

### ISSUE THREAD

**Issue by xiaxia2017** [antvis/g2#715]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by xiaxia2017** [comment]
http://antvis.github.io/g2/demo/18-other/double-axis.html

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/gallery/g2/double-axes.html

**Comment by giscafer** [comment]
https://antv-g2.gitee.io/zh/examples/other/other#double-axes
