### ISSUE TITLE
G2 webpack 打包时过大的问题

### ISSUE THREAD

**Issue by w3286879** [antvis/g2#716]
webpack 打包时antv  居然有2MB,请教怎么排除打包？
externals 也设置了 g2 和 antv

**Comment by leungwensen** [comment]
externals 应设置 `@antv/g2`，也就是 require 的时候写的 package 名称

**Comment by zzfGood** [comment]
why closed?

**Comment by xiaoshuishuihuohuo** [comment]
config.externals({
      'vue': 'Vue',
      'vuex': 'Vuex',
      'vue-router': 'VueRouter',
      'axios': 'axios',
      'element-ui': 'ELEMENT',
      '@antv/g2': 'G2',
})
