### ISSUE TITLE
3.0.x 版本tickline位置问题

### ISSUE THREAD

**Issue by muyucanqiu** [antvis/g2#718]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

https://antv.alipay.com/zh-cn/g2/3.x/demo/line/series.html
3.0.x 版本cat 类型坐标轴 tickLine 的默认位置（tickLabel 在 tickLine 中间）
请问可不可以设置为原来的tickLabel与tickLine与图像中的点在一条直线对齐的 如何配置？
![line](https://user-images.githubusercontent.com/15388391/42143935-a07cd9b6-7dea-11e8-9bd4-a957206ab31c.jpg)

**Comment by hawaiiey** [comment]
官网的例子居然也是这样的问题
我自己写的组件 开发环境没问题 到了生产环境也出现这样的问题
这应该不是配置的问题 就是 bug

**Comment by leungwensen** [comment]
这是 3.1.x 开始的样式，cat 类型的字段 tickLabel 位于两个 tickLine 之间。

**Comment by muyucanqiu** [comment]
然而 绝云老哥 文档中没有找到配置的项啊 就是3.1.x以后的版本就只能tickLabel 位于两个 tickLine 之间了呗 不能配置成以前的那种tickLabel与tickLine与图像中的点在一条直线对齐的？
![1](https://user-images.githubusercontent.com/15388391/42194880-aefc6cae-7ea8-11e8-846f-454bd72c9f84.jpg)
上图X轴两侧各多出来一个刻度
![11](https://user-images.githubusercontent.com/15388391/42194892-c6382796-7ea8-11e8-973d-c76b7ac286bb.jpg)
上图官网的例子12个月份坐标轴等分6份时最后的月份那里又不能等分了 
所以这个3.1.x的X轴的tickLabel与tickLine的位置问题我觉得是有BUG

**Comment by leungwensen** [comment]
两侧多一个刻度和 设置了 tickCount 的地方是个 bug，这周会发掉。

**Comment by leungwensen** [comment]
@paleface001

**Comment by muyucanqiu** [comment]
但是tickLabel与tickLine与图像中的点在一条直线对齐 这个是没有配置了吗 只能默认tickLabel 位于两个 tickLine 之间吗

**Comment by dxq613** [comment]
最好默认还是 3.0 的样式，开放个属性可以让用户选择 tick 的位置就好了，这种文本在 tick 中间的方式在设置了 tickCount 后，确实会出现问题。
