### ISSUE TITLE
调用 chart.render() 多次会多出几个图例

### ISSUE THREAD

**Issue by mystorp** [antvis/g2#72]
我是参考文档里面快速上手的例子，然后在控制台输入`chart.render()`发现的，版本是 2.2.1。

**Comment by simaQ** [comment]
如果是要多次 render()，是需要调用 chart.repaint() 的，多次调用 render() ，图表上的坐标轴几何元素也都会重绘多次>

**Comment by mystorp** [comment]
OK，了解了。不过我觉得这个方法可以优化一下，要么私有，要么维持一个是否已渲染的内部状态
`isRendered ? chart.repaint() : chart.render()`

**Comment by dxq613** [comment]
我们其实倾向于用户，调用 chart.clear()，然后重新声明一遍 chart.line之类的再调用chart.render();

**Comment by mystorp** [comment]
😊好吧
