### ISSUE TITLE
Bar's width overlay the yAxis

### ISSUE THREAD

**Issue by Evoque** [antvis/g2#720]
As shown below:

![not](https://user-images.githubusercontent.com/3809046/42150135-587f33ea-7e0b-11e8-9ec0-0e76f9c9bb67.png)

**Comment by leungwensen** [comment]
因为 year 字段呗解释成 time 类型了（也就是 linear，线性字段类型）。柱状图可以把 x 轴配置为分类字段，这样就正常了。

```js
chart.source(data, {
  year: {
    type: 'timeCat'
  }
});
```
