### ISSUE TITLE
同一图形，开发环境正常，生产环境 bug 明显

### ISSUE THREAD

**Issue by hawaiiey** [antvis/g2#721]
* **G2 Version**: 3.0.8
* **Platform**: react v15.4.4 antd v2.10.0
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

> 相同的页面 相同的 screen width 相同的 Card width

> 更奇怪的是：canvas width 也是相同的

### 开发环境：
![18_04_04__07_02_2018](https://user-images.githubusercontent.com/25291779/42159558-d113a406-7e26-11e8-8921-1f79a3175813.jpg)
![18_06_24__07_02_2018](https://user-images.githubusercontent.com/25291779/42159564-d6c6db52-7e26-11e8-9e92-b8b3be43b912.jpg)

### 生产环境：
![18_02_58__07_02_2018](https://user-images.githubusercontent.com/25291779/42159583-e7bedbda-7e26-11e8-8272-3939b37fb413.jpg)
![18_05_49__07_02_2018](https://user-images.githubusercontent.com/25291779/42159599-f0c0e7fa-7e26-11e8-9064-cabc78bf10ed.jpg)

> 生产环境下 StackedArea 组件，在改变 width 触发 resize 的效果特别奇怪

> Card width 变小，实际图形 width 居然还变大

**Comment by hawaiiey** [comment]
@leungwensen 两个环境容器宽度都正常 但是渲染效果差别很大

**Comment by leungwensen** [comment]
能用 codepen 复现吗？这个链接就是生产环境的 G2：

`https://gw.alipayobjects.com/os/antv/pkg/_antv.g2-3.2.0-beta.6/dist/g2.min.js`

**Comment by leungwensen** [comment]
你先把 padding auto 去掉，我们看一下这个问题

**Comment by hawaiiey** [comment]
@leungwensen 可以先帮我解决 labelLine 和 labelTick 没有垂直对齐的问题吗

**Comment by leungwensen** [comment]
@hawaiiey cat 类型现在默认 tickLabel 是在两个 tickLine 之间的。这两周会发布一个版本把这个做成配置项

**Comment by leungwensen** [comment]
已解决 axis 的 tickLine 可以配置 alignWithLabel: true
