### ISSUE TITLE
当数据只有一条时，如何使线图唯一的点在中间？

### ISSUE THREAD

**Issue by aa1011372655** [antvis/g2#725]
* **G2 Version**:3.1.2
* **Platform**:mac
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/8445734/42209984-a56a5aea-7ee2-11e8-8c7f-ddb661973d52.png)

* **CodePen Link**:https://codepen.io/anon/pen/eKXxMX

如果线图只有一个点时，建议显示在中间，另外，当前版本，我如何设置让点在中间？非常感谢

**Comment by dxq613** [comment]
把你设置的 range 去掉就好了：
```
chart.scale('year', {
  //range: [ 0 , 1 ]
});
```

**Comment by aa1011372655** [comment]
非常感谢，犯二了
