### ISSUE TITLE
如何支持中断型折线图？

### ISSUE THREAD

**Issue by zwei8908** [antvis/g2#728]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

比如数据是
[{
  date: '2018-01-01',
  value: 3
}, {
  date: '2018-01-02',
  value: 3.5
}, {
  date: '2018-01-04',
  value: 5
}, {
  date: '2018-01-05',
  value: 4.9
}]

(缺少了'2018-01-03')

如何支持'2018-01-01'和'2018-01-02'相连，'2018-01-03'和'2018-01-04'相连，中间展示tick'2018-01-03'，但是是中断的？

如下图
![linechart](https://user-images.githubusercontent.com/3939596/42255191-21a4b07a-7f7d-11e8-9227-a06898b68f81.jpg)

**Comment by leungwensen** [comment]
拆分数据，用两个 view 画，x 轴字段 scale 配置 sync: true
