### ISSUE TITLE
柱形图 外部容器宽度改变时重绘legend 位置异常

### ISSUE THREAD

**Issue by yuanguandong** [antvis/g2#729]
柱形图 外部容器宽度改变时重绘legend 位置异常
chart.interval().position('genre*sold').color('genre')
第一次初始化正常
![image](https://user-images.githubusercontent.com/13197560/42263225-f71c1a0a-7f9f-11e8-8ab8-487d7c27abac.png)

resizeyichang异常
![image](https://user-images.githubusercontent.com/13197560/42263176-ce5d76ea-7f9f-11e8-859c-7731dd94c5f0.png)

**Comment by aa1011372655** [comment]
我看3.2.1版本修复了，可以更新一下
