### ISSUE TITLE
咨询沟通方式

### ISSUE THREAD

**Issue by ass233** [antvis/g2#735]
想咨询下有没有交流群？想加入

**Comment by leungwensen** [comment]
有个外部的钉钉交流群

![5be6d8f1-bfec-406c-95ff-29d2620fd600_ b b27bac7](https://user-images.githubusercontent.com/1655789/42428778-0f9d91dc-8368-11e8-9ebe-b17af1fc438e.jpg)

**Comment by Airkro** [comment]
能像G6一样建官方群吗
