### ISSUE TITLE
饼图label的位置调整适应

### ISSUE THREAD

**Issue by SlimJason** [antvis/g2#74]
小白用户求问：这个label的位置怎么能做到适应啊，最好是在旁边。。。可以设置么
有丁丁群吗？这样问好累啊
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>饼图</title>
    <script src="https://a.alipayobjects.com/jquery/jquery/1.11.1/jquery.js"></script>
    <script src="https://a.alipayobjects.com/g/datavis/g2/2.2.1/g2.js"></script>
  </head>
  <body>
    <div id="c1"></div>
    <script>
      var data = {
      	peekRadio:88,
        valleyRadio:12,
        peekQ:230,
        valleyQ:30,
        billQUnit:'度'
      }
      var dataSource = [{
			name: '峰时',
			value: data.peekRadio,
			num: data.peekQ
		},{
			name: '谷时',
			value: data.valleyRadio,
			num: data.valleyQ
		}];
		var Stat = G2.Stat;
		var g2PvChart = new G2.Chart({
			id: 'c1',
			forceFit: true,
			height: 200,
			plotCfg: {
				margin: [10, 0, 10, 0],
			}
		});
		g2PvChart.source(dataSource);
		// 重要：绘制饼图时，必须声明 theta 坐标系
		g2PvChart.coord('theta', {
			radius: 1,
			inner: 0.6
		});
		g2PvChart.tooltip(false);
		g2PvChart.legend(false);
		g2PvChart.intervalStack()
			.position(Stat.summary.percent('value'))
			.color('name', ['#FF6242','#FFD02D'])
			.label('name*..percent', function(name, percent) {
				var label = "";
				if (name == '峰时') {
					label = name + data.peekQ + ' ' + data.billQUnit;
				} else if (name == '谷时') {
					label = name + data.valleyQ + ' ' + data.billQUnit;
				}
				return label;
			});
		g2PvChart.render();
      // 设置默认选中
      var geom = g2PvChart.getGeoms()[0]; // 获取所有的图形
      var items = geom.getData(); // 获取图形对应的数据
      geom.setSelected(items[3]); // 设置选中
    </script>
  </body>
</html>

**Comment by simaQ** [comment]
你好，有钉钉群，请扫码加入：

![g2](https://cloud.githubusercontent.com/assets/6628666/22092774/63a7b3ee-de3b-11e6-9626-f0219f4893ca.jpg)

**Comment by emmaccacca** [comment]
二维码只加载出来一半

**Comment by ShawshankLin** [comment]
二维码过期了，麻烦再发下
