### ISSUE TITLE
请教一下 这个tip变成白色是那个属性控制的？

### ISSUE THREAD

**Issue by JulesCesar** [antvis/g2#742]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/19618696/42548892-fcc7bde0-84fb-11e8-9fc5-48b259d33a3b.png)
https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_tooltip

我的现在是黑色。想变成例子里的蓝色。实在是不知道具体的那个代码是控制它的 ，请赐教
![image](https://user-images.githubusercontent.com/19618696/42548933-2f18cf32-84fc-11e8-9e36-71c64dd644cd.png)

**Comment by leungwensen** [comment]
这是 3.2 的新主题，升级一下版本就可以了。 `@antv/g2@3.2.2`
