### ISSUE TITLE
图例点击时可以切换隐藏和显示，能不能设置默认显示指定几个图例，其它图例只是隐藏，点击时还可以显示

### ISSUE THREAD

**Issue by kongqingfei** [antvis/g2#749]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

图例点击时可以切换隐藏和显示，能不能设置默认显示指定几个图例，其它图例只是隐藏，点击时还可以显示

**Comment by leungwensen** [comment]
可以用 filter 接口： https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_filter

**Comment by kongqingfei** [comment]
@leungwensen 谢谢，可以使
