### ISSUE TITLE
Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by vxzhong** [antvis/g2#75]
当通过combinColumns生成一列，设置type会报错。但是一开始数据是空，必须设置type，changeData才能渲染出来。

TypeError: Cannot read property 'toString' of undefined
    at e (index.js:2)
    at index.js:2
    at r.each (index.js:1)
    at Function.groupToMap (index.js:2)
    at Function.group (index.js:2)
    at d._groupFrames (index.js:12)
    at d.processData (index.js:12)
    at index.js:4
    at Object.each (index.js:9)
    at f._initGeoms (index.js:4)

大致的代码如下：

const Line = createG2((chart, data) => {
  let frame = new Frame(data)

  frame.addCol('avg_device_using', function () {
    return Math.floor(Frame.mean(frame, 'device_using'))
  })
  frame.addCol('avg_using_rate', function () {
    return Frame.mean(frame, 'using_rate');
  })
  frame = Frame.combinColumns(frame, ['device_total', 'device_using', 'avg_device_using'],
    'device', 'device_type', ['day', 'using_rate', 'avg_using_rate'])

  frame = Frame.combinColumns(frame, ['using_rate', 'avg_using_rate'], 'rate', 'rate_type')

  chart.source(frame, {
    day: {
      type: 'cat',
      alias: '日期',
    },
    device: {
      type: 'linear',
      alias: '数量',
      formatter: function (value) {
        return value + '台'
      }
    },
    rate: {
      type: 'linear',
      alias: '率(%)',
      // formatter: function (value) {
      //   return value.toFixed(2) + '%'
      // }
    },
    device_type: {
      type: 'cat',
      // formatter: function (value) {
      //   switch (value) {
      //     case 'device_total':
      //       return '设备数量'
      //     case 'device_using':
      //       return '开机数量'
      //     case 'avg_device_using':
      //       return '平均开机量'
      //     default:
      //       return value
      //   }
      // }
    },
    rate_type: {
      type: 'cat',
      // formatter: function (value) {
      //   switch (value) {
      //     case 'avg_using_rate':
      //       return '平均开机率'
      //     case 'using_rate':
      //       return '开机率'
      //     default:
      //       return value
      //   }
      // }
    }
  })
  chart.legend({
    position: 'bottom',
    title: null,
  })
  chart.line().position('day*device').color('device_type').shape('smooth').size(2)
  chart.line().position('day*rate').color('rate_type', ['#1bbd19', '#fa513a']).shape('smooth').size(2)
  chart.render()
})

**Comment by vxzhong** [comment]
调试下来，应该是在changeData的时候出错的。
if (newData !== oldData) {
        this.chart.changeData(newData);
      }

**Comment by jaredleechn** [comment]
@ch-daisy 是不是今天你遇到的那个问题？
