### ISSUE TITLE
折线图设置crosshairs.type为'rect'无效

### ISSUE THREAD

**Issue by Me-Momo** [antvis/g2#751]
* **G2 Version**: 
* **Platform**: 
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/15646325/42814574-337174da-89f7-11e8-9b83-4fe4d44e53a6.png)
期望效果如图2:
![image](https://user-images.githubusercontent.com/15646325/42814595-44e6b298-89f7-11e8-84f5-1fc761e435a3.png)

* **Riddle Link**: https://riddle.alibaba-inc.com/riddles/7ce85dd1

给折线图设置crosshairs.type为'rect'，不能和柱形图一样显示矩形背景吗
```
chart.tooltip({
 crosshairs: {
   type: 'rect',
   style: {
     // 图形样式
   }
  },
});
```

**Comment by aa1011372655** [comment]
源码中是根据geom的size进行计算的crosshairsRectShape.attr(attr, 3 * firstItem.size / 2)，所以宽度是0，如果是线图的话，需要默认设置上宽https://riddle.alibaba-inc.com/riddles/17c203cb

**Comment by Me-Momo** [comment]
@aa1011372655 好的 谢谢哈. 还是得多看看源码 👏

**Comment by Airkro** [comment]
您好，请问在3.x版本如何实现？
