### ISSUE TITLE
曲线折线图是否可以使用其他的数据格式？

### ISSUE THREAD

**Issue by vm-001** [antvis/g2#758]
https://antv.alipay.com/zh-cn/g2/3.x/demo/line/curved.html 我从贵方文档里看到需要使用
`
[{
  month: 'Jan',
  Tokyo: 7.0,
  London: 3.9
}, {
  month: 'Feb',
  Tokyo: 6.9,
  London: 4.2
}]
`
这种数据格式，Tokyo与London会成为两条曲线。

现在我有数据是这样
`
[
        { date: '2018-07-11', origin_type: 'a', words: 10},
        { date: '2018-07-11', origin_type: 'b', words: 20},
        { date: '2018-07-12', origin_type: 'a', words: 10},
        { date: '2018-07-12', origin_type: 'b', words: 20},
        { date: '2018-07-13', origin_type: 'a', words: 10},
        { date: '2018-07-13', origin_type: 'b', words: 20},
        { date: '2018-07-14', origin_type: 'a', words: 10},
        { date: '2018-07-14', origin_type: 'b', words: 20},
        { date: '2018-07-15', origin_type: 'a', words: 10},
]
`
想要以origin_type来作为曲线，也就是a与b各成一条曲线，date为横坐标，words为纵坐标。
劳烦了。

**Comment by dxq613** [comment]
其实绘制多条线的方式本质上是：
```js
[{name: 'Jan', value: 20, type: 'a'}, {name: 'Jan', value: 10, type: 'b'},  {name: 'Jan', value: 15, type: 'c'}]
```
这种格式只需要
```js
chart.line().position('name*value').color('type');
```

数据全部加工成这种格式就行了
