### ISSUE TITLE
Update candle chart with few last candles only

### ISSUE THREAD

**Issue by karimhossenbux** [antvis/g2#759]
How would one update the candle chart without updated the whole set of data again?
Say like you have new data for the latest 5 candles or so, how to achieve that?

Thank you in advance!

**Comment by guisturdy** [comment]
use [candlestick](https://antv.alipay.com/zh-cn/g2/3.x/demo/candlestick/basic.html) for example

you can add new data to chart by doing this follows

```javascript
// the data map callback function same with line 35
function mapCallback(obj) {
  obj.trend = obj.start <= obj.end ? '上涨' : '下跌';
  obj.range = [obj.start, obj.end, obj.max, obj.min];
  return obj;
}
// add new data
dv.addRow(mapCallback({time:'2018-07-22',start:8.21,max: 8.30,min: 7.00,end:8.21}))
// updata chart
chart.changeData(dv)
```

**Comment by karimhossenbux** [comment]
Thank you! I'll try that asap :))

**Comment by leungwensen** [comment]
the key point is, you can update data of the chart and re-render it by calling `chart.changeData(newData)`

closing for not further info is provided
