### ISSUE TITLE
g2 饼图 value = 0 不显示

### ISSUE THREAD

**Issue by EagleWolf** [antvis/g2#76]
g2 饼图 value = 0 不显示，
![image](https://cloud.githubusercontent.com/assets/4488399/22100461/aea78c96-de6a-11e6-8a9b-3bddeb27a274.png)

如何显示出来显示0.00%也可以

**Comment by dxq613** [comment]
这个已经修复，春节后回来发布，value = 0的显示文本和线

**Comment by dxq613** [comment]
![image](https://cloud.githubusercontent.com/assets/1264678/22181900/9f3db302-e0d1-11e6-94d0-3c5e178ea073.png)

**Comment by EagleWolf** [comment]
3Q可以关闭了
