### ISSUE TITLE
g2后续是否可以添加支持双X轴的功能呢

### ISSUE THREAD

**Issue by pasBone** [antvis/g2#760]
* **G2 Version**: 3.2.4
* **Platform**: windows10
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/18027183/43060741-c0789598-8e84-11e8-82f0-0f9d9cf571d2.png)

大概是像这种多X轴的对比图。
目前我通过官方的实例只做到了这一步
![image](https://user-images.githubusercontent.com/18027183/43060777-e6df21d4-8e84-11e8-9523-3ebd5b520033.png)
不知道是目前不支持这个功能，还是我打开的姿势不对呢？
如果支持，可否告知一下具体如何配置，如果不支持后续是否可以添加此功能呢？
感谢！

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/gallery/g2/area-rainfall.html

**Comment by pasBone** [comment]
去掉就不是双X轴了， 我这边想达到的效果是双X轴。然后共享一个Y轴，
![image](https://user-images.githubusercontent.com/18027183/43061959-d4a8d3d4-8e89-11e8-9dfb-b80af85ad2d7.png)
大概是上图这样...

**Comment by leungwensen** [comment]
![image](https://user-images.githubusercontent.com/1655789/43063668-142b08b0-8e8f-11e8-8fdb-6a97b5563833.png)

**Comment by pasBone** [comment]
@leungwensen  谢谢您的回答， 我说的是公用一个y轴，好像创建一个view就会自动生成一个y轴吧？
不能实现就算了。感谢！

**Comment by leungwensen** [comment]
@pasBone 这个 case 的数据差异比较大，共用 y 轴的话也可以做，但效果不会很好。共用 y 轴的方法有两个：

1. 把字段变成一个，然后 chart 设置 scale sync 
2. 给两个 y 轴字段 scale 设置相同的 min 和 max，然后隐藏掉其中一个 y 轴

参考 scale 和 axis 的文档：
- https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_chart.scale-field-,-scaleConfig-  
- https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_chart.axis-false-
