### ISSUE TITLE
tooltip消失逻辑

### ISSUE THREAD

**Issue by elaine1234** [antvis/g2#761]
* **G2 Version**: 3.2
* **Platform**:chrome
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

tooltip在鼠标移出主图表区域（例如移到坐标轴，图例上）时不会消失

**Comment by maplor** [comment]
相关的 Issue 还有 #663 和 #554

**Comment by dxq613** [comment]
我在看这段代码，发现目前的 plotleave 事件的逻辑错了，变成 canvas-leave了

**Comment by dxq613** [comment]
两个事件其实都应该做一下监听，防止出现 tooltip 隐藏不了的情况

**Comment by maplor** [comment]
@dxq613  还有一种情况是从图表中直接移出浏览器返回，会无法触发 leave 事件。在 #663 中我贴出了 Highcharts 的解决方案，使用一个内部的定时器来保证效果。

**Comment by dxq613** [comment]
tooltip 内部有定时器控制 tooltip 的显示隐藏的，这个地方的问题可能存在于移出去的事件没监听到。
当然目前 plotleave 的事件实现成了 canvasleave 判定了 toElement 是否是 canvas 这个逻辑有问题。

**Comment by dxq613** [comment]
同时在 plotleave 和canvas leave 时隐藏 tooltip
