### ISSUE TITLE
层叠柱状图时，设置 tooltip shared: false，显示多个字段时，显示了 marker

### ISSUE THREAD

**Issue by dxq613** [antvis/g2#762]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/1264678/43070198-c4edc90a-8ea1-11e8-8d62-37e7071437b7.png)

```js
chart.tooltip({
  shared: false
})

// Step 3：创建图形语法，绘制柱状图，由 genre 和 sold 两个属性决定图形位置，genre 映射至 x 轴，sold 映射至 y 轴
chart.interval().position('month*_value').color('_cate').adjust([{
  type: 'dodge',
  dodgeBy: 'type'
}, {
  type: 'stack'
}]).tooltip('month*_value');

```

**Comment by leungwensen** [comment]
这是什么鬼

**Comment by dxq613** [comment]
是 bug，shared: false 时，chart.showTooltip() 也不生效了，主要是 tooltip 为了计算背后的阴影矩形，所以需要 target，导致了一堆问题。我明天看看修复一下这块逻辑

**Comment by simaQ** [comment]
已修复
