### ISSUE TITLE
如何在自定义图形中，填充扇形？

### ISSUE THREAD

**Issue by aa1011372655** [antvis/g2#765]
* **G2 Version**:3.2.5
* **Platform**:mac
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/8445734/43123190-f7a7db1a-8f55-11e8-878c-70696d95938f.png)

* **CodePen Link**:
https://riddle.alibaba-inc.com/riddles/9f454dc1

我设置了一个自定义的形状，根据颜色平分饼图，画扇形时设置fill后不生效，无法填充扇形，请问如何进行填充？
g库里面arc没有closePath，请问是这里的问题吗？https://github.com/antvis/g/blob/17ea65108a26f4b2b84ac6f62188fb5b4710c9cd/src/canvas/shape/arc.js#L110

**Comment by dxq613** [comment]
别用 arc 吧，用 fan 或者直接用 path 生成，参考一下：https://antv.alipay.com/zh-cn/gallery/g2/pie-slice.html，知道几个0-1 范围的点，通过 parsePath 就能转换成饼图需要的 path

**Comment by aa1011372655** [comment]
非常感谢，arc只能画一个弧度线，用fan可以实现^^
