### ISSUE TITLE
多条折线图重叠，警告缺少字段，如何去掉警告

### ISSUE THREAD

**Issue by childdd** [antvis/g2#766]
会警告  warning: option fields is not specified, will fold all columns. data-set.js?3561:53532

**Comment by childdd** [comment]
如何去掉警告
![qq 20180724163359](https://user-images.githubusercontent.com/26546435/43126570-a0560652-8f5f-11e8-9ab4-3cbc31173dba.png)

**Comment by leungwensen** [comment]
第一个告警是存在多个版本的 G2
第二个告警是使用 fold 这个 transform 的时候没有指定 fields  https://antv.alipay.com/zh-cn/g2/3.x/api/transform.html#_fold-%E5%AD%97%E6%AE%B5%E5%B1%95%E5%BC%80

按照提示改就行

**Comment by childdd** [comment]
@leungwensen 我发现是渲染了两次，第一次数据是空，是空数据的时候怎么办

**Comment by childdd** [comment]
第二个解决了。第一个两个版本我只安装了一次，不知道为什么有两个版本
