### ISSUE TITLE
[Firefox] Tooltip内key/value的layout出现溢出情况

### ISSUE THREAD

**Issue by tweiping** [antvis/g2#769]
* **G2 Version**: 3.2.2
* **Platform**: Firefox 61.0.1 
* **Mini Showcase(like screenshots)**:
<img width="736" alt="g2_layout_overflow" src="https://user-images.githubusercontent.com/33923624/43177205-a6133a20-8ff9-11e8-8799-e4eef9958e56.png">

* **CodePen Link**:
官网示例用Firefox打开运行即可复现这个问题，Chrome目前没有
https://antv.alipay.com/zh-cn/g2/3.x/demo/line/basic.html

**Comment by aa1011372655** [comment]
是由于float: right;导致的

**Comment by tweiping** [comment]
个人觉得实现tooltip的key/value 使用table更make sense些

containerTpl: '<div class="g2-tooltip">'
            + '<div class="g2-tooltip-title"></div>'
            + '<table class="g2-tooltip-list"></table></div>',
            itemTpl: '<tr class="g2-tooltip-list-item">'
            + '<td>'
            + '<span style="background-color:{color};width:8px;height:8px;border-radius:50%;display:inline-block;margin-right:8px;"></span>'
            + '</td>'
            + '<td style="padding-right:10px;">{name}:</td>'
            + '<td>{value}</td>'
            + '</tr>'

**Comment by leungwensen** [comment]
@aa1011372655 多谢 PR！已经合并，最新的 3.2.6 已发布
@tweiping 多谢反馈和建议！改为 table 形式的建议，我们会和交互视觉讨论过后决定
