### ISSUE TITLE
Map 中的示例可否提供数据格式

### ISSUE THREAD

**Issue by chenfengyanyu** [antvis/g2#77]
想实现“全国各个城市 pm 指数”效果，[链接](https://antv.alipay.com/g2/demo/10-map/map-projection.html)。
如上，其中的world.geo.json和china-pm.json完全catch不到，请问，我要实现相同的效果，没有数据源格式，我该怎么办？
求指教～

**Comment by simaQ** [comment]
你好，我们的地图数据是标准的 [GeoJSON](http://geojson.org/) 格式的数据，你可以从这里下载这些地理信息数据: https://github.com/antvis/resource/tree/master/geo

**Comment by chenfengyanyu** [comment]
@simaQ 十分感谢，我看到其他数据了，china-pm这个貌似没有，请问这个数据格式是怎样的。

**Comment by simaQ** [comment]
哦哦，我已经补充了： https://github.com/antvis/resource/blob/master/data/china-pm.json

**Comment by chenfengyanyu** [comment]
@simaQ 感谢🙏～
