### ISSUE TITLE
浏览器引入和通过 npm 安装同样的代码，浏览器渲染出来的图形不一致

### ISSUE THREAD

**Issue by xiaxia2017** [antvis/g2#771]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![1532512918 1](https://user-images.githubusercontent.com/25976259/43194503-1336bbd2-9035-11e8-8a75-4ca49d288992.jpg)
![1532513148 1](https://user-images.githubusercontent.com/25976259/43194637-6b4a0ef0-9035-11e8-9e65-ebd91e2c8244.jpg)
var G2 = require('g2');

// 绘制双Y轴图表
export function drawDoubleYChart(option) {
    var data = option.data || [
        {y1: 42563, time: "2018-07-20 07:06:06", y2: 2},
        {y1: 2235, time: "2018-07-21 07:06:06", y2: 3},
        {y1: 13212, time: "2018-07-22 07:06:06", y2: 5},
        {y1: 9415, time: "2018-07-23 07:06:06", y2: 1},
        {y1: 5545, time: "2018-07-24 07:06:06", y2: 3},
        {y1: 865, time: "2018-07-25 07:06:06", y2: 1},
        {y1: 1253, time: "2018-07-26 07:06:06", y2: 2}
    ];
    var defs = option.defs || {
        'time': {type: 'timeCat', mask: 'mm/dd'},
        'y1': {alias: '答疑处理时效', min: 0},
        'y2': {alias: '答疑超时数', min: 0}
    };
    var plotCfg = option.plotCfg || {
        margin: [30, 30, 80, 50], // 上，右，下，左
        background: {
          stroke: 'red', // 边颜色
          strokeOpacity: 0.4, // 边框的透明度设置，0 至 1 范围的数据
          lineWidth: 1, // 边框粗细
          fill: '#efefef', // 背景色
          fillOpacity: 0.4, // 背景色的透明度设置，0 至 1 范围的数据
          radius: 30 // 圆角设置
        } // 绘图区域背景设置
    };

    var chart = new G2.Chart({
        id: option.id,
        forceFit: true,
        height: option.height || 321,
        data: data,
        plotCfg: plotCfg
    });
    // 去除 X 轴标题
    chart.axis('time', {
        title: null
    });
    // 去除 Y 轴标题、坐标轴线、刻度线
    chart.axis('y1', {
        title: null,
        line: null,
        tickLine: null
    });
    chart.axis('y2', {
        title: null,
        line: null,
        tickLine: null
    });

    chart.source(data, defs);
    chart.legend({position:'bottom'});// 图例
    chart.interval().position('time*y1').color('#428FFF');
    chart.line().position('time*y2').color('#FF9D0B').size(3).shape('smooth');
    chart.point().position('time*y2').color('#FF9D0B').size(3).shape('circle');

    return chart;
}

**Comment by xiaxia2017** [comment]
官网没找到源码下载链接，直接复制链接粘贴的代码和npm的代码不一致

**Comment by aa1011372655** [comment]
能提供一下你浏览器引入的地址吗？

**Comment by leungwensen** [comment]
新版本的 npm 包名是 `@antv/g2`

**Comment by xiaxia2017** [comment]
更新G2到version: "3.2.7"问题解决了，推测是3.2.7 (2018-08-17)和3.2.6 (2018-07-28)不兼容
