### ISSUE TITLE
Could not find a declaration file for module '@antv/g2'

### ISSUE THREAD

**Issue by QETHAN** [antvis/g2#772]
* **G2 Version**: 3.2.5
* **Platform**:widows
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by jackytedy** [comment]
Perhaps you changed the value of the noImplicitAny attribute in your TypeScript compiler configuration.


`
{
"compilerOptions":{
"noImplicitAny":false
}
}
`

**Comment by QETHAN** [comment]
thx@jackytedy
