### ISSUE TITLE
[Feature request]Finger zoom associated chart with slider

### ISSUE THREAD

**Issue by LinFeng1997** [antvis/g2#777]
* **G2 Version**:3.2.4
* **Platform**:Mac OS

#### What problem does this feature solve?
Enhance the user experience with slider component.

#### What does the feature look like?
Such as echarts [dataZoom](http://echarts.baidu.com/examples/editor.html?c=area-simple);

#### What does the proposed API look like?
```
// chart
chart.dataZoom({
  yAxisIndex: 'none'
})
chart.on('zoom', ev => {
  // modify slider start and end
});
```
#### How should this be implemented in my opinion?
Maybe we can add a zoom event to the chart, and let the slider change when the scaling event is triggered.I willing to work on this myself,but I am not very familiar with your source structure, if you can give me some guidance, just fine.

**Comment by aa1011372655** [comment]
Hello, I think you want this： https://antv.alipay.com/zh-cn/g2/3.x/tutorial/how-to-use-slider.html，And hope to be inspired by you.

**Comment by LinFeng1997** [comment]
@aa1011372655 It has no zoom events

**Comment by LinFeng1997** [comment]
@aa1011372655 老哥你答非所问啊，我想要的是 chart 上支持 zoom 事件，当 chart 用手指缩放的时候触发，接着再在回调里面修改 slider 的 start 和 end 属性：
```
// chart
chart.dataZoom({
  yAxisIndex: 'none'
})
chart.on('zoom', ev => {
  // modify slider start and end
  this.slider = new Slider({
  // other options
  start: ev.start,
  end: ev.end
  })
});
```

**Comment by aa1011372655** [comment]
这个应该暂时不支持，官方例子都是通过滑动改数据，暂时没有根据位置改滑块的
