### ISSUE TITLE
使用downloadImage下载图片时，label不会显示

### ISSUE THREAD

**Issue by ritawr** [antvis/g2#780]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

显示：
![image](https://user-images.githubusercontent.com/4171044/43443525-b23456de-94d3-11e8-9762-9bcf7a5086b5.png)

下载保存图片：
![image](https://user-images.githubusercontent.com/4171044/43443552-cc3d0922-94d3-11e8-9f1f-302c85096082.png)

**Comment by weepy3641** [comment]
@leungwensen  
html2svg 了解一下。
https://www.npmjs.com/package/html2svg

感觉应该将 container 中的 html 和 canvas 都转为 svg。

**Comment by aa1011372655** [comment]
这部分源码里面是html实现的，@leungwensen，有计划用canvas实现一下吗？

**Comment by leungwensen** [comment]
嗯嗯，3.5 之前会把 components 抽出来，到时候每一种都会有默认的 G 版本的实现。 @aa1011372655

**Comment by dxq613** [comment]
html 的图片导出暂时不支持，建议有导出需求时，使用非 html 实现
