### ISSUE TITLE
Slider每次更新数据都会渲染出一个canvas

### ISSUE THREAD

**Issue by njueyupeng** [antvis/g2#782]
页面渲染了一个Slider，
每隔5秒调用 changeData().
每次更新数据，页面DOM会增加一个canvas（虽然页面没有显示）。

造成的问题：

第一次渲染的canvas宽度为700px;
页面缩小为500px后，五秒后渲染出一个500Px的Slider,但是仍然占据700px的宽度，因为第一个canvas没有销毁。

**Comment by leungwensen** [comment]
slider 已在改造，上线通知你
