### ISSUE TITLE
g2 svg 3.2.0 版在火狐浏览器里面不兼容

### ISSUE THREAD

**Issue by jayfmQQ** [antvis/g2#784]
* **G2 Version**: 3.2.0
* **Platform**: 火狐浏览器 61.0.1 

因为canvas导出的图片清晰度不够，然后切换到svg 版本，发现3.2的svg版本在火狐浏览器绘制的图不完整，报错信息和用火狐浏览器打开  https://antv.alipay.com/zh-cn/g2/3.x/tutorial/renderers.html# 一样

![image](https://user-images.githubusercontent.com/10105754/43515490-39817bf8-95b5-11e8-9df2-b12b240c224d.png)

**Comment by leungwensen** [comment]
已解决 `3.2.7-beta.5`
