### ISSUE TITLE
图表hover时的背景效果怎么配置，看demo有默认的效果，不知道是哪项配置来控制的？

### ISSUE THREAD

**Issue by xiaxia2017** [antvis/g2#789]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![1533255818 1](https://user-images.githubusercontent.com/25976259/43617772-189c0168-96f7-11e8-9bac-7ffd490abe69.jpg)

**Comment by xiaxia2017** [comment]
![1533255818 1](https://user-images.githubusercontent.com/25976259/43617779-252dda64-96f7-11e8-9392-ed220413cf7e.jpg)

**Comment by xiaxia2017** [comment]
默认我们为 geom 为 ‘line’, ‘area’, ‘path’, ‘areaStack’ 开启了垂直辅助线；geom 为‘interval’ 默认会展示矩形背景框;

**Comment by leungwensen** [comment]
```js
crosshairs: {
  type: 'rect' | 'x' | 'y' | 'cross',
  style: {
    // 图形样式
    fill: {string}, // 填充的颜色
    stroke: {string}, // 边框的颜色
    strokeOpacity: {number}, // 边框颜色的透明度，数值为 0 - 1 范围
    fillOpacity: {number}, // 填充的颜色透明度，数值为 0 - 1 范围
    lineWidth: {number}, // 边框的粗细
    lineDash: {number} | {array} // 线的虚线样式
  }
}
```
这个 rect 是这样的，折线图对应的值的占宽往往只有一像素，所以配置为 rect 显示可能也是像  line 一样。
