### ISSUE TITLE
和弦图更新失败问题

### ISSUE THREAD

**Issue by lhy1149** [antvis/g2#79]
现象：浏览器刷新正常显示，但是改变窗口大小触发图形重新绘制失败

const {nodes, links} = {
      'nodes': [
        {'id': 0, 'name': 'xx', 'value': 4},
        {'id': 1, 'name': 'x', 'value': 1},
        {'id': 2, 'name': 'x', 'value': 7},
        {'id': 3, 'name': 'x', 'value': 1},
        {'id': 4, 'name': 'x', 'value': 5},
        {'id': 5, 'name': 'x', 'value': 3},
        {'id': 6, 'name': 'x', 'value': 3},
        {'id': 7, 'name': 'x', 'value': 1},
        {'id': 8, 'name': 'x', 'value': 3},
        {'id': 9, 'name': 'x', 'value': 2},
        {'id': 10, 'name': 'x', 'value': 2}
      ],
      'links': [
        {'source': 0, 'target': 1, 'sourceWeight': 1, 'targetWeight': 1, 'relation': 'y'},

        {'source': 2, 'target': 0, 'sourceWeight': 1, 'targetWeight': 1, 'relation': 'y'},
        {'source': 2, 'target': 9, 'sourceWeight': 1, 'targetWeight': 1, 'relation': 'y'},
        {'source': 2, 'target': 10, 'sourceWeight': 1, 'targetWeight': 1, 'relation': 'y'},

        {'source': 4, 'target': 0, 'sourceWeight': 1, 'targetWeight': 1, 'relation': 'y'},
        {'source': 4, 'target': 2, 'sourceWeight': 1, 'targetWeight': 1, 'relation': 'y'},
        {'source': 4, 'target': 5, 'sourceWeight': 1, 'targetWeight': 1, 'relation': 'y'},
        {'source': 4, 'target': 6, 'sourceWeight': 1, 'targetWeight': 1, 'relation': 'y'},

        {'source': 5, 'target': 9, 'sourceWeight': 1, 'targetWeight': 1, 'relation': 'y'},
        {'source': 5, 'target': 10, 'sourceWeight': 1, 'targetWeight': 1, 'relation': 'y'},

        {'source': 6, 'target': 2, 'sourceWeight': 1, 'targetWeight': 1, 'relation': 'y'},
        {'source': 6, 'target': 3, 'sourceWeight': 1, 'targetWeight': 1, 'relation': 'y'},

        {'source': 7, 'target': 2, 'sourceWeight': 1, 'targetWeight': 1, 'relation': 'y'},

        {'source': 8, 'target': 0, 'sourceWeight': 1, 'targetWeight': 1, 'relation': 'y'},
        {'source': 8, 'target': 2, 'sourceWeight': 1, 'targetWeight': 1, 'relation': 'y'},
        {'source': 8, 'target': 4, 'sourceWeight': 1, 'targetWeight': 1, 'relation': 'y'}
      ]
    }
    
   。。。

 edgeView
      .edge()
      .position(Stat.link.weight('source*target*sourceWeight*targetWeight', layout.getNodes()))
                                     调用 weight 出错，奇怪的是第一次成功，图形正常显示
                             

错误信息：

TypeError: Cannot read property '0' of undefined
    at eval (eval at 169 (0.6cf4478….js:41), <anonymous>:1:9909)
    at Object.each (eval at 169 (0.6cf4478….js:41), <anonymous>:9:1299)
    at s._processShapePoints (eval at 169 (0.6cf4478….js:41), <anonymous>:1:9855)
    at s.draw (eval at 169 (0.6cf4478….js:41), <anonymous>:1:10246)
    at d._draw (eval at 169 (0.6cf4478….js:41), <anonymous>:11:23840)
    at i (eval at 169 (0.6cf4478….js:41), <anonymous>:11:24025)
    at d.paint (eval at 169 (0.6cf4478….js:41), <anonymous>:11:24442)
    at eval (eval at 169 (0.6cf4478….js:41), <anonymous>:13:11039)
    at Object.each (eval at 169 (0.6cf4478….js:41), <anonymous>:9:1299)
    at S._paint (eval at 169 (0.6cf4478….js:41), <anonymous>:13:11018)

**Comment by ch-daisy** [comment]
感谢你的反馈，问题已修复，下次发布会更新

**Comment by dxq613** [comment]
已经修复。
