### ISSUE TITLE
ie的兼容性做的不是很好，官网的样例都存在很多问题，比如pie。我使用的是IE11

### ISSUE THREAD

**Issue by perfect711** [antvis/g2#794]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by dxq613** [comment]
确定一下是 demo 的兼容性还是  g2 本身的兼容性问题。ie 11 理论上说跟chrome 的兼容性已经不错了。

**Comment by leungwensen** [comment]
可以提供一下截图吗？最新版应该已经解决兼容性问题了
