### ISSUE TITLE
Uncaught max not  equal to min

### ISSUE THREAD

**Issue by ShighGoing** [antvis/g2#8]
在[光滑的折现图](https://g2.alipay.com/demo/02-line/line-smooth.html)的demo中

将data修改如下
var data = [
        {name: '2012-2013 冬', time: Date.UTC(1970, 9, 21), value: 0},
        {name: '2013-2014 冬', time: Date.UTC(1970, 9, 21), value: 0.28}
];
出现 `Uncaught max not  equal to min`报错

**Comment by simaQ** [comment]
已经解决，今天会发新版本。

**Comment by travilyu** [comment]
并没有修复啊。只有一个点时还会报这个错
var data = [
{name: '2012-2013 冬', time: Date.UTC(1970, 9, 21), value: 0}
];

**Comment by merfais** [comment]
这个错误只会在<单点 && type= time >时出现，其他的type并没有，
chart.source(data, {
        time: {
          type: 'time',
          mask: 'mm-dd',
          alias: '日期'
        },

对于单个值的处理time类型的适配坐标轴范围时，对于max和min值是同一个值， 处理有错误

**Comment by dxq613** [comment]
最新发布的是1.2.8版本，线上demo上版本是1.2.6，因为这几天网站没法发布，所以替换不了demo上的链接
