### ISSUE TITLE
希望可以给地图类的图形提供一个点击方法以方便在用户点击时获取对应区域的数据

### ISSUE THREAD

**Issue by stupid2013** [antvis/g2#808]
* **G2 Version**: 最新版
* **Platform**: MacBook Pro
* **Mini Showcase(like screenshots)**: [截图](http://wx3.sinaimg.cn/mw690/0060lm7Tly1fu88z9f6kcj30ue0u6gpy.jpg)
* **CodePen Link**: none

如截图，鼠标悬浮时可以拿到该区域的对应的data，希望可以在点击该区域时也能有对应的点击方法可以获取当前区域的相关数据，目前在API里没有找到对应的方法～

**Comment by aa1011372655** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_%E4%BA%8B%E4%BB%B6
可以通过
```
  chart.on('polygon:click', (e) => {
  	console.log(e);
  })
```

**Comment by stupid2013** [comment]
@aa1011372655 got it! thanks~~~
