### ISSUE TITLE
tooltip 上 offset 属性无效

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#809]
如题，任意图标，tooltip 上 offset 属性无效
chart.tooltip({
  offset: 100 // 属性无效。
});

**Comment by aa1011372655** [comment]
@leungwensen ，这部分的业务逻辑已经缺失了，当前计算都是通过gap这个字段写死的
https://github.com/antvis/g2/blob/7407d6966ab40828fd2ab53e3d131b6369d64bb7/src/component/tooltip/index.js#L24
还需要支持吗？不知道使用场景及频率如何

**Comment by leungwensen** [comment]
@aa1011372655 应该要支持的，tooltip 在重构中，3.4 要把这个问题修掉。
