### ISSUE TITLE
南丁格尔玫瑰图在浏览器刷新时不能正确定位

### ISSUE THREAD

**Issue by lhy1149** [antvis/g2#81]
问题有二：

1、浏览器刷新时，南丁格尔玫瑰图会缩小显示，改变窗口大小后恢复正常大小
2、浏览器刷新后，南丁格尔玫瑰图中的 html guide 定位偏移，切换图例或改变窗口大小后恢复正常

`    const data = [
      {stakeholder: 'x1', '影响力': 2, '紧密程度': 3, '可预测性': 2},
      {stakeholder: 'x2', '影响力': 2, '紧密程度': 1, '可预测性': 1},
      {stakeholder: 'x3', '影响力': 2, '紧密程度': 3, '可预测性': 3},
      {stakeholder: 'x4', '影响力': 1, '紧密程度': 2, '可预测性': 1},
      {stakeholder: 'x5', '影响力': 3, '紧密程度': 3, '可预测性': 3},
      {stakeholder: 'x6', '影响力': 2, '紧密程度': 2, '可预测性': 3},
      {stakeholder: 'x7', '影响力': 2, '紧密程度': 2, '可预测性': 3},
      {stakeholder: 'x8', '影响力': 2, '紧密程度': 2, '可预测性': 2},
      {stakeholder: 'x9', '影响力': 3, '紧密程度': 2, '可预测性': 3},
      {stakeholder: 'xa', '影响力': 1, '紧密程度': 1, '可预测性': 1},
      {stakeholder: 'xb', '影响力': 1, '紧密程度': 1, '可预测性': 1}
    ]

    const frame = Frame.combinColumns(new Frame(data),
      ['影响力', '紧密程度', '可预测性'], 'point', 'aspect', 'stakeholder'
    )

    const chart = new Chart({id: 'c-stakeholder-influence', forceFit: true, height: 450})

    chart.source(frame)
    chart.coord('polar', {inner: 0.1})
    chart.legend('aspect', {position: 'bottom'})
    chart.axis('stakeholder', {labels: {label: {fontSize: '9'}}})
    chart.axis('point', {labels: null})

    chart.guide().html([0, 0], '<i>menu</i>', {align: 'bc', offset: [0, 10]})

    chart
      .intervalStack()
      .position('stakeholder*point')
      .color('aspect', ['rgb(136,186,174)', 'rgb(184,189,61)', 'rgb(107,136,138)'])
      .style({lineWidth: 1, stroke: '#fff'})

    chart
      .on('tooltipchange', function (ev) {
        const labels = ['低', '中', '高']
        ev.items.forEach(function (item) {
          item.value = labels[item.value - 1]
        })
      })

    chart.render()`

**Comment by dxq613** [comment]
经过测试没发现对应的问题。
