### ISSUE TITLE
用DataSet()的方式绘制的双折线图，然后想给第二条线绘制成虚线(在style中设置)，但是失效了

### ISSUE THREAD

**Issue by luguoeryi** [antvis/g2#810]
* **G2 Version**: v3.0.5

let newData = [{'name': '当前'}, {'name': '预期'}]
                let fields = []

                data.map((item, index) => {
                    let keyName = item[json.keyName].replace(/-/, '/')
                    newData[0][keyName] = item[json.keyVal]
                    fields.push(keyName)
                    if (index == data.length -1) {
                        // newData[1][keyName] = json.expect || 0
                        newData[1][keyName] = 100 || 0
                    }
                    if (index == data.length -2 && !json.chartType) {
                        newData[1][keyName] = item[json.keyVal]
                    }
                })
                
                // console.log({newData})
                // console.log({fields})
                if (this[chart_obj]) {
                    // this[chart_obj].changeData(newData)
                    $('#'+id+'>div').remove()
                    // return false
                }
                let chartType = json.chartType || 'line'
                let size = json.size || 3
                let shape = json.shape || ''
                let lineDash = json.lineDash || ''

                const ds = new DataSet()
                const dv = ds.createView().source(newData)

                dv.transform({
                    type: 'fold',
                    fields: fields, // 展开字段集
                    key: json.keyName, // key字段
                    value: json.keyVal // value字段
                })

                const chart = new G2.Chart({
                    container: id,
                    forceFit: true,
                    height: 271,
                    padding: [10, 23, 60, 58] // 上，右，下，左
                })

                chart.source(dv, {
                    [json.keyName]: {
                        tickCount: json.gridLength || 12
                    }
                })

                // let stateColor = json.expect >= json.nowData ? '#10cfbd' : '#ff4949'
                // let stateColor = '#DBDBDE'
                let stateColor = 'red'

                if (chartType == 'line') {
                    chart[chartType]().position(json.keyName + '*' + json.keyVal).color('name', ['#555858', stateColor]).shape(shape).style('预期', {lineDash: true}).size(size) // #BCBCBC 
                } else {
                    chart[chartType]().position(json.keyName + '*' + json.keyVal).color('name', ['#555858', stateColor]).shape(shape) // #BCBCBC
                }

                chart.tooltip(true, {
                    custom: true, // 自定义图例
                    useHtml: true, // 自定义模板
                    // title: null,
                    containerTpl: '<div class="g2-tooltip">'
                                + '<div class="g2-tooltip-title"></div>'
                                + '<ul class="g2-tooltip-list custom-table"></ul>'
                                + '</div>',
                    itemTpl: '<li data-index={index} style="padding-left:0;">'
                            + '<span style="background:{color}" class="g2-list-item"></span> <span>{name}</span> '
                            + `<span style="font-weight:500;">{value} ${json.unit ? json.unit : '次'}</span>`
                            + '</li>',
                    crosshairs: {type: 'line'}
                    // crossLine: {
                    //     stroke: '#fcb813'
                    // }
                })
                
                chart.render()

                this[chart_obj] = chart

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/api/graphic.html#
