### ISSUE TITLE
tooltip上 enterable 属性无效。

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#811]
如题，新版本，任意图表，tooltip 上 enterable 属性无效

**Comment by leungwensen** [comment]
其实是有效的，只是手速要快～～如果有停住的逻辑。。。先可以用之前给你说的 stopTooltip 那个 hack 方法。后面我们改一下 enterable 的逻辑

**Comment by dxq613** [comment]
已经修复，#816

**Comment by leungwensen** [comment]
3.2.7
