### ISSUE TITLE
3.2.x 版本 legend marker 自定义绘制函数，ctx 找不到

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#814]
如题：
在 demo：
https://antv.alipay.com/zh-cn/g2/3.x/demo/line/series.html
中加入代码
chart.legend('city', {marker: (x, y, r, ctx)=>{
   ctx.fillStyle = ctx.strokeStyle;
   ctx.fillRect(x - 8, y - 5, 16, 10);
}});

图表报错，g2 3.1.2 版本是好的。

**Comment by leungwensen** [comment]
因为要切换渲染引擎，自定义 marker 现在改为用 path segments 的方式来定义了：

```diff
-function _markerFn(x, y, r, ctx) {
-  ctx.moveTo(x - r, y);
-  ctx.lineTo(x + r, y);
+function _markerFn(x, y, r) {
+  return [
+    [ 'M', x - r, y ],
+    [ 'L', x + r, y ]
+  ];
```

下次发布官网会改一下文档
