### ISSUE TITLE
请问各位大神，【实时数据应用区域着色】的图中我怎样把从服务器中获取的数据加载上去。比如我获取的数据是图二这样的。谢谢回答！（angular6）

### ISSUE THREAD

**Issue by Sunshine-L** [antvis/g2#817]
![default](https://user-images.githubusercontent.com/41154870/44294849-55bac180-a2d0-11e8-93ee-25be5c1b3cad.PNG)
![default](https://user-images.githubusercontent.com/41154870/44294957-548a9400-a2d2-11e8-996c-831a86bbe879.PNG)

**Comment by leungwensen** [comment]
请自行参考 demo，关键接口是 `chart.guide().dataMarker` 和 `chart.changeData`
