### ISSUE TITLE
测试用例有误

### ISSUE THREAD

**Issue by Me-Momo** [antvis/g2#818]
* **G2 Version**:  3.2.7-beta.4
* **Platform**: MacOX
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/15646325/44303630-38d9c900-a378-11e8-8103-31bc985c7969.png)

执行命令`npm run test`时，测试用例全通过；而单独执行`torch --compile --renderer --recursive ./test/unit/geom/shape` 显示测例中有误

**Comment by elaine1234** [comment]
请先更新dependencies，如果还有这个问题请重开此issue。
