### ISSUE TITLE
支持坐标系偏移

### ISSUE THREAD

**Issue by Me-Momo** [antvis/g2#819]
* **G2 Version**:
* **Platform**: 
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

想请问以下，为什么不开放坐标系coord.translate功能呢

**Comment by Me-Momo** [comment]
比如我在chart中创建了一个view来自定义图表辅助元素guide。想使用translate来进行位置偏移，而目前只能通过图2的方式进行
![image](https://user-images.githubusercontent.com/15646325/44326139-4a60c500-a48d-11e8-9d8f-fb5277a352e0.png)

![image](https://user-images.githubusercontent.com/15646325/44326255-a62b4e00-a48d-11e8-987b-96a363520b45.png)

[在线demo](https://riddle.alibaba-inc.com/riddles/ffa2f7b5)

**Comment by dxq613** [comment]
你调整 辅助图片的偏移不行了。当初设计这块的时候，没想清楚 translate的用处，所以就没有支持。你这个场景无法说服我增加这个函数啊，虽然 coord 底层是天然支持的。
