### ISSUE TITLE
层叠柱状图加了slider之后异常的问题

### ISSUE THREAD

**Issue by DDDlk** [antvis/g2#82]
不知道是不是我用得不对。slider滑动时只显示两端的柱子，而不是范围内的都显示。谢谢。
`
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>层叠柱状图</title>
    <script src="https://a.alipayobjects.com/jquery/jquery/1.11.1/jquery.js"></script>
    <script src="https://a.alipayobjects.com/g/datavis/g2/2.2.2/g2.js"></script>
  	<script src="https://a.alipayobjects.com/g/datavis/g2-plugin-slider/1.0.0/slider.js"></script>
  </head>
  <body>
    <div id="c1"></div>
    <div id="slider"></div>
    <script>
    var data =[{"State":"WI","小于5岁":362277,"5至13岁":640286,"14至17岁":311849,"18至24岁":553914,"25至44岁":1487457,"45至64岁":1522038,"65岁及以上":750146},{"State":"MD","小于5岁":371787,"5至13岁":651923,"14至17岁":316873,"18至24岁":543470,"25至44岁":1556225,"45至64岁":1513754,"65岁及以上":679565},{"State":"MO","小于5岁":399450,"5至13岁":690476,"14至17岁":331543,"18至24岁":560463,"25至44岁":1569626,"45至64岁":1554812,"65岁及以上":805235},{"State":"TN","小于5岁":416334,"5至13岁":725948,"14至17岁":336312,"18至24岁":550612,"25至44岁":1719433,"45至64岁":1646623,"65岁及以上":819626},{"State":"IN","小于5岁":443089,"5至13岁":780199,"14至17岁":361393,"18至24岁":605863,"25至44岁":1724528,"45至64岁":1647881,"65岁及以上":813839},{"State":"MA","小于5岁":383568,"5至13岁":701752,"14至17岁":341713,"18至24岁":665879,"25至44岁":1782449,"45至64岁":1751508,"65岁及以上":871098},{"State":"AZ","小于5岁":515910,"5至13岁":828669,"14至17岁":362642,"18至24岁":601943,"25至44岁":1804762,"45至64岁":1523681,"65岁及以上":862573},{"State":"WA","小于5岁":433119,"5至13岁":750274,"14至17岁":357782,"18至24岁":610378,"25至44岁":1850983,"45至64岁":1762811,"65岁及以上":783877},{"State":"VA","小于5岁":522672,"5至13岁":887525,"14至17岁":413004,"18至24岁":768475,"25至44岁":2203286,"45至64岁":2033550,"65岁及以上":940577},{"State":"NJ","小于5岁":557421,"5至13岁":1011656,"14至17岁":478505,"18至24岁":769321,"25至44岁":2379649,"45至64岁":2335168,"65岁及以上":1150941},{"State":"NC","小于5岁":652823,"5至13岁":1097890,"14至17岁":492964,"18至24岁":883397,"25至44岁":2575603,"45至64岁":2380685,"65岁及以上":1139052},{"State":"GA","小于5岁":740521,"5至13岁":1250460,"14至17岁":557860,"18至24岁":919876,"25至44岁":2846985,"45至64岁":2389018,"65岁及以上":981024},{"State":"MI","小于5岁":625526,"5至13岁":1179503,"14至17岁":585169,"18至24岁":974480,"25至44岁":2628322,"45至64岁":2706100,"65岁及以上":1304322},{"State":"OH","小于5岁":743750,"5至13岁":1340492,"14至17岁":646135,"18至24岁":1081734,"25至44岁":3019147,"45至64岁":3083815,"65岁及以上":1570837},{"State":"PA","小于5岁":737462,"5至13岁":1345341,"14至17岁":679201,"18至24岁":1203944,"25至44岁":3157759,"45至64岁":3414001,"65岁及以上":1910571},{"State":"IL","小于5岁":894368,"5至13岁":1558919,"14至17岁":725973,"18至24岁":1311479,"25至44岁":3596343,"45至64岁":3239173,"65岁及以上":1575308},{"State":"FL","小于5岁":1140516,"5至13岁":1938695,"14至17岁":925060,"18至24岁":1607297,"25至44岁":4782119,"45至64岁":4746856,"65岁及以上":3187797},{"State":"ddddddddddd","小于5岁":1208495,"5至13岁":2141490,"14至17岁":1058031,"18至24岁":1999120,"25至44岁":5355235,"45至64岁":5120254,"65岁及以上":2607672},{"State":"TX","小于5岁":2027307,"5至13岁":3277946,"14至17岁":1420518,"18至24岁":2454721,"25至44岁":7017731,"45至64岁":5656528,"65岁及以上":2472223},{"State":"CA","小于5岁":2704659,"5至13岁":4499890,"14至17岁":2159981,"18至24岁":3853788,"25至44岁":10604510,"45至64岁":8819342,"65岁及以上":4114496}];
        var Stat = G2.Stat;
        var Frame = G2.Frame;
        var frame = new Frame(data);
        frame = Frame.combinColumns(frame,["小于5岁","5至13岁","14至17岁","18至24岁","25至44岁","45至64岁","65岁及以上"],'人口数量','年龄段','State');
        var chart = new G2.Chart({
          id: 'c1',
          forceFit: true,
          height: 450,
          plotCfg: {
            margin: [30, 40, 50,150],
            background: { 
              stroke: '#ccc', // 边颜色
              lineWidth: 1, // 边框粗细
            } // 绘图区域背景设置
          }
        });
        chart.source(frame);
        chart.legend({
          position: 'left'
        });
        chart.axis('State', {
          title: null
        });
        chart.axis('人口数量', {
          titleOffset: 75,
          formatter: function(val) {
            return val / 100 + 'M';
          },
          position: 'left'
        });
        chart.intervalStack().position('State*人口数量').color('年龄段', ['#98ABC5', '#8A89A6', '#7B6888', '#6B486B', '#A05D56', '#D0743C', '#FF8C00']).size(9);
        chart.render();
      
      var slider = new Slider({
  		domId: 'slider', // 用于显示该组件的 dom 容器 ID
  		width: 800, // 指定滑块的宽度，建议同 chart 的宽度一致
  		height: 20, // 指定滑块的高度
  		charts: chart, // 滑块控制的 chart 对象，如果有多个使用数组，只有一个传入对象即可复制代码
  		xDim: 'State', // 滑块控制的维度
  		yDim: '人口数量' // 滑块背景图表对应的 Y 轴维度, 没有传入则默认不绘制背景图
 
	});
	slider.render(); // 渲染
    </script>
  </body>
</html>
`

**Comment by DDDlk** [comment]
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>层叠柱状图</title>
    <script src="https://a.alipayobjects.com/jquery/jquery/1.11.1/jquery.js"></script>
    <script src="https://a.alipayobjects.com/g/datavis/g2/2.2.2/g2.js"></script>
  	<script src="https://a.alipayobjects.com/g/datavis/g2-plugin-slider/1.0.0/slider.js"></script>
  </head>
  <body>
    <div id="c1"></div>
    <div id="slider"></div>
    <script>
    var data =[{"State":"AZ","小于5岁":515910,"5至13岁":828669,"14至17岁":362642,"18至24岁":601943,"25至44岁":1804762,"45至64岁":1523681,"65岁及以上":862573},{"State":"WA","小于5岁":433119,"5至13岁":750274,"14至17岁":357782,"18至24岁":610378,"25至44岁":1850983,"45至64岁":1762811,"65岁及以上":783877},{"State":"VA","小于5岁":522672,"5至13岁":887525,"14至17岁":413004,"18至24岁":768475,"25至44岁":2203286,"45至64岁":2033550,"65岁及以上":940577},{"State":"NJ","小于5岁":557421,"5至13岁":1011656,"14至17岁":478505,"18至24岁":769321,"25至44岁":2379649,"45至64岁":2335168,"65岁及以上":1150941},{"State":"NC","小于5岁":652823,"5至13岁":1097890,"14至17岁":492964,"18至24岁":883397,"25至44岁":2575603,"45至64岁":2380685,"65岁及以上":1139052},{"State":"GA","小于5岁":740521,"5至13岁":1250460,"14至17岁":557860,"18至24岁":919876,"25至44岁":2846985,"45至64岁":2389018,"65岁及以上":981024},{"State":"MI","小于5岁":625526,"5至13岁":1179503,"14至17岁":585169,"18至24岁":974480,"25至44岁":2628322,"45至64岁":2706100,"65岁及以上":1304322},{"State":"OH","小于5岁":743750,"5至13岁":1340492,"14至17岁":646135,"18至24岁":1081734,"25至44岁":3019147,"45至64岁":3083815,"65岁及以上":1570837},{"State":"PA","小于5岁":737462,"5至13岁":1345341,"14至17岁":679201,"18至24岁":1203944,"25至44岁":3157759,"45至64岁":3414001,"65岁及以上":1910571},{"State":"IL","小于5岁":894368,"5至13岁":1558919,"14至17岁":725973,"18至24岁":1311479,"25至44岁":3596343,"45至64岁":3239173,"65岁及以上":1575308},{"State":"FL","小于5岁":1140516,"5至13岁":1938695,"14至17岁":925060,"18至24岁":1607297,"25至44岁":4782119,"45至64岁":4746856,"65岁及以上":3187797},{"State":"ddddddddddd","小于5岁":1208495,"5至13岁":2141490,"14至17岁":1058031,"18至24岁":1999120,"25至44岁":5355235,"45至64岁":5120254,"65岁及以上":2607672},{"State":"TX","小于5岁":2027307,"5至13岁":3277946,"14至17岁":1420518,"18至24岁":2454721,"25至44岁":7017731,"45至64岁":5656528,"65岁及以上":2472223},{"State":"CA","小于5岁":2704659,"5至13岁":4499890,"14至17岁":2159981,"18至24岁":3853788,"25至44岁":10604510,"45至64岁":8819342,"65岁及以上":4114496}];
        var Stat = G2.Stat;
        var Frame = G2.Frame;
        var frame = new Frame(data);
        frame = Frame.combinColumns(frame,["小于5岁","5至13岁","14至17岁","18至24岁","25至44岁","45至64岁","65岁及以上"],'人口数量','年龄段','State');
        var chart = new G2.Chart({
          id: 'c1',
          forceFit: true,
          height: 450,
          plotCfg: {
            margin: [30, 40, 50,150],
            background: { 
              stroke: '#ccc', // 边颜色
              lineWidth: 1, // 边框粗细
            } // 绘图区域背景设置
          }
        });
        chart.source(frame);
        chart.legend({
          position: 'left'
        });
        chart.axis('State', {
          title: null
        });
        chart.axis('人口数量', {
          titleOffset: 75,
          formatter: function(val) {
            return val / 100 + 'M';
          },
          position: 'left'
        });
        chart.intervalStack().position('State*人口数量').color('年龄段', ['#98ABC5', '#8A89A6', '#7B6888', '#6B486B', '#A05D56', '#D0743C', '#FF8C00']).size(9);
        chart.render();
      
      var slider = new Slider({
  		domId: 'slider', // 用于显示该组件的 dom 容器 ID
  		width: 800, // 指定滑块的宽度，建议同 chart 的宽度一致
  		height: 20, // 指定滑块的高度
  		charts: chart, // 滑块控制的 chart 对象，如果有多个使用数组，只有一个传入对象即可复制代码
  		xDim: 'State', // 滑块控制的维度
  		yDim: '人口数量' // 滑块背景图表对应的 Y 轴维度, 没有传入则默认不绘制背景图
 
	});
	slider.render(); // 渲染
    </script>
  </body>
</html>
```

**Comment by mystorp** [comment]
你的图表的横轴数据不是数字/时间类型，而是字符串，调节 slider 的时候，获取的范围虽然没错，但是G2内部并不知道如何比较字符串，所以获取的结果就是只有两个，也就是你说的两端。

不知道G2有没有提供比较横轴数据的配置，我也是新手，只能帮你到这了。

**Comment by dxq613** [comment]
是的 横轴加 slider 的时候必须是连续的数据，否则没法判断区域
