### ISSUE TITLE
minLimit 设置最小值时，最小值以下的区域依然绘制

### ISSUE THREAD

**Issue by laispace** [antvis/g2#820]
* **G2 Version**: 3.2
* **Platform**: Mac Chrome 68
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/laispace-the-reactor/pen/GXKLmw

minLimit 设置最小值时，最小值以下的区域依然绘制。

期望的是设置最小值后，最小值以下的区域被 clip 掉，或者提供配置提供选择是否 clip。

**Comment by simaQ** [comment]
可以在创建 chart 实例的时候，开启 `limitInPlot` 属性：

```js
var chart = new G2.Chart({
  container: 'mountNode', 
  limitInPlot: true,
});

```

**Comment by pyuyu** [comment]
> 

超出的点或者线被切掉一半现在可以解决么
