### ISSUE TITLE
抽样是否可以提供灵活的配置

### ISSUE THREAD

**Issue by laispace** [antvis/g2#821]
* **G2 Version**: 3.2
* **Platform**: Mac Chrome 68
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/laispace-the-reactor/pen/QVLPYN

如 codepen 所示，目前是 time 类型的抽样逻辑是默认抽成 6 个刻度显示，这种情况下两个刻度之间其实还存在很多的空白，期望空白间还能显示更多的刻度。

**Comment by dxq613** [comment]
x 轴设置成timeCat，同时 tickCount: null ，就所有都显示了。或者直接设置 type:'cat'

**Comment by laispace** [comment]
@dxq613 这个是期望能合理使用空白做抽样，如果能提供 callback 提供详细参数，给我们自由配置那就更好了

**Comment by dxq613** [comment]
设计师提过根据画布的宽度自动确定 tickCount ,不过按照他们的想法是不要进行旋转的个数。我个人感觉有个比较好的方式，是给 axis 加个配置项，判断是否遮挡，如果遮挡了前面的文本就不显示，如果你设置了 旋转 90 度，只要不遮挡，就会显示尽可能多的 tick

**Comment by laispace** [comment]
再进一步，是否遮挡的结果暴露出来，让使用方来决定是否需要抽样。
