### ISSUE TITLE
饼图 label 设置换行后文本碰撞到一起

### ISSUE THREAD

**Issue by laispace** [antvis/g2#823]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/laispace-the-reactor/pen/bxbybE

![image](https://user-images.githubusercontent.com/2217416/44327304-cf99a900-a490-11e8-8bbf-37ebefdb86f3.png)

**Comment by dxq613** [comment]
@leungwensen 看看为啥 labelHeight 不生效了？

**Comment by leungwensen** [comment]
我估计这块没有取 bbox，直接拿 label 预设的 lineheight 来计算了。这次重构做掉

**Comment by leungwensen** [comment]
这些 issue 是我和 轻声 讨论过 DI 需求后整理出来的，大部分在 component 重构期间解决掉。

**Comment by dxq613** [comment]
我及得以前这块让用户自己设置 labelHeight，这个比计算bbox 更管用，因为用户有可能是html 的label

**Comment by leungwensen** [comment]
@monkindey 你这里是 legend 和 label 两个组件之间的碰撞，这个没法统一做

**Comment by simaQ** [comment]
设置 `labelHeight` 属性即可。

```js
.label([measure], {
    labelHeight: 28,
    formatter: function formatter(val, item) {
      return `${item.point[dimension]}\n${val}`;
    },
  })
```
