### ISSUE TITLE
tooltip 支持自定义 callback 返回 html

### ISSUE THREAD

**Issue by laispace** [antvis/g2#825]
* **G2 Version**: 3.2
* **Platform**: Mac Chrome 68
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://antv.alipay.com/zh-cn/gallery/g2/cutomize-tooltip.html#

期望 tooltip 支持自定义 callback 返回 html，以支持自由的内容填充。

**Comment by dxq613** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/tutorial/tooltip.html#_%E6%A0%BC%E5%BC%8F%E5%8C%96-tooltip-%E7%9A%84%E6%98%BE%E7%A4%BA%E5%86%85%E5%AE%B9

可以在回调函数中自己组织 title,name,value，然后修改模板，或者直接将 name，value设置成 html 字符串也行。

**Comment by leungwensen** [comment]
这个需求是之前讨论过的，回调函数做个判断，如果是对象，就走 template，如果是字符串，就整段塞进去。后者是对不熟悉咱们 tooltip 模板的用户比较友好的

**Comment by laispace** [comment]
```
chart.line().position('x*y').tooltip('x*y', (x, y) => {
  return {
    x, 
    y
  }; // 返回的参数名对应 itemTpl 中的变量名
);
```

这种写法，得到的 y 值是原始值，而实际上需要显示的是自定义格式化的值，也就是会破坏 defs 中设置的对 value 进行的格式化：
https://github.com/antvis/g2/pull/773

**Comment by leungwensen** [comment]
要不看看排期看这期来不来得及加这个？ @dxq613

**Comment by elaine1234** [comment]
已在3.4版本中支持
