### ISSUE TITLE
鼠标悬浮在绘图区域就会显示 tooltip 

### ISSUE THREAD

**Issue by laispace** [antvis/g2#826]
* **G2 Version**: 3.2
* **Platform**: Mac Chrome 68
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://antv.alipay.com/zh-cn/g2/3.x/demo/funnel/basic.html

鼠标悬浮在绘图区域就会显示 tooptip，期望能配置是否限制在图形区域才显示 tooltip

**Comment by dxq613** [comment]
可以设置 shared: false

```JS
chart.tooltip({shared: false}) 
```
就只有移动到图形上才显示图例了
