### ISSUE TITLE
Uncaught TypeError: Cannot read property 'draw' of undefined

### ISSUE THREAD

**Issue by LinFeng1997** [antvis/g2#828]
* **G2 Version**: 3.2.7
* **Platform**: Mac Chrome
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/16188742/44383317-f1576680-a54a-11e8-8c46-eab6a74681c6.png)

* **Link**: https://antv.alipay.com/zh-cn/g2/3.x/demo/candlestick/basic.html

When use slider from cdn script import,the error occur.

**Comment by leungwensen** [comment]
known issue, use `@antv/g2@3.2.7` and `@antv/g2-plugin-slider@2.0.4` to fix this.
