### ISSUE TITLE
更新日志日期错误

### ISSUE THREAD

**Issue by tyyzqmf** [antvis/g2#83]
https://antv.alipay.com/g2/doc/history.html
v2.2.2

2016-01-19
应该是2017-01-19

**Comment by tyyzqmf** [comment]
还有g6的日志日期是不是也错了？难道已经1年没更新了？
https://antv.alipay.com/g6/doc/history.html

**Comment by tyyzqmf** [comment]
哦！还有g2-mobile的更新日志，同样的，很容易误导啊
https://antv.alipay.com/g2-mobile/doc/history.html

**Comment by simaQ** [comment]
非常感谢，太细心了。
我表示真的好！尴！尬！

**Comment by dxq613** [comment]
已经更新。
