### ISSUE TITLE
scale.formatter 格式化结果也影响 label 的结果

### ISSUE THREAD

**Issue by laispace** [antvis/g2#830]
* **G2 Version**: 3.2
* **Platform**: Mac Chrome 68
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

> Scale.formatter 用于格式化坐标轴刻度点的文本显示，会影响数据在坐标轴 axis、图例 legend、tooltip 上的显示。

目前的版本，对数据标签 label 的格式化还得设置一遍，是否可以统一？

**Comment by dxq613** [comment]
这个地方之所以没有用 scale 的formatter 很重要的一个因素在于 .label 方法是可以接受多个字段的

```js
chart.point()
         .label('a*b', 
             function(a, b) {
               return (a + b) + 'cm';
         });
```

**Comment by laispace** [comment]
@dxq613 但这种方式有个问题，若用了 fold 的 transform：
```
dataView.transform({
      type: 'fold',
      fields: measures,
      key: 'a',
      value: 'b',
    });
```
那这里拿到的 b 若想个性化地格式化的话就没法做了。
