### ISSUE TITLE
去掉axis或legend后图表剩余部分不能自动铺满容器

### ISSUE THREAD

**Issue by NereusLee** [antvis/g2#833]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

去掉g2的axis和legend:
chart.axis("value", {
     label: null
});
chart.legend('date',false);
原先的位置变成了一片空白而不是去掉这一部分,导致图表部分看起来是往右移了一样,很不美观
去掉axis之前:
![g9mgui0q caf64x oypat s](https://user-images.githubusercontent.com/23068807/44511414-11715c00-a6ea-11e8-9534-db91fb43de18.png)

去掉axis之后:
![o _m rgdqu6n slyy2hbp](https://user-images.githubusercontent.com/23068807/44511464-3960bf80-a6ea-11e8-82f9-ecd53eed1120.png)

**Comment by leungwensen** [comment]
因为有默认的 padding。可以手动设置 padding https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_padding
