### ISSUE TITLE
3.2.7版图例position设置不支持top

### ISSUE THREAD

**Issue by photino** [antvis/g2#836]
文档里说：
`也可使用'left'(默认为left-bottom'),'right'(默认为'right-bottom'),'top'(默认为top-center'),'bottom'(默认为bottom-center')定位。`

但是，设置`postion: 'top'`图例出不来，只有设置`position: 'top-center'`才行。

**Comment by leungwensen** [comment]
![image](https://user-images.githubusercontent.com/1655789/44636373-05cdb000-a9de-11e8-9157-6fe0ae2a7e00.png)

可以的
