### ISSUE TITLE
如何使用不同时间点做对比折线图？

### ISSUE THREAD

**Issue by xiaxia2017** [antvis/g2#837]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![4232323211f8f8f81d797ae56912612](https://user-images.githubusercontent.com/25976259/44625816-509ae980-a944-11e8-8475-9245b03d9550.png)
目前我根据曲线折线图做出了折线效果，但是tootip提示title会展示绘图时的坐标日期，对比折线应该显示自己的实际时间，这个貌似不好更改，求解？
https://antv.alipay.com/zh-cn/g2/3.x/demo/line/curved.html

![1535269275 1](https://user-images.githubusercontent.com/25976259/44625951-8345e180-a946-11e8-8f7c-00c4ce05f992.jpg)

**Comment by xiaxia2017** [comment]
![1535269275 1](https://user-images.githubusercontent.com/25976259/44625990-21d24280-a947-11e8-9120-b22299512333.jpg)

**Comment by leungwensen** [comment]
这种情况应该用双 x 轴，不应该共用一个 x 轴，否则会带来误导。参考这个例子用两个 view 来解决：

https://antv.alipay.com/zh-cn/g2/3.x/demo/other/area-rainfall.html

**Comment by xiaxia2017** [comment]
我尝试使用了基础折线图绘制两条折线，但是X轴坐标无法匹配一致，y轴也有两个；目前使用的这个图例就是tootip无法实时更新，title自定义会有各种问题；可能我本身业务逻辑过多，给自定义设置增加了难度；
有没有类似chart.changeData()的方法，我在vue中watch一个变量来手动更新tootip的数据，tootip目前来看跟数据貌似不是绑定的热更新
