### ISSUE TITLE
饼图label设置offset后,改变窗口宽度,label显示出错,刷新后恢复正常

### ISSUE THREAD

**Issue by Me-Momo** [antvis/g2#838]
* **G2 Version**:  3.2.7
* **Platform**:
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/15646325/44627744-b055bc80-a965-11e8-9c3a-7715957ad941.png)

* **CodePen Link**: https://codepen.io/kasmine/pen/MqKZaV?editors=0010

**Comment by leungwensen** [comment]
好像是动画问题，帮忙看看 @elaine1234

**Comment by elaine1234** [comment]
G2中label的布局跟offset取值有关，如果offset是负值，布局在对应shape内部，0的时候是默认布局，正值布局在shape外。这个图建议取正数offset，效果如下图：
<img width="327" alt="2018-08-27 9 53 33" src="https://user-images.githubusercontent.com/8325822/44636604-63163100-a9df-11e8-80d2-d9f4450cb9d3.png">

**Comment by leungwensen** [comment]
offset 是负值的时候，resize 的时候 label 位置不对，这应该是个 bug

**Comment by Me-Momo** [comment]
@elaine1234 目前不支持label在内部 我只能取offset为负值哇...
