### ISSUE TITLE
关于图例 title 的 alias 问题

### ISSUE THREAD

**Issue by csbun** [antvis/g2#84]
目前图例(legend) 中的 title 是按照字段的 key 设置的，在 `chart.legend()` 中似乎没有找到对应的方法修改，而

```javascript
chart.col('type', {
  alias: '分类',
});
```

的方式也不会产生影响。

**Comment by dxq613** [comment]
chart.col()需要在chart.line之类的图形语法之前定义。最好直接在chart.souce(data, {})里面直接指定。如果chart.col在chart.line的语法后面定义那么只有在下次changeData时才生效。

**Comment by csbun** [comment]
按 @dxq613 的说法，`chart.col('type', { alias: '分类' }).line()` 的写法有效！

PS. 因为使用了 g2-react，`chart.source(data)` 已经封装在内，无法直接调用。

**Comment by never615** [comment]
您好,请教一下,图例的标题怎么自定义...我也是在文档上找不到..
我见你评论的col方法我也没见过,貌似是以前的版本?
我这样设置,图例还是key名:
```
            chart.scale({
                ref_date: {
                    alias: '日期',
                    tickCount: 11,
                },
                cumulate_user: {
                    alias: '微信累计用户'
                }
            });

            chart.line().position('ref_date*cumulate_user').color('#95ceff');
            chart.line().position('ref_date*有效用户').color('#90ed7d');

```

![jietu20180822-181039](https://user-images.githubusercontent.com/9959927/44457760-bb8fac00-a636-11e8-9522-065dedaae2f5.jpg)

**Comment by acecode** [comment]
g2@3.4.5 版本 查到底层实现

@antv/component/src/legend/category.js
* _renderItems() 
* -> _addItem(item, index) 
*-> 构造item 文字

[源码](https://github.com/antvis/component/blob/35674014f2deeae524578d4fa6e7c367e6fffdb2/src/legend/category.js#L463)

那就加个`itemFormatter` 配置函数吧

```js
chart.legend({
        itemFormatter(field) {
            const scale = chart.get('options').scales[field]
            return scale && scale.alias || field
        }
    })
```
