### ISSUE TITLE
加入 regionFilter guide 后，legend position=top 时，legend 不显示

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#842]
如题！

在如下 demo: https://antv.alipay.com/zh-cn/g2/3.x/demo/bar/stacked-column.html 中，
插入 code：
```
chart.legend('name', {position:'top'})
chart.guide().regionFilter({
    top: true,
    start: ['min', 0],
    end: ['max', 'max'],
    color: '#ff0000'
  });
```

legend 不显示，并不是 padding 引起的，是由于 regionFilter 引起的。

同时这个图表中加入  regionFilter 位置为 mix max 但不能填满绘图去，是否不符合 min、max 语意？

**Comment by leungwensen** [comment]
min max 的问题，这里的 min max 指的是数据的 min max，新增了 start 和 end 指的是画布的 start 和 end，可以试一下

**Comment by simaQ** [comment]
排查下来是因为，https://github.com/antvis/g2/blob/master/src/chart/controller/legend.js#L66 计算 legend 位置时，计算 backPlot 的 bbox 的时候，因为声明了 chart.guide()，会往 backPlot 和 frontPlot 两个层级上分别创建一个存放 guide 的 group，在这个 issue 中，因为 guide 的 top: true 添加到了 frontPlot  的容器中，但是 backPlot 中创建的 group 依然存在，而且是一个空的 group，恰恰是这个空的 group 影响了 backPlot 的 bbox 计算，导致 legend 的定位出现了问题。

目前认为解决方案应是 G 在计算 group 的 bbox 时，应该忽略空 group 的 bbox 计算。关联 https://github.com/antvis/g/issues/72

**Comment by blankul** [comment]
遇到类似的问题, legend position 为 top 时,  
加入chart.guide().text({
  position: ['0%', '0%'],
  content: '单位: 万'
}), 
legend同样不显示，
guide 的 top的 无论是true, false 都不显示

**Comment by weepy3641** [comment]
新版本已经解决。
