### ISSUE TITLE
如何在websocket下使用g2的股票图呢？

### ISSUE THREAD

**Issue by chinalijinglun** [antvis/g2#844]
如何在websocket下使用g2的股票图呢？

**Comment by leungwensen** [comment]
G2 不会感知上层获取数据用的是什么技术，拿到数据之后，只需要调用 chart.changeData(data) 就可以触发图表更新了。 https://antv.alipay.com/zh-cn/g2/3.x/tutorial/update-data.html#_%E5%8A%A8%E6%80%81%E6%9B%B4%E6%96%B0%E6%95%B0%E6%8D%AE-chart.changeData-data-
