### ISSUE TITLE
数据存在 null 时，tooltip format 后，tooltip 数据 null 的内容重复

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#846]
如题。 是新版本的问题。
demo地址：
https://riddle.alibaba-inc.com/riddles/2f760744

错误截图：
![image](https://user-images.githubusercontent.com/3838676/44766840-dfe70d80-ab8d-11e8-89e8-af6a9b6071d9.png)

**Comment by weepy3641** [comment]
最新版本已经修复。

**Comment by Cmaxd** [comment]
你好，我也遇到了这个问题，请问是在哪个版本修复了，我试了几个版本还是有问题
