### ISSUE TITLE
G2多Geom情况对Legend支持

### ISSUE THREAD

**Issue by orangeyyy** [antvis/g2#849]
* **G2 Version**:
3.2.x
* **Platform**:
mac
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

对于多geom情况下的legend使用，希望能够支持以下两个功能：
1，多geom情况下legend中显示的字段支持别名配置：
https://riddle.alibaba-inc.com/riddles/13228019
![image](https://user-images.githubusercontent.com/19667299/44832973-20628c00-ac5f-11e8-9b8c-1031c4dd3907.png)

2，多geom情况下如果使用fold的情况，如果同一geom的legend点击置灰以后，所有其他geom都无法显示了，希望只隐藏当前geom：
https://riddle.alibaba-inc.com/riddles/fd319dff
![image](https://user-images.githubusercontent.com/19667299/44833163-d4641700-ac5f-11e8-9f5f-7d46d43afe9f.png)
![image](https://user-images.githubusercontent.com/19667299/44833183-dfb74280-ac5f-11e8-885e-e3a09221686f.png)

**Comment by paleface001** [comment]
将在g2-plot的混合图表中进行支持
