### ISSUE TITLE
slider的背景图案问题

### ISSUE THREAD

**Issue by DDDlk** [antvis/g2#85]
![image](https://cloud.githubusercontent.com/assets/22271047/22726372/1cee4980-ee0e-11e6-818a-c69975f1e5e3.png)
1、如何使slider的背景图案和原图一样是柱状图案， 而不是如上图所示被圆滑了的背景。？
2、当原图数据源更新之后，slider应该怎样同步更新？ 
（我现在用的方法不好，把div remove掉重新加的。）
 谢谢。

**Comment by DDDlk** [comment]
补充一下第二个问题。
![image](https://cloud.githubusercontent.com/assets/22271047/22727682/27aadbf2-ee15-11e6-9d94-c868cb6d82d9.png)
当上图的分类选择状态改变之后，slider怎样也跟着改变？

**Comment by dxq613** [comment]
* 建议使用新的 range 插件：https://antv.alipay.com/g2/demo/03-area/area.html

* 背景主要用于显示趋势，不建议同步柱状图之类，会复杂化
* 分类的筛选是对数据的筛选，不会影响 slider 对象
