### ISSUE TITLE
柱狀圖圖例無法顯示

### ISSUE THREAD

**Issue by Roytangrb** [antvis/g2#851]
* **G2 Version**:3.2.7
* **Platform**: chrome
<img width="303" alt="screen shot 2018-08-30 at 2 41 57 pm" src="https://user-images.githubusercontent.com/25113108/44834288-4558fe00-ac63-11e8-9fe4-5f4eb47879bd.png">
<img width="175" alt="screen shot 2018-08-30 at 2 42 02 pm" src="https://user-images.githubusercontent.com/25113108/44834290-45f19480-ac63-11e8-8de8-7f359f4ad919.png">

* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

```js
const chart = new G2.Chart({
        container: container,
        width: 290,
        height: 250,
        padding:{top:20, left:10, right:20, bottom:30},
        plotCfg:{
            margin:[20, 0, 0, 0]
        }
      });
chart.legend('group',{
        marker: 'circle',
        position: 'top', 
      });
```
* Legend 是否需要Margin空間渲染？通過plotCfg無法設置margin

**Comment by aa1011372655** [comment]
hello，固定设置padding的情况下，不存在边框，Legend无法展示，建议将padding设置为'auto'，类似于：
```
const chart = new G2.Chart({
        container: container,
        width: 290,
        height: 250,
        padding: 'auto',
        plotCfg:{
            margin:[20, 0, 0, 0]
        }
      });
chart.legend('group',{
        marker: 'circle',
        position: 'top', 
      });
```

**Comment by Roytangrb** [comment]
thx, 設置```padding: 'auto'``` 之後依然無法調整legend位置：
```js
chart.legend('group',{
        marker: 'circle',
        //position: 'top', 
}
```
<img width="310" alt="screen shot 2018-08-30 at 3 10 16 pm" src="https://user-images.githubusercontent.com/25113108/44835562-2c524c00-ac67-11e8-92a4-5944fd51cf99.png">

```js
chart.legend('group',{
        marker: 'circle',
        position: 'top', 
}
```
設置position之後出現下圖狀況：
<img width="306" alt="screen shot 2018-08-30 at 3 10 38 pm" src="https://user-images.githubusercontent.com/25113108/44835587-40964900-ac67-11e8-9516-edbe5dfc1603.png">

**Comment by dxq613** [comment]
1. 确认一下是否是 group 是生成 legend 的字段
2. 可以尝试把 position:'top' 改成 'top-center' 试试

![image](https://user-images.githubusercontent.com/1264678/44837046-19417b00-ac6b-11e8-999d-6273353dfb4c.png)

chart.legend('genre', {
  position: 'top-center'
})

// Step 3：创建图形语法，绘制柱状图，由 genre 和 sold 两个属性决定图形位置，genre 映射至 x 轴，sold 映射至 y 轴
chart.interval().position('genre*sold').color('genre');

**Comment by dxq613** [comment]
如果整个图的图例只有一个，可以不设置字段名直接：

```js
chart.legend({
position: 'top'
})
```

**Comment by Roytangrb** [comment]
已經參考https://antv.alipay.com/zh-cn/g2/3.x/demo/bar/grouped.html
映射的維度是group沒錯，是否提供```chart.legend('group')```沒有影響, 只有不提供position的時候才能正常顯示legend

完整代碼：
```js
import '@antv/g2';

const render = (divID, data, dir =1)=>{
    const container = document.querySelector(divID)
    const chart = new G2.Chart({
        container: container,
        width: 290,
        height: 250,
        padding:'auto',//{top:20, left:10, right:20, bottom:30},
      });
      chart.source(data);
      
      chart.coord().transpose().scale(1, -1);
      chart.interval().position('x*y').color('group', ['#FFB618', '#4CBED7']).adjust([{
        type: 'dodge',
        marginRatio: 1 / 32
      }]);

      chart.legend({
        marker: 'circle',
        //position: 'top-center', 
        textStyle:{
            fill:'#808080'
        }
      });
    
      chart.axis('y', {
        position: 'right',
        label:{
            textStyle:{
                fill: '#808080'
            },
            formatter:(val)=>val+'%'
        },
        grid: {
            type: 'line',
            lineStyle: {
              stroke: '#808080',
              lineWidth: 1,
              lineDash:[0, 0]
            }
        }
      });
      chart.axis('x', {
        position: 'bottom',
        line: null,
        tickLine: null,
        label: {
            offset:-3,
            labelLine: false,
            htmlTemplate: (text, item, index) => {
                let color = {inside: '#808080', outside: 'grey'}
                return '<span class="bar-label" color:' + color.inside + ';">' + text + '  </span>'
            }
        },
      });
      chart.render();
}

export default render
```

**Comment by paleface001** [comment]
特定field没有做向上兼容，已修复。
