### ISSUE TITLE
想使用g2 地图做一个人口迁徙图这样效果的图表？ 如何做？

### ISSUE THREAD

**Issue by forbreak** [antvis/g2#854]
* **G2 Version**: 3.2.7
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

有没有人口迁徙这样效果的图表样例参考？  还有那种根据时间轴自动变化的折线图/柱状图的，g2图表需要如何实现？

**Comment by leungwensen** [comment]
G2 暂时没有提供中国地图的资质，所以中国地图已经下线掉了。明年1月份会接入高德，届时敬请体验。时间轴组件还在排期，暂时没有定上线时间。

**Comment by forbreak** [comment]
@leungwensen  地图资源我可以找到，主要是线的那种动画效果，我现在自己做了一个点在线上移动，想要那种水滴装的点不知道如何实现。
现在我做到这样的
![image](https://user-images.githubusercontent.com/6947976/44903482-43fd0380-ad3f-11e8-824d-b53e6ccd94ae.png)
不知道怎么传gif图。
想要这样的点的移动效果
![image](https://user-images.githubusercontent.com/6947976/44903570-73ac0b80-ad3f-11e8-9945-b6d8e5eccc04.png)

**Comment by leungwensen** [comment]
飞线效果对吧？这个底层引擎暂时还不支持，我们会加到开发计划里 @elaine1234

**Comment by jany3534** [comment]
> G2 暂时没有提供中国地图的资质，所以中国地图已经下线掉了。明年1月份会接入高德，届时敬请体验。时间轴组件还在排期，暂时没有定上线时间。

地图上线了没

**Comment by yangAlan** [comment]
底层引擎G支持矩阵设置，可以计算出水滴在每个点的旋转矩阵和位移矩阵，最后做复合变换。应该是可以实现的（我在g6就是这样做的）。

**Comment by paleface001** [comment]
会在g2-plot的地图相关图表进行支持

**Comment by strawberrydot** [comment]
> @leungwensen 地图资源我可以找到，主要是线的那种动画效果，我现在自己做了一个点在线上移动，想要那种水滴装的点不知道如何实现。
> 现在我做到这样的
> ![image](https://user-images.githubusercontent.com/6947976/44903482-43fd0380-ad3f-11e8-824d-b53e6ccd94ae.png)
> 不知道怎么传gif图。
> 想要这样的点的移动效果
> ![image](https://user-images.githubusercontent.com/6947976/44903570-73ac0b80-ad3f-11e8-9945-b6d8e5eccc04.png)

hi，刚开始用g2，想请问在地图上绘制折线你这个是怎么做到的呢，使用经纬度的情况下

**Comment by simaQ** [comment]
地理可视化，我们建议使用 L7：https://github.com/antvis/L7
