### ISSUE TITLE
legend筛选后饼图的百分比保持不变的问题

### ISSUE THREAD

**Issue by shiyuwudi** [antvis/g2#855]
* **G2 Version**:3.1.2
* **Platform**:MacOS
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

请问下官方饼图实例的情况下，有没有属性可以控制点击其中一个legend，做了筛选操作之后重新计算剩下部分的百分比；否则剩下的部分加到一起后百分比不是100%。

**Comment by shiyuwudi** [comment]
我现在是通过chart.filter配合手动转换数据数量为0来实现的，感觉太勉强了。

**Comment by dxq613** [comment]
这个原因其实是因为数据都是计算好百分比的，切换 legend 后，没有重新计算。这个问题下个版本解决，我们会将统计函数再次集成到语法中，每次都动态计算百分比，类似于 2.3 的场景。

```js
// 2.3
chart.intervalStack(Stat.summary.percent('value')).color('name')
```

还有一种解决方案：抛出 filter 事件，在事件中可以处理数据，不过依然不太方便

**Comment by LPDLKBN** [comment]
请问解决这个问题的版本出了吗
