### ISSUE TITLE
3.2.7版本在基础折线图demo中使用chart.scale自定义别名alias时，只有y轴生效，不知道是不是新版本不支持x轴的自定义别名?

### ISSUE THREAD

**Issue by xiaxia2017** [antvis/g2#859]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

3.2.7版本在基础折线图demo中使用自定义别名alias时，只有y轴生效，不知道是不是新版本不支持x轴的自定义别名?代码如下：
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,height=device-height">
    <title>基础折线图</title>
    <style>::-webkit-scrollbar{display:none;}html,body{overflow:hidden;height:100%;margin:0;}</style>
</head>
<body>
<div id="mountNode"></div>
<script>/*Fixing iframe window.innerHeight 0 issue in Safari*/document.body.clientHeight;</script>
<script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.g2-3.2.7/dist/g2.min.js"></script>
<script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.8.9/dist/data-set.min.js"></script>
<script>
var data = [{
  year: '1991',
  value: 3
}, {
  year: '1992',
  value: 4
}, {
  year: '1993',
  value: 3.5
}, {
  year: '1994',
  value: 5
}, {
  year: '1995',
  value: 4.9
}, {
  year: '1996',
  value: 6
}, {
  year: '1997',
  value: 7
}, {
  year: '1998',
  value: 9
}, {
  year: '1999',
  value: 13
}];
var chart = new G2.Chart({
  container: 'mountNode',
  forceFit: true,
  height: window.innerHeight
});
chart.source(data);

  // 指定度量(或称 列定义）
  // x轴
  chart.scale('year', {
    alias: '年份' // 为属性定义别名
  });
  // y轴
  chart.scale('value', {
    formatter: function (val) {
      return `${val}℃`;
    },
    min: 0,
    alias: '温度' // 为属性定义别名
  });
chart.tooltip({
  crosshairs: {
    type: 'cross'
  }
});
chart.line().position('year*value');
chart.point().position('year*value').size(4).shape('circle').style({
  stroke: '#fff',
  lineWidth: 1
});
chart.render();
</script>
</body>
</html>

**Comment by xiaxia2017** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/tutorial/tooltip.html

**Comment by xiaxia2017** [comment]
// x轴
    chart.scale(option.x, {
        type: 'cat',
        alias: '日期' // 为属性定义别名
    });
问题解决了，x轴需要定义type类型才会生效

**Comment by leungwensen** [comment]
![image](https://user-images.githubusercontent.com/1655789/44904226-38aad780-ad41-11e8-8198-c607606191c9.png)

**Comment by leungwensen** [comment]
x 轴的值默认是 title，title 值前边不会带上属性名的
