### ISSUE TITLE
时不时出现空白的图表，移上去只显示当前点的数据

### ISSUE THREAD

**Issue by chenghaohao** [antvis/g2#86]
![image](https://cloud.githubusercontent.com/assets/9986914/22870490/aefb2e24-f1e2-11e6-9271-8bfabfcb2a8e.png)

时不时的出现这种界面，偶尔可以正常，偶尔异常。异常如上图：
我用的版本是2.2.1，最新的版本好像是2.2.2
不知道这个是不是2.1的bug?2.2修复没有？

**Comment by simaQ** [comment]
你好，可以贴下代码么？我定位下

**Comment by chenghaohao** [comment]
我在vue里面用的，应该是正常的按照文档来条用的吧。。
watch: {
      charData: function (val, oldVal) {
        console.log('new: %s, old: %s', val, oldVal);
        this.drawChart(val);
      }
    },
    methods: {
      drawChart: function (datas) {
        this.chart && this.chart.destroy();
        let data = utils.translateCharDate(datas);
        this.chart = new G2.Chart({
          id: this.id,
          width: 1000,
          height: 250
        });
        this.chart.source(data, {
          strftime: {
            alias: '日期',
            type: 'cat',
            range: [0, 1]
          },
          value: {
            alias: '数量值(人)'
          }
        });
        this.chart.line().position('strftime*value').size(2);
        this.chart.point().position('strftime*value').color('#757373')
          .shape('circle')
          .label('value', {offset: 20, label: {fill: '#000'}});
        this.chart.render();
      }
    }

**Comment by simaQ** [comment]
```js
this.chart.line().position('strftime*value').size(2);
this.chart.point().position('strftime*value').color('#757373')
.shape('circle')
.label('value', {offset: 20, label: {fill: '#000'}});
```
有数据么，给几条数据，你这个语法没什么问题

**Comment by chenghaohao** [comment]
[{"mzkId":112,"strftime":"2017-01-14","value":9297913},{"mzkId":112,"strftime":"2017-01-15","value":9306918},{"mzkId":112,"strftime":"2017-01-16","value":9315641},{"mzkId":112,"strftime":"2017-01-17","value":9323248},{"mzkId":112,"strftime":"2017-01-18","value":9331130},{"mzkId":112,"strftime":"2017-01-19","value":9341768},{"mzkId":112,"strftime":"2017-01-22","value":9375094},{"mzkId":112,"strftime":"2017-01-23","value":9384701},{"mzkId":112,"strftime":"2017-01-24","value":9396385},{"mzkId":112,"strftime":"2017-01-26","value":9418749},{"mzkId":112,"strftime":"2017-01-27","value":9428797},{"mzkId":112,"strftime":"2017-01-28","value":9439091},{"mzkId":112,"strftime":"2017-01-29","value":9452451},{"mzkId":112,"strftime":"2017-01-30","value":9463434},{"mzkId":112,"strftime":"2017-01-31","value":9473279},{"mzkId":112,"strftime":"2017-02-01","value":9482911},{"mzkId":112,"strftime":"2017-02-02","value":9492489},{"mzkId":112,"strftime":"2017-02-03","value":9502304},{"mzkId":112,"strftime":"2017-02-04","value":9511876},{"mzkId":112,"strftime":"2017-02-05","value":9520833},{"mzkId":112,"strftime":"2017-02-06","value":9528588},{"mzkId":112,"strftime":"2017-02-07","value":9536067},{"mzkId":112,"strftime":"2017-02-08","value":9543812},{"mzkId":112,"strftime":"2017-02-09","value":9551315},{"mzkId":112,"strftime":"2017-02-10","value":9558409},{"mzkId":112,"strftime":"2017-02-11","value":9565964},{"mzkId":112,"strftime":"2017-02-12","value":9573399}]

**Comment by dxq613** [comment]
先把 动画关了试试，是否是动画导致的， chart.animate(false);

**Comment by simaQ** [comment]
恩，先把动画关了，语法这些都是没有问题的。

**Comment by chenghaohao** [comment]
好像是动画导致的。。关了动画，刷新了很多次都没有这个问题了，正常的显示图表

**Comment by chenghaohao** [comment]
不知道这个是否是一个bug,还是希望大神们处理下啊。。没有动画感觉降低了一点炫酷档次。。

**Comment by dxq613** [comment]
嗯，我们定位一下这个问题，看看是什么原因导致的。
