### ISSUE TITLE
请教：【股票交易所深度图】怎么做

### ISSUE THREAD

**Issue by dyfvicture** [antvis/g2#862]
各位好，我想一个类似股票交易所的深度图，请问有没有例子，要怎么做：
![image](https://user-images.githubusercontent.com/6755466/45017034-11158100-b059-11e8-84cb-f07e36e0bf73.png)

* **G2 Version**: [bizcharts:3.2.1-beta.3,  @antv/g2:3.2.7-beta.5]
* **Platform**: React
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by dxq613** [comment]
用一般的面积图就好了，设置一下渐变样式就好了
