### ISSUE TITLE
玉玦图如何自定义柱子之间的间距

### ISSUE THREAD

**Issue by beautycss** [antvis/g2#864]
现状：
玉玦图只有2个数据的时候，柱子之间的间距比较大，如下图：
![image](https://user-images.githubusercontent.com/16473160/45030003-0ff64b00-b07d-11e8-9cf1-5132b66591c9.png)
已查看了g2文档，试过adjust等属性不好用。

因此，希望自定义柱子之间的间距：
![image](https://user-images.githubusercontent.com/16473160/45029946-dc1b2580-b07c-11e8-814a-e3e0b1c32551.png)

期望的效果：
![image](https://user-images.githubusercontent.com/16473160/45030397-3bc60080-b07e-11e8-8ebd-b7806ebbe563.png)

柱子之间的间距小一些。

请问如何设置，谢谢。

**Comment by dxq613** [comment]
一般来说可以通过调整柱子的宽度来调整间距
* 这个同柱状图一样，可以通过 size() 来设置柱子的宽度，
* 也可以通过全局的控制嵌套饼图宽度的参数来控制：
```js
 G2.Global.widthRatio.multiplePie = 1/2； 
```
但是对你这个场景来说，不是柱子宽度的问题，你可以通过改变坐标系内部半径的方式，将两个柱子的间距调小

```js
chart.coord('polar', {
  innerRadius: 0.2 // 调节这个半径大小
}).transpose();
```

**Comment by beautycss** [comment]
@dxq613 谢谢，调节半径解决了问题。回答的很全面很专业，赞！
