### ISSUE TITLE
外层容器缩放后图表内的tooltip位置显示没有在鼠标下

### ISSUE THREAD

**Issue by tianxuzhang** [antvis/g2#865]
G2 版本：最新版
应用场景：大屏场景，为页面自适应用了transform。
复现步骤：随便找个g2画的图，外层div使用样式transform: scale(0.5)。
现象描述：里面的图tooltip位置没有在鼠标下显示。

**Comment by zenxds** [comment]
同样遇到了这个问题，外层容器做了scale之后tooltip就错乱了

**Comment by maplor** [comment]
Duplicate of #912 
在912中我提供了一个临时解决方案。
