### ISSUE TITLE
解决了

### ISSUE THREAD

**Issue by komagic** [antvis/g2#866]
* **G2 Version**:3.2.7
* **Platform**:mac
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

为什么单折线图的时候显示正确，而双折线图显示的时候错误？（并没有数据数值超过100，最大值只有80）
错误图
![1](https://user-images.githubusercontent.com/13415767/45078212-feb34a00-b121-11e8-8660-6557a71bfebc.jpg)
![2](https://user-images.githubusercontent.com/13415767/45078215-007d0d80-b122-11e8-983d-6563c83229a8.jpg)
![3](https://user-images.githubusercontent.com/13415767/45078219-0246d100-b122-11e8-9acd-231fceeb7b2f.jpg)

**Comment by leungwensen** [comment]
麻烦发代码。codepen 链接

**Comment by komagic** [comment]
我自己弄错了，搞成stack了
