### ISSUE TITLE
  建议：可不可以闹一个中国地图的图表，具体请看图片

### ISSUE THREAD

**Issue by imsole** [antvis/g2#868]
链接地址： [点击查看](http://index.baidu.com/?tpl=crowd&word=%D6%A7%B8%B6%B1%A6)
图片：
<img width="1282" alt="map" src="https://user-images.githubusercontent.com/3367457/45100985-11974000-b15d-11e8-9d8f-970b5bd3ba5f.png">
应用场景：在做用户画像的时候，往往需要统计全国各省市的会员数量，这个时候这种图表就很方便。
不知道g2可不可以加上，感觉这个是刚需

**Comment by leungwensen** [comment]
需要自己找 geojson 来画。参考 https://antv.alipay.com/zh-cn/g2/3.x/demo/map/bubble-map.html 

G2 不会内置中国地图，因为没有地图服务的资质。后面19年1月份会接入高德，到时候就能有比较好的 2D 地图可视化体验了。

**Comment by imsole** [comment]
🐂！给你们一个大写的赞！

**Comment by ShawshankLin** [comment]
> 需要自己找 geojson 来画。参考 https://antv.alipay.com/zh-cn/g2/3.x/demo/map/bubble-map.html
> 
> G2 不会内置中国地图，因为没有地图服务的资质。后面19年1月份会接入高德，到时候就能有比较好的 2D 地图可视化体验了。
有办法我在一个自己的图片上，，然后按照坐标给地图标点吗？
https://antv.alipay.com/zh-cn/vis/chart/bubble-map.html

**Comment by FranklyCai** [comment]
> 需要自己找 geojson 来画。参考 https://antv.alipay.com/zh-cn/g2/3.x/demo/map/bubble-map.html
> 
> G2 不会内置中国地图，因为没有地图服务的资质。后面19年1月份会接入高德，到时候就能有比较好的 2D 地图可视化体验了。

https://antv.alipay.com/zh-cn/g2/3.x/demo/map/bubble-map.html 这个链接地址失效了
