### ISSUE TITLE
Uncaught Error: Invalid Date in fecha.format

### ISSUE THREAD

**Issue by suiyi8760** [antvis/g2#870]
* **G2 Version**: 3.2.7
* **Platform**: Windows 10/Chrome 69
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/16010142/45226628-f1e55080-b2f1-11e8-9279-3a7d30b0d476.png)
![image](https://user-images.githubusercontent.com/16010142/45226635-f6116e00-b2f1-11e8-8f69-c98c473ca9dc.png)

* **CodePen Link**: Sorry for none.

目前有部分海外项目用上bizcharts@3.2.2(`G2.version`输出为3.2.7)，最近陆续收到小部分海外客户反馈出现上面截图的错误导致部分页面无法打开，但是奇怪的是我们无论在线上和线下都无法重现出来，最后很艰难才把问题定位到这个组件，附上部分代码:
![image](https://user-images.githubusercontent.com/16010142/45227878-265a0c00-b2f4-11e8-8cd3-8b816815388d.png)

目前只能发现这批客户的共同点是空数据即`data=[]`，和都是window系统，麻烦看看
-------------------------------------------
有点像这个issue，但是我们使用的已经是最新的版本了：
#615

**Comment by heiniuhaha** [comment]
已修复，查看以下Demo
bizcharts@3.x https://bizcharts.net/product/bizcharts/demo/525
bizcharts@4.x https://bizcharts.net/product/BizCharts4/demo/524
