### ISSUE TITLE
Legend过滤在多Geom和selectedMode = 'single'的情况下不会生效

### ISSUE THREAD

**Issue by Frezc** [antvis/g2#874]
* **G2 Version**: latest
* **Platform**: win10
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/6942296/45290579-8f26cb80-b522-11e8-910b-557165650a8c.png)

* **CodePen Link**: https://antv.alipay.com/zh-cn/g2/3.x/demo/other/double-axes.html 在这个例子的legend配置里加一行 `selectedMode: 'single'`

**Comment by elaine1234** [comment]
legend事件其实是生效的，这个demo写的有问题，将在最新版官网中更正。感谢指出。
``` js
function onClick(ev) {
    var item = ev.item;
    var value = item.value;
    var checked = item.checked;
    var geoms = chart.getAllGeoms();
    for (var i = 0; i < geoms.length; i++) {
      var geom = geoms[i];
      if (geom.getYScale().field === value) {
        if (checked) {
          geom.show();
        }
      } else {
          geom.hide();
        }
    }
  }
```
