### ISSUE TITLE
饼图在绘制时，由于闭合问题偶发会出现 bug

### ISSUE THREAD

**Issue by dxq613** [antvis/g2#878]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

* 参看 https://riddle.alibaba-inc.com/riddles/922de17e, 有一个扇形没显示出来
* 有时候闭合错误：
![image](https://user-images.githubusercontent.com/1264678/45409604-3f6f0e00-b6a2-11e8-8309-1409f2449b86.png)

**Comment by ziposcar** [comment]
有同样的问题，偶发在某区域为50%的时候
