### ISSUE TITLE
y轴波动幅度如何设置

### ISSUE THREAD

**Issue by sangxiaolong** [antvis/g2#88]
Y轴设置了min为0，值大部分都是9.8、9.6的样子，y轴刻度否自动适应，让曲线波动幅度明显一点

![f](https://cloud.githubusercontent.com/assets/77712/23057641/0a40c126-f52c-11e6-9dc3-4274f6a64690.jpg)

**Comment by simaQ** [comment]
把 Y 轴的 min: 0 配置删除

**Comment by sangxiaolong** [comment]
@simaQ 如果把y轴的min设置为0，经常会出现曲线在x轴之下的情况，如图所示：

![ff](https://cloud.githubusercontent.com/assets/77712/23194801/3b3050a4-f8eb-11e6-986f-e80258f040d4.jpg)

所以才把min设成了0，但是这样又看不到波动了，这个问题该怎么解决？谢谢

**Comment by sangxiaolong** [comment]
官方的文档上默认刻度线是5个，实际情况好像是9个吧

**Comment by dxq613** [comment]
对于数字类型的数据基本能控制在 5-6个的坐标点，但是对于时间坐标轴来说很难保证5个刻度线，否则时间间隔会很怪，因为没法平均分割坐标点，那么可能会出现20个小时间隔的数据。

**Comment by sangxiaolong** [comment]
@dxq613 是Y轴的刻度线，数据都是数字类型的，tickCount设置成4时有4个刻度，设置成5时有6个刻度线

**Comment by dxq613** [comment]
数字坐标轴的计算也没法得到精确数量的坐标点个数，因为坐标间隔是人容易理解的数字，例如 1，2，5，10这样的数字。

假如用户的数据是 3 - 97 ，要求5个坐标点，那么会计算成 0， 20，40，60，80，100 这里有6个坐标点
如果此时预设的容易理解的数字是 [1,2,3,5,10]那么为了保证5个坐标点则会计算结果是[0,30,60,90,120],所以计算坐标点的个数没法精确确定，现在的算法能保证最多多出一个，以前版本的时候误差更大能够达到

**Comment by dxq613** [comment]
现在最新版本的默认tickCount的限制其实已经去掉了，保证能得到用户感观最好的数字，但是总有不满意的时候。坐标点的计算其实是非常复杂和麻烦的过程。
