### ISSUE TITLE
当渲染模式是 svg 时，changeData 时，底层 G animate  有问题，fade 的 svg 节点不会被清除。

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#881]
如题，demo 地址：
https://codepen.io/anon/pen/wEjbbW?editors=0010

demo 左上角 button 1 2 来回切换，图表会有fade out chart 的残影。应该是 svg 动画执行后节点没有被清除的问题。

注意：在 mac retina 屏上没有这个 bug，不会出现残影。

**Comment by leungwensen** [comment]
fixed in  3.3.1
