### ISSUE TITLE
Slider新功能需求

### ISSUE THREAD

**Issue by fenglu09** [antvis/g2#887]
* **G2 Version**: 3.1
* **Platform**:   Chrome
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

1. 能否做到直接通过鼠标左右滑动图表在进行左右移动？
2. Slider能否支持垂直方向滑动呢?
例如：[基础柱状图](https://antv.alipay.com/zh-cn/g2/3.x/demo/bar/basic.html)，像这样横向的图表，如果数据量比较大，就需要垂直方向的Slider。当然，如果能像Echart的DataZoom一样，支持直接在图标上滑动来移动图表就更好了。

**Comment by aa1011372655** [comment]
@fenglu09 ，要是着急的话，Slider里面有个pr，支持左右移动可以看一下源码，不复杂，第二个问题，我看源码中是支持的layout设置为"vertical"
这个插件在重构，不着急的话，可以等等，看看是否给予支持@leungwensen

**Comment by leungwensen** [comment]
第二个需求新版组件会支持

**Comment by linrf** [comment]
> 第二个需求新版组件会支持

请问，这个有新的进展么？

**Comment by paleface001** [comment]
dataZoom会在g2-plot中进行支持，暂时不考虑y轴slider
