### ISSUE TITLE
官网文档的 Slider 示例无法显示出 Slider 了

### ISSUE THREAD

**Issue by mobbjelly** [antvis/g2#888]
* **G2 Version**: 3.2.8
* **Platform**: macOS 10.13.6
* **Mini Showcase(like screenshots)**:
<img width="839" alt="2018-09-16 4 44 38" src="https://user-images.githubusercontent.com/8497784/45594587-0e5b4a00-b9d0-11e8-91aa-96087233a18f.png">

* **CodePen Link**:

https://antv.alipay.com/zh-cn/g2/3.x/tutorial/how-to-use-slider.html

ps: 3.2.7 版本的 G2 可以正常显示出 Slider

**Comment by leungwensen** [comment]
可以升级到  @antv/g2-plugin-slider@2.1.0 ，多谢反馈！
