### ISSUE TITLE
隐藏 Y 轴导致图例 top-right 定位失效

### ISSUE THREAD

**Issue by liunian** [antvis/g2#889]
* **G2 Version**: 3.2.8
* **Platform**: *
* **Mini Showcase(like screenshots)**: 
![image](https://user-images.githubusercontent.com/646129/45605132-2503ae80-ba6d-11e8-822e-2bedf6ffcf9f.png)

![image](https://user-images.githubusercontent.com/646129/45605172-6c8a3a80-ba6d-11e8-9faa-02828325e553.png)

* **CodePen Link**: https://codepen.io/liunian/full/ZMMmaJ

把 legend position 设为 `top-right`，但当隐藏 Y 轴后，定位到有右下方（见上方截图）；轴都显示或都隐藏时，legend 定位正常

**Comment by weepy3641** [comment]
新版本已经修复。
