### ISSUE TITLE
请问G2如何使用渐变色？

### ISSUE THREAD

**Issue by kunsam** [antvis/g2#89]
chart.intervalStack()
            .color('name', ['#cccccc-#000000', '#1ac6b3', '#ffbc2e', '#ccd5ff']);

我尝试过
`.color('name', ['#cccccc-#000000', '#1ac6b3', '#ffbc2e', '#ccd5ff']);`
`.color('name', ['linear-gradient(left, #cccccc, #000000', '#1ac6b3', '#ffbc2e', '#ccd5ff']);`
均没有效果

**Comment by simaQ** [comment]
你好，支持的，如果你这种场景的话，使用这种形式：` l(270) 0:#173162 1:#3663a1'`, l 后面传入角度，0 代表起始颜色，1 代表结束颜色。

```js
.color('name',['l(0) 0:#ccc 1:#000', '#1ac6b3', '#ffbc2e', '#ccd5ff']]); 
```

**Comment by kunsam** [comment]
谢谢解答！
