### ISSUE TITLE
chart.source(data, scaleConfig)中，默认的scaleConfig.[field].type是如何判断的？

### ISSUE THREAD

**Issue by NoraGithub** [antvis/g2#893]
当使用chart.source(data)时，没有声明scaleConfig。这时，scaleConfig根据数据对不同field判断 了不同的type。但这并不是我想要的。如， 2019-09-12 判断为'time'，但我希望按时间处理为直方图（柱形图），请问如何处理。

**Comment by dxq613** [comment]
直接把时间处理成时间戳就好了
