### ISSUE TITLE
根据数据配置tooltip,当数据值为undined时，不显示这条数据的tooltip

### ISSUE THREAD

**Issue by zhoujiamin** [antvis/g2#896]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

想根据数据值配置tooltip，当数据值为undined时，不显示这条数据的tooltip
this.chart.line().position('x*z').color('lineName').size(3).tooltip('lineName*z', (lineName, z) => {
                if (z !== undefined) {
                    return {
                        name: lineName,
                        value: z + '%',
                    };
                }
                return false;
            });
但我这么配置还是会显示出这数据的占位
![image](https://user-images.githubusercontent.com/16118305/45673826-4ee8ce00-bb5e-11e8-86eb-e9a7f295b0e6.png)

**Comment by aa1011372655** [comment]
复杂场景可以通过tooltipchange事件来处理，能满足几乎所有奇葩需求，https://antv.alipay.com/zh-cn/g2/3.x/tutorial/tooltip.html#_%E6%A0%BC%E5%BC%8F%E5%8C%96-tooltip-%E7%9A%84%E6%98%BE%E7%A4%BA%E5%86%85%E5%AE%B9
