### ISSUE TITLE
tooltip的css改动优化？

### ISSUE THREAD

**Issue by youyinnn** [antvis/g2#897]
关于tooltip的显示和隐藏

如果用`visibility:visible`和`visibility:hidden`去做的话 当容器如果有高z-index的时候 多层z-index的情况下 
tooltip的隐藏会有样式滞留 不太美观

我是改了源代码用opacity的0 1去做显示和隐藏的

你们看这两个哪种好点？

**Comment by leungwensen** [comment]
都做上吧。新版里加一下 @paleface001
