### ISSUE TITLE
Slider滑动条的结束时间显示不完整，请问显示位置可以修改吗？

### ISSUE THREAD

**Issue by zhangyanf** [antvis/g2#899]
通过设置padding的方式方式不太理想，如果slider显示的开始结束时间的格式变化了，就需要重新调整padding，并且slider与图表也不太容易对齐了。
可以设置结束时间的位置在右侧滑块图标的左侧吗？
![image](https://user-images.githubusercontent.com/10766381/45743885-a9059400-bc2f-11e8-8020-26cee7a7f379.png)

**Comment by paleface001** [comment]
slider文字避让已在g2-plot中支持
