### ISSUE TITLE
chart.guide().dataMarker里的content可以接收callback，动态展示数据吗？

### ISSUE THREAD

**Issue by houzip** [antvis/g2#900]
别如说 我的折线图需要展示最高点的数据 就需要动态的获取最高点的数据 并进行展示。

**Comment by paleface001** [comment]
你好，可以看看这个demo里的用法符不符合你的需求： https://antv.alipay.com/zh-cn/g2/3.x/demo/component/region-filter-realtime-data.html

**Comment by houzip** [comment]
@paleface001 这个例子里的 content是写死的 当前最大峰值 我想要把这个content对应的数据动态展示出来

**Comment by yshenhua** [comment]
这个问题有解决方案了吗，我要画一根均值线，但是不知道chart.guide().line()里的content该怎么动态展示

**Comment by dxq613** [comment]
可以清理掉 guide 重新绘制
```js
chart.guide().clear();
chart.guide().line();

chart.repaint();
```
