### ISSUE TITLE
有vue版本的G2吗

### ISSUE THREAD

**Issue by yelingfeng** [antvis/g2#91]
如题

**Comment by dxq613** [comment]
vue的封装还没进行，后面会提供简单的封装

**Comment by fireyy** [comment]
@yelingfeng vue 我封装了个简单的，可以看这里 https://github.com/fireyy/g2-vue

**Comment by yelingfeng** [comment]
@fireyy  3q

**Comment by zx8713** [comment]
@fireyy 在vue里用g2怎么设置一个chart的config，比如width，height和plotCfg这些？

**Comment by umi-soft** [comment]
至今都没有vue的版本吗？

**Comment by gy18505** [comment]
现在有vue2.x可用的了吗？
