### ISSUE TITLE
【基础环图】当占比为50%的时候，半圆变小了

### ISSUE THREAD

**Issue by hxdyj** [antvis/g2#910]
* **G2 Version**:g2-3.2.7
* **Platform**:Mac Chrome
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/14368755/45995735-ebb1eb00-c0cb-11e8-84b4-7c5f1ceabeee.png)

* **CodePen Link**:

当占比为50%的时候，半圆变小了

**Comment by leungwensen** [comment]
更新到 3.2.8，这个问题已修复
