### ISSUE TITLE
图表在大屏上显示会出现鼠标位置偏移的问题

### ISSUE THREAD

**Issue by DonChengCheng** [antvis/g2#912]
* **G2 Version**: 3.2.8
* **Platform**: mac 台式
* **Mini Showcase(like screenshots)**:

* **CodePen Link**:

**Comment by leungwensen** [comment]
是不是 container 的 css 里用了缩放（譬如 `transform: scale(0.7);`）？目前容器如果存在 scaling，确实会有问题

**Comment by DonChengCheng** [comment]
这个bug什么时候能修复好？

**Comment by leungwensen** [comment]
排期在 3.3.x 的迭代中修复，要在十月份之后了。

**Comment by DonChengCheng** [comment]
@leungwensen 这个问题修复的怎么样了？

**Comment by zenxds** [comment]
同问

**Comment by leungwensen** [comment]
抱歉，这个涉及到底层 G 的改动，暂时还没有修复

**Comment by teazean** [comment]
@leungwensen 这个问题，什么时候修复，已经过了快半年了？

**Comment by 18402025768** [comment]
@leungwensen 这个问题什么时候修复,已经3.5.5版本了

**Comment by maplor** [comment]
各位如果等不及的，我提供一个临时解决方案：
在G2初始化之前运行以下代码，亲测是可以解决问题的。

```javascript
/**
 * 在G2初始化前，替换 G.Canvas.getPointByClient 函数，适配CSS缩放的场景。
 * */
const rawGetPointByClient = G2.G.Canvas.prototype.getPointByClient;
// 由于需要运行时this指针，这个函数不可改为箭头函数。
G2.G.Canvas.prototype.getPointByClient = function(clientX, clientY) {
  // 获取原函数返回的坐标值
  const raw = rawGetPointByClient.call(this, clientX, clientY);
  // 获取设定高宽和真实高宽。
  // 当设定的高宽不等于getBoundingClientRect获取的高宽时，说明存在缩放。
  const el = this.get('el');
  const bbox = el.getBoundingClientRect();
  const setWidth = this.get('width');
  const setHeight = this.get('height');
  const { width: realWidth, height: realHeight } = bbox;
  // 除以缩放比（真实高宽 / 设定高宽）获得真实的坐标。
  return {
    x: raw.x / (realWidth / setWidth),
    y: raw.y / (realHeight / setHeight),
  };
};
```

另外 @leungwensen  看下这部分是否合适直接在G改造，或者我发起PR。

**Comment by tianxuzhang** [comment]
@maplor 问题能解决

**Comment by dxq613** [comment]
@maplor 可以在 G 4.0 的版本中实现。https://github.com/antvis/g/tree/4.x

**Comment by fuyongxia** [comment]
> 各位如果等不及的，我提供一个临时解决方案：
> 在G2初始化之前运行以下代码，亲测是可以解决问题的，我的G2版本：3.5.3。
> 
> ```js
> /**
>  * 在G2初始化前，替换 G.Canvas.getPointByClient 函数，适配CSS缩放的场景。
>  * */
> const rawGetPointByClient = G2.G.Canvas.prototype.getPointByClient;
> // 由于需要运行时this指针，这个函数不可改为箭头函数。
> G2.G.Canvas.prototype.getPointByClient = function(clientX, clientY) {
>   // 获取原函数返回的坐标值
>   const raw = rawGetPointByClient.call(this, clientX, clientY);
>   // 获取设定高宽和真实高宽。
>   // 当设定的高宽不等于getBoundingClientRect获取的高宽时，说明存在缩放。
>   const el = this.get('el');
>   const bbox = el.getBoundingClientRect();
>   const setWidth = this.get('width');
>   const setHeight = this.get('height');
>   const { width: realWidth, height: realHeight } = bbox;
>   // 除以缩放比（真实高宽 / 设定高宽）获得真实的坐标。
>   return {
>     x: raw.x / (realWidth / setWidth),
>     y: raw.y / (realHeight / setHeight),
>   };
> };
> ```
> 
> 另外 @leungwensen 看下这部分是否合适直接在G改造，或者我发起PR。

G2初始化在哪个文件，我用的3.5.8只找到了这个定义的地方：
getPointByClient: function getPointByClient(clientX, clientY) {
    var el = this.get('el');
    var pixelRatio = this.get('pixelRatio') || 1;
    var bbox = el.getBoundingClientRect();
    return {
      x: (clientX - bbox.left) * pixelRatio,
      y: (clientY - bbox.top) * pixelRatio
    };
    
  },

**Comment by fuyongxia** [comment]
> 各位如果等不及的，我提供一个临时解决方案：
> 在G2初始化之前运行以下代码，亲测是可以解决问题的，我的G2版本：3.5.3。
> 
> ```js
> /**
>  * 在G2初始化前，替换 G.Canvas.getPointByClient 函数，适配CSS缩放的场景。
>  * */
> const rawGetPointByClient = G2.G.Canvas.prototype.getPointByClient;
> // 由于需要运行时this指针，这个函数不可改为箭头函数。
> G2.G.Canvas.prototype.getPointByClient = function(clientX, clientY) {
>   // 获取原函数返回的坐标值
>   const raw = rawGetPointByClient.call(this, clientX, clientY);
>   // 获取设定高宽和真实高宽。
>   // 当设定的高宽不等于getBoundingClientRect获取的高宽时，说明存在缩放。
>   const el = this.get('el');
>   const bbox = el.getBoundingClientRect();
>   const setWidth = this.get('width');
>   const setHeight = this.get('height');
>   const { width: realWidth, height: realHeight } = bbox;
>   // 除以缩放比（真实高宽 / 设定高宽）获得真实的坐标。
>   return {
>     x: raw.x / (realWidth / setWidth),
>     y: raw.y / (realHeight / setHeight),
>   };
> };
> ```
> 
> 另外 @leungwensen 看下这部分是否合适直接在G改造，或者我发起PR。

**zoom这个不适用，但是scale的话也没的字体会变模糊**

**Comment by fuyongxia** [comment]
> 各位如果等不及的，我提供一个临时解决方案：
> 在G2初始化之前运行以下代码，亲测是可以解决问题的，我的G2版本：3.5.3。
> 
> ```js
> /**
>  * 在G2初始化前，替换 G.Canvas.getPointByClient 函数，适配CSS缩放的场景。
>  * */
> const rawGetPointByClient = G2.G.Canvas.prototype.getPointByClient;
> // 由于需要运行时this指针，这个函数不可改为箭头函数。
> G2.G.Canvas.prototype.getPointByClient = function(clientX, clientY) {
>   // 获取原函数返回的坐标值
>   const raw = rawGetPointByClient.call(this, clientX, clientY);
>   // 获取设定高宽和真实高宽。
>   // 当设定的高宽不等于getBoundingClientRect获取的高宽时，说明存在缩放。
>   const el = this.get('el');
>   const bbox = el.getBoundingClientRect();
>   const setWidth = this.get('width');
>   const setHeight = this.get('height');
>   const { width: realWidth, height: realHeight } = bbox;
>   // 除以缩放比（真实高宽 / 设定高宽）获得真实的坐标。
>   return {
>     x: raw.x / (realWidth / setWidth),
>     y: raw.y / (realHeight / setHeight),
>   };
> };
> ```
> 
> 另外 @leungwensen 看下这部分是否合适直接在G改造，或者我发起PR。
    

不支持zoom，使用scale会有字体模糊的情况，能不能支持zoom

**Comment by maplor** [comment]
> > 各位如果等不及的，我提供一个临时解决方案：
> > 在G2初始化之前运行以下代码，亲测是可以解决问题的，我的G2版本：3.5.3。
> > ```js
> > /**
> >  * 在G2初始化前，替换 G.Canvas.getPointByClient 函数，适配CSS缩放的场景。
> >  * */
> > const rawGetPointByClient = G2.G.Canvas.prototype.getPointByClient;
> > // 由于需要运行时this指针，这个函数不可改为箭头函数。
> > G2.G.Canvas.prototype.getPointByClient = function(clientX, clientY) {
> >   // 获取原函数返回的坐标值
> >   const raw = rawGetPointByClient.call(this, clientX, clientY);
> >   // 获取设定高宽和真实高宽。
> >   // 当设定的高宽不等于getBoundingClientRect获取的高宽时，说明存在缩放。
> >   const el = this.get('el');
> >   const bbox = el.getBoundingClientRect();
> >   const setWidth = this.get('width');
> >   const setHeight = this.get('height');
> >   const { width: realWidth, height: realHeight } = bbox;
> >   // 除以缩放比（真实高宽 / 设定高宽）获得真实的坐标。
> >   return {
> >     x: raw.x / (realWidth / setWidth),
> >     y: raw.y / (realHeight / setHeight),
> >   };
> > };
> > ```
> > 
> > 
> > 另外 @leungwensen 看下这部分是否合适直接在G改造，或者我发起PR。
> 
> 不支持zoom，使用scale会有字体模糊的情况，能不能支持zoom


zoom 是非标准属性，暂时没有支持的计划。scale字体模糊的原因是缩放前文字元素高度为奇数：
> 这是因为transform变换会在浏览器上单独创建一个绘画层并重新进行渲染，rotate渲染的时候，由于图层渲染的时候也处理了周围的文字，如果高度为奇数的文字可能会存在半个像素的计算量，浏览器对这半个像素会进行优化渲染，所以边缘会出现模糊的情况。
尽量控制高度和宽度为整数就可以规避这个问题，网上也有很多其它的解决方案。例如设置 `perspective(1px)`

**Comment by maplor** [comment]
> > 排期在 3.3.x 的迭代中修复，要在十月份之后了。
> 
> 这个问题已经修复了么？4.x后还是会出现 t-t

看起来遥遥无期了，而且 3.x 的 hack 方法在 4.x 还用不了，又得重写

**Comment by liyujian3225** [comment]
用g2做了很多大屏应用，大屏自适应时tooltip偏移，希望g2团队能快速解决这个问题！

**Comment by jinzhuming** [comment]
new Chart({supportCSSTransform: true})  就可以支持缩放和旋转 4.1.x 亲测可行
<img width="806" alt="CleanShot 2021-11-06 at 16 18 40@2x" src="https://user-images.githubusercontent.com/19699476/140603079-c056c166-1faf-4723-bb03-fb8dc9ac8634.png">
