### ISSUE TITLE
当初始图表宽高小于padding时，auto padding计算错误

### ISSUE THREAD

**Issue by Frezc** [antvis/g2#919]
* **G2 Version**: latest
* **Platform**: all
* **Mini Showcase(like screenshots)**: 
* **CodePen Link**: https://codepen.io/anon/pen/RewMLY?editors=1000#0

当new Chart时传入的width和height小于某个方向的padding时，同方向的auto padding会计算错误。

**Comment by leungwensen** [comment]
预期的结果是什么？

**Comment by leungwensen** [comment]
指定 height 为 0，那确实没办法正常绘图

**Comment by Frezc** [comment]
这个问题太久了，记得好像是当初始化时图表的height < padding时，比如上面例子里 height: 0, paddingBottom: 80，这个时候paddingTop的auto就会根据80这个异常值来计算了，我希望的是就算出现height < padding的情况也不应该存在异常值。虽然图表初始height为0，但在changeSize后也应该有正确的padding
