### ISSUE TITLE
为什么年月日前面要加个空格才能显示正常？

### ISSUE THREAD

**Issue by 2413052180** [antvis/g2#92]
![bug1](https://cloud.githubusercontent.com/assets/13171956/23248526/c606b17e-f9da-11e6-8084-371a1a684195.png)
![bug2](https://cloud.githubusercontent.com/assets/13171956/23248527/c60c27da-f9da-11e6-9188-7ce33c6c196e.png)

请观察上面两张图片，第一张是错误的，第二张是正确的，数据里的日期为1月1日至1月30日，为什么在年月日前面加个空格才能显示我想要显示的界面，是我设置的问题么？

**Comment by simaQ** [comment]
这个需要你在列定义中配置下 range 属性，可以参照这个例子：https://antv.alipay.com/g2/demo/02-line/simple-line.html

```js
 chart.source(data, {
        month: {
          alias: '月份',
          range: [0, 1]
        },
        temperature: {
          alias: '平均温度(°C)'
        }
      });
```

**Comment by zpz1982** [comment]
加空格以后会认为是‘cat’ 类型， 不加空格会自动转为'time'类型，我也遇到这样问题。不知g2为什么要这样做。

**Comment by dxq613** [comment]
时间类型的坐标轴计算的时候会找到一个合适的时间间隔，你这个demo计算出来的时间间隔是6天，所以会在坐标轴的两端留下空白，可以在列定义里面增加个配置项 nice: false。我记得之前的时候时间类型的scale默认设置了nice: false

**Comment by wengcd** [comment]
@simaQ `datetime` 如何设置range？

**Comment by simaQ** [comment]
一样的， range: [start, end] start 和 end 必须是 0 至 1  范围的数据。
