### ISSUE TITLE
scale类型pow，全部值为0无法正常显示

### ISSUE THREAD

**Issue by hongfs** [antvis/g2#920]
* **G2 Version**: 3.2.7
* **Platform**: Chrome
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/hongfs/pen/OBJEwv

类型为pow的时候。如果全部值都是0，将无法显示度量

**Comment by leungwensen** [comment]
这种情况你要手动设置最大值最小值

```js
chart.scale('value', {
  min: 0,
  max: 100,
  type: 'pow'
});
```

**Comment by hongfs** [comment]
如果是无法指定最大值的情况呢？
