### ISSUE TITLE
在非刻度位置，max 的地方出现了 grid 线，也无法去掉

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#924]
如题

https://antv.alipay.com/zh-cn/g2/3.x/demo/other/punch-card.html
删除49行可见

![image](https://user-images.githubusercontent.com/3838676/46240590-7fd9c600-c3dc-11e8-915f-d8454c0e03d7.png)

https://github.com/alibaba/BizCharts/issues/547

**Comment by dxq613** [comment]
nice: false 时会出现这种情况，grid 有个隐藏第一个、最后一个栅格线的配置项：

```js
chart.axis('weekday', {
    line: null,
    tickLine: null,
    grid: {
    	hideLastLine: true
    },
    label: {
      textStyle: {
        fontSize: 14,
        fill: '#555'
      }
    }
  });
```
