### ISSUE TITLE
（需求）关于多轴分组柱状图的原生支持

### ISSUE THREAD

**Issue by wxhccc** [antvis/g2#927]
关于这个需求，可以查看F2库的“其他图表”里[双 Y 轴分组柱状图](https://antv.alipay.com/zh-cn/f2/3.x/demo/other/double-axis-interval.html)，本人在使用G2时遇到此类图标需求，实现方式和上面提到的的一致，都是使用shape来实现目标的，然而个人认为这是一种不太好的实现方式（从辅助框宽度和分组不一致就可以看出）。PS: 之后我又在echart官网查找过，发现其多轴柱状图在使用相同几何标记时默认支持分组，辅助框也是正常的。
    希望贵团队能在百忙之中抽点时间处理下这个需求，万分感谢

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/demo/bar/grouped-column.html

1. 一定要用双 Y 轴的原因是？两个柱子摆在一起，如果刻度不一致，会带来歧义；
2. 如果两个柱子可以公用一个坐标轴，那用分组柱状图就可以了

**Comment by wxhccc** [comment]
产品的需求是双y轴分组柱状图，可能是从其他地方看见的（echart也有原生支持说明确实有需求），多轴同几何标记如果缺少图例确实会有歧义，但加上图例就很明显了。
    另外，2个坐标一个是单位是（件），另外一个是（元），金额最大值远大于数量，用单轴分组柱状图不合适，数量柱高度会过小。

**Comment by jany3534** [comment]
也有相同的需求

**Comment by jany3534** [comment]
坐标轴位置设置偏移值是否能支持下

**Comment by mrKylinZhou** [comment]
能否根据原始指标设置Y轴，而不是根据 transform fold 方式转变后的设置，分组多Y轴这种情况确实是存在的。

**Comment by mrKylinZhou** [comment]
我们做可视化场景也很长时间了，确实有实实在在的用户需求，之前一直用Echarts或者Hightcharts。非常喜欢avtv 的设计理念，在用avtv重构的过程中，卡在这个地方了。考虑到自己绘制成本很高，而且也会有场景满足不了，还是希望官方能解决下。

**Comment by dxq613** [comment]
* 这个问题从可视化的角度来说并不是一个好的方案，当两个坐标轴差异非常大时，不建议使用两个柱状图，而是一个柱状图，一个折线图。
* 回到具体的解决方案来看，一份数据通过 dodge 进行分组时是对同一个分类下的数据进行了调整，而从 GPL (The Grammar O Graphics 作者设计的一套图形语言）来看没有这方面的设计，从我们的角度来看这牵扯到了多个 geometry 的数据调整，所以从目前来看通过自定义 shape 是一个方便的方案。

* 不建议的方案，我们不会内置到 G2 中，见谅！

**Comment by BoleLee** [comment]
默默地问一下，有这种类型的双Y轴需求：
x轴共用，y轴1是分组柱状图，y轴2是几条折线图，y轴1用的刻度是数字，y轴2为百分比。
我应该用怎样的方案来实现比较合适？

**Comment by hustcc** [comment]
> 默默地问一下，有这种类型的双Y轴需求：
> 
> x轴共用，y轴1用于分组柱状图，y轴2用于折线图，y轴1用的刻度是数字，y轴2为百分比。
> 
> 我应该用怎样的方案来实现比较合适？（目前是用F2）
> 
> @dxq613 

G2 官网有双轴图的 demo，G2Plot 有封装好，直接用的双轴图。
