### ISSUE TITLE
Is this available in R Shiny?

### ISSUE THREAD

**Issue by temiwale88** [antvis/g2#928]
Hello, 

Is this available for R Shiny users?

Thanks,
Elijah

* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by timelyportfolio** [comment]
not yet, but I started a discussion [here](https://community.rstudio.com/t/lets-clarify-the-successor-to-ggvis/392/52)

**Comment by temiwale88** [comment]
Ok. Thanks!
