### ISSUE TITLE
优化tooltip在大量数据下的性能问题

### ISSUE THREAD

**Issue by Frezc** [antvis/G2#930]
* **G2 Version**: latest
* **Platform**: any
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/6942296/46590199-0fb9f700-cae4-11e8-9a97-f128ebe29d2f.png)

* **CodePen Link**: https://codepen.io/Frezc/pen/EdNNRg

上面的例子里有3万个点，显示tooltip大概要耗时2s，完全没法用。
希望实现类似 http://echarts.baidu.com/option.html#hoverLayerThreshold 的功能。

**Comment by Frezc** [comment]
请问这个需求你们有排期实现吗？
没有的话我近期可以尝试实现一下。

**Comment by leungwensen** [comment]
暂时没排期，整个架构和流程升级、彻底解决性能问题可能要放到下一个大版本了。
