### ISSUE TITLE
G2 词云data为中文时位置错乱相互重叠

### ISSUE THREAD

**Issue by demoncome** [antvis/g2#931]
我在G2词云的demo中按照原来的json结构引入中文关键词内容，结果如图中，位置错乱和相互覆盖，引入英文则没有此问题，请问有没有解决的办法？
![image](https://user-images.githubusercontent.com/23188627/46595141-97662c80-cb09-11e8-83b5-9579465fb256.png)
json数据片段：
![image](https://user-images.githubusercontent.com/23188627/46595153-a5b44880-cb09-11e8-8b23-07d5472c8c7f.png)

**Comment by leungwensen** [comment]
发 codepen

**Comment by leungwensen** [comment]
词云的布局和是否中文字符是无关的。它规避文字重叠的原理是把文字在 canvas 上画出来，然后看它占的像素是否已经有已经画了的像素点了。事实上我们这个 demo 甚至是中英文混排的： https://antv.alipay.com/zh-cn/g2/3.x/demo/other/word-cloud-mask.html 。你对着官网 demo 检查一下配置语法吧。

**Comment by LinFeng1997** [comment]
字体设置小一点，padding 设置大一点@demoncome

**Comment by Jody9d** [comment]
请问如何解决中文重叠的问题呀？

**Comment by czh1998yr** [comment]
我现在碰到了跟您一样的问题，请问您的解决办法是什么呢？
