### ISSUE TITLE
双y轴，设置min:0 后 ，y轴仍旧出现最小值-1的情况

### ISSUE THREAD

**Issue by luckhpy** [antvis/g2#932]
双y轴，设置min:0 后 ，y轴仍旧出现最小值-1的情况，代码如下
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,height=device-height">
    <title>曲线折线图</title>
    <style>::-webkit-scrollbar{display:none;}html,body{overflow:hidden;height:100%;margin:0;}</style>
</head>
<body>
<div id="mountNode"></div>
<script>/*Fixing iframe window.innerHeight 0 issue in Safari*/document.body.clientHeight;</script>
<script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.g2-3.3.0-beta.4/dist/g2.min.js"></script>
<script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js"></script>
<script>

var data =  [
  {
    "statDate": "2018-10-01",
    "mallId": 7606022,
    "goodsId": null,
    "aaaaaa": 0,
    "aaaaab": 0,
    "aaaaac": 0,
    "aaaaad": 0,
    "aaaaae": 0
  },
  {
    "statDate": "2018-10-02",
    "mallId": 7606022,
    "goodsId": null,
    "aaaaaa": 0,
    "aaaaab": 0,
    "aaaaac": 0,
    "aaaaad": 0,
    "aaaaae": 0
  },
  {
    "statDate": "2018-10-03",
    "mallId": 7606022,
    "goodsId": null,
    "aaaaaa": 0,
    "aaaaab": 0,
    "aaaaac": 0,
    "aaaaad": 0,
    "aaaaae": 0
  },
  {
    "statDate": "2018-10-04",
    "mallId": 7606022,
    "goodsId": null,
    "aaaaaa": 0,
    "aaaaab": 0,
    "aaaaac": 0,
    "aaaaad": 0,
    "aaaaae": 0
  },
  {
    "statDate": "2018-10-05",
    "mallId": 7606022,
    "goodsId": null,
    "aaaaaa": 0,
    "aaaaab": 0,
    "aaaaac": 0,
    "aaaaad": 0,
    "aaaaae": 0
  },
  {
    "statDate": "2018-10-06",
    "mallId": 7606022,
    "goodsId": null,
    "aaaaaa": 0,
    "aaaaab": 0,
    "aaaaac": 0,
    "aaaaad": 0,
    "aaaaae": 0
  },
  {
    "statDate": "2018-10-07",
    "mallId": 7606022,
    "goodsId": null,
    "aaaaaa": 1,
    "aaaaab": 0,
    "aaaaac": 0,
    "aaaaad": 0,
    "aaaaae": 0
  }
]

var ds = new DataSet();
var dv = ds.createView().source(data);
// fold 方式完成了行列转换，如果不想使用 DataSet 直接手工转换数据即可
dv.transform({
  type: 'fold',
  fields: ['aaaaaa'], // 展开字段集
  key: 'ylKey', // key字段
  value: 'ylValue' // value字段
});
dv.transform({
  type: 'fold',
  fields: ['aaaaab', 'aaaaac', 'aaaaad', 'aaaaae'], // 展开字段集
  key: 'yrKey', // key字段
  value: 'yrValue' // value字段
});
var chart = new G2.Chart({
  container: 'mountNode',
  forceFit: true,
  height: window.innerHeight
});
chart.source(dv);
chart.tooltip({
  crosshairs: {
    type: 'line'
  }
});
chart.scale( 'yrValue', {"alias":"指数","tickCount":6,"min":0})
chart.scale( 'ylValue', {"alias":"销量","tickCount":6,"min":0})
chart.line().position('statDate*yrValue').color('yrKey').shape('smooth');
chart.line().position('statDate*ylValue').color('ylKey').shape('smooth');
chart.render();
</script>
</body>
</html>
通过设置nice: false可以解决该问题，但是这样子的话，UI会比较丑，是否可以考虑优化这一点

**Comment by leungwensen** [comment]
-1 那个是由 yrValue 字段计算出来的，这个字段只有一个值：0，所以强制设置 tickCount 为6的情况下，会尝试去上下拓展它的边界。

单值的字段确实没法给出“好看”的 ticks，因为我们不知道你的预期是什么。这种情况可以手动设置 ticks

**Comment by luckhpy** [comment]
对的，但是设置了min的情况下，拓展边界在min之上去拓展不是更合适吗
