### ISSUE TITLE
旭日图的子集等于父集时，子集不能完全填充

### ISSUE THREAD

**Issue by carlosshilei** [antvis/g2#933]
旭日图实例。
![_ _20181008165105](https://user-images.githubusercontent.com/32117692/46599630-65a99180-cb1a-11e8-9ece-2c814b7012c7.png)
sum为1，子集sum也为1.弧度只占父集的一半左右。
没有找到能调整这个的api或参数。

**Comment by leungwensen** [comment]
dataset 的 partition 布局会对指定的字段（field）进行 sum 运算，子节点的 field 值会被累加到父节点上。这个数据如果正常展示层级信息的时候，field 应该指定为 uv 的。数据里的 sum 是提前统计的结果，指定 field 为 sum 的时候会导致进一步累加统计结果，所以就出现了看起来 sum 和子节点 sum 之和不同的情况。画旭日图只要保证 field 上的值没有经过累加即可。

举例： https://antv.alipay.com/zh-cn/g2/3.x/demo/relation/sunburst.html

把布局部分的代码改为

```js
  dv.source(data, {
    type: 'hierarchy'
  }).transform({
    type: 'hierarchy.partition',
    field: 'uv', // 用未经统计的 uv 字段，而不是 sum 字段
    as: ['x', 'y']
  });
```

**Comment by carlosshilei** [comment]
uv的值是如何计算的？我看实例给的数据没有看明白，若能指点一下，非常感谢。 @leungwensen

**Comment by leungwensen** [comment]
@carlosshilei uv 的值是原始值，sum 值是基于 uv 统计的。要符合你的需求，这个布局需要用原始值进行计算

**Comment by carlosshilei** [comment]
明白了。非常感谢

**Comment by dxq613** [comment]
很多人在这个场景下，会直觉的进行累加，所以很容易出错。可以加个参数或者增加个判定，兼容掉这个问题，否则后面依然会不少人采坑。
