### ISSUE TITLE
桑基图绘制出错

### ISSUE THREAD

**Issue by Me-Momo** [antvis/g2#934]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/kasmine/pen/aRpwyy

可以看到 华东到技术产品有数据，但是绘制结果如下～
但是将数据拷贝到codePen时，绘制又正常了
![image](https://user-images.githubusercontent.com/15646325/46646998-0dc56600-cbc0-11e8-88a6-6ae39ff631db.png)

**Comment by leungwensen** [comment]
codepen 无法复现，你发一下你的代码以及 g2、dataset 的版本号。

看起来像是 x 和 y 的度量没有统一，检查一下代码里有没有这一段：

```js
  chart.scale({
    x: {
      sync: true
    },
    y: {
      sync: true
    }
  });
```

**Comment by Me-Momo** [comment]
@leungwensen  确实是呢！不同view数据源不同的时候要使用sync来统一度量，但是感觉上这样子的设计不是很合理，不过目前问题解决了～谢谢哈
