### ISSUE TITLE
series 的 legend 别名不生效

### ISSUE THREAD

**Issue by huxiaoyun** [antvis/g2#937]
* **G2 Version**:

* **Platform**:
* **Mini Showcase(like screenshots)**:

![image](https://user-images.githubusercontent.com/4345248/46709074-9b628d80-cc74-11e8-9eac-165cca6c904e.png)

* **CodePen Link**:

https://riddle.alibaba-inc.com/riddles/4ab8403e?amdType=common

另外一个问题：
数据处理后，tooltip 和 legend 别名都不生效

![image](https://user-images.githubusercontent.com/4345248/46709100-be8d3d00-cc74-11e8-9c58-66ad942b7ffd.png)

https://riddle.alibaba-inc.com/riddles/1df620e8

**Comment by leungwensen** [comment]
第一个问题是目前 legend 机制的问题，它显示值需要是原始数据，因为这个值直接用来过滤数据。是个 bug。第二个问题是这样的：你做了 fold 之后，数据里已经没有 Tokyo 和 London 这俩字段了，只有 city，scale 配置是针对字段的，不是针对字段值的。
