### ISSUE TITLE
Word error in official docs description 

### ISSUE THREAD

**Issue by kunsam** [antvis/g2#94]
I find a field error in https://antv.alipay.com/g2/api/chart.html.

The place is chart guide part.

// 添加辅助框
chart.guide().rect([startXValue, startYValue], [endXValue, **startYValue**], {
  lineWidth: 0, // 辅助框的边框宽度
  fill: '#f80', // 辅助框填充的颜色
  fillOpacity: 0.1, // 辅助框的背景透明度
  stroke: '#ccc' // 辅助框的边框颜色设置
});

The strong word above  should be **endYValue** i think.

**Comment by simaQ** [comment]
Thanks

**Comment by simaQ** [comment]
已纠正
