### ISSUE TITLE
G2类型定义文件 - 问题

### ISSUE THREAD

**Issue by Me-Momo** [antvis/g2#941]
* **G2 Version**: 3.2.8
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

![image](https://user-images.githubusercontent.com/15646325/46788275-60438580-cd6c-11e8-9eaf-7dbd586f1008.png)
使用G2类型定义的时候，geom.label如何使用了除offset和textStyle字段外的属性会报错，严格模式下 ts编译无法通过 ～ 
**建议1：**  下个小版本是否可以帮忙加上这一段
```
label(exe: string, opt: {
      offset?: number;
      textStyle?: Styles.text;
      [key: string]: any; // 加上这一段～～
    }): this;
```
**建议2：** 类型定义文件是否在lib下也备份一份，目前存在src源目录夹下～

**Comment by leungwensen** [comment]
done in 3.3.1
