### ISSUE TITLE
极坐标的起始角度和结束角度可以设置为逆时针方向吗

### ISSUE THREAD

**Issue by zenxds** [antvis/g2#945]
* **G2 Version**: 3.2.8
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

目前看起来只能顺时针，设置startAngle和endAngle为逆时针方向是不行的，比如这个[玉珏图](https://antv.alipay.com/zh-cn/g2/3.x/demo/other/radial-bar.html)，如何能够变成逆时针方向

**Comment by leungwensen** [comment]
直接用坐标系翻转做： 把那个 demo coord 定义那一句改成：

```js
chart.coord('polar', {
  innerRadius: 0.1
}).transpose().scale(1, -1);
```

**Comment by PomeloMan** [comment]
这个方法在新版本(v4)不行了，新版本有什么方法实现吗？
