### ISSUE TITLE
Support tooltip mount node customization.

### ISSUE THREAD

**Issue by Frezc** [antvis/G2#948]
希望对于html渲染的tooltip能添加自定义挂载节点的配置

**Comment by leungwensen** [comment]
目前没法放到 container 外部，但可以做细节的自定义：

https://antv.alipay.com/zh-cn/g2/3.x/demo/component/tooltip-fixed-position.html

这个能满足要求吗？

**Comment by Frezc** [comment]
因为应用场景是看板，这种需要额外空间的方式不太合适。
我碰到的问题是tooltip会被外层容器限制，所以能像antd一样挂到body上是最好的。

**Comment by paleface001** [comment]
请问你的需求对tooltip的鼠标跟随有要求吗？
目前G2 tooltip采用的策略是对其做container内部的位置约束，后期会看需求来决定是否开放更灵活的接口配置。

**Comment by Frezc** [comment]
对鼠标跟随倒没有要求，当然是能有更好。
我提这个需求的原因是图表的父容器里有任何一级的overflow不为visible时，tooltip里超出容器的内容就会被截断，或者容器被tooltip的高度撑开。
因为我们项目里tooltip里的项一般会比较多(主机ip、pod name之类的)，所以上面例子里的方式不太好。

不过目前可以通过保证所有父容器的overflow为visible来绕过这个问题，所以也不是很迫切的需求

**Comment by BlackGanglion** [comment]
有同样的问题，外层容器被业务加上了 overflow: visible

**Comment by szcyungui** [comment]
这个问题在后续已经被修复了吗？tooltip被外层截断
![image](https://user-images.githubusercontent.com/46086626/167104243-cd2d3c60-6513-449d-8b08-c93c48c69e65.png)

**Comment by szcyungui** [comment]
或者是新版本 有提供什么解决办法吗，能不能挂载到body上之类的？
