### ISSUE TITLE
折线图 legend 有全选和反选的例子吗

### ISSUE THREAD

**Issue by ZOEWANGCHINA** [antvis/g2#949]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

如题
现在是用
const geoms = this.charts.getAllGeoms();
                for (let i = 0; i < geoms.length; i++) {
                    const geom = geoms[i];
                    if (e) {
                        geom.show();
                    } else {
                        geom.hide();
                    }
                }
但是无法和 legend 联动

**Comment by aa1011372655** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_filter
这个方法可以做到，形如：
https://codepen.io/anon/pen/PyearQ?editors=1111

**Comment by ZOEWANGCHINA** [comment]
好的，谢谢，但是我试了一下，用checkbox的话，legend的点 取消的 时候 all还是会亮着 无法联动。

**Comment by ZOEWANGCHINA** [comment]
@aa1011372655

**Comment by aa1011372655** [comment]
可以在legend上绑定事件legend-item:click，储存一个全局的legend数组，然后根据数组来做判断，全局维护这个数组中的legend值即可
