### ISSUE TITLE
是否支持Y（左）轴和Y（右）轴分别显示multiple-bar和multiple-line

### ISSUE THREAD

**Issue by menes127** [antvis/g2#95]
官网的双Y轴例子https://antv.alipay.com/g2/demo/18-other/double-axis.html
![untitled1](https://cloud.githubusercontent.com/assets/767234/23489366/e62c9f34-ff2c-11e6-8bdf-514071b48404.png)

期望例子如下，如果支持，现在让我困惑的是数据格式是怎么样的？分组可以这样写吗？

frame = Frame.combinColumns(frame, ['call','waiting',**'people','XXXXX'**],'count','type',['time']);
chart.intervalStack().position('time*count').color(**'type[0..1]'**, ['#348cd1', '#43b5d8']);
chart.line().position('time*count').color(**'type[2..3]'**,['#fec514','#db4c3c'])

![untitled](https://cloud.githubusercontent.com/assets/767234/23489017/19e08d56-ff2b-11e6-9cb8-29a0ee43c0bb.png)

**Comment by simaQ** [comment]
```js
frame = Frame.combinColumns(frame, ['call','waiting'],'count','type',['time', 'people']);
```

例子中这句是为了将 call 和 waiting 数据进行合并，并以 type 区分，参见 https://antv.alipay.com/g2/doc/tutorial/start/frame.html#合并多列-frame-combincolumns，如果你想要再绘制一条线图的话，比如绘制 waiting 字段，你只需要往上述方法的最后一个参数加入 waiting 字段，表示合并后的数据源保留原先的 waiting 字段，这样你就可以再绘制一条线图了。完整代码如下：

```js
var data = [
        {'time': '10:10', 'call': 4, 'waiting': 2, 'people': 2},
        {'time': '10:15', 'call': 2, 'waiting': 6, 'people': 3},
        {'time': '10:20', 'call': 13, 'waiting': 2, 'people': 5},
        {'time': '10:25', 'call': 9, 'waiting': 9, 'people': 1},
        {'time': '10:30', 'call': 5, 'waiting': 2, 'people': 3},
        {'time': '10:35', 'call': 8, 'waiting': 2, 'people': 1},
        {'time': '10:40', 'call': 13, 'waiting': 1, 'people': 2}
      ];
      var Frame = G2.Frame;
      var frame = new Frame(data);
      frame = Frame.combinColumns(frame, ['call','waiting'],'count','type',['time', 'people', 'waiting']);
      var chart = new G2.Chart({
        id: 'c1',
        forceFit: true,
        height: 450,
        plotCfg: {
          margin: [60, 160, 60, 90]
        }
      });
      chart.source(frame, {
        'count': {alias: '话务量（通）', min: 0},
        'people': {alias: '人数（人）', min: 0}
      });
      // 去除 X 轴标题
      chart.axis('time', {
        title: null
      });
      chart.axis('waiting', {
        line: null,
  	  	titleOffset: 210,
  		labelOffset: 80,
        title: {
          fill: '#f80' 
        },
        labels: {
          label: {
            fill: '#f80' 
          }
        }
	  });
      chart.legend(false);// 不显示图例
      chart.intervalStack().position('time*count').color('type', ['#348cd1', '#43b5d8']); // 绘制层叠柱状图
      chart.line().position('time*people').color('#5ed470').size(2).shape('smooth'); // 绘制曲线图
      chart.line().position('time*waiting').color('#ff8800').size(2).shape('smooth'); 
      chart.render();
```

**Comment by menes127** [comment]
@simaQ 谢谢你的代码，通过你的代码，你的图应该如下
![untitled1](https://cloud.githubusercontent.com/assets/767234/23491552/ec1c9d7e-ff39-11e6-8243-e79d84a71284.png)
我这里有这些需求
1. 能否把'call','waiting','people','XXXXX'这样都放入到legend?但是call和waiting是bar,而people和XXXX是line
2. Y（右）轴其实我并不需要有两个，我这边的需求是他们两个都是百分比刻度，所有只需要一个就可以了。

**Comment by simaQ** [comment]
右侧 y 轴如果不显示，你直接调用 chart.axis('y轴对应字段名', false) 即可。对于你的第一个需求，通过 chart 创建的话目前是不支持生成这种混合图例的，但是你可以使用多视图达到目的，给你写了代码，具体的含义，你可以看下我们官网的 api:

```js
 var data = [
        {'time': '10:10', 'call': 4, 'waiting': 2, 'people': 2},
        {'time': '10:15', 'call': 2, 'waiting': 6, 'people': 3},
        {'time': '10:20', 'call': 13, 'waiting': 2, 'people': 5},
        {'time': '10:25', 'call': 9, 'waiting': 9, 'people': 1},
        {'time': '10:30', 'call': 5, 'waiting': 2, 'people': 3},
        {'time': '10:35', 'call': 8, 'waiting': 2, 'people': 1},
        {'time': '10:40', 'call': 13, 'waiting': 1, 'people': 2}
      ];
      var Frame = G2.Frame;
      var frame1 = new Frame(data);
      frame1 = Frame.combinColumns(frame1, ['call','waiting'],'count','type',['time']);
      var frame2 = new Frame(data);
      frame2 = Frame.combinColumns(frame2, ['people','waiting'],'count','type',['time']);
      var chart = new G2.Chart({
        id: 'c1',
        forceFit: true,
        height: 450,
        plotCfg: {
          margin: [60, 160, 60, 90]
        }
      });
      
      chart.col('count', {alias: '话务量（通）', min: 0});
      chart.col('people', {alias: '人数（人）', min: 0});
      chart.legend({
        title: null 
      });
      chart.axis('time', {
        title: null
      });
      chart.axis('waiting', false);
      var intervalStackView = chart.createView();
      intervalStackView.source(frame1);
      intervalStackView.intervalStack().position('time*count').color('type', ['#348cd1', '#43b5d8']); // 绘制层叠柱状图
      
      var lineView = chart.createView();
      lineView.source(frame2);
      lineView.axis('time', false);
      lineView.axis('count', false);
      lineView.line().position('time*count').color('type', ['red', '#f80']).size(2).shape('smooth'); // 绘制曲线图
      chart.render();
```

**Comment by menes127** [comment]
@simaQ 非常感谢你的帮助，多视图view绘制能够满足我的需求。最后一个问题，多视图view绘制支持facet 分面吗？

**Comment by simaQ** [comment]
支持，你可以先试试

**Comment by menes127** [comment]
@simaQ 好的，我先把你的例子改一下试试看。

**Comment by menes127** [comment]
var data = [
        {'time': '10:10', 'call': 4, 'waiting': 2, 'people': 2, 'group': "G1"},
        {'time': '10:15', 'call': 2, 'waiting': 6, 'people': 3, 'group': "G1"},
        {'time': '10:20', 'call': 13, 'waiting': 2, 'people': 5, 'group': "G1"},
        {'time': '10:25', 'call': 9, 'waiting': 9, 'people': 1, 'group': "G1"},
        {'time': '10:30', 'call': 5, 'waiting': 2, 'people': 3, 'group': "G1"},
        {'time': '10:35', 'call': 8, 'waiting': 2, 'people': 1, 'group': "G1"},
        {'time': '10:40', 'call': 13, 'waiting': 1, 'people': 2, 'group': "G1"},
        {'time': '11:10', 'call': 4, 'waiting': 2, 'people': 2, 'group': "G2"},
        {'time': '11:15', 'call': 2, 'waiting': 6, 'people': 3, 'group': "G2"},
        {'time': '11:20', 'call': 13, 'waiting': 2, 'people': 5, 'group': "G2"},
        {'time': '11:25', 'call': 9, 'waiting': 9, 'people': 1, 'group': "G2"},
        {'time': '11:30', 'call': 5, 'waiting': 2, 'people': 3, 'group': "G2"},
        {'time': '11:35', 'call': 8, 'waiting': 2, 'people': 1, 'group': "G2"},
        {'time': '11:40', 'call': 13, 'waiting': 1, 'people': 2, 'group': "G2"}  
      ];
      var Frame = G2.Frame;
      var frame1 = new Frame(data);
      frame1 = Frame.combinColumns(frame1, ['call','waiting'],'count','type',['group', 'time']);
      var frame2 = new Frame(data);
      frame2 = Frame.combinColumns(frame2, ['people','waiting'],'count','type',['group', 'time']);
      var chart = new G2.Chart({
        id: 'c1',
        forceFit: true,
        height: 450,
        plotCfg: {
          margin: [60, 160, 60, 90]
        }
      });
      
      chart.col('count', {alias: '话务量（通）', min: 0});
      chart.col('people', {alias: '人数（人）', min: 0});
      chart.legend({
        title: null 
      });
      chart.axis('time', {
        title: null
      });
      chart.axis('waiting', false);
      
      chart.facet('group')
      var intervalStackView = chart.createView();
      intervalStackView.source(frame1);
      intervalStackView.intervalStack().position('time*count').color('type', ['#348cd1', '#43b5d8']); // 绘制层叠柱状图
      
      var lineView = chart.createView();
      lineView.source(frame2);
      lineView.axis('time', false);
      lineView.axis('count', false);
      lineView.line().position('time*count').color('type', ['red', '#f80']).size(2).shape('smooth'); // 绘制曲线图
      chart.render();



@simaQ 增加group一列，然后增加了chart.facet('group')，报错了Uncaught TypeError: Cannot read property 'colArray' of null

**Comment by simaQ** [comment]
各个view支持facet 功能，你这种用法是不支持的。如果你又要分面又要混合图例，那只好自定义 html 图例了。https://antv.alipay.com/g2/doc/tutorial/start/legend.html#自定义-html-图例

**Comment by menes127** [comment]
@simaQ 非常感谢你的支持，由于我这周刚开始学习G2，感觉和其他传统的chart lib有很大不一样，目前我可能会采用官网的双Y轴例子，增加一条line，然后分面。基本可以满足需求。自定义的html图例我还得在研究下。
对应当前issue的解决方法，多视图view绘制就能解决。关闭当前issue。

**Comment by onecorner** [comment]
请问一下这个最新版本的如何实现啊？

**Comment by ShawshankLin** [comment]
最新版本是不是不支持Frame了？

**Comment by ShawshankLin** [comment]
@simaQ

**Comment by simaQ** [comment]
G2 3.0 开始就不支持了，你可以使用 DataSet 来代替，https://www.yuque.com/antv/g2-docs/api-transform#oulhyz
