### ISSUE TITLE
chart.souce报错

### ISSUE THREAD

**Issue by huangchaofei** [antvis/g2#950]
* **G2 Version**:3.2.8
* **Platform**:chrome
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

this.stationChart = new G2.Chart({
          container: 'rankingCanvas',
          forceFit: true,
          width:500,
          height:500
      });
      this.stationChart.souce(this.data)
      this.stationChart.axis('country', {
        label: {
          offset: 12
        }
      });
      this.stationChart.coord().transpose();
      this.stationChart.interval().position('country*population');
      this.stationChart.render();
报错 this.stationChart.souce is not a function

**Comment by leungwensen** [comment]
typo source

**Comment by chenmengS** [comment]
![image](https://github.com/antvis/G2/assets/21307847/fe7177e4-d81a-481d-8eb0-47343585a7d8)

**Comment by chenmengS** [comment]
@leungwensen 在v5.1.13，source被移除了？
