### ISSUE TITLE
bizcharts 上的Tooltip组件缺少htmlContent方法

### ISSUE THREAD

**Issue by abc879475908** [antvis/g2#952]
bizcharts 上的Tooltip组件比原生缺少了一个htmlContent方法,这个怎么解决啊.求教
export interface TooltipProps extends React.Props<any> {
    showTitle?: boolean;
    crosshairs?: {
      type?: CrosshairsType;
      style?: G2.Styles.background | G2.Styles.line;
    };
    offset?: number;
    containerTpl?: string;
    itemTpl?: string;
    'g2-tooltip'?: React.CSSProperties;
    'g2-tooltip-title'?: React.CSSProperties;
    'g2-tooltip-list'?: React.CSSProperties;
    'g2-tooltip-list-item'?: React.CSSProperties;
    'g2-tooltip-marker'?: React.CSSProperties;
    inPlot?: boolean;
    follow?: boolean;
    shared?: boolean;
    position?: PositionType;
  }

chart.tooltip(
   { 
     useHtml:true, 
     htmlContent:function(title,items){
        return '<div><ul><li>.....</li></ul></div>'
     }
   }
);

**Comment by leungwensen** [comment]
可以到 bizcharts 项目提 issue： https://github.com/alibaba/BizCharts/issues

**Comment by abc879475908** [comment]
@leungwensen  那里都没人回...
