### ISSUE TITLE
柱状图y轴只要整数怎么设置呢

### ISSUE THREAD

**Issue by huangchaofei** [antvis/g2#954]
this.chart.scale('value', {
      type:'linear',
      nice:true,
      min:0,
    });
后台返回的数组也是整 数的      
好像是因为数据太小了  
最大的值为2  所以有小数

**Comment by leungwensen** [comment]
如果是这种特殊的情况，可以通过手动设置 ticks 来解决

https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#___%E5%8F%82%E6%95%B0

**Comment by huangchaofei** [comment]
但是我y轴的刻度并不是固定的  这次这么小 下次有可能会很大 手动设置ticks这样不好吧

**Comment by huangchaofei** [comment]
@leungwensen

**Comment by leungwensen** [comment]
默认让 g2 计算的话，确实没有提供“只返回整数”这样的配置项，是用 nice numbers 算法算的。目前确实没办法。你可以判断一下数据的最大值是多少，根据你的实际情况判断要不要用手动配置的 ticks？
