### ISSUE TITLE
forceFit 在容器 width:100% 情况下未能获取正确的宽度

### ISSUE THREAD

**Issue by miaojiuchen** [antvis/g2#955]
生成的 chart 超出了 div 的范围
padding已设置为0，
翻了一遍issue没有找到类似的问题

**Comment by leungwensen** [comment]
问题可能是这样的，div 的宽度在 chart 在初始化的时候和 chart render 后可能发生了改变

**Comment by miaojiuchen** [comment]
好的，感谢
