### ISSUE TITLE
中国地图-省市下钻demo页面拼写错误

### ISSUE THREAD

**Issue by zenxds** [antvis/g2#956]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

[中国地图-省市下钻demo](https://antv.alipay.com/zh-cn/g2/3.x/demo/map/drill-down.html)里latitude的拼写都拼成了lantitude

**Comment by leungwensen** [comment]
多谢反馈，网站相关的问题后续可以到 antvis/site 里提 issue 或者 pr

https://github.com/antvis/site

**Comment by leungwensen** [comment]
https://github.com/antvis/site/issues/160
