### ISSUE TITLE
自定义legend，设置container无效

### ISSUE THREAD

**Issue by luckhpy** [antvis/g2#957]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,height=device-height">
    <title>基础折线图</title>
    <style>::-webkit-scrollbar{display:none;}html,body{overflow:hidden;height:100%;margin:0;}</style>
</head>
<body>
  <div id="aa"></div>
<div id="mountNode"></div>
<script>/*Fixing iframe window.innerHeight 0 issue in Safari*/document.body.clientHeight;</script>
<script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.g2-3.3.0/dist/g2.min.js"></script>
<script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js"></script>
<script>
var data = [{
  year: '1991',
  value: 3,
  aa: 11
}, {
  year: '1992',
  value: 4,
  aa: 11
}, {
  year: '1993',
  value: 3.5,
  aa: 11
}, {
  year: '1994',
  value: 5,
  aa: 11
}, {
  year: '1995',
  value: 4.9,
  aa: 11
}, {
  year: '1996',
  value: 6,
  aa: 11
}, {
  year: '1997',
  value: 7
}, {
  year: '1998',
  value: 9,
  aa: 11
}, {
  year: '1999',
  value: 13,
  aa: 11
}];
var chart = new G2.Chart({
  container: 'mountNode',
  forceFit: true,
  height: window.innerHeight
});
chart.source(data);
chart.scale('value', {
  min: 0
});
chart.scale('year', {
  range: [0, 1]
});
chart.tooltip({
  crosshairs: {
    type: 'line'
  }
});
chart.legend({
   position: 'top',
   custom: true,
   items: [
    { value: 'value', marker: {symbol: 'square', fill: '#3182bd', radius: 5} },
    { value: 'aa', marker: {symbol: 'square', fill: '#3182bd', radius: 5} }
  ],
  onHover: ev => {}, // 自定义 hover 事件
  onClick: ev => {}, // 自定义 click 事件
  "useHtml": true,
  "container": "#aa",
  "itemTpl": "\n  <li\n    class=\"g2-legend-list-item item-{index} {checked}\"\n    data-color=\"{originColor}\"\n    data-value=\"{originValue}\"\n    >\n    <i class=\"g2-legend-marker square\"\n      style=\"background-color: {color};\">\n    </i>\n    <span class=\"g2-legend-text\">{value}</span>\n  </li>"
})
  /*
chart.legend({
   position: 'top',
   custom: true,
   items: [
    { value: 'value', marker: {symbol: 'square', fill: '#3182bd', radius: 5} },
    { value: 'aa', marker: {symbol: 'square', fill: '#3182bd', radius: 5} }
  ],
  "useHtml": true,
  "container": "#aa",
  "itemTpl": "\n  <li\n    class=\"g2-legend-list-item item-{index} {checked}\"\n    data-color=\"{originColor}\"\n    data-value=\"{originValue}\"\n    >\n    <i class=\"g2-legend-marker square\"\n      style=\"background-color: {color};\">\n    </i>\n    <span class=\"g2-legend-text\">{value}</span>\n  </li>"
})*/
chart.line().position('year*value');
chart.line().position('year*aa');
chart.render();
</script>
</body>
</html>

运行完成后，legend仍然不在设定的container里面。"container": "#aa"或者"container": "aa"都无效

**Comment by PerseveranceZ** [comment]
加一个，自定义 `tooltip container` 也无效
官方 demo 地址：[https://antv.alipay.com/zh-cn/g2/3.x/demo/other/cutomize-tooltip.html][https://antv.alipay.com/zh-cn/g2/3.x/demo/other/cutomize-tooltip.html]
里面修改`g2-tooltip` 无任何效果，是 `3.3.0 ` 版本的问题， demo 里面换成 `3.2.8` 版本就好了。

**Comment by luckhpy** [comment]
刚刚试出来了，在"@antv/g2": "^3.0.12"是ok的，然后最新版本就不行！就想知道这个bug什么时候修复

**Comment by leungwensen** [comment]
写个 codepen 描述一下问题吧

**Comment by luckhpy** [comment]
deom地址https://codepen.io/luckhpy/pen/GYQrNe，你把src="https://gw.alipayobjects.com/os/antv/pkg/_antv.g2-3.2.8/dist/g2.min.js">替换成src="https://gw.alipayobjects.com/os/antv/pkg/_antv.g2-3.3.0/dist/g2.min.js">试试，legend不在container里面

**Comment by leungwensen** [comment]
多谢反馈，我们尽快修复

**Comment by PerseveranceZ** [comment]
`tooltipCrosshairsLine` 这个属性配置也不好使了，
我在 3.2.8 中在主题中注入配置均可以，最新版本`3.3.2` 不行：
```
tooltipCrosshairsLine: {
        style: {
            lineWidth: 1,
            stroke: 'red', // 边框的颜色
            strokeOpacity: 0.5, // 边框颜色的透明度，数值为 0 - 1 范围
        }
    }
```

**Comment by leungwensen** [comment]
@PerseveranceZ tooltip 的问题可以另开 issue 跟踪，我们排期修复
