### ISSUE TITLE
Question on property: sortable of geometry

### ISSUE THREAD

**Issue by henrych4** [antvis/G2#958]
* **G2 Version**: 3.3.0
* **Platform**: mac OS
* **Mini Showcase(like screenshots)**: N/A
* **CodePen Link**: N/A

Thanks for the great library. I am working with a project using another package based on g2, and have some questions when reading the source code of geom [(here)](https://github.com/antvis/g2/blob/master/src/geom/base.js). There is a property called `sortable` and it is involved in `paint` method. When I search it for the documentation, I find there is another library called f2 and from its [api](https://antv.alipay.com/zh-cn/f2/3.x/api/geometry.html#_sortable), it mentions that `sortable` can set to false if data is already sorted to save time.

However, if `sortable` is false, the condition on line 712 becomes true and the `mappedArray` created are sorted which is unnecessary. So, is it a bug and the "!" operator on line 712 should be removed?

Thank you for taking time to read this.

**Comment by henrych4** [comment]
After taking more time to read the source code, it seems that `sortable` property is only available in f2 but not in g2. Because in my case, unnecessary sorting triples the time spent. So is it possible to have such property in g2 as well?

**Comment by komagic** [comment]
为什么中国人要用英文写字...

**Comment by simaQ** [comment]
Already support at v4.0.0.
