### ISSUE TITLE
x轴label显示顺序不对

### ISSUE THREAD

**Issue by huangchaofei** [antvis/g2#959]
![image](https://user-images.githubusercontent.com/25143078/47026227-8f585d80-d197-11e8-82c8-55b9be4d53c8.png)
我拿到的数据格式是倒序的
但是在页面上显示的却不一样 和期望的效果不一样 我希望按照我给他的顺序x轴排列
![image](https://user-images.githubusercontent.com/25143078/47026277-a8610e80-d197-11e8-861f-d92fb71066d9.png)
这是我的代码 
this.chart = new G2.Chart({
      container: 'chart',
      forceFit: true,
      padding:'auto'
    });
    this.chart.source(this.warning_list);
    this.chart.scale('value', {
      min: 0
    });
    this.chart.scale('year', {
      range: [0, 1]
    });
    this.chart.tooltip({
      crosshairs: {
        type: 'line'
      }
    });
    this.chart.line().position('year*报警数量');
    this.chart.point().position('year*报警数量').size(4).shape('circle').style({
      stroke: '#fff',
      lineWidth: 1
    });
    this.chart.render();
    this.searchWarning()

**Comment by dxq613** [comment]
你 x 轴对应的数据是日期格式，会自动匹配成 type: 'time', 可以在列定义里面自己指定是分类类型 type: 'cat'。

```js
this.chart.scale('year', {
type:'cat',
range: [0, 1]
});
```
