### ISSUE TITLE
引用g6，打包压缩后，页面报错；

### ISSUE THREAD

**Issue by sy13277072001** [antvis/g2#963]
本地的环境页面没有报错情况，代码打包压缩后，出现报错。
错误如下：
![image](https://user-images.githubusercontent.com/25413638/47128464-db082580-d2c3-11e8-9c0f-137891742fd8.png)
请问是g2／g6打包编译的问题么？
用未压缩的包部署在开发环境，就不会报这个错误，所以怀疑是g2编译的问题。

**Comment by leungwensen** [comment]
请到 G6 项目提 issue，提供具体的环境、重现代码。AntV 技术栈目前用的是 webpack+babel，构建工具层面应该是没有问题的，这个报错看起来是逻辑层面的问题，麻烦先用带 source map 的版本 debug 一下定位问题
