### ISSUE TITLE
条形图hover效果，方向错误

### ISSUE THREAD

**Issue by aa1011372655** [antvis/g2#967]
* **G2 Version**:3.3.1
* **Platform**:mac
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/8445734/47334423-6bc27500-d6b9-11e8-9be7-d3893cd73bdd.png)

* **CodePen Link**:https://codepen.io/anon/pen/MPqEgb

3.3.1版本，条形图hover效果，方向错误

**Comment by paleface001** [comment]
定位到的问题是isTransposed参数没有正确传递到tooltip crosshairs，已解决

**Comment by aa1011372655** [comment]
确实是isTransposed没有传入的问题，我差点去改component，已修复
