### ISSUE TITLE
color 分类图例，itemMarginBottom 属性失效。

### ISSUE THREAD

**Issue by weepy3641** [antvis/g2#968]
如题

https://antv.alipay.com/zh-cn/g2/3.x/demo/bar/grouped-column.html

demo 加入代码：
```
chart.legend('name', {
  position: 'top-left',
  itemGap: 150,
  itemMarginBottom: 20
});
```

itemMarginBottom 属性失效。

**Comment by leungwensen** [comment]
itemMarginBottom 这个参数在两种情况下生效：1. legend 竖直排布；2. legend 横排时超过一行。它定义的是俩 legend item 在竖直方向上的 margin。这个需求可以用 offsetY 实现
