### ISSUE TITLE
不准备开源吗, 很想看源码啊

### ISSUE THREAD

**Issue by lirongfei123** [antvis/g2#97]

**Comment by simaQ** [comment]
很快了哦~ 很想看的话，可以先看看我们的 G2 框架的设计文档： https://github.com/antvis/g2/wiki

**Comment by lirongfei123** [comment]
快点吧, 现在也想在图形方向深入, 我也想贡献些力量

**Comment by lirongfei123** [comment]
@simaQ 多谢解答, 很感谢啊, 具体什么时候能透露下不

**Comment by simaQ** [comment]
今年下半年

**Comment by dxq613** [comment]
开源的工作已经做些准备了，下半年7，8月份应该所有的源码会开放出来

**Comment by yuyangvi** [comment]
为啥要等那么久啊，legend过多导致的bug，我想修都修不了。

**Comment by dxq613** [comment]
9月份正式开源，正在开发 3.0 ,原先有部分代码比较老，数据交互比较弱。9月份的正式版本会处理好这些问题

**Comment by leungwensen** [comment]
已经开源啦，欢迎使用～～ https://github.com/antvis/g2
