### ISSUE TITLE
一个有多条折线图的图表，点击图例后，被过滤掉的图表数据标注点未清空。

### ISSUE THREAD

**Issue by LinFeng1997** [antvis/g2#970]
* **G2 Version**:3.2.7
* **Platform**:Mac
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/16188742/47350342-426d0d80-d6e8-11e8-92ce-661baa160ed1.png)

* **Case Link**:https://antv.alipay.com/zh-cn/g2/3.x/demo/gallery/line6.html

**Comment by paleface001** [comment]
你好，数据标注点关注的是特定数据在画布中的位置，与图形是不相关联的

**Comment by paleface001** [comment]
解决办法：
* 通过legend点击事件获取当前value
legend.on('itemclick',function(ev){
   const value = ev.item.value;
  });
* 通过value判断隐藏对应数据标注
guide.changeVisible(false);

**Comment by LinFeng1997** [comment]
@paleface001  我监听 legend-item:click 这个事件，无论选中图例还是置灰图例，checked 属性都是 false，请问这符合预期吗？

**Comment by LinFeng1997** [comment]
问题解决了，原来图例项的选中状态要靠 ev.target._cfg.checked 来确定，guide 也只有 setVisible 没有 changeVisible 方法。

**Comment by paleface001** [comment]
请问你用的G2版本是？G2 3.3的话，guide.changeVisible()是可以的
