### ISSUE TITLE
G2实时更新视图时候，smooth的bug？

### ISSUE THREAD

**Issue by komagic** [antvis/g2#971]
* **G2 Version**:3.3.2
* **Platform**:macos
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:http://jsrun.net/XNhKp/edit

实时更新视图的时候，chart.area 加了.shape('smooth') 就卡，不加就不卡，貌似报错，可见http://jsrun.net/XNhKp/edit
报错如下：
![2018-10-23 8 54 12](https://user-images.githubusercontent.com/13415767/47362069-224c4700-d706-11e8-933e-be1552031c0f.png)

**Comment by leungwensen** [comment]
fixed in 3.3.3
