### ISSUE TITLE
SVG模式下玫瑰图中有值为0时的异常

### ISSUE THREAD

**Issue by juniusc** [antvis/g2#972]
* **G2 Version**: 3.3.2
* **Platform**: Windows
* **Mini Showcase(like screenshots)**:
![bugreport](https://user-images.githubusercontent.com/39425304/47403167-1484d900-d77b-11e8-8eca-7ce78484ff5d.png)
* **CodePen Link**:

canvas模式没有这个问题。

**Comment by leungwensen** [comment]
fixed in 3.3.3

**Comment by leungwensen** [comment]
我们保留了 warning 信息方便开发者自己定位问题。在这个 case 下是由于在值为0的玫瑰图内部显示 label 导致的，确实是个异常情况

**Comment by juniusc** [comment]
难道要过滤掉值为0的数据？报warning也不是个事啊，一下子就几百个warning出来了。
