### ISSUE TITLE
SVG模式下设置了透明度的点在移动上去之后颜色会永久变深

### ISSUE THREAD

**Issue by juniusc** [antvis/g2#973]
* **G2 Version**: 3.3.2
* **Platform**: Windows
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/juniusc/pen/XxxPvN

**Comment by juniusc** [comment]
我看了下已经修复了，这个可以关闭了吧。

**Comment by leungwensen** [comment]
done in 3.3.3
