### ISSUE TITLE
tooltip 设置 follow 为 false 时自定义样式控制 tooltip.htmlContent 的 position 失效

### ISSUE THREAD

**Issue by laispace** [antvis/g2#976]
* **G2 Version**: 3.3.3
* **Platform**: Mac/Chrome
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/2217416/47472537-a22afc00-d841-11e8-92ab-bf0a94f02b5d.png)

* **CodePen Link**:
https://codepen.io/laispace-the-reactor/pen/ePQQEM

我理解 follow 设置为 true 时，tooltip 要跟随鼠标位置；但 follow 设置为 false 时，应不对 tooltip 的位置做 js 控制，使其能遵从 css 样式控制。

**Comment by laispace** [comment]
CodePen 例子与官网的例子一样：https://antv.alipay.com/zh-cn/g2/3.x/demo/component/tooltip-fixed-position.html

**Comment by paleface001** [comment]
已在3.4版本修复
