### ISSUE TITLE
tooltip 的顺序是由第一组数据的顺序决定的，目前没有动态排序的功能，希望实现这个问题。

### ISSUE THREAD

**Issue by chenhandsome** [antvis/g2#977]
* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by paleface001** [comment]
你好，目前tooltip排序可以通过tooltip的htmlContent配置项来解决，htmlContent通过一个回调函数获取当前tooltip的必要数据，包括title和itmes，你可以根据这些数据自定义tooltip如何渲染。排序功能可以通过对items.value的排序进行。

相关 api 文档：[链接](https://antv.alipay.com/zh-cn/g2/3.x/api/tooltip.html#_htmlTooltip%E5%B1%9E%E6%80%A7)
相关demo: [1](https://antv.alipay.com/zh-cn/g2/3.x/demo/component/tooltip-custmed.html) [2](https://antv.alipay.com/zh-cn/g2/3.x/demo/component/tooltip-html-content.html)

后续会根据用户需求评估是否加入排序功能配置项，目前可以通过上面的方法解决。
希望能对你有所帮助，谢谢！
