### ISSUE TITLE
官网需及时更新

### ISSUE THREAD

**Issue by aa1011372655** [antvis/g2#978]
* **G2 Version**:3.3.3
* **Platform**:mac
* **Mini Showcase(like screenshots)**:
![image](https://user-images.githubusercontent.com/8445734/47501960-455b3000-d899-11e8-8079-5314e95c7a08.png)

* **CodePen Link**:

新版本g23.3.3更新以后，想要使用axis的htmlTemplate回调，由源码可知需要同时设置useHtml为true才会生效，请及时更新文档

**Comment by simaQ** [comment]
非常感谢！这周新官网会上线，网站所有的文档和示例都会维护在仓库的 docs/ 和 examples 目录下，欢迎提交 PR 帮助矫正~
