### ISSUE TITLE
如何更改坐标轴文字的字体？

### ISSUE THREAD

**Issue by zpz1982** [antvis/g2#98]
想把字体改成等宽字体，找不到在哪里能设置，好像只能修改大小和颜色

**Comment by dxq613** [comment]
```js
chart.axis('y',{
        labels: {
          label: {
            fontSize: 14,
            fontFamily: '宋体'
          }
        }
      });

```

**Comment by sunflower2056** [comment]
请问颜色怎么修改？

**Comment by 3030811865** [comment]
> 请问颜色怎么修改？
chart.axis('姓名',{
        label:{
            style:{
                textAlign:'left',
                // textAlign: 'center', // 文本对齐方向，可取值为： left center right
                fill: '#a36969', // 文本的颜色
  
                fontWeight: 'bold', // 文本粗细
                //rotate: 30 // 文本旋转角度
            }
        }
    })
