### ISSUE TITLE
极坐标系下tick显示颠倒

### ISSUE THREAD

**Issue by juniusc** [antvis/g2#980]
* **G2 Version**: 3.3.3
* **Platform**: Windows
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: https://codepen.io/juniusc/pen/XxovZQ

上半（0-25，80-95）的显示和下半颠倒。

**Comment by leungwensen** [comment]
极坐标的坐标轴 label 是会根据旋转角度自动旋转的

![image](https://user-images.githubusercontent.com/1655789/47546679-ecd17480-d924-11e8-837d-cb2d47b4d955.png)

**Comment by leungwensen** [comment]
```js
chart.axis('value', {
  label: {
    autoRotate: false
  }
});
```

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/api/chart.html#_axis
