### ISSUE TITLE
缺少图表标题

### ISSUE THREAD

**Issue by jingsam** [antvis/g2#983]
翻遍G2的文档，没有找到给图表设置标题的地方。图表标题属于图表的基本要素，是否考虑新增一个图表标题的辅助元素？

* **G2 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

**Comment by leungwensen** [comment]
guide.text 可以做，不过目前还是比较鼓励自己在外面用 html 写，这样自定义的自由度更高。我们收到过的图表标题的需求，都各不一样，所以目前没法抽象出特别好的实现。

**Comment by jingsam** [comment]
可否考虑使用html模板，例如如下配置：
```
chart.title({
  text: '人口结构',
  position: 'top-center',
  textStyle: {...},
  htmlTpl: '<h1>{titile}</h1>'
})
```

**Comment by leungwensen** [comment]
如果是这个需求，目前你可以用 guide.html

**Comment by jingsam** [comment]
OK, 谢谢

**Comment by tianxuzhang** [comment]
图表标题应该是必备的吧，可以参考echarts
