### ISSUE TITLE
html legend position invaild

### ISSUE THREAD

**Issue by maplor** [antvis/g2#985]
* **G2 Version**: 3.3.3
* **Platform**: Mac
* **Mini Showcase(like screenshots)**:
* **CodePen Link**: http://riddle.alibaba-inc.com/riddles/e417dba

legend with useHtml: true, but positon: 'top-left' is invaild.

In my stack, code in
https://github.com/antvis/g2/blob/master/src/chart/controller/legend.js#L348
this result of function _getXAlign() may have some mistake.

**Comment by jiaoyanfei** [comment]
package.json 中 "@antv/g2": "^3.2.2",  这样安装好依赖后 
chart.legend({
    position: 'left-center',
})
无效

改成 package.json 中 "@antv/g2": "3.2.2",  这样安装好依赖后
chart.legend({
    position: 'left-center',
})
正常
新版本有bug？

**Comment by dd1994** [comment]
这个问题解决了吗？

**Comment by maplor** [comment]
> 这个问题解决了吗？

我在最新版本中测试已经基本正常了（还有少量定位不完全准确），目前先关掉该issue。
