### ISSUE TITLE
y 轴数值格式化

### ISSUE THREAD

**Issue by wangzhe1995** [antvis/g2#988]
我发现当我的 Y 轴数值非常大的时候，g2 没有办法自动的完成格式化，比如，100000，我看在 highcharts  里面可以转换成 100k 这样子显示，不知道官方有没有支持这种格式化

**Comment by leungwensen** [comment]
https://antv.alipay.com/zh-cn/g2/3.x/tutorial/how-to-scale.html#_Demo-%E6%BC%94%E7%A4%BA

**Comment by wangzhe1995** [comment]
所以还是需要用户自己去做对应的配置的，就不能官方默认加上这个转换吗

**Comment by leungwensen** [comment]
不能，不同的数据需求不一样
