### ISSUE TITLE
x 轴格式化

### ISSUE THREAD

**Issue by wangzhe1995** [antvis/g2#989]
当我的 scales.type 是 time 的时候，我发现时间格式没有办法自动的格式化，都是统一的被格式化成了 YYYY-mm-dd 这样子的，而我期望的是这样子的:

10-28 08:00:00 16:00:00 10-29 08:00:00 16:00:00 10-30 08:00:00 16:00:00

**Comment by aa1011372655** [comment]
可以直接在time格式scale中使用mask属性来直接赋值，或者使用formatter方法

**Comment by wangzhe1995** [comment]
> 可以直接在time格式scale中使用mask属性来直接赋值，或者使用formatter方法

如果是 mask，那么我只能格式化固定的值，但这个是不满足需求的。我觉得 G2 不知道能不能参考一下 highcharts 的 time 格式的实现

**Comment by wangzhe1995** [comment]
目前我自己用这种方式做了转换：

`chart.axis('year', {
  label: {
  	formatter: (() => {
      let lastTime;
      return (val) => {
        console.info('val: ', );
        if (lastTime === undefined || moment(val).diff(moment(lastTime), 'day') !== 0) {
        	lastTime = val;
          return moment(val).format('MM-DD');
        }
      	return moment(val).format('HH:mm:ss');
      };
    })()
  }
});`
