### ISSUE TITLE
我的图形容器 div 一开始是隐藏的 有dispaly:none 后面我将dispaly：none 属性去掉 没有图形，此时要怎么做 

### ISSUE THREAD

**Issue by 18613109040** [antvis/g2#99]
我的图形容器 div 一开始是隐藏的 有dispaly:none 后面我将dispaly：none 属性去掉 没有图形

**Comment by dxq613** [comment]
forceFit: true 导致的，必须根据父元素的宽度进行自适应，解决方案：

* forceFit : false，指定宽度
* display: none 去掉后在创建图表或者 直接调用 chart.forceFit 方法
