### ISSUE TITLE
Treemap乱序显示问题

### ISSUE THREAD

**Issue by z784324922** [antvis/g2#995]
Treemap传入数据必须按照value值排序，不然显示直接炸了。一点优化建议，再做transform时候排好序，不然后面在label的htmlTemplate回调中拿到的数据也有问题。

**Comment by z784324922** [comment]
按照value列排好序 
![image](https://user-images.githubusercontent.com/31068244/47893244-e6984680-de96-11e8-8995-2c3ada0926cf.png)

**Comment by z784324922** [comment]
这个是我自己排序的结果
![image](https://user-images.githubusercontent.com/31068244/47893261-03347e80-de97-11e8-8a5d-781e42705be8.png)

**Comment by z784324922** [comment]
官方给的demo，value值的那一列是有序的，所以显示正常。如果遇到无序的数据，显示效果就会像图一的效果，其实我们想看到的都是图二这种效果。

**Comment by z784324922** [comment]
https://riddle.alibaba-inc.com/riddles/6387cceb

**Comment by leungwensen** [comment]
这种扁平的树要求有序建议自己对树节点的 children 字段进行排序
