### ISSUE TITLE
多层饼状图，legend，useHTML时，3.2.7升级到3.3.3报错

### ISSUE THREAD

**Issue by redclown** [antvis/g2#997]
![65181541127991_ pic](https://user-images.githubusercontent.com/11514145/47891723-6b7f6200-de8f-11e8-9a46-b3da39beaab6.jpg)
渲染多层饼状图时，legend {useHTML:true} 会报错
1. 单层没有问题
2. 3.2.7版本没有问题 升级到 3.3.3 出现问题

帮忙看下，多谢~

**Comment by leungwensen** [comment]
useHtml

麻烦发代码

**Comment by redclown** [comment]
G2 Version: 3.3.3 (3.2.7没有问题)
Platform: mac chrome
Mini Showcase(like screenshots):
CodePen Link: https://codepen.io/redclown-the-decoder/pen/RqbKdp
[https://codepen.io/redclown-the-decoder/pen/RqbKdp](url)

**Comment by nzbin** [comment]
3.4.x 依然有这个 bug，而且更严重了

**Comment by heke1994** [comment]
3.4.10，依然有这个问题
