### ISSUE TITLE
饼图，在每个分片上鼠标左键点击，分片会凸出，再次点击鼠标左键，分片复原不了。

### ISSUE THREAD

**Issue by fine24** [antvis/g2#999]
饼图，在每个分片上鼠标左键点击，分片会凸出，再次点击鼠标左键，分片复原不了。

**Comment by redclown** [comment]
好像鼠标移出饼状图之后再点击才可以

**Comment by jerryyan1990** [comment]
我是鼠标移上去，最大的分片变成100%了，其他的分片消失了....

**Comment by xxxxxMiss** [comment]
饼图点击选中之后，没法复原。如果选中之后再点击一下空白区域，那么之前选中的区域就可以复原了。。。

**Comment by dxq613** [comment]
按照 https://www.yuque.com/antv/g2-docs/api-geom#select，把 cancelable: true 就允许取消选中。我试了试，确实是点击饼图后需要移出去，再移入进来才能取消选中，我看看怎么改一下。
